### ISSUE TITLE
32-bit version

### ISSUE THREAD

**Issue by ruimgoncalves** [rustdesk/rustdesk#1]
Hi

Any plan to support 32-bit systems?

Thanks

**Comment by rustdesk** [comment]
win10?2020年10月10日 22:34，ruimgoncalves <notifications@github.com>写道：
Hi
Any plan to support 32-bit systems?
Thanks

**Comment by ruimgoncalves** [comment]
Windows 7 onward

**Comment by rustdesk** [comment]
Why are you still using Windows 7 32-bit?

**Comment by ruimgoncalves** [comment]
Not me specifically .. but many of the systems I manage do, in fact 25% of all operating systems are still Windows 7.

source : https://www.netmarketshare.com/operating-system-market-share.aspx

So, why not support windows 7 and 32 bit for embedded systems?

**Comment by open-trade** [comment]
Yes, you are right

**Comment by BurntDog** [comment]
I miss win 7 but who would be crazy to connect to web on a unsecure non updated system?

**Comment by rustdesk** [comment]
#78
