### ISSUE TITLE
Windows Installer

### ISSUE THREAD

**Issue by sitiom** [rustdesk/rustdesk#100]
Hi, it would be great to have an installer for silent installs like Teamviewer and [Anydesk](https://download.anydesk.com/AnyDesk.msi). I would like to create a [Chocolatey](http://chocolatey.org/) package of this but there doesn't seem to have an installer.

**Comment by rustdesk** [comment]
How can I help you?

**Comment by rustdesk** [comment]
I followed AnyDesk, make RustDesk run without installation, and add the install link on the main window.

**Comment by sitiom** [comment]
Great, that works as a portable option. But is there any way to silently install it to `Program Files` in case the user wants to install it in their system?

**Comment by rustdesk** [comment]
> Great, that works as a portable option. But is there any way to silently install it to `Program Files` in case the user wants to install it in their system? ([Anydesk installer](https://download.anydesk.com/AnyDesk.msi) for reference)

I do have it using Inno Setup. I will publish it in 1.1.7.

**Comment by rustdesk** [comment]
> install link

You can also install it to `Program Files` or any other directory by clicking on the install link on the main window.

**Comment by JerryLiew** [comment]
create a windows intaller application  by intall shield or visual studio.

**Comment by rustdesk** [comment]
> create a windows intaller application by intall shield or visual studio.

Below is my Inno Setup script. I have little time to check msi make script, wondering if anyone can help make one for RustDesk.

```
; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "RustDesk"
#define MyAppVersion "1.1.5"
#define MyAppPublisher "Carriez, Inc."
#define MyAppURL "https://www.rustdesk.com/"
#define MyAppExeName "RustDesk.exe"
#define MyAppExe ".\RustDesk.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{54E86BC2-6C85-41F3-A9EB-1A94AC9B1F93}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DisableDirPage=yes
DefaultGroupName={#MyAppName}
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes
ArchitecturesInstallIn64BitMode=x64
UninstallDisplayIcon={app}\{#MyAppExeName}

[Languages] 
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
; Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#MyAppExe}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{commonstartup}\{#MyAppName} Tray"; Filename: "{app}\{#MyAppExeName}"; Parameters: "--tray";

[Run]
Filename: "sc.exe"; Parameters: "create {#MyAppName} start= auto DisplayName= ""{#MyAppName} Service"" binPath= ""\""{app}\{#MyAppExeName}\"" --service"""; Flags: runhidden
Filename: "netsh.exe"; Parameters: "advfirewall firewall add rule name=""{#MyAppName} Service"" dir=in action=allow program=""{app}\{#MyAppExeName}"" enable=yes"; Flags: runhidden
Filename: "sc.exe"; Parameters: "start {#MyAppName}" ; Flags: runhidden 

[UninstallRun]
Filename: "sc.exe"; Parameters: "stop {#MyAppName}" ; Flags: runhidden   
Filename: "sc.exe"; Parameters: "delete {#MyAppName}" ; Flags: runhidden
Filename: "netsh.exe"; Parameters: "advfirewall firewall delete rule name=""{#MyAppName} Service"""; Flags: runhidden
```

**Comment by sitiom** [comment]
I believe InnoSetup is sufficient and that an MSI setup is not necessarily needed anymore. I can't think of a use case where MSI is really needed and there is really no difference if it is done with MSI.

**Comment by rustdesk** [comment]
> MSI

I think normal users like to see msi more, which is the standard. Correct me if I am wrong.

**Comment by sitiom** [comment]
> > MSI
> 
> I think normal users like to see msi more, which is the standard. Correct me if I am wrong.

Doesn't matter in the end. Teamviewer setup is exe.

**Comment by rustdesk** [comment]
> Teamviewer setup

TV setup is their own.

**Comment by sitiom** [comment]
> > Teamviewer setup
> 
> TV setup is their own.

It is in [NSIS](https://nsis.sourceforge.io). If you extract it in 7z, You can see the NSIS plugins inside:
![image](https://user-images.githubusercontent.com/56180050/122853283-8fe02380-d344-11eb-8e9a-77b714bef6c3.png)

**Comment by sitiom** [comment]
Oh well, It seems like the setup file is silently inserted into the latest release on the releases page. It doesn't seem like you put the setup script in the repo though (please do put it).

Also, the language is only in Chinese. Might be good to include English as well (Multi-language setup):
![image](https://user-images.githubusercontent.com/56180050/125636306-5adf204c-95be-4d00-8980-59821d31dc2a.png)

**Comment by rustdesk** [comment]
> Multi-language setup
Sorry, my fault again, please check out the new setup file, I just overwrite it. It seems my brain stop working lately.

https://github.com/rustdesk/rustdesk/blob/master/setup.iss

**Comment by sitiom** [comment]
Thanks, please see [this PR](https://github.com/rustdesk/rustdesk/pull/170) (Fixed some problems with the setup).

**Comment by sitiom** [comment]
@rustdesk Can you overwrite the setup in the releases now?

**Comment by rustdesk** [comment]
any bug of current one?2021年7月15日 22:00，sitiom ***@***.***>写道：
@rustdesk Can you overwrite the setup in the releases now?

**Comment by sitiom** [comment]
> any bug of current one?

The bugs InnoSetup were described in my PR (#170) which were fixed there.

**Comment by rustdesk** [comment]
Got it, I think it is not urgent.

**Comment by july008** [comment]
copy sciter.dll to target\release or target\debug, copy this code to setup-new.nsi
and
cd target\release
"C:\Program Files (x86)\NSIS\bin\makensis.exe" setup-new.nsi


`Unicode true

####################################################################
# Includes

!include nsDialogs.nsh
!include MUI2.nsh
!include x64.nsh
!include LogicLib.nsh

####################################################################
# File Info

!define PRODUCT_NAME "RustDesk"
!define PRODUCT_DESCRIPTION "Installer for ${PRODUCT_NAME}"
!define COPYRIGHT "Copyright 2021"
!define VERSION "1.1.6"

VIProductVersion "${VERSION}.0"
VIAddVersionKey "ProductName" "${PRODUCT_NAME}"
VIAddVersionKey "ProductVersion" "${VERSION}"
VIAddVersionKey "FileDescription" "${PRODUCT_DESCRIPTION}"
VIAddVersionKey "LegalCopyright" "${COPYRIGHT}"
VIAddVersionKey "FileVersion" "${VERSION}.0"

####################################################################
# Installer Attributes

Name "${PRODUCT_NAME}"
Outfile "rustdesk-${VERSION}-setup.exe"
Caption "Setup - ${PRODUCT_NAME}"
BrandingText "${PRODUCT_NAME}"

ShowInstDetails show
RequestExecutionLevel admin
SetOverwrite on
 
InstallDir "$PROGRAMFILES64\${PRODUCT_NAME}"

####################################################################
# Pages

!define MUI_ICON "src\tray-icon.ico"
!define MUI_ABORTWARNING
!define MUI_LANGDLL_ALLLANGUAGES
!define MUI_FINISHPAGE_SHOWREADME ""
!define MUI_FINISHPAGE_SHOWREADME_NOTCHECKED
!define MUI_FINISHPAGE_SHOWREADME_TEXT "Create Desktop Shortcut"
!define MUI_FINISHPAGE_SHOWREADME_FUNCTION CreateDesktopShortcut
!define MUI_FINISHPAGE_RUN "$INSTDIR\${PRODUCT_NAME}.exe"

!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

####################################################################
# Language

!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "SimpChinese"

####################################################################
# Sections

Section "Install"
  SetOutPath $INSTDIR

  # Regkeys
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" "DisplayIcon" "$INSTDIR\${PRODUCT_NAME}.exe"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" "DisplayName" "${PRODUCT_NAME} (x64)"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" "DisplayVersion" "${VERSION}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" "UninstallString" '"$INSTDIR\${PRODUCT_NAME}.exe" --uninstall'
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" "InstallLocation" "$INSTDIR"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" "Publisher" "Carriez, Inc."
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" "HelpLink" "https://www.rustdesk.com/"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" "URLInfoAbout" "https://www.rustdesk.com/"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" "URLUpdateInfo" "https://www.rustdesk.com/"

  nsExec::Exec "taskkill /F /IM ${PRODUCT_NAME}.exe"
  Sleep 500 ; Give time for process to be completely killed
  File "${PRODUCT_NAME}.exe"
  File "sciter.dll"
  SetOutPath $INSTDIR\src
  File /r "src\*" 

  SetOutPath $INSTDIR

  SetShellVarContext all
  CreateShortCut "$INSTDIR\Uninstall ${PRODUCT_NAME}.lnk" "$INSTDIR\${PRODUCT_NAME}.exe" "--uninstall" "msiexec.exe"
  CreateDirectory "$SMPROGRAMS\${PRODUCT_NAME}"
  CreateShortCut "$SMPROGRAMS\${PRODUCT_NAME}\${PRODUCT_NAME}.lnk" "$INSTDIR\${PRODUCT_NAME}.exe" "" "$INSTDIR\src\tray-icon.ico" 0
  CreateShortCut "$SMPROGRAMS\${PRODUCT_NAME}\Uninstall ${PRODUCT_NAME}.lnk" "$INSTDIR\${PRODUCT_NAME}.exe" "--uninstall" "msiexec.exe"
  CreateShortCut "$SMSTARTUP\${PRODUCT_NAME} Tray.lnk" "$INSTDIR\${PRODUCT_NAME}.exe" "--tray"
	CreateShortCut "$DESKTOP\rustdesk.lnk" "$INSTDIR\${PRODUCT_NAME}.exe" "" "$INSTDIR\src\tray-icon.ico" 0


  nsExec::Exec 'sc create ${PRODUCT_NAME} start=auto DisplayName="${PRODUCT_NAME} Service" binPath= "\"$INSTDIR\${PRODUCT_NAME}.exe\" --service"'
  nsExec::Exec 'netsh advfirewall firewall add rule name="${PRODUCT_NAME} Service" dir=in action=allow program="$INSTDIR\${PRODUCT_NAME}.exe" enable=yes'
  nsExec::Exec 'sc start ${PRODUCT_NAME}'
SectionEnd

####################################################################
# Functions

Function .onInit
  # RustDesk is 64-bit only
  ${IfNot} ${RunningX64}
    MessageBox MB_ICONSTOP "${PRODUCT_NAME} is 64-bit only!"
    Quit
  ${EndIf}
  ${DisableX64FSRedirection}
  SetRegView 64

  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Function CreateDesktopShortcut
  CreateShortCut "$DESKTOP\${PRODUCT_NAME}.lnk" "$INSTDIR\${PRODUCT_NAME}.exe"
FunctionEnd
`

**Comment by MeikelLP** [comment]
@sitiom did you create a chocolatey package yet? I didn't find any

**Comment by sitiom** [comment]
> @sitiom did you create a chocolatey package yet? I didn't find any

Nope, blocked by #212

**Comment by sitiom** [comment]
I no longer use Chocolatey, so I am no longer interested in maintaining a Chocolatey package for RustDesk. I am, however, looking to putting this into Winget.

**Comment by rustdesk** [comment]
https://github.com/microsoft/winget-pkgs/pull/63466

**Comment by sitiom** [comment]
> "Winget must be run by a user in an interactive console. (...) You cannot run Winget in a remote session using Invoke-Command or SSH. This also means you can’t run Winget in a PowerShell background job".

This is an OpenSSH issue, you cannot run AppX CLI apps over SSH: https://github.com/PowerShell/Win32-OpenSSH/issues/1632.

**Comment by dufayf** [comment]
My problem really is : "JumpCloud uses the NT Authority\System account to run commands on remote systems, preventing the use of commands that require a user context to run" ([source](https://support.jumpcloud.com/support/s/article/getting-started-commands-2019-08-21-10-36-47)). With that possibility, I may install software with a single **chocolatey** line including parameters. It doesn't work with **winget** who need an actual user to run and to be installed, as i understood.

And I'm not speaking of the native Jumpcloud applications management which includes choclatey as engine ([source](https://jumpcloud.com/resources/install-manage-applications-remote-systems)).

In both cases a **chocolatey package** would allow me to install Rustdesk on every PC of my fleet, which I'd love to.

**Comment by sitiom** [comment]
If you are talking about installing Winget, just make sure [App Installer](https://apps.microsoft.com/store/detail/app-installer/9NBLGGH4NNS1) is updated as it already bundles Winget with it.

**Comment by dufayf** [comment]
> If you are talking about installing Winget, just ensure the [App Installer](https://apps.microsoft.com/store/detail/app-installer/9NBLGGH4NNS1) is updated as Winget is bundled with it.

@sitiom : Microsoft Store is roughly uninstalled on all of my fleet. I sholdl have done it with GPO, but it requires Education or Enterprise Win X licenses. I only have bundled Pro licenses.

**Comment by sitiom** [comment]
Aw, that's a bummer. How about check out https://github.com/jdhitsolutions/WingetTools, which has a command that bootstraps Winget from GitHub ([Install-Winget](https://github.com/jdhitsolutions/WingetTools#install-winget))

**Comment by dufayf** [comment]
Thanks. Same author as the source I quoted in my previous comment https://github.com/rustdesk/rustdesk/issues/100#issuecomment-1161566272 on winget limitations. I may give it a try but I'm very pessimistic about it. My guess is it won't work with NT Authority\System account in powershell, which is a Jumpcloud limitations (and strength) I can't override.

**Comment by MichaelUray** [comment]
> I believe InnoSetup is sufficient and that an MSI setup is not necessarily needed anymore. I can't think of a use case where MSI is really needed and there is really no difference if it is done with MSI.

MSI installers are required if you want to rollout software via GPOs by your Active Directory Windows servers.

**Comment by shanold** [comment]
> > MSI
> 
> I think normal users like to see msi more, which is the standard. Correct me if I am wrong.

I

> > [#769 (comment)](https://github.com/rustdesk/rustdesk/issues/769#issue-1270511224) he uses the other tool to deploy on 260 machines.
> 
> @rustdesk : That did the trick. Many thanks. I only have execute that command with Jumpcloud :
> 
> `wget "https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-windows_x64.zip" -Outfile 'C:\Windows\Temp\rustdesk-1.1.9-windows_x64.zip' Expand-Archive C:\Windows\Temp\rustdesk-1.1.9-windows_x64.zip -DestinationPath C:\Users\Public\ C:\Users\Public\rustdesk-1.1.9-putes.exe --silent-install`
> 
> But, anyway, it won't help me maintain and update Rustdesk on my PCs. Choco helps a lot in that way.
> 
> > Here is a [Helper Function](https://github.com/Romanitho/Winget-AutoUpdate/blob/main/Winget-AutoUpdate/functions/Get-WingetCmd.ps1) that is used from https://github.com/Romanitho/Winget-AutoUpdate that gets the location of Winget for use in a system context.
> 
> @sitiom : This is an excellent suggestion which could help maintain Rustdesk updated. Thanks. But the problems remains : "How do I remotely install **winget** on my PCs?".

Thanks for this I was trying to figure out a way to deploy this in a AD environment
