### ISSUE TITLE
Online status indicator doesn't work for remotes added via `id@server/r`

### ISSUE THREAD

**Issue by sepsol** [rustdesk/rustdesk#10005]
### Bug Description

I have a remote client that I usually connect to. The remote client is using a relay server and an ID server on its end. When I want to connect to that specific remote via its pure `<id>`, I have to change the networking settings on my client to add that relay and ID server globally. When I do that, everything works just fine and the online status indicator for that remote updates correctly.

Since the adding and deleting of relay and ID servers on my client for connecting to that remote client was becoming cumbersome, I researched this repository and found out that [an alternative method has been added in v1.3.0](https://github.com/rustdesk/rustdesk/issues/6198#issuecomment-1794694273) that allows connecting to remotes behind an ID and a relay server without having to change these settings globally.

Therefore, I gave it a shot and am now able to connect to my remote client via `<id>@<server>/r` without having to set the relay and ID servers globally on my client. Although this works great, the issue I'm experiencing with this method is that it no longer updates the small online status indicator for that remote correctly and it always stays orange, even though I'm able to connect to it just fine and if I use the old method it is able to detect when the remote is online and shows it as green.

### How to Reproduce

1. Install RustDesk on 2 machines (I tested on 2 Windows machines).
2. Open up the settings on machine 1 and go to networking and assign it to a custom (public) ID and relay server.
3. Now try connecting to machine 1 from machine 2 via `<id>@<server>/r` without changing the global networking settings on machine 2.
4. You should be able to connect to machine 1 but the online status indicator won't work and it'll stay orange.

### Expected Behavior

The online status indicator should turn green when the remote behind the ID and relay server is ready to receive connections.

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows 11 -> Windows 11

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.0 -> 1.3.0

### Screenshots

![image](https://github.com/user-attachments/assets/df2d3012-f879-437f-9df4-54990b919908)

![image](https://github.com/user-attachments/assets/bd7f761c-5576-44f9-8272-9809b81d6017)

**Comment by rustdesk** [comment]
No plan for this.

**Comment by rustdesk** [comment]
PR is welcome
