### ISSUE TITLE
Error in `workflows'. Customization for Linux builds does not work.

### ISSUE THREAD

**Issue by jurykor** [rustdesk/rustdesk#10010]
### Bug Description

Custom builds for Linux do not connect to private servers with default settings.

### How to Reproduce

Clone the repository, add the variables `RS_PUB_KEY` and `RENDEZ-VOUS_SERVER` to the project, and run the workflow.

### Expected Behavior

Custom builds for Linux must connect to private servers with default settings.

### Operating system(s) on local (controlling) side and remote (controlled) side

linux

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

-

### Screenshots

-

### Additional Context

The variables `RS_PUB_KEY` and `RENDEZ-VOUS_SERVER` are not passed to `rustdesk-org/run-on-arch-action`, so `.deb`, `.rmp` and `AppImage` files are built without these variables.

Workaround for me:
```
diff --git a/.github/workflows/flutter-build.yml b/.github/workflows/flutter-build.yml
index dd21515ba..7ef731001 100644
--- a/.github/workflows/flutter-build.yml
+++ b/.github/workflows/flutter-build.yml
@@ -1413,6 +1413,9 @@ jobs:
             --volume "${PWD}:/workspace"
             --volume "/opt/artifacts:/opt/artifacts"
           shell: /bin/bash
+          env: |
+            RS_PUB_KEY: "${{ secrets.RS_PUB_KEY }}"
+            RENDEZVOUS_SERVER: "${{ secrets.RENDEZVOUS_SERVER }}"
           install: |
             apt-get update -y
             echo -e "installing deps"
```

**Comment by rustdesk** [comment]
#763
