### ISSUE TITLE
RustDesk APK Incompatibility with Android 5.1.1

### ISSUE THREAD

**Issue by 2837164889** [rustdesk/rustdesk#10044]
### Bug Description

The RustDesk APK is incompatible with Android 5.1.1 devices, preventing users from installing and utilizing the application on these specific devices.

### How to Reproduce

Attempt to download and install the RustDesk APK on an Android 5.1.1 device.
Observe the installation failure or incompatibility message displayed on the device.

### Expected Behavior

The RustDesk APK should be compatible with Android 5.1.1 devices, allowing users to successfully install and use the application without encountering any issues.

Operating system(s) on local (controlling) side and remote (controlled) side:
The issue is observed on Android 5.1.1 devices as the local (controlling) side. The remote (controlled) side's operating system is not relevant to this particular issue.

RustDesk Version(s) on local (controlling) side and remote (controlled) side:
The issue is observed with the RustDesk APK intended for installation on Android devices, regardless of the version on the remote (controlled) side. However, for completeness, the local (controlling) side is attempting to install version compatible with Android (assuming the latest available if specified compatibility is not noted).

### Operating system(s) on local (controlling) side and remote (controlled) side

android 5.1.1

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.2

### Screenshots

N/A (as this is an installation compatibility issue, screenshots may not provide additional context).

### Additional Context

Users of Android 5.1.1 devices are unable to install RustDesk due to incompatibility. This limits the accessibility and functionality of RustDesk for these users. It is recommended that RustDesk consider expanding its compatibility to include Android 5.1.1 devices to enhance user experience and accessibility.

**Comment by rustdesk** [comment]
Close as wontfix
