### ISSUE TITLE
Chinese Input Method Switching Issue in Translation Mode (Beta)

### ISSUE THREAD

**Issue by chenlong96** [rustdesk/rustdesk#10057]
### Bug Description

When using traditional mode or 1:1 transfer mode, switching to the Chinese input method works as expected.
However, in the translation mode (Beta), while the system indicates that the input method has switched to Chinese, it continues to only accept English input.

### How to Reproduce

1.Switch to translation mode (Beta).
2.Attempt to toggle the input method to Chinese.
3.Observe that the system displays the input method as "Chinese."
4.Attempt to input text, and note that only English characters can be entered.

### Expected Behavior

The input method should correctly switch to Chinese and allow Chinese text input.

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows 10 > Windows 10

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.1 > 1.3.1

### Screenshots

![image](https://github.com/user-attachments/assets/67caf2d9-6840-4372-8687-ccd79489f2ce)

**Comment by rustdesk** [comment]
Stick to map mode please then.
