### ISSUE TITLE
multiple entries with poor internet connection

### ISSUE THREAD

**Issue by cw-felix** [rustdesk/rustdesk#10052]
### Bug Description

With a slow internet connection, numbers and letters are often transmitted multiple times.

![image](https://github.com/user-attachments/assets/01847031-75bf-45c0-b71c-a32b42bd13ec)

### How to Reproduce

Connect to a Device with a bad Netzwork connection.

### Expected Behavior

.

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows 10 -> Debian

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.2 -> 1.3.2

### Screenshots

![image](https://github.com/user-attachments/assets/c28348db-d417-4974-be53-90055aa05324)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/6793 we fixed before, come back again? @fufesou

**Comment by fufesou** [comment]
@cw-felix Thanks for the feedback.

Could you please run the following command on the controlled side?
```bash
xev -event keyboard
```

Then the press the keys and upload a video and paste the output here, thanks.

**Comment by fufesou** [comment]
Could you please also run the test build here https://github.com/fufesou/rustdesk/releases/tag/test-10052 ?

Only some logs are added.

```
Windows: %appdata%\rustdesk\log\rustdesk_rCURRENT.log
Linux: ~/.local/share/logs/RustDesk/server/rustdesk_rCURRENT.log
```

Please preoduce this issue, remove sensitive infos and upload the logs here, thanks.

**Comment by cw-felix** [comment]
Do you need any assist?

**Comment by fufesou** [comment]
I'll submit PR later.

Then please test it.

**Comment by rustdesk** [comment]
Please test https://github.com/rustdesk/rustdesk/releases/nightly you need to install both the controlling and the controlled side.

**Comment by cw-felix** [comment]
@rustdesk
