### ISSUE TITLE
ios version build error

### ISSUE THREAD

**Issue by sj6219** [rustdesk/rustdesk#1006]
If you build the current latest source, an error will occur as below.
 
> cargo build --release --target=aarch64-apple-ios
> ...
> error[E0432]: unresolved imports `crate::mobile::connection_manager`, `crate::mobile::connection_manager`
>  --> src/mobile_ffi.rs:2:20
>   |
> 2 | use crate::mobile::connection_manager::{self, get_clients_length, get_clients_state};
>   |                    ^^^^^^^^^^^^^^^^^^   ^^^^ no `connection_manager` in `mobile`
>   |                    |
>   |                    could not find `connection_manager` in `mobile`
> ...
> 

May I know the value of commit id (SHA-1 hash) of the source without error?

**Comment by rustdesk** [comment]
#763
