### ISSUE TITLE
No Retry button is displayed in the Supermarket Disconnection confirmation box for version 1.3.2（1.3.3）

### ISSUE THREAD

**Issue by hackgsl** [rustdesk/rustdesk#10072]
### Bug Description

Since version 1.3.2, the connection is automatically disconnected after a long period of no operation reaches the set time, at this time, the pop-up window only "OK", click the field to close the connection.
This problem has been reported before, and the later versions are normal. The problem recurred after the release of 1.3.2, and the upgrade to 1.3.3 version today after the issue was raised is also the same.

### How to Reproduce

V1.3.2,1.3.3

### Expected Behavior

Leave the Retry button.

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows10

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.2,1.3.3->1.*

### Screenshots

![PixPin_2024-11-05_09-04-11](https://github.com/user-attachments/assets/b849a559-656c-432a-afd2-73a3478eaf68)

**Comment by rustdesk** [comment]
intended
