### ISSUE TITLE
Crash on Mac M1 macOS 15.1.1 After Unlock Network Settings

### ISSUE THREAD

**Issue by yikZero** [rustdesk/rustdesk#10071]
### Bug Description

MacBook Pro (2020, M1) running macOS 15.1.1 (24B91)experiences consistent system crash upon any user input in Network Settings panel after unlocking. All required permissions have been granted. Crash log from Apple diagnostic report is attached for reference.

### How to Reproduce

1. Navigate to System Settings
2. Select Network from the settings menu
3. Click "Unlock Network Settings" and authenticate
4. Once unlocked, attempt to input any character in any text field

### Expected Behavior

Text input should be accepted

### Operating system(s) on local (controlling) side and remote (controlled) side

local side 

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.2

### Screenshots

https://github.com/user-attachments/assets/5fac5589-24b6-44ba-b7db-7284b7e07ff0

### Additional Context

[RustdeskAppCrash.log](https://github.com/user-attachments/files/17930448/RustdeskAppCrash.log)

**Comment by rustdesk** [comment]
A lot of duplicate about this, please search and find workaround.

**Comment by rustdesk** [comment]
https://github.com/flutter/flutter/issues/151428 fixed in main of Flutter, but not published yet.
