### ISSUE TITLE
Android【Mouse Mode】Swipe the gesture to the right and stop in place

### ISSUE THREAD

**Issue by QuantWorker** [rustdesk/rustdesk#10084]
[###](url) Bug Description

rustdesk 1.3.3
Android AArch64 (ARM64)

In [mouse mode]
When the screen is zoomed to maximum
It is normal for the gesture to slide to the left, and the distance moved is normal.
If you slide the gesture to the right, you will not be able to slide to the right, 
and the mouse movement distance will become smaller or stop in place.

chinese
在[滑鼠模式]
在畫面縮放到最大
手勢向左滑是正常的，移動的距離是正常。
手勢向右滑會無法向右滑移動，滑鼠移動距離會變小或停在原處。

### How to Reproduce

In [mouse mode]
Zoom in, move mouse gestures

### Expected Behavior

Gestures to the right should slide normally as to the left

### Operating system(s) on local (controlling) side and remote (controlled) side

Android -> Windows 11

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.3 -> 1.3.3

### Screenshots

no Screenshots

### Additional Context

[Video display](https://github.com/user-attachments/assets/1fb91fca-db29-44a8-93a4-e017e1a02c65)

**Comment by fufesou** [comment]
Could you please record a short video? thanks.

**Comment by QuantWorker** [comment]
> Could you please upload a short video? thanks.

this Video display
https://github.com/user-attachments/assets/1fb91fca-db29-44a8-93a4-e017e1a02c65

**Comment by QuantWorker** [comment]
> Both I and fufesou can not reproduce this on our phone. This seems quite specific to your phone or controlled side
ruskdesk 1.3.2 tested  is normal .
this bug only in ruskdesk 1.3.3. is mouse right freeze

**Comment by QuantWorker** [comment]
> BTW, tech analysis is hard to make money in stock market.
yes,Quantitative trading, heavy losses

**Comment by NeoPolak** [comment]
I totally have the same issue - galaxy note 20 ultra

moving mouse to the right became hard

from the right border of the screen to the left, no issue, smooth move of distant cursor
from left to right, the cursor stops at 3/4 of the screen, and sometimes only moves up

**Comment by rustdesk** [comment]
> ruskdesk 1.3.2 tested is normal .
> this bug only in ruskdesk 1.3.3. is mouse right freeze

@fufesou dig

**Comment by rustdesk** [comment]
> ruskdesk 1.3.2 tested is normal .

@QuantWorker should you show me the build date of your 1.3.2 version.

**Comment by fufesou** [comment]
@QuantWorker @NeoPolak How about move up/down?

I did not find the cause of this issue, but I've reverted the most possible changes in this build https://github.com/fufesou/rustdesk/releases/tag/test-10084-1

Could you please also test it? Thanks

**Comment by QuantWorker** [comment]
Tested **test-10084-1**, it is normal
https://github.com/user-attachments/assets/cd8d6402-de3e-467c-adbb-999f75be2d0e

**Comment by QuantWorker** [comment]
> @QuantWorker @NeoPolak Thanks a lot for the kind feedback.
> 
> 1. How about move up/down?
> 2. How about connecting to other devices? Or other Android connect to the same controlled side?
> 3. I did not find the cause of this issue, but I've reverted the most possible changes in this build https://github.com/fufesou/rustdesk/releases/tag/test-10084-1 Could you please also test it? Thanks

Tested **test-10084-1**, it is normal
https://github.com/user-attachments/assets/cd8d6402-de3e-467c-adbb-999f75be2d0e

**Comment by QuantWorker** [comment]
> > ruskdesk 1.3.2 tested is normal .
> 
> @QuantWorker should you show me the build date of your 1.3.2 version. When did you download it?

The ruskdesk  1.3.2 version I am using is [rustdesk-1.3.2-aarch64-signed.apk]. 
The download date on the computer is October 30, 2024.
MD5:1F39973684042411E47695ED1CAE397D
CRC32:C18990B8

**Comment by rustdesk** [comment]
THanks

**Comment by fufesou** [comment]
@QuantWorker @NeoPolak Can you run `adb logcat`? I've added some prints in this build https://github.com/fufesou/rustdesk/releases/tag/test-10084-2

**Comment by rustdesk** [comment]
We reproduced this issue.

**Comment by QuantWorker** [comment]
> @QuantWorker Is it possible to connect your controlled side for me?
> 
> Or show me your display settings.
> 
> You can contact my email `linlong1266@gmail.com`

Email has been replied

**Comment by QuantWorker** [comment]
> @QuantWorker @NeoPolak Can you run `adb logcat`? I've added some prints in this build https://github.com/fufesou/rustdesk/releases/tag/test-10084-2

my Android device no root, can't adb

**Comment by NeoPolak** [comment]
> @QuantWorker @NeoPolak Thanks a lot for the kind feedback.
> 
> 1. How about move up/down?
> 2. How about connecting to other devices? Or other Android connect to the same controlled side?
> 3. I did not find the cause of this issue, but I've reverted the most possible changes in this build https://github.com/fufesou/rustdesk/releases/tag/test-10084-1 Could you please also test it? Thanks

Hi, i have tested it too, works like a charm

**Comment by rustdesk** [comment]
Please test https://github.com/rustdesk/rustdesk/releases/nightly, we put a fix.

**Comment by QuantWorker** [comment]
> Please test https://github.com/rustdesk/rustdesk/releases/nightly, we put a fix.

has tested this rustdesk_1.3.3-nightly
[rustdesk-1.3.3-aarch64-signed.apk] -> [rustdesk-1.3.3-x86_64.exe]
All Normal , Good.

**Comment by NeoPolak** [comment]
> > Please test https://github.com/rustdesk/rustdesk/releases/nightly, we put a fix.
> 
> has tested this rustdesk_1.3.3-nightly [rustdesk-1.3.3-aarch64-signed.apk] -> [rustdesk-1.3.3-x86_64.exe] All Normal , Good.

Same for me, I would even say that it seems to be smoother than before
