### ISSUE TITLE
Rustdesk Windows 7 Error

### ISSUE THREAD

**Issue by abdullah-erturk** [rustdesk/rustdesk#10085]
### Bug Description

When trying to install v1.3.3 on Windows 7, it gives the error in the picture.

### How to Reproduce

Older versions of Rustdesk installed on Windows 7 without any problems

### Expected Behavior

Older versions of Rustdesk installed on Windows 7 without any problems

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows 7

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.3

### Screenshots

![rustdesk error](https://github.com/user-attachments/assets/6c8a0e83-e680-4947-8b26-8489b64416fa)

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
This is introduced in Flutter 3.22, we can not be always stick to old Flutter, please use 32 bit instead.
