### ISSUE TITLE
win7 64 1.33版无法安装，同机器1.32没问题

### ISSUE THREAD

**Issue by josephelunt** [rustdesk/rustdesk#10093]
### Bug Description

win7 64 1.33版无法安装，同机器1.32没问题

### How to Reproduce

win7 64 1.33版无法安装，同机器1.32没问题

### Expected Behavior

win7 64 1.33版无法安装，同机器1.32没问题

### Operating system(s) on local (controlling) side and remote (controlled) side

windows 7 

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.3

### Screenshots

![11](https://github.com/user-attachments/assets/e37ad496-e501-4df3-bafb-45c1770c35fb)
![22](https://github.com/user-attachments/assets/3ee58ea6-e514-47d1-8a5c-398cd4c2aa89)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/10085#issuecomment-2506485955
