### ISSUE TITLE
Cannot drag the vertical slider in RustDesk GUI

### ISSUE THREAD

**Issue by xbyte99** [rustdesk/rustdesk#10106]
### Bug Description

Since 1.3.3 the vertical slider bar cannot be clicked on anymore for dragging list contents up and down. No matter which menu your're in (Favorites, Settings). Clicking and holding the slider bar when hovering the vertical slider area simply has no effect at all. Clicking in the empty areas above and below the bar results in the expected list up/down movement though.

This makes the annoying and still existing mouse wheel bug #8152 even more annoying now.

### How to Reproduce

- Move mouse cursor to the vertical slider are for the slider bar to appear
- Click and hold left mouse button on the slider bar
- Move up or down
- Nothing happens

### Expected Behavior

- Move mouse cursor to the vertical slider are for the slider bar to appear
- Click and hold left mouse button on the slider bar
- Move up or down
- List content moves up or down according to the mouse movement

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows 11 - bug not related to remote controlling

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.3 - bug not related to remote controlling

### Screenshots

https://github.com/user-attachments/assets/31fafa9e-f892-409c-b453-c43e9485477a

**Comment by rustdesk** [comment]
Please test https://github.com/rustdesk/rustdesk/releases/nightly
