### ISSUE TITLE
Keys are sent without window being in focus

### ISSUE THREAD

**Issue by davidskuza** [rustdesk/rustdesk#1010]
**Describe the bug you encountered:**

If you have mouse over rustdesk window (not focus, only mouse over) keys you type are sent. I just had situation when on one monitor I was connected to collegue but I was doing my things on main monitor. My mouse went over rustdesk's window and while typing on my keyboard everything was also sent to him.

**What did you expect to happen instead?**

Keys are only sent when I have focus on that window.

**How did you install `RustDesk`?**

Windows portable on both sides.

---

rustdesk-1.1.9-windows_x64-portable

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/461

**Comment by rustdesk** [comment]
Let's confirm the other vendors' behavior first.
