### ISSUE TITLE
failed to run custom build command for scrap v0.5.0 & failed to run custom build command for hwcodec v0.7.0

### ISSUE THREAD

**Issue by rockjl** [rustdesk/rustdesk#10114]
### Bug Description

I am following https://rustdesk.com/docs/en/dev/build/android/ Step by step execution of the build command. The following issues have been identified. At present, no solution has been found.

### How to Reproduce

rockjiang@rockjiang-ThinkPad-T490:~/workspace/rustdesk$ ./flutter/ndk_arm64.sh 
    Building arm64-v8a (aarch64-linux-android)
   Compiling ring v0.17.8
   Compiling zstd-sys v2.0.11+zstd.1.5.6
   Compiling libsodium-sys v0.2.7
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling webm-sys v1.0.4 (https://github.com/rustdesk-org/rust-webm#d2c4d3ac)
   Compiling oboe-sys v0.6.1
   Compiling backtrace v0.3.73
warning: lint `box_pointers` has been removed: it does not detect other kinds of allocations, and existed only for historical reasons
  --> /home/rockjiang/workspace/rustdesk/target/release/build/hbb_common-8824e7f0c3b5334e/out/protos/message.rs:12:10
   |
12 | #![allow(box_pointers)]
   |          ^^^^^^^^^^^^
   |
   = note: `#[warn(renamed_and_removed_lints)]` on by default

warning: lint `box_pointers` has been removed: it does not detect other kinds of allocations, and existed only for historical reasons
  --> /home/rockjiang/workspace/rustdesk/target/release/build/hbb_common-8824e7f0c3b5334e/out/protos/rendezvous.rs:12:10
   |
12 | #![allow(box_pointers)]
   |          ^^^^^^^^^^^^

warning: creating a shared reference to mutable static is discouraged
  --> libs/hbb_common/src/platform/mod.rs:65:33
   |
65 |         if let Some(callback) = &GLOBAL_CALLBACK {
   |                                 ^^^^^^^^^^^^^^^^ shared reference to mutable static
   |
   = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
   = note: shared references to mutable statics are dangerous; it's undefined behavior if the static is mutated or if a mutable reference is created for it while the shared reference lives
   = note: `#[warn(static_mut_refs)]` on by default
help: use `&raw const` instead to create a raw pointer
   |
65 |         if let Some(callback) = &raw const GLOBAL_CALLBACK {
   |                                 ~~~~~~~~~~

warning: `hbb_common` (lib) generated 3 warnings
   Compiling dart-sys v4.1.5
   Compiling hwcodec v0.7.0 (https://github.com/rustdesk-org/hwcodec#da7dab48)
   Compiling scrap v0.5.0 (/home/rockjiang/workspace/rustdesk/libs/scrap)
error: failed to run custom build command for `scrap v0.5.0 (/home/rockjiang/workspace/rustdesk/libs/scrap)`

Caused by:
  process didn't exit successfully: `/home/rockjiang/workspace/rustdesk/target/release/build/scrap-48b3787b17e34a74/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=NO_PKG_CONFIG_libyuv
  cargo:info=arm64-android
  cargo:rustc-link-lib=static=yuv
  cargo:rustc-link-search=/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/lib
  cargo:include=/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/include
  cargo:rerun-if-env-changed=NO_PKG_CONFIG_libvpx
  cargo:info=arm64-android
  cargo:rustc-link-lib=static=vpx
  cargo:rustc-link-search=/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/lib
  cargo:include=/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/include
  rerun-if-changed=/home/rockjiang/workspace/rustdesk/libs/scrap/src/bindings/vpx_ffi.h
  rerun-if-changed=/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/include
  cargo:rerun-if-env-changed=NO_PKG_CONFIG_aom
  cargo:info=arm64-android
  cargo:rustc-link-lib=static=aom
  cargo:rustc-link-search=/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/lib
  cargo:include=/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/include
  rerun-if-changed=/home/rockjiang/workspace/rustdesk/libs/scrap/src/bindings/aom_ffi.h
  rerun-if-changed=/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/include

  --- stderr
  /home/rockjiang/workspace/rustdesk/libs/scrap/src/bindings/aom_ffi.h:1:10: fatal error: 'aom/aom.h' file not found
  thread 'main' panicked at libs/scrap/build.rs:173:18:
  called `Result::unwrap()` on an `Err` value: ClangDiagnostic("/home/rockjiang/workspace/rustdesk/libs/scrap/src/bindings/aom_ffi.h:1:10: fatal error: 'aom/aom.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
warning: hwcodec@0.7.0: In file included from /home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/platform/linux/linux.cpp:2:
warning: hwcodec@0.7.0: /home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/platform/linux/../../log.h:5:10: fatal error: 'libavutil/attributes.h' file not found
warning: hwcodec@0.7.0:     5 | #include <libavutil/attributes.h>
warning: hwcodec@0.7.0:       |          ^~~~~~~~~~~~~~~~~~~~~~~~
warning: hwcodec@0.7.0: 1 error generated.
warning: hwcodec@0.7.0: ToolExecError: Command "/home/rockjiang/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" "-O3" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-linux-android" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/externals/nv-codec-headers_n11.1.5.2/include/ffnvcodec" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/platform/linux" "-I" "/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/include" "--target=aarch64-linux-android21" "-o" "/home/rockjiang/workspace/rustdesk/target/aarch64-linux-android/release/build/hwcodec-0a4731cc4081085c/out/469bfb2a4cdb3825-linux.o" "-c" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/platform/linux/linux.cpp" with args clang did not execute successfully (status code exit status: 1).cargo:warning=In file included from /home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/log.cpp:2:
warning: hwcodec@0.7.0: /home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/log.h:5:10: fatal error: 'libavutil/attributes.h' file not found
warning: hwcodec@0.7.0:     5 | #include <libavutil/attributes.h>
warning: hwcodec@0.7.0:       |          ^~~~~~~~~~~~~~~~~~~~~~~~
warning: hwcodec@0.7.0: 1 error generated.
warning: hwcodec@0.7.0: ToolExecError: Command "/home/rockjiang/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" "-O3" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-linux-android" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/externals/nv-codec-headers_n11.1.5.2/include/ffnvcodec" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/platform/linux" "-I" "/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/include" "--target=aarch64-linux-android21" "-o" "/home/rockjiang/workspace/rustdesk/target/aarch64-linux-android/release/build/hwcodec-0a4731cc4081085c/out/b0ca93ef57a5e2ea-log.o" "-c" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/log.cpp" with args clang did not execute successfully (status code exit status: 1).cargo:warning=/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/util.cpp:2:10: fatal error: 'libavutil/opt.h' file not found
warning: hwcodec@0.7.0:     2 | #include <libavutil/opt.h>
warning: hwcodec@0.7.0:       |          ^~~~~~~~~~~~~~~~~
warning: hwcodec@0.7.0: 1 error generated.
warning: hwcodec@0.7.0: ToolExecError: Command "/home/rockjiang/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" "-O3" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-linux-android" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/externals/nv-codec-headers_n11.1.5.2/include/ffnvcodec" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/platform/linux" "-I" "/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/include" "--target=aarch64-linux-android21" "-o" "/home/rockjiang/workspace/rustdesk/target/aarch64-linux-android/release/build/hwcodec-0a4731cc4081085c/out/b0ca93ef57a5e2ea-util.o" "-c" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/util.cpp" with args clang did not execute successfully (status code exit status: 1).cargo:warning=/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/ffmpeg_ram/ffmpeg_ram_encode.cpp:4:10: fatal error: 'libavcodec/avcodec.h' file not found
warning: hwcodec@0.7.0:     4 | #include <libavcodec/avcodec.h>
warning: hwcodec@0.7.0:       |          ^~~~~~~~~~~~~~~~~~~~~~
warning: hwcodec@0.7.0: 1 error generated.
warning: hwcodec@0.7.0: ToolExecError: Command "/home/rockjiang/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" "-O3" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-linux-android" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/externals/nv-codec-headers_n11.1.5.2/include/ffnvcodec" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/platform/linux" "-I" "/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/include" "--target=aarch64-linux-android21" "-o" "/home/rockjiang/workspace/rustdesk/target/aarch64-linux-android/release/build/hwcodec-0a4731cc4081085c/out/8e359797294e1a8f-ffmpeg_ram_encode.o" "-c" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/ffmpeg_ram/ffmpeg_ram_encode.cpp" with args clang did not execute successfully (status code exit status: 1).cargo:warning=/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/ffmpeg_ram/ffmpeg_ram_decode.cpp:5:10: fatal error: 'libavcodec/avcodec.h' file not found
warning: hwcodec@0.7.0:     5 | #include <libavcodec/avcodec.h>
warning: hwcodec@0.7.0:       |          ^~~~~~~~~~~~~~~~~~~~~~
warning: hwcodec@0.7.0: 1 error generated.
warning: hwcodec@0.7.0: ToolExecError: Command "/home/rockjiang/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" "-O3" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-linux-android" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/externals/nv-codec-headers_n11.1.5.2/include/ffnvcodec" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/platform/linux" "-I" "/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/include" "--target=aarch64-linux-android21" "-o" "/home/rockjiang/workspace/rustdesk/target/aarch64-linux-android/release/build/hwcodec-0a4731cc4081085c/out/8e359797294e1a8f-ffmpeg_ram_decode.o" "-c" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/ffmpeg_ram/ffmpeg_ram_decode.cpp" with args clang did not execute successfully (status code exit status: 1).cargo:warning=/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/mux/mux.cpp:4:10: fatal error: 'libavcodec/avcodec.h' file not found
warning: hwcodec@0.7.0:     4 | #include <libavcodec/avcodec.h>
warning: hwcodec@0.7.0:       |          ^~~~~~~~~~~~~~~~~~~~~~
warning: hwcodec@0.7.0: 1 error generated.
warning: hwcodec@0.7.0: ToolExecError: Command "/home/rockjiang/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" "-O3" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-linux-android" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/externals/nv-codec-headers_n11.1.5.2/include/ffnvcodec" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/platform/linux" "-I" "/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/include" "--target=aarch64-linux-android21" "-o" "/home/rockjiang/workspace/rustdesk/target/aarch64-linux-android/release/build/hwcodec-0a4731cc4081085c/out/65884d1dd29b2c18-mux.o" "-c" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/mux/mux.cpp" with args clang did not execute successfully (status code exit status: 1).
error: failed to run custom build command for `hwcodec v0.7.0 (https://github.com/rustdesk-org/hwcodec#da7dab48)`

Caused by:
  process didn't exit successfully: `/home/rockjiang/workspace/rustdesk/target/release/build/hwcodec-edb13cd54d31b668/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=src
  cargo:rerun-if-changed=deps
  cargo:rerun-if-changed=/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/externals
  cargo:rerun-if-changed=/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp
  cargo:info=arm64-android
  cargo:rustc-link-search=native=/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/lib
  cargo:rustc-link-lib=static=avcodec
  cargo:rustc-link-lib=static=avutil
  cargo:rustc-link-lib=static=avformat
  cargo:include=/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/include
  cargo:rustc-link-lib=z
  cargo:rustc-link-lib=m
  cargo:rustc-link-lib=android
  cargo:rustc-link-lib=atomic
  OUT_DIR = Some(/home/rockjiang/workspace/rustdesk/target/aarch64-linux-android/release/build/hwcodec-0a4731cc4081085c/out)
  TARGET = Some(aarch64-linux-android)
  OPT_LEVEL = Some(3)
  HOST = Some(x86_64-unknown-linux-gnu)
  cargo:rerun-if-env-changed=CC_aarch64-linux-android
  CC_aarch64-linux-android = Some(/home/rockjiang/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/linux-x86_64/bin/clang)
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(false)
  cargo:rerun-if-env-changed=CFLAGS_aarch64-linux-android
  CFLAGS_aarch64-linux-android = Some(--target=aarch64-linux-android21)
  cargo:warning=In file included from /home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/platform/linux/linux.cpp:2:
  cargo:warning=/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/platform/linux/../../log.h:5:10: fatal error: 'libavutil/attributes.h' file not found
  cargo:warning=    5 | #include <libavutil/attributes.h>
  cargo:warning=      |          ^~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=1 error generated.
  exit status: 1
  cargo:warning=ToolExecError: Command "/home/rockjiang/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" "-O3" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-linux-android" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/externals/nv-codec-headers_n11.1.5.2/include/ffnvcodec" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/platform/linux" "-I" "/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/include" "--target=aarch64-linux-android21" "-o" "/home/rockjiang/workspace/rustdesk/target/aarch64-linux-android/release/build/hwcodec-0a4731cc4081085c/out/469bfb2a4cdb3825-linux.o" "-c" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/platform/linux/linux.cpp" with args clang did not execute successfully (status code exit status: 1).cargo:warning=In file included from /home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/log.cpp:2:
  cargo:warning=/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/log.h:5:10: fatal error: 'libavutil/attributes.h' file not found
  cargo:warning=    5 | #include <libavutil/attributes.h>
  cargo:warning=      |          ^~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=1 error generated.

  exit status: 1
  cargo:warning=ToolExecError: Command "/home/rockjiang/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" "-O3" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-linux-android" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/externals/nv-codec-headers_n11.1.5.2/include/ffnvcodec" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/platform/linux" "-I" "/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/include" "--target=aarch64-linux-android21" "-o" "/home/rockjiang/workspace/rustdesk/target/aarch64-linux-android/release/build/hwcodec-0a4731cc4081085c/out/b0ca93ef57a5e2ea-log.o" "-c" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/log.cpp" with args clang did not execute successfully (status code exit status: 1).cargo:warning=/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/util.cpp:2:10: fatal error: 'libavutil/opt.h' file not found
  cargo:warning=    2 | #include <libavutil/opt.h>
  cargo:warning=      |          ^~~~~~~~~~~~~~~~~
  cargo:warning=1 error generated.

  exit status: 1
  cargo:warning=ToolExecError: Command "/home/rockjiang/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" "-O3" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-linux-android" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/externals/nv-codec-headers_n11.1.5.2/include/ffnvcodec" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/platform/linux" "-I" "/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/include" "--target=aarch64-linux-android21" "-o" "/home/rockjiang/workspace/rustdesk/target/aarch64-linux-android/release/build/hwcodec-0a4731cc4081085c/out/b0ca93ef57a5e2ea-util.o" "-c" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/util.cpp" with args clang did not execute successfully (status code exit status: 1).cargo:warning=/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/ffmpeg_ram/ffmpeg_ram_encode.cpp:4:10: fatal error: 'libavcodec/avcodec.h' file not found
  cargo:warning=    4 | #include <libavcodec/avcodec.h>
  cargo:warning=      |          ^~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=1 error generated.

  exit status: 1
  cargo:warning=ToolExecError: Command "/home/rockjiang/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" "-O3" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-linux-android" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/externals/nv-codec-headers_n11.1.5.2/include/ffnvcodec" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/platform/linux" "-I" "/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/include" "--target=aarch64-linux-android21" "-o" "/home/rockjiang/workspace/rustdesk/target/aarch64-linux-android/release/build/hwcodec-0a4731cc4081085c/out/8e359797294e1a8f-ffmpeg_ram_encode.o" "-c" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/ffmpeg_ram/ffmpeg_ram_encode.cpp" with args clang did not execute successfully (status code exit status: 1).cargo:warning=/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/ffmpeg_ram/ffmpeg_ram_decode.cpp:5:10: fatal error: 'libavcodec/avcodec.h' file not found
  cargo:warning=    5 | #include <libavcodec/avcodec.h>
  cargo:warning=      |          ^~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=1 error generated.

  exit status: 1
  cargo:warning=ToolExecError: Command "/home/rockjiang/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" "-O3" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-linux-android" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/externals/nv-codec-headers_n11.1.5.2/include/ffnvcodec" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/platform/linux" "-I" "/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/include" "--target=aarch64-linux-android21" "-o" "/home/rockjiang/workspace/rustdesk/target/aarch64-linux-android/release/build/hwcodec-0a4731cc4081085c/out/8e359797294e1a8f-ffmpeg_ram_decode.o" "-c" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/ffmpeg_ram/ffmpeg_ram_decode.cpp" with args clang did not execute successfully (status code exit status: 1).cargo:warning=/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/mux/mux.cpp:4:10: fatal error: 'libavcodec/avcodec.h' file not found
  cargo:warning=    4 | #include <libavcodec/avcodec.h>
  cargo:warning=      |          ^~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=1 error generated.

  exit status: 1
  cargo:warning=ToolExecError: Command "/home/rockjiang/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" "-O3" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-linux-android" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/externals/nv-codec-headers_n11.1.5.2/include/ffnvcodec" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/platform/linux" "-I" "/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/include" "--target=aarch64-linux-android21" "-o" "/home/rockjiang/workspace/rustdesk/target/aarch64-linux-android/release/build/hwcodec-0a4731cc4081085c/out/65884d1dd29b2c18-mux.o" "-c" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/mux/mux.cpp" with args clang did not execute successfully (status code exit status: 1).

  --- stderr

  error occurred: Command "/home/rockjiang/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" "-O3" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-linux-android" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/externals/nv-codec-headers_n11.1.5.2/include/ffnvcodec" "-I" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/common/platform/linux" "-I" "/home/rockjiang/tools/vcpkg/vcpkg/installed/arm64-android/include" "--target=aarch64-linux-android21" "-o" "/home/rockjiang/workspace/rustdesk/target/aarch64-linux-android/release/build/hwcodec-0a4731cc4081085c/out/65884d1dd29b2c18-mux.o" "-c" "/home/rockjiang/.cargo/git/checkouts/hwcodec-74796a7f8f16bbb9/da7dab4/cpp/mux/mux.cpp" with args clang did not execute successfully (status code exit status: 1).

note: If the build failed due to a missing target, you can run this command:
note: 
note:     rustup target install aarch64-linux-android

### Expected Behavior

![截图 2024-11-30 10-17-45](https://github.com/user-attachments/assets/4b236a9c-15e6-4654-855c-a692f9995b37)

### Operating system(s) on local (controlling) side and remote (controlled) side

ubuntu 24.04

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.3

### Screenshots

![截图 2024-11-30 10-15-50](https://github.com/user-attachments/assets/3ce331f0-99cc-4650-9fbb-476be99c10b2)
![截图 2024-11-30 10-09-24](https://github.com/user-attachments/assets/11b449d9-bb07-444d-a1e2-0e5228f1afc5)

**Comment by rustdesk** [comment]
#763
