### ISSUE TITLE
Missing Chinese characters in GUI for Linux Version

### ISSUE THREAD

**Issue by onlyacat** [rustdesk/rustdesk#1011]
**Describe the bug you encountered:**

The Chinese characters are missing in the GUI in the Linux version. 

![image](https://user-images.githubusercontent.com/29370032/179970595-f5132d6e-057b-4a8c-9096-6d2e7ddd08f9.png)

If I run the Rustdesk from the terminal, it drops some outputs:
```
INFO:TIS: scaleFactor 1
INFO:TIS: current platform: Linux
INFO:TIS: is_xfce:  true
```

**What did you expect to happen instead?**

It can show Chinese characters as expected.

**How did you install `RustDesk`?**

yay -S rustdesk
use rustdesk-bin version

---

**RustDesk version and environment**

```
OS: Manjaro Linux x86_64 
Kernel: 5.15.49-1-MANJARO 
Resolution: 2560x1440 
DE: Xfce 4.16 
WM: Xfwm4 
CPU: Intel Celeron N5105 (4) @ 2.900GHz 
GPU: Intel JasperLake [UHD Graphics] 
Memory: 7792MiB / 15746MiB 
```
rustdesk version: v1.1.9

Also, it might be a workaround if I can change the language for Rustdesk. Is there any entry? Thanks!

**Comment by rustdesk** [comment]
try out our version, https://github.com/rustdesk/rustdesk/releases/tag/1.1.9#:~:text=rustdesk%2D1.1.9%2Dmanjaro%2Darch.pkg.tar.zst,
it will install Chinese font file.

**Comment by Heap-Hop** [comment]
Same issue with Raspberry Pi OS

**Comment by Heap-Hop** [comment]
Could you please make a simple test for sciter in your environment?

```
# scapp is a simple sciter test bin
wget https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin.lnx/x64/scapp

# and prepare a index.html with some Chinese characters, like 
echo '<h1>Test 测试中文<h1/>' > index.html

chmod +x ./scapp
./scapp

# or run ./scapp and chose any other html with Chinese characters
```

**Comment by onlyacat** [comment]
> Could you please make a simple test for sciter in your environment?
> 
> ```
> # scapp is a simple sciter test bin
> wget https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin.lnx/x64/scapp
> 
> # and prepare a index.html with some Chinese characters, like 
> echo '<h1>Test 测试中文<h1/>' > index.html
> 
> chmod +x ./scapp
> ./scapp
> 
> # or run ./scapp and chose any other html with Chinese characters
> ```

For my environment, it shows the characters correctly. Guessing it is related to the font set.

**Comment by onlyacat** [comment]
> try out our version, https://github.com/rustdesk/rustdesk/releases/tag/1.1.9#:~:text=rustdesk%2D1.1.9%2Dmanjaro%2Darch.pkg.tar.zst, it will install Chinese font file. rustdesk-bin is not actually uploaded by us.

Thanks! This one works for me :)

**Comment by goodluck1982** [comment]
> Same issue with Raspberry Pi OS

This problem still exists on Raspberry Pi.

**rustdesk-1.2.2-aarch64.deb**

```
raspberrypi$ lsb_release
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
raspberrypi$ uname -a
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```
![image](https://github.com/rustdesk/rustdesk/assets/48718961/abcfb036-94dd-40e4-a172-2ad4d1936f8c)
