### ISSUE TITLE
mouse cursor is not accurate

### ISSUE THREAD

**Issue by kansonkong** [rustdesk/rustdesk#10123]
### Bug Description

when remote control a client desktop, running PD(parallel desktop) virtual machine. the mouse cursor in the client OS(ubuntu 20.04) is floating, you cannot click right on the icon you want to click.

### How to Reproduce

Local Side: macOS Sequoia 15.1.   Rustdesk:  1.3.3
Remote Side: macOS Ventura 13.4 Rustdesk: 1.3.3
Virtual Machine on Remote Side:  Parallel Desktop 18.1.1   Client OS:  Ubuntu 20.04

mouse cursor floating will not happen in the remote host OS, you can  click accurately anywhere you want, but when you shift to the virtual machine OS, the mouse cursor floating occurred.  

### Expected Behavior

the mouse cursor floating should not be happening.

### Operating system(s) on local (controlling) side and remote (controlled) side

macOS->macOS

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.3->1.3.3

### Screenshots

<img width="805" alt="image" src="https://github.com/user-attachments/assets/161b8d6a-0e90-4e89-80e2-4351772534a2">

**Comment by rustdesk** [comment]
1.3.2 works？

**Comment by rustdesk** [comment]
Is it only inaccurate in the VM, but ok in the host?

**Comment by link1873** [comment]
Android problems to inaccuation movement or more doesn't wanna even move sometimes.

**Comment by rustdesk** [comment]
> Android problems to inaccuation movement or more doesn't wanna even move sometimes.

https://github.com/rustdesk/rustdesk/issues/10084#issuecomment-2508118904

**Comment by kansonkong** [comment]
> 1.3.2 works？

same

**Comment by kansonkong** [comment]
> Is it only inaccurate in the VM, but ok in the host?

yes, only in VM

**Comment by rustdesk** [comment]
Close as tracked by https://github.com/rustdesk/rustdesk/issues/4357

**Comment by kansonkong** [comment]
btw， same local and remote macOS, when I use sunlogin(another remote control software), the mouse works without problem.
