### ISSUE TITLE
Keyboard input issues after pressed F4: some letter redirected to dock icons.

### ISSUE THREAD

**Issue by Atom2004** [rustdesk/rustdesk#10126]
### Bug Description

After pressed the F4 (or F1) key while connecting from Windows 11 to macOS via RustDesk, keyboard input behavior becomes abnormal:

When typing 'A' in text input fields (e.g., Edge browser's search bar):
Expected: Letter 'a' appears in the text field
Actual: Focus moves to the Finder icon in the dock instead
When pressing 'E':
Expected: Letter 'e' appears in the text field
Actual: Emoji input dialog opens

Disconnecting and reconnecting the remote session does not fix the problem.
Restarting the RustDesk service temporarily resolves the issue.

It's OK if I connect the same keyboard into this macos directly.

### How to Reproduce

1. Start RustDesk on Windows 11 client
2. Connect to macOS host
3. Open a browser (e.g., Edge)
4. Click on the search bar
5. Press and release F4 key once (or F1 can got same behavior)
6. Try typing key 'A' in the search bar.
7. Now focus on the Finder icon in dock, and no letter append into the search bar. Or show the message box on right side of the screen if typing key 'N'.

### Expected Behavior

Letter what I typed appears in the text field (search bar).

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows 11 -> macOS

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.3 -> 1.3.3

### Screenshots

Here is a screen recording. It shows the key and mouse action in the bottom right corner.
[outgoing_192.168.9.62_20241201132829085_display0_av1.webm](https://github.com/user-attachments/assets/f1212b39-3506-4bd1-9c81-addd62809ed6)

Here is the keyboard config of RustDesk.
![image](https://github.com/user-attachments/assets/51a0bb1b-cfb4-46d5-a27e-6b63bc7205ed)

**Comment by rustdesk** [comment]
Could you help confirm if 1.3.1 / 1.3.2 have the same issue?

**Comment by Atom2004** [comment]
> Could you help confirm if `1.3.1 / 1.3.2` -> `1.3.1 / 1.3.2` have the same issue? And if turn off `swap contr-cmd key`.

Thank for your reply.

I tried to turn off `swap contr-cmd key`. The behavior absolutely same.

Here is the screen recoding of 1.3.1 -> 1.3.1. It occurs this issue but fix after click the mouse button anywhere. 1.3.3 doesn't.
[outgoing_192.168.9.62_20241201153832606_av1.webm](https://github.com/user-attachments/assets/28e01ec1-cba3-4d68-8626-ba06f6ca22c1)

behaviors of 1.3.2 -> 1.3.2 same as 1.3.3 -> 1.3.3.
behaviors of 1.3.0 -> 1.3.0 same as 1.3.1 -> 1.3.1.

**Comment by rustdesk** [comment]
> fix after click the mouse button anywhere. 1.3.3 doesn't.

@fufesou

**Comment by rustdesk** [comment]
> click the mouse button anywhere

Did this also occurs after presed F4?

**Comment by fufesou** [comment]
@Atom2004 Thanks for your feedback. 

https://stackoverflow.com/questions/74938870/sticky-fn-after-home-is-simulated-programmatically-macos

I've tested `F1` and `F4`, `Fn` is sticky too.

I'll find all keys that affects `Fn`.

> Disconnecting and reconnecting the remote session does not fix the problem.
Restarting the RustDesk service temporarily resolves the issue.

Clicking `Fn` on the controlled side also release it.

**Comment by Atom2004** [comment]
> Clicking `Fn` on the controlled side also release it.

Thanks for your solution.
But I'm using Windows keyboard, without `Fn` key for macos.

I have no idea for now. I'm sure Rustdesk will provide the perfect solution in the next update.

**Comment by fufesou** [comment]
@Atom2004 I'll put a fix soon.

You can also press `Home`, `End`, `PageUp`, `PageDown` or `Arraw up/down/left/right` to release `Fn` for now.
We have handled thoes sticky keys.

But it may be that the `F1-F12` keys are missing.

**Comment by Atom2004** [comment]
> @Atom2004 I'll put a fix soon.
> 
> You can also press `Home`, `End`, `PageUp`, `PageDown` or `Arraw up/down/left/right` to release `Fn` for now. We have handled thoes sticky keys.
> 
> But it may be that the `F1-F12` keys are missing.

Thank you so much.

**Comment by rustdesk** [comment]
We got a fix, please test https://github.com/rustdesk/rustdesk/releases/tag/nightly on both sides.

**Comment by Atom2004** [comment]
> We got a fix, please test https://github.com/rustdesk/rustdesk/releases/tag/nightly on both sides.

That's fixed. Great!
