### ISSUE TITLE
Rounded corners are opaque black after 1.3.3

### ISSUE THREAD

**Issue by darkblaze69** [rustdesk/rustdesk#10121]
### Bug Description

* Arch Linux
* GNOME 47.2
* Intel i915

After upgrading to 1.3.3 semi-transparent rounded corners and shadows turned into black opaque.

### How to Reproduce

update to 1.3.3

open rustdesk

### Expected Behavior

semi-transparent rounded corners and shadows

### Operating system(s) on local (controlling) side and remote (controlled) side

Linux > Linux

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.3 -> 1.3.3

### Screenshots

1.3.3:

![Screenshot From 2024-11-30 12-28-36](https://github.com/user-attachments/assets/dc9935fc-e378-4dd1-83fa-0c34d36cf74d)

1.3.2:

![Screenshot From 2024-11-30 12-31-04](https://github.com/user-attachments/assets/8d8f88e1-d85f-4251-a421-4f83fb8ca449)

**Comment by rustdesk** [comment]
Please test https://github.com/rustdesk/rustdesk/releases/nightly

**Comment by darkblaze69** [comment]
Thanks, tested main window and remote connection, seems working good now.
