### ISSUE TITLE
BUG: Error after RDP Login: Error code: 0x904 | RDP still works with Version 1.2.3

### ISSUE THREAD

**Issue by Seamoconic** [rustdesk/rustdesk#10125]
### Bug Description

If the target computer has a newer Rustdesk version than 1.2.3, you can no longer connect via RDP. As soon as you enter the login data of the domain user or the local user, the following error message appears: 
Error code: 0x904
Extended error code: 0x0

![image](https://github.com/user-attachments/assets/4640a6bc-c30a-4fb5-8e33-f23680883818)

The Rustdesk version of the PC that starts the connection does not matter.

### How to Reproduce

Connect to a PC via RDP Rustdesk which is a Rustdesk version 1.2.7 or newer and then enter the login data of the domain user or the local user. 

### Expected Behavior

Following error message appears:
Error code: 0x904
Extended error code: 0x0

![image](https://github.com/user-attachments/assets/4640a6bc-c30a-4fb5-8e33-f23680883818)

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows 11

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.2 -> 1.3.3

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/10039

**Comment by rustdesk** [comment]
I will block you if you continue to push.

**Comment by rustdesk** [comment]
This is open source, but we are not you free programmer.
