### ISSUE TITLE
Linuxmint - Window is not displayed

### ISSUE THREAD

**Issue by twprh** [rustdesk/rustdesk#10134]
### Bug Description

Version 1.3.4: 
The window is not displayed correctly.

The thumbnail graphic is displayed and if you move the window using the context menu, the position in the workspace switcher is also displayed correctly.

Version 1.3.3 2024-11-28 18:33: 
The window is displayd correctly

Same behavior with the appimage and flatpack version. The Sciter version works.

### How to Reproduce

Just start new Version. 

### Expected Behavior

Window should be displayed

### Operating system(s) on local (controlling) side and remote (controlled) side

Linuxmint 22 - Mate 1.26.2

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.4

### Screenshots

![Arbeitsfläche 1_003](https://github.com/user-attachments/assets/1b18b56e-e828-4be3-97ae-4eb70c2b586d)

**Comment by fufesou** [comment]
Thanks for the feedback. I'll test it.

**Comment by twprh** [comment]
Just tested the nightly.
From Linuxmint to Windows (both new nightly):  
Both main window and remote window are fine. The remote window is displayed correctly with rounded corners.
 
I will test Linuxmint to Linuxmint tomorrow.
