### ISSUE TITLE
"Uninstall RustDesk" not translated in program group

### ISSUE THREAD

**Issue by bovirus** [rustdesk/rustdesk#10147]
### Bug Description

@rustdesk 

In program group there is an icon"Uninstall RustDesk".
Could be possible to localzie "UninstalL" (the instalelr is multilanguage).

### How to Reproduce

Install the program

### Expected Behavior

Translated "Uninstall"

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows 10 22H2 64bit Pro

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.3

### Screenshots

![image](https://github.com/user-attachments/assets/a918bb25-c093-492a-b6fc-12e2b7145933)

**Comment by rustdesk** [comment]
Noted, but this one is not normal as other translations, a big effort required. We will do in the future.
