### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Accademia** [rustdesk/rustdesk#10145]
### Bug Description

I am using the latest version of ARM macOS and the latest version of RustDesk.

When I click to modify the “Unlock Network Settings” and enter the password, RustDesk crashes. The program crashes every time I enter the password. How can I assist you in identifying this bug?

### How to Reproduce

When I click to modify the “Unlock Network Settings” and enter the password, RustDesk crashes. 

### Expected Behavior

The program crashes every time I enter the password. How can I assist you in identifying this bug?

### Operating system(s) on local (controlling) side and remote (controlled) side

macos 15.1

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.3

### Screenshots

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               RustDesk [9641]
Path:                  /Applications/RustDesk.app/Contents/MacOS/RustDesk
Identifier:            com.carriez.rustdesk
Version:               1.3.3 (52)
Code Type:             ARM-64 (Native)
Parent Process:        RustDesk [9309]
Responsible:           RustDesk [9309]
User ID:               501

Date/Time:             2024-12-02 22:33:30.5152 +0800
OS Version:            macOS 15.1.1 (24B91)
Report Version:        12
Anonymous UUID:        197E6FAC-7935-690F-BE33-32E609786AF3

Time Awake Since Boot: 1100 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   RustDesk [9641]

Application Specific Information:
abort() called

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1979ee600 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x197a26f70 pthread_kill + 288
2   libsystem_c.dylib             	       0x197933908 abort + 128
3   libc++abi.dylib               	       0x1979dd44c abort_message + 132
4   libc++abi.dylib               	       0x1979cba40 demangling_terminate_handler() + 348
5   libobjc.A.dylib               	       0x1976713e4 _objc_terminate() + 156
6   libc++abi.dylib               	       0x1979dc710 std::__terminate(void (*)()) + 16
7   libc++abi.dylib               	       0x1979dfcdc __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 88
8   libc++abi.dylib               	       0x1979dfc84 __cxa_throw + 92
9   libobjc.A.dylib               	       0x197666e40 objc_exception_throw + 448
10  CoreFoundation                	       0x197c35638 -[NSObject(NSObject) doesNotRecognizeSelector:] + 364
11  CoreFoundation                	       0x197aeccc0 ___forwarding___ + 1568
12  CoreFoundation                	       0x197aec5e0 _CF_forwarding_prep_0 + 96
13  FlutterMacOS                  	       0x1051e1c04 0x1051e0000 + 7172
14  FlutterMacOS                  	       0x1051e1604 0x1051e0000 + 5636
15  FlutterMacOS                  	       0x105a5b874 0x1051e0000 + 8894580
16  FlutterMacOS                  	       0x10521724c 0x1051e0000 + 225868
17  FlutterMacOS                  	       0x1051f95dc 0x1051e0000 + 103900
18  FlutterMacOS                  	       0x105a6de60 0x1051e0000 + 8969824
19  FlutterMacOS                  	       0x105a80a50 0x1051e0000 + 9046608
20  FlutterMacOS                  	       0x10598dd8c 0x1051e0000 + 8052108
21  FlutterMacOS                  	       0x105a7e150 0x1051e0000 + 9036112
22  FlutterMacOS                  	       0x105a66dac 0x1051e0000 + 8940972
23  FlutterMacOS                  	       0x1051f8e40 0x1051e0000 + 101952
24  FlutterMacOS                  	       0x1051f8ff4 0x1051e0000 + 102388
25  libdispatch.dylib             	       0x1978728f8 _dispatch_call_block_and_release + 32
26  libdispatch.dylib             	       0x197874658 _dispatch_client_callout + 20
27  libdispatch.dylib             	       0x197882f68 _dispatch_main_queue_drain + 980
28  libdispatch.dylib             	       0x197882b84 _dispatch_main_queue_callback_4CF + 44
29  CoreFoundation                	       0x197b4ce60 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
30  CoreFoundation                	       0x197b0ca4c __CFRunLoopRun + 1996
31  CoreFoundation                	       0x197b0bbc4 CFRunLoopRunSpecific + 588
32  HIToolbox                     	       0x1a2f7bf64 RunCurrentEventLoopInMode + 292
33  HIToolbox                     	       0x1a2f81d54 ReceiveNextEventCommon + 636
34  HIToolbox                     	       0x1a2f81eb8 _BlockUntilNextEventMatchingListInModeWithFilter + 76
35  AppKit                        	       0x19b637a08 _DPSNextEvent + 660
36  AppKit                        	       0x19bf77e0c -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
37  AppKit                        	       0x19b62aae0 -[NSApplication run] + 480
38  AppKit                        	       0x19b601364 NSApplicationMain + 888
39  RustDesk                      	       0x1026159d4 main + 36
40  dyld                          	       0x1976a4274 start + 2840

Thread 1:: flexi_logger-fs-cleanup
0   libsystem_kernel.dylib        	       0x1979e5db0 semaphore_wait_trap + 8
1   libdispatch.dylib             	       0x197874bf4 _dispatch_sema4_wait + 28
2   libdispatch.dylib             	       0x1978752a8 _dispatch_semaphore_wait_slow + 132
3   liblibrustdesk.dylib          	       0x104bc6c14 0x103bd4000 + 16722964
4   liblibrustdesk.dylib          	       0x1049d17d0 0x103bd4000 + 14669776
5   liblibrustdesk.dylib          	       0x1049cef70 0x103bd4000 + 14659440
6   liblibrustdesk.dylib          	       0x1049d4350 0x103bd4000 + 14680912
7   liblibrustdesk.dylib          	       0x104bd8574 0x103bd4000 + 16794996
8   libsystem_pthread.dylib       	       0x197a272e4 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x197a220fc thread_start + 8

Thread 2:: io.flutter.ui
0   libsystem_kernel.dylib        	       0x1979e5e34 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1979f85d0 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1979ee9d8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x1979e617c mach_msg + 24
4   CoreFoundation                	       0x197b0dedc __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x197b0c73c __CFRunLoopRun + 1212
6   CoreFoundation                	       0x197b0bbc4 CFRunLoopRunSpecific + 588
7   FlutterMacOS                  	       0x10526068c 0x1051e0000 + 525964
8   FlutterMacOS                  	       0x1052577d0 0x1051e0000 + 489424
9   FlutterMacOS                  	       0x10525f2a8 0x1051e0000 + 520872
10  FlutterMacOS                  	       0x10525ed60 0x1051e0000 + 519520
11  libsystem_pthread.dylib       	       0x197a272e4 _pthread_start + 136
12  libsystem_pthread.dylib       	       0x197a220fc thread_start + 8

Thread 3:: io.flutter.raster
0   libsystem_kernel.dylib        	       0x1979e95cc __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x197a27894 _pthread_cond_wait + 1204
2   Metal                         	       0x1a27f8564 -[_MTLCommandBuffer waitUntilScheduled] + 84
3   FlutterMacOS                  	       0x105209138 0x1051e0000 + 168248
4   FlutterMacOS                  	       0x1051e81b4 0x1051e0000 + 33204
5   FlutterMacOS                  	       0x105a6af80 0x1051e0000 + 8957824
6   FlutterMacOS                  	       0x105a78770 0x1051e0000 + 9013104
7   FlutterMacOS                  	       0x105a7617c 0x1051e0000 + 9003388
8   FlutterMacOS                  	       0x10596c150 0x1051e0000 + 7913808
9   FlutterMacOS                  	       0x10596b838 0x1051e0000 + 7911480
10  FlutterMacOS                  	       0x105969dcc 0x1051e0000 + 7904716
11  FlutterMacOS                  	       0x10596ae48 0x1051e0000 + 7908936
12  FlutterMacOS                  	       0x10596ea38 0x1051e0000 + 7924280
13  FlutterMacOS                  	       0x10596a494 0x1051e0000 + 7906452
14  FlutterMacOS                  	       0x10596a0b4 0x1051e0000 + 7905460
15  FlutterMacOS                  	       0x10598d5d4 0x1051e0000 + 8050132
16  FlutterMacOS                  	       0x1052579d4 0x1051e0000 + 489940
17  FlutterMacOS                  	       0x1052603f0 0x1051e0000 + 525296
18  CoreFoundation                	       0x197b27824 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
19  CoreFoundation                	       0x197b274c8 __CFRunLoopDoTimer + 1012
20  CoreFoundation                	       0x197b26fd8 __CFRunLoopDoTimers + 356
21  CoreFoundation                	       0x197b0c9c0 __CFRunLoopRun + 1856
22  CoreFoundation                	       0x197b0bbc4 CFRunLoopRunSpecific + 588
23  FlutterMacOS                  	       0x10526068c 0x1051e0000 + 525964
24  FlutterMacOS                  	       0x1052577d0 0x1051e0000 + 489424
25  FlutterMacOS                  	       0x10525f2a8 0x1051e0000 + 520872
26  FlutterMacOS                  	       0x10525ed60 0x1051e0000 + 519520
27  libsystem_pthread.dylib       	       0x197a272e4 _pthread_start + 136
28  libsystem_pthread.dylib       	       0x197a220fc thread_start + 8

Thread 4:: io.flutter.io
0   libsystem_kernel.dylib        	       0x1979e5e34 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1979f85d0 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1979ee9d8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x1979e617c mach_msg + 24
4   CoreFoundation                	       0x197b0dedc __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x197b0c73c __CFRunLoopRun + 1212
6   CoreFoundation                	       0x197b0bbc4 CFRunLoopRunSpecific + 588
7   FlutterMacOS                  	       0x10526068c 0x1051e0000 + 525964
8   FlutterMacOS                  	       0x1052577d0 0x1051e0000 + 489424
9   FlutterMacOS                  	       0x10525f2a8 0x1051e0000 + 520872
10  FlutterMacOS                  	       0x10525ed60 0x1051e0000 + 519520
11  libsystem_pthread.dylib       	       0x197a272e4 _pthread_start + 136
12  libsystem_pthread.dylib       	       0x197a220fc thread_start + 8

......

**Comment by rustdesk** [comment]
Please answer this https://github.com/rustdesk/rustdesk/discussions/7766#discussioncomment-11435150

**Comment by rustdesk** [comment]
How about unlock this?

![image](https://github.com/user-attachments/assets/e0a02d23-cc80-42d1-add0-a5dc0d51a766)

**Comment by rustdesk** [comment]
How about restart rustdesk or restart os?

**Comment by Accademia** [comment]
https://github.com/user-attachments/assets/c6e5ceaa-7fbd-42f0-854a-0817ccf1e95d

Sir. This issue has been present on my computer for quite some time (at least three months). I did not report it earlier because I found that completely uninstalling the program (using CleanMyMac) and reinstalling it would resolve the bug. This meant that the bug would not occur during the initial configuration after reinstallation.

However, I’ve now discovered that even after completely uninstalling the program with CleanMyMac and reinstalling it, the bug still occurs immediately, preventing the initial configuration from completing.

I’ve tried various methods to resolve this issue, all of which have failed, including:
	•	Using a version of the program from three months ago.
	•	Restarting the computer.
	•	Fully uninstalling the program, restarting the computer, and then reinstalling it.

Despite these efforts, the bug persists. Interestingly, I’ve noticed the same issue on my Windows 11 laptop, but on that machine, uninstalling and reinstalling the program does allow the configuration process to complete.

I suspect the issue might be related to RustDesk’s multilingual support. Although the recording you’re viewing is in English, my Windows 11 and macOS systems are usually set to Chinese. When using the program in English mode, there’s a small chance the bug does not occur, whereas in Chinese mode, the bug consistently appears.

Could the problem be tied to language settings?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/7766

**Comment by Accademia** [comment]
> #7766

Thanks.

**Comment by rustdesk** [comment]
Could you try out the new https://github.com/rustdesk/rustdesk/releases/nightly?
