### ISSUE TITLE
Using proxy server is not ready

### ISSUE THREAD

**Issue by Rocky-Jinxing** [rustdesk/rustdesk#10164]
### Bug Description

I can't use a proxy server. My proxy server software is CCProxy, and connecting to the proxy server in my browser is normal. But after setting up Rustdesk, it can't be ready.
![image](https://github.com/user-attachments/assets/8a4a612e-ebc4-4031-9b6e-704b6f3bdae9)
![image](https://github.com/user-attachments/assets/9d4b305c-ffb9-4176-bdf7-eef8b4718e19)

### How to Reproduce

![image](https://github.com/user-attachments/assets/11b86197-af00-4074-9938-4d1a2ea2d767)
The problem persists

### Expected Behavior

Using proxy server is not ready

### Operating system(s) on local (controlling) side and remote (controlled) side

 Windows11 -> Windows10

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.2   ->  1.3.2

### Screenshots

![image](https://github.com/user-attachments/assets/aa41c0bb-316d-4a1d-9a00-0739ab24c67b)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/6398
