### ISSUE TITLE
RustDesk VMWare Windows 10 VM Keyboard Input Issue

### ISSUE THREAD

**Issue by ctoox** [rustdesk/rustdesk#10172]
### Issue Description
I am experiencing a keyboard input issue when using RustDesk to remotely access a Windows 10 virtual machine (VM) hosted on VMware. The issue does not occur on the host machine or when using RustDesk with iOS and Android clients to remote Windows 11.

### Steps to Reproduce
1. Launch RustDesk on the host machine and connect to the Windows 10 VM via VMware.
2. Attempt to type any character, for example, '1'.
3. Observe that the character is repeated indefinitely, e.g., '1' becomes '1111111111...'.

### Actual Behavior
The keyboard input results in continuous character repetition, which is not present on the host machine or when using other client platforms.

### Environment
- Host OS: Windows 11
- VM OS: Windows 10
- VM Platform: VMware
- RustDesk Version: 1.3.3

### Additional Information
- The issue is specific to the Windows 10 VM running on VMware.
- The host machine does not exhibit this issue.
- Other client platforms (iOS and Android) do not show this behavior when connecting to the same Windows 11 host.

### Expected Behavior
The keyboard input should function correctly without any character repetition.

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows10 -> Android

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.3

### Screenshots

![image](https://github.com/user-attachments/assets/9f383fc7-42e5-45e5-bde1-b7da7637df3d)

**Comment by rustdesk** [comment]
Close as tracked by https://github.com/rustdesk/rustdesk/issues/4357

**Comment by ctoox** [comment]
old version  \ oray  \ todesk are not causing this problem.

**Comment by ctoox** [comment]
I saw there are a lot of Android apk updated, maybe there some API chain causing this problem.
I'll check the code lately, thx.

**Comment by ctoox** [comment]
https://github.com/user-attachments/assets/b7f5a8c6-c3f1-4a1d-81e0-a5ff08959d79

this is the bug reproduce video.
