### ISSUE TITLE
release the app on Google Play Store because couldn't enable input control through accessibility service without the app download from Google Play Store

### ISSUE THREAD

**Issue by rajarshikhatua100** [rustdesk/rustdesk#10195]
### Bug Description

couldn't enable accessibility services permission if the app is not downloaded from Play Store

### How to Reproduce

download and install app, try to grant accessibility services permission

### Expected Behavior

system should permit the app to enable accessibility services

### Operating system(s) on local (controlling) side and remote (controlled) side

Android 14 & 14+

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

letest 

### Screenshots

![Uploading Screenshot_20241205_154717_Settings.png…]()

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/5660
