### ISSUE TITLE
Non translated text - update info

### ISSUE THREAD

**Issue by BestiaPL** [rustdesk/rustdesk#10199]
### Bug Description

RustDesk checks the website for a newer version of the program, but the notification is only in English.

### How to Reproduce

Just run older version of EXE file (in Windows), I'm not using Linux or Mac.

### Expected Behavior

Status text should be translated into local language.

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows 10

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.4

### Screenshots

![obraz](https://github.com/user-attachments/assets/ba826a2c-26ab-4d5f-afe4-bfd7de6fec25)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/10198
