### ISSUE TITLE
Privacy mode not working in Linux (Manjaro KDE)

### ISSUE THREAD

**Issue by happyZYM** [rustdesk/rustdesk#10196]
### Bug Description

I turned on 'privacy mode' in the clients of both local and remote, but there is not effect. I also tried to use X11 instead of Wayland, but the screen of the remote machine (Manjaro KDE) is not disabled.

### How to Reproduce

Turn on 'privacy mode' in the client, and start the session.

### Expected Behavior

Privacy mode working on Linux (Manjaro KDE).

### Operating system(s) on local (controlling) side and remote (controlled) side

ios -> Manjaro KDE(Wayland)

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.1 -> 1.3.4

### Screenshots

![图片](https://github.com/user-attachments/assets/8aa07d57-dc32-42b3-9f49-e1d20e778afa)

**Comment by rustdesk** [comment]
Windows only
