### ISSUE TITLE
GUI issue - String untranslated

### ISSUE THREAD

**Issue by bovirus** [rustdesk/rustdesk#10198]
### Bug Description

@rustdesk 

there is a string untranslated

### How to Reproduce

Check foir a new version available

### Expected Behavior

String translated

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows 10 22 H2 64bit Pro Italian

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.4

### Screenshots

![image](https://github.com/user-attachments/assets/b8a70cf7-4f56-4607-a301-3a843c81f0f1)

**Comment by rustdesk** [comment]
Noted

**Comment by bovirus** [comment]
I propose to change the string to
"There is a new Rustdesk version available (v. x.x.x)."
Move version at the end.

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
> "There is a new Rustdesk version available (v. x.x.x)."

I do not know which one is more formal, @21pages please have an investigation of which one is more used by others.
