### ISSUE TITLE
Can not install on MacOS 12

### ISSUE THREAD

**Issue by fyeeme** [rustdesk/rustdesk#102]
“访达”不能完成该操作，因为不能读取或写入“RustDesk.app”中的某些数据。
（错误代码-36

**Comment by rustdesk** [comment]
Noted with thanks

**Comment by rustdesk** [comment]
What's your MacOS 12 minor version? X64 or Arm(M1)?

**Comment by rustdesk** [comment]
Please go to https://support.apple.com/en-us/HT202491

**Comment by fyeeme** [comment]
sorry for late. @rustdesk 
 Processor Name:	Dual-Core Intel Core i5

**Comment by fyeeme** [comment]
it worked now. and I'll close the issue myself.
![image](https://user-images.githubusercontent.com/6078758/123358083-61a95080-d59d-11eb-99f0-cf32b8ed03c6.png)
