### ISSUE TITLE
Settings UI - Weird scrolling behaviour

### ISSUE THREAD

**Issue by CB-Vista** [rustdesk/rustdesk#10201]
### Bug Description

Scrolling using mouse wheel in settings UI causes large jumps between sections.
See images, pay attention to scroll bar.
- first image is at top
- second image, one click of scroll wheel, has scrolled down a normal expected amount
- third image, second click of scroll wheel, has scrolled down to bottom - unexpected

Only using Windows so can't confirm other OS.
Similar weird behaviour when scrolling back up

### How to Reproduce

Open rustdesk UI
Open setting pane
scroll with mouse wheel

### Expected Behavior

UI should scroll down in consistent amounts

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows 11

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.3

### Screenshots

![Screenshot 2024-12-06 092528](https://github.com/user-attachments/assets/79eb3882-a976-44f9-a013-f4dc1cafc8ce)
![Screenshot 2024-12-06 092542](https://github.com/user-attachments/assets/5c681330-935f-4e71-9484-881527b1b4a6)
![Screenshot 2024-12-06 092547](https://github.com/user-attachments/assets/6a2cb425-b683-4c7e-9229-21fe12289aa0)

**Comment by rustdesk** [comment]
Fixed in 1.3.4
