### ISSUE TITLE
Rustdesk Windows suddenly unable to connect to relay server

### ISSUE THREAD

**Issue by Zaelnorth** [rustdesk/rustdesk#10212]
### Bug Description

I setup Relay server hbbr/hbbs running in Oracle Cloud in Docker Containers. Everything used to work just fine. Recently Rustdesk WIndowscannot access the relay anymore, wondering why that is, I checked the firewall, the ports are still open, other docker containers are having no problems. When I save the Relay and the key in desktop app, it says Successful, but then nothing happens.

Is there anyway to debug this?

### How to Reproduce

1. Add relay server (running in docker container) in OCI
2. Rustdesk Windows stopped being able to connect to it

### Expected Behavior

The windows app should be able to connect to relay

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows 11

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.4

### Screenshots

![image](https://github.com/user-attachments/assets/a9133963-47a3-47e5-8d46-c25681140187)

**Comment by rustdesk** [comment]
#763
