### ISSUE TITLE
Windows: The host's clipboard is cleared when the remote connection is closed.

### ISSUE THREAD

**Issue by hwf1324** [rustdesk/rustdesk#10220]
### Bug Description

The host's clipboard is cleared when the remote connection is closed.

### How to Reproduce

Close the remote connection

### Expected Behavior

Clipboard will not be emptied

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows 11 -> Windows 10

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.5 -> 1.3.5

### Screenshots

None

### Additional Context

Is this expected behavior?

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
Please test https://github.com/rustdesk/rustdesk/release/nightly, need to update on both sides.

**Comment by hwf1324** [comment]
> Please test https://github.com/rustdesk/rustdesk/releases/nightly, need to update on both sides.

Confirmed, issue fixed in nightly.

**Comment by rustdesk** [comment]
Please also test file copy&poast

**Comment by hwf1324** [comment]
> Please also test file copy&paste

Yes, copying/pasting files works fine.

BTW: Is the drag and drop functionality not currently implemented?

**Comment by fufesou** [comment]
> BTW: Is the drag and drop functionality not currently implemented?

Yes, not currently implemented.
