### ISSUE TITLE
Not Ready: Please Check Your Connection

### ISSUE THREAD

**Issue by ankurgupta555** [rustdesk/rustdesk#10222]
### Bug Description

From last few months we are not able to use Rust Desk. It is showing "Not Ready: Please Check Your Connection" message. 
We also tried to self host rust desk. and reinstalled it from the self hosted version in which configuration is prefilled but still seeing same message. Why rustdesk is not connectiing to the servers (Either self hosted one or the official one)

### How to Reproduce

Just installed rust desk.

### Expected Behavior

We should be able to see green "Ready" message. 

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows 11 and Ubuntu 20.04

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.5

### Screenshots

![image](https://github.com/user-attachments/assets/bf83780b-aa34-46f9-aea0-eb95b44f8748)

**Comment by rustdesk** [comment]
https://www.reddit.com/r/rustdesk/comments/1cr8kfv/should_you_selfhost_a_rustdesk_server/
