### ISSUE TITLE
Version 1.3.5 iOS plays no sound from remote windows PC anymore

### ISSUE THREAD

**Issue by danigl93** [rustdesk/rustdesk#10230]
### Bug Description

Hello,
the Version 1.3.5 don’t plays the music from a windows remote pc.

### How to Reproduce

Play music in a media player.
In version 1.3.1 for iOS everything worked.

### Expected Behavior

I hear the sounds from the remote pc.

### Operating system(s) on local (controlling) side and remote (controlled) side

iOS -> win11

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.5 -> 1.3.5

### Screenshots

-

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
Is the new testflight working for you?

**Comment by danigl93** [comment]
> Is the new testflight working for you?

Yes, with this fix I can hear the sounds on my iPhone. Thank you.
