### ISSUE TITLE
3/66 security vendors flagged the rustdesk1.3.5  as malicious

### ISSUE THREAD

**Issue by 812552787** [rustdesk/rustdesk#10247]
### Bug Description

3 security vendors（AhnLab-V3、BitDefenderFalx、Kaspersky） flagged the rustdesk-1.3.5-universal-signed.apk  as malicious
but the1.3.3 is not。

### How to Reproduce

3 security vendors（AhnLab-V3、BitDefenderFalx、Kaspersky） flagged the rustdesk-1.3.5-universal-signed.apk  as malicious
but the1.3.3 is not。

### Expected Behavior

3 security vendors（AhnLab-V3、BitDefenderFalx、Kaspersky） flagged the rustdesk-1.3.5-universal-signed.apk  as malicious
but the1.3.3 is not。

### Operating system(s) on local (controlling) side and remote (controlled) side

andorid

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.5

### Screenshots

![rustdesk 1 3 5 apk](https://github.com/user-attachments/assets/acf43ccf-6ac6-4783-af84-9592ab641673)

**Comment by rustdesk** [comment]
https://www.reddit.com/r/rustdesk/comments/1h81ei9/135_android_flagged_as_harmful_by_play_store/
