### ISSUE TITLE
Not Ready: Please Check Your Connection

### ISSUE THREAD

**Issue by redjumper** [rustdesk/rustdesk#10261]
### Bug Description

It was normal before last month, but now it shows “Not Ready: Please Check Your Connection”. I can't remember exactly when the problem started. I have tried completely uninstalling and reinstalling RustDesk, deleting C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk   C:\Users\abc\AppData\Local\rustdesk C:\Users\abc\AppData\Roaming\RustDesk, cleaning the registry, and testing various versions from 1.32 to 1.3.5, but the same issue persists. Other clients can not connect to this client, and it shows the error "the ID does not exist". Additionally, every time I reinstall, the same ID is generated. 
I feel it is more likely a system issue, but I don't know how to troubleshoot it. Btw, i have two monitors and  the system was updated to Windows 11 24H2 recently, and I'm not sure if this is related. However, my other Windows 11 24H2 client do not have this problem.

### How to Reproduce

install rustdesk

### Expected Behavior

We should be able to see green "Ready" message.

### Operating system(s) on local (controlling) side and remote (controlled) side

windows 11 24h2

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.5

### Screenshots

![image](https://github.com/user-attachments/assets/01048391-7c0f-4bf2-8bcf-2e1adff55f79)

> [2024-12-11 11:48:05.869206 +08:00] INFO [src\core_main.rs:140] main start args: ["--server"], env: Args { inner: ["C:\\Program Files\\RustDesk\\RustDesk.exe", "--server"] }
> [2024-12-11 11:48:05.871813 +08:00] INFO [src\core_main.rs:266] start --server with user SYSTEM
> [2024-12-11 11:48:05.877957 +08:00] INFO [src\ipc.rs:318] Started ipc server at path: \\.\pipe\RustDesk\query
> [2024-12-11 11:48:05.886791 +08:00] INFO [src\rendezvous_mediator.rs:384] start rendezvous mediator of rs-ny.rustdesk.com
> [2024-12-11 11:48:05.892003 +08:00] INFO [src\lan.rs:29] lan discovery listener started
> [2024-12-11 11:48:05.892253 +08:00] INFO [src\common.rs:498] Testing nat ...
> [2024-12-11 11:48:05.907832 +08:00] DEBUG [libs\hbb_common\src\udp.rs:35] Receive buf size of udp 0.0.0.0:0: Ok(65536)
> [2024-12-11 11:48:05.910223 +08:00] INFO [src\rendezvous_mediator.rs:594] register_pk of rs-ny due to key not confirmed
> [2024-12-11 11:48:06.495211 +08:00] DEBUG [src\common.rs:535] Got nat response from rs-ny.rustdesk.com:21116: port=6395
> [2024-12-11 11:48:07.136774 +08:00] DEBUG [src\common.rs:535] Got nat response from rs-ny.rustdesk.com:21115: port=30113
> [2024-12-11 11:48:07.136863 +08:00] INFO [src\common.rs:561] Tested nat type: SYMMETRIC in 1.2424798s
> [2024-12-11 11:48:07.514603 +08:00] INFO [libs\scrap\src\common\hwcodec.rs:518] set hwcodec config
> [2024-12-11 11:48:07.514624 +08:00] DEBUG [libs\scrap\src\common\hwcodec.rs:519] HwCodecConfig { signature: 16044161475578922, ram_encode: [CodecInfo { name: "hevc_qsv", mc_name: None, format: H265, priority: 0, hwdevice: AV_HWDEVICE_TYPE_NONE }, CodecInfo { name: "h264_qsv", mc_name: None, format: H264, priority: 0, hwdevice: AV_HWDEVICE_TYPE_NONE }], ram_decode: [CodecInfo { name: "h264", mc_name: None, format: H264, priority: 0, hwdevice: AV_HWDEVICE_TYPE_D3D11VA }, CodecInfo { name: "h264", mc_name: None, format: H264, priority: 3, hwdevice: AV_HWDEVICE_TYPE_NONE }, CodecInfo { name: "hevc", mc_name: None, format: H265, priority: 3, hwdevice: AV_HWDEVICE_TYPE_NONE }], vram_encode: [FeatureContext { driver: MFX, luid: 56021, api: API_DX11, data_format: H264 }, FeatureContext { driver: MFX, luid: 56021, api: API_DX11, data_format: H265 }, FeatureContext { driver: FFMPEG, luid: 56021, api: API_DX11, data_format: H264 }, FeatureContext { driver: FFMPEG, luid: 56021, api: API_DX11, data_format: H265 }], vram_decode: [DecodeContext { device: None, driver: AMF, luid: 52975, api: API_DX11, data_format: H264 }, DecodeContext { device: None, driver: MFX, luid: 56021, api: API_DX11, data_format: H265 }, DecodeContext { device: None, driver: MFX, luid: 56021, api: API_DX11, data_format: H264 }, DecodeContext { device: None, driver: FFMPEG, luid: 56021, api: API_DX11, data_format: H264 }, DecodeContext { device: None, driver: FFMPEG, luid: 52975, api: API_DX11, data_format: H264 }, DecodeContext { device: None, driver: FFMPEG, luid: 56021, api: API_DX11, data_format: H265 }] }
> [2024-12-11 11:48:07.920753 +08:00] INFO [libs\scrap\src\common\hwcodec.rs:733] Check hwcodec config, exit with: exit code: 0
> [2024-12-11 11:48:08.914871 +08:00] INFO [src\rendezvous_mediator.rs:594] register_pk of rs-ny due to key not confirmed
> [2024-12-11 11:48:14.921849 +08:00] INFO [src\rendezvous_mediator.rs:594] register_pk of rs-ny due to key not confirmed
> [2024-12-11 11:48:24.910653 +08:00] INFO [src\rendezvous_mediator.rs:594] register_pk of rs-ny due to key not confirmed
> [2024-12-11 11:48:36.919678 +08:00] INFO [src\rendezvous_mediator.rs:594] register_pk of rs-ny due to key not confirmed
> [2024-12-11 11:48:51.921453 +08:00] INFO [src\rendezvous_mediator.rs:594] register_pk of rs-ny due to key not confirmed
> [2024-12-11 11:49:10.916991 +08:00] DEBUG [libs\hbb_common\src\udp.rs:35] Receive buf size of udp 0.0.0.0:0: Ok(65536)
> [2024-12-11 11:49:10.917201 +08:00] INFO [src\rendezvous_mediator.rs:594] register_pk of rs-ny due to key not confirmed
> [2024-12-11 11:49:31.917947 +08:00] INFO [src\rendezvous_mediator.rs:594] register_pk of rs-ny due to key not confirmed
> [2024-12-11 11:49:56.927485 +08:00] INFO [src\rendezvous_mediator.rs:594] register_pk of rs-ny due to key not confirmed
> [2024-12-11 11:50:24.922804 +08:00] DEBUG [libs\hbb_common\src\udp.rs:35] Receive buf size of udp 0.0.0.0:0: Ok(65536)
> [2024-12-11 11:50:24.922902 +08:00] INFO [src\rendezvous_mediator.rs:594] register_pk of rs-ny due to key not confirmed
> [2024-12-11 11:50:55.918510 +08:00] INFO [src\rendezvous_mediator.rs:594] register_pk of rs-ny due to key not confirmed
> [2024-12-11 11:51:26.928146 +08:00] DEBUG [libs\hbb_common\src\udp.rs:35] Receive buf size of udp 0.0.0.0:0: Ok(65536)
> [2024-12-11 11:51:26.928515 +08:00] INFO [src\rendezvous_mediator.rs:594] register_pk of rs-ny due to key not confirmed
> [2024-12-11 11:51:56.916835 +08:00] INFO [src\rendezvous_mediator.rs:594] register_pk of rs-ny due to key not confirmed
> [2024-12-11 11:52:26.918314 +08:00] INFO [src\rendezvous_mediator.rs:594] register_pk of rs-ny due to key not confirmed
> [2024-12-11 11:52:57.917941 +08:00] DEBUG [libs\hbb_common\src\udp.rs:35] Receive buf size of udp 0.0.0.0:0: Ok(65536)
> [2024-12-11 11:52:57.918712 +08:00] INFO [src\rendezvous_mediator.rs:594] register_pk of rs-ny due to key not confirmed
> [2024-12-11 11:53:27.921859 +08:00] INFO [src\rendezvous_mediator.rs:594] register_pk of rs-ny due to key not confirmed
> [2024-12-11 11:53:32.101622 +08:00] INFO [src\ipc.rs:524] temporary-password updated

> [2024-12-11 11:48:05.836036 +08:00] INFO [src\core_main.rs:140] main start args: ["--service"], env: Args { inner: ["C:\\Program Files\\RustDesk\\RustDesk.exe", "--service"] }
> [2024-12-11 11:48:05.837738 +08:00] INFO [src\core_main.rs:262] start --service
> [2024-12-11 11:48:05.839822 +08:00] INFO [src\platform\windows.rs:543] session id 1
> [2024-12-11 11:48:05.845075 +08:00] INFO [src\ipc.rs:318] Started ipc_service server at path: \\.\pipe\RustDesk\query_service

**Comment by rustdesk** [comment]
https://www.reddit.com/r/rustdesk/comments/1cr8kfv/should_you_selfhost_a_rustdesk_server/
