### ISSUE TITLE
Windows to Mac, both just upgraded to 1.3.5, mouse & keyboard don't work

### ISSUE THREAD

**Issue by jrmain** [rustdesk/rustdesk#10286]
### Bug Description

Was working fine with RustDesk 1.1.9. Upgraded both to 1.3.5 and now, although I can see the display, I can't interact using mouse or keyboard.

Connection from RustDesk on the same Windows machine to a different Mac running RustDesk 1.1.9 still work fine, so the problem seems to be on the Mac running 1.3.5.

### How to Reproduce

1. Upgrade RustDesk 1.1.9 to 1.3.5 on macOS.
2. Connect from RustDesk 1.3.5 on Windows 8.1.
3. Remote display appears, but cannot interact using local mouse or keyboard.

### Expected Behavior

A connections from Windows to Mac using RustDesk 1.3.5 should allow interaction with the remote Mac using local keyboard and mouse.

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows 8.1 -> macOS

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.5 -> 1.3.5

### Screenshots

There's nothing really visible to show.

**Comment by rustdesk** [comment]
#763
