### ISSUE TITLE
Rustdesk 1.3.5 doesn't support Mac OS 12.2 ? 

### ISSUE THREAD

**Issue by jaywhj** [rustdesk/rustdesk#10299]
### Bug Description

Rustdesk 1.3.5 doesn't support Mac OS 12.2 ? 

The previous 1.3.2 did, how come it's gone? 

Coincidentally, my system version happens to be 12.2.1.

### How to Reproduce

when open the app, it says: The app requires macOS 12.3 or later.

### Expected Behavior

no

### Operating system(s) on local (controlling) side and remote (controlled) side

mac os 12.2

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.5

### Screenshots

no

**Comment by fufesou** [comment]
Is your system aarch64? x86_64 is not changed.

> how come it's gone

Since "screencapturekit" requires "macOS 12.3+", we changed the minimum system requirements.

https://developer.apple.com/documentation/screencapturekit/

**Comment by jaywhj** [comment]
@fufesou 

> Is your system aarch64? x86_64 is not changed.

Mac OS 12.2.1,  Apple M1.

Version 1.3.2 is fine, did you change the screencapturekit?

**Comment by fufesou** [comment]
> Version 1.3.2 is fine, did you change the screencapturekit?

The `screencapturekit` is newly introduced, it requires `macOS 12.3+`.

We did not do dynamic adaptation of the framework because it is rather troublesome.

**Comment by jaywhj** [comment]
Well, I'll see what I can do about upgrading the system.
