### ISSUE TITLE
RustDesk Client connects to Session 0 instead of 1 when user is logged in via Windows Remote Desktop (RDP)

### ISSUE THREAD

**Issue by domenicdistefano** [rustdesk/rustdesk#1029]
Like many other support / tech people I have multiple headless Windows boxes that can only be accessed via RDP. When I am connected to one of these boxes via RDP and I try to have a 3rd party remote control me using RustDesk they are connected to the locked console (session 0) instead of the active RDP session (session 1). 

You should be able to fix this issue since all other major similar software connects properly to session 1.

Thanks

**Comment by rustdesk** [comment]
how to figure out session 0 is locked?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/914#issuecomment-1173839858

**Comment by fufesou** [comment]
I've seen both two cases, the login picture and RDP session picture.
I'll try to find out the trigger.

**Comment by domenicdistefano** [comment]
Thank you!

**Comment by rustdesk** [comment]
close to favor https://github.com/rustdesk/rustdesk/issues/323
