### ISSUE TITLE
Rewrite Desktop UI with Flutter

### ISSUE THREAD

**Issue by open-trade** [rustdesk/rustdesk#103]
Unify mobile and desktop side with the same UI framework.

**Comment by aissat** [comment]
@open-trade  i can help u to dev flutter app

**Comment by rustdesk** [comment]
@aissat  Thanks, let me know if you need any help.

**Comment by rustdesk** [comment]
> app

Mobile side is ready.

**Comment by rustdesk** [comment]
Currently desktop side is Sciter. I chose Sciter because Flutter desktop is not mature last year.

**Comment by rustdesk** [comment]
Seems https://github.com/tauri-apps/tauri is also another choice if Flutter build too big.

**Comment by Aarstad** [comment]
> Currently desktop side is using Sciter. I chose Sciter because Flutter desktop was not mature last year.

Mind sharing why you have decided to move away from sciter? i looked into flutter, but seems like they produce executables of ~50mb ? wouldn't that massively increase bundle size of rustdesk?

Also regarding tauri, sciter apparently is building support for webview now. i believe tauri is just a webview wrapper as well.

**Comment by rustdesk** [comment]
> sciter

I do not trust Sciter any more.

**Comment by rustdesk** [comment]
> 50mb

Where do you get 50mb?

**Comment by Aarstad** [comment]
> > sciter
> 
> I do not trust Sciter any more. We have worked with Sciter for almost 2 years, it is painful. And it is time to switch to an open source solution.

Oh dear, not good. I recently started using sciter and have found it to be great actually. It's actually through sciter forums I initially found RustDesk.  Are there technical reasons you don't trust sciter, or are they political?

I honestly have no idea what the realistic alternative would be to using sciter. webview wrappers are a bit meh, wouldn't work well if webview2 isn't installed on windows, etc. basically a lot of control of your product is placed on what's installed on client, which probably get better eventually, but still a bit ways off.

regarding flutter 50mb is untested myself, i actually found it hard to see generated bundle size. considering they don't market desktop size being tiny heavily, i suppose it's nowhere near as light as sciter.

**Comment by Aarstad** [comment]
hmm, i looked through the ui, seems like you do a lot of TI script. i only tried sciter with js.

what i am currently doing is importing <script type="module" src="app.js"> in the main html, then i can do javascript style imports much like electron in the rest of the application.

ie 
```
import TheComponent from  './componentdir/somecomponent.js'
class App extends Element {
  render(props) {
    return <div>
      <TheComponent someprop={props.theprop}/>
   </div>
  }
}
```
and so on.

**Comment by rustdesk** [comment]
> started

you feel good because you just start. no political

**Comment by davidak** [comment]
@link2xt the topic is discussed in https://github.com/rustdesk/rustdesk/issues/900.

**Comment by Aarstad** [comment]
maybe vizia ? compiles to wasm. supports css. has elegant declarative api

https://github.com/vizia/vizia

**Comment by grummbeer** [comment]
Alea iacta est. decision was made, can be closed?

**Comment by buczek** [comment]
What _is_ the decision here? Apart from the license problem and the security problem of installing binaries, rustdesk+sciter crashes on our systems (scientific GNU/Linux, no distribution) e.g. when just run with an argument like `rustdesk foobar` and I can't analyze and fix the bug, because I don't have sources. SEGV happens in `libsciter-gtk.so`.

**Comment by eworm-de** [comment]
I would like to package Rustdesk for _Arch Linux_... But looks like it is a no-go because of `libsciter-gtk.so` for now.

Finally found this issue... So what _is_ the decision made here? Can we expect a release based on flutter any time soon?

**Comment by mon-jai** [comment]
@eworm-de The master branch is based on Flutter.

**Comment by davidak** [comment]
There is also a milestone https://github.com/rustdesk/rustdesk/milestone/1

I see forward to the next release that fixes this issue!
