### ISSUE TITLE
Disable Background Service / Autostart (Windows/Linux)

### ISSUE THREAD

**Issue by Cebrain** [rustdesk/rustdesk#1030]
Hi,
i found rustdesk and it works great.

I have one problem, this is the running background service which cant be killed or will be automatic started on system startup.
On Linux i disabled the server connection and closed rustdesk, still the service persists. Also starts on the startup again.
I really don't like this, that i never definitly know if something is running in the background.
I want to control what starts on my client and i want to enable such a thing first.

I couldnt find a way to disable the service on startup in the app and also dont find a way to close the app completely the app. (Linux)
On Windows i dont know if the app closes correctly every time. In my tests some times the app closes completly and sometimes it runs in the background.

Feature Request:
Create a Quit Application Button (To Close all background Services)
Create a Host Startup Toggle in the Rustdesk App. (Windows/Linux)

**Comment by rustdesk** [comment]
#912
