### ISSUE TITLE
Colossal gluttony RustDesk

### ISSUE THREAD

**Issue by Tamila-2017** [rustdesk/rustdesk#10315]
### Bug Description

When the server is running without an RustDesk connection to it, it consumes **68** watts.
But when I connect to the server via RustDesk, it starts to consume colossal power - over **200** watts, and the CPU load reaches **100**%.
It's not normal.
How can I fix this?

### How to Reproduce

Connect to computer

### Expected Behavior

The power should not increase when connected RustDesk

### Operating system(s) on local (controlling) side and remote (controlled) side

Debian 12

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.2.3

### Screenshots

![Power of RustDesk](https://github.com/user-attachments/assets/4f1cdb71-ef5c-4477-8f6e-95383c378e24)

**Comment by rustdesk** [comment]
1.3.5

**Comment by Tamila-2017** [comment]
Ok. Please tell me: night will this solve the problem with the colossal power?

**Comment by T-Shilov** [comment]
Developers, please tell me, have you fixed this annoying bug?

**Comment by T-Shilov** [comment]
Why doesn't anyone fix this malicious bug? It is impossible to use such a voracious product.
