### ISSUE TITLE
I want to prevent this dialog box from popping up on the controlled computer when connecting to it. What should I do?

### ISSUE THREAD

**Issue by hallejuyahaha** [rustdesk/rustdesk#10311]
### Bug Description

![15e9622c16f410214951cee6fbaa390](https://github.com/user-attachments/assets/3f55d2f9-7a36-4638-8b61-26a6521d8c42)

### How to Reproduce

This dialog box will pop up when I connect to the controlled computer for the first time.

### Expected Behavior

I hope that it will not pop up automatically when connected, but only wake up from the taskbar in the lower right corner when I need it. This allows me to focus more on my desktop work and obscures important parts of my work every time this dialog pops up.

### Operating system(s) on local (controlling) side and remote (controlled) side

windows10 or windows11

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.5

### Screenshots

![15e9622c16f410214951cee6fbaa390](https://github.com/user-attachments/assets/c0be6f3f-b4f0-4ace-8237-5b259db2a430)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/6008
