### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#1031]
Not planned yet before finishing https://github.com/rustdesk/rustdesk/discussions/918 
But PR and discussions about feasible implementation are welcome.

**Comment by gaetanolip** [comment]
Up for 2Fa or id White list.thx

**Comment by simeononsecurity** [comment]
Yeah, more specifically, we'd like the ability to lock the client to receive connections only from one relay or from one account. That plus enforcing 2fa on the accounts themselves is more advisable than 2fa on each machine. Managing the 2fa keys for each machine would be nice to have but honestly the inconvenience there out-ways the gains. 2FA is for non-repudiation, and should be implemented on an account level and not on a system level. It just doesn't make sense otherwise. @rustdesk

**Comment by TheScenePool** [comment]
It may be wise to use Google Authenticator project for ease of development.

**Comment by rustdesk** [comment]
https://github.com/tailscale/tailscale/issues/4728#issuecomment-1135149464

**Comment by rustdesk** [comment]
Including active directory

**Comment by rustdesk** [comment]
https://github.com/tailscale/tailscale + https://github.com/juanfont/headscale

**Comment by rustdesk** [comment]
> an account level

@simeononsecurity how do you think about TeamViewer's 2FA? https://community.teamviewer.com/English/kb/articles/108791-two-factor-authentication-for-connections

**Comment by v4dkou** [comment]
Consider testing TOTP with FreeOTP as an open-source alternative to Google Authenticator

**Comment by v4dkou** [comment]
Here's some library that implements the necessary algorithms in Rust https://github.com/TimDumol/rust-otp

There's an example of somebody using this library in production, although, they've had to jump hoops as the library seems to be unsupported and not published to crates.io
https://github.com/scpwiki/wikijump/pull/1048

**Comment by Dunkelicht** [comment]
While RustDesk is becoming very stable, please do consider supporting 2FA and FIDO. With those two we could put RustDesk into Enterprise situations.

Thank you for creating such good software!

**Comment by rustdesk** [comment]
@Dunkelicht Thanks, it is alreay under dev.

**Comment by deajan** [comment]
@Dunkelicht @rustdesk Using FIDO2/Webauthn since it has become the current security standard would make Rustdesk a really secure solution. Thanks.

**Comment by rustdesk** [comment]
> FIDO2/Webauthn

@Heap-Hop

**Comment by KarstenDE** [comment]
Is this done now? The issues are in loop referencing each other.
Thanks for clarification!
