### ISSUE TITLE
Audio stops on local pc when connecting to a client

### ISSUE THREAD

**Issue by katero01** [rustdesk/rustdesk#10329]
### Bug Description

When connecting to a remote client the audio on the local system stops working and no audio can be heard from either local or remote sounds. The sound doesn't work until reboot or after switching the audio device in the control panel on the local pc and then switch it back to the correct hdmi.

### How to Reproduce

use rustdesk to connect to a remote client while having any audio playing on the local pc

### Expected Behavior

audio continues to work when connecting to a remote connection and/or working again after disconnecting

### Operating system(s) on local (controlling) side and remote (controlled) side

Manjaro Linux KDE 6.2.4 kernel 6.11.11

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.35 -> 1.35

### Screenshots

https://github.com/user-attachments/assets/e4929380-4587-4c4a-8af8-2665c51dd30e

### Additional Context

I can recreated this on both of my PCs hardware is mostly the same and so is the OS

**Comment by katero01** [comment]
https://github.com/user-attachments/assets/5afe78f5-084d-4650-a105-29460327abd8

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/10197
