### ISSUE TITLE
Can only type lowercase letters when using android client to connect to KDE/Wayland session.

### ISSUE THREAD

**Issue by queenbiscuit311** [rustdesk/rustdesk#10328]
### Bug Description

When trying to use the android rustdesk client to connect to a KDE/Wayland session, it is not possible to type capital letters, numbers, punctuation marks, or special characters. Only lowercase letters work. This issue doesn't happen on X11, in other wayland sessions, or on windows or macos hosts. I thought that this might be due to KDE input permissions system, but KDE connect, which also uses it, doesn't have this problem.

### How to Reproduce

1. Install rustdesk on linux on a KDE/Wayland session
2. Try to connect to it using the android client
3. Try to type
4. You can only type lowercase letters, no other kinds of characters

### Expected Behavior

You can type any character on your phone's keyboard as when connecting to any other platform/desktop environment.

### Operating system(s) on local (controlling) side and remote (controlled) side

Android 14 --> Arch Linux x86_64

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.1.10-1 --> 1.3.5

### Screenshots

https://github.com/user-attachments/assets/9b5a3d0e-4f58-4fd6-a83a-33d5f8f977d9

### Additional Context

I've observed this problem for almost a year now but haven't reported it since I didn't need to use rustdesk often until recently.

**Comment by rustdesk** [comment]
@fufesou  low priority

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565 for low priority
