### ISSUE TITLE
Custom build for Windows is behind 3 versions

### ISSUE THREAD

**Issue by 1500DotCloud** [rustdesk/rustdesk#10321]
### Bug Description

When I create a custom build for Windows in the pro rustdesk console, despite the current version being 1.3.5, the final build version is 1.3.2

### How to Reproduce

Create a custom build for Windows in the pro rustdesk console

### Expected Behavior

Custom build installer v1.3.5

### Operating system(s) on local (controlling) side and remote (controlled) side

N/A

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

N/A

### Screenshots

![image](https://github.com/user-attachments/assets/1f7988ff-a300-4a47-a2dc-67c1c397c1d7)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server-pro/discussions/463
