### ISSUE TITLE
Can't build on Linux: expected item, found `..`

### ISSUE THREAD

**Issue by vlad20012** [rustdesk/rustdesk#10342]
### Bug Description

```
error: expected item, found `..`
 --> /home/vlad20012/.cargo/git/checkouts/x11-rs-e35f68bad83be40e/c2e9bfa/x11/src/internal.rs:1:1
  |
1 | ../../src/internal.rs
  | ^^ expected item
  |
  = note: for a full list of items that can appear in modules, see <https://doc.rust-lang.org/reference/items.html>
```

### How to Reproduce

clone, checkout `1.3.5`, run cargo check

### Expected Behavior

it should compile successfully

### Operating system(s) on local (controlling) side and remote (controlled) side

Linux -> Linux

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.5 -> 1.3.5

### Screenshots

![image](https://github.com/user-attachments/assets/09900320-da26-448d-ba37-edca61c21816)

**Comment by rustdesk** [comment]
#763
