### ISSUE TITLE
Remote Windows 7 second monitor screen stuck

### ISSUE THREAD

**Issue by luminouskk** [rustdesk/rustdesk#10358]
### Bug Description

When controlling a Windows 7 computer with dual monitors, it was found that the second monitor screen would get stuck when the content in the window changed (such as switching folders, opening new programs, etc.). Only after reconnection can the previous picture of the second monitor be displayed, and then it gets stuck again after the screen content changes. 

However, after getting stuck, all actions (dragging, clicking, inputting, etc.) can be transmitted to the second display, but the screen stops refreshing. And the main display was normal throughout.

### How to Reproduce

1. Install rustdesk 1.3.6 on a Windows 7 with dual monitors.
2. Use any clinet to remote control it and swich to the secondary monitor.
3. Screen stuck is easy to found.

### Expected Behavior

Fix the control for the second monitor on Windows7.

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows10 -> Windows7

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.6 -> 1.3.6-sciter

### Screenshots

Here is a screen record:

https://github.com/user-attachments/assets/f0f0c851-7995-415b-8bd0-39ad15378c60

### Additional Context

I tried to install a previous version (<1.1.9), but the problem still there. The GPU is R5 240 on this computer, while using the Rustdesk the encorder method is VP8/VP9 (no other choice). Therefore, Anydesk (4.3.0.0) runs properly with no such problem.

**Comment by rustdesk** [comment]
#763
