### ISSUE TITLE
Black Screen on Log In

### ISSUE THREAD

**Issue by UhlhornHH** [rustdesk/rustdesk#1035]
When I connect to a remote Mac, the remote computer's screen turns black, perhaps it switches off.

I expect to see the login screen of the remote computer.
And when I parallel log in via JumpDesktop, it works fine, because JumpDesktop activates the screen and RustDesk does not.

Download and drag into Applications.

1.1.9 for macOS, downloaded from web site.

Version 1.1.9

Both computers are equipped with dual screens

**Comment by rustdesk** [comment]
#981 dup
