### ISSUE TITLE
Keyboard loses reponse randomly when swtiching between two displays

### ISSUE THREAD

**Issue by ChunguangLiang** [rustdesk/rustdesk#10367]
### Bug Description

under ubuntu 24.04, with rustdesk I am using two monitors.
Keyboard loses reponse randomly when swtiching between two displays.

### How to Reproduce

it loses keyboard response randomly when switching mouse between these two monitors, I have to choose "Map mode" or "Translat emode beta" to activate the keyboard again when the bug happens. e.g. it happened, then I choosed translate mode beta to continue with work. after around 10 minutes, the keyboard losed connection again, then I had to choose Map mode to enable the keyboard again.... 

### Expected Behavior

with the rustdesk automatically reenable the keyboard in stead of our manual work.
many thanks for fixing the problem in advance.

### Operating system(s) on local (controlling) side and remote (controlled) side

Ubuntu 24.04

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.1->1.3.6

### Screenshots

I do not have any screenshot at this time moment

### Additional Context

thanks

**Comment by fufesou** [comment]
> it loses keyboard response randomly when switching mouse between these two monitors.

On the local side?

>  I have to choose "Map mode" or "Translat emode beta" to activate the keyboard again when the bug happens.

Gnome, X11?

**Comment by ChunguangLiang** [comment]
thanks for asking.  it is not wayland, I have disabled the wayland from gdm/custom.conf
it is a gnome under X11.

frequency: it loses keyboard connection (about 20%) by switching between two screens.

**Comment by rustdesk** [comment]
Please both side using 1.3.6

**Comment by ChunguangLiang** [comment]
> Please both side use 1.3.6

thanks. I just upgraded to 1.3.6 at both side, however, the problem remains. 
it did not occur each time when I moved mouse between two monitors.  however it happens still quite frequently...

**Comment by fufesou** [comment]
@ChunguangLiang Hello, is the issue occurred when performing the following operations?

https://github.com/user-attachments/assets/f712de7b-86d5-4193-97a6-32cb2a6deeb1

**Comment by ChunguangLiang** [comment]
> @ChunguangLiang Hello, is the issue occurred when performing the following operations?
> 
>  a.mp4

thanks.

yes very similar. 
in my home computer I also have two screens. 
each one using rustdesk connects to one monitor from my office.

in particular after I performed copy and paste, this problem appeared randomly. so that I have to  change a keyboard mode to reactivate keyboard response.

I just reinstalled the latest version of rustdesk server and will giva it a try in minutes. 
will report you soon.

many thanks again

**Comment by ChunguangLiang** [comment]
many thanks to fufesou and rustdesk.
it seems the problem is gone after installed the latest version rustdesk server.
at least it functions pretty well until now (10 mins' work). I will keep testing it.

-->
solution: upgrade to latest client 1.3.6 at both side and together with server to 1.1.12.
