### ISSUE TITLE
Android 9 X86 use rustdesk-1.3.6-x86-apk the image transfer exception

### ISSUE THREAD

**Issue by kuye1320** [rustdesk/rustdesk#10365]
### Bug Description

Simulating Android 9 with a virtual machine,After installing rustdesk 1.3.6 in android9, connect to Android 9 from PC desktop，the rustdesk  keep displaying: connected, waiting for screen transfer.

![Snipaste_2024-12-25_16-05-57](https://github.com/user-attachments/assets/1c99060a-4bbe-4193-b957-7ff6698ccb23)

### How to Reproduce

everytime

### Expected Behavior

Simulating Android 9 with a virtual machine,After installing rustdesk 1.3.6 in android9, connect to Android 9 from PC desktop，the rustdesk  keep displaying: connected, waiting for screen transfer.

### Operating system(s) on local (controlling) side and remote (controlled) side

Android 9 X 86

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.6

### Screenshots

![Snipaste_2024-12-25_16-05-57](https://github.com/user-attachments/assets/ca7192a4-5222-4d7e-ba90-80e577db46bc)

**Comment by rustdesk** [comment]
We wont fix x86
