### ISSUE TITLE
Rustdesk shows a white screen when I start it.

### ISSUE THREAD

**Issue by ntsilverwing** [rustdesk/rustdesk#10371]
### Bug Description

Main Control Rust Version: 1.3.6

Controlled Rust Version: 1.3.6

Controlled System: Windows 10 Professional, AMDR5 5600, GPU RX5600 OEM

After opening the main control, the Rust interface is white. I initially thought it was a bandwidth issue with the public server, so I set up a private server, but the same problem persists.

At the same time, when I open Potplay, the video screen cannot be displayed, but the video plays normally. 

When I click on the "Start" menu and select "All Apps," there is only a thumbnail-style menu, and the program groups cannot be displayed properly.

On another computer with Windows 11 + Intel + NVIDIA graphics card, I do not encounter these issues.

### How to Reproduce

1. Connected to the controlled endpoint successfully, but the Rust interface is a white screen.

2. Clicked on the Start menu - All Apps, but the program menu cannot be displayed properly.

### Expected Behavior

I hope the relevant content can be displayed properly.

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows10 -> Windows10

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.6 -> 1.3.6

### Screenshots

![white](https://github.com/user-attachments/assets/a80a42e9-5c8a-4fed-937d-6c56b3222f79)
![start menu](https://github.com/user-attachments/assets/92877212-eef8-457c-8543-27bf91d4eae4)
![potplay](https://github.com/user-attachments/assets/3d97e574-af33-4ff3-bae6-b4e3b8a41ace)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/10344
https://github.com/rustdesk/rustdesk/issues/6756
