### ISSUE TITLE
Cannot load libcuda.so1

### ISSUE THREAD

**Issue by tianqing108** [rustdesk/rustdesk#10382]
### Bug Description

it's happened on an arm architecture Linux computer without a discrete graphics card：
Cannot load libcuda.so.1
Cannot load libcuda.so.1
Try setting transparent
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(76)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed

### How to Reproduce

an arm architecture Linux computer without a discrete graphics card，version is rustdesk-1.3.6-aarch64.deb

### Expected Behavior

Cannot load libcuda.so.1
Cannot load libcuda.so.1
Try setting transparent
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(76)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed

### Operating system(s) on local (controlling) side and remote (controlled) side

aarch64 linux

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.6

### Screenshots

![image](https://github.com/user-attachments/assets/9d7825cc-d756-4bd9-b8df-2e9fa9a2e95f)

**Comment by rustdesk** [comment]
Search "GL_VERSION" on this repo, a lot of duplciates

**Comment by rustdesk** [comment]
> Search "GL_VERSION" on this repo, a lot of duplicates.
