### ISSUE TITLE
win10: remoter cannot see the UAC window if the other side useraccount has no system rights.

### ISSUE THREAD

**Issue by way1012** [rustdesk/rustdesk#104]
win10: remoter cannot see the UAC window if the other side useraccount has no system rights.

**Comment by rustdesk** [comment]
Thanks, but system right is required, we have no way to get round.

**Comment by marekjedrzejewski** [comment]
related: https://github.com/rustdesk/rustdesk/issues/70

**Comment by zazazouthecat** [comment]
First step you need to disable SecureDesktop on the remote host to see the uac screen (fix issue black screen or freezing screen)

Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "PromptOnSecureDesktop" -Value 0 -Force;

Maybe, see to deploy GPO  for 
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-gpsb/9ad50fd3-4d8d-4870-9f5b-978ce292b9d8


But after this, keyboard & mouse are locked anyway.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/2041
