### ISSUE TITLE
Blackscreen on connection to WayVNC Headless (Raspberry Pi OS 12/bookworm)

### ISSUE THREAD

**Issue by Zyzonix** [rustdesk/rustdesk#10406]
### Bug Description

First of all I am aware of the experimental support of Wayland for RustDesk, but that's why I'm reporting my issue here.

Earlier it was easily to use a Raspberry Pi headless with a running VNC server, back then with X11, and connect then via RustDesk. Since Raspberry Pi dropped the support of this easy configuration with X11 in Debian12/bookworm the headless use of a Raspberry Pi is more complicated/impossible. 

I searched a lot of forums to get a working solution but actually I failed. Then I discovered that the WayVNC server serves on port 5900 to which I can connect from Remmina (Kubuntu 24 LTS) using the VNC protocol. This connection is fast and reliable. As it is basically the same setup as in earlier versions of Raspberry Pi OS I then tried to install RustDesk which works. I can load the UI without any issues. I can connect to any other machine from this virtual session. 

But now to my issue: when trying to connect **to the virtual session** it works when there is an active VNC connection. Although it is a bit delayed it works. I can see the desktop, open applications etc. When I do the same without an active VNC connection in parallel RustDesk also connects, requests the password but then I get a blackscreen. No mouse-pointer nor anything. However when clicking in the left-upper corner the menu opens, I can see that when opening a VNC connection to the virtual display thereafter. This means to me that there is a working connection, because keyboard/mouse is transferred, it seems to be just a display bug? 

When leaving the RustDesk window open for a while the Desktop gets displayed but interaction has an immense delay. Maybe this helps to figure out the issue.

### How to Reproduce

- install Raspberry Pi OS 12 with Desktop (**64-bit**!)
- connect via SSH
- enter `raspi-config` > `Interface` > `VNC` > `enable`
- **leave all other settings concerning wayland as they are!**
- edit `/etc/wayvnc/config` > change `enable_auth` to `false`
- reboot
- test connection by connection with Remmina (VNC)
- reboot
- connect again with Remmina and install RustDesk (aarch64), set password for RustDesk
- connect also with RustDesk (Desktop should now be visible)
- reboot
- connect with RustDesk now, connection should be ok, but blackscreen
- click in the upper-left corner (where the taskbar is), try to click on the browser/konsole icons (although they are not visible)
- connect also with Remmina via VNC
- > as you should see there are open windows (browser or console or whatever you clicked on)

### Expected Behavior

Visible Desktop to use the virtual display hosted by WayVNC with RustDesk.

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows 10 > Raspberry Pi OS 12 64-bit / bookworm

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.6 > 1.3.6 

### Screenshots

Output of `journalctl -r -u rustdesk.service`:

> Dec 31 15:11:39 testpi rustdesk[4932]: flutter: CM hidden timer has been canceled
Dec 31 15:11:38 testpi rustdesk[4932]: flutter: Bring window 'null' on top
Dec 31 15:11:38 testpi rustdesk[4932]: flutter: Bring window 'null' on top
Dec 31 15:11:37 testpi rustdesk[4932]: flutter: registerEventHandler native_ui native_ui
Dec 31 15:11:37 testpi rustdesk[4932]: flutter: registerEventHandler language language
Dec 31 15:11:37 testpi rustdesk[4932]: flutter: registerEventHandler theme theme
Dec 31 15:11:37 testpi rustdesk[4932]: flutter: _globalFFI init end
Dec 31 15:11:37 testpi rustdesk[4932]: flutter: registerEventHandler load_lan_peers discovered peer
Dec 31 15:11:37 testpi rustdesk[4932]: flutter: registerEventHandler callback_query_onlines discovered peer
Dec 31 15:11:37 testpi rustdesk[4932]: flutter: registerEventHandler load_fav_peers fav peer
Dec 31 15:11:37 testpi rustdesk[4932]: flutter: registerEventHandler callback_query_onlines fav peer
Dec 31 15:11:37 testpi rustdesk[4932]: flutter: registerEventHandler load_recent_peers recent peer
Dec 31 15:11:37 testpi rustdesk[4932]: flutter: registerEventHandler callback_query_onlines recent peer
Dec 31 15:11:37 testpi rustdesk[4932]: flutter: registerEventHandler load_group_peers group peer
Dec 31 15:11:37 testpi rustdesk[4932]: flutter: registerEventHandler callback_query_onlines group peer
Dec 31 15:11:37 testpi rustdesk[4932]: flutter: registerEventHandler load_address_book_peers address book peer
Dec 31 15:11:37 testpi rustdesk[4932]: flutter: registerEventHandler callback_query_onlines address book peer
Dec 31 15:11:37 testpi rustdesk[4932]: flutter: _globalFFI init
Dec 31 15:11:37 testpi rustdesk[4932]: flutter: _appType:cm,info1-id:b9d2551407d84470a12aa13ae4919c5a,info2-name:Debian GNU/Linux,dir:/home/testuser/Documents
Dec 31 15:11:37 testpi rustdesk[4932]: flutter: initializing FFI cm
Dec 31 15:11:37 testpi rustdesk[4932]: flutter: --cm started
Dec 31 15:11:37 testpi rustdesk[4932]: flutter: launch args: [--cm]
Dec 31 15:11:37 testpi rustdesk[4932]: Try setting transparent
Dec 31 15:11:37 testpi rustdesk[4932]: atk_socket_embed: assertion 'plug_id != NULL' failed
Dec 31 15:11:37 testpi rustdesk[4831]: Error: Can't open display: (null)
Dec 31 15:11:36 testpi rustdesk[4932]: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Dec 31 15:11:34 testpi rustdesk[4875]: Cannot load libcuda.so.1
Dec 31 15:11:34 testpi rustdesk[4875]: Cannot load libcuda.so.1
Dec 31 15:11:34 testpi rustdesk[4849]: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Dec 31 15:11:34 testpi rustdesk[4831]: Error: Can't open display: (null)
Dec 31 15:11:34 testpi sudo[4836]: pam_unix(sudo:session): session opened for user testuser(uid=1000) by (uid=1000)
Dec 31 15:11:34 testpi sudo[4836]: testuser : PWD=/ ; USER=testuser ; ENV=XDG_RUNTIME_DIR=/run/user/1000 ; COMMAND=/usr/share/rustdesk/rustdesk --tray
Dec 31 15:11:34 testpi sudo[4830]: pam_unix(sudo:session): session opened for user testuser(uid=1000) by (uid=0)
Dec 31 15:11:34 testpi sudo[4830]:     root : PWD=/ ; USER=testuser ; ENV=XDG_RUNTIME_DIR=/run/user/1000 ; COMMAND=/usr/share/rustdesk/rustdesk --server
Dec 31 15:11:33 testpi rustdesk[2230]: flutter: model  closed
Dec 31 15:06:08 testpi rustdesk[2230]: flutter: Bring window 'null' on top
Dec 31 15:06:08 testpi rustdesk[2230]: flutter: Bring window 'null' on top
Dec 31 15:06:08 testpi rustdesk[2230]: flutter: Bring window 'null' on top
Dec 31 15:06:07 testpi rustdesk[2230]: flutter: registerEventHandler native_ui native_ui
Dec 31 15:06:07 testpi rustdesk[2230]: flutter: registerEventHandler language language
Dec 31 15:06:07 testpi rustdesk[2230]: flutter: registerEventHandler theme theme
Dec 31 15:06:07 testpi rustdesk[2230]: flutter: _globalFFI init end
Dec 31 15:06:07 testpi rustdesk[2230]: flutter: registerEventHandler load_lan_peers discovered peer
Dec 31 15:06:07 testpi rustdesk[2230]: flutter: registerEventHandler callback_query_onlines discovered peer
Dec 31 15:06:07 testpi rustdesk[2230]: flutter: registerEventHandler load_fav_peers fav peer
Dec 31 15:06:07 testpi rustdesk[2230]: flutter: registerEventHandler callback_query_onlines fav peer
Dec 31 15:06:07 testpi rustdesk[2230]: flutter: registerEventHandler load_recent_peers recent peer
Dec 31 15:06:07 testpi rustdesk[2230]: flutter: registerEventHandler callback_query_onlines recent peer
Dec 31 15:06:07 testpi rustdesk[2230]: flutter: registerEventHandler load_group_peers group peer
Dec 31 15:06:07 testpi rustdesk[2230]: flutter: registerEventHandler callback_query_onlines group peer
Dec 31 15:06:07 testpi rustdesk[2230]: flutter: registerEventHandler load_address_book_peers address book peer
Dec 31 15:06:07 testpi rustdesk[2230]: flutter: registerEventHandler callback_query_onlines address book peer
Dec 31 15:06:07 testpi rustdesk[2230]: flutter: _globalFFI init
Dec 31 15:06:07 testpi rustdesk[2230]: flutter: _appType:cm,info1-id:b9d2551407d84470a12aa13ae4919c5a,info2-name:Debian GNU/Linux,dir:/home/testuser/Documents
Dec 31 15:06:07 testpi rustdesk[2230]: flutter: initializing FFI cm
Dec 31 15:06:07 testpi rustdesk[2230]: flutter: --cm started
Dec 31 15:06:07 testpi rustdesk[2230]: flutter: launch args: [--cm]
Dec 31 15:06:07 testpi rustdesk[2230]: Try setting transparent
Dec 31 15:06:07 testpi rustdesk[932]: Error: Can't open display: (null)
Dec 31 15:06:06 testpi rustdesk[2230]: atk_socket_embed: assertion 'plug_id != NULL' failed
Dec 31 15:06:04 testpi rustdesk[2230]: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Dec 31 15:05:14 testpi sudo[979]: pam_unix(sudo:session): session closed for user testuser
Dec 31 15:05:14 testpi rustdesk[1020]: Cannot load libcuda.so.1
Dec 31 15:05:14 testpi rustdesk[987]: cannot open display: 
Dec 31 15:05:14 testpi rustdesk[1020]: Cannot load libcuda.so.1
Dec 31 15:05:13 testpi rustdesk[932]: Error: Can't open display: (null)
Dec 31 15:05:13 testpi sudo[979]: pam_unix(sudo:session): session opened for user testuser(uid=1000) by (uid=1000)
Dec 31 15:05:13 testpi sudo[979]: testuser : PWD=/ ; USER=testuser ; ENV=XDG_RUNTIME_DIR=/run/user/1000 ; COMMAND=/usr/share/rustdesk/rustdesk --tray
Dec 31 15:05:13 testpi sudo[899]: pam_unix(sudo:session): session opened for user testuser(uid=1000) by (uid=0)
Dec 31 15:05:13 testpi sudo[899]:     root : PWD=/ ; USER=testuser ; ENV=XDG_RUNTIME_DIR=/run/user/1000 ; COMMAND=/usr/share/rustdesk/rustdesk --server
Dec 31 15:05:10 testpi systemd[1]: Started rustdesk.service - RustDesk.

**Comment by rustdesk** [comment]
Tracked by https://github.com/rustdesk/rustdesk/issues/3565
