### ISSUE TITLE
Languages: Translation platform

### ISSUE THREAD

**Issue by tiagogaspar8** [rustdesk/rustdesk#1046]
Hi,

Can I ask for the creation of a translation platform? Something like Weblate? It would be great to have users without git knowledge to contribute.

Thanks.

**Comment by itamarjp** [comment]
the portuguese brazilian translation is very poor, I think M$ AI or google translator can translate better

**Comment by rustdesk** [comment]
> poor

It is a manual translation. :)

**Comment by tiagogaspar8** [comment]
Like, I have git knowledge, and I'd like to add Portuguese for Portugal, but adding a platform for it would be better.

**Comment by rustdesk** [comment]
Yes

**Comment by tiagogaspar8** [comment]
Were there any plans? Is there any way we can proceed with this?

**Comment by rustdesk** [comment]
I do not know weblate, but you just see it supports json. I can give you template.json, and you give me pt.json.

**Comment by tiagogaspar8** [comment]
Weblate would be deployed (probably) to rust.com server and would allow users to participate in the translation process easily and clearly with a web interface.
I can investigate how one would deploy and integrate weblate to rustdesk but I need some confirmation that you guys are on board with me to actually do it. 😄

**Comment by rustdesk** [comment]
no problem.

**Comment by rustdesk** [comment]
csv format please. I just write a csv <-> rs translator.

**Comment by rustdesk** [comment]
[ptbr.csv](https://github.com/rustdesk/rustdesk/files/9183327/ptbr.csv)

**Comment by rustdesk** [comment]
It is better to integrate to the github repo.

**Comment by WofWca** [comment]
Weblate is very well integrated with git, translations are automatically committed to a remote repo and all you have to do is merge them. I'd say it's a must-have.
And you don't actually need to self-host a Weblate server, they provide hosting for FOSS software https://hosted.weblate.org/hosting/

**Comment by bigretromike** [comment]
I did update for Polish translation not so long ago. Yes doing this via text editor is not the best, but to be honest Its better to have more features like address book thank easy to use 1-2-3-times-use platform for translation.

**Comment by Coool** [comment]
@yurtpage, what is the current progress? What still needs to be implemented?

**Comment by Coool** [comment]
@yurtpage, convert them to CSV as @rustdesk suggested in comment[^convert_comment] and then import them in your project. I can help you if you give me some more privileges on your project. 

[^comment1]: [Convert](https://github.com/rustdesk/rustdesk/issues/1046#issuecomment-1194360218) to CSV

**Comment by Coool** [comment]
@yurtpage, does Weblate have some automation built-in? Haven't looked at documentation. Or may somebody already opened issue on Weblate about *.rs file support.
