### ISSUE TITLE
App says generating ID but never generates ID or gives informative message

### ISSUE THREAD

**Issue by Corallus-Caninus** [rustdesk/rustdesk#1054]
**Describe the bug you encountered:**
App constantly says generating ID in I'd entry
...

**What did you expect to happen instead?**
A meaningful message or generated I'd eventually.
...

**How did you install `RustDesk`?**
Following the install instructions exactly for windows and Ubuntu respectively.

Newest listed for download.
---

**RustDesk version and environment**
Newest release.

Ubuntu and windows.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/314
