### ISSUE TITLE
iOS IPA file is not on the release page

### ISSUE THREAD

**Issue by iMonZ** [rustdesk/rustdesk#1057]
Hey, have you forgotten to put the iOS version on the release page? The .IPA file is missing there!

**Comment by rustdesk** [comment]
be patient.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3703#issuecomment-1474740035

**Comment by rustdesk** [comment]
How do you install the ipa file then?

**Comment by larryqiann** [comment]
I use AltStore and/or Signulous to do this. I'd love to have access to nightly builds of iOS

**Comment by rustdesk** [comment]
Sadly, you wont see it, we wont spend time on platform like AltStore or Signulous.

**Comment by larryqiann** [comment]
I wasn't necessarily saying you would have to publish it there, since this is something users would do by themselves. I am wondering if it would be possible to build it for iOS myself (not sure how well this is supported) locally, is this something that currently works properly?

**Comment by rakleed** [comment]
@rustdesk you can distribute the nightly version on iOS via TestFlight: https://developer.apple.com/testflight/
