### ISSUE TITLE
Unsupported display server x11 expected on chromebook install

### ISSUE THREAD

**Issue by coalabear371** [rustdesk/rustdesk#1064]
**Describe the bug you encountered:**

... I installed the app via the .deb package on a ChromeOS linux environment and receive this error when trying to connect to it and on the app itself in a pink box. I am unsure what can be done for this after researching a fair bit. Any support would be appreciated. Thanks

**How did you install `RustDesk`?**

--- Downloaded .deb file and installed using package manager

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/670

**Comment by rustdesk** [comment]
Closed for dup. Go to dup issue please.

**Comment by sam-ulrich1** [comment]
I'm not sure that these were the same. @coalabear371 Did the linked issue resolve for you? It appears that the linked issue has to do with running wayland vs x11 as compared to the weird ChomeOS linux (crostinin) X forwarding to the ChromeOS gui from a linux container.
