### ISSUE TITLE
Memory cannot be read

### ISSUE THREAD

**Issue by qiaoqia** [rustdesk/rustdesk#107]
![1624411909(1)](https://user-images.githubusercontent.com/37836325/123021174-29bbd500-d406-11eb-83f1-1cb81501a240.png)

**Comment by rustdesk** [comment]
More details please? e.g. WIndows update version, how and when does the error dialog pops up?

**Comment by rustdesk** [comment]
More details please? e.g. WIndows update version, how and when does the error dialog pops up?

**Comment by qiaoqia** [comment]
**The remote control is about two hours.
The controlled end shows that the memory cannot be read.
Windows10 version is 20H2**
![1624415001(1)](https://user-images.githubusercontent.com/37836325/123025735-a605e680-d40d-11eb-8da0-1169d1a5b991.png)


 **An error occurred while just connecting**

![2320c1cbf6fb7f22e524a870e9ade9b](https://user-images.githubusercontent.com/37836325/123025762-b1591200-d40d-11eb-9318-c83fcb8a417f.png)

**Comment by rustdesk** [comment]
Thanks a lot.

**Comment by rustdesk** [comment]
I will review all my unsafe code.

**Comment by qiaoqia** [comment]
Thanks a lot.

**Comment by rustdesk** [comment]
Similar issue found on Win7 profession Chinese version also.
![image](https://user-images.githubusercontent.com/71636191/123218963-ee510180-d4fe-11eb-9443-a77b50ad5ebe.png)
And also below installation error.
![image](https://user-images.githubusercontent.com/71636191/123219049-06c11c00-d4ff-11eb-98be-1ba0741b734c.png)

**Comment by rustdesk** [comment]
Can you reproduce this problem with latest version?
