### ISSUE TITLE
SSO/SAML

### ISSUE THREAD

**Issue by richard-gardner-ipintegration** [rustdesk/rustdesk#1070]
Firstly - great project! really awesome work!

Secondly one of the barriers to uptake is single sign on with google/apple/microsoft etc?

Could that be added to the roadmap?

**Comment by rustdesk** [comment]
selfhosted pro

**Comment by benedikt-bartscher** [comment]
@rustdesk what is selfhosted pro?

**Comment by IcedQuinn** [comment]
> @rustdesk what is selfhosted pro?

it means like many supposedly open source projects, some features will be gatekept out of the source code so they can sell it and appease the bean counters.
