### ISSUE TITLE
Linux client 2 pinkish copies of desktop (Linux on XCP-NG)

### ISSUE THREAD

**Issue by kennethnipper** [rustdesk/rustdesk#1073]
Sorry if this has been asked before but I haven't found anyone with the same issue.  I just installed this on 2 linux vms and a windows box.  When using either of these linux vms as a client I'm getting 2 pinkish copies of the desktop.  Is this a known bug or have I overlooked something?

![image](https://user-images.githubusercontent.com/41587561/181263239-b427b7b3-238d-4333-9935-3338c9cad5fe.png)

**Comment by rustdesk** [comment]
It should be bug, but seems not easy to reproduce.

**Comment by kennethnipper** [comment]
This happens when using windows to linux or linux to linux.  Windows to Windows works fine.  Here is a decent screenshot of the neofetch output from one of the linux machines, if that helps.

![image](https://user-images.githubusercontent.com/41587561/181269161-55d87720-dac6-46d4-af32-56a005291aca.png)

**Comment by rustdesk** [comment]
Thanks

**Comment by kennethnipper** [comment]
I tested this today with a Proxmox hosted Linux VM and it worked fine.  Looks like it's something specific to Linux on XCP-NG.

**Comment by rustdesk** [comment]
> Linux on XCP-NG.

Got it.

**Comment by Ceti76** [comment]
I have the same issue with Linux Mint in an VM (KVM/Qemu on OpenSUSE) and a Windows-Client.

**Comment by rustdesk** [comment]
#3565
