### ISSUE TITLE
Connection error - Dropped by the peer

### ISSUE THREAD

**Issue by YarnikeyZ** [rustdesk/rustdesk#1075]
# Connection error - Dropped by the peer
**Describe the bug you encountered:**

_When I try to connect to my Linux-machine on Debian 11 from my Xiaomi Redmi 7A after confirmation on the PC, a window appears with the inscription "Connection error / Dropped by the peer" and the password is requested again, if you enter a password, the window appears, closes, appears and eventually the application hangs with all my android._
![screenshot](https://user-images.githubusercontent.com/83335375/181283331-f59f7f36-18d2-4159-b1b1-aca7997c4eff.png)

---

**What did you expect to happen instead?**

_Connection._

---

**How did you install `RustDesk`?**

**PC** - `sudo apt install ./###.deb` _from GitHub_
**Phone** - `opened ###.apk` _from GitHub_

---

**RustDesk version and environment**

**PC** - `1.1.9` _(XFCE)_
**Phone** - `1.1.10-1` _(MIUI Global 12.5.2 (i think so))_

**Comment by rustdesk** [comment]
How about connect from a PC?

**Comment by YarnikeyZ** [comment]
> How about connect from a PC?

It's normal and works/looks nice

**Comment by rustdesk** [comment]
How about connect from PC to PC?

**Comment by rustdesk** [comment]
try out nightly build please.

**Comment by YarnikeyZ** [comment]
I tried it and it's a different issue now!
I can't run it anymore at all.
![image](https://user-images.githubusercontent.com/83335375/203616018-9703c20a-96e3-40d5-9505-526b07fd9d0b.png)
For installation i (obviously) have used the deb package

**Comment by rustdesk** [comment]
try out new nightly build.
