### ISSUE TITLE
Arrow keys on local result in wrong keycode being sent to remote

### ISSUE THREAD

**Issue by Nuno69** [rustdesk/rustdesk#1077]
**Describe the bug you encountered:**
Description: Whenever I press the up, down, left or right arrow key, the numpad keys are sent to the remote computer instead. I have tested this on a Windows local client, Windows remote client, Mac local client, Windowsremote client, iOS local client, Windows remote client, iOS local client, Windows remote client with and without the hardware keyboard. Allthese situations resulted in sending the numpad keys instead of the true arrow keys.
...

**What did you expect to happen instead?**
Expected behavior: Of course, I would want the arrow keys to behave as arrow keys, and not as numpad keys which are totally different
...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/851

**Comment by rustdesk** [comment]
remote side is what?

**Comment by asur4s** [comment]
There is an issue with numpad sync in legacy mode, merge #964 will [fix](https://github.com/rustdesk/rustdesk/pull/964/commits/1caee4e30678ba6d784689920ecd83ed2af3293a) that.

**Comment by asur4s** [comment]
#495

**Comment by rustdesk** [comment]
closed because of duplication.

**Comment by rustdesk** [comment]
Interesting, I can not reproduce on my side.

**Comment by asur4s** [comment]
Linux -> Windows
