### ISSUE TITLE
Can not transfer file from remote(Android) to local(Windows10)

### ISSUE THREAD

**Issue by tangxianzu-ming** [rustdesk/rustdesk#1080]
**Describe the bug you encountered:**
local file(Win10) can transfer to remote(Android) when press ">" button, but remote file (Android) can not transfer to local(Win10) when press "<" button.
...

**What did you expect to happen instead?**
remote file(Android) can transfer to local(Win10)
...

**How did you install `RustDesk`?**
download exe and apk file from https://rustdesk.com/zh
...

**RustDesk version and environment**
RustDesk version
local(Windows):1.1.9
remote(Android):1.1.10-1

Environment
local(Windows): win 10
remote(Android): pico g2 4k VR headset, Android 8
...

![2022728-93007](https://user-images.githubusercontent.com/11407632/181411027-f22273e8-69d0-4ea5-a967-b09a42118777.jpg)

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by rustdesk** [comment]
@Kingtous android is 1.1.10 version, windows is 1.1.9, seems that PR has compatibility issue.

**Comment by JumperCzech** [comment]
both windows>android and android>windows dont work for me 
same rustdesk versions, android 11 MIUI 13

(using the android app)
android to windows gets stuck at 0%, windows to android says the file was successfully transferred but no file is present
