### ISSUE TITLE
win7 no sound

### ISSUE THREAD

**Issue by dongjian** [rustdesk/rustdesk#1086]
**Describe the bug you encountered:**
在win7上运行无法传输声音(win10测试ok)
...

**What did you expect to happen instead?**
远程控制win7 设备时可以听见播放的声音(像win10一样)
...

**How did you install `RustDesk`?**

rustdesk-1.1.9-x32.exe
---

**RustDesk version and environment**
rustdesk-1.1.9-x32.exe , win7 32/64

**Comment by sirtemporary** [comment]
For me, when other os connect to win7 computer, the sound is not sent/played on the other os.  But when win7 connect to other os, it does receive/play the remote machine's sound.

**Comment by AnatolMV** [comment]
When controlling a remote computer with Windows 7 installed, no sound is played. AnyDesk plays.

**Comment by Yorunetsu** [comment]
Win 7 local, Win 8.1 remote, Rustdesk version 1.1.9 x64: no sound coming from the remote side.

**Comment by airblast-dev** [comment]
I am also facing the same issue :(

**Comment by rustdesk** [comment]
closr to favor 1189

**Comment by Telestractor19254** [comment]
I have three computers with Windows(7/11) and one with Ubuntu(20.04), but only one of them sends sound to others(laptop-omen16/win11). I'm pretty sure RustDesk has captured the sound, but I just couldn't hear it.
![Uploading 屏幕截图 2024-06-10 030949.png…]()
