### ISSUE TITLE
Why rustdesk runs in background

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [rustdesk/rustdesk#109]
I just started my pc and noticed this. I also have disabled it on startup

![signal-2021-06-23-170737.png](https://user-images.githubusercontent.com/73130443/123121575-cac18480-d434-11eb-957f-7aa3e4d1a208.png)

**Comment by rustdesk** [comment]
Start up is the system tray only. The background service is required for waiting for incoming peer connection. You can see their CPU usage is 0. If you do not like, please uninstall RustDesk and run portable RustDesk executable directly.
