### ISSUE TITLE
[bug] You can choose your own id(?!?!?)

### ISSUE THREAD

**Issue by Bellisario** [rustdesk/rustdesk#1093]
**Describe the bug you encountered:**
Seems you can literally choose your own connection id, just by editing the RustDesk.toml file and using another id you choose.
(and this seems allow connection, too. Tried connecting web version with portable client on the same computer)

_How:_
- navigate to `C:\Users\yourUser\AppData\Roaming\RustDesk\config` (you need to already have used RustDesk in the past).
- open `RustDesk.toml`
- change your id (tried with a numeric id, 9 chars) (notice sometimes, for me just the first try, maybe someone have the same id, opening the application will not display the id you decided but a similar one, maybe someone have the same id.)

...

**What did you expect to happen instead?**
I expect application id's cannot be choose by users but auto-generated.
This could also, theoretically, make sure someone other takes your id and you're not able anymore to connect your PC, because the id is instead re-assigned to the first online device, and not your (so the password doesn't not work).

...

**How did you install `RustDesk`?**
GitHub release, Windows portable version

---

**RustDesk version and environment**
v1.1.9 on Windows 7.

**Comment by WofWca** [comment]
Does the new ID actually get accepted by the server?

**Comment by Bellisario** [comment]
> Does the new ID actually get accepted by the server? Because if you try changing it through the UI, it says "Not supported by the server".

Yes, as I wrote above, the new ID is accepted by the server modifying it through app stored data (_**note:** I edited the file manually, I didn't do any change through UI, see above for path and file_): I was able to connect with my custom id through the web version of RustDesk.

> Btw, Win 7 is discontinued and is not receiving any more security updates.

I know but this is not a problem of my machine (all the app works correctly and this can be also achieved also on a W10 or W11 machine, if someone wants to replicate may help debug for DEVs), this is actually a problem of the app, which doesn't encrypt/sign the file containing the id (allowing easily modifications) and maybe the server... who knows what can be achieved if the custom id is assigned to more than one computer!

**Comment by rustdesk** [comment]
No, you can only change to an id which is not occupied yet.

**Comment by Bellisario** [comment]
> No, you can only change to an id which is not occupied yet, we are not that stupid as you think, :). But your suggestion of encrypting id is good.

This was just my worry, anyway, this means I can take an ID of a client which is offline and make my own? I would like to understand more... :face_with_spiral_eyes: 

Anyway, happy this idea is liked! :wink:

**Comment by rustdesk** [comment]
occupied both for offline and online.
