### ISSUE TITLE
UX: it's not clear how to disable remote access to local machine

### ISSUE THREAD

**Issue by WofWca** [rustdesk/rustdesk#1094]
I guess you can uncheck "Enable service" (right?), but it's not clear.
In TeamViewer there is this: 
![image](https://user-images.githubusercontent.com/39462442/181596768-f83c7f55-4d97-4c16-937b-1f5000cf1112.png)
But I think it would be better if this was in plain sign, in case you only want to connect to other machines yourself.

**Comment by rustdesk** [comment]
Added into https://github.com/rustdesk/rustdesk/discussions/918

**Comment by pixeldoc2000** [comment]
Looks like the Config Setting `access-mode=deny` never made it into release code? https://github.com/rustdesk/rustdesk/pull/1736/commits/688519320e63eb8ce3bd40fede2217644f7392b1

Maybe it has been has been cut in favor of providing this Option with self-hosted or pro version / paid feature? **I think for privat use / security this is very bad.** I would like to see remote access disabled or at lest give the user a clear option to disabled remote access (by default).

From a business standpoint I can "understand" the decision.
