### ISSUE TITLE
不好意思 找不到就win10测试2021年2月22日 15:22，RustDesk Help <info@rustdesk.com>写道：好的 我更新win10看看2021年2月21日 14:06，mingpcer <notifications@github.com>写道：

### ISSUE THREAD

**Issue by mingpcer** [rustdesk/rustdesk#11]
作者你好，谢谢回复，我用另一台Win10 LTSC 1809安装，install过程无报错，完了在C:\Program Files没生成RustDesk.exe，只有开始菜单的快捷方式，很喜欢这软件，希望能修复，感谢！

不好意思 找不到就win10测试2021年2月22日 15:22，RustDesk Help <info@rustdesk.com>写道：好的 我更新win10看看2021年2月21日 14:06，mingpcer <notifications@github.com>写道：

一样的情况，RustDesk V1.1.1，Win10 2004版，没装杀软，系统自带安全中心。

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

_Originally posted by @rustdesk in https://github.com/rustdesk/rustdesk/issues/8#issuecomment-783201237_

**Comment by rustdesk** [comment]
这个应该是Program Files下创建文件夹失败，具体原因，我这里很难复现。你能否手动在Program Files下创建RustDesk目录，然后把程序复制过去，取名RustDesk.exe。然后重启一下RustDesk服务，或者重启。

**Comment by zhangbo8418** [comment]
这本身就是我自己放到Program Files目录下的，服务也是我添加的，它自己根本就不能安装。。。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月17日(星期三) 晚上8:56
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [rustdesk/rustdesk] 不好意思 找不到就win10测试2021年2月22日 15:22，RustDesk Help ***@***.***&gt;写道：好的 我更新win10看看2021年2月21日 14:06，mingpcer ***@***.***&gt;写道： (#11)

**Comment by rustdesk** [comment]
不好意思，手头找不到Win10 LTSC 1809测试
