### ISSUE TITLE
Rustdesk does not work properly

### ISSUE THREAD

**Issue by MC-DALIU** [rustdesk/rustdesk#1103]
![image](https://user-images.githubusercontent.com/104657722/181675296-04ca2fee-3778-46e6-a6c7-800d45e2a22e.png)

**Comment by rustdesk** [comment]
This is old issue on some Windows update or PC which we can not reproduce, https://github.com/rustdesk/rustdesk/issues/210
That's also why we are rewriting UI with Flutter.
