### ISSUE TITLE
Logging and Auditing Facilities

### ISSUE THREAD

**Issue by Coyote21** [rustdesk/rustdesk#1107]
Really need more logging to use for debugging and troubleshooting.
And also need the ability to audit connections for security.

**Comment by simeononsecurity** [comment]
Agreed. Even the self hosted relay option provides almost no logs.
We want to see verbose logs with connection information to include IPs, ID info, hostnames, user permissions, connection type, etc.

**Comment by adamency** [comment]
@rustdesk Please, when you close issues as completed, if you could at least link the PR/commits that add the feature in question. Cause your docs are still extremely scarce, there's nowhere a mention of logging in rustdesk in them. How does logging works ? Where is it located ?
