### ISSUE TITLE
It is suggested that the password is hidden by default. Some people don't know when using it for the first time. I suggest that the password be displayed by default and can be hidden manually.

### ISSUE THREAD

**Issue by smxlicx** [rustdesk/rustdesk#111]
For example, today, I sent rustdesk to a colleague on wechat, asked him to install rustdesk and cut a picture to me. As a result, I couldn't get the password. I still couldn't control him remotely for a long time,

I called him again and he found the code.

So I suggest that the password should be displayed directly, and only when you are proficient in it and need it, can you hide it,

It is mainly convenient for people who use rustdesk for the first time and remote for the first time,

I'm a computer administrator in my unit. When I talk to other colleagues, it's always hard to use it for the first time.

Thank you for the wonderful rustdesk

**Comment by ShivamJhaa** [comment]
I would like to fix this issue.

**Comment by rustdesk** [comment]
> I would like to fix this issue.

Thanks, but we should also care about who like it to be hidden.

**Comment by rustdesk** [comment]
I do not have a good idea to compromise.

**Comment by SmartManoj** [comment]
What's the need for a password from the perspective of an Anydesk user?

**Comment by SmartManoj** [comment]
> picture

We should share it as a link.
