### ISSUE TITLE
Ruskdesk doesn't work properly in Windows Server 2008

### ISSUE THREAD

**Issue by ceyhunn** [rustdesk/rustdesk#1111]
**Describe the bug you encountered:**
When I connect another computer, it gives me following error, seems like ruskdesk windows service doesn't work properly.
![ruskdesk_error](https://user-images.githubusercontent.com/5506156/181768887-4aecae3f-1201-4b3e-acea-e4ecf2db1c8c.jpeg)

**What did you expect to happen instead?**

**How did you install `RustDesk`?**
Github release.

**RustDesk version and environment**
[1.1.9](https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-x64.exe), Windows Server 2008.

**Comment by rustdesk** [comment]
I do not think we can support 2008.

**Comment by rustdesk** [comment]
As an example, winsock error 10022 means some process or program tried an "invalid argument" to the Windows network drivers - in fact this error number can be a kind of catch-all error. Many other winsock errors are possible when dealing with firewall and security software blocking network access.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/689

**Comment by ceyhunn** [comment]
> As an example, winsock error 10022 means some process or program tried an "invalid argument" to the Windows network drivers - in fact this error number can be a kind of catch-all error. Many other winsock errors are possible when dealing with firewall and security software blocking network access.

Thank you for detailed information. I will look into it.
