### ISSUE TITLE
win -> mac Exit when press any key

### ISSUE THREAD

**Issue by zhanghongxiao** [rustdesk/rustdesk#112]

**Comment by rustdesk** [comment]
RustDesk 1.1.6?
Your mac version?

**Comment by rustdesk** [comment]
We had this problem in 1.1.5, #43

**Comment by zhanghongxiao** [comment]
RustDesk 1.1.6

**Comment by rustdesk** [comment]
Could you give me the crash report?

**Comment by zhanghongxiao** [comment]
RustDesk 1.1.6   mac 11.4

**Comment by zhanghongxiao** [comment]
> Could you give me the crash report?

I couldn't find any crash reports

**Comment by rustdesk** [comment]
https://support.apple.com/zh-cn/guide/console/cnsl664be99a/mac

**Comment by rustdesk** [comment]
https://macreports.com/crash-reports-how-to-use-them-to-troubleshoot-why-your-mac-crashed/

**Comment by rustdesk** [comment]
"Configuration Permissions"?

![image](https://user-images.githubusercontent.com/71636191/123240187-ab992480-d512-11eb-84a7-3ddbf9de9b5f.png)

**Comment by zhanghongxiao** [comment]
sorry, i re install and working

**Comment by rustdesk** [comment]
Thanks anyway.
