### ISSUE TITLE
Add two  separate password fields: an optional "permanent" password and a randomly generated one-time access password field

### ISSUE THREAD

**Issue by pacman366** [rustdesk/rustdesk#1122]
Another nice to have security feature. Rather than having just one password field, I'd like to propose 2 password fields instead of just one. One that's a randomly generated one-time access password that changes after a set number of minutes (Ideally 30 by default), the other password field for an optional permanent password that can be set by the user for convent for quick regular remote access to a given host. 

This feature would complement the new network discovery feature pretty well.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/1036
