### ISSUE TITLE
Cannot install debian client package behind a proxy

### ISSUE THREAD

**Issue by ralfi** [rustdesk/rustdesk#1138]
**Describe the bug you encountered:**
dpkg -i rustdesk-1.1.9.deb tells me ...

`WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object a
t 0x7fbe5c1c7e50>: Failed to establish a new connection: [Errno 113] Keine Route zum Zielrechner')': /simple/pynput/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object a
t 0x7fbe5c1f01c0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pynput/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object a
t 0x7fbe5c1f05e0>: Failed to establish a new connection: [Errno 113] Keine Route zum Zielrechner')': /simple/pynput/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object a
t 0x7fbe5c1f0790>: Failed to establish a new connection: [Errno 113] Keine Route zum Zielrechner')': /simple/pynput/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object a
t 0x7fbe5c1f0940>: Failed to establish a new connection: [Errno 113] Keine Route zum Zielrechner')': /simple/pynput/
ERROR: Could not find a version that satisfies the requirement pynput (from versions: none)
ERROR: No matching distribution found for pynput

`
It seems to me my http/https proxy setting for python3-pip could not be recognized (https_proxy=http://IP:PORT)
Do i need a ending slash ("/") at my settings?
I am using Debian 11

**What did you expect to happen instead?**
Clean deb install

**How did you install `RustDesk`?**
Download deb from site

---

**RustDesk version and environment**

**Comment by rustdesk** [comment]
this is out of our control.

**Comment by ralfi** [comment]
Thanks, for quick reply, but how can i check this or which method do you use inside your deb package?

**Comment by rustdesk** [comment]
pynput

**Comment by ralfi** [comment]
Cool, install python3-pynput solves this behavior. Could be helpfull to add this package in the dependency list of this package. Thanks!

**Comment by rustdesk** [comment]
Many old version does not have python3-pynput, it solves your problem, will cause more problems for others.

**Comment by ralfi** [comment]
Okay... Thanks for explanation!
