### ISSUE TITLE
Remote connect with Kodi on, popup won't minimize

### ISSUE THREAD

**Issue by Lowrida** [rustdesk/rustdesk#1139]
**Describe the bug you encountered:**
When i connect to my Kodi machine (with Linux Mint xfce 20.3 and Kodi Matrix 19.4) the connection popup window won't minimize or hide behind Kodi. Probably because Kodi has no taskbar?

...

**What did you expect to happen instead?**
That when i click the minimize icon on the popup the window goed away Or when i click on a section of the Kodi screen it would hide behind Kodi.

...

**How did you install `RustDesk`?**
Downloaded via the website as deb package

---

**RustDesk version and environment**
Rustdesk Version 1.1.9
Linux XFCE 20.3
Kodi Matrix 19.4

**Comment by Lowrida** [comment]
After fiddling around for almost an hour, i rebooted the system and now all of a sudden it hides behind Kodi when i click one a section in Kodi. Minimize still does not work..  is  there a way to disable  that popup?

**Comment by rustdesk** [comment]
Thanks for your patience, but for sorry I can not give you advise because I have never used Kodi.

**Comment by rustdesk** [comment]
no

**Comment by rustdesk** [comment]
#3565
