### ISSUE TITLE
waiting for image, then connection reset by peer errors looping indefinitely

### ISSUE THREAD

**Issue by ll3N1GmAll** [rustdesk/rustdesk#1146]
**Describe the bug you encountered:**

I have this same issue detailed in https://github.com/rustdesk/rustdesk/issues/499; but am not using the docker container. Client connects, then hangs on "waiting for image" for a second, and then i get the "reset by peer" error. This just keeps looping indefinitely until i stop it. All other clients are working fine except this one. This is a linux client; but other linux clients work fine. This client is running PopOS. So, it's possible the GUI is having an issue with RustDesk.

**What did you expect to happen instead?**

The connection to establish properly and show the desktop

**How did you install `RustDesk`?**

installed github release 1.1.9 from the rustdesk website's download button

**RustDesk version and environment**

installed github release 1.1.9 from the rustdesk website's download button to a PopOS linux client. Using a self hosted server (not the docker container). All other windows and linux clients are working properly.

**Comment by sirtemporary** [comment]
Downloaded current Pop!_Os (22.04 LTS) from website, installed in VM.  Downloaded rustdesk-1.1.9.deb, attempt to install (failed with pulseaudio requirement).  re-packaged it according to https://github.com/rustdesk/rustdesk/issues/559 then re-tried the install, which worked.  Started it up, entered my id server and key, and successfully connected to the pop!_os client computer.  After that, I successfully used it to connect to a windows client.
So, it is possible to run on pop!_os.  I just did a default install, maybe you have some custom configuration?  I guess, I'd advise that you double-check everything, the id server and key, and make sure the server is reachable from the pop!_os computer (ping)

**Comment by rustdesk** [comment]
Thanks

**Comment by ll3N1GmAll** [comment]
RustDesk installed successfully for me in PopOS and I can connect to the client; but it fails to fully establish. Instead, it loops between the 2 "waiting for image", then "connection reset by peer" errors indefinitely.

**Comment by sirtemporary** [comment]
Could you please run the following commands in a terminal window and post the result:
lsb_release -a
dpkg -s rustdesk

**Comment by vyncusp** [comment]
Same issue, im using centos os and install itu without using docker.
Rustdesk working fine if the client is LAN problem only happen when i need to connect outside of LAN
![2022-08-05_16-19-03](https://user-images.githubusercontent.com/56208673/183046151-d8a158f2-8f6f-446d-85c4-494e88f1758b.jpg)
.

**Comment by vyncusp** [comment]
> Same issue, im using centos os and install itu without using docker. Rustdesk working fine if the client is LAN problem only happen when i need to connect outside of LAN ![2022-08-05_16-19-03](https://user-images.githubusercontent.com/56208673/183046151-d8a158f2-8f6f-446d-85c4-494e88f1758b.jpg) .

Problem solved when installed using ubuntu and docker. Thx you all
