### ISSUE TITLE
Cannot connect use rustdesk-server-demo

### ISSUE THREAD

**Issue by Zhanghailin1995** [rustdesk/rustdesk#115]
I tried use rustdesk-server-demo as a simple server，but Cannot establish a connection through the server. 
![image](https://user-images.githubusercontent.com/49049478/123367556-b7392980-d5ac-11eb-92c7-df26f21a8f50.png)

**Comment by rustdesk** [comment]
#48

**Comment by rustdesk** [comment]
and follow https://github.com/rustdesk/rustdesk-server/blob/master/id-relay-set.md

**Comment by rustdesk** [comment]
pay attention to firewall settings

**Comment by rustdesk** [comment]
and more tries

**Comment by rustdesk** [comment]
Maybe a video tutorial is needed, hope someone can help.

**Comment by EmPablo** [comment]
@Zhanghailin1995 I made a video, Wish it can help your issue here.
https://www.youtube.com/watch?v=2pdr5k7fEZA

**Comment by Zhanghailin1995** [comment]
> @Zhanghailin1995 I made a video, Wish it can help your issue here.
> https://www.youtube.com/watch?v=2pdr5k7fEZA

thanks you! I have successfully used rustdesk-server-demo as a simple Relay Server.I did not open the UDP port of the firewall when I used this service before. When I turn on the firewall, it works successfully.

**Comment by JiayongO-O** [comment]
> @Zhanghailin1995 I made a video, Wish it can help your issue here. https://www.youtube.com/watch?v=2pdr5k7fEZA

cannot open the video

**Comment by Ohlagrange** [comment]
> 

Can you make a tutorial, and post it on bilibili or zhihu?

**Comment by hackfinn99** [comment]
> @Zhanghailin1995 I made a video, Wish it can help your issue here. https://www.youtube.com/watch?v=2pdr5k7fEZA

why'd you delete the video? sadge, I needed it this time man :((
