### ISSUE TITLE
Native operation of keyboard and mouse for Android/IOS

### ISSUE THREAD

**Issue by LuncyBloont** [rustdesk/rustdesk#116]
I hope Rustdesk for Android could support the native operation of keyboard and mouse when the keyboard and mouse are connected. At present, when the Bluetooth keyboard and mouse are connected, the mouse operation (Drag or scroll ...) and key combination input can only be realized through the touch screen function, and the experience is not good.
Thank you for your hard work!

**Comment by rustdesk** [comment]
Noted with thanks. But not in high priority now. Too many big issues right now.
