### ISSUE TITLE
Debian Client - Ask for id/relay url during install

### ISSUE THREAD

**Issue by RudiOnTheAir** [rustdesk/rustdesk#1164]
Hi

As a feature request. 
I don't know if this will work for alle debian derivatives like Ubuntu, Mint and the many others .. 
While installing the .deb package a question window or readline in terminal (debconf) opens and asks for the id/proxy url.

Tnx 

Wolf

**Comment by rustdesk** [comment]
PR welcome

**Comment by bmcgonag** [comment]
One of the things they did was make an appimage, but I think it was sadly more trouble than they wanted...but it allowed me to install it, set my server and key info, then when I moved it to any other machine those values were already set, and it just assigned a new ID.  So i shared the appimage securely to a couple of my cousins, and I was able to jump on their machines to help them real quick without them having to do any changing of id/relay or key values.

The appImage is really great, so I hope they'll come back around to it, but it may be worth a shot for your purposes in the mean time.
