### ISSUE TITLE
Right ctrl button not working in combination with another key

### ISSUE THREAD

**Issue by Reikooters** [rustdesk/rustdesk#1166]
**Describe the bug you encountered:**
The right ctrl button is not working as expected when used in combination with another key. (tested using a regular US English keyboard)

For example, on Chrome browser, in regular use on the client computer (not through Rustdesk), pressing either left ctrl + P, or right ctrl + P, both pops up the window to Print the page.

On the remote computer in Rustdesk, only left ctrl + P works. Right ctrl + P is not working - instead, it only types the letter "p" (as if only P was pressed without ctrl).

The right ctrl button by itself is being detected correctly, e.g. in Windows Explorer, if I hold right ctrl and click and drag a file to make a copy, it works fine, just the same way it would with left ctrl. It is only when right ctrl is used in combination with another key (e.g. Right Ctrl+P), the combination doesn't work.

For some situations/key combinations (e.g. moving around and selecting in an Excel spreadsheet, using arrows, shift+arrows, ctrl+arrows) it's easier to use the right ctrl button to do this (with the left hand) and not need to take my right hand off the mouse - so while it is less common to use the right ctrl button, in some situations it's useful. So it would be nice to fix this. Right shift does work fine.

...

**What did you expect to happen instead?**
Pressing right ctrl + (some other key) in Rustdesk, the remote machine should work the same as it would on a regular machine, i.e. the action which should normally occur when pressing the combination should happen.

...

**How did you install `RustDesk`?**

Build from source (yesterday)

---

**RustDesk version and environment**

Client: Windows 10, Rustdesk built from source
Remote: Windows 7, Rustdesk 1.1.9 downloaded from website.

**Comment by rustdesk** [comment]
@asur4s

**Comment by rustdesk** [comment]
For track: https://github.com/rustdesk/rustdesk/issues/406

**Comment by asur4s** [comment]
I have reproduced the bug. Thanks for your feedback. Next I will try to fix this problem.

**Comment by KoalaBear84** [comment]
@asur4s Did you make a PR? As I cannot find it anywhere, only on your fork. But maybe I'm not searching for the right thing.

**Comment by asur4s** [comment]
Yes, you can try using nightly on both sides. This problem should be fixed in nightly

@KoalaBear84

**Comment by asur4s** [comment]
@Reikooters Can you try nightly on both sides?

**Comment by Reikooters** [comment]
Using the nightly build on my local machine was enough to make it work. I tried updating the remote machine too, but it seems Windows 7 is no longer supported (got an error along the lines of: "The procedure entry point SwDeviceCreate could not be located in the dynamic link library CFGMGR32.dll"). Anyway, this is good enough for me now. Thanks!

**Comment by KoalaBear84** [comment]
Yes, also here, the nightly works 👍
