### ISSUE TITLE
Remote machine taking keyboard input while RustDesk window not focused (foreground window) but mouse is inside it

### ISSUE THREAD

**Issue by Reikooters** [rustdesk/rustdesk#1178]
**Describe the bug you encountered:**
As per title, RustDesk is sending keyboard input to the remote machine when the window is not focused (i.e. not the foreground window) but the mouse cursor is inside of it.

Steps to reproduce:

1. On your screen, put RustDesk remote screen window on the right.
2. Have another application on the left, e.g. Notepad
3. Click on Notepad so it is the active window.
4. Hover mouse pointer onto the Rustdesk remote screen window, but Notepad still focused
5. Start typing. Input text is typed into BOTH Notepad and RustDesk remote machine

Could be a problem if e.g. typing messages in Skype to someone on local machine, and using arrows/delete key during conversation, and at the same time altering/deleting contents of a file which is open at the remote machine, or possibly deleting files/folders if Windows File Explorer was the active window at the remote side while typing.
...

**What did you expect to happen instead?**
Remote machine should not take Keyboard input while not the active window.

...

**How did you install `RustDesk`?**

Build from source 2 August 2022

---

**RustDesk version and environment**

Client: Windows 10, Rustdesk built from source
Remote: Windows 7, Rustdesk 1.1.9 downloaded from website.

**Comment by rustdesk** [comment]
Will be fixed together Flutter version, because flutter version does not use global listener.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/980
