### ISSUE TITLE
[1.1.9] Local Catalina user cannot control mouse properly when remote user connected 

### ISSUE THREAD

**Issue by bilogic** [rustdesk/rustdesk#1179]
**Describe the bug you encountered:**
When remote connects into a Mac Catalina and acquires keyboard+mouse access, the local user cannot control the mouse cursor properly. 

- cannot control mouse properly is defined as: local user can move the mouse from current position (A) to new position (B), however, within 1 second or 2, the mouse returns  to position A
- if the remote user unfocuses from Rust Desk, local user is now able to control the mouse properly

**What did you expect to happen instead?**
If the remote user is focused on their rust desk, but not moving the mouse, local user should be able to control their mouse properly
...

**How did you install `RustDesk`?**
DMG on catalina

---

**RustDesk version and environment**
1.1.9 MacOS Catalina

**Comment by rustdesk** [comment]
@asur4s should not only Mac has this problem. Can you help test on Windows also?

**Comment by bilogic** [comment]
@rustdesk I just tested from W10 to W10, no issue with local control of mouse, it appears to be Mac only.

**Comment by rustdesk** [comment]
Thanks

**Comment by bilogic** [comment]
@rustdesk want to add that I faced the same issue on some W10 and W11 systems. 

Do you know the cause? Is it a bug or fundamental design isssue? Thanks.

**Comment by poshest** [comment]
We got this yesterday. Local = Linux, Remote = Windows 7

**Comment by bilogic** [comment]
I think it happens across any mix of OS intermittently, question becomes, why is it intermittent?

**Comment by jackykwandesign** [comment]
we got this issue also, remote = local = win10

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3819#issuecomment-1535892616
