### ISSUE TITLE
DEB package should declare dependency on python3-dev

### ISSUE THREAD

**Issue by CoolSpot** [rustdesk/rustdesk#1185]
**Describe the bug you encountered:**
Attempt to install rustdesk-1.1.9.deb on a system without python3-dev would result in error:
```
evdev/input.c:10:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
```

After installing python3-dev, rustdesk still wouldn't install because of the following error:
```
Running setup.py bdist_wheel for evdev ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-otcgepu7/evdev/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp1d7kd4tepip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
```

Issuing
`sudo apt install python3-dev`
and then
`pip3 install wheel`
fixed both errors
...

**What did you expect to happen instead?**
Expected rustdesk to be installed successfully.
...

**How did you install `RustDesk`?**
Opened rustdesk-1.1.9.deb with GDebi GUI tool.

---

**RustDesk version and environment**
rustdesk v.1.1.9 on Linux Mint 19.3 Tricia

![image](https://user-images.githubusercontent.com/3990370/182972371-ae2decba-47c1-49f0-9d81-4aa7052cc8de.png)

**Comment by rustdesk** [comment]
we are removing pynput and python deps.
