### ISSUE TITLE
Cannot tick Privacy mode from Android to W10

### ISSUE THREAD

**Issue by bilogic** [rustdesk/rustdesk#1195]
**Describe the bug you encountered:**
Connecting from Android to W10, however, under Android settings `Privacy mode`, the checkbox does not get ticked after clicking on it, however W10 monitor turns off

Sidetrack: if I keep moving the mouse, the W10 monitor sometimes turns on and I get a glimpse of the desktop. Maybe a better way is to add an extra "screensaver" topmost window on the local machine, like Teamviewer.

...

**What did you expect to happen instead?**
The checkbox should be able to tick
...

**How did you install `RustDesk`?**
Android: from Playstore 1.1.10-1
W10: from GitHub 1.1.9

---

**RustDesk version and environment**
See above

**Comment by StudentWeis** [comment]
Me too.

**Comment by Rehtt** [comment]
Me too.

**Comment by ATBZ14** [comment]
Fully updated Samsung phone to Windows 11, no go. Same symptoms.

**Comment by rustdesk** [comment]
How about the nightly build?

**Comment by ATBZ14** [comment]
After updating both to nightly, the prompt now says unsupported. What causes this? I'm running a pretty normal windows 11 machine.

**Comment by rustdesk** [comment]
@fufesou

**Comment by ATBZ14** [comment]
The license is activated, but I have two monitors, I suppose that's the problem, but why is that a problem?

**Comment by fufesou** [comment]
> The license is activated, but I have two monitors, I suppose that's the problem, but why is that a problem?

1. RustDesk does not support multi-screen control for now.
2. It may cause crash to use the magnifier in multi-screen.
https://github.com/rustdesk/rustdesk/blob/7f006102b5a018575cc3fc1a9c0e458dbb8a8993/libs/scrap/src/dxgi/mag.rs#L131

**Comment by rustdesk** [comment]
@fufesou check if the other venders (using the same API) have the same issue? Most of office users have multiple monitors nowadays.

**Comment by ATBZ14** [comment]
As a point of potential interest, the magnifier application works for me, is the magnifier API unrelated to the application?

**Comment by fufesou** [comment]
> As a point of potential interest, the magnifier application works for me, is the magnifier API unrelated to the application?

I've captured the api by Api Monitor. The results are the same APIs.

I refer to webrtc for the use of magnifications APIs. It has methioned the APIs unsafe on multi-screen.

https://github.com/rustdesk/rustdesk/blob/7f006102b5a018575cc3fc1a9c0e458dbb8a8993/libs/scrap/src/dxgi/mag.rs#L1

https://github.com/shiguredo/libwebrtc/blob/754f26f7b7d75aa18a596115f399c6e9026efa81/modules/desktop_capture/win/screen_capturer_win_magnifier.cc#L213

I'll try to find why it crashes sometimes, but I cannot promise.

**Comment by rustdesk** [comment]
BTW， the supported message should include the reason since you already knew it exactly.

**Comment by fufesou** [comment]
> BTW， the `unsupported` message should include the reason since you already knew it almost exactly.

Yes, I'll improve the message.
