### ISSUE TITLE
warning: panic message is not a string literal

### ISSUE THREAD

**Issue by EmPablo** [rustdesk/rustdesk#120]
**Describe the bug you encountered:**

It's a warning during compiling after "cargo run" command:

`warning: panic message is not a string literal
   --> libs/rust-sciter/src/lib.rs:352:28`

**What did you expect to happen instead?**
`
Err(error) => panic!("{}", error),`

**How did you install `RustDesk`?**
Following the README info on github.com/rustdesk/rustdesk

---

**RustDesk version and environment**

Version: 1.1.6
Ubuntu 20.04

**Comment by rustdesk** [comment]
PR please.
