### ISSUE TITLE
最希望的是能支持ip6

### ISSUE THREAD

**Issue by bigben446** [rustdesk/rustdesk#1203]
最希望能支持ip6。日常使用远程，但是没有公网ip4，都需要官方服务器转发。但这不是长久之计，如果能支持ip6直连就太方便了，这是杀手级的应用

I hope to support IP6 most. Daily use of remote, but there is no public network IP4, all need to be forwarded by the official server. However, this is not a long-term solution. If you can support IP6 direct connection, it will be too convenient. This is a killer application

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/152
