### ISSUE TITLE
Hardcoding public key while building from source is not working

### ISSUE THREAD

**Issue by xrock569** [rustdesk/rustdesk#1217]
**Describe the bug you encountered:**
I've included the public key [ self hosted server's ] in config.rs & connection.tis  pub const RS_PUB_KEY: and const RS_PK fields respectively. It throws Key mismatch error. 
...

**What did you expect to happen instead?**
Expected to work with encrypted connection
...

**How did you install `RustDesk`?**

build from source both server and client
---

**RustDesk version and environment**
windows 1.1.9

**Comment by rustdesk** [comment]
#763

**Comment by zhangtaidong** [comment]
I got same issue!
