### ISSUE TITLE
How to override the language?

### ISSUE THREAD

**Issue by timothyparez** [rustdesk/rustdesk#123]
For some reason, probably based on my locale, the GUI does not match my own language.
I want to set the language to English. Where do I configure it? In the `.toml` files? What's the settings name?

**Comment by rustdesk** [comment]
Very sorry, currently there is no place to set it. I will add it soon. Are you using Windows?

**Comment by timothyparez** [comment]
Hi, I am using `Ubuntu 20.10`.

**Comment by rustdesk** [comment]
Then it is Sciter bug, I use it to detect language. Anyway, I will add manually changing language in next release.

**Comment by timothyparez** [comment]
Thank you!

**Comment by timothyparez** [comment]
Version 1.1.8 correctly follows the system language. Thank you.
