### ISSUE TITLE
Add icon for dark mode on macOS

### ISSUE THREAD

**Issue by manfuku** [rustdesk/rustdesk#1230]
<img width="297" alt="macOS tray icon on dark mode" src="https://user-images.githubusercontent.com/8419393/183669249-5d69b48f-fd39-4230-a22b-edecd3be0b33.png">
 
On dark mode, the icon is hard to see. I just found out after a couple of days that there was actually an icon for the RustDesk service on the menu bar.

**Comment by rustdesk** [comment]
@Kingtous
