### ISSUE TITLE
Win10，后台占用CPU20%

### ISSUE THREAD

**Issue by munpf** [rustdesk/rustdesk#124]
如题，一开始用的是压缩包版本，之后直接安装到了电脑上，然后每次开机就看见rustdesk的后台服务占用20%的CPU，而且一直降不下来，除非停止服务，这个是正常现象吗？

**Comment by rustdesk** [comment]
I guess you downloaded it 10 days ago. Please use the latest build.

**Comment by rustdesk** [comment]
dup #90
