### ISSUE TITLE
"Send Ctrl+Alt+Del" function

### ISSUE THREAD

**Issue by vavilov** [rustdesk/rustdesk#1244]
Some Windows machines working under strict Active Directory rules have "Secure Sign-In" lock screen where user has to press Ctrl+Alt+Del on lock screen to start working. 
TeamViewer and even UltraVNC have special button that send sends this keys.
Maybe Rustdesk have to get such function too? Otherwise there is no way to remotely unlock and start working on such machines :(

**Comment by SmartByteKam** [comment]
I press Alt+Ctrl+Del on my local machine, then press cancel, but whis combination still send on remote machine

**Comment by rustdesk** [comment]
goto `lightning` icon on the titlebar please.

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/108#issuecomment-866467860

**Comment by vavilov** [comment]
It's strange, i have installed Rustdesk to remote machine (service is running, no UAC tip on GUI, even i can click on UAC prompts),
but menu of lightning icon hasn't "Insert Ctrl+Alt+Del" choice. There is only "Insert Lock"
![image](https://user-images.githubusercontent.com/6057414/184195728-9fff3e94-164f-4b86-be8d-37269d179b24.png)

**Comment by SoftwareMagicIT** [comment]
@rustdesk i think as physical pressure you could implement control alt ins which then remotely send control alt del

**Comment by joe733** [comment]
@rustdesk also seems to discard input from [`xdotool`](https://github.com/jordansissel/xdotool) or `xvkbd`.

```console
~ 
$ xdotool search --onlyvisible --classname Navigator windowactivate --sync key F5
$ #works - refreshes page

~ 
$ xdotool search --onlyvisible --classname rustdesk windowactivate --sync key Control_L+Alt_L+Delete
$ #fails!
```

**Comment by TheShadowAngel** [comment]
@rustdesk, when can we expect the release for testing on Windows? 😊
Without Ctrl+Alt+Del, at the moment, it is not possible to log in to a remote PC or server that is locked 🤷‍♂

**Comment by SoftwareMagicIT** [comment]
You can download source code and compile yourself for testing.

**Comment by TheShadowAngel** [comment]
Thanks.
Can you add appveyor.yml for creating "nightly build"? 🤔

**Comment by bmcgonag** [comment]
I'm not following this thread very well. I can lock my windows machine, and still have the options of Insert CTRL + ALT + DEL from the lightning icon at the top of the rustdesk window.
![ctrl-alt-del-in-restdesk-windows](https://user-images.githubusercontent.com/7346620/196513496-2271d8c9-3eef-45c7-a4ef-cacdd79dae14.png)

**Comment by TheShadowAngel** [comment]
If you build from source - may be, but in official "Windows release 1.1.9 - from 2 may" have not yet.
@rustdesk, can you add online compiler to create "night build" for windows, if don't have release roadmap?

**Comment by TheShadowAngel** [comment]
Rustdesk 1.2.0 (night) windows x64
![Rustdesk_120](https://user-images.githubusercontent.com/41905618/198193768-f275b8f0-0410-47f6-9335-e60073b9286f.png)
Invisible options in lightning "Insert Ctrl+Alt+Del"
For debugging - PC is in domain.

**Comment by rustdesk** [comment]
It is only visalbe, when it is installed and run as system service

**Comment by TheShadowAngel** [comment]
I am install Rustdesk on remote side as system service, but "Ctrl+Alt+Del" does not visible.
At last night build Antivirus Dr.Web after install kill rustdesk.exe as virus suspicion.

**Comment by rustdesk** [comment]
> I am install Rustdesk on remote side as system service, but "Ctrl+Alt+Del" does not visible. At last night build Antivirus Dr.Web after install kill rustdesk.exe as virus suspicion.

@21pages please try installing windows nightly, and check if we can see "ctrl+alt+del" from remote side.

**Comment by 21pages** [comment]
It's visible if installed on remote side, both 1.1.9 and nightly. But you need to have keybord/mouse permission.

**Comment by dintra7** [comment]
![изображение](https://user-images.githubusercontent.com/9625956/207357320-4ccd019c-b09f-46f1-8e7a-b64b6a51e122.png)

**Comment by warnerbryce** [comment]
I can confirm, i have both Nightly version installed 1.2 on a Linux Client and a Windows Server under a domain. 
On the Windows Server i havec RustDesk as a service, it's running, 
Trying to connect, i am on the login screen, need to do a CTRL + ALT + SUPPR, nothing into the Lighting logo about that. 
the same as @dintra7

**Comment by fufesou** [comment]
@dintra7 @warnerbryce 
Hi, I cannot reproduce this problem. Please ensure your have installed the application and you have keyboard permission to the remote side.

https://github.com/rustdesk/rustdesk/blob/35f174fa5d1ab53aebbd3da8a5ff381d3c01cde0/flutter/lib/desktop/widgets/remote_menubar.dart#L589

![image](https://user-images.githubusercontent.com/13586388/207381639-d7f45d8d-6488-4ea1-92da-908ebd06a211.png)

**Comment by rustdesk** [comment]
https://stackoverflow.com/questions/4023586/correct-way-to-find-out-if-a-service-is-running-as-the-system-user

**Comment by rustdesk** [comment]
> installed 1.2

I just put a fix, please download and install the new nightly build several minutes later (controlled side).

**Comment by warnerbryce** [comment]
@dintra7 the new Windows Installer file gave me an error : 
Can't find desktop_drop_plugin.dll in my computer. 
The program can't finish to be installed...
It's on a Windows Server 2012 machine

**Comment by Kingtous** [comment]
> 

Could you please provide the steps to reproduce this issue?

I can't reproduce it by removing any dlls in appdata, and rename .exe to "rustdesk-1.2.0-install.exe" to start the installer.

**Comment by warnerbryce** [comment]
@Kingtous Install the Nightly Installer from two days in the past on a Windows host.
Remove it in Add/Remove Program. 
Try to install the Nightly Installer from yesterday, get this error. 

Go into AppData\Roaming, delete the folder RustDesk, go into AppData\Local, delete the folder RustDesk
Reinstall the nightly installer, it's okay.

**Comment by Kingtous** [comment]
> @Kingtous Install the Nightly Installer from two days in the past on a Windows host. Remove it in Add/Remove Program. Try to install the Nightly Installer from yesterday, get this error.
> 
> Go into AppData\Roaming, delete the folder RustDesk, go into AppData\Local, delete the folder RustDesk Reinstall the nightly installer, it's okay.

Could you please test the latest nightly build? I tried to reproduce by the steps you provide, and still cannot see the error. If the problem still exists, could you also provide a gif or video to describe your issue?  :)

**Comment by DexterHagler** [comment]
Sorry if this has been fixed already, but for those who still do not see the "ALT+CTRL+DEL" _(Yes I have OCD)_ under the Lightning Menu, the issue is probably as others, incl. _@21pages_ stated: 
You need to have **keybord/mouse permission** enabled on the Host side. After Installing Rustdesk,
click on the 3 dots next to the ID to open config menu and make sure **"Enable Keyboar/Mouse"** has a tick next to it (NOT a red strike-through) Hope this helps someone .

![RD](https://github.com/rustdesk/rustdesk/assets/151370794/22198f07-098a-4924-9da0-6da8f595a609)

**Comment by rcorsari** [comment]
> It is only visalbe, when it is installed and run as system service on remote side.

well, as comparison I can tell (just as example) AnyDesk run from .exe as Administrator , allows to send ctrl-alt-del

if I send this to a friend or to someone for support I just want him to run the file .exe I give him the link to download it, especially if , as example , I send this to someone that doesn't have the rights to install software on the given machine

but I may need to access the task manager and I want to shoot ctrl-alt-del

hope you may think about to enable this feature e.g. at least when running just the .exe as Administrator
