### ISSUE TITLE
Connect via domain name

### ISSUE THREAD

**Issue by initdc** [rustdesk/rustdesk#126]
I tried to connect to a remote desktop using a public IP and it worked.

I have also deployed DDNS service, can you add the function of connecting via domain name? 
So that users can get higher upload rate and better experience.

**Comment by rustdesk** [comment]
noted with thanks，but a small reminder, explosure to internet is not safe.

**Comment by rustdesk** [comment]
Marked as wontfix before I can be convinced by anyone.
