### ISSUE TITLE
Relay server in internal network

### ISSUE THREAD

**Issue by Mo8it** [rustdesk/rustdesk#1265]
**Describe the bug you encountered:**
Connecting to the relay server in an internal network does fail with the following example:

```
podman create network net
podman run -it --rm --name hbbr --network net -p 21117:21117 -p 21119:21119 -v /path/to/hbbr/volume:/root:Z docker.io/rustdesk/rustdesk-server:latest hbbr -k _
podman run -it --rm --name hbbs --network net -p 21115:21115 -p 21116:21116 -p 21116:21116/udp -p 21118:21118 -v /path/to/hbbs/volume:/root:Z docker.io/rustdesk/rustdesk-server:latest hbbs -k _ -r hbbr:21117
```

But it does work if I replace `hbbr:21117` with `my.domain.com:21117` or if I enter my ip instead of `my.domain.com`.

With "does not work" or "does not connect", I mean that I get "Failed to connect via relay server" when I try to connect to a device.

If you are not familiar with Podman, just replace the word `podman` with `docker`. It should be the same.

Can Rustdesk handle internal IPs? I did also try to start hbbr first, then I did get its IP in the `net` network. Then I did enter the IP instead of `hbbr` in `hbbr:21117`. It did not work :(

---

**What did you expect to happen instead?**
hbbs connects to hbbr.

---

**How did you install `RustDesk`?**
Podman with the latest image of Rustdesk on hub.docker.com

---

**RustDesk version and environment**
Latest Docker image.

---

**What I need to say**
Thanks for this great free open source software!

**Comment by rustdesk** [comment]
#763
