### ISSUE TITLE
Disconnects while playing any media (Raspberry Pi 4B as host)

### ISSUE THREAD

**Issue by DEM0Nreal** [rustdesk/rustdesk#1266]
**Describe the bug you encountered:**

Whenever I connect to my Raspberry Pi 4B with either my Windows machine or Android phone it works correctly until I play media like video or music. It happens while opening a video on YouTube as well as opening the video/music via VLC media player, then it disconnects and reconnects, but waits for an image, after a while it shows 1 current frame of Raspberry's desktop and disconnects again. It happens in a loop. 

**What did you expect to happen instead?**

To not disconnect.

**How did you install `RustDesk`?**

Raspberry Pi 4B - installed using recommended .deb file for Raspberry pi from assets.
Windows - 64bit version, ran without install though
Android - downloaded from Google Play Store.

**RustDesk version and environment**

RustDesk 1.1.9 (rustdesk-1.1.9-raspberry-armhf.deb)

**Comment by rustdesk** [comment]
no resource to test pi.
