### ISSUE TITLE
win -> ubuntu 'alt' key is always pressed

### ISSUE THREAD

**Issue by wuzh07** [rustdesk/rustdesk#127]
**Describe the bug you encountered:**

alt key is always pressed, then normal input is unavailable.
For example, when I pressed 'd', ubuntu showed the desktop.

**What did you expect to happen instead?**

normal input

**How did you install `RustDesk`?**

Github release

**RustDesk version and environment**

Local: 1.1.6, Win 10
Remote: Ubuntu 18.04

**Comment by rustdesk** [comment]
Noted with thanks.

**Comment by wuzh07** [comment]
Fresh connection in the first time is ok (like after the remote computer is reboot). But later reconnection will have this problem.

**Comment by rustdesk** [comment]
Noted

**Comment by rustdesk** [comment]
I am fixing this issue, seems you pressed "alt+tab" or some other "alt+...", you can press "alt" again to fix the problem as a wordraround.

**Comment by open-trade** [comment]
try out https://github.com/rustdesk/rustdesk/releases/download/1.1.8/rustdesk-1.1.8-windows_x64.zip
