### ISSUE TITLE
Have an always exposed dynamic password + always hidden static password

### ISSUE THREAD

**Issue by bilogic** [rustdesk/rustdesk#1274]
I think Teamviewer has better approach. 

1. The password at the main UI should be always dynamic, and thus can always be exposed, no need to be masked by default
2. The reason for it to be exposed is that user who need help are usually quite tech unsavvy, I ran into cases where the user is unable to read me the password, i.e. they don't understand they have to click the eye to get the password, thus creating additional overhead for support side
3. An additional static password can be set and is always hidden, once set, it cannot be revealed
4. A way to improve it further could be to change the dynamic password every X interval
5. There should also be a countdown timer so that the user can tell it is about to expire and can extend the countdown or reset it

Thank you.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/1036
https://github.com/rustdesk/rustdesk/issues/1122
https://github.com/rustdesk/rustdesk/issues/659
