### ISSUE TITLE
Administrative rights

### ISSUE THREAD

**Issue by bilogic** [rustdesk/rustdesk#1275]
I'm not sure how Teamviewer portable does it, but it is able to control programs that have admin privilege without going through UAC itself. I could be wrong, but that's something I remember and always wondered about.

Could RustDesk achieve the same, or prompt for the user to install everytime it starts? Thank you.

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/70

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/2974
