### ISSUE TITLE
ruskdek 1.1.9 deb for arm doesn't work in Raspberry Pi OS because library used is too new

### ISSUE THREAD

**Issue by cpcbegin** [rustdesk/rustdesk#1288]
If I try rustdesk from console I get this error:

```
rustdesk: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by rustdesk)
rustdesk: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.29' not found (required by rustdesk)
```

I download this package deb:
https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-raspberry-armhf.deb

I'm using a fresh and updated version of Raspberry pi OS in a Raspberry pi 400.

**Comment by rustdesk** [comment]
will work on flatpak in next release.

**Comment by grawsom** [comment]
When to expect ??
