### ISSUE TITLE
Dear author, is there any problem with the X86 version on July 18? 

### ISSUE THREAD

**Issue by youhers** [rustdesk/rustdesk#1289]
**Describe the bug you encountered:**

...Dear author, is there any problem with the X86 version on July 18? After installation, it always prompts that it is not installed.

**What did you expect to happen instead?**

...It should be the same as the previous version, and it should be installed on the computer normally.

**How did you install `RustDesk`?**

---The latest version downloaded from github

**RustDesk version and environment**

  1.1.9 July 18th version

**Comment by grummbeer** [comment]
@youhers can this be closed, or still exists in nightly version?
