### ISSUE TITLE
WOL

### ISSUE THREAD

**Issue by mkono87** [rustdesk/rustdesk#129]
Would love to see WOL capabilties as my systems never stay on 24/7.

Great work thus far!!

**Comment by rustdesk** [comment]
Noted with thanks

**Comment by JerryLiew** [comment]
You just need to send a very simple magic package.

**Comment by rustdesk** [comment]
> send

The problem is how you send from outside of intranet.

**Comment by JerryLiew** [comment]
I don't think WOL is a necessary capability. If it's in the LAN, WOL is very easy as there are so many ways/tools to do that, If it's in the WAN, it needs an extra running device in the LAN to broadcast magic packets.after all,WOL's full name is "Wake on lan".

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/844#discussioncomment-2999041
