### ISSUE TITLE
Mouse pointer not showing with web beta 

### ISSUE THREAD

**Issue by Infilz** [rustdesk/rustdesk#1295]
**Describe the bug you encountered:**

When i connect to my device with the web beta interface, i cannot see my mouse pointer.
It is active, i can clic on things by guessing where it is, but i can't see it.
All the options are active.

**What did you expect to happen instead?**
See the pointer

**How did you install `RustDesk`?**
Full install downloaded from official website on the client side.

**RustDesk version and environment**
1.1.9 on legit unactivated windows 10 64 bit, trying to access from chrome or firefox

**Comment by LJH1024** [comment]
你好，你是怎么搭建web网页版，可以了解一下吗
