### ISSUE TITLE
rustdesk.desktop doesnt appear in application launcher

### ISSUE THREAD

**Issue by jayfan0** [rustdesk/rustdesk#1299]
**Describe the bug you encountered:**
There is no entry for Rustdesk in my application launcher.
Running `kbuildsycoca5` shows this error: 
`kf.service.services: The action "new-window" in the desktop file "/usr/share/applications/rustdesk.desktop" has no Name or no Exec key`

...

**What did you expect to happen instead?**
Rustdesk to show in the application launcher automatically after install
...

**How did you install `RustDesk`?**
Github release - [rustdesk-1.1.9-suse.rpm](https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-suse.rpm)
followed by `sudo zypper install --allow-unsigned-rpm /home/<user>/Downloads/rustdesk-1.1.9-suse.rpm`
...

**RustDesk version and environment**

RustDesk 1.1.9-suse.rpm from github releases
OpenSUSE Tumbleweed
KDE Plasma 5.25.4
KDE Frameworks 5.96.0
Qt Version 5.15.5
Kernel 5.19.0-1-default (64-bit)
Graphics Platform X11

**Comment by jayjay991** [comment]
adding `Exec=rustdesk --new-window %u` to the end of `/usr/share/rustdesk/files/rustdesk.desktop` and copying to `/usr/share/applications/rustdesk.desktop` seems to have removed the error. 

Still isnt appearing in my launcher after reloading or logging out/in or rebooting. Might not be a rustdesk issue at this point but rather plasma. Keeping this here for the above error fix. Should the version number `Version=1` also be updates to `Version=1.1.9`?

**Comment by grummbeer** [comment]
there is a new suse rpm. Please try the nightly https://github.com/rustdesk/rustdesk/releases/tag/nightly

RustDesk **1.2.0 (nightly)**
Operating System: openSUSE Tumbleweed 20230118
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.102.0
Qt Version: 5.15.8
Graphics Platform: X11

![rustdesk-launcher](https://user-images.githubusercontent.com/67791701/213741208-62d26237-6108-44eb-820d-6f6b2515434c.png)

**Comment by rustdesk** [comment]
close this old issue first because i believe it is fixed, it can be opened again if you still has issue.
