### ISSUE TITLE
GLIBC_2.29 not found

### ISSUE THREAD

**Issue by ceokei** [rustdesk/rustdesk#13]
rustdesk: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found
os: debian 10

建议打包不要采用glibc包过新！

**Comment by open-trade** [comment]
> rustdesk: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found
> os: debian 10
> 
> 建议打包不要采用glibc包过新！

什么发行版?

**Comment by ceokei** [comment]
os: debian 10 (buster)

> > rustdesk: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found
> > os: debian 10
> > 建议打包不要采用glibc包过新！
> 
> 什么发行版?

debian 10 (glibc 2.28)  == deepin 20.2 (glibc 2.28)
debian 9 (glibc 2.24)
opensuse (glibc 2.26)

你现在是需要glibc 2.29以上才能运行，
ubuntu >19.04 (glibc 2.29) 
所以你打包支持的版本就太少了，只能在ubuntu 19.04及以上版本能跑。其它的版本都跑不了。

**Comment by rustdesk** [comment]
> os: debian 10 (buster)
> 
> > > rustdesk: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found
> > > os: debian 10
> > > 建议打包不要采用glibc包过新！
> > 
> > 
> > 什么发行版?
> 
> debian 10 (glibc 2.28) == deepin 20.2 (glibc 2.28)
> debian 9 (glibc 2.24)
> opensuse (glibc 2.26)
> 
> 你现在是需要glibc 2.29以上才能运行，
> ubuntu >19.04 (glibc 2.29)
> 所以你打包支持的版本就太少了，只能在ubuntu 19.04及以上版本能跑。其它的版本都跑不了。

是的，考虑不周

**Comment by rustdesk** [comment]
> > os: debian 10 (buster)
> > > > rustdesk: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found
> > > > os: debian 10
> > > > 建议打包不要采用glibc包过新！
> > > 
> > > 
> > > 什么发行版?
> > 
> > 
> > debian 10 (glibc 2.28) == deepin 20.2 (glibc 2.28)
> > debian 9 (glibc 2.24)
> > opensuse (glibc 2.26)
> > 你现在是需要glibc 2.29以上才能运行，
> > ubuntu >19.04 (glibc 2.29)
> > 所以你打包支持的版本就太少了，只能在ubuntu 19.04及以上版本能跑。其它的版本都跑不了。
> 
> 是的，考虑不周

下次我在Ubuntu 18上编译。
