### ISSUE TITLE
Option to control delay display the main menu bar 

### ISSUE THREAD

**Issue by cnmade** [rustdesk/rustdesk#130]
Need option to control the delay of display the main menu bar. 
The current main menu bar will display instantly, But i am not want to access the main menu bar. I almost to control remote windows minimal, max, close. 

Please provide us an option to control the behaviour.

For example, If we put mouse on the top of the screen for more than 5 seconds. Then we know we really want to see the Rustdesk main menu bar.
![image](https://user-images.githubusercontent.com/278153/123749219-c3442480-d8e7-11eb-9a8d-382031aa9154.png)

As the screen shot, the most common action, we need to take action with remote desktop window.
Not close the rustdesk window. I often got the wrong action.

**Comment by rustdesk** [comment]
You can use full screen mode, there is full screen button on the toolbar.

**Comment by rustdesk** [comment]
> 5 seconds.

Understood, Thanks.

**Comment by cnmade** [comment]
no sir, the full scrren mode. the main button will easy to show , user will not want to close the rustdesk close button.

You can see the screen shot picture, user want to take action with the remote desktop browser window. 

We often click the wrong button.

**Comment by rustdesk** [comment]
> We often click the wrong button.

Yes, me too. I will think about it.

**Comment by rustdesk** [comment]
Good point, Thank you very much.
