### ISSUE TITLE
Phisycal Mouse doesn't work properly on Android and iPad

### ISSUE THREAD

**Issue by InfinityLoop1308** [rustdesk/rustdesk#1314]
**Describe the bug you encountered:**

(both streaming a Linux host on public server)

On Android client, mouse wheel doesn't work
On iPad client, mouse wheel and click (right/left) don't work.

Streaming different hosts will not change the result.
Using finger click instead physical mouse make it work properly.
...

**What did you expect to happen instead?**
They work
...

**How did you install `RustDesk`?**

from official website

**RustDesk version and environment**
1.1.10-1

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1739
