### ISSUE TITLE
Physical keyboard always double-click on iPad

### ISSUE THREAD

**Issue by InfinityLoop1309** [rustdesk/rustdesk#1318]
**Describe the bug you encountered:**

Physical keyboard always double-click on iPad.
Say, whatever I input will be triggered twice. 
...

**What did you expect to happen instead?**
No double click.
...

**How did you install `RustDesk`?**

Official website
...

**RustDesk version and environment**

1.1.10-1

**Comment by rustdesk** [comment]
dup https://github.com/rustdesk/rustdesk/issues/907
