### ISSUE TITLE
Mac: Empty White Screen On Startup bug

### ISSUE THREAD

**Issue by RunningSanil** [rustdesk/rustdesk#132]
**Describe the bug you encountered:**

Mac 客户端启动后一闪一闪的，鼠标动一下就闪一下，不动就是白板。
![image](https://user-images.githubusercontent.com/10514424/123780882-39578400-d906-11eb-8701-cf68805ce2ba.png)

**What did you expect to happen instead?**

MAC 系统版本：
![image](https://user-images.githubusercontent.com/10514424/123781011-568c5280-d906-11eb-8e59-cffed2923663.png)

**Comment by rustdesk** [comment]
Noted with thanks.

**Comment by rustdesk** [comment]
dup https://github.com/rustdesk/rustdesk/issues/93, though different OS

**Comment by rustdesk** [comment]
But hard to reproduce, seems having underlying Sciter problem

**Comment by rustdesk** [comment]
Sciter has big compatibility issue, seems have to replace it in the future.

**Comment by xyu2019** [comment]
昨天下载安装了rustdesk-1.1.6.dmg，这个bug还存在，1.1.5也有相同问题，能否修复？
系统：macOS Mojave，版本10.14

**Comment by rustdesk** [comment]
> 修复

Please help on this, because I can not reproduce it on my mac.

**Comment by c-smile** [comment]
> Sciter has big compatibility issue, seems have to replace it ASAP. #103

That's rather DirectX driver problems as it appears.

Try to put:
```C++ 
SciterSetOption(NULL, SCITER_SET_GFX_LAYER, GFX_LAYER_D2D_WARP);
```
This will tell Direct2D/DirectX to use [WARP](https://en.wikipedia.org/wiki/Windows_Advanced_Rasterization_Platform) so bypassing possibly buggy drivers.

Also it makes sense to handle SC_GRAPHICS_CRITICAL_FAILURE notifications.

Another option is to use Sciter version with Skia backends rather than DirectX. That's the same backend as Flutter will use on desktop.

**Comment by rustdesk** [comment]
> Direct2D/DirectX

Thank you so much. Do you have any clue about possible blank screen on Mac?

**Comment by c-smile** [comment]
I haven't such reports on relatively recent Macs.

On what version on MacOS is that?

**Comment by rustdesk** [comment]
> version
It is 10.14.1
![image](https://user-images.githubusercontent.com/71636191/126874624-21e7e986-55d9-419b-8090-7e2deac5b68e.png)

**Comment by rustdesk** [comment]
> reports

The user said the window blinks when mouse moving, it is blank when mouse not moving.

**Comment by c-smile** [comment]
> > reports

> The user said the window blinks when mouse moving

I have similar reports on MacOS v 10.XX, yes.  

Apple changed something in regards of OpenGL handling between v.10 and  v.11. 

Looking on this at the moment.

**Comment by c-smile** [comment]
FYI: I've fixed the issue here. 

The fix will appear in the next build.

**Comment by rustdesk** [comment]
> fixed

@c-smile Thanks a lot

**Comment by xyu2019** [comment]
@c-smile 您好，请问下一个mac版本什么时间发布？

**Comment by rustdesk** [comment]
@xyu2019 He is not Chinese.

**Comment by open-trade** [comment]
@c-smile I saw you have update sciter-js-sdk to 4.4.8.7, but sciter-sdk is still lagging behind, we are still using sciter-sdk.

**Comment by open-trade** [comment]
try out https://github.com/rustdesk/rustdesk/releases/download/1.1.8/rustdesk-1.1.8.dmg

**Comment by rustdesk** [comment]
@c-smile warp not work on windows, still white screen. https://github.com/rustdesk/rustdesk/issues/210

**Comment by grummbeer** [comment]
@RunningSanil have you already tried the nightly version? https://github.com/rustdesk/rustdesk/releases/tag/nightly

still any issues? probably related to the "white screen" thing #80
