### ISSUE TITLE
I can't connect to a Linux Mint 20.3 machine with Rustdesk 1.1.9

### ISSUE THREAD

**Issue by cpcbegin** [rustdesk/rustdesk#1335]
I can't connect to a PC with Linux Mint Mate 20,3 with Rustdesk 1.1.9

ID never is generated and always show the message 'Connection to the RustDesk network'.

```
If I run from console show this error:
INFO:TIS: scaleFactor 1
INFO:TIS: current platform: Linux
INFO:TIS: is_xfce:  false
INFO:TIS: id updated
INFO:TIS: id updated
INFO:TIS: id updated
INFO:TIS: id updated
INFO:TIS: id updated
INFO:TIS: id updated
...
```

![rustdesk_error](https://user-images.githubusercontent.com/10259216/186121490-fc5eb65c-9608-4b1e-b53f-9f4205dcfb58.png)

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/314
