### ISSUE TITLE
rustdesk client will not use configured rendevous/relay server

### ISSUE THREAD

**Issue by lakester** [rustdesk/rustdesk#1338]
**Describe the bug you encountered:**

The rustdesk client will ALWAYS use the predefined id and relay servers and will ignore the user configured id and relay server settings.

FWIW, the web beta client WILL use the configured id and relay server settings..., so it appears that my hbbs/hbbr installation is working at some level.  I.e., I can connect to my remote desktop using web beta, using my hbbs/hbbr server..., but not with the rustdesk client.

Also..., it would appear that the "rustdesk --server" processes do successfully make themselves available to the self-hosted hbbs/hbbr server.

Have verified with "nc" (Linux) that all ports are configured on the hbbs/hbbr server as documented.

The problem SEEMS to be with how the client attempts to connect with the rendevous/relay server(s).

tcpdump indicates that the client is making some kind of attempt to connect with hbbs..., but nothing happens with hbbr afterwards.  Also..., nothing appears in hbbs.log except for the initial startup messages.

...

**What did you expect to happen instead?**

Two things:  first, I hoped that the client would use the configured servers, but it doesn't.  Second, if it couldn't access or use the configured server, it should fail with an error message of some kind.  Instead, it silently flips over to the pre-defined servers.  This feels like a less than optimal security practice.

...

**How did you install `RustDesk`?**

**Server(hbbs/hbbr):**
Version 1.1.6 from https://github.com/rustdesk/rustdesk-server/releases
Manual install.   
Ubuntu 18.04 (Linode instance)
Have run with and without "-k _" flags.  No difference wrt problem.
Have run hbbs with and without explicit "-r" flag.  No difference wrt problem.

**Client(rustdesk)**
Version 1.1.9 from https://github.com/rustdesk/rustdesk/releases (rustdesk-1.1.9.deb)
Installed via deb package on
Ubuntu 20.04, Mint 20, and Debian 10

The same behavior is seen on all machines, regardless of which one is acting as client, or which one is acting as the remote desktop.

---

**Comment by rustdesk** [comment]
please go to discord for help, there are many selfhost users, no guys have this issue.

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
https://www.reddit.com/r/rustdesk/comments/wtit7b/client_will_not_use_configured_rendevousrelay/
