### ISSUE TITLE
Online Status?

### ISSUE THREAD

**Issue by mkono87** [rustdesk/rustdesk#134]
What the possibility of this? Say when opening the main window it will go through each (ping) and display a red/green dot for online status. Sure I guess you could just double the computer but seeing dots are quicker :)

**Comment by rustdesk** [comment]
Sorry, can not under u?

**Comment by mkono87** [comment]
Would be nice to see in the computer list which devices are online or not.

**Comment by rustdesk** [comment]
+1

**Comment by Man-in-Black** [comment]
I would also like to see this feature in the future

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/2786
