### ISSUE TITLE
suppress alt+F2 and some other shortcuts in linux host

### ISSUE THREAD

**Issue by test2a** [rustdesk/rustdesk#1340]
**Describe the bug you encountered:**
when i am using a linux host and want to connect to a client, say a windows device or a linux one, ALT+F2 on my KDE neon installation triggers the krunner

WIN-super key
win+v 
alt+f2

...

**What did you expect to happen instead?**
these shortcuts should not get triggered on host but only on client, currently this shortcut is being triggered on both.

when anydesk is in view, maximized for example, it should try to forward all shortcuts rather than allowing the host system to trigger it..
...

btw, i use rustdesk 11 hours a day, everyday and it is a much better experience than anydesk, my anecdata at least so you are doing something right for once... good job

**How did you install `RustDesk`?**

github release i believe
---

**RustDesk version and environment**
1.1.9

**Comment by rustdesk** [comment]
@asur4s

**Comment by test2a** [comment]
i would add "alt+tab" as well.  doing alt-tab in rustdesk does it on both machines so it is unusable

**Comment by test2a** [comment]
vnc viewers and anydesk even i think has something like "try to capture all shortcuts" or something similar to that.  anydesk has "transmit hotkeys" option so this error does not show on it

**Comment by asur4s** [comment]
#1694

> Support grab global shortcut keys: by grab ctrl, shift, alt, command.

Maybe the next version will solve your problem.

**Comment by Rostislaved** [comment]
same for me.
Solving it will help a lot. It's very annoying issue.
I have i3wm at both client and host and when I press win+n it changes client's workspace and unfortunately host's!

**Comment by asur4s** [comment]
Try nightly both side. Grab global shortcut keys has been supported @Rostislaved

**Comment by rustdesk** [comment]
#1547

**Comment by rustdesk** [comment]
Close to favor https://github.com/rustdesk/rustdesk/issues/3488
