### ISSUE TITLE
Local PC can no longer use backticks (and possibly other keys) once connected to remote machine

### ISSUE THREAD

**Issue by kirides** [rustdesk/rustdesk#1342]
**Describe the bug you encountered:**

Windows 11 & Windows 11 both on DE keyboard layout

Once Rustdesk runs on the "Supporter" PC and connected to "Client 1" the "Supporter PC" can no longer type `` ` ``

Typing `` ` `` usually requires the "Supporter PC" to press the key  `SHIFT`+`` ´ `` followed by `(SPACE) `

The real issue is, that the Supporter PC can not even type this key combination in a local notepad anymore.
Rustdesk seems to consume the keystrokes even when not having the remote window focused.

**What did you expect to happen instead?**

still being able to use my LOCAL keyboard like usual

**How did you install `RustDesk`?**

GitHub release 1.1.9 portable exe

**RustDesk version and environment**

Windows 11 Local and remote machine

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/980

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1178
