### ISSUE TITLE
os error 10054

### ISSUE THREAD

**Issue by Ramon403** [rustdesk/rustdesk#1343]
rustdesk 1.19

clients:
windows 11 x64   |  win10 x64 | win server2012 R2

always  os error 10054

使用的是自己搭建的 ID/中继服务器

![image](https://user-images.githubusercontent.com/2922635/186376164-a14f3348-b8e1-4840-858c-aac940509f27.png)

另外一台电脑远程时除了 10054错误，还有经常是没有画面传输过来，一直显示如下
![image](https://user-images.githubusercontent.com/2922635/186376944-c43b979f-dfd4-41bc-8183-7b6f05a0af9c.png)

**Comment by rustdesk** [comment]
Try out https://github.com/rustdesk/rustdesk-server/issues/59 for hbbs for 10054 as workaround.

**Comment by 21pages** [comment]
This problem has been merged into master just now, Here is a 
temporary master [build](https://github.com/21pages/tmp). You can try enable ALWAYS_USE_RELAY or try this build.

**Comment by rustdesk** [comment]
Try out nightly build please

**Comment by Jerrycelery** [comment]
relay cannot fix error 10054 here.
