### ISSUE TITLE
win7->win10， win 10 keyboard abnormal

### ISSUE THREAD

**Issue by caoyiwen** [rustdesk/rustdesk#135]
install  last version(1.1.6) in both side;

when linked to remote side， the key  of  “ctrl”  pressed  in remote side；

win7->win10

**Comment by rustdesk** [comment]
Noted with thanks

**Comment by rustdesk** [comment]
Similar issue https://github.com/rustdesk/rustdesk/issues/127

**Comment by caoyiwen** [comment]
when will you repaire this problem？

**Comment by rustdesk** [comment]
> -> 2012 server, ctrl+alt+del not work - from zhihu user

**Comment by rustdesk** [comment]
> ctrl

I am fixing this issue, seems you pressed "ctrl+alt+del" or some other "ctrl+alt", you can press "ctrl+alt" again to fix the problem as a wordaound.

**Comment by open-trade** [comment]
try out https://github.com/rustdesk/rustdesk/releases/download/1.1.8/rustdesk-1.1.8-windows_x64.zip
