### ISSUE TITLE
Swedish kb layout problem

### ISSUE THREAD

**Issue by BXZ** [rustdesk/rustdesk#1371]
Bug:
The ´ and ¨ keys yields 8 and , respectively on remote computer and both keys stop working completely locally.

Environment:
Both computers are running Windows (11 on local, 10 on remote) and both has keyboard layout set to Swedish.
Both are using RustDesk x64 v1.1.9

Extra Info:
Key codes are 192 and 160 (decimal)
Both keys are so called dead keys
Shift + ´ = `
Shift + ¨ = ^
Alt Gr + ¨ = ~

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/964

**Comment by rustdesk** [comment]
#1547

**Comment by fufesou** [comment]
@BXZ Hi, thanks for your feedback.
Can you please try the nightly build, with "Map mode"?
<img width="235" alt="20230104201351" src="https://user-images.githubusercontent.com/13586388/210695310-3b43155b-3cb1-4ff2-81d7-330b668641d9.png">

**Comment by BXZ** [comment]
@fufesou Hi, I've done some quick testing and the original problem seem to be solved but I noticed a new one that's almost as bad.
When holding Alt Gr it's treated as if Ctrl is also held, causing different problems depending on how an application handles the input. Some applications seem to prioritize Ctrl combinations while others prioritize Alt Gr combinations.

**Comment by fufesou** [comment]
> When holding Alt Gr it's treated as if Ctrl is also held

Is this issue happened on Windows (11 on local, 10 on remote).

@BXZ Can you please give more details? Is this issue appears every time you press Alt Gr? Or is there some triggers?

I've tried 3 cases, but cannot find this issue.
Win --> MacOS, Win --> Linux, Win --> Win

But Win --> Win cannot use the soft keyboard on the peer side. (I'll try to fix later)

https://user-images.githubusercontent.com/13586388/211181408-1334cae7-6d9b-423b-a753-31f16fccbe29.mp4

https://user-images.githubusercontent.com/13586388/211181409-a7d15baf-055e-402a-8608-4ce6fd1df650.mp4

**Comment by fufesou** [comment]
I've also tried Win11 --> Win10, Alt Gr works ok, but soft keyboard dose not.

**Comment by BXZ** [comment]
The problem occurs without any special trigger. I've now also tested it between two clean Win10 2H22 installs, Swedish language and Swedish keyboard layout, just installed RustDesk on both of them, connected, opened notepad, pressed Alt Gr+W which acts like Ctrl+W causing it to close.
I also just realized as I was writing this that osk would be a great visualizer for the problem so here's a clip showing it, remote on top, local on bottom:

https://user-images.githubusercontent.com/1578059/211299920-4425d44f-3937-4e9c-b58a-b231fa48f04c.mp4

**Comment by fufesou** [comment]
Thanks, I can reproduce this issue. And I've learned a new tool osk.
I'll fix it as soon as possible.

**Comment by BXZ** [comment]
I verified yesterday that just sending RAlt works by setting my local keyboard layout to US.
Do you happen to know how RustDesk injects keyboard strokes in Windows?
I already found how it reads them and have been messing around with that in C# but I'm curious to know what happens if you inject 0x021D because before your fix RustDesk just masked it with 0xFF resulting in a normal LCtrl so this bug (and the fix of ignoring >0xFF) might affect some exotic keyboard layouts too.

**Comment by fufesou** [comment]
RustDesk hook keyboard with the rdev repo. https://github.com/fufesou/rdev
You can download and run `cargo run --example grab` .

> so this bug (and the fix of ignoring >0xFF) might affect some exotic keyboard layouts too.
Thanks for your reminding.

Yes. Just ignore >0xFF is wrong, some scancode is prefixed with 0xE0.

The scancode is defined [here](https://learn.microsoft.com/en-us/windows/win32/inputdev/about-keyboard-input#:~:text=102%20Enhanced%20keyboard-,Scan%201%20make,-Scan%201%20break).

0X021D is a very strange one. I'm not sure how to handle it. For now, just filtering it works fine. Maybe I'll find a better way in the future.

**Comment by BXZ** [comment]
I've tested the latest nightly and it works flawlessly.
I've also done some research and turns out 0x0200 is a flag bit on the scancode called SCANCODE_SIMULATED which is defined in kbd.h from the Windows DDK.
I've also found out that internally SendInput only uses the lowest byte of the scancode so there's no way to actually send 0x021D.
How you're doing it now is probably the best way to do it.

**Comment by fufesou** [comment]
@BXZ Thanks so much.

I'll read the following code later. To find out the right way to handle 
```C
#define SC_FAKE_LSHIFT 0x22A
#define SC_FAKE_RSHIFT 0x236 // This is the actual scancode received by the hook, excluding the 0x100 we add for "extended" keys.
#define SC_FAKE_LCTRL 0x21D
```

https://github.com/HotKeyIt/ahkdll/blob/818386f5af7e6000d945801838d4e80a9e530c0d/source/keyboard_mouse.h#L150

**Comment by rustdesk** [comment]
> I have an issue where when I press AltGr + "#", it gives me "#" instead of "\".
> 
> PS: Oh wow, I tried doing AltGr + "#" again, and it locked up my system! It is like Alt is being press down continuously

@fufesou

**Comment by rustdesk** [comment]
@mutageneral new issue please
