### ISSUE TITLE
Can I control my Android devices?

### ISSUE THREAD

**Issue by Wmeteor** [rustdesk/rustdesk#138]
I can't get the remote ID on my Android Devices when I want mac -> Android or Android -> Android

**Comment by rustdesk** [comment]
dup https://github.com/rustdesk/rustdesk/issues/76

**Comment by Heap-Hop** [comment]
[knox.remotecontrol](https://docs.samsungknox.com/devref/knox-sdk/reference/com/samsung/android/knox/remotecontrol/package-summary.html)
better remote control for samsung
