### ISSUE TITLE
How to compile this code on mac os

### ISSUE THREAD

**Issue by iakuf** [rustdesk/rustdesk#139]
How to compile this code on mac os?
There is no introduction to the installation library in the documentation.
I tried to install it but was prompted for the following error:
   Compiling runas v0.2.1
   Compiling cocoa-foundation v0.1.0
   Compiling dasp v0.11.0
   Compiling sha2 v0.9.3
   Compiling futures-util v0.3.14
   Compiling tokio v1.7.1
   Compiling rand v0.8.3
error[E0463]: can't find crate for `objc`
  --> libs/rust-sciter/src/lib.rs:75:14
   |
75 | #[macro_use] extern crate objc;
   |              ^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `sciter-rs`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by rustdesk** [comment]
Yes, I only have detailed Linux steps, because I do not wanna redo all steps on Mac.

**Comment by rustdesk** [comment]
https://joshsulin.github.io/rustdesk/2021/07/06/compiling-rustdesk/
https://translate.google.com/translate?sl=zh-CN&tl=en&u=https://joshsulin.github.io/rustdesk/2021/07/06/compiling-rustdesk/

**Comment by rustdesk** [comment]
dup https://github.com/rustdesk/rustdesk/issues/19
