### ISSUE TITLE
Really bad english wording about security

### ISSUE THREAD

**Issue by emiddleton** [rustdesk/rustdesk#14]
In the website[1] and on the readme you use the phrase "no concern of security".  In this context it means you have not considered or cared about security in creating this software.  I think what you meant to write is "no concerns about security" which suggests you don't need to worry about security using this product.

1. https://rustdesk.com/

**Comment by rustdesk** [comment]
Thank you so much. I used google translation.2021年4月2日 21:25，Edward Middleton ***@***.***>写道：
In the website[1] and on the readme you use the phrase "no concern of security".  In this context it means you have not considered or cared about security in creating this software.  I think what you meant to write is "no concerns about security" which suggests you don't need to worry about security using this product.
https://rustdesk.com/
