### ISSUE TITLE
Discovered tab blank

### ISSUE THREAD

**Issue by warpedlogic83** [rustdesk/rustdesk#1407]
I've installed Rust on several computers, and am very impressed with it.  The biggest issue I have right now is one of my computers isn't discovering peers on the network.  All other computers have discovered peers with no problems.  The troublemaker in question is a Win 10 Pro machine on a domain and using wifi for the network access.  One other is also using Wifi, Zorin OS, and it discovers peers fine.

**Comment by rustdesk** [comment]
#844
