### ISSUE TITLE
DEB pkg depends on pulseaudio but works fine with pipewire

### ISSUE THREAD

**Issue by aapjeisbaas** [rustdesk/rustdesk#1408]
Installed the deb on pos_OS 22.04 with --ignore-depends=pulseaudio
There is no pulseaudio in the new pop_OS, I skipped the depend on install and it worked fine.
Even audio from the remote machine was working, maybe make in depend on pulse or pipewire.

I had to remove it because apt didn't like the missing depend.

PS: Thnx for this awesome software really helped me out when TeamViewer kept kicking out my sessions telling me to to buy a business license to help family members with their machines.
I'll definitely give the self hosted version a try if I find the time.

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/559

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3203
