### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by jack9603301** [rustdesk/rustdesk#1410]
**Describe the bug you encountered:**

The following error actually occurs:

```
Caused by:
  process didn't exit successfully: `/home/user/rustdesk/target/debug/build/rustdesk-a6e4c488f51bac5c/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=src/flutter_ffi.rs

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ffigen is not a command, or not executable.', build.rs:99:56
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**What did you expect to happen instead?**

Compiled successfully

**How did you install `RustDesk`?**

I am trying to compile and install rustdesk in gentoo

---

**RustDesk version and environment**

gentoo, build env: podman/docker

**Comment by rustdesk** [comment]
#763

**Comment by awsms** [comment]
Same here on Arch. Followed all the steps from the build guide.
