### ISSUE TITLE
在macOS上运行./flutter/ios_arm64.sh报错error[E0412]: cannot find type `Frame` in this scope

### ISSUE THREAD

**Issue by attackers** [rustdesk/rustdesk#1411]
error[E0412]: cannot find type `Frame` in this scope
  --> libs/scrap/src/common/mod.rs:55:81
   |
55 |     fn frame<'a>(&'a mut self, timeout: std::time::Duration) -> std::io::Result<Frame<'a>>;
   |                                                                                 ^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0412`.
error: could not compile `scrap` due to previous error
[ERROR cargo_lipo] Failed to build "rustdesk" for "aarch64-apple-ios": Executing "/Users/cailei/.rustup/toolchains/1.62.0-x86_64-apple-darwin/bin/cargo" "--color" "auto" "build" "-p" "rustdesk" "--target" "aarch64-apple-ios" "--release" "--lib" finished with error status: exit status: 101

**Comment by rustdesk** [comment]
#763

**Comment by xhzth70911** [comment]
fn frame<'a>(&'a mut self, timeout: std::time::Duration) -> std::io::Result<Frame<'a>>;  not found in this scope,你这个问题怎么解决的,能给个方法吗
