### ISSUE TITLE
AppImage crash on launch

### ISSUE THREAD

**Issue by RafaelLinux** [rustdesk/rustdesk#1413]
I launch the AppImage version but have a lot of errors in console and finally crash without any window.

...

To show RustDesk interface

...

RustDesk-1.1.10-x86_64_1804_ed59bc43b73d8aa4a03fe86adf0f2560.AppImage
Operating System: openSUSE Tumbleweed 20220820
KDE Plasma Version: 5.25.4
KDE Frameworks Version: 5.97.0
Qt Version: 5.15.5
Kernel Version: 5.19.2-1-default (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-9700K CPU @ 3.60GHz
Graphics Processor: NVIDIA GeForce RTX 2060/PCIe/SSE2
Manufacturer: HP

Console output:
`
./RustDesk-1.1.10-x86_64_1804_ed59bc43b73d8aa4a03fe86adf0f2560.AppImage
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
Gtk-Message: 13:37:26.825: Failed to load module "canberra-gtk-module"

(rustdesk:17113): Gtk-WARNING **: 13:37:26.960: Theme parsing error: gtk.css:3341:25: 'font-feature-settings' is not a valid property name
Gtk-Message: 13:37:26.975: Failed to load module "colorreload-gtk-module"
Gtk-Message: 13:37:26.976: Failed to load module "window-decorations-gtk-module"
INFO:TIS: scaleFactor 1
INFO:TIS: current platform: Linux
INFO:TIS: is_xfce:  false
Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/48-spacing.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/56-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/61-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
`

**Comment by rustdesk** [comment]
dup: #1243
