### ISSUE TITLE
How to get rid of border for a "real" fullscreen mode?

### ISSUE THREAD

**Issue by techflashYT** [rustdesk/rustdesk#1416]
### Discussed in https://github.com/rustdesk/rustdesk/discussions/1279

<div type='discussions-op-text'>

<sup>Originally posted by **techflashYT** August 14, 2022</sup>
How would you get rid of the white border around the viewable area?</div>
I made a discussion for this a little over 2 weeks ago and have still gotten no response.

**Comment by lastzero** [comment]
👇
https://twitter.com/rustdesk/status/1565404878792339456
