### ISSUE TITLE
No file transfer window comes out

### ISSUE THREAD

**Issue by solerzhuxy** [rustdesk/rustdesk#1421]
**Describe the bug you encountered:**
Hi, developers. I am using Rustdesk in Win10 to remotely control a Ubuntu computer, both through my own built relay server and default Rustdesk server. I encounters file transfer window not appearing after click Transfer File tab. I accidentally repaired this issue by closing the app and restarting. But restarting doesn't work when the rustdesk process is stuck and cannot be killed in the system monitor both for the host and remote side.
So how to deal with issue, even when the rustdesk process cannot be killed in the system monitor? Thanks in advance.
...
******
**What did you expect to happen instead?**
Transfer files normally without stuck.
...

*****
**How did you install `RustDesk`?**

I check the current installation, I install Rustdesk by exe file in Win10. Deb file installation in Ubuntu22.04.

*****
**RustDesk version and environment**

ver: 1.1.9

**Comment by rustdesk** [comment]
since you can build, please help fix it, we won't help you soon.

**Comment by solerzhuxy** [comment]
> since you can build, please help fix it, we have no time and resource to help you soon.

Hi, thanks for the reply. I check the installation in Win10, I installed Rustdesk by exe file instead, not build from source. So What is the possible reason?

**Comment by solerzhuxy** [comment]
I reproduced this error again. It will come out when Rustdesk is running accompanied with second monitor connected, After second monitor removed, the file transfer window cannot show correctly. I am not sure whether others will encounter or not.
