### ISSUE TITLE
Missing menu option to send CTRL+ALT+DEL

### ISSUE THREAD

**Issue by fabneto** [rustdesk/rustdesk#1422]
I've read some of other issues about the same topic, but none of the solutions have worked for me.

I'm using rust desk 1.1.9 on macOS Monterey as a client.

And I have two virtual servers installed on VMWare ESXi 7.0U3 running windows server 2022 Standard.
I have installed Rustdesk 1.1.9 on both servers but after the initial connection I reach the windows server login screen and I can't send CTRL+ALT+DEL to the server to make the login.

I've made something different running rust desk inside a virtual machine on my Mac, then I use the Vmware player send CTRL+ALT+DEL to the rust and it works, but after I put the password the connection is closed and return to the windows server login screen

**Comment by rustdesk** [comment]
windows version is installed?

**Comment by rustdesk** [comment]
dup https://github.com/rustdesk/rustdesk/issues/1244

**Comment by fabneto** [comment]
I've already read that thread, but it din't work for me.
As I've explained, on the lightning menu I don't have the option to send ctrl+alt+del.
And it is installed normally on Windows Server
<img width="1218" alt="Captura de Tela 2022-09-01 às 15 37 51" src="https://user-images.githubusercontent.com/67835186/187988298-8053a662-78b3-4678-8ad4-d747e39216e4.png">

**Comment by rustdesk** [comment]
that's why that issue is still open, no duplicate issue please.

**Comment by fabneto** [comment]
Sorry, I din't pay attention that the issue is still opened. Thanks anyway!
