### ISSUE TITLE
Support for DNS SRV record

### ISSUE THREAD

**Issue by Alien21** [rustdesk/rustdesk#1423]
It would be great to add support for DNS SRV record. This would allow you to easily use multiple hbbs/hbbr on a single IP address without having to remember and enter the port. For example 2 hbbs would run on one sever (one ip address 185.185.185.185 for test). First private hbbs on port 11116 and second public hbbs on port 12116. Using DNS SRV record would set up the 2 domains and determine which hbbs to use. For the private hbbs: _rustdesk._tcp.rustdesk.example.com service = 0 5 11116 rustdesk.example.com and rustdesk A 185.185.185.  For public hbbs (on the same ip address): _rustdesk._tcp.rustdeskfree.example.com service = 0 5 12116 rustdeskfree.example.com and rustdeskfree A 185.185.185. In the clients, it would be enough to use rustedesk.example.com or rustdeskfree.example.com as the server ID and the client would know which hbbs to log into based on the SRV record.

And if you need to move hbbs to another server in the future, there is no need to change the server ID on dozens of clients. It will be enough to modify the DNS SRV record and the changes will be applied automatically on the clients

**Comment by rustdesk** [comment]
dup #1268
