### ISSUE TITLE
keyboard does not work on mac when connecting to a remote windows machine

### ISSUE THREAD

**Issue by adehgha** [rustdesk/rustdesk#1425]
I have installed the 1.1.9 version both on mac and windows.
When I try to connect to the windows box from my mac, I am not able to type because apparently keys do not map correctly across systems. The only keys that do work properly are "command" that maps to "windows" key and "control" that maps correctly to the "control" key on windows. The rest of the keys do not work and certainly I cannot type any letters.
I'd love to know if there is a setting that I may have missed.

**Comment by rustdesk** [comment]
#964

**Comment by avrileader** [comment]
Me too,Montenery normal，Catalina does not respond to keyboard input，The Catalina has an external keyboard，

**Comment by rustdesk** [comment]
> keyboard input

https://github.com/rustdesk/rustdesk/issues/974#issuecomment-1186577391

**Comment by adehgha** [comment]
> > keyboard input
> 
> [#974 (comment)](https://github.com/rustdesk/rustdesk/issues/974#issuecomment-1186577391)

I can confirm that granting access to rustdesk app on macos for "input monitoring" resolves the issue that I reported in this bug ([see this link for step by step directions](https://github.com/rustdesk/rustdesk/issues/974#issuecomment-1186577391)) .

However I am wondering why this step is necessary as other apps such as "Microsoft Remote Desktop" on macos perform the same exact mapping across platforms (mac to Windows) without requiring "input monitoring".

Note that enabling "input monitoring" in macos allows rustDesk to "monitor input from your keyboard even while using other apps" while it only should be necessary when using the app.

**Comment by rustdesk** [comment]
It is just a workaround for now.

**Comment by arekm** [comment]
Are there some nightly builds to test this? (assuming this is already implemented in code)

**Comment by HannibalZA** [comment]
This shouldn't need any fixes. The first time you connect via RustDesk client on Mac you will be prompted to allow Input monitoring under Privacy and Security settings for the Rustdesk app.
This resolves it entirely.
<img width="733" alt="image" src="https://user-images.githubusercontent.com/2007626/214656845-a3e53b37-a134-4fe9-b842-f467ee527d44.png">

**Comment by bhajneet** [comment]
> However I am wondering why this step is necessary as other apps such as "Microsoft Remote Desktop" on macos perform the same exact mapping across platforms (mac to Windows) without requiring "input monitoring".
> 
> Note that enabling "input monitoring" in macos allows rustDesk to "monitor input from your keyboard even while using other apps" while it only should be necessary when using the app.

Note that in Microsoft Remote Desktop it is a single app. RustDesk is two apps in the dock. Both have the same name "Rust Desk", but if you click on the name top-left (next to the apple icon) it will show you two different menus. Odd set up, but probably related to the explanation for why it needs to monitor from one and forward to the other.
