### ISSUE TITLE
RustDesk icon in macOS dark mode does not show up

### ISSUE THREAD

**Issue by tejasraman** [rustdesk/rustdesk#1427]
**Describe the bug you encountered:**
Using RustDesk on macOS Catalina (10.15) on an older patched 2011 MacBook Pro (13") and 12 (Monterey) on a 2018 Macbook Pro (15") in dark mode causes tray icon to not show up. 

**What did you expect to happen instead?**
Either the dark or light tray icon should show up in the top bar

**How did you install `RustDesk`?**

GH release

**RustDesk version and environment**

macOS 10.15.7 (Build 19H2)
2011 MacBook Pro (MacBookPro8,1)

macOS 12.5.1 (Build 21G83)
2018 MacBook Pro (MacBookPro15,1)

RustDesk 1.1.9

**Screenshots:**
![Screen Shot 2022-09-01 at 8 31 01 PM](https://user-images.githubusercontent.com/96961804/188047268-c2a1d246-af0d-473d-b104-df5c379d539d.png)
![Screen Shot 2022-09-01 at 8 30 41 PM](https://user-images.githubusercontent.com/96961804/188047274-ecb4b3db-d5cb-4911-a2f2-ed1a2c0a6e4c.png)

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/1230
