### ISSUE TITLE
build error on windows11

### ISSUE THREAD

**Issue by heimasi** [rustdesk/rustdesk#1432]
**Describe the bug you encountered:**

follow the doc to build on windows 11

cargo run

 Compiling rustdesk v1.1.10 (C:\Users\sizhi\rustdesk)
error[E0412]: cannot find type `CliprdrClientContext` in this scope
  --> src\client\io_loop.rs:45:40
   |
45 |     clipboard_file_context: Option<Box<CliprdrClientContext>>,
   |                                        ^^^^^^^^^^^^^^^^^^^^ not found in this scope
   |
help: consider importing this type alias
   |
1  | use clipboard::cliprdr::CliprdrClientContext;
   |

error[E0425]: cannot find function `get_rx_clip_client` in this scope
   --> src\client\io_loop.rs:109:42
    |
109 |                 let mut rx_clip_client = get_rx_clip_client().lock().await;
    |                                          ^^^^^^^^^^^^^^^^^^ not found in this scope
    |
help: consider importing this function
    |
1   | use clipboard::get_rx_clip_client;
    |

error[E0425]: cannot find function `clip_2_msg` in this scope
   --> src\client\io_loop.rs:155:59
    |
155 | ...                   allow_err!(peer.send(&clip_2_msg(clip)).await);
    |                                             ^^^^^^^^^^ not found in this scope
    |
help: consider importing this function
    |
1   | use crate::clipboard_file::clip_2_msg;
    |

error[E0425]: cannot find function `msg_2_clip` in this scope
   --> src\client\io_loop.rs:807:49
    |
807 | ...                   if let Some(clip) = msg_2_clip(clip) {
    |                                           ^^^^^^^^^^ not found in this scope
    |
help: consider importing this function
    |
1   | use crate::clipboard_file::msg_2_clip;
    |

error[E0425]: cannot find function `server_clip_file` in this scope
   --> src\client\io_loop.rs:808:33
    |
808 | ...                   server_clip_file(context, 0, clip);
    |                       ^^^^^^^^^^^^^^^^ not found in this scope
    |
help: consider importing this function
    |
1   | use clipboard::server_clip_file;
    |

error[E0425]: cannot find function `create_clipboard_file_context` in this scope
    --> src\client\io_loop.rs:1158:27
     |
1158 |                     match create_clipboard_file_context(true, false) {
     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `IS_ALT_GR` in this scope
   --> src\ui_session_interface.rs:752:28
    |
752 |                         if IS_ALT_GR {
    |                            ^^^^^^^^^ not found in this scope
    |
note: static `crate::ui::remote::IS_ALT_GR` exists but is inaccessible
   --> src\ui\remote.rs:42:1
    |
42  | static mut IS_ALT_GR: bool = false;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not accessible

error[E0425]: cannot find value `IS_ALT_GR` in this scope
   --> src\ui_session_interface.rs:758:33
    |
758 | ...                   IS_ALT_GR = false;
    |                       ^^^^^^^^^ not found in this scope
    |
note: static `crate::ui::remote::IS_ALT_GR` exists but is inaccessible
   --> src\ui\remote.rs:42:1
    |
42  | static mut IS_ALT_GR: bool = false;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not accessible

error[E0425]: cannot find value `IS_ALT_GR` in this scope
   --> src\ui_session_interface.rs:781:33
    |
781 | ...                   IS_ALT_GR = true;
    |                       ^^^^^^^^^ not found in this scope
    |
note: static `crate::ui::remote::IS_ALT_GR` exists but is inaccessible
   --> src\ui\remote.rs:42:1
    |
42  | static mut IS_ALT_GR: bool = false;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not accessible

**What did you expect to happen instead?**

normal build result
no error

**How did you install `RustDesk`?**

git clone at 2022-09-02
windows 11 family

**RustDesk version and environment**

**Comment by rustdesk** [comment]
#763

**Comment by heimasi** [comment]
I know the rule.
But the document not help me.
The document is very poor,  no limit plugins version . the document is old. sometime  use some tool or plugin's lastest version , errors are coming.
