### ISSUE TITLE
Interface issues: "Language" menu entry is absent on some languages and "OS Password" field is ugly stretched

### ISSUE THREAD

**Issue by Comraddm** [rustdesk/rustdesk#1444]
**Describe the bug you encountered:**

Hello! On some language translations menu entry "Language" is absent, only some empty space for it.
Also "OS Password" field is very very stretched.
See included screenshots.

**What did you expect to happen instead?**

Please correct that interface issues.

**How did you install `RustDesk`?**
Portable version.

---

**RustDesk version and environment**
Windows Portable version 1.1.9

![pic_01](https://user-images.githubusercontent.com/14926499/188330732-a2aa35e7-e5d1-481e-a556-9481a2bfefa0.jpg)
![pic_02](https://user-images.githubusercontent.com/14926499/188330731-d4fa9c73-d42d-44db-8717-14ddcb4a9116.jpg)

**Comment by rustdesk** [comment]
@21pages

**Comment by 21pages** [comment]
Great issue! The 1.1.9 release tagged [tmp](https://github.com/rustdesk/rustdesk/blob/df32b8f07bf4fe7a6be34d86bec87ad6f4f6d4a6/src/lang.rs#L84)  has no judgment on empty translation,  it has been fixed on master branch.
And wordwrap will be added.
![ff82fe487ea72e6fc53b7d8a7fe3aa1](https://user-images.githubusercontent.com/14891774/188580643-adcbd7c7-f5f4-4e11-af36-963c8b2d7604.png)
