### ISSUE TITLE
--- stderr   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ffigen is not a command, or not executable.', build.rs:99:56

### ISSUE THREAD

**Issue by dmcmulle** [rustdesk/rustdesk#1446]
Running into a build issue.  

I have followed the guide here https://rustdesk.com/docs/en/dev/build/windows/

I get to the last step `cargo run`, and get the following output:

```
Compiling rustdesk v1.1.10 (C:\Users\user\rustdesk)
error: failed to run custom build command for `rustdesk v1.1.10 (C:\Users\user\rustdesk)`

Caused by:
  process didn't exit successfully: `C:\Users\user\rustdesk\target\debug\build\rustdesk-78f46452508b75bc\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=src/flutter_ffi.rs

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ffigen is not a command, or not executable.', build.rs:99:56
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Someone else had the problem as well in the discussion here:

### Discussed in https://github.com/rustdesk/rustdesk/discussions/1431

<div type='discussions-op-text'>

<sup>Originally posted by **HighPing1667** September  2, 2022</sup>
--- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ffigen is not a command, or not executable.', build.rs:99:56
How do I solve？</div>

Let me know any additional information you need from me to help me resolve this.

I am using Windows 10, and installed msvc, rustup-init.exe, git-bash, vcpkg, sciter, and LLVM

**Comment by dmcmulle** [comment]
To anyone running into this issue, I fixed it by pulling the latest release branch (in my case, `git checkout 1.1.9`), and then ran cargo run, and everything built as expected.

**Comment by 724898928** [comment]
I also encountered this problem on ubuntu20. How can I solve this problem?

**Comment by dmcmulle** [comment]
> I also encountered this problem on ubuntu20. How can I solve this problem?

Did you try my solution above?

**Comment by 724898928** [comment]
> > I also encountered this problem on ubuntu20. How can I solve this problem?
> 
> Did you try my solution above?

I tried, but the code got too many errors to compile.
