### ISSUE TITLE
iOS device list direct Ip connection not stored

### ISSUE THREAD

**Issue by takov751** [rustdesk/rustdesk#1447]
**Describe the bug you encountered:**

So Finnaly I was able to test it as my phone was fixed. That ID based connection is stored , however direct ip based connection is not showing up in the list of recent devices. 

**What did you expect to happen instead?**

To ip addresses show up in recent connection. 

**How did you install `RustDesk`?**
AppStore 

---

**RustDesk version and environment**
iOS 15.6 and 16 beta tested

**Comment by rustdesk** [comment]
merged in master.
