### ISSUE TITLE
about shortkey

### ISSUE THREAD

**Issue by li-dianzheng** [rustdesk/rustdesk#1449]
**Describe the bug you encountered:**

When my mouse is on the remote desktop, the shortcut keys still call up the local program instead of the remote desktop program.

**What did you expect to happen instead?**

当我的鼠标在远程桌面中时，我的快捷键调用的是远程的程序。或者有个设置，快捷键是调用本地的程序还是远程桌面的。

**How did you install `RustDesk`?**
GitHub release.

**RustDesk version and environment**
local desktop is Windows,remote desktop is arhclinux gnome.
remote desk: rustdesk-1.1.9-manjaro-arch.pkg.tar.zst
local version: rustdesk-1.1.9-windows_x64.zip

**Comment by li-dianzheng** [comment]
What did you expect to happen instead?
When my mouse is in the remote desktop, my shortcuts call the remote program. Or there is a setting, the shortcut key is to call the local program or the remote desktop

**Comment by rustdesk** [comment]
try out nightly build please.

**Comment by rustdesk** [comment]
and please help confirm if the other app can capture all shortcuts?

**Comment by fufesou** [comment]
@li-dianzheng Hi, can you please give some shortcut keys that cannot be sent to the remote? I can't reproduce this issue.
BTW, can you please try the nightly build, with "Map mode". A lot of keyboard issues are fixed.

<img width="235" alt="20230104201351" src="https://user-images.githubusercontent.com/13586388/210694998-3ea17e75-8760-4253-9b1d-4824ca2656a3.png">

**Comment by li-dianzheng** [comment]
I will try。

**Comment by li-dianzheng** [comment]
it's working.Thanks
