### ISSUE TITLE
win10->mac can't control mac

### ISSUE THREAD

**Issue by iamshifty** [rustdesk/rustdesk#145]
I setup up on win10 and mac big Sur 11.4.
mac file is https://github.com/rustdesk/rustdesk/releases/download/1.1.6/rustdesk-1.1.6-dbg.dmg
win10 file is https://github.com/rustdesk/rustdesk/releases/download/1.1.6/rustdesk-1.1.6.exe
I can control win10 from mac,but can't control mac from win10.Only connect and display mac screen.

**Comment by rustdesk** [comment]
dup https://github.com/rustdesk/rustdesk/issues/133
