### ISSUE TITLE
Can't connect after a restart

### ISSUE THREAD

**Issue by fabifont** [rustdesk/rustdesk#1453]
**Describe the bug you encountered:**
Can't reconnect to rustdesk after a restart on linux.
I enabled `rustdesk.service`, it works but after each reboot the password or the ID resets so I can't connect anymore with my fixed password. Is there any way to have a persistent ID/password across reboots?

**What did you expect to happen instead?**
Connect to the machine with my previous ID and my fixed password.

**How did you install `RustDesk`?**
From AUR, `rustdesk-bin` package.

---

**RustDesk version and environment**
```
rustdesk --version
1.1.9
```
```
uname -a
Linux atlas3 5.19.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 31 Aug 2022 22:09:40 +0000 x86_64 GNU/Linux
```

**Comment by rustdesk** [comment]
close since we can not reproduce this, and no further report from the other users.

**Comment by GPOSCLIC** [comment]
Sorry, but I have the same issue:
New ID on each reboot.
Rustdesk version: 1.3.9
OS: Win 10 / Build: 19041
Regards
