### ISSUE TITLE
Docker Build error "ffigen is not a command, or not executable"

### ISSUE THREAD

**Issue by topaz2002** [rustdesk/rustdesk#1456]
While building via docker-container i get error
```
error: failed to run custom build command for `rustdesk v1.1.10 (/home/user/rustdesk)`

Caused by:
  process didn't exit successfully: `/home/user/rustdesk/target/release/build/rustdesk-b236ee71c6208b6b/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=src/flutter_ffi.rs

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ffigen is not a command, or not executable.', build.rs:99:56
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

...

**What did you expect to happen instead?**

successfully built

**How did you install `RustDesk`?**

```
git clone https://github.com/rustdesk/rustdesk
cd rustdesk
docker build -t "rustdesk-builder" .

```

**RustDesk version and environment**
last available

**In order to reproduce your issue, please add some information about the environment
in which you're running RustDesk.**
-->
docker --version
Docker version 20.10.17, build 100c701

 uname -a
Linux 4.14.35-2047.516.2.1.el7uek.x86_64 #2 SMP Wed Aug 17 16:30:09 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux

Exactly follow the building instruction (Docker version)

**Comment by rustdesk** [comment]
#763
