### ISSUE TITLE
win10->win10，After using for a period of time, the mouse and keyboard are abnormal

### ISSUE THREAD

**Issue by jun-time** [rustdesk/rustdesk#146]
version 1.1.6

**Comment by rustdesk** [comment]
Seems similar to https://github.com/rustdesk/rustdesk/issues/135

**Comment by rustdesk** [comment]
More details please.

**Comment by jun-time** [comment]
实际使用中，好几个同事与我自己。一开始连接还正常，使用大概使用0.1-5小时左右，不定期键盘无法输入，一输入就成快捷键那种，打开些系统界面。解决方法是：重启电脑即恢复远程，但过一会又发生键盘无法输入。

**Comment by jun-time** [comment]
> More details please.

实际使用中，好几个同事与我自己。一开始连接还正常，使用大概使用0.1-5小时左右，不定期键盘无法输入，一输入就成快捷键那种，打开些系统界面。解决方法是：重启电脑即恢复远程，但过一会又发生键盘无法输入。

**Comment by jun-time** [comment]
> More details please.

rustdesk后台运行中没使用，也有一定的机率产生影响键盘输入。我使用向日葵远程工具时

**Comment by jun-time** [comment]
> More details please.

期待尽快解决键盘问题，我们会进行付费使用

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/135

**Comment by open-trade** [comment]
try out https://github.com/rustdesk/rustdesk/releases/download/1.1.8/rustdesk-1.1.8-windows_x64.zip
