### ISSUE TITLE
Rustdesk Connection Error 10054 just in a strage condition

### ISSUE THREAD

**Issue by Emanuele971** [rustdesk/rustdesk#1460]
Hi guys, I have a strange problem! 🙃  I set up my self-server Rustdesk.
On my inaternal DNS I registered a URL linked to the LAN IP of my Rustdesk server . For the outside (internet) I registered a record type "A" with the same URL which is resolved instead with my public IP. After that I created the redirections for the ports indicated by the documentation, towards the LAN ip of my server: 
21114:21119/tcp
8000/tcp
21116/udp
and I see traffic passing on these ports from my firewall.
For both clients I enter my url in the "server ID" setting and they both mark "ready"✅ 
Now, between two client connected outside my LAN (internet) It works!
Between two client connected inside my LAN, It works!
But between two client, one connected outside my LAN (internet) and one connected inside my LAN, it does not work!....😭 
I get the error: Connection Error 10054 - An existing connection have go be close from the client.
Anyone have an idea? Please

![image](https://user-images.githubusercontent.com/112970750/188713773-f0b4fe80-5a23-44f9-b1b3-9c39b50018bd.png)

**Comment by rustdesk** [comment]
#1343

**Comment by Emanuele971** [comment]
Hi, thanks for you reply, but I don't understand.
In the other cases that you linked, it's advised to enable ALWAYS_USE_RELAY, but I dont understand how...
In my folder /opt/rustdesk/ I have just these files:
db_v2.sqlite3  db_v2.sqlite3-shm  db_v2.sqlite3-wal  hbbr  hbbs  id_ed25519  id_ed25519.pub
Which is the configuration file? Where i can enable ALWAYS_USE_RELAY?
The files hbbr and hbbs are not editable... when I open them with nano are like crypted.
I tried even to edit the file install.sh (downloaded from https://raw.githubusercontent.com/dinger1986/rustdeskinstall/master/install.sh following the ufficial docs).
I have read someone saying: "ALWAYS_USE_RELAY=Y" or put below into .env file..." 
but where is the .env files?
Thanks a lot in advance for your support.
Greetings
Martino

**Comment by Emanuele971** [comment]
@rustdesk Can you please reopen the case?
