### ISSUE TITLE
Error in color when render on web desktop client

### ISSUE THREAD

**Issue by BuckyGao** [rustdesk/rustdesk#1464]
There is no problem when entering the page. But the screen will appear some colorful spot on the static picture after a while. We use chrome V 101.0.4951.54.

...

Can you please help us dealing with the display error.

...

 GitHub release

---

RustDesk version leastest release
OS: Ubuntu 20.04.4 LTS
![2022-09-07 16-10-51屏幕截图](https://user-images.githubusercontent.com/68122679/188827539-129ee56e-f398-464f-b08c-e37ada73f1c8.png)
![2022-09-07 16-10-18屏幕截图](https://user-images.githubusercontent.com/68122679/188827543-2e7ea5c6-6cdb-4433-ac7f-331a67cef146.png)

**Comment by rustdesk** [comment]
known
