### ISSUE TITLE
There is no response when using the mouse wheel on the Android Tablet

### ISSUE THREAD

**Issue by xoipz** [rustdesk/rustdesk#1466]
**Describe the bug you encountered:**

When I use the mouse wheel to scroll the vertical page on the Android Tablet, the page does not move. I use the computer wheel to find that it is not the problem of the page itself.

**What did you expect to happen instead?**

I want to have the experience of using a wheel on an Android device using a Bluetooth mouse

**How did you install `RustDesk`?**

Installing the application of official website in win10

---

**RustDesk version and environment**

RustDeskversion 1.1.9

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1739

**Comment by rustdesk** [comment]
Close to favor 1739
