### ISSUE TITLE
The android terminal cannot be blocked after the screen is closed

### ISSUE THREAD

**Issue by zhsande** [rustdesk/rustdesk#1467]
After the screen of the Android phone is off, it cannot be remotely performed from other terminals (including win, Android, and web), and it will prompt: Link error The remote computer is offline

Remote control can still be initiated even when the screen is off

Downloaded from https://rustdesk.com/zh/ web page, all platform versions are downloaded on 2022.9.5

**Comment by rustdesk** [comment]
duplcate

**Comment by zhsande** [comment]
What does that mean?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/816

**Comment by zhsande** [comment]
Hello, I read what you posted, but this is not my problem, I haven't been able to remotely access it yet. After the screen is off for a period of time, the phenomenon as shown in the figure will appear, and after the screen is lit, it can be remoted normally. All restrictions in the battery are lifted.
![Screenshot_20220909_090429_com carriez flutter_hb](https://user-images.githubusercontent.com/108330975/189251165-cc9abe20-f05b-4314-a877-97caf87c6b82.jpg)

**Comment by danmoqian1997** [comment]
> 

same problem
