### ISSUE TITLE
rustdesk server莫名其妙关闭

### ISSUE THREAD

**Issue by bigben446** [rustdesk/rustdesk#1471]
在远程云主机——阿里云上，ubuntu主机，成功部署rustdesk server，开放了相关端口，可以通过主机ip作为中继服务器访问。问题是，每隔几个小时，似乎又连接不上云主机的中继服务器，需要在云主机上重启hhbs、hbbr才能又连接上。不知道是啥原因，很麻烦，隔几个小时就要手动重启hhbs、hbbr才行

**Comment by rustdesk** [comment]
#763
