### ISSUE TITLE
Mouse scrolling speed too fast on Mac

### ISSUE THREAD

**Issue by iamGaryLiao** [rustdesk/rustdesk#1474]
**Describe the bug you encountered:**

Mouse scrolling speed was way too fast when controlling a Mac, even if adjusted the Mac's mouse scrolling speed to slowest.

**What did you expect to happen instead?**

I wished you can find out what was the cause of this and made the scrolling speed normal. (I used other remote control softwares too, and their mouse scrolling speed were quite similar with controlling locally)

**How did you install `RustDesk`?**

---GitHub release

**RustDesk version and environment**

 RustDesk 1.1.9, macOS Monterey 12.2.1

**Comment by niehongbo** [comment]
Me too, I can't control the scrolling very well. View scrolls too fast when I remote control window on magic mouse

**Comment by IsaacZD** [comment]
same issue here, quite annoying

**Comment by rustdesk** [comment]
@asur4s

**Comment by asur4s** [comment]
I didn't reproduce this bug, maybe it's because of the magic mouse?

**Comment by ul** [comment]
It's reproducible for me when controlling another Mac with MacBook Pro's built-in trackpad.

**Comment by rustdesk** [comment]
> trackpad

How about with mouse?

**Comment by ul** [comment]
The scrolling speed is normal when I use a regular mouse.

**Comment by rustdesk** [comment]
> The scrolling speed is normal when I use a regular mouse.

@xxrlzzz we need to test both mouse and trackpad for Flutter.

**Comment by aiden0820** [comment]
Still happening on my MBP

**Comment by Torrontes123** [comment]
I have the exact opposite problem. Controlling a Mac from Windows, scrolling using the wheel is painfully slow, regardless of the scroll settings on the Mac.

**Comment by Throwaway24924** [comment]
Controlling Mac from Linux laptop
Scroling is fine most of the time like when using chrome 

But scrolling through a spreadsheet is so fast and inaccurate it's unusable i have to use arrow keys
There were other times where the speed was unberable but can't remember what I was doiing
