### ISSUE TITLE
Pop! OS: Deb package missing dependency

### ISSUE THREAD

**Issue by mikensan** [rustdesk/rustdesk#1477]
**Describe the bug you encountered:**

Attempted to install deb package on Pop! OS 22.04, eddy reported code 100 - sudo apt install reported that a dependency was missing: Pulseaudio.

When attempting to install pulseaudio I received a conflict error (See below)
The following packages have unmet dependencies:
 pop-desktop : Conflicts: pulseaudio
               Recommends: io.elementary.sideload but it is not installable
               Conflicts: pulseaudio:i386

**What did you expect to happen instead?**

For it to install

**How did you install `RustDesk`?**

Downloaded rustdesk-1.1.9.deb
Opened it with Eddy GUI - Code 100
Opened it with gdebi | dependency unable to install
sudo apt install ./rustdesk-1.1.9.deb | Dependency missing

**RustDesk version and environment**
Pop! OS 22.04 LTS
rustdesk-1.1.9

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/559

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3203

**Comment by evanlesmez** [comment]
Have the same problem
