### ISSUE TITLE
sends two characters instead of one when keyboard is pressed

### ISSUE THREAD

**Issue by LuckyHost** [rustdesk/rustdesk#1489]
friends who faced such a problem.  when I send one character from the phone, two come on the computer.  example: the letter "g" should come, "gg" comes.  The keyboard is connected to the phone external!.  I also noticed one bug when you send a press from the phone to the SHIFT or CONTROL or ALT key.  only KEY PRESSING, WITHOUT ITS reverse release, comes to the computer.  in fact, a constantly pressed SHIFT comes to the computer, and there is no way to work adequately

Video https://youtu.be/LBVCn6A6XIQ

**Comment by rustdesk** [comment]
dup: #1318
