### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by SmartManoj** [rustdesk/rustdesk#149]

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/65

**Comment by itsmeboy0** [comment]
It's not a duplicate, he is talking about creating a dark mode for the GUI.

**Comment by rustdesk** [comment]
should be "dark theme"

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/67

**Comment by rustdesk** [comment]
PR welcome

**Comment by xmha97** [comment]
> should be "dark theme"

My Android phone using dark theme but this app is light!

**Comment by grummbeer** [comment]
dark theme in place. close

**Comment by rollingmoai** [comment]
Where? I do not see

**Comment by grummbeer** [comment]
use the nightly build https://github.com/rustdesk/rustdesk/releases/tag/nightly

![rustdesk-dark](https://user-images.githubusercontent.com/67791701/213592654-2df78353-891e-4bdc-92c2-279e97386b1f.png)
