### ISSUE TITLE
Install AppImage error

### ISSUE THREAD

**Issue by lexcorp** [rustdesk/rustdesk#1495]
I'm trying to install Rustdesk client on Rocky Linux 9, Iḿ using AppImage
I follow this steps:

1.- Download AppImage of Rustdesk

2.-Set executable permissions to file:
$ chmod + x RustDesk-1.1.10-x86_64_1804.AppImage 

3.- Install libnsl
yum install libnsl

4.- Execute AppImage file:
./RustDesk-1.1.10-x86_64_1804.AppImage 

I get this error:

(rustdesk:11530): GLib-GIO-ERROR **: 15:29:25.650: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
`trap' para punto de parada/seguimiento (`core' generado)

**Comment by lexcorp** [comment]
Configuring Xorg as the default GNOME session

https://docs.fedoraproject.org/en-US/quick-docs/configuring-xorg-as-default-gnome-session/

After that:
./RustDesk-1.1.10-x86_64_1804.AppImage 
Gtk-Message: 15:56:48.735: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:56:48.744: Failed to load module "canberra-gtk-module"
INFO:TIS: scaleFactor 1
INFO:TIS: current platform: Linux
INFO:TIS: is_xfce:  false
Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/25-unhint-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
Violación de segmento (`core' generado)

**Comment by lexcorp** [comment]
Fix load module: pk-gtk-module 

https://robbinespu.github.io/eng/2018/05/29/fixing-pk-gtk-module-and-canberra-gtk-module.html

**Comment by rustdesk** [comment]
#1243
