### ISSUE TITLE
Why one win10 computer cannot remote-control another win10 computer?

### ISSUE THREAD

**Issue by wonlee2019** [rustdesk/rustdesk#150]
Both `TWO` computers are running the Rustdesk.exe, and one types another ID & Password

>  can display desktop of another computer, `But` cannot conduct any operations;

> virtual keyboard & mouse click, even the operation menu buttons do not work;

> mobile app can use the mouse click, but can not use the virtual keyboard.

**Comment by rustdesk** [comment]
installed?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/96

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/150

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/83

**Comment by wonlee2019** [comment]
> installed?

Nope, just run the exe file, but installed app in my phone.

**Comment by rustdesk** [comment]
> > installed?
> 
> Nope, just run the exe file, but installed app in my phone.

Please install controlled side

**Comment by wonlee2019** [comment]
> > > installed?
> > 
> > 
> > Nope, just run the exe file, but installed app in my phone.
> 
> Please install controlled side

Okay, can you tell me which instruction i should follow , thanks!

**Comment by rustdesk** [comment]
> instruction

Pay attention to the "install" link under your id/password.
