### ISSUE TITLE
rustdesk for mac 

### ISSUE THREAD

**Issue by 835952293** [rustdesk/rustdesk#1506]
**Describe the bug you encountered:**
在我使用mac版的rustdesk，远程windows的电脑进行输入操作，发现输入不了任何东西，我怀疑是软件没有监听到我的键盘输入
键盘是正常的
...

**What did you expect to happen instead?**
mac远程windows是可以复现bug
mac是m1 pro
...

**How did you install `RustDesk`?**
官网下载

---

**RustDesk version and environment**
1.1.9

**Comment by 835952293** [comment]
尝试1.1.8版本的客户端，没有这样的问题。目前1.18版本客户端能正常监听到输入

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/974#issuecomment-1186577391
