### ISSUE TITLE
After entering the password, it displays Remote Error No display 

### ISSUE THREAD

**Issue by EthanAlvord** [rustdesk/rustdesk#151]
**Describe the bug you encountered:**

win10->win10，after entering the password, it displays Remote Error No display 

**What did you expect to happen instead?**

I want to use it normally 

**How did you install `RustDesk`?**

Official website 

**RustDesk version and environment**

PC: win10
rustdesk: 1.1.6

**Comment by rustdesk** [comment]
-> win10, does it have attached monitor?

**Comment by rustdesk** [comment]
or is it powered off?

**Comment by EthanAlvord** [comment]
> -> win10, does it have attached monitor?

no attached monitor

**Comment by EthanAlvord** [comment]
> or is it powered off?

ToDesk test ok

**Comment by rustdesk** [comment]
ok, it is what we need to improve.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/59

**Comment by rustdesk** [comment]
For windows, a virtual display driver is recommended:

https://github.com/rustdesk/rustdesk/issues/418#issuecomment-1233018617

**Comment by tan-wei** [comment]
Win10 -> Linux just meet the same issue. What does it mean?

**Comment by rustdesk** [comment]
windows version support virtual display now. Comming soon for linux.
