### ISSUE TITLE
allow loading libsciter-gtk.so from different locations

### ISSUE THREAD

**Issue by kolAflash** [rustdesk/rustdesk#1513]
I'm using [rustdesk-1.1.9.deb](https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9.deb), but I didn't installed it. Instead I just extracted it and ran `./bin/rustdesk`.

Unfortunately `rustdesk` searches for `libsciter-gtk.so` only at `/usr/lib/rustdesk/`.  
[LD_LIBRARY_PATH](https://en.wikipedia.org/wiki/Rpath#GNU_ld.so) is not being considered.

**-> Please consult `LD_LIBRARY_PATH` before checking `/usr/lib/rustdesk/libsciter-gtk.so` statically!**

&nbsp;

... or did I miss any Rust style way to use instead of `LD_LIBRARY_PATH`!?

Maybe related:
[#1492](https://github.com/rustdesk/rustdesk/pull/1492) _Added flatpak feature_

&nbsp;

**Workaround:**
Patch the `rustdesk` binary to load `libsciter-gtk.so` from the current working directory:
`sed -i 's:/usr/lib/rustdesk/:./././././././././:' rustdesk`
Then change directory into the folder containing `libsciter-gtk.so` before running `rustdesk`.

**Comment by anddam** [comment]
@rustdesk Can we have a line of explanation about why this was marked as `wontfix`?

**Comment by kolAflash** [comment]
@anddam 
I just discovered, that RustDesk will replace Sciter completly with Flutter. So I guess that's the explanation.

https://github.com/rustdesk/rustdesk/blob/400911f78235469537e966f15f8e0d78c8663f56/README.md#dependencies

https://github.com/rustdesk/rustdesk/wiki/RustDesk-Desktop-Flutter-Migration

Here you can get a "beta" version with Flutter:
https://github.com/rustdesk/rustdesk/releases/tag/nightly

https://de.wikipedia.org/wiki/Flutter_(Software)

**Comment by anddam** [comment]
So *DartDesk*?
