### ISSUE TITLE
French (azerty) key mapping numeric keypad

### ISSUE THREAD

**Issue by roukmoute** [rustdesk/rustdesk#1517]
Hi,

On my Linux VM with RustDesk, it is currently not possible to use the numeric keypad because it writes like if this is numeric above.

So if I type `123456789` on my numeric keypad, I've got: `&é"'(-è_çà`.

**Comment by rustdesk** [comment]
#1547

**Comment by fufesou** [comment]
Hi @roukmoute , can you please try the nightly build, with "Map mode"? 

<img width="235" alt="20230104201351" src="https://user-images.githubusercontent.com/13586388/210692735-bc237dd4-bd1a-4ef7-a348-e8b78f79b2a7.png">

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1518
