### ISSUE TITLE
French (azerty) key mapping issues

### ISSUE THREAD

**Issue by roukmoute** [rustdesk/rustdesk#1518]
Many issues in French

# First

**Describe the bug you encountered:**

It is not possible currently for me to tape the number `5` on the VM linux.
With Shift+5 I obtain: `(`

**What did you expect to happen instead?**

I should obtain with Shift+5: `5`

# Second

**Describe the bug you encountered:**

It alternate between two chars for the same char.
I just type `^^^^` and I obtain `)ç)ç`
For the shift+`^^^^`, I obtain `°9°9`.

https://user-images.githubusercontent.com/2140469/190368405-8202f31f-5f3d-4bef-aa8a-40dc4feff547.mp4

**What did you expect to happen instead?**

I should obtain:
- `^`
- `¨` with Shift

# Third

When my Linux session is running, I can't use many characters on Windows like:

- `
- `^`

As soon as I close the window these characters are available again.

# Configuration

**How did you install `RustDesk`?**

Windows installed setup.

---

**RustDesk version and environment**

On my Windows: 1.1.9
On my VM Linux (`Linux Travail 5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux`): 1.1.9

**Comment by Jodge65** [comment]
Same 2 & 3 bug on a Windows 10 targeting another Windows 10.
For the 3rd bug, it's as long as the connection is up, but if you have the application open without connection, you have no problem

**Comment by dylanpistachi** [comment]
Also the numeric keypad is not working.
When I type "1" on the numeric keypad, I obtain "&".
This issue is valid for all numbers of my numeric keypad.

**Comment by rustdesk** [comment]
#1547

**Comment by Mozoloa** [comment]
Same general problem, using AZERTY and trying to type 1 (above keyboard, not on the keypad) writes 7, I also can't write a . nor a / nor any punctuation, there's probably ton of those

**Comment by fufesou** [comment]
Hi guys, Thanks for your feedback.
Can you please try nightly build, with "Map mode". This issue should be fixed.
The "Legacy mode" issues will be processed after "Map mode" issues are clean.

<img width="235" alt="20230104201351" src="https://user-images.githubusercontent.com/13586388/210691577-b4671d9a-2756-4154-ac99-b5c8ac0ba74f.png">

**Comment by Jodge65** [comment]
I made a little test with the version available on [github (1.2.0 - Oct 20, 2022)](https://github.com/rustdesk/rustdesk/releases/tag/nightly) and it broke everything: 
i try to write "azertyuiop^$" and "pqrstuvwxyz" was written (yes, the last character is missing)

I'm on a nominal case: **Azerty** keyboard, with **French** on host and **French** on guest.
Note that my keyboard is not 100% iso azerty, the "> <" touch is not at his nominal position and may impact

**Comment by fufesou** [comment]
@Jodge65 Thanks for your test and feedback.
But please test with the latest nightly build. There're stile some keyboard problems on Oct 20, 2022.

**Comment by Jodge65** [comment]
The name in github is misleading, it's named October but the exe was built the 5 January 2023. 
Just to be sure, i redo the same test with the last build (9h ago) and the result in Map Mode are the same:

![image](https://user-images.githubusercontent.com/13049502/211069785-4bc62499-eb2f-4a01-90d9-8a186dd7dce8.png)
_(each line in legacy is a line in the keyboard, the two empty line is because a \n appear instead of a basic character in map mode)_

The third problem (host cannot use some specific key when connection is established) look fixed in my side
The second one is still here in legacy mode. It's look like it's fixe in map mode, but has the keyword is not working great i can't confirm.

**Comment by fufesou** [comment]
@Jodge65 Thanks for your test.
I'll test later.
BTW, what are the OS on both sides? Win --> Linux?

**Comment by rustdesk** [comment]
Close as no response for long

**Comment by roukmoute** [comment]
I sincerely apologize for my delay, I hadn't had a chance to test again before. I finally took the time to download everything again on April 24, 2022, and I'm happy to report that everything works perfectly on the keyboard. Many thanks to you!

**Comment by ericpodico** [comment]
With a french keyboard, when logging in Windows 10, I cannot use the "6" or "8",
the displaid letter will be "as if" i did not press the shift to get my 6 or 8.
I still can use the NUM pad to get a 6 or an 8, but some mini laptop (mac) do not have any NUM Pad

**Comment by fufesou** [comment]
@ericpodico Hi, please try the nightly build on both sides.
Map mode or Translate mode
