### ISSUE TITLE
You can consider strengthening support for IPv6

### ISSUE THREAD

**Issue by MrMu666** [rustdesk/rustdesk#152]
Now that IPv6 is very popular in China, we can consider the scenario of using home IPv6 DDNS as a transit server or directly connecting to each other's IPv6 address point to point

**Comment by rustdesk** [comment]
Noted with thanks

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/98

**Comment by open-trade** [comment]
> https://www.v2ex.com/t/559408

**Comment by MrMu666** [comment]
> > https://www.v2ex.com/t/559408

In fact, ipv6 works very well when set up correctly. My home server uses the shandong mobile network, and I can easily connect to various services on my home server via ipv6 in my beijing education network environment. for ipv6 application developers, there are several issues to be aware of: first, some routers (such as xiaomi) deny all ipv6 external access by default and cannot change it; second, systems such as windows need to turn off RFC3041; third, pay attention to firewall release ports. but for the user, since he chooses to use ipv6 to build a server, he naturally knows how to use ipv6.

**Comment by congzhangzh** [comment]
Ipv6 works well most of time, works well even as server:)

**Comment by congzhangzh** [comment]
Please give ipv6 support, nat should be easy than ipv4 most of time if router firewall exists.

Btw, direct ipv6 connect by ip will be great:)

**Comment by zhaoqishan** [comment]
Please give ipv6 support,Ipv6 is the only assignable public IP address in China

**Comment by rustdesk** [comment]
We are looking for contributors for this.

**Comment by rustdesk** [comment]
> ipv4

Try out our new build, we modified client to fetch ipv4 first. https://github.com/rustdesk/rustdesk/issues/665#issuecomment-1153643970

**Comment by rustdesk** [comment]
https://twitter.com/rustdesk/status/1538758459373813760

**Comment by tiagogaspar8** [comment]
Hi all,

I want to point out that currently, rustdesk can't work in a NAT64 network since when given an IPv6 address it will not connect. This is a bigger issue than native IPv6 support, there are lots of mobile carriers that use NAT64

**Comment by Avey777** [comment]
希望可以支持ipv6，真心的

**Comment by Avey777** [comment]
我的域名解析到了ipv6地址，折腾好久才发现是rustdesk 不支持ipv6地址，导致的不可使用

**Comment by rustdesk** [comment]
> 我的域名解析到了ipv6地址，折腾好久才发现是rustdesk 不支持ipv6地址，导致的不可使用

Working on it.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server/pull/119#issuecomment-1336154587
https://github.com/rustdesk/rustdesk/pull/1594#issuecomment-1336155261

**Comment by rustdesk** [comment]
We just added nat64 support in nightly build, you can test.

**Comment by rustdesk** [comment]
Added in nightly build.

**Comment by JanGamesHD** [comment]
I am getting the error „Operation not permitted (OS error 1)“ while trying to connect with mobile data

**Comment by freaky-m0** [comment]
> Added in nightly build. Not ready for iOS users.

Any roadmap for iOS support? ;-)
