### ISSUE TITLE
why listening 0.0.0.0?

### ISSUE THREAD

**Issue by 12end** [rustdesk/rustdesk#153]
some building errors on windows x64,when I build:
`error: could not find native static library `vpxmt`, perhaps an -L flag is missing?`

And,why RustDesk client listening 0.0.0.0？I think it's unnecessary,sunlogin(sunlogin.oray.com another RDP software) had been pwned because this,it's not safe
I just want change it to 127.0.0.1 and waste whole day to deal this...(not success

**Comment by 12end** [comment]
I have some other needs, want change source and build on my windows,how to get this "vpxmt",(I download vpxmt.dll from network and put it into C:\windows\System32,C:\windows\SysWOW64,but no use)

**Comment by alex8088** [comment]
@12end ，Have you solved the problem？

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/160
https://github.com/rustdesk/rustdesk/issues/164
