### ISSUE TITLE
Apple M1Pro, cargo run failed, fatal error: 'vpx/vp8.h' file not found

### ISSUE THREAD

**Issue by songwei163** [rustdesk/rustdesk#1533]
this is my computer:
 MacbookPro 14
 Apple M1 Pro
When I follow this documentation,https://rustdesk.com/docs/en/dev/build/osx/, I Found some errors when cargo run
Here is details.
error: failed to run custom build command for `scrap v0.5.0 (/Users/songwei/work/rustdesk/libs/scrap)`

Caused by:
  process didn't exit successfully: `/Users/songwei/work/rustdesk/target/debug/build/scrap-5b4b8530a1319865/build-script-build` (exit status: 101)
  --- stdout
  cargo:info=x64-osx
  cargo:rustc-link-lib=static=yuv
  cargo:rustc-link-search=/Users/songwei/vcpkg/installed/x64-osx/lib
  cargo:include=/Users/songwei/vcpkg/installed/x64-osx/include
  cargo:info=x64-osx
  cargo:rustc-link-lib=static=vpx
  cargo:rustc-link-search=/Users/songwei/vcpkg/installed/x64-osx/lib
  cargo:include=/Users/songwei/vcpkg/installed/x64-osx/include
  rerun-if-changed=/Users/songwei/work/rustdesk/libs/scrap/vpx_ffi.h
  rerun-if-changed=/Users/songwei/vcpkg/installed/x64-osx/include

  --- stderr
  /Users/songwei/work/rustdesk/libs/scrap/vpx_ffi.h:1:10: fatal error: 'vpx/vp8.h' file not found
  /Users/songwei/work/rustdesk/libs/scrap/vpx_ffi.h:1:10: fatal error: 'vpx/vp8.h' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', libs/scrap/build.rs:128:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by rustdesk** [comment]
#763
