### ISSUE TITLE
French (azerty) key mapping "^¨" on inline numeric keypad does not work bug Something isn't working

### ISSUE THREAD

**Issue by roukmoute** [rustdesk/rustdesk#1538]
**Describe the bug you encountered:**

It alternate between two chars for the same char.
I just type `^^^^` and I obtain `)ç)ç`
For the shift+`^^^^`, I obtain `°9°9`.

https://user-images.githubusercontent.com/2140469/190368405-8202f31f-5f3d-4bef-aa8a-40dc4feff547.mp4

**What did you expect to happen instead?**

I should obtain:
- `^`
- `¨` with Shift

**How did you install `RustDesk`?**

Windows installed setup.

---

**RustDesk version and environment**

On my Windows: 1.1.9
On my VM Linux (`Linux Travail 5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux`): 1.1.9

**Comment by rustdesk** [comment]
Can you group your azerty problem into one issue please?

**Comment by roukmoute** [comment]
Reported on https://github.com/rustdesk/rustdesk/issues/1518
