### ISSUE TITLE
" symbol no longer working on US International keyboard layout after connecting to remote machine

### ISSUE THREAD

**Issue by seannowotny** [rustdesk/rustdesk#1541]
After connecting to remote machine the " symbol no longer works on the US-International keyboard layout.
The issues is resolved once Rust Desk processes are closed with the task manager.

...

**What did you expect to happen instead?**

" should be typed

**How did you install `RustDesk`?**

 From github releases of this repository.

---

**RustDesk version and environment**

Version: 1.1.9
Windows 10 x64

**Comment by fufesou** [comment]
@seannowotny Thanks for your feedback.
But I cannot reproduce this issue.
Only " cannot be typed? Or Shift cannot work with all other keys, like Shift + a?

If you're still using Rustdesk, can you please test and give more infos about how to reproduce this issue ?

**Comment by fufesou** [comment]
@seannowotny Thanks for your feedback.
But I cannot reproduce this issue.
Only " cannot be typed? Or Shift cannot work with all other keys, like Shift + a?

If you're still using Rustdesk, can you please test and give more infos about how to reproduce this issue ?

**Comment by seannowotny** [comment]
@fufesou I've since moved to use Splashtop instead of Rustdesk.
On the UI International keyboard layout, I have to press shift and double-tap another key at the same time to type "".
This no longer worked as soon as I connected to a remote computer.

I'm using Powertoys to 'switch' my caps lock and escape keys for better ergonomics when using VIM.
Perhaps that could have something to do with it.

**Comment by fufesou** [comment]
Thanks for your heelpful reply. I'll try later.
