### ISSUE TITLE
Long Password issues

### ISSUE THREAD

**Issue by imtrobin** [rustdesk/rustdesk#1544]
Hi, when I set long password (16 characters), the dialog accepts it , but when I view the password, 

1. I cannot see the whole password as it is longer than the sidebar. And I cannot resize sidebar

![image](https://user-images.githubusercontent.com/531606/190531162-df495de6-017c-4204-ad41-7d197208f6d8.png)

2. The system have a limit on password length, but it did not prevent me from setting a long password.

Rustdesk 1.1.9

**Comment by rustdesk** [comment]
we strengthed password in new version， only onetime password will be shown in next version.
