### ISSUE TITLE
JIS (Japan Industrial Standards) key mapping issues

### ISSUE THREAD

**Issue by fa0311** [rustdesk/rustdesk#1545]
**Describe the bug you encountered:**

半角/全角 keys do not work on jis keyboard

**What did you expect to happen instead?**

switch to japanese input
This operation is equivalent to a US keyboard alt + \`
alt + \` works fine

**How did you install `RustDesk`?**

GitHub release

**RustDesk version and environment**

[1.1.9](https://github.com/rustdesk/rustdesk/releases/tag/1.1.9)

**Comment by grummbeer** [comment]
Please try the nightly version https://github.com/rustdesk/rustdesk/releases/tag/nightly
a lot of keyboard issues are fixed. #1547
