### ISSUE TITLE
Keyboard issues (try out nightly build please)

### ISSUE THREAD

**Issue by Jeffmartt** [rustdesk/rustdesk#1547]
When establishing a connection, using a Portuguese keyboard, the accent no longer works correctly on both - the local and remote computers.

Some special characters still appear correctly (like ç or Ç), but trying to accentuate gives weird results like "[é" for "é" or "[à" instead of "à".

Other special characters like :, /, and ? lose mapping...

I tried using three versions: Ubuntu/Debian version, Windows (installed) and Windows Portable version, with same results
 (1.1.9)

**Comment by lsascha** [comment]
same issue with german keyboard. having a connection open,
basically makes a lot of special characters completely unavailable.
even when the remote window is minimized and trying to enter the character on the local PC.

Only tested on Windows as Host and Remote.

**Comment by rustdesk** [comment]
try out https://github.com/rustdesk/rustdesk/releases/tag/nightly please.

**Comment by Jeffmartt** [comment]
Trying to download the Windows version, I got an alert from Windows
Defender:

Trojan Win32/Wacatac.H!ml Detected

------
Jeff

Em dom., 23 de out. de 2022 às 22:54, RustDesk ***@***.***>
escreveu:

**Comment by rustdesk** [comment]
If you trust, please go ahead.

**Comment by nacesprin** [comment]
https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64-unknown-linux-gnu-ubuntu-18.04.deb fails installation on ubuntu 18.
https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9.deb is working fine.

**Comment by flusheDData** [comment]
> When establishing a connection, using a Portuguese keyboard, the accent no longer works correctly on both - the local and remote computers.
> 
> Some special characters still appear correctly (like ç or Ç), but trying to accentuate gives weird results like "[é" for "é" or "[à" instead of "à".
> 
> Other special characters like :, /, and ? lose mapping...
> 
> I tried using three versions: Ubuntu/Debian version, Windows (installed) and Windows Portable version, with same results (1.1.9)

Nor does it work with Spanish á é í ó ú [] and other special symbols.

**Comment by ntiagobr** [comment]
> try out https://github.com/rustdesk/rustdesk/releases/tag/nightly please.

Even with this version(1.2.0), problem still occurs, i can´t do "`" like "à" or "^" like "ê" it appears "~e".

**Comment by rustdesk** [comment]
@asur4s

**Comment by ibrahimkazanci** [comment]
In Turkish-Q Keyboard layout;
```
İ character appear as I
i character appear as ı
```
on host computer.

I tried [nightly](https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64-pc-windows-msvc.exe) windows build on both host and client but nothing changed.

**Comment by asur4s** [comment]
> In Turkish-Q Keyboard layout;
> 
> ```
> İ character appear as I
> i character appear as ı
> ```
> 
> on host computer.
> 
> I tried [nightly](https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64-pc-windows-msvc.exe) windows build on both host and client but nothing changed.

Thx, Let me try the Turkish-Q Keyboard

**Comment by jrmpt** [comment]
Same problems with the Portuguese (pt-pt) layout.

When I need to write a word with "á", rustdesk will insert "," before. When using shift+key it will wrongly produce ';', making it impossible to write words containing 'ò' or 'à'.
https://prnt.sc/_Fdg2rry-O0c

It´s possible to write words with '~'. If I shift that key to get '^', will do nothing.
https://i.postimg.cc/VvrhWFDB/screenshot-1650.jpg

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1974

**Comment by kayo77** [comment]
Similar situation with polish keyboard layout.
Alt + a producing "a" instead "ą"
Alt + a producing "e" instead "ę"
Alt + a producing "z" instead "ż"
Same with other polish chars..

**Comment by cetjunior** [comment]
Same issue, PT-BR (ABNT) keyboard, Windows 10 (guest and host). Key bindings for special characters not working; get worse when using laptops (as they have less keys and more bindings/combinations).

**Comment by rustdesk** [comment]
@cetjunior try out nightly build please.

**Comment by cetjunior** [comment]
> @cetjunior try out nightly build please.

Perfect, @rustdesk team! Working as expected! I'll keep testing and will report if I find any more issues on this matter. Congratulations for the great work!

Thank you very much!

**Comment by RudiOnTheAir** [comment]
> @cetjunior try out nightly build please.

Have the same key mapping problems.

What about using the nightly build only at one side, and let the stable run on the client side wait for the next release. So i could test with nightly releases and one test client with nightly also.. But let in the "field" the latest stable...

The question is, is rustdesk backward compatible with the main funktions...?

**Comment by cetjunior** [comment]
> > @cetjunior try out nightly build please.
> 
> Have the same key mapping problems.
> 
> What about using the nightly build only at one side, and let the stable run on the client side wait for the next release. So i could test with nightly releases and one test client with nightly also.. But let in the "field" the latest stable...
> 
> The question is, is rustdesk backward compatible with the main funktions...?

Hi @RudiOnTheAir,

I'm using the stable installed in the host machine and I'm connecting (client side) with the nightly build, and it's working fine.

Best regards.

**Comment by RudiOnTheAir** [comment]
> Hi @RudiOnTheAir,
> 
> I'm using the stable installed in the host machine and I'm connecting (client side) with the nightly build, and it's working fine.
> 
> Best regards.

Thanks, that more easy to test and help with debugging.. Thanks.

**Comment by dgva** [comment]
I tested both ways (Client: Stable <-> Host: Nightly and Client: Nightly <-> Host: Stable) and it did not work. My tests so far consisted of:

- Client: Windows 10 and 11
- Host: EndeavourOS
- ID server: Ubuntu 18 (RustDesk Stable) 

I didn't have much more time to test more combinations, but during this week I'll drop by with more combinations, if helpfull.

**Comment by dannykorpan** [comment]
Once again with today's nightly. Linux (XUbuntu 22.04.2
![SCR-20230321-rvim](https://user-images.githubusercontent.com/8004507/226721224-19412104-29cf-4db7-bf43-9644d72c585a.png)
) as remote, macOS (13.2.1) to connect from. German keyboard layout on both systems. First character is working (z), from the second character the keyboard layout is wrong.

**Comment by ihalili-info** [comment]
Issues using Shift and write a ketter it is not showing at all.

**Comment by rustdesk** [comment]
@fufesou @chiehw

**Comment by fufesou** [comment]
> Issues using Shift and write letter it is not showing at all at the remote side

@ihalili-info Thanks for you feedback, I can reproduce this issue. I'll try to fix it.

BTW, are the following reproduce steps the same to you?

Reproduce steps:

Win/macOS -> Linux, Translate mode beta.

The remote side does not set the default language input (The first language).


https://user-images.githubusercontent.com/13586388/227689719-beb66bbf-aa8c-424c-b173-aaa3c90c6cf8.mp4

**Comment by fufesou** [comment]
> Nightly 3/22/2023,  macOS (13.2.1) -> Linux (XUbuntu 22.04.2), German keyboard layout both. First character is working (z), from the second character the keyboard layout is wrong.

@dannykorpan Hi, thanks for your feedback. 

![image](https://user-images.githubusercontent.com/13586388/227690601-5ad7c6e6-8fa8-43b2-956b-d0d6acb5dd75.png)


I cannot reproduce the issue you mentioned accurately, but there is indeed a problem with "Translate mode beta".

When Linux is used as the controlled side, the German input method, which should output 'y' when the left shift key is pressed, outputs 'z'.

There is no problem when Win and macOS are used as the controlled system.

**Comment by ihalili-info** [comment]
Actually my reproduced steps are like this

IOS/Android -> Windows Machine -> HVD (Horizon Virtual Desktop) Machine.

so it was double remote connectivity, but i tried in both remotes.

**Comment by dannykorpan** [comment]
> > Nightly 3/22/2023,  macOS (13.2.1) -> Linux (XUbuntu 22.04.2), German keyboard layout both. First character is working (z), from the second character the keyboard layout is wrong.
> 
> @dannykorpan Hi, thanks for your feedback.
> 
> ![image](https://user-images.githubusercontent.com/13586388/227690601-5ad7c6e6-8fa8-43b2-956b-d0d6acb5dd75.png)
> 
> I cannot reproduce the issue you mentioned accurately, but there is indeed a problem with "Translate mode beta".
> 
> When Linux is used as the controlled side, the German input method, which should output 'y' when the left shift key is pressed, outputs 'z'.
> 
> There is no problem when Win and macOS are used as the controlled system.

How to enable keyboard/"Translate mode beta"? There is no Keyboard icon with the todays nightly or do I also have to use the todays beta on the remote side?

**Comment by fufesou** [comment]
@dannykorpan There are two reasons why the keyboard icon is not displayed:
1. Wayland as the control side.
2. No input permission on the remote side, which you can see on the "cm" window.
![image](https://user-images.githubusercontent.com/13586388/227788706-0575033e-5775-4194-b924-02cf1f8ae301.png)

**Comment by rustdesk** [comment]
Or remote side is old version.

**Comment by dannykorpan** [comment]
I'm using the current nightly on macos (control side) and ubuntu (remote side). Xubuntu 22.04.2 is runnung in x11.
![SCR-20230326-rhya](https://user-images.githubusercontent.com/8004507/227794666-bbe5fc75-3cb5-4ad0-91a9-4083626430a2.png)

**Comment by fufesou** [comment]
> Wayland as the control side.
No input permission on the remote side, which you can see on the "cm" window.

@dannykorpan Can you please give a picture about your toolbar on remote page?
I've viewed the code, and tested again. But I can't finger why the "keyboard mode" is not shown.

![1679926499074](https://user-images.githubusercontent.com/13586388/227966113-4ce793bf-de10-4de6-a37f-4cea2ebee867.png)

**Comment by dannykorpan** [comment]
![SCR-20230327-okrw](https://user-images.githubusercontent.com/8004507/227968279-77224392-a4c1-4296-bc09-9ea8415e0530.png)

**Comment by fufesou** [comment]
@dannykorpan Thanks. 
The only possible reason is that the control side do not have the connrect input permission check.
I will try to find and fix it.

**Comment by dannykorpan** [comment]
O.k. If you need any other informations/screenshots, you're welcome.

**Comment by fufesou** [comment]
Can you please upload a picutre about "Action" submenu.

https://user-images.githubusercontent.com/13586388/227973744-cb04c476-c31f-4797-bbd8-408563d02557.mp4

**Comment by fufesou** [comment]
@dannykorpan "Insert Ctrl + Alt + Del" is shown, it means you have input permission to peer side.
Possible reason is that you haven't enabled input permission in Preferences.

https://github.com/rustdesk/rustdesk/blob/679d3d9868108f710e184da7fbc3f804c9192757/src/platform/macos.rs#L63

![image](https://user-images.githubusercontent.com/13586388/227987453-714171c1-ae4b-4841-848d-b5574dc1ab77.png)

**Comment by dannykorpan** [comment]
That was the problem, thank you and shame on me for this. Also the keyboard translation is working with "Translation mode beta" activated.

**Comment by pixeldoc2000** [comment]
I had the same (german) Keyboard Problem with Rustdesk 1.1.9.

Update to current Rustdesk 1.2.0 Nightly fixed the issue.

**Note:** You need up updating both Host and Remote to Nightly and enable "Translation Mode beta" on Remote (is only available if Host is updated too).

**Comment by Karbust** [comment]
I was having the following issue with the keyboard on 1.1.9 when connecting to a Windows 10 from Windows 11.

The host has 2 keyboard layouts on Windows (the physical keyboard has US layout), US and PT-PT, the computer used to connect is full PT-PT.

Examples:
When remote has layout PT-PT, writing `á` shows up as `,á`.
When remote has layout US, writing `á` shows up as  `;á`.

I also notice that the computer connecting has issues with the keyboard when connected to the remote computer, using those kind of keys are not working correctly until I close the connection.

This issue appears to have been fixed after updating to Nightly and using "Translation Mode Beta".

**Comment by cetjunior** [comment]
> I was having the following issue with the keyboard on 1.1.9 when connecting to a Windows 10 from Windows 11.
> 
> The host has 2 keyboard layouts on Windows (the physical keyboard has US layout), US and PT-PT, the computer used to connect is full PT-PT.
> 
> Examples: When remote has layout PT-PT, writing `á` shows up as `,á`. When remote has layout US, writing `á` shows up as `;á`.
> 
> I also notice that the computer connecting has issues with the keyboard when connected to the remote computer, using those kind of keys are not working correctly until I close the connection.
> 
> This issue appears to have been fixed after updating to Nightly and using "Translation Mode Beta".

Hi @Karbust,

Test again using the nightly version at both ends and check if the problem persists.

Best regards.

**Comment by Gisbert12843** [comment]
Has this been resolved because I am still affected by this.. direction is German to German layout on Android to cachyos
