### ISSUE TITLE
White screen appears when I run rustdesk from Swift project

### ISSUE THREAD

**Issue by tahajamil-github** [rustdesk/rustdesk#1549]
<img width="1440" alt="Screenshot 2022-09-16 at 11 29 03 AM" src="https://user-images.githubusercontent.com/99480646/190571758-218e150a-ae89-4266-b59e-069107ceef91.png">
When i open rustdesk.app from a swift project It shows white screen but when i open it from terminal it works fine @palfrey @SantiagoValdez @maxxer

**Comment by rustdesk** [comment]
#763
