### ISSUE TITLE
Question: about releases

### ISSUE THREAD

**Issue by cyb233** [rustdesk/rustdesk#155]
what's different between "rustdesk-1.1.6-setup.exe" and "rustdesk-1.1.6.exe" ?

**Comment by rustdesk** [comment]
![IMG_20210711_084749](https://user-images.githubusercontent.com/71636191/125179819-b6e39400-e224-11eb-959e-2861414ea167.jpg)

**Comment by cyb233** [comment]
so rustdesk-1.1.6.exe is portable version？thanks

**Comment by rustdesk** [comment]
yes
