### ISSUE TITLE
KDE Plasma: window gets stuck in fullscreen

### ISSUE THREAD

**Issue by TheSiman** [rustdesk/rustdesk#1574]
**Describe the bug you encountered:**

Fullscreen button doesn't properly exit fullscreen (can't move the window, covers panel etc.), the only way is manually disabling fullscreen property with ALT+F3 > More Actions > Fullscreen

**What did you expect to happen instead?**

Click fullscreen button = enter fullscreen (window fullscreen property = Yes, this part works)
Click fullscreen button again = exit fullscreen (window fullscreen property = No, this part doesn't work)

**How did you install `RustDesk`?**

Github Release

---

**RustDesk version and environment**

Rustdesk 1.1.9
Fedora 36 KDE spin
Plasma 2.25.5
WM: kWin

**Comment by grummbeer** [comment]
i can confirm that issue for Plasma and 1.1.9. Do you have tried the nightly?  I tried it just now with the latest AppImage, it works.

**Comment by rustdesk** [comment]
@grummbeer Thanks
