### ISSUE TITLE
Not able to build the package in dev - hwcodec error exists regardless of operating system which we use - even in docker

### ISSUE THREAD

**Issue by sunsathees** [rustdesk/rustdesk#1575]
**Describe the bug you encountered:**

Trying to build dev build. But struck up with cargo run. Using Ubuntu, Docker & windows separately to test this and all throws the same error. 

**What did you expect to happen instead?**

...
# VCPKG_ROOT=$HOME/vcpkg cargo run
info: syncing channel updates for '1.62.0-x86_64-unknown-linux-gnu'
info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
    Updating git repository `https://github.com/21pages/hwcodec`
error: failed to get `hwcodec` as a dependency of package `scrap v0.5.0 (/root/rustdesk/libs/scrap)`

Caused by:
  failed to load source for dependency `hwcodec`

Caused by:
  Unable to update https://github.com/21pages/hwcodec#890204e0

Caused by:
  object not found - no match for id (890204e0703a3d361fc7a45f035fe75c0575bb1d); class=Odb (9); code=NotFound (-3)

**How did you install `RustDesk`?**

Build from source. Followed below instructions:
https://rustdesk.com/docs/en/dev/build/linux/

---

**RustDesk version and environment**

 rustc --version
rustc 1.62.0 (a8314ef7d 2022-06-27)

Can some one help in resolving this issue ?

**Comment by rustdesk** [comment]
#763
