### ISSUE TITLE
Support hide remote wallpaper

### ISSUE THREAD

**Issue by Avey777** [rustdesk/rustdesk#1586]
The remote wallpaper has a great influence on the fluency of remote access. I hope to support the removal of the remote wallpaper for a better remote experience.

**Comment by bigretromike** [comment]
Also this would be nice addon, very useful as plain color vs photo would give bandwith different.
Also color mode: https://github.com/rustdesk/rustdesk/issues/1619

**Comment by rustdesk** [comment]
@21pages did try out revoing wallpaper, we did not see obvious bandwidth saving.

**Comment by danielmarschall** [comment]
In TeamViewer and anydesk I used the removed wallpaper as indicator that one of my collegues is currently connected with my system and watching, so that would be still a nice feature.

**Comment by rustdesk** [comment]
> In TeamViewer and anydesk I used the removed wallpaper as indicator that one of my collegues is currently connected with my system and watching, so that would be still a nice feature.

Good point, @21pages  add this back, check if it is turned on by default in tv/anydesk, any additional option?

**Comment by danielmarschall** [comment]
In TeamViewer it is enabled by default.

In AnyDesk you need to enable it by doing a manual configuration in the custom build (I think the full version also has an option in the GUI, but I had never tested the full version):
```
ad.privacy.wallpaper.mode=1
ad.privacy.wallpaper.color=#222222
```
---

Another solution to notice if somebody is watching, other than Wallpaper being removed:

- TeamViewer has this "flag" at the side of the screen, showing that there is an active connection

- FastViewer has an orange "rectangle" around the screen, like a camcorder HUD.

But these things sound complicated to develop, not sure how this would be developed in Win32 API.

**Comment by 21pages** [comment]
AnyDesk set on controlled side, default "Unchanged"
![1696644339546](https://github.com/rustdesk/rustdesk/assets/14891774/4e73c10c-65b6-4d6b-b7fc-44d808f1cd41)
Teamviewer set on the control side, default "checked"
![1696644372547](https://github.com/rustdesk/rustdesk/assets/14891774/bc6a80fc-8d8e-42d0-a52d-8892d1e93027)

**Comment by rustdesk** [comment]
Let's make it unchecked by default on controlled side.

**Comment by rustdesk** [comment]
"View" mode will remove wallpaper?

**Comment by 21pages** [comment]
I think they are independent options.

**Comment by rustdesk** [comment]
Try it out, open a connection without keyboard permission.

**Comment by 21pages** [comment]
Checked AnyDesk and Teamviewer, wallpaper always keep consistent with setting in view mode.

**Comment by rustdesk** [comment]
> consistent with settings

independent option?

**Comment by 21pages** [comment]
Yes, will remove wallpaper

**Comment by bigretromike** [comment]
Looks like @21pages work has been merge into master branch. 
@rustdesk can we close this ?

**Comment by mitsol** [comment]
it is available and works for windows. However. for mac it is not available but would be nice as well. Can you add this for mac too?
