### ISSUE TITLE
Unable to install at PopOs 22.04 (Ubuntu 22.04 based)  Installation Failed Child process exited with code 100

### ISSUE THREAD

**Issue by Roko131** [rustdesk/rustdesk#1589]
**Describe the bug you encountered:**
Unable to install using deb file
...

**What did you expect to happen instead?**
Program to install
Instead I got an error message saying:

com.github.donadigo.eddy
Installation Failed
Child process exited with code 100

![image](https://user-images.githubusercontent.com/3532929/191286217-b07db291-7564-40ad-b2ca-28cdc18f7cd0.png)

I tried running it after a fresh restart, still getting error.
...

**How did you install `RustDesk`?**
Tried to install
Using the deb file at site: `rustdesk-1.1.9.deb`

---

**RustDesk version and environment**
`rustdesk-1.1.9.deb`

uname -a:
`Linux pc 5.19.0-76051900-generic #202207312230~1660780566~22.04~9d60db1 SMP PREEMPT_DYNAMIC Thu A x86_64 x86_64 x86_64 GNU/Linux`

cat /etc/os-release

```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/559

**Comment by Animesh384** [comment]
> **Describe the bug you encountered:** Unable to install using deb file ...
> 
> **What did you expect to happen instead?** Program to install Instead I got an error message saying:
> 
> com.github.donadigo.eddy Installation Failed Child process exited with code 100
> 
> ![image](https://user-images.githubusercontent.com/3532929/191286217-b07db291-7564-40ad-b2ca-28cdc18f7cd0.png)
> 
> I tried running it after a fresh restart, still getting error. ...
> 
> **How did you install `RustDesk`?** Tried to install Using the deb file at site: `rustdesk-1.1.9.deb`
> 
> **RustDesk version and environment** `rustdesk-1.1.9.deb`
> 
> uname -a: `Linux pc 5.19.0-76051900-generic #202207312230~1660780566~22.04~9d60db1 SMP PREEMPT_DYNAMIC Thu A x86_64 x86_64 x86_64 GNU/Linux`
> 
> cat /etc/os-release
> 
> ```
> NAME="Pop!_OS"
> VERSION="22.04 LTS"
> ID=pop
> ID_LIKE="ubuntu debian"
> PRETTY_NAME="Pop!_OS 22.04 LTS"
> VERSION_ID="22.04"
> HOME_URL="https://pop.system76.com"
> SUPPORT_URL="https://support.system76.com"
> BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
> PRIVACY_POLICY_URL="https://system76.com/privacy"
> VERSION_CODENAME=jammy
> UBUNTU_CODENAME=jammy
> LOGO=distributor-logo-pop-os
> ```

facing the same issue

**Comment by Roko131** [comment]
@Animesh384 Use the *nightly* build at [releases](https://github.com/rustdesk/rustdesk/releases) page (Top page)
