### ISSUE TITLE
startx

### ISSUE THREAD

**Issue by Bundy01** [rustdesk/rustdesk#159]
**Describe the bug you encountered:**

On Arch, there is an error message on a pink background.
```
Unsupported display type, x11 expected!
```
I use the rustdesk-bin package from AUR, here is the file to compile this package:
```
pkgname=rustdesk-bin
pkgver=1.1.6
pkgrel=1
pkgdesc="Yet another remote desktop software, written in Rust. Works out of the box, no configuration required. Great alternative to TeamViewer and AnyDesk! "
arch=('x86_64')
url="https://github.com/rustdesk/rustdesk"
license=('GPLv3')
provides=(${pkgname})
conflicts=(${pkgname} ${pkgname%-bin} ${pkgname/bin/git} )
#replaces=(${pkgname})
depends=('gtk3' 'xdotool' 'libxcb' 'libxfixes' 'alsa-lib' 'pulseaudio')
# 'libsciter-gtk-bin'
makedepends=('unzip' 'zip' 'pkg-config' 'make' 'git' 'cmake' 'gcc' 'curl' 'wget' 'rust' 'yasm' 'nasm' 'clang')
backup=()
options=('!strip')
#install=${pkgname}.install
source=("${url}/releases/download/${pkgver}/rustdesk-${pkgver}-manjaro-arch.pkg.tar.zst")
sha256sums=('dbfd6ea2e6994f5157f5794049796a06ea94d424c41121f30181e6ff48fbcaa3')

noextract=("rustdesk-${pkgver}-manjaro-arch.pkg.tar.zst")

prepare() {
    bsdtar -xf "${srcdir}/rustdesk-${pkgver}-manjaro-arch.pkg.tar.zst"
}

package() {
     cp -r "${srcdir}/usr" "${pkgdir}/"
}
```
...

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**
rustdesk-bin 1.1.6-1
cinnamon 5.0.4-1

I found that this problem did not occur with a Debian base and the .deb. A compilation error in Arch? Maybe due to the PKGBUILD file provided above?

Regards.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/56

**Comment by Bundy01** [comment]
I don't use Wayland but xorg with Cinnamon.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/blob/master/src/platform/linux.rs#L352

**Comment by Bundy01** [comment]
I connect to the session with the `startx` command. Do you think it's coming from there?

**Comment by rustdesk** [comment]
I thought this PR fixed this problem, https://github.com/rustdesk/rustdesk/pull/89, but not work for your case.

**Comment by Bundy01** [comment]
Hi,

I just tested with the `slim` login software, but the problem persists with the same error.

**Comment by grummbeer** [comment]
@Bundy01 can this be closed?
