### ISSUE TITLE
Connection error : Connection reset by peer OS error 104

### ISSUE THREAD

**Issue by clues4me** [rustdesk/rustdesk#1597]
Hi, just got twice issue get connected to client. I dont know what its, but i think related to security because its somehow blocked by router/firewall.
The day before its okay, nothing got wrong, but accidently its cant connect to a client, others clients is ok.

Im using debian on both side and installed correctly on x11 desktop.
Rustdesk version 1.1.9

![Cuplikan layar dari 2022-09-22 05-42-51](https://user-images.githubusercontent.com/28584711/191623917-4ee4a936-eeb3-48c0-b8f6-db0ffeae00c3.png)

**Comment by 21pages** [comment]
try this master [build](https://github.com/21pages/tmp)

**Comment by 21pages** [comment]
> Am also facing the exact problem.
> 
> > try this master [build](https://github.com/21pages/tmp)
> 
> Would you mind doing some explanation before I try that? BTW, I'm on Linux...

This problem has been fixed on master branch. I'll put  a linux build on that link later.

**Comment by escape0707** [comment]
> > Am also facing the exact problem.
> > 
> > > try this master [build](https://github.com/21pages/tmp)
> > 
> > Would you mind doing some explanation before I try that? BTW, I'm on Linux...
> 
> This problem has been fixed on master branch. I'll put  a linux build on that link later.

Okay, thanks for the fix.

I'm using my Linux machine to setup a server and letting my windows enjoyer friend using mine, for a better direct connection. Does he need to update his client software or do I need to update my Linux server for the fix to work?

**Comment by 21pages** [comment]
Just update client

**Comment by clues4me** [comment]
> try this master [build](https://github.com/21pages/tmp)

thanks, i'll try

**Comment by rustdesk** [comment]
Can you try out nightly build? There is a fix, though not good enough, not sure if it works in your scenario.

**Comment by weirdal3333** [comment]
The nightly build works better, but clicking or using the keyboard causes the os error 104

**Comment by rustdesk** [comment]
> The nightly build works better, but clicking or using the keyboard causes the os error 104

What env on controlled side?

**Comment by eMPee584** [comment]
Same thing here, with latest nightly .deb and APK.. this comes up in the system log:

```
Feb 12 14:24:49 base sudo[2193853]:     root : PWD=/ ; USER=empee584 ; ENV=XDG_RUNTIME_DIR=/run/user/1000 ; COMMAND=/usr/lib/rustdesk/rustdesk --cm 
Feb 12 14:24:49 base sudo[2193853]: pam_unix(sudo:session): session opened for user empee584(uid=1000) by (uid=0) 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: launch args: [--cm] 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: --cm started 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: initializing FFI cm 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: _appType:cm,info1-id:5dd12be64155148fd70962fd0000000b,info2-name:Debian GNU/Linux,dir:/home/empee584/ 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: _globalFFI init 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: _globalFFI init end 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: registerEventHandler theme theme 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: registerEventHandler language language 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: Failed to find definition for #a 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: #0      debugPrintStack (package:flutter/src/foundation/assertions.dart:1209) 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: #1      FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:1028) 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: #2      reportMissingDef (package:flutter_svg/src/utilities/errors.dart:5) 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: #3      _Elements.linearGradient (package:flutter_svg/src/svg/parser_state.dart:378) 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: #4      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:885) 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: <asynchronous suspension> 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: #5      SvgParser.parse (package:flutter_svg/parser.dart:27) 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: <asynchronous suspension> 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: #6      Svg.fromSvgString (package:flutter_svg/svg.dart:139) 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: <asynchronous suspension> 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: #7      Svg.svgPictureStringDecoder (package:flutter_svg/svg.dart:90) 
Feb 12 14:24:50 base rustdesk[2193862]: flutter: <asynchronous suspension> 
Feb 12 14:24:52 base sudo[2193853]: pam_unix(sudo:session): session closed for user empee584 

```

**Comment by eMPee584** [comment]
Surprisingly, anydesk has the same problem right now when it previously worked. Their hint to
> try disabling "Allow direct connections" [or] adding "/np" at the end [of the ID]

helped.. both devices are connected to an OpenWRT router (phone via wifi, desktop via LAN) but haven't changed the configuration for quite a while.. :thinking:

**Comment by rustdesk** [comment]
> > try disabling "Allow direct connections" [or] adding "/np" at the end [of the ID]

@21pages  let's add this also.

**Comment by rustdesk** [comment]
Could you please test? The new nightly build will be ready soon.

**Comment by eMPee584** [comment]
uum, the `/r` 
![image](https://user-images.githubusercontent.com/1227833/221371253-bcc41ea6-87b4-4dd5-baa1-517d07d6115e.png)
gives ![image](https://user-images.githubusercontent.com/1227833/221370964-0570887f-9b5d-43ac-bf59-dbdc25864af9.png)
with latest nightly on desktop / phone.. i can activate "Always connect via relay" in the menu of the connection though which works.
But trying without relay why does it occasionally work well for more than a minute, then keeps bringing up error 104 instantly on reconnect? This is on a local network, what is going wrong.. is my openwrt b0rked :thinking:

**Comment by rustdesk** [comment]
please try out the new fix

**Comment by GreGNee** [comment]
Installed nightly built on both sides. Still the same error: Deadline has elapsed.
nothing to see in the logs.

And the funny part is, when i shut down the remote pc, the local system sees that it is now offline... so there is some kind of communication. But to establish a connection it's not working.

**Comment by weirdal3333** [comment]
It's late, but those patches did indeed fix the error 104 that I was having.

**Comment by M4rt1n12** [comment]
I also get this error. Rustdesk 1.3.8 on Debian Testing, Plasma with Wayland
