### ISSUE TITLE
文件传输

### ISSUE THREAD

**Issue by Reinering** [rustdesk/rustdesk#1601]
![image](https://user-images.githubusercontent.com/29029467/191746756-ab8877e3-134a-423d-a98a-7c735e8cd409.png)

windows11 下 不显示其他盘

**Comment by 21pages** [comment]
click "/"
![1663849988401](https://user-images.githubusercontent.com/14891774/191747900-de91330a-4b5d-4031-9c10-f6fae22b8e9a.png)
