### ISSUE TITLE
The IP address of the relay server cannot be updated automatically.

### ISSUE THREAD

**Issue by YamatoRyou** [rustdesk/rustdesk#1603]
**Describe the bug you encountered:**
When the IP address of the relay server changes, the client will get stuck at "Accessing RustDesk service" for a long time. Unless the service is manually stopped and restarted on the client side.

**What did you expect to happen instead?**
When the IP address of the relay server changes, the client has the ability to automatically solve the above problems.

**How did you install `RustDesk`?**
1.1.9 for Windows (Portable)

---

**RustDesk version and environment**
Server version: 1.1.6 on Synology DSM 6.2
Self-hosted relay server, dynamic public IPv4 address.

**Comment by rustdesk** [comment]
#751 dup
