### ISSUE TITLE
Input the fourth ID in the input box, and the cursor always jumps back to the previous position

### ISSUE THREAD

**Issue by intionwun** [rustdesk/rustdesk#1605]
**Describe the bug you encountered:**

Input the fourth ID in the input box, and the cursor always jumps back to the previous position

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

GitHub release-Windows portable

---

**RustDesk version and environment**
1.1.9  Windows 10 21H2

**Comment by rustdesk** [comment]
Sorry, can not understand you, upload a video recording please.

**Comment by rustdesk** [comment]
Close this because can not reproduced on our side, and no further report from the other users.
