### ISSUE TITLE
Chat window should persist after window is closed

### ISSUE THREAD

**Issue by bilogic** [rustdesk/rustdesk#1616]
Sometimes remote user has walked away but we want to leave a note.
The chat window should persist even though we have disconnected.

**Comment by rustdesk** [comment]
Finally, I get this requirement.
@21pages

**Comment by bilogic** [comment]
@rustdesk can't help but sense you feel overjoyed haha btw would be good if this can be disabled. Should enable by default.

**Comment by rustdesk** [comment]
@21pages currently, we only persist the message, but window still closed, we need to investigate how the others handle such case.

**Comment by bilogic** [comment]
Since no reply is expected, perhaps 

1. Open another window showing just the last conversation
2. This window has a checkbox that is unticked, "Don't show last conversation after disconnection"
3. If the user doesn't want to see conversations next time, just tick the box

This is really just off the top of my head... should evaluate in a bit more detail thanks

**Comment by rustdesk** [comment]
We follow anydesk behavior.
