### ISSUE TITLE
Segmentation fault when executing with command line argument

### ISSUE THREAD

**Issue by MaxGietl** [rustdesk/rustdesk#1618]
**Describe the bug you encountered:**
when running rustdesk with a command line argument, a segmentation fault happens.
`$ rustdesk foo`
`Segmentation fault (core dumped)`

...

**What did you expect to happen instead?**
rustdesk rejecting or ignoring the argument.
...

**How did you install `RustDesk`?**

https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9.deb
---

**RustDesk version and environment**
RustDesk 1.1.9, Ubuntu 20.04.5 LTS

**Comment by rustdesk** [comment]
we knew

**Comment by MaxGietl** [comment]
Sorry, searched for an issue and couldn't find any

**Comment by abitrolly** [comment]
@rustdesk is there a plan to release the new version with this fix? I am really curious if I can raise verbosity level to troubleshoot connection problems https://www.reddit.com/r/rustdesk/comments/11yc9xd/how_to_troubleshoot_linux_to_windows_connection/
