### ISSUE TITLE
Change color mode

### ISSUE THREAD

**Issue by bigretromike** [rustdesk/rustdesk#1619]
While conneting to really unstable/slow connection lowering number of color would help for stability of the connection (lowe bandwidth). 

I was looking tru client and documentation and didn't found any related settings. Right now Im trying to connect to slow (1 bar windows wifi indicator) laptop and its kicking me like crazy thanks to "full" color connection. In past what wans't a thing with VNC color mode.

**Comment by rustdesk** [comment]
＃1392 dup

**Comment by rustdesk** [comment]
in our milestone
