### ISSUE TITLE
UOS Chinese input

### ISSUE THREAD

**Issue by open-trade** [rustdesk/rustdesk#162]
Not work (chat window)

**Comment by gxon2019** [comment]
在统信uos系统里面，在其它软件里crtl+space可以切换到中文界入法并输入文字，但是在rustdesk软件上，无法切换。即使在系统里设置默认中文，也无法输入。

**Comment by c-smile** [comment]
> https://sciter.com/forums/topic/cant-input-chinese-in-windows-2/#post-73074
> Sciter does not support IME
> @c-smile

That's not correct. IME is supported on Windows and Mac. 
But not Linux at the moment - to many Linuxes and IME mechanisms.

**Comment by rustdesk** [comment]
@c-smile Thanks, you can choose to support the most popular one on Linux, no need to support all.

**Comment by rustdesk** [comment]
@c-smile at the moment, deepin (derived from Ubuntu) is the most popular Linux in China, and it is widely used because of domestic substitution policy.

**Comment by rustdesk** [comment]
my memo

> 1、1.1.6win客户端 托盘图标 停止 启动 停止 启动 会掉中继服务器 1.1.5无此问题
2、1.1.6添加快捷方式后链接的名称不能更新过来 希望能在后续版本得到解决
3、远程对话框中间的ID建议改成备注名称 或者一起显示ID最好
4、主界面ID字太小啦 建议调大点
5、建议后续增加通讯录功能 通讯录内容存在配置文件那里就可以 如有需要 用其他同步软件直接同步到其他电脑
6、建议在通讯录里面增加查找功能
7、建议客户端链接那里显示最近连接客户端 下面显示通讯录
8、建议后续在配置文件里面可以手动选择显示托盘图标跟隐藏托盘图标 个人建议隐藏最好 我看到1.1.4是隐藏的
9、默认链接客户端希望可以自动调节窗口 免得每次都要点调节窗口 还有画面放大后比例最好是自动伸展
10、建议主界面添加一个设置按钮把所有的设置都放在 这个设置按钮里面 以及远程参数的默认设置
11、还有就是连接的默认密码 也放在以上的参数里面 目前好多参数都在配置文件里面 使用起来不方便

**Comment by darcy-shen** [comment]
> 在统信uos系统里面，在其它软件里crtl+space可以切换到中文界入法并输入文字，但是在rustdesk软件上，无法切换。即使在系统里设置默认中文，也无法输入。

这可能是具体某个软件的问题，这类问题我遇到过。我自己的软件，墨干编辑器就有这样的问题。我发现同样一个快捷键，直接在Linux系统里面用是没有问题的。如果我用远程桌面（zoho的远程桌面），那个快捷键就无法识别。

**Comment by rustdesk** [comment]
fixed in nightly build.
