### ISSUE TITLE
My ID Changed Like This pic

### ISSUE THREAD

**Issue by jau1jz** [rustdesk/rustdesk#1630]
**Describe the bug you encountered:**

![image](https://user-images.githubusercontent.com/3905600/192500486-2aa179ec-5f8a-445d-95b1-a46375af22f7.png)

**What did you expect to happen instead?**

i complie code,install 1.2.0,then uninstall 1.2.0,download from homepage 1.1.9

**How did you install `RustDesk`?**

homepage 1.1.9 download

**RustDesk version and environment**
full install,win11 64bit

**Comment by rustdesk** [comment]
Yes, that's expected.

**Comment by rustdesk** [comment]
@21pages this problem is annoying, I think we can create another field in config, e.g. enc_id, we do not change original id field.
