### ISSUE TITLE
How do I rotate the screen? 

### ISSUE THREAD

**Issue by dcx013** [rustdesk/rustdesk#1634]
**Describe the bug you encountered:**
How do I rotate the screen? When I connect an Android device, the top of the screen is facing left, but the top of the input control is facing up
...

**What did you expect to happen instead?**
rotate the screen
...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**
RustDesk 1.1.9
windows 10

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by rustdesk** [comment]
close to favor https://github.com/rustdesk/rustdesk/issues/576
