### ISSUE TITLE
Keyboard is not redirected from MacOS to Windows OS...

### ISSUE THREAD

**Issue by eugenijusrom** [rustdesk/rustdesk#1636]
I'm using MacOS connect to Windows OS with RustDesk. 
After connection established keyboard is not redirected to client. 
When You disable and enable Mouse and Keyboard on client side (in RustDesk) it starts to redirect.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/974#issuecomment-1186577391
