### ISSUE TITLE
Security issue - Logs and Conf files includes cleartext passwords and keys!

### ISSUE THREAD

**Issue by Clouseau68** [rustdesk/rustdesk#1645]
### Discussed in https://github.com/rustdesk/rustdesk/discussions/1644

<div type='discussions-op-text'>

<sup>Originally posted by **Clouseau68** September 29, 2022</sup>
All passwords and keys are shown as cleartext! This may never ever be possible!

Folder:
Config
C:\Users\%User\AppData\Roaming\RustDesk\config
RustDesk.toml
RustDesk2.toml
Logs
C:\Users\%User\AppData\Roaming\RustDesk\log
All log files!

Also you can see your password in the client. That's not good either. If you need to add permannet password it should be differ that this temprorary password. Need to be able to add seperate password for unattanded acces.

All password should be hiddend and show like this: ************

</div>

**Comment by rustdesk** [comment]
fixed in next new release

**Comment by Clouseau68** [comment]
Great! This was fast response!
