### ISSUE TITLE
Duplicate remote discovered entry

### ISSUE THREAD

**Issue by robin-raymond** [rustdesk/rustdesk#1647]
(I am self-hosting using docker/synology and chaned the password for each and always used the password checked "remember password" rather than "accepting" the connection remotely and explicity used the public key)

Installed on Machine A, tried to from iPad. Everything worked. Installed to Machine B. Connected from Machine A to machine B. Worked. Connected from machine B to machine A. Worked. But I notice on Machine B, in the "discovered" tab I have two Machine entries for machine A. I installed on machine C. Every other machine sees Machine B once, but machine A is also twice on Machine C under the "discovered" tab.

I'm not sure how to purge the duplicate entry (or why there's a duplicate entry in the first place for machine A). 

...

Only one machine A should be present in the "discovered" tab.

...

**How did you install `RustDesk`?**

Windows installer 64-bit. Latest release as of today.

---

Windows 64-bit; rustdesk 1.1.9

Local LAN. Synology running docker using the rustdesk registered hbbs/hbbr service (which appears to be working well).

**Comment by rustdesk** [comment]
seems fixed in nightly build.
