### ISSUE TITLE
Compile on MacOs 11 (M1) fails

### ISSUE THREAD

**Issue by diegotibi** [rustdesk/rustdesk#165]
I've followed the build instructions, but I can't go thorught this error.

Here's the complete log:

cargo run --verbose
       Fresh cfg-if v1.0.0
       Fresh autocfg v1.0.1
       Fresh unicode-xid v0.2.2
       Fresh rand_core v0.4.2
       Fresh autocfg v0.1.7
       Fresh cfg-if v0.1.10
       Fresh adler v1.0.2
       Fresh regex-syntax v0.6.24
       Fresh glob v0.3.0
       Fresh gimli v0.23.0
       Fresh lazy_static v1.4.0
       Fresh termcolor v1.1.2
       Fresh rustc-demangle v0.1.18
       Fresh version_check v0.1.5
       Fresh object v0.23.0
       Fresh quick-error v1.2.3
       Fresh unicode-width v0.1.8
       Fresh vec_map v0.8.2
       Fresh strsim v0.8.0
       Fresh siphasher v0.2.3
       Fresh ansi_term v0.11.0
       Fresh shlex v0.1.1
       Fresh rustc-hash v1.1.0
       Fresh lazycell v1.3.0
       Fresh peeking_take_while v0.1.2
       Fresh pkg-config v0.3.19
       Fresh pin-project-lite v0.2.6
       Fresh futures-core v0.3.14
       Fresh futures-sink v0.3.14
       Fresh dasp_sample v0.11.0
       Fresh serde v0.9.15
       Fresh slab v0.4.3
       Fresh itoa v0.3.4
       Fresh scopeguard v1.1.0
       Fresh futures-io v0.3.14
       Fresh dtoa v0.4.8
       Fresh smallvec v1.6.1
       Fresh pin-utils v0.1.0
       Fresh once_cell v1.7.2
       Fresh futures-task v0.3.14
       Fresh version_check v0.9.3
       Fresh foreign-types-shared v0.1.1
       Fresh bytes v1.0.1
       Fresh ppv-lite86 v0.2.10
       Fresh dasp_ring_buffer v0.11.0
       Fresh block v0.1.6
       Fresh humantime v2.1.0
       Fresh void v1.0.2
       Fresh byteorder v1.4.3
       Fresh platforms v0.2.1
       Fresh mio-named-pipes v0.1.7
       Fresh yansi v0.5.0
       Fresh unescape v0.1.0
       Fresh opaque-debug v0.3.0
       Fresh itoa v0.4.7
       Fresh unicode-segmentation v1.7.1
       Fresh machine-uid v0.2.0
       Fresh dispatch v0.2.0
       Fresh instant v0.1.9
       Fresh rand_core v0.3.1
       Fresh addr2line v0.14.1
       Fresh textwrap v0.11.0
       Fresh humantime v1.3.0
       Fresh phf_shared v0.7.24
       Fresh futures-channel v0.3.14
       Fresh lock_api v0.4.4
       Fresh dasp_frame v0.11.0
       Fresh dasp_window v0.11.1
       Fresh foreign-types v0.3.2
       Fresh libc v0.2.94
       Fresh proc-macro2 v1.0.26
       Fresh memchr v2.4.0
       Fresh bitflags v1.2.1
       Fresh log v0.4.14
       Fresh rand_xorshift v0.1.1
       Fresh rand_isaac v0.1.1
       Fresh rand_hc v0.1.0
       Fresh proc-macro-hack v0.5.19
       Fresh phf v0.7.24
       Fresh proc-macro-nested v0.1.7
       Fresh serde v1.0.125
       Fresh protobuf v3.0.0-pre (https://github.com/stepancheg/rust-protobuf#bbe35a98)
       Fresh core-foundation-sys v0.8.2
       Fresh typenum v1.13.0
       Fresh dasp_peak v0.11.0
       Fresh dasp_rms v0.11.0
       Fresh dasp_interpolate v0.11.0
       Fresh dasp_slice v0.11.0
       Fresh winapi v0.3.9
       Fresh anyhow v1.0.40
       Fresh crc32fast v1.2.1
       Fresh ryu v1.0.5
       Fresh jobserver v0.1.22
       Fresh quote v1.0.9
       Fresh atty v0.2.14
       Fresh aho-corasick v0.7.18
       Fresh rand_os v0.1.3
       Fresh rand_jitter v0.1.4
       Fresh num_cpus v1.13.0
       Fresh getrandom v0.2.2
       Fresh malloc_buf v0.0.6
       Fresh parking_lot_core v0.8.3
       Fresh signal-hook-registry v1.3.0
       Fresh dirs-sys v0.3.6
       Fresh dirs-sys-next v0.1.2
       Fresh socket2 v0.3.19
       Fresh filetime v0.2.14
       Fresh time v0.1.43
       Fresh darwin-libproc-sys v0.1.2
       Fresh mach v0.3.2
       Fresh core-foundation-sys v0.6.2
       Fresh whoami v1.1.2
       Fresh rpassword v5.0.1
   Compiling sciter-rs v0.5.53 (/Users/ceres/rustdesk/libs/rust-sciter)
       Fresh miniz_oxide v0.4.4
       Fresh nom v4.2.3
       Fresh num-traits v0.2.14
       Fresh mio v0.7.13
       Fresh nix v0.19.1
       Fresh nix v0.17.0
       Fresh rand_chacha v0.1.1
       Fresh rand_pcg v0.1.2
       Fresh protobuf-codegen v3.0.0-pre (https://github.com/stepancheg/rust-protobuf#bbe35a98)
     Running `rustc --crate-name sciter libs/rust-sciter/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type rlib --emit=dep-info,metadata,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="dynamic"' -C metadata=1eeae39b6a83eb8a -C extra-filename=-1eeae39b6a83eb8a --out-dir /Users/ceres/rustdesk/target/debug/deps -C incremental=/Users/ceres/rustdesk/target/debug/incremental -L dependency=/Users/ceres/rustdesk/target/debug/deps --extern lazy_static=/Users/ceres/rustdesk/target/debug/deps/liblazy_static-6a58226798bc48d9.rmeta --extern libc=/Users/ceres/rustdesk/target/debug/deps/liblibc-c831fa18cfd367ff.rmeta`
       Fresh core-foundation v0.9.1
       Fresh toml v0.5.8
       Fresh generic-array v0.14.4
       Fresh cc v1.0.67
       Fresh dasp_envelope v0.11.0
       Fresh miow v0.3.7
       Fresh serde_json v1.0.64
       Fresh syn v1.0.71
       Fresh regex v1.5.2
       Fresh clap v2.33.3
       Fresh objc v0.2.7
       Fresh rand_core v0.6.2
       Fresh uuid v0.8.2
       Fresh parking_lot v0.11.1
       Fresh directories v2.0.2
       Fresh directories-next v2.0.0
       Fresh dirs-next v2.0.0
       Fresh darwin-libproc v0.1.2
       Fresh cexpr v0.3.6
       Fresh flate2 v1.0.20
       Fresh rand v0.6.5
       Fresh num-traits v0.1.43
       Fresh protobuf-codegen-pure v3.0.0-pre (https://github.com/stepancheg/rust-protobuf#bbe35a98)
       Fresh mac_address v1.1.1
       Fresh num-integer v0.1.44
       Fresh core-graphics-types v0.1.1
       Fresh block-buffer v0.9.0
       Fresh digest v0.9.0
       Fresh dasp_signal v0.11.0
       Fresh env_logger v0.7.1
       Fresh futures-macro v0.3.14
       Fresh tokio-macros v1.2.0
       Fresh rand_chacha v0.3.0
       Fresh thiserror-impl v1.0.24
       Fresh serde_derive v1.0.125
       Fresh env_logger v0.8.3
       Fresh objc_id v0.1.1
       Fresh derive_more v0.99.13
       Fresh async-trait v0.1.50
       Fresh phf_generator v0.7.24
       Fresh confy v0.4.1 (/Users/ceres/rustdesk/libs/confy)
       Fresh repng v0.2.2
   Compiling serde_json v0.9.10
   Compiling zstd-sys v1.6.1+zstd.1.5.0
   Compiling hbb_common v0.1.0 (/Users/ceres/rustdesk/libs/hbb_common)
   Compiling chrono v0.4.19
   Compiling libsodium-sys v0.2.6
   Compiling core-graphics v0.22.2
   Compiling runas v0.2.1
     Running `rustc --crate-name serde_json /Users/ceres/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-0.9.10/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C metadata=79dcd633288c9b95 -C extra-filename=-79dcd633288c9b95 --out-dir /Users/ceres/rustdesk/target/debug/deps -L dependency=/Users/ceres/rustdesk/target/debug/deps --extern dtoa=/Users/ceres/rustdesk/target/debug/deps/libdtoa-14e6732d8e5fbcfc.rmeta --extern itoa=/Users/ceres/rustdesk/target/debug/deps/libitoa-617bd1dfc7634f5f.rmeta --extern num_traits=/Users/ceres/rustdesk/target/debug/deps/libnum_traits-103f1462273aa985.rmeta --extern serde=/Users/ceres/rustdesk/target/debug/deps/libserde-7dd813a1301acdd6.rmeta --cap-lints allow`
     Running `rustc --crate-name build_script_build --edition=2018 libs/hbb_common/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C metadata=7131513008fc03bd -C extra-filename=-7131513008fc03bd --out-dir /Users/ceres/rustdesk/target/debug/build/hbb_common-7131513008fc03bd -C incremental=/Users/ceres/rustdesk/target/debug/incremental -L dependency=/Users/ceres/rustdesk/target/debug/deps --extern protobuf_codegen_pure=/Users/ceres/rustdesk/target/debug/deps/libprotobuf_codegen_pure-3142143ab310ee13.rlib`
     Running `/Users/ceres/rustdesk/target/debug/build/zstd-sys-d34e468130b1fd2b/build-script-build`
     Running `rustc --crate-name chrono /Users/ceres/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --cfg 'feature="clock"' --cfg 'feature="default"' --cfg 'feature="libc"' --cfg 'feature="oldtime"' --cfg 'feature="std"' --cfg 'feature="time"' --cfg 'feature="winapi"' -C metadata=300240e1eb544418 -C extra-filename=-300240e1eb544418 --out-dir /Users/ceres/rustdesk/target/debug/deps -L dependency=/Users/ceres/rustdesk/target/debug/deps --extern libc=/Users/ceres/rustdesk/target/debug/deps/liblibc-c831fa18cfd367ff.rmeta --extern num_integer=/Users/ceres/rustdesk/target/debug/deps/libnum_integer-6197bfb5dc3b0ac8.rmeta --extern num_traits=/Users/ceres/rustdesk/target/debug/deps/libnum_traits-f33c92569ccbcf54.rmeta --extern time=/Users/ceres/rustdesk/target/debug/deps/libtime-78c718ecafacbc48.rmeta --cap-lints allow`
     Running `/Users/ceres/rustdesk/target/debug/build/libsodium-sys-b6b7f83318cdd91d/build-script-build`
     Running `rustc --crate-name core_graphics /Users/ceres/.cargo/registry/src/github.com-1ecc6299db9ec823/core-graphics-0.22.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --cfg 'feature="default"' -C metadata=8624252f2a9737a8 -C extra-filename=-8624252f2a9737a8 --out-dir /Users/ceres/rustdesk/target/debug/deps -L dependency=/Users/ceres/rustdesk/target/debug/deps --extern bitflags=/Users/ceres/rustdesk/target/debug/deps/libbitflags-7e8c35729097e448.rmeta --extern core_foundation=/Users/ceres/rustdesk/target/debug/deps/libcore_foundation-5ef3218507057593.rmeta --extern core_graphics_types=/Users/ceres/rustdesk/target/debug/deps/libcore_graphics_types-c2811ab0e74c52a6.rmeta --extern foreign_types=/Users/ceres/rustdesk/target/debug/deps/libforeign_types-50ae9eea9c0ae293.rmeta --extern libc=/Users/ceres/rustdesk/target/debug/deps/liblibc-c831fa18cfd367ff.rmeta --cap-lints allow`
     Running `/Users/ceres/rustdesk/target/debug/build/runas-f06eb0293aed57e5/build-script-build`
error[E0463]: can't find crate for `objc`
  --> libs/rust-sciter/src/lib.rs:75:14
   |
75 | #[macro_use] extern crate objc;
   |              ^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `sciter-rs`

Caused by:
  process didn't exit successfully: `rustc --crate-name sciter libs/rust-sciter/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type rlib --emit=dep-info,metadata,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="dynamic"' -C metadata=1eeae39b6a83eb8a -C extra-filename=-1eeae39b6a83eb8a --out-dir /Users/ceres/rustdesk/target/debug/deps -C incremental=/Users/ceres/rustdesk/target/debug/incremental -L dependency=/Users/ceres/rustdesk/target/debug/deps --extern lazy_static=/Users/ceres/rustdesk/target/debug/deps/liblazy_static-6a58226798bc48d9.rmeta --extern libc=/Users/ceres/rustdesk/target/debug/deps/liblibc-c831fa18cfd367ff.rmeta` (exit status: 1)
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by iakuf** [comment]
I have the same problem

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/139

**Comment by diegotibi** [comment]
No, it's not the same problem. I've compiled on another machine (Intel based mac) with no problems at all.

It's something due to the fact that M1 cpu is arm based, so the architecture can't be x86.

**Comment by rustdesk** [comment]
then you have to help youself, i have no m1

**Comment by rustdesk** [comment]
@diegotibi please contribute your compilation step on m1 arm after you figure out.

**Comment by diegotibi** [comment]
@rustdesk it's what I'm traying to do... So far the only step I've made is to change "target.x86_64-apple-darwin.dependencies" with "target.'cfg(target_os = "macos")'.dependencies" in libs/rust-sciter/Cargo.toml

The compilation still fails, at least for another reason

**Comment by iakuf** [comment]
> No, it's not the same problem. I've compiled on another machine (Intel based mac) with no problems at all.
> 
> It's something due to the fact that M1 cpu is arm based, so the architecture can't be x86.

my other notebook is ok. it only occur at M1 cpu.

**Comment by diegotibi** [comment]
Now the error is:

Compiling scrap v0.5.0 (/Users/ceres/rustdesk/libs/scrap)
error[E0425]: cannot find value `DLL_NAMES` in this scope
   --> libs/rust-sciter/src/lib.rs:264:17
    |
264 |       let dll = DLL_NAMES.iter()
    |                 ^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `DLL_NAMES` in this scope
   --> libs/rust-sciter/src/lib.rs:346:101
    |
346 |     Err(format!("error: '{}' was not found neither in PATH nor near the current executable.\n  {}", DLL_NAMES[0], msg))
    |                                                                                                     ^^^^^^^^^ not found in this scope

error[E0277]: the size for values of type `[u8]` cannot be known at compilation time
   --> libs/rust-sciter/src/lib.rs:270:15
    |
270 |         .map(|path| try_load(&path))
    |               ^^^^ doesn't have a size known at compile-time
    |
    = help: within `std::path::Path`, the trait `Sized` is not implemented for `[u8]`
    = note: required because it appears within the type `std::path::Path`
help: function arguments must have a statically known size, borrowed types always have a known size
    |
270 |         .map(|&path| try_load(&path))
    |               ^

error: failed to run custom build command for `magnum-opus v0.3.4 (/Users/ceres/rustdesk/libs/magnum-opus)`

Anyone knows where DLL_NAMES comes from? Is it something releted to vcpkg?

**Comment by iakuf** [comment]
I only use rust-sciter, this dir examples can run and is ok.

**Comment by iakuf** [comment]
> Now the error is:
> 
> Compiling scrap v0.5.0 (/Users/ceres/rustdesk/libs/scrap)
> error[E0425]: cannot find value `DLL_NAMES` in this scope
> --> libs/rust-sciter/src/lib.rs:264:17
> |
> 264 | let dll = DLL_NAMES.iter()
> | ^^^^^^^^^ not found in this scope
> 
> error[E0425]: cannot find value `DLL_NAMES` in this scope
> --> libs/rust-sciter/src/lib.rs:346:101
> |
> 346 | Err(format!("error: '{}' was not found neither in PATH nor near the current executable.\n {}", DLL_NAMES[0], msg))
> | ^^^^^^^^^ not found in this scope
> 
> error[E0277]: the size for values of type `[u8]` cannot be known at compilation time
> --> libs/rust-sciter/src/lib.rs:270:15
> |
> 270 | .map(|path| try_load(&path))
> | ^^^^ doesn't have a size known at compile-time
> |
> = help: within `std::path::Path`, the trait `Sized` is not implemented for `[u8]`
> = note: required because it appears within the type `std::path::Path`
> help: function arguments must have a statically known size, borrowed types always have a known size
> |
> 270 | .map(|&path| try_load(&path))
> | ^
> 
> error: failed to run custom build command for `magnum-opus v0.3.4 (/Users/ceres/rustdesk/libs/magnum-opus)`
> 
> Anyone knows where DLL_NAMES comes from? Is it something releted to vcpkg?
you can set this env if vcpkg work under you home dir.
export VCPKG_ROOT=$HOME/vcpkg

**Comment by diegotibi** [comment]
> > you can set this env if vcpkg work under you home dir.
> > export VCPKG_ROOT=$HOME/vcpkg

Yep, already done, the path is ok, maybe there's a missing library, something that's not been ported on arm, I don't know.

In my MacBook, with the same software config (big sur 11.4, brew, vcpkg....) everithing works like a charm.

**Comment by iakuf** [comment]
= note: ld: in /Users/fukai/Documents/data/rust/rustdesk.nosync/target/debug/deps/libscrap-7490b2efe03b6282.rlib(convert_argb.cc.o), archive member 'convert_argb.cc.o' with length 33944 is not mach-o or llvm bitcode for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          
          
 I have a new error message. I use "vcpkg/vcpkg install opus:arm64-osx" to solve opus that doesn`t support arm64 at M1.
 what I can do if I want to make scrap support arm64 ?

**Comment by iakuf** [comment]
error[E0463]: can't find crate for `objc`
  --> libs/rust-sciter/src/lib.rs:75:14
   |
75 | #[macro_use] extern crate objc;
   |              ^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `sciter-rs`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed


if the show as is the error above at macos m1. I modify Cargo.toml, use sciter-rs crate get crates.io, don`t use local dir. the problem is fixed.

**Comment by iakuf** [comment]
error: failed to run custom build command for `magnum-opus v0.3.4 (/Users/Documents/data/rust/rustdesk.nosync/libs/magnum-opus)`

Caused by:
  process didn't exit successfully: `/Users/Documents/data/rust/rustdesk.nosync/target/debug/build/magnum-opus-d1d4fd09c644f155/build-script-build` (exit status: 101)
  --- stdout
  cargo:info=x64-osx
  cargo:rustc-link-lib=opus
  cargo:rustc-link-search=/Users/vcpkg/installed/x64-osx/lib
  cargo:include=/Users/vcpkg/installed/x64-osx/include
  rerun-if-changed=/Users/Documents/data/rust/rustdesk.nosync/libs/magnum-opus/opus_ffi.h
  rerun-if-changed=/Users/vcpkg/installed/x64-osx/include
  cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
  cargo:warning=set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable
  
  and then have new error above. I think that build.rs not correctly the architecture. so i change the build.rs 
  `
  let target =  "arm64-osx".to_owned()
`

**Comment by iakuf** [comment]
Please install the latest vcpkg， Before that, apple M1 will be mistakenly identified as x86_ OSX, the new one will be identified as arm64_ osx.

**Comment by iakuf** [comment]
Now I can compile normally
