### ISSUE TITLE
Preserve file's timestamp at file transfer

### ISSUE THREAD

**Issue by Evgen2** [rustdesk/rustdesk#1653]
Please preserve file's timestamp at file transfer

Seems it is not so  difficult

**Comment by rustdesk** [comment]
@Heap-Hop I remember the timestamp is preserved when I did it, please double check if there is anything broken.

**Comment by Evgen2** [comment]
Just check it.
If I copy file from local to remote - timestamp is preserved, if I copy file from remote to local - timestamp is not preserved.
Both computers are windows hosts

**Comment by rustdesk** [comment]
> check

THanks

**Comment by Heap-Hop** [comment]
@Evgen2 
Hi, I couldn't reproduce.
Could you please give more details?
RustDesk version and OS version
and screenshot of lost timestamp file is better

**Comment by Evgen2** [comment]
RustDesk  version 1.1.9
Remote Windows 11 or Windows 7
Local Windows 7

3 selected files from right  just copy to left

![Rustdesk_data](https://user-images.githubusercontent.com/11079227/195520425-12c9fcfe-8673-40b3-8edb-994e25388250.jpg)
[](url)


Remote Linux
Local Windows 7

hehe.... I can see remote desktop and run applications, but  file transfer dialog show error window "No active console logged on, please connect and logon again.

Ok, go to PuTTY and logon to remote via SSH, reconnect in rustdesk and see again error window 
may the reason is that Rustdesk run another user

**Comment by rustdesk** [comment]
Try out latest nightly build please. will reopen if the issue still appears.
