### ISSUE TITLE
option to see devices that have "remembered passwords to this device" and option to disable them

### ISSUE THREAD

**Issue by test2a** [rustdesk/rustdesk#1669]
Currently, as it stands, if i allow someone to remote INTO my pc and they select "remember password", they can log in or out at any time and i have no way of seeing which remote computer can access MY device and disable them if i want.
There is an active connection indicator at the top right but i don't know if 10 people have access to my machine or 100 and if i wanted to remove their access, i don't think i could do that either. 
This is a big security risk also because if an attacker got into my machine and set "save password", short of removing rustdesk, i can't do that.

There is one "change id" but i suppose then everyone will be wiped clean but that is not really helpful.

**Comment by bmcgonag** [comment]
I like this idea as well. not sure how difficult it is, or where I would prioritize it in all of the other work that's being done, but it's interesting that you could disable the autoconnect function of specific machines that have connected previously.

**Comment by rustdesk** [comment]
unremember added

**Comment by test2a** [comment]
@rustdesk can we know on the app page itself that "these particular machines can automatically connect to your machine. click here to unremember"

**Comment by NNickey** [comment]
As a general idea, if you set a permanent password, you can change that password and they can't connect. It probably would be nice if there was a shared per-device key that could be saved instead and revoke a singular device from being able to unattended connect when necessary etc, but RustDesk doesn't have that for their free release afaik.

But if you never adjusted your RustDesk settings, you can just rotate or reset the temporary password that shows so even if they click 'remember password' with that temporary password, it wouldn't work.
