### ISSUE TITLE
No menu to full exit in windows

### ISSUE THREAD

**Issue by CyrilTaylor** [rustdesk/rustdesk#167]
There is not any menu to full exit in windows setup version

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/38

**Comment by rustdesk** [comment]
will redesign full exit on 1.1.9

**Comment by open-trade** [comment]
and hide tray icon

**Comment by grummbeer** [comment]
> will redesign full exit on 1.1.9

done?

**Comment by rustdesk** [comment]
redesigned in nightly build
