### ISSUE TITLE
Cannot send keystrokes into Bluestacks password field

### ISSUE THREAD

**Issue by bilogic** [rustdesk/rustdesk#1678]
**Describe the bug you encountered:**

```
A. PASS - W10 RustDesk -> W10 RustDesk, BlueStacks' password
B. FAIL - Android RuskDesk -> W10 RustDesk, BlueStacks' password
```
1. Connected from Android RustDesk to Windows RustDesk
2. Tried to type in a password into Bluestacks, only alphabets can be sent through, numbers and .! can't be sent through, not sure what else can't be sent through
3. Sent through is defined as, click on Android's keyboard but does not appear in the Bluestacks app
4. Quite puzzling to me, perhaps the way Android RustDesk is sending non-alphabets?

...

**What did you expect to happen instead?**
I expected the non-alphabetic keystrokes to be received by Bluestacks app

...

**How did you install `RustDesk`?**
GitHub for Windows and Playstore for Android

---

**RustDesk version and environment**
RustDesk v1.1.10-1

**Comment by bilogic** [comment]
Android has this `OS Password` with a pencil icon, what does that do?
Clicking on it, I was able to input numbers, but when I type symbols, e.g. $#$%, an extra space is introduced with each key.

**Comment by rustdesk** [comment]
no resources to work on Bluestacks issues
