### ISSUE TITLE
多屏显示的问题

### ISSUE THREAD

**Issue by lxq** [rustdesk/rustdesk#1680]
**Describe the bug you encountered:**

把远程桌面在第二屏中使用后关闭，下次没有多屏情况下，连接远程成功后的窗口还在原来的第二屏位置，导致无法再使用。

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

**Comment by rustdesk** [comment]
English

**Comment by lxdfly** [comment]
Same issue as lxq

**Comment by rustdesk** [comment]
Try out nightly build please.
