### ISSUE TITLE
vi problem via putty

### ISSUE THREAD

**Issue by TheSquale60** [rustdesk/rustdesk#1681]
**Describe the bug you encountered:**

When I want to use vi in a putty's windows, the arrows doesn't works and replaced by x r t v letters

**What did you expect to happen instead?**

Use arrows

**How did you install `RustDesk`?**

Windows normal

**RustDesk version and environment**

1.1.9 under Windows 10

**Comment by rustdesk** [comment]
@asur4s

**Comment by TheSquale60** [comment]
??

**Comment by TheSquale60** [comment]
Ok, thx

**Comment by TheSquale60** [comment]
Hi,

News?
And now numeric keyboard doesn't works, I have &é"'(-è_ç instead of 123456789

**Comment by rustdesk** [comment]
Try out nightly build, it is updated every day.

**Comment by TheSquale60** [comment]
Ok, thx, I will try

**Comment by TheSquale60** [comment]
Hummm, on my Kali, I can't type anything once connected and I have a window with: Connection Error, the connection has been closed by the peer

**Comment by rustdesk** [comment]
not stable yet, allow us more time.

**Comment by TheSquale60** [comment]
Ok, thx

**Comment by akong77** [comment]
I has try rustdesk 1.2.0 night version.It's the same problem.

**Comment by imadeput0287** [comment]
> @akong77 I've tried the latest nightly build. This issue is fixed with "Map mode". Can you please confirm ? <img alt="20230104201351" width="235" src="https://user-images.githubusercontent.com/13586388/210687377-280d9c3c-568c-470a-a4ce-50fdd347158f.png">

I have try it, but not fixed yet.

**Comment by akong77** [comment]
@imadeput0287 I have install latest nightly build.It's not fixed yet.And use map mode will more question.

**Comment by fufesou** [comment]
@akong77 @imadeput0287 Hi, I've tested both 1.1.9 and ngihtly build.
I can reproduce this issue with 1.1.9.
But "Map mode" seems work fine.

There may be something different.

Did you install the nightly build both sides? And  Win --> Win?

**Comment by akong77** [comment]
@fufesou I will try it both sides.

**Comment by akong77** [comment]
@fufesou I try if both side is use nightly build.It's work fine.But I will try most time.

**Comment by imadeput0287** [comment]
> 

Hi @fufesou I'm sorry, I can't install it on remote side. So I think I can't check it now. I will info if I get remove request again. Thank you

**Comment by imadeput0287** [comment]
I can confirm, both side using 1.2.0 then select Map Mode fix this issue. Thank you.

**Comment by TheSquale60** [comment]
Hi,

Ok, thank you, I will try.

A little question, I told my boss about your solution and he jumped up and down when I told him the solution came from China, he said, we're not going to install a remote control solution from China!!! What do you say?

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by fufesou** [comment]
Please try the nightly build on both sides.
"Modalità legacy" means you are using 1.1.9 on the remote side.

**Comment by albgen** [comment]
> Please try the nightly build on both sides. "Modalità legacy" means you are using 1.1.9 on the remote side.

i already spcified that 1.2.0 (**running on the remote desktop and also on local**)

**Comment by rustdesk** [comment]
Make sure old version is not running and removed.

**Comment by albgen** [comment]
i'm running portable version. You mean to find the settings where are witten?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/4028#discussioncomment-5603873
