### ISSUE TITLE
GPU conflicts

### ISSUE THREAD

**Issue by open-trade** [rustdesk/rustdesk#169]
Remotely opening gpu-related applications will be stuck, such as opening a game program

**Comment by open-trade** [comment]
When remotely to the target computer and operating the game, a pop-up window will be prompted, and then repeatedly connect-disconnect-connect...
![image](https://user-images.githubusercontent.com/42061627/125586313-8744d0f7-27bb-45e5-b66b-c14aea54a539.png)

https://gitee.com/rustdesk/rustdesk/issues/I3WWV4#note_5788609

**Comment by rustdesk** [comment]
another feedback from discord:

> After some test I find a possible reason. That issue would happen when the remote side is mining the cryptocurrency, so it seems a GPU problem? But other RDP software won't run into this issue. Both side in Windows and the latest (1.18) release, direct connection with no relaying node.
