### ISSUE TITLE
error: failed to run custom build command for scrap v0.5.0

### ISSUE THREAD

**Issue by weihaigang** [rustdesk/rustdesk#17]
![image](https://user-images.githubusercontent.com/10528701/114166615-8e67a780-9960-11eb-95d6-c95930e3e266.png)

error: failed to run custom build command for scrap v0.5.0

**Comment by rustdesk** [comment]
vcpkg

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/19

**Comment by QYH2MMT4EVER** [comment]
Have you solved this problem?
