### ISSUE TITLE
Pointer on presentation side while mouse button of remote is pressed.

### ISSUE THREAD

**Issue by FloMaetschke** [rustdesk/rustdesk#1709]
Hey guys, we tried Ruskdesk today and it is amazing.
We often do pair programming using team viewer at the moment and there is a very nice feature.
The other side can point to a location on the screen and its shown with an arrow like using a laser pointer.

The mouse position/click is already transmitted i guess. so all informations are already at the presentation side. 
Instead of giving control, there could be an additional button for allowing presentation or similiar to toggle it on/off.

Would be really nice!

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/2755 https://github.com/rustdesk/rustdesk/issues/3652 #573
