### ISSUE TITLE
macos cannot be controlled when display power save, from windows/ios.

### ISSUE THREAD

**Issue by fisherwei** [rustdesk/rustdesk#1712]
**Describe the bug you encountered:**

1. macos logged in, display power on <-- OK
2. macos locked, but display power on <-- OK
3. macos locked, and display power save <-- windows rustdesk popup: connected waiting for image / ios rustdesk shows a gray screen and not any message.

**What did you expect to happen instead?**

should show login screen

**How did you install `RustDesk`?**

macos: rustdesk-1.1.9.dmg from github
windows: rustdesk-1.1.9-x64.exe from github
ios: from app store

**RustDesk version and environment**

server(controlled): macos rustdesk 1.1.9, macos 12.5.1 @ m1max
client(controller): windows rustdesk 1.1.9 win10, ios rustdesk 1.1.10 ios16.0.2

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/981
