### ISSUE TITLE
win server  ctrl+alt+delete can not use

### ISSUE THREAD

**Issue by shizenghua** [rustdesk/rustdesk#172]
win server  ctrl+alt+delete can not use

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/108

**Comment by rustdesk** [comment]
I forget to add "reg add HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System /f /v SoftwareSASGeneration /t REG_DWORD /d 1" into setup file.
