### ISSUE TITLE
Greek accent mark problems on remote and host pc

### ISSUE THREAD

**Issue by GIKAS123** [rustdesk/rustdesk#1720]
**Describe the bug you encountered:**

Greek accent markers dont work correctly on the remote pc(types <<;ά>> instead of just <<ά>>) and dont work at all on my host pc until I turn off rustdesk

**What did you expect to happen instead?**

Accent markers to work correctly

**How did you install `RustDesk`?**

Github release

**RustDesk version and environment**

1.1.9 on a windows 11 and windows 10 machine

In order to reproduce your issue, please add some information about the environment
in which you're running RustDesk.
My keyboard language is set to Greek (Greece) in both pcs. Note that in the Greek keyboard layout in order to add an accent mark you must first push the ; button on the keyboard (which doesnt make the <<;>> symbol appear when your keyboard language is Greek) and then type the letter you want to accent for example α

**Comment by rustdesk** [comment]
@asur4s

**Comment by asur4s** [comment]
In 1.2.0(unreleased), the accent mark of Greek keyboard work fine. 

BTW, when you update both remote and local machines to the next version of rustdesk (1.2.0), just make sure the remote machine is Greek Keyboard(no need to ensure both remote and local), you will get the correct char, even with the accent mark.

Please look forward to out next version.

**Comment by mikekgr** [comment]
That's a very good new! Is there any way to test the upcoming release 1.2.0 ?
Thanks

**Comment by asur4s** [comment]
Try this, https://github.com/rustdesk/rustdesk/releases/tag/tmp

**Comment by mikekgr** [comment]
THANKS I will try. Changed the client version, is required to change the server version (I running local server installations) or it should work?

**Comment by asur4s** [comment]
It's best to update the server, because 1.2.0 adds some security features and requires the support of the latest server

**Comment by mikekgr** [comment]
So, updating the server break the compatibility with the existing clients 1.1.9?
Do you have new server released or how can get it?
Thanks

**Comment by asur4s** [comment]
The new server still supports the old version of the client

You can get it from https://github.com/rustdesk/rustdesk-server/releases.

**Comment by mikekgr** [comment]
Many thanks. I will test it when at home and report back here.

**Comment by GIKAS123** [comment]
> Linux can try this, https://github.com/rustdesk/rustdesk/releases/tag/tmp
> 
> Other system needs to compile from source.
Im glad to hear that the problem is fixed in the newer version! Is there any tutorial on how to compile this project from source? Or is there a release window for the windows version? Many thanks in advance!

**Comment by GIKAS123** [comment]
Hey!

So I just downloaded the latest nightly build for windows and the accent mark problem persists... Both pcs are using a greek keyboard btw
