### ISSUE TITLE
[Self-Hostet] Can't connect via domain

### ISSUE THREAD

**Issue by Johnnii360** [rustdesk/rustdesk#1725]
**Describe the bug you encountered:**

It is not really a bug, it's a request for help. :)

The problem is that I can connect to my self-hosted server via IP but not via domain. Via domain it stands always on "connecting with Rustdesk network". There is no error in the logs and all ports are allowed on ufw.

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

Via Linux install script mentioned in the tutorial (none Docker).

**RustDesk version and environment**

Server OS: Linux 4.19.0-22-amd64 #1 SMP Debian 4.19.260-1 (2022-09-29) x86_64 GNU/Linux
Rustdesk Server: 1.1.6
Rustdesk Client: 1.1.9

**Comment by rustdesk** [comment]
#763

**Comment by Johnnii360** [comment]
Wow... Really lame. Just closed with a link to a generic site with some information like "use Google you fool there you can find all". And when I google I just get nothing or your sites with very weak information or help. That's the truly downside of the open source community. "You want really help? Pffff, just use Google or pay me for it!" You suck!
