### ISSUE TITLE
Various issues/bugs on Rustdesk Android: File Transfer, Input Control, and so on

### ISSUE THREAD

**Issue by Unknown78** [rustdesk/rustdesk#1729]
Rustdesk Version:

RustDesk Windows Version 1.1.9
RustDesk Android from F-Droid Version 1.1.10-1

Test Device:
Windows 11
Note 4 Android 6.0.1
LG V20 Android 8.0.0

<hr>

File transfer between Windows 11, Note 4 (6.0.1) and LG V20 (8.0.0)

- In the Android APK UI, there's no option to change the Windows drive, its always at C:
- File transfer between Android and Android is working.

Running Rustdesk on Android and connect to Windows:
 - File transfer from Local to Remote doesn't work
    It says "Waiting Speed: 0.0 B/s" and keep stuck in there.
		
- File transfer from Remote to Local doesn't work
   It says "Successful!" but no file has been transfered.

Running Rustdesk on Windows and connect to Android:
- File transfer from Local to Remote is working.
- File transfer from Remote to Local doesn't work.
  It stuck at "0 /1 files". The APK UI Freeze. If I click X to cancel in RustDesk Desktop then tap Home in Android then open The RustDesk APK, it won't crash. But if I don't click X then tap Home in Android then open the Rustdesk APK, it will crash. 
	

<hr>

Input Control

Connect to Note 4 Android 6.0.1
	Mouse and Keyboard Input Control doesn't work. (Accessbility is turned on)
	
Connect to LG V20 Android 8.0.0 
	Only the Mouse Input Control work, I have to use the internal phone keyboard. 
	
<hr>	

Android APK in general:
- Mouse scroll doesn't work, only the scroll button does, which is to press the Home button.
- Clipboard between device doesn't work
- No option to start on boot
- There's no disable remote configuration modification just like in desktop, so anyone could edit the RustDesk APK settings such as password, server key, and so on
- If Power/Battery Saver is turned on, it will cut off the wifi, forcing it to disconnect to the server. Workaround at the moment is to disable it.
- Even if the battery saver is off, it will be disconnect and there will be a timeout message. Although the wifi is not off so you could connect it again, but there should be a feature to set the timeout duration or to disable it.
- Android 10 was released publicly in September 3, 2019. Many old phone won't get any official update anymore. Perfect Custom ROM to replace the Stock ROM is rare, so audio capture is needed for lower version.
- The mouse press isn't continuously correspond with screen tap on the phone, you need to release the mouse button for it to be sent to the phone. This is a major problem for various tap mechanics such as slide/drag movement on the phone, for example the the status bar, it's so difficult to drag it down with the current mechanics.

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by mehdi-song** [comment]
Hi
In Samsung A73 in addition to the problems told , screen size not correct and the bottom of the screen is not seen

**Comment by FCrane** [comment]
I can confirm that File Transfer from Android to Windows 11 does not work - it's stuck at 0b/s. Also, the Windows Client most of the time claims the remote computer is offline, when the RustDesk Service is actually running on the Android machine...

**Comment by mohan43u** [comment]
>     The mouse press isn't continuously correspond with screen tap on the phone, you need to release the mouse button for it to be sent to the phone. This is a major problem for various tap mechanics such as slide/drag movement on the phone, for example the the status bar, it's so difficult to drag it down with the current mechanics.

I confirm this issue, when pressing mouse continuously, I didn't get the menu with "appinfo, uninstall" options, I get this menu only when I release after pressing continuously, this affects when I try to move app icons to group together in a box.

**Comment by rustdesk** [comment]
close to favor #3893
