### ISSUE TITLE
Remote is not saved in recent sessions when address contains port number

### ISSUE THREAD

**Issue by SubhashBose** [rustdesk/rustdesk#1730]
**Describe the bug you encountered:**

The remote is not saved in 'recent sessions' when connecting to a remote computer with non-standard RustDesk port.

For example: Rustdesk on remote computer is configured to accept IP connection at port 21234. Now when connecting to remote using the address 192.168.1.10:21234, the connection is successful but the peer is not saved in the recent sessions list.

I guess this is because RustDesk saves peers' addresses in filenames, and ':' is a disallowed filename character.

**What did you expect to happen instead?**

I expect the remote address with port number is also saved in recent session list as IP:PORT

**How did you install `RustDesk`?**

Windows Portable

**RustDesk version and environment**

Windows, version 1.1.9

**Comment by panoskj** [comment]
In addition, this bug means losing all peer settings, such as image resizing and quality. I thought there was no way to save these settings them, until I tried a non-direct connection, in which case they were saved.
