### ISSUE TITLE
Edge scrolling / auto scroll when cursor is at the session window edge

### ISSUE THREAD

**Issue by ForsakenRei** [rustdesk/rustdesk#1732]
Hey guys, 

I setup my own rrustdesk server recently and it works really good and thank you all for the great work.

The only thing missed a lot from Anydesk is an edge scrolling function, while will scroll automatically up or down when your cursor is at the edge of current session window.
For example, when you connected to a remote with same or larger resolution compared to your screen, in original mode you will not see the taskbar. If the remote screen has more to show and your cursor is at the bottom edge or current session window, it will automatically scroll down till the bottom of remote screen.

I know there are fullscreen mode and scroll bars, but it would be more convenient if we have a similar edge scroll to make the workflow more seamlessly without moving to the scroll bar everytime. It's not something urgen, but good to have.

**Comment by rustdesk** [comment]
ready in new version，please wait for the release
