### ISSUE TITLE
macos - rustdesk v1.1.9 can not input anything by keyboard

### ISSUE THREAD

**Issue by foundworld** [rustdesk/rustdesk#1735]
**Describe the bug you encountered:**
two desktop, one is MacBook Pro (macos 12.6), another one is Mac mini (macos 12.6). Both are installed Rustdesk v1.1.9, the Mac mini as the remote desktop, MacBook Pro as the client. After connected between them, the Mac mini can response mouse event, but can't response keyboard event when input anything from MacBook Pro side.

I reinstall RustDesk v1.1.8 in MacBook Pro, keep RustDesk v1.1.9 in Mac mini, it works!
...

**What did you expect to happen instead?**
RustDesk v1.1.9 in macOs can accept keyboard input event.
...

**How did you install `RustDesk`?**
I downloaded RustDesk v1.1.9 （rustdesk-1.1.9.dmg) for macos from official site https://www.rustdesk.com.

---

**RustDesk version and environment**

RustDesk v1.1.9 in macOS 12.6

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/974#issuecomment-1186577391
