### ISSUE TITLE
Support and optimize for bluetooth Mouse and Keyboard native operations (strengthen physical Keyboard / mouse support)

### ISSUE THREAD

**Issue by MuelNova** [rustdesk/rustdesk#1739]
#116 also mentioned it.

On the latest version by now ( which are `Version 1.1.9 (windows)`, `Version 1.1.10 (IOS)` and `Version 1.1.6 (linux server)` ) on my iPad (`IOS 15.7`), the bluetooth mouse and keyboard work pretty bad:
- I can't use my bluetooth mouse to click ( sometime it works when I double-click it ), let alone the right click, middle click or dragging, scroll.
- My bluetooth keyboard will input 2 keys each time when I press it, windows and ctrl shift keys work though. ( as far as I'm concered, it may because that there were some lagging between `key press` and `key up` commands, which caused multiple chars inputted. )

I'm not sure if Android has this problem too, with now `rustdesk` is getting much more stable, I think this feature should be supported with high priority as it really helps those who want to take effective work.

Thanks for your works.

**Comment by Nova-Noir** [comment]
as far as I know, both `ToDesk` and `Steam Link` are fully bluetooth mouse and keyboard supported, so this is technically workable, sorry that I can't make any works around due to the lack of rust / web programming skills.

**Comment by rustdesk** [comment]
dup

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1466

**Comment by rustdesk** [comment]
Yes, you are right, bluetooth Mouse and Keyboard is not in our priority before we polish desktop.

**Comment by rustdesk** [comment]
Try out nightly build
