### ISSUE TITLE
Add Linux ARM support

### ISSUE THREAD

**Issue by hmsjy2017** [rustdesk/rustdesk#175]
I want to run RustDesk on the Raspberry Pi, but I was disappointed to find that it does not work on the ARM architecture. I hope you can add support for the ARM platform (including the server version). Thanks.

**Comment by rustdesk** [comment]
Where can I buy a Raspberry Pi for free? :)

**Comment by hmsjy2017** [comment]
@rustdesk You can use QEMU to compile RustDesk and it is free. In addition, rust supports cross-compilation.

**Comment by hmsjy2017** [comment]
@rustdesk Travis CI already supports building on the arm64 architecture. I think it might be a good choice to use Travis CI to compile the arm version of RustDesk.

**Comment by rustdesk** [comment]
I am waiting for new M1 release.

**Comment by walfud** [comment]
> I am waiting for new M1 release.

so, is it time to support arm64? :)

**Comment by rustdesk** [comment]
Sorry for your long waiting. I will try QEMU.

**Comment by rustdesk** [comment]
But which Linux distro?

**Comment by hmsjy2017** [comment]
@hmsjy2017 Debian.

**Comment by Heap-Hop** [comment]
I tried to build RustDesk on Raspberry Pi4(Ubuntu-ARM64) and Raspberry Pi3(Raspbian OS-ARM32).
Unfortunately,both failed.

For Pi4(test on Linux ARM64):
From the code and README:
> Desktop versions use **sciter** for GUI......

sciter-sdk only provides the _libsciter-gtk.so_ build on x64 / ARM32 , they didn't release arm64 for linux yet.
[libsciter-gtk.so doesn't support in ARM64 platform #210](https://github.com/c-smile/sciter-sdk/issues/210)
We can't build on ARM64 unless sciter-sdk provides the .so someday.


For Pi3(test on Linux ARM32):
_libsciter-gtk.so_ maybe fine.
but I can't build success vcpkg on Raspbian OS-ARM32.
So I build the three libs _libvpx libyuv opus_ from those offical source code,then I put them in vcpkg/installed/arm-linux/ 
and _cargo build_
......a very long build time...... 
all rust crates and lib passed the compilation,but finally failed on maybe some gcc/link problem:
![2021-12-21 20-44-39屏幕截图](https://user-images.githubusercontent.com/62206297/146932228-c9e36c20-2496-41e3-8004-51b7c5e1c594.png)
...
![2021-12-21 20-45-29屏幕截图](https://user-images.githubusercontent.com/62206297/146932277-e88fd7a2-eb20-48c6-9415-be20761fcf34.png)

Im not good at gcc compiling and linking,I cant understand these problem...

I think it's not ready to support Raspberry Pi(Linux ARM) yet.

**Comment by rustdesk** [comment]
https://stackoverflow.com/questions/19768267/relocation-r-x86-64-32s-against-linking-error

**Comment by rustdesk** [comment]
> > I am waiting for new M1 release.
> 
> so, is it time to support arm64? :)

You need ask Sciter author support arm64 first. Because RustDesk depends on Sciter. https://github.com/c-smile/sciter-sdk/issues/210

**Comment by avently** [comment]
@rustdesk what about support without ui, just a server mode?

**Comment by rustdesk** [comment]
> just a server mode

PR please.

**Comment by dimaguy** [comment]
Since Sciter does arm32, wouldn't it be possible to at least create an arm32 build for the time being? arm64 is backwards compatible with it

**Comment by rustdesk** [comment]
I will try to find one arm machine.

**Comment by dimaguy** [comment]
> I will try to find one arm machine.

Dude you don't need an arm machine, qemu will do just fine for you

**Comment by rustdesk** [comment]
Where can I find an Ubuntu 16 arm desktop iso?

**Comment by dimaguy** [comment]
Also maybe you could just create some compilation instructions so I could test it on my raspberry pi and give you feedback?

**Comment by busyluo** [comment]
> @Heap-Hop tested today on Pi4, performance is bad, and failed to get vpx encoder work. We paused to invest time on it. Will continue once we are free.

How did you test it with SCiter not supporting AARCH64

**Comment by Heap-Hop** [comment]
@busyluo we tested on arm32

**Comment by wwjabc** [comment]
I have successfully compiled RustDesk on armHF and AARM64, running in service state without UI. Arm runs Ubuntu18.04. TCP penetration is available to use SSH services.
我已经成功在armhf和aarm64上编译了rustdesk。运行于服务状态，没有UI。Arm跑的是Ubuntu18.04.可以进行TCP穿透来使用SSH服务。

**Comment by rustdesk** [comment]
> I have successfully compiled RustDesk on armhf and aarch64, running in service state without UI. Arm runs Ubuntu18.04. TCP penetration is available to use SSH services. 我已经成功在armhf和aarch64上编译了rustdesk。运行于服务状态，没有UI。Arm跑的是Ubuntu18.04.可以进行TCP穿透来使用SSH服务。

Good job.

**Comment by rustdesk** [comment]
> I have successfully compiled RustDesk on armhf and aarch64, running in service state without UI. Arm runs Ubuntu18.04. TCP penetration is available to use SSH services. 我已经成功在armhf和aarch64上编译了rustdesk。运行于服务状态，没有UI。Arm跑的是Ubuntu18.04.可以进行TCP穿透来使用SSH服务。

If possible, can you write a tutorial?

**Comment by rustdesk** [comment]
> > I have successfully compiled RustDesk on armhf and aarch64, running in service state without UI. Arm runs Ubuntu18.04. TCP penetration is available to use SSH services. 我已经成功在armhf和aarch64上编译了rustdesk。运行于服务状态，没有UI。Arm跑的是Ubuntu18.04.可以进行TCP穿透来使用SSH服务。
> 
> If possible, can you write a tutorial?

**Comment by wwjabc** [comment]
> > I have successfully compiled RustDesk on armhf and aarch64, running in service state without UI. Arm runs Ubuntu18.04. TCP penetration is available to use SSH services. 我已经成功在armhf和aarch64上编译了rustdesk。运行于服务状态，没有UI。Arm跑的是Ubuntu18.04.可以进行TCP穿透来使用SSH服务。
> 
> If possible, could you please write a tutorial on https://github.com/rustdesk/doc.rustdesk.com?

I'll try. Wait for me. Haha

**Comment by rustdesk** [comment]
> I'll try.

Respect!!!

**Comment by wwjabc** [comment]
![image](https://user-images.githubusercontent.com/102203060/168975030-6358d2db-ded8-4140-93ec-e0c94d3f3fd0.png)
I added a new folder that shows 404.
![image](https://user-images.githubusercontent.com/102203060/168975286-7a952d34-08dc-42c2-ac22-6e833e0d80b1.png)

**Comment by rustdesk** [comment]
You need PR first. Because our repo has no t his page before your PR.

**Comment by rustdesk** [comment]
https://rustdesk.com/docs/en/dev/build/armhf/

**Comment by wwjabc** [comment]
> https://rustdesk.com/docs/en/dev/build/armhf/, Thanks @wwjabc

I'm still working on it, so I'm going to redo it from scratch to make sure it's functional.
还在进行编写中，我从头开始重做一遍，确保能功能复现。（英文是有道翻译的，不准确的地方别怪我了）

**Comment by rustdesk** [comment]
> > https://rustdesk.com/docs/en/dev/build/armhf/, Thanks @wwjabc
> 
> I'm still working on it, so I'm going to redo it from scratch to make sure it's functional. 还在进行编写中，我从头开始重做一遍，确保能功能复现。（英文是有道翻译的，不准确的地方别怪我了）

I modified and added English version.

**Comment by wwjabc** [comment]
> > > https://rustdesk.com/docs/en/dev/build/armhf/, Thanks @wwjabc
> > 
> > 
> > I'm still working on it, so I'm going to redo it from scratch to make sure it's functional. 还在进行编写中，我从头开始重做一遍，确保能功能复现。（英文是有道翻译的，不准确的地方别怪我了）
> 
> I modified and added English version.

That's too fast! But you can handle it when I'm done.

**Comment by wwjabc** [comment]
> > > https://rustdesk.com/docs/en/dev/build/armhf/, Thanks @wwjabc
> > 
> > 
> > I'm still working on it, so I'm going to redo it from scratch to make sure it's functional. 还在进行编写中，我从头开始重做一遍，确保能功能复现。（英文是有道翻译的，不准确的地方别怪我了）
> 
> I modified and added English version.

The tutorial is almost done, and I'll just add some tests at the end.
教程基本写完，最后我再补充点测试就好了。

**Comment by rustdesk** [comment]
Thanks, English also please. :)

**Comment by wwjabc** [comment]
> Thanks, English also please. :)

Your translation is good!

**Comment by dimaguy** [comment]
I'm not quite sure whether it is a good idea to use Ubuntu's rootfs, especially from a source like baidu. Maybe make it a docker container build using the official images?

**Comment by rustdesk** [comment]
> I'm not quite sure whether it is a good idea to use Ubuntu's rootfs, especially from a source like baidu( good luck translating this -> ![image](https://user-images.githubusercontent.com/7207103/169067896-f005efd1-8235-4def-877e-3901acae5b5a.png) ). Maybe make it a docker container build using the official images? Running random builds of libvpx and opus doesn't exactly sound good either

Talking is cheap, please take action. Our doc is open source.

**Comment by rustdesk** [comment]
It comes from contributors, I think we should respect everyone's work.

**Comment by dimaguy** [comment]
Don't you always take internet strangers' word at face value, it's a bad idea for you and for those who depend on you

**Comment by dimaguy** [comment]
This would've all been a little less problematic, if at least the contributor had some track record, which he DOESN'T HAVE, literally that account has only interacted with your repos, and nothing else

**Comment by dimaguy** [comment]
> Ok, you persuaded me.

What you going to do then? Redo the docs to be more trustable(changing the ubuntu thing to docker and fetching sources instead of binaries)? Erase the page overall until another knight in shining armor comes and does your job?

**Comment by rustdesk** [comment]
@wwjabc since you have added libvpx/opus compilation steps, I will remove the baidu download links. and I will also replace ubuntu18.04_rootfs.tar.gz with an official image.

**Comment by BlackDragon-B** [comment]
For god sake. https://hub.docker.com/r/arm32v7/ubuntu
Make it build with docker instead. It's way more safe and should be more trustable.

**Comment by rustdesk** [comment]
@wwjabc Sorry, it is my fault to ask you for doc and cause you trouble.

**Comment by dimaguy** [comment]
> @wwjabc since you have added libvpx/opus compilation steps, I will remove the baidu download links. and I will also replace ubuntu18.04_rootfs.tar.gz with an official image. Wondering if this link https://github.com/ikwzm/ZynqMP-FPGA-Ubuntu18.04-Ultra96/blob/master/doc/build/ubuntu18.04-rootfs.md is correct?

Using rootfs is bad overall, if you get a docker image going you make it possible to do it from existing installs, it's way less bothersome for anyone following the instructions

**Comment by BlackDragon-B** [comment]
Instead of deleting every comment. You are aware that you can lock conversations right? https://docs.github.com/en/communities/moderating-comments-and-conversations/locking-conversations

**Comment by dimaguy** [comment]
> Instead of deleting every comment. You are aware that you can lock conversations right? https://docs.github.com/en/communities/moderating-comments-and-conversations/locking-conversations

That only serves to make it read only, the dev wants to avoid being fully transparent at all costs, because he doesn't want people to know that he fell on the cheapest social engineering trick possible

**Comment by rustdesk** [comment]
Try out [raspberry-armhf.deb](https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-raspberry-armhf.deb) please.
