### ISSUE TITLE
Virtual_display can not run on Windows7

### ISSUE THREAD

**Issue by Baker9017** [rustdesk/rustdesk#1752]
**Describe the bug you encountered:**

After complier all the code on Winodws 10, it can run well on all the Windows 10. But it can not run on Windows 7.
Error report as below

```
RustDesk.exe -- Entry Point Not Found

The procedure entry point SwDeviceCreate count not located in the dynamic link library CFGMGR32.dll.
```

I found the problem probably related to Virtual_display. Win7 can't call the function of SwDeviceCreate.

```
\libs\virtual_display\src\win10\IddController.c : line 239

// Create the device
    HRESULT hr = SwDeviceCreate(L"RustDeskIddDriver",
        L"HTREE\\ROOT\\0",
        &createInfo,
        0,
        NULL,
        CreationCallback,
        &hEvent,
        hSwDevice);
    if (FAILED(hr))
    {
        SetLastMsg("SwDeviceCreate failed with 0x%lx\n", hr);
        if (g_printMsg)
        {
            printf(g_lastMsg);
        }

        return FALSE;
    }

```
**What did you expect to happen instead?**

Win 7 doesn't support the feature of virual_display,  whether we can add a condition,
 if os == windows7  
            call the legacy method instead of call 'SwDeviceCreate'

**How did you install `RustDesk`?**

Build curren code and run it directly.

---

**RustDesk version and environment**

1.2.0 Windows7

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
No idea either.
