### ISSUE TITLE
"No monitor" error then display is turned off

### ISSUE THREAD

**Issue by mehelme** [rustdesk/rustdesk#1756]
Hi and thanks for rustdesk !

Target host is ubuntu 2204 with nvidia card connected to 4k monitor "samsung" via "display port" cable
All works fine until monitor is turned off 
Tried both ubuntu and windows clients

Another target host is ubuntu 2004 with nvidia card connected to fullhd monitor "dell" via hdmi cable - all work fine even with monitor turned off

**Comment by rustdesk** [comment]
RustDesk needs monitor

**Comment by rustdesk** [comment]
We have some virtual display implementation before, but unstable, then we paused.

**Comment by rustdesk** [comment]
#59 #1131

**Comment by mehelme** [comment]
can you little describe what the problem then monitor turned off ?
what is difference inside OS or somewhere between "monitor off" and "monitor power suspended" ?
