### ISSUE TITLE
Cannot hold down ctrl, option, cmd, and shift keys from windows to mac

### ISSUE THREAD

**Issue by jeffli95** [rustdesk/rustdesk#1765]
**Describe the bug you encountered:**

I am connecting from windows 10 machine to macOS (Monterey 12.6) host. When I hold down any of the modifier keys (mentioned in the title) the host machine interprets it as me repeatedly clicking on the keys. This prevents me from performing certain actions like cmd + tab to switch apps.

**What did you expect to happen instead?**

I expect that holding down a modifier key from my windows machine to also be held down on macOS machine. 

**How did you install `RustDesk`?**

downloaded binary from https://rustdesk.com/ on both devices

**RustDesk version and environment**

version 1.1.9 on both devices

**Comment by rustdesk** [comment]
@asur4s

**Comment by asur4s** [comment]
Fixed in #1032
