### ISSUE TITLE
Add Contact List / Computer list 

### ISSUE THREAD

**Issue by Swiftgti** [rustdesk/rustdesk#177]
Like TeamViewer it’s super necessary to have a shared list of computers through our working collages of the support team. 
it’s possible to add this feature?, adding this is the definitive Remote Desktop solution.

**Comment by rustdesk** [comment]
local or cloud?

**Comment by Swiftgti** [comment]
Hi, will be a bombshell if it’s cloud like Anydesk or TeamViewer, sharing the list of computer is essential. If you got that, it’s the real replacement of TeamViewer. 
also it will be necessary for company’s  that give support to their customers, a custom installer, that when is installed by the client automatically that pc appears in this cloud list of computers, without the need of password or id’s sent by the client. 

If you can’t do it cloud…. At list add an http server to the rdp client so via an http api it’s possible to integrate and automate tasks from a web browser. 
if it bind to listening to localhost ip (127.0.0.1), port ( example 8080) we can create a separate cloud for sharing contacts and interact with the rdp and the web browser via this http api of the rdp client 

Did you like it ??
Have a nice weekend

**Comment by omriasta** [comment]
+1 for this, yes the address book should definitely be maintained on the "servers" and also include online status of clients.

Also curious regarding the "Discovered" tab, if I am running my own server, shouldn't any connected client be "Discovered" since the server should be aware of all clients which are registered and online? I believe right now it only shows other clients on the same subnet.

Also agree with custom installers, this would also provide a way to "lock" the settings from regular users. In other words, if the admin installs this on a windows or linux machine, the user can not change id or relay server or even stop the service. That way the limited users can't turn off access for the admins.

**Comment by bigretromike** [comment]
+1 for Address Book stored on server with login/password.
Saw it's `planned` as it even have its own port in documentation.

Very needed, and if so with ability to "group" those contacts via folders or so.

**Comment by MichaelF25** [comment]
@rustdesk The Address Book is the only missing feature which blocks us from replacing TeamViewer with your solution. Of course we would also pay for Rustdesk if there is for example a commercial edition available.

**Comment by rustdesk** [comment]
> @rustdesk The Address Book is the only missing feature which blocks us from replacing TeamViewer with your solution. Of course we would also pay for Rustdesk if there is for example a commercial edition available.

Coming soon

**Comment by bigretromike** [comment]
would be nice to have it

**Comment by jammin1911** [comment]
> course we would also pa



> > @rustdesk The Address Book is the only missing feature which blocks us from replacing TeamViewer with your solution. Of course we would also pay for Rustdesk if there is for example a commercial edition available.
> 
> Coming soon

+1 from me on this.  Out of curiosity, is this like an elon musk type of "Coming Soon™" or do you think we might see this within a couple months yet?

**Comment by try2hack** [comment]
can rustdesk have access control list like Anydesk?

**Comment by YamiYukiSenpai** [comment]
What version of Rust Desk is needed to be able to access this?

saw that it was competed last week (at the time of writing).

**Comment by bigretromike** [comment]
any doc about this ?

**Comment by rene-bayer** [comment]
The address book should really be available to everyone ... at least for personal use (without sync).
9,90/month is to much for my personal use case, only for the address book

**Comment by rustdesk** [comment]
https://rustdesk.com/pricing.html
