### ISSUE TITLE
failed to install deb package on pop os with Eddy app

### ISSUE THREAD

**Issue by bitfanatic** [rustdesk/rustdesk#1771]
**Describe the bug you encountered:**
after download deb package i tried to install with eddy (some sort of deb installeron pop os)
when trying toinstal with eddy i got an error (installation failed: Child process exited with code 100)

dont know if this is something with the deb package just my experience trying to install 

**What did you expect to happen instead?**
i expected the install to finish and be working 
...

**How did you install `RustDesk`?**
i didnt

---

**RustDesk version and environment**
1.19

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/1477
