### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by classicalguy** [rustdesk/rustdesk#1775]
This is a great program, but I am having a couple of issues.  
1.  Is there a way to have the application load on reboot and be ready to receive connections, both on windows and android?  Having to physically run the app each time doesn't work well for remote access when no one is waiting for the connection on the other end.  
2. My 96 year old mother needs help with her android cellphone and it is very hard for her to run the app, go to share screen, hit start service,  and say "ok" to the warning, before I can get in to help her.  This would be a lot easier if we could bypass all of the warnings after the first (or a few) times, and run directly.  Is this possible?
3. Is there no way to change the name of computers that have previously been connected on Android like there is on Windows?
Thanks all.

**Comment by rustdesk** [comment]
We know, but we do not know how to implement.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/1330
