### ISSUE TITLE
Better way to mouse scroll than three-finger on phone

### ISSUE THREAD

**Issue by Anutrix** [rustdesk/rustdesk#1776]
Sliding 3 fingers to scroll makes it very hard. Especially on large monitors. Also, most phones have 3 finger as some gestures like multi-window activation which often interferes with RustDesk.

Make 2 finger slide to scroll instead like most touch pads do.

**Comment by rustdesk** [comment]
Sorry, we have considered this problem, but eventually we chose current implementation.

**Comment by Anutrix** [comment]
But what about atleast adding support to make this actions customisable?

**Comment by YasharSL** [comment]
Same problem here, most android devices have already configured 3-finger gesture and the inability to customize the inputs, causes a lot of hassle

**Comment by HuaLun666** [comment]
I encountered a similar problem. My device (Redmi Pad Pro) has turned off three finger gestures, but still cannot use the mouse wheel. I would like to add custom options.
