### ISSUE TITLE
Keyboard not working correctly when local machine and remote machine are using differnt keyboard layouts

### ISSUE THREAD

**Issue by Giorgio-Banani** [rustdesk/rustdesk#1780]
Local machine US-Laptop running Windows 11, English Keyboard layout
Remote machine DE-Laptop running Windows 11, German Keyboard layout

When typing @ for example on the local machine, it will not get transferred to the remote machine.
When i change the remote machine to the same US-keyboard layout, everthing works fine.

Conclusion: RustDesk is not transferring the correct ASCI-Code, but instead emulates the keyboard imput. This is not working for different keyboard layouts.

**Comment by rustdesk** [comment]
@asur4s can translate mode work in this case?

**Comment by Giorgio-Banani** [comment]
translate mode? i checked every menu for that option and couldn't find it.

**Comment by asur4s** [comment]
> @asur4s can translate mode work in this case?

Yes

**Comment by asur4s** [comment]
> translate mode? i checked every menu for that option and couldn't find it.

Translate mode is a new keyboard mode that relies on char which generated on the client. The current keyboard mode is based on key position.

**Comment by demelev** [comment]
@Giorgio-Banani rustdesk currently looks for KEYBOARD_MODE environment variable.
'translate mode' will be activated if environment variable KEYBOARD_MODE is set to 'translate'

**Comment by michaeldrob** [comment]
> KEYBOARD_MODE
Is this something that needs to be set on the relay server? or can clients set this? I am also having keyboard issues between a mac and a pc. if on the relay , would that be hbbs or hbbr?

**Comment by rustdesk** [comment]
closed as no response.
