### ISSUE TITLE
Rustdesk Nightly build 1.2 windows

### ISSUE THREAD

**Issue by giuliovale** [rustdesk/rustdesk#1781]
Rustdesk fail to start because not find any *.dll files

**Comment by rustdesk** [comment]
@Kingtous

**Comment by Kingtous** [comment]
any screenshots?

or can u check if this location exists and files are all placed in there `after` click .exe once:
`C:\Users\YourUserName\AppData\Local\rustdesk`

**Comment by giuliovale** [comment]
If i start rustdesk from exe inside \AppData\Local\rustdesk there is no problem

If I start rustdesk from Start icon or from icon on desktop there is fail message with miss *.dll

**Comment by Kingtous** [comment]
> any screenshots or logs?
> 
> or u can check if this location exists and files are all placed in there `after` click .exe once: `C:\Users\YourUserName\AppData\Local\rustdesk`
> 
> Thanks for the feedback and looking for your kind reply :)

Thanks, lets fix it.

**Comment by 21pages** [comment]
> If i start rustdesk from exe inside \AppData\Local\rustdesk there is no problem
> 
> If I start rustdesk from Start icon or from icon on desktop there is fail message with miss *.dll


Is there any difference between the dll files in the directory above and in the installation directory?

**Comment by giuliovale** [comment]
Inside installation directory there are no *.dll but only rustdesk.exe
The rustdesk.exe is the same inside installation directory and  \AppData\Local\rustdesk

**Comment by 21pages** [comment]
Can you run `XCOPY` in cmd?

**Comment by giuliovale** [comment]
Yes,
btw: if I copy all *.dll and also the data directory rustdesk start from install

**Comment by 21pages** [comment]
Did you install it by rename?

**Comment by giuliovale** [comment]
No, I have the previous version of rustdesk.exe 1.1.9 on my computer ed installed the nightly with default install

**Comment by 21pages** [comment]
What's the default install?

**Comment by giuliovale** [comment]
c:\program files\rustdesk
Please note this machine have italian settings so default install is
c:\programmi\rustdesk

**Comment by 21pages** [comment]
How did you install [rustdesk-1.2.0-install-x86_64-pc-windows-msvc.exe](https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-install-x86_64-pc-windows-msvc.exe),  just click it and install page will show?

**Comment by 21pages** [comment]
![e4498abbb0842c5bed646d0d65ec4c9](https://user-images.githubusercontent.com/14891774/197379298-26c0f7a5-3463-4169-8711-f34ce70b466d.png)
Reproduce by click this. Thanks for your feedback!

**Comment by giuliovale** [comment]
No the click to upgrade not work also on a new computer rustdesk-1.2.0-install start, but if I try Install this not have effect

**Comment by 21pages** [comment]
Yes, you can uninstall 1.1.9 and run it as portable.

**Comment by 21pages** [comment]
> How did you install [rustdesk-1.2.0-install-x86_64-pc-windows-msvc.exe](https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-install-x86_64-pc-windows-msvc.exe), just click it and install page will show?

btw, was that so?

**Comment by giuliovale** [comment]
> > How did you install [rustdesk-1.2.0-install-x86_64-pc-windows-msvc.exe](https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-install-x86_64-pc-windows-msvc.exe), just click it and install page will show?
> 
> btw, was that so?

yes

and also note that with this file after start on a new computer rustdesk work but the button Install newer install nothing

**Comment by 21pages** [comment]
Could you reproduce it and show your step?

**Comment by giuliovale** [comment]
> Could you reproduce it and show your step? About the *dll not found.

Computer have previous versione of rustdesk.exe

Download nightly build and try execution

this file with *.dll not found

there are no other test I can do

Only find that start rustdesk from  \AppData\Local\rustdesk  work otherwise no

Button always show that there is a new version, but if I click for upgrade nothing happens

**Comment by 21pages** [comment]
Thanks.
> nothing happens

That was because I'm on a dev version.

**Comment by 21pages** [comment]
So yesterday, you clicked the button 'Click to upgrade', or see the page
![1666516634332](https://user-images.githubusercontent.com/14891774/197384240-57b23129-9250-4cff-afa9-85c1c2175b59.png)

**Comment by giuliovale** [comment]
Click to upgrade

**Comment by 21pages** [comment]
OK, that's it!

**Comment by rustdesk** [comment]
try out https://github.com/rustdesk/rustdesk/releases/tag/nightly please.

**Comment by giuliovale** [comment]
rustdesk.exe from last nightly build not start, Windows show there is a problem of security and kill it

**Comment by 21pages** [comment]
It's not signed, try to choose still run.

**Comment by giuliovale** [comment]
Ok work.

Can't install it, correct?

**Comment by 21pages** [comment]
Expected, will be fixed soon.

**Comment by Benny7587** [comment]
I did download the nightly build 1.2.0 for Windows and would like to run it portable with the host and key as paramater in the filename. Version 1.2.0 does not accept these parameters like version 1.1.9. Did i download the wrong file or is there an other option to start the application with the host and key for my self hosted server?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2930#issuecomment-1403025933
