### ISSUE TITLE
Physical mouse/touchpad and keyboard doesn't work on SAMSUNG tablet devices

### ISSUE THREAD

**Issue by SuperMarioSF** [rustdesk/rustdesk#1786]
**Describe the bug you encountered:**
I'm currently using a tablet to access RustDesk on my Windows machine. Everything works fine, until I connect the official keyboard to it. It seems RustDesk client treat my touchpad on keyboard as touch input. In mouse mode, only if I press hard and drag on touchpad, the mouse cursor works. In touchscreen mode it kinda looks like worked, but only if I clicked somewhere, and no mouse wheel support nor right click support. 
This kind of behaviour suggests there is no native mouse support implemented in RustDesk Android client.

Keyboard doesn't works correctly either. I type in characters from physical keyboard, and double amount of characters were sent to remote side. Did some test, and found if no IME is currently actively receiving input (hiding keyboard), the double character sent issue present. If IME is handling input, then everything is fine except some key binding will be intercepted by IME (normal behaviour).
Optionally please give user an option to disable certain modifier key code, because some physical keyboard base phone have weird key mappings, like need ALT key for entering symbols, but instead sent ALT+key bindings.

**What did you expect to happen instead?**
1. There is native mouse support included in RustDesk Android client, which can properly capture mouse movent and mouse wheel, and right click works.
2. There is proper physical keyboard support that does NOT send same key twice.

**How did you install `RustDesk`?**

- Local client: Android client installed via Google Play.
- Remote server: Windows client installed via install button presented in portable version, from official website.

---

**RustDesk version and environment**
- Local client: RustDesk Google Play release v1.1.10-1 running on Android 12, SAMSUNG OneUI 4.1, on SAMSUNG Galaxy Tab S8, with official keyboard cover. Should present problem with most SAMSUNG based tablet. Other brand's may or may not have this issue, I don't have hardware to confirm this.
- Remote server: RustDesk PC release from website v1.1.9.0 running on Windows 11 21H2.

**Comment by rustdesk** [comment]
dup

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1466

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1739
