### ISSUE TITLE
Win7>Win10 second monitor issue 

### ISSUE THREAD

**Issue by Swiftgti** [rustdesk/rustdesk#179]
In latest version .16 when switching to view the second monitor, it works for only some second and then it freezes the image. 
if you make any change of compression/ quality it works again for a few seconds and freezes again. 
In primary monitor works fine.

**Comment by rustdesk** [comment]
maybe related https://github.com/rustdesk/rustdesk/issues/169

**Comment by Swiftgti** [comment]
Hi it’s not the same,  because it works fine if you see the monitor 1 ( and with gpu app in monitor 1) , but if you switch to monitor 2 ( regardless of gpu app is in monitor 1 or 2) , it starts the freezing issue.

**Comment by rustdesk** [comment]
strange bug

**Comment by Swiftgti** [comment]
Do you want to give you access to this pc so you can see the issue and grab any information you may need ?

**Comment by grummbeer** [comment]
@Swiftgti have you already tried the nightly version? https://github.com/rustdesk/rustdesk/releases/tag/nightly

Still any issues?

**Comment by Swiftgti** [comment]
Hi, sorry I don't have any more access to that pc, so I can't check it.

**Comment by grummbeer** [comment]
OK thanks for reply. close?

**Comment by Swiftgti** [comment]
yes, I close it, i never had similar issue again.

**Comment by rustdesk** [comment]
wont fix win 7 anymore

**Comment by Swiftgti** [comment]
yes, I agree.
