### ISSUE TITLE
End to end encryption for direct local connections?

### ISSUE THREAD

**Issue by yuliu** [rustdesk/rustdesk#1798]
Two Windows PCs connect to a same rendezvous server (started with `_k`). When the connection established from one to another via direct local IP, e.g., 192.168.x.x, I saw that in the status balloon popup it said the direct local connection was unencrypted.

Is there any configurations I was missing, or is the end to end encryption for direct local connections not implemented yet?

**Comment by Sympatron** [comment]
Can you please explain why you won't fix this.
You could generate some key from the password and use this for local connections. This wouldn't be as secure, but better than nothing.

**Comment by yuliu** [comment]
I'm wondering the same thing.

**Comment by Daviddeer2** [comment]
I met the same situation, can u please share how u fix it?
