### ISSUE TITLE
failed to build on windows 7 

### ISSUE THREAD

**Issue by rfyiamcool** [rustdesk/rustdesk#180]
### env

os: windows 7
rust-master: master
rust: 1.53.0

already install vcpkg tool, install dependent package, set `VCPKG_ROOT` system env.

```bash
PS C:\Users\Administrator\rustdesk-master> $env:VCPKG_ROOT
C:\Users\Administrator\vcpkg

PS C:\Users\Administrator\rustdesk-master> cd C:\Users\Administrator\vcpkg
PS C:\Users\Administrator\vcpkg> ls
Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----         2021/7/28     13:54            .github
d----         2021/7/28     16:35            .vs
d----         2021/7/28     16:14            buildtrees
d----         2021/7/27     17:14            docs
d----         2021/7/28     16:15            downloads
d----         2021/7/28     14:46            installed
d----         2021/7/28     16:14            packages
d----         2021/7/28     13:54            ports
d----         2021/7/28     13:54            scripts
d----         2021/7/27     17:14            toolsrc
...
...
-a---         2021/7/28     13:54    3348872 vcpkg.exe      
```

### cargo run

failed to execute `cargo run`.

```                       
PS C:\Users\Administrator\rustdesk-master> cargo run
warning: output filename collision.
The bin target `rustdesk` in package `rustdesk v1.1.6 (C:\Users\Administrator\rustdesk-master)` has the same output file
name as the lib target `rustdesk` in package `rustdesk v1.1.6 (C:\Users\Administrator\rustdesk-master)`.
Colliding filename is: C:\Users\Administrator\rustdesk-master\target\debug\deps\rustdesk.pdb
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The bin target `rustdesk` in package `rustdesk v1.1.6 (C:\Users\Administrator\rustdesk-master)` has the same output file
name as the lib target `rustdesk` in package `rustdesk v1.1.6 (C:\Users\Administrator\rustdesk-master)`.
Colliding filename is: C:\Users\Administrator\rustdesk-master\target\debug\rustdesk.pdb
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: unreachable pattern
   --> libs\enigo\src\win\win_impl.rs:348:13
    |
348 |             _ => 0,
    |             ^
    |
    = note: `#[warn(unreachable_patterns)]` on by default

warning: 1 warning emitted

   Compiling hbb_common v0.1.0 (C:\Users\Administrator\rustdesk-master\libs\hbb_common)
   Compiling scrap v0.5.0 (C:\Users\Administrator\rustdesk-master\libs\scrap)
   Compiling magnum-opus v0.3.4-1 (https://github.com/open-trade/magnum-opus#86b58e5c)
The following warnings were emitted during compilation:

warning: couldn't execute `llvm-config --prefix` (error: 系统找不到指定的文件。 (os error 2))
warning: set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable

error: failed to run custom build command for `scrap v0.5.0 (C:\Users\Administrator\rustdesk-master\libs\scrap)`

Caused by:
  process didn't exit successfully: `C:\Users\Administrator\rustdesk-master\target\debug\build\scrap-1d91e4ec00ad13ec\bu
ild-script-build` (exit code: 101)
  --- stdout
  cargo:info=x64-windows-static
  cargo:rustc-link-lib=static=yuv
  cargo:rustc-link-search=C:\Users\Administrator\vcpkg\installed\x64-windows-static\lib
  cargo:include=C:\Users\Administrator\vcpkg\installed\x64-windows-static\include
  cargo:info=x64-windows-static
  cargo:rustc-link-lib=static=vpx
  cargo:rustc-link-search=C:\Users\Administrator\vcpkg\installed\x64-windows-static\lib
  cargo:include=C:\Users\Administrator\vcpkg\installed\x64-windows-static\include
  rerun-if-changed=C:\Users\Administrator\rustdesk-master\libs\scrap\vpx_ffi.h
  rerun-if-changed=C:\Users\Administrator\vcpkg\installed\x64-windows-static\include
  cargo:warning=couldn't execute `llvm-config --prefix` (error: 系统找不到指定的文件。 (os error 2))
  cargo:warning=set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll',
'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid:
[])"', C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.53.1\src/lib.rs:1956:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
The following warnings were emitted during compilation:

warning: couldn't execute `llvm-config --prefix` (error: 系统找不到指定的文件。 (os error 2))
warning: set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable

error: build failed
```

**Comment by rfyiamcool** [comment]
if don't  install `llvm-config` tool on windows 7,  can't build ?

**Comment by ArchieFu** [comment]
download and install [LLVM](https://prereleases.llvm.org/win-snapshots/LLVM-12.0.0-6923b0a7-win64.exe)

**Comment by rfyiamcool** [comment]
😅  During `cargo run` process, a new problem appeared. 

![](https://ftp.bmp.ovh/imgs/2021/07/f550003bea70cdc1.jpg)

**Comment by rfyiamcool** [comment]
[![WbpRRs.jpg](https://z3.ax1x.com/2021/07/29/WbpRRs.jpg)](https://imgtu.com/i/WbpRRs)

**Comment by ArchieFu** [comment]
#### install x64 lib
``` shell
vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static
```

**Comment by rfyiamcool** [comment]
😅  after vcpkg install xxx, a new problem appeared.

```
PS C:\Users\Administrator\rustdesk-master> cargo run

warning: output filename collision.
The bin target `rustdesk` in package `rustdesk v1.1.6 (C:\Users\Administrator\rustdesk-master)` has the same output file
name as the lib target `rustdesk` in package `rustdesk v1.1.6 (C:\Users\Administrator\rustdesk-master)`.
Colliding filename is: C:\Users\Administrator\rustdesk-master\target\debug\deps\rustdesk.pdb
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The bin target `rustdesk` in package `rustdesk v1.1.6 (C:\Users\Administrator\rustdesk-master)` has the same output file
name as the lib target `rustdesk` in package `rustdesk v1.1.6 (C:\Users\Administrator\rustdesk-master)`.
Colliding filename is: C:\Users\Administrator\rustdesk-master\target\debug\rustdesk.pdb
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: unreachable pattern
   --> libs\enigo\src\win\win_impl.rs:348:13
    |
348 |             _ => 0,
    |             ^
    |
    = note: `#[warn(unreachable_patterns)]` on by default

warning: 1 warning emitted

   Compiling hbb_common v0.1.0 (C:\Users\Administrator\rustdesk-master\libs\hbb_common)
   Compiling scrap v0.5.0 (C:\Users\Administrator\rustdesk-master\libs\scrap)
   Compiling magnum-opus v0.3.4-1 (https://github.com/open-trade/magnum-opus#86b58e5c)
   Compiling rustdesk v1.1.6 (C:\Users\Administrator\rustdesk-master)
error: could not compile `rustdesk`

Caused by:
  could not execute process `rustc --crate-name rustdesk --edition=2018 src\lib.rs --error-format=json --json=diagnostic
-rendered-ansi --crate-type cdylib --crate-type staticlib --crate-type rlib --emit=dep-info,link -C embed-bitcode=no -C
debuginfo=2 -C metadata=9382a6c0e0c9f8c5 --out-dir C:\Users\Administrator\rustdesk-master\target\debug\deps -C increment
al=C:\Users\Administrator\rustdesk-master\target\debug\incremental -L dependency=C:\Users\Administrator\rustdesk-master\
target\debug\deps --extern async_trait=C:\Users\Administrator\rustdesk-master\target\debug\deps\async_trait-7f3e359b7a94
511c.dll --extern cfg_if=C:\Users\Administrator\rustdesk-master\target\debug\deps\libcfg_if-adf64ce910787d55.rlib --exte
rn clap=C:\Users\Administrator\rustdesk-master\target\debug\deps\libclap-81907574812248d5.rlib --extern copypasta=C:\Use
rs\Administrator\rustdesk-master\target\debug\deps\libcopypasta-7a6b568f8555bfd3.rlib --extern cpal=C:\Users\Administrat
or\rustdesk-master\target\debug\deps\libcpal-d5454efbbdaeb15b.rlib --extern crc32fast=C:\Users\Administrator\rustdesk-ma
ster\target\debug\deps\libcrc32fast-3a7fd3acb9a42c77.rlib --extern dasp=C:\Users\Administrator\rustdesk-master\target\de
bug\deps\libdasp-3f864be0ec9cd9ef.rlib --extern enigo=C:\Users\Administrator\rustdesk-master\target\debug\deps\libenigo-
bdab966a79e9017e.rlib --extern flexi_logger=C:\Users\Administrator\rustdesk-master\target\debug\deps\libflexi_logger-b0d
c3fe12d408791.rlib --extern hbb_common=C:\Users\Administrator\rustdesk-master\target\debug\deps\libhbb_common-5de29ec780
c1e39e.rlib --extern lazy_static=C:\Users\Administrator\rustdesk-master\target\debug\deps\liblazy_static-367279847866395
a.rlib --extern libc=C:\Users\Administrator\rustdesk-master\target\debug\deps\liblibc-8b805a8fca775bfa.rlib --extern mac
_address=C:\Users\Administrator\rustdesk-master\target\debug\deps\libmac_address-3364a82d184601d0.rlib --extern machine_
uid=C:\Users\Administrator\rustdesk-master\target\debug\deps\libmachine_uid-19d32ac0871b14ec.rlib --extern magnum_opus=C
:\Users\Administrator\rustdesk-master\target\debug\deps\libmagnum_opus-12da5983da4cbe68.rlib --extern parity_tokio_ipc=C
:\Users\Administrator\rustdesk-master\target\debug\deps\libparity_tokio_ipc-8cd1104aa3046217.rlib --extern repng=C:\User
s\Administrator\rustdesk-master\target\debug\deps\librepng-593506a5d43cc3b7.rlib --extern rpassword=C:\Users\Administrat
or\rustdesk-master\target\debug\deps\librpassword-6abafd91ed1b8a32.rlib --extern runas=C:\Users\Administrator\rustdesk-m
aster\target\debug\deps\librunas-87290052c7921220.rlib --extern sciter=C:\Users\Administrator\rustdesk-master\target\deb
ug\deps\libsciter-79d61bbd182a16d0.rlib --extern scrap=C:\Users\Administrator\rustdesk-master\target\debug\deps\libscrap
-df77bb5278053c43.rlib --extern serde=C:\Users\Administrator\rustdesk-master\target\debug\deps\libserde-8d04ab34dfaf580d
.rlib --extern serde_derive=C:\Users\Administrator\rustdesk-master\target\debug\deps\serde_derive-25e09e925e5e37de.dll -
-extern serde_json=C:\Users\Administrator\rustdesk-master\target\debug\deps\libserde_json-f1110ec32640be98.rlib --extern
 sha2=C:\Users\Administrator\rustdesk-master\target\debug\deps\libsha2-593a064a9df2a669.rlib --extern systray=C:\Users\A
dministrator\rustdesk-master\target\debug\deps\libsystray-ff37255dcd962b6c.rlib --extern uuid=C:\Users\Administrator\rus
tdesk-master\target\debug\deps\libuuid-f2f9f6be2bba8667.rlib --extern whoami=C:\Users\Administrator\rustdesk-master\targ
et\debug\deps\libwhoami-f141471d8c51d766.rlib --extern winapi=C:\Users\Administrator\rustdesk-master\target\debug\deps\l
ibwinapi-c307c6b1e32ebc91.rlib --extern windows_service=C:\Users\Administrator\rustdesk-master\target\debug\deps\libwind
ows_service-23338e967469ef0b.rlib --extern winreg=C:\Users\Administrator\rustdesk-master\target\debug\deps\libwinreg-d05
5a3bf0e6e3d33.rlib -L native=C:\Users\Administrator\rustdesk-master\target\debug\build\rustdesk-0e02bfb576112fe7\out -l
static=windows -l WtsApi32 -L native=C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\libsodium-sy
s-0.2.6\msvc/x64/Debug/v142/ -L native=C:\Users\Administrator\rustdesk-master\target\debug\build\zstd-sys-33399801402210
d2\out -L C:\Users\Administrator\vcpkg\installed\x64-windows-static\lib -L native=C:\Users\Administrator\rustdesk-master
\target\debug\build\runas-d05181c16f799ac0\out -L C:\Users\Administrator\vcpkg\installed\x64-windows-static\lib -L C:\Us
ers\Administrator\vcpkg\installed\x64-windows-static\lib -L C:\windows\system32` (never executed)
```

**Comment by rfyiamcool** [comment]
`rustdesk` is compiled successfully 😅  , thank u  @ArchieFu

**Comment by 15674813000** [comment]
@rfyiamcool  我编译出来是个白版，没有界面 。知道原因吗？

**Comment by rfyiamcool** [comment]
@15674813000  我记得是把 `https://github.com/rustdesk/rustdesk/tree/master/src/ui` 目录的东西，copy到执行目录. 或者指定一个path.

**Comment by skypan** [comment]
> `rustdesk` is compiled successfully 😅 , thank u @ArchieFu

@rfyiamcool  win10提示这个，咋整 

D:\work\workspace\vcpkg\installed\x64-windows-static\include\vpx/vpx_integer.h:15:10: fatal error: 'stddef.h' file not found
  D:\work\workspace\vcpkg\installed\x64-windows-static\include\vpx/vpx_integer.h:15:10: fatal error: 'stddef.h' file not found, err: true

LLVM，还有  

vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static

本地都已经安装

**Comment by 15674813000** [comment]
好像没有遇到过。设置了VCPKG_ROOT 环境变量吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rustdesk/rustdesk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月21日(星期二) 下午4:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rustdesk/rustdesk] failed to build on windows 7  (#180)





  
rustdesk is compiled successfully 😅 , thank u @ArchieFu
  
@rfyiamcool  win10提示这个，咋整
 
D:\work\workspace\vcpkg\installed\x64-windows-static\include\vpx/vpx_integer.h:15:10: fatal error: 'stddef.h' file not found
 D:\work\workspace\vcpkg\installed\x64-windows-static\include\vpx/vpx_integer.h:15:10: fatal error: 'stddef.h' file not found, err: true
 
LLVM，还有
 
vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static
 
本地都已经安装
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by skypan** [comment]
> 好像没有遇到过。设置了VCPKG_ROOT 环境变量吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "rustdesk/rustdesk" ***@***.***&gt;; 发送时间:&nbsp;2021年12月21日(星期二) 下午4:30 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [rustdesk/rustdesk] failed to build on windows 7 (#180) rustdesk is compiled successfully 😅 , thank u @ArchieFu @rfyiamcool win10提示这个，咋整 D:\work\workspace\vcpkg\installed\x64-windows-static\include\vpx/vpx_integer.h:15:10: fatal error: 'stddef.h' file not found D:\work\workspace\vcpkg\installed\x64-windows-static\include\vpx/vpx_integer.h:15:10: fatal error: 'stddef.h' file not found, err: true LLVM，还有 vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static 本地都已经安装 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

已经设置了的，但是还是不行：
这是我的设置：
![image](https://user-images.githubusercontent.com/11325807/147019761-828dc7b0-3ca3-4d09-8183-b31045c0ce2d.png)

这是我本地完整的错误：
![image](https://user-images.githubusercontent.com/11325807/147019818-95112bd6-0933-4521-a907-ebecc40410ac.png)

**Comment by 15674813000** [comment]
我是在win10上编译的。win7上没有试过。我大致记录了我的编译流程。但是我也没有时间去review了。


中间是否还有其他操作。我也忘记了。


RustDesk 编译流程&nbsp;&nbsp;


1：下载rust开发环境 rustup-init.exe
2：下载最新版本vcpkg-master ，运行 bootstrap-vcpkg.bat 安装
下载目录 D:\vcpkg-master\vcpkg-master\downloads&nbsp;
$env:VCPKG_ROOT 设置环境变量
3：vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static
4:&nbsp; download and install LLVM
https://github.com/llvm/llvm-project/releases/tag/llvmorg-12.0.1
设置环境变量
5：编译
$Env:RUST_BACKTRACE=1;cargo run
cargo build –-release





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rustdesk/rustdesk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月22日(星期三) 上午9:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rustdesk/rustdesk] failed to build on windows 7  (#180)





  
好像没有遇到过。设置了VCPKG_ROOT 环境变量吗
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "rustdesk/rustdesk" @.&gt;; 发送时间:&nbsp;2021年12月21日(星期二) 下午4:30 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [rustdesk/rustdesk] failed to build on windows 7 (#180) rustdesk is compiled successfully 😅 , thank u @ArchieFu @rfyiamcool win10提示这个，咋整 D:\work\workspace\vcpkg\installed\x64-windows-static\include\vpx/vpx_integer.h:15:10: fatal error: 'stddef.h' file not found D:\work\workspace\vcpkg\installed\x64-windows-static\include\vpx/vpx_integer.h:15:10: fatal error: 'stddef.h' file not found, err: true LLVM，还有 vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static 本地都已经安装 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
已经设置了的，但是还是不行：
 这是我的设置：
 
 
这是我本地完整的错误：
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by orcNo** [comment]
> 

我也遇到了相同的问题，我通过在INCLUDE环境变量中加入了windows kit 和 msvc 的头文件目录解决。

**Comment by orcNo** [comment]
> 

我也遇到了相同的问题，我通过在INCLUDE环境变量中加入了windows kit 和 msvc 的头文件目录解决。

**Comment by orcNo** [comment]
> 
@skypan 我也遇到了相同的问题，我通过在INCLUDE环境变量中加入了windows kit 和 msvc 的头文件目录解决。

**Comment by open-trade** [comment]
> > 
> 
> @skypan 我也遇到了相同的问题，我通过在INCLUDE环境变量中加入了windows kit 和 msvc 的头文件目录解决。

i did not modify INCLUDE, but everything is possible on Windows.

**Comment by 82kg** [comment]
> 我是在win10上编译的。win7上没有试过。我大致记录了我的编译流程。但是我也没有时间去review了。 中间是否还有其他操作。我也忘记了。 RustDesk 编译流程&nbsp;&nbsp; 1：下载rust开发环境 rustup-init.exe 2：下载最新版本vcpkg-master ，运行 bootstrap-vcpkg.bat 安装 下载目录 D:\vcpkg-master\vcpkg-master\downloads&nbsp; $env:VCPKG_ROOT 设置环境变量 3：vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static 4:&nbsp; download and install LLVM https://github.com/llvm/llvm-project/releases/tag/llvmorg-12.0.1 设置环境变量 5：编译 $Env:RUST_BACKTRACE=1;cargo run cargo build –-release
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "rustdesk/rustdesk" ***@***.***&gt;; 发送时间:&nbsp;2021年12月22日(星期三) 上午9:33 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [rustdesk/rustdesk] failed to build on windows 7 (#180) 好像没有遇到过。设置了VCPKG_ROOT 环境变量吗 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "rustdesk/rustdesk" @.&gt;; 发送时间:&nbsp;2021年12月21日(星期二) 下午4:30 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [rustdesk/rustdesk] failed to build on windows 7 (#180) rustdesk is compiled successfully 😅 , thank u @ArchieFu @rfyiamcool win10提示这个，咋整 D:\work\workspace\vcpkg\installed\x64-windows-static\include\vpx/vpx_integer.h:15:10: fatal error: 'stddef.h' file not found D:\work\workspace\vcpkg\installed\x64-windows-static\include\vpx/vpx_integer.h:15:10: fatal error: 'stddef.h' file not found, err: true LLVM，还有 vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static 本地都已经安装 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: @.***&gt; 已经设置了的，但是还是不行： 这是我的设置： 这是我本地完整的错误： — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

win10上编译出来的，win7上没法运行，你们遇到过吗

**Comment by rfyiamcool** [comment]
@82kg 忘了怎么折腾了，只能说很费劲。
