### ISSUE TITLE
Windows Snap (Win+Arrow Key) not working

### ISSUE THREAD

**Issue by kingmustard** [rustdesk/rustdesk#1807]
I have recently switched from AnyDesk.

In RuskDesk, Win+Left/Right Arrow Key is not snapping windows to the left/right.

Win+Up/Down Arrow Key is correctly maximizing and minimising, though.

Any ideas?

Host Windows 11 x64, remote Windows 10 x64, RustDesk 1.1.9 on both.

**Comment by rustdesk** [comment]
Try out nightly build please.

**Comment by rustdesk** [comment]
closed as no response
