### ISSUE TITLE
Reducing two taskbar entries to one?

### ISSUE THREAD

**Issue by kingmustard** [rustdesk/rustdesk#1809]
There are two taskbar windows on each system (host and remote) during a session.

The screenshot below shows the remote machine. One is the main dialogue, one is the upper-right dialogue.

Is it possible to reduce it to one window?

Host Windows 11 x64, remote Windows 10 x64, RustDesk 1.1.9 on both.

![eb_rust1](https://user-images.githubusercontent.com/1947304/197722987-5f5d9b40-9a7d-4da1-aabc-76077ab281a0.png)

**Comment by rustdesk** [comment]
@Kingtous our flutter version also has this problem. Before I thought it is not important, and it made our multiple window complex. But for now, it seems we need to consider this problem. Always only one process, no matter the first window is main window, --connect window or --cm window.

**Comment by nikkdevic** [comment]
> There are two taskbar windows on each system (host and remote) during a session.
> 
> The screenshot below shows the remote machine. One is the main dialogue, one is the upper-right dialogue.
> 
> Is it possible to reduce it to one window?
> 
> Host Windows 11 x64, remote Windows 10 x64, RustDesk 1.1.9 on both.
> 
> ![eb_rust1](https://user-images.githubusercontent.com/1947304/197722987-5f5d9b40-9a7d-4da1-aabc-76077ab281a0.png)

This doesn't happen on my remote systems. Only one(top right) window opens.
![RD01](https://user-images.githubusercontent.com/97282126/201276373-a287eeaf-1962-4eb3-9d95-20f8d215f8b8.png)

**Comment by Kingtous** [comment]
> > There are two taskbar windows on each system (host and remote) during a session.
> > 
> > The screenshot below shows the remote machine. One is the main dialogue, one is the upper-right dialogue.
> > 
> > Is it possible to reduce it to one window?
> > 
> > Host Windows 11 x64, remote Windows 10 x64, RustDesk 1.1.9 on both.
> > 
> > ![eb_rust1](https://user-images.githubusercontent.com/1947304/197722987-5f5d9b40-9a7d-4da1-aabc-76077ab281a0.png)
> 
> This doesn't happen on my remote systems. Only one(top right) window opens.
> ![RD01](https://user-images.githubusercontent.com/97282126/201276373-a287eeaf-1962-4eb3-9d95-20f8d215f8b8.png)
> 

we have done some optimizations to combine two into one. will opt in these days.

**Comment by rustdesk** [comment]
nightly build.
