### ISSUE TITLE
High split screen mouse position dislocation

### ISSUE THREAD

**Issue by ArchieFu** [rustdesk/rustdesk#181]
#### When my win10 OS is on 125% zooming, the mouse position is misplaced during remote control.

windows version: Windows 10 Professional Edition 20H2

rustdesk version: 1.1.6  [git: 7282a46] build by vscode

reproduce issue: win10  -> win7 

win10: Resolution 2560x1440  zoom:125%

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/75
