### ISSUE TITLE
Back mouse button (side button) not working on remote system

### ISSUE THREAD

**Issue by kingmustard** [rustdesk/rustdesk#1810]
The back mouse button is not working on remote system.

Middle-click (the wheel button) works fine.

Any ideas how I can solve this?

Host Windows 11 x64, remote Windows 10 x64, RustDesk 1.1.9 on both.

**Comment by rustdesk** [comment]
We do not have mouse with "back button", no idea how to test.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/35#issuecomment-840432870

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/2230
