### ISSUE TITLE
nightly build1.2.0  rustdesk-host=xxx.yyyy.zz,key=123456.exe This writing file names doesn't seem to support it

### ISSUE THREAD

**Issue by chmis8000** [rustdesk/rustdesk#1811]
**Describe the bug you encountered:**
rustdesk-host=xxx.yyyy.zz,key=123456.exe 
This way of writing file names doesn't seem to support it.
Doc: https://rustdesk.com/docs/en/self-host/install/#step-3--set-hbbshbbr-address-on-client-side

**RustDesk version and environment**
1.2.0 portable + Win10

**Comment by rustdesk** [comment]
@Kingtous

**Comment by Kingtous** [comment]
we ll support it soon in nightly build.

**Comment by chmis8000** [comment]
In addition, when Chrome downloads the same file repeatedly, 
it will automatically add spaces and parentheses after it, 
for example: rustdesk-host=xxx.yyy.zz, key=123456 (1).exe
Is it possible to resolve keys to exclude characters that may be added to the same file name later?

**Comment by Kingtous** [comment]
> In addition, when Chrome downloads the same file repeatedly, it will automatically add spaces and parentheses after it, for example: rustdesk-host=xxx.yyy.zz, key=123456 (1).exe Is it possible to resolve keys to exclude characters that may be added to the same file name later?

spaces and parentheses may not easily handle, e.g.:

In Chinese, the file name will be `rustdesk-xxx（1）.exe`, `（` and `）`are all in chinese character.

So it's depend on what language the desktop platform use.

**Comment by rustdesk** [comment]
> spaces and parentheses

No need to consider Chrome download.

**Comment by eduardohachete** [comment]
> In addition, when Chrome downloads the same file repeatedly, it will automatically add spaces and parentheses after it, for example: rustdesk-host=xxx.yyy.zz, key=123456 (1).exe Is it possible to resolve keys to exclude characters that may be added to the same file name later?

You can put the exe file inside a zip file.

**Comment by My1** [comment]
> You can put the exe file inside a zip file.

makes it harder to use especially with tech-illiterate ppl over the phone, especially if they accidetially click download multiple times, and I know this happens often enough (including re-downloading half an eternity later).

> No need to consider Chrome download

all browsers do this

> spaces and parentheses may not easily handle, e.g.:

might it be possible to for example just exclude unwanted characters.

you could for example regex this stuff up, no matter whether it's using normal or full-width brackets (or any other random bs, provided it does add something that isnt used in the main string.

the docs for example mention `rustdesk-host=192.168.1.137,key=xfdsfsd32=32.exe` so assuming the key is either base64URL with padding or base32 you can use
`/rustdesk-host=([0-9a-z.-]+),key=([0-9a-z-_=]+).*\.exe/i``for base64url with padding or
`/rustdesk-host=([0-9a-z.-]+),key=([2-7a-z=]+).*\.exe/i` for base32
