### ISSUE TITLE
Issue with Windows installer

### ISSUE THREAD

**Issue by hiavata** [rustdesk/rustdesk#1812]
**Describe the bug you encountered:**

When running the installer and selecting the "accept and install" option, the installer just closes, and nothing happens. Tried doing it via winget, and I had the same issue. Tried rebooting, etc...

**What did you expect to happen instead?**

Expect the app to be installed

**How did you install `RustDesk`?**

Tried via win package and wiget

**RustDesk version and environment**

Windows 10 Pro 22H2 x64, Rustdesk client 1.1.9

**Comment by hiavata** [comment]
I've tried solutions presented there and:

1. Running the installed from an elevated prompt with a silent option provided no output
2. x86_v2 installer behaved the same way.
3. There is no install.bat file in %TEMP%

**Comment by hiavata** [comment]
OK, I've run it again, and it generated the file in %TEMP%. After running the installer file, it worked

`
C:\Users\J&N\Downloads>
C:\Users\J&N\Downloads>rustdesk-1.1.9-putes.exe --silent-install 1


C:\Users\J&N\Downloads>cd ..

C:\Users\J&N>cd AppData

C:\Users\J&N\AppData>cd Local

C:\Users\J&N\AppData\Local>cd Temp

C:\Users\J&N\AppData\Local\Temp>RustDesk_install.bat

C:\Users\J&N\AppData\Local\Temp>chcp 65001
Active code page: 65001

C:\Users\J&N\AppData\Local\Temp>sc stop RustDesk
[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.


C:\Users\J&N\AppData\Local\Temp>sc delete RustDesk
[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.


C:\Users\J&N\AppData\Local\Temp>taskkill /F /IM RustDesk.exe
ERROR: The process "RustDesk.exe" not found.

C:\Users\J&N\AppData\Local\Temp>reg delete HKEY_CLASSES_ROOT\.rustdesk /f
ERROR: The system was unable to find the specified registry key or value.

C:\Users\J&N\AppData\Local\Temp>netsh advfirewall firewall delete rule name="RustDesk Service"

No rules match the specified criteria.


C:\Users\J&N\AppData\Local\Temp>reg delete HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk /f
ERROR: The system was unable to find the specified registry key or value.

C:\Users\J&N\AppData\Local\Temp>if exist "C:\Program Files\RustDesk" rd /s /q "C:\Program Files\RustDesk"

C:\Users\J&N\AppData\Local\Temp>if exist "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\RustDesk" rd /s /q "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\RustDesk"

C:\Users\J&N\AppData\Local\Temp>if exist "C:\Users\Public\Desktop\RustDesk.lnk" del /f /q "C:\Users\Public\Desktop\RustDesk.lnk"

C:\Users\J&N\AppData\Local\Temp>if exist "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\RustDesk Tray.lnk" del /f /q "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\RustDesk Tray.lnk"

C:\Users\J&N\AppData\Local\Temp>chcp 65001
Active code page: 65001

C:\Users\J&N\AppData\Local\Temp>md "C:\Program Files\RustDesk"

C:\Users\J&N\AppData\Local\Temp>copy /Y "C:\Users\J&N\Downloads\rustdesk-1.1.9-putes.exe" "C:\Program Files\RustDesk\RustDesk.exe"
        1 file(s) copied.

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk /f
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk /f /v DisplayIcon /t REG_SZ /d "C:\Program Files\RustDesk\RustDesk.exe"
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk /f /v DisplayName /t REG_SZ /d "RustDesk"
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk /f /v DisplayVersion /t REG_SZ /d "1.1.9"
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk /f /v Version /t REG_SZ /d "1.1.9"
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk /f /v InstallLocation /t REG_SZ /d "C:\Program Files\RustDesk"
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk /f /v Publisher /t REG_SZ /d "RustDesk"
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk /f /v VersionMajor /t REG_DWORD /d 1
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk /f /v VersionMinor /t REG_DWORD /d 1
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk /f /v VersionBuild /t REG_DWORD /d 9
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk /f /v UninstallString /t REG_SZ /d "\"C:\Program Files\RustDesk\RustDesk.exe\" --uninstall"
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk /f /v EstimatedSize /t REG_DWORD /d 14893
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk /f /v WindowsInstaller /t REG_DWORD /d 0
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>cscript "C:\Users\J&N\AppData\Local\Temp\RustDesk_mk_shortcut.vbs"
Microsoft (R) Windows Script Host Version 5.812
Copyright (C) Microsoft Corporation. All rights reserved.


C:\Users\J&N\AppData\Local\Temp>cscript "C:\Users\J&N\AppData\Local\Temp\RustDesk_uninstall_shortcut.vbs"
Microsoft (R) Windows Script Host Version 5.812
Copyright (C) Microsoft Corporation. All rights reserved.


C:\Users\J&N\AppData\Local\Temp>cscript "C:\Users\J&N\AppData\Local\Temp\RustDesk_tray_shortcut.vbs"
Microsoft (R) Windows Script Host Version 5.812
Copyright (C) Microsoft Corporation. All rights reserved.


C:\Users\J&N\AppData\Local\Temp>copy /Y "C:\Users\J&N\AppData\Local\Temp\\RustDesk Tray.lnk" "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\"
        1 file(s) copied.

C:\Users\J&N\AppData\Local\Temp>copy /Y "C:\Users\J&N\AppData\Local\Temp\\RustDesk.lnk" "C:\Users\Public\Desktop\"
        1 file(s) copied.

C:\Users\J&N\AppData\Local\Temp>md "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\RustDesk"

C:\Users\J&N\AppData\Local\Temp>copy /Y "C:\Users\J&N\AppData\Local\Temp\\RustDesk.lnk" "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\RustDesk\"
        1 file(s) copied.

C:\Users\J&N\AppData\Local\Temp>copy /Y "C:\Users\J&N\AppData\Local\Temp\\Uninstall RustDesk.lnk" "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\RustDesk\"
        1 file(s) copied.

C:\Users\J&N\AppData\Local\Temp>copy /Y "C:\Users\J&N\AppData\Local\Temp\\Uninstall RustDesk.lnk" "C:\Program Files\RustDesk\"
        1 file(s) copied.

C:\Users\J&N\AppData\Local\Temp>sc create RustDesk binpath= "\"C:\Program Files\RustDesk\RustDesk.exe\" --import-config \"C:\Users\J  & N\AppData\Roaming\RustDesk\config\RustDesk.toml\"" start= auto DisplayName= "RustDesk Service"
[SC] CreateService SUCCESS
'N\AppData\Roaming\RustDesk\config\RustDesk.toml\""' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\J&N\AppData\Local\Temp>sc start RustDesk
[SC] StartService FAILED 1053:

The service did not respond to the start or control request in a timely fashion.


C:\Users\J&N\AppData\Local\Temp>sc stop RustDesk
[SC] ControlService FAILED 1062:

The service has not been started.


C:\Users\J&N\AppData\Local\Temp>sc delete RustDesk
[SC] DeleteService SUCCESS

C:\Users\J&N\AppData\Local\Temp>chcp 65001
Active code page: 65001

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_CLASSES_ROOT\.rustdesk /f
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_CLASSES_ROOT\.rustdesk\DefaultIcon /f
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_CLASSES_ROOT\.rustdesk\DefaultIcon /f /ve /t REG_SZ  /d "\"C:\Program Files\RustDesk\RustDesk.exe\",0"
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_CLASSES_ROOT\.rustdesk\shell /f
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_CLASSES_ROOT\.rustdesk\shell\open /f
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_CLASSES_ROOT\.rustdesk\shell\open\command /f
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_CLASSES_ROOT\.rustdesk\shell\open\command /f /ve /t REG_SZ /d "\"C:\Program Files\RustDesk\RustDesk.exe\" --play \"%1\""
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>sc create RustDesk binpath= "\"C:\Program Files\RustDesk\RustDesk.exe\" --service" start= auto DisplayName= "RustDesk Service"
[SC] CreateService SUCCESS

C:\Users\J&N\AppData\Local\Temp>netsh advfirewall firewall add rule name="RustDesk Service" dir=in action=allow program="C:\Program Files\RustDesk\RustDesk.exe" enable=yes
Ok.


C:\Users\J&N\AppData\Local\Temp>sc start RustDesk

SERVICE_NAME: RustDesk
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 2  START_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x7d0
        PID                : 9764
        FLAGS              :

C:\Users\J&N\AppData\Local\Temp>reg add HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System /f /v SoftwareSASGeneration /t REG_DWORD /d 1
The operation completed successfully.

C:\Users\J&N\AppData\Local\Temp>timeout 300

Waiting for 249 seconds, press a key to continue ...

C:\Users\J&N\AppData\Local\Temp>`

**Comment by rustdesk** [comment]
Installed successfully now?

**Comment by hiavata** [comment]
Yes.
