### ISSUE TITLE
Mac Monterey M1 full screen BUG

### ISSUE THREAD

**Issue by simon2413** [rustdesk/rustdesk#1819]
**Describe the bug you encountered:**
Device: mbp 14
Processor: M1 pro
System: Monterey 12.16.1
When rustdesk is displayed in full screen, a large blank space appears when the mouse is moved to the software menu bar, and this space grows larger and larger over time.
...

**What did you expect to happen instead?**
When rustdesk is displayed in full screen, a large blank space appears when the mouse is moved to the software menu bar, and this space grows larger and larger over time.
...

**How did you install `RustDesk`?**
Download and install on the official website

---

**RustDesk version and environment**
Device: mbp 14
Processor: M1 pro
System: Monterey 12.16.1
RustDesk Version: 1.1.9

**Comment by simon2413** [comment]
![image](https://user-images.githubusercontent.com/25585766/197920047-b12578ce-e3b6-4321-b034-32e3e2d10f02.png)

**Comment by rustdesk** [comment]
Our new version  (incoming) has different implementation, this problem will vanish.
