### ISSUE TITLE
Flutter compiles the Windows version and crashes after clicking the "connect" button

### ISSUE THREAD

**Issue by szxv587** [rustdesk/rustdesk#1820]
**Describe the bug you encountered:**
I used the latest code of the master branch to compile, click the connect button after running it, and found that it did not work properly and crashed. I hope you can help me to see what caused it
...

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**
RustDesk 1.2.0 win10

C:\Users\dell>flutter doctor
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.5, on Microsoft Windows [版本 10.0.19044.2130], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.6)
[√] Android Studio (version 2021.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

C:\Users\dell>

![488931f0d96d778ff61b9311a2b8dc2](https://user-images.githubusercontent.com/18606623/197922943-5f257341-54be-43f1-b2de-38fa03fd6f01.jpg)

**Comment by rustdesk** [comment]
#763

**Comment by szxv587** [comment]
> #763
这不是编译问题，我已经编译过了，运行时点击连接崩溃了
This is not a compilation problem, I have already compiled it, and it crashes when I click the link at runtime

**Comment by szxv587** [comment]
@rustdesk
