### ISSUE TITLE
rustdesk for mac version  in vmware cant tranter screen 

### ISSUE THREAD

**Issue by sinull** [rustdesk/rustdesk#1821]
**Describe the bug you encountered:**
Device: mac os in vmware 16 
System: mac os big sur 11.6.5
rustdesk for mac version  in vmware cant tranter screen , 

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

GitHub release

**RustDesk version and environment**

**Comment by charlespick** [comment]
I'm having a similar problem, running macos on vmware esxi on a mac mini. I'm connecting from my Macbook Pro running macos natively. It's been saying waiting for image the entire time I've written this comment. I installed by downloading from rustdesk.com, dragging to applications, and installing service.

**Comment by mattchis** [comment]
I have the same issue running Mac os on Proxmox.  I have done some researching on this issue and all signs seem to point towards needing a video driver built from scratch for Ruskdesk.  Some people have resolved this issue by enabling the VM guest to have direct access to the hosts video card and plugging in a monitor or a dummy adapter. For now I have resorted to VNC.

**Comment by rustdesk** [comment]
we have no mac in vmware

**Comment by charlespick** [comment]
@rustdesk if you have a mac you can run a mac vm using vmware fusion for free or parallels for a small cost. As far as I can tell the problem is there's no graphics acceleration in a mac vm so compatibility will need to start with software encoding there.

**Comment by rustdesk** [comment]
tracked by #4357
