### ISSUE TITLE
"Connected. waiting for image" dialog has OK button which closes the connection

### ISSUE THREAD

**Issue by test2a** [rustdesk/rustdesk#1825]
**Describe the bug you encountered:**
check the screenshot.  this is shown AFTER a connection gets connected and it is waiting for image.
![Screenshot_20221026_144843](https://user-images.githubusercontent.com/39449563/197996642-84476750-0c6c-4f2e-90cf-def94a56ff67.png)
the button says "ok" but it actually closes the connection, so either we have to change the button text to say "close" or remove the button because it should not do what it currently is doing
...

**What did you expect to happen instead?**
either cancel the connection or not do anything because the user EXPECTS to get conncted
...

**How did you install `RustDesk`?**

github

---

**RustDesk version and environment**
1.19

**Comment by test2a** [comment]
if we are changing the text, let me submit the PR so that i can contribute to this awesome project

**Comment by rustdesk** [comment]
changed already

**Comment by rustdesk** [comment]
> changed already

Wondering you can confirm

**Comment by test2a** [comment]
sure.... let me try that

**Comment by test2a** [comment]
@rustdesk https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64-unknown-linux-gnu-ubuntu-18.04.deb

i downloaded this file and i just updated to 22.04 ubuntu and rustdesk is not running. 

from the terminal i got 

```
rustdesk
rustdesk: error while loading shared libraries: libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory

```
