### ISSUE TITLE
libayatana-appindicator3.so.1 dependency missing in kde neon

### ISSUE THREAD

**Issue by test2a** [rustdesk/rustdesk#1837]
**Describe the bug you encountered:**
downloaded the deb from releases and could not get rustdesk to run.

tried from terminal and got this error
```
 rustdesk
rustdesk: error while loading shared libraries: libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory
```
...

**What did you expect to happen instead?**
error should not happen or software should ask to download the dependency or ship it,

i fixed this by 
```
sudo apt-get install libayatana-appindicator3-1

```
...

**How did you install `RustDesk`?**

github
---

**RustDesk version and environment**

**Comment by rustdesk** [comment]
Known, will fix soon.

**Comment by rustdesk** [comment]
@Kingtous
