### ISSUE TITLE
win10 remote access macos desktop  lead macos external display black screen,only show cursor.

### ISSUE THREAD

**Issue by cecini** [rustdesk/rustdesk#184]
**Describe the bug you encountered:**

win 10's rustdesk will show 1/2 window.  1 windows show macbook pro 13 inc desktop. 2 maybe show the macbook external display content.
When first lock screen on macbooks, and remote unlock the macbook screen, then enter the remote macos desktop.

Now the macbook external display monitor show black screen,but if i move cursor in the display screen, it show this cursor.

**What did you expect to happen instead?**

Once unlock the screen,whether from remote or local, the external display always show original content..
...

**How did you install `RustDesk`?**

win10: portal 
macos: dmg-dbg,

**RustDesk version and environment**
1.16 version 
use direct ip, win10 as client, macos as controlled node.

**Comment by rustdesk** [comment]
I do not have mac external display

**Comment by rustdesk** [comment]
close since too old and no further report from the other users.
