### ISSUE TITLE
Hover menu inaccessible in fullscreen. (menu/toolbar color theme and border)

### ISSUE THREAD

**Issue by Gryxx** [rustdesk/rustdesk#1842]
After switching virtual desktops in KDE Plasma  Rustdesk's windows set to fullscreen will loose the ability to show the top bar with settings on hover.

**How did you install `RustDesk`?**

GitHub nightly release on Windows, build from source on Linux. when tested on 1.2.0
GitHub release on Windows and Linux (rpm suse) when tested on 1.1.9

---

**RustDesk version and environment**

Tested on 1.1.9 and 1.2.0, connection from openSUSE Tumbleweed KDE Plasma X11 to Windows 10 21H2 and Linux openSUSE Tumbleweed KDE Plasma X11

**Comment by rustdesk** [comment]
@fufesou

**Comment by ForsakenRei** [comment]
It works on my Win10 and Manjaro KDE machines. But it's a little hard to see if you have a relatively light background. Maybe this is the problem I guess? Another thing I noticed it the them mismatch for the menu when using dark theme. Title bar was black while the menu is still white.
![image](https://user-images.githubusercontent.com/23041178/198312772-757f54db-70f2-4c1e-aeba-afbb6e0caff6.png)

**Comment by rustdesk** [comment]
> dark theme

Good pointer, and the toolbar/menu should have a border with another color, assuming the background is white. @fufesou

**Comment by Gryxx** [comment]
> @Gryxx I cannot clear of what problem you've met. Do you means the setting menu dose no show after clicking the bar button? ![image](https://user-images.githubusercontent.com/13586388/198239769-9ef511d0-2f46-4e74-a69e-0aa1ec579ace.png)
> 
> Would you please give a screenshot?

Hard to, it is a movement. Until i switch desktops the menu shown in your comment will appear  i i move mouse in its general direction. Once i switch desktops this behavior no longer works.

**Comment by fufesou** [comment]
> switch desktops
Do you means switch desktop like this, on windows? It's a case I've not tested. Thanks for your report.
![image](https://user-images.githubusercontent.com/13586388/198332066-ff75779a-3b0e-42b5-a42f-b2f4195554db.png)

**Comment by Gryxx** [comment]
Here is a video of issue
https://youtu.be/ihxi67qIlbQ

**Comment by rustdesk** [comment]
> Here is a video of issue https://youtu.be/ihxi67qIlbQ

This is old Sciter version. Sciter is going to be discarded.

**Comment by Gryxx** [comment]
How do i get new one?

**Comment by fufesou** [comment]
No stable release is published. The nightly build can be found [here](https://github.com/rustdesk/rustdesk/releases/tag/nightly).

**Comment by Gryxx** [comment]
My video is from 1.2.0 not 1.1.9.

**Comment by rustdesk** [comment]
try out new nightly

**Comment by Gryxx** [comment]
> try out new nightly

On Windows when hosting i have new UI. On Linux i have the old one. Both show 1.2.0 as version.

**Comment by rustdesk** [comment]
We will fix Sciter anymore, no matter if it is 1.2.

**Comment by Gryxx** [comment]
How do i get the new UI on Linux? The issue with old one persist.

**Comment by rustdesk** [comment]
New ui does not have this problem because it does not have hover, old ui is not maintained anymore.

**Comment by Gryxx** [comment]
How do I get the new one then?

**Comment by Extarys** [comment]
@Gryxx found an answer yet? :P I'm facing the same issue, under Fedora with the rpm provided in the release page.

**Comment by Gryxx** [comment]
@Extarys I'm killing the Rustdesk process every time i need to access the menu.

**Comment by rustdesk** [comment]
rpm version is not ready in nightly build yet, @Kingtous
