### ISSUE TITLE
Automatic Password Change

### ISSUE THREAD

**Issue by JoshuaPettus** [rustdesk/rustdesk#1844]
I like that the user can manually change the password and ID at any point.   One thing that a lot of other products are doing, and I think would be better at least for our use case, is if the password could automatically change every 10 minutes or so.  Therefor a connection couldn't be made without a users express consent for that particular session.

Granted there are probably many who use this for remote desktop purposes it wouldn't mesh well.  But as an IT support tool, I think would be a simple way to enhance the security of the product.

**Comment by rustdesk** [comment]
Try out nightly build, it has enhanced password mechnism.

**Comment by JoshuaPettus** [comment]
I took a look at nightly and I'm not understanding the password system and how it helps my suggestion.  I mean yes we can go over 6 characters, that's nice.

I don't think you are understand my meaning.  It's not enough to just have one random password.  I strongly believe a constantly changing password is needed.  Forcing the user to give you their current password and thereby forcing them to give you permission before you can make a connection.  A person, even IT staff, shouldn't be able to connect at any time.  We need to respect some semblance of privacy.
