### ISSUE TITLE
Can you add the online status display of the access list?

### ISSUE THREAD

**Issue by shizenghua** [rustdesk/rustdesk#185]
能否添加访问列表的在线状态显示？

**Comment by rustdesk** [comment]
English please

**Comment by july008** [comment]
> 能否添加访问列表的在线状态显示？

Can you add the online status display of the access list?

**Comment by rustdesk** [comment]
The "issue" is not only for me, I hope more guys can see it and contribute. So English Please.

**Comment by rustdesk** [comment]
no, because it need bandwidth, i have no money.
