### ISSUE TITLE
linux client -nightly version just crashes randomly

### ISSUE THREAD

**Issue by test2a** [rustdesk/rustdesk#1851]
**Describe the bug you encountered:**
i am on https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64-unknown-linux-gnu-ubuntu-18.04.deb
this nightly and i am connected to a windows host from my linux desktop and today the app seems to randomly crash.

sometimes i am tying something on the remote desktop and rustdesk just vanishes. 
...

here is rustdesk being opened from terminal and the crash information
```
rustdesk
flutter: launch args: []
flutter: initializing FFI main
flutter: _appType:main,info1-id:24ad89ec3d94441e8b45106afaf27e7f,info2-name:KDE neon,dir:/home/user/Documents,homeDir:/home/user/Downloads
flutter: _globalFFI init
flutter: _globalFFI init end
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
flutter: fetch id again at 0:id:459330179
on state change: 0x3236f80on state change: 0x3236f80flutter: launch args: [multi_window, 1, {"type":1,"id":"421231539"}]
flutter: initializing FFI remote
flutter: _appType:remote,info1-id:24ad89ec3d94441e8b45106afaf27e7f,info2-name:KDE neon,dir:/home/user/Documents,homeDir:/home/user/Downloads
flutter: _globalFFI init
flutter: _globalFFI init end
flutter: registerEventHandler theme theme
flutter: registerEventHandler language language
flutter: isMaximized false
on state change: 0x3236f80on state change: 0x3236f80flutter: {restart: false}
on state change: 0x3236f80flutter: onPointDownImage

(rustdesk:29069): Gdk-ERROR **: 10:48:04.539: The program 'rustdesk' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
  (Details: serial 13001 error_code 8 request_code 139 (RENDER) minor_code 27)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap

```

**What did you expect to happen instead?**
no crash
...

**How did you install `RustDesk`?**
github releases

---

**RustDesk version and environment**

**Comment by rustdesk** [comment]
@Kingtous another crash

**Comment by rustdesk** [comment]
@Kingtous have a thorough valgrind check please.

**Comment by rustdesk** [comment]
@test2a can you upload a recording video please?

**Comment by rustdesk** [comment]
tying?

**Comment by test2a** [comment]
yes. wait a minute

**Comment by Kingtous** [comment]
> yes. wait a minute

Thanks for the feedback. I've created a PR which fixes window resize issue causing kde freeze. The CI will release new deb file in about 30min. U can try if the problem exists: https://github.com/Kingtous/rustdesk/releases/tag/nightly

**Comment by Kingtous** [comment]
> yes. wait a minute

Thanks for the feedback. I've created a PR which fixes window resize issue causing kde freeze. The CI will release new deb file in about 30min. U can try if the problem exists: https://github.com/Kingtous/rustdesk/releases/tag/nightly

**Comment by test2a** [comment]
@Kingtous this is getting more weird. yesterday i told you will be uploading a video but i could not recreate the crash. So today morning i updated the file from your link and now i am pretty sure i can recreate this.

the crash only happens when i have a word file open and i am doing something with clipboard, sometimes the crash just happens when word is open.... i am trying to record it so yeah, i will be able to do that now

**Comment by Kingtous** [comment]
> @Kingtous this is getting more weird. yesterday i told you will be uploading a video but i could not recreate the crash. So today morning i updated the file from your link and now i am pretty sure i can recreate this.
> 
> the crash only happens when i have a word file open and i am doing something with clipboard, sometimes the crash just happens when word is open.... i am trying to record it so yeah, i will be able to do that now


@rustdesk seems like a rdev issue.

**Comment by rustdesk** [comment]
> rdev

yes, @asur4s

**Comment by test2a** [comment]
https://user-images.githubusercontent.com/39449563/198824917-1abc220a-c12c-44c0-835e-e0d5febe1578.mp4

**Comment by rustdesk** [comment]
@test2a can you try again? we have put some fix.

**Comment by test2a** [comment]
@rustdesk yes. i've been using the last nightly and the latest one (it shows 5 hours ago) and that has fixed the issue.

i am not seeing any crashes so yeah, this is fixed

**Comment by rustdesk** [comment]
Thanks
