### ISSUE TITLE
mac->mac, shift not work, can not select word via number/space in Chinese IME, command+/ not work

### ISSUE THREAD

**Issue by SiliconZou** [rustdesk/rustdesk#186]

**Comment by rustdesk** [comment]
English please

**Comment by SiliconZou** [comment]
Don't you understand Chinese?

**Comment by rustdesk** [comment]
The "issue" is not only for me, I hope more guys can see it and contribute.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/eb76f7cecc6c580328f0c863379a3483082dfcad fix shift issue only.
command (Win not work on Windows also), and IME seems related to privilege, I have no idea for now.

**Comment by SiliconZou** [comment]
thanks a lot! I've found another APP to replace it.

**Comment by chenjianhua** [comment]
In 1.1.9, this issue has been resolved.
