### ISSUE TITLE
Issues with latest release and installing

### ISSUE THREAD

**Issue by bdntv** [rustdesk/rustdesk#1861]
There seems to be an issue when trying to install with the latest version 1.2.0 (Self compiled).
I have traced it down to the run_cmds function in windows.rs
It appears to get hung around line 1248 and doesn't finish the function.
Program gets installed, but tray icon and app don't launch unless I do so automatically after install.
I've added log::debug!("Run_CMD End: {}", tip); to line 1252 to verify that it never makes it that far.
I've also noticed the tray icon does not work with the stop/start feature. IE: it will stop the service, but then never changes the text to Start and won't start the service unless I close the tray app and reopen. It writes to the config file the first time as well. Double click works fine.

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
@bdntv can you figure out why 1248 fails? i do not think we can reproduce on our side. @21pages will look into tray icon issue.

**Comment by bdntv** [comment]
Not seeing anything that jumps out at me. The script runs successfully, but doesn't seem to continue on after. If I change show to true I can see the bat file run. I've ran the bat file separately in an elevated cmd and no errors are produced. It just doesn't seem to continue after that line.

**Comment by bdntv** [comment]
Also, this is compiled using the sciter version as I am having difficulties compiling with flutter

**Comment by 21pages** [comment]
> sciter version
> but tray icon and app don't launch unless I do so automatically after install.

Add sciter.dll's directory to PATH env

**Comment by bdntv** [comment]
I have tried that. I’ve also tried adding sciter.dll to resources and manually copied to program dir. tray app opens fine if I manually start it. It just doesn’t open through the install script as it hangs as mentioned above

**Comment by rustdesk** [comment]
So nightly build install does not open tray?

**Comment by bdntv** [comment]
Correct. I pulled code as of Tuesday. Compiled and that’s the one I’m experiencing problems with.

**Comment by rustdesk** [comment]
hope you do not only pull and report, you can fix also.

**Comment by rustdesk** [comment]
merged, you can pull and test

**Comment by bdntv** [comment]
Absolutely I will once I'm more comfortable with Rust. This is my first experience with it.

**Comment by bdntv** [comment]
Tested tray merge and it works beautifully. Thanks. Now just trying to figure out the initial install issue with hanging on code.
I've added sciter.dll to PATH env, I've compiled sciter.dll as a resource in the same directory. Everything installs, but tray app does not open unless I do so manually. I added log cmds to windows.rs.

`fn run_cmds(cmds: String, show: bool, tip: &str) -> ResultType<()> {
    let tmp = write_cmds(cmds, "bat", tip)?;
    let tmp_fn = tmp.to_str().unwrap_or("");
    log::debug!("Run_CMD Start: {}", tip);
	let res = runas::Command::new("cmd")
        .args(&["/C", &tmp_fn])
        .show(show)
        .force_prompt(true)
        .status();	
	if !show {
            allow_err!(std::fs::remove_file(tmp));
        }
	log::debug!("Run_CMD End: {}", tip);
    let _ = res?;
    Ok(())
}`
It never gets to the "Run_CMD End" entry

**Comment by bdntv** [comment]
All good. I just wiped my local copy and repulled down. Seems to work now. Thanks for your help

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues
