### ISSUE TITLE
Generate password on first run

### ISSUE THREAD

**Issue by tobias-kuendig** [rustdesk/rustdesk#187]
This is a very specific situation:

1. I do have an Ubuntu server running a graphical desktop environment
2. I do currently only have SSH access and need remote access to the desktop
3. Rustdesk fits perfectly! I can install the deb via SSH and a system service is registered

Unfortunately, I cannot connect to the server after the installation because it seems like the first random password is only generated once the user hovers the mouse over the password field in the GUI. This makes it impossible for me to connect to the server without a user's interaction.

If the first password was generated during the start of the service (or even after running `DISPLAY=:0 rustdesk` via SSH) I could get the credentials from the `.config/rustdesk/RustDesk.toml` file and connect.

Another alternative would be to provide a command line flag to force a password:

```bash
# Accept connections using `mypass`
rustdesk --password=mypass
```

**Comment by rustdesk** [comment]
`rustdesk --password mypass`
