### ISSUE TITLE
Two-way transmission of sound

### ISSUE THREAD

**Issue by july008** [rustdesk/rustdesk#188]
PC1 controls the PC. The sound from PC2 can be transmitted to PC2. Can the sound of PC1 be transmitted to PC2?
That is, the voice intercom function is realized.

**Comment by rustdesk** [comment]
You can write

**Comment by rustdesk** [comment]
I do not think it is a necessary feature, there are huge number of tools for voice intercom nowadays.

**Comment by rustdesk** [comment]
https://www.reddit.com/r/rustdesk/comments/vl87h7/rustdesk_audio_appears_to_be_one_way_only/

**Comment by rustdesk** [comment]
Need to confirm if the other vendors provide this.

**Comment by vmsman** [comment]
I will tell you that I have had to conduct a parallel session in Jitsi Meet to have two way voice.  If Rustdesk supports voice, collaboration includes not only remote control, but voice.  As an example, consider TeamViewer which supports two way voice.  Screen sharing and two way voice exists in Jitsi Meet, but without remote control.  Rustdesk would be the first open source app to do two way voice and remote control in a single app

**Comment by rustdesk** [comment]
@asur4s Check out how does the other vendors work first.

**Comment by rustdesk** [comment]
@Kingtous, @asur4s is busy in looking for job, please follow up this.

**Comment by Kingtous** [comment]
> @Kingtous, @asur4s is busy in looking for job, please follow up this.

get it.

**Comment by Anaphylaxis** [comment]
> > Need to confirm if the other vendors provide this. The audio is mainly for system sound, not for intercom.
> 
> yes. I can Confirm that TV can make an audio call

And despite using TeamViewer for 4+ years I never used that feature once.

**Comment by vmsman** [comment]
@Anaphylaxis EVERYTIME that I use Rustdesk, I launch Jitsi, Skype, or Jami in the background to speak with the person that I am supporting.   The problem with support these days is that too many people that are providing support do not communicate, cannot communicate or think they automatically know what someone needs.   Two way voice communication is an absolute requirement when providing support.

**Comment by Anaphylaxis** [comment]
> @Anaphylaxis EVERYTIME that I use Rustdesk, I launch Jitsi, Skype, or Jami in the background to speak with the person that I am supporting. The problem with support these days is that too many people that are providing support do not communicate, cannot communicate or think they automatically know what someone needs. Two way voice communication is an absolute requirement when providing support.

Which is why you should use some VoIP platform or Teams to communicate. I would rather devs prioritize features that would help us deliver support like SOCKS proxies and the address book etc than focus their attention on something so mundane and solved as 2-way voice communication.Should we have it make us coffee as well?

**Comment by vmsman** [comment]
The reason that I prefer not to use Teams, Skype or Team Viewer is because they are proprietary applications and I prefer to support open source creators.  There are easy workarounds for SOCKS that can be implemented via network enclaves.  Those are fringe features.  A viable and critical function of a remove assistance software should be communication.  Rustdesk only supports one way communication to listen to desktop audio.  Why is it such a stretch to provide collaborative communication as a part of a product that is collaborative.  To me, it seems like Rustdesk is a first rate program with flagship features.  It only lacks communicate.  No, it shouldn't make coffee.  I didn't ask for holographic 3D projection.

**Comment by Anaphylaxis** [comment]
Feel free to make a pull request. From a programmatic standpoint it would seem rather complicated to transmit not only audio from the desktop, but also a call where your voice is coming through the Desktop, without also transmitting back your voice. If I am remoting on someone's computer I am either going to be on the phone with them or speaking via email/live chat, what purpose does having an extra audio communication do? In my opinion lines of communication should be open before you connect, not after. You should never be connecting to a client machine. TeamViewer's "Communication" tab was just an annoyance for 4 years as every time you clicked it, it ducked your PC audio until you restarted TeamViewer.
Perhaps you misunderstood me about the SOCKS proxy, there are a limited amount of tools that can let me essentially open what is a dynamic SSH SOCKS tunnel on the endpoint to traverse the clients network without having to occupy the screen. 
To clarify I am not against the feature being added but this is nowhere near a priority imo and I assume it would go unmissed by the majority

**Comment by vmsman** [comment]
Yeah, you are right.  It serves really no purpose.  I'll just keep starting a Jitsi Meet session to handle voice whenever I use Rustdesk.  Either that or I will make an International phone call.  It's no big deal.

**Comment by Anaphylaxis** [comment]
> Yeah, you are right. It serves really no purpose. I'll just keep starting a Jitsi Meet session to handle voice whenever I use Rustdesk. Either that or I will make an International phone call. It's no big deal.

Not sure if sarcastic or not but voice is a done deal, it's been solved. SIP and RTP are open standards, firertc.com is free, Mumble is open source, if you can't get in touch via audio there are other problems

**Comment by vmsman** [comment]
The point is that I will continue using my workaround since you have no interest in this issue.

**Comment by k1ttt-remote** [comment]
there are many ham radio operators using anydesk or teamviewer for remote control of radios, but teamviewer audio is poor and anydesk is only one-way, so either of those requires another tool like mumble... but mumble doesn't do stereo audio like rustdesk does.  stereo audio from the remote host is a big help in rustdesk but still requires mumble or another tool to send audio to the remote controlled radio.  having rustdesk do 2 way stereo audio would be a huge help as it is much easier to set up by users who are not experienced with remote control and communications software.

**Comment by entrptaher** [comment]
I just found this issue and a bit sad to see this is not supported yet. :( I have setup rustdesk over a lan and the performance is quite good, except the audio is only one way.

**Comment by bilogic** [comment]
Something I wished would work: I rustdesk to a remote, load up whatsapp, and start recording a voice message

**Comment by 173duprot** [comment]
Man this would be incredible.
