### ISSUE TITLE
Transmitting keyboard shortcuts

### ISSUE THREAD

**Issue by paolosezart** [rustdesk/rustdesk#1887]
In connection mode (Windows ---> Windows), I would like to be able to transfer keyboard shortcuts (Ctrl + Alt +Del), (Ctrl + Shift + Esc), (Alt + Tab) etc. Sometimes, when connected to a remote computer, a screensaver is running there, which can only be disabled by a keyboard shortcut. Is it possible to implement this as in many other similar remote access programs?

**Comment by rustdesk** [comment]
duplicate

**Comment by paolosezart** [comment]
Thank you for the detailed and clear answer. Would you be so kind as to show the answer to a similar question? It's just a very long time to scroll through 345 open and 576 closed questions

**Comment by ClaskoTheKnight** [comment]
This is where search engines brought me, and it is useless. Thank you @Rustdesk
