### ISSUE TITLE
Problems with accents and other symbols on the Spanish keyboard

### ISSUE THREAD

**Issue by flusheDData** [rustdesk/rustdesk#1892]
**Describe the bug you encountered:**
When I connect to a Windows machine or a virtual instance of Debian 11 (VirtualBox) and type "áééíóú" I get "'a'e'i'o'u". 
In Windows`, open curly brackets does not work. Open brackets does work every few strokes.
In Debian 11 I get "×" instead of "[" and "\" instead of "{".

...

**What did you expect to happen instead?**
The typed characteres to appear correctly
...

**How did you install `RustDesk`?**
Windows installer.

---

**RustDesk version and environment**
nightly on Windows 10 Pro 22H2

**Comment by rustdesk** [comment]
known and duplicate as the other languages

**Comment by rustdesk** [comment]
try out nightly build please

**Comment by flusheDData** [comment]
Bug still present. Running the nightly version along with the installed 1.1.9. Please let me know If I should unistall the previous version before trying the nightly version. Thx.

**Comment by flusheDData** [comment]
Unistalled the previoius version 1.1.9. Installed the nightly 2.0 version. Vowels with accents do not work. Special symbols [ and { not working either.

**Comment by rustdesk** [comment]
Make sure both side use nightly.

**Comment by flusheDData** [comment]
Tried Windows 10 22H2 machine connected a virtual instance of Debian 11 in VirtualBox both using the nightly version.
Wowels with accent working like a charm. Brackets and curly brackets not working at all.
Pending to test with two Windows hardware.
Thank you

**Comment by flusheDData** [comment]
Tested with a remote Windows machine. Everything working ok. Vowels and special symbols.

**Comment by rustdesk** [comment]
> Brackets and curly brackets not working at all.

@asur4s win ~ linux

**Comment by asur4s** [comment]
>  Please let me know If I should unistall the previous version before trying the nightly version. Thx.

Need to uninstall the installed 1.19 version.

**Comment by hugocornago** [comment]
I had the same issue and it was solved by using the nightly version on both computers.
Therefore, this issue should be closed as completed. 

Thanks for this awesome project.

**Comment by huangliwood** [comment]
I also had the same issue,client nightly,server1.1.9

**Comment by jorgitobg** [comment]
im having same issue but between MAC and windows11... how to fix it?

**Comment by ssantosv** [comment]
Problem still exists but only with capital letters in Spanish keyboard.

Both versions in Windows. Version 1.2 installed.

Expected ÁÉÍÓÚ, but we get AEIOU while the program is running.

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
> Special symbols [ and { not working either.

@fufesou confirm this please.

**Comment by rustdesk** [comment]
> Problem still exists but only with capital letters in Spanish keyboard.
> 
> Both versions in Windows. Version 1.2 installed.
> 
> Expected ÁÉÍÓÚ, but we get AEIOU while the program is running.

@fufesou confirm this please.

**Comment by langfingaz** [comment]
> > Special symbols [ and { not working either.
> 
> @fufesou confirm this please.

Just speaking for myself, not for @fufesou: I installed v1.1.9 today and some non-ascii characters were wrong. Both, server and client are on Arch Linux with `de-latin1-nodeadkeys` keyboard layouts. I could e.g. not type `[`, `}`. Then I switched to nightly v1.2 and all characters are transferred fine!

**Comment by rustdesk** [comment]
@langfingaz you are right, "not working on 1.1.9" (being phased out) is expected, "working on nightly v1.2" is expected.

**Comment by CRC-Mismatch** [comment]
@fufesou as [emedeirosit](https://github.com/rustdesk/rustdesk/issues/2670#issuecomment-1416734026) mentioned in that issue, the 1.2.0 nightly fixes this issue.

**Comment by ssantosv** [comment]
Hello.

Both latest versin, 1.2 nightly from a few ours ago. While connected, accents in capital letters do not work as mentioned here:

https://github.com/rustdesk/rustdesk/issues/1892#issuecomment-1401516740

Expected ÁÉÍÓÚ, but we get AEIOU while the program is running and connected.

**Comment by fufesou** [comment]
I use Windows both sides. The accents work fine.
Did you have some others application running?

https://user-images.githubusercontent.com/13586388/229714884-0f2b14d2-80f0-4088-9ab1-1dccb6723711.mp4

**Comment by fufesou** [comment]
I use Windows both sides. The accents work fine.
Did you have some others application running?

https://user-images.githubusercontent.com/13586388/229714884-0f2b14d2-80f0-4088-9ab1-1dccb6723711.mp4

**Comment by zash1958** [comment]
Problem does also exist with 1.2 nightly on both sides. I cannot find f.e. the \ or a lot of other special charcters.
Not even the "-" is positioned correct. So I have to use the numeric keypad to enter this sign.

Both sides linux. My PC Archlinux latest and on the remote side Ubuntu 20.x

**Comment by zash1958** [comment]
Here the same problem with Archlinux on my PC and Windows Server 2016 on the other side. German language an both

**Comment by fufesou** [comment]
It's strange. They also work fine for me.

https://user-images.githubusercontent.com/13586388/229722521-91a6285a-4e85-4738-8268-db0b665038b7.mp4

**Comment by ssantosv** [comment]
Run rustdesk.
Try to connect to a client.
Try to write capital letters with accent. They will not work.
Kill rustdesk (desktop program, not service).
They will work again.


https://user-images.githubusercontent.com/16861474/229725056-68fda2a3-468e-4175-b372-4ef8873498be.mp4

**Comment by fufesou** [comment]
I don't think your issue is related to RustDesk.
I've tested both when rustdesk is running and after uninstalling rustdesk.

All inputs are fine without "On-Screen Keyboard".
After I run "Ctrl + Win + O", "Shift + ´" and "Shift + `" no longer work.

https://user-images.githubusercontent.com/13586388/229727693-1de6fea2-45fc-48b7-8c9c-ec4b696509eb.mp4

**Comment by zash1958** [comment]
If I - on the same machines - use Anydesk, Teamviewer or dwservice all keyboard mappings are correct an there is absolutely no problem with all the keys

@fufesou:
The menu You have shown does not exist on my systems in the same way

![Bildschirmfoto_20230404_104141](https://user-images.githubusercontent.com/7055809/229737540-bc51a657-dbae-4a7a-ac2b-434ea6bbc6f1.png)

**Comment by fufesou** [comment]
@zash1958 
"Legacy Mode" is not maintained. 

I think you're using version 1.1.9 on the remote side. Please check and use both the ngihtly build.
The keyboard mode should be "Map mode" if the remote version is greater than "1.1.9".

**Comment by zash1958** [comment]
1.2 nightly on both sides
![Bildschirmfoto_20230404_113346](https://user-images.githubusercontent.com/7055809/229750933-b0ccb723-a363-4483-bf4c-c144bace27b3.png)

**Comment by fufesou** [comment]
Yes, I see "Map mode" now.
Are there still problems when typing  "\" or the other special charcters.

"Map mode" feels like using your local keyboard plugged into a remote computer.

**Comment by zash1958** [comment]
Thanks a lot. Gladly I will test it when available

**Comment by fufesou** [comment]
@zash1958 Thanks. I've submitted a PR.
This issue should be resolved in the next nightly build.

**Comment by zash1958** [comment]
With both sides the newest nighly all is running proper now :-)
I can use the keys like öäü and \ correct now

Thanks a lot. Is there any way to make an installer (WIN64) from the newest nightly ?

**Comment by fufesou** [comment]
> I don't think your issue is related to RustDesk. I've tested both when rustdesk is running and after uninstalling rustdesk.
> 
> All inputs are fine without "On-Screen Keyboard". After I run "Ctrl + Win + O", "Shift + ´" and "Shift + `" no longer work.

@ssantosv Hi, can you input `Ä` and `Â` after closing "On-Screen Keyboard"?
Or do they still cannot be typed when RustDesk is running?

**Comment by ssantosv** [comment]
Seems ok now. Thank you!
