### ISSUE TITLE
rustdesk opens main window and connection window. closing main window also closes connection

### ISSUE THREAD

**Issue by test2a** [rustdesk/rustdesk#1894]
**Describe the bug you encountered:**
the main window that is opened on rustdesk is not closable right now. 

in the stable version, i could have just 1 "connection" window open while the rustdesk desktop window could be closed. 
in the nightly version, closing the main window force quits the connection so i am forced to keep 2 windows open at all times.

i can recall in earlier stable versions, i can close the main window and connections would not be affected.

https://user-images.githubusercontent.com/39449563/199182527-47154868-8a4b-41b5-8077-f29cb5c1dd04.mp4
...

**What did you expect to happen instead?**
connected window should not also close if we close main window
...

**How did you install `RustDesk`?**
github nightly

---

**RustDesk version and environment**

**Comment by test2a** [comment]
https://user-images.githubusercontent.com/39449563/199182724-09b890db-4e7b-4d4c-8bf8-ee6851ceeb03.mp4

**Comment by rustdesk** [comment]
@Kingtous another problem is how to open main window if there is remote window.

**Comment by Kingtous** [comment]
Now it's expected. Main window must keep to make flutter works. Maybe we can hide main window when there're sub windows? And we add buttons or a tray listener to show main window?
