### ISSUE TITLE
about the server demo

### ISSUE THREAD

**Issue by Xiaflowers** [rustdesk/rustdesk#190]
Hello, thanks so much for your open source project！
What I want to ask is that I ve already run the demo project following the tutorial as shown in the figure below(On ubuntu18).
So what do I do next?
I don t know how to operate next on the client (Windows).

Looking forward to your response！

Actually I don t know how to set the IP address here either. Embarrassing!
![2](https://user-images.githubusercontent.com/52392977/128509161-99afb6ca-0141-46f0-a9f1-06c4d91d7205.jpg)

**Comment by rustdesk** [comment]
> how to set the IP address here either

IP=<public ip of this machine> cargo run

https://rustdesk.com/blog/id-relay-set/

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/115
