### ISSUE TITLE
Client doesn't switch to fullscreen; it stays as smaller-than-desktop window

### ISSUE THREAD

**Issue by 64kramsystem** [rustdesk/rustdesk#1901]
**Describe the bug you encountered:**

I can't switch to fullscreen. I click on the small rectangle in the window top bar (left of the connection name/id), and there switch to fullscreen doesn't happen.

What happens instead is that the client window gets a little bigger, but still leaves large borders on the left/top/right (the desktop background is displayed).

I'm not sure if this issue is the same as #1416 and/or #599 - it may be related, but I think it's different.

**What did you expect to happen instead?**

The client should switch to fullscreen mode (I guess, it should turn into a borderless window).

**How did you install `RustDesk`?**

From sources.

**RustDesk version and environment**

Commit: cd1090efea465122b15edb15466720c7ce67ebd5
Rustc: 1.66.0-nightly (758f19645 2022-10-24)
O/S: Ubuntu MATE 22.04 (X11), both server and client

**Comment by rustdesk** [comment]
@Kingtous

**Comment by Kingtous** [comment]
any screenshots or runtime logs?

**Comment by 64kramsystem** [comment]
> Let's check it. Any screenshots or runtime logs?

I can provide both! I'll reproduce it, and follow up over the next days.

**Comment by Kingtous** [comment]
> > Let's check it. Any screenshots or runtime logs?
> 
> I can provide both! I'll reproduce it, and follow up over the next days.

Perfect! Could you please try our [night build](https://github.com/rustdesk/rustdesk/releases/tag/nightly)? Is nightly build can set fullscreen?

**Comment by 64kramsystem** [comment]
Hello!

Here you can find the screenshots taken of the client full screen (with private information edited out, including the bottom panel), before and after clicking on the fullscreen icon.

For the sake of precision, note that the statement I made about the window getting a bit larger, is not correct - the window size stays the same, but the window header goes away.

I didn't find any obvious log around; while clicking the fullscreen icon, this is what I've observed in the terminal, which I'm not sure if it's relevant:

```
INFO:TIS: enter
INFO:TIS: Update cursor, system: false
INFO:TIS: leave
INFO:TIS: state changed from 1 -> 5
INFO:TIS: enter
INFO:TIS: Update cursor, system: false
INFO:TIS: state changed from 5 -> 1
INFO:TIS: Update cursor, system: false
INFO:TIS: state changed from 1 -> 5
INFO:TIS: Update cursor, system: false
INFO:TIS: Update cursor, system: false
INFO:TIS: leave
```


![client_0_before](https://user-images.githubusercontent.com/1595356/199292680-438c90fb-1c7d-44cb-8600-8f7be266ab29.jpg)
![client_1_fullscreen](https://user-images.githubusercontent.com/1595356/199292707-a8b671f7-d4d7-41ea-b2e8-603b523cd3b3.jpg)

**Comment by rustdesk** [comment]
sciter version is going to be discorded
