### ISSUE TITLE
Wrong char Map Mode

### ISSUE THREAD

**Issue by giuliovale** [rustdesk/rustdesk#1906]
Nightly Build 1.2
Connection windows 11 vs windows 11
Keyboard Map Mode

In the Italian keyboard some characters are wrong:
instead of < comes out ù
instead of > comes out §

**Comment by rustdesk** [comment]
@asur4s

**Comment by furkangkhsn** [comment]
I have a similar issue. I use Turkish Q keyboard. When i press the letter i, it sends ı signal.

**Comment by rustdesk** [comment]
> I have a similar issue. I use Turkish Q keyboard. When i press the letter i, it sends ı signal.

nightly build?

**Comment by furkangkhsn** [comment]
I downloaded the binary from home page.

> > I have a similar issue. I use Turkish Q keyboard. When i press the letter i, it sends ı signal.
> 
> nightly build?

**Comment by rustdesk** [comment]
try out github nightly build please

**Comment by furkangkhsn** [comment]
Nightly build solves the issue for me. Thank you for your great work.
