### ISSUE TITLE
in the intranet,Why is the frame rate and network transmission speed so low compared with the built-in mstsc?

### ISSUE THREAD

**Issue by JerryLiew** [rustdesk/rustdesk#191]
Theoretically speaking, the network transmission speed should be very fast in the intranet. But in fact, it is very slow that i felt very stuck.Under the same conditions(playing a game), the following  screenshot shows that the transmission speed of  mstsc is serveral times  that of rustdesk.  so Is there a network transmission speed limitation?   How to make itas smooth as mstsc.thanks very much.
mstsc:
![zt8ERl0QzE](https://user-images.githubusercontent.com/51161678/128627533-5f9ddb87-97ed-4b11-8d97-fc42925d517b.png)

rustdesk:
![7U3wRY46bX](https://user-images.githubusercontent.com/51161678/128627542-e7255333-e00f-49e6-b170-36b752f53b0a.png)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/79, and also need more guy's contribution, not only ask for help.

**Comment by JerryLiew** [comment]
Supplementary note: I connected the target PC directly through the LAN IP,instead of the relay  server.

**Comment by JerryLiew** [comment]
> #79, and also need more guy's contribution, not only ask for help.

I like rust and rustdesk,but as a beginner of rust language, my skills does not allow me to be a contributor, and I am preparing for the graduate examination this year. In order to learn rust,i sincerely hope I can do something for this project next year.Anyway, thanks for your work.

**Comment by QGB** [comment]
为什么局域网下直连，rustdesk不如mstsc，卡卡的，画面经常不同步？  @rustdesk
