### ISSUE TITLE
Vert Cursor

### ISSUE THREAD

**Issue by AaleeyahIvy** [rustdesk/rustdesk#1910]
The cursor is always displaying as a vertical cursor and I don't know why. When typing, selecting and clicking the cursor is always vertical cursor and doesn't change upon interaction.
- 1.1.9
- [rustdesk-1.1.9-windows_x64.zip](https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-windows_x64.zip)
- On Windows 11.

**Comment by rustdesk** [comment]
not clear

**Comment by rustdesk** [comment]
if you can not state clearly, you should attach a video

**Comment by rustdesk** [comment]
closed before restated
