### ISSUE TITLE
how to connect to a Linux server without a monitor but with fake display using xvfb?

### ISSUE THREAD

**Issue by yluo-astro** [rustdesk/rustdesk#192]
Hi all, 

I am grateful if anyone could help me to remote connect to a server without a moniter.  I have one server that has no display, but if I try to connect with rustdesk, it shows "unsupported display server type, x11 expected".  

I tried a fake display by installing xvfb, but still get no solution.  Could anyone give any comments ?

Thanks,
Y

**Comment by wwjabc** [comment]
https://techoverflow.net/2019/02/23/how-to-run-x-server-using-xserver-xorg-video-dummy-driver-on-ubuntu/

**Comment by congzhangzh** [comment]
#634
