### ISSUE TITLE
Run build_android_deps.sh failed

### ISSUE THREAD

**Issue by NARUTONBM** [rustdesk/rustdesk#1923]
I just clone this repo, and I'm trying to run the flutter part project on win11.

I already install vcpkg and set the flutter Android environment and all those environment variables.

So I start with build_android_deps.sh and it's keeping failing. The following code is full log.

`
$ ./build_android_deps.sh
Cloning into 'build/libvpx'...
remote: Enumerating objects: 1228, done.
remote: Counting objects: 100% (1228/1228), done.
remote: Compressing objects: 100% (1176/1176), done.
remote: Total 1228 (delta 239), reused 142 (delta 30), pack-reused 0
Receiving objects: 100% (1228/1228), 5.47 MiB | 1.48 MiB/s, done.
Resolving deltas: 100% (239/239), done.
Note: switching to '626ff35955c2c35b806b3e0ecf551a1a8611cdbf'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Cloning into 'build/oboe'...
remote: Enumerating objects: 1464, done.
remote: Counting objects: 100% (1464/1464), done.
remote: Compressing objects: 100% (1195/1195), done.
remote: Total 1464 (delta 438), reused 835 (delta 169), pack-reused 0
Receiving objects: 100% (1464/1464), 5.85 MiB | 1.78 MiB/s, done.
Resolving deltas: 100% (438/438), done.
Note: switching to '855ea841a93bf304065e5152909983b1b85ffabb'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

(Stripping trailing CRs from patch; use --binary to disable.)
patching file CMakeLists.txt
Hunk #1 succeeded at 64 (offset 4 lines).
Hunk #2 succeeded at 95 (offset 4 lines).
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/common/AudioStreamBuilder.cpp
Hunk #1 succeeded at 222 (offset 7 lines).
*** [arm64-v8a][Start] Build opus / libyuv from vcpkg
/c/src/vcpkg /d/saas/rustdesk/flutter
Computing installation plan...
The following packages are already installed:
    opus[core]:arm64-android -> 1.3.1#9
opus:arm64-android is already installed
Restored 0 package(s) from C:\Users\amanda.dai\AppData\Local\vcpkg\archives in 87.5 us. Use --debug to see more details.
Total elapsed time: 6.339 ms

opus provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(Opus CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Opus::opus)

Computing installation plan...
The following packages are already installed:
    libyuv[core]:arm64-android -> 2021-04-15#1
libyuv:arm64-android is already installed
Restored 0 package(s) from C:\Users\amanda.dai\AppData\Local\vcpkg\archives in 89.4 us. Use --debug to see more details.
Total elapsed time: 6.005 ms

libyuv provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(libyuv CONFIG REQUIRED)
    target_link_libraries(main PRIVATE yuv)

/d/saas/rustdesk/flutter
*** [arm64-v8a][Finished] Build opus / libyuv from vcpkg
*** [arm64-v8a][Start] Build libvpx
/d/saas/rustdesk/flutter/build/libvpx /d/saas/rustdesk/flutter
make: *** No rule to make target 'clean'.  Stop.
  enabling pic
  disabling vp8
  disabling webm_io
  disabling unit_tests
  disabling examples
  disabling libyuv
  disabling postproc
  disabling tools
  disabling docs
Libdir C:\src\vcpkg/installed/arm64-android/lib must be a subdirectory of C:\src\vcpkg/installed/arm64-android

Configuration failed. This could reflect a misconfiguration of your
toolchains, improper options selected, or another problem. If you
don't see any useful error messages above, the next step is to look
at the configure error log file (config.log) to determine what
configure was trying to do when it died.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
/d/saas/rustdesk/flutter
*** [arm64-v8a][Finished] Build libvpx
*** [arm64-v8a][Start] Build oboe
/d/saas/rustdesk/flutter/build/oboe /d/saas/rustdesk/flutter
make: *** No rule to make target 'clean'.  Stop.
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

-- Building for: Visual Studio 17 2022
CMake Error at CMakeLists.txt:7 (project):
  Failed to run MSBuild command:

    C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe

  to get the value of VCTargetsPath:

    MSBuild version 17.3.1+2badb37d1 for .NET Framework
    生成启动时间为 2022/11/2 14:08:26。
    节点 1 上的项目“D:\saas\rustdesk\flutter\build\oboe\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj”(默认目标)。
    C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(823,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [D:\saas\rustdesk\flutter\build\oboe\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj]
    已完成生成项目“D:\saas\rustdesk\flutter\build\oboe\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj”(默认目标)的操作 - 失败。

    生成失败。

    “D:\saas\rustdesk\flutter\build\oboe\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj”(默认目标) (1) ->
    (_CheckForInvalidConfigurationAndPlatform 目标) ->
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(823,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [D:\saas\rustdesk\flutter\build\oboe\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj]

        0 个警告
        1 个错误

    已用时间 00:00:00.08

  Exit code: 1

-- Configuring incomplete, errors occurred!
See also "D:/saas/rustdesk/flutter/build/oboe/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
mv: cannot stat 'C:\src\vcpkg/installed/arm64-android/lib/arm64-v8a/liboboe.a': No such file or directory
/d/saas/rustdesk/flutter
*** [arm64-v8a][Finished] Build oboe
*** [arm64-v8a][All Finished]
*** [armeabi-v7a][Start] Build opus / libyuv from vcpkg
/c/src/vcpkg /d/saas/rustdesk/flutter
Computing installation plan...
The following packages are already installed:
    opus[core]:arm-android -> 1.3.1#9
opus:arm-android is already installed
Restored 0 package(s) from C:\Users\amanda.dai\AppData\Local\vcpkg\archives in 83.5 us. Use --debug to see more details.
Total elapsed time: 6.375 ms

opus provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(Opus CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Opus::opus)

Computing installation plan...
The following packages are already installed:
    libyuv[core]:arm-android -> 2021-04-15#1
libyuv:arm-android is already installed
Restored 0 package(s) from C:\Users\amanda.dai\AppData\Local\vcpkg\archives in 83.7 us. Use --debug to see more details.
Total elapsed time: 6.033 ms

libyuv provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(libyuv CONFIG REQUIRED)
    target_link_libraries(main PRIVATE yuv)

/d/saas/rustdesk/flutter
*** [armeabi-v7a][Finished] Build opus / libyuv from vcpkg
*** [armeabi-v7a][Start] Build libvpx
/d/saas/rustdesk/flutter/build/libvpx /d/saas/rustdesk/flutter
make: *** No rule to make target 'clean'.  Stop.
  enabling pic
  disabling vp8
  disabling webm_io
  disabling unit_tests
  disabling examples
  disabling libyuv
  disabling postproc
  disabling tools
  disabling docs
Libdir C:\src\vcpkg/installed/arm-android/lib must be a subdirectory of C:\src\vcpkg/installed/arm-android

Configuration failed. This could reflect a misconfiguration of your
toolchains, improper options selected, or another problem. If you
don't see any useful error messages above, the next step is to look
at the configure error log file (config.log) to determine what
configure was trying to do when it died.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
/d/saas/rustdesk/flutter
*** [armeabi-v7a][Finished] Build libvpx
*** [armeabi-v7a][Start] Build oboe
/d/saas/rustdesk/flutter/build/oboe /d/saas/rustdesk/flutter
make: *** No rule to make target 'clean'.  Stop.
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

CMake Error at CMakeLists.txt:7 (project):
  Failed to run MSBuild command:

    C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe

  to get the value of VCTargetsPath:

    MSBuild version 17.3.1+2badb37d1 for .NET Framework
    生成启动时间为 2022/11/2 14:08:28。
    节点 1 上的项目“D:\saas\rustdesk\flutter\build\oboe\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj”(默认目标)。
    C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(823,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [D:\saas\rustdesk\flutter\build\oboe\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj]
    已完成生成项目“D:\saas\rustdesk\flutter\build\oboe\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj”(默认目标)的操作 - 失败。

    生成失败。

    “D:\saas\rustdesk\flutter\build\oboe\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj”(默认目标) (1) ->
    (_CheckForInvalidConfigurationAndPlatform 目标) ->
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(823,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [D:\saas\rustdesk\flutter\build\oboe\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj]

        0 个警告
        1 个错误

    已用时间 00:00:00.10

  Exit code: 1

-- Configuring incomplete, errors occurred!
See also "D:/saas/rustdesk/flutter/build/oboe/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
mv: cannot stat 'C:\src\vcpkg/installed/arm-android/lib/armeabi-v7a/liboboe.a': No such file or directory
/d/saas/rustdesk/flutter
*** [armeabi-v7a][Finished] Build oboe
*** [armeabi-v7a][All Finished]
`

Any advices to fix this error? Thanks a lot.

**Comment by rustdesk** [comment]
#763
