### ISSUE TITLE
rustdesk.exe white screen

### ISSUE THREAD

**Issue by mrwrighty** [rustdesk/rustdesk#1929]
When running cargo run --release rustdesk will compile and run with the correct interface. I can connect to the client. However if I subsequently run rustdesk.exe I just get a white screen which is about 4 x the size of the proper rustdesk screen. Although nothing is displayed, I can connect to the client.

So After margin run --release I get

![Screenshot 2022-11-02 at 13 07 25](https://user-images.githubusercontent.com/6585298/199497734-ec1614d8-6695-4f19-8368-19463afef6f3.png)

If I run the compile rustdesk.exe I get

![Screenshot 2022-11-02 at 12 54 07](https://user-images.githubusercontent.com/6585298/199497810-30ac15d5-57bd-4bd9-83ee-a8d49229475d.png)

**Comment by rustdesk** [comment]
#763

**Comment by mrwrighty** [comment]
Sorry why is this closed. I have built according to [#763](https://github.com/rustdesk/rustdesk/discussions/763) and getting the white screen. I cannot find on the link you posted anything relating to this issue.
