### ISSUE TITLE
Copy and Paste file directly in a remote desk session

### ISSUE THREAD

**Issue by lc700x** [rustdesk/rustdesk#193]
Can Rustdesk directly copy and paste files between host and client by dragging or use clip board like this feature in Teamviewer?

**Comment by chenall** [comment]
+1

向日葵已是一样的操作,感觉比较方便,希望开发者可以考虑添加这个功能.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/718
