### ISSUE TITLE
Unable to copy and transfer specially formatted data between clients and remote desktops

### ISSUE THREAD

**Issue by BAKAOLC** [rustdesk/rustdesk#1935]
**Describe the bug you encountered:**

If the clipboard is copied in a format similar to image data, it will not be able to be copied and transferred between the client and the remote desktop.

**What did you expect to happen instead?**

It should be copied correctly and pasted in the device on the other end.

**How did you install `RustDesk`?**

GitHub release

---

**RustDesk version and environment**

client: 1.1.9 windows 10
remote: 1.1.9 windows 11

**Comment by rustdesk** [comment]
duplicate
