### ISSUE TITLE
rustdesk-server-demo error

### ISSUE THREAD

**Issue by xiaofengtongxue** [rustdesk/rustdesk#194]
根据步骤，下载好rustdesk-server-demo，安装rustup ，无法启动
![image](https://user-images.githubusercontent.com/17273994/128656170-bd410b35-7575-484d-be25-568096fd2e14.png)

**Comment by rustdesk** [comment]
you need vpn

**Comment by xiaofengtongxue** [comment]
什么意思？可否更详细一点，服务器为阿里云centos7.6  有公网IP

**Comment by rustdesk** [comment]
If you still need my private help, [buy me a good hotpot](https://github.com/sponsors/rustdesk/sponsorships?sponsor=rustdesk&tier_id=84000&preview=false) please!
