### ISSUE TITLE
excessive cpu usage in linux nightly

### ISSUE THREAD

**Issue by test2a** [rustdesk/rustdesk#1947]
**Describe the bug you encountered:**
cpu is up to 20.5% which is while rustdesk isn't even connected to a remote machine..

![Screenshot_20221103_222256](https://user-images.githubusercontent.com/39449563/199785182-afd0f5b7-fe38-42c9-9eb5-194e6e036b79.png)

...

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**
github nightly

---

**RustDesk version and environment**

**Comment by rustdesk** [comment]
@Kingtous

**Comment by Kingtous** [comment]
did u just start rustdesk and do nothing？

**Comment by test2a** [comment]
@Kingtous 
![Screenshot_20221104_104005](https://user-images.githubusercontent.com/39449563/199893923-ce33826e-0a00-4880-84cf-964a620cdb6c.png)
![Screenshot_20221104_103913](https://user-images.githubusercontent.com/39449563/199893957-4c078d62-4877-47d8-a344-48a210ac85a3.png)


here is system monitor right now being connected to a windows machine. 58.8% even, i could not take a photo of that.
i am trying to recreate yesterday's after disconnection high CPU usage but this too looks very high. ok.  i am up to 61% now

**Comment by test2a** [comment]
@Kingtous ok. so i in the above screenshot i was connected to a machine so i disconnected and let it sit while i was writing this and suddenly the CPU is up to now 25%.... from rustdesk.

can i send you some logs or something?

**Comment by rustdesk** [comment]
@test2a Thanks for your report, we get some clue and will fix it soon.

**Comment by rustdesk** [comment]
@test2a could you try new nightly again?

**Comment by test2a** [comment]
@rustdesk ok. i do apt remove and install the nightly version and the cpu usage is now in cycles. 

up and down, 

i have left the remote connection "connected" and using other local windows and the graph shows just plain 35% all the time.
![Screenshot_20221105_105132](https://user-images.githubusercontent.com/39449563/200102593-27cf66cf-dd99-4bff-8532-733f4e32957d.png)


here is after i started directly using remote window for 1-2 minutes.
![Screenshot_20221105_105307](https://user-images.githubusercontent.com/39449563/200102872-ebf4c09d-59c2-4274-8434-13f5fa8a2c92.png)

so from this i can gather, keeping the rustdesk as top active window keeps the cpu usage to minimum but if it goes behind other active windows, the usage just keeps on growing

**Comment by rustdesk** [comment]
can you help compare cpu usage with 1.1.9?

**Comment by test2a** [comment]
@rustdesk ok. i installed 1.1.19 from github after removing nightly and the usage is 0.3%.

when using it,  the cpu usage doesnt go much and the RAM is also very low. check the screenshots 
![Screenshot_20221105_113402](https://user-images.githubusercontent.com/39449563/200105101-e6dcd1d8-1d02-4252-a234-1d101a27fc72.png)

**Comment by test2a** [comment]
@rustdesk 1.1.9 does not even show up in the graph on the right side for the most time

**Comment by rustdesk** [comment]
@Kingtous the memory usage is acceptable, but seems much more than dart vm usage, the  cpu usage is still high.

**Comment by Kingtous** [comment]
> @rustdesk ok. i do apt remove and install the nightly version and the cpu usage is now in cycles.
> 
> up and down,
> 
> i have left the remote connection "connected" and using other local windows and the graph shows just plain 35% all the time. ![Screenshot_20221105_105132](https://user-images.githubusercontent.com/39449563/200102593-27cf66cf-dd99-4bff-8532-733f4e32957d.png)
> 
> here is after i started directly using remote window for 1-2 minutes. ![Screenshot_20221105_105307](https://user-images.githubusercontent.com/39449563/200102872-ebf4c09d-59c2-4274-8434-13f5fa8a2c92.png)
> 
> so from this i can gather, keeping the rustdesk as top active window keeps the cpu usage to minimum but if it goes behind other active windows, the usage just keeps on growing

I cannot reproduce the excessive cpu usage on my manjaro using latest nightly build. I connected to a remote computer, and KDE monitor shows below:
![image](https://user-images.githubusercontent.com/39793325/200153284-85e9968f-d642-4945-91db-1fb93e277bda.png)

If I use other windows and unfocus the window, the cpu usage is becoming lower.

![image](https://user-images.githubusercontent.com/39793325/200153471-831cc4c3-dc13-400b-bb41-c344e25e704e.png)


btw, I highly doubt there's some render issues on flutter engine. Could u please provide some cpu usage clues?

Steps: 
- `perf record -F 99 -p RUSTDESK_PID -g -- sleep 60`, `RUSTDESK_PID` can be found by `ps -aux | grep rustdesk`
- wait for one minute, `perf` will sample cpu usage of rustdesk. Then u can upload `perf.data` generated by the command above.

And what are the graphic cards u use and your graphic drivers (nouveau or something)?

**Comment by test2a** [comment]
@Kingtous i installed the latest nightly today after removing 1.1.9 and the performance looks much better, same as your screenshots so it must've been something in the interim that fixed. i am going to install 2-3-5 days old nightly versions and send you perf data..

no dedicated graphics. 

Operating System: KDE neon 5.26
KDE Plasma Version: 5.26.2
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.7
Kernel Version: 5.15.0-52-generic (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i7-4600U CPU @ 2.10GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 4400
Manufacturer: Dell Inc.
Product Name: Latitude E7440
System Version: 01

**Comment by Kingtous** [comment]
> @Kingtous i installed the latest nightly today after removing 1.1.9 and the performance looks much better, same as your screenshots so it must've been something in the interim that fixed. i am going to install 2-3-5 days old nightly versions and send you perf data..
> 
> no dedicated graphics. 
> 
> Operating System: KDE neon 5.26
> KDE Plasma Version: 5.26.2
> KDE Frameworks Version: 5.99.0
> Qt Version: 5.15.7
> Kernel Version: 5.15.0-52-generic (64-bit)
> Graphics Platform: X11
> Processors: 4 × Intel® Core™ i7-4600U CPU @ 2.10GHz
> Memory: 7.7 GiB of RAM
> Graphics Processor: Mesa Intel® HD Graphics 4400
> Manufacturer: Dell Inc.
> Product Name: Latitude E7440
> System Version: 01

perfect, thanks for reporting.

**Comment by xzipyx** [comment]
> can you help compare cpu usage with 1.1.9 based on above two scenarios?

I experienced the same on arch + gnome + x11. High load when I connect to the nightly or git compiled version. The stable version is not affected.

**Comment by rustdesk** [comment]
> git compiled

then please help dig in.

**Comment by wakewon** [comment]
I found a similar issue on macOS. RustDesk server daemon `/Applications/RustDesk.app/Contents/MacOS/rustdesk --server` always take nearly 90% usage of CPU (maybe a core?) even without any connection. Once this service has been stopped, the high-usage item in system activity monitor will be disappear for seconds.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/40191996/220589503-933a8877-91ca-4fc2-952c-f507d8fc2ca9.png">

Meanwhile, it seems that `com.carriez.RustDesk_server.plist` cannot be unload, and this servies always restart no matter how I stop it (making it really hard to upgrade).

> macOS 13.2.1, Intel
> RustDesk nightly 1.2.0, Build date: 2023-02-22 00:16

**Comment by rustdesk** [comment]
@wakewon noted.

**Comment by xzipyx** [comment]
> > git compiled
> 
> then please help dig in.

how can i help, i just installed it from arch user repository

**Comment by rustdesk** [comment]
@21pages looks like it happens lately, please confirm.

**Comment by 21pages** [comment]
Ok, let me try flamegraph first

**Comment by rustdesk** [comment]
> how can i help

Sadly, I can not reproduce on Linux and Mac. You can try out chatgpt.

![image](https://user-images.githubusercontent.com/71636191/220841054-537e12e3-4760-4839-b60a-60946001504d.png)

**Comment by wakewon** [comment]
> > how can i help
> 
> Sadly, I can not reproduce on Linux and Mac. You can try out chatgpt.
> 
> ![image](https://user-images.githubusercontent.com/71636191/220841054-537e12e3-4760-4839-b60a-60946001504d.png)

Well... I have no idea how to provide a way to reproduce this issue since it just happens.

Without server agent:
![image](https://user-images.githubusercontent.com/40191996/220848373-0db713db-268d-4100-bd29-0e0309cbc10d.png)

Once server agen has been launchedt:
![image](https://user-images.githubusercontent.com/40191996/220849274-094a84e7-c594-42dc-a18c-db28c61db6fe.png)

**Comment by rustdesk** [comment]
Let me know if you can get anything.

![image](https://user-images.githubusercontent.com/71636191/220852404-9806bbf0-c7dd-4f4a-b741-94be06ac940f.png)

**Comment by wakewon** [comment]
> Let me know if you can get anything.
> 
> ![image](https://user-images.githubusercontent.com/71636191/220852404-9806bbf0-c7dd-4f4a-b741-94be06ac940f.png)

Sadly, my "Inspect" window doesn't have a "CPU" tab or a "Threads" tab.
<img width="559" alt="image" src="https://user-images.githubusercontent.com/40191996/220860034-36c072af-1c58-4190-a7f2-8e415dbcd9a5.png">

Here is my sampling result, 
[Sampling of "RustDesk".txt](https://github.com/rustdesk/rustdesk/files/10811777/Sampling.of.RustDesk.txt)
I don't know whether it is helpful.

**Comment by rustdesk** [comment]
Thanks a lot, though I can not get helpful message from the file so far.

**Comment by rustdesk** [comment]
But good news, I reproduced the problem.

**Comment by wakewon** [comment]
> But good news, I reproduced the problem.

Here are more detail for this issue (maybe still not helpful at all):
If remove RustDesk's server's global agent and start RustDesk manually, this issue can be override, and this device can still be accessed.
Meanwhile, running RustDesk's server by `/Applications/RustDesk.app/Contents/MacOS/rustdesk --server` can also reproduce this problem.

Another thing is that I found I cannot see my cursor (iOS -> macOS) in the latest nightly build. Maybe I will write a new issue for this problem.

**Comment by rustdesk** [comment]
https://github.com/tauri-apps/tray-icon/issues/30

**Comment by xzipyx** [comment]
> cursor

do you have a mouse and keyboard attached? if not, it will show a pointer instead of cursor

**Comment by wakewon** [comment]
> > > But good news, I reproduced the problem.
> > 
> > 
> > Here are more detail for this issue (maybe still not helpful at all): If remove RustDesk's server's global agent and start RustDesk manually, this issue can be override, and this device can still be accessed. Meanwhile, directly running RustDesk's server in Terminal with `/Applications/RustDesk.app/Contents/MacOS/rustdesk --server` can also reproduce this problem (the agent service is previously disabled).
> > Another thing is that I found I cannot see my cursor (iOS -> macOS) when connecting to the latest nightly build for macOS. Maybe I will open a new issue for this problem later.
> 
> do you have a mouse and keyboard attached? if not, it will show a pointer instead of cursor

Nope. No mouse or keyboard has been connected to local iOS/macOS device.

When connected to another remote device (Windows, nightly, Build Date: 2023-02-18 00:32), I can see the cursor on both mouse mode and touch mode. 
![IMG_01DC86E15554-1](https://user-images.githubusercontent.com/40191996/221079902-6fb0c2e0-c929-4376-b6e8-4f8a9a9a51a6.jpeg)

While connect to macOS (nightly, Build Date: 2023-02-24 00:18), I can't see any cursor on either mode.
![IMG_F5EE73B5EB23-1](https://user-images.githubusercontent.com/40191996/221079932-38fcd544-5709-4c71-a87b-b5c5f81f336f.jpeg)

It should be notice that control works, and I can see the curson on remote computer's physical screen is moving. I think this issue only happened on recent builds (macOS, Build Date: 2023-02-18 00:20 works well before).

**Comment by rustdesk** [comment]
> macOS, Build Date: 2023-02-18 00:20 works well before

you can try out macOS 1.1.9. We have never touch "cursor" related code for more than 1 years.

**Comment by wakewon** [comment]
> > macOS, Build Date: 2023-02-18 00:20 works well before
> 
> you can try out macOS 1.1.9. We have not touched "cursor" related code on controlled side for more than 1 year.

1.1.9 works well.
![IMG_2113](https://user-images.githubusercontent.com/40191996/221082578-d4636dd3-1b10-4d1e-bfd7-d83536866e54.PNG)

I can't find my macOS 2023-02-18 00:20 build now, and I belive it worked well. I assume it is a problem caused by a recent change (flutter?). Windows's latest build also works well. This issue only happens on macOS.

Ummm... I found another issue now... It seems "Lock after session end" doesn't work now on both Windows and macOS. I don't know when does this start.

Another thing... If the remote computer didn't lock before connection, "Auto Login" makes macOS remote device waiting at the Apple menu. After trigger Esc on keyboard, the OS Password will be automatically input. I think this function should't perform any action if the remote device did't locked.

**Comment by rustdesk** [comment]
I reproduced it. @fufesou

**Comment by rustdesk** [comment]
> Lock after session end

Nothing to do with remote side. iOS has this bug, long time not updated yet. 

> "Auto Login"

I knew this when I wrote it. Allow us more time to perfect all details. We knew a lot of "should not".

**Comment by wakewon** [comment]
> > Lock after session end
> 
> Nothing to do with remote side. iOS has this bug, long time not updated yet.
> 
> > "Auto Login"
> 
> I knew this when I wrote it. Allow us more time to perfect all details. We knew a lot of "should not".

I see. Everything is getting better and thx a lot to the whole team.

**Comment by wakewon** [comment]
> iOS has this bug, long time not updated yet.

I test "Lock after session end" again, found that a connection as macOS -> Windows (both latest nightly) also cannot auto lock the remote side. I have no impression of this problem in the earlier version (2023-02-18 00:20 build).

Manual lock triggered by the button in RustDesk menu works.

**Comment by fufesou** [comment]
> I test "Lock after session end" again, found that a connection as macOS -> Windows (both latest nightly) also cannot auto lock the remote side.

@wakewon Thanks for your feedback. This issue should be fixed by PR 3356 mentioned above.

**Comment by rustdesk** [comment]
created an issue for the cursor issue https://github.com/rustdesk/rustdesk/issues/3408
