### ISSUE TITLE
ConnectionManager issues in Nightly Build

### ISSUE THREAD

**Issue by bdntv** [rustdesk/rustdesk#1951]
**Describe the bug you encountered:**

Beginning on Oct 27 commit (nightly), if user clicks "accept" button, cm minimizes as should. However, if connection requires password input, the cm closes completely with error "ERROR librustdesk::server::connection] ipc to connection manager exit: reset by the peer" Remote control still functions, but you lose the ability to chat or view the cm.

**What did you expect to happen instead?**

cm should minimize as it does if the user clicked accept

**How did you install `RustDesk`?**

GitHub (Nightly)

**RustDesk version and environment**

Version 1.20 - Nightly build. (Still works on Oct 26 commit) sciter build
Windows 10 & 11

**Comment by rustdesk** [comment]
then, why do not you help fix it?

**Comment by bdntv** [comment]
As stated before, I’m new to rust and using this as a learning curve too. I’m actively going through the code to see if I can figure it out. I was merely just reporting what I’ve found as many others have previous. If you do not wish for me to do that, I can stop until I’m more comfortable with the language. Was just trying to help in a debugging role.

**Comment by rustdesk** [comment]
Sorry, i forgot your previous station, please go ahead with your testing, it is also very important for us. @21pages please follow up this issue.

**Comment by rustdesk** [comment]
@bdntv could you help find whose commit cause this issue?

**Comment by bdntv** [comment]
From what I’m seeing right now it looks like it starts with Oct 27 commit from fufesou

**Comment by bdntv** [comment]
Still functions as of Oct 26

**Comment by rustdesk** [comment]
@bdntv Thanks

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
@bdntv Thanks for your feedback. But I cannot reproduce this problem on the latest commit(master).  I've tested both sciter and flutter versions.
Is your both sides Version 1.2.0 - Nightly build (latest build) ? Or 1.2.0 Nightly self-side and 1.1.9 peer-side?

**Comment by fufesou** [comment]
@bdntv I've reproduce this problem. I'll fix it on my next commit.

**Comment by bdntv** [comment]
Awesome. Thanks. Great work

**Comment by bdntv** [comment]
Works great. Only thing I would mention is maybe have the cm minimize upon connection with password like it does with clicking the accept button. I am going to play around on my end and see if I can figure that out as well. But like I said, still learning. I know the accept button minimizes through the tis file, just trying to figure out how I would call that via the rs source.

**Comment by bdntv** [comment]
I figured it out and have submitted the request.
