### ISSUE TITLE
Multiline text message support

### ISSUE THREAD

**Issue by itbencn** [rustdesk/rustdesk#1972]
The message sent by both the control end and the controlled end supports multi line text sending

**Comment by rustdesk** [comment]
@21pages , flutter only

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
@NicKoehler do you have interest to implement this? No hurry, just take your time.

**Comment by NicKoehler** [comment]
I'll take a look

**Comment by rustdesk** [comment]
👍

**Comment by NicKoehler** [comment]
Removing `sendOnEnter` from `InputOptions` seems to do it, the only drawback is that to send a message you need to press the the send button with the mouse.

**Comment by rustdesk** [comment]
Yes, it bring another inconvience.

**Comment by rustdesk** [comment]
close as fix merged
