### ISSUE TITLE
rustdesk can't display the remote Ubuntu 22.04.1 desktop 

### ISSUE THREAD

**Issue by lanbao2021** [rustdesk/rustdesk#1973]
**Describe the bug you encountered:**

rustdesk can't display the remote Ubuntu 22.04.1 desktop 

I tried to reinstall the Ubuntu 22.04.1 desktop, it happened again.

I tried to reinstall the rustdesk 1.1.9, it happened again.

I tried to reinstall the Ubuntu Server 22.04.1 -> install ubuntu-desktop -> happened again...

I tried to use my RelayServer,  it happened again.

I tried to use the default free server, it happened again.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/77654725/200111721-4261cb6d-0b40-4ea8-b71f-ceb6734423b5.png">

**What did you expect to happen instead?**

It should works all right.

**How did you install `RustDesk`?**

I installed RustDesk by the command: `sudo dpkg -i rustdesk-xxx.deb`

---

**RustDesk version and environment**

Rustdesk 1.1.9

**Comment by rustdesk** [comment]
dup #426
