### ISSUE TITLE
CTRL (copy funciton)

### ISSUE THREAD

**Issue by riyadist** [rustdesk/rustdesk#1974]
Hi

I am using 3d modelling program and the ctrl (copy) shortcut is not working well. When I hold ctrl it doesn't run stable. I checked in the anydesk it works well

**Comment by rustdesk** [comment]
checkout nightly build please

**Comment by rustdesk** [comment]
Another case:

> Pressing Ctrl has the effect of Ctrl + Tab, causing me to press Ctrl + C unsuccessfully.
> I have connected to peer before, and then closed the connection, leaving only one main page running. With RustDesk off, the keyboard works fine.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1974

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1547

**Comment by fufesou** [comment]
@riyadist Can you try the nightly build, with "Map mode". Thanks.
I've fixed the sticky key on Dec 10 2022.

<img width="235" alt="20230104201351" src="https://user-images.githubusercontent.com/13586388/210558617-c9e9c3e9-8427-435e-b14b-fc490ae58992.png">

**Comment by rustdesk** [comment]
close since no response.
