### ISSUE TITLE
Allow to use video codecs other than VP9 (for better performance on low-end/older hardware)

### ISSUE THREAD

**Issue by tomasz1986** [rustdesk/rustdesk#1981]
At the moment, RustDesk uses the VP9 codec to compress video, which is very slow on low-end/older hardware with no hardware decoding support for the codec. For instance, we use RustDesk on systems that are based on older and rather slow Intel/AMD CPUs, and the average CPU usage of the program just to display the screen is between 25% (on the faster systems) and 50% in the worst case (on Intel Atom). Because of this, not much CPU is left for other tasks, and also the remote control itself is just laggy and slow to respond.

I don't want to bring up other software, but AnyDesk does perform way better on the same hardware. I would prefer to stick to RustDesk due to it being open source software though. Just for the record, all devices in question run Windows 10.

**Comment by rustdesk** [comment]
try out nightly build

**Comment by tomasz1986** [comment]
Is the nightly build going to be available for x86 platforms? I can't test the most affected one (Intel Atom) because it runs Windows x86 (and can't run Windows x64 due to 32-bit UEFI).
