### ISSUE TITLE
Option to disable popup notification for incoming connections without password

### ISSUE THREAD

**Issue by korden32** [rustdesk/rustdesk#1982]
There should be a security option to disable popup "Accept/decline" notification so only password-authenticated connections could be made.

**Comment by rustdesk** [comment]
done

**Comment by rustdesk** [comment]
nightly build

**Comment by AbstractFlame** [comment]
Hi, I've tried many versions and I couldn't see the s option. I have set the permanent password too, but even that did not help. Please help. What is the best version and the best way to set unattended connection?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/6008
