### ISSUE TITLE
Unable to navigate Kodi/Xbmc thru RustDesktop client

### ISSUE THREAD

**Issue by bigretromike** [rustdesk/rustdesk#1989]
**Describe the bug you encountered:**
Unable to navigate Kodi (xbmc) via rustdesk on windows 10 client - mouse work fine, keyboard is not responding. Also trying to move any navigation in fullscreen kodi via rustdesk results in Kodi crashing/freezing.

...

**What did you expect to happen instead?**

I should be able to navigate (arrows) the menu inside Kodi as im able with vnc/anydesk/teamviewer/rdp
...

**How did you install `RustDesk`?**

via official installer

---

**RustDesk version and environment**
Client Stable 1.1.9
Windows 10 LTSC Target (with Kodi)
Windows 11 Pro Client
Kodi 19.4

**Comment by rustdesk** [comment]
try out nightly build please, on both side

**Comment by rustdesk** [comment]
reported from email:

> Delete key not work in Houdini  app.

**Comment by rustdesk** [comment]
@asur4s

**Comment by bigretromike** [comment]
I will close this, because https://github.com/rustdesk/rustdesk/commit/52ce3dd2c299e262a54af0b5350fa60f66215e60  build allow me to naviaget, thru kodi still freeze on exit, but I call this a success because I can kill it thru Task Manager, the bigger problem which was no navigation is fixed.
