### ISSUE TITLE
Run failed on Ubuntu16 with deb

### ISSUE THREAD

**Issue by fy2462** [rustdesk/rustdesk#199]
Hi guys,

I have installed the `rustdesk-1.1.6-ubuntu16.deb` on Ubuntu-16, but it is failed when launch, and output as follow:

`thread 'main' panicked at 'error: 'libsciter-gtk.so' was not found neither in PATH nor near the current executable.
  Please verify that Sciter SDK is installed and its binaries (from bin.lnx) are available in PATH.', /home/hzhou/rust-sciter/src/lib.rs:354:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

How to fix that? anybody knows how to install the `libsciter-gtk.so` correctly?

Thanks.

**Comment by fy2462** [comment]
Fix that after installing the `vcpkg/vcpkg install libvpx libyuv opus`.

But could we add any related dependency file in the deb file to fix it? 
@rustdesk 

Thanks.

**Comment by rustdesk** [comment]
No, rustdesk-1.1.6-ubuntu16.deb is not related to vcpkg. vcpkg is only need if you wanna build from source code.

**Comment by fy2462** [comment]
> No, rustdesk-1.1.6-ubuntu16.deb is not related to vcpkg. vcpkg is only need if you wanna build from source code.

But why did the Rustdesk output the error as below and how to fix it? do you have any idea? @rustdesk

**Comment by 21pages** [comment]
https://github.com/rustdesk/rustdesk#build
`wget https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin.lnx/x64/libsciter-gtk.so` 
Did you do this step?

**Comment by VladislavNekto** [comment]
I get this trouble when build release with docker and 
`

**Comment by VladislavNekto** [comment]
I get this when i build release in docker with this settings in Cargo.toml. 
```
[features]
default = ["use_dasp", "inline"]
```
