### ISSUE TITLE
RustDesk could not paste screenshot on the remote computer

### ISSUE THREAD

**Issue by aoozoo** [rustdesk/rustdesk#1995]
**Describe the bug you encountered:**

I took a screenshot on my local computer, copied it to the clipboard, and could not paste it on the remote computer, but the text was fine.

**What did you expect to happen instead?**

I would like to be able to paste my screenshots on a remote computer

**How did you install `RustDesk`?**

GitHub release

**RustDesk version and environment**

Windows 10
RustDesk Version 1.1.9

Build your own server
docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
docker.io/rustdesk/rustdesk-server   latest              fdd2924f0c5f        2 months ago        95.3 MB

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/683

**Comment by rustdesk** [comment]
ready now https://x.com/rustdesk/status/1807981430775206289
