### ISSUE TITLE
外网无法访问 和rustdesk server 同一个局域网的客户端

### ISSUE THREAD

**Issue by js571** [rustdesk/rustdesk#1996]
**Describe the bug you encountered:**
场景：家里的群晖搭建了rustdesk server,  家里还有台PC使用群晖当ID服务器, 路由器端口(21115-21119)映射到群晖，外网一台通过家里外网ip当id服务器，中继服务器能连接上，客户端显示就绪，公司pc客户端使用id请求连接家里pc的时候，提示 connection reset by peer (os error 54)
...

**What did you expect to happen instead?**
这种网络环境下也能连接
...

**How did you install `RustDesk`?**

下载的官方客户端安装

**RustDesk version and environment**

外网 mac版本 1.1.9
家里pc 1.1.9

**Comment by rustdesk** [comment]
#763

**Comment by uniartisan** [comment]
![image](https://user-images.githubusercontent.com/31544054/201291807-d924b706-c99a-40ac-8b27-a99fd3c2ae83.png)
我的问题是部署后同局域网下的linux设备无法连接，win设备可以连接。外网设备可以连接。

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/wiki/FAQ#deploy-rustdesk-server-in-intranet
