### ISSUE TITLE
Source Code Build

### ISSUE THREAD

**Issue by Kevin2021-jk** [rustdesk/rustdesk#20]
Is it difficult to configure the environment for this source code build? After reading half a day did not understand how to build this build environment, and asked for a slightly more detailed tutorial steps.

**Comment by rustdesk** [comment]
For begin learner, it is difficult.

**Comment by rustdesk** [comment]
> detailed tutorial steps

hope you can contribute.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/19
