### ISSUE TITLE
HarmoneyOS voice record

### ISSUE THREAD

**Issue by wcdn** [rustdesk/rustdesk#2000]
鸿蒙操作系统(2.0版本)的手机作为被控端，显示当前安卓版本不支持“音频录制”，请升级至安卓10及以上。
腾讯会议也是利用的屏幕录制，是可以录制内部声音的，所以Rustdesk可否对鸿蒙系统做一下适配，谢谢！

**Comment by wcdn** [comment]
当时鸿蒙版本为2.0.0.276

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/849#issuecomment-1306748848
