### ISSUE TITLE
win11 官网下载最新版  一直产生不了id

### ISSUE THREAD

**Issue by unity20221019** [rustdesk/rustdesk#2005]
![image](https://user-images.githubusercontent.com/116188011/200469236-b89ab8b3-6cc5-4bcc-9b1b-d886aa54451c.png)

![image](https://user-images.githubusercontent.com/116188011/200469306-22fc1fcd-8870-4e34-9d37-a893001cdc8a.png)

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/314 or try out self-host

**Comment by rustdesk** [comment]
maybe https://github.com/rustdesk/rustdesk/discussions/5209
