### ISSUE TITLE
anydesk does not handle keyboard

### ISSUE THREAD

**Issue by chiehw** [rustdesk/rustdesk#2006]
keyboard has 2 problems for me.

1. nested anydesk does not handle keyboard. so i am on linux host, rustdesk into windows machine. from there, anydesk into another windows machine. keyboard does not go from my host>rustdesk>windows>anydesk>windows
2. there is a windows software that refuses certain keyboard inputs from rustdesk host.  i am using rustdesk on linux host rustdesk into windows machine. so the number and alphabets work , esc key works but arrow keys don't. alt, shift are broken the same

_Originally posted by @test2a in https://github.com/rustdesk/rustdesk/issues/1934#issuecomment-1301686696_

**Comment by asur4s** [comment]
@rustdesk Can you add a bug label for me?

**Comment by rustdesk** [comment]
added, Thanks

**Comment by Birol2010** [comment]
small i key doesnt work in Turkish keyboard also. If I press i in keyboard, it appears as ı in remote client.

**Comment by rustdesk** [comment]
> small i key doesnt work in Turkish keyboard also. If I press i in keyboard, it appears as ı in remote client.

Which build?

**Comment by rustdesk** [comment]
@Birol2010 please try out nightly build if you are taling about 1.1.9.

**Comment by Birol2010** [comment]
I am using 1.1.9 version. Dowloaded www.rustdesk.com

**Comment by rustdesk** [comment]
then try out nightly build please. https://github.com/rustdesk/rustdesk/releases/tag/nightly

**Comment by MANKUD** [comment]
> then try out nightly build please. https://github.com/rustdesk/rustdesk/releases/tag/nightly

Hello the nightly build does not seem to be working on windows server 2016.

![image](https://user-images.githubusercontent.com/83474708/201316957-c786a38f-90ce-4fed-86e2-62941f381001.png)

![image](https://user-images.githubusercontent.com/83474708/201317021-a3de513c-5070-45f0-a42d-0c8d2af002f2.png)

**Comment by MANKUD** [comment]
oh ok so the nightly build is only for the latest version of windows due to limitations of Github CI and the future stable build should support older versions too.

**Comment by rustdesk** [comment]
https://github.com/pypa/cibuildwheel/issues/423#issuecomment-677763904

**Comment by rustdesk** [comment]
#1547

**Comment by ForsakenRei** [comment]
With latest nightly build, Map mode didn't work but Legacy mode will work in this specific case, but we might want more test to replicate the workaround.

**Comment by rustdesk** [comment]
wont fix nested anydesk
