### ISSUE TITLE
Reset by the peer once any keyboard input is given, 2nd connection always hangs at connecting

### ISSUE THREAD

**Issue by ForsakenRei** [rustdesk/rustdesk#2013]
**Describe the bug you encountered:**

1. When connected to a remote, as long as I have any keyboard input, like typing some code it will display connection error-reset by the peer, mouse input has no issue. Then rustdesk will try to reconnect, once the reconnect finished, usually everything works but it's not 100%.
2. When I already have one connect to one of my machiens, if I want to have a 2nd connection to another machine, it will just keep connecting. Once I close the 1st connection it will get connected.

**What did you expect to happen instead?**

1. keyboard works normally on remote
2. can have simultaneously connection to multiple machines

**How did you install `RustDesk`?**

Windows 10 and Windows 11.
I used nightly 1.2.0, but I'm not sure if it is the latest one as the nightly release on release page is on 
https://github.com/rustdesk/rustdesk/commit/52ce3dd2c299e262a54af0b5350fa60f66215e60?

**RustDesk version and environment**

Self hosted docker server with nightly 1.2.0

**Comment by rustdesk** [comment]
@fufesou anyway, please verify the latest nightly build still have above issues.

**Comment by ForsakenRei** [comment]
> @fufesou anyway, please verify if the latest nightly build still have above issues.

Anywhere I can get the latest nightly build on the latest commit instead of built myself? Thanks.

**Comment by ForsakenRei** [comment]
> This morning build should not have above issues. Today's commit has nothing to do with above.

Got it. I will give it a try later.
