### ISSUE TITLE
Window position lost in Nightly

### ISSUE THREAD

**Issue by spamitinmy** [rustdesk/rustdesk#2014]
**Describe the bug you encountered:**

Using Nightly build, every time after closing the main RustDesk window after closing the session, the position of the previous window location is not saved. It goes back to original location (ie center of the screen). Closing the session and then reopening the remote session without closing the main RustDesk window will not lose the previous window position of the session.

**What did you expect to happen instead?**

In Release build 1.1.9, it would save the previous session's window position. For example after restarting my machine (or even just closing RustDesk), it would save the position and the next time I use RustDesk, it would keep the same position.

**How did you install `RustDesk`?**

GitHub nightly build install

---

**RustDesk version and environment**

build https://github.com/rustdesk/rustdesk/commit/52ce3dd2c299e262a54af0b5350fa60f66215e60

**Comment by rustdesk** [comment]
@Kingtous

**Comment by Kingtous** [comment]
did you install rustdesk nightly by the deb file or compile with this commit

**Comment by spamitinmy** [comment]
It's Windows 10, I used the rustdesk-1.2.0-x86_64-pc-windows-msvc.exe file.

**Comment by Kingtous** [comment]
I cannot reproduce this issue on the latest nightly build. Please make sure u are using the latest daily build.

![GIF 2022-11-9 0-32-44](https://user-images.githubusercontent.com/39793325/200622316-77319a4f-7733-45b8-8dd5-29f9e92c7787.gif)

after install, i cannot reproduce this either.
![after](https://user-images.githubusercontent.com/39793325/200622919-ae8b12cd-b257-4f5f-814d-72bc55e9d484.gif)

in addition, this is a test for the session window:
![2](https://user-images.githubusercontent.com/39793325/200624377-eac70e20-c60b-4227-800b-4e38d9623e8f.gif)

All of them behave normally.

btw, could you please describe your problem encountered with a gif? maybe i misunderstood your problem.

**Comment by spamitinmy** [comment]
Ok, I think I am able to figure out how to reproduce my situation. My situation is closely regarding your third gif.

To explain more how to reproduce my issue, it's when you resize the session window that causes the position to reset after reopening the main RustDesk window.
![RustDesk](https://user-images.githubusercontent.com/17346857/200633608-f3b94d64-4862-44cf-8300-da44283ff165.gif)

I resized my gif to fit under 10MB. I have 2 screens with 2560x1440, and the remote session is 1920x1080.

**Comment by Kingtous** [comment]
> Ok, I think I am able to figure out how to reproduce my situation. My situation is closely regarding your third gif.
> 
> To explain more how to reproduce my issue, it's when you resize the session window that causes the position to reset after reopening the main RustDesk window. ![RustDesk](https://user-images.githubusercontent.com/17346857/200633608-f3b94d64-4862-44cf-8300-da44283ff165.gif) [ ![RustDesk](https://user-images.githubusercontent.com/17346857/200633608-f3b94d64-4862-44cf-8300-da44283ff165.gif) ](https://user-images.githubusercontent.com/17346857/200633608-f3b94d64-4862-44cf-8300-da44283ff165.gif) [ ](https://user-images.githubusercontent.com/17346857/200633608-f3b94d64-4862-44cf-8300-da44283ff165.gif)
> 
> I resized my gif to fit under 10MB. I have 2 screens with 2560x1440, and the remote session is 1920x1080.

Great! We'll fix it soon.

**Comment by Kingtous** [comment]
Could u please try out our new nightly build including the bugfix?  U could head to https://github.com/Kingtous/rustdesk/releases/tag/nightly.

Please report whether the problem still exists :)

**Comment by spamitinmy** [comment]
This issue is fixed with the nightly build in your repo.
