### ISSUE TITLE
Wake on LAN on Rustdesk client

### ISSUE THREAD

**Issue by PabloGrok** [rustdesk/rustdesk#2015]
Anydesk has integrated WoL capabilities. I would like to ask for something similar for Rustdesk. It would be nice to have it implemented somewhat like this:

"This remote computer seems to be powered off. Would you like to try and turn it on via Wake on LAN?"

Then send the magic packets and hope for the best.

I administer some 50 systems in a studio and having this capability would be absolutely a lifesaver for us. Of course, I would take care of setting up Wake on LAN on each remote computer beforehand.

PS: I'm loving Rustdesk so far. I encourage you to offer some paid plans. It's hard to convince a CFO to donate, but easier to make them pay for something like Rustdesk.

**Comment by rustdesk** [comment]
dup

**Comment by PabloGrok** [comment]
What is the dup?

**Comment by abiroid** [comment]
> What is the dup?

I think they mean duplicate. As there is already a request like this.
Look through the issues and you'll find: "WOL" or wake on lan referenced at several places.
I think they merged some issues.

https://github.com/rustdesk/rustdesk/issues/129

**Comment by PabloGrok** [comment]
Wow, thank you. A bit rude by the developer not to link to the duplicate isssue(s).

**Comment by rustdesk** [comment]
Thanks, @abiroid
