### ISSUE TITLE
Remember Password doesn't save when connect via LAN Direct IP

### ISSUE THREAD

**Issue by xkvnn** [rustdesk/rustdesk#2024]
**Describe the bug you encountered:**
- Although I connect success with the correct password and **Remember Password** checked, subsequent connections still require typing the password.
-  Connect via Direct IP doesn't show in **Recent Sessions** tab and can't add to **Favorites**.

**What did you expect to happen instead?**
- **Remember Password** feature works correctly.
- Show Direct IP in Recent Sessions.
- Direct IP can add to **Favorites**

**How did you install `RustDesk`?**
- Download from Homepage https://rustdesk.com/

---

**RustDesk version and environment**
RustDesk 1.1.9 on Windows 11

**Comment by rustdesk** [comment]
try out nightly build

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/701
