### ISSUE TITLE
rustdesk and work through a repeater "not ready. please check the connection"

### ISSUE THREAD

**Issue by lichnost3d** [rustdesk/rustdesk#2030]
Rustdesk 1.1.9 doesn't work on "windows server 2019 standart" when using its own relay,
 rustdesk keeps saying "not ready. please check the connection".
 At the same time, there are no connection errors in the Rustdesk log.
 What could be the reason and how to enable extended logging of connection to the repeater?

**Comment by rustdesk** [comment]
#763

**Comment by lichnost3d** [comment]
The problem occurs only on one PC on Windows Server 2019, with Win10, Win8, Win7 strategies - everything works fine
