### ISSUE TITLE
ID Search Feature Not Useful

### ISSUE THREAD

**Issue by cormonster** [rustdesk/rustdesk#2032]
When searching for an ID in Recent Sessions/favorites, it only picks up the actual ID. Even if I rename the session to a memorable name, it still searches only by ID number. That requires me to actually remember the ID number to search for it again. 

...

It would be useful if it also searches by the renamed name as well as the computer name as displayed on the thumbnail, as those are usually more memorable.

...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

Windows ver 1.1.9

**Comment by rustdesk** [comment]
try nightly build

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/774#issuecomment-1227191142
