### ISSUE TITLE
Mouse keyboard input is interrupted when you press some windows in the Night version. (but work on 1.1.9)

### ISSUE THREAD

**Issue by YTOAA** [rustdesk/rustdesk#2033]
In Windows 10, the antivirus program "AVAST" in the nightly version was activated by double-clicking on the tray, but the mouse and keyboard input were interrupted. However, the screen output is normal. If you click the avast window while working in a different window, the re-entry is aborted. Is this bug currently known?
Another interesting thing is that if you press the "INPPUT CTRL+ALT+DEL" button, the mouse and keyboard input return Of course, if you press the "avast" program window again, the symptoms will be reproduced.
The nightly version is now using the version of the time this article was posted.

**Comment by rustdesk** [comment]
duplicate

**Comment by YTOAA** [comment]
> 

Could you tell me the link to the issue post?

**Comment by YTOAA** [comment]
> duplicate

The mouse keyboard works normally on 1.19 other than the nightly version. It's very strange

**Comment by rustdesk** [comment]
@asur4s

**Comment by rustdesk** [comment]
reopened because it is different from #266

**Comment by zhOrange** [comment]
I got the same problem.
the mouse and keyboard can work well when I open the common window or input sth. But the input and mouse is interrupted  when I open some system window like service manager. I tried v1.1.9 and nightly(without the config of key) and got the same problem.
After the config of key for the client, v1.1.9 works well but  problem still exists in nightly.

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
@zhOrange Hi, do you have RustDesk installed?

> After the config of key for the client, v1.1.9 works well but problem still exists in nightly.

What do you mean by configing the key?

**Comment by zhOrange** [comment]
Sorry about the problem. It's my fault. 
The "RustDesk service" was changed to demand when i build and install the exe. I got the problem when I stop the service and run it as normal user.
It works well without any problem, when I run it as administrator or start the rustdesk service.
