### ISSUE TITLE
Auto Start Service On Boot Android

### ISSUE THREAD

**Issue by rizqijune** [rustdesk/rustdesk#2034]
Hi, I love this program!
Can some free dev add an auto start service after boot, especially for android?
It will be help full for someone who have a lot of old devices, and doesn't want to bother activating it one by one.

I know this feature is will be a flaw for scammer to use. But, it can also be useful for someone like me who have a lot of old devices.

**Comment by rustdesk** [comment]
duplicate

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/1516

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3322

**Comment by rustdesk** [comment]
Please try out it tomorrow, just added.
