### ISSUE TITLE
Pin menu bar not saved

### ISSUE THREAD

**Issue by spamitinmy** [rustdesk/rustdesk#2036]
**Describe the bug you encountered:**

Pinning the menu bar does not save on the next session. After pinning the menu bar and closing the session, the menu bar goes back hidden.

**What did you expect to happen instead?**
If the menu bar is pinned, the setting should be saved. Currently this is not the case. It resets to being unpinned every time a new session starts.

**How did you install `RustDesk`?**

Github nightly build, Windows 10 installed with .exe file in nightly release.

---

**RustDesk version and environment**

Github nightly build Nov 8, 2022

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
https://github.com/rustdesk/rustdesk/pull/2043
I've saved pin option. But it may not work. I'll fix the config storage later.
