### ISSUE TITLE
Cursor icon does not change, always on default arrow

### ISSUE THREAD

**Issue by spamitinmy** [rustdesk/rustdesk#2038]
**Describe the bug you encountered:**

When mouse is on different areas of remote session, the cursor does not change to its associated icon. It is static on the default arrow cursor icon.

**What did you expect to happen instead?**

For example, if I hover around a link, cursor should change from arrow icon to the hand icon with index finger pointing. If I hover around text, cursor should change to the text selection symbol.

**How did you install `RustDesk`?**

Windows 10, installed with .exe file

---

**RustDesk version and environment**

Windows Nightly build nov 8, 2022, Windows 10 remote into another Windows 10 computer

**Comment by ForsakenRei** [comment]
I was about to report the same thing. And when you locate the cursor at the edge of windows it should show as resize cursor but there is no change, but you can still change the window size as long as your cursor is at the correct location.

**Comment by rustdesk** [comment]
@Kingtous

**Comment by Kingtous** [comment]
we need to use our custom flutter engine on windows in our nightly ci.

**Comment by rustdesk** [comment]
seems not easy to use our engine in nightly build

**Comment by Kingtous** [comment]
We have a solution for this issue and will fix it soon.

**Comment by ForsakenRei** [comment]
> We have a solution for this issue and will fix it soon.

Great! Will the fix solve the problem of host cursor disappear as well? Or I can wait for the fix and see if the works then open an issue if necessary.

**Comment by rustdesk** [comment]
> host cursor

upload a video please

**Comment by ForsakenRei** [comment]
> > host cursor
> 
> upload a video please

![rustdesk_t8o1WQnEpQ](https://user-images.githubusercontent.com/23041178/201002955-2fc387aa-de6d-4311-ae54-72885d7a1c21.gif)

What I did:
Uncheck show remote cursor first, and check show remote cursor(then host cursor disappeared)
Move host cursor position to the menu bar or the title bar then it will re-appear.

Nightly build on Windows machines. No input from remote at all.

**Comment by Kingtous** [comment]
please test if there any issues in the version including this bugfix.

I've manually triggered a nightly build for this bugfix:
https://github.com/Kingtous/rustdesk/releases/tag/nightly

**Comment by ForsakenRei** [comment]
> please test if there any issues in the version including this bugfix.
> 
> I've manually triggered a nightly build for this bugfix: https://github.com/Kingtous/rustdesk/releases/tag/nightly

I updated both host and remote. Cursor changes accordingly without issue.

While for the cursor disappear issue, once show remote cursor checked:
-if I don't move host cursor and wait for about 10sec then move, cursor won't disappear.
-if I move immediately host cursor will disappear but show up again after about 10sec, but there is no need to move cursor out of remote window area.

**Comment by rustdesk** [comment]
> While for the cursor disappear issue, once show remote cursor checked:
> -if I don't move host cursor and wait for about 10sec then move, cursor won't disappear.
> -if I move immediately host cursor will disappear but show up again after about 10sec, but there is no need to move cursor out of remote window area.

@fufesou

**Comment by ForsakenRei** [comment]
> @ForsakenRei can you also try out 1.1.9? does 1.1.9 work as expected?

Just tried 1.1.9, everything seems working in 1.1.9 for both cursor changing and cursor disappearing.

Another thing I just found is, in 1.1.9 installation you can click the whole row for check/uncheck create folder/icon option, in nightly 1.2.0 you have to click the checkbox itself. Not a big deal though.

**Comment by fufesou** [comment]
Thanks. I've reproduced this problem. I'll fix it tomorrow.

**Comment by fufesou** [comment]
@ForsakenRei Thanks for you test and reply. On my computer

**Comment by fufesou** [comment]
@ForsakenRei Thanks for your test and reply. 
Cursor disappear about 1~3 seconds on my computer. And peer mouse cannot be controlled.
But it may be the same problem.

https://github.com/rustdesk/rustdesk/pull/2064

Would you please try my nightly build here?  It will finish soon.
https://github.com/fufesou/rustdesk/releases/tag/nightly

**Comment by ForsakenRei** [comment]
> @ForsakenRei Thanks for your test and reply. Cursor disappear about 1~3 seconds on my computer. And peer mouse cannot be controlled. But it may be the same problem.
> 
> #2064
> 
> Would you please try my nightly build here? It will finish building and publishing soon. https://github.com/fufesou/rustdesk/releases/tag/nightly

NP. There are several different ones but I guess they should be same？
Installed this one [rustdesk-1.2.0-x86_64-pc-windows-msvc.exe](https://github.com/fufesou/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64-pc-windows-msvc.exe) on both side. And the cursor issue dissappeared. 

Not sure if it's my network but after show remote cursor checked, I felt a little lag some time, visible from the cursor changing. e.g. if I move to a hpyerlink the cursor will become a pointer hand, then I move away it should go back to normal cursor. Without show remote cursor on, everything seems fine. With show remote cursor on, not always but from time to time I felt a small lag when cursor need to change to pointer or vise versa. It will keep as pointer for a few seconds then change back.

**Comment by rustdesk** [comment]
> Not sure if it's my network but after show remote cursor checked, I felt a little lag some time, visible from the cursor changing. e.g. if I move to a hpyerlink the cursor will become a pointer hand, then I move away it should go back to normal cursor. Without show remote cursor on, everything seems fine. With show remote cursor on, not always but from time to time I felt a small lag when cursor need to change to pointer or vise versa. It will keep as pointer for a few seconds then change back.

it is not network issue if non remote cursor mode works.

**Comment by rustdesk** [comment]
> Not sure if it's my network but after show remote cursor checked, I felt a little lag some time, visible from the cursor changing. e.g. if I move to a hpyerlink the cursor will become a pointer hand, then I move away it should go back to normal cursor. Without show remote cursor on, everything seems fine. With show remote cursor on, not always but from time to time I felt a small lag when cursor need to change to pointer or vise versa. It will keep as pointer for a few seconds then change back.

Could you help test if 1.1.9 has such lag?

**Comment by ForsakenRei** [comment]
> > Not sure if it's my network but after show remote cursor checked, I felt a little lag some time, visible from the cursor changing. e.g. if I move to a hpyerlink the cursor will become a pointer hand, then I move away it should go back to normal cursor. Without show remote cursor on, everything seems fine. With show remote cursor on, not always but from time to time I felt a small lag when cursor need to change to pointer or vise versa. It will keep as pointer for a few seconds then change back.
> 
> Could you help test if 1.1.9 has such lag?

Just tried on Win host and remote, 1.1.9 seems fine to me.

**Comment by rustdesk** [comment]
> 1.1.9 seems fine to me.

Thanks, then it is our problem.

**Comment by rustdesk** [comment]
we do should find these user expierence issues before users.

**Comment by ForsakenRei** [comment]
> we do should find these user expierence issues before users.

Well I kinda think another way as end user can help dev to make it better. That's the good side of open sourced project right? And thank for all you guys' work.

**Comment by ForsakenRei** [comment]
> @ForsakenRei Can you try the latest nightly build tomorrow? The cursor icon problem should have been fixed.

I can confirm in the lastest nightly build this issue has been fixed.
