### ISSUE TITLE
Erro /lib/generated_bridge.dart

### ISSUE THREAD

**Issue by renyldo** [rustdesk/rustdesk#2039]
**Describe the bug you encountered:**
Erro ao compilar no flutter 
![D47F6A92-85E8-4594-9EB1-A391AC53BA5E](https://user-images.githubusercontent.com/117871914/200968366-45e48d1a-cde3-4d2c-a15c-7ca23bac65da.jpeg)

...

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

**Comment by rustdesk** [comment]
#763

**Comment by yunxingyu** [comment]
may you can  execute sh run.sh
