### ISSUE TITLE
open windows rustdesk have no message

### ISSUE THREAD

**Issue by QiJiajun-ahnu** [rustdesk/rustdesk#2040]
**Describe the bug you encountered:**
The open program is blank
<img width="514" alt="Snipaste_2022-11-10_08-34-55" src="https://user-images.githubusercontent.com/52004583/200971751-3fafa309-3ae1-4864-90ed-4e83ab0f34c6.png">

...

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

**Comment by rustdesk** [comment]
#80
