### ISSUE TITLE
Command line parameter --silent-install or --install not works as expected

### ISSUE THREAD

**Issue by ertankucukoglu** [rustdesk/rustdesk#2042]
Hello,

I am using nightly build rustdesk-1.2.0-x86_64-pc-windows-msvc.exe from yesterday on my Windows 11 insider built version. In an administrator command line below command does not install service as expected
`rustdesk-1.2.0-x86_64-pc-windows-msvc.exe --silent-install`
This opens up UI and red indication for installation suggestion is still there

https://user-images.githubusercontent.com/14805520/201008440-fdf58b8b-3275-4074-b75a-8ee16f54f98f.mp4

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
@ertankucukoglu test tomorrow please when the new build is ready.

**Comment by ertankucukoglu** [comment]
Hello,
Today's build behave same way. It does not install from command line parameters and displays UI to user.

https://user-images.githubusercontent.com/14805520/201267798-a0950f1c-2204-48a2-81f6-05a2ad5c9fbf.mp4

**Comment by 21pages** [comment]
Can you download the latest [nightly](https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64-pc-windows-msvc.exe) another time? File size is different between your exe and my download.  Your File size is 14503424, my is 14645760 
![1668144611995](https://user-images.githubusercontent.com/14891774/201270159-51966178-e088-419f-8e00-b215404ba26d.png)

**Comment by ertankucukoglu** [comment]
My bad, there are two files now (download tool renamed rather than overwrite) and I did run the one from yesterday. Sorry about that.
Will try this new one again.. after I sort out that annoying false positive virus warning of avira antivirus.

**Comment by ertankucukoglu** [comment]
Yes, works as expected now. Thank you.
