### ISSUE TITLE
New window crash with Flutter 3.3.6 on Win11

### ISSUE THREAD

**Issue by zkteco-home** [rustdesk/rustdesk#2047]
App crash when click Connect button,i also report it to https://github.com/Kingtous/rustdesk_desktop_multi_window/issues/2

...

**What did you expect to happen instead?**

...
i know you suggest to use Flutter 3.0.5 to compile,i still hope your team can solve this on New Flutter.

**How did you install `RustDesk`?**

download source code from github and build it

---

**RustDesk version and environment**

RustDesk:1.2.0
os:win11
Flutter:3.3.6 stable

**Comment by rustdesk** [comment]
https://github.com/flutter/engine/pull/36143

**Comment by rustdesk** [comment]
So please keep testing with every new Flutter.
