### ISSUE TITLE
How to generate a exe like the one available in the rustdesk site.

### ISSUE THREAD

**Issue by albertoVieiraNeto** [rustdesk/rustdesk#205]
Hi.

the title says most of my question, how can i generate a executable file like the one available on [rustdesk website](https://rustdesk.com/)?

i`m curently building using cargo build --release, this generates a file named rustdesk.exe, in this folder i still need to add the sciter.dll and the ui folder from the sources folder. 

but when the app is executed, instead of only showing the "window" with the UI it also opens a console, how can i avoid opening the console?

platform: windows.

**Comment by rustdesk** [comment]
money

**Comment by rustdesk** [comment]
https://github.com/sponsors/rustdesk/sponsorships?sponsor=rustdesk&tier_id=74919&preview=false

**Comment by albertoVieiraNeto** [comment]
hi, i already bought the server and i`m just trying to create a custom client logos/translation for my location.

Besides buying the sciter library, do i need to do anything else?

**Comment by muaaz0412** [comment]
@albertoVieiraNeto did you find any solution to build it with UI a single executable any how?

**Comment by rtest12** [comment]
@albertoVieiraNeto @muaaz0412
Did you succeed? any news?
