### ISSUE TITLE
Rocky Linux 8.6 can't launch from Icon

### ISSUE THREAD

**Issue by BrushXue** [rustdesk/rustdesk#2052]
First of all, thank you for creating this project. After being banned by teamviewer and anydesk I found this open-source alternative.

I can launch it from command and it's fully functional.
![2](https://user-images.githubusercontent.com/12702149/201166003-38c86ea4-4450-4297-b56e-cf4e298dad87.png)

But clicking the icon doesn't work at all
![1](https://user-images.githubusercontent.com/12702149/201166321-90662bb4-8678-4d19-8a90-69e8997f8b92.png)

And it doesn't start with system
...

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**
```
wget https://pkgs.dyn.su/el8/base/x86_64/cjkuni-uming-fonts-0.2.20080216.1-62.el8.noarch.rpm
sudo dnf install cjkuni-uming-fonts-0.2.20080216.1-62.el8.noarch.rpm
sudo dnf install rustdesk-1.1.9-fedora28-centos8.rpm 
 ```

---

**RustDesk version and environment**

RustDesk 1.1.9
Rocky Linux 8.6

**Comment by rustdesk** [comment]
@Xerxes-2 could you check out this when you have time?

**Comment by Xerxes-2** [comment]
what desktop are you using?

**Comment by BrushXue** [comment]
Hello. I'm using the default gnome3

**Comment by rustdesk** [comment]
close to favor #3565

**Comment by rustdesk** [comment]
1.2.2 works?
