### ISSUE TITLE
Show alias instead of ID in taskbar window title

### ISSUE THREAD

**Issue by G-Kevin** [rustdesk/rustdesk#2054]
When a connection is opened the windows ist titled with the ID of the remote computer.
It would be nice, if the number could be replaced with the alias, if the connection is set as a favorite. Maybe make it configurable?

![2022-11-10 21_10_23-](https://user-images.githubusercontent.com/16777924/201196403-6654bf78-3096-4df5-9ed6-dc060f0b97bf.jpg)

![2022-11-10 21_13_49-Window](https://user-images.githubusercontent.com/16777924/201196727-4f83a8fb-47cc-4116-82ca-f74a1b18683e.jpg)

I am using Windows 10 64Bit.
Thank you! :)

**Comment by rustdesk** [comment]
@fufesou we do ignore this

**Comment by G-Kevin** [comment]
Hello, thank you for your quick replay!

Tabs are shown in nightly, but still show the IDs, not the alias.

![2022-11-11 08_35_19-Window](https://user-images.githubusercontent.com/16777924/201289925-4d216978-2e7b-4ba2-8f7a-4bd3a79e9637.jpg)

Taskbar shows one window only:

![2022-11-11 08_35_34-](https://user-images.githubusercontent.com/16777924/201289964-a53d61da-2995-4865-acfc-e048f62ba8a5.jpg)

**Comment by rustdesk** [comment]
chrome show only one window also.

**Comment by rustdesk** [comment]
tab name will be fixed soon.

**Comment by G-Kevin** [comment]
Furthermore I noticed that links from filesystem do not open connections anymore. Is this feature removed?

**Comment by rustdesk** [comment]
@Kingtous finally some one report this though i guessed
