### ISSUE TITLE
remote desktop on ubuntu cloud image

### ISSUE THREAD

**Issue by initdc** [rustdesk/rustdesk#206]
**Describe the bug you encountered:**

`X11 error: connection refused`

**What did you expect to happen instead?**

rustdesk works well in`xrdp` or `anydesk` session, even run it from ssh `shell`, 

**How did you install `RustDesk`?**

1. [ubuntu 20 cloud image](https://cloud-images.ubuntu.com/focal/20210819/focal-server-cloudimg-amd64.ova)
2. install xrdp by run:
-  1. `sudo su`
    2.  `sh <(curl -L xrdp.ubtu.net)`
-  >solve ubuntu network unmanaged 
    1. `sudo nano /etc/NetworkManager/NetworkManager.conf`
    2. change to `managed=true`
-  1. connect it by useing RDP client
   2. use Firefox download rustdesk installer
   3. `dpkg -i rustdesk-1.16.deb`
- open rustdesk
  1. use ID and password, get `X11 error: connection refused`
  2. I successfully connected by click the `allow` button in RDP for just one time. In this session, rustdesk very smooth at the cost of quality, I close the RDP session to save bandwith, rustdesk still working, but maybe just for a while. Then screen forzed, I got no response from it.
  3. I reconnect to rustdesk, On the ubuntu (cloud image) , I get no alert from rustdesk, but anydesk works well, I can get alert from anydesk. On my VPS, I get alert from rustdesk, but even I click `allow` button, I get the same error. I get no alert from anydesk, so I can not connect my VPS with anydesk. 
 

**RustDesk version and environment**

- 1.16 
- windows 7

**Comment by rustdesk** [comment]
> 1. connection refused

Please show me your log file: /root/.local/share/logs/RustDesk/service/rustdesk_rCURRENT.log

**Comment by initdc** [comment]
check [this](https://nerd.arm.li/log.tgz)

**Comment by rustdesk** [comment]
What's you current $DISPLAY?

**Comment by rustdesk** [comment]
`systemctl --user show-environment | grep DISPLAY`

**Comment by initdc** [comment]
- on VPS
 ```
➜ ~ echo $DISPLAY                                                                                               0 <<18:33:37
:0
➜ ~ systemctl --user show-environment | grep DISPLAY                                                            0 <<18:33:45
Failed to connect to bus: No such file or directory
➜ ~ sudo su                                                                                                     1 <<18:37:18
racknerd-88be9a# echo $DISPLAY

racknerd-88be9a# systemctl --user show-environment | grep DISPLAY

racknerd-88be9a# 
```

- on local VMware
```
ubuntu@ubuntuguest:~$ echo $DISPLAY
:10.0
ubuntu@ubuntuguest:~$ sudo su
root@ubuntuguest:/home/ubuntu# echo $DISPLAY
:10.0
root@ubuntuguest:/home/ubuntu# systemctl --user show-environment | grep DISPLAY
Failed to connect to bus: No such file or directory
root@ubuntuguest:/home/ubuntu# 
```

**Comment by rustdesk** [comment]
> :10.0

Which one is the remote side when you see "X11 error: connection refused"?

**Comment by initdc** [comment]
> > :10.0
> 
> Which one is the remote side when you see "X11 error: connection refused"?

Using windows client, both of them get the same error. They are cloud image OS.

**Comment by rustdesk** [comment]
> cloud image OS

Where can I download "cloud image OS"?

**Comment by initdc** [comment]
https://cloud-images.ubuntu.com/focal/20210819/focal-server-cloudimg-amd64.ova

**Comment by rustdesk** [comment]
sorry, i tried, it has no x by default, seems i need spend time to get x up. sorry, i can not spend more time on this.
