### ISSUE TITLE
"Alt Gr" key not transmitted at all

### ISSUE THREAD

**Issue by Kukulkano** [rustdesk/rustdesk#2066]
**Describe the bug you encountered:**

I connect to a Windows 10 remote desktop from my local OpenSUSE 15.4 rustdesk 1.1.9.

I can not enter any key that uses the "Alt Gr" key on my keyboard.

For example, trying to type @ on my German keqboard results in a q letter in Windows (Alt Gr seems ignored).

**What did you expect to happen instead?**

I expect Alt Gr transmitted the same as other keystrokes.

**How did you install `RustDesk`?**

On my host I installed the RPM rustdesk-1.1.9-fedora28-centos8.rpm downloaded from https://github.com/rustdesk/rustdesk/releases I've had one warning regarding a missing font that I ignored.

On the remote Windows I downloaded rustdesk-1.1.9-windows_x64.zip from your website and ran the included executable.

**RustDesk version and environment**

My local OpenSUSE is with German keyboard and German language and RustDesk 1.1.9.
The remote Windows 10 (VirtualBox machine) is with German keyboard and German language and RustDesk 1.1.9.

**Comment by rustdesk** [comment]
Please expect 1.2.0

**Comment by Kukulkano** [comment]
When to expect 1.2.0? There is no such version yet on the releases page.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1547
