### ISSUE TITLE
can't find newdev.dll in win7。can‘t run on Win7

### ISSUE THREAD

**Issue by shuai8819** [rustdesk/rustdesk#2067]
**Describe the bug you encountered:**

你好，我在win10环境中下载的rustdesk开发版本成功的运行起来了，项目打包成 .exe文件后在win10可以正常运行。但是将安装文件拿到win7中运行 就会报 **无法定位程序输入点 DiUninstallDriverW 于动态链接库 newdev.dll** 在win7系统文件中也可以找到 newdev.dll系统文件。
请问如何才能在 win7中运行 打包后的安装文件。是只有在win7中打包才行么？

Hello, the rustdesk development version I downloaded in the win10 environment runs successfully. After the project is packaged into an. exe file, it can run normally in win10. However, if the installation file is taken to Win7 for running, it will report  **无法定位程序输入点 DiUninstallDriverW 于动态链接库 newdev.dll** You can find the newdev.dll system file in the win7 system file.
How can I run the packaged installation file in win7. Is it only possible to package in win7?

![微信图片_20221111162813](https://user-images.githubusercontent.com/68989281/201300015-3207bdad-2586-41b2-ab98-fc51755b2945.jpg)

---

**RustDesk version and environment**

**Comment by rustdesk** [comment]
English please

**Comment by rustdesk** [comment]
Flutter does not support win7.

**Comment by rustdesk** [comment]
https://docs.flutter.dev/development/tools/sdk/release-notes/supported-platforms#supported-platforms

https://stackoverflow.com/questions/73517044/flutter-build-stopped-working-for-windos-7-64-bits

@Kingtous 

No idea which plugin uses this dll.

**Comment by Kingtous** [comment]
Your system lacks `newdev.dll`, which is in system folder. Please check if your os is a complete one, or download this dll from internet.

**Comment by rustdesk** [comment]
<img width="337" alt="1668162985745" src="https://user-images.githubusercontent.com/71636191/201322798-e9be84b1-709e-492c-8c6c-6b3cd8a97c32.png">

**Comment by shuai8819** [comment]
你好，在我的win7系统查了是有这个系统文件的， 但是启动还是会报同样的错误。是不是因为打包的问题呢？是不是需要换一种打包的方式呢。

Hello, I found this system file in my Windows 7 system, but the same error will be reported after startup. Is it because of packaging? Is it necessary to change the packaging method.

@rustdesk 
![a2a30c27f346b1622d9e6322b7832a1](https://user-images.githubusercontent.com/68989281/203672845-1d32c941-00f2-47e6-9cb7-39073a4c4975.jpg)

**Comment by 82kg** [comment]
> 你好，在我的win7系统查了是有这个系统文件的， 但是启动还是会报同样的错误。是不是因为打包的问题呢？是不是需要换一种打包的方式呢。
> 
> Hello, I found this system file in my Windows 7 system, but the same error will be reported after startup. Is it because of packaging? Is it necessary to change the packaging method.
> 
> @rustdesk ![a2a30c27f346b1622d9e6322b7832a1](https://user-images.githubusercontent.com/68989281/203672845-1d32c941-00f2-47e6-9cb7-39073a4c4975.jpg)

你解决了吗。为什么官方的exe能在win7运行，自己打包的却不可以？
