### ISSUE TITLE
add win7/8/10  32bit  Support

### ISSUE THREAD

**Issue by tx991020** [rustdesk/rustdesk#207]
add win7/8/10 32bit  Support

**Comment by rustdesk** [comment]
Will be released together with 1.1.8 tomorrow.

**Comment by open-trade** [comment]
try out https://github.com/rustdesk/rustdesk/releases/download/1.1.8/rustdesk-1.1.8-windows_x32.zip

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/78
