### ISSUE TITLE
Proposal submission

### ISSUE THREAD

**Issue by zmdao** [rustdesk/rustdesk#208]
才发现有这么好的一个软件可以代替tv
不过有2个建议：（都是被人提出过的）
1，可以增加通讯录的功能 、保存远程电脑ID（当然是服务器存储了，注册账户，然后云端存储）
2，我一直用的ios手机，之前tv我都是外出用手机直接操控电脑，现在已经无法实现了，因为你的软件不支持ios，我也没安卓手机，所以建议增加ios系统。

**Comment by rustdesk** [comment]
Address book will be added, but it will be only for paid user.

iOS got online today morning. 

https://apps.apple.com/us/app/rustdesk-remote-desktop/id1581225015
