### ISSUE TITLE
Cannot configure the key for encryption in the linux client settings

### ISSUE THREAD

**Issue by ThiloBohr** [rustdesk/rustdesk#2085]
Dear maintainers - thanks for your attention and this great product ! :-)

**Describe the bug you encountered:**

I am not able to configure the public key for encryption - the config dialog misses the _key_ field.

![rustdesk-server-config](https://user-images.githubusercontent.com/54250043/201477751-6471dfe8-db15-447c-9641-5bbee595514e.png)

(_myserver.com obviously is not my server - just typed that in for security reasons_)

Also, the _Server_ property just has a label but no input field.

**What did you expect to happen instead?**

I want to configure the key in the dialog - or alternatively in a config file.
I tried to add a "key" entry in the ~/.config/rustdesk/Rustdesk.toml file but that did not work.

**How did you install `RustDesk`?**

As nixos package (see https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/networking/remote/rustdesk/default.nix)

**RustDesk version and environment**

1.1.9 Linux (NIXOS 22.05 unstable)

![rustdesk-about](https://user-images.githubusercontent.com/54250043/201477729-9aa08474-47d5-46d7-a4ea-9dc2463f5a47.png)

**Comment by ThiloBohr** [comment]
Just wanted to add that the issue does not seem to be language-related because when I start the rustdesk client with

```
export LANGUAGE=en_US.utf8
export LANG=en_US.utf8
export LC_ALL=en_US.utf8
rustdesk
```

the UI is in English but the key field is still missing.

**Comment by rustdesk** [comment]
#763
