### ISSUE TITLE
Disable Tray Icon

### ISSUE THREAD

**Issue by Timon0586** [rustdesk/rustdesk#2089]
Hey,

i've installed RustDesk and i can't deactivate or disable the Tray Icon. So i think the Tray Icon is maybe Okay, but if i close the Program (RustDesk), the Tray Icon is anyway shown. And if i make a rightclick on the Tray Icon i can't click on "Close" so there isn't a close Button. Please i don't want this Tray Icon or i will disable it Or when I close the program the tray icon should also disappear.

Greetings
Timon

**Comment by rustdesk** [comment]
duplicate issue

**Comment by rustdesk** [comment]
in todo
