### ISSUE TITLE
macos 10.13.6 vcpkg install libvpx error.

### ISSUE THREAD

**Issue by eagle518** [rustdesk/rustdesk#209]
eagle$ vcpkg install libvpx
Computing installation plan...
The following packages will be built and installed:
    libvpx[core]:x64-osx -> 1.9.0#9
Detecting compiler hash for triplet x64-osx...
Could not locate cached archive: /Users/eagle/.cache/vcpkg/archives/d4/d40625a300006481f655134a256f6ce92dc2e379.zip
Starting package 1/1: libvpx:x64-osx
Building package libvpx[core]:x64-osx...
-- Using cached /usr/local/Cellar/vcpkg/2021.05.12/libexec/downloads/webmproject-libvpx-v1.9.0.tar.gz
-- Cleaning sources at /usr/local/Cellar/vcpkg/2021.05.12/libexec/buildtrees/libvpx/src/v1.9.0-72894c6d82.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /usr/local/Cellar/vcpkg/2021.05.12/libexec/downloads/webmproject-libvpx-v1.9.0.tar.gz
-- Applying patch 0001-vcxproj-nasm.patch
-- Applying patch 0002-Fix-nasm-debug-format-flag.patch
-- Applying patch 0003-add-uwp-and-v142-support.patch
-- Applying patch 0004-remove-library-suffixes.patch
-- Using source at /usr/local/Cellar/vcpkg/2021.05.12/libexec/buildtrees/libvpx/src/v1.9.0-72894c6d82.clean
-- Build info. Target: x86_64-darwin17-gcc; Options: --disable-examples --disable-tools --disable-docs --disable-unit-tests --enable-static --disable-shared
-- Configuring libvpx for Release
-- Building libvpx for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: /bin/bash --noprofile --norc -c "make -j8"
    Working Directory: /usr/local/Cellar/vcpkg/2021.05.12/libexec/buildtrees/libvpx/x64-osx-rel
    Error code: 2
    See logs for more information:
      /usr/local/Cellar/vcpkg/2021.05.12/libexec/buildtrees/libvpx/build-x64-osx-rel-out.log
      /usr/local/Cellar/vcpkg/2021.05.12/libexec/buildtrees/libvpx/build-x64-osx-rel-err.log

Call Stack (most recent call first):
  ports/libvpx/portfile.cmake:190 (vcpkg_execute_required_process)
  scripts/ports.cmake:142 (include)

Error: Building package libvpx:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libvpx:x64-osx
  Vcpkg version: 2021-05-05-unknownhash

Additionally, attach any relevant sections from the log files above.
eagle$
eagle$ nasm -v
NASM version 2.15.05 compiled on Aug 29 2020
eagle$
eagle$ uname -a
Darwin eagle-mac.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
eagle$
eagle$ cat /usr/local/Cellar/vcpkg/2021.05.12/libexec/buildtrees/libvpx/build-x64-osx-rel-err.log
nasm: error: unable to find utility "nasm", not a developer tool or in PATH
nasm: error: unable to find utility "nasm", not a developer tool or in PATH
make[1]: *** [vpx_ports/emms_mmx.asm.o] Error 72
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [vpx_dsp/x86/intrapred_sse2.asm.o] Error 72
nasm: error: unable to find utility "nasm", not a developer tool or in PATH
nasm: error: unable to find utility "nasm", not a developer tool or in PATH
make[1]: *** [vpx_dsp/x86/intrapred_ssse3.asm.o] Error 72
make[1]: *** [vpx_dsp/x86/add_noise_sse2.asm.o] Error 72
nasm: error: unable to find utility "nasm", not a developer tool or in PATH
make[1]: *** [vpx_dsp/x86/deblock_sse2.asm.o] Error 72
nasm: error: unable to find utility "nasm", not a developer tool or in PATH
make[1]: *** [vpx_dsp/x86/vpx_subpixel_8t_sse2.asm.o] Error 72
nasm: error: unable to find utility "nasm", not a developer tool or in PATH
make[1]: *** [vpx_dsp/x86/vpx_subpixel_bilinear_sse2.asm.o] Error 72
make: *** [.DEFAULT] Error 2

**Comment by rustdesk** [comment]
Google please
