### ISSUE TITLE
Floating menu recommended for full screen

### ISSUE THREAD

**Issue by samliu319** [rustdesk/rustdesk#2092]
When in full screen, the mouse is moved to the title bar operation will be very confusing. 

For example, clicking to close the Explorer, but it always closes to the Rustdesk.
![image](https://user-images.githubusercontent.com/1710990/201506580-6d0497de-745a-4af6-9256-6992f3c8c194.png)

It is recommended to use the floating menu and keep the original window untouched so as not to cause any confusion in operation. Take anydesk as an example:
![image](https://user-images.githubusercontent.com/1710990/201506645-c1552ffa-077c-4daf-9bad-2eecd07b1e15.png)

Thanks.

**Comment by rustdesk** [comment]
try out nightly build please
