### ISSUE TITLE
Run in background in login

### ISSUE THREAD

**Issue by StrangerGithuber** [rustdesk/rustdesk#2096]
Hi
I am using Arch Linux and whenever I am on login then I can't connect with RustDesk. I must open RustDesk manually.
It would be nice to have option connect to the RustDesk while the operation system is at login page.

If I am connecting to the Windows operation system while the operation system at login page  then I can connect to the RustDesk because RustDesk service or something is going in the background.

However if I connect to the Linux operation systems then I must open the RustDesk manually first...
Anydesk has this option to linux too but it would nice to have on rustdesk too.

Thanks in advance.

**Comment by rustdesk** [comment]
Linux has also if you download from guthub, the aur is not maintained by us.
