### ISSUE TITLE
Transfer file no working? 

### ISSUE THREAD

**Issue by zkteco-home** [rustdesk/rustdesk#2099]
**Describe the bug you encountered:**

我困扰一个奇怪问题，传输文件显示都正常，但实际文件大小为0。复制粘贴文件是可以的，如下图：
![image](https://user-images.githubusercontent.com/66519168/201592321-d9b601de-5e7c-4fc2-8202-b213c2a7c7e2.png)

**What did you expect to happen instead?**

期望正常传输

下载的
**How did you install `RustDesk`?**

运行的rustdesk-1.2.0-x86_64-pc-windows-msvc.exe

**RustDesk version and environment**

os:windows 11
rustdesk:1.2.0

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by Kingtous** [comment]
I can reproduce this issue. It happens when we upload files to remote. The download operations do not have these issues.

**Comment by rustdesk** [comment]
wierd

**Comment by perarg** [comment]
I confirm the issue with version 1.2.0
I tried with 1.1.9 and transfer functionality seems to work without any issue.

**Comment by rustdesk** [comment]
No, it is a workaround only.

**Comment by djex** [comment]
Can confirm #2151 fixes the issue
