### ISSUE TITLE
Windows whitescreen

### ISSUE THREAD

**Issue by 1040395857** [rustdesk/rustdesk#210]
System version: [windows10 - 64bit - 20h2 ]

After installation, open the white screen, and nothing is displayed on the whole interface. What's the problem

**Comment by open-trade** [comment]
https://github.com/rustdesk/rustdesk/issues/132

**Comment by open-trade** [comment]
try out https://github.com/rustdesk/rustdesk/releases/download/1.1.8/rustdesk-1.1.8-windows_x64.zip

**Comment by w93163red** [comment]
still the same using the latest master code

**Comment by rustdesk** [comment]
> still the same using the latest master code

https://github.com/rustdesk/rustdesk/issues/132#issuecomment-886069737

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/blob/master/src/ui.rs#L43 not work?

**Comment by rustdesk** [comment]
or please try out https://github.com/c-smile/sciter-sdk/tree/master/bin.win/x64skia

**Comment by w93163red** [comment]
both did not work

**Comment by rustdesk** [comment]
> both did not work
Show me your screen?

**Comment by rustdesk** [comment]
> > both did not work

Show me your screen?

**Comment by rustdesk** [comment]
> both did not work

And you run by `cargo run`?

**Comment by w93163red** [comment]
cant' even open the window
![image](https://user-images.githubusercontent.com/7308728/130547093-068d3a0a-6421-4728-af91-b716511c95ff.png)
``` 
   Compiling rustdesk v1.1.6 (C:\Users\lingxiang.wang\code\rustdesk)
    Finished dev [unoptimized + debuginfo] target(s) in 12.05s
     Running `target\debug\rustdesk.exe`
[2021-08-24T02:34:00Z INFO  rustdesk::server] server not started (will try to start): The system cannot find the file specified. (os error 2)
[2021-08-24T02:34:00Z INFO  rustdesk::rendezvous_mediator] start rendezvous mediator of rs-cn.rustdesk.com
[2021-08-24T02:34:00Z INFO  rustdesk::rendezvous_mediator] start rendezvous mediator of rs-ny.rustdesk.com
[2021-08-24T02:34:00Z INFO  rustdesk::rendezvous_mediator] start rendezvous mediator of rs-sg.rustdesk.com
[2021-08-24T02:34:00Z INFO  rustdesk::ipc] Started ipc server at path: \\.\pipe\RustDesk\query
[2021-08-24T02:34:00Z INFO  rustdesk::common] Testing nat ...
INFO:TIS: current platform: Windows
[2021-08-24T02:34:00Z INFO  rustdesk::common] Tested nat type: ASYMMETRIC in 550.8712ms
```

**Comment by rustdesk** [comment]
Can you go to discord? I know the issue, but I can not reproduce on all my Windows machines. Can we debug this issue together? We can start from replacing index.tis with very simple content, one button or text etc.

**Comment by w93163red** [comment]
sure

**Comment by rustdesk** [comment]
Conclusion: looks like sciter resource file load path issue

**Comment by rustdesk** [comment]
@w93163red looking forward to your PR

**Comment by 1040395857** [comment]
![image](https://user-images.githubusercontent.com/54677924/130557732-7395292c-0546-4f65-92a3-81d7a4ceaa26.png)

**Comment by rustdesk** [comment]
@1040395857 can you run from source?

**Comment by rustdesk** [comment]
@1040395857 could you also try out this one https://github.com/rustdesk/rustdesk/releases/download/1.1.8/rustdesk-1.1.8-skia.zip

**Comment by 1040395857** [comment]
> @1040395857 can you build and run from source code? I can help you if you have any problem.
I think I should be able to, but now I am very busy

**Comment by 1040395857** [comment]
I think I should be able to build it, but now I am very busy

**Comment by rustdesk** [comment]
> I think I should be able to build it, but now I am very busy

No problem, let me know when you have time, you can ping me at discord at any time. Also please try out  https://github.com/rustdesk/rustdesk/releases/download/1.1.8/rustdesk-1.1.8-skia.zip

**Comment by w93163red** [comment]
Hmm.. It is interesting @rustdesk .  After I restarted the computer, I can see the content now.

**Comment by rustdesk** [comment]
Congratulations

**Comment by GGGGGHT** [comment]
I also had the same problem. OS version: Windows 10

**Comment by rustdesk** [comment]
> I also had the same problem. OS version: Windows 10

Do you have split-screen turned on?

**Comment by GGGGGHT** [comment]
> > I also had the same problem. OS version: Windows 10
> 
> Do you have split-screen turned on?

Don't worry about this problem, I have solved it.

**Comment by rustdesk** [comment]
> > > I also had the same problem. OS version: Windows 10
> > 
> > 
> > Do you have split-screen turned on?
> 
> Don't worry about this problem, I have solved it.

How do you solve it?

**Comment by irecsys** [comment]
I have this problem again on Win10. It works well before. But recently, it just starts with a blank/white window. Re-installation does not work

**Comment by fufesou** [comment]
> I have this problem again on Win10. It works well before. But recently, it just starts with a blank/white window. Re-installation does not work

Hi, try this version
https://github.com/rustdesk/rustdesk/releases/download/1.1.8/rustdesk-1.1.8-skia.zip

**Comment by fufesou** [comment]
@1040395857 @w93163red 

Hi, I'm trying to solve this problem.
But I need a environment to reproduce this problem. Can I send the prebuild file to you on email?

**Comment by irecsys** [comment]
> > I have this problem again on Win10. It works well before. But recently, it just starts with a blank/white window. Re-installation does not work
> 
> Hi, try this version https://github.com/rustdesk/rustdesk/releases/download/1.1.8/rustdesk-1.1.8-skia.zip
> 
> I'm trying to solve this problem. But I need a environment to reproduce this problem. Can I send the prebuild file to you?

yes, send it to me. I installed rustdesk-1.1.8-skia. It is not working

**Comment by fufesou** [comment]
> 

Hi, I've sent you an email with a debug version. Please try agian, the error messages may show on the command window.

Please attach the messages here. Thanks!

**Comment by fufesou** [comment]
> > > I have this problem again on Win10. It works well before. But recently, it just starts with a blank/white window. Re-installation does not work
> > 
> > 
> > Hi, try this version https://github.com/rustdesk/rustdesk/releases/download/1.1.8/rustdesk-1.1.8-skia.zip
> > I'm trying to solve this problem. But I need a environment to reproduce this problem. Can I send the prebuild file to you?
> 
> yes, send it to me. I installed rustdesk-1.1.8-skia. It is not working. My email is my ID + gmail


Hi, I've sent you an email with a debug version. Please try agian, the error messages may show on the command window.

Please attach the messages here. Thanks!

**Comment by irecsys** [comment]
[2021-12-15T02:30:56Z INFO  rustdesk::server] server not started (will try to start): The system cannot find the file specified. (os error 2)
[2021-12-15T02:30:56Z INFO  rustdesk::ipc] Started ipc server at path: \\.\pipe\RustDesk\query
[2021-12-15T02:30:56Z DEBUG hbb_common::config] Configuration path: C:\Users\xxxx\AppData\Roaming\RustDesk\config\RustDesk2.toml
[2021-12-15T02:30:56Z DEBUG hbb_common::config] Configuration path: C:\Users\xxxx\AppData\Roaming\RustDesk\config\RustDesk.toml
[2021-12-15T02:30:56Z DEBUG hbb_common::config] Config { id: "2459xxxx", password: "xxxxxxxx", salt: "h7u3wv", key_pair: ([38, 103, 127, 83, 173, 237, 36, 224, 123, 129, 106, 117, 23, 127, 118, 132, 112, 27, 92, 24, 179, 64, 55, 38, 90, 81, 110, 236, 136, 217, 3, 217, 119, 39, 124, 164, 186, 216, 245, 227, 254, 193, 89, 203, 107, 230, 16, 249, 144, 233, 137, 213, 191, 57, 198, 166, 28, 247, 142, 66, 126, 241, 71, 48], [119, 39, 124, 164, 186, 216, 245, 227, 254, 193, 89, 203, 107, 230, 16, 249, 144, 233, 137, 213, 191, 57, 198, 166, 28, 247, 142, 66, 126, 241, 71, 48]), key_confirmed: true, keys_confirmed: {} }
INFO:TIS: current platform: Windows

**Comment by irecsys** [comment]
It seems that the RustDesk service was not started. I manually started it on windows, but still got a white screen. See the debug info below

[2021-12-15T02:33:25Z INFO  rustdesk::server] server info: SystemInfo(Some("log_path: C:\\WINDOWS\\ServiceProfiles\\LocalService\\AppData\\Roaming\\RustDesk\\log, config: C:\\WINDOWS\\ServiceProfiles\\LocalService\\AppData\\Roaming\\RustDesk\\config\\RustDesk.toml, username: SYSTEM"))
[2021-12-15T02:33:25Z DEBUG hbb_common::config] Configuration path: C:\Users\xxxx\AppData\Roaming\RustDesk\config\RustDesk.toml
[2021-12-15T02:33:25Z DEBUG hbb_common::config] Config { id: "2459xxxx", password: "xxxx", salt: "h7u3wv", key_pair: ([38, 103, 127, 83, 173, 237, 36, 224, 123, 129, 106, 117, 23, 127, 118, 132, 112, 27, 92, 24, 179, 64, 55, 38, 90, 81, 110, 236, 136, 217, 3, 217, 119, 39, 124, 164, 186, 216, 245, 227, 254, 193, 89, 203, 107, 230, 16, 249, 144, 233, 137, 213, 191, 57, 198, 166, 28, 247, 142, 66, 126, 241, 71, 48], [119, 39, 124, 164, 186, 216, 245, 227, 254, 193, 89, 203, 107, 230, 16, 249, 144, 233, 137, 213, 191, 57, 198, 166, 28, 247, 142, 66, 126, 241, 71, 48]), key_confirmed: true, keys_confirmed: {} }
INFO:TIS: current platform: Windows
[2021-12-15T02:33:25Z DEBUG hbb_common::config] Configuration path: C:\Users\xxxx\AppData\Roaming\RustDesk\config\RustDesk2.toml

**Comment by fufesou** [comment]
> 

I've sent you an email yesterday, but got no reply.

My logs are more than yours. Are those all logs you attached above?
The logs on my computer include some messages from "rendezvous_mediator" module.
It seems rendezvous_mediator does not work as expected. 

....
[2021-12-15T03:40:14Z INFO  rustdesk::rendezvous_mediator] start rendezvous mediator of rs-ny.rustdesk.com
[2021-12-15T03:40:14Z INFO  rustdesk::rendezvous_mediator] start rendezvous mediator of rs-sg.rustdesk.com
[2021-12-15T03:40:14Z INFO  rustdesk::rendezvous_mediator] start rendezvous mediator of rs-cn.rustdesk.com
...
[2021-12-15T03:40:14Z DEBUG rustdesk::rendezvous_mediator] Latency of rs-cn.rustdesk.com: 38.727ms
[2021-12-15T03:40:14Z INFO  rustdesk::common] Tested nat type: ASYMMETRIC in 153.4044ms
[2021-12-15T03:40:14Z DEBUG rustdesk::rendezvous_mediator] Latency of rs-ny.rustdesk.com: 253.337ms
[2021-12-15T03:40:14Z DEBUG rustdesk::rendezvous_mediator] Latency of rs-sg.rustdesk.com: 259.136ms
...

**Comment by fufesou** [comment]
> It seems that the RustDesk service was not started. I manually started it on windows, but still got a white screen. See the debug info below
> 
> [2021-12-15T02:33:25Z INFO rustdesk::server] server info: SystemInfo(Some("log_path: C:\WINDOWS\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log, config: C:\WINDOWS\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml, username: SYSTEM")) [2021-12-15T02:33:25Z DEBUG hbb_common::config] Configuration path: C:\Users\xxxx\AppData\Roaming\RustDesk\config\RustDesk.toml [2021-12-15T02:33:25Z DEBUG hbb_common::config] Config { id: "2459xxxx", password: "xxxx", salt: "h7u3wv", key_pair: ([38, 103, 127, 83, 173, 237, 36, 224, 123, 129, 106, 117, 23, 127, 118, 132, 112, 27, 92, 24, 179, 64, 55, 38, 90, 81, 110, 236, 136, 217, 3, 217, 119, 39, 124, 164, 186, 216, 245, 227, 254, 193, 89, 203, 107, 230, 16, 249, 144, 233, 137, 213, 191, 57, 198, 166, 28, 247, 142, 66, 126, 241, 71, 48], [119, 39, 124, 164, 186, 216, 245, 227, 254, 193, 89, 203, 107, 230, 16, 249, 144, 233, 137, 213, 191, 57, 198, 166, 28, 247, 142, 66, 126, 241, 71, 48]), key_confirmed: true, keys_confirmed: {} } INFO:TIS: current platform: Windows [2021-12-15T02:33:25Z DEBUG hbb_common::config] Configuration path: C:\Users\xxxx\AppData\Roaming\RustDesk\config\RustDesk2.toml

I've sent you an email yesterday, but got no reply.

My logs are more than yours. Are those all logs you attached above?
The logs on my computer include some messages from "rendezvous_mediator" module.
It seems rendezvous_mediator does not work as expected. 

....
[2021-12-15T03:40:14Z INFO  rustdesk::rendezvous_mediator] start rendezvous mediator of rs-ny.rustdesk.com
[2021-12-15T03:40:14Z INFO  rustdesk::rendezvous_mediator] start rendezvous mediator of rs-sg.rustdesk.com
[2021-12-15T03:40:14Z INFO  rustdesk::rendezvous_mediator] start rendezvous mediator of rs-cn.rustdesk.com
...
[2021-12-15T03:40:14Z DEBUG rustdesk::rendezvous_mediator] Latency of rs-cn.rustdesk.com: 38.727ms
[2021-12-15T03:40:14Z INFO  rustdesk::common] Tested nat type: ASYMMETRIC in 153.4044ms
[2021-12-15T03:40:14Z DEBUG rustdesk::rendezvous_mediator] Latency of rs-ny.rustdesk.com: 253.337ms
[2021-12-15T03:40:14Z DEBUG rustdesk::rendezvous_mediator] Latency of rs-sg.rustdesk.com: 259.136ms
...

**Comment by irecsys** [comment]
> > It seems that the RustDesk service was not started. I manually started it on windows, but still got a white screen. See the debug info below
> > [2021-12-15T02:33:25Z INFO rustdesk::server] server info: SystemInfo(Some("log_path: C:\WINDOWS\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log, config: C:\WINDOWS\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml, username: SYSTEM")) [2021-12-15T02:33:25Z DEBUG hbb_common::config] Configuration path: C:\Users\xxxx\AppData\Roaming\RustDesk\config\RustDesk.toml [2021-12-15T02:33:25Z DEBUG hbb_common::config] Config { id: "2459xxxx", password: "xxxx", salt: "h7u3wv", key_pair: ([38, 103, 127, 83, 173, 237, 36, 224, 123, 129, 106, 117, 23, 127, 118, 132, 112, 27, 92, 24, 179, 64, 55, 38, 90, 81, 110, 236, 136, 217, 3, 217, 119, 39, 124, 164, 186, 216, 245, 227, 254, 193, 89, 203, 107, 230, 16, 249, 144, 233, 137, 213, 191, 57, 198, 166, 28, 247, 142, 66, 126, 241, 71, 48], [119, 39, 124, 164, 186, 216, 245, 227, 254, 193, 89, 203, 107, 230, 16, 249, 144, 233, 137, 213, 191, 57, 198, 166, 28, 247, 142, 66, 126, 241, 71, 48]), key_confirmed: true, keys_confirmed: {} } INFO:TIS: current platform: Windows [2021-12-15T02:33:25Z DEBUG hbb_common::config] Configuration path: C:\Users\xxxx\AppData\Roaming\RustDesk\config\RustDesk2.toml
> 
> I've sent you an email yesterday, but got no reply.
> 
> My logs are more than yours. Are those all logs you attached above? The logs on my computer include some messages from "rendezvous_mediator" module. It seems rendezvous_mediator does not work as expected.
> 
> .... [2021-12-15T03:40:14Z INFO rustdesk::rendezvous_mediator] start rendezvous mediator of rs-ny.rustdesk.com [2021-12-15T03:40:14Z INFO rustdesk::rendezvous_mediator] start rendezvous mediator of rs-sg.rustdesk.com [2021-12-15T03:40:14Z INFO rustdesk::rendezvous_mediator] start rendezvous mediator of rs-cn.rustdesk.com ... [2021-12-15T03:40:14Z DEBUG rustdesk::rendezvous_mediator] Latency of rs-cn.rustdesk.com: 38.727ms [2021-12-15T03:40:14Z INFO rustdesk::common] Tested nat type: ASYMMETRIC in 153.4044ms [2021-12-15T03:40:14Z DEBUG rustdesk::rendezvous_mediator] Latency of rs-ny.rustdesk.com: 253.337ms [2021-12-15T03:40:14Z DEBUG rustdesk::rendezvous_mediator] Latency of rs-sg.rustdesk.com: 259.136ms ...

Yes. I run the run_debug.bat file. And these are all the outputs on the Windoes cmd window

**Comment by fufesou** [comment]
> It seems that the RustDesk service was not started. I manually started it on windows, but still got a white screen. See the debug info below
> 
> [2021-12-15T02:33:25Z INFO rustdesk::server] server info: SystemInfo(Some("log_path: C:\WINDOWS\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log, config: C:\WINDOWS\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml, username: SYSTEM")) [2021-12-15T02:33:25Z DEBUG hbb_common::config] Configuration path: C:\Users\xxxx\AppData\Roaming\RustDesk\config\RustDesk.toml [2021-12-15T02:33:25Z DEBUG hbb_common::config] Config { id: "2459xxxx", password: "xxxx", salt: "h7u3wv", key_pair: ([38, 103, 127, 83, 173, 237, 36, 224, 123, 129, 106, 117, 23, 127, 118, 132, 112, 27, 92, 24, 179, 64, 55, 38, 90, 81, 110, 236, 136, 217, 3, 217, 119, 39, 124, 164, 186, 216, 245, 227, 254, 193, 89, 203, 107, 230, 16, 249, 144, 233, 137, 213, 191, 57, 198, 166, 28, 247, 142, 66, 126, 241, 71, 48], [119, 39, 124, 164, 186, 216, 245, 227, 254, 193, 89, 203, 107, 230, 16, 249, 144, 233, 137, 213, 191, 57, 198, 166, 28, 247, 142, 66, 126, 241, 71, 48]), key_confirmed: true, keys_confirmed: {} } INFO:TIS: current platform: Windows [2021-12-15T02:33:25Z DEBUG hbb_common::config] Configuration path: C:\Users\xxxx\AppData\Roaming\RustDesk\config\RustDesk2.toml

Thank you for your support!

I've check the code, but cannot find any logic error.
I have updated the debug package, please download and try again.
Nothing changed but more logs.
Then send logs to my email address shuanglongchen@yeah.net.

https://github.com/fufesou/rustdesk/releases/download/tmp/rust-debug-target.zip

![20211216122646](https://user-images.githubusercontent.com/13586388/146308173-11004600-c35f-4662-a667-6ed003c965b3.png)

**Comment by irecsys** [comment]
I saved a remote machine in RustDesk. The machine is offline now.

I go to the configuration folder, and delete the file which saved the information of the remote machine.

Now, it works perfectly without white window

**Comment by fufesou** [comment]
> I saved a remote machine in RustDesk. The machine is offline now.
> 
> I go to the configuration folder, and delete the file which saved the information of the remote machine.
> 
> Now, it works perfectly without white window

_RustDesk2.toml_ is a self config file.
Files in directory _peers_ are those that save the remote infos.

By the way, did you use multi-display before? 
The author said the negative numbers may appear on that situation. But the number are still too big. Strange position numbers.

**Comment by irecsys** [comment]
> > I saved a remote machine in RustDesk. The machine is offline now.
> > I go to the configuration folder, and delete the file which saved the information of the remote machine.
> > Now, it works perfectly without white window
> 
> _RustDesk2.toml_ is a self config file. Files in directory _peers_ are those that save the remote infos.
> 
> By the way, did you use multi-display before? The author said the negative numbers may appear on that situation. But the number are still too big. Strange position numbers.

Yes, two 27'' monitors

**Comment by grummbeer** [comment]
related to #80
