### ISSUE TITLE
Two keys are pressed

### ISSUE THREAD

**Issue by SmartManoj** [rustdesk/rustdesk#2104]
**Describe the bug you encountered:**
When pressing Home key, Numpad 7 also is pressed.
...

**What did you expect to happen instead?**
only Home should be pressed.
...

**How did you install `RustDesk`?**

Host: AUR 
Remote: portable

---

**RustDesk version and environment**
Host: Manjaro  XFCE  v1.1.9
Remote: Windows 10 lite (from oprekin)  (version : downloaded today - version dialog is protected)

**Comment by rustdesk** [comment]
try out nightly build please

**Comment by grummbeer** [comment]
#1547

**Comment by rustdesk** [comment]
@grummbeer Thanks
