### ISSUE TITLE
Specify id/relay server as part of target id when connecting to another device (id@server)

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#2118]
### Discussed in https://github.com/rustdesk/rustdesk/discussions/2072

<div type='discussions-op-text'>

<sup>Originally posted by **vladimir-angelov-1337** November 11, 2022</sup>
It would be cool if instead of "123 456 789" I could write "123 456 789@domain.com" when connecting to another device and that would use domain.com as the id/relay server for this specific connection. That way even with self-hosted setups we could connect cross-organization.</div>

**Comment by pedjas** [comment]
That way keys could be specified in domain DNS so clients would not have to bother with that too.

**Comment by vladimir-angelov-1337** [comment]
@rustdesk 
Thank you!

@pedjas 
Yes, exactly!

**Comment by ertankucukoglu** [comment]
I hope it will not be limited with domain and something like `123 456 789@1.1.1.1` would be possible. Not everybody uses a domain anyway.

I know there is IPv6 side of the things, though it would be considerable to start with IPv4

**Comment by vladimir-angelov-1337** [comment]
Can I put up a bounty for this?

**Comment by rustdesk** [comment]
> Can I put up a bounty for this?

Off course

**Comment by vladimir-angelov-1337** [comment]
Does US$100 seem reasonable?

**Comment by rustdesk** [comment]
@Xerxes-2 this can be done together with https://github.com/rustdesk/rustdesk/pull/2058

**Comment by rustdesk** [comment]
The problem is how to pass the key in?

**Comment by vladimir-angelov-1337** [comment]
Key can be fetched automatically from domain, there is no reason to pass a key manually just like there is no reason to pass the key when you open a website in your browser.

**Comment by rustdesk** [comment]
It is not website.

**Comment by rustdesk** [comment]
Combine this with https://github.com/rustdesk/rustdesk/discussions/1873, no plan to implement solely.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/6198
