### ISSUE TITLE
Windows installer silent install

### ISSUE THREAD

**Issue by itsmeboy0** [rustdesk/rustdesk#212]
Hi, I noticed the new installer on the latest version. What are the command line arguments needed to do a silent install of this one?

**Comment by rustdesk** [comment]
no

**Comment by rustdesk** [comment]
I never know such requirement

**Comment by rustdesk** [comment]
why?

**Comment by itsmeboy0** [comment]
> I never know such requirement

> why

My reasons are the same as #100. I would like to automate the deployment of this over multiple computers. Also, I see that an NSIS setup is merged which is **exactly** what I needed but is unused in the latest release. Why is that?

**Comment by itsmeboy0** [comment]
The new "setup" is not really a setup. It's just basically the portable RustDesk version but with the installation page and the main page swapped with the installation page put on the front. This is not a good change as it puts the installation page in an intrusive spot as people who only want to use the portable version would be nagged every time on the installation screen. The previous UI was already perfect, why did you have to change that?

**Comment by rustdesk** [comment]
because too many users ask about UAC. you only need to modify the file name, remove "putes".

**Comment by rustdesk** [comment]
also i do not want maintain two setup

**Comment by sitiom** [comment]
> also i do not want maintain two setup

That puts my NSIS setup in #100 to waste. If you are not gonna use the NSIS setup, put a silent installation switch to yours at least.

**Comment by sitiom** [comment]
> because too many users ask about UAC. you only need to modify the file name, remove "putes".

Also, why would UI be dependent on the file name of the running executable? That's not good practice for the least part.

**Comment by rustdesk** [comment]
it is not waste, it can be used by the guys who wanna build from source code.

**Comment by geshii** [comment]
> @rustdesk My reasons are the same as #100. I would like to automate the deployment of RustDesk over multiple computers. Also, I see that an NSIS setup is merged which is **exactly** what I needed but is unused in the latest release. Why is that?

Why don't you build rustdesk from the source then install it using a script?

**Comment by itsmeboy0** [comment]
> > @rustdesk My reasons are the same as #100. I would like to automate the deployment of RustDesk over multiple computers. Also, I see that an NSIS setup is merged which is **exactly** what I needed but is unused in the latest release. Why is that?
> 
> Why don't you build rustdesk from the source then install it using a script?

That cannot be put into package managers like Nuget, Chocolatey, Winget, Scoop, etc. They would need to have a prebuilt binary and end-users would expect one otherwise.

**Comment by rustdesk** [comment]
@itsmeboy0 I will give you --install-silent today

**Comment by rustdesk** [comment]
@itsmeboy0 Actually there is already silent install, please run with --reinstall

**Comment by itsmeboy0** [comment]
> @itsmeboy0 Actually there is already silent install, please run with --reinstall

Great, that works. Although two problems:

- It asks for UAC two times, it should only ask for UAC at the start.
- Switch should be renamed to `--silent-install` or `--install`

**Comment by rustdesk** [comment]
because it is reinstall

**Comment by itsmeboy0** [comment]
> because it is reinstall

It works as an install option so it should be renamed to `--install`.

**Comment by itsmeboy0** [comment]
Although I see the `--reinstall` does an uninstall operation as well. So maybe you should do a separate `--install` flag.

**Comment by rustdesk** [comment]
--install already used, it has gui. yes, i can add --silent-install in next release.

**Comment by Vogelbusch** [comment]
After using parameter --silent-install the Rundesk application starts. Is ist possible to block starting rundesk.exe after installation?
Because we are install over 260 windows clients.

**Comment by rustdesk** [comment]
>  --silent-install 

No problem, for your 100/month donation. haha

**Comment by rustdesk** [comment]
> starting rundesk.exe after installation

x64 for Windows updated https://github.com/rustdesk/rustdesk/releases/tag/1.1.9

**Comment by tutsde** [comment]
Is it possible to add self-hostet server as parameter when using a silent-install ?

**Comment by troubleshootme** [comment]
I am curious about this as well. Install seems to disregard the id and key in the exe file name. Can we specify with params?

**Comment by dudefoxlive** [comment]
Download the installer and add the host=<HOST>,key=<KEY> to the end of the file like in the docs [here](https://rustdesk.com/docs/en/self-host/install/#step-3--set-hbbshbbr-address-on-client-side). Then just run the silent install commands like normal. I think this gets reverted after an update though.

**Comment by troubleshootme** [comment]
Yeah, you're right, I wasn't very bright that day. It was actually adding those parameters but they were not showing up in the input fields. Sorry about that.

**Comment by dudefoxlive** [comment]
In my opinion I would like the option to copy a config file to the programdata directory or somewhere and have that set the server info and key. Would be useful if deploying via something like MECM, Group Policy, or MDT.

**Comment by marwinxtra** [comment]
Can someone help me with this issue, I tried to install Rust Desk on our server windows 2012 r2. O
![RustDesk](https://user-images.githubusercontent.com/73467387/201628057-c45730f5-8b5b-44b4-bdb3-41d3bd696fcf.png)
ne was successful but the other one says "Due to UAC, RustDesk can not work properly as the remote side in some cases."

Thank you in advance.

**Comment by naklow88** [comment]
Hello, what do I need to do to send to Windows 10 clients over server 2008 r2? Can someone write the full path? Do I need to msi the exe first?

**Comment by tobiasplagge** [comment]
Moin,
I'm testing the client installer by selfe hosting server.
The --silent-install partially successful. The client install, start not automatical in the background.
By the default client with the normal admin right install, the client can find in the taskbar.
When I start the deinstallation with --silent-reinstall the client starts itself.
When I type --reinstall, nothing happens.

The Client is running on the Windows 10 22H2 Notebook.

**Comment by duczz** [comment]
@rustdesk a allusers Installation parameter would be create

**Comment by fliespl** [comment]
Does silent-install also install service? How to do it?

**Comment by dinger1986** [comment]
> Does silent-install also install service? How to do it?
on windows?

Check install scripts here https://rustdesk.com/docs/en/self-host/client-deployment/
