### ISSUE TITLE
Copyright symbol

### ISSUE THREAD

**Issue by giuliovale** [rustdesk/rustdesk#2124]
Instead of the copyright symbol, the words &copy; are shown; 

https://github.com/rustdesk/rustdesk/blob/03e7b48d6f2570082ee3022b5c1c04851d5d3e88/flutter/lib/desktop/pages/desktop_setting_page.dart#L1078

**Comment by rustdesk** [comment]
Can you submit a PR?

**Comment by KoalaBear84** [comment]
Added a PR to fix it
