### ISSUE TITLE
rpm install fails : 'nothing provides cjkuni-uming-fonts needed by rustdesk-1.1.9-0.x86_64'

### ISSUE THREAD

**Issue by mytestsamsung** [rustdesk/rustdesk#2125]
Description:
-----------------
Trying install rustdesk-1.1.9-fedora28-centos8.rpm on AlmaLinux 8.5 fails due to cjkuni-uming-fonts missing 

Target O.S. (uname -a)
-----------------
Linux alma8-localdomain 4.18.0-348.12.2.el8_5.x86_64 #1 SMP Wed Jan 19 14:35:04 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

Rustdesk Version
-----------------
rustdesk-1.1.9-0.x86_64

Command Log:
-----------------
$ sudo yum install rustdesk-1.1.9-fedora28-centos8.rpm
Last metadata expiration check: 0:18:07 ago on Tue 15 Nov 2022 10:20:01 AM CET.
Error: 
 Problem: conflicting requests
  - nothing provides cjkuni-uming-fonts needed by rustdesk-1.1.9-0.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

**Comment by rustdesk** [comment]
removed in nightly build.
