### ISSUE TITLE
Cursor isn't clearly visible (when not default)

### ISSUE THREAD

**Issue by KoalaBear84** [rustdesk/rustdesk#2126]
I'm not sure if #2100 is the fix for this.

**Describe the bug you encountered:**

It looks like the cursor is light, and with white outline in text areas. So most of the time I've lost my cursor completely. I'm almost certain this wasn't the case before the nightly as I would've notived it right away. I've moved to the nightly because of #1166

The cursor:
![image](https://user-images.githubusercontent.com/5886900/201889196-84c396f4-958e-458a-909d-314d15201616.png)

**What did you expect to happen instead?**

Same cursor as Windows would show normally (only black) so it will be clear again.

![image](https://user-images.githubusercontent.com/5886900/201889702-9563ed82-e4a1-403e-b02e-94019a01be8a.png)

**How did you install `RustDesk`?**

GitHub nigthly build 52ce3dd, installed, Windows.

**RustDesk version and environment**

**Host**
Windows 10 Pro 21H2 (OS Build 19044.2251)
Rustdesk nightly build 52ce3dd, installed

**Client**
Windows 10 Enterprise 21H2 (OS Build 19044.2251)
Rustdesk nightly build 52ce3dd, installed

It also looks like the cursor is offset a little to the left, so sometimes it clicks the wrong point.

And I see in this nightly that the whole screen is outlined with I think a gray line, which isn't that nice.

**Comment by rustdesk** [comment]
@Kingtous check out the gray outline issue please.
@fufesou check out the others please.

**Comment by rustdesk** [comment]
Could you please test latest build?

**Comment by Kingtous** [comment]
i ve updated custom engine today. could you please wait for some minutes and i am preparing a new build in https://github.com/Kingtous/rustdesk/actions/runs/3469562600

**Comment by rustdesk** [comment]
> And I see in this nightly that the whole screen is outlined with I think a gray line, which isn't that nice.

Could you show me a picture?

**Comment by KoalaBear84** [comment]
Yes. I've tried to make a screenshot of it in the initial post, but I see it also appears when not in fullscreen.

Here is the bottom right corner, it's the line between the two taskbars and the one at the right, it has color #CCCCCC

![image](https://user-images.githubusercontent.com/5886900/201903524-3d8ab9e2-7106-414c-90d5-27ffdf7d974e.png)

**Comment by KoalaBear84** [comment]
Great, it looks like that in @Kingtous [nightly release](https://github.com/Kingtous/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64-pc-windows-msvc.exe) the cursor is working as expected 👍
![image](https://user-images.githubusercontent.com/5886900/201913796-b025490b-e2c7-4769-8c34-27d0034cf5ec.png)

And I noticed I could easily show the cursor offset issue by creating a screenshot on the host of Paint.NET on the client:
![image](https://user-images.githubusercontent.com/5886900/201913171-db60f321-c212-4642-b8ef-87b0d6858c5a.png)

It looks like it is around 16x16 offset in this example. I see it also is the case in the text area in the first screenshot, so it looks like it is an issue everywhere. That why I sometimes click outside of a window instead of it's top 'caption' bar.

The outline is still there, just to inform on all issues.

**Comment by rustdesk** [comment]
Thanks for your test.

**Comment by KoalaBear84** [comment]
Sorry, small update to the outline. If you want it could be a separate issue. It got a little larger at the bottom. After pressing "Reset canvas" it goes back to the 1 pixel outline again.

![image](https://user-images.githubusercontent.com/5886900/202113279-e853545a-85e5-4515-a8e1-f72639423976.png)

**Comment by rustdesk** [comment]
> a separate issue

Go ahead please.

**Comment by rustdesk** [comment]
clear issue seems fixed.

**Comment by rustdesk** [comment]
@KoalaBear84 Could you help test cursor not clear and hotspot wrong issue with the newest nightly build?

**Comment by KoalaBear84** [comment]
Yes, tested the other 2 issues, those are fixed. This one also seems fixed, altought I cannot say that it is a 100%, because yesterday I did saw it again, but not sure what the host/client versions were. But for now it can be closed, and I could reopen when I notice it again. 👍

**Comment by KoalaBear84** [comment]
Ah, I understand. The nightly was just 'run', and it doesn't (of course) updates the already installed version. But because the version is the same it also doesn't show the Install part. Uninstalled and reinstalled, now it's working as expected.
