### ISSUE TITLE
Keyboard key Grave accent (`) and Tilde (~) dont work with Remote Access is open.

### ISSUE THREAD

**Issue by claudioferrazb** [rustdesk/rustdesk#2129]
<!**Describe the bug you encountered:**
Keyboard key Grave accent (`) and Tilde (~) dont work with Remote Access is open.

**What did you expect to happen instead?**
Keyboard key Grave accent (`) and Tilde (~) should work's with Remote Access is open.

**How did you install `RustDesk`?**
Win x64 installer.

--

**RustDesk version and environment**
Version: 1.1.9 - Windows x64

**Comment by rustdesk** [comment]
try out nightly build please

**Comment by claudioferrazb** [comment]
Tks! Work's fine =)
