### ISSUE TITLE
copy/paste sync bug when multiple connections

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#2131]
From email

> We are using Rustdesk software for our users to access their dashboard PC and now they are complaining that they are getting weird issue while copy and paste the content from browser or any app.
> 
>  
> 
> They are trying to copy the content from browser and when they are pasting it to their email compose its pasting the other remote users content.

My understanding:

`A -----> B <------C`

A's clipboard is synced to C via B

**Comment by firozkhan431** [comment]
@rustdesk Please support for this issue.

**Comment by kir-lys** [comment]
I have the same problem. Clipboard settings don't turn it off. 
@rustdesk, plaese help with that

**Comment by rustdesk** [comment]
@fufesou since you are working on https://github.com/rustdesk/rustdesk/issues/3952 and https://github.com/rustdesk/rustdesk/issues/427, let do this together.

**Comment by fufesou** [comment]
RustDesk compare the clipboard text for now.
It does not listen the clipboard update event.

Consider this situation:

```
A -----> B <------ C
Or
A <----- B -------> C
```

1. `A` update clipboard "A".
2. `B` update clipboard "A".

Should `B` sync clipboard content "A" to `C`?

If so, this issue exists.
If not so, what if `A` `Ctrl+C` "A", and try to past on `C`?
`A` detects no changes, and will never sync clipboard text to `C`, until the text other than "A" is copied.

**Comment by rustdesk** [comment]
Follow anydesk/teamviewer behavior.

**Comment by fufesou** [comment]
Anydesk works perfect.
```
A -----> B <------ C
Or
A <----- B -------> C
```

1. Copying on `A` or `C` does not affect the other side.
2. Copying on `B` affects both sides.

Maybe RustDesk need to listen the clipboard update event on all platforms, not only comparing the clipboard text.

**Comment by firozkhan431** [comment]
@rustdesk It should work like AnyDesk platform. Anyhow I'm not working anymore on RustDesk.

**Comment by rustdesk** [comment]
close since fix merged
