### ISSUE TITLE
Recent sessions shows permanent offline.

### ISSUE THREAD

**Issue by wazerstar** [rustdesk/rustdesk#2134]
**Describe the bug you encountered:**

Recent connections I had to users shows offline all time even if they are started in their end.
Waiting a period of 5 minutes did not do anything

Tested Lan and Wan sessions with own server and official server.

**What did you expect to happen instead?**

Show clients/sessions with a green dot / Online whenever they start their rustdest client

**How did you install `RustDesk`?**

Nightly Build rustdesk-1.2.0-x86_64-pc-windows-msvc.exe

---

**RustDesk version and environment**

Windows 10 Pro x64 and Windows 11 Pro x64

**Comment by rustdesk** [comment]
server side not deployed yet
