### ISSUE TITLE
Double letters

### ISSUE THREAD

**Issue by dronov-dmitry** [rustdesk/rustdesk#2137]
Hallo
When in windows is russian language (or any not english letters) - in linux is created second superflous letter
![изображение](https://user-images.githubusercontent.com/9892891/202010154-0e3a3b5c-a868-4cf7-969a-a6c3bc3df0c9.png)

**Comment by rustdesk** [comment]
try out nightly build please

**Comment by grummbeer** [comment]
Very cool!  A lot of effort has gone into the key thing over the last few weeks. Thanks for that!

I can confirm that the double letters problem is not longer present. Build from source last hour.

That problem occured under Linux > Windows.

**Comment by rustdesk** [comment]
thanks

**Comment by dronov-dmitry** [comment]
Yes. Night build is work perfect. Thx
