### ISSUE TITLE
PORTABLE - request to elevate permissions

### ISSUE THREAD

**Issue by neogalaxy88** [rustdesk/rustdesk#2155]
As in AnyDesk to have the possibility to request in the portable version the elevation to admin user.

it would also be important for the software to ask for the user and password on the client side (useful in situations with a domain)

**Comment by rustdesk** [comment]
duplicate issue

**Comment by rustdesk** [comment]
try out nightly build tommorrow, code merged today

**Comment by rustdesk** [comment]
#70
