### ISSUE TITLE
Rustdesk 1.1.9 not compatible with windows 10 pro [PLEASE HELP]

### ISSUE THREAD

**Issue by sistemaspbi** [rustdesk/rustdesk#2164]
Hello everyone

I wanted to ask if anyone knows why rustdesk 1.1.9 (client) not compatible with windows 10 pro version 22H2. I have installed it on a laptop with windows 11 pro and also in a Ubuntu 20.04 TLS and there has been no problem, but when trying to install it on a desktop with windows 10 pro it tells me that it is not compatible. I tried in 2 different computers and same message. 

The exactly message is:

_"Cannot run this application on the computer.

To find a version for your computer, please contact the software advertiser."_

Say that these desktops currently have Anydesk installed and I do not know if that could be affecting.

I would really appreciate it if you could help me to solve this problem as we are in a bit of a hurry in the organization.

Thank you very much for your time

**Comment by Pedro-Guilherme** [comment]
Hi there...

Do you have a screenshot ??

**Comment by sistemaspbi** [comment]
Hi, thanks for the replay, I just realize was me I didn't read that, even if the machine is a icore7, has installed a 32bit system. I didn't try yet to install the 32 bit version but I really hope will work. I will try tomorrow and if everything works correctly I will close the issue.

Anyway here are the screenshots.
![rustdesk1](https://user-images.githubusercontent.com/118367381/202320439-4742ca13-2bf2-4009-8bb6-a90f8f1e0fdf.jpg)
![rustdesk02](https://user-images.githubusercontent.com/118367381/202320484-efd3343f-b750-43a7-83ac-0e0c4a43a1e6.jpg)

Thanks a lot for your time.

**Comment by nikkdevic** [comment]
You have 32 bit Windows. So download the 32-bit installer.
[https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-windows_x32.zip](url)
