### ISSUE TITLE
If you connect to android host and drag it, it will work after the delay.

### ISSUE THREAD

**Issue by YTOAA** [rustdesk/rustdesk#2167]
Is this a limitation in the current version, not some kind of bug?

**Comment by rustdesk** [comment]
when you illusrate that issue dlearly, we will convert that back to issue, please do not create duplicate things.

**Comment by YTOAA** [comment]
This only happens when you open the host on Android, no matter what os the client is installed on. (Including the test version) To be exact, this happens when dragging rather than with a normal touch. If you exit the touch or mouse click rather than react immediately when dragging, you will then move along the corresponding drag path. And this is a different problem, but I don't think the input from the hardware keyboard goes to the Android host yet.

**Comment by rustdesk** [comment]
it is limitation.

**Comment by YTOAA** [comment]
> it is limitation.

Can you explain what the limit is?

**Comment by rustdesk** [comment]
Our brain is the limit, :)

**Comment by rustdesk** [comment]
Yes, I see you many times.
