### ISSUE TITLE
Android Problem to open keyboard

### ISSUE THREAD

**Issue by JostickDev** [rustdesk/rustdesk#217]
The keyboard dont open, dont work when i want to write something

**Comment by rustdesk** [comment]
click keyboard button on the toolbar.

**Comment by rustdesk** [comment]
it can not pop out automatically.

**Comment by JostickDev** [comment]
I do it, but the problem is on android, when I press the keyboard icon, the keyboard close automatically and I can do nothing, on previous version it was working fine

**Comment by rustdesk** [comment]
understood, I will give a quick fix soon.

**Comment by rustdesk** [comment]
try out https://github.com/rustdesk/rustdesk/releases/download/1.1.8/rustdesk-1.1.9.apk please

**Comment by JostickDev** [comment]
its working now very good

**Comment by rustdesk** [comment]
> its working now very good

Can you help test if dragging scrollbar works? because some one report this problem, i am not sure it is real problem or he do not know how to use.

**Comment by JostickDev** [comment]
ok

**Comment by JostickDev** [comment]
do you mean that the scroll option in the mouse icon its working?

**Comment by rustdesk** [comment]
both scroll option and drag option. If you use drag option, you must move cursor on to scrollbar first.

**Comment by JostickDev** [comment]
the scroll is working, but I dont know how the drag option works, beacuse with the scroll option i can navigate fine or using just the mouse pointer an doing click on the scrollbar of the web

**Comment by rustdesk** [comment]
You can move cursor onto scrollbar first without "drag" option. Then you turn on "drag" option and drag the scrollbar.

**Comment by JostickDev** [comment]
ok let me try

**Comment by JostickDev** [comment]
The drag option is working fine, but when I remove the option my mouse pointer doesn't have move on the screen, it just let me do clicks on the screen, the pointer will static

**Comment by rustdesk** [comment]
"touch" mode?

**Comment by rustdesk** [comment]
Thanks for your test.
