### ISSUE TITLE
iOS client cant interact when macOS display go to sleep

### ISSUE THREAD

**Issue by kintaro1981** [rustdesk/rustdesk#2170]
**Describe the bug you encountered:**
during a ios => macos connection
if the macos display go to sleep there's no way of interact with it and awake it. 
I don't know if this happens with other os' too.
...

**What did you expect to happen instead?**
the display turn on again, or at least continue to interact with os
...

**How did you install `RustDesk`?**
binary download from rustdesk.com
 
...

**RustDesk version and environment**
ios rustdesk 1.1.10
macos rustdesk 1.1.9
macos mojave 10.14.6
ios 15.6.1

...

**how to reproduce the issue:**
connect from ios to control macos. send display to sleep

**Comment by rustdesk** [comment]
duplicate issue

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/981
