### ISSUE TITLE
Rustdesk can it support h264 h265 video encoding for cloud game?

### ISSUE THREAD

**Issue by 1265578519** [rustdesk/rustdesk#2174]
Rustdesk can it support h264 h265 video encoding for cloud game?
how set gpu encoding, no cpu use, RTX 3090 like Parsec support 4k 144fps and custom video bitrate.

**Comment by 21pages** [comment]
Support h264/h265, try [nightly](https://github.com/rustdesk/rustdesk/releases/tag/nightly) both side.

It's enabled default.
![1668646809620](https://user-images.githubusercontent.com/14891774/202328229-261d66f1-a574-471b-adc8-ae0eccd1aa05.png)
![1668646913218](https://user-images.githubusercontent.com/14891774/202328418-d5f1504e-8602-42d7-826a-2ee0e5817f84.png)
![1668646947833](https://user-images.githubusercontent.com/14891774/202328507-2d3b6f09-5053-4d68-8a5e-ae5c7e5aded6.png)

**Comment by hiro-yoshida** [comment]
Hello Rustdesk, I tested the current nightly for ubuntu (rustdesk-1.2.0-x86_64-unknown-linux-gnu-ubuntu-18.04.deb) on a Ubuntu 20.04 box with RTX8000, but it did not seem to have enabled the GPU encoding, as a Windows client did not show the selection of encoding. Is a special setting/library needed for Ubuntu 20.04?
