### ISSUE TITLE
"waiting for image" when locked screen on windows server 2012 (installed)

### ISSUE THREAD

**Issue by mail136** [rustdesk/rustdesk#2175]
有些电脑锁定状态时，远程过去一直卡在“画面传输中...”，一直无法显示windows登录界面，例如：我有一部腾讯云ECS windows server 2012远程过去正常，而另一部实体电脑也是windows server 2012则一直卡在“画面传输中...”，两部电脑使用同一自建服务器。我使用的RustDesk客户端是https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-windows_x32.zip服务端是[rustdesk-server-windows-x64.zip](https://github.com/rustdesk/rustdesk-server/releases/download/1.1.6/rustdesk-server-windows-x64.zip)

**Comment by rustdesk** [comment]
duplicate issue

**Comment by rustdesk** [comment]
install

**Comment by mail136** [comment]
> install

你好！非常感謝你的回覆！是不是要開啟服務才行？就算install了，服務如果未啟動也會有這種情況嗎？

**Comment by rustdesk** [comment]
can not connect if service not open.

**Comment by mail136** [comment]
> can not connect if service not open.

我很確定，我已經兩邊電腦都install安裝了，而且用向日葵、anydesk、Teamviewer遠程都是正常的，就rustdesk遠程那部機時一直卡在“画面传输中...”，除非我用向日葵遠程過去登錄rustdesk才能見到畫面。

**Comment by rustdesk** [comment]
traced by https://github.com/rustdesk/rustdesk/issues/5609
