### ISSUE TITLE
Main window is hidden by subwindow

### ISSUE THREAD

**Issue by fufesou** [rustdesk/rustdesk#2176]
**Describe the bug you encountered:**

1. Preview on taskbar shows only main window.
2. Main window is shadowed by subwindow.

https://user-images.githubusercontent.com/13586388/202349605-716d34fe-6457-469b-9c8a-267c30b21894.mp4

...

**What did you expect to happen instead?**

- [x] Preview on taskbar should show all windows.

- [x] Actived window should show in front of others.

- [x] Subwindow does not show blank if all windows are minimized and shown again.

...

**How did you install `RustDesk`?**

Build from source.

---

**RustDesk version and environment**

Win10.

**Comment by rustdesk** [comment]
@Kingtous

**Comment by fufesou** [comment]
Latest source build still does not fix this problem.

1. Main window is hidden by subwindow.
2. Subwindow retains blank for sometime, if both windows are hidden and shown again.

https://user-images.githubusercontent.com/13586388/202830128-59b7fd94-f10c-4ac1-abf0-46403485b13c.mp4

**Comment by rustdesk** [comment]
only one issue solved yet

**Comment by Kingtous** [comment]
> Subwindow retains blank for sometime, if both windows are hidden and shown again.
related:  https://github.com/leanflutter/window_manager/issues/155
