### ISSUE TITLE
code bug about sessionGetOption

### ISSUE THREAD

**Issue by zkteco-home** [rustdesk/rustdesk#2177]
![image](https://user-images.githubusercontent.com/66519168/202363191-aaf09e5c-5367-40e0-8021-b30308983a1d.png)

      In display settings,i can guess default is adaptive from source code,but it didnt work

![image](https://user-images.githubusercontent.com/66519168/202363607-7022ff29-3e9d-4822-aab0-177b4071f534.png)

![image](https://user-images.githubusercontent.com/66519168/202364285-a83f6684-131a-4eb1-a212-cbce1c20e1a1.png)

it looks ?? not working when sessionGetOption function return ''
...

**What did you expect to happen instead?**

   I expect default is adaptive when connected and adaptive menu is selected,as same as menu balanced

**How did you install `RustDesk`?**

    compiled master source code(with flutter)

**RustDesk version and environment**

latest code

**Comment by rustdesk** [comment]
@fufesou
