### ISSUE TITLE
W10 title bar appearing causes whole screen to shift

### ISSUE THREAD

**Issue by bilogic** [rustdesk/rustdesk#2178]
1. When in full screen, moving the mouse to the top of the screen causes the whole remote desktop to shift downwards
2. This shift can be quite distracting/disruptive
3. It would be better if the title bar slides down like Teamviewer
4. The key point is the shift is distracting especially if the mouse is moved to the top accidentally
5. My request is to keep the remote desktop static, the title bar can be shown in any manner

Thank you.

**Comment by rustdesk** [comment]
try out nightly build, also the bar is also being refactoring in nightly build.
