### ISSUE TITLE
I can't unlock remote win10's screen saver.

### ISSUE THREAD

**Issue by iamshifty** [rustdesk/rustdesk#218]
My remote client is a win10, and I set auto lock when I have leaved 10 minutes. I can't unlock this screen saver to input password screen.

**Comment by rustdesk** [comment]
installed? double clicked? or alt+crl+del from toolbar?

**Comment by iamshifty** [comment]
Yes,installed!
If I controll the computer directly,I can use any key or drap mouse from bottom to up unlock this screen.
But I can't do these from remote.

**Comment by rustdesk** [comment]
I can also on my remote win10, but not sure what happened in your case.2021年9月3日 12:58，iamshifty ***@***.***>写道：
Yes,installed!
If I controll the computer directly,I can use any key or drap mouse from bottom to up unlock this screen.
But I can't do these from remote.

**Comment by rustdesk** [comment]
make sure it is installed on remote side.

**Comment by iamshifty** [comment]
Sorry,I reinstall the new version,I have could unlock remote screen now.Thanks.

**Comment by sarankrishhh** [comment]
rustdesk screen cant unlock
