### ISSUE TITLE
Update the app tray icon to highres version (macOS)

### ISSUE THREAD

**Issue by NoLooseEnds** [rustdesk/rustdesk#2187]
The current tray icon is lowres, and since pretty much everything running macOS is on retina displays that sticks out like a sore thumb among the other highres icons.

As far as I know macOS supports SVG, so I just went ahead and created two versions for dark/light GUI from the logo, but I can't figure out where they are located, so I can't make a pull request.

Anyhow, they can be downloaded here: https://www.dropbox.com/t/H9BwT0Uxl9vSPmrY

Let me know if you need anything.

Thanks.

**Comment by rustdesk** [comment]
Fixed in our master branch, though not release nightly macos build yet.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/tree/master/flutter/macos/Runner/Assets.xcassets/AppIcon.appiconset

**Comment by rustdesk** [comment]
Sorry, you mentioned tray icon. reopen.

**Comment by NoLooseEnds** [comment]
Thanks, I made [a pull request](https://github.com/rustdesk/rustdesk/pull/2709) now. Just changed the files and path info. Hopefully it works (no experience in rust at all).
