### ISSUE TITLE
Compile error on arm platform（Nvidia Xavier）

### ISSUE THREAD

**Issue by depeng6** [rustdesk/rustdesk#219]
The previous compilation steps have been completed, and when I run this code：vcpkg/vcpkg install libvpx libyuv opus
  , I am prompted : Environment variable VCPKG_FORCE_SYSTEM_BINARIES must be set on arm, s390x, and ppc64le platforms.
How do I do that ^^^?

![image](https://user-images.githubusercontent.com/42143485/132076584-49e3b836-42b2-454a-9789-6304621768b0.png)

**Comment by rustdesk** [comment]
sorry, i have no arm

**Comment by rustdesk** [comment]
and you should ask microsoft about this question, the author of vcpkg, it has nothing to do with RustDesk.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/175

**Comment by alienshengzi** [comment]
我也是一样的问题  Jetson Xavier NX  ,  来个大佬编译好,  放个链接啊.

**Comment by cgdsss** [comment]
有大佬可以提供jetson Orin或者Xavier的deb安装包吗？也就是armv8版本的
