### ISSUE TITLE
API Server Field Validation Issue

### ISSUE THREAD

**Issue by BB21B** [rustdesk/rustdesk#2190]
Hello,

On latest nightly API Server field gives the error when you press Apply.

API Server: must start with http:// or https://

The URL is starts with https://

OS: Windows 11

![Screenshot 2022-11-17 182228](https://user-images.githubusercontent.com/50427842/202527621-c640ad86-0d3a-497c-8283-1c2c2eb3880e.png)

Thanks.

**Comment by rustdesk** [comment]
@21pages
