### ISSUE TITLE
Allow connections between LAN and external devices

### ISSUE THREAD

**Issue by yanickrochon** [rustdesk/rustdesk#2193]
I have my phone connected to the RustDesk server using the external IP, it's ready and waiting.
I have a PC connected to the RustDesk server using the LAN IP, it's ready and waiting.

The phone and PC can't connect to each other.

**Comment by rustdesk** [comment]
selfhost？

**Comment by yanickrochon** [comment]
Yes, installed via the [install script](https://rustdesk.com/docs/en/self-host/install/).

**Comment by rustdesk** [comment]
#763
