### ISSUE TITLE
UI version 1.20 to remember session pane view

### ISSUE THREAD

**Issue by Aerasyn** [rustdesk/rustdesk#2196]
Currently, when using 1.20, the session view panel always reverts back to the default large view instead of remembering which view to use like 1.19 did. Any chance of that being reimplemented?

**Comment by rustdesk** [comment]
@fufesou it worked, wondering if it is related to yesterday change, anydesk, check it out please.

**Comment by fufesou** [comment]
I've tested on my PC. Restoring position and size works.
The problem may exist a long time, but it does not always appear.
I will try to find it out.

**Comment by rustdesk** [comment]
> Restoring position and size works.

it is not position / size. it is card / grid style in rencent sessions.

**Comment by Aerasyn** [comment]
I just tried the latest nightly and this issue seems to have gone away. It failed to remember the grid style the first time after setting it but it is working in all following opens
