### ISSUE TITLE
Mouse between client and host is off center enough to misclick frequently

### ISSUE THREAD

**Issue by Aerasyn** [rustdesk/rustdesk#2197]
**Describe the bug you encountered:**
The location of the client's view of the mouse is ever so slightly, but noticeably, off-center than the host pc's side
...

**What did you expect to happen instead?**
The mouse to be using a 1 to 1 ratio for position on the screen.
...

**How did you install `RustDesk`?**

Github release of 1.20 for windows on clients. Possibly different levels of nightly in between some of the machines but issue persists.
---

**RustDesk version and environment

**Comment by rustdesk** [comment]
#2147 confirmed fix, are you sure using latest nightly build? also please give a picture please.

**Comment by Aerasyn** [comment]
Ah, yeah, wasn't using latest one. Ty
