### ISSUE TITLE
Uppercase vowels with accent (Spanish) do not work

### ISSUE THREAD

**Issue by flusheDData** [rustdesk/rustdesk#2198]
**Describe the bug you encountered:**

When I type an uppercase vowel with accent it does not work. I get one without accent. Eg. AEIOU

**What did you expect to happen instead?**

ÁÉÍÓÚ

**How did you install `RustDesk`?**

Portable 

**RustDesk version and environment**

**Comment by rustdesk** [comment]
#1892
