### ISSUE TITLE
What does "patch for wayland" actually do?

### ISSUE THREAD

**Issue by desertstsung** [rustdesk/rustdesk#220]
I login with X11, and then click something like "patch for wayland" in the left part of RustDesk GUI. However, the next time I get into GDM, there is no option for Wayland. After some seeking, I modified the `/etc/gdm/custom.conf` with doas, comment the `WaylandEnable=false` option. After that, I got the Wayland option in GDM, again.

So, my question is: When I click the "patch for wayland" or something in RustDesk under X11, are you actually modify the file `/etc/gdm/custom.conf`? If so, how can you do that without authentication?

OS: ArchLinux
kernel: 5.13.13-zen1-1-zen
Desktop Environment: GNOME 40.4.0

**Comment by desertstsung** [comment]
Okay, I found it in function [fix_login_wayland](https://github.com/rustdesk/rustdesk/blob/a99e6f38e5817cce62d1a0b8a500640d327e8830/src/platform/linux.rs#L409). But I still feel weird of doing this without users' permission.

**Comment by desertstsung** [comment]
I'm sorry, I tried again and the function contains `pkexec` need authentication.

**Comment by desertstsung** [comment]
But I still think this kind of "kill" is NOT "fix". The label `Fix it` should be `Disable it`. Source: [class FixWayland: Reactor.Component](https://github.com/rustdesk/rustdesk/blob/3cd9ee2aa34ba88af6b75b31118c3e9c2dc8cbd5/src/ui/index.tis#L547)

**Comment by rustdesk** [comment]
Agree

**Comment by desertstsung** [comment]
> Agree

Thx. It's kind of easy job, so I want to fork this repository and pull request.

If I am honored to join in, my further step is going to check if there is a better way of logging in using X11 by default while keep Wayland remain, till the real implementation of Wayland fix is done.

**Comment by rustdesk** [comment]
> fork this repository and pull request

Welcome

**Comment by desertstsung** [comment]
> if there is a better way of logging in using X11 by default while keep Wayland remain

There's a pseudo code of such implementation:
```python3
if current_session_is_wayland:
    valid_sessions = exec("ls -1 /usr/share/xsessions/").stdout()
    for valid_session in valid_sessions:
        if valid_session is ends with "xorg": session = valid_session
    for valid_session in valid_sessions:
        if valid_session is ends with "wayland": session = valid_session - "wayland"
    target_file = "/var/lib/AccountsService/users/"+username()
    change "Session=*" into "Session="+session in target_file
```
After this step, user should log out, and then the default login session is "Xorg"

**Comment by rustdesk** [comment]
> After this step, user should log out, and then the default login session is "Xorg"

Is ok for all Linux distributions? If so, please go ahead.

**Comment by desertstsung** [comment]
I found that's ok in ArchLinux (my laptop) and Ubuntu-LTS(my workstation), therefore I'm looking for a rpm-based distro to verify. In addition, there's not enough info about other desktop environment, that's another difficaulty. Could you please offer me some kind help if you have some other environment?

Appendix:
valid sesssion of my Arch: `gnome`, `gnome-classic`, `gnome-xorg`
valid session of my Ubuntu: `ubuntu`, `ubuntu-wayland`

**Comment by rustdesk** [comment]
I also only test Manjaro, Ubuntu and Fedora.

**Comment by desertstsung** [comment]
Oh, It's a great help, I think that's enough. I'm going to work on it during my spare time.

**Comment by dannkunt** [comment]
What about looking through obs-studio code? It can stream video on the wayland

**Comment by rustdesk** [comment]
"Fxi it" button is removed, because it is dangerous, many guys complain it.
