### ISSUE TITLE
The master branch code is on macOS, and the screen can be displayed by actively connecting to the other party'windows'. However, when 'windows' connects to'macOS', no screen is transmitted. The error log is as follows

### ISSUE THREAD

**Issue by szxv587** [rustdesk/rustdesk#2204]
<img width="1293" alt="截屏2022-11-18 12 32 47" src="https://user-images.githubusercontent.com/18606623/202617499-c511ab89-a251-4052-a804-f410c821ce51.png">
Can you tell me what causes it?

**Comment by rustdesk** [comment]
#763
