### ISSUE TITLE
Nightly 1.2.0 - CAPS LOCK don't work and some weird problems

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#2211]
### Discussed in https://github.com/rustdesk/rustdesk/discussions/2210

<div type='discussions-op-text'>

<sup>Originally posted by **emporiobviver** November 18, 2022</sup>
Hi guys.

My primary language is Brazilian Portuguese, we use Portuguese ABNT2 keyboard layout and installed 1.2 Nightly due accent problems.

But now, when i connect in any machine, i can't use CAPS LOCK to digit in CAPS, i need to hold Shift but even Shift sometimes don't work.

This problem occurs on 1.1.9 and 1.2 versions, on legacy and map modes.

There's a way to solve this problem?

I self-hosting my server with Ubuntu Server 22.10 LTS.
All machines have Windows 10 Pro.
Keyboards layout are Portuguese ABNT2.
All machines have Rust 1.2.0 version running.

Sorry my bad english.</div>

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1547

**Comment by ForsakenRei** [comment]
Potentially same issue as https://github.com/rustdesk/rustdesk/issues/2139 but I never encountered `Shift` didn't work.

**Comment by ForsakenRei** [comment]
> > Potentially same issue as #2139 but I never encountered a situation where `Shift` didn't work either.
> 
> If `CAPS` are locked on the client machine, `Shift` don't work, if not locked, `Shift` works.
> 
> But you can't lock/unlock `CAPS` using RustDesk.
> 
> Assuming that `CAPS`+`Shift` are lower case and only `Shift` are UPPER CASE, combination of `CAPS`+`Shift` don't work for me.

I cannot reproduce the exact same issue because even Caps locked in remote, as long as I have any keyboard input from the host, Caps will be unlocked. Anyway it is pretty weird for sure.

**Comment by Benhur91** [comment]
Hi,
I had the same issue on my computer. Caps lock as well as shift and other keys were working weirdly or simply not working.
I solved it by switching RustDesk service off in tray bar (on driving computer, not target one).
Hope it helps.
