### ISSUE TITLE
Rustdesk systemd service not working as expected

### ISSUE THREAD

**Issue by NicKoehler** [rustdesk/rustdesk#2227]
Rustdesk systemd service not working as expected, this is what I see using `systemctl status rustdesk`.

```sh
systemd[1]: Started RustDesk.
rustdesk[145763]: g_signal_emit_valist: assertion 'signal_id > 0' failed
rustdesk[145858]: g_signal_emit_valist: assertion 'signal_id > 0' failed
rustdesk[145958]: g_signal_emit_valist: assertion 'signal_id > 0' failed
rustdesk[146055]: g_signal_emit_valist: assertion 'signal_id > 0' failed
rustdesk[146150]: g_signal_emit_valist: assertion 'signal_id > 0' failed
```

Changing the user `root` in the service file to mine seems to get the service to work as expected.

I installed rustdesk using pacman and the Nighly build from 19/11/2022
| | |
| - | -: |
| OS | Arch linux
| Kernel | 6.0.8-zen1-1-zen
| DE | Gnome 43.1
| Window System | X11

**Comment by rustdesk** [comment]
“not working as expected” is what?

**Comment by NicKoehler** [comment]
I can't connect to the machine with another computer unless I change the service file and reload the service

**Comment by rustdesk** [comment]
@Kingtous  g_signal_emit_valist seems from tray? there is no the other UI things in --server.

**Comment by Kingtous** [comment]
> Changing the user root in the service file to mine seems to get the service to work as expected.

Did u changed root with current running `USER`?

**Comment by rustdesk** [comment]
it has been working as `root`.

**Comment by rustdesk** [comment]
we can not reproduce this issue.

**Comment by NicKoehler** [comment]
> Did u changed root with current running `USER`?

I did `User=nic` instead of `User=root` in the .desktop file.

Before I was using rustdesk-bin from AUR and I didn't have this issue.

The only differences that I found is that the service from rustdesk-bin was located in `/usr/lib/systemd/system/rustdesk.service` and the file now is in `/etc/systemd/system/rustdesk.service`.

Here's the diff:
```
diff /etc/systemd/system/rustdesk.service oldservice.desktop 
9c9
< PIDFile=/run/rustdesk.pid
---
> PIDFile=/var/run/rustdesk.pid
```

**Comment by rustdesk** [comment]
aur is not maintained by us.

**Comment by NicKoehler** [comment]
Yes I know, but the AUR was working fine, now I'm using your nightly release directly to get the latest builds every day

**Comment by rustdesk** [comment]
so we tried our best to reproduce the issue on our side.

**Comment by Kingtous** [comment]
`rustdesk-bin` is 1.1.9. The nightly aur I found is `rustdesk-nightly`.

and it seems to install package directly from our nightly release only.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rustdesk-nightly

**Comment by NicKoehler** [comment]
> `rustdesk-bin` is 1.1.9. The nightly aur I found is `rustdesk-nightly`.

I saw that, but it doesn't update daily, it just download the latest version at the time of the installation

**Comment by Kingtous** [comment]
> > `rustdesk-bin` is 1.1.9. The nightly aur I found is `rustdesk-nightly`.
> 
> I saw that, but it doesn't update daily, it just download the latest version at the time of the installation



> I can't connect to the machine with another computer unless I change the service file and reload the service

Is `connection refused` or something?

**Comment by NicKoehler** [comment]
> Is `connection refused` or something?

No, it loads for like 30 seconds and then this error occurs: 

![Screenshot_20221119_125900.jpg](https://user-images.githubusercontent.com/53040044/202849869-fb1efd76-2acb-47f6-b44d-5884701eb358.jpg)

Also I think it connects, because if I try to copy some text on the computer while is connecting in the 30 seconds before the error, I see the phone receiving the clipboard content

**Comment by Kingtous** [comment]
I'm preparing a patch for stopping show the tray icon when the execution user is `root`. Let's check if it make the connection failed.

https://github.com/Kingtous/rustdesk/commit/6d0039b104c3e35c52839500200d326a9dd9d9dc

U can check https://github.com/Kingtous/rustdesk/actions/runs/3503452805. Once it's done, the release will be [here](https://github.com/Kingtous/rustdesk/releases/tag/nightly) in about 30-40mins. Thanks for testing.

**Comment by NicKoehler** [comment]
> I'm preparing a patch for stopping show the tray icon when the execution user is `root`. Let's check if it makes the connection failed.
> 
> https://github.com/Kingtous/rustdesk/commit/6d0039b104c3e35c52839500200d326a9dd9d9dc
> 
> U can check https://github.com/Kingtous/rustdesk/actions/runs/3503452805. Once it's done, the release will be [here](https://github.com/Kingtous/rustdesk/releases/tag/nightly) in about 30-40mins. Thanks for testing.

I think it worked, your last build now works fine!

**Comment by Kingtous** [comment]
> > I'm preparing a patch for stopping show the tray icon when the execution user is `root`. Let's check if it makes the connection failed.
> > 
> > https://github.com/Kingtous/rustdesk/commit/6d0039b104c3e35c52839500200d326a9dd9d9dc
> > 
> > U can check https://github.com/Kingtous/rustdesk/actions/runs/3503452805. Once it's done, the release will be [here](https://github.com/Kingtous/rustdesk/releases/tag/nightly) in about 30-40mins. Thanks for testing.
> 
> I think it worked, your last build now works fine!

thanks
