### ISSUE TITLE
secure 

### ISSUE THREAD

**Issue by lbl8603** [rustdesk/rustdesk#223]
请问这个端到端加密是如何防止中间人攻击的呢，研究了你这部分代码[server.rs](https://github.com/rustdesk/rustdesk/blob/master/src/server.rs#L90)，如果中间人篡改数据的话，用户可能建立一个不安全的连接，这是否存在安全漏洞呢，请麻烦解答一下

google translate

> How does this end-to-end encryption prevent man-in-the-middle attacks? I studied this part of your code server.rs. If the man-in-the-middle tampered with the data, the user may establish an insecure connection. Is there a security vulnerability? Please answer me.

**Comment by rustdesk** [comment]
Can you tell me how can they modify the data specifically?

**Comment by rustdesk** [comment]
and at which stage?

**Comment by lbl8603** [comment]
1.我发现是否加密是由中继服务器控制的，有一个secure 参数并且传递一个客户端pk值，如果中继服务器不安全，那客户端会不进行加密
2.如果有中间人截取了客户端传递的公钥，并且将公钥拦截下来替换成自己的密钥对，那是否就能在中间进行加解密数据呢
3.连接过程中用户密码只有两端知道，为什么不使用密码参与加密呢

**Comment by lbl8603** [comment]
我对你们的源码研究得不够深，也许你们考虑到了这个问题，也请麻烦解答是怎么做到的

**Comment by rustdesk** [comment]
1, It is not relay server, it is rendezvous server, You should trust my rendezvous servers, and the server do not know your secret key. If the connection is not encrypted, you can see it from the icon on the toolbar. And I can also pop out dialog to tell you also, you choose to if allow the unencrypted connection.
2, public key is encrypted while transiting
3, you need to learn more about TLS knowledge.

**Comment by lbl8603** [comment]
你们是怎么对公钥进行加密的呢

**Comment by rustdesk** [comment]
Check code please

**Comment by rustdesk** [comment]
Or TLS doc

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/63#issuecomment-855530293

**Comment by lbl8603** [comment]
> 2, Public key is encrypted while transiting
可是如果走服务器转发的话，传递出去的公钥并没有进行加密呢，如何保证公钥传递过程是安全的呢https://github.com/rustdesk/rustdesk/blob/c5f1222476887eb51f3ba5a6403158e8bbea08a2/src/rendezvous_mediator.rs#L370

**Comment by rustdesk** [comment]
This public key is not what public key I meant.

**Comment by rustdesk** [comment]
Please learn TLS yourself.

**Comment by rustdesk** [comment]
It is not exactly TLS, but similar to TLS.

**Comment by rustdesk** [comment]
crypto_sign_ed25519 for signature creation and verification  - register_pk' pk is here
crypto_box_curve25519xsalsa20poly1305 for asymmetric cryptography
crypto_secretbox_xsalsa20poly1305 for symmetric cryptography - the pk I meant
