### ISSUE TITLE
Mouse buttons Next/Previous Page Functionality Feature

### ISSUE THREAD

**Issue by sabaton21** [rustdesk/rustdesk#2230]
Hail to rustdesk team. Thank you very much for your great efforts in coding this super nice tool.
It would be super cool if you could implement mouse buttons Next/Previous page functionality as i think is is a very useful-practical feature to exist in the app.

**Comment by rustdesk** [comment]
what is it?

**Comment by sabaton21** [comment]
Many mice have these two extra buttons on the side that are programmed when clicked to return web pages back and front and the same for windows, it is like you press front and back arrows on windows explorer and browsers. This does not work with rustdesk 1.1.9 and 1.2.0 and is a really cool and practical feature.

**Comment by tacaly** [comment]
<html>
<body>
<h3>Advanced Buttons</a></h3>

Name | Description
-- | --
XButton1 | 4th mouse button. Typically performs the same function as Browser_Back.
XButton2 | 5th mouse button. Typically performs the same function as Browser_Forward.


</body>
</html>

> Many mice have these two extra buttons on the side that are programmed when clicked to return web pages back and front and the same for windows, it is like you press front and back arrows on windows explorer and browsers. This does not work with rustdesk 1.1.9 and 1.2.0 and is a really cool and practical feature.

**Comment by tacaly** [comment]
@sabaton21 Would it be as a setting you think of, or a pre-set function like a macro?

**Comment by sabaton21** [comment]
> @sabaton21 Would it be as a setting you think of, or a pre-set function like a macro?

A preset function like a macro.

**Comment by rustdesk** [comment]
#1547

**Comment by G2G2G2G** [comment]
>Many mice have these two extra buttons on the side that are programmed when clicked to return web pages back and front and the same for windows, it is like you press front and back arrows on windows explorer and browsers. This does not work with rustdesk 1.1.9 and 1.2.0 and is a really cool and practical feature.

This is mouse4 and mouse5 they're common all over and it is up to the software itself to read them, not the buttons to do anything other than send their code.

Also as @tacaly said those are the windows names for the buttons, I assume rust translates it to whatever mac uses (linux is probably the same name as windows)

For the web browser,
As javascript implements: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button
their codes are wrong (vs every other language that exists.. that's how javascript likes to be I guess)
their array starts at 0. Also the middle mouse is generally "Mouse3" to keep a lookout there.

all browsers have supported this for ~20 years, file managers in windows, macOS & OS X, linux, and many other programs.

**Comment by rustdesk** [comment]
@fufesou  is on this.

**Comment by sabaton21** [comment]
Yes
Sent from Yahoo Mail on Android 
 
  On Thu, Jan 5, 2023 at 10:33 AM, ***@***.***> wrote:   


@fufesou is on this.

**Comment by fixsssator** [comment]
Any luck with adding additional mouse buttons?

**Comment by ForDefault** [comment]
Wondering as well
