### ISSUE TITLE
Issue with toning Greek Words

### ISSUE THREAD

**Issue by sabaton21** [rustdesk/rustdesk#2231]
**Describe the bug you encountered:**

When you switch to Greek language in keyboard, when you press this button ![image](https://user-images.githubusercontent.com/118606727/202848857-f6269fa4-24ad-4bf8-becc-349abbcab331.png) and then the Greek letter you want to tone then instead of toning the letter it is typed a  semicolon (;) and then the Greek letter with the tone. This happens all the time and sometimes as an additional issue, after the letter is presented toned with the semicolon in front, then keyboard language changes to English the next typed character comes as English and then language returns back to Greek so the next and on Greek letter typed remain in Greek.

For example, you want to type **καλημέρα (good morning)** the outcome is: καλημ;έρα all times and sometimes comes as καλημ;έrα 

...

**What did you expect to happen instead?**

For example, you want to type **καλημέρα (good morning)** the outcome is: **καλημ;έρα** all times and sometimes comes as **καλημ;έrα**
...

**How did you install `RustDesk`?**

I have installed Rustdek 1.2.0 nightly windows version (not the portable one). Same happens with the stable one (1.1.9). 
---

**RustDesk version and environment**

I am Running Windows 10 Pro 21H2 on a Desktop PC with all Microsoft updates installed and have ENG and Greek keyborad languages enabled.

**Comment by rustdesk** [comment]
#1720
