### ISSUE TITLE
Socks5 Proxy bug

### ISSUE THREAD

**Issue by BB21B** [rustdesk/rustdesk#2232]
**Describe the bug you encountered:**
Socks5 Proxy does not connect. RustDesk shows Not Ready.

I have setup a Dante Socks5 proxy on port 443 I can successfully connect to with the following command on the same machine running the RustDesk Client

curl -v -x socks5://socks:password@inform.url.tld:443 http://inform.url.tld

I can successfully connect to resources running on the same server. (RustDesk Server and Dante are running on the same instance).

I cannot find any useful logs mentioning the Socks5 connection in \AppData\Roaming\RustDesk\log\

...

**What did you expect to happen instead?**

That RustDesk connects via the Socks5 Proxy
...

**How did you install `RustDesk`?**

Latest Nightly Build on Windows 11

![socks](https://user-images.githubusercontent.com/50427842/202850643-606a8bd2-add2-4f6b-8b86-506b7e9e9690.jpg)

**Comment by BB21B** [comment]
Also posting my Dante config

`logoutput: syslog
user.privileged: root
user.unprivileged: nobody

# The listening network interface or address.
internal: 0.0.0.0 port=443
internal: 0.0.0.0 port = 143
internal: 0.0.0.0 port = 110

# The proxying network interface or address.
external: eth0

# socks-rules determine what is proxied through the external interface.
socksmethod: username

# client-rules determine who can connect to the internal interface.
clientmethod: none

client pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
}

socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
}
`

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
@BB21B Hi, would you please try capture the network package to see if socks5 is established.

![image](https://user-images.githubusercontent.com/13586388/202854941-bbf64f06-5eda-469d-bd69-803f5f1bf305.png)

**Comment by BB21B** [comment]
@fufesou will do later np

**Comment by fufesou** [comment]
May you try ```[IP]:[PORT]``` in the Hostname field. I haven't tested domain before. I'll try later too.

**Comment by fufesou** [comment]
> May you try `[IP]:[PORT]` in the Hostname field. I haven't tested domain before. I'll try later too.

`[DOMAIN]:[PORT]` works on my machine as well.

**Comment by BB21B** [comment]
I opened it up on port 1080 so Wireshark would categorise it properly.

It does appear to be making 

the Socks connection

![socks2](https://user-images.githubusercontent.com/50427842/202856401-60937a61-0ccb-4b63-a92e-993ce7e4828e.jpg)

**Comment by BB21B** [comment]
Maybe this is an issue with running Danted Socks and RustDesk Server on the same instance? That's the only thing I can think of now.

**Comment by BB21B** [comment]
Still fails if I take my relay server out and it attempts to connect to rs-cn.rustdesk.com (and others)

It must be something with my config but it should be pretty simple, I'll probably have to do some more verbose logging on the Danted server and see what is happening

**Comment by fufesou** [comment]
I don't know your server environment well. But in most cases, it is enough to open the network port.

**Comment by BB21B** [comment]
Opening up UDP 21115 and 21116 seems to be enough. Thanks for the help, not sure why I didn't think to open up Wireshark.

**Comment by gdomod** [comment]
its possible to add simple https_proxy support ? it would be usefull for many many business users
