### ISSUE TITLE
Rustdesk with socks5 proxy cannot connect to rustdesk network

### ISSUE THREAD

**Issue by aarmn** [rustdesk/rustdesk#2237]
**Describe the bug you encountered:**
I cannot use rustdesk over socks5 proxy (a two hop ssh tunnel)
...

**What did you expect to happen instead?**
Both way connection work, but I can connect to other rustdesks, others cannot connect to my desk
...

**How did you install `RustDesk`?**
NixOS Repos
---

**RustDesk version and environment**
computer is located in Iran, therefore there maybe some blockades on some ports and stuff, but socks5 should (and do) pass them all, I can bypass videocall restrictions which should be similar in their protocol complexities
version 1.1.9

My assumption is it ignore socks5 somehow in one stage of connecting to rustdesk servers, that's why I cannot connect with socks on, it cannot register itself and somehow mapping do not occur, when not using socks, with a diff system (using a sys wide vpn) it worked halfway (I got a popup from other side) it may have worked and maybe the reason it didn't work that time was due to internet speed.

Thanks beforehand

**Comment by rustdesk** [comment]
#2232 duplicate

**Comment by Perryen** [comment]
I met the same problem ,but not solved it yet
