### ISSUE TITLE
Password is not protected 

### ISSUE THREAD

**Issue by Mofidul-10** [rustdesk/rustdesk#2243]
**Describe the bug you encountered:**
when Mouse hover in password section then password is visible for all users.
...

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

**Comment by rustdesk** [comment]
try out nightly build.

**Comment by Mofidul-10** [comment]
> try out nightly build.

how long will it take?

**Comment by GogoFC** [comment]
Works fine for me on Linux, but on Andriod 8 it is visible. Rustdesk version 1.1.10-1
This actually worked nice for me because my screen just lost color and visibility so I couldn't see it on the actual screen :) so thanks.
