### ISSUE TITLE
Keyboard does not work controlling Android from Windows

### ISSUE THREAD

**Issue by stunndard** [rustdesk/rustdesk#2244]
Tried with the latest APK: https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9.apk
Tried on 2 different phones, Huawei and Xiaomi.

Client version: Windows nightly, 1.2.0, build 2022-11-20 00:27

Tried both Legacy and Map keyboard modes, to no avail, cannot type using my physical keyboard from Windows. Onscreen Android keyboard works fine though.
Am I missing something or keyboard is not supposed to work on Android?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3000
