### ISSUE TITLE
Service needs restart after DNS record change

### ISSUE THREAD

**Issue by elveos** [rustdesk/rustdesk#2245]
**Describe the bug you encountered:**
Rustdesk service needs to be restarted on a receiver machine after ID/relay server's IP get changed. 
E.g., rustdesk.example.com 'A' record points to 10.1.1.1, this gets updated to 10.1.1.2, but receiver machine doesn't see an IP change and keeps using the old IP (10.1.1.1) even if operating system is aware of the DNS change. This is the case on both Linux and Windows machines.

**What did you expect to happen instead?**
Receiver machine could use the operating system's DNS record, or perform a DNS lookup at regular intervals when FQDN instead of IP is used for ID/relay server. 
Or a better way would be a round robin check-until-succeeded (when same domain uses multiple A records). This could potentially lead to high-availability feature that was requested in [ #1486](https://github.com/rustdesk/rustdesk/issues/1486).

**How did you install `RustDesk`?**
Downloaded latest stable version from rustdesk.com (Github) for Debian and Windows.
On Manjaro, installed nightly build via Pamac from AUR repo (Github).

---

**RustDesk version and environment**
RustDesk client `1.1.9` on `Debian 11` and `Android`
RustDesk latest `nightly` build client on `Manjaro`

RustDesk receiver side version `1.1.9` on `Windows 7` and `Debian 11`
`hbbs/hbbr` server Docker image on `Debian 11`

**Comment by rustdesk** [comment]
try out nightly build
