### ISSUE TITLE
IP whitelisting by CIDR blocks

### ISSUE THREAD

**Issue by bbhenry** [rustdesk/rustdesk#2246]
It seems like I can only input single IP addresses per line. I'd like to whitelist entire local network as a single item. 

for example:
```
192.168.0.0/24
```

**Comment by rustdesk** [comment]
@Xerxes-2 there should be some efficient CIDR lib which can verify an IP with multiple CIDR in most efficient way.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/2281

**Comment by rustdesk** [comment]
But iOS does not have ID.

**Comment by rustdesk** [comment]
Mobile has no ID also if server not started.

**Comment by rustdesk** [comment]
That's why we did not add id whitelist before.

**Comment by akong77** [comment]
I understand, so I just suggest that you can do this. After all, most people will use remote control to control computer. I think this kind of function can be done, and remind users that it is not recommended to use it on ios or android.
