### ISSUE TITLE
rustdesk\flutter\web\js>yarn build

### ISSUE THREAD

**Issue by jujuejifada** [rustdesk/rustdesk#2249]
rustdesk\flutter\web\js>yarn build
yarn run v1.22.19
warning package.json: No license field
$ ./gen_js_from_hbb.py > src/gen_js_from_hbb.ts && ./ts_proto.py && tsc && vite build
error Command failed with exit code 9009.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by rustdesk** [comment]
#763
