### ISSUE TITLE
Self hosted server and clients set up with key. Not getting encrypted connection notification

### ISSUE THREAD

**Issue by Aerasyn** [rustdesk/rustdesk#2261]
**Describe the bug you encountered:**

Everything is connecting as expected with k_ to produce locked down server, I just noticed that now, connections are not showing as encrypted. Gives "insecure connection" message on top left with shield icon in red.

**What did you expect to happen instead?**

Encrypted connection to be functioning and shield icon to be green.

**How did you install `RustDesk`?**

Installed self hosted server on raspberry pi with docker, clients are windows machines using 1.20 from 11/20/22

**RustDesk version and environment**
Self hosted 1.19 server on raspberry pi through docker. Clients are all windows 11 machines with latest 1.20 nightly

**Comment by rustdesk** [comment]
#763
