### ISSUE TITLE
screen rotation support

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#227]

**Comment by rustdesk** [comment]
https://github.com/bryal/dxgcap-rs/blob/master/src/lib.rs#L397

**Comment by Makoto-WAT** [comment]
Thank you for supporting the horizontal display of Lenovo Miix 2 8 with rustdesk-1.1.9.
In rustdesk-1.1.8, even if Miix 2 8 is displayed horizontally, it is displayed vertically on another PC to be operated, and the screen is distorted.
With rustdesk-1.1.9, I now have full control over my horizontal Miix 2 8.
I am very grateful to you.

**Comment by rustdesk** [comment]
> Makoto-WAT
Help to hear it helps you, then can you give us a Start for support? :)
