### ISSUE TITLE
Enter the up and down keys will become 2 and 6

### ISSUE THREAD

**Issue by akong77** [rustdesk/rustdesk#2270]
**Describe the bug you encountered:**
1. I connect my remote windows pc.
2. I use remote windows pc to connect linux server via putty.
3. I edit linux file use vim command.
4. If I use up down left right key will show number. 

...

**What did you expect to happen instead?**
Should be moving the cursor

...

**How did you install `RustDesk`?**
Install by exe

---

**RustDesk version and environment**
server 1.1.6
client 1.1.9
![圖片](https://user-images.githubusercontent.com/6081927/203276714-8e5f8963-41c0-4267-9087-445e77ce9f0e.png)

**Comment by akong77** [comment]
I make sure not input number.

**Comment by rustdesk** [comment]
duplicate issue.

**Comment by rustdesk** [comment]
#1681
