### ISSUE TITLE
win10 64bit  compile fails

### ISSUE THREAD

**Issue by tx991020** [rustdesk/rustdesk#228]
vcpkg is already installed 

$ cargo build
   Compiling hbb_common v0.1.0 (C:\Users\Administrator\rustdesk\libs\hbb_common)
   Compiling scrap v0.5.0 (C:\Users\Administrator\rustdesk\libs\scrap)
   Compiling magnum-opus v0.3.4-2 (https://github.com/open-trade/magnum-opus#ad083616)
error: failed to run custom build command for `magnum-opus v0.3.4-2 (https://github.com/open-trade/magnum-opus#ad083616)`

Caused by:
  process didn't exit successfully: `C:\Users\Administrator\rustdesk\target\debug\build\magnum-opus-539cee280161eae9\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', C:\Users\Administrator\.cargo\git\checkouts\magnum-opus-7580b098b18e2bc5\ad08361\build.rs:7:50
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by rustdesk** [comment]
search old issues please.
