### ISSUE TITLE
File copy and paste function not working

### ISSUE THREAD

**Issue by thgadelha8bits** [rustdesk/rustdesk#2283]
**Describe the bug you encountered:**

File copy and paste function not working in Windows 10

...

**What did you expect to happen instead?**
Is it possible to copy a file from my computer and paste it into the session user's computer?

...

**How did you install `RustDesk`?**

Rustdesk installed on windows 10 64bit

nightly Release 1.2.0 installed on both computers

---

**RustDesk version and environment**

**Comment by rustdesk** [comment]
enabled?

**Comment by fufesou** [comment]
@thgadelha8bits @zkteco-home Can you please check if this option is enabled?
![image](https://user-images.githubusercontent.com/13586388/203526055-0820125d-2a43-4c1f-af15-e0e11ec72059.png)

**Comment by thgadelha8bits** [comment]
> @thgadelha8bits @zkteco-home Can you please check if this option is enabled? ![image](https://user-images.githubusercontent.com/13586388/203526055-0820125d-2a43-4c1f-af15-e0e11ec72059.png)

Yes, its enable. but not working

**Comment by rustdesk** [comment]
1.1.9 works?

**Comment by thgadelha8bits** [comment]
> 1.1.9 works?

no

**Comment by rustdesk** [comment]
@fufesou it seems our file copy/past is not robust enough, though we can not reproduce it. Let me reopen this and keep watch.

**Comment by wazerstar** [comment]
@rustdesk 

I can confirm with latest nighties.

The copy/move will sometimes crash the target end machine explorer or just freeze rustdesk connection to the controlling unit, while it will be stuck for either a random amount of time or refresh within a few seconds. 

Trying to copy/move once again will never work until you deactivate rustdesk connection down in tray on target machine and enable it again, not very convenient asking the user to do this to continue to operation.

But that's how it is with windows machines atm.

**Comment by rustdesk** [comment]
We may have to rewrite our file copy&paste, current implementation is ugly and buggy. That's why we do not enable it by default.

**Comment by test2a** [comment]
@fufesou hey.... i just updated to the latest nightly on my linux but i dont see the option, is this windows only?

**Comment by test2a** [comment]
i updated to the latest version as i said and clipboard  "from local to remote"  is not working while "remote to local" is working.

**Comment by fufesou** [comment]
@test2a "File copy&pates" only works with connection between Windows.

**Comment by test2a** [comment]
@fufesou got it. the clipboard should work, maybe something broke recently?

**Comment by test2a** [comment]
@zkteco-home i would like to say it is currently working for me, has worked for the past 3-5 days so i will update if i see this again (clipboard text copy paste)

**Comment by fufesou** [comment]
New files copy and paste silently interrupt previous files pasting.

**Comment by arkabase** [comment]
Same here between two Windows 11 stations with RustDesk 1.1.9 64bits.
Can copy/paste text in and out, but not files.

**Comment by wazerstar** [comment]
> Same here between two Windows 11 stations with RustDesk 1.1.9 64bits. Can copy/paste text in and out, but not files.

I would deff not use 1.1.9 its a graveyard!

Use latest nightly build, but yes it still has problems.

https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64-pc-windows-msvc.exe

**Comment by rustdesk** [comment]
Looking for contributors to rewrite this part. Current implementation is hard to be maintained.

**Comment by agarre** [comment]
Hi! I'm new here. I'm unsure about the location of the functions related to it in the code.
Could anyone kindly provide me with some guidance on which files I should investigate to find the implementation of these functions? It would be extremely helpful for me to know where to start looking so I can begin working on a solution.

Thank you all

**Comment by fufesou** [comment]
@agarre Hi, you can refer mainly here https://github.com/rustdesk/rustdesk/tree/master/libs/clipboard.

Only windows is implemented for now.
https://github.com/rustdesk/rustdesk/blob/master/libs/clipboard/src/windows/wf_cliprdr.c
The code is mainly from https://github.com/FreeRDP/FreeRDP/blob/master/client/Windows/wf_cliprdr.c

The clipboard is recently updated.

https://github.com/rustdesk/rustdesk/pull/4700

**Comment by NikAWing** [comment]
I did read the links, but I'm not sure if this is related:

yesterday I updated the nightly from two weeks ago to the one from yesterday.
Today I noticed that copying/pasting files does not work anymore (it does nothing at all).
source machine W11, destination machine W7

So I tried it with the build in file transfer window/menu: it just says error and the file is not copied.
BTW: I STILL have to log in if I want to use the file transfer, even if I already am connected via rustdesk itself. I thought that was fixed already but I can't find the issue I wrote about this when I first found rustdesk :)

**Comment by fufesou** [comment]
@NikAWing Thanks for your feedback. I'll try to fix the issue.

**Comment by fufesou** [comment]
@NikAWing 

> So I tried it with the build in file transfer window/menu: it just says error and the file is not copied.
 
Can you please attach a picture?

> Today I noticed that copying/pasting files does not work anymore.

I can reproduct this issue, Win10 -> Win7
I've tried both ngihtly and older version. All do not wok. (Win10 -> Win7)

![1687967567299](https://github.com/rustdesk/rustdesk/assets/13586388/d0294dc0-d6f2-4c3a-9725-03717dd3a34f)

Did copy/pasting from an older version work for you?

This is a very serious bug that causes Explorer to hang. I'll fix it as soon as possible.

**Comment by NikAWing** [comment]
yes, old nightly worked fine (the one from 2 weeks ago IIRC)
I don't have the old nightlies installed anymore and can not test or screenshot them.
But yeah, it happens from 7 to 11 (screenshot) and 11 to 7 works.
![Screenshot_2](https://github.com/rustdesk/rustdesk/assets/76008757/aac27d93-91dd-4b39-b65d-4aac389304c6)
Thanks fufesou :)

but yeah, you should stop fixing bugs, especially for operating systems that still are used by MANY people and companies and you should spend the time helping M$ fix their crappy W11 so it might some day be able to be used on production systems.
But I don't want to start another W7 discussion here, some people just don't (want to) understand that several companies don't really want to waste money on new hardware if the current computers work without problems :/

**Comment by Nandoo85** [comment]
Copy/Paste or Drag with last released version 1.2.0 ain't working for me, nor local or remote, allow option is enabled always. 
if i roll back to 1.1.9 it works.
tested w10-w10 and w11

**Comment by daysplume** [comment]
The clipboard can't paste images either

**Comment by Nandoo85** [comment]
copying text works fine but files no, transfer files is working, clipboard copy/paste options enabled
tested with last version and nightly (win 10 and 11)

**Comment by rustdesk** [comment]
Current file copy/paste implementation is very buggy, we plan to rewrite it rather than fix it.

**Comment by fufesou** [comment]
Hi, guys, I've tested the latest nightly build.

The "file copy-paste" works for me. I've tested Win10->Win11, Win11 -> Win10, Win10 -> Win10.

But many people has reported that "file copy-paste" does not work on 1.2.1->1.2.1.

I cannot reproduce this issue, and I've read the code, but failed to find the bug. I'm stuck now.

Can anyone contact me (shuanglongchen@yeah.net) and let me connect to your test computer if you have the same issue?

Many thanks.

https://github.com/rustdesk/rustdesk/assets/13586388/06c30b03-0cf7-4db2-9e4b-e8337e6f607b

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/5201#issuecomment-1660897276

**Comment by michealroberts** [comment]
File Transfer with Rust Desk is broken beyond salvation at this moment in time ... even the file transfer mechanism inside Rust Desk has an out-of-date filesystem without any way to refresh ... absolutely broken.

**Comment by fufesou** [comment]
@michealroberts Hi, could you please explain a little more?

Windows -> Windows? Waht are the versions on both sides? Installed or not?
How to trigger the issue?

Thanks

**Comment by michealroberts** [comment]
> [@michealroberts](https://github.com/michealroberts) Hi, could you please explain a little more?
> 
> Windows -> Windows? Waht are the versions on both sides? Installed or not? How to trigger the issue?
> 
> Thanks

Ubuntu Linux > Mac OS.

Drag & Drop is broken.

And the filesystem receive / send functionality doesn’t seem to pick up any files or directories in some areas.

There’s no way to transfer files.

**Comment by fufesou** [comment]
Copying to MacOS is not supported for now.
Drag & Drop is also not sipported.

**Comment by michealroberts** [comment]
@fufesou Brilliant.

I do get somewhere with the file transfer from inside Rust Desk and clicking in the transfer from the three dot dropdown, it’s looks more broken than not available tbh …

**Comment by acdcjavier** [comment]
Hi
For my side transfer files doesn't work using Windows 11 -> Debian 13
Only I can copy/paste text but files doesn't work
