### ISSUE TITLE
1.2.0 nightly Cursor does not hide

### ISSUE THREAD

**Issue by naddel91** [rustdesk/rustdesk#2296]
Dear Rustdesk team,

the feature "hide cursor" does not work. It still shows the mouse cursor moving around even when "hidden" is selected.

Best wishes!

Great app, btw!

**Comment by rustdesk** [comment]
where is "hide cursor" feature?

**Comment by naddel91** [comment]
there it is:

![hide cursor](https://user-images.githubusercontent.com/83251379/203593071-bbd90c97-0c78-4e4b-a6b6-e01785414b9b.png)

**Comment by rustdesk** [comment]
Or show a video to me so that I can understand you.

**Comment by naddel91** [comment]
I thought it would hide the cursor when unchecked.
