### ISSUE TITLE
Win10 -> MacOS black screen with mouse cursor only (awake and keep the screen unlocked for all OS)

### ISSUE THREAD

**Issue by misaka10086** [rustdesk/rustdesk#230]
**Describe the bug you encountered:**
When Win10(should be any version of client but only tested on Win10 yet) try to connect a MacOS machine with RustDesk pre-installed(internal Remote Desktop function also enabled which allow VNC client to connect). 
If the target Mac is auto locked due to long time no operation, it will show a black screen with mouse cursor only and unable to show login page. 

One way to resolve it is open a tunnel of port 5900(VNC) and run VNC viewer to connect to target machine and it will prompt login page normally, once unlocked, close VNC viewer and back to RustDesk, the login page is now prompted. 

**What did you expect to happen instead?**
When connected, a login page(same as login locally) should be displayed which allows unlock remote machine. 
...

**How did you install `RustDesk`?**
Github release

**RustDesk version and environment**
Windows: 1.1.8 
MacOS: 1.1.6
Mac mini m1(OS version: Big Sur 11.5) with no external display
This bug can only be recreated when target machine is locked(either manually or automatic due to timeout)

**Comment by misaka10086** [comment]
**Screenshot of Win10 Rustdesk Window after connected:** 
![BAMIXMJ 49_AX3P}55256$F](https://user-images.githubusercontent.com/16052890/133121978-59963cca-4170-4db5-9829-ae67b79ad70b.png)

**Comment by rustdesk** [comment]
A background service with privilege is required, should be duplicate to https://github.com/rustdesk/rustdesk/issues/77

**Comment by Lighfer** [comment]
Any progress?

**Comment by mrcblt** [comment]
I am also curious about any news regarding this issue. I can confirm that this issue persists with the latest version 1.1.9 on both Windows 10 and macOS. I have provided all permissions required by RuskDesk on my Mac.

In addition, this behavior is also reproducible from Android 12 (version 1.1.10-1) to macOS, again I only see a black screen with a cursor.

**Comment by donthomas21** [comment]
Is there any update on this issue. I still cannot connect to any Mac that has gone to sleep.

Thanks.

**Comment by rustdesk** [comment]
@asur4s

**Comment by tan-wei** [comment]
I just met the similar issue. But I find that I can only see the previous screen (yesterday evening), now MacOS should be on lock screen to input password.

**Comment by working-name** [comment]
Still an issue, lock screen does not render via rustdesk. If I connect via another remote software the screen will show and then everything will work in rustdesk.

**Comment by Lighfer** [comment]
There is a temporary solution：
1. open a tcp tunnel to remote host's ssh port
2. ssh to remote host, and`caffeinate -u` to wake up the screen

**Comment by working-name** [comment]
#981 - to be tackled when they have time.

**Comment by fazakis** [comment]
Hi I intorduced a small hack to overcome this problem by integrating caffeinate in the source, in 
 case somebody wants to use it: https://github.com/rustdesk/rustdesk/compare/master...fazakis:rustdesk:mac_hack

**Comment by rustdesk** [comment]
> Hi I intorduced a small hack to overcome this problem by integrating caffeinate in the source, in case somebody wants to use it: [master...fazakis:rustdesk:mac_hack](https://github.com/rustdesk/rustdesk/compare/master...fazakis:rustdesk:mac_hack)

But I think `spawn` is better, `output` will block 2 seconds.

**Comment by fazakis** [comment]
> > Hi I intorduced a small hack to overcome this problem by integrating caffeinate in the source, in case somebody wants to use it: [master...fazakis:rustdesk:mac_hack](https://github.com/rustdesk/rustdesk/compare/master...fazakis:rustdesk:mac_hack)
> 
> But I think `spawn` is better, `output` will block for 2 seconds.

Thanks fixed that

**Comment by rustdesk** [comment]
@fazakis good job, could you submit a pull request?

**Comment by grummbeer** [comment]
After https://github.com/rustdesk/rustdesk/pull/2678 the wake up problem should be solved (#981)

Time to try the latest nightly https://github.com/rustdesk/rustdesk/releases/tag/nightly

Still any issues?

**Comment by rustdesk** [comment]
Need to use something in [wakelock pub](https://pub.dev/packages/wakelock) to prevent mac from sleeping. @sj6219 wondering if you have interest to take a look at this.

**Comment by grummbeer** [comment]
thanks for explaination.

To get it right. Wakelock can only help when connected to an running Mac (to prevent it from falling into dreams), but not when trying to connect to an already sleeping mac? In this case caffeinate will waking up the mac? 

Beware, force keeping it awake (depend on connection not on active usage) could be security/privacy related.

**Comment by sj6219** [comment]
It is questionable whether the ability to prevent clients from falling asleep while connecting to the server is required.  Because user can just wake the client up with a mouse or keyboard.
I guess what the user wants is the ability to wake up a Mac computer server remotely that is sleeping.

I tried waking up Mac computers remotely, but it isn't easy.
As someone else explained above, if you try to connect to the port of vnc or ssh program that Apple provided the server, the server wakes up. However, in the case of the 3rd party program like rustdesk, there seems to be no wake-up function.

It's even very difficult to set up the wake on lan on the Mac.

**Comment by rustdesk** [comment]
This PR https://github.com/rustdesk/rustdesk/pull/2678 does not work for you?

**Comment by sj6219** [comment]
I don't know how to use it.
I briefly analyzed the source, and it seems to prevent the server from falling asleep while the client connects to the server.
It doesn't seem to wake up a server that's already asleep.

**Comment by sj6219** [comment]
I tested it, but it doesn't work.

By the way, it's amazing that you can wake up a server that's already asleep.

**Comment by ethpsantos** [comment]
@sj6219
> It is questionable whether the ability to prevent clients from falling asleep while connecting to the server is required. Because user can just wake the client up with a mouse or keyboard. I guess what the user wants is the ability to wake up a Mac computer server remotely that is sleeping.

Maybe each case is a case... the remote PC is a bit away from me and I need to wake up go there and unlock it (because consumer windows prevent the remote app to enter credentials).
Having to make that 20 times or more a day is really painful.

So while I'm connected to the remove PC it should not enter in lock screen at all.
That is how AnyDesk always worked for me.

**Comment by ethpsantos** [comment]
Hello.
Some update.

I found an app called Caffeine (seems like Insommia do the same but I did not tested) and I'm letting it active while I'm using Rustdesk... the only annoying is that I have to remember to turn it off when I will left remote session at the end of day to let Windows lock the screen and my childrens didn't mess with it after school.

For now it is working very well.. it could be better if it was auto in the Rustdesk but it is fine.

**Comment by Silentdoer** [comment]
This problem also occurs in the ArchLinux KDE desktop environment of the Wayland Protocol

**Comment by rustdesk** [comment]
- [ ] https://github.com/rustdesk/rustdesk/discussions/4452 https://github.com/rustdesk/rustdesk/issues/550 https://github.com/rustdesk/rustdesk/pull/729

**Comment by ethpsantos** [comment]
I wanted to share that you guys are awesome.
You don't know how much happiness I have with your app after it stopped to go back to login screen in the remote host.
Thanks so much.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/4557
