### ISSUE TITLE
Control Remote ID when autogenerated with 3 zero (XXX 000 XXX) cant connect

### ISSUE THREAD

**Issue by Mark-Oasan** [rustdesk/rustdesk#2300]
**Describe the bug you encountered:**
Control Remote ID when autogenerated with 3 zero (XXX 000 XXX) cant connect
...

**What did you expect to happen instead?**
Rough fix
run %appdata%
C:\Users\Administrator\AppData\Roaming\RustDesk\config\RustDesk.toml
Edit 'id' manually any numbers but not zero
...

**How did you install `RustDesk`?**

Installed from downloaded rar and proceed with the default installation
---

**RustDesk version and environment**
Windows/ WindowsServer 2019

I believe this is just a random bug that the id cant accept zeros

**Comment by rustdesk** [comment]
I believe it is fixed in nightly build.
