### ISSUE TITLE
1.1.8  background computer no signal only sound, the current one no problem

### ISSUE THREAD

**Issue by richelsky** [rustdesk/rustdesk#231]
**Describe the bug you encountered:**

I have two computers (Windows 10) sharing a set of keyboard, mouse and monitor. After updating 1.1.8, there is only sound when connecting to the background computer, there is no signal on the black screen, and the image is always displayed on the screen. There is no problem connecting to the current computer.

**What did you expect to happen instead?**

I don't know if there is a problem with the update patch

**How did you install `RustDesk`?**

2x windows 10 20H2        1.1.8
2x  android  11                 1.1.8

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/222

**Comment by richelsky** [comment]
ok ,that is running good.
 i have Netease music  by cracked version, it's black still, but I can still click the on button.
This does not affect my use，just reporting
