### ISSUE TITLE
Can´t find package:flutter_hbb/generated_bridge.dart

### ISSUE THREAD

**Issue by claudneysessa** [rustdesk/rustdesk#2311]
Hi!

I'm trying to compile the rustDesk project in flutter but it says the file is missing:

package:flutter_hbb/generated_bridge.dart

This file is not in the repository, it is as deleted in .gitignore

How do I compile it, can you make these files available?

---flutter rust bridge---
lib/generated_bridge.dart
lib/generated_bridge.freezed.dart

![image](https://user-images.githubusercontent.com/12506432/203897548-97e01a4e-6868-456e-8211-c913db46c9bc.png)

**Comment by rustdesk** [comment]
#763

**Comment by yunxingyu** [comment]
may you can  execute sh run.sh
