### ISSUE TITLE
AltGr (right side Alt) key not working inside a VMware

### ISSUE THREAD

**Issue by FCrane** [rustdesk/rustdesk#2316]
I'm controlling a computer in my LAN with RustDesk, which works great. It's running Windows 11 (21H2) and all the keys of my German keyboard work (even öäß\@ etc.) Only the "back" and "forward" mouse buttons don't work, but that's another issue which has already been reported.

Now for the bug I encountered: the PC I'm controlling is running a VMware guest (also Win11) and inside that guest OS, the "AltGr" (it's the Alt key on the right side of the German keyboard) does not work correctly. It's used to produce @ or \ on the German keyboard, but that does not work. As I said, it works on the host controlled by RustDesk, but not inside the VMware. Other Remote Desk programs (AnyDesk, TeamViewer, Parsec) do not have this problem.

Seems the AltGr key combinations are forwarded to the remote machine correctly, but then somehow they are not forwarded into the VMware correctly anymore. AltGr seems to be equivalent to Ctrl+Alt by the way, which (strangely enough!) DOES work correctly in the VMware guest. So I can type the characters @ and \ with "Ctrl+Alt" in the VMware, but not with "AltGr" (which should be the same).

Would be nice if this could be fixed!

Thanks for the great program!

**Comment by rustdesk** [comment]
#1547

**Comment by FCrane** [comment]
That's NOT the same issue! As I described, AltGr gets correctly sent to the remote machine! It just isn't transmitted correctly to a VMware running on the remote machine...

**Comment by rustdesk** [comment]
I did not say it is the same.

**Comment by FCrane** [comment]
I've just tried v1.2.0, but unfortunately, it's even worse. Here are the issues:

1) in keyboard mode "Map", it works outside the VMware. Inside VMware, the mapping is completely wrong - it seems to map to an English qwerty keyboard instead of the German qwertz I've installed (and configured correctly on all systems (host, remote and VMware guest).

2) in keyboard mode "Legacy", it also works on the remote machine, but inside the VMware guest, the mapping seems correct, however it does not transmit the "up" key for the special keys! Meaning that if I type e.g. "ä", I will get "äääääääääääääääääää" (indefinitely until I press another key. If i press "\" (with AltGr), I get "\ßßßßßßßßßßßßßßßß" (the ß is the key without AltGr). So it seems to recognize that AltGr is released, but it thinks the other key is still pressed.

3) Ctrl+Alt instead of AltGr works outside, but produces the same issues as 2) in the VMware guest.

4) the keyboard mode is not remembered between sessions. It always starts with "Map mode".

Other issues of v1.2.0 I encountered immediately:

1) the mouse cursor is about 2x the size it should be (maybe because the remote machine uses 150% dpi?) - was no problem on v1.1.9 (however sometimes the cursor was extremely tiny)

2) I have a shortcut to open an IP in my LAN on my desktop. When I start that, I get the remote window but additionally, the "RustDesk" main dialog opens (the one which is opened when I open the main program). I don't need that when I open a remote PC directly and it's pretty annoying, because I need to close it every time.

So unfortunately, I need to go back to v1.1.9, because the nightly (posted 2 hours ago) is unusable inside the VMware guest.

Regards!

**Comment by rustdesk** [comment]
> 1. the mouse cursor is about 2x the size it should be (maybe because the remote machine uses 150% dpi?) - was no problem on v1.1.9 (however sometimes the cursor was extremely tiny)
> 2. I have a shortcut to open an IP in my LAN on my desktop. When I start that, I get the remote window but additionally, the "RustDesk" main dialog opens (the one which is opened when I open the main program). I don't need that when I open a remote PC directly and it's pretty annoying, because I need to close it every time.

@fufesou

**Comment by rustdesk** [comment]
> 4\. the keyboard mode is not remembered between sessions. It always starts with "Map mode".

@fufesou and this

**Comment by rustdesk** [comment]
> 2\. I have a shortcut to open an IP in my LAN on my desktop. When I start that, I get the remote window but additionally, the "RustDesk" main dialog opens (the one which is opened when I open the main program). I don't need that when I open a remote PC directly and it's pretty annoying, because I need to close it every time.

@Kingtous

**Comment by rustdesk** [comment]
> > 2. I have a shortcut to open an IP in my LAN on my desktop. When I start that, I get the remote window but additionally, the "RustDesk" main dialog opens (the one which is opened when I open the main program). I don't need that when I open a remote PC directly and it's pretty annoying, because I need to close it every time.
> 
> @Kingtous

@FCrane could you test?

**Comment by FCrane** [comment]
> @FCrane could you test?

Sorry, no time yet. Will test tomorrow and report back!

**Comment by FCrane** [comment]
I've downloaded the latest nightly now (released 5 hours ago): 

1) the additional "RustDek" dialog does not appear anymore! Great!

2) mouse scaling does work if I enable "Zoom Cursor". If this is off, the cursor is always 2x the normal size. If the option is on, the cursor gets scaled with the remote window, which is ok. However, I'd still prefer that the cursor size is always constant like on my main desktop. This doesn't seem to be possible anymore, but was possible with 1.1.9. "Show remote cursor" does not seem to have any effect.

3) The keyboard issues inside the VMware are still present. Keyboard mapping mode is not remembered between sessions.

Regards!

**Comment by rustdesk** [comment]
> 2\. mouse scaling does work if I enable "Zoom Cursor". If this is off, the cursor is always 2x the normal size. If the option is on, the cursor gets scaled with the remote window, which is ok. However, I'd still prefer that the cursor size is always constant like on my main desktop. This doesn't seem to be possible anymore, but was possible with 1.1.9. "Show remote cursor" does not seem to have any effect.

@fufesou please check out the default cursor size of anydesk/teamviewer in this scenario. i think we need to follow mainstream design.

**Comment by rustdesk** [comment]
![mmexport1669538493385](https://user-images.githubusercontent.com/71636191/204126391-d8d78d36-f63c-4b67-8a09-63804f44fc94.png)
anydesk follows local cursor size, let's keep our current design first.

**Comment by FCrane** [comment]
Cursor scaling works fine and makes sense in most scenarios - so it is probably the best way for most users. However, an option to keep the cursor size constant would be nice...

Thanks!

**Comment by FCrane** [comment]
Regarding the "RustDesk" dialog, which pops up on the remote machine (top right of the desktop) for about 3 seconds and then minimizes to the task bar: do we need this at all? If the menu bar is accessible, the RustDesk dialog could be hidden completely (or vice versa). My preferred way would be just having the collapsed menu bar, because this is the least intrusive and gives me access to RustDesk on the remote machine if I need it (which I never do, once all settings are configured). The additional "RustDesk" item on the task bar (and the 3 seconds of dialog obscuring important info on the remote desk) is just disturbing for me without any value, so it would be great if there was an option to completely get rid of it. The (collapsed) menu bar is enough.

Thanks!

**Comment by FCrane** [comment]
Any idea when the keyboard mapping issue in VMware will be fixed? The problems still exist in the latest nightly build...

Thanks!

**Comment by fufesou** [comment]
@FCrane Hi, thanks for your detailed feedback.
I'm fixing keyboard issues of "Map mode".
The mapping issue should have been fixed now.
Can you please try the ngihtly build, with "Map mode". Thanks.

<img width="235" alt="20230104201351" src="https://user-images.githubusercontent.com/13586388/210727231-8ece41a0-7c46-4ff3-b4e4-f2f1193c4736.png">

**Comment by grummbeer** [comment]
can be closed?

**Comment by rustdesk** [comment]
Sure, Thanks @grummbeer
