### ISSUE TITLE
第一次连接后总是显示设备不在线

### ISSUE THREAD

**Issue by mlrsyz** [rustdesk/rustdesk#2318]
安卓被控端在第一次连接断开后就无法连接
再次连接就一直显示连接断开
自建服务器:hbbr.ondev.top:60041
公钥:EWPhILUWtZ8hO7HVPGJau6Wh9oIsAP6itQoNtS4kt1I=

是不是安卓客服端代码写死了tcp/udp心跳检测的端口号？

下面是docker容器配置
hbbr running
-rustdesk/rustdesk-server 2022-11-24 22:44:39 /
172.17.0.3  /
60044:21119 / 60042:21117

hbbs running
-rustdesk/rustdesk-server 2022-11-24 22:44:49 /
172.17.0.4 /
60043:21118 / 60040:21115 / 60041:21116

hbbs容器写了hbbr参数的
Args [ -r, hbbs.ondev.top:60042, -k, _ ]
麻烦解决下这个问题

**Comment by rustdesk** [comment]
#763
