### ISSUE TITLE
Why does my own compilation work on win10 x64 compiler, but it can not  run on win7 x64

### ISSUE THREAD

**Issue by tx991020** [rustdesk/rustdesk#232]
Why does my own compilation work on win10 x64 compiler, but it  can not  run on win7 x64

**Comment by TopsDesk** [comment]
Here is my menifest.xml. This covers from Windows Vista to Windows 10. Please check if this helps?
in main.rs enable #![windows_subsystem = "windows"] to build the windows executable.

<?xml version="1.0" encoding="utf-8"?>
<asmv1:assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1" xmlns:asmv1="urn:schemas-microsoft-com:asm.v1" xmlns:asmv2="urn:schemas-microsoft-com:asm.v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <assemblyIdentity version="1.0.0.0" name="RustDesk.exe"/>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges xmlns="urn:schemas-microsoft-com:asm.v3">
        <requestedExecutionLevel level="asInvoker" uiAccess="false" />
      </requestedPrivileges>
    </security>
  </trustInfo>

  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"></supportedOS>

      
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>

      
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"></supportedOS>

      
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>

      
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>

    </application>
  </compatibility>
</asmv1:assembly>

**Comment by rustdesk** [comment]
Not real issue
