### ISSUE TITLE
only spacebar working during remote session (no other keys functional)

### ISSUE THREAD

**Issue by MichaelOHInTO** [rustdesk/rustdesk#2325]
Hello, 

Using Windows 11, the only key that works during my remote session is the spacebar.  No other typing shows up at all.  

I checked with another remote desktop program and the same issue does not occur. 

Thanks!

**Comment by MichaelOHInTO** [comment]
Sorry upon further experimentation - certain other keys work.  Arrow keys, period, comma - etc.  Just not any letters.

**Comment by rustdesk** [comment]
#1547
