### ISSUE TITLE
When the mobile phone remote game account password, the Google keyboard cannot type the digital password

### ISSUE THREAD

**Issue by woshishiq1** [rustdesk/rustdesk#233]
I remotely control the win10 computer on my mobile phone and log in to QQ Speed! The Google input method used by the mobile phone, the English letter password can be entered normally when the password is input remotely, but the digital password can not be input no matter how I switch the Google input method. It works normally in other places, that is, it cannot be used when entering the password.

**Comment by rustdesk** [comment]
I can not reproduce your issue, what android phone are you using?

**Comment by rustdesk** [comment]
BTW, are you using https://gitee.com/rustdesk/rustdesk/attach_files/817674/download/rustdesk-1.1.8-1.apk?

**Comment by rustdesk** [comment]
No response.
