### ISSUE TITLE
Nightly 1.2.0 - RustDesk shortcuts are broken when you try to use them on the remote machine.

### ISSUE THREAD

**Issue by emporiobviver** [rustdesk/rustdesk#2334]
When you use RustDesk to connect to any machine, if this remote machine have RustDesk shortcuts to access any other machine and you try to use them, RustDesk don't connect and only show your little information window of the existent connection, if you open the RustDesk client on the remote machine and try to connect to a favorited machine, it works.

**What did you expect to happen instead?**
Using a RustDesk shortcut into a remote machine will open a new connection on this machine to another remote.

**How did you install `RustDesk`?**
Windows EXE intaller.

---

**RustDesk version and environment**
Selfhosting server, Ubuntu 22.04 LTS
All other machines are running Windows 10 Pro 21H2
All machines running Nightly 1.2.0.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2316#issuecomment-1328045075
