### ISSUE TITLE
Silent installation und deinstallation running partially

### ISSUE THREAD

**Issue by tobiasplagge** [rustdesk/rustdesk#2343]
**Describe the bug you encountered:**
When I install manuel the client with admin right, the installation is running and in the Taskbar can find Rustdesk Icon.
When I install the installation with --silent-install, the program install. When I show in the taskbar is missing the rustdesk button.
Search rustdesk in windows start menu, I can start the program. The program can't find in the right taskbar.

When I will deinstall rustdesk with --silent-reinstall, nothing happens.
When I running the paramenter --deinstall, rustdesk is starting and creat a icon in the right taskbar.

**What did you expect to happen instead?**
When I install rustdesk client with the silent parameter, the installation create a icon in the right taskbar and start automatical.
![image](https://user-images.githubusercontent.com/119170668/204139531-1a43573a-162c-4f37-bb20-bdc79fb4519d.png)

When I typing the deinstallation transfer parameters --silent-deinstall oder --deinstall, the client uninstalls itself.

**How did you install `RustDesk`?**

Yes manuel the version 1.1.9

**RustDesk version and environment**

Rustdesk Client 1.1.9

System. Acer ZenBook with Windows 10 22H2

Rustdesk Server is selfhosting in docker / portainer environment.

**Comment by rustdesk** [comment]
no need to repost
