### ISSUE TITLE
magnum-opus code is wrong with Macos M1

### ISSUE THREAD

**Issue by zkteco-home** [rustdesk/rustdesk#2349]
![image](https://user-images.githubusercontent.com/66519168/204227837-ba59aeae-5c56-4e3a-8777-1509ebba35a8.png)

**What did you expect to happen instead?**

code should be like this:
    let mut target = if target_os == "macos" {
        if target_arch == "x64" {
            "x64-osx".to_owned()
        } else if target_arch == "arm64"{
            "arm64-osx".to_owned()
        } else {
            format!("{}-{}", target_arch, target_os)
        }

i suggest you fork and push it to your repository

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
go PR
