### ISSUE TITLE
connection timeout

### ISSUE THREAD

**Issue by xyz0101** [rustdesk/rustdesk#235]
如图，在连接的时候会自动弹出一个空白的弹窗，无法点击和确认，最后连接超时，无法连接

Windows 10专业版 系统

客户端是最新版

![image](https://user-images.githubusercontent.com/20569072/134537487-76c1621e-a71b-4782-9dce-789b8753fd6b.png)

**Comment by rustdesk** [comment]
seems direct connection interrupted by firewall or 360 etc.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/215
