### ISSUE TITLE
After the win11 computer turns off UAC, the installation is still incomplete, and the win10 computer cannot connect to win11 through the self-built server

### ISSUE THREAD

**Issue by CodeNoobLH** [rustdesk/rustdesk#2350]
**Describe the bug you encountered:**

When installing for the first time, it is prompted that UAC is not turned off, resulting in an incomplete installation. After closing the UAC reminder and restarting the computer, the second installation still prompted the UAC, and changing the installation directory and clicking the install button had no effect. It doesn't matter how many times you install it in other ways. Other computers can connect to this computer through the default public server, but win10 computer connecting to this computer using a self-built server will prompt that the connection to the server fails. Strangely, using this computer to connect to other computers through the self-built server is successful (note: other computers can connect to each other through the self-built server, so the self-built server is available). I used 2 win7 computers, 1 win10 computer, and 1 win11 computer. The win11 computer has a UAC prompt, and after turning off UAC, the prompt of incomplete installation will still not effect, and it will not work after changing the installation directory and restarting.The win10 computer cannot connect to this win11 computer through the self-built server, but the default server can successfully connected,and the win7 computers can connect to the win11 computer also.

**What did you expect to happen instead?**

The installation can be successful, at least the reinstallation after UAC is closed can be installed successfully. To solve my problem, my win10 can connect to win7 through the self-built server, and my win11 can connect to win10 and win7 through the self-built server, but my win10 cannot connect to win11 through the self-built server, it will prompt the server connection failed, really Is it because of an incomplete installation?

rustdesk 1.1.9
windows 11 21H2 22000.1219
windows 10 21H2 19044.2251

**Comment by rustdesk** [comment]
#763
