### ISSUE TITLE
Unable to locate the program input point DiUninstallDriverW in the dynamic link library newdev.dll  （in win7）

### ISSUE THREAD

**Issue by shuai8819** [rustdesk/rustdesk#2358]
你好，在我的win7系统查了是有这个系统文件的， 但是启动还是会报同样的错误。是不是因为打包的问题呢？是不是需要换一种打包的方式呢。

Hello, I found this system file in my Windows 7 system, but the same error will be reported after startup. Is it because of packaging? Is it necessary to change the packaging method.

#2067 

![image](https://user-images.githubusercontent.com/68989281/204477291-70766671-accb-4303-9d03-df46a39b4f72.png)

**Comment by rustdesk** [comment]
our latest nightly build?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2359

**Comment by Kingtous** [comment]
we can successfully open rustdesk nightly on official win7 in virtualbox.

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/39793325/204721778-ba7c9c9d-87e0-4f58-a4f0-dda6b493175d.png">
