### ISSUE TITLE
Option to change modifier key mapping (mac <-> win)

### ISSUE THREAD

**Issue by drkvogel** [rustdesk/rustdesk#2365]
It would be good to be able to configure the mapping of modifier keys between different platforms.

For example, I am using RustDesk to remote from a Mac to a Windows host. On the Mac, I am used to using `cmd+tab` to change focus between apps, e.g. once I have finished doing something on the Windows host via RustDesk, I will tend to `cmd+tab` away to another application (e.g. to an editor like VS Code, particularly if I am doing something that involves copy-pasting text between the client and host). But RustDesk maps `cmd` on a Mac client to `Win` on a Windows host, and so `Win+tab` is output to the Windows host, which is the shortcut for Task View in Windows - so I keep accidentally opening Task View in Windows, which can be difficult to escape from sometimes - it is often not very responsive (which I think is a fault of Windows). I tried disabling the Windows key completely in the host, but although it disables physical keypresses from an attached keyboard, the host can still receive `Win` keypresses from RustDesk, so I have not found any way of working around this problem.

It would be good if at least there was an option to disable the mapping of `cmd` to `Win` for Mac hosts.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/3079

**Comment by rustdesk** [comment]
#1547

**Comment by rustdesk** [comment]
#1547

**Comment by rustdesk** [comment]
@fufesou please review

**Comment by rustdesk** [comment]
added in #3121
