### ISSUE TITLE
turn on #![windows_subsystem = "windows"] on windows the compiled exe cannot run

### ISSUE THREAD

**Issue by tx991020** [rustdesk/rustdesk#238]
When I turn on #![windows_subsystem = "windows"] on windows, the compiled exe  cannot run? what's the reason

**Comment by rustdesk** [comment]
> 研究越深，越发现作者很多代码故意写的啰嗦，写错的，正确的没开源，大家用的时候要慎用作者的代码，已现在的排版，#![windows_subsystem = "windows"] 根本去了黑框，试了10-20天 终于自己解决了。 如不明白联系我

It is not intentional. some verbosity is because of cross-platform. #![windows_subsystem = "windows"] is commented, because we have to comment it during debug stage, building for release is another story.
