### ISSUE TITLE
Can run RustDesk on Window 7 with installer built from Windows 10 machine.

### ISSUE THREAD

**Issue by samwell-ho** [rustdesk/rustdesk#2387]
**Describe the bug you encountered:**

I built RustDesk 1.1.10 (build on Windows 10).
When running RustDesk on Windows 7, the following error appears: "The procedure entry point SwDeviceCreate could not be located in the dynamic link library CFGMGR32.dll"

**What did you expect to happen instead?**

How to fix it? Has anyone ever encountered this error?

**How did you install `RustDesk`?**

Install by installer that I built from source.

---

**RustDesk version and environment**
- Windows 7.
- If I install the RustDesk 1.1.9 from RustDesk release, It can run.

**Comment by rustdesk** [comment]
#763
