### ISSUE TITLE
Cannot click buttons on certain macOS software

### ISSUE THREAD

**Issue by working-name** [rustdesk/rustdesk#2398]
**Describe the bug you encountered:**

I'm remoting a 10.14.4 system from windows 11 22000.1281 and Coda (a code editor on macOS) does not register clicks from rustdesk but it does so from other remote software (anydesk, teamviewer).

**What did you expect to happen instead?**

To register my left click.

**How did you install `RustDesk`?**

Your website.

---

**RustDesk version and environment**

1.1.9 vanilla install from your site on both systems.

### Client:
Windows 11 build 22000.1281
HyperVM enabled, running Ubuntu and Android

### Host:
MacOS 10.14.4 Mojave

**Comment by rustdesk** [comment]
https://rustdesk.com/docs/en/manual/mac/#enable-permissions

**Comment by working-name** [comment]
@rustdesk I think you missed the "on certain macOS software" part. The permissions are there for accessibility. There are no screen recording permissions on 10.14.4.

So the rest of the software I can click around but the tabs of open files at the top I cannot. Maybe you can look into why that is?

**Comment by working-name** [comment]
@rustdesk This is #981 by the way
