### ISSUE TITLE
Can't Generate ID With `Please Check Your Connection` Message

### ISSUE THREAD

**Issue by yasirroni** [rustdesk/rustdesk#24]
I'm trying to run RustDesk for my PC on campus. Zoho and AnyDesk got no problem setup connection, but RustDesk seems can't make connection.

The message are:

`Not ready. Please check your connection`

![Screenshot](https://user-images.githubusercontent.com/48709672/115135690-7371f300-a044-11eb-8d2f-987657595856.png)

For your information:
My campus block certain port, thus for GitHub adn GitLab we use `Port 443` to bypass the blocked port.

**Comment by yasirroni** [comment]
Manual ID setup also not possible:

![Screenshot](https://user-images.githubusercontent.com/48709672/115135746-23dff700-a045-11eb-8f77-6eacc8c4ed50.png)

**Comment by rustdesk** [comment]
please `telnet rs-sg.rustdesk.com 21116`?

**Comment by rustdesk** [comment]
> For your information:
> My campus block certain port, thus for GitHub adn GitLab we use `Port 443` to bypass the blocked port.

Port blocked.

**Comment by yasirroni** [comment]
Then, how to reroute the `Port` used by `rustdesk`? And what is the default `Port` used?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server/blob/master/id-relay-set.md

**Comment by rustdesk** [comment]
Some one told a reason.

>  I have found the reason, it is the clash whitch I opened.

**Comment by pabloab** [comment]
> https://github.com/rustdesk/rustdesk-server/blob/master/id-relay-set.md

The link is broken.
