### ISSUE TITLE
Error of video service

### ISSUE THREAD

**Issue by xhzth70911** [rustdesk/rustdesk#2402]
我在写ios端 被控端的程序 ，ios 当被控端的时候,macos控制端 连接ios被控端,连接成功的时候,ios端报错：
`Error of video service: Failed to create encoder: FailedCall("errcode=3 scrap::common::codec:libs/scrap/src/common/codec.rs:145:9")`

报错的源码:
```
call_vpx!(vpx_codec_enc_init_ver(
            &mut ctx,
            i,
            &c,
            0,
            VPX_ENCODER_ABI_VERSION as _
        ));
```

rustdesk的版本是git checkout c1bad84a86
请教一下怎么修改才能Encoder 编码创建成功,这块代码是没有修改过的，codec.rs里Decoder可以正常运行，谢谢

**Comment by rustdesk** [comment]
#763
