### ISSUE TITLE
Signing failed when building APK with Flutter Nightly Build in Actions.

### ISSUE THREAD

**Issue by CM5080** [rustdesk/rustdesk#2404]
Hello
Signing failed when building APK with Flutter Nightly Build in Actions. How can I do?
Thank you!
![image](https://user-images.githubusercontent.com/97935956/204986257-434ec46a-1350-43be-ab28-dbe82f910852.png)

**Comment by rustdesk** [comment]
#763

**Comment by KhyHolyDragon** [comment]
> Hello Signing failed when building APK with Flutter Nightly Build in Actions. How can I do? Thank you! ![image](https://user-images.githubusercontent.com/97935956/204986257-434ec46a-1350-43be-ab28-dbe82f910852.png)

Hi, so can you signed normally now? I also have this issue. even I have set android_signing_key, android_alias, android_key_store_password, android_key_password.
