### ISSUE TITLE
Update installation of nightly builds

### ISSUE THREAD

**Issue by FCrane** [rustdesk/rustdesk#2405]
Hi!

Every time I want to try a new nightly version, I first need to downgrade to 1.1.9 so that 1.2.0 will offer me to install itself. This is annoying... The program should check if the installed version is different than the setup (even if it's the same v1.2.0 like all nightly builds currently are) and if so, it should offer to "Upgrade" (or "Downgrade" or whatever). Having to install v1.1.9 every time I want to install a new 1.2.0 is really awkward...

Thanks!

**Comment by rustdesk** [comment]
rustdesk.exe --install or change name to rustdesk-install.exe
