### ISSUE TITLE
Error of video service

### ISSUE THREAD

**Issue by xhzth70911** [rustdesk/rustdesk#2407]
rustdesk安卓版本构建成功, 在android端运行的被控制的时候,报错：
`Error of video service: Failed to create encoder: FailedCall("errcode=3 scrap::common::codec:libs/scrap/src/common/codec.rs:145:9")`

报错的源码:
```
call_vpx!(vpx_codec_enc_init_ver(
            &mut ctx,
            i,
            &c,
            0,
            VPX_ENCODER_ABI_VERSION as _
        ));
```
rustdesk的版本是 c1bad84a86 
请教一下怎么修改才能让Encoder 创建成功，并正常运行

**Comment by rustdesk** [comment]
#763

**Comment by xhzth70911** [comment]
> #763

这不是编译构建的问题啊
