### ISSUE TITLE
ios not Encoder

### ISSUE THREAD

**Issue by xhzth70911** [rustdesk/rustdesk#2409]
https://github.com/rustdesk/doc.rustdesk.com/releases/download/console/ios_dep.tar.gz
解压出vcpkg文件夹, 这个文件是不是只支持解码,不支持编码？ 如果只支持Decoder，不支持Encoder，能不能给一个支持Encoder和Decoder的文件夹，谢谢，或者给一个可以编译ios vcpkg 文档支持

**Comment by rustdesk** [comment]
#763
