### ISSUE TITLE
Tray will broken after killed and restarted explorer on windows

### ISSUE THREAD

**Issue by yyjdelete** [rustdesk/rustdesk#241]
**Describe the bug you encountered:**

When you use task manager or other methods to kill and restart all explorer.exe (desktop) processes on windows, a new Rustdesk Tray icon will be shown on the taskbar, but unable to be opened. If you close it, the tray icon and menu will still be shown, but double-clicking and clicking `stop service` from menu have no effect 

当在windows下使用任务管理器或其他方式杀掉并重启所有explorer.exe(桌面)进程后, 在任务栏上会新显示一个无法打开的Rustdesk Tray图标, 如果将其关闭, tray图标及其菜单仍会正常显示, 但双击和点击长度中的关闭服务均没有效果

**What did you expect to happen instead?**

Tray icon should works and no extra window is shown, as all other programs does.
Rustdesk Tray的表现和其他windows上的正常tray程序一样, 不应该显示一个无法打开(或0大小?)的窗口, 且tray图标应该继续正常工作

**How did you install `RustDesk`?**

 GitHub release

---

**RustDesk version and environment**
1.1.8+Windows

**Comment by rustdesk** [comment]
thanks

**Comment by rustdesk** [comment]
close since too old and no further report from the other users.
