### ISSUE TITLE
fit to host screen

### ISSUE THREAD

**Issue by test2a** [rustdesk/rustdesk#2423]
Hi.

currently there are only 2 options for the screen resolution.

scale original
scale adaptive

original means the resolution of the remote connection
and adaptive is to "shrink" the remote desktop to fit to square screen on the client side.

the problem is, my desktop is  a tiny monitor
and my  host is a laptop .

so, if i do original, i am stuck with a good display but it is much bigger so the scroll comes up. that is not good.

adaptive makes it better but there are black bars on the sides which is wasted  space.

there should be a third "fit to screen" option that takes the current resolution of host and displays the full image
![Screenshot_20221202_113303](https://user-images.githubusercontent.com/39449563/205225984-210db3ac-2b11-407e-ae90-e04b9a3f1239.png)

here is the black bars. if the option to stretch or "fit to screen" was there, it would make the experience imo similar to "original" but without the scrolling.
![Screenshot_20221202_113416](https://user-images.githubusercontent.com/39449563/205226150-5857d1bb-ada8-42b4-b58c-d80a4d633f3d.png)

i "really really like" the original resolution for some reason but cannot stand scrolling. adaptive doesnt have that nice feeling

i dont know if the screenshots help my case but the original looks so much better

**Comment by chenzhihao1040728129** [comment]
I feel the same way

**Comment by thorstenwagner** [comment]
me too! That is definitely missing

**Comment by fufesou** [comment]
Maybe "Scale original" & "Scrollbar" can help you.

![image](https://user-images.githubusercontent.com/13586388/210070893-42ab20b0-e978-4b39-a565-4bdd33ad34aa.png)

**Comment by thorstenwagner** [comment]
Thanks! While this helpful a solution to adapt the resolution on the host screen ( and reset it on logout) would be much more convenient (like implemented in anydesk e.g).

30.12.2022 13:38:28 fufesou ***@***.***>:

**Comment by rustdesk** [comment]
> anydesk

how does it do? can you give me a picture about how to enable this on anydesk?

**Comment by fufesou** [comment]
@thorstenwagner Thanks, I've tried anydesk. I think it's a useful feature.

**Comment by thorstenwagner** [comment]
This is how it looks before I enable it (Full screen & stretch activated):
![image](https://user-images.githubusercontent.com/1113977/210078098-652129a6-31f4-4a25-bc6a-d98992572f43.png)

Then I enable "Auto adapt resolution"  (Full screen & stretch activated):
![image](https://user-images.githubusercontent.com/1113977/210078214-7a48910a-6fa3-44fb-9d59-f8993de9fcc3.png)

It basically sets the resolution on the host to the closest matching resolution of the client.

**Comment by rustdesk** [comment]
got it, it changes resolution of remote side.

**Comment by thorstenwagner** [comment]
exactly!

**Comment by rustdesk** [comment]
#1053

**Comment by rustdesk** [comment]
@fufesou This issue is reassigned to @21pages

**Comment by sanebg** [comment]
I can't believe 2 years later this is still not a feature. It's almost mandatory for good experience on mobile an remote pc's.

**Comment by jh-hh** [comment]
Hi! 

Now in 2026 I am still trying to find a way to adjust the resolution of the remote desktop to the size of my window... if I don't I can't read the tiny fonts of the remote machine. 

I know I can use adaptive scaling but that makes working on th remote desktop very much unusable because the local window only shows a fracture of the whole remote desktop - and the mouse movement moves the desktop... not ready for productive work! 

So at the moment I use KRDC which easily gives me the option to set "remote desktop resolution". I still would like to use Rustdesk as KRDC needs an additional VPN connection to work. 

This seems to be a very basic feature... I am not sure: Am I missing something obvious? 

Thx for reading! 
jh-hh
