### ISSUE TITLE
Steam OS and downstream Linux systems cannot connect after restarting

### ISSUE THREAD

**Issue by huangsijun17** [rustdesk/rustdesk#2424]
**Describe the bug you encountered:**

After installing and rebooting the system, unable to connect to the server, the software reports an error "connection refused".
![BD8 ~}CER~H5SR}G1~ 1~5V](https://user-images.githubusercontent.com/31504595/205240693-6d8e50ad-e2a5-42ff-8780-5b18787f4e7f.jpg)
log：
```
(deck@steamdeck ~)$ sudo rustdesk
flutter: launch args: []
flutter: initializing FFI main
flutter: _appType:main,info1-id:1aaf4bb709c14f669bf8214d7a4150ff,info2-name:SteamOS,dir:/root,homeDir:/root
flutter: _globalFFI init
flutter: _globalFFI init end
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
flutter: [MultiWindowHandler] active window changed: [0]
flutter: fetch id again at 0:id:494835479
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
```

**What did you expect to happen instead?**

Connect normally.

**How did you install `RustDesk`?**

GitHub release

**RustDesk version and environment**

 nightly 1.2.0

Same on both SteamOS running on SteamDeck(mine) and HoloISO running on any PC(test by @danyi).

**Comment by Kingtous** [comment]
I've noticed u run `rustdesk` with `sudo`. Are there any issues running `rustdesk` with non-root user?

**Comment by huangsijun17** [comment]
> I've noticed u run `rustdesk` with `sudo`. Are there any issues running `rustdesk` with non-root user?

Run with root or non-root, the result is the same.

**Comment by DrSchnagels** [comment]
May i ask how you got it running in the first place?
Which release did you install? The flathub one?
I cant even install the flathub one.
Thanks for your insight!

**Comment by huangsijun17** [comment]
> May i ask how you got it running in the first place? Which release did you install? The flathub one? I cant even install the flathub one. Thanks for your insight!

```
wget https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-0-x86_64.pkg.tar.zst
sudo pacman -U rustdesk-1.2.0-0-x86_64.pkg.tar.zst
```

Run the code and double-click to run after installation.
[nightly 1.2.0](https://github.com/rustdesk/rustdesk/issues/2335)

**Comment by DrSchnagels** [comment]
Maybe it doesnt run after a restart because of the fixed partition system the Steam Deck has?

**Comment by huangsijun17** [comment]
> Maybe it doesnt run after a restart because of the fixed partition system the Steam Deck has?

Both SteamOS and HoloISO. Holo isn't a fixed partition system.

**Comment by dayue1984** [comment]
Here I am trying to install rust desk on SteamOS with no luck, not working too.

**Comment by huangsijun17** [comment]
> Here I am trying to install rust desk on SteamOS with no luck, not working too.

Let me make sure, have you unlocked and reinstalled the base library? SteamDeck locks the root directory by default, and some lib libraries are incomplete. I am a Chinese user, and I used pacman to reinstall most of the libraries and files while repairing Chinese.

**Comment by dayue1984** [comment]
谢谢兄弟，我刚用pacman装的1.19，发现得要x11，然后就没再捣鼓。你搞定了吗？

**Comment by huangsijun17** [comment]
> 谢谢兄弟，我刚用pacman装的1.19，发现得要x11，然后就没再捣鼓。你搞定了吗？

1.1.9装不了，我之前报告过，被打了不再修复的的标签。1.2.0的测试版，在汉化后可以安装运行。但现在重启后无法连接。同样的，基于SteamOS衍生的HoloISO也是1.1.9装不了，1.2.0重启后连不上。

**Comment by rustdesk** [comment]
Steam OS is so special?

**Comment by dayue1984** [comment]
> > 谢谢兄弟，我刚用pacman装的1.19，发现得要x11，然后就没再捣鼓。你搞定了吗？
> 
> 1.1.9装不了，我之前报告过，被打了不再修复的的标签。1.2.0的测试版，在汉化后可以安装运行。但现在重启后无法连接。同样的，基于SteamOS衍生的HoloISO也是1.1.9装不了，1.2.0重启后连不上。

是不是服务没起来，试过解除文件系统只读了吗？sudo steamos-readonly disable

**Comment by huangsijun17** [comment]
> > > 谢谢兄弟，我刚用pacman装的1.19，发现得要x11，然后就没再捣鼓。你搞定了吗？
> > 
> > 
> > 1.1.9装不了，我之前报告过，被打了不再修复的的标签。1.2.0的测试版，在汉化后可以安装运行。但现在重启后无法连接。同样的，基于SteamOS衍生的HoloISO也是1.1.9装不了，1.2.0重启后连不上。
> 
> 是不是服务没起来，试过解除文件系统只读了吗？sudo steamos-readonly disable

不解锁，都装不进去。哪个服务？

**Comment by huangsijun17** [comment]
> Steam OS is so special?

You can install a [HoloISO](https://github.com/theVakhovskeIsTaken/holoiso) to experience it.

**Comment by pythoninthegrass** [comment]
> > May i ask how you got it running in the first place? Which release did you install? The flathub one? I cant even install the flathub one. Thanks for your insight!
> 
> ```
> wget https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-0-x86_64.pkg.tar.zst
> sudo pacman -U rustdesk-1.2.0-0-x86_64.pkg.tar.zst
> ```
> 
> Run the code and double-click to run after installation. [nightly 1.2.0](https://github.com/rustdesk/rustdesk/issues/2335)

Thanks for the hot tip! This got me up and running on the deck. Think with [rwfus](https://github.com/ValShaped/rwfus), shouldn't have any issues after a reboot.
