### ISSUE TITLE
Wrong Endsession code on Lunux Mint (Ubuntu based)

### ISSUE THREAD

**Issue by NoGAD-de** [rustdesk/rustdesk#2428]
Hello, when a connection to Linux Mint is terminated and at the same time the option to lock the PC is set, an incorrect key combination (Windows key + L) is sent to the system. But its CTRL + ALT + L.

Here are the relevant standard combinations:

Windows Windows + L
Ubuntu Ctrl + Alt + L
Linux Mint Ctrl + Alt + L

There is one more problem. If a custom key combination is set, the default combination will lead nowhere. (It's the same in my case)

Here it might be useful to read out the corresponding key combination from the system settings.

It is also possible to disable the function under the operating systems. Theoretically, a security leak would occur here.

...

Lock screen with alternative methods.

...

**How did you install `RustDesk`?**

GitHub release

---

1.1.9

**Comment by rustdesk** [comment]
not yet in master.
