### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by Toonym** [rustdesk/rustdesk#245]
Hello !

I would like to launch 2 instances of rustdesk in order to display screen n°1 on one screen and screen n°2 on a second screen.
But a click in the top bar on the screen1 or 2 change the display on the two instances.
Is there a way to make it work properly ?
Thx

**Comment by rustdesk** [comment]
Yes, that's the way RustDesk works

**Comment by Toonym** [comment]
Thank you for your answer !

But i don't understand, do you mean it's not possible to display to different screen with two instances ?  :-)

**Comment by rustdesk** [comment]
Not possible now, but PR welcome

**Comment by Toonym** [comment]
OK thank you. What does "PR" means ?

**Comment by rustdesk** [comment]
https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by rustdesk** [comment]
in the plan

**Comment by rustdesk** [comment]
#486
