### ISSUE TITLE
Thai keyboard layout not available

### ISSUE THREAD

**Issue by wannadrunk** [rustdesk/rustdesk#2451]
**Describe the bug you encountered:**
The Thai keyboard layout doesn't work on the remote. I am using both Linux Mint 21 Cinnamon/Windows 11 to remote to Windows 10/11. When I switch the keyboard layout from EN to TH. The icon in the taskbar changed to TH but I could not get Thai, it shows English only.
...

**What did you expect to happen instead?**
Thai characters when typed using a Thai keyboard layout.
...

**How did you install `RustDesk`?**
download from the GitHub release.

---

**RustDesk version and environment**
RustDesk v. 1.1.9 in Windows 10/11, Windows Server, and Linux Mint 21

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1547

**Comment by wannadrunk** [comment]
I did try the nightly build a few weeks back, but could not remember the number.

Here is what the Thai keyboard layout looks like.

![G6zVVW.png](https://sv1.picz.in.th/images/2022/12/06/G6zVVW.png)

**Comment by try2hack** [comment]
cannot switch language between EN-TH too.

**Comment by wannadrunk** [comment]
OK, I will try the nightly build and will update this issue.

**Comment by wannadrunk** [comment]
Yes, the nightly build on 20-Dec can switch the Thai keyboard layout.

But many keys missing, doesn't have the right character. I don't know how to explain it. Example, when I type `ก`, match to `d`, the cursor jump to the beginning of the line.

**Comment by wannadrunk** [comment]
I tried from Linux Mint to Windows 11 with the problem, kind of incorrect key mapping.

I will find the same platform and try again.

**Comment by rustdesk** [comment]
close as no response.
