### ISSUE TITLE
Laptop in deep sleep， can't connect

### ISSUE THREAD

**Issue by kingflyok** [rustdesk/rustdesk#2463]
**Describe the bug you encountered:**
When my laptop was in deep sleep, I couldn't connect to it through RustDesk

**What did you expect to happen instead?**
I hope we can solve this problem

**How did you install `RustDesk`?**
Windows portable version - rustdesk-1.1.9-windows_x64.zip

**RustDesk version and environment**
Windows 10 Or 11

**Comment by rustdesk** [comment]
infeasible

**Comment by kingflyok** [comment]
why infeasible？ bussiness software todesk isn't this bug！

**Comment by 21pages** [comment]
Todesk cannot be woken up, even in light sleep, note that it takes a while for the computer to go to sleep.
