### ISSUE TITLE
Rustdesk connection is not encrypted although a key is used

### ISSUE THREAD

**Issue by AlphaDE** [rustdesk/rustdesk#2472]
**Describe the bug you encountered:**

Running my own Rustdesk server with key (-k command) used by the server and all connected clients, the connection window always indicates that the connection is not encrypted (red shield symbol). 
The overall connection is fine, access without the key is rejected, key is supplied to hbbr and hbbs with the -k parameter.

**What did you expect to happen instead?**

Encrypted connection (green symbol).

**How did you install `RustDesk`?**

Github docker release

**RustDesk version and environment**

Rustdesk 1.1.9 on an Ubuntu 20.04.5 LTS under Proxmox.

**Comment by rustdesk** [comment]
#763
