### ISSUE TITLE
Mouse controll is not smooth and may loose some events after elevating

### ISSUE THREAD

**Issue by fufesou** [rustdesk/rustdesk#2479]
**Describe the bug you encountered:**

Mouse controll seems missing some events after elevating.

https://user-images.githubusercontent.com/13586388/206126181-81101af6-38e2-4091-a28b-05f7e8579524.mp4

...

**What did you expect to happen instead?**

Mouse controll should be good.

...

**How did you install `RustDesk`?**

Build from source.

---

**RustDesk version and environment**

Latest master build. both side Win10.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1547

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
debug version on slow machine, not found obvious delay in ipc calling.
