### ISSUE TITLE
how i can put all thing(such as ui and dll) in one exe?

### ISSUE THREAD

**Issue by GrapeLemon** [rustdesk/rustdesk#248]
WARNING:DOM: failed to load "D:/code/rust/rustdesk-master/target/debug/src/ui/index.html" file, error=3
i  got this when i use cmd to run 'rustdesk.exe'

i copy the ui to the WARNING destination, it can work right now!
but how can i put all the thing in one exe just like the installation? because i want to repackage a exe and embed it in my win app.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/240

**Comment by rustdesk** [comment]
> i try to run 'packfolder ui resources.rc -i ".html;.css;*.tis" -v "resources" -binary', it only generate a file which name is 'resources.rc', i still can not get what i want. please can you give me more details abourt how to finish my target? because i am a java developer and i am a beginner about this.

ask the contributor yourself.

**Comment by smartekIT** [comment]
same issue here, I created the file resources.rc using packfolder but the question is where should i place the file resources.rc so the build can include it in the final RustDesk.exe file ???

please help. thank you so much for such perfect project.
