### ISSUE TITLE
id服务器的域名如果是ddns的，每次更换会无法连接

### ISSUE THREAD

**Issue by jiaoting** [rustdesk/rustdesk#2494]
id服务器的域名如果是ddns的，每次更换会无法连接

**Comment by rustdesk** [comment]
duplicate

**Comment by rustdesk** [comment]
can we borrow your ddns for test? send me your email to info@rustdesk.com, @21pages  will contact you.

**Comment by rustdesk** [comment]
Or please checkout nightly build

**Comment by open-trade** [comment]
![e9a35ee77c6046ef6ab2a648b5afa79](https://user-images.githubusercontent.com/42061627/206685859-8a6fced0-76c1-4855-a058-7e3d7097110c.png)
