### ISSUE TITLE
Main Window Prevent PC from Turning off Screen or Going to Sleep

### ISSUE THREAD

**Issue by ForsakenRei** [rustdesk/rustdesk#2495]
**Describe the bug you encountered:**

When I have Rustdesk mian window openned(no matter normal window or minimized to taskbar), Windows 10 or 11 machine will not turn off screen/sleep after idle for certain time(Power setting in windows - how long turn off the screen/sleep). It seems the main window will keep the PC awake.

As long as I close the main window, everything is back to normal. I don't think it's a feature by design?

**What did you expect to happen instead?**

Even the main window is opened, PC should still behave as usual and turn off screen/go to sleep after the desired time of idling.

**How did you install `RustDesk`?**

Nightly build 1.2.0 installed

**RustDesk version and environment**
Tested on both Windows 10 and Windows 11. 
Self-hosted relay server.

**Comment by rustdesk** [comment]
expected.

**Comment by ForsakenRei** [comment]
> expected.

mind me asking why the designed behavior is this way?
I kinda understand the remote need to be awake from sleep otherwise it won't connect, but for preventing screen turn off part is not that necessary imo?

**Comment by imtrobin** [comment]
I noticed it too. My screen will not sleep when rustdesk window is opened, even when it is disconnected due to error.
