### ISSUE TITLE
Feature request : Centos RPM support

### ISSUE THREAD

**Issue by elkekou** [rustdesk/rustdesk#25]
Hi,

first of all thank you for your great job, finally a great simple product to kill teamviewer and respect privacy :).

I'm really not goot with compilation, and does not know rust :(.

Do you plan to compile RPM For Centos  7/8 ?

thank you

**Comment by rustdesk** [comment]
maybe in next release.

**Comment by elkekou** [comment]
ho it would be really great :).
thanks

**Comment by rustdesk** [comment]
Centos8 version is ready, I tested on fedora28. Sorry I can not provide Centos7 build, because RustDesk depends on sciter which does not support Centos7, I do not wanna pay money to buy sciter source code to build on Centos7.

https://github.com/rustdesk/rustdesk/releases
