### ISSUE TITLE
Nightly 1.2 - Some connections are freezing both client and remote systems.

### ISSUE THREAD

**Issue by emporiobviver** [rustdesk/rustdesk#2500]
**Describe the bug you encountered:**

Sometimes, when you connect to any remote, RustDesk causes massive lag and sometimes freezes the remote and client machine, you can't even use 'CTRL+ALT+DEL' to forcely close RustDesk.

RustDesk created new logs at 'check-hwcodec-config', i don't know if are related, but only logs from the day i have this problem have been stored.

**RustDesk version and environment**
Windows 10 Pro
Self Hosting server on Ubuntu 22.04LTS
Nightly 1.2

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
old nightly you used before worked fine?

**Comment by 21pages** [comment]
check-hwcodec-config is another process, could you uncheck this option and try again?
![1670639514468](https://user-images.githubusercontent.com/14891774/206824527-91789648-6134-48f0-bfe4-2aab914e3739.png)
