### ISSUE TITLE
Nightly build: File transfer wouldn't reposition when I press alpha keys on keyboard

### ISSUE THREAD

**Issue by mtelis** [rustdesk/rustdesk#2527]
Hello,

this trick works with Teamviewer, Anydesk and regular build of Rustdesk: when I hit a key on keyboard (for example, 'L'), file list in the file transfer window would position to files that start with 'L'.

Doesn't work in the nightly build, though.

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by rustdesk** [comment]
@Kingtous
