### ISSUE TITLE
Chat: Remote site clears local text on pressing Enter

### ISSUE THREAD

**Issue by larsen0815** [rustdesk/rustdesk#2528]
Steps to reproduce:
- Type in some text into the chat window, but don't send it
- Have the remote site enter and send some text

Result: Local text is removed

RustDesk 1.1.9
Windows 10 on local and remote

**Comment by rustdesk** [comment]
Try out nightly build please.

**Comment by larsen0815** [comment]
Chat now works as expected. Thx!

btw: When opening the chat window, the text field should have focus (didn't want to create an issue for this small cosmetic bug/feature).
