### ISSUE TITLE
Auto start service android on boot

### ISSUE THREAD

**Issue by itsfks** [rustdesk/rustdesk#2529]
I would like to request a feature to auto start the service on Android in case it is restarted or something similar.

Rustdesk was the best solution for remote control of indoor TV Boxes, but if the device is restarted, it cannot be remotely controlled again.

Is it possible to make some kind of function, or make some modification in the code so that the service starts automatically?
If you have that possibility and can tell how to do it, I would greatly appreciate it.

**Comment by rustdesk** [comment]
duplicate

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3322

**Comment by rustdesk** [comment]
Please try out it tomorrow, just added.
