### ISSUE TITLE
Ruskdesk doesn't work properly in Win7 32BIT

### ISSUE THREAD

**Issue by Sanysoft** [rustdesk/rustdesk#2531]
when you try to connect, an error occurs 'An invalid argument was supplied. (os error 10022)'

**Comment by Tzwcard** [comment]
same issue, any solution?

**Comment by grummbeer** [comment]
ralated to #2833 #789

**Comment by rustdesk** [comment]
Close as wontfix, phasing out official win7 support.

**Comment by vipka1n** [comment]
> Close as wontfix, phasing out official win7 support.

Installing Sp1 solves the problem

**Comment by vipka1n** [comment]
> when you try to connect, an error occurs 'An invalid argument was supplied. (os error 10022)'

Installing Sp1 solves the problem
