### ISSUE TITLE
ID doesn't exist

### ISSUE THREAD

**Issue by Akazhiel** [rustdesk/rustdesk#2532]
**Describe the bug you encountered:**
When attempting to connect to my work PC that's connected to my workplace's network, from my home PC I get ID doesn't exist. My remote PC is Ubuntu 20.04 and my home PC is Windows 10.
...

**What did you expect to happen instead?**
I expected the connection to go through and prompt me for the password to connect.
...

**How did you install `RustDesk`?**
I downloaded both the .exe and the .deb from the website. And the .deb was installed according to the guidelines in the website.

---

**RustDesk version and environment**
RustDesk version 1.1.9.
I'm running RustDesk on an Ubuntu 20.04 as mentioned above which is the remote machine to which I want to connect and a windows 10 machine which is the one I'm connecting from. Both are on different networks.

**Comment by bigretromike** [comment]
- did you edit relay server address now or before (as its same configuration file) 
- is your work not filtering IP trafic? maybe they are capturing traffic and not allowing for any remote access pass thru ? that would explain why your PC dont see the ID  (just theory)

**Comment by rustdesk** [comment]
Server maintanence issue.
