### ISSUE TITLE
Protocol not available (os error 92)

### ISSUE THREAD

**Issue by xhy1999** [rustdesk/rustdesk#2539]
- When I try to use RustDesk to control Windows PC on my Android phone, RustDesk displays `Protocol not available (os error 92)`.
- The phone will be in the 'Ready' state after the service is started; However, after the attempt to control the PC fails, 'Not ready, please check the network connection' will be displayed.
- After the service is started, the app interface will flicker, and will not flicker after returning to the main screen.
- When the computer tries to control the phone, it will prompt the connection failure after waiting for a period of time.

**Server:**
- CentOS 7.9.2009 x86_64
  - [rustdesk-server-linux-amd64](https://github.com/rustdesk/rustdesk-server/releases/download/1.1.6-2/rustdesk-server-linux-amd64.zip)

**PC:**
- Windows 10 家庭中文版
  - 22H2
  - 19045.2251
- RustDesk 1.1.9

**Android:**
- Phone Model: Xiaomi Mi 3W 2014215 (cancro)
- OS: [MK100.0-cancro-221019-RELEASE](https://download.mokeedev.com/cancro.html)
- RustDesk 1.1.10-1

Both Android and PC are downloaded on the [Official Website](https://rustdesk.com/zh/).

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/152

**Comment by xhy1999** [comment]
That phone uses ipv4. In fact, it does not support ipv6.
