### ISSUE TITLE
Voice interaction function

### ISSUE THREAD

**Issue by Fowindy** [rustdesk/rustdesk#254]
At present, there is an imperfect place in the software, the controlled person cannot hear the voice of the controller, and in terms of voice interaction, the controller can only hear the voice of the controlled person.Hope to improve this voice interaction function, thank you

**Comment by rustdesk** [comment]
Understood.

**Comment by Fowindy** [comment]
When I remotely operate my colleague's computer, I can hear my colleague's voice, but my colleague can't hear me. Unable to conduct voice interaction during manipulation; Voice interaction must now be realized with wechat voice during manipulation

> For help desk?

When I remotely operate my colleague's computer, I can hear my colleague's voice, but my colleague can't hear me. Unable to conduct voice interaction during manipulation; Voice interaction must now be realized with wechat voice during manipulation

**Comment by Fowindy** [comment]
Is the function of two-way voice interaction realized? I saw you close, but I downloaded it. It seems that only the voice of the accused computer can hear it, and vice versa

**Comment by rustdesk** [comment]
merged https://github.com/rustdesk/rustdesk/pull/2981
