### ISSUE TITLE
Linux host: Can't use full qwerz keyboard

### ISSUE THREAD

**Issue by xzipyx** [rustdesk/rustdesk#2542]
Hey!

I noticed that I can't use symbols on qwertz keyboard that use hotkeys i.e. ctrl + alt + q (@) or ctrl + alt (€) on Linux (Rustdesk host X11)
it will result in a capital Q or E instead.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1547

**Comment by fufesou** [comment]
@xzipyx Hi, which rustdesk version did you use? If you are using the nightly build, please choose "Map mode".

<img width="235" alt="20230104201351" src="https://user-images.githubusercontent.com/13586388/210940361-83e55459-65ec-4d5c-8f4d-c9db8c694bbb.png">


1. Legacy mode. Characters are sent. The input is based on local keyboard and local input method.
2. Map mode. Positions of physical keyboard are sent. The input is based on local keyboard and remote input method.

For now, "Legacy mode" has some problems.

**Comment by fufesou** [comment]
@xzipyx Hi, which rustdesk version did you use? If you are using the nightly build, please choose "Map mode".

<img width="235" alt="20230104201351" src="https://user-images.githubusercontent.com/13586388/210940361-83e55459-65ec-4d5c-8f4d-c9db8c694bbb.png">


1. Legacy mode. Characters are sent. The input is based on local keyboard and local input method.
2. Map mode. Positions of physical keyboard are sent. The input is based on local keyboard and remote input method.

For now, "Legacy mode" has some problems.

**Comment by xzipyx** [comment]
> @xzipyx Hi, which rustdesk version did you use? If you are using the nightly build, please choose "Map mode".
> 
> <img alt="20230104201351" width="235" src="https://user-images.githubusercontent.com/13586388/210940361-83e55459-65ec-4d5c-8f4d-c9db8c694bbb.png">
> 
>     1. Legacy mode. Characters are sent. The input is based on local keyboard and local input method.
> 
>     2. Map mode. Positions of physical keyboard are sent. The input is based on local keyboard and remote input method.
> 
> 
> For now, "Legacy mode" has some problems.

Hey, thank you, I switched to the nightly version and now everything works fine!
