### ISSUE TITLE
Nightly build (Linux): RustDesk (flutter) crash upon establish connection

### ISSUE THREAD

**Issue by 7th-fret** [rustdesk/rustdesk#2543]
**Describe the bug you encountered:**

Upon establish connection to client, remote image remains black while waiting for image, it freeze and after a few moments Rustdesk crash.
Rarely it gets connected and works for a little but after a few moments it freeze and then crash  
Enabling or disabling hardware codec makes no difference.
I have tried precompiled nightly and custom build (flutter) with no difference.
With custom sciter build, it works OK

**How did you install `RustDesk`?**

Nightly, rustdesk-1.2.0-0-x86_64.pkg.tar.zst
Custom build (flutter)

**RustDesk version and environment**

Arch Linux x64, fully updated
Xfce4
NVidia with nouveau driver

**Comment by 21pages** [comment]
#2523 
both Nouveau driver

**Comment by rustdesk** [comment]
Since you can custom build, can you help debug? @21pages can help you in any way.

**Comment by 21pages** [comment]
> I have tried precompiled nightly and custom build (flutter) with no difference.

Could you try custom build sciter?
just `cargo run`

**Comment by 21pages** [comment]
> With custom sciter build, it works OK

Did you add hwcodec feature?

**Comment by 7th-fret** [comment]
> hwcodec

Just tested.
With new custom sciter build with enabled hwcodec feature works OK

**Comment by rustdesk** [comment]
> OK

Remote side? Can you confirm it is hard codec from the local side (checkout menubar, there are something which can show it)?

**Comment by 7th-fret** [comment]
> Remote side? Can you confirm if it is hard codec from the local side (check out menubar, there are something which can show it)?

Remote side's installed version is nightly (01/12/2022) and tested both enabled/disabled hwcodec.
Also i tried update remote side's with latest nightly, and tested again both enabled/disabled hwcodec , with no luck.

At this time, i have the problem only in one of my office PC, and i can't reproduce it on any other PCs.

Tomorrow, when i return to my office, i'll try to temporary change the NVidia card , as i suspect that this is maybe a hardware related problem.

**Comment by rustdesk** [comment]
> 01/12/2022

Please try out new nightly build, enable/disable hwcodec did not take effect in your version, https://github.com/rustdesk/rustdesk/pull/2530

**Comment by rustdesk** [comment]
@7th-fret  please try out https://github.com/rustdesk/rustdesk/discussions/2523#discussioncomment-4378044

**Comment by rustdesk** [comment]
We may need to use vp9 by default in Linux before we get a fix.

**Comment by 7th-fret** [comment]
> Please try out latest nightly build

Tried, makes no difference.



> Did you add hwcodec feature for custom build flutter version?

Yes, it was compiled with hwcodec feature




Also i have to say that the problematic PC is old, with an old nvidia GT220.
I tried move to proprietary NVidia driver, but then rustdesk didn't run at all, and i got error about GL_VERSION
"Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed"

A simple research points me that there is a NVidia bug with flutter,
and the recommended workaround is to go with nouveau driver
[https://github.com/fermat28/flutter_shell_gpu_surface_gl_delegate.cc_error_fix](url)

Went back to nouveau driver, and had the idea to run rustdesk with forced software acceleration via env
LIBGL_ALWAYS_SOFTWARE=true ./rustdesk
this made the difference, despite the higher CPU usage, worked and never got a crash

**Comment by rustdesk** [comment]
https://github.com/flutter/flutter/issues/85460

**Comment by rustdesk** [comment]
> LIBGL_ALWAYS_SOFTWARE=true ./rustdesk
the connection work?

**Comment by 7th-fret** [comment]
> does the connection work?

Yes, connection worked
