### ISSUE TITLE
some character doesn't work properly :example â ê Ë french characters with keyboard combinaisons.

### ISSUE THREAD

**Issue by mdelag13** [rustdesk/rustdesk#2545]
Hi,

With last nightly build  1.2.0_x86_64 Windows.exe ,  through a rustdesk server 1.1.9  , we can't use specials french caracters as  â ^  Ë (minuscule)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1547

**Comment by rustdesk** [comment]
try nightly build on both side.

**Comment by rustdesk** [comment]
BTW, we are still refactoring our keyboard.

**Comment by mdelag13** [comment]
Yes, with last build 1.2.0 windows x64  on both sides ,  its necessary to activate map mode keyboard on the top , in the options of rustdesk while the remote sessions.

thx you :)   juste need a similary install with ps1  same like stable version .
