### ISSUE TITLE
Turkish Q Keyboard we push 'i' letter rustdesk write 'ı'

### ISSUE THREAD

**Issue by apieiron** [rustdesk/rustdesk#2547]
Hello,

We used 1.1.9 and 1.2.0 nightly both build for testing. When we connect to other client and using Turkish Q keyboard. When we push 'i' letter rustdesk write 'ı' letter.  Can you fix this problem. 

Thank you this great aplication.

Have a nice days.

**Comment by rustdesk** [comment]
#1547

**Comment by fufesou** [comment]
@apieiron Thanks for your report.
What're the OS on both sides?

Can you please try the nightly build, with "Map mode"?

<img width="235" alt="20230104201351" src="https://user-images.githubusercontent.com/13586388/210715578-13b62bb1-7e67-4ff5-8ad5-4afa34d4740d.png">

**Comment by rustdesk** [comment]
close as no repsonse.

**Comment by engerex** [comment]
This problem continues.

![image](https://user-images.githubusercontent.com/5686053/216812061-17148557-9c94-4edc-ab17-2dd7318aa1b4.png)

@fufesou Where is this option?

RustDesk 1.1.9
Windows 11 Pro & Windows 11 Pro

**Comment by rustdesk** [comment]
Try out nightly build please.

**Comment by fufesou** [comment]
@engerex Hi, did you use the ngihtly build on both sides?

**Comment by engerex** [comment]
@fufesou yes, I used nightly build on both sides. If the remote pc is 1.1.9, the connection is not established.

**Comment by engerex** [comment]
Faulty keys

![image](https://user-images.githubusercontent.com/5686053/218164553-db7553e0-efe9-4e8f-b161-6d775832eb48.png)

it says : ı I
should be : i İ

it says : " é <
should be : < > |

(respectively)

**Comment by fufesou** [comment]
Both nightly should show "Map mode" option. I'll test later.

**Comment by fufesou** [comment]
@engerex Hi, I've tested and read the code.
Your remote rustdesk may be 1.1.9. Please confirm and tell back.

BTW, "Legacy mode" does not currently work well. I'm developing another keyboard mode.

For "Map mode", input should behave like a local keyboard connected to the remote computer.
https://github.com/rustdesk/rustdesk/issues/2549#issuecomment-1365929440
https://github.com/rustdesk/rustdesk/issues/2549#issuecomment-1373119456

**Comment by engerex** [comment]
Now I tested it again. If 1.2.0 on one computer and 1.1.9 (remote) on the other computer, I get the following error message: ID is incorrect.

I found the source of the problem. Even if the keyboard language of both computers is Turkish, this problem occurs if Windows English is installed on one of the computers.
It doesn't matter which one is the remote computer.

PC1 : Windows 11 Pro Turkish, Windows display language is Turkish, Turkish keyboard.
PC2 : Windows 11 Pro English, Windows display language is English, Turkish keyboard.

**Comment by rustdesk** [comment]
1.2 on both side please

**Comment by msahinciftci** [comment]
Are there any solution for this. It's a great app but can't be used for Turkish keyboard because of this.

**Comment by fufesou** [comment]
@msahinciftci Did you use the latest nightly build, with the "Map mode"?

![image](https://github.com/rustdesk/rustdesk/assets/13586388/b78e32d4-302d-4273-b5d6-17cd9094c06e)


I've tested Turkish keyboard layout, both Win and set Turkish input method.

The outputs are the same.

```
"1234567890*-
qwertyuıopğü
asdfghjklşi,
<zxcvbnmöç.
é!'^+%&/()=?_
QWERTYUIOPĞÜ
ASDFGHJKLŞİ;
>ZXCVBNMÖÇ:
```


https://github.com/rustdesk/rustdesk/assets/13586388/0b9dcd59-77e5-439a-ba2a-194aaeefb5cc

**Comment by msahinciftci** [comment]
> @msahinciftci Did you use the latest nightly build, with the "Map mode"?
> 
> ![image](https://user-images.githubusercontent.com/13586388/244982480-b78e32d4-302d-4273-b5d6-17cd9094c06e.png)
> 
> I've tested Turkish keyboard layout, both Win and set Turkish input method.
> 
> The outputs are the same.
> 
> ```
> "1234567890*-
> qwertyuıopğü
> asdfghjklşi,
> <zxcvbnmöç.
> é!'^+%&/()=?_
> QWERTYUIOPĞÜ
> ASDFGHJKLŞİ;
> >ZXCVBNMÖÇ:
> ```
> 
>  xdf.mp4

Yes it worked, thanks. When will this be released as a stable feature?
