### ISSUE TITLE
problem with different kayboard language layout  (keyboard translation)

### ISSUE THREAD

**Issue by Darkmagister** [rustdesk/rustdesk#2549]
**Describe the bug you encountered:**

i'm using rustdesk from linux mint with us keyboard, i'm connecting to a windows machine with IT keyboard layout set, i get some really strange behavior with the key that have different function in the two layout
for example if i press the key **=** on my us keyboard i got **ì** in map mode or  **0** in mode legacy
(i've tried the 1.2.0 nightly also)

**What did you expect to happen instead?**

i was expecting to write = if i press = not to be converted in the same key position or similar

**How did you install `RustDesk`?**

from github release

**RustDesk version and environment**

1.1.9 and 1.2.0 nightly (even with the two keyboard mode it doen't work as i was expecting)

**Comment by rustdesk** [comment]
#1547

**Comment by fufesou** [comment]
@Darkmagister Hi, would you please try again with the latest ngihtly build. It may have been fixed now.
Choose **Map Mode**, the legacy mode has not been fixed.

**Comment by Darkmagister** [comment]
i just tried again ... and same behavior as before,
in map mode i press on my english keyboard (linux)  -_ key and on my other pc with italian map (windows is mapped like that) i get '? that is the same key in the 2 different layout same physical key but i get the layout of the machine that i'm connected to instead of the one on my local machine

it's difficult to remember the layout of different language i think the best way is i to get the character from the local machine to be sent to the remote one ...

**Comment by fufesou** [comment]
@Darkmagister Thanks for your test and replay.
But I don't think so send character to the remote is a good way.
When connected to a remote computer, input should behave like a local keyboard connected to the remote computer. The layout of the local keyboard and the system input of the remote computer should be used.

**Comment by fufesou** [comment]
@Darkmagister Yes, you're right on some cases.
1. Send characters. The "Legacy mode" (But not work well for now).
2. Send code according to keyboard physical position. The "Map mode".

**Comment by rustdesk** [comment]
translation mode is ready

**Comment by glundby** [comment]
Remote keyboard 'norwegian' on target ubuntu shows like from US ASCI key positions. When target is a Windows machine the keys shows like 'norwegian' as they should. Using VNC Viewer the ubuntu machines shows 'norwegian' as they should! øæå....
