### ISSUE TITLE
Audio - local microphone transfer to remote

### ISSUE THREAD

**Issue by TheShadowAngel** [rustdesk/rustdesk#2558]
**New feature.**
Please, think about add function to transfer local sound input to remote device.

**Case of use**
We use SIP-client on remote PC, VoIP-server work only in local network.
The user connects to their remote PC and can use their local microphone to make calls on the remote PC using the installed SIP-clien.

**Comment by rustdesk** [comment]
duplidate

**Comment by MaKaNu** [comment]
duplicate of which issue?
