### ISSUE TITLE
RustDesk.exe looping on uninstall registry keys

### ISSUE THREAD

**Issue by 0x100001** [rustdesk/rustdesk#2562]
**Describe the bug you encountered:**

While inspecting rustdesk.exe with procmon, I noticed the behaviour that the rustdesk.exe continuously accesses the same registry keys. 

**What did you expect to happen instead?**

Accessing it only if needed. The current behaviour does not look normal.

**How did you install `RustDesk`?**

From the website: rustdesk-1.1.9-windows_x64

Version: 1.1.9
OS: Windows 11 21h2 (Build 22000.1281)

You can reproduce it with the following steps:
1. Install rustdesk.
2. Download procmon and execute it. https://learn.microsoft.com/en-us/sysinternals/downloads/procmon)
3. Set procmon filter to process name -> RustDesk.exe -> include.
4. Look for the following contents
`3:54:11.5938657 PM	RustDesk.exe	7396	RegOpenKey	HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk	SUCCESS	Desired Access: Read`
`3:54:11.5938844 PM	RustDesk.exe	7396	RegQueryValue	HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk\InstallLocation	SUCCESS	Type: REG_SZ, Length: 52, Data: C:\Program Files\RustDesk`
`3:54:11.5939005 PM	RustDesk.exe	7396	RegCloseKey	HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk	SUCCESS`

**Comment by rustdesk** [comment]
Our code does not have this behavior.

**Comment by rustdesk** [comment]
@21pages could you check where calls https://github.com/rustdesk/rustdesk/blob/master/src/platform/windows.rs#L1328 repeatly?

**Comment by rustdesk** [comment]
> continuously

how often?

**Comment by rustdesk** [comment]
> 4\. `3:54:11.5938657 PM	RustDesk.exe	7396	RegOpenKey	HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk	SUCCESS	Desired Access: Read`
>     `3:54:11.5938844 PM	RustDesk.exe	7396	RegQueryValue	HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk\InstallLocation	SUCCESS	Type: REG_SZ, Length: 52, Data: C:\Program Files\RustDesk`
>     `3:54:11.5939005 PM	RustDesk.exe	7396	RegCloseKey	HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk	SUCCESS`

not the same https://github.com/rustdesk/rustdesk/blob/master/src/platform/windows.rs#L1358

@21pages no need investigate
