### ISSUE TITLE
the image keeps breaking

### ISSUE THREAD

**Issue by wep777** [rustdesk/rustdesk#2563]
**Describe the bug you encountered:**

hello, the image keeps breaking
 - from Fedora 37 to Fedora 37
 - direct connect
 - trying 1.2.0 ver - same result

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

install from rpm file

---

**RustDesk version and environment**

1.1.9
1.2.0

from Fedora 37 Gnome to Fedora 37 Gnome using Rustdesk

see my video

https://www.youtube.com/watch?v=rmSlQWU2NvA

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
Try out latest nightly build, we have done many things related to image. will reopen it sillt not work
