### ISSUE TITLE
Rustdesk is always running even if I disable its opening at startup

### ISSUE THREAD

**Issue by albertopasqualetto** [rustdesk/rustdesk#2564]
**Describe the bug you encountered:**

Once Rustdesk is installed it is always running.
Even if I disabled the open at startup from Windows' task manager.

![image](https://user-images.githubusercontent.com/39854348/207929190-9ca7404f-9830-4397-ad01-b9251a840c86.png)

If I disable the service from inside Rustdesk, then it does not uses the network, but it remains active in background.

**What did you expect to happen instead?**

To have an option to run only if manually opened.

**How did you install `RustDesk`?**

Github installable release

---

**RustDesk version and environment**

1.19
Windows 11

**Comment by rustdesk** [comment]
stop the system service

**Comment by albertopasqualetto** [comment]
Ok, but that should not be a normal behaviour...
