### ISSUE TITLE
UI broken on windows 10

### ISSUE THREAD

**Issue by fangdaoyou** [rustdesk/rustdesk#2571]
When I use rustdesk on windows 10, I can't get into the ui interface.

Rustdesk does create a window, but it can't be shown in the screen, like this:
![image](https://user-images.githubusercontent.com/54983082/208109442-050b18e5-c9c2-4da6-a4d6-2246472a0afb.png)

I install the lasted 1.1.9 rustdesk on windows 10.

**Comment by rustdesk** [comment]
duplicate
