### ISSUE TITLE
where is appimage?

### ISSUE THREAD

**Issue by newyorkthink** [rustdesk/rustdesk#2578]

**Comment by rustdesk** [comment]
do not support anymore.

**Comment by rustdesk** [comment]
https://twitter.com/rustdesk

**Comment by cooperbang** [comment]
> it is back. https://twitter.com/rustdesk

In Fedora 37 (using Wayland) it only works if you start the Appimage in XWayland.
--> `GDK_BACKEND=x11 ./rustdesk-1.2.0-x86_64.AppImage`

When trying to start in Wayland it fails with Error 
`(rustdesk:8523): GLib-GIO-ERROR **: 16:23:28.318: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
`

**Comment by Kingtous** [comment]
> > it is back. https://twitter.com/rustdesk
> 
> In Fedora 37 (using Wayland) it only works if you start the Appimage in XWayland. --> `GDK_BACKEND=x11 ./rustdesk-1.2.0-x86_64.AppImage`
> 
> When trying to start in Wayland it fails with Error `(rustdesk:8523): GLib-GIO-ERROR **: 16:23:28.318: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing' `

Seems there're some issues with `wayland` and flutter when in the AppImage env. 

https://github.com/Ultimaker/Cura/issues/12776

Maybe we can add `GDK_BACKEND=x11` in our desktop files.
