### ISSUE TITLE
Android http API server problem

### ISSUE THREAD

**Issue by jboban** [rustdesk/rustdesk#2587]
Could not enter any http (not https) API server. The same server could be used on Windows platform. Have tried with stable 1.1.9 version and nightly build 1.2.0.

![Screenshot_20221217_165734](https://user-images.githubusercontent.com/11806707/208250679-4a981a03-a7ca-4a0a-98f5-2ad648a2fb49.png)
![Screenshot_20221217_170030](https://user-images.githubusercontent.com/11806707/208250699-14d924c3-7fc3-4601-8d35-d75aeceba663.png)

**Comment by jboban** [comment]
What is wrong with port here, please? API server is up and running.

**Comment by rustdesk** [comment]
@Heap-Hop
