### ISSUE TITLE
nightly build reconnect repeatly after keybboard input

### ISSUE THREAD

**Issue by coolxy** [rustdesk/rustdesk#2600]
**Describe the bug you encountered:**
On version 1.2. When I remotely connect to the rustdesk computer and enter through the keyboard, it prompts that the connection is closed by the other party, and then connects again after disconnecting, and disconnects again when typing repeatedly, and so on. So I installed back to version 1.1.9.
在版本1.2上。当我远程连接到rustdesk电脑，通过键盘输入时，提示连接被对方关闭，断开后又连接上，重复输入时又断开，如此反复。所以我又安装回1.1.9版本了。
...

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

**Comment by rustdesk** [comment]
@fufesou it seems keyboard bug

**Comment by fufesou** [comment]
@coolxy Thanks for your feedback. Are the both sides Win? And both 1.2.0 nightly?

https://user-images.githubusercontent.com/13586388/208353665-dc63775c-405e-4c9d-8833-f081fddc5291.mp4

**Comment by fufesou** [comment]
@coolxy Are there some special keys or operations you've typed?

I've tested today's nightly build. The following connections are fine with keyboard input.
1. Win --> Win, Win --> Ubuntu, Win --> Mac OS
2. Mac OS --> Win, Mac OS --> Ubuntu
3. Ubuntu --> Win, Ubuntu --> MacOS

**Comment by coolxy** [comment]
@fufesou  @rustdesk 
When I reinstall version 1.2, the previous error will no longer be repeated, before WIN->linux(deepin), Andriod->linux(deepin) will have an error

**Comment by coolxy** [comment]
@fufesou @rustdesk 
Installing the new packaged version works fine now, thanks
