### ISSUE TITLE
Cant't change icons

### ISSUE THREAD

**Issue by djpaulinho07** [rustdesk/rustdesk#2603]
Dear friends
I'm compiling a custom version but I can't change the main window icon. It already replaces all the icon files of the project but the original icon continues to appear. Does anyone have an idea what I can do?
![issue](https://user-images.githubusercontent.com/78569619/208413618-6bfc90e6-a779-4d1f-bf23-b49bad84cc57.png)

**Comment by rustdesk** [comment]
#763

**Comment by djpaulinho07** [comment]
Useless tutorial for the proposed doubt. But I got the message about me having to teach myself. Very friendly.
