### ISSUE TITLE
Rustdesk Client {Ubuntu 22.04} keyboard input not received on rustdesk host {Windows 10}

### ISSUE THREAD

**Issue by Marthaarman** [rustdesk/rustdesk#2604]
**Describe the bug you encountered:**
When I type anything, like text in the host (remote) device's start menu, nothing is printed on the remote machine.
Keyboard input from the machine taking over the remote is not received or processed.
Permissions are enabled and input is not blocked by a setting. (I assume?)
Does not work on any of the remote machines (all windows 10)

**What did you expect to happen instead?**
when I have a notepad open on the remote machine and I type on my local machine, text should appear on the remote's notepad.
-> Any keystrokes on the local machine should be repeated on the remote machine. 

**How did you install `RustDesk`?**
Remote: windows client via the website
Local: ubuntu client via the website

---

**RustDesk version and environment**
local: ubuntu 22.04 -> version 1.1.9
remote: windows 10 32bit

**Comment by michag86** [comment]
Did you use wayland or x server?
have you tested switching keyboard from compatibility mode to map mode?

**Comment by Marthaarman** [comment]
> Did you use wayland or x server? Ubuntu 22.04 uses wayland as default

ehh... I'm not quite sure but I installed rustdesk client using this tutorial:
https://www.linuxshelltips.com/install-rustdesk-remote-desktop-ubuntu/



> Ubuntu 22.04 uses wayland as default, this can be changed before login on the gear in the right bottom corner on the login screen.

I cannot find either such a "login" nor a gear on the right bottom of the screen

![Screenshot from 2022-12-21 12-32-09](https://user-images.githubusercontent.com/9247891/208895862-d38f7221-4fe4-477f-b138-4b9cf3d578d5.png)

**Comment by TheGeka** [comment]
I am running into the same issue from Kubuntu 22.10 with X11. The mouse works just fine but keystrokes are not being transmitted
RustDesk Version: 1.1.9
Targets:
- MacOs Monterey 12.6.1
  RustDesk Version: 1.1.9
- Windows 10 21H2
  RustDesk Version: 1.1.9
Works just fine from Windows to Mac and the other way around

**Comment by timonoj** [comment]
Same here.
Host: KDE Neon 5.26 (Ubuntu 22.04), X11
Client: KDE Neon 5.26, Wayland.
Mouse works around no problem, but input from the keyboard is not received. I had to unlock the screen by using the Rustdesk OS password option (because nothing actually typed onto the screen is received), and even after that, only the mouse works.

**Comment by zveronline** [comment]
same problem on nightly build, only for ubuntu 22.04. keyboad input not work.

**Comment by Marthaarman** [comment]
> upd: there were different nightly versions.

What does that mean for us, the users? Or is that not a fix when reinstall or update?

**Comment by zveronline** [comment]
> > upd: there were different nightly versions.
> 
> What does that mean for us, the users? Or is that not a fix when reinstall or update?

everything works relatively well when the night versions are the same within a day

**Comment by Marthaarman** [comment]
Solution:



> Did you use wayland or x server? Ubuntu 22.04 uses wayland as default, this can be changed before login on the gear in the right bottom corner on the login screen.

This actually solves it but I didn't know what was meant with "login screen", it is the login screen of ubuntu itself which is mentioned. However, in 22.04 there is no longer a gear icon on that screen. The workaround is:

`sudo nano /etc/gdm3/custom.conf`

change (in the part that says [daemon]

`#WaylandEnable=false` to `WaylandEnable=false`

Now reboot and rustdesk's keyboard should work.

source: https://rustdesk.com/docs/en/manual/linux/

Myself also purged rustdesk and did a new install according to the link above but I think that should not be required.

**Comment by olmec-dolithe** [comment]
I understand the bit about wayland (although I haven't tried this) but what is meant by switching keyboard from compatibility mode to map mode?
