### ISSUE TITLE
Automated Client Discovery on LAN

### ISSUE THREAD

**Issue by fdbryant3** [rustdesk/rustdesk#261]
RustDesk should be able to automatically discover other Rustdesk clients on a local area network.  Settings could include a flag to hide a client from automated discovery.

**Comment by rustdesk** [comment]
PR welcome

**Comment by fy2462** [comment]
https://github.com/rustdesk/rustdesk/pull/337

**Comment by laeo** [comment]
Why not use mDNS to implement client discovery? It is most commonly way to accomplish this.

**Comment by rustdesk** [comment]
> Why not use mDNS to implement client discovery? It is most commonly way to accomplish this.

Can you help? we have an implementation, but seem not good. https://github.com/rustdesk/rustdesk/issues/845

**Comment by fufesou** [comment]
> Why not use mDNS to implement client discovery? It is most commonly way to accomplish this.

mDNS seems not suitable for RustDesk discovery.
mDNS response only supplies basic net informations, like ip, type, ttl. No more custom infomations.

Using mDNS, we need two steps:
1. query IPs
2. query peer infomations.

**Comment by laeo** [comment]
> 

I'v write a bit code to accomplish this, because i do not have another computer, so i can't confirm it works properly. But if you are interesting you can try my [code](https://github.com/laeo/rustdesk/tree/feature/mdns). Im totally new to rust, any suggestion about my code are welcome.

**Comment by rustdesk** [comment]
> you can try my [code](https://github.com/laeo/rustdesk/tree/feature/mdns)

Good job, @fufesou can you test?

**Comment by fufesou** [comment]
> > > Why not use mDNS to implement client discovery? It is most commonly way to accomplish this.
> > 
> > 
> > mDNS seems not suitable for RustDesk discovery. mDNS response only supplies basic net informations, like ip, type, ttl. No more custom infomations.
> > Using mDNS, we need two steps:
> > 
> > 1. query IPs
> > 2. query peer infomations.
> 
> I'v write a bit code to accomplish this, because i do not have another computer, so i can't confirm it works properly. But if you are interesting you can try my [code](https://github.com/laeo/rustdesk/tree/feature/mdns). Im totally new to rust, any suggestion about my code are welcome.

I've read your code, it seems good to work. Not tested yet.
It was my mistake to think that DNS-format message does not contain additional informations.

**Comment by laeo** [comment]
> > > > Why not use mDNS to implement client discovery? It is most commonly way to accomplish this.
> > > 
> > > 
> > > mDNS seems not suitable for RustDesk discovery. mDNS response only supplies basic net informations, like ip, type, ttl. No more custom infomations.
> > > Using mDNS, we need two steps:
> > > 
> > > 1. query IPs
> > > 2. query peer infomations.
> > 
> > 
> > I'v write a bit code to accomplish this, because i do not have another computer, so i can't confirm it works properly. But if you are interesting you can try my [code](https://github.com/laeo/rustdesk/tree/feature/mdns). Im totally new to rust, any suggestion about my code are welcome.
> 
> I've read your code, it seems good to work. Not tested yet. It was my mistake to think that DNS-format message does not contain additional informations.

How you guys test this project? It seems can't cross compile, otherwise i can build a Windows version and let my friends to help to test the code, so i can make my first PR in Rust world!

**Comment by fufesou** [comment]
@laeo What's the problem. You can send me an email (shuanglongchen@yeah.net) , and we can exchange wechat accounts.

**Comment by fufesou** [comment]
> But if you are interesting you can try my [code](https://github.com/laeo/rustdesk/tree/feature/mdns). Im totally new to rust, any suggestion about my code are welcome.

I've tested [mdns-sd](https://crates.io/crates/mdns-sd). There're two problems:
1. It's listener socket does not work well on multiple net adapter. Binding to 0.0.0.0 seems to choose a random adapter.
2. Multiple rustdesk instance use the same server-name. The register service stores [only one](https://github.com/keepsimple1/mdns-sd/blob/29dddf57234e8a75e731ee7d575fe8c5b9a9ffa6/src/lib.rs#L1092). 

We need to fix the problems.

**Comment by rustdesk** [comment]
> mdns-sd

Actively maintained lately, https://github.com/keepsimple1/mdns-sd/issues/22

**Comment by laeo** [comment]
> > But if you are interesting you can try my [code](https://github.com/laeo/rustdesk/tree/feature/mdns). Im totally new to rust, any suggestion about my code are welcome.
> 
> I've tested [mdns-sd](https://crates.io/crates/mdns-sd). There're two problems:
> 
> 1. It's listener socket does not work well on multiple net adapter. Binding to 0.0.0.0 seems to choose a random adapter.
> 2. Multiple rustdesk instance use the same server-name. The register service stores [only one](https://github.com/keepsimple1/mdns-sd/blob/29dddf57234e8a75e731ee7d575fe8c5b9a9ffa6/src/lib.rs#L1092).
> 
> We need to fix the problems.

1. The author had actively changed to bind all interfaces, because of [this](https://github.com/keepsimple1/mdns-sd/pull/36) PR.
2. If we have to support multiple rustdesk instance on same machine, maybe we can use `instance id` as [instance name](https://github.com/keepsimple1/mdns-sd/blob/b562184ee82000d629e7ed63bfe79a50667e2ef9/examples/register.rs#L30) instead of hostname.

**Comment by rustdesk** [comment]
> 2\. multiple rustdesk instance

No plan to support yet.

**Comment by timschloe** [comment]
> > 2. multiple rustdesk instance
> 
> No plan to support yet.

Can we have a "how to set up a rust desk server in your local area network on a raspi" tutorial video at least? (That would solve the problem for me)

**Comment by timschloe** [comment]
> RustDesk should be able to automatically discover other Rustdesk clients on a local area network. Settings could include a flag to hide a client from automated discovery.
This problem seems to persist - Can we have a "how to set up a rust desk server in your local area network on a raspi" tutorial video at least? (That would solve the problem for me)

**Comment by nullbyto** [comment]
Only the ID of the discovered device is shown and when I try to connect to it, it will only try to connect through the ID, so it doesn't work through direct IP when the service is not running or no internet.
