### ISSUE TITLE
Distributable Client address book

### ISSUE THREAD

**Issue by fdbryant3** [rustdesk/rustdesk#262]
Distributable client address book. In other words, if you log into a remote client from a new login it can provide a list of other clients it knows about or is associated with (through a decentralized account id) either automatically or on-demand.

**Comment by bigretromike** [comment]
For now its planned to be per user address book that would be stored on relay/randevuz server, when you log in to your address book on your client you can add/edit/remove all those machine.

More about this #177 

@rustdesk
