### ISSUE TITLE
[Steam Deck specific] App crash on Steam Deck when typing on remote computer

### ISSUE THREAD

**Issue by DrSchnagels** [rustdesk/rustdesk#2641]
**Describe the bug you encountered:**
I use rustdesk on my Steam Deck and my PC to do to daily tasks easier from my PC.
I connect from my PC to the Steam Deck.
When i type on my PC keyboard to f.e. into the Steam Deck Firefox address bar to search something, instantly, after the first typed character, rustdesk on the Steam Deck crashes. It has to be restarted on the Steam Deck.
Also it seems that right click mouse button does not work.
...

**What did you expect to happen instead?**
not crash
...

**How did you install `RustDesk`?**
Ive installed it on the Steam Deck by the flathub version using flatpak install.

latest nightly
---

**RustDesk version and environment**
both pc and steam deck latest nightly

Latest Steam OS Version 3.4 (2 days old)

**Comment by Kingtous** [comment]
Could u please try the [latest nightly build](https://github.com/rustdesk/rustdesk/releases/tag/nightly) ? In my holoiso 4.0, it wont crash any more when typing any characters.

![image](https://user-images.githubusercontent.com/39793325/210195595-b50b65ea-17bf-45b8-8d3c-4bd633905fd5.png)

**Comment by GarnetSunset** [comment]
Running into the same issue with latest nightly on steamdeck and client

**Comment by krodax** [comment]
+1 same issue

**Comment by shown1985** [comment]
+1 same issue, it seems a real bug

**Comment by jrcharney** [comment]
Same issue, on Arch Linux and I installed it using the `aur/rustdesk-git` package using `yay`.

**Comment by shown1985** [comment]
ok it's resolved when I used nightly  , both client and server

**Comment by DrSchnagels** [comment]
Resolved for me too, stable and hadn't had a crash since yesterdays nightly.
