### ISSUE TITLE
Collimator in video game can't follow the mouse movement

### ISSUE THREAD

**Issue by duyanning** [rustdesk/rustdesk#266]
**Describe the bug you encountered:**
I used rustdesk to connect to my home computer today and played DianFeng Tank from QQ Game. 
The mouse can move, but the game's collimator can't follow the mouse movement.
The game does not seem to sense the movement of the mouse.

rustdesk 1.1.6
win10, 19042, x64, both home and work

> 用rustdesk连上家里的电脑，打了一盘腾讯游戏里的巅峰坦克。结果发现鼠标虽然能动，但是指挥不了游戏中的瞄准镜。游戏似乎感知不到鼠标的移动。

**Comment by rustdesk** [comment]
How about 1.1.8? There is some change related to dxgi.

**Comment by rustdesk** [comment]
> > How about 1.1.8? There is some change related to dxgi.
> 
> I downloaded rustdesk-1.1.8-windows_x64-portable.zip and used it without uninstalling previously installed 1.1.6 version. I only "Stop Service" 1.1.6. This problem still exists.

You need to uninstall. In your way, still 1.1.6.

**Comment by duyanning** [comment]
> You need to uninstall. In your way, still 1.1.6.
OK.
I uninstalled 1.1.6, then I used 1.1.8.
This problem still exists.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2033

**Comment by YTOAA** [comment]
> #2033

Is this the same issue? It's even been more than a year since the issue occurred.

**Comment by YTOAA** [comment]
> #2033

Above all, the problem has not been resolved.

**Comment by YTOAA** [comment]
> #2033

The mouse keyboard works normally on 1.19 other than the nightly version. It's very strange

**Comment by rustdesk** [comment]
@asur4s

**Comment by rustdesk** [comment]
#1547
