### ISSUE TITLE
OSX, Big Sur 11.7.1, "RustDesk Internal Error".

### ISSUE THREAD

**Issue by ksuuk** [rustdesk/rustdesk#2669]
Hi,

OSX, Big Sur 11.7.1, always when I launch RustDesk 1.1.9 and/or connect, I get “RustDesk Internal Error” popup, however, when I close the error popup, I still can connect.

![Screenshot 2022-11-22 at 22 48 52](https://user-images.githubusercontent.com/26193002/203420881-dc528b23-4131-4b82-907a-462b427bb306.png)

**Comment by rustdesk** [comment]
try out nightly build.
