### ISSUE TITLE
Keyboard issues on local computer only - some accents not working  - Portuguese (Brazil) ABNT2

### ISSUE THREAD

**Issue by emedeirosit** [rustdesk/rustdesk#2670]
**Describe the bug you encountered:**

The issue happens only in the local computer, not in the remote computer. Version and environment details are in the proper sections below.

During or after a remote connection, and even if the connection has stopped but the RustDesk GUI is still open in the local computer, some accent keys don't work properly in the local computer:

` ^ ` (SHIFT+`~^`)
`` ` `` (SHIFT+`` ´` ``)
` ¨ ` (SHIFT+`6¨`)

If I try to type characters like `ô ò ö` in the local computer I only get `õ ó o`. If I try to type ``^ ` ¨`` I get ``~ ´  `` (not the `6`, if it matters).

It happens if I type in Notepad, Notepad++, Word, Chrome and Edge browsers (and typing this very post here in Chrome): those are the programs I tested so far, along with the VirtualBox mentioned below.

It DOESN'T happen if I type in the Windows search bar, in the search field of Windows settings GUI. If I try File Explorer, it happens in the address bar, but NOT in the search field.

It DOESN'T happen if I type in a VirtualBox guest running Windows inside the same computer (the same physical keyboard), but DOES happen if I type in the VirtualBox management interface of the host, local computer (things like VirtualBox settings).

The issue doesn't appear if I simply open the RustDesk GUI in the local computer: it only appears if I make a connection, and disappears after I end the connection AND close the local GUI.

If I type in the local computer's keyboard to write in the remote computer during a connection, the results in the remote computer are fine; there were issues in the past, with previous versions, but they were solved.

If I move to the remote computer and type using its own keyboard during a connection, the results are fine.

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

BOTH computers have:
RustDesk version 1.2.0 build 2022-12-28 00:24
Installed from the available nightly build `rustdesk-1.2.0-x86_64-pc-windows-msvc.exe`.
RustDesk's GUI was automatically set to Portuguese.

Other info:
RustDesk was installed on both, but only the remote has the service installed.
The remote computer has unattended access configured.
Using RustDesk's map mode for the keyboard.
Using the public RustDesk servers.

---

**Environment**

BOTH computers have:
OS: Windows 10 Home 22H2
OS language: Portuguese (Brazil)
Keyboard layout: Portuguese (Brazil) ABNT2

**Observations**

I started to test RustDesk recently, with the same environment above but with version 1.1.9, and noticed a lot of keyboard issues affecting the REMOTE computer. Those issues were being corrected in subsequent 1.2.0 nightly builds until the experience on the remote computer got perfect in this matter, but only now that I started to use RustDesk more often, with connections established while I do other tasks, I noticed those issues in the LOCAL computer, so I have no idea if they were already present.

By the way: what is the proper way to refer to both computers involved in the connection? Local and remote?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1547
try nightly build please.

**Comment by emedeirosit** [comment]
> #1547 try nightly build please.

I just tried version 1.2.0 build 2022-12-29 00:30 on both computers, and the problem still persists.

As far as I understand, the issues reported on #1547 are related to how the characters end up on the remote computer: I had similar issues (I even sent PMs about that to the subreddit's moderator, sorry about that by the way), and they were solved in nightly releases: you did a great job fixing them.

This issue reported here affects the local computer, the one I'm using to access other computers: I can type those characters perfectly on the remote computer though RustDesk, but I can't type them on the local computer while RustDesk is open, during or after a remote connection, and it only affects certain programs or areas of programs like descripted above.

Thank you!

**Comment by fufesou** [comment]
@emedeirosit Thanks for your detailed report. 
I'm not sure how to reproduce this problem. Is it mandatory? If you don't type `Shift`, will the sticky key be produced?

**Comment by rustdesk** [comment]
@emedeirosit are you sure you used `map` mode? https://github.com/rustdesk/rustdesk/issues/2676#issuecomment-1367330833

**Comment by emedeirosit** [comment]
> Thanks for your detailed report.

You're welcome! I'm excited by your project.

> I'm not sure how to reproduce this problem.

Well, I just tried to use the native virtual keyboard in Windows, and the problem persists, so I guess you wouldn't need a physical keyboard with the same layout. I don't know about the language in Windows tho.

> Is it mandatory?

What do you mean by that?

> If you don't type Shift, will the sticky key be produced?

If I don't press SHIFT, the keys works fine (I get `~`, ` ´ ` and `6`), if I press SHIFT I get `~`, `´` and ` ` (not `6`).

**Comment by emedeirosit** [comment]
> are you sure you used `map` mode

Yes, I am. I've been dealing with those other keyboard issues, affecting the remote side, for the last few days, and they are solved now, at least for me. So, I've been careful to use the `map` mode.

**Comment by fufesou** [comment]
>> Is it mandatory?

> What do you mean by that?

Does this issue occur every time you press the `Shift` key?

**Comment by emedeirosit** [comment]
> Does this issue occur every time you press the `Shift` key?

Yes, every time I try to use `ô` `ò` `ö` (or other letters that would accept those accents), or simply `^` `` ` `` `¨` for a test (by hitting SPACE instead of a letter, like when I want to use `` ` `` to format text like code here with Markdown). Since those accents require the SHIFT key, the answer to your question can be "yes", as long as you understand that the other characters that require the SHIFT key work fine: it's not simply a SHIFT problem.

I guess I can take the risk and say that the issue involves accents that require SHIFT, whether they are going to be over a letter or just alone. Only involves `circumflex accent`,  `grave accent` and `diaeresis`. The other accents that are on the same keys (that don't require SHIFT), `tilde` and `acute accent`, work fine; character `6` and `diaeresis` are on the same key, and that's the funny thing: if I try to get `diaeresis` with SHIFT, I will get a space instead of `6`, unlike what happens with the other two keys (if I try `circumflex accent` I get `tilde`, if I try `grave accent` I get `acute accent`).

And remember that the issue only appears after I open a RustDesk connection to a remote computer, persists if I end the connection but leave RustDesk open, and disappears after I close RustDesk. It doesn't happen if I simply open RustDesk. And the fact that it doesn't affect some Windows native fields like I detailed in other comment.

Thank you!

**Comment by emedeirosit** [comment]
Maybe this can help:

Trying to type ôòö in the local computer:
no RustDesk GUI - ôòö (success)
RustDesk GUI open - ôòö (success)
RustDesk conection established to a remote computer - õóo (fail)
RustDesk conection ended, RustDesk GUI open - õóo (fail)
RustDesk GUI closed - ôòö (success)

**Comment by emedeirosit** [comment]
Any news on this matter? Is there any fix planned for some nightly release?

**Comment by fufesou** [comment]
Hi, this issue is fixed, please conform. Thx

**Comment by emedeirosit** [comment]
Hello! I just tested running `1.2.0 2023-01-22 00:42` on both sides, and I've been testing it regularly with nightly releases: the exact same behavior, no change at all. Thank you!

**Comment by fufesou** [comment]
Thanks for your test and kind feedback.
I'll test tomorrow.

**Comment by emedeirosit** [comment]
Great! I'm excited about your project.

Just to make it clear one more time: I can type well in the remote computer (or to the remote computer) during a session, the problem only occur when I'm using my own local computer, doing other stuff, while a connection to a remote computer is active, or while my own RustDesk GUI is still open after the connection is closed.

**Comment by fufesou** [comment]
@emedeirosit Sorry for late. I can partially reproduce this issue.

`ô` `ò` seems work now.

I'll try to fix it.
`ö` does not work well.

**Comment by KNSd2** [comment]
Hello, 
I can confirm that this is also an issue on azerty-keyboards (belgian-point). Typing ë is not possible when rustdesk is open. 

Additionally, when the remote pc has another layout, the keyboard mapping is not working. It appears to be random. This might be a symptom of the same problem.

**Comment by rustdesk** [comment]
> Additionally, when the remote pc has another layout (qwerty), the keyboard mapping is not working

This is expected, we do not support layout translation yet.

**Comment by KNSd2** [comment]
OK, thanks for the info.

**Comment by fufesou** [comment]
> Typing ë is not possible when rustdesk is open.

It is because windows cannot recognize the dead code of `Shift + 6`.

I've tried the following code with Portuguese (Brazil).

^ (SHIFT+~) prints dead code.
` (SHIFT+´)    prints dead code.
¨ (SHIFT+6)   dose not print dead code.

```c++
#include <stdio.h>
#include <Windows.h>

LRESULT CALLBACK LowLevelKeyboardProc(int nCode, WPARAM wParam, LPARAM lParam)
{
    BYTE state[256] = { 0 };
    DWORD current_window_thread_id = GetWindowThreadProcessId(GetForegroundWindow(), NULL);
    DWORD thread_id = GetCurrentThreadId();
    AttachThreadInput(thread_id, current_window_thread_id, TRUE);
    BOOL status = GetKeyboardState(state);
    if (status == FALSE)
    {
        printf("Failed to GetKeyboardState()\n");
    }
    AttachThreadInput(thread_id, current_window_thread_id, FALSE);

    WCHAR buf[32] = { 0, };
    HKL layout = GetKeyboardLayout(current_window_thread_id);

    printf("print scan code: %d\n", ((PKBDLLHOOKSTRUCT)lParam)->scanCode);
    
    state[0] = 1;
    int len = ToUnicodeEx(((PKBDLLHOOKSTRUCT)lParam)->vkCode, ((PKBDLLHOOKSTRUCT)lParam)->scanCode, state, buf, 8 - 1, 0, layout);
    bool is_dead = false;
    switch(len){
        case 0:
        break;
        case -1:
            printf(" is dead\n");
        break;
        default:
            break;
    };

    return CallNextHookEx(NULL, nCode, wParam, lParam);
}

int main()
{
    HHOOK hhkLowLevelKybd = SetWindowsHookEx(WH_KEYBOARD_LL, LowLevelKeyboardProc, 0, 0);
    MSG msg;
    while (!GetMessage(&msg, NULL, NULL, NULL)) {    //this while loop keeps the hook
        TranslateMessage(&msg);
        DispatchMessage(&msg);
    }
    UnhookWindowsHookEx(hhkLowLevelKybd);
}
```

rdev uses `ToUnicodeEx` and changes the keyboard state.
https://github.com/fufesou/rdev/blob/1be26c7e8ed0d43cebdd8331d467bb61130a2e6e/src/windows/keyboard.rs#L81

I have no idea how to properly fix it. But I'll avoid calling `ToUnicodeEx` for tmp fix.

**Comment by fufesou** [comment]
> Additionally, when the remote pc has another layout (qwerty), the keyboard mapping is not working. It appears to be random, e.g. typing "1" becomes a "7". This might be a symptom of the same problem.

@KNSd2 Hi, did you use map mode? But typing "1" becomes a "7" is a strange behavior. Is the key position of remote "7" the same to local "1"?

For "Map mode", input should behave like a local keyboard connected to the remote computer.
https://github.com/rustdesk/rustdesk/issues/2549#issuecomment-1365929440
https://github.com/rustdesk/rustdesk/issues/2549#issuecomment-1373119456

**Comment by emedeirosit** [comment]
> I have no idea how to properly fix it. But I'll avoid calling ToUnicodeEx for tmp fix.

You are talking about the ` ¨ ` character only, the ` SHIFT + 6 `, right? Well, luckily for me, this accent is not used in the Portuguese language anymore (in Brazil, since there are different rules for Portuguese around the world). So, if you can fix `` ` `` and ` ^ ` it will be fine by me and it won't be an issue to most people who writes in Brazilian Portuguese. But I have no idea about other people, like that one that mentioned the Belgian keyboard (that you replied to).

**Comment by fufesou** [comment]
> You are talking about the ¨ character only, the SHIFT + 6, right?

Yes.

> So, if you can fix ` and ^ it will be fine by me

I've tried recent nightly build, ``` and `^` are fixed.

**Comment by KNSd2** [comment]
@fufesou **_Current setup: Remote PC: Linux Mint, set as qwerty. Main PC: Windows 11 azert_**y. 
In map mode: keyboard is wrong. e.g. `The quick brown fox 123` becomes `<=a76-a8 49a) 5a<_ `
in legacy mode: `The quick brown fox 123 `becomes `The quick brown fox &É `

in legacy mode the letters are all in azerty, all other keys are scrambled (not even like a qwerty keyboard).
I experienced it with multiple devices (windows to windows, windows to linux).
Adding / changing the keyboard layout on the remote-desktop does not work.  

note: is it ok for you to discuss this in this issue?

**Comment by KNSd2** [comment]
> You are talking about the ¨ character only, the SHIFT + 6, right?

I also just tested the latest nightly build. And I can type ë again when rustdesk is open. Note that is located next to the "p" key on a Belgian azerty keyboard.   
![image](https://user-images.githubusercontent.com/26322072/215122726-070a1c2e-02f6-40c3-b3e5-d68f8f9b83fe.png)

**Comment by fufesou** [comment]
@KNSd2 It is better to create a new issue.

Is the issue still exists?

For now, "legacy mode" does not work. "Map mode" is under maintained.

> The `quick brown fox 123` becomes `<=a76-a8 49a) 5a<_`

I can not understand. Can you please write like this?

`1` --> `a`

**Comment by emedeirosit** [comment]
> I've tried recent nightly build, ``` and ^ are fixed.

Yes, good work, thank you very much! I just tried `1.2.0 2023-01-27 13:28`: `` ` `` and ` ^ ` are working fine! I can type them isolated, or with letters, like ` ô ` and ` ò `; I'm typing here with an active remote connection in the background, by the way.

But ` ¨ ` will work sometimes! But I wasn't able to find a pattern in the behavior. Below you have two lines of gibberish I got trying to make it work, either alone or with the letter ` o ` (there are other characters as well):

    ôòo ççöotooloçoôö
    ¨    ool ooçoç o o ` o ôo o ¨       o  öoo o o    o  

Are you going to try to fix ` ¨ `, or are going to close the issue as solved?

**Comment by KNSd2** [comment]
> @KNSd2 It is better to create a new issue.
> 
> Is the issue still exists?

Sorry, I opened an issue. But while debugging it, I found the solution:
Updating the remote desktop to the latest nightly worked.

Thanks!

**Comment by emedeirosit** [comment]
Using 1.2.0 2023-01-30 00:20 on both ends, everything seems to be working fine now, so I will close it. Thank you!

**Comment by emedeirosit** [comment]
Using `1.2.0 2023-01-30 00:20` on both ends, everything seems to be working fine now, so I will close it. Thank you!
