### ISSUE TITLE
Assign names to desks on mobile

### ISSUE THREAD

**Issue by Joery-M** [rustdesk/rustdesk#2677]
Currently it is not possible to assign names to a desk on mobile, but i think it should be possible (like on desktop) to have assign names to desks.

I think an extra button in the option menu could do just fine, like in the picture below.

<img src="https://user-images.githubusercontent.com/44531907/209945385-a36ce5d6-13a8-4cfc-aec8-94e5db5a0bfa.png" alt="Concept of Edit name button" width="500"/>

**Comment by rustdesk** [comment]
in nightly build.
