### ISSUE TITLE
Security issue - Bypass permissions

### ISSUE THREAD

**Issue by RAZ0RBECK** [rustdesk/rustdesk#2680]
Hello , 
I have been using nightly version 1.2.0 for some time now and I found this flaw that allows me to change the settings of the PC I connected to without having any permission (Enable remote configuration modification).

How to reproduce:
- Connect to a computer using Rustdesk;
- open Rustdesk on that computer (you should now see the program screen blurred if you do not have permission to change the configuration);
- to bypass this obfuscation, simply move your pointer to any icon in the program window in the upper right-hand corner; then slowly move the cursor down ( you may need to repeat several times);
-You can now change any of the program settings.

Tested on both Windows and Linux.
I haven't tested the stable version.

**Comment by rustdesk** [comment]
Honestly, we know this flaw. But if you wanna modify security related settings, you need addministrative priviledge.

**Comment by RAZ0RBECK** [comment]
Thank you for the fast reply, yes this is true for linux, unfortunately on a stock windows you only need to press 'yes' to grant admin permission. Today I tried to connect to a stable version (1.1.9), the problem is not present.

**Comment by bigretromike** [comment]
I wanted to report this, but looks like someone was first :-)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/3071

**Comment by Kurgan-** [comment]
You can also use cursor keys to move inside of the rustdesk window leaving the mouse cursor on the title bar. I have just tried it and it worked, I modified the config avoiding the "greyout" of the rustdesk window. 
Or you can put the mouse inside of the window (that turns gray) and then still move around using cursor keys and enter key to enable/disable functions.

**Comment by JReming85** [comment]
Another bypass I just found, if you hover over the window it will darken to prevent access.

With your mouse over the window, press the Windows key to open the start menu and you can now click any of the buttons on the window.  Unhide password, 3 dot menu + enable remote config access, etc.

**Comment by bigretromike** [comment]
So maybe moving setting under button in popup window? so if you click it you need UAC ?

**Comment by sevk** [comment]
really need this security feature?

**Comment by rustdesk** [comment]
Even we fix this, touch mode on mobile still can bypass this.

**Comment by nevaran** [comment]
Could the setting be changed to "as long as theres someone connected to the machine, the window is locked for everyone" ? At least to have some sort of security, since most of the time if its unchecked, you probably wouldnt be making changes while theres someone connected and able to see stuff.

**Comment by flier268** [comment]
Maybe add a password to protect that?

**Comment by rustdesk** [comment]
> Could the setting be changed to "as long as theres someone connected to the machine, the window is locked for everyone" ? At least to have some sort of security, since most of the time if its unchecked, you probably wouldnt be making changes while theres someone connected and able to see stuff.

@21pages let's change to this? Sync # of connections (remote desktop type connection) here https://github.com/rustdesk/rustdesk/blob/588103c6dc36e16d07347dbc7f15e7566ec3dcee/src/ui_interface.rs#L1218
No idea if mouse_time is still used, please confirm. It might still be used by cm.

https://github.com/rustdesk/rustdesk/commit/e3ca82945febcb0f1575773435522d23f58c111d

**Comment by rustdesk** [comment]
Please test https://github.com/rustdesk/rustdesk/releases/nightly
