### ISSUE TITLE
Weird clicking issues

### ISSUE THREAD

**Issue by bcnx** [rustdesk/rustdesk#2688]
Hi,

tried this software yesterday from my Linux Mint 21 to my MacOS 12.6. Could not double click or right click. When going back to the Mac, this behavior was also showing locally. Everything went back to normal when closing the Rustdesk session. Cool software project, but not in a usable stage at this moment, at least not for these operating systems. 

Cheers,

BC

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
try nightly build please

**Comment by rustdesk** [comment]
#1547

**Comment by bcnx** [comment]
Nightly build on Mac results into the same. Do I need to use the nightly build for my Linux viewer as well?

**Comment by rustdesk** [comment]
> Linux

yes

**Comment by rustdesk** [comment]
> service

nightly build is still in heavy dev.

**Comment by bcnx** [comment]
Now it is very workable, even with the non-nightly build om the Linux viewer. Hopefully the nightly build for MacOS will go mainstream soon.
