### ISSUE TITLE
Screen rotated on client

### ISSUE THREAD

**Issue by digitizer0** [rustdesk/rustdesk#269]
Using a windows 10 laptop with 1.1.8 and a linux desktop with 1.1.8.

When connecting to the windows laptop the screen is rotated 90 degrees. Mouse orientation is correct, if I click in the bottom left corner on the client the windows menu is showing. But as you se on the attached image the bottom left corner on the client is not showing the menu.
 
![2021-10-23-124254_931x584_scrot](https://user-images.githubusercontent.com/17356910/138553003-afe31e23-e90e-430e-be14-2f2b5a3b3af8.png)

**Comment by rustdesk** [comment]
No idea how to reproduce.

**Comment by skrzacikus** [comment]
I have the same problem when I connect to several Lenovo Miix 320 laptops with Windows 10 (resolution 1200x800, scale 100%, horizontal orientation). No probem with connection to several different PCs and laptops.

**Comment by rustdesk** [comment]
Try out this one https://github.com/rustdesk/rustdesk/releases/download/tmp/rustdesk-1.1.9-putes.exe on both side please.

**Comment by skrzacikus** [comment]
Everything works fine now. Thanks.

**Comment by skrzacikus** [comment]
I there Android version 1.1.9? I can not connect from Android 1.1.8 to Windows 1.1.9 :(

**Comment by Heap-Hop** [comment]
@skrzacikus coming soon
