### ISSUE TITLE
Lag spikes during remote control with latest windows builds

### ISSUE THREAD

**Issue by Eruthon** [rustdesk/rustdesk#2694]
**Describe the bug you encountered:**
Lag spikes with 2 latest nightly windows builds.
Quality monitor shows 0kB/s and 0 FPS every half second. Mouse is very unresponsive. On slow connections it's even unable to connect, due to remote machine cancelling the connection.
...

**What did you expect to happen instead?**
Run smoothly.. I guess.
...

**How did you install `RustDesk`?**
Downloaded https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64-pc-windows-msvc.exe
Installed via Administrator Powershell/Terminal with --reinstall argument.

Latest nightly windows build from Github.
---

**RustDesk version and environment**
1.2.0 2023-01-01 00:35 (and the one before that)

Windows 11 as local at home, Windows 10 as one remote at friend's house with slow connection and one remote at work.

**Comment by Eruthon** [comment]
If connecting to older version built on 2022-12-05 02:07 running on Windows 10, it's working well.

**Comment by rustdesk** [comment]
can you help confirm which commit or day causes the issue?

**Comment by Eruthon** [comment]
Don't know, as I've downloaded the buggy version yesterday and last time before that I downloaded sometimes before Christmas, I think. And I deleted the old installer which was working fine, unfortunately.

**Comment by rustdesk** [comment]
are you old build is working and new build is not in the same network condition?

**Comment by rustdesk** [comment]
or you just guess old build can work because it worked well before?

**Comment by Eruthon** [comment]
No, the old build works. If I try to connect with latest version on my PC to Windows 10 with the older version, it works correctly.

**Comment by Eruthon** [comment]
When I tried updating the PC at work with working old build, it started to lag after the upgrade on the remote PC.

**Comment by rustdesk** [comment]
@Heap-Hop please follow up, give builds of  different weeks, and then different days for test. @Eruthon can you help test different builds?

**Comment by Eruthon** [comment]
Sure can

**Comment by JReally** [comment]
rustdesk-1.2.0-x86_64-pc-windows-msvc_20221221 worked OK (Win 10 connecting to Win 11)
rustdesk-1.2.0-x86_64-pc-windows-msvc_20221222 (Win 10 to win 11) showed sluggish mouse

**Comment by rustdesk** [comment]
@Eruthon @JReally  Thank you so much

**Comment by rustdesk** [comment]
@JReally did you build yourself?

**Comment by JReally** [comment]
No... just downloaded from the nightly

**Comment by JReally** [comment]
rustdesk-1.2.0-x86_64-pc-windows-msvc_20230102.exe downloaded this morning works properly

JR

**Comment by Eruthon** [comment]
For me the problem persists in the newest version from today. Can it be caused by my private server being outdated?

**Comment by JReally** [comment]
I'm no expert but here's my setup
  - private server setup last June on Linux Mint - no updates to the server after that
  - my test connections were from Win10 to control a new Win 11 on my local network
  - the connection was direct so that would (I think) that the server was only used for initial connection?
  - my previous download from the nightly (to the Win 10) did show the poor connection for mouse and typing
  - today's download to the Win 10 works fine

**Comment by Heap-Hop** [comment]
hi @Eruthon.  
Thanks for your report, 

but I can't repuduce in my PC :(


> Quality monitor shows 0kB/s and 0 FPS every half second

How about the `Delay` showed when it happened?
And what is the connection status ? (`Direct` or `Relayed`, it will be showed on connection tab's icon, when your mouse hover on it).

or could you please record screen (with Quality monitor on) when it happened.

**Comment by Eruthon** [comment]
Hi @Heap-Hop

I tried a fresh new installation on my Windows server 2022 at work today.
I'm connecting via Wireguard VPN, but I'm going to try without it, too.

For your question:
the delay starts at 10-20 ms, but during lag it goes to 500-1000 ms and it fluctuates (even without VPN) over relayed and direct, too.
![image](https://user-images.githubusercontent.com/37985268/210320672-6d425c59-b57f-44c4-a21d-d23ab68248a3.png)
The lag happens every 1-3s. The screen just freezes and every action I make gets displayed after the lag when it unfreezes for a bit. It's just very unusable, you can imagine.

https://user-images.githubusercontent.com/37985268/210321597-ef18c07f-caac-4b07-aec2-cbd17fafc854.mp4

Versions:
Win server: 2023-01-02
My Win 11 PC: 2023-01-02
RustDesk server: latest 1.1.9

**Comment by Heap-Hop** [comment]
@Eruthon  Thanks a lot, very helpful screen record!
Did all lag happened only on your Win 11 PC as local?
 
Hi @JReally, please check the screen record, if it is the same problem from you before?

**Comment by Heap-Hop** [comment]
@Eruthon Could please try out other device or OS as local in your same network environment, if there is still same problem?

**Comment by Heap-Hop** [comment]
@Eruthon Win11 local to Win10 remote, I can repuduce now. I will check it, thanks again.

**Comment by rustdesk** [comment]
@Eruthon can you try out different builds in https://github.com/open-trade/rustdesk/releases/tag/tmp? Later I will build more for you, it help us know which date RustDesk starts not work in your scenario.

**Comment by Eruthon** [comment]
@rustdesk
Summary of Win Server 2022 as remote and Win 11 22H2 as local:
rustdesk-2022-12-05-x86_64-pc-windows-msvc.exe ✔️
rustdesk-2022-12-12-x86_64-pc-windows-msvc.exe ✔️
rustdesk-2022-12-19-x86_64-pc-windows-msvc.exe ✔️
rustdesk-2022-12-26-x86_64-pc-windows-msvc.exe ❌

**Comment by rustdesk** [comment]
Thanks, we put a fix, you can try the new nightly build one hour later.

**Comment by Eruthon** [comment]
![TheOfficeDwightSchruteGIF](https://user-images.githubusercontent.com/37985268/210348690-ea72c3ed-b4dc-43d8-b98e-dfb777222735.gif)

**Comment by Eruthon** [comment]
@rustdesk
Works now!
