### ISSUE TITLE
Fonts on Rustdesk website aren't loading properly

### ISSUE THREAD

**Issue by paulocoghi** [rustdesk/rustdesk#27]
First of all, congratulations of the project.

On rustdesk.com, the fonts seem strange:

![rustdesk](https://user-images.githubusercontent.com/378397/115931750-fc958980-a48b-11eb-98af-adb6ea55099d.png)

**Comment by rustdesk** [comment]
Thanks anyway.

**Comment by paulocoghi** [comment]
I saw the custom fonts on CSS, but their .otf or .ttf files are not pointed. Just uploading them and pointing their files on CSS will solve the issue, and they will be rendered properly.

> Thanks anyway.

You are welcome!

**Comment by rustdesk** [comment]
Thanks for your reminder. I remove fonts.googleapis.com and all font-family in css.
