### ISSUE TITLE
Segfault when passing command line options (--help)

### ISSUE THREAD

**Issue by douardda** [rustdesk/rustdesk#2700]
**Describe the bug you encountered:**

While trying to debug connection issues to a self-hosted rustdesk server, I tried to see possible command line options of the desktop app by running the command `rustdesk --help` but it then segfault.

**What did you expect to happen instead?**

Ideally a nice help message, at least a message stating the command line option is not supported instead of crashing.

**How did you install `RustDesk`?**

Installed using the provided deb file from the website (1.1.9) and installed it on my Debian Bullseye amd64 laptop.
 
---

**RustDesk version and environment**

Rundesk 1.1.9, deb package, Debian Bullseye, amd64, RAM 32GB, NVME drive.

Thank you

**Comment by douardda** [comment]
FYI the connection issue I had was due to the lack of support of ipv6 in v1.1.9. Using the v4 ip address directly (instead of the server name which resolves in both ipv4 and ipv6) worked, as well as using the nightly build with the server name (and it actually uses ipv6, as seen by tcpdumping the network traffic).

**Comment by douardda** [comment]
Also the cmd line option handling seems better with the nightly buikld (no segfault) but the seems not to have proper `--help` support (UI starts instead of showing a help message with possible cmdline options and arguments).

**Comment by douardda** [comment]
Did I forgot to say _thank you for this nice and promising project_ before rumbling? I sure did! sorry about that.

**Comment by rustdesk** [comment]
Close in favour of https://github.com/rustdesk/rustdesk/issues/69
