### ISSUE TITLE
Cannot Install RustDesk to my computer

### ISSUE THREAD

**Issue by AlterGu** [rustdesk/rustdesk#271]
**Describe the bug you encountered:**
I was download 'rustdesk-1.1.8-windows_x64.zip' and unpacked it , then I double click 'rustdesk-1.1.8-putes.exe' to try to install this application, but after steps it was nothing to happen
...

**What did you expect to happen instead?**
Finish the installation
...

**How did you install `RustDesk`?**

GitHub release
---

**RustDesk version and environment**
rustdesk-1.1.8
Windows 10 20H2 19042.1288

**Comment by rustdesk** [comment]
No response.
