### ISSUE TITLE
macos Ventura 13.0.1 M1 doesn't work 

### ISSUE THREAD

**Issue by syadnom** [rustdesk/rustdesk#2710]
Installed newest release, 1.1.9, attempted to connect out to another host and attempted to connect to macos host.  Neither work.  Says connecting but just times out.  Other windows hosts can connect to each other, but the mac is shunned.

Installed via dmg, granted all permissions

Macos Ventura 13.0.1 on Mac Mini M1

remote terminals vary, win 10 , win 11, win server etc.  I don't believe any of the remote hosts are an issue.

**Comment by rustdesk** [comment]
try out nightly build please.

**Comment by syadnom** [comment]
This worked.  It's very slow right now, I haven't checked to figure out why.  I didn't see this slowness on the windows client at the office.  I'm new to rustdesk though, is this a side effect of failing to get a p2p connection or something?

**Comment by rustdesk** [comment]
self-hosting please, our public servers are for demo only.
