### ISSUE TITLE
Shift + Arrow key didn't work properly on remote side

### ISSUE THREAD

**Issue by ForsakenRei** [rustdesk/rustdesk#2711]
**Describe the bug you encountered:**

When holding Shift, arrow keys(left, right, up and down) didn't select text on remote side in a text editor.

**What did you expect to happen instead?**

Text selected as usual

**How did you install `RustDesk`?**

1.2.0 nightly build date 1/3/2022

**RustDesk version and environment**

1.2.0 nightly build on both host and remote, self hosted server.

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1547

**Comment by fufesou** [comment]
@ForsakenRei Thanks for your feedback. 
Do "Shift" and Arrow keys work properly respectively? Can "Shift" + "a"  results "A"?
What OS you're using on both sides? 
What's your keyboard mode?
<img width="309" alt="1672798824052" src="https://user-images.githubusercontent.com/13586388/210472742-d59dcedc-73db-4fae-b236-bd1c577cd430.png">

**Comment by ForsakenRei** [comment]
> @ForsakenRei Thanks for your feedback. Do "Shift" and Arrow keys work properly respectively? Can "Shift" + "a" results "A"? What OS you're using on both sides? What's your keyboard mode? <img alt="1672798824052" width="309" src="https://user-images.githubusercontent.com/13586388/210472742-d59dcedc-73db-4fae-b236-bd1c577cd430.png">

All Windows, I'm on Win10 and tried two remote machines with Win10 and Win11 but seems doesn't work on both.
`shift` works properly when typing other keys like alphabet or numbers symbols etc. And arrow keys themselves works just fine. The only thing I noticed is shift+arrow keys didn't really work.

I used legacy mode but just tried map mode as well, now confirmed legacy mode didn't work but map mode work.

**Comment by fufesou** [comment]
Thanks for your testing and report.
I'm fixing "Map mode" issues now. Issues of "Legacy mode" will be fixed after that.
Fow now, please choose "Map mode".
