### ISSUE TITLE
https://web.rustdesk.com got hijacked

### ISSUE THREAD

**Issue by SailReal** [rustdesk/rustdesk#2712]
https://web.rustdesk.com linked on https://rustdesk.com got hijacked 

![Screenshot from 2023-01-03 23-05-16](https://user-images.githubusercontent.com/1786772/210449644-ff17c0f1-b57f-48ba-926a-af36cf0879a6.png)

**!!!WOULD NOT RECOMMEND TO CLICK ON THIS LINK!!!**

**Comment by rustdesk** [comment]
Thanks, fixed, but web.rustdesk.com has no https support, we stated the reason in another issue.

**Comment by kwinz** [comment]
What was the issue here exactly? @rustdesk  Was there a (security) issue with the website **server-side**?
Or was @SailReal's local connection hijacked because it's not a `HTTPS` connection?

> we stated the reason in another issue.
Could you link this?

Appreciate it!

**Comment by rustdesk** [comment]
nothing special, i screwed up nginx config, that's another website hosted on the same server.
