### ISSUE TITLE
Mouse (multiple) buttons not registering

### ISSUE THREAD

**Issue by KoalaBear84** [rustdesk/rustdesk#2713]
**Describe the bug you encountered:**

When you press and hold the right button, and then press the left button, the left button is not registered on the client.
And then, when you release the right button it is not registered. Only the release of the left mouse button is registered.

1. Mouse right press and hold (registered)
2. Mouse left press and hold (not registered)
3. Mouse right released (not registered)
4. Mouse left released (registered)

The side effect is also that the right mouse button remains down at the client, so I cannot use the left mouse for most of the actions until I right click and release again which happens like 30 times a day :)

**What did you expect to happen instead?**

That all 4 actions are registered, and the right mouse is not down anymore.

**How did you install `RustDesk`?**

I've updated to host the nightly from 5 hours ago, it didn't fix this. I did introduce a 'bug' that the big enter key didn't work anymore in map mode, but that worked after updating the client too, so that's OK.

---

**RustDesk version and environment**

Host: RustDesk nightly @ Windows 10 Pro 22H2
Client: RustDesk nightly @ Windows 10 Enterprise 22H2

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1547

**Comment by KoalaBear84** [comment]
Confirmed. Great and fast fix! ♥
