### ISSUE TITLE
rustdesk-1.2.0-x86_64-pc-windows-msvc (unreleased version) avast displays virus warning

### ISSUE THREAD

**Issue by lunatic1972** [rustdesk/rustdesk#2716]
Just wanted to let you know that it shows up as a virus in avast. So either the code has been modified or because it's a remote desktop application it may be triggering it to show it or last case scenario is that the code somehow resembles a known virus

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/2485
