### ISSUE TITLE
Some key are duplicated in i18n

### ISSUE THREAD

**Issue by wangzexi** [rustdesk/rustdesk#2718]
I'm building the web version, but I'm having the same problem as he: https://github.com/rustdesk/rustdesk/issues/1706

The TypeScript compiler checked for duplicate key values in the safed Unicode string.

So I checked the raw input of the `gen_js_from_hbb.py` script and found that there are indeed duplicate keys.

https://github.com/rustdesk/rustdesk/blob/803152da483fee1ed52a1d4db6bbdd07c5d961d7/src/lang/ca.rs#L202
https://github.com/rustdesk/rustdesk/blob/803152da483fee1ed52a1d4db6bbdd07c5d961d7/src/lang/ca.rs#L350

However, JavaScript naturally supports Unicode strings, so I'm not sure why this conversion is needed.

``` JavaScript
const obj = {
    "🎉": "😄"
}
console.log(obj) // { '🎉': '😄' }
console.log(obj["🎉"]) // 😄
```

**Comment by rustdesk** [comment]
fix it then.

**Comment by rustdesk** [comment]
safe
