### ISSUE TITLE
Android source code

### ISSUE THREAD

**Issue by alfredonodo** [rustdesk/rustdesk#272]
Hi,
I just found this project and it seems very promising. Unfortunately I cannot find android source code. Is it released?
Thank you

**Comment by rustdesk** [comment]
@ dannkunt @alfredonodo 
We are now open source everything/
https://github.com/rustdesk/rustdesk/tree/master/flutter
Help yourself, doc will follow up.

**Comment by sascha1337** [comment]
that’s the spirit

**Comment by rustdesk** [comment]
@toplinux @technodrome @nickbe @alecgm both server side and mobile client are now open source.

**Comment by rustdesk** [comment]
> donate

Twitter https://github.com/rustdesk/rustdesk may be more helpful. :)
