### ISSUE TITLE
Administrator permissions blank the screen

### ISSUE THREAD

**Issue by Emanuele971** [rustdesk/rustdesk#2720]
Hi, I'm the network manager of our company who deals with remote support on various levels. 

We have set up our own Rustdesk server to be able to support our customers who mainly use Windows. 

However, we find a big obstacle: **_When windows asks for the Administrator password for an operation with elevated privileges, the window goes dark..._** 

With TeamViewer for example this does not happen because we can enter the credentials remotely, while with Rustdesk , since the screen goes dark, we can't work. 

Is there a solution to this? 

Thank you very much in advance.
Best Regards
Martino

**Comment by rustdesk** [comment]
duplicate

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/70#issuecomment-1371634199
