### ISSUE TITLE
macOS app icon doesn't match HIG

### ISSUE THREAD

**Issue by rakleed** [rustdesk/rustdesk#2722]
**Describe the bug you encountered:**

The app icon doesn't match HIG - not that much rounding of the corners.

**What did you expect to happen instead?**

Application icon corresponds to HIG - correct corner radius. There is information [here](https://stackoverflow.com/a/71134715/11336855) about what rounding the icon should have, but it's best to use the production templates from [Apple Design Resources](https://developer.apple.com/design/resources/#macos-apps).

**How did you install `RustDesk`?**

GitHub nightly release

---

**RustDesk version and environment**

1.2.0 build date 2023-01-03 11:36, macOS 13.1

<details><summary>Screenshots</summary>

![Screenshot 2023-01-04 at 23 55 21](https://user-images.githubusercontent.com/19418601/210655736-a5256002-a284-4225-bc7c-baebd82de3c4.png)

<img width="512" alt="rustdesk" src="https://user-images.githubusercontent.com/19418601/210655752-f361f513-ade4-4380-b068-4bb5c6d7ff2e.png">

</details>

**Comment by rustdesk** [comment]
Thanks, it is helpful

**Comment by grummbeer** [comment]
Is the SVG the source for the png? 

Screenshot from the svg.  
https://github.com/rustdesk/rustdesk/blob/master/flutter/assets/logo.svg
https://github.com/rustdesk/rustdesk/blob/master/res/logo.svg

Both sides are different, not mirrored and not 100% aligned. 

@NicKoehler do you think you can fix that too?

![rustdesk-logo-upperside](https://user-images.githubusercontent.com/67791701/214275034-cc4a7366-7e0b-4cae-957d-b0b7ff9fac4f.png)

![rustdesk-logo](https://user-images.githubusercontent.com/67791701/214272590-0ed2e298-0dfb-4984-abdf-3fb1e299e41e.png)


The markup is also not clear

```xml
<svg xmlns="http://www.w3.org/2000/svg" 

viewBox="0 0 375 375" 
<!-- viewBox does not match … -->

style="width:32px;height:32px;margin:0 4px 4px 0">

<!-- … the style --->

<rect transform="matrix(.91553 0 0 .91553 -152.92 116.76)" x="167.03" y="-127.54" 

width="409.6" height="409.6" 

<!-- … the with and height --> 

rx="64" ry="64" fill="#0071ff"></rect>
```

https://jakearchibald.github.io/svgomg/

![rustdesk-logo-svg](https://user-images.githubusercontent.com/67791701/214278810-80ca5cbc-d49f-458b-978e-6ed1d3c25d18.png)

**Comment by NicKoehler** [comment]
I used the source SVG. If the logo needs to be fixed, I can do it, but I need to know if the logo's asymmetry is intentional.

**Comment by grummbeer** [comment]
>  but I need to know if the logo's asymmetry is intentional.

Yes, of course.

The remote desktop is also (or should be)  a 100% reflection.

**Comment by NicKoehler** [comment]
I made this version. It should be perfectly symmetrical

![logo](https://user-images.githubusercontent.com/53040044/214295728-c04bb442-8652-45bb-ac37-cc7a6afd0db8.svg)

**Comment by grummbeer** [comment]
thanks, very cool, much better in my opinion.  At least technically right.

Maybe this is a bit pedantic or esoteric ... but what do you think of these little "humps"?

![rustdesk-logo-4](https://user-images.githubusercontent.com/67791701/214314400-1eab238b-e58f-43f4-89d2-9869e7866871.png)

![rustdesk-logo-3](https://user-images.githubusercontent.com/67791701/214316366-22d2e331-688d-458c-bedc-6ea8227295e0.png)

Independent of this question, just to have it clear. Afterward, there are at least two versions 

1. Complete icon set, dedicated for iOS (larger border radius)  followed the guildlines of apple
2. Default set of icons, with a smaller border radius, which is used for Android, Windows, macOS

Is there a need to have dedicated set for macOS and Android too?

let's wait for feedback from the devs.

**Comment by rustdesk** [comment]
Thanks for your feedback, you are teaching us new knowledge. Our current logo is very similar to one brand, we need to redesign our logo soon. Then we will think about all you mentioned seriously.

**Comment by NicKoehler** [comment]
I would like to redesign it, if you want. I just need to know your constraints/guidelines.

**Comment by NicKoehler** [comment]
What about this one? I just made minor refinements like rotation, spacing between the two half circles and color. Tell me if you want any changes or try something completely different.

![rustdesk](https://user-images.githubusercontent.com/53040044/214406797-be1b1b19-5995-4972-ad20-7cb7978249c6.svg)

**Comment by rustdesk** [comment]
Wow, you are genius, I like your design style very much, totally match my preference and expectation. I am looking forward to your other changes and something completely different.

**Comment by NicKoehler** [comment]
Here are some sketches that I made today. Each one of them features a minimal 'R' and 'D' forming a logo. There is always room for improvement, if you like one of them. However, I still prefer yesterday's redesign.

![Group](https://user-images.githubusercontent.com/53040044/214669801-463ed85b-0724-4d90-ab7c-47d007ca0bc4.png)
![Group_2](https://user-images.githubusercontent.com/53040044/214669804-22874696-0577-446c-b68f-7aeba8b790de.png)
![Group_3](https://user-images.githubusercontent.com/53040044/214669805-5262e799-afb1-4cae-bd0f-271689e53f41.png)
![Group_4](https://user-images.githubusercontent.com/53040044/214669807-79dd269d-c7a2-4748-ab8a-6e18f001884b.png)
![Group_5](https://user-images.githubusercontent.com/53040044/214669808-d2e5e6c5-5761-4234-be36-2f906042e3e7.png)

**Comment by rustdesk** [comment]
Wow, You are creative. I prefer yesterday's redesign too, though it looks like a refresh icon a little. :)

**Comment by NicKoehler** [comment]
I created a [new branch in my fork](https://github.com/NicKoehler/rustdesk/tree/new-icon) with my previous redesign. If you're interested.

**Comment by NicKoehler** [comment]
I'll try something

**Comment by NicKoehler** [comment]
How about one of these?

![rd1](https://user-images.githubusercontent.com/53040044/216305064-4e7b79b2-3551-4156-bd07-5071ab12210c.png)
![rd2](https://user-images.githubusercontent.com/53040044/216305067-73898b77-29a8-442b-9bd8-5c95f4d8486f.png)

**Comment by rustdesk** [comment]
It looks great, what font is it?

**Comment by rustdesk** [comment]
Got it, could you upload svg file?

**Comment by NicKoehler** [comment]
Sure

![rd1](https://user-images.githubusercontent.com/53040044/216333102-4d10c195-be66-4fa0-97ca-70a71756b25e.svg)
![rd2](https://user-images.githubusercontent.com/53040044/216333104-f3ccf68b-98f8-42d1-8342-60c4fc0ac7e0.svg)

**Comment by rustdesk** [comment]
@NicKoehler I made a little change to your design to make the color brighter and conforming to original blue color. Which one do you prefer? Do you have the other suggesions?

![path9](https://user-images.githubusercontent.com/71636191/216807019-2a7b46d2-3458-4e92-b5e2-0b8982359306.png)

![path9](https://user-images.githubusercontent.com/71636191/216807072-b02524a6-5593-4570-9b63-76919dce7f43.png)

**Comment by rustdesk** [comment]
![image](https://user-images.githubusercontent.com/71636191/216807093-33e879bc-e951-47c2-a77d-f4947454bd34.png)

**Comment by rustdesk** [comment]
![image](https://user-images.githubusercontent.com/71636191/216807218-9203f31a-f478-4250-897a-2f271495805b.png)

**Comment by NicKoehler** [comment]
If you want to maintain the gradient, I'd say the first one is more visible as the logo scales.

**Comment by rustdesk** [comment]
The first one is copied from above iOS picture.

**Comment by NicKoehler** [comment]
The only thing is that I think the colors now are very similar to the logo on https://www.fishbowlinventory.com. I changed it to differentiate it from theirs.

**Comment by rustdesk** [comment]
The second one is more different.

**Comment by NicKoehler** [comment]
Yeah the second one is better if you want to differentiate

**Comment by rustdesk** [comment]
@NicKoehler which one do you prefer? though very little different.

![image](https://user-images.githubusercontent.com/71636191/216903220-6e453f18-3026-4e05-9798-31fce5c64949.png)

**Comment by NicKoehler** [comment]
I prefer the top one

**Comment by rustdesk** [comment]
My daughter prefers the first one also.

**Comment by rakleed** [comment]
@rustdesk when you [added the new icons](https://github.com/rustdesk/rustdesk/commit/3ca72e82a0b26d8a1aa38bbb731f9c7119b66953#diff-cda9e923e23c587e00084b2e5d1abe55d012fd233c088985e9dd207c485cc46b) you forgot to add a drop shadow for the icon itself as required by [HIG](https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons/#platform-considerations:~:text=Use%20the%20drop%20shadow%20in%20the%20icon%2Ddesign%20template.%20The%20app%2Dicon%20template%20includes%20the%20system%2Ddefined%20drop%20shadow%20that%20helps%20your%20app%20icon%20coordinate%20with%20other%20macOS%20icons.). It is best to use [a template from Apple](https://developer.apple.com/design/resources/#macos-apps).

@NicKoehler and can you add a drop shadow for the semicircle and update the icon for macOS as the [HIG mentions](https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons/#platform-considerations:~:text=Consider%20using%20interior,tilted%20slightly%20downward.) that on macOS you can add drop shadow and highlights to elements inside the icon.
