### ISSUE TITLE
Keyboard

### ISSUE THREAD

**Issue by giuliovale** [rustdesk/rustdesk#2725]
Nigtly Build
Italian lang

Windows 11 -> Windows 11  Legacy keyboard OK,  Map keyboard totally wrong
WIndows 11 -> Windows 10 Legacy Keyboard totally wrong, Map mode totally wrong

**Comment by rustdesk** [comment]
Does not make sense.

**Comment by giuliovale** [comment]
Sorry my fault! All ok for windows 11-> windows 10 (on remote there is a different lang).

**Comment by grummbeer** [comment]
#1547
