### ISSUE TITLE
Mouse hotkeys not transfering to the server

### ISSUE THREAD

**Issue by roda37** [rustdesk/rustdesk#2726]
I have a mouse that has 2 keys on the left side of it and I use it to go forward and backwards in a web browser and some other apps. This in rustdesk doesn't work at all. I imagine it wouldn't be a huge issue to add but would make the experience a lot better. Note, these buttons (mouse4, mouse5) do not register at all on the host. I used xev to register the clicks but to no avail.

**Comment by rustdesk** [comment]
duplicate

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2230

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3488
