### ISSUE TITLE
Input Control dosen't work when ues Windows7 to control Android 9

### ISSUE THREAD

**Issue by Kx-Y** [rustdesk/rustdesk#2738]
**Describe the bug you encountered:**

Input Control dosen't work sometimes,restart the device can help,but it will become invalid soon.
When I  tried to click on the screen,the speed and FPS become very low.
![image](https://user-images.githubusercontent.com/86878459/210936757-7bf13a47-4616-4c0b-886d-329a9b979de0.png)

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

GitHub release 

**RustDesk version and environment**
both v1.1.9 and v1.2.0 have this problem.
device info:
![image](https://user-images.githubusercontent.com/86878459/210936921-4e85e617-c6c8-482a-9fb6-ebe0c3526c82.png)
![d571e17a3a34b1e0d2aa78a826b5de6](https://user-images.githubusercontent.com/86878459/210937076-bcf82535-53f4-406d-b816-66c947aeee26.jpg)(It is android 9 infact)

**Comment by Kx-Y** [comment]
What can I do to provide you with more information?
If necessary,I can let you control my device remotely to find more info.

**Comment by rustdesk** [comment]
close to favor https://github.com/rustdesk/rustdesk/issues/3893
