### ISSUE TITLE
RD on MacOS 12, 13, shift + symbol keys arent working

### ISSUE THREAD

**Issue by perfecto25** [rustdesk/rustdesk#2746]
**Describe the bug you encountered:**

From my Ubuntu host, I am connecting to a MacOS client

when connecting to MacOS 12 or 13 

typing shift and symbol:   !, @, #, $, %, ^, &, *, (, ), _, +

none of these symbols work on RD mac client when typing from Host

**What did you expect to happen instead?**

working keyboard keys

**How did you install `RustDesk`?**

on Host (Ubuntu 22), installed via RD 1.1.9.deb

on Client (where keyboard doesnt work properly, MacOS 12.2),   installed RD 1.1.9 pkg 

Tried this on both MacOS 12 and 13, same issue

**Comment by rustdesk** [comment]
try out nightly build please
