### ISSUE TITLE
In nightly versions, it's not possible to select and copy text in app (chat  window, error message, about page)

### ISSUE THREAD

**Issue by rakleed** [rustdesk/rustdesk#2747]
**Describe the bug you encountered:**

Unable to highlight and copy chat text, error message, and version number in About.

**What did you expect to happen instead?**

In 1.1.9, it was possible to highlight and copy text in chat, but the error message and version number in About were not copied.

**How did you install `RustDesk`?**

GitHub nightly release

---

**RustDesk version and environment**

Windows 11 v. 22H2 / macOS 13.1, RustDesk 1.2.0 build date 2023-01-06 00:19

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by youhers** [comment]
This problem only needs to be closed and connected again, and the paste can be copied, which seems to be a bug as well

**Comment by rustdesk** [comment]
https://medium.com/flutter/whats-new-in-flutter-3-7-38cbea71133c#:~:text=Flutter%20apps%20page.-,Global%20selection%20improvements,-SelectionArea%20now%20supports

**Comment by rustdesk** [comment]
trackpad can not work totally on Flutter 3.7, there seems api changed, @fufesou please follow up.

**Comment by rustdesk** [comment]
Confirmed, still very fast.

**Comment by rustdesk** [comment]
todo: https://github.com/rustdesk/rustdesk/commit/68cc667f475ee66c445fe66380c98c4ef9f9d934 partly fix the issue, but to make chat message selectable need to modify dash chat pub.

**Comment by rustdesk** [comment]
@Heap-Hop dash chat is not maintained any more, may need to migrate to https://pub.dev/packages/dash_chat_2 and submit feature request there.

**Comment by powerman** [comment]
Not sure is it related, but it's also impossible to "paste" using default Linux way (by pressing middle mouse button). Paste using popup menu or Ctrl-V works.

**Comment by rustdesk** [comment]
> Not sure is it related, but it's also impossible to "paste" using default Linux way (by pressing middle mouse button). Paste using popup menu or Ctrl-V works.

You'd better to report to google flutter repo.

**Comment by powerman** [comment]
> You'd better to report to google flutter repo.

You right. But looks like it's already reported: https://github.com/flutter/flutter/issues/99074
