### ISSUE TITLE
un-remember password

### ISSUE THREAD

**Issue by coolit** [rustdesk/rustdesk#275]
If you check the remember psw checkbox, there is no way to uncheck it, unless you change psw. 
There should be an easy way to un-remember psw.
Thanks.

**Comment by rustdesk** [comment]
The simplest way is you remove it from recent session list.

**Comment by coolit** [comment]
yeah, this is one way. But imagine you have multiple sessions in your list. And you need to keep the list for easy access, then you'd better add an option to unremember psw.
