### ISSUE TITLE
Cannot drag the middle mouse button when playing games remotely

### ISSUE THREAD

**Issue by longshao5520** [rustdesk/rustdesk#2753]
Cannot drag the middle mouse button when playing games remotely

I hope the middle mouse button can be dragged

Initiator：Windows10 resdesk1.1.9
Controlled end：Windows10 resdesk1.1.9
game：DYSON SPHERE PROGRAM

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/787
