### ISSUE TITLE
Right side Ctrl key isn't working

### ISSUE THREAD

**Issue by tzengshinfu** [rustdesk/rustdesk#2760]
**Describe the bug you encountered:**
I try to use shortcuts(Ctrl + C/Ctrl + V) to copy/paste, right side Ctrl key is invalid.
PS: Right side shift & alt are working.
...

**What did you expect to happen instead?**
Work fine.
...

**How did you install `RustDesk`?**
GitHub release.

---

**RustDesk version and environment**
RustDesk Server version: 1.1.9
Server OS version: Windows 10 Pro 22H2 19045.2364
RustDesk Client version: 1.1.9
Client OS version: Windows 10 Pro 22H2 19045.2364

**Comment by rustdesk** [comment]
nightly build please

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/728#issuecomment-1370855497
