### ISSUE TITLE
linux(arch) -> windows 10 keyboard not working

### ISSUE THREAD

**Issue by mihalycsaba** [rustdesk/rustdesk#2764]
**Describe the bug you encountered:**

Installed rustdesk on windows 10, mouse and screen works, cant use keyboard at all.

**What did you expect to happen instead?**

being able to type and use kb shortcuts on remote.

**How did you install `RustDesk`?**

dowloaded from rustdesk.com and installed it on windows on remote

from AUR on local

---

**RustDesk version and environment**
remote: 1.1.9 windows 10
local: 1.1.9-3 rustdesk-bin from AUR on arch linux

**Comment by rustdesk** [comment]
nightly build please.
