### ISSUE TITLE
Crash on exit, Ubuntu 22.04

### ISSUE THREAD

**Issue by fufesou** [rustdesk/rustdesk#2771]
**Describe the bug you encountered:**

Rustdesk report signal 11 and print backtrace.

https://user-images.githubusercontent.com/13586388/211283616-45e400a6-d7a5-476a-b7fb-6f7cc6e1f08a.mp4

1. Establish a connection.
2. Close the main page.
3. Close the remote page.

Reversing the second and third steps does not produce this problem.

```
flutter: [Remote Page] call onDestroy with args {} from window 0
flutter: [MultiWindowHandler] active window changed: []
flutter: closing multi window: WindowType.RemoteDesktop

** (rustdesk:12998): CRITICAL **: 17:42:54.378: gboolean fl_binary_messenger_send_response(FlBinaryMessenger *, FlBinaryMessengerResponseHandle *, GBytes *, GError **): assertion 'FL_IS_BINARY_MESSENGER(self)' failed
[2023-01-09T09:43:00Z ERROR librustdesk::platform::linux] Got signal 11 and exit. stack:
    backtrace::backtrace::libunwind::trace::h98033be41657c4bc
    backtrace::backtrace::trace_unsynchronized::h713f110a0016000e
    backtrace::backtrace::trace::h826914da78dfbca5
    librustdesk::platform::linux::breakdown_signal_handler::hb79c35a48bd58ba3
    fl_method_call_respond
    _ZZN13WindowChannel12InvokeMethodElPKcP8_FlValueP13_FlMethodCallENK3$_1clEP8_GObjectP13_GAsyncResultPv
    _ZZN13WindowChannel12InvokeMethodElPKcP8_FlValueP13_FlMethodCallEN3$_18__invokeEP8_GObjectP13_GAsyncResultPv
    g_main_context_dispatch
    g_main_context_iteration
    g_application_run
    main
    __libc_start_call_main
    __libc_start_main_impl
    _start
[FATAL:flutter/fml/thread_local.cc(30)] Check failed: false. pthread_setspecific failed (22): Invalid argument
Lost connection to device.
```

**What did you expect to happen instead?**

Exit normally.

**How did you install `RustDesk`?**

Build from source.

---

**RustDesk version and environment**

The latest source build. Ubuntu 22.04.

**Comment by Kingtous** [comment]
cannot reproduce the crash on Ubuntu 22.04, both on xorg and wayland.

strictly followed the steps:

> 1. Establish a connection.
> 2. Close the main page.
> 3. Close the remote page.

release: nightly release build today (2023.1.29)
<img width="661" alt="image" src="https://user-images.githubusercontent.com/39793325/215301173-4cc59dca-d29a-48cc-9223-3dfb44c8a3d4.png">

**Comment by fufesou** [comment]
This crash is still there on my PC. I'm using VM Ubuntu 22.04.
As it appears on my PC, I'll try to fix later.
