### ISSUE TITLE
[Nightly] Scale Adaptive not taking effect on monitor switch

### ISSUE THREAD

**Issue by bilago** [rustdesk/rustdesk#2774]
**Describe the bug you encountered:**

Using Scale Adaptive, if I switch from monitor 1 to 2 (two different resolutions - one is bigger than the client window, one smaller) the output is not scaled to fit the window, until I un-collapse the top tool bar - which then it takes effect immediately. This happens in both directions (Monitor 1 to 2, and 2 to 1). Pinning the top tool bar open, does not resolve the issue. I have to then collapse and then uncollapse again for it to take effect.

**What did you expect to happen instead?**

I would expect the scaling to be instantaneously in effect upon switching monitors

**How did you install `RustDesk`?**

GitHub nightly (Latest as of this post)

---

**RustDesk version and environment**

v1.2.0
Build Date: 2023-01-09 -09 00:29

Windows 10

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
@bilago Thanks for your feedback. I've fixed this issue.
Please confirm using the ngihtly build tommorrow.

**Comment by bilago** [comment]
@fufesou 

I confirm that this is resolved, thank you
