### ISSUE TITLE
Prompt to obtain administrator privileges when opening the software

### ISSUE THREAD

**Issue by K2M74** [rustdesk/rustdesk#2784]
当软件发送给用户时，由于默认没有获取管理员权限，很多操作无法进行。
我知道可以安装，但需要考虑到一种情况，用户不需要长期使用该软件。
也许可以像Chrome安装时一样，先向用户申请管理员权限，被拒绝后以普通用户权限运行。

---

When the software is sent to the user, many operations cannot be performed because the administrator authority is not obtained by default.
I know it can be installed, but there is a situation that needs to be considered, the user does not need to use the software for a long time.
Maybe it can apply to the user for administrator privileges like when Chrome is installed, and run with ordinary user privileges after being rejected.

**Comment by rustdesk** [comment]
W

**Comment by rustdesk** [comment]
It is designed to run without administrator. Which step stop you run without administrator?

**Comment by rustdesk** [comment]
@21pages follow up this please.

**Comment by 21pages** [comment]
In this way, UAC will pop up every time the user clicks, this is how todesk/sunlogin/teamviewer(admin user) did it.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/70
