### ISSUE TITLE
Unable to establish a connection to a Macbook using Rustdesk despite having permission for screen recording

### ISSUE THREAD

**Issue by andrejtr** [rustdesk/rustdesk#2797]
**Describe the bug you encountered:**
When attempting to connect to a Macbook using Rustdesk, the connection gets established, the operator is prompted for the password, and a screen appears in Rustdesk to accept or decline the connection. However, even though Rustdesk has permission for screen recording, a message appears saying "Connected, waiting for image..." and the connection remains loading indefinitely. This issue occurred despite checking all permission, reviewing the Rustdesk documentation, and attempting to resolve the issue by removing and re-adding Rustdesk to the permissions list, reinstalling, and even trying to connect from a Windows or iPhone device.

<img width="978" alt="image" src="https://user-images.githubusercontent.com/64274971/211620751-c9731c0e-3d1f-413f-9906-f94b1ff8f73c.png">

**Steps to reproduce:**
1. Attempt to connect to a Macbook using Rustdesk from a Windows or iPhone device
2. Enter the password when prompted or click "accept" when the connection request appears
3. Observe the message "Connected, waiting for image..." and an indefinite loading time

**Notes:**
- The issue has been observed on a Macbook running macOs Monterey 12.6
- The issue has been reproduced on a MacBook Pro (13-inch, M1, 2020) running macOs Monterey 12.6
- The issue is not related to permissions or security settings, as these have been checked and confirmed to be correct, Rustdesk has permission for screenrecording
- Attempting to connect to the Macbook through Teamviewer was successful
- The Rustdesk documentation has been reviewed and all steps have been followed as described
- Tried removing Rustdesk from the permissions list and adding it again, no change
- Even when reinstalling Rustdesk, the issue still persists

**Expected result:** 
Establish a successful connection to the Macbook

**Actual result:**
Connection gets established but loading indefinitely, even though Rustdesk has permission for screenrecording

**How did you install `RustDesk`?**
From the official RustDesk website.

**RustDesk version and environment**
1.1.9 for Mac on a MacBook Pro (13-inch, M1, 2020) running macOs Monterey 12.6

**Comment by Zacharybinx34** [comment]
Same problem here

**Comment by rustdesk** [comment]
Try out nightly build please.

**Comment by andrejtr** [comment]
> Try out nightly build please.

Hey there, nothing changed.

I have created a small video where you can see the issue: https://rumble.com/v25tdco-rustdesk-issue-2797.html

**Comment by rustdesk** [comment]
Make sure you can not see anything like this.
![image](https://user-images.githubusercontent.com/71636191/212687533-99a73052-163b-4ac5-858c-7154f90d9f4c.png)

**Comment by andrejtr** [comment]
> Make sure you can not see anything like this in your video,
> 
> ![image](https://user-images.githubusercontent.com/71636191/212687533-99a73052-163b-4ac5-858c-7154f90d9f4c.png)
> 
> 

I did, but there is no way to set the permissions, as you can see in the video, the permissions are set properly.

**Comment by rustdesk** [comment]
https://rustdesk.com/docs/en/manual/mac/

> If you have enabled it in the settings window, but RustDesk still warns. Please Remove RustDesk from the settings windows by the - button, and click on + button, select RustDesk in /Applications.

**Comment by rustdesk** [comment]
close to favor #3261
