### ISSUE TITLE
Failed to obtain screen capture (wayland, on arch/manjora KDE)

### ISSUE THREAD

**Issue by jjgalvez** [rustdesk/rustdesk#2798]
**Describe the bug you encountered:**
I know that wayland isn't aware near ready, but I wanted to see where this project was at. I build directly from git (actually AUR rustdesk-git) and tried to connect from Android. When I try to connect I get the screen asking me to accept the session and once I hit accept, my phone immediately responds with "LoginError" "Failed to obtain screen capture"

...

**What did you expect to happen instead?**
I expected a window to pop up asking me what to share, either the entire screen, or specific window
...

**How did you install `RustDesk`?**
from the AUR rustdesk-git bulding from the [57f9ed3] commit  on Arch Linux, KDE 
---

**RustDesk version and environment**
version 1.2.0
build date 2023-01-10

running on Arch
KDE Plasma 5.26.5
KDE framework 5.101.0
QT 5.15.8
Kernel 6.1.4
Wayland
Intel i7
Graphics Mesa Intel UHD Graphics 620

Happy to provide any additional information which would help, Thanks for a cool project

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
try out nightly build please.

**Comment by jjgalvez** [comment]
> try out nightly build please.

Tried the nightly build and although it does ask which screen to share, I get the same error on my android device and nothing shows

**Comment by jjgalvez** [comment]
> Wayland is working in our test. If it does not work for you, hope you can dig in, you know it is not easy to copy another failure dev env. Wayland support is experimental in our dev plan, we have no way to put too much effort on every distro and env for the time being.

completely understand, right now I am mainly using this to control windows machines. Happy to keep testing.

**Comment by rustdesk** [comment]
Yes, i can reproduce. @fufesou

**Comment by fufesou** [comment]
I'll test later.
Wayland screen share depends on the portal version and the frontend implement of portal.

**Comment by userofryzen** [comment]
The same here with arch, I'll test with manjaro too in a few minutes.

**Comment by fufesou** [comment]
It seems portal does not support some options with KDE.

@jjgalvez @st0nie @userofryzen @rustdesk Can you please download the attached file and run it.

[screenshot.tar.gz](https://github.com/rustdesk/rustdesk/files/10527056/screenshot.tar.gz)

My output
```
Response from DBus: response: OrgFreedesktopPortalRequestResponse { response: 0, results: {"session_handle": Variant("/org/freedesktop/portal/desktop/session/1_644/u1")} }, message: Message { Type: Signal, Path: "/org/freedesktop/portal/desktop/request/1_644/u1", Interface: "org.freedesktop.portal.Request", Member: "Response", Sender: ":1.30", Destination: ":1.644", Serial: 1039, Args: [0, {"session_handle": Variant("/org/freedesktop/portal/desktop/session/1_644/u1")}] }
REMOVE ME ============== 1. begin create capturer
REMOVE ME ============== 2. available_cursor_modes Ok(0)
REMOVE ME ============== 3. path created
Error requesting screen capture via dbus: Unavailable cursor mode 1
```

`2. available_cursor_modes Ok(0)` means available cursor mode of portal is 0.  `Unavailable cursor mode 1`. 

It is strange. https://flatpak.github.io/xdg-desktop-portal/#gdbus-property-org-freedesktop-portal-ScreenCast.AvailableCursorModes

But I'll try to fix this issue by setting cursor mode according to available_cursor_modes.

**Comment by userofryzen** [comment]
@fufesou Response from DBus: response: OrgFreedesktopPortalRequestResponse { response: 0, results: {"session_handle": Variant("/org/freedesktop/portal/desktop/session/1_73/u1")} }, message: Message { Type: Signal, Path: "/org/freedesktop/portal/desktop/request/1_73/u1", Interface: "org.freedesktop.portal.Request", Member: "Response", Sender: ":1.8", Destination: ":1.73", Serial: 195, Args: [0, {"session_handle": Variant("/org/freedesktop/portal/desktop/session/1_73/u1")}] }
REMOVE ME ============== 1. begin create capturer
REMOVE ME ============== 2. available_cursor_modes Ok(7)
You are attempting to capture the cursor under KDE Plasma, this may crash your desktop, see https://bugs.kde.org/show_bug.cgi?id=435042 for details! You have been warned.
REMOVE ME ============== 3. path created
REMOVE ME ============== 4. select source done
Response from DBus: response: OrgFreedesktopPortalRequestResponse { response: 0, results: {} }, message: Message { Type: Signal, Path: "/org/freedesktop/portal/desktop/request/1_73/u2", Interface: "org.freedesktop.portal.Request", Member: "Response", Sender: ":1.8", Destination: ":1.73", Serial: 207, Args: [0, {}] }
REMOVE ME ============== begin start
Response from DBus: response: OrgFreedesktopPortalRequestResponse { response: 0, results: {"restore_token": Variant("cb8c1d01-93b6-4f32-bfec-dd70a7a27b78"), "streams": Variant(InternalArray { data: [[66, {"size": Variant([1680, 1050]), "source_type": Variant(1)}]], inner_sig: Signature("(ua{sv})\0") })} }, message: Message { Type: Signal, Path: "/org/freedesktop/portal/desktop/request/1_73/u3", Interface: "org.freedesktop.portal.Request", Member: "Response", Sender: ":1.8", Destination: ":1.73", Serial: 223, Args: [0, {"restore_token": Variant("cb8c1d01-93b6-4f32-bfec-dd70a7a27b78"), "streams": Variant(InternalArray { data: [[66, {"size": Variant([1680, 1050]), "source_type": Variant(1)}]], inner_sig: Signature("(ua{sv})\0") })}] }
REMOVE ME ============== 333
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Failed to obtain screen capture." }', libs/scrap/examples/screenshot.rs:12:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Abortado (`core' generado)

**Comment by jjgalvez** [comment]
@fufesou 
Response from DBus: response: OrgFreedesktopPortalRequestResponse { response: 0, results: {"session_handle": Variant("/org/freedesktop/portal/desktop/session/1_190/u1")} }, message: Message { Type: Signal, Path: "/org/freedesktop/portal/desktop/request/1_190/u1", Interface: "org.freedesktop.portal.Request", Member: "Response", Sender: ":1.7", Destination: ":1.190", Serial: 665, Args: [0, {"session_handle": Variant("/org/freedesktop/portal/desktop/session/1_190/u1")}] }
REMOVE ME ============== 1. begin create capturer
REMOVE ME ============== 2. available_cursor_modes Ok(7)
You are attempting to capture the cursor under KDE Plasma, this may crash your desktop, see https://bugs.kde.org/show_bug.cgi?id=435042 for details! You have been warned.
REMOVE ME ============== 3. path created
REMOVE ME ============== 4. select source done
Response from DBus: response: OrgFreedesktopPortalRequestResponse { response: 0, results: {} }, message: Message { Type: Signal, Path: "/org/freedesktop/portal/desktop/request/1_190/u2", Interface: "org.freedesktop.portal.Request", Member: "Response", Sender: ":1.7", Destination: ":1.190", Serial: 679, Args: [0, {}] }
REMOVE ME ============== begin start
Response from DBus: response: OrgFreedesktopPortalRequestResponse { response: 0, results: {"restore_token": Variant("d98bbe06-5aa5-446c-8f03-f90ef62e928e"), "streams": Variant(InternalArray { data: [[93, {"size": Variant([2560, 1440]), "source_type": Variant(1)}]], inner_sig: Signature("(ua{sv})\0") })} }, message: Message { Type: Signal, Path: "/org/freedesktop/portal/desktop/request/1_190/u3", Interface: "org.freedesktop.portal.Request", Member: "Response", Sender: ":1.7", Destination: ":1.190", Serial: 691, Args: [0, {"restore_token": Variant("d98bbe06-5aa5-446c-8f03-f90ef62e928e"), "streams": Variant(InternalArray { data: [[93, {"source_type": Variant(1), "size": Variant([2560, 1440])}]], inner_sig: Signature("(ua{sv})\0") })}] }
REMOVE ME ============== 333
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Failed to obtain screen capture." }', libs/scrap/examples/screenshot.rs:12:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: IOT instruction (core dumped)  ./screenshot

**Comment by fufesou** [comment]
@userofryzen @jjgalvez  Thanks. My PR dose not fix your issue from your output.

I'll install arch KDE and Mandarin and try to fix later.

**Comment by fufesou** [comment]
Capturer can be created now, but the images are totally wrong.
It seems hard to support Arch or Manjora KDE now.

deps:
```
pacman -S gst-plugins-base gst-plugin-pipewire
```

https://user-images.githubusercontent.com/13586388/215711876-61d84f4c-f109-43d9-8ed1-597087cfccc9.mp4

**Comment by rustdesk** [comment]
Try out obs on it

**Comment by fufesou** [comment]
> Try out obs on it
obs capture(pipewire) does not work.

@userofryzen  @jjgalvez Hi, how did you enable wayland on manjora KDE? I installed `pacman -S plasma-wayland-session`, maybe it's not a good way. I'm trying Arch linux now.

Can you please test obs as well? Thanks.

```
pacman -S obs-studio
```

If obs works, the result should be like this

https://user-images.githubusercontent.com/13586388/215731382-91aca64b-a9ff-4937-a58e-8b110f1ee875.mp4

**Comment by userofryzen** [comment]
Yes, and obs studio works since you install portal packages. I have it
installed already and working while rust desk doesn't works. Actually I
have TeamViewer and TeamViewer works too with Wayland (arch and manjaro
it's the same almost so... )

**Comment by fufesou** [comment]
My OS seems not installed correctly.

I did not install portal manually. I'll try later.

BTW, I'm using a vm manjora, the default desktop is x11. I switch to wayland by `pacman -S plasma-wayland-session`.

How did you enable wayland?

**Comment by fufesou** [comment]
@userofryzen And can you please try my nightly build? Maybe it works on your OS 😄.
https://github.com/fufesou/rustdesk/releases/tag/nightly

**Comment by userofryzen** [comment]
You should select plasma(wayland) on sddm, at the start before logging in.
You have to install manually portal packages and after that you'll be able
to. I can't test it right now but I think you can do it. If you have any
other questions tell me

**Comment by jjgalvez** [comment]
@fufesou I ran OBS and it works as expected capturing the desktop. I tried the nightly build (AppImage) and it did not work I got the same error as before that it could not create the screen capture.  As for how I enabled wayland, yes I installed the plasma-wayland-session and then selected that as my session when I logged in

**Comment by fufesou** [comment]
I've tried different versions of manjaro, and update all applications. OBS still dose not work. I'm not sure if it is caused by VM.

> I finally got the build to compile and running the compiled version screen capture is working!
@jjgalvez Is the latest rustdesk working? Have you ever install `gstreamer` manually?  `pacman -S gst-plugins-base gst-plugin-pipewire`

**Comment by userofryzen** [comment]
> I've tried different versions of manjaro, and update all applications. OBS still dose not work. I'm not sure if it is caused by VM.
> 
> > I finally got the build to compile and running the compiled version screen capture is working!
> 
> @jjgalvez Is the latest rustdesk working? Have you ever install `gstreamer` manually? `pacman -S gst-plugins-base gst-plugin-pipewire`

It's probably VM related then. Because portals KDE package and portal package is the only things needed that I have to install manually the last time I installed manjaro or arch. I think pipewire has something to be related with drivers and not every driver works, so, VM thing are interferimg with those thing(?)

I'll give a try when I have time

**Comment by jjgalvez** [comment]
> 

yes I have gstreamer and gst-plugin-pipewire both installed

**Comment by fufesou** [comment]
> "cargo build --features hwcodec --release"

@jjgalvez You'd better build flutter version. See https://github.com/rustdesk/rustdesk/blob/master/.github/workflows/flutter-nightly.yml for details. `cargo build` results sciter version, which is not maintained currently.

For debug, you can

```bash
cd flutter && flutter clean && flutter pub get && cargo build --features default,flutter,hwcodec --lib && flutter run -d linux
```

**Comment by jjgalvez** [comment]
Thanks, I'll review the yml file and give the flutter build a try.

**Comment by userofryzen** [comment]
> @fufesou I ran OBS and it works as expected capturing the desktop. I tried the nightly build (AppImage) and it did not work I got the same error as before that it could not create the screen capture. As for how I enabled wayland, yes I installed the plasma-wayland-session and then selected that as my session when I logged in
> 
> I finally got the build to compile and running the compiled version screen capture is working! haven't tried any input yet, I will give that a try later tonight

if you can try the input. I have tested the flatpak version of  rustdesk and it's not working the input( but the screen capture yeah) So no idea of whatever is happening. It would be a help to create a arch install package because I can't compile the bin of rustdesk because of my pc resources.

**Comment by jjgalvez** [comment]
Last night I tested the input from Android to Arch desktop and was able to fully control the desktop. I'm going to try and build the flutter version and will do the same test. FYI I'm now building on full metal no docker or VM if that matters, with rustup from the official repos.  I'll be using the latest flutter from the AUR.

**Comment by rustdesk** [comment]
Input is not working in flatpak / appimage + wayland, this is expected.

**Comment by userofryzen** [comment]
> Input is not working in flatpak / appimage + wayland, this is expected, because wayland input requires root.
shouldn't it in a future be possible to install rustdesk like a flatpak and being able to remote desktop with wayland too?

**Comment by rustdesk** [comment]
> > Input is not working in flatpak / appimage + wayland, this is expected, because wayland input requires root.
> > shouldn't it in a future be possible to install rustdesk like a flatpak and being able to remote desktop with wayland too?

It is up to Flatpak, not us.
