### ISSUE TITLE
Open-source claim is false, server component is paywalled and closed source 

### ISSUE THREAD

**Issue by technodrome** [rustdesk/rustdesk#28]
You claim that rustdesk is "The best open-source remote desktop software, written in Rust." This is not true as you have not published your server component. Without server, you can do the same thing TeamViewer did and simply force users to do what you want in the future as they won't be unable to function without a public server not under your control. 

It is not clear what exactly your server component does as the source code is not public.
Moreover, in order to self-host the server, you require a yearly fee of 199 USD as stated here: https://rustdesk.com/server/

Are you actually planning to make this a truly open-source product or are you just trying to win over users from TeamViewer and co. and later do the same thing as TW? 

Are you planning on publishing the server component code?

**Comment by open-trade** [comment]
maybe in the future.

**Comment by rustdesk** [comment]
"The best open-source remote desktop software" -> "The best open-source remote desktop **client** software

**Comment by ruruiye** [comment]
![image](https://user-images.githubusercontent.com/52643407/119290921-1b9c5c80-bc80-11eb-89b8-f23334b8386e.png)

without license, we can't run this program for free. that's not the real open source. I know earn money from open source is hard, but a better strategy will help this project more successfully.

**Comment by rustdesk** [comment]
> we can't run this program for free

Sorry, forgot to update the website. It is really free before. I will update the website.

**Comment by technodrome** [comment]
Why did you edit and redact my comment?! This is not what you do in github and sure as hell not what you do with OSS! Where did you hear of such practice of removing valid comments because they actually shed light on your shady practices, just to cover up the fact your project is NOT open source? 

My original comment:
_You claim that rustdesk is "The best open-source remote desktop software, written in Rust." This is not true as you have not published your server component. Without server, you can do the same thing TeamViewer did and simply force users to do what you want in the future as they won't be unable to function without a public server not under your control.

It is not clear what exactly your server component does as the source code is not public.
Moreover, in order to self-host the server, you require a yearly fee of 199 USD as stated here: https://rustdesk.com/server/

Are you actually planning to make this a truly open-source product or are you just trying to win over users from TeamViewer and co. and later do the same thing as TW?

Are you planning on publishing the server component code?_

**Comment by technodrome** [comment]
> ![image](https://user-images.githubusercontent.com/52643407/119290921-1b9c5c80-bc80-11eb-89b8-f23334b8386e.png)
> 
> without license, we can't run this program for free. that's not the real open source. I know earn money from open source is hard, but a better strategy will help this project more successfully.

He even edited out my comment which acutally stated they require a payment and that they haven't published server component's source code. It is obviously their goal to push users towards paid subscription, even hiding this fact here on github by editing comments which say so. 

I'd suggest huge caution with this software - they're clearly trying to suppress freedom of speech here.

**Comment by technodrome** [comment]
Will you keep deleting user comments? Wow, what a douchebag!

**Comment by technodrome** [comment]
Will you keep deleting user comments? Wow, what a douchebag!
