### ISSUE TITLE
cannot unlock

### ISSUE THREAD

**Issue by coolit** [rustdesk/rustdesk#281]
Both the controlling and remote side are win10. The remote side has fingerprint login option. 

When the remote side is locked, rustdesk cannot unlock it (at least I don't know how). In the remote side, you can see options to choose from pin, psw and fingerprint. But in the controlling side, you cannot see them, so there is no way to unlock.

Please help.

**Comment by coolit** [comment]
I had viewed #218 before I opened this issue. Seemed different. In my case, rustdesk is installed on both sides. But there seemed to be no way to unlock the remote side.

**Comment by rustdesk** [comment]
> I had viewed #218 before I opened this issue. Seemed different. In my case, rustdesk is installed on both sides. But there seemed to be no way to unlock the remote side.

How do you unlock in local side?

**Comment by rustdesk** [comment]
> you cannot see them

The options are shown in local side, but not shown in remote side? Local picture and remote picture are different?

**Comment by coolit** [comment]
yes, different. In the controlling side, you cannot see the options at all. But it shows normally when I use xxxdesk.

**Comment by coolit** [comment]
I have deleted other options and keep the psw loggin option only. But the problem remains. On the controlling side, you just cannot see any way in. You click anywhere in the locked screeen, nothing happens.

**Comment by rustdesk** [comment]
can you show us the two different pictures? we will try to reproduce the problem.

**Comment by coolit** [comment]
No problem with the latest version of rustdesk

**Comment by coolit** [comment]
Today the problem comes back.  When I tried to click from the controlling side, the remote side has already ready for me to input psw, but no input bar appears in the controlling side.

**Comment by fufesou** [comment]
> Today the problem comes back. When I tried to click from the controlling side, the remote side has already ready for me to input psw, but no input bar appears in the controlling side.

Hi, I'm trying to fix this problem.
But I cannot reproduce on my computers.

The most possible reason is permission. Without installing on computer, rustdesk cannot be granted enough permissions.

And if rustdesk failed to change desktop, error logs will be written.
Would you please send me your logs(shuanglongchen@yeah.net).
Or attach error messages here.
C:\Users\{user}\AppData\Roaming\RustDesk\log

Many thanks!

**Comment by coolit** [comment]
Below is how I could reproduce.
Manually kill all rustdesk processes. Then open rustdesk from start/menu/rustdesk. Then the problem will occur. If I restart my pc, then rustdesk will be started at startup, and now the problem should be gone.
Hopefully it helps.

**Comment by fufesou** [comment]
> Below is how I could reproduce. Manually kill all rustdesk processes. Then open rustdesk from start/menu/rustdesk. Then the problem will occur. If I restart my pc, then rustdesk will be started at startup, and now the problem should be gone. Hopefully it helps.

Yes, it's useful.
Rustdesk start a process as a service. Click rustdesk exe will not start the service.

I think current service mechanism is not friendlly enough. I hope it can be better in the future.

For now, just do not kill the service process. It do not take up many resources.
