### ISSUE TITLE
I build flutter and I can't. because this issue, I don't know why

### ISSUE THREAD

**Issue by svn-nguyen-minh-hai** [rustdesk/rustdesk#2814]
**Describe the bug you encountered:**
I build flutter and I can't. because this issue, I don't know why
![Screen Shot 2023-01-13 at 05 25 20](https://user-images.githubusercontent.com/113173552/212194146-7dd9a392-2a8b-4679-9248-47acbbd88694.png)
![Screen Shot 2023-01-13 at 05 29 24](https://user-images.githubusercontent.com/113173552/212194660-f96cec1e-f240-4936-8299-109c70a26359.png)

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

**Comment by rustdesk** [comment]
#763
