### ISSUE TITLE
In nightly versions is not possible to setup service (MacOs)

### ISSUE THREAD

**Issue by reyesmfabian** [rustdesk/rustdesk#2819]
Describe the bug you have encountered:** ** ** **

On MacOs with nightly versions it is not possible to install as a service, you always need to have the application open for it to work.

**What would you expect to happen instead?

That the application runs as a service and is always in the background listening.

**How did you install `RustDesk`?

Nightly version directly from Github

---

**Version and environment of RustDesk

Mac M1, Ventura 13.1, Rustdesk 1.2.0

**Comment by rustdesk** [comment]
try out today's build please.

**Comment by sj6219** [comment]
A similar phenomenon is appearing for me. My execution environment is...
mac mini m1 chip ventura 13.1 입니다.
Once the program is running as a service, it cannot be run on finder or launchpad as follows.
So I can't see the gui screen.
The same error occurs when running from the terminal.
However, if you do the following, it will run normally.A similar phenomenon is appearing for me. My execution environment is...
mac mini m1 chip ventura 13.1 입니다.
Once the program is running as a service, it cannot be run on finder or launchpad as follows.

![Untitled](https://user-images.githubusercontent.com/3592759/212575720-d08a7341-d7fb-47f5-bd4c-ec810c8be488.png)

So I can't see the gui screen.
The same error occurs when running from the terminal.

![Untitled 4](https://user-images.githubusercontent.com/3592759/212575843-ebeb8cd7-7e2d-4abd-8e3b-a8ee23435e8f.png)

However, if you do the following, it will run normally.

![Untitled 6](https://user-images.githubusercontent.com/3592759/212575950-c7433c88-091c-4042-8c88-dfd378dcae31.png)

**Comment by rustdesk** [comment]
Thanks, @Kingtous
