### ISSUE TITLE
dxgi EnumOutputs

### ISSUE THREAD

**Issue by xiaoshengduan** [rustdesk/rustdesk#282]
抓屏程序是运行在system用户session0下吗，
https://docs.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgiadapter-enumoutputs?redirectedfrom=MSDN
注意  如果您在会话 0 进程中调用此 API，它将返回DXGI_ERROR_NOT_CURRENTLY_AVAILABLE。
DXGI_ERROR_NOT_CURRENTLY_AVAILABLE。

**Comment by rustdesk** [comment]
windows.rs
