### ISSUE TITLE
Keyboard issues on Manjaro KDE: local keyboard on the PC will completely stop working

### ISSUE THREAD

**Issue by KB8DOA** [rustdesk/rustdesk#2824]
**Describe the bug you encountered:**
When rustdesk is running, the keyboard on the PC will completely stop working for ALL local apps and remote sessions until rustdesk is closed.
...

**What did you expect to happen instead?**
For RustDesk not to halt the keyboard
...

**How did you install `RustDesk`?**
AUR Package = rustdesk-nightly

---

**RustDesk version and environment**
RustDesk v1.2.0 2022-12-21 06:42
Manjaro (KDE Plasma v5.26.4 Kernel v6.1.1-1)
HP Spectre x360 14" (2022) Laptop
Intel i7-1255U = 12 cores

**Comment by rustdesk** [comment]
how about latest nightly build? 

@fufesou #1547

**Comment by rustdesk** [comment]
rustdesk-1.2.0-0-x86_64.pkg.tar.zst

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-0-x86_64.pkg.tar.zst

**Comment by KB8DOA** [comment]
> how about latest nightly build?
> 
> @fufesou #1547

It seems that the file you sent me (build 2023-01-17) resolved it.
Perhaps someone is not maintaining/updating the rustdesk-nightly AUR ?

**Comment by rustdesk** [comment]
we do not maintain aur
