### ISSUE TITLE
Nightly Recent Sessions empty

### ISSUE THREAD

**Issue by sinyb** [rustdesk/rustdesk#2831]
**Describe the bug you encountered:**

In Rustdesk Nightly, Recent Sessions tab is empty

**What did you expect to happen instead?**

To see recent sessions, just like in 1.1.9 that I have installed via rpm

Sessions established through Nightly do get saved, and I can see them in 1.1.9

**How did you install `RustDesk`?**

1.1.9 is from an unofficial opensuse repo, installed as rpm
Nightly is Appimage from Github
Also tried Nightly fedora/centos rpm with same result

---

**RustDesk version and environment**

Nightly 2023-01-16, but also previous versions. I don't remeber this ever working in Nightly (ever=2-3 months)
Running on opensuse Tumbleweed and LEAP 15.4

**Comment by rustdesk** [comment]
I belive it is file write permission issue or something unexpected. Sorry for that, we have no way to test all env.

**Comment by rustdesk** [comment]
recent sessions are stored under `~/.config/rustdesk/peers/`, make sure RustDesk has permission to create this directory and write file there.

**Comment by sinyb** [comment]
> Recent sessions are stored under `~/.config/rustdesk/peers/`, make sure RustDesk has permission to create this directory and write files there.

Yes, I found them there, RustDesk Nightly CAN and DOES write there, but it does not display them
I have all the premissions (just checked again): rwx on directory, rw on .toml files

strace shows only access to file "RustDesk2.toml" inside "/home/$USER/.config/rustdesk/", nothing else.

**Comment by rustdesk** [comment]
Hope some one can dig in if encounting the same issue, code of  reading peers is here.

https://github.com/rustdesk/rustdesk/blob/08b8f403975a16f6eeeff2afeb6f11f32e29384d/libs/hbb_common/src/config.rs#L922

**Comment by sinyb** [comment]
I have copied all peers to a Windows machine, and latest Nightly can see them just fine there.

**Comment by rustdesk** [comment]
So there is text encoding/decoding issue on your env.

**Comment by sinyb** [comment]
> So there is text encoding/decoding issue on your env.

OK, I can confirm that this is working just fine in a new install of opensuse tumbleweed, both .AppIMage and .rpm.

It would be nice to know what exactly is wrong with encoding, because I coud not find anything different...

**Comment by sinyb** [comment]
Sorry to spam, but it seems that this is working fine with rpm from Kingtous

**Comment by morphx666** [comment]
I just installed nightly 2023-02-16 05:38 on Windows, and every time I run it, it deletes the contents of the `%AppData%\RustDesk\config\peers` folder. Any idea why this is happening?

**Comment by rustdesk** [comment]
> , it deletes the contents of the `%AppData%\RustDesk\config\peers` 

Wierd, we dev every day, also impossible to miss this bug which can be seen once we open the window.

**Comment by morphx666** [comment]
@rustdesk Would you like me to record a video? Not sure if that could help...

**Comment by rustdesk** [comment]
I and @fufesou had this issue also today and yesterday, we will investigate in.

**Comment by fufesou** [comment]
Some config fields do not support default empty config.
It causes the parsing error, and then removing the config files.

**Comment by rustdesk** [comment]
Close since PR merged
