### ISSUE TITLE
Rustdesk 1.2 Nightly doesnt work with Windows 7 32-Bit

### ISSUE THREAD

**Issue by bensende** [rustdesk/rustdesk#2833]
Hi,
I was trying to solve the problem with AltGr Key on german Keyboard with nightly release from today but unfortunately it's not possible to install 1.2.0 on Windows 7 32Bit client.
Thank you!

![WrongVersion](https://user-images.githubusercontent.com/122827908/212756138-26968650-23f4-4ca9-b1d9-6dff8184a7da.gif)

**Comment by rustdesk** [comment]
flutter doesnot support 32

**Comment by rustdesk** [comment]
Close as wontfix, phasing out official win7 support.

**Comment by Chapra78** [comment]
Hello guys,

We have deployed a self hosted Ruskdesk server (192.168.1.10) in our LAN.
Then we have build the Rustdesk Client using the sourcecode downloaded from "https://github.com/rustdesk/rustdesk" and by following the steps mentioned at https://github.com/infiniteremote/installer/files/14814894/Setup_rustdesk_development_on_Windows.pdf
We have hardcoded our server IP (192.168.1.10) and Rustdesk server key in the source code.
The client is working successfully on all our 64 bit windows machines.Unfortunately we are having issues running the Rustdesk client on 32 bit windows machines. Hence please let us know how to resolve this issue and how to build the client for running on 32 bit Windows machines.
