### ISSUE TITLE
tcp tunneling doesnt work correctly with multiple tunnels

### ISSUE THREAD

**Issue by phr34k** [rustdesk/rustdesk#2835]
**Describe the bug you encountered:**

When using tcp tunneling feature with multiple tunnels only one of the tunnels gets picked up. I dont recall if its the first or last one but only one of the tunnels was working for me. 

**How did you install `RustDesk`?**

Windows installer from the website

---

**RustDesk version and environment**

Windows 10 Pro

**Comment by rustdesk** [comment]
it will be refactored in the future, current implementation will not be maintained any more.

**Comment by mherrmann3** [comment]
(I also had similar issues; I found that it it works well for a while (3 ports), but eventually, all local ports are forwarded to the last-specified remote port.)

Looking forward to the new implementation!

**Comment by MikeT-KBU** [comment]
Any new infos? It is been over 2 Years already. We must use Teamviewer and can't switch to RustDesk before the Port Forwarding Feature is working correctly.

**Comment by rustdesk** [comment]
No plan, port forwarding is not our priority, you might choose the other product.

**Comment by mherrmann3** [comment]
@MikeT-KBU: for me it works very well and stable as long as you don't set up more than 3 port forwards, see https://github.com/rustdesk/rustdesk/issues/487#issuecomment-2564070164.
