### ISSUE TITLE
keyboard doesnt work correctly

### ISSUE THREAD

**Issue by phr34k** [rustdesk/rustdesk#2837]
**Describe the bug you encountered:**

When running rustdesk on windows the application doesnt allow certain keys to work correctly in other programs. For example when I run rustdesk on windows, and have sublime open I can't type   `'` , `"` or `^` (shift, alpha 6). The moment I close rustdesk those keys work as intended again, I believe some of these keys also didn't work on the remote controlled machine. 

**How did you install `RustDesk`?**

Windows installer from website

---

**RustDesk version and environment**

Windows 10 pro

**Comment by rustdesk** [comment]
try out nightly build please.

**Comment by rustdesk** [comment]
#1547
