### ISSUE TITLE
==> ERROR: rustdesk-bin is not available for the 'aarch64' architecture.

### ISSUE THREAD

**Issue by Ananthageethan** [rustdesk/rustdesk#284]
=========================================================
In raspberry pi 4, MANJARO OS,  I have tried the below suggestions, but have not succeeded so far. I will be grateful to the experts in this community if they can help me install Rustdesk software.

Rustdesk installation Through GUI:

    Went to https://github.com/rustdesk/rustdesk/releases
    Downloaded - rustdesk-1.1.8-manjaro-arch.pkg.tar.zst
    Right click - Clicked on Open with Software
    Clicked on Install button
    Authentication Required - Put the password.
    Installing Tab suddenly appear and disappeared.
    No any other improvement.

   2.Installation through terminal :

    sudo pamac build rustdesk-bin
    sudo pamac build rustdesk

    Encountered the following error:
-----------------------------------------------------------
[pi@anandh-pc ~]$ pamac build rustdesk-bin
Preparing...
Checking rustdesk-bin dependencies...
Resolving dependencies...
Checking inter-conflicts...

To install (10):
  compiler-rt   12.0.1-2        (Required By: rustdesk-bin)  extra      1.5 MB
  xdotool       3.20210903.1-1  (Required By: rustdesk-bin)  community  64.7 kB
  jsoncpp       1.9.4-1         (Required By: rustdesk-bin)  extra      122.0 kB
  libuv         1.42.0-1        (Required By: rustdesk-bin)  extra      219.1 kB
  yasm          1.3.0-4         (Required By: rustdesk-bin)  extra      604.9 kB
  rhash         1.4.2-1         (Required By: rustdesk-bin)  extra      160.7 kB
  cmake         3.21.3-1        (Required By: rustdesk-bin)  extra      11.7 MB
  nasm          2.15.05-1       (Required By: rustdesk-bin)  extra      374.4 kB
  rust          1:1.55.0-1      (Required By: rustdesk-bin)  extra      60.4 MB
  clang         12.0.1-1        (Required By: rustdesk-bin)  extra      34.6 MB
To build (1):
  rustdesk-bin  1.1.8-1                                      AUR

Total download size: 109.8 MB
Total installed size: 608.1 MB

Edit build files : [e] 
Apply transaction ? [e/y/N] y

Downloading compiler-rt (12.0.1-2)...                                           
Downloading xdotool (3.20210903.1-1)...                                         
Downloading jsoncpp (1.9.4-1)...                                                
Downloading libuv (1.42.0-1)...                                                 
Downloading yasm (1.3.0-4)...                                                   
Downloading rhash (1.4.2-1)...                                                  
Downloading cmake (3.21.3-1)...                                                 
Downloading nasm (2.15.05-1)...                                                 
Downloading rust (1:1.55.0-1)...                                                
Downloading clang (12.0.1-1)...                                                 
Checking keyring...                                                      [10/10]
Checking integrity...                                                    [10/10]
Loading packages files...                                                [10/10]
Checking file conflicts...                                               [10/10]
Checking available disk space...                                         [10/10]
Installing compiler-rt (12.0.1-2)...                                      [1/10]
Installing xdotool (3.20210903.1-1)...                                    [2/10]
Installing jsoncpp (1.9.4-1)...                                           [3/10]
Installing libuv (1.42.0-1)...                                            [4/10]
Installing yasm (1.3.0-4)...                                              [5/10]
Installing rhash (1.4.2-1)...                                             [6/10]
Installing cmake (3.21.3-1)...                                            [7/10]
Installing nasm (2.15.05-1)...                                            [8/10]
Installing rust (1:1.55.0-1)...                                           [9/10]
Installing clang (12.0.1-1)...                                           [10/10]
Running post-transaction hooks...
Arming ConditionNeedsUpdate...                                             [1/4]
Updating icon theme caches...                                              [2/4]
Updating the desktop file MIME type cache...                               [3/4]
Updating the MIME type database...                                         [4/4]
Cloning rustdesk-bin build files...
Generating rustdesk-bin information...

Building rustdesk-bin...
==> ERROR: rustdesk-bin is not available for the 'aarch64' architecture.
[pi@anandh-pc ~]$ 

--------------------------------------------------------------------------------------------------------------
help me install this software in manjaro 64bit os (Raspberrypi-4 board)
[pi@anandh-pc ~]$ uname -m
aarch64

**Comment by rustdesk** [comment]
No arm support yet, because i have no arm machine.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/175

**Comment by rustdesk** [comment]
Try out [raspberry-armhf.deb](https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-raspberry-armhf.deb) please.
