### ISSUE TITLE
Clipboard only transfers text

### ISSUE THREAD

**Issue by attikov** [rustdesk/rustdesk#2842]
**Describe the bug you encountered:**

Clipboard transfers only the TEXT part

**What did you expect to happen instead?**

Clipboard transfers as it is

**How did you install `RustDesk`?**

downloaded precompiled installer from the web

**RustDesk version and environment**

1.1.9

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/683
