### ISSUE TITLE
Allow direct connect to {hostname}:{port}

### ISSUE THREAD

**Issue by AutumnSun1996** [rustdesk/rustdesk#2847]
Currently, all the clients only supports direct connection to {ip}:{port} format, and lacks support for {hostname}:{port} format.

I have a pc with dynamic public ip, which will be bound to a hostname via ddns, and I want to connect to it with direct connection.
It will be really convenient to be able to connect with {hostname}:{port}.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/126

**Comment by AutumnSun1996** [comment]
Got it. Will you accept a PR for this feature?

**Comment by rustdesk** [comment]
It is not code issue, this PR is super simple.

**Comment by rustdesk** [comment]
If you wanna submit PR, I wish this feature is turned off by default.

**Comment by AutumnSun1996** [comment]
> If you wanna submit PR, I wish this feature is turned off by default.

This feature should only include changes in client side.
For server side, a security warning for 'Direct Access via IP' may be a better choice? (like when user first enable direct access) 
There should be little difference to access the direct connection port by IP or hostname.
It's also possible use hostname in intranet, like when there are a lot of machines.

And, expose the port to public network requires some extra configs at the router side, and I think anyone can do that should have some understanding of the security impact.

**Comment by rustdesk** [comment]
But how do you make sure the domain name does not conflict with custom id.

**Comment by AutumnSun1996** [comment]
not quite sure, but should be a similar method to distinguish {ip}:{port} format from custom id.
is there any restriction on custom id, like some forbidden characters?

**Comment by rustdesk** [comment]
custom id has format limit in front end, but on backend, it has no limit.

**Comment by rustdesk** [comment]
Force using port together with domain is a good way, then you need to define a url regex following with `:port`.

**Comment by AutumnSun1996** [comment]
Current implement use regex to check ipv4 addr and ipv6 addr.
Regex for domain is likely to catch some custom ids, `{domain}:{port}` should a good choice.

If we need more confidence, somthing like `rustdesk://hostname:port` should be enough

**Comment by rustdesk** [comment]
url regex plus :port is enough.
