### ISSUE TITLE
Connection type indicator

### ISSUE THREAD

**Issue by Oceanwatcher** [rustdesk/rustdesk#2852]
It would be nice to have something that let ut know if hole punch was successful or if the traffic is being relayed. A little button or similar that goes green for direct and yellow for relayed?

You can get a really cheap VPS these days to host the relay server, but there is always a limit on traffic. The Oracle Cloud "always free tiear" gives you 0.48 GB of traffic. Not much, but as long as hole punch is successful, it could actually be enough if you don't support a lot of computers. So it is worth knowing what kind of connection we have.

**Comment by rustdesk** [comment]
There is.

**Comment by Oceanwatcher** [comment]
> There is.

Great. Now we just need to know where it is ;-)

**Comment by rustdesk** [comment]
There is a shield icon, please pay attention.

**Comment by rustdesk** [comment]
![image](https://user-images.githubusercontent.com/71636191/213077844-7053f9dc-3dce-420c-878c-01d457211495.png)

**Comment by Oceanwatcher** [comment]
> There is a shield icon, please pay attention.

There is no mention of this in the docs. And the docs does not even have a Windows section.

One more thing: Your tone in the answer is in violation of your own code of conduct.

Demonstrating empathy and kindness toward other people
Being respectful of differing opinions, viewpoints, and experiences
Giving and gracefully accepting constructive feedback

**Comment by rustdesk** [comment]
Sorry for my bad English if you have any misunderstanding.

**Comment by rustdesk** [comment]
BTW, welcome contribution to docs. https://github.com/rustdesk/doc.rustdesk.com

**Comment by Oceanwatcher** [comment]
> BTW, welcome contribution to docs. https://github.com/rustdesk/doc.rustdesk.com

I will actually consider that :-)

> Sorry for my bad English if you have any misunderstanding.

The problem was not any misunderstanding because of bad English. It was the fact you told me to "pay attention". That is rude and is especially bad as there is no explanation of this anywhere I can find. But I will try to put together some things for the documentation myself :-)

**Comment by Oceanwatcher** [comment]
A green shield will normally indicate that the connection is fully encrypted. Not if the connection is direct or is being relayed.

**Comment by RichardFevrier** [comment]
Why did you close this issue @rustdesk ?
