### ISSUE TITLE
macOS->Target Auto-capitalizes Keyboard Input

### ISSUE THREAD

**Issue by aidan-gibson** [rustdesk/rustdesk#2863]
**Describe the bug you encountered:**
macOS->Target Computer (tested Windows 11, Arch Linux, Kubuntu) auto-capitalizes the first letter of the first word of keyboard input. Inconvenient for terminal commands etc. 

I believe this is default behavior for macOS in general, but I have this disabled via System Settings > Keyboard > Text Input > Input Sources > Edit > Untoggle 'Capitalize words automatically'
...

**How did you install `RustDesk`?**

GitHub release

---

**RustDesk version and environment**
Version 1.1.9 (20220610.104829)
Apple M1 Max, Ventura 13.1

**Comment by aidan-gibson** [comment]
The relevant setting for macOS automatic capitalization can also been seen via 
`defaults read NSGlobalDomain NSAutomaticCapitalizationEnabled`. Running that command returns `0` on my machine.

**Comment by rustdesk** [comment]
try out nightly build please

**Comment by aidan-gibson** [comment]
Keyboard doesn't work at *all* in nightly 😳

**Comment by rustdesk** [comment]
Make sure you can not see below things in the main window.
![image](https://user-images.githubusercontent.com/71636191/213858215-00408a39-7496-4529-a2bc-367e52f865dc.png)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2797#issuecomment-1384720665
