### ISSUE TITLE
Address Book

### ISSUE THREAD

**Issue by axel9546** [rustdesk/rustdesk#287]
Would it be possible to locally backup a copy of our connected PC's ID list, as an address book, and restore it to another PC using RustDesk, to avoid new configuration each time?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/262

**Comment by rustdesk** [comment]
C:\Users\foo\AppData\Roaming\RustDesk\config\peers\

**Comment by henriquelucas** [comment]
Is it also possible on android?
