### ISSUE TITLE
Text color issue on password requried dialogue

### ISSUE THREAD

**Issue by ForsakenRei** [rustdesk/rustdesk#2872]
**Describe the bug you encountered:**

Not sure if it is intended but the text on password requried dialogue now has a mixed black and white when using dark theme. I didn't remember this from earlier nightly release? 

![NXZW}~G21 4( ILILER~D(Q](https://user-images.githubusercontent.com/23041178/213608208-a681f072-5c37-41ba-8fe3-e524462309d5.png)

**What did you expect to happen instead?**
Maybe use a color relatively easier to see for `Enter your password` and `Remember password`?

**How did you install `RustDesk`?**

Github release installation

**RustDesk version and environment**
nightly release build 2023-01-20, Windows 10

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
BTW, in the dark mode, the border color of outlined button ("cancel") is a little dark.
