### ISSUE TITLE
There is a problem inserting ctrl+alt+delete in the nightly version

### ISSUE THREAD

**Issue by youhers** [rustdesk/rustdesk#2875]
**Describe the bug you encountered:**

...Control 2 clients at the same time, and the first client clicks Ctrl+Alt+Delete to receive a command request, but the second client receives a command request

**What did you expect to happen instead?**

...You should switch and click this command, which should be executed to the corresponding client, not another client

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

Daily nightly version

**Comment by youhers** [comment]
![截图_20230120135505](https://user-images.githubusercontent.com/106003909/213627418-bdde8427-eefa-4b13-b190-36ac86ffeda3.gif)

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
@fufesou you need to test this thorougly, not only ctrl-alt-del

**Comment by fufesou** [comment]
@youhers Thanks for your feedback.

https://github.com/rustdesk/rustdesk/pull/2880
