### ISSUE TITLE
Unable to connect (rustdesk 1.19, timeout/deadline has elapsed)

### ISSUE THREAD

**Issue by konstantin3002** [rustdesk/rustdesk#2877]
Hey there! Encountered a connection problem with rustdesk 1.19 (regular and nightly) unable to connect to anything, message being timeout/deadline has elapsed (nightly and regular respectively).

Clients: win10 x64 on both ends, no custom server, been able to connect every day untill 18.01.2023

Able to connect to the target via phone using the same WiFi, unable to connect via web.rustdesk from current PC.

Problem persisted after multiple restarts, disabling firewall and switching to an earlier rustdesk version. 

Anydesk and other remote access programs work fine.

Logs attached
[rustdesk_rCURRENT.log](https://github.com/rustdesk/rustdesk/files/10465108/rustdesk_rCURRENT.log)

**Comment by rustdesk** [comment]
duplicate #732

**Comment by konstantin3002** [comment]
Oh, and I also tried to Enable Direct IP Access. Made no difference

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1597#issuecomment-1432517984

**Comment by konstantin3002** [comment]
An issue remains with thte latest nightly build, the message is the same both in portable try and when fully installed.
Logs attached:
[rustdesk_rCURRENT.log](https://github.com/rustdesk/rustdesk/files/10909171/rustdesk_rCURRENT.log)

**Comment by yaroz** [comment]
In case anyone runs into this.. I just upgraded all of our servers to the latest nightly build and got this error on all of them.  I uninstalled the client, then reinstalled the latest fresh, and it fixed the issue.
