### ISSUE TITLE
Chain control

### ISSUE THREAD

**Issue by attikov** [rustdesk/rustdesk#2878]
I can't control computers in a chain. I can do it with TeamViewer.
RustDesk does no allow to control its client on a remote machine to connect to one of is entry.
Nonsense.
Nonsense as I can copy the peer files.

**Comment by brtwrst** [comment]
This is quite ridiculous indeed.
It only blocks mouse input and if you just use the keyboard to navigate the remote rustdesk window you can enter an ID and connect to another machine without any issue.
Even if the windows is "greyed out" because you have your cursor above it.

**Comment by attikov** [comment]
Haha, thx for the hint Bratwurst!

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4570#issuecomment-1586865401 https://github.com/rustdesk/rustdesk/releases/nightly

**Comment by vaab** [comment]
@brtwrst Thanks, keyboard naviguation works. But is still very cumbersome : Tab navigation is not really well supported (a number of element are not properly highlighted).

I don't understand the answer given by @rustdesk (that seem totally unrelated as far as I understand), and the closing as `completed`. I'm using latest version and experience the same issue.

What is the rationale to prevent chaining ? this seems to have been added intentionally.
