### ISSUE TITLE
Failed to connect to Rendezvous server from iOS / iPadOS over cellular 

### ISSUE THREAD

**Issue by OccultWarlock** [rustdesk/rustdesk#288]
While on cellular data, iOS and iPadOS app cannot connect to a server. Switching over to wifi allows a connection though. See attached video. 

https://user-images.githubusercontent.com/1431774/141220229-43f476d9-d86e-41c7-858b-a646d2e2cb8b.MOV

**Comment by rustdesk** [comment]
Thx

**Comment by rustdesk** [comment]
#3688
