### ISSUE TITLE
Rustdesk is unable to compile/build on windows 10 & Ubuntu. Magnum-Opus & Scrap library error.

### ISSUE THREAD

**Issue by 997123** [rustdesk/rustdesk#2881]
![photo_2023-01-18_12-20-58](https://user-images.githubusercontent.com/122609560/213710929-e37e46cf-844a-4037-96ca-d02e9d5b95a4.jpg)
![photo_2023-01-18_12-20-52](https://user-images.githubusercontent.com/122609560/213711489-74959f76-b369-468a-b0cb-4ee06db68f21.jpg)

Photos seen above represent two similar problems with which i have fought for few days already. I have tried two approaches, first on windows 10 64 bit, second on Ubuntu 20.04 64bit. The issues are very alike due to the fact that in both situations the origin of error is probably the same. I suspect that the main issue is scrap itself.

I need help with compiling and building rustdesk for windows and linux. I have tried to handle it myself, with no effects.

Here is what i have done in exact order in which it was done in both cases.

On Windows: (https://rustdesk.com/docs/en/dev/build/windows/)
1.
git clone https://github.com/microsoft/vcpkg
cd vcpkg
git checkout 2021.12.01
cd ..
vcpkg/bootstrap-vcpkg.bat
export VCPKG_ROOT=$PWD/vcpkg
vcpkg/vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static
2. add System environment variable VCPKG_ROOT=\vcpkg
3. I have downloaded scritter.dll
4. add System environment variable LIBCLANG_PATH=<llvm_install_dir>/bin
5. git clone https://github.com/rustdesk/rustdesk
cd rustdesk
mkdir -p target/debug
mv sciter.dll target/debug
6. cargo run

On step 6th, i have encoutered an error which was presented above. I tried to solve it. The only information i could find was to check whether libraries were properly installed. In fact, they were properly installed. I even reinstalled everything and did anything necessary to make it work. But unfortunately, it didn't.

Then i decided to try it on linux. I was using oracle virtual box to install ubuntu. Yet again, here i present what i have done in exact order in which it was done.

Linux Ubuntu 20.04 64bit (https://rustdesk.com/docs/en/dev/build/linux/)

1.sudo apt install -y g++ gcc git curl wget nasm yasm libgtk-3-dev clang libxcb-randr0-dev libxdo-dev
libxfixes-dev libxcb-shape0-dev libxcb-xfixes0-dev libasound2-dev libpulse-dev cmake
2.git clone https://github.com/microsoft/vcpkg
cd vcpkg
git checkout 2021.12.01
cd ..
vcpkg/bootstrap-vcpkg.sh
export VCPKG_ROOT=/vcpkg
vcpkg/vcpkg install libvpx libyuv opus
3. Here another wild error appeared:
![photo_2023-01-18_12-24-50](https://user-images.githubusercontent.com/122609560/213712210-6751bd17-9ad0-4e44-9b38-53708250ae94.jpg)

I have managed to solve it by using : sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
4.curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs/ | sh

Then according to instruction:

source $HOME/.cargo/env
git clone https://github.com/rustdesk/rustdesk
cd rustdesk
mkdir -p target/debug
wget https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin.lnx/x64/libsciter-gtk.so
mv libsciter-gtk.so target/debug
VCPKG_ROOT=$HOME/vcpkg cargo run
5. After using cargo run it returns me error presented at the top of the thread.

I would appreciate any form of help, it is really important to me to solve this problem.

**Comment by rustdesk** [comment]
#763
