### ISSUE TITLE
In nightly version, triple clicking left mouse button doesn't select entire ID in input field

### ISSUE THREAD

**Issue by rakleed** [rustdesk/rustdesk#2886]
**Describe the bug you encountered:**

In the nightly version 1.2.0, triple clicking the left mouse button does not select the entire ID in the input field.

**What did you expect to happen instead?**

By triple clicking the left mouse button, the entire ID is selected in the input field, this works in 1.1.9. Most likely in 1.2.0 this field is not considered as one line, but as several separate lines, since selecting the entire ID with `Ctrl+A` will work.

**How did you install `RustDesk`?**

GitHub release nightly

---

**RustDesk version and environment**

RustDesk 1.2.0 build date 2023-01-20 02:36
Windows 11 v. 22H2/macOS 13.1

**Comment by rustdesk** [comment]
https://github.com/flutter/flutter/issues/63576

**Comment by rustdesk** [comment]
@21pages we need to handle tripple click by ourselves.

**Comment by rustdesk** [comment]
@21pages I added a work around, let's ignore this issue, just wait for flutter's fix.

**Comment by rustdesk** [comment]
https://github.com/flutter/flutter/pull/119046

**Comment by rustdesk** [comment]
fixed in flutter master
