### ISSUE TITLE
Client does not handle all Alt Codes

### ISSUE THREAD

**Issue by DreamsVoid** [rustdesk/rustdesk#289]
**Describe the bug you encountered:**
I am unable to send many different alt codes for example: `alt + 129`
Common alt codes such as `alt+0153` do work.

**What did you expect to happen instead?**
I was expecting `ü` to be appear on the client display.

**How did you install `RustDesk`?**
Installed Version: [1.1.8 x64](https://github.com/rustdesk/rustdesk/releases/tag/1.1.8)
Binary Downloaded: rustdesk-1.1.8-windows_x64.zip 
Portable mode: No

**RustDesk version and environment**
Operating System: Windows 10
HBBR/HBBS: Default

This applys to both host and client devices.

Steps to reproduce:
1. Connect from your client to your host,
2. Open up a text input field, e.g. Notepad
3. Type an alt code e.g. `alt+129` 
4. Observe nothing turning up in the text field

N.b. You can type and transmit the alt codes via the built in chat function.

**Comment by rustdesk** [comment]
> brazil keyboard usually have that c on the right of the "L" key where we have our ";", so it's a physical key for them, but on my french keyboard it's an alt code, so I think they still use alt code for that c even if it's a physical key

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/292
