### ISSUE TITLE
The client cannot be installed on the PC

### ISSUE THREAD

**Issue by youhers** [rustdesk/rustdesk#2891]
**Describe the bug you encountered:**

...The nightly version cannot be installed ，and must carry the command，Clicking Install has no effect，The shortcut must be used with --install to install
**What did you expect to happen instead?**

...It should be clickable to install

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

1.2.0Nightly version win10

**Comment by youhers** [comment]
![截图_20230121094119](https://user-images.githubusercontent.com/106003909/213834884-9d323e3d-6c76-4dcc-91f8-9ea9b4aab301.gif)

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
@Kingtous it may be related to your last commit

**Comment by Kingtous** [comment]
> @Kingtous it may be related to your last commit

Yes, Let's figure it out.

**Comment by youhers** [comment]
happy new year

**Comment by youhers** [comment]
@Kingtous @rustdesk happy new year

**Comment by rustdesk** [comment]
Happy new year!
