### ISSUE TITLE
Flip access fails and stutters abnormally

### ISSUE THREAD

**Issue by youhers** [rustdesk/rustdesk#2893]
**Describe the bug you encountered:**

...Night version, after controlling the client, click to flip the access, and connect to the client again after the access, it will be very stuttering, and you must restart the rustdesk service to resume normal operation

**What did you expect to happen instead?**

...There shouldn't be such a serious delay

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

win10  1.21 Night Edition

**Comment by youhers** [comment]
![截图_20230121140402](https://user-images.githubusercontent.com/106003909/213846127-a6319922-1065-43aa-b374-06e4a0fff67f.gif)

**Comment by rustdesk** [comment]
@21pages

**Comment by 21pages** [comment]
> after controlling the client, click to flip the access, and connect to the client again after the access

Click the Elevate button, then it will be unresponsive than normal?
![1674287655080](https://user-images.githubusercontent.com/14891774/213852380-58866456-cdfc-49d6-b0c9-0d041894231b.png)

**Comment by youhers** [comment]
I set the password to enter. Client A connects to Client B, and the operation on Client A flips over. Then Client B connects to Client A. After Client A clicks to close the connection, it will be slow to connect to Client B. After connecting, it will be stuck seriously and basically unavailable. You must restart the trustdesk service before it can be used normally

**Comment by rustdesk** [comment]
Yes, it has nothing to do with elevation.

**Comment by 21pages** [comment]
reproduced

**Comment by rustdesk** [comment]
@youhers could you try out latest nightly build?

**Comment by youhers** [comment]
Ok, I'll test it. It's hard

**Comment by youhers** [comment]
The problem has been solved. Thank you very much
