### ISSUE TITLE
Accept dialog box exception after connection

### ISSUE THREAD

**Issue by youhers** [rustdesk/rustdesk#2896]
**Describe the bug you encountered:**

...When the mobile phone connects to the computer client, the reception prompt is usually white. You need to move the mouse over the white box to display it normally. Sometimes it is normal. I don't know what the situation is

**What did you expect to happen instead?**

...It should work properly

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

win 10 1.2.0 1.21Night version

**Comment by youhers** [comment]
![截图_20230121181249](https://user-images.githubusercontent.com/106003909/213862492-008ee060-aeea-4ac3-abce-f297670f4a4c.gif)

**Comment by rustdesk** [comment]
@21pages
