### ISSUE TITLE
UI won't become active again if the window focus mode is set to 'hover'. 

### ISSUE THREAD

**Issue by DieSchoeneWolke** [rustdesk/rustdesk#2897]
**Describe the bug you encountered:**

Worked for a bit now but it suddenly broke. 
Changing the setting on my desktop won't fix the problem neither does restarting the system or Rustdesk fix it.

The UI becomes darkened when I move over the window and I can't click any buttons. It is lightnened up when it's not active though. Keyboard functions do still work. Sadly you can't reach the three dots for the settings with it.

As a potential workaround I was trying around with modifier keys since the UI becomes clickable for a short time with a bit of luck. Setting the window to always on top, resizing it, maximizing it again, placing it on another workspace or anything else may help to get the behavior that the UI becomes clickable for longer than a split second.

...

**What did you expect to happen instead?**

Window doesn't get darkened and every UI Element is clickable.
...

**How did you install `RustDesk`?**

Official site

---

**RustDesk version and environment**

Client: 1.19
Docker Image: rustdesk/rustdesk-server:latest

Debian 11 bullseye stable with cinnamon

**Comment by rustdesk** [comment]
try out nightly build please

**Comment by DieSchoeneWolke** [comment]
Thanks that did. Now I simply don't know how to autostart the AppImage.
Is there something special about it? Using the startup gui or using a systemd service doesn't work.


Thanks for your reply!

**Comment by DieSchoeneWolke** [comment]
resolved the issue and it worked via the startup gui. I think I had the wrong version of the app.

**Comment by DieSchoeneWolke** [comment]
Happening in 1.20 again

**Comment by DieSchoeneWolke** [comment]
Happening in 1.20 again

**Comment by rustdesk** [comment]
wontfix, flutter bevavior, out of our control for the time being.
