### ISSUE TITLE
The night version client cannot open the client to view the ID number after receiving the remote connection

### ISSUE THREAD

**Issue by youhers** [rustdesk/rustdesk#2904]
**Describe the bug you encountered:**

...The client cannot be opened to view the ID number and set software parameters after being charged

**What did you expect to happen instead?**

...After the client is controlled, it should be able to open a connection page to facilitate the accused to control another client again

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

WIN  10  1.2.0 1.22

**Comment by rustdesk** [comment]
known

**Comment by rustdesk** [comment]
@Kingtous does this problem still exist? The plus button on remote window seems not  intuitive solution on windows and linux. mac seems a little different, we need to confirm how does anydesk bevavior on mac.

**Comment by youhers** [comment]
![截图_20230123102812](https://user-images.githubusercontent.com/106003909/213956395-242d436f-1101-4ea8-8d01-ffb4a1e4e0c8.gif)
Cannot open the main window after being controlled

**Comment by Kingtous** [comment]
> @Kingtous does this problem still exist? The plus button on remote window seems not  intuitive solution on windows and linux, we need to allow clicking on rustdesk icon to open main window always. mac seems a little different, we need to confirm how does anydesk bevavior on mac.

The problem is that cm window is treated as main window now. in windows cpp, we need to change the window id, other than rustdesk, which should indicates there is already a main window has opened.

**Comment by Kingtous** [comment]
> > @Kingtous does this problem still exist? The plus button on remote window seems not  intuitive solution on windows and linux, we need to allow clicking on rustdesk icon to open main window always. mac seems a little different, we need to confirm how does anydesk bevavior on mac.
> 
> The problem is that cm window is treated as main window now. in windows cpp, we need to change the window id when invoking with --cm, other than rustdesk, which should indicates there is already a main window has opened.
> 
> Prior fixes have not considered this situation, a quick fix is needed and be soon.

**Comment by youhers** [comment]
thank you
