### ISSUE TITLE
Protocol not available (os error 92)

### ISSUE THREAD

**Issue by Ahiok** [rustdesk/rustdesk#2908]
When I try to use RustDesk to control other Android phones on my Android phone, RustDesk displays Protocol not available (os error 92).,
But when I used redmi k20Pro to connect to K30S, it was smooth, and there was no error pop-up window
Host
Redmi K30S
OS：Android10 （MIUI13）
RustDesk 1.1.10-1
Android:
Phone Model: Xiaomi4
OS: Android 6.0.1（MIUI8）
RustDesk 1.1.10-1/1.1.9

**Comment by rustdesk** [comment]
#2539

**Comment by rustdesk** [comment]
try out nigtly build please

**Comment by Ahiok** [comment]
> try out nigtly build please

That phone uses ipv4. In fact, it does not support ipv6.

**Comment by Ahiok** [comment]
Nightly build（1.2.0-0）shows “not installed”，In fact ，I can only install 1.1.9/1.1.10-1 in Xiaomi4
That phone uses ipv4. In fact, it does not support ipv6.

**Comment by rustdesk** [comment]
I do not think I can help you with xiaomi4, a 2014 phone.

**Comment by rockxsj** [comment]
Same problem on nexus 5, it seems related with socket connection build. Wish @rustdesk could give a patch, thanks!
