### ISSUE TITLE
Connecting to both remote machines results in disconnecting from both after some time.

### ISSUE THREAD

**Issue by bigretromike** [rustdesk/rustdesk#2909]
**Describe the bug you encountered:**
When connected to 2 machines in local host (one is being connected directly, other is thru self-hosted gateway) after few minutes (activity or not) rustdesk close both connection.
...

**What did you expect to happen instead?**
connection should be allowed until there is DC or I disconnect
...

**How did you install `RustDesk`?**

download daily build and install thru client "Install" option

---

**RustDesk version and environment**

1.2.0  23-12-2022 build time (dd-mm-yyyy)
first remote machine is win7 64 
second remote machine is win 10 ltsc 64
machine that is doing connection is win 11 64 
All using same

**Comment by rustdesk** [comment]
@fufesou

**Comment by bigretromike** [comment]
I will add, because it think it related, after connecting to only one machine and leaving it open (not focused) something even minimalized, the keyboard act like it was switched from legacy mode, yet, switching it back and foward don't fix this issue: the F1-F12 stop working properly.

**Comment by bigretromike** [comment]
I just downloaded and installed 1.2.0-24.01.2023 build.
For now it looks like it's ok - but I will give more feedback after few days.

**Comment by bigretromike** [comment]
Sadly this is still the issue @rustdesk

**Comment by rustdesk** [comment]
High priority

**Comment by fufesou** [comment]
@bigretromike  Hi, I've run this case for 5 hours, it does not crash.
The local side is Win10, it has controlled two peers.

This issue may be fixed by this PR.
https://github.com/rustdesk/rustdesk/pull/3238

Can you please help confirm? Thx

**Comment by bigretromike** [comment]
Will try to test it tomorrow, will be back

**Comment by bigretromike** [comment]
@rustdesk @fufesou Sorry for making you guys wait. I tried today with 5 VM machines, all using build from 18.03.2023, and im 30minut in using and nothing close/crashed. So its a good sign. If the issue will come back (and I updated) I will report back. Thank you for help.

**Comment by rustdesk** [comment]
👍
