### ISSUE TITLE
Nightly builds had UI exceptions under certain conditions.

### ISSUE THREAD

**Issue by YamatoRyou** [rustdesk/rustdesk#2914]
**Describe the bug you encountered:**
First set the theme to Basic, then start RustDesk and let it sit idle for a few hours.
Hours later, another RustDesk client got stuck trying to connect to this one.
If you bypass RustDesk and directly operate the virtual machine, you will find that the client is still running, but its UI is stuck. If you try to move the window, the entire desktop will become broken.
The workaround is to close RustDesk from the taskbar to quit, then re-run manually. But the crash reappears after a few more hours.

**The virtual machine's graphics adapter cannot enable the Aero theme, and the status of RustDesk running under the classic theme is still under observation.**

**What did you expect to happen instead?**
n/a

**How did you install `RustDesk`?**
https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64-pc-windows-msvc.exe

---

**RustDesk version and environment**
Operating system: 64-bit Windows Embedded Standard 7 SP1 (in a virtual machine)
RustDesk client version: 1.2.0 (Nightly, build date: 0:42, Jan 22, 2023)
RustDesk server version: 1.1.7

**Comment by rustdesk** [comment]
honestly, we wont test on windows 7.

**Comment by rustdesk** [comment]
let us know if you have the same problem on 10.

**Comment by youhers** [comment]
I also encountered the same problem. Finally, I still installed 1.1.9. Will win7 be eliminated so soon

**Comment by rustdesk** [comment]
we still offer Sciter 32bit version in the future.

**Comment by youhers** [comment]
expect
