### ISSUE TITLE
After connecting the client, I found that the image quality of the right side is too different from that of the left side

### ISSUE THREAD

**Issue by youhers** [rustdesk/rustdesk#2915]
**Describe the bug you encountered:**

...The icon on the right is too vague after the client connects

**What did you expect to happen instead?**

...After connection, the image quality should be refreshed automatically, or the connection speed should be reduced to make the client completely ready to provide better image quality requirements

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

win 10 1.2.0 1.23Night version
![截图_20230123113449](https://user-images.githubusercontent.com/106003909/213962086-f08f0c91-016f-4be6-9a25-7b3bb959b28a.gif)

**Comment by rustdesk** [comment]
image quality is another big topic.

**Comment by youhers** [comment]
I understand Thank you

**Comment by rustdesk** [comment]
This is also related to how to handle key frame in a clever way, @21pages @Heap-Hop i think it is time to solve the key frame issue, let us discuss later together, find out a good solution.

**Comment by youhers** [comment]
The picture quality on the right side is obviously much worse than that on the left side. You need to enlarge the picture and click to connect it. If you do not refresh after connecting, the picture quality cannot be automatically updated to the best picture. Click the refresh button on the client, and the picture quality returns to normal, but it is still a bit unstable

**Comment by rustdesk** [comment]
> The picture quality on the right side is obviously much worse than that on the left side. You need to enlarge the picture and click to connect it. If you do not refresh after connecting, the picture quality cannot be automatically updated to the best picture. Click the refresh button on the client, and the picture quality returns to normal, but it is still a bit unstable

we know this.

**Comment by youhers** [comment]
I understand. I look forward to optimization later
