### ISSUE TITLE
Turkish please, international keyboard

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#292]
From email

> Is there Server Installation Documentation for step-by-step installation? (for Windows or Linux)
When I tested your program, I observed slowdowns. I request an improvement on this issue.
Could I do the file transfer using the copy-paste method?
Last but not least, I need Language Support in Turkish. Is it possible for you to provide me with that kind of support?

**Comment by rustdesk** [comment]
> brazil keyboard usually have that c on the right of the "L" key where we have our ";", so it's a physical key for them, but on my french keyboard it's an alt code, so I think they still use alt code for that c even if it's a physical key

> Hi! I'm from Brazil, most keyboards here have ç. I connected to two remote hosts today and I couldn't use \ and ç

**Comment by vielhuber** [comment]
This is the same for german keyboard layouts (both on client and remote applied):
The following characters are not working:
"'" (single quote), ">" (right arrow), "<" (left arrow)

This happens:
![anim](https://user-images.githubusercontent.com/3183737/143245280-832e9447-a929-475d-8c0f-021276c8dba4.gif)

**Comment by rustdesk** [comment]
> "'" (single quote), ">" (right arrow), "<" (left arrow)

Thanks, international keyboard support is our next most important milestone.

**Comment by rustdesk** [comment]
https://github.com/stweil/OSXvnc/blob/main/OSXvnc-server/VNCServer.m#L489

**Comment by open-trade** [comment]
xdo hanging https://github.com/jordansissel/xdotool/issues/10#issuecomment-454634439

**Comment by rustdesk** [comment]
How to handle AltGr (on some keyboard, Ctrl+Alt events triggered): https://github.com/microsoft/vscode/issues/50341#issuecomment-510003060

**Comment by rustdesk** [comment]
https://github.com/TigerVNC/tigervnc/pull/1137  Japanese Keyboard Support
