### ISSUE TITLE
RS_PUB_KEY doesnt work with -k _

### ISSUE THREAD

**Issue by botanicvelious** [rustdesk/rustdesk#2921]
if you set the key via RS_PUB_KEY and your server is using -k _ to force the key it doesnt work unless you put the key into the config field in the client. The connection just times out.

It appears that the default key is not used properly.

Tested on windows with linux server, hbbs and hbbr set to -k _

**Comment by rustdesk** [comment]
please go ahead with your contribution.

**Comment by rustdesk** [comment]
I do not know why RS_PUB_KEY is not set correctly, but your last commit does have a bug and broke our nightly build. I have to fix like this way.

https://github.com/rustdesk/rustdesk/commit/efa7b52f49dcd0c39d6b7971785ede8558a0495c

**Comment by botanicvelious** [comment]
> I do not know why RS_PUB_KEY is not set correctly, but your last commit does have a bug and broke our nightly build. I have to fix like this way.
> 
> [efa7b52](https://github.com/rustdesk/rustdesk/commit/efa7b52f49dcd0c39d6b7971785ede8558a0495c)

I had been looking into it and have no idea why it doesn't work... apparently its been an issue since at least November

https://github.com/rustdesk/rustdesk/discussions/2236

**Comment by rustdesk** [comment]
no, you have misunderstanding

**Comment by rustdesk** [comment]
> The RS_PUB_KEY value isn't used and only the config value is used

yes, you reminded me, i did this intentionally, because public server do need it. if you wanna fix, please be considerate for public server.

**Comment by rustdesk** [comment]
using_public_server can be used.

**Comment by botanicvelious** [comment]
So appears on linux RENDEZVOUS_SERVER also doesn't work. Cant test OSX but this is strange, is there some os specific code paths I dont see any?

I assume the issue with both of these is in the connection...

**Comment by rustdesk** [comment]
> is there some os specific code paths I dont see any?
this part is totally os independent.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3328#issuecomment-1475322112
