### ISSUE TITLE
[Nightly] Changing monitors sets the cursor to the top left corner of the switched monitor

### ISSUE THREAD

**Issue by bilago** [rustdesk/rustdesk#2923]
**Describe the bug you encountered:**
When switching from a monitor to another, rustdesk thinks your cursor is in the top left corner of the newly selected screen until you click somewhere else in the window
...

**What did you expect to happen instead?**

When switching monitors I would expect the cursor location to track the cursor of my mouse immediately
...

**How did you install `RustDesk`?**

GitHub nightly build

---

**RustDesk version and environment**

1.2.0 2023-01-23 17:51

Windows 10 connecting to Windows 10

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
> until you click somewhere else in the window

@fufesou this behavior seems stupid，please confirm and fix

**Comment by rustdesk** [comment]
oh, i see. this is old behavior for mobile, please add desktop.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/2985

**Comment by fufesou** [comment]
@bilago Hi, my cursor does not move to top left after swithing monitor.

https://user-images.githubusercontent.com/13586388/215311628-36f317bb-a395-4ee8-a820-115a9707cfac.mp4

Can you please upload a video, or tell more details?

**Comment by bilago** [comment]
> @bilago Hi, my cursor does not move to top left after swithing monitor.
> 
>  aa.mp4 
> Can you please upload a video, or tell more details?

The visual cursor is not moving anywhere. It's as if the remote client thinks the cursor location is in the top left upon monitor switch, and the first click of the mouse anywhere in the window registers as if you clicked the top corner instead of where you are trying to click. I'm on the road this weekend so I cannot make a video right now

**Comment by fufesou** [comment]
Thanks, I get it.
But I'm not sure how it makes trouble. Can you please give an example?

**Comment by bilago** [comment]
> Thanks, I get it. But I'm not sure how it makes trouble. Can you please give an example?

There has been a few times where I've run into a scenario where I'm multitasking two applications maximized on monitor 1 and 2 and If I don't click somewhere in the switched monitor, keystrokes will activate on the titlebar of  one of the applications, which has closed the application entirely on several occasions. I can take some time tomorrow to replicate exact key combinations that cause this issue. It was never an issue using anydesk or TeamViewer

**Comment by fufesou** [comment]
Thanks. I'm on the road too.
I'll fix it as soon as possible.

**Comment by fufesou** [comment]
Hi, this issue may be fixed. Please confirm when you have time.
