### ISSUE TITLE
Linux not using self-hosted Rendezvous Server address

### ISSUE THREAD

**Issue by cluneke416** [rustdesk/rustdesk#2927]
I installed a rustdesk client from my repository(fork of rustdesk) on ubuntu desktop. When running the client it is still connecting to rustdesk public servers rather than my own self hosted server

I also installed the windows client on several windows machines and they work as expected

...

Expected behavior should be the client connecting to my server allowing access to my other clients on other machines rather than being connected to the public server

...

**How did you install `RustDesk`?**

Fork from rustdesk repository, built with Rendezvous server secret and PS_KEY_PUB secret

---

Rustdesk Nightly V1.2.0 debian on Ubuntu Desktop 22.04.1 LTS

[Rustdesk_rCURRENT.log](https://github.com/rustdesk/rustdesk/files/10486409/Rustdesk_rCURRENT.log)
[Rustdesk.toml.txt](https://github.com/rustdesk/rustdesk/files/10486422/Rustdesk.toml.txt)

[RustDesk2.toml.txt](https://github.com/rustdesk/rustdesk/files/10486453/RustDesk2.toml.txt)

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2921, maintained by contributor.

**Comment by cluneke416** [comment]
@rustdesk so you want me to rewrite the code for you?

**Comment by ivan-ivanov-1** [comment]
Yes, I can confirm this behavior on the last nightly build (04\10\23)
