### ISSUE TITLE
Multiple icons on Mac and better taskbar integration.

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#293]
From email
![image](https://user-images.githubusercontent.com/71636191/141397289-080fc5d9-b241-4a71-b920-9aa28e0b5fc2.png)

**Comment by rustdesk** [comment]
Need to avoid invoking new process.

**Comment by rustdesk** [comment]
https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428612-application

**Comment by rustdesk** [comment]
Simple solution:

1, modify dock icon to snapshot image or with id for each peer connection
2, remove dock icon when exit
   http://macinstallers.blogspot.com/2013/12/remove-dock-icon-using-cocoa.html

**Comment by rustdesk** [comment]
![屏幕快照 2022-06-06 下午12 31 55](https://user-images.githubusercontent.com/71636191/172095331-faff63ce-709c-454d-a1d4-c4020fd97077.png)

**Comment by rustdesk** [comment]
fixed in nightly build.

**Comment by risaw1981** [comment]
I'm running on a Pro self hosted server and have the multiple icon issue, every time I restart my Mac a new icon appears, is this going to be fixed for Pro users?
