### ISSUE TITLE
About Window: Information is missing

### ISSUE THREAD

**Issue by oliuo1** [rustdesk/rustdesk#2930]
**Describe the bug you encountered:**

Information in About Window is missing in nighly and 1.1.9 Windows Clients
![image](https://user-images.githubusercontent.com/122091080/214292222-8b83e273-fe92-48fc-b7bf-a01d77a6bf69.png)

![image](https://user-images.githubusercontent.com/122091080/214292310-9d9756bb-b8f3-4f3a-9951-f6e00565134d.png)

**What did you expect to happen instead?**

have it look like in the documentation:
https://rustdesk.com/docs/en/self-host/install/images/lic.png

**How did you install `RustDesk`?**

Windows portable version

---

**RustDesk version and environment**

own Rustdesk Server

**Comment by rustdesk** [comment]
in settings page

**Comment by rustdesk** [comment]
Is this hard to find?

![image](https://user-images.githubusercontent.com/71636191/214322165-3beadf90-2994-4554-b4c4-dc92e0cd821c.png)
