### ISSUE TITLE
I found that after switching the image quality in the remote process, the connection must be disconnected before the conversion can take effect

### ISSUE THREAD

**Issue by youhers** [rustdesk/rustdesk#2935]
**Describe the bug you encountered:**

...When my connection succeeds, I change the connection picture quality, and the mouse moves at an abnormal speed. When I disconnect and connect to the remote desktop again, everything becomes normal again, and when I readjust the connection picture quality, it becomes abnormal again

**What did you expect to happen instead?**

...After adjustment, it will be very troublesome to reconnect every time

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

win 10 1.2.0 1.25Night version

**Comment by rustdesk** [comment]
@fufesou please confirm.

**Comment by youhers** [comment]
During my test, there is a noticeable shortage of frames after the switch between good quality and normal quality is completed. After reconnection, the number of frames will return to normal.

**Comment by rustdesk** [comment]
@21pages please confirm this while you working on #2943 .
