### ISSUE TITLE
Android 13 - Physical keyboard does not work unless virtual keyboard is brought up

### ISSUE THREAD

**Issue by cstrife1** [rustdesk/rustdesk#2941]
**Describe the bug you encountered:**

The physical keyboard does not work at at all until the Virtual Keyboard is brought up. When the virtual keyboard is visible (taking up half the screen), the physical keyboard will work as expected.

**What did you expect to happen instead?**

Physical keyboard works.

**How did you install `RustDesk`?**

rustdesk-1.2.0-aarch64-linux-android-release-signed.apk from nightly builds.

---

**RustDesk version and environment**

Android 13, Samsung Galaxy Tab S8 Ultra with physical keyboard case.

Running nightly version as of Jan 25, 6:30 AM EST version.

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by Babrr** [comment]
I have the exact same problem with galaxy tab s7+ and physical keyboard case.

**Comment by rustdesk** [comment]
Sadly we have no android 13 device, it can not be reproduced in simulator.

**Comment by Babrr** [comment]
It wasn't working on my tab s7+ android 12 before the update to 13

**Comment by Heap-Hop** [comment]
Hi, we did have a bug that cause mobile physical keyboard didn't work.
Have fixed it on https://github.com/rustdesk/rustdesk/pull/3138 .

> When the virtual keyboard is visible (taking up half the screen), the physical keyboard will work as expected.

But I'm not sure your issue on your Android13 device still exist or not.
Please try new nightly build tomorrow. And tell me your result. Thank you @cstrife1 @Babrr .

**Comment by Babrr** [comment]
It's working, there's a kind of yellow line around the whole screen as if I've selected something (it doesn't usually happen with other program).  Now it remains to fix that the touch mode does not remain saved when I exit and enter the session and that with the touch mode if you want to move a folder it has so much latency that it takes the folder after

**Comment by gaetanolip** [comment]
Please help.us with android 13 and physical keyboard.
Thank you very much for the effort. You are great

**Comment by uliscat** [comment]
Android 12. Physical keyboard does not work even with virtual keyboard brought up.

**Comment by rustdesk** [comment]
close to favor https://github.com/rustdesk/rustdesk/issues/2941
