### ISSUE TITLE
IOS App with connection error: Operation not permitted (os error 1)

### ISSUE THREAD

**Issue by bst27** [rustdesk/rustdesk#2942]
**Describe the bug you encountered:**

1. Download Rustdesk for Windows (1.1.9), install and start
2. Download Rustdesk iOS app (1.1.10) and start on iPhone 14 Pro with iOS 16.1.2
3. Disable Wifi and use mobile internet on the iPhone
4. Enter id and password of the windows machine on the iPhone app and try to connect
5. Receive the following error message:

<img src="https://user-images.githubusercontent.com/6805736/214553490-d92b2823-77fd-42d1-8932-da2794adc4f4.png" height="500">

6. Enable Wifi on the iPhone again
7. Try to connect to the windows machine again
8. See it work

**What did you expect to happen instead?**
I expect to be able to connect to the windows machine not only when using Wifi but also when using mobile internet.

**How did you install `RustDesk`?**
* Download RustDesk for windows from website ([link](https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-windows_x64.zip)) and install
* Download RustDesk app from Apple Store
* Use default settings (no self hosting or something)
---

**RustDesk version and environment**
* Windows 10 Pro, RustDesk 1.1.9
* iPhone 14 Pro, iOS 16.1.2, RustDesk 1.1.10, wifi disabled

**Comment by rustdesk** [comment]
dupliate: https://github.com/rustdesk/rustdesk/issues/152

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/959
