### ISSUE TITLE
Scrolling with mouse wheel results in garbled remote screen's image

### ISSUE THREAD

**Issue by mtelis** [rustdesk/rustdesk#2943]
As %subj suggests, when I scroll down/up using the mouse wheel screen becomes garbled (see attached video). To restore the image, I have to make the remote's screen change (click on the document, initiate the mouse-over event etc).

https://user-images.githubusercontent.com/335301/214582530-9945037a-a853-4ce1-aebf-7d7b549570c2.mp4

**Comment by rustdesk** [comment]
duplicate: https://github.com/rustdesk/rustdesk/issues/2935 

the root cause is the same.

**Comment by rustdesk** [comment]
duplicate: https://github.com/rustdesk/rustdesk/issues/2915

the root cause is the same.

**Comment by youhers** [comment]
The problem still exists
