### ISSUE TITLE
Privacy screen is "hidden" when peeking applications from taskbar in nightly

### ISSUE THREAD

**Issue by tomudding** [rustdesk/rustdesk#2945]
**Describe the bug you encountered:**
When enabling privacy mode in a remote session (and disabling remote input) the remote cannot be used (which is great). However, when the party doing the remote controlling peeks an application in the taskbar, the privacy window is removed as the peek application is moved to the foreground (and all other applications are essentially minimalized).

Here is a screenshot of the remote with the privacy mode enabled, you clearly see nothing (ignore the white part, that is an unfortunate artifact):

![privacy screen](https://user-images.githubusercontent.com/4983571/214651859-8aa12b77-762e-46d1-9689-6ee85c24fc53.png)

However, when hovering over an application in the taskbar that is not in the foreground, that window is moved towards the foreground, essentially disabling the privacy window:

![image](https://user-images.githubusercontent.com/4983571/214647322-92236e91-701d-4a61-81bc-f501cba1f3ca.png)

**What did you expect to happen instead?**

**How did you install `RustDesk`?**

From GH nightly release, applies to both PCs (so 1.2.0, the build from yesterday).

Both PCs are Windows 10 Pro 22H2 build 19045.2546.

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
Hi, this issue cannot be fixed with this implementation.

**Comment by rustdesk** [comment]
wontfix in current implementation. need to rewrite an implementation with driver in the future.
