### ISSUE TITLE
Sort favorites alphabetically by name

### ISSUE THREAD

**Issue by fedo911** [rustdesk/rustdesk#2948]
For the "Recent Sessions" it is intuitive to have them sorted by "last used", but favorites should be sorted (or at least also be sortable) by name. The order of adding to favorites is not really meaningful.

**Comment by rustdesk** [comment]
Then sort by? sort by `[online status, name]`, which name?

- [ ] peer id
- [ ] user name
- [ ] host name

A new dropbox, let user choose.

address book? discovery?

@21pages  let's do it later, low priority.

then

**Comment by rustdesk** [comment]
@NicKoehler Wondering if you have interest to work on this?

**Comment by NicKoehler** [comment]
I can try and report back

**Comment by rustdesk** [comment]
👍

**Comment by rustdesk** [comment]
I just finished the langs sorting from rust side.

![image](https://user-images.githubusercontent.com/71636191/222625350-39b35ed0-1a24-46c4-a967-913c1f927686.png)

**Comment by rustdesk** [comment]
Close as fix merged.

**Comment by fedo911** [comment]
Thanks for implementing and sorry for checking back in so late. I was actually referring to the "name" of the favorite that can be assigned via "Rename". Can this be added as a 4th option?
