### ISSUE TITLE
Image tearing

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#295]
Reported in discord,

> By resetting image quality this issue could be temporally solved … for few seconds, but soon the image would break again.

![image](https://user-images.githubusercontent.com/71636191/141884327-a4173eed-2234-4290-ab59-11ba06cb8dc3.png)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/blob/master/src/server/connection.rs#L201

**Comment by fufesou** [comment]
> 

I cannot understand, more clearly. I want to contribute this project. 

Timeout with 1 second occurs frequently in weak network environment, whitch this design can not deal with?

**Comment by rustdesk** [comment]
> https://github.com/rustdesk/rustdesk/blob/master/src/server/connection.rs#L201
> 
> A bad frame lost design, need to rewrite.

This piece of code drops some video frames in weak netowork, which cause image tearing. This is a big issue,. One simple solution is enabling key frames (disable in this project), but this can not solve bad network problem. @lbl8603 is invesigating on another solution, if you have interest, you can discuss with him.
