### ISSUE TITLE
Get connection ID via command line (--get-id)

### ISSUE THREAD

**Issue by Gigaion** [rustdesk/rustdesk#2953]
The newest 1.2.0 versions have the ID and passwords encrypted.
There is no longer an automated way to get the connection ID due to this.

Similar to AnyDesk, Rustdesk needs a way to find the connection ID without a human opening up the software.

https://support.anydesk.com/knowledge/command-line-interface-for-windows
Please add a software flag such as ./rustdesk --get-id

I will limit this feature request to just getting the ID, as that is more useful then other terminal flag features.

**Comment by rustdesk** [comment]
close in favour of #69
