### ISSUE TITLE
Remote dialog connecting client color darkened

### ISSUE THREAD

**Issue by youhers** [rustdesk/rustdesk#2957]
**Describe the bug you encountered:**

...It's not clear which client is being controlled in the remote process, so it would be great if you could deepen the color distinction

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

![企业微信截图_20230127211043](https://user-images.githubusercontent.com/106003909/215095736-f3ab194e-912e-4e7c-b485-1441f86b6c90.png)

**Comment by youhers** [comment]
The dialog box color being controlled should be displayed more deeply

**Comment by rustdesk** [comment]
Do not be hurry, we will polish these details before it gets stable.

**Comment by youhers** [comment]
Thank you, it's been a hard time. It feels good now.

**Comment by youhers** [comment]
Thank you
