### ISSUE TITLE
Under win7 and server2008, the software cannot open to display the black screen status

### ISSUE THREAD

**Issue by youhers** [rustdesk/rustdesk#2958]
**Describe the bug you encountered:**

...All black, no content, see GIF

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

win server 2008 r2  1.2.0 
![截图_20230127230545](https://user-images.githubusercontent.com/106003909/215118859-9f6fdd21-d131-4603-b5a2-2442b86aba9d.gif)

**Comment by rustdesk** [comment]
@Kingtous

**Comment by youhers** [comment]
It works normally at first, but there has been a problem since I updated the PC driver

**Comment by rustdesk** [comment]
I don't think we have capabitlity to solve your problem.

**Comment by rustdesk** [comment]
For those who fail to run Flutter version, we can only sugguest they are stick to Sciter version in the future.

**Comment by youhers** [comment]
But I changed three PC-end drivers at the same time. This is the only problem. Is it my driver

**Comment by youhers** [comment]
All right, thank you
