### ISSUE TITLE
.AppImage doesn't run/open on VanillaOS (Nightly Version) 

### ISSUE THREAD

**Issue by gonzoknows** [rustdesk/rustdesk#2961]
**Describe the bug you encountered:**

.AppImage doesn't run on VanillaOS which is an Ubuntu based distro that's immutable 

**What did you expect to happen instead?**

For the application to run and open

**How did you install `RustDesk`?**

Installed via appimage using [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher)

**RustDesk version and environment**

Using [nightly](https://github.com/rustdesk/rustdesk/releases/tag/nightly)

**Comment by Kingtous** [comment]
Could you also provide the runtime log by running `.AppImage` in your terminal?

`./rustdesk-xxx-.AppImage`

**Comment by gonzoknows** [comment]
> Could you also provide the runtime log by running `.AppImage` in your terminal?
> 
> `./rustdesk-xxx-.AppImage`

I'm on an immutable system, it displays this 
![image](https://user-images.githubusercontent.com/122128828/215238952-62bbf40b-05f5-41b4-9563-9c5683ed52dc.png)

**Comment by Kingtous** [comment]
> > Could you also provide the runtime log by running `.AppImage` in your terminal?
> > 
> > `./rustdesk-xxx-.AppImage`
> 
> I'm on an immutable system, it displays this 
> ![image](https://user-images.githubusercontent.com/122128828/215238952-62bbf40b-05f5-41b4-9563-9c5683ed52dc.png)
> 
> Update: I got this 
> ![image](https://user-images.githubusercontent.com/122128828/215239159-6070a95e-2750-4cc8-8622-39ff32d54fd5.png)
> 

you should use x86_64 appimage, not the aarch64 one.
