### ISSUE TITLE
rustdesk-server-demo run error

### ISSUE THREAD

**Issue by charmer1989** [rustdesk/rustdesk#297]
$ cargo run
    Updating crates.io index
    Updating git repository `https://github.com/open-trade/confy`
    Updating git repository `https://github.com/stepancheg/rust-protobuf`
error: no matching package named `protobuf-codegen-pure` found
location searched: https://github.com/stepancheg/rust-protobuf
required by package `hbb_common v0.1.0 (C:\Users\zxc\code\rustdesk-server-demo\libs\hbb_common)`
    ... which satisfies path dependency `hbb_common` of package `rustdesk-server v1.0.0 (C:\Users\zxc\code\rustdesk-server-demo)`

**Comment by charmer1989** [comment]
The same error in macOS

**Comment by rustdesk** [comment]
Fixed

**Comment by charmer1989** [comment]
Thank you so much for your quick response, this is really a great project
