### ISSUE TITLE
Quality Monitor blocks mouse input

### ISSUE THREAD

**Issue by fragtion** [rustdesk/rustdesk#2970]
Hi

When enabling the "Show quality monitor" feature, it becomes impossible to click on anything beneath the quality monitor. The quality monitor blocks mouse clicks and needs to be disabled in order to interact with that part of the remote display once again

This is not a problem if you're just viewing the remote display, but if you want to see stats while actually working/interacting with the remote display, then it can be an annoyance/problematic.

Is it possible to make this information dialog no longer intercept mouse inputs, for future builds?

Thanks

**Comment by rustdesk** [comment]
@fufesou  is this possible?

**Comment by fufesou** [comment]
Thanks, good advisement.
I'll try.
