### ISSUE TITLE
Do not display remote cursor during screen recording

### ISSUE THREAD

**Issue by youhers** [rustdesk/rustdesk#2977]
**Describe the bug you encountered:**

...There is no remote cursor for screen recording, it should be displayed perfectly

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

1.2.0  Night Version

**Comment by rustdesk** [comment]
we know, but wont fix because there are underlying problem we can not solve.

**Comment by youhers** [comment]
Well, thank you
