### ISSUE TITLE
Can't switch input method by Ctrl + Shift in Windows 7.

### ISSUE THREAD

**Issue by YamatoRyou** [rustdesk/rustdesk#2980]
**Describe the bug you encountered:**
Computer A: 64-bit Windows 7 SP1
Computer B: 64-bit Windows 10 21H2

a) A is connected to B, even if the remote desktop window of A has no focus (that is, in other windows such as notepad or browser), the input method cannot be switched by Ctrl + Shift, unless the remote desktop connection is terminated (and need to close all RustDesk windows);
b) B is connected to A, the remote desktop cannot switch the input method through Ctrl + Shift.

**What did you expect to happen instead?**
Regardless of whether the Windows 7 computer is the initiator or the called party, switching input methods via Ctrl + Shift should not behave abnormally.

**How did you install `RustDesk`?**
https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64-pc-windows-msvc.exe

---

**RustDesk version and environment**
RustDesk client version: 1.2.0 (Nightly, build date: 0:23, Jan 23, 2023)
RustDesk server version: 1.1.7

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
#1547

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3117#issuecomment-1422242788
