### ISSUE TITLE
On fullscreen mode, show toolbar over remote content

### ISSUE THREAD

**Issue by lihanchen** [rustdesk/rustdesk#2986]
I am using windows client.
Currently, when I move my mouse to show full-screen toolbar, it pushes the remote screen down to make space for the toolbar. When I need to click something near the top edge of the screen, I may accidentally reveal the toolbar and my target is therefore moved.
I think it is to add an option to show the toolbar over the content. Maybe also reduce the size of the toolbar as there is a lot of blank space now. Like how RDP and anydesk do.
![rust](https://user-images.githubusercontent.com/5497974/215315890-c2d40c0c-d447-4acf-a4ac-d99304773349.png)

**Comment by rustdesk** [comment]
try out nightly build
