### ISSUE TITLE
How to build server on macOS 

### ISSUE THREAD

**Issue by malicioustoker** [rustdesk/rustdesk#299]
Can we get some step by step instructions on how to build for macOS?

**Comment by malicioustoker** [comment]
*instead of relying on docker

**Comment by rustdesk** [comment]
99% similar to Linux, both Unix system.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/139

**Comment by rustdesk** [comment]
Some guy already contributed the steps.
https://github.com/rustdesk/rustdesk/issues/139#issuecomment-874419397

**Comment by malicioustoker** [comment]
Oops, I meant to post this is -server

**Comment by rustdesk** [comment]
`cargo run` please. server building has no trick.

**Comment by malicioustoker** [comment]
The poor guy panicked :S

    Finished dev [unoptimized + debuginfo] target(s) in 3.04s
     Running `target/debug/rustdesk-server`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', src/main.rs:16:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by rustdesk** [comment]
100% follow the readme please.

**Comment by rustdesk** [comment]
I believe you will have more question, you can find all answers from.

https://github.com/rustdesk/rustdesk/search?q=demo+server&type=issues

**Comment by malicioustoker** [comment]
Oh wow, it really was that easy - thanks for all the help!
