### ISSUE TITLE
please add options for mapping host keyboard with client keyboard

### ISSUE THREAD

**Issue by UriZafrir** [rustdesk/rustdesk#2991]
hello.
is there a possibility to add an option that exists in anydesk?
https://support.anydesk.com/knowledge/keyboard-and-hotkeys
since I am using an international keyboard, sometimes there is a discrepancy between host keyboard and client keyboard, which then I have to see that both of them are on the same language.
In anydesk I can decide to map 1:1, and that means my keyboard goes as is to the client keyboard.

Could you please add that feature?

**Comment by rustdesk** [comment]
try out nightly build， map mode there
