### ISSUE TITLE
Cannot move my mouse to screen edge in fullscreen adaptive mode

### ISSUE THREAD

**Issue by lihanchen** [rustdesk/rustdesk#2992]
**Describe the bug you encountered:**
When I move my mouse cursor to the screen edge on client. The mouse cursor on server stops at about 1 inch from screen edge.
It only happened with nightly, adaptive mode.
The mouse cursor changes to resizing cursor, but it still shows the regular cursor on server, becuase cursor is not on screen edge on server.
...

**What did you expect to happen instead?**
Cursor location should be same on client and server
...

**How did you install `RustDesk`?**

Github nightly release

---

**RustDesk version and environment**

Nightly on 1-28, windows on both client and server.

**Comment by lihanchen** [comment]
Btw, my server has 2k resolution. Client is 4k.
![IMG_20230129_040622](https://user-images.githubusercontent.com/5497974/215325128-58c5c388-5dd2-445e-aee5-a5e6118ff7d6.jpg)

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
Yes, it is really stupid with resizing cursor on full screen mode. @Kingtous

**Comment by lihanchen** [comment]
The fix is confirmed working. Thanks for the quick response
