### ISSUE TITLE
Build failure (rustdesk-git) caused by flutter build failure

### ISSUE THREAD

**Issue by amyipdev** [rustdesk/rustdesk#2996]
**Describe the bug you encountered:**

Building current `rustdesk`-git fails. Appears to be because of flutter's rust bridge failing to build:
```rs
thread 'main' panicked at 'Failed to parse function output type `SyncReturn<i64>`', src/parser/mod.rs:151:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

(specifically, this happened after replacing `flutter_rust_bridge_codegen`)

This was also reported [here](https://aur.archlinux.org/packages/rustdesk-git) on 1/23/23 by @kode54 (Christopher Snowhill). 

**What did you expect to happen instead?**

Successful build of flutter leading to a successful rustdesk build.

**How did you install `RustDesk`?**

Build from source via AUR `rustdesk-git`. 

**RustDesk version and environment**

Arch Linux, kernel 6.1.8, Rust most recent stable (1.66.0). AUR package was tagged `1.2.0-r450.gc63da06f-1`.

**Comment by Akkowicz** [comment]
I know almost nothing about Rust and I'm not currently an Arch user, but just looking at the PKGBUILD file it seems that there are some mismatches.

RustDesk uses Flutter 3.7.0 for CI builds, Arch uses 3.0.5.

RustDesk uses flutter_rust_bridge 1.61.1 from here: https://github.com/fzyzcjy/flutter_rust_bridge
Arch uses flutter_rust_bridge 1.32.0 from here https://github.com/SoLongAndThanksForAllThePizza/flutter_rust_bridge

If the upstream project's CI builds pass, I'd probably start looking at how the downstream is building it first - it's usually downstream responsibility to make sure their builds are working.

**Comment by kode54** [comment]
I just checked, Arch doesn't package Flutter. It's in a user repository package.

Oh, I see, this stupid AUR package doesn't even use the flutter AUR package, it pulls its own copy, and a really old one at that.

**Comment by Akkowicz** [comment]
Yup, it looks like this build file for Arch needs to be rewritten because it's using outdated dependencies and misses some of the good practices.

All in all, it's not an issue on RustDeck side and should probably be closed to not put burden on RustDeck developers.

**Comment by kode54** [comment]
Yeah, hence why I filed the issue as a comment to the AUR package. Though now I know why that was the right choice and not filing here as well.

**Comment by rustdesk** [comment]
> All in all, it's not an issue on RustDeck side and should probably be closed to not put burden on RustDeck developers.

Thanks a lot
