### ISSUE TITLE
Mac连不上Win7。。。。

### ISSUE THREAD

**Issue by zhangbo8418** [rustdesk/rustdesk#3]
<img width="958" alt="QQ20201022-085821@2x" src="https://user-images.githubusercontent.com/46797568/96806028-929d1880-1445-11eb-83ff-d0041223e15a.png">
<img width="958" alt="QQ20201022-085729@2x" src="https://user-images.githubusercontent.com/46797568/96806042-9892f980-1445-11eb-893b-0d04a45abbf9.png">

**Comment by open-trade** [comment]
retry之后什么反应？

**Comment by zhangbo8418** [comment]
> retry之后什么反应？
循环往复无穷尽也。。。。
<img width="959" alt="QQ20201022-104353@2x" src="https://user-images.githubusercontent.com/46797568/96818211-9a63b980-1453-11eb-9487-02d4abb92606.png">
<img width="959" alt="QQ20201022-104431@2x" src="https://user-images.githubusercontent.com/46797568/96818219-a0599a80-1453-11eb-8ce8-027c76c19d6a.png">

**Comment by open-trade** [comment]
我没在7上测试过， 我会装个虚拟机试一下

**Comment by zhangbo8418** [comment]
> 我没在7上测试过， 我会装个虚拟机试一下

对了啥时候出Android端？

**Comment by open-trade** [comment]
ing，一个人开发精力有限

**Comment by open-trade** [comment]
> > 我没在7上测试过， 我会装个虚拟机试一下
> 
> 对了啥时候出Android端？

出了新版本，支持win7，以及安卓客户端

**Comment by zhangbo8418** [comment]
> > > 我没在7上测试过， 我会装个虚拟机试一下
> > 
> > 
> > 对了啥时候出Android端？
> 
> 出了新版本，支持win7，以及安卓客户端

大佬辛苦了，我都不忍心报告BUG。。。安卓端控制Windows Server 2019鼠标箭头不显示，文件传输不可用。。。Windows Server 2008 R2不可用。。。不可安装成服务。。。

**Comment by open-trade** [comment]
> > > > 我没在7上测试过， 我会装个虚拟机试一下
> > > 
> > > 
> > > 对了啥时候出Android端？
> > 
> > 
> > 出了新版本，支持win7，以及安卓客户端
> 
> 大佬辛苦了，我都不忍心报告BUG。。。安卓端控制Windows Server 2019鼠标箭头不显示，文件传输不可用。。。Windows Server 2008 R2不可用。。。不可安装成服务。。。

你的使用场景都是我的测试之外

**Comment by open-trade** [comment]
08是xp时代的玩意，注册表跟现在都不一样了。12以上倒是要找个时间测试一下

**Comment by zhangbo8418** [comment]
> > > > > 我没在7上测试过， 我会装个虚拟机试一下
> > > > 
> > > > 
> > > > 对了啥时候出Android端？
> > > 
> > > 
> > > 出了新版本，支持win7，以及安卓客户端
> > 
> > 
> > 大佬辛苦了，我都不忍心报告BUG。。。安卓端控制Windows Server 2019鼠标箭头不显示，文件传输不可用。。。Windows Server 2008 R2不可用。。。不可安装成服务。。。
> 
> 你的使用场景都是我的测试之外

我也就随便测试了下。。。那发几个图看看？
Windows Server 2019文件文件传输不可用
<img width="1174" alt="Windows Server 2019" src="https://user-images.githubusercontent.com/46797568/100711730-aba5cb80-33ec-11eb-83c4-7ca70b06be43.png">

安卓端控制Windows Server 2019不显示鼠标箭头
![无箭头](https://user-images.githubusercontent.com/46797568/100711891-e3ad0e80-33ec-11eb-8cb8-cba1e8b01bac.jpg)

Windows Server 2008R2不可用
<img width="957" alt="Windows Server 2008 R2" src="https://user-images.githubusercontent.com/46797568/100711959-f889a200-33ec-11eb-8fbf-6d8064069b9b.png">

无法安装成服务
![6A8C1E4E-7D13-483A-8C5C-3A4056A291FD](https://user-images.githubusercontent.com/46797568/100712354-98473000-33ed-11eb-9429-78eb1cd98292.png)

**Comment by open-trade** [comment]
谢谢，看了截图，我大概知道原因了，不过找个server测试也挺费劲的

**Comment by open-trade** [comment]
08果然是xp时代的玩意，窗口风格都一样

**Comment by open-trade** [comment]
你觉得ToDesk做的怎么样？

**Comment by zhangbo8418** [comment]
> 你觉得ToDesk做的怎么样？

BUG少点，哈哈哈。。。

**Comment by rustdesk** [comment]
惭愧2020年12月1日 16:16，裙下孤魂 <notifications@github.com>写道：



你觉得ToDesk做的怎么样？



BUG少点，哈哈哈。。。

**Comment by zhangbo8418** [comment]
> 你觉得ToDesk做的怎么样？

安卓端的鼠标控制确实有点蛋疼。。。还有无法安装成服务不只是Windows Server 2008R2不行，Win7也不行，Windows Server 2019也不行呢。。。
