### ISSUE TITLE
linux manjaro display

### ISSUE THREAD

**Issue by 370750149** [rustdesk/rustdesk#300]
I'm using manjaro xfce 21.1.6,env utf8.zh_CN.When I installed from aur,the application can not displayed chinese text.

**Comment by rustdesk** [comment]
I only tested manjaro KDE.

**Comment by rustdesk** [comment]
I install ttf-arphic-uming on Manjaro KDE to show Chinese. Not sure about xfce.

**Comment by 370750149** [comment]
I changed to KDE is OK,thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rustdesk/rustdesk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月17日(星期三) 下午4:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rustdesk/rustdesk] linux manjaro display (Issue #300)





 
I install ttf-arphic-uming on Manjaro KDE to show Chinese. Not sure about xfce.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
