### ISSUE TITLE
 About Windows controlling Android: keyboard map function 

### ISSUE THREAD

**Issue by 1049731887** [rustdesk/rustdesk#3000]
As the title, transfer the input from Windows to Android. 

 ** How to achieve: ** 
 Android software registers the virtual keyboard and guides the user to set it as the default keyboard. 
 Simulate by getting the key code sent by the Windows side. 

 machine translation 
 Excuse me.

**Comment by 1049731887** [comment]
中文版：
如题，将Windows端的输入传输到安卓端。

**实现方法：**
安卓端软件注册虚拟键盘，并引导用户设置为默认键盘。
通过获取Windows端发送的键码进行模拟。

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/681#discussioncomment-2869884

**Comment by rustdesk** [comment]
If there is concrete demonstration if it is feasible please tell us.
