### ISSUE TITLE
About touch controls

### ISSUE THREAD

**Issue by wilinz** [rustdesk/rustdesk#3005]
Three-finger sliding will trigger the screen capture operation of the mobile phone, resulting in gesture conflicts, such as miui, and three-finger operation is very inconvenient. It is recommended to use two-finger sliding operation for scrolling or moving the canvas. The two functions can be switched by buttons

**Comment by wilinz** [comment]
The default behavior is to scroll the screen

**Comment by rustdesk** [comment]
We know this, but still insist using 3 finger.

**Comment by wilinz** [comment]
In addition, other remote tools are two-finger sliding, using three-finger sliding will disrupt our habits

**Comment by wilinz** [comment]
And the two-finger zoom canvas is very easy to be misoperated. Sometimes the size of the canvas has been adjusted, and the size of the canvas will be changed accidentally. I hope to add a button to lock the position and size of the canvas

**Comment by wilinz** [comment]
I found that the three-finger swipe does not work on my android client, even if I have turned off the three-finger screenshot function, on Android 12, miui 13

**Comment by wilinz** [comment]
> We knowed this, but still insisted using 3 finger because some other reasons.

What is the reason
