### ISSUE TITLE
Ugly Dock Icon on macOS

### ISSUE THREAD

**Issue by YIMINGMA** [rustdesk/rustdesk#301]
**Describe the bug you encountered:**

The icon on the dock looks very ugly. It has huge white borders when the app is fixed.
<img width="126" alt="截屏2021-11-17 11 51 26" src="https://user-images.githubusercontent.com/45311510/142195542-96715490-e003-429f-9f29-7c5bbf3ebdca.png">

But strangely, there is no such problem when the app is opened. 
<img width="141" alt="截屏2021-11-17 11 52 22" src="https://user-images.githubusercontent.com/45311510/142195684-1a4bdfe7-4056-4893-aa96-a57a115037fb.png">

**What did you expect to happen instead?**

No white borders please.

**How did you install `RustDesk`?**

GitHub release

---

**RustDesk version and environment**

1.1.8, on macOS Monterey 12.0.1

**Comment by rustdesk** [comment]
Yes, it is known issue, I have not spent time to dig in yet.

**Comment by YIMINGMA** [comment]
Hi @rustdesk, 

By
1. transforming the `.icns` file into the `png` file;
2. removing all white edges via ImageMagick;
3. making the background transparent via [remove.bg](https://www.remove.bg);
4. transforming the `.png` file back to the `.icns` file;
5. placing the icon file under `/Applications/RustDesk.app/Contents/Resources/` and naming it as `RustDesk.icns`;
now the icon on the dock looks as desired.

<img width="157" alt="截屏2021-11-18 10 16 26" src="https://user-images.githubusercontent.com/45311510/142396413-7ee7c8f5-eaad-4341-894a-4a813a5ef74f.png">

**Comment by rustdesk** [comment]
You are so great.

**Comment by rustdesk** [comment]
> 5\. RustDesk.icns

Can you send RustDesk.icns to me? info@rustdesk.com

**Comment by YIMINGMA** [comment]
The app's icon in launchpad also looks normal. I forgot to mention, for anyone who wish to keep the original resolution (256x256), you can adjust it while it is still in the `png` format. You may also need to clean the icon caches after these changes. Please refer to [this gist](https://gist.github.com/ismyrnow/e92c6010cda9325b2d8811387a05f224) for clearing caches.

<img width="268" alt="截屏2021-11-18 11 04 04" src="https://user-images.githubusercontent.com/45311510/142403768-26492893-6684-4ac2-8894-ea7b607e3fee.png">

For simplicity I will also add the icon file here, all you need to do is unzip it and place it in the right directory.

![RustDesk](https://user-images.githubusercontent.com/45311510/142404327-a15aa372-cd78-4796-b16d-7047003eb42b.png)
[RustDesk.zip](https://github.com/rustdesk/rustdesk/files/7562259/RustDesk.zip)

**Comment by YIMINGMA** [comment]
> > 5. RustDesk.icns
> 
> Can you send RustDesk.icns to me? [info@rustdesk.com](mailto:info@rustdesk.com)

Sent.
