### ISSUE TITLE
Build issues due to vcpkg

### ISSUE THREAD

**Issue by jjgalvez** [rustdesk/rustdesk#3013]
Hi all I just wanted to report, I've had several issues trying, unsuccessfully, to get rust desk to build following the instructions as close as possible. Finally looked over at the vscpkg site and it seems that package is the reason for my failures as it's failing due to an issue with git (https://github.com/microsoft/vcpkg/issues/29288). Seems they are trying to fix it. Hopefully they will fix it soon and I can get back to trying to get rustdesk to build.

**Comment by rustdesk** [comment]
#763
