### ISSUE TITLE
Application with adminstrator needed wont show dialog

### ISSUE THREAD

**Issue by imsoso** [rustdesk/rustdesk#3017]
**Describe the bug you encountered:**

When I open an application with adminstrator, NO dialog shown, and not responding anymore.
After a while, dialog disappear.
If I repeat, it happened again.

**RustDesk version and environment**
1.2.0 nightly build.

Server：Windows 10 22H2
Client：Windows 11 22H2

**Comment by rustdesk** [comment]
video please

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
#1275

**Comment by rustdesk** [comment]
or install on controlled side, required by uac

**Comment by imsoso** [comment]
thanks
waiting for the windows installation for night build

**Comment by rustdesk** [comment]
#104

**Comment by rustdesk** [comment]
> thanks waiting for the windows installation for night build
click install button on main window
