### ISSUE TITLE
Build error: ubuntu 18

### ISSUE THREAD

**Issue by Mutronics** [rustdesk/rustdesk#3019]
Compiling default-net v0.11.0 (https://github.com/Kingtous/default-net#bdaad8dd)
   Compiling sys-locale v0.2.3
   Compiling whoami v1.2.3
   Compiling system_shutdown v3.0.0
   Compiling webm v1.0.2
   Compiling zstd v0.9.2+zstd.1.5.1
   Compiling rustdesk v1.2.0 (/home/user/rustdesk)
error[E0583]: file not found for module `version`
  --> src/lib.rs:25:1
   |
25 | mod version;
   | ^^^^^^^^^^^^
   |
   = help: to create the module `version`, create file "src/version.rs" or "src/version/mod.rs"

error[E0432]: unresolved import `crate::VERSION`
  --> src/server/connection.rs:11:18
   |
11 | use crate::{ipc, VERSION};
   |                  ^^^^^^^
   |                  |
   |                  no `VERSION` in the root
   |                  help: a similar name exists in the module: `version`

error[E0425]: cannot find value `VERSION` in the crate root
    --> src/client.rs:1464:29
     |
1464 |             version: crate::VERSION.to_string(),
     |                             ^^^^^^^ not found in the crate root

error[E0425]: cannot find value `VERSION` in the crate root
   --> src/rendezvous_mediator.rs:307:29
    |
307 |             version: crate::VERSION.to_owned(),
    |                             ^^^^^^^ not found in the crate root

error[E0425]: cannot find value `VERSION` in the crate root
   --> src/rendezvous_mediator.rs:357:29
    |
357 |             version: crate::VERSION.to_owned(),
    |                             ^^^^^^^ not found in the crate root

error[E0425]: cannot find value `VERSION` in the crate root
   --> src/rendezvous_mediator.rs:401:29
    |
401 |             version: crate::VERSION.to_owned(),
    |                             ^^^^^^^ not found in the crate root

error[E0425]: cannot find value `VERSION` in the crate root
   --> src/common.rs:523:21
    |
523 |         url: crate::VERSION.to_owned(),
    |                     ^^^^^^^ not found in the crate root

error[E0425]: cannot find value `VERSION` in the crate root
   --> src/common.rs:532:77
    |
532 |                 if get_version_number(&version) > get_version_number(crate::VERSION) {
    |                                                                             ^^^^^^^ not found in the crate root

error[E0425]: cannot find value `VERSION` in the crate root
  --> src/core_main.rs:65:31
   |
65 |         println!("{}", crate::VERSION);
   |                               ^^^^^^^ not found in the crate root

error[E0425]: cannot find value `VERSION` in the crate root
   --> src/ui_interface.rs:637:12
    |
637 |     crate::VERSION.to_owned()
    |            ^^^^^^^ not found in the crate root

error[E0425]: cannot find value `VERSION` in the crate root
  --> src/hbbs_http/sync.rs:57:80
   |
57 |                         v["ver"] = json!(hbb_common::get_version_number(crate::VERSION));
   |                                                                                ^^^^^^^ not found in the crate root

Some errors have detailed explanations: E0425, E0432, E0583.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `rustdesk` due to 11 previous errors

**Comment by simonspa** [comment]
https://github.com/rustdesk/rustdesk/issues/3008

**Comment by rustdesk** [comment]
#764

**Comment by rustdesk** [comment]
#763
