### ISSUE TITLE
Can't show 1080*1920 

### ISSUE THREAD

**Issue by myxemhoho** [rustdesk/rustdesk#302]
When connect a 1080*1920 remote PC, It can connect, but can not show, and will break a while ,and try connect again. still can not Show the screen.

**Comment by rustdesk** [comment]
More details please. You 'd better record a short video, and tell us about OS version on remote side, installed or not etc.

**Comment by myxemhoho** [comment]
Local PC is Win10, and Remote side PC is Win10 too.
When Remote side PC is set as :   1080*1920 ，Portrait
![image](https://user-images.githubusercontent.com/13776473/142539340-6b2c2e57-5ae4-4caa-b2c5-e548872511f2.png)
Rustdesk can Connect remote side PC , but  can not  show the screen of it.


When Remote side PC is set as:   1920*1080,  Landscape 
Rustdesk can Connect remote side PC , and  can show the screen of it.

**Comment by rustdesk** [comment]
Understood, Thanks a lot.
https://github.com/rustdesk/rustdesk/issues/227

**Comment by myxemhoho** [comment]
https://user-images.githubusercontent.com/13776473/142545804-c0f2dd48-0898-4fd5-ae39-c3d1d8870878.mp4

**Comment by rustdesk** [comment]
Yes, 10054 is an old issue, though several report, but I still can not reproduce it on my side. Very embarrassing.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/106

**Comment by rustdesk** [comment]
Have you installed anti-virus software?

**Comment by myxemhoho** [comment]
When Remote side PC is set as: 1920*1080, Landscape  :  No err.  It work very good.

When Remote side PC is set as : 1080*1920 ，Portrait:  Black Screen and err 10054.

**Comment by rustdesk** [comment]
> When Remote side PC is set as : 1080*1920 ，Portrait: Black Screen and err 10054.

Very helpful

**Comment by rustdesk** [comment]
How do you change from landscape to portrait? Rotate your display physically?

**Comment by myxemhoho** [comment]
![image](https://user-images.githubusercontent.com/13776473/142551445-2cea7115-c578-4e70-a38f-5bf8741c5a2e.png)
use Anydesk

**Comment by rustdesk** [comment]
> use Anydesk

You are genius.

**Comment by myxemhoho** [comment]
I just want use RestDesk replace Anydesk

**Comment by rustdesk** [comment]
RustDesk is immuture for now. You give me very important clue.

**Comment by rustdesk** [comment]
> If you remote in to a machine that happens to have a display in the portrait orientation, rustdesk has issues portraying this and tries to refit it to landscape
However if you click on anything in the screen portrait refit it causes stability issues and has to restart the connection with the remote machine, if you switch to the portrait display again it will continually disconnect if anything is attempted.
Rustdesk doesn't appear to support other screen orientations.

**Comment by myxemhoho** [comment]
Will try to fix ?

**Comment by rustdesk** [comment]
Yes, but you see so many issues here.
