### ISSUE TITLE
Zoom level on Linux client （linux display zoom factor = 150% Gnome, RH9)

### ISSUE THREAD

**Issue by hsteinhaus** [rustdesk/rustdesk#3020]
When using Linux/Gnome with 150% zoom level, the rustdesk client behaves a bit weird. Using "Original" screen size, fullscreen mode and a resolution on the controlled device matching the physical one of the client, there is only a portion of the screen visible - 66% I guess.

After compensating the client zoom level of 150% by using a smaller resolution on the controlled computer (e.g. 2160x1350 -> 1440x900) on the controlled host, the result is close to ok. Unfortunately, there seems to be some rounding issue causing the controlled screen to be one pixel larger than the screen of the client, triggering the presence of scroll bars. There image quality is also quite blurry.

Both machines were Linux/Xorg/Gnome. Debian 22.04 on client, RHEL9 on host. Switching to Wayland on the client seems to make no difference.

Expected behavior: crisp and more or less pixel-precise image on the client, if host resolution matches the physical resolution of the client - either with manual resolution adjustment or automatically.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
