### ISSUE TITLE
Error using keyboard English International on Windows

### ISSUE THREAD

**Issue by cladic** [rustdesk/rustdesk#3021]
I am using Windows 10 with keyboard language **ENGLISH International** active. 

When I call the rustdesk program and do a remote connection, some keys do not works any more. Obs.: using the regular keyboard language ENGLISH does not cause any problem like this.

Examples:
-  **grave accent**   ==> no character is accepted
- áááá ( letter A plus acute accent ) ==> the  acute accent is inactive )

The problem occur on my regular Desktop ( the place where I start the RustDesk client ), NOT in the remote desktop or in the remote display !

So I can not do my regular work while the rustdesk is active ( **after activating a remote connection** ! ).

**What did you expect to happen instead?**

The rustdesk program do not intercepts those keys and make them DEAD.....

**How did you install `RustDesk`?**

The problem occurs on portable version and also on the installed version

---

**RustDesk version and environment**

RustDesk version 1.1.9
Windows 10 - version 22H2 ( Build 19045.2364 )

In Settings->Language choose English ( United States ) and then ->Options -> Add a Keyboard and now choose "**United States-International**"
And now set this language as **default/principal** for the keyboard.

To test try to config the letter A plus acute accent, which should be like this:  ÁÁÁ  or ááá

The **grave accent**  is not a special character to this type keyboard language ( **English International** ) and so it is very 
weird what is happen with this character ( maybe have others with the same problem too )

If we choose the regular **ENGLISH language keyboard**, the "grave accent" problem does not occur!

**Comment by rustdesk** [comment]
try out nightly build please

**Comment by cladic** [comment]
It is OK now !

Obs: AVAST anti-virus detect a problem with this nightly build...say it contains a "win64 evo-gen". I tested also using VIRUSTOTAL and AVAST is the only one who detects the malware !
