### ISSUE TITLE
Hope to adapt to openSUSE as soon as possible

### ISSUE THREAD

**Issue by EminemRap** [rustdesk/rustdesk#303]
The operating system of my computer is openSUSE Leap 15.3, and the desktop environment is KDE plasma X11. After installing RustDesk, other computers can be remotely controlled, but other computers cannot remotely control my computer. Hope to adapt as soon as possible.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-suse.rpm tested on Leap 15.0
