### ISSUE TITLE
Release nightly cann't split the tab to new window.

### ISSUE THREAD

**Issue by wilon** [rustdesk/rustdesk#3040]
**Describe the bug you encountered:**

Cann't split the tab to new window.
![微信图片编辑_20230202085908](https://user-images.githubusercontent.com/7512755/216261089-33dadef9-dccf-4c13-9f77-c58a87cd4584.jpg)

**What did you expect to happen instead?**

Just like Chrome tab, can split and combine.

**How did you install `RustDesk`?**

GitHub release

---

**RustDesk version and environment**

nightly+win10

**Comment by rustdesk** [comment]
No plan yet.

**Comment by rustdesk** [comment]
@Kingtous we mentioned before.

**Comment by wilon** [comment]
Thank for your amazing work.
I will use old 1.1.9 version and the nightly version fulfill my needs. 😊
