### ISSUE TITLE
Click the up arrow on the keyboard will display the number 8

### ISSUE THREAD

**Issue by willzhang** [rustdesk/rustdesk#3043]
**Describe the bug you encountered:**

Click the up arrow on the keyboard to display the number 8

![image](https://user-images.githubusercontent.com/33590311/216273028-314e7675-dd8a-462e-a67a-acc695aa556d.png)

![image](https://user-images.githubusercontent.com/33590311/216272390-ef8dee5b-b66f-44f0-ab82-6451fe2a1293.png)

**What did you expect to happen instead?**

Click the up arrow on the keyboard in the Linux operating system should call up the previous historical command.

![image](https://user-images.githubusercontent.com/33590311/216272658-b7a4d4b2-e3d5-4af1-8d1e-a05ee89ae384.png)

**How did you install `RustDesk`?**

windows 11 exe install.

**RustDesk version and environment**

1.1.9

**Comment by rustdesk** [comment]
try out nightly build please.
