### ISSUE TITLE
rustdesk linux client is unable to connect since last rustdesk server update

### ISSUE THREAD

**Issue by Benance** [rustdesk/rustdesk#3046]
**Describe the bug you encountered:**

Since last rustdesk server update, my rustdesk linux client is unable to connect. My other rustdesk client (android and windows) work well.

**What did you expect to happen instead?**

make my rustdesk linux client work again

**How did you install `RustDesk`?**

github .deb release

**RustDesk version and environment**

Version 1.1.9 on linux mint 20.3

my rustdesk server is hosted on a debian LXC container running on proxmox VE
t has been updated 2 days ago with [the easy install method](https://github.com/techahold/rustdeskinstall/issues/30#event-8399567057)

**Comment by rustdesk** [comment]
try out nightly build please.
