### ISSUE TITLE
win10 building error for android, Tips: error: could not find native static library `sodium`, perhaps an -L flag is missing?

### ISSUE THREAD

**Issue by fan0424** [rustdesk/rustdesk#3050]
When I compile the Android version under Win10, I get the following error：

D:\Code\RustDesk\rustdesk-master>cargo ndk --platform 21 --target aarch64-linux-android build --release --features flutter
[2023-02-03T02:00:35Z INFO  cargo_ndk::cli] Using NDK at path: D:\Android\SDK\ndk\22.1.7171670 (ANDROID_NDK_HOME)
[2023-02-03T02:00:35Z INFO  cargo_ndk::cli] NDK API level: 21
[2023-02-03T02:00:35Z INFO  cargo_ndk::cli] Building targets: arm64-v8a
[2023-02-03T02:00:35Z INFO  cargo_ndk::cli] Building arm64-v8a (aarch64-linux-android)
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.47
   Compiling quote v1.0.21
   Compiling unicode-ident v1.0.5
   Compiling syn v1.0.105
   Compiling libc v0.2.138
   Compiling winapi v0.3.9
   Compiling memchr v2.5.0
   Compiling cfg-if v1.0.0
   Compiling serde_derive v1.0.149
   Compiling serde v1.0.149
   Compiling log v0.4.17
   Compiling jobserver v0.1.25
   Compiling cc v1.0.77
   Compiling futures-core v0.3.25
   Compiling thiserror v1.0.37
   Compiling slab v0.4.7
   Compiling lock_api v0.4.9
   Compiling indexmap v1.9.2
   Compiling once_cell v1.16.0
   Compiling futures-task v0.3.25
   Compiling parking_lot_core v0.9.5
   Compiling futures-util v0.3.25
   Compiling version_check v0.9.4
   Compiling autocfg v0.1.8
   Compiling winapi-util v0.1.5
   Compiling rand_core v0.4.2
   Compiling scopeguard v1.1.0
   Compiling aho-corasick v0.7.20
   Compiling regex-syntax v0.6.28
   Compiling either v1.8.0
   Compiling which v4.3.0
   Compiling rand_core v0.3.1
   Compiling same-file v1.0.6
   Compiling atty v0.2.14
   Compiling num_cpus v1.14.0
   Compiling num-traits v0.2.15
   Compiling anyhow v1.0.66
   Compiling pin-project-lite v0.2.9
   Compiling walkdir v2.3.2
   Compiling thiserror-impl v1.0.37
   Compiling futures-macro v0.3.25
   Compiling regex v1.7.0
   Compiling tokio-macros v1.8.2
   Compiling zstd-sys v1.6.2+zstd.1.5.1
   Compiling hashbrown v0.12.3
   Compiling termcolor v1.1.3
   Compiling rand_pcg v0.1.2
   Compiling rand_chacha v0.1.1
   Compiling smallvec v1.10.0
   Compiling protobuf v3.2.0
   Compiling bitflags v1.3.2
   Compiling futures-channel v0.3.25
   Compiling rand v0.6.5
   Compiling remove_dir_all v0.5.3
   Compiling unicode-width v0.1.10
   Compiling fastrand v1.8.0
   Compiling futures-sink v0.3.25
   Compiling windows_x86_64_msvc v0.42.0
   Compiling siphasher v0.2.3
   Compiling phf_shared v0.7.24
   Compiling tempfile v3.3.0
   Compiling textwrap v0.11.0
   Compiling parking_lot v0.12.1
   Compiling bytes v1.3.0
   Compiling rand_isaac v0.1.1
   Compiling rand_hc v0.1.0
   Compiling rand_xorshift v0.1.1
   Compiling rand_jitter v0.1.4
   Compiling rand_os v0.1.3
   Compiling tokio v1.23.0
   Compiling futures-io v0.3.25
   Compiling lazy_static v1.4.0
   Compiling vec_map v0.8.2
   Compiling strsim v0.8.0
   Compiling pkg-config v0.3.26
   Compiling humantime v2.1.0
   Compiling pin-utils v0.1.0
   Compiling env_logger v0.9.3
   Compiling clap v2.34.0
   Compiling libsodium-sys v0.2.7
   Compiling protobuf-support v3.2.0
   Compiling proc-macro-error-attr v1.0.4
   Compiling mio v0.8.5
   Compiling socket2 v0.4.7
   Compiling signal-hook-registry v1.4.0
   Compiling zstd-safe v4.1.3+zstd.1.5.1
   Compiling glob v0.3.0
   Compiling itoa v1.0.4
   Compiling clang-sys v1.4.0
   Compiling phf_generator v0.7.24
   Compiling windows-sys v0.42.0
   Compiling proc-macro-error v1.0.4
   Compiling ring v0.16.20
   Compiling crossbeam-utils v0.8.14
   Compiling phf_codegen v0.7.24
   Compiling protobuf-parse v3.2.0
   Compiling pin-project-internal v1.0.12
   Compiling tracing-core v0.1.30
   Compiling dasp_sample v0.11.0
   Compiling minimal-lexical v0.2.1
   Compiling heck v0.4.0
   Compiling nom v7.1.1
   Compiling tracing v0.1.37
   Compiling protobuf-codegen v3.2.0
   Compiling target_build_utils v0.3.1
   Compiling num-traits v0.1.43
   Compiling libloading v0.7.4
   Compiling num-integer v0.1.45
   Compiling bindgen v0.59.2
   Compiling dtoa v0.4.8
   Compiling serde v0.9.15
   Compiling spin v0.5.2
   Compiling untrusted v0.7.1
   Compiling itoa v0.3.4
   Compiling adler v1.0.2
   Compiling hbb_common v0.1.0 (D:\Code\RustDesk\rustdesk-master\libs\hbb_common)
   Compiling serde_json v0.9.10
   Compiling tokio-util v0.7.4
   Compiling cexpr v0.6.0
   Compiling dasp_frame v0.11.0
   Compiling toml v0.5.9
   Compiling phf v0.7.24
   Compiling getrandom v0.2.8
   Compiling memoffset v0.7.1
   Compiling typenum v1.16.0
   Compiling serde_json v1.0.89
   Compiling peeking_take_while v0.1.2
   Compiling rustc-hash v1.1.0
   Compiling ryu v1.0.11
   Compiling lazycell v1.3.0
   Compiling shlex v1.1.0
   Compiling generic-array v0.14.6
   Compiling dirs-sys-next v0.1.2
   Compiling crossbeam-epoch v0.9.13
   Compiling unicode-segmentation v1.10.0
   Compiling camino v1.1.1
   Compiling fnv v1.0.7
   Compiling os_str_bytes v6.4.1
   Compiling semver v1.0.14
   Compiling clap_lex v0.2.4
   Compiling heck v0.3.3
   Compiling http v0.2.8
   Compiling rand_core v0.6.4
   Compiling backtrace v0.3.66
   Compiling android_system_properties v0.1.5
   Compiling cbindgen v0.23.0
   Compiling gimli v0.26.2
   Compiling httparse v1.8.0
   Compiling rustls v0.20.7
   Compiling rustversion v1.0.9
   Compiling linked-hash-map v0.5.6
   Compiling strsim v0.10.0
   Compiling ppv-lite86 v0.2.17
   Compiling tinyvec_macros v0.1.0
   Compiling dasp_ring_buffer v0.11.0
   Compiling textwrap v0.16.0
   Compiling signature v1.6.4
   Compiling ed25519 v1.5.2
   Compiling rand_chacha v0.3.1
   Compiling clap v3.2.23
   Compiling addr2line v0.17.0
   Compiling tinyvec v1.6.0
   Compiling yaml-rust v0.4.5
   Compiling iana-time-zone v0.1.53
   Compiling structopt-derive v0.4.18
   Compiling directories-next v2.0.0
   Compiling futures-executor v0.3.25
   Compiling miniz_oxide v0.5.4
   Compiling crossbeam-channel v0.5.6
   Compiling pin-project v1.0.12
   Compiling cargo-platform v0.1.2
   Compiling winreg v0.6.2
   Compiling time v0.1.45
   Compiling webm-sys v1.0.3
   Compiling object v0.29.0
   Compiling atomic v0.5.1
   Compiling crc32fast v1.3.2
   Compiling try-lock v0.2.3
   Compiling rayon-core v1.10.1
   Compiling rustc-demangle v0.1.21
   Compiling percent-encoding v2.2.0
   Compiling form_urlencoded v1.1.0
   Compiling want v0.3.0
   Compiling chrono v0.4.23
   Compiling machine-uid v0.2.0
   Compiling webpki v0.22.0
   Compiling sct v0.7.0
   Compiling cargo_metadata v0.14.2
   Compiling structopt v0.3.26
   Compiling futures v0.3.25
   Compiling tokio-socks v0.5.1-1 (https://github.com/open-trade/tokio-socks#7034e792)
   Compiling confy v0.4.0 (https://github.com/open-trade/confy#630cc28a)
   Compiling crossbeam-deque v0.8.2
   Compiling sodiumoxide v0.2.7
   Compiling serde_yaml v0.8.26
   Compiling unicode-normalization v0.1.22
   Compiling rand v0.8.5
   Compiling dasp_rms v0.11.0
error: could not find native static library `sodium`, perhaps an -L flag is missing?

error: could not compile `libsodium-sys` due to previous error
warning: build failed, waiting for other jobs to finish...
[2023-02-03T02:02:49Z INFO  cargo_ndk::cli] If the build failed due to a missing target, you can run this command:
[2023-02-03T02:02:49Z INFO  cargo_ndk::cli]
[2023-02-03T02:02:49Z INFO  cargo_ndk::cli]     rustup target install aarch64-linux-android

**Comment by rustdesk** [comment]
#763

**Comment by FrozenSquidward** [comment]
Pls how was it resolved
