### ISSUE TITLE
Connection error: connection reset by peer when Ctrl+ mouse scroll in mapping mode

### ISSUE THREAD

**Issue by gfgerard** [rustdesk/rustdesk#3063]
Using  Version: 1.2.0 nightly build 2023-02-02 between 2 Ubuntu hosts, both with same installed .deb versions.

When you try to do Ctrl+mouse wheel scroll for zoom in/out in Chrome, for example, connection crashes (reset by peer).

Also, I'm using mapping mode in keyboard settings for language compatibility (spanish keyboard). Without mapping mode it does not happen.

**Comment by rustdesk** [comment]
@fufesou

**Comment by gfgerard** [comment]
Just tried with 2023-03-08 releas (installing and also AppImage in Ubuntu):

- Now when doing ctrl + mouse wheel (zoom) keeps crashing but immediately reconnects
- New (very strange): when reconnecting, keyboard seems to stop working on both machines BUT if I focus on some input text on my client machine and try to write, the text gets input in the remote machine :shrug: (as if the keyboard was reversed and only in one way)

**Comment by rustdesk** [comment]
Thanks for your update

**Comment by chiehw** [comment]
@gfgerard 

What version of Ubuntu do you have on both sides? Is there a wayland?

**Comment by chiehw** [comment]
I'm using Ubuntu22 to control Ubuntu20, both using Xorg desktop server(map mode), but no reproduce.

https://user-images.githubusercontent.com/99897242/224186088-1a4e0534-b7bc-4d53-8c08-d2f56fc2400b.mp4

**Comment by gfgerard** [comment]
I'm controlling 18.04 from 20.04. It just breaks with that combination regardless of the program.

With the current nightly it's more complicated as it reverts my keyboard and it also happened 2 times that I had to force reset because my system crashed even after trying to close rustdesk (no keyboard and some system menus didn't work)

**Comment by chiehw** [comment]
Is  the latest version of rustdesk on both sides? Can you try to upgrade to the latest version?

**Comment by chiehw** [comment]
If only one side is updated, there may be some strange bugs.

**Comment by gfgerard** [comment]
As I said, tried with 2023-03-08 release (reinstalling and also with AppImage)

When I can I'll try with latest again

**Comment by chiehw** [comment]
Another possibility is that the old version of the rustdesk service has not been completely uninstalled.

**Comment by gfgerard** [comment]
Hi! tried again today and the problem seems to be fixed.

**Comment by rustdesk** [comment]
👍
