### ISSUE TITLE
MacOS "Adjust window" cause remote window to the left bottom corner and hanging up

### ISSUE THREAD

**Issue by fufesou** [rustdesk/rustdesk#3067]
**Describe the bug you encountered:**

Click "Adjust window" on remote menu, the window moves to the left bottom corner, and the window is hanging up.

...

**What did you expect to happen instead?**

Adjust window the the size as expected and window does not hang up.

...

**How did you install `RustDesk`?**

Build from source. (2023-02-03)

---

**RustDesk version and environment**

Local: MacOS

This issue if found on @rustdesk 's MacOS. I cann't reproduce.

![20230203222907](https://user-images.githubusercontent.com/13586388/216628507-9c754a68-70e7-4ba0-8a37-4aca68955e8f.jpg)

**Comment by rustdesk** [comment]
@Kingtous
