### ISSUE TITLE
Cursor offsets are not the same MacOS --> Win

### ISSUE THREAD

**Issue by fufesou** [rustdesk/rustdesk#3068]
**Describe the bug you encountered:**

MacOS --> Win, mismatch cursor offsets.

...

**What did you expect to happen instead?**

The offset should be the same.

...

**How did you install `RustDesk`?**

Build from source.(2023-02-03)

---

**RustDesk version and environment**

Local: MacOS
Remote: Win

This issue is found on @rustdesk 's PCs. I cannot reproduce.

![20230203223727](https://user-images.githubusercontent.com/13586388/216630650-577e0909-80d5-4812-9cd6-2a4d66134716.jpg)
![20230203223829](https://user-images.githubusercontent.com/13586388/216630684-5fced2cc-18de-4d9c-b9d3-3a3731e844cb.jpg)

**Comment by zhangbo8418** [comment]
> **Describe the bug you encountered:**
> 
> MacOS --> Win, mismatch cursor offsets.
> 
> ...
> 
> **What did you expect to happen instead?**
> 
> The offset should be the same.
> 
> ...
> 
> **How did you install `RustDesk`?**
> 
> Build from source.(2023-02-03)
> 
> **RustDesk version and environment**
> 
> Local: MacOS Remote: Win
> 
> This issue is found on @rustdesk 's PCs. I cannot reproduce.
> 
> ![20230203223727](https://user-images.githubusercontent.com/13586388/216630650-577e0909-80d5-4812-9cd6-2a4d66134716.jpg) ![20230203223829](https://user-images.githubusercontent.com/13586388/216630684-5fced2cc-18de-4d9c-b9d3-3a3731e844cb.jpg)

Reproduce: Quickly move the cursor to the target (without any shaking, the cursor will synchronize if it moves slightly over the target). #3261

**Comment by rustdesk** [comment]
@fufesou please follow up to reproduce as above
