### ISSUE TITLE
macos build error, I have set the environment variable, export VCPKG_ROOT=/Users/wangchengyun/vcpkg

### ISSUE THREAD

**Issue by yingeo** [rustdesk/rustdesk#3078]
macos build error, I have set the environment variable, export VCPKG_ROOT=/Users/wangchengyun/vcpkg
![11111](https://user-images.githubusercontent.com/24560653/216769250-eda5b9e7-1bd5-4e8f-9bef-16793ca01269.png)

**Comment by rustdesk** [comment]
#763
