### ISSUE TITLE
failed to build in win10

### ISSUE THREAD

**Issue by xiaoshengduan** [rustdesk/rustdesk#308]
Compiling hbb_common v0.1.0 (E:\rust\project\rustdesk-master\libs\hbb_common)
   Compiling scrap v0.5.0 (E:\rust\project\rustdesk-master\libs\scrap)
   Compiling magnum-opus v0.3.4-2 (https://github.com/open-trade/magnum-opus#ad083616)
error: failed to run custom build command for `scrap v0.5.0 (E:\rust\project\rustdesk-master\libs\scrap)`

Caused by:
  process didn't exit successfully: `E:\rust\project\rustdesk-master\target\debug\build\scrap-3f214540dd6d60a9\build-script-build` (exit code: 101)
  --- stdout
  cargo:info=x64-windows-static
  cargo:rustc-link-lib=static=yuv
  cargo:rustc-link-search=E:\rust\vcpkg\installed\x64-windows-static\lib
  cargo:include=E:\rust\vcpkg\installed\x64-windows-static\include
  cargo:info=x64-windows-static
  cargo:rustc-link-lib=static=vpx
  cargo:rustc-link-search=E:\rust\vcpkg\installed\x64-windows-static\lib
  cargo:include=E:\rust\vcpkg\installed\x64-windows-static\include
  rerun-if-changed=E:\rust\project\rustdesk-master\libs\scrap\vpx_ffi.h
  rerun-if-changed=E:\rust\vcpkg\installed\x64-windows-static\include

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.59.1\src/lib.rs:2117:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed;

vcpkg list:

libjpeg-turbo:x64-windows-static                   2.0.6#2          libjpeg-turbo is a JPEG image codec that uses SI...
libvpx:x64-windows-static                          1.10.0#2         The reference software implementation for the vi...        
libyuv:x64-windows-static                          2021-04-15       libyuv is an open source project that includes Y...        
opus:x64-windows-static      

Do you need to install clang separately？

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/180#issuecomment-888819371

**Comment by rustdesk** [comment]
Search in repo please before ask questions.

**Comment by xiaoshengduan** [comment]
thanks
