### ISSUE TITLE
modifiers (ctrl / shift etc) for click on mobile

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#3081]
https://www.reddit.com/r/rustdesk/comments/10tp9os/executing_windows_based_keystrokes_while_on/
Before we had this, but it seemed removed in new version after adding mouse mode by mistake.
@Heap-Hop

**Comment by rustdesk** [comment]
@Heap-Hop done?

**Comment by Heap-Hop** [comment]
Done with https://github.com/rustdesk/rustdesk/pull/3183
