### ISSUE TITLE
Android control Windows10 but keyboard double input and mouse cursor not show 

### ISSUE THREAD

**Issue by shyakocat** [rustdesk/rustdesk#3083]
I use an `Android13` device to control an `Windows10` device. 
The version of `rustdesk` is `1.1.9`, from [rustdesk.com](https://rustdesk.com/).
I link extra keyboard and mouse by bluetooth to operate Android device.
There are two problem,
+ Although I check the button that show remote device cursor, the cursor not display (on `Windows11` device it works). What make things worse, it hide the cursor on Android so that I cannot see any cursor. If the problem is hard to reproduce, I think at least add a setting to reserve original cursor on Android also helps.
+ When I type `123`, the real input is `112233` or `123123`. Type backspace 3 times it delete 6 character. I'm not sure whether it is the fault of IME (because I use IME in Chinese both on Android and Win10).

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3083

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/777

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by Heap-Hop** [comment]
Hi, we just fixed a bug about mobile physical keyboard didn't work.
https://github.com/rustdesk/rustdesk/pull/3138 .


But I'm not sure your issue on your Android13 device still exist or not.
A real Android13 device with physical keyboard and an Android13 in simulator may have different result about input.
Unluckily we haven't have an Android13 device yet. :(

Please try new nightly build after tomorrow. And tell us your result. Thx.
