### ISSUE TITLE
sciter  version

### ISSUE THREAD

**Issue by xiaoshengduan** [rustdesk/rustdesk#309]
how to download old version build sciter  <= 4.4.5.4,sciter 4.4.8.3 can't run, only black screen

**Comment by rustdesk** [comment]
You can ask in Sciter repo

**Comment by Fabio3rs** [comment]
On github official archived repository: https://github.com/c-smile/sciter-sdk

Commit named 4.4.5.4 https://github.com/c-smile/sciter-sdk/commit/dc65744b66389cd5a0ff6bdb7c63a8b7b05a708b
