### ISSUE TITLE
Nightly 1.2.0 from 2023-01-30 00:20 process blocked by Bitdefender

### ISSUE THREAD

**Issue by Benny7587** [rustdesk/rustdesk#3091]
**Describe the bug you encountered:**

After starting the Nightly 1.2.0 from 2023-01-30 00:20 for Windows, Bitdefender Anti Virus (Advance Threat Defence) comes in and stops the RustDesk process. Previous RD versions are okay and also later versions are. The version that is stopped by Bitdefender is the first RD version where the green button starts RustDesk in elevated mode and where this elevation worked fine. So i hope very much there will be a version with this great elevation functionality that is not blocked by Bitdefender.

**What did you expect to happen instead?**

I would expect that RustDesk would not be stopped by Bitdefender.

**How did you install `RustDesk`?**

Nightly build 1.2.0 from 2023-01-30 00:20 on Windows 11 home edition. (Running portable)
---

**RustDesk version and environment**
Nightly build 1.2.0 from 2023-01-30 00:20

Windows 11 home with Bitdefender anti virus

**Comment by rustdesk** [comment]
@21pages i do not think we can avoid this, but we do need to avoid unnecessary elevation.

**Comment by rustdesk** [comment]
Close because out of our control.

**Comment by rustdesk** [comment]
i guess it is because we use a new sysyem call for remote admin password input feature.
https://github.com/rustdesk/rustdesk/issues/70

**Comment by kintaro1981** [comment]
Teamviewer and Anydesk are not blocked by bitdefender and they can elevate themself once the remote host send them credentials. Maybe it's the way to do it?

**Comment by rustdesk** [comment]
> use a new sysyem call for remote admin password input feature.

It is also called only if remote sends credentials.

**Comment by rustdesk** [comment]
Anyway, it is my guess only.
