### ISSUE TITLE
RustDesk Client freezes while connected to local self hosted server

### ISSUE THREAD

**Issue by JaCh0o** [rustdesk/rustdesk#3098]
RustDesk is stopping to work properly.
After some time RustDesk is going from "Ready." (Green dot) to "Connecting to the RustDesk network..." (Orange dot) when connected to self hosted server.
-Stopping service and starting again doesn't help.
-Uninstalling RustDesk thru Software Installer and installing back (configuration persist on this action - ID, password, entered server ID and key) doesn't help.
-Removing Server ID and/or key gives green dot with Ready thru public server, but entering back server ID/key gives back yellow dot with "Connecting to the RustDesk network..." info.

To get RustDesk working back system reboot is needed. After reboot RustDesk is working properly (access thru local network, outside (phone LTE) and connect to another host in local network also.

...

Persist to work thru time without any nessesary action needed.

...

Download directly from GitHub ver 1.1.9 Deb file. 
Installed thru Software Installer.

---
RustDesk Client
Ubuntu 22.0.4 LTS amd64 En-US on 1U server 32GB Xeon E5-1650v3, SATA 3

RustDesk Server
Build od RPi3B+ 2Gb/64GB microSD

Both are located in same Local network but in different VLANS/ip addressations.

**Comment by rustdesk** [comment]
#763
