### ISSUE TITLE
编译后的可执行文件加载不了资源

### ISSUE THREAD

**Issue by dawnadvent** [rustdesk/rustdesk#31]
请问一下为什么编译后加载不了index.html，谢谢

**Comment by rustdesk** [comment]
cargo run， 可以加载，注意当前目录

**Comment by ekuiperemr** [comment]
Thank you - While building with  the following command on windows
cargo install   --no-track  --all-features  --force --root "C:\Users\fskhan\source\repos\FiveCentz" --path=rustdesk
Apparently there is no file called manifest.xml in this tree - I get this error:
 file not found: manifest.xml
