### ISSUE TITLE
Rustdesk in Manjaro VM

### ISSUE THREAD

**Issue by CyrosX** [rustdesk/rustdesk#310]
Dear Developers,
I found this software by chance and like it so far :-) thank you!
What I'm trying right now is a connection to a Manjaro Linux VM
from a Mac. Next to slightly higher CPU utilization on the Mac, it
seems audio is not working. I've already tried standards: rebooting, reinstalling, setting
the "audio input" option to soundcard, to "monitor of soundcard", but it won't work.
Can I somehow find out why it won't work?

**Comment by rustdesk** [comment]
It is hard to make audio work on Linux, even for me. Finally, I give up. Hope someone can make it easier to work.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/3d39d9c27c378dbe1cb7c1b128d8d1af75cf1305
