### ISSUE TITLE
White screen window on MacOS 13.2

### ISSUE THREAD

**Issue by cupid0426** [rustdesk/rustdesk#3100]
This issue has been present in macOS 12 and I thought upgrading would solve the problem, but the issue still persists even after multiple attempts to reinstall. It continues to be a white screen and I am unable to perform any actions.

![image](https://user-images.githubusercontent.com/5316981/217128770-2c59047b-551c-4844-b6e3-9ebfb54df4dc.png)

**Comment by rustdesk** [comment]
try out nightly build please.

**Comment by cupid0426** [comment]
> try out nightly build please.

The issue has been resolved, thank you.

**Comment by rustdesk** [comment]
Nightly mac is still buggy, we are still working on.
