### ISSUE TITLE
[Bug]  screen recording icon is indicative of video call

### ISSUE THREAD

**Issue by test2a** [rustdesk/rustdesk#3106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

check screenshot.. this is the latest nightly

now with the call icon, on first glance, telephone icon does audio call and the next icon does screen recording?

we should change the screen recording icon so that it is not confused with video call

### How to Reproduce

screenshot

### Expected Behavior

different screen recording icon to differentiate from video call

### Operating System(s) and RustDesk Version(s) on local side and remote side

linux/win10

### Screenshots

![Screenshot_20230207_150214](https://user-images.githubusercontent.com/39449563/217207271-db7e86b7-131f-45a5-86b0-5159805f208b.png)

### Additional Context

nothing

**Comment by rustdesk** [comment]
We even have not merge this PR yet.

**Comment by rustdesk** [comment]
Report to https://github.com/rustdesk/rustdesk/pull/2981 please.

**Comment by test2a** [comment]
@rustdesk this is about this icon and not about audio calling. 
![Screenshot_20230207_150214](https://user-images.githubusercontent.com/39449563/217209393-cc8df0c4-4c28-4318-98ec-5840078a4b21.png)

**Comment by rustdesk** [comment]
We will change record icon

![image](https://user-images.githubusercontent.com/71636191/217210463-9ff2fa36-582b-4039-bddb-86c7cfb7105d.png)

**Comment by test2a** [comment]
yes thanks. that is all i am asking in this issue
