### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jabo59** [rustdesk/rustdesk#3107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

Using the nightly build on my Mac I discover the following problem with the Mac version: Connecting to a remote machine works. Mouse is working while keyboard is not working. When I use the windows version (Windows VM on the Mac with Parallels) then both mouse and keyboard are working as expected.

### How to Reproduce

Connect from a Mac with an remote Windows machine (WIN-Server 2016).

### Expected Behavior

Keyboard should be working

### Operating System(s) and RustDesk Version(s) on local side and remote side

Local: OS-X v1.2.0 (2023-02-07); Remote: WIN10 Server 2016, v1.2.0 (2023-02-07)

**Comment by rustdesk** [comment]
#974

**Comment by rustdesk** [comment]
No such warning on Mac side.

![image](https://user-images.githubusercontent.com/71636191/217487994-600ab0b0-fbfe-41fb-822f-5d300c9f4056.png)

**Comment by jabo59** [comment]
OK. Thanks for the hint. I had another "configure" message. Did everything to configure and install and now it's working.
