### ISSUE TITLE
[Bug] Client crashes when any keystroke is entered

### ISSUE THREAD

**Issue by roda37** [rustdesk/rustdesk#3108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

Connection to a host is possible. I does connect fine. However despite mouse working fine and mouse input does work the keyboard does not at all.

### How to Reproduce

Click any key

### Expected Behavior

I expect keyboard to work

### Operating System(s) and RustDesk Version(s) on local side and remote side

Host is Windows 10 22H2, machine connecting from is Macos Big Sur 11.7.3

### Screenshots

Here is a video preview of what happens. When I click a button on keyboard the connection drops.

https://user-images.githubusercontent.com/55464245/217297540-ef23127c-8e2d-4e78-a3d4-138952a6b7ee.mp4

**Comment by rustdesk** [comment]
#974
