### ISSUE TITLE
[Bug] Connection problem with Github/Google/Okta

### ISSUE THREAD

**Issue by alexodee** [rustdesk/rustdesk#3111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

It is impossible to connect with Github/Google/Okta

### How to Reproduce

Fix this problem with the different APIs

### Expected Behavior

To be able to connect easily in order to offer an optimal comfort

### Operating System(s) and RustDesk Version(s) on local side and remote side

Windows 11 10.0.22623 Build 22623 / RustDesk 1.2.0

### Screenshots

![image](https://user-images.githubusercontent.com/91338066/217360323-a57d2f3a-ed78-4eae-93c8-4d3824205b0a.png)
![image](https://user-images.githubusercontent.com/91338066/217360400-3b29dcca-aa61-45bb-b551-b26ea58c211e.png)
![image](https://user-images.githubusercontent.com/91338066/217360414-e22ac90d-cb3f-4058-afe9-7995bd7b81f8.png)

**Comment by rustdesk** [comment]
server not ready yet
