### ISSUE TITLE
[Bug] Cannot see UAC screen on the client side

### ISSUE THREAD

**Issue by Agych** [rustdesk/rustdesk#3113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

Cannot see UAC screen on the client side

### How to Reproduce

The PC I'm connecting to has RustDesk running as admin.
Connect to the remote PC, see the desktop, launch some program that requires to be run as admin, the image freezes and it's impossible to do anything except for calling and asking the PC's owner to press "Yes" on the UAC screen.
This applies both to standalone and installed versions.

### Expected Behavior

When RustDesk runs as admin, this issue should not occur, I should see the UAC screen of the remote PC, see the dialog window with "Yes" and "No" buttons and be able to press them.

### Operating System(s) and RustDesk Version(s) on local side and remote side

Windows 7 SP1 x64

**Comment by rustdesk** [comment]
install

**Comment by rustdesk** [comment]
wont fix win 7 anymore

**Comment by Agych** [comment]
what? what do you mean?

**Comment by 21pages** [comment]
test ok win10 nightly

**Comment by Agych** [comment]
The problem exists on 1.1.9, haven't tried the nightly

**Comment by Agych** [comment]
Have checked the 1.2.0 nightly, the issue persists.

Why is the issue marked as closed btw? This bug still exists!

**Comment by 21pages** [comment]
nightly host run as admin, client can't see uac on win7? What about click elevation button on host connection manage window?

**Comment by rustdesk** [comment]
Phasing out official win 7 support

**Comment by Agych** [comment]
@21pages ,
but it's already elevated / running as admin..
anyway, will try that tomorrow :-) 

@rustdesk 
What a nonsense. Phasing out one of the last and most popular versions of Windows, what the hell?
It this is indeed true, then RustDesk turns into a certain no-go just like any other anti-Windows software, which would be very sad.

**Comment by Agych** [comment]
@21pages 
> click elevation button on host connection manage window
Couldn't find it, where is is?

**Comment by GoFreeman** [comment]
I have this issue too.
Was considering switching to RustDesk from AnyDesk, and found this bug when I was trying it.
Hope it will be fixed in the near future

**Comment by rustdesk** [comment]
fixed already. 3 choices.
- install
- accept as elevation in nightly portable vesion
- send elevation request on local side

**Comment by Oszy88** [comment]
I tried version 1.2, but i have the same problem.  

Can you show in a pic this: "click elevation button on host connection manage window?"

If i go personaly to the pc i can install Rustdesk?
