### ISSUE TITLE
[Bug] missing api-ms-win-shcore-scaling-l1-1-1.dll error when start on Windows 7

### ISSUE THREAD

**Issue by yangshujing** [rustdesk/rustdesk#3117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

missing api-ms-win-shcore-scaling-l1-1-1.dll error when start on Windows 7

### How to Reproduce

missing api-ms-win-shcore-scaling-l1-1-1.dll error when start on Windows 7

### Expected Behavior

can start on Windows 7

### Operating System(s) and RustDesk Version(s) on local side and remote side

windows7

**Comment by rustdesk** [comment]
Close as wontfix, no official win7 support.

**Comment by yangshujing** [comment]
信件已收到，谢谢！
