### ISSUE TITLE
[Bug] RENDEZVOUS_SERVER variable is not used/working with github actions anymore

### ISSUE THREAD

**Issue by nextgen-networks** [rustdesk/rustdesk#3126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

Hello rust-team and community,

since a couple of days the parameter RENDEZVOUS_SERVER as well as RS_PUB_KEY no longer seems to be taken into account when building the nightly releases with github actions.
Issue was faced with the Windows executables but other platforms may affected also.

Both parameter "should" work - here you can see how they are currently set up:
![image](https://user-images.githubusercontent.com/21206978/217586074-57f24c19-dd80-4b36-82a1-47132a52ad34.png)

### How to Reproduce

1. Clone rustdesk repo
2. set permissions to "Read and write permissions" in -> Settings / Actions / General / Workflow Permissions
3. create "New Repository Secret" in -> Settings / Secrets and Variables / Actions / Actions secrets and variables
    (you maybe have to create a new environment before and configure a "deployment branch rule" and set the branches you want to apply this rule in "Deployment branches" and choose "Selected branches"
4. start the nightly build with the branch that the secrets are applied to via -> Actions / Flutter Nightly Build / Run Workflow
5. use the created (windows) binary and try to connect via your own hosted rustdesk-server - a connection error will appear after timeout

Cross-check: enter the secrets uses for building the release into the proper sections in the rustdesk client leads instant to a working connection.

### Expected Behavior

Secrets delivered in cloned Github repo should be taken in account within build process and should lead to a realease that don't require any manual configuration to connect via own hosted rustdesk server.

### Operating system(s) on local side and remote side

Windows 10 & 11

### RustDesk Version(s) on local side and remote side

1.2.0 nightly

**Comment by rustdesk** [comment]
Sadly, original contributor stop maintaining thisfeature. Do you have interest to maintain this feature? If we can not find, we will remove this feature.

**Comment by nextgen-networks** [comment]
Thanks for the status information.
I've setup a test branch with some minor changes in variable declaration 
to check what I'm able to achieve and keep you (and this issue) updated.

Am 2023-02-09 01:50, schrieb RustDesk:

**Comment by rustdesk** [comment]
Thanks

**Comment by botanicvelious** [comment]
This was working the other day for me I'll check it when I get home later

**Comment by botanicvelious** [comment]
I tried it and it worked with my fork without any issues, are you maby expecting it to fill in the config options in the client? it just does it transparently.

**Comment by botanicvelious** [comment]
My fork is up to date with rustdesk

This branch is up to date with rustdesk/rustdesk:master. 

How are you seeing that it isnt working?

**Comment by nextgen-networks** [comment]
> How are you seeing that it isnt working?

Connection via my self hosted rustdesk server is only possible if server adress and key is provided manually via GUI.

A message to consider hosting a own server is shown if no variables are provided in GUI (like in the default unconfigured builds provided here).

**Comment by botanicvelious** [comment]
sounds like you added the wrong key or url in the secrets. Try re-adding them then rebuilding with github actions.

far as im aware there is no way to see the default url and key that is built into the client. I assume this was done on purpose @rustdesk if not I could change that code so its easier to troubleshoot?

**Comment by nextgen-networks** [comment]
> sounds like you added the wrong key or url in the secrets. Try re-adding them then rebuilding with github actions.

Nope that should not be the problem readded them already and also cloned that repo with my company account and faced the same problems there.
It was working for a short period of time - approx from mid until end of January.
For me it looks like the respective code to have a custom server configured has been removed:

This is the curent version of the code in "/libs/hbb_common/src/config.rs":
`pub const RENDEZVOUS_SERVERS: &[&str] = &[`
`    "rs-ny.rustdesk.com",`
`    "rs-sg.rustdesk.com",`
`    "rs-cn.rustdesk.com",`
`];`

> far as im aware there is no way to see the default url and key that is built into the client. I assume this was done on purpose @rustdesk if not I could change that code so its easier to troubleshoot?

Jepp I'm aware of that both variables are not visible in the client. This is the expected behavior.

**Comment by botanicvelious** [comment]
line 53 should have 

```rust    
pub static ref PROD_RENDEZVOUS_SERVER: Arc<RwLock<String>> = Arc::new(RwLock::new(match option_env!("RENDEZVOUS_SERVER") {
        Some(key) if !key.is_empty() => key,
        _ => "",
    }.to_owned()));
```

you are using windows right? can you open resource monitor and check what ip it is making the connection to when you click connect to be sure its rustdesk.com servers

**Comment by nextgen-networks** [comment]
ohhh - hell I'm deeply sorry - I think I answered the cause of the problem already in the first post of this issue :-/
While recreating the the repository I made the mistake to create environment secrets and not repository secrets (see https://github.com/rustdesk/rustdesk/issues/3126#issue-1576437698).

Enviroment secrets are not into account while building the binaries.

Sorry @botanicvelious and @rustdesk  for keeping you busy with this non-problem for so long :-/ *aaargh*

**Comment by rustdesk** [comment]
> Sorry @botanicvelious and @rustdesk for keeping you busy with this non-problem for so long :-/ _aaargh_

But you save us time to answer the same question in the future.
