### ISSUE TITLE
When using an Android device in portrait mode, the keyboard covers its own FAB

### ISSUE THREAD

**Issue by FlareHeart** [rustdesk/rustdesk#3131]
I am using my Pixel 5 device to control my Windows desktop at home, but if I open the keyboard (while in portrait orientation) I am unable to close it (the keyboard appears over its own FAB) and the whole control bar at the bottom becomes non-responsive. I have to swipe down from the top of the screen, press the home button, then switch back to the RustDesk app and the keyboard will be closed. 

Edit to add: Just discovered, if I rotate the screen 90 degrees and then back again, the FAB comes out from under the keyboard.
Edit again: This seems intermittent. Sometimes the FAB loads under the keyboard and sometimes it pops up high enough to be touchable.  

Device: Pixel 5
Android version: 11
Keyboard: GBoard
RustDesk Windows version: 1.1.9
RustDesk Android version: 1.1.10-1

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by rustdesk** [comment]
Upload screenshots please.

**Comment by rustdesk** [comment]
Video is better.

**Comment by FlareHeart** [comment]
[Here is an album](https://photos.app.goo.gl/QE2p89bmRszywqJs7) with both a screenshot showing the FAB being covered by the keyboard as well as a video showing it happen and how the keyboard sort of pops above the blue bar the first time, rather than covering it up properly like it does on later attempts. 

I can successfully repro it regularly by swiping the app out of recents and loading it fresh. On first connect it seems to always cover the FAB rather than be in the normal position.

**Comment by rustdesk** [comment]
Thanks

**Comment by Heap-Hop** [comment]
Hi, @FlareHeart  thanks for your report, we just adjusted FAB position on keyboard showed. Please try a new nightly build tomorrow.

The reason for this issue may be a little weird, and could be related to some mechanisms of Flutter and Android. 
We may follow up this in the future.

**Comment by FlareHeart** [comment]
Fantastic thanks. I'll watch for the new build and test it out.

**Comment by FlareHeart** [comment]
I downloaded the nightly but it won't install on my device. 
Pixel 5 -> Android 11 (yes I know I'm out of date, I don't like the changes made in 12, and 13).

**Comment by Heap-Hop** [comment]
@FlareHeart 

> but it won't install on my device

Is there any error message when your installing failed?

**Comment by FlareHeart** [comment]
No, it tries to install, asks if I want to update the current version of the app, the progress bar starts, and then it just says "app was not installed."

**Comment by Heap-Hop** [comment]
It might be the different APK signature.
Please uninstall old version, and install new nightly apk.
Notice, uninstall will reset all configs on your Android device.

**Comment by FlareHeart** [comment]
I apologize for the long delay on this testing. IRL got in my way. I did manage to get the nightly installed by removing the previous version first, and the issue does appear to be resolved in the nightly! Thanks so much for looking at this!
