### ISSUE TITLE
#![windows_subsystem = "windows"]

### ISSUE THREAD

**Issue by 291598912** [rustdesk/rustdesk#3132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

Closing the console does not work
>cargo build --release --features  inline

### How to Reproduce

>cargo build --release --features  inline

### Expected Behavior

I want to pack and close the cmd console

### Operating system(s) on local side and remote side

windows11

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

wu

### Additional Context

I want to pack and close the cmd console

**Comment by rustdesk** [comment]
#763
