### ISSUE TITLE
[Bug] Error: Dart library 'dart:ffi' is not available on this platform.

### ISSUE THREAD

**Issue by lihui123456** [rustdesk/rustdesk#3133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

Android studio编译web端报错

### How to Reproduce

flutter web端编译

### Expected Behavior

希望作者能出个正常编译各端的教程，网上很多人编译不通过

### Operating system(s) on local side and remote side

linux上用Android studio编译

### RustDesk Version(s) on local side and remote side

local

### Screenshots

![image](https://user-images.githubusercontent.com/14088043/217766581-871afa54-383a-48fb-96f8-02ac88ba4d0b.png)

**Comment by rustdesk** [comment]
#763
