### ISSUE TITLE
[Bug] Remote sound

### ISSUE THREAD

**Issue by giuliovale** [rustdesk/rustdesk#3134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

Windows 11 -> Windows 11, I hear the sound of the remote computer
Windows -> OSX , the sound of the remote computer is not heard

### How to Reproduce

Simple connect

### Expected Behavior

Hear the sound of the remote computer

### Operating system(s) on local side and remote side

Windows 11 -> OSX

### RustDesk Version(s) on local side and remote side

nightly -> nightly

**Comment by rustdesk** [comment]
Known issue.

**Comment by rustdesk** [comment]
Actually not implemented yet since starting the project.

**Comment by rustdesk** [comment]
In milestone.
