### ISSUE TITLE
ID is GENERATING Issue

### ISSUE THREAD

**Issue by josephjosedev** [rustdesk/rustdesk#314]
When RUST DESK is installed and opened, it will show that the ID is GENERATING .Is there any solution?

**Comment by rustdesk** [comment]
I will investigate. Thanks.

**Comment by josephjosedev** [comment]
![IMG-20211126-WA0003](https://user-images.githubusercontent.com/71834579/143579771-d68e724f-88ae-400f-bf80-46d83c53f612.jpg)

**Comment by josephjosedev** [comment]
IS RustDesk support Ubuntu32bit ?

**Comment by rustdesk** [comment]
> IS RustDesk support Ubuntu32bit ?

Not yet.

**Comment by rustdesk** [comment]
Can you build and run this open source version?

**Comment by rustdesk** [comment]
> it is GOVERNMENT IP

**Comment by josephjosedev** [comment]
> > IS RustDesk support Ubuntu32bit ?
> 
> Not yet.

currently  32 bit and 64 bit rustdesk available for windows.but rustdesk not support on 32bit ubuntu machines.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/24

**Comment by alexya** [comment]
I met a similar issue. ID is always generating and prompts me `Connecting to the RustDesk network...` in the RustDesk tool status bar.
I tried `telnet rs-sg.rustdesk.com 21116` in the windows command window, then it show nothing. about 1~2 mins later, it back to the windows command prompt. nothing happened. 
my OS is win10

![image](https://user-images.githubusercontent.com/2831220/172528322-787bfb7a-27ab-49d9-845a-6426594d1796.png)

**Comment by josephjosedev** [comment]
I discuss the above issue with our networking team friends, they says that
it happen due to port(port blocked ) issue.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/376

**Comment by rustdesk** [comment]
from reddit
![2](https://user-images.githubusercontent.com/71636191/175451850-684e1d54-6488-4141-a591-35e93b76c382.png)

**Comment by cpcbegin** [comment]
I have no problem with port because Windows version runs OK but Linux Mint Mate 20.3 (64bits) NO.

**Comment by rustdesk** [comment]
> I have no problem with port because Windows version runs OK but Linux Mint Mate 20.3 (64bits) NO.

Then, we have no clue either.

**Comment by WaleedMortaja** [comment]
I had the same problem. I found my problem was seemingly in my ISP DNS server.
When my machine requests a domain like `rs-sg.rustdesk.com`, the ISP DNS times out with no response. Later, my machine requests `rs-sg.rustdesk.com.domain.name` which returns an IP address. rustdesk tries to connect to that IP on port 21116/UDP, but it gets ICMP (Port Unreachable) response.

Changing my machine's DNS to `1.1.1.1`, `9.9.9.9` or `8.8.8.8` did the work. Now, `rs-sg.rustdesk.com` gives a reponse (which is a different IP from the one that was returned for `rs-sg.rustdesk.com.domain.name`).

Seeing that there are many issues raised for this, could be a mis-configuration on rustdesk DNS server?
( I tried to check the validity of DNSSEC, but I got contradicting results, for example it works [here](https://geekflare.com/tools/tests/h54rmccj0), but I think there appears to be some issues [here](https://dnssec-analyzer.verisignlabs.com/rs-sg.rustdesk.com), so I am not sure if it is the cause)

**Comment by hanweikung** [comment]
I am having the same issue. I am using RustDesk 1.1.9 on Ubuntu 22.04. When I launched RustDesk from the terminal, the terminal kept showing id updated, but the GUI always showed generating id. I can successfully `telnet rs-sg.rustdesk.com 21116` though.

![Screenshot from 2022-10-23 10-25-02](https://user-images.githubusercontent.com/643825/197370526-d3450c91-170b-4cd4-8e61-a1b63b709fd7.jpg)

**Comment by rustdesk** [comment]
udp

**Comment by lxne** [comment]
Why is this closed?
I do have the same issue.
Is there a solution?
