### ISSUE TITLE
[Bug] Memory leak - 2/7/23+ nightly, M1/macOS (improve decodeImageFromPixels performance, or use native rendering with texture)

### ISSUE THREAD

**Issue by working-name** [rustdesk/rustdesk#3141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

If Rustdesk is running for a couple hours, it'll slowly increase its RAM usage but won't stop.

### How to Reproduce

Get a nightly (2/7/23 and on), run it on macOS (with M1?) and have it connected to one of your stations in the background. Within 1h your mac should be screaming at you to force-quit something to release memory.

### Expected Behavior

Don't chew on my ram sticks.

### Operating system(s) on local side and remote side

macOS 13.1 -> Windows 11 21H2

### RustDesk Version(s) on local side and remote side

1.2.0 (2023-01-07 05:13) -> 1.2.0 (2023-01-09 00:29)

### Screenshots

<img width="743" alt="Screenshot 2023-02-09 at 1 50 42 PM" src="https://user-images.githubusercontent.com/16505052/217923305-a2f46b1b-751b-40fd-a031-73076a9a9c26.png">

### Additional Context

I guess the up-side of this: you're as good at coding as Microsoft itself. Their auto-updater also has a fat memory leak because I block its outgoing connections.

**Comment by fufesou** [comment]
Thanks for your feedback.
I'll try to fix this issue.

**Comment by rustdesk** [comment]
I have not found memory leak so far after running a connection for more than 15 minutes.

**Comment by rustdesk** [comment]
reproduced

**Comment by fufesou** [comment]
@working-name Hi, I've found a memory problem. But I'm not sure it is the same to yours.

Can you please download the next ngihtly build, and try? Thx

**Comment by rustdesk** [comment]
Let's keep this issue open until we solve the poor performance of decodeImageFromPixels. Current performance is not acceptable, it is even slower than video decoding? It is a big bottleneck.

![image](https://user-images.githubusercontent.com/71636191/218071885-b4f0d64f-885c-4f4d-8ade-55be78f7821e.png)

**Comment by Kingtous** [comment]
I think we can do a refactor to change the rendering from the passive to the positive mode.  Once the processing speed of flutter cannot catch up with the speed of producing events by rust native codes, the memory leak increases forever.

**Comment by working-name** [comment]
I've tried the nightlies and have not found the memory leak issue happen again. The only thing was 1 crash but did not dig into why, it was an isolated incident. Great job!

**Comment by rustdesk** [comment]
Let us know if you see the crash and get some clue.

**Comment by rustdesk** [comment]
Reopen because performance is still bad, may have to use texture directly to avoid flutter cost.

https://github.com/flutter/flutter/issues/38601
https://api.flutter.dev/flutter/widgets/Texture-class.html

**Comment by MatthewZMD** [comment]
![IMG_20240129_161317.jpg](https://github.com/rustdesk/rustdesk/assets/12422335/c49ae68b-9ae3-47e7-a7a2-71eb12f16176)

My computer is completely frozen, seemingly related rustdesk. I have to reboot forcefully.

**Comment by yves-surrel** [comment]
Experiencing also a memory leak with RustDesk 1.4.3 (can grow up to over 1Gb):


<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/b2d1057d-750b-49b5-8d50-72aeb4efbc8c" />

**Comment by rustdesk** [comment]
> Experiencing also a memory leak with RustDesk 1.4.3 (can grow up to over 1Gb):

Coud you confirm your OS? could you also try old versions? So that we can confirm which version the issue starts to happen.

**Comment by yves-surrel** [comment]
macOS Tahoe 26.1, Mac mini M4.

[rustdesk_issue.tif](https://github.com/user-attachments/files/23728566/rustdesk_issue.tif)

Sorry it will not be possible to try older versions of RustDesk...
