### ISSUE TITLE
[Bug] Reset by peer, reconnect after keyboard input on nightly build arm64 ubuntu

### ISSUE THREAD

**Issue by aresyy** [rustdesk/rustdesk#3142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

The environment I tested:

Mac m1 rustdesk 1.1.9           --->     vm ubuntu 22.04 arm64 rustdesk 1.2.0 nightly build date 2023-02-09 01:15
Mac m1 rustdesk 1.1.9           --->     xavier ubuntu 18.04 arm64 rustdesk 1.2.0 nightly build
Ubuntu rustdesk 1.1.9 x86    --->     xavier ubuntu 18.04 arm64 rustdesk 1.2.0 nightly build

After initial connection, when I input normal keyboard, like "a, b, c, d",
On the local client, it shows reset by peer, then reconnects.
On the remote client, it's like someone presses the keyboard but not releases it, so it keeps printing the keyboard input.

Seems like it only happens on the middle layout part keyboard input like "a, b, c, d, ., /, ", 
but for "shift, ctrl, opt, cmd, enter, backspace, space", it works fine.

Also, I tried, 
Mac m1 rustdesk 1.2.0  x86 2023-02-08 07:42   --->    vm ubuntu 22.04 arm64 rustdesk 1.2.0 nightly
Mac m1 rustdesk 1.2.0  x86 2023-02-08 07:42   --->    xavier ubuntu 18.04 arm64 rustdesk 1.2.0 nightly build

This time every keyboard input does not work on both map/legacy modes. But it also not shows reset by peer, no reconnects as well.

I couldn't find any log places. On the remote client side, `systemctl status rustdesk` didn't show any log related to these issues.

These environments work well:
Mac m1 rustdesk 1.1.9      <--->     ubuntu 18.04, 20.04 x86 rustdesk 1.1.9

Any suggestions will be appreciated.

### How to Reproduce

When connect, it happens

### Expected Behavior

work as expected

### Operating system(s) on local side and remote side

mac m1 -> ubuntu(18.04, 22.04)

### RustDesk Version(s) on local side and remote side

(1.1.9, 1.2.0) -> 1.2.0

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
I have tested from mac to arm ubuntu, no problem found, which language / keyboard are you using?

**Comment by aresyy** [comment]
Interesting, I'm using a pretty normal English keyboard.

I tried again with a clean reboot.

I found log on the mac m1 client may be related to this issue.
[2023-02-10 14:10:49.359163 +08:00] ERROR [src/keyboard.rs:257] rdev Error: EventTapError

MacOS Monterey 12.6
MacBook Pro (14-inch, 2021)

RustDesk
Version: 1.2.0
Build Date: 2023-02-08 07:42

**Comment by aresyy** [comment]
I think I found keyboard issue on.

Mac m1 rustdesk 1.2.0 x86 2023-02-08 07:42 ---> vm ubuntu 22.04 arm64 rustdesk 1.2.0 nightly

Since I uninstall rustdesk 1.1.9 and install rustdesk 1.2.0 on Mac m1. I have to manually remove and add again rustdesk on System & Security Accessibility to grant permission for rustdesk.

I think the above log is system won't allow rustdesk to access keyboard.

Also, seems like 1.2.0   --->   1.2.0 has works with some defects.

1. Insert Lock will cause "reset by peer"

remote client log:

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 108', /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/slice/sort.rs:203:26
```

2. Remote client lock screen or unlock screen some time cause "reset by peer" as well

remote client log:

```
rustdesk[2686]: Authorization required, but no authorization protocol specified
rustdesk[2686]: cannot open display: :0
```

Since I'm using release version, not extra log can be provided

**Comment by aresyy** [comment]
I think I can work with 1.2.0  ---> 1.2.0 for now. Feel free to close this ticket.

Thanks for helping

**Comment by fufesou** [comment]
> Mac m1 rustdesk 1.2.0 x86 2023-02-08 07:42 ---> vm ubuntu 22.04 arm64 rustdesk 1.2.0 nightly

@aresyy Hi, I've tested "Insert Lock" on Win --> Ubuntu x64. It works fine.
Is your ubuntu arm64 Desktop or Server version? I can only find Ubuntu Arm64 Server.

**Comment by rustdesk** [comment]
> remote client log:
> 
> ```
> rustdesk[2686]: Authorization required, but no authorization protocol specified
> rustdesk[2686]: cannot open display: :0
> ```

@aresyy do you refer to this?

![image](https://user-images.githubusercontent.com/71636191/218055778-477d738e-7432-4899-93cf-6fb0cef7541c.png)

**Comment by aresyy** [comment]
> 

@fufesou desktop version Linux vm 5.15.0-58-generic aarch64 GNU/Linux

**Comment by aresyy** [comment]
> > remote client log:
> > ```
> > rustdesk[2686]: Authorization required, but no authorization protocol specified
> > rustdesk[2686]: cannot open display: :0
> > ```
> 
> @aresyy do you refer to this?
> 
> ![image](https://user-images.githubusercontent.com/71636191/218055778-477d738e-7432-4899-93cf-6fb0cef7541c.png)

Yes, seems like lock screen will cause the display not be found and reset by peer.

Also, after remote machine reboot if I don't perform login in directly on a remote server, and connect with rustdesk, then login in through remote desk, it will also cause display not found. But I can connect again.

**Comment by rustdesk** [comment]
Before we tested lock, no issue like you. @fufesou need to confirm this also, but I guess it is unlikely to be reproduced.

**Comment by aresyy** [comment]
Default ubuntu 22.04 use wayland, but it requires confirm share screen after lock. Then I edit `/etc/gdm3/custom.config` to disable wayland. Wayland itself won't allow connection on lock screen. This bug occurs on X11.

**Comment by fufesou** [comment]
@aresyy Hi, "Log out" is not supported.
Because the login window is wayland and cannot be captured.

"Lock" is supported in my test.

**Comment by aresyy** [comment]
@fufesou I understand "Log out" should not be supported. 
For "Lock" and my observation:

On Wayland, since Ubuntu requires to confirm share screen, so on local side, it show black screen after "Lock". And on the remote side, I need to click share manually, then Rustdesk shows the screen again.

![image](https://user-images.githubusercontent.com/8334724/218371189-e8115b17-57c3-4322-b307-7162fded2452.png)

On X11, I suspect Ubuntu reload display, so the client side will show reset by peer. Then client reconnects again to the remote will work.

**Comment by fufesou** [comment]
> On X11, I suspect Ubuntu reload display, so the client side will show reset by peer. Then client reconnects again to the remote will work.

The client sould not show "Reset by peer" on X11 after locking. It seems the server process is terminated and restarted by the service again. Can you please paste some logs here, thx. 
```
sudo journalctl -f
or some other journactl usages, eg journalctl -S "2022-02-13 14:00:00" -U  "2022-02-13 14:10:00"
```

For Wayland on my observation:

"Lock" and "Unlock" are not well supported now.
Screen sharing is stopped after locking.
The confirmation is needed after unlocking. And it is required only one time each time the OS starts up.

**Comment by aresyy** [comment]
@fufesou sorry for late

Here is the remote client log for local client hit "Insert Lock"

```
Feb 16 18:36:21 vm rustdesk[3382]: flutter: launch args: [--cm]
Feb 16 18:36:21 vm rustdesk[3382]: flutter: --cm started
Feb 16 18:36:21 vm rustdesk[3382]: flutter: initializing FFI cm
Feb 16 18:36:21 vm rustdesk[3382]: flutter: _appType:cm,info1-id:b477f66e4bd843f2b9b89e9149eb86a2,info2-name:Ubuntu,dir:/home/ares/Documents
Feb 16 18:36:21 vm rustdesk[3382]: flutter: _globalFFI init
Feb 16 18:36:21 vm rustdesk[3382]: flutter: _globalFFI init end
Feb 16 18:36:21 vm rustdesk[3382]: flutter: registerEventHandler theme theme
Feb 16 18:36:21 vm rustdesk[3382]: flutter: registerEventHandler language language
Feb 16 18:36:39 vm rustdesk[2380]: thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 108', /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/slice/sort.rs:203:26
Feb 16 18:36:39 vm rustdesk[2380]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Feb 16 18:36:40 vm rustdesk[3382]: flutter: clients not match!
```

For "Lock" directly on remote client, it works on my machine today. For the reference, I found the log last week.

```
Feb 10 11:13:29 vm rustdesk[5354]: Authorization required, but no authorization protocol specified
Feb 10 11:13:29 vm rustdesk[5354]: cannot open display: :0
```

**Comment by fufesou** [comment]
@aresyy Sorry for late. Thanks for you helpful reply.

The first log has no matter with "Reset by peer". It's about starting info.

> thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 108', /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/slice/sort.rs:203:26

But this log is very important, there's something wrong when on starting.

The second log is very strange. It shows rustdesk on this machine is starting, but failed with "no authorization protocol specified". It should be exact near where rustdesk is down on peer side.
1. I will try to find what "no authorization protocol specified" means, and how it happen?
2. Can you please try to find some messages just before the second logs.

**Comment by fufesou** [comment]
I didn't see the discussion before carefully. The 'thread panicked' and the other log is discussed before.
Anyway I'll test the panic again.

> Also, after remote machine reboot if I don't perform login in directly on a remote server, and connect with rustdesk, then login in through remote desk, it will also cause display not found. But I can connect again.

Which remote desk did you use to login? Maybe rustdesk cannot connect when this remote desk is running.
