### ISSUE TITLE
[Bug] Mouse around the black border, still controlling the controlled PC

### ISSUE THREAD

**Issue by youhers** [rustdesk/rustdesk#3143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

In the process of operation, sometimes it is not necessary to operate the client. At present, it is necessary to put the mouse on the top of the task bar or dialog box, which is very inconvenient. I don't know whether there is a repair plan

### How to Reproduce

Control any computer, not the server operating system

### Expected Behavior

After control, only the page mouse of the controlled end should react

### Operating system(s) on local side and remote side

WIN10 - WIN7

### RustDesk Version(s) on local side and remote side

1.2.0 - 1.2.0

### Screenshots

![截图_20230210134212](https://user-images.githubusercontent.com/106003909/218011695-09134c8d-a4e9-4dab-9c6b-9b96c75af1dd.gif)

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
do not send the event in this case.

**Comment by fufesou** [comment]
@youhers Hi, you means putting mouse over the remote image, and do not send any event through, some shortcut like "Ctrl +Alg +G" in vmware?

**Comment by rustdesk** [comment]
only mouse

**Comment by youhers** [comment]
When the mouse no longer controls the remote picture, move the mouse to the black area, move the mouse in the black area, and still control the client's picture. I think it moves in the black area without controlling the inside of the picture.

**Comment by youhers** [comment]
I am using translation software, if inaccurate, please understand, sorry
