### ISSUE TITLE
[bug]Nightly version cannot run on kylinos-arm64

### ISSUE THREAD

**Issue by iuiuiu1818** [rustdesk/rustdesk#3144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

The nightly version is installed in kylinos-arm64, running Rustdesk, prompt `[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(57)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed.`

**Comment by rustdesk** [comment]
#3565
