### ISSUE TITLE
[BUG] UI: On Linux the option "allow-always-software-render" is flickering when hovering the app

### ISSUE THREAD

**Issue by grummbeer** [rustdesk/rustdesk#3147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

On Linux the option is flickering when mouse enter and leave the app canvas.

Seems that this is depend on the "Toolip", without there is no flickering.

### How to Reproduce

Open Settings | General

Move the mouse over the edge of the app canvas. The option is flickering.

### Expected Behavior

No flickering.

### Operating system(s) on local side and remote side

Linux

### RustDesk Version(s) on local side and remote side

1.2.0 build from source today

### Screenshots

https://user-images.githubusercontent.com/67791701/218052159-5522edab-657f-470d-bca3-6d1a7f646e4c.mp4

### Additional Context

Only on Linux

Video shows that the left side is not affected, but it is.

**Comment by rustdesk** [comment]
I thinik this is out of our control, a Flutter engine problem. Though maybe we can find a workaround, but I do not think it deserves the effort.

**Comment by rustdesk** [comment]
Anyway, Thanks, it is a good finding.

**Comment by rustdesk** [comment]
Let's wait for Flutter update.

**Comment by grummbeer** [comment]
yes … but its hard to accept for me because at other places this is not happen … my flutter/dart experience is just a few hours so far, i take this as a good challenge to get deeper into. :-)

**Comment by rustdesk** [comment]
> at other places this is not happen

If it is an obvious bug, I guess Flutter team had fixed it.

**Comment by grummbeer** [comment]
just for the record/FYI

I already tried the flutter master, but since a fews days this is not longer possible because of a dependency conflict 

```
Because every version of dash_chat_2 depends on intl ^0.17.0 and every version of flutter_localizations from sdk depends on intl 0.18.0, dash_chat_2 is incompatible with

  flutter_localizations from sdk.

So, because flutter_hbb depends on both flutter_localizations from sdk and dash_chat_2 ^0.0.14, version solving failed.
```
https://github.com/molteo-engineering-team/Dash-Chat-2/blob/main/pubspec.yaml#L15

I do not understand this. `^0.17.0` means `min 0.17 and up` and this should include `0.18`

**Comment by rustdesk** [comment]
We can lower our version of flutter_localizations.
