### ISSUE TITLE
[Bug]  audio call clips during linux-windows

### ISSUE THREAD

**Issue by test2a** [rustdesk/rustdesk#3151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

i tried new nightly version on linux host and windows client. the delay kept hovering between 5-25ms  and there was clipping of audio.

without audio calls, delay was never more than 0ms so this is the first time i am seeing that.

i am also reporting very less audio on windows client side but i will investigate that fully before writing a new issue for that

### How to Reproduce

audio call.

i played music on one machine and listened to it on another

### Expected Behavior

audio should work 

### Operating system(s) on local side and remote side

linux>windows

### RustDesk Version(s) on local side and remote side

1.20>1.20 nightly both sides fresh install

**Comment by rustdesk** [comment]
@Kingtous

**Comment by rustdesk** [comment]
@test2a video with sound please if possible.

**Comment by Kingtous** [comment]
Thanks for the feedback. So the problem is the audio clipping, which means we can't listen to the sound fluently right?

**Comment by rustdesk** [comment]
Close as no response.
