### ISSUE TITLE
[Bug] Unable to confirm password

### ISSUE THREAD

**Issue by giuliovale** [rustdesk/rustdesk#3157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

Unable to confirm password

### How to Reproduce

Try changing your password. Each time you type a character in the confirmation box, the cursor moves to password

### Expected Behavior

Confirm the password

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

Nightly build (2023-02-09)

### Screenshots

![image](https://user-images.githubusercontent.com/6909743/218104525-afb1a72e-5564-4071-b0e3-a1e6ac36e74c.png)

**Comment by rustdesk** [comment]
This is intended.

**Comment by rustdesk** [comment]
I know your concern and what you wanna to explain. But we insist current design.

**Comment by rustdesk** [comment]
I misunderstood.

**Comment by rustdesk** [comment]
I do not see your problem. Even it is a problem on your side, i still think so https://github.com/rustdesk/rustdesk/issues/3147#issuecomment-1425570266.

**Comment by rustdesk** [comment]
Next time, please recording a video, reading text is really hard to understand.

**Comment by rustdesk** [comment]
Can you help fix?

**Comment by youhers** [comment]
![截图_20230210220230](https://user-images.githubusercontent.com/106003909/218110914-e4869953-d41b-4f3f-86b6-f89ca2c9c7df.gif)
Let me provide gif

**Comment by RudiOnTheAir** [comment]
Can confirm this.

**Comment by rustdesk** [comment]
> let me provide gif

Wierd, I do not have this problem on my M1,  too bad I do not bring my windows today.

**Comment by RudiOnTheAir** [comment]
I'm using not Windows. On my site it is debian!

**Comment by ajstadlin** [comment]
I have this same issue in Ubuntu 22.0.4 LTS, Rustdesk nightly build 1.2.0, 2023-02-10 11:49

My work around is to Copy the password as text (e.g. from a Text Editor) then Paste the password text into the Password and Confirm fields.

To Paste into the Confirm textbox, I need to hold the mouse button down and Ctrl+V.  If the mouse button is not held down, the focus shifts back to the upper password textbox

//ajs

**Comment by grummbeer** [comment]
https://github.com/rustdesk/rustdesk/blob/master/flutter/lib/desktop/pages/desktop_home_page.dart#L637

the focus is always forced to itself.

**Comment by Zack-Heisnberg** [comment]
and i thought i am getting crazy and mad xD , error still happen
