### ISSUE TITLE
Rustdesk.exe suddenly flagged as a Trojan

### ISSUE THREAD

**Issue by breathless19** [rustdesk/rustdesk#3164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

I'm not sure if this is known or not - I've tried searching and didn't see anyone else mention it, but Rustdesk.exe was just recognized on my system by Windows Security on Windows 11 as a Trojan and automatically quarantined.   I manually restored it and it aggressively quarantined it again.   

Specifically, it is said to be infected with:  Trojan:Win32/Wacatac.B!ml

I've had this Rustdesk exe on my machine for weeks with no issue, then suddenly I was browsing through my downloads folder and Windows Security flagged it and removed it.  I've since restored it, but this is very problematic for giving this exe (which has my hostname and encryption key built into it for easy connection) to Clients only to have it get removed.  

### How to Reproduce

The file was downloaded directly from the official Github nightly releases.  

I'm currently running the server service (hbbs / hbbr files) on this same Windows 11 Pro machine.  Customize Rustdesk.exe client file name with your hostname and the necessary encryption key, and see if Windows Security picks it up.   Note that this filename has "exe" in the filename itself as well as having the exe extension.... Not sure if that matters. 

### Expected Behavior

I would expect it to not get falsely flagged as a trojan

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

![Wacatac Trojan](https://user-images.githubusercontent.com/10132126/218225293-d8bf9908-e083-430b-ad71-03d342ef22bf.png)

**Comment by Benny7587** [comment]
I'm using the nightly buid 1.2.0 from 2023-02-07 08:15 and do not have any issue. Not with Microsoft security nor with Bitdefender Anti Virus. One weird thing is your filename with the double .exe but i doubt if this will be the reason. My filename is: rustdesk-host=xxxxx,key=xxxxx=.exe

**Comment by emedeirosit** [comment]
Symantec Endpoint Protection (Symantec Endpoint Security Enterprise subscription) detected version `1.2.0 2023-01-30 00:20` as a "high risk" file. I remember seeing a mention of the threat name, in the client computer, at the moment it was blocked, but looking at the management console now the name is not shown. I just remember it was a trojan.

**Comment by kintaro1981** [comment]
I think is because of this:
https://github.com/rustdesk/rustdesk/issues/70
and this is related:
https://github.com/rustdesk/rustdesk/issues/3091

Maybe is the way the credentials are sent? or/and the elevation is done?
Teamviewer and Anydesk have not problems and is possibile to send admin credentials and elevate the host.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/2485
