### ISSUE TITLE
Some feedback about operation on iOS

### ISSUE THREAD

**Issue by xmsz** [rustdesk/rustdesk#317]
先原谅我不会英文 只能打中文

然后我最近再找适合自己的远程控制，我的设备
- Mac
- ipad
- iphone

我想要控制mac

我用过了
- teamviewer
- anydesk
- 向日葵
- todesk

但都有自己的问题，然后用了rustdesk，发现问题更大

首先是操控模式，想象中是直接适配触控板，但是实际上除了anydesk，大家都是不完全支持
导致操作起来很不方便，比如拖动要点击一会才能拖，太麻烦了

而rustdesk直接和触控板冲突不能用，不是网络延迟而是直接拖动了整个画布

其次是键盘，键盘大家也是差不多问题就是一些特殊键位没映射，比如tab和上下左右。但基础是能用的
而rustdesk，输入前还要先点击左下角的键盘才能输入太奇怪了

然后是中文输入，大部分软件也做得挺好的，除了anydesk不能支持中文输入，这个也是非常的扯
然后rustdesk可以说支持了一般，就是能支持打中文，但是看不到输入的过程

所以还是挺影响的

--------

然后我目前使用的方案变成了双系统，然后用windows自带的远程控制
还挺完美
✔️  触控板支持
✔️  中文输入支持
✔️  画质清晰 (仅次于anyDesk)
✔️  画面不会被拉伸（toDesk会拉伸屏幕特别搞笑）
✔️  多用户使用 (毕竟实现方式不同，是原生支持)
✔️  主机熄屏 （原生支持的优势）
✔️  有声音 (anyDesk toDesk都是没声音的)

当然缺点就是
- 我其实需要使用的是macOS，而不是windowsOS，现在只能勉强用一下

**Comment by rustdesk** [comment]
Thanks a lot for your feedback.

**Comment by rustdesk** [comment]
https://stackoverflow.com/questions/14391852/windows-h-notification-when-focus-enters-a-text-input
