### ISSUE TITLE
LAN connection support

### ISSUE THREAD

**Issue by lzw-723** [rustdesk/rustdesk#318]
This is a great app and I like it very much.
In my personal use scenario, I like to lie in bed and connect my mobile phone to my desktop computer to complete some basic operations like viewing the task manager.
In this case, connecting to a server on the Internet will waste server resources and increase latency.
It is necessary to support connections that only rely on the local area network.

**Comment by lzw-723** [comment]
The specific problem is that if the two devices are not connected to the Internet, the two devices cannot be connected, but after the connection is disconnected from the Internet, the connection can be maintained only by the LAN.
A self-built server is too difficult for individual users.

**Comment by rustdesk** [comment]
Similar to https://github.com/rustdesk/rustdesk/issues/261

**Comment by lzw-723** [comment]
> Similar to #261

It is my mistake.😂

**Comment by voltagex** [comment]
> A self-built server is too difficult for individual users.

Not if all clients also contain a small server, or if the client is changed to allow direct LAN connections.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/9053#discussioncomment-10333677

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/wiki/FAQ#i-only-use-rustdesk-for-a-few-devices-on-my-local-network-with-no-internet-connectivity-can-i-still-use-rustdesk-with-direct-ip-access
