### ISSUE TITLE
[FR] `Retry`/`Reconnect` button after disconnection

### ISSUE THREAD

**Issue by rakleed** [rustdesk/rustdesk#3182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Add a `Retry`/`Reconnect` button next to the OK button to the popup with a message that the connection was reset. Since now you have to press OK, search for the desired device and reconnect to it, which takes more time than pressing one button. AnyDesk has such feature.

### Impact

If the host/remote user has an unstable connection, then now it is very inconvenient to reconnect every time. Or if on Windows you need to switch to a different user.

### Additional Context

<details><summary>Screenshots</summary>

![Screenshot 2023-01-04 at 02 27 11@2x](https://user-images.githubusercontent.com/19418601/218335849-ce61ca02-8246-45dc-b177-450cf8a4817d.png)

![Screenshot 2023-02-12 at 23 40 56](https://user-images.githubusercontent.com/19418601/218335948-fb100103-e677-4332-842b-a0da4992dfc2.png)

</details>

**Comment by rustdesk** [comment]
@21pages does not it auto reconnect? adding retry button does nake sense.

**Comment by 21pages** [comment]
It will automatically reconnect when the network is interrupted, and I did not find the `Connection Closed` title. Could tell me the software build time?

**Comment by rakleed** [comment]
@21pages the second screenshot with `Connection Closed` from the AnyDesk, added for an example of how it is implemented in other software.

**Comment by test2a** [comment]
I've already requested this here

https://github.com/rustdesk/rustdesk/issues/2623


My feature request is more detailed

**Comment by 21pages** [comment]
> @21pages the second screenshot with `Connection Closed` from the AnyDesk, added for an example of how it is implemented in other software.

Want a retry button for each close,  like reset by the peer ?

**Comment by rakleed** [comment]
> Want a retry button for each close, like reset by the peer?

It would be nice.

> It should reconnect automically when closed unexpected.

When did you add it? Since I have a version from the beginning of January 2023, and I never automatically reconnect.

**Comment by 21pages** [comment]
You can test by changing network.

**Comment by rakleed** [comment]
@21pages if the host has Windows 10+, and I try to switch to another user account (and all accounts are password-protected), then it says that the connection was reset by the user, and automatic reconnection does not occur.

I've also had occasional disconnections, possibly due to internet issues on the host or RustDesk server, and would not automatically reconnect. So on any screen with a disconnect message, it would be nice to have a `Retry` button.

**Comment by rustdesk** [comment]
@21pages 

- [ ] check why not auto connect when switching user
- [ ]  on any screen with a disconnect message, it would be nice to have a Retry button. A outlined reconnect button on the left side of Ok button.

**Comment by 21pages** [comment]
> @21pages if the host has Windows 10+, and I try to switch to another user account (and all accounts are password-protected), then it says that the connection was reset by the user, and automatic reconnection does not occur.
> 
> I've also had occasional disconnections, possibly due to internet issues on the host or RustDesk server, and would not automatically reconnect. So on any screen with a disconnect message, it would be nice to have a `Retry` button.

`Reconnect` button is good idea, but it will automatically reconnect when switching users in my test, installed version on win10.
