### ISSUE TITLE
account can not log in

### ISSUE THREAD

**Issue by yuehun** [rustdesk/rustdesk#3187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

account can not log in
![微信截图_20230213133732](https://user-images.githubusercontent.com/24507941/218379485-3c8c88e4-69ab-45ec-bbbc-feb7299f169d.png)

### How to Reproduce

account can not log in

### Expected Behavior

account can not log in

### Operating system(s) on local side and remote side

win10 64

### RustDesk Version(s) on local side and remote side

1.1.10

**Comment by rustdesk** [comment]
server side not ready yet

**Comment by rustdesk** [comment]
@fufesou but you need to check out the overflow problem of error message.
