### ISSUE TITLE
will SSH be supported on Linux system?

### ISSUE THREAD

**Issue by can2049** [rustdesk/rustdesk#319]
Sometimes, SSH  is useful, when network is not well. We can still work from terminal.

**Comment by rustdesk** [comment]
Actually, you can use our port forwarding

**Comment by rustdesk** [comment]
Can do like RDP.

![image](https://user-images.githubusercontent.com/71636191/147224016-fd3cb7f7-401e-4cc4-b69c-f148ffaa8307.png)

**Comment by solerzhuxy** [comment]
> Can do like RDP (remote side is Win). Add a new menu item called SSH if remote side is Linux.
> 
> ![image](https://user-images.githubusercontent.com/71636191/147224016-fd3cb7f7-401e-4cc4-b69c-f148ffaa8307.png)

Hi, RDP is removed in the nearly version? I didn't see it both in Win10 and ubuntu version.

**Comment by rustdesk** [comment]
Why do we remove it?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/blob/master/src/ui/ab.tis#L320

**Comment by rustdesk** [comment]
Design something like current RDP to make ssh easier. 
- name
-  password
-  port
-  key

**Comment by rustdesk** [comment]
+ https://github.com/rustdesk/rustdesk/issues/1088

**Comment by ceewanna** [comment]
Why my rustdesk doesn't show RDP ?  How to get it there? Any specific setup needed?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/49
