### ISSUE TITLE
[Bug] CreateWindowInBand code 0x57

### ISSUE THREAD

**Issue by clem2** [rustdesk/rustdesk#3192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

A small window titled CreateWindowInBand appears in the remote side after opening the session. It says "The parameter is incorrect.
, code 0x57"

### How to Reproduce

open a session

### Expected Behavior

no window

### Operating system(s) on local side and remote side

Win 10 -> Win 8.1

### RustDesk Version(s) on local side and remote side

1.2.0 2023-02-10 01:24 both sides

### Screenshots

![rustdesk createwindowinband](https://user-images.githubusercontent.com/7561576/218405213-36a27ffc-beb2-4800-8700-c0e00bef042c.png)

**Comment by rustdesk** [comment]
Phasing out win7/8 official support, but we welcome PR.
