### ISSUE TITLE
[FR] run/install rustdesk on linux without root privileges...

### ISSUE THREAD

**Issue by robiwan1** [rustdesk/rustdesk#3199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Rustdesk for linux would be more secure, if it could be run/installed as normal user - therefor a ZIP or TAR.GZ or APPIMAGE package would be neccessary. A ZIP file just could be downloaded, extracted and run as normal user. Anydesk does this...

### Impact

Rustdesk would be more secure, because wether on installation nor on running any root privileges would be neccessary - just a normal user can download and run it...

**Comment by rustdesk** [comment]
use appimage please
