### ISSUE TITLE
[Bug] Laggy & crashing (android -> 5k imac)

### ISSUE THREAD

**Issue by probablykasper** [rustdesk/rustdesk#3200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

When connected to my 5K iMac, the Android app lags a lot (1-2 fps) and eventually crashes.

### How to Reproduce

Connect to macOS and move the cursor around a bit

### Expected Behavior

No lag or crashes

### Operating system(s) on local side and remote side

Android -> macOS

### RustDesk Version(s) on local side and remote side

1.1.10-1 -> 1.1.9

**Comment by rustdesk** [comment]
Try out nightly build please.

**Comment by probablykasper** [comment]
Nightly works great! :D
