### ISSUE TITLE
[Bug]  - Unsatisfied Dependency - PulseAudio

### ISSUE THREAD

**Issue by marcoczen** [rustdesk/rustdesk#3203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

Guys, is the pulseaudio issue  dependency still  unsolved ? 

Its 2023 now ... I had to repack the deb as per https://github.com/rustdesk/rustdesk/issues/559

Pls do consuder fixing the deb file.

### How to Reproduce

Try installing rustdesk in PopOS / Ubuntu 22.x distros

### Expected Behavior

No hard dependency of pulseaudio

### Operating system(s) on local side and remote side

Ubuntu 22.04 LTS based distros

### RustDesk Version(s) on local side and remote side

1.1.9

**Comment by rustdesk** [comment]
nightly build.

**Comment by marcoczen** [comment]
> try out nightly build.

Thank you. 

Updated - I have tested rustdesk in several locations. Its great !!!!
Kindly consider accepting one-off paypal donations pls.

**Comment by Li-Gru** [comment]
> try out nightly build.
> 
> https://github.com/rustdesk/rustdesk/releases/tag/nightly
> 
> commit: [ab33ab3](https://github.com/rustdesk/rustdesk/commit/ab33ab3a50c6c5a9805d24a49d504c65ede67896)

How to "Unlock Network Settings" in nightly build?
blue button, and text "Unlock Network Settings"
debian 12

**Comment by benmotyka** [comment]
Same issue, resolved by installing nightly build

**Comment by Li-Gru** [comment]
![image](https://github.com/rustdesk/rustdesk/assets/8824876/3ab3c624-d050-40d5-9e7b-2fda08170b11)


> Same issue, resolved by installing nightly build

![image](https://github.com/rustdesk/rustdesk/assets/8824876/a9e15759-714c-4c06-a8d8-0b49b9b324a8)

**Comment by Li-Gru** [comment]
in jornald
`polkit-agent-helper-1[2183226]: pam_unix(polkit-1:auth): conversation failed
polkit-agent-helper-1[2183226]: pam_unix(polkit-1:auth): auth could not identify password for [root]
polkitd[1139]: Unregistered Authentication Agent for unix-process:2182971:36550766 (system bus name :1.533820, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
polkitd[1139]: Operator of unix-process:2182971:36550766 FAILED to authenticate to gain authorization for action com.rustdesk.RustDesk.options for unix-process:2182971:36550766 [<unknown>] 
laptop obexd[2927]: DISCONNECT(0x1), <unknown>(0xff)
obexd[2927]: DISCONNECT(0x1), Success(0x20)
obexd[2927]: disconnected: Transport got disconnected`

rustdesk needed root?
