### ISSUE TITLE
[Bug] [GUI] wrong locale detection for traditional chinese

### ISSUE THREAD

**Issue by samul-hwang** [rustdesk/rustdesk#3204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

in translate_locale() of src/lang.rs, check locale contains "TW" for traditional chinese but actually the locale already be converted to lowercase. so should check "tw" to instead.

```
pub fn translate(name: String) -> String {
    let locale = sys_locale::get_locale().unwrap_or_default().to_lowercase();
    translate_locale(name, &locale)
}

pub fn translate_locale(name: String, locale: &str) -> String {
    let mut lang = hbb_common::config::LocalConfig::get_option("lang").to_lowercase();
    if lang.is_empty() {
        // zh_CN on Linux, zh-Hans-CN on mac, zh_CN_#Hans on Android
        if locale.starts_with("zh") {
            lang = (if locale.contains("TW") { "tw" } else { "cn" }).to_owned();
        }
    }
```

### How to Reproduce

it's obviously a coding bug.

### Expected Behavior

just expect to show right GUI language for traditional chinese.

### Operating system(s) on local side and remote side

Linux -> Linux

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

**Comment by rustdesk** [comment]
Fixed in above commit.
