### ISSUE TITLE
[Bug] Permanent password is the same for every user on a single machine

### ISSUE THREAD

**Issue by tatavignot** [rustdesk/rustdesk#3209]
### Permanent password same for every user on a single machine

- [X] I have searched the existing issues

### Bug Description

When you set a permanent password on a machine, this permanent password is used for every user on the machine. 
let's take a real example:
User A set a permanent password.
User B connect to his session and set a permanent password aswell.
When User A will try to connect to the machine using his password, it won't work because it has been replaced by user B's password.

### How to Reproduce

Set permanent password on user A.
set permanent password on user B, on the same machine.
reconnect on user A' session and Try to take control of the machine using user A's password. it will decline the connection

### Expected Behavior

For each user sharing a session on the same computer, be able to set a different permanent password. 

### Operating system(s) on local side and remote side

Ubuntu 20.04, ubuntu 22.04, Windows 10 in any case

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

**Comment by rustdesk** [comment]
We know your concern since we starting this project. But honestly, we also have the other concerns.
