### ISSUE TITLE
[Bug] File transfer window laggy when viewing folder containing thousands of files

### ISSUE THREAD

**Issue by the-yipper** [rustdesk/rustdesk#3211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

Viewing a folder containing thousands of files makes the entire file transfer window laggy.
This doesn't occur using the Android client.

### How to Reproduce

Conduct a file transfer using Windows 10 and access a folder that contains thousands of files (about 2000 on my system). The folder containing the files can be remote or local.

Try to scroll up/down either the local or remote directories, or try other actions within the file transfer window.

### Expected Behavior

No lag, or about as much lag when using the OS default file explorer, performance may be dependent on system specs.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

nightly -> nightly

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by Heap-Hop** [comment]
Thx, reproduced.

**Comment by rustdesk** [comment]
Transfered to @Kingtous

**Comment by rustdesk** [comment]
https://github.com/flutter/flutter/issues/62596#issuecomment-1032428588

**Comment by Kingtous** [comment]
After optimizations: 10,000 files test result.
![Peek 2023-02-15 15-15](https://user-images.githubusercontent.com/39793325/218958263-6cecec3c-88c3-40ed-adb4-7b4afaa78ca1.gif)

After do a refactor which replace the `DataTable` with `ListView.builder`, the file browser has no issues on scrolling or memory and it runs fluently.
