### ISSUE TITLE
[Bug] No online / offline correct status information on Android apk

### ISSUE THREAD

**Issue by mikekgr** [rustdesk/rustdesk#3213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

Using the today (15 / Feb. 2023) 1.2.0 nightly release (I have not tested the older, its my first test in Android), I observed that all remotes are having offline status (orange led) even these are online !

### How to Reproduce

Just run these nightly release and connect to a know online remote, then in the Recent Sessions Window you will incorrectly see it as offline that is not correct !

### Expected Behavior

to see the correct online /offline status as it should in Windows / Linux clients

### Operating system(s) on local side and remote side

Android 13 (OxygenOS) on OnePlus 9 Pro 

### RustDesk Version(s) on local side and remote side

Both running the today nightly release

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/2786

**Comment by mikekgr** [comment]
@rustdesk 
Hello. As I understood you suggesting me to update the server but I already running 1.1.7 ( I updated a few days ago ). Is there any new release ?
Thanks

**Comment by rustdesk** [comment]
Desktop ok, but mobile not?

**Comment by rustdesk** [comment]
Thank @mikekgr, my misunderstanding.

**Comment by mikekgr** [comment]
> Desktop ok, but mobile not?
Yes, in my Windows 10 PC the status seems ok at the same time my Android phone say all remotes as offline.

**Comment by rustdesk** [comment]
BTW, are you sure mobile is connected to self-hosted server?

**Comment by mikekgr** [comment]
One more observation regarding the RustDesk Server, although it remains at 1.1.7 is younger !!! Do I need to re update my 1.1.7 server installation ?

**Comment by mikekgr** [comment]
> BTW, are you sure mobile RustDesk is connected to self-hosted server?

Sure because I can connect to my remotes without problems

**Comment by rustdesk** [comment]
> younger

How old? this feature has been added serveral month.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server/pull/122

**Comment by mikekgr** [comment]
> > younger
> 
> How old? this feature has been added serveral month.

Let me explain better, I update my server from version 1.1.6 to 1.1.7 a few days ago (4-5 or so). Today going to 
https://github.com/rustdesk/rustdesk-server/releases/tag/1.1.7
I saw release time: 15 hours ago  So that is the question

**Comment by Heap-Hop** [comment]
@mikekgr When it happens, can this Android device establish a remote control connection with other devices normally?

**Comment by mikekgr** [comment]
> @mikekgr When it happens, can this Android device establish a remote control connection with other devices normally?

Yes, the remote connection(s) working fine, only the indication is always orange color "let" / offline see the video at URL: 
https://photos.app.goo.gl/b8KVbXmyKMfvEPSX7

Is it more clear now?

**Comment by mikekgr** [comment]
Dear Sirs,
without change anything, today (16 Feb. 2023 I can see the correct online / offline status for my remotes on my Android phone.
I can't explain it though ...

**Comment by rustdesk** [comment]
We can not either. :(

**Comment by mikekgr** [comment]
@rustdesk 
Please explain to me something, on 11 Feb. 2023 I downloaded the below rustserver.zip from 1.1.7 release. As you can see the size of the zip is 8214419 
-rw-r--r-- 1 root root 8214419 Jan 11 05:48 /root/rustdesk-server-linux-amd64-11-02-2023.zip

Yesterday I downloaded the same rustserver 1.1.7 release BUT THE SIZE IS NOT THE SAME please see it below now it is 8214122 
-rw-r--r-- 1 root root 8214122 Feb 14 17:24 /root/rustdesk-server-linux-amd64.zip

Why? Should I "update" my 1.1.7 installation of 11 Feb. with this one (14 Feb.) ?
Thanks !

**Comment by rustdesk** [comment]
No need, only some not important update.
