### ISSUE TITLE
[Bug] get_audio_mode 方法不存在

### ISSUE THREAD

**Issue by yangshujing** [rustdesk/rustdesk#3216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

被控端菜单点击时，返回调式信息：
ERROR:TIS: Error: Element (Element(<video#handler>)) has no method - get_audio_mode
ERROR:TIS:      at toggleMenuState
ERROR:TIS:      at

### How to Reproduce

在被控端菜单点击调节窗口或其他菜单

### Expected Behavior

提供此方法

### Operating system(s) on local side and remote side

win7->win10

### RustDesk Version(s) on local side and remote side

1.1.9->master

**Comment by rustdesk** [comment]
Sciter version not maintained any more.

**Comment by rustdesk** [comment]
But will still fix it soon.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/3230
