### ISSUE TITLE
[Bug] The remote page shows "Failed to connect ..."  even the conn is already established

### ISSUE THREAD

**Issue by fufesou** [rustdesk/rustdesk#3220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

The connection is established. And the images are shown in the window.

But the remote page shows "Failed to connect via rendezvous server: Please try later".  I have to click Ok. The remote page is then dismissed.

### How to Reproduce

Connect through the free server. It does not always appear.

### Expected Behavior

Do not show the dialog after the conn is established.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

ngihtly -> nightly

### Screenshots

![1676452880207](https://user-images.githubusercontent.com/13586388/218986411-d878e95d-f0cb-4001-9065-12cf439f9662.png)

**Comment by rustdesk** [comment]
Dig in please.

**Comment by rustdesk** [comment]
Transfer to @Heap-Hop
