### ISSUE TITLE
[Bug] keyboard input not working, only beeping

### ISSUE THREAD

**Issue by schlomo** [rustdesk/rustdesk#3221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

Cannot type in remote desktop, there is a beep on every key press but nothing is typed

### How to Reproduce

connect to remote desktop

### Expected Behavior

typing should work normally

### Operating system(s) on local side and remote side

Mac OS X 12.6 → Windows 10 22H2

### RustDesk Version(s) on local side and remote side

both 1.2.0 nightly Build Date: 2023-02-15 00:23

### Additional Context

Same connection worked well with 1.1.9 but file transfer didn't work well, so I thought to try out the nightly

**Comment by SystemFuchs** [comment]
Had this behaviour when RustDesk was running in portable mode on my Mac. Installed it, gave it all necessary rights & was able to type normaly in my windows remote session. The binary was moved to the /Applications folder. Also all older permissions in the system settings where deleted. After this steps everything was running as expected

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/974

**Comment by rustdesk** [comment]
Thanks @SystemFuchs
