### ISSUE TITLE
[Bug] After opening the Show Remote Cursor, you can see the client's mouse bouncing during the password entry process

### ISSUE THREAD

**Issue by youhers** [rustdesk/rustdesk#3227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

After opening the Show Remote Cursor, you can see the client's mouse bouncing during the password entry process

打开显示远程光标以后在输入密码的过程中可以看到客户端的鼠标在跳动

Should not see the other party's mouse until there is no control over the other party's desktop

在没有控制对方桌面前不应该能看到对方的鼠标

### How to Reproduce

This problem can be reproduced by simply turning on the setting to display the remote cursor, which allows you to see the other party's mouse moving while entering the password.

只需要打开显示远程光标这个设置就可以复现这个问题，在输入密码的过程中就能看到对方的鼠标在动

### Expected Behavior

You should not see the other party's mouse before entering the password. You should not see the other party's mouse until the input password is controlled.

在输入密码之前不应该能看到对方的鼠标，应该是在被输入密码被控制以后才能显示对方的鼠标

### Operating system(s) on local side and remote side

WIN10 - WIN7

### RustDesk Version(s) on local side and remote side

1.2.0 - 1.2.0

### Screenshots

![截图_20230215224912](https://user-images.githubusercontent.com/106003909/219063912-d468cb9e-43d2-4b4b-96bf-5e5d0e2bd77a.gif)

**Comment by rustdesk** [comment]
@fufesou I knew this also, fix it please.

**Comment by fufesou** [comment]
@youhers This issue may be fixed. Please confirm with the next ngihtly build. Thx
https://github.com/rustdesk/rustdesk/pull/3251

**Comment by youhers** [comment]
Thank you, I will

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/3251
