### ISSUE TITLE
[Bug] RustDesk  report a uninstall error

### ISSUE THREAD

**Issue by CppXL** [rustdesk/rustdesk#3229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

By the tutorial, RustDesk is renamed RustDesk-host=hostip,key=public key.exe, but when I enter RustDesk, but RustDesk ask me to install it

### How to Reproduce

rename the RustDesk.exe to RustDesk-host=hostip,key=public key.exe

### Expected Behavior

Should not remind me to install, because I has install it 

### Operating system(s) on local side and remote side

windows 21h2

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![](https://i.imgur.com/khiyINQ.png)

![](https://i.imgur.com/pkfyXDk.png)

**Comment by rustdesk** [comment]
The tutorial does not tell you rename it in installed dir.

**Comment by rustdesk** [comment]
You should rename it before install.
