### ISSUE TITLE
multiple concurrent users (multiple rdp sessions / terminals)

### ISSUE THREAD

**Issue by test2a** [rustdesk/rustdesk#323]
would it be possible to get multiple clients to hit a windows machine multiple user logins at once? i mean i understand this to be an anydesk/teamviewer alternative than a rdp alternative but still, can users be selected and can multiple people hit a single server at once and not get the same account

**Comment by fufesou** [comment]
For now rustdesk captures picture of the displays.
This idea can be implemented, if multiple accounts login on different displays.
But there seems no way to do this?

Rustdesk can also start rdp client.
On the other way, you can use rdp connection to do this on windows.
https://github.com/anhkgg/SuperRDP

**Comment by test2a** [comment]
@fufesou i currently use rdpwrap to avoid buying cals or whatever but i don;t know what superrdp does. anyways, i haone "this" via anydesk but its janky. maybe you can "automate" it.

i have multiple terminals on the "server" that i need to remote into. instead of initiating the connection from the remote>server, i do the opposite, i start a connection server>remote then reverse the connection. 

i have only achieved this when the account on the server is on and someone can do this manually but i'm not sure if this is making much sense. 
oh, i have also had the idea of " different anydesk IDs per user" on a machine so a remote user can join their own account remotely with password so that is something you can look into. Anydesk does not allow that, they have a per machine id which makes this a bummer but maybe you can try.

**Comment by fufesou** [comment]
@test2a  "SuperRDP is a new version rdpwarp base on the rdpwrap by stascorp." You can learn it very in few minutes.

As I know, SuperRDP may handle your request well.

**Comment by Tapuzi** [comment]
Discussion was useful for me - thank you all.

**Comment by rustdesk** [comment]
![890347658](https://user-images.githubusercontent.com/1255404/212705498-b0815476-52d5-410e-8960-db9fdd065c86.gif)

**Comment by pata2004** [comment]
Thanks for the great work.
Can Rustdesk manage several virtual graphics desktops (different users) on a single remote server?
If yes, how can I set up that?
If not, do you plan to add this function?

**Comment by rustdesk** [comment]
no plan yet

**Comment by pata2004** [comment]
Hi,
I use the Rustdesk to connect to my Centos machine with 4 users/desktops. 
But I never know what user/desktops Rustdesk will go open.
Can I define what user/desktop to connect to?
Or, do I need to use Centos with only the root user?

**Comment by test2a** [comment]
@pata2004 yes. same problem for me. we have  a dozen users and its like a roulette which user you get. Not great ux. if we could only specific, like windows remote desktop connection does, which user to connect to, that would be awesome.

**Comment by tayvermtos** [comment]
Hi

If I may add to the above the following:

I have a VM hosted on my physical Windows 11 machine using HyperV. The VM is also a Windows 11 machine. When I connect to the VM, it uses some kind of RDP to connect to it (it isn't a completely regular RDP session, as for example you can go into the BIOS of the VM which isn't really possible as it runs on OS level).
When the VM is running and I would try to login to this VM via RDP onto the same user, it obviously will terminate the other session, as by standard config more then one RDP session to the same user isn't allowed. 

When using Teamviewer for example, this isn't an issue since it just shows on teamviewer the screen which the rdp session user sees.

BUT, when using RustDesk to remote into the VM mentioned above (hosted on HyperV) as soon as RustDesk connects, it does not allow you to stay connected via RDP. Or the vs versa when logged in via RustDesk and then logging in to the same VM via RDP the following error is displayed on RustDesk: "an existing connection was forcibly closed by the remote host 10054"

I'm unsure why this is happening but it's almost as if RustDesk is considered as another RDP session to the same machine. 

@rustdesk I'm unsure if this is an issue or a limitation, but I'd certainly not be able to use RustDesk if it kicks users off their RDP sessions.

**Comment by vmiwouter** [comment]
@rustdesk Like above, will there be an option that rdp sessions get unique ids?

**Comment by mstarostik** [comment]
Similar here. I have a bunch of VMs and the console session isn't really visible anywhere. Everyone connects via RDP, but when I want to support the users, I'd like to keep their session open and use RustDesk to view the same session. This works, when the software is just started by the user without being installed, but when I install it to also get unattended capabilities, I can only connect to session 0.

**Comment by jb-esselink** [comment]
Same issue here, i am trying to connect to a user specific session. Current state of the application sends me to the windows login screen. Would be nice to have a session specific ID or have a session selection popup in the case of an RDP connection.

**Comment by technoicon** [comment]
+1 we need this function to be able to use RustDesk.
We connect and support multiple users on one Remote Desktop Services Server.
Following to be able to move to rustdesk when functionality is avaliable.

**Comment by rustdesk** [comment]
[![Open Bounties](https://img.shields.io/endpoint?url=https%3A%2F%2Fconsole.algora.io%2Fapi%2Fshields%2Frustdesk%2Fbounties%3Fstatus%3Dopen)](https://console.algora.io/org/rustdesk/bounties?status=open)

**Comment by technoicon** [comment]
How do these bounties work?
I'd be happy to pay for this or chuck in some monies to increase the bounty.

**Comment by rustdesk** [comment]
If you wanna increase the bounty, please have a one-time sponsor on https://github.com/sponsors/rustdesk, I will increase this bounty per your sponsor. @technoicon

**Comment by zcesur** [comment]
@rustdesk thanks for installing the app & trying out the bounty command! that's the best way for maintainers to use algora

your community can also fund bounties themselves here: https://algora.io/org/rustdesk/bounties/new
ex @technoicon could use this. if more folks add bounties on the same issue they get pooled

**Comment by subscribernamegoeshere** [comment]
maybe this is the wrong bug entry but I will start commenting here, sorry to bother, I would like to know what that "remote desktop" checkbox does mean in the rustdesk 1.2.3 version (on windows) i couldnt really make sense of it when activating and triggering this kind of rdp something from a remote machine (windows as well) it would create kind of like a tcp tunnel or so and spawn an mstsc.exe (rdp client on windows, default microsoft) but then fail to deliver any kind of connection or pixels to whatever rdp session that would turn out. i didnt find documentation to this?

my actual question or feature? request would be allowing to connect into the single rdp-ish session there is on personal windows client editions (so not windows server), that windows pro/professional editions support.

is this feature realted to this ticket? i am not totally sure. Maybe terminal services and multiple such rdp sessions inside a machine (server) is then a extended upper set of this feature? would be very glad to see this happening. thanks.

also: how to donate best to this project without wasting funds to payment processors and all. is there a charity or foundation of some sorts that directly supports you, maybe GNU or free software foundation or any such thing? or is github sponsor and that bounty page the best to do so?

i am a paying user of anydesk but they are seriously degrading and deteriorating more and more and I would like to donate my yearly anydesk consts to this project to begin with or so if possible. thanks.

**Comment by strarsis** [comment]
+1, at the moment only TightVNC (at least from knowledge) is able to use RDP-sessions.
It would be awesome if this VNC-alternative also supported RDP-sessions.

**Comment by rustdesk** [comment]
Ready in nightly build now, https://github.com/rustdesk/rustdesk/pull/7184
