### ISSUE TITLE
[Bug]  multi touch not getting transmitted 

### ISSUE THREAD

**Issue by test2a** [rustdesk/rustdesk#3234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

my laptop has two finger scroll option which works locally and in anydesk but not in rustdesk for some reason.

I don't even remember now if it was working earlier, probably was working

### How to Reproduce

laptop host to remote machine

### Expected Behavior

multi finger scroll are not getting transmitted. single finger is working properly, same is multi finger selection, "hold with one finger and move second finger to move the item", that works fine so its not like multi touch is not working.  

### Operating system(s) on local side and remote side

linux>windows

### RustDesk Version(s) on local side and remote side

1.20>1.19

**Comment by rustdesk** [comment]
@fufesou together with https://github.com/rustdesk/rustdesk/issues/2655 higher priority than file copy paste.

**Comment by fufesou** [comment]
@test2a Hi, RustDesk does not support trackpad until https://github.com/rustdesk/rustdesk/pull/1987.
I've tested Linux --> Win, Win --> Win. It works fine now.

Please try both nightly build.

**Comment by fufesou** [comment]
Maybe 1.1.9 support one finger control as you said, I'm not sure.
But multi fingles control is Ok for me.
