### ISSUE TITLE
CreateWindowInband Wrong Parameter. ,code 0x57

### ISSUE THREAD

**Issue by attikov** [rustdesk/rustdesk#3237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

Wrong Parameter. ,code 0x57 window appears after every connection (nightly build, did not see on stable)

 on Windows Server 2012 on a VM

### How to Reproduce

 go figure

### Expected Behavior

 no error

### Operating system(s) on local side and remote side

Windows 2012 Server

### RustDesk Version(s) on local side and remote side

1.20+ 

### Screenshots

 
![grafik](https://user-images.githubusercontent.com/17452773/219363191-2ed86d17-f7b5-4311-b6ae-9d910e576291.png)

**Comment by rustdesk** [comment]
@Kingtous

**Comment by rustdesk** [comment]
@kingtous take a look, if no clue, ignore for the time being.

**Comment by rustdesk** [comment]
#3192

**Comment by Kingtous** [comment]
Seems a windows issue on Windows 8 series. Let's figure out what happened by installing a window 8 vm. btw, any logs in terminal?

**Comment by attikov** [comment]
since the update today I'm getting every second an entry into the logfile:

[2023-02-16 16:12:30.094847 +01:00] DEBUG [src\platform\windows.rs:1352] update portable executable name to rustdesk-1.2.0-x86_64-pc-windows-msvc.exe


thx for the tip, looking into the logfiles <o>

**Comment by attikov** [comment]
to the original issue, the log file is as follows:

[2023-02-16 16:17:47.608730 +01:00] DEBUG [src\ui_cm_interface.rs:458] Got new connection
[2023-02-16 16:17:47.608929 +01:00] DEBUG [src\ui_cm_interface.rs:408] ipc task begin
[2023-02-16 16:17:47.609030 +01:00] DEBUG [src\ui_cm_interface.rs:312] conn_id: 58
[2023-02-16 16:17:49.395778 +01:00] DEBUG [src\ui_cm_interface.rs:450] Failed to get hwnd after started, librustdesk::ui_cm_interface:src\ui_cm_interface.rs:450:9

**Comment by attikov** [comment]
Also Alt+TAB ist not working on this 2012 Server.

**Comment by rustdesk** [comment]
As stated here https://github.com/rustdesk/rustdesk/issues/3192#issuecomment-1427548201. No guarentee to fix.

**Comment by attikov** [comment]
Is it possible that windows 10 also won't be supported in the near future?
Is there some critical part of the application which is not compatible with an OS not reached its EOL?

**Comment by rustdesk** [comment]
For easy reproducing and critical issue, we still try our best.
