### ISSUE TITLE
ubuntu auto start rustdesk when startup server

### ISSUE THREAD

**Issue by dennistsc** [rustdesk/rustdesk#324]
may i know anyone can help? thx u

**Comment by rustdesk** [comment]
What do you mean?

**Comment by dennistsc** [comment]
> What do you mean?

when i restart my ubuntu and the rustdesk didn't startup itself.
i have to open the terminal and type the following:

cd rustdesk
VCPKG_ROOT=$HOME/vcpkg cargo run

then the program startup

**Comment by rustdesk** [comment]
You need create systemd service yuorself or use prebuilt https://github.com/rustdesk/rustdesk/releases/download/1.1.8/rustdesk-1.1.8.deb

**Comment by dennistsc** [comment]
> 

im using anydesk too.
i found out anydesk is faster.
anyway to speed up rustdesk?

**Comment by rustdesk** [comment]
more dev, more contributors. :)

**Comment by dennistsc** [comment]
> more dev, more contributors. :)

i build into my own ubuntu, didn't use from the website

**Comment by dennistsc** [comment]
i go through all the step and build "VCPKG_ROOT=$HOME/vcpkg cargo run"

**Comment by dennistsc** [comment]
> more dev, more contributors. :)

i mean sometime is lagging and smooth

not speed up the r&d....

**Comment by masi0** [comment]
> You need to create systemd service yourself or use prebuilt https://github.com/rustdesk/rustdesk/releases/download/1.1.8/rustdesk-1.1.8.deb

can you share what should be a correct rushdesk serviced file to make sure it will work correctly?
