### ISSUE TITLE
[Bug] UI. New menubar. New style for "mobile action" is missing

### ISSUE THREAD

**Issue by grummbeer** [rustdesk/rustdesk#3240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

icon does not follow the new style.

### How to Reproduce

connect to a mobile device

### Expected Behavior

icon look like the others

### Operating system(s) on local side and remote side

any

### RustDesk Version(s) on local side and remote side

nightly

### Screenshots

![menubar-mobile-action](https://user-images.githubusercontent.com/67791701/219376070-0226e681-a683-4a05-ac8f-cb9cc6bb0ea4.png)

**Comment by grummbeer** [comment]
@NicKoehler The new icons are very cool!

**Comment by NicKoehler** [comment]
I missed that, will fix it
