### ISSUE TITLE
disconnect problem (10054)

### ISSUE THREAD

**Issue by dennistsc** [rustdesk/rustdesk#325]
i set up or build up my ubuntu server and let my friend use it but have a problem
i upload a photot

![mmexport1638888741793.jpg](https://user-images.githubusercontent.com/60589279/145051951-5be45587-d0c3-4d24-a7db-c4d398e77eb1.jpg)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/106

**Comment by rustdesk** [comment]
@dennistsc can you reproduce this issue?

**Comment by rustdesk** [comment]
close this so that we can focus on its dup https://github.com/rustdesk/rustdesk/issues/1113.
