### ISSUE TITLE
[Bug] Privacy mode slows down the FPS

### ISSUE THREAD

**Issue by sascha224** [rustdesk/rustdesk#3254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

When I enable the Privacy mode in the Client, the connection becomes very slow. The FPS decrease to 1-2 FPS, the remote PC becomes unusable. If I disable Privacy mode, all is getting back to normal.

### How to Reproduce

Enable the Privacy mode

### Expected Behavior

The Privacy mode should be as fast as the connection without it enabled.

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.2.0

**Comment by rustdesk** [comment]
We know.

**Comment by rustdesk** [comment]
We are looking for another implementation also, but currently, low priority.
