### ISSUE TITLE
UI (mobile) Canvas overflow 

### ISSUE THREAD

**Issue by grummbeer** [rustdesk/rustdesk#3262]
### Bug Description

Depend on the translate button text, the button become very large and push the state indicator outside the canvas.

### How to Reproduce

use german language

### Expected Behavior

button and state indicator should be both visible in any case.

### Operating system(s) on local side and remote side

android

### RustDesk Version(s) on local side and remote side

build from source

### Screenshots

State indicator and button are visible at the same time

![stop-service-overflow](https://user-images.githubusercontent.com/67791701/219857866-bdeffdd5-884c-4677-9d41-ff821ddd0619.png)

With german translation

- the state indicator is not visible anymore
- the button itself does not fit

![stop-service-overflow-effect](https://user-images.githubusercontent.com/67791701/219857865-6c8d73c6-dfe3-4d5c-a45b-e90dc294ee1d.png)

### Additional Context

Elements needs to be rearranged

Idea:

Healine (Text what currently is button text)

below a row

- left: state indicator, with short text (ready, not ready)
- right: toggeling [Play][Stop] IconButton

**Comment by rustdesk** [comment]
Thanks, please go ahead. You have been doing great job.

**Comment by grummbeer** [comment]
need to build the apk locallly, but … https://github.com/rustdesk/rustdesk/discussions/763 its very inconvienient waiting for the apk build from workflow

**Comment by rustdesk** [comment]
cargo run -d android?

**Comment by rustdesk** [comment]
@21pages since you are working on android, please fix this.

**Comment by grummbeer** [comment]
thanks :)

> cargo run -d android?

no success, "-d" is a unknown option. please don't waste time, i will get it working, just no time next days.

**Comment by rustdesk** [comment]
@grummbeer you do not need to build rust for android, rust library can be extracted from the apk file directly (apk is zip format, `unzip rustdesk-xxx.apk`, under `lib/arm64-v8a/`).

**Comment by grummbeer** [comment]
thank you for your help, [now I can build the lib locally](https://rustdesk.com/docs/en/dev/build/android/), but it was my device from the beginning … ABI, a bit embarrassing. Had to flash it with a current lineage. 

hopefully the last thing to solve. `flutter run -d [device]`
```
F/flutter (14144): [FATAL:flutter/runtime/dart_vm_initializer.cc(89)] 
Error while initializing the Dart VM: Wrong full snapshot version, 

expected   

   '501ef5cbd64ca70b6b42672346af6a8a' 

found 

   'adb4292f3ec25074ca70abcd2d5c7251'


[✓] Flutter (Channel stable, 3.7.5, on openSUSE Tumbleweed 6.1.12-1-default, locale de_DE.UTF-8)
    • Flutter version 3.7.5 on channel stable at ~/dev/flutter
    • Framework revision c07f788888 (vor 5 Tagen), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2

```
Something with a specific flutter or dart version? dependencies? If you have a quick hint that would be fine, if not, no problem, will get it work.

**Comment by rustdesk** [comment]
we are using flutter 3.7.0, not sure if it is related.

**Comment by grummbeer** [comment]
Back on track. It is also a very much better feeling to be able to spot possible side effects in mobile directly. I already produced one and will fix it.


@21pages have you already started on this issue? I'am ready todo now.

**Comment by NicKoehler** [comment]
@grummbeer I'm having the same exact same error, how did you solve it? I tried a bunch of stuff I found on the web, but nothing seems to work.

> expected   
> 
>    '501ef5cbd64ca70b6b42672346af6a8a' 
> 
> found 
> 
>    'adb4292f3ec25074ca70abcd2d5c7251'

**Comment by grummbeer** [comment]
what files you have in "flutter/android/app/src/main/jniLibs/arm64-v8a/"?
Do you have `libflutter.so` and `libapp.so`? Delete them.

rustdesk dir
```
./flutter/ndk_arm64.sh
cp target/aarch64-linux-android/release/liblibrustdesk.so flutter/android/app/src/main/jniLibs/arm64-v8a/librustdesk.so
```

run from cli

```
cd flutter
flutter run -d [Android Device ID]
```

"r" for hot reload or let your IDE do this on file save.

for me, i use the ide for the device i currently focused on and run the other per cli to be able to interact between desktop and mobile. Work on Android per IDE, then in cli `flutter -d Linux`, or vice versa.

**Comment by NicKoehler** [comment]
I'm getting build errors with './flutter/ndk_arm64.sh' I'll find another way to build, my arch installation is a mess, thanks for the help
