### ISSUE TITLE
`Connection Error: Reset by the peer` when switching user in Windows

### ISSUE THREAD

**Issue by rakleed** [rustdesk/rustdesk#3263]
### Bug Description

When switching a user on Windows, if RustDesk is installed, the error `Connection Error: Reset by the peer` appears, instead of automatically reconnecting.

### How to Reproduce

0. All Windows users must be password protected
2. Install RustDesk on a remote computer with a local user (not an administrator)
3. Add password access in RustDesk
4. Connect to the remote computer by entering the password
5. Switch user

### Expected Behavior

When changing user, RustDesk automatically reconnects without losing connection.

### Operating system(s) on local side and remote side

macOS 13 → Windows 11

### RustDesk Version(s) on local side and remote side

1.2.0 nightly

### Additional Context

Continuing the discussion https://github.com/rustdesk/rustdesk/issues/3182#issuecomment-1432525793

**Comment by rustdesk** [comment]
We tested yeterday, but reproduxed yet.

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
@21pages if you still can not reproduce. @rakleed can you let he connect to you for test? you can create an temp account on your machine.

**Comment by rakleed** [comment]
@rustdesk, I can reproduce this on my Win 11 VM, so I can grant access without any problem.

<details><summary>Contacts</summary>

You could write me to rakleed@gmail.com or [@rakleed](https://t.me/rakleed) at Telegram
</details>

But as I understand it, it is important to install RustDesk as a local user, and also that all users have a login password set.

**Comment by 21pages** [comment]
I can't reproduce, sent a email already

**Comment by rustdesk** [comment]
> But as I understand it, it is important to install RustDesk as a local user, and also that all users have a login password set.

answered before, :)

**Comment by 21pages** [comment]
Or you can make a video/gif if convenient.
