### ISSUE TITLE
If lid closed: Screen freezes while alt-tab preview correctly shows state of Windows

### ISSUE THREAD

**Issue by jens-k** [rustdesk/rustdesk#3266]
### Bug Description

Once in a while (sorry for being so vague), when being connected to another machine (both via public or local Rust server), the connection seems to get into a semi-frozen state in which I can still somehow interact with the current window (e.g. mark text) but all further interactions (press buttons, change windows etc.) do not seem to work.

However, if I do perform an action (e.g., press a button) and then use Alt-Tab to see the Windows previews, as if I were to switch to another window, the action was actually performed correctly and the real state of Windows is being shown to me in the preview. The actual screen, however, does not reflect this and remains in thie semi-frozen state.

### How to Reproduce

Connect to remote machine, interact with it for a while.

### Expected Behavior

I would expect the actual screen and the previews to match and to be able to interact with the machine.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

<img width="1127" alt="Captura de pantalla 2023-02-18 163239" src="https://user-images.githubusercontent.com/10050167/219874508-f683d6ec-e40b-4cb2-8f21-083728a014e8.png">

Please note how one window is still shown on the actual screen (Git installation), while it is not among the open windows in the previews (as in reality it is not there anymore).
In contrast, the GitHub installation window is not shown on the actual screen, while it has correctly been started and is shown in the preview.

**Comment by rustdesk** [comment]
Try out nighly build please on both side.

**Comment by jens-k** [comment]
I upgraded both sides to 1.2.0, but that did not help.

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
Could you upload a recording video?

**Comment by felixsevero** [comment]
I'm having a similar problem when I'm doing some remote support.
After a few seconds, I can't interact with the windows anymore, but sometimes I can still press the Windows Start Menu button and interact with the tray icons.
I'm using the latest version of Rustdesk (1.1.9) and both machines are Windows 10.

**Comment by fufesou** [comment]
> After a few seconds, I can't interact with the windows anymore, but sometimes I can still press the Windows Start Menu button and interact with the tray icons.

@felixsevero Hi, do you mean the Windows Start Menu can be pressed when other window lose interaction?

BTW, did you have RustDesk installed? For the portable version, foreground sysmtem window or foreground process that run as admin will stop the interaction.

**Comment by rustdesk** [comment]
UAC related, https://github.com/rustdesk/rustdesk/issues/3017, install please.

**Comment by felixsevero** [comment]
Just to let you know, when I tried with a VM the same thing happened, but when I installed it, as suggested by you, the problem was solved.

Thank you very much!

**Comment by jens-k** [comment]
I'm not sure this is the problem I have. I use an installed version of Rust. Please find a video attached.

https://user-images.githubusercontent.com/10050167/221256844-4df7307a-e35d-4978-83f7-2e8950bd6445.mp4

In the beginning the video is already playing but remains black in Rust. Then when I change applications, the playing video is updated. 
I then open several folders that are on the desktop. None of them is shown on the screen, but they appear in the Windows app preview (Alt-Tab). This latter part almost feels like there is another virtual screen on which the windows pop up but that is invisible to me via remote (which does not explain the freezing of windows, though, which I have experienced in several different applications).

**Comment by jens-k** [comment]
Maybe it helps to say that the majority of glitches I am experiencing occurs when the lid of the laptop to which I connect is closed (while "When I close the lid" is set to "Do nothing" in the Systems setting).

**Comment by jens-k** [comment]
Just to clarify, the computer to which I dial in is never locked.

**Comment by jens-k** [comment]
Is there any further information I can give? I don't think the issue should be closed. Please check the video I posted, this issue still occurs. Thanks!
@rustdesk

**Comment by fufesou** [comment]
@jens-k Hi, the video can't be played for me. Can you please re-upload the video?

**Comment by rustdesk** [comment]
Reopened，frankly, totally no clue.

**Comment by jens-k** [comment]
If there are problems playing the video, here is a dropbox link to it:
https://www.dropbox.com/s/m8fanytbx009zbg/rust%20issue%203266.mp4?dl=0

**Comment by rustdesk** [comment]
Upload video here please, dropbox sucks.

**Comment by rustdesk** [comment]
close to favor duplicate https://github.com/rustdesk/rustdesk/issues/4296
