### ISSUE TITLE
Installation under Windows 11 fails

### ISSUE THREAD

**Issue by JoBilert** [rustdesk/rustdesk#3270]
### Bug Description

I tried installing RustDesk on my Laptop (Windows 11) in the current release version and the current nightly.
But after clicking the install-button nothing seems to happen. 

No directories or shortcuts are created. 
I tried changing the directory, tired installing via chocolatey and winget, but never got any different results.

However the installation went smooth when I did it on my DesktopPC (Windows 11)

### How to Reproduce

Try installing Rundesk

### Expected Behavior

create directories and shortcuts

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.1.9 and 1.2 nightly

**Comment by JoBilert** [comment]
Could it be, that a faulty cmd.exe be the reason?

**Comment by rustdesk** [comment]
#3170

**Comment by rustdesk** [comment]
yes, cmd.exe used.

**Comment by JoBilert** [comment]
Hey I have to apologize. The problem had nothing to do with your software. 

The problem was, that somehow the cmd.exe was corrupted in my user. Generating a new windows-user solved the problem.
Maybe failures in the cmd.exe is something to be considered in future issues.

**Comment by JoBilert** [comment]
Hey, I have to apologize. The problem had nothing to do with your software.

The problem was, that somehow the cmd.exe was corrupted in my user. Generating a new windows-user solved the problem.
Maybe failures in the cmd.exe is something to be considered in future issues.
