### ISSUE TITLE
Auto reconnect when open or close VPN Connection or change Network Interface (WLAN<>LAN) without need of new accept

### ISSUE THREAD

**Issue by zillnerit** [rustdesk/rustdesk#3272]
### Description

When the IP of the Remote Side changes, a reconnect happens, but every reconnect need the password or the User on the Other side has to accept every Time again.

could a reconnect happen without need of new authentication or accept? 

### Impact

every Admin which has to do with VPN or chaning WLAN and LAN Connections

**Comment by DelcioSbeghen** [comment]
Why not change it? If the user who accepted access needs to leave and the connection drops, support is left without access, as there is no one on the other side to accept a connection that had already been authorized again. This happens a lot, and causes many tickets to go unfinished here for this reason. If you consider this a security risk, there could be a configuration that enables this automatic recovery functionality in case of loss of an already established connection, without having to accept it again.
