### ISSUE TITLE
[Feature] Switch phone screen orientation within the app

### ISSUE THREAD

**Issue by TenmaSennpai** [rustdesk/rustdesk#3273]
### Description

Add a button to rotate the screen (Android), press this button to change the orientation of the screen (landscape/portrait), it is best to put it in the menu at the same level as "chat", "input mode", etc for easy operation
Also, it would be nice to add a default screen orientation (Android phone screen) setting when connecting to a computer

### Impact

Users who need to rotate the screen do not need to change the screen orientation of the phone, so it will not affect other APPs

**Comment by rustdesk** [comment]
close to favor https://github.com/rustdesk/rustdesk/issues/576
