### ISSUE TITLE
The service starts automatically when Android boots

### ISSUE THREAD

**Issue by 1049731887** [rustdesk/rustdesk#3275]
### Description

Android automatically starts the service when booting, saving the trouble of opening the software startup service every time the computer is turned on (my phone screen is broken awa)

### Impact

Android users will benefit all

**Comment by rustdesk** [comment]
close as duplicate many times.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3322

**Comment by rustdesk** [comment]
Please try out it tomorrow, just added.
