### ISSUE TITLE
SHIFT select text and keyboard combination from ALT-GR

### ISSUE THREAD

**Issue by micceo** [rustdesk/rustdesk#3279]
### Bug Description

SHIFT select text not working.
ALT-GR (the combination key for SHIFT+ALT) keyboard combination not working (sv-se localization)

### How to Reproduce

Use the above functions.

Try to select text with SHIFT and arrow keys.
Try typing the character "\" from a sv-se localized keyboard.

### Expected Behavior

Working selection and keyboard combinations

### Operating system(s) on local side and remote side

Windows 11 to varios other windows versions.

### RustDesk Version(s) on local side and remote side

1.1.9 to 1.1.9

### Screenshots

No screen shot

### Additional Context

No comment

**Comment by rustdesk** [comment]
try out nightly build please on both side.

**Comment by micceo** [comment]
Yes, can confirm its working as it should in 'rustdesk-1.2.0-x86_64-pc-windows-msvc'. Sorry for not checking that out first.
Immensely fast response, thank you!
Haven't tried updating the destionation, but it's working with 1.2.0 -> 1.1.9

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
@ForsakenRei Thanks 
Nightly -> Nightly

I've tested "Legacy Mode".
1. SHIFT selecting works for me.
2. AltGr does not work fine. I thinks it's an unresolved issue.

BTW, please use "Map Mode". "Legacy Mode" is not maintained for now.
https://github.com/rustdesk/rustdesk/issues/2549#issuecomment-1365929440
https://github.com/rustdesk/rustdesk/issues/2549#issuecomment-1373119456

**Comment by ForsakenRei** [comment]
> @ForsakenRei Thanks Nightly -> Nightly
> 
> I've tested "Legacy Mode".
> 
> 1. SHIFT selecting works for me.
> 2. AltGr does not work fine. I thinks it's an unresolved issue.
> 
> BTW, please use "Map Mode". "Legacy Mode" is not maintained for now. [#2549 (comment)](https://github.com/rustdesk/rustdesk/issues/2549#issuecomment-1365929440) [#2549 (comment)](https://github.com/rustdesk/rustdesk/issues/2549#issuecomment-1373119456)

Hm, maybe something wrong on my end then. But it's good to know legacy mode is not the choice. Thanks.
