### ISSUE TITLE
Can not play the audio in deskrust on Ubuntu.

### ISSUE THREAD

**Issue by fy2462** [rustdesk/rustdesk#328]
**Describe the bug you encountered:**

I am running rustdesk on Ubuntu 20.04,  Ubuntu A-> Ubuntu B.  A is the controller. and paying the music on B, but can not receive the audio on A.

I look into the log and show that B already sends the audio message, but A can not play the audio data with ALSA. 

...

**What did you expect to happen instead?**

A can play the audio from B.

...

**How did you install `RustDesk`?**

cargo run

---

**RustDesk version and environment**

Linux 5.11.0-41-generic #45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/310
Yes, we do need a new solution to make Linux audio work easier.

**Comment by fy2462** [comment]
I think, maybe the opus encoder and decode don't work, I try to write the raw audio data with `wav` file as your test.
I can read the PCM raw data, and then can convert it with `wav`(PCM -> WAV) and play well.
But I hear nothing after covert it in the local Rustdesk client (PCM -> encode opus -> decode opus -> WAV), it seems all encoder and decoder parameters are set well.
So, is it the issue about OPUS encoder?

**Comment by open-trade** [comment]
no，seems more related to alsa input source.

**Comment by fy2462** [comment]
I can get the PCM input data from `get_pa_source_name` by name, and can also play the `ogg` file on the same PC, https://github.com/RustAudio/rodio/blob/master/examples/music_ogg.rs, which uses `cpal` yet.

So, I think the input and output device works well. but I can not get any sound after encoding and decoding ogg with `magnum_opus` to PCM stream, you can try to verify it on your side.

**Comment by rustdesk** [comment]
Really, can you help figure out?

**Comment by fy2462** [comment]
I am trying, but I can not fix the encode and decode issue, only make sure my input and output device working well.

**Comment by rustdesk** [comment]
Thanks
