### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by iamckun** [rustdesk/rustdesk#3285]
### Bug Description

Login cannot be used，not provided api server ,github err
![QQ截图20230220104700](https://user-images.githubusercontent.com/65990499/219997943-c8062099-842b-4d77-a5dd-b5e2d2005175.png)

### How to Reproduce

login

### Expected Behavior

Login in and get the ID in the account

### Operating system(s) on local side and remote side

docker->win,Android

### RustDesk Version(s) on local side and remote side

1.1.9->1.1.9,1.2

**Comment by rustdesk** [comment]
close as many duplicate.

**Comment by iamckun** [comment]
Unresolved
