### ISSUE TITLE
Device status is always offline when using public servers

### ISSUE THREAD

**Issue by rakleed** [rustdesk/rustdesk#3295]
### Bug Description

The device status is always offline when using public servers.

### How to Reproduce

1. Connect to the device through a public server.
2. Disconnect from the device.

### Expected Behavior

The device status is online.

### Operating system(s) on local side and remote side

macOS 13 → Windows 11

### RustDesk Version(s) on local side and remote side

1.2.0 nightly

### Screenshots

![Screenshot 2023-02-20 at 13 53 56](https://user-images.githubusercontent.com/19418601/220087658-9a9ef8c1-3fd4-40e2-b31f-829a141c630e.png)

### Additional Context

I saw similar issues #3213 and https://github.com/rustdesk/rustdesk/discussions/2786, but it was always about self-hosted server. Is the status not working for free public servers, or do public servers use older versions of [rustdesk-server](https://github.com/rustdesk/rustdesk-server)?

**Comment by rakleed** [comment]
@rustdesk does this only work for self-hosted servers? If so, can you add information about this to the documentation or to the application itself?

**Comment by rustdesk** [comment]
Will be finalized once it is release officially, this is nightly release, be patient.
