### ISSUE TITLE
Operation not permitted (OS error 1)

### ISSUE THREAD

**Issue by Aspillane789** [rustdesk/rustdesk#3297]
### Bug Description

It was working fine until about 2 hours ago

OS Error 1 

### How to Reproduce

Just launch rust desk from an iOS phone and try to connect to anyone. (Doesn’t work for Mac OS or windows.

### Expected Behavior

Error code 1 pops up

“ Operation not permitted (OS error 1)”

### Operating system(s) on local side and remote side

iOS 14.7.1 > Mac OS or windows

### RustDesk Version(s) on local side and remote side

1.1.9 > 1.1.9

### Additional Context

It happened out of nowhere. It was working fine for few weeks when I needed to work with clients from my phone. Then all the sudden I tried connecting to my clients and I had “error code1 OS”

I tried uninstalling, restarting my phone, and turning off my vpn to no avail.
_No response_

**Comment by rustdesk** [comment]
dupliate, close in favour of #152

**Comment by rustdesk** [comment]
I thought it is duplicate ipv6/nat64 issue. If you did not switch to ipv6/nat64, please reply in the issue, I will reopen. the issue, though I have no clue yet, but we will keep watch.

**Comment by Aspillane789** [comment]
tried turning off vpn. With any ID same thing happens


https://user-images.githubusercontent.com/125886218/221275420-60193f60-0640-4743-9f5d-bdf70eb2a52e.MP4

**Comment by rustdesk** [comment]
@Aspillane789 thanks

**Comment by z301012390** [comment]
I encountered a similar problem, I must open my vpn to use rustdesk 1.1.9 on ios.
