### ISSUE TITLE
Reverse a connection

### ISSUE THREAD

**Issue by bilogic** [rustdesk/rustdesk#3299]
### Description

While 2 parties are connected A and B, and A is looking at B's desktop. Can their roles be reversed with an option?
i.e. B now looking at A's desktop instead.

I'm trying to troubleshoot why A can connect to B for a long time, but if B connects to A, the connection is terminated within 30 seconds like https://github.com/rustdesk/rustdesk/issues/106 `The remote host forcibly closed an existing connection (erro 10054)（erro 10054）` 

### Impact

In a discussion, sometimes this is required to make sharing easier and less disruptive

It might also help with https://github.com/rustdesk/rustdesk/issues/1113

**Comment by rustdesk** [comment]
in nightly build.

**Comment by rustdesk** [comment]
#3088

**Comment by bilogic** [comment]
thanks!
