### ISSUE TITLE
Appimage version?

### ISSUE THREAD

**Issue by mlunax** [rustdesk/rustdesk#33]
I would like to see the AppImage version for your product.

**Comment by Tea-Wrex710** [comment]
K

**Comment by rustdesk** [comment]
https://github.com/sponsors/rustdesk/sponsorships?sponsor=rustdesk&tier_id=74919&preview=false

**Comment by rustdesk** [comment]
Sorry, I misunderstood AppImage before.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/577
