### ISSUE TITLE
fork nightly build not working on MACos

### ISSUE THREAD

**Issue by swoop124** [rustdesk/rustdesk#3301]
### Bug Description

Hello,

First of all, this prject is amazing.
But i am no Programmer. ;-)

I have successfully built my own version of the binarys, using this tutorial:
https://rustdesk.com/docs/en/dev/build/all/
only to have a build with my own Rendezvous-Server and Key.

The windows version is working great. But the MAC version is not working at all. Linux i haven't testet jet.
When i open the DMG-File the Icon of  RustDesk.app is showing up but nothing else. Shouldn't there be an Application-Folder? In the official MAC build, there is the Application-Folder present.
And i saw that the official nightly build is 21,3MB in size my build is 23,4MB in size.

how can i get macos version running?

### How to Reproduce

When i double-klick the RustDesk.app, Macos is saying that it cannot look for Malware. Even when i klick open, the App is not starting. 
So i right-click on the app then i klick on open. Usually that does the trick, but not this one. 
After i klick open nothing happens.

i found a logfile on my mac. please see attached 
[App-Crash 2023-2-20 16-23.log](https://github.com/rustdesk/rustdesk/files/10785740/App-Crash.2023-2-20.16-23.log)

now that i scaned through the log file, i see that there is apparently a library missing.

### Expected Behavior

Thr app should open as it should

### Operating system(s) on local side and remote side

osx 

### RustDesk Version(s) on local side and remote side

Nightly

**Comment by rustdesk** [comment]
#763

**Comment by kitzler-walli** [comment]
This doesn't seem to be a build issue - the app builds just fine but it is simply not executable on macOS (arm64)

**Comment by swoop124** [comment]
> This doesn't seem to be a build issue - the app builds just fine but it is simply not executable on macOS (arm64)

Hello kitzler-walli,

yes, this is correct. As i mentioned, i saw in the provided log file, there are missing librarys. 
So wich library i didn't found out.

**Comment by kitzler-walli** [comment]
@swoop124 My comment was meant for @rustdesk as they seem to simply close the case referring to build issues - but this isn't a build issue and it happens with a simple fork - no changes and following their tutorial. 
I couldn't find anything in the docs or the faq that matches this problem.
So thank you @swoop124 for creating this issue - hopefully they will look into it.
