### ISSUE TITLE
The number will be misplaced when entering the remote ID

### ISSUE THREAD

**Issue by TwoDogs2** [rustdesk/rustdesk#3305]
### Bug Description

The number will be misplaced when entering the remote ID

### How to Reproduce

Just enter the remote ID and it will reappear

### Expected Behavior

Just enter the remote ID and it will reappear

### Operating system(s) on local side and remote side

Windows 10 -> Windows server2016

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

**Comment by rustdesk** [comment]
Too vague

**Comment by rustdesk** [comment]
Video please, it will help us understand you.

**Comment by TwoDogs2** [comment]
How can I send you video

**Comment by rustdesk** [comment]
Drag here.

**Comment by TwoDogs2** [comment]
https://user-images.githubusercontent.com/121689365/220242318-bea35a43-d633-4ec1-b30c-31ff9420b621.mp4

**Comment by TwoDogs2** [comment]
https://user-images.githubusercontent.com/121689365/220242681-62fcb6c8-eb08-4735-8f40-683796181522.mp4

**Comment by rustdesk** [comment]
What gave your confidence about your english? haha, :)

**Comment by rustdesk** [comment]
Fixed in nightly build.

**Comment by TwoDogs2** [comment]
> What gave your confidence about your english? haha, :)

梁静茹给的

**Comment by TwoDogs2** [comment]
> 

Okay, please tell me

**Comment by rustdesk** [comment]
It is wierd, my 1.1.9 does not have this problem. Anyway, I believe you won't have this issue in nightly build which use totally different implementation.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/tag/nightly

**Comment by rustdesk** [comment]
> 梁静茹

She gave courage only, not confidence.

**Comment by TwoDogs2** [comment]
> > > What gave your confidence about your english? haha, :)
> 
> > 梁静茹给的
> 
> She gave courage only, not confidence.

Only with courage can we have confidence

**Comment by TwoDogs2** [comment]
Can I configure ID refresh

**Comment by rustdesk** [comment]
no

**Comment by TwoDogs2** [comment]
> https://github.com/rustdesk/rustdesk/releases/tag/nightly

This version has been solved in Windows server 2012. The problem still exists in Windows server 2016

**Comment by rustdesk** [comment]
> Windows server 2016

Video?

**Comment by SamGenTLEManKaka** [comment]
> > Windows server 2016
> 
> Video?

https://github.com/rustdesk/rustdesk/assets/24671601/44f4e68c-465b-40da-a8a8-9e3e45def027

**Comment by SamGenTLEManKaka** [comment]
> > > 视窗服务器 2016
> > 
> > 
> > 视频？
> 
>  20230531-144623.mp4

@rustdesk
