### ISSUE TITLE
Arm64 Native Builds For Windows

### ISSUE THREAD

**Issue by huangyinhaow** [rustdesk/rustdesk#3308]
### Description

I am currently using a Windows PC with a Qualcomm Snapdragon processor.
I would like to be able to get a native build for arm64 in the release.
Thanks!

### Impact

It is friendly to users with Arm processors, and this group of users is also more likely to use remote desktop applications.

**Comment by rustdesk** [comment]
PR please, or if you wanna donate us a Arm64 PC.

**Comment by huangyinhaow** [comment]
Great.

**Comment by docgalaxyblock** [comment]
@rustdesk would be a Raspberry Pi 4 *(I guess the team owns at least one?)* and https://worproject.com/ be an option?

I personally have no rust or msvc experience but I will give a compile try a shot.
