### ISSUE TITLE
Combination all keys with Win

### ISSUE THREAD

**Issue by fufesou** [rustdesk/rustdesk#332]
Reported from wechat

All keys are combined with Win after connecting for a while.

L works like Win+L, screen lock.
h works like Win+h, hide window.

environment: Linux both side.

Win is the shortcut that often pressed on the controlling side.
Press Win may produce this problem.

Reconnection do not clear the status.

Clearing keys like "Win" "Ctrl" may help when connecting is established.

**Comment by rustdesk** [comment]
The user uses autokey on local side.

![image](https://user-images.githubusercontent.com/71636191/147181223-ed2891ac-ba6a-437f-a442-98592253e3b5.png)

right key is binded to win + /,
if binded to ctrl + /, can also trigger the bug.
