### ISSUE TITLE
impossible to copy / paste a file form / to Windows 10/10 & RustDesk nightly release

### ISSUE THREAD

**Issue by mikekgr** [rustdesk/rustdesk#3324]
### Bug Description

Dear Sirs,
it is impossible to copy a file and then to paste it form Windows 10 to Windows 11 PC that both running the today nightly & RustDesk release. I don't know if the reported problem is also in the previous releases though.
If I try it at the target Computer the Paste is gray (deactivated) also I can not drag it and drop the file.
P.S. I am running local 1.1.7 server NOT the Public cloud.
Please note that the "Allow file copy and paste" is checked / activated,

### How to Reproduce

Just check from your side

### Expected Behavior

To be able to copy paste the file provided that the "Allow file copy and paste" is checked / activated, as it is in my case

### Operating system(s) on local side and remote side

Windows 10 => Windows 11

### RustDesk Version(s) on local side and remote side

1.2.0 Nightly release 2023-02-22 00:36

### Screenshots

Not available but if you need tell me to provide

**Comment by rustdesk** [comment]
close to favor #2283

**Comment by chmis8000** [comment]
It's not ok!no! I just downloaded and tried the new version.

**Comment by chmis8000** [comment]
It's not ok!no! I just downloaded and tried the new version.

**Comment by chmis8000** [comment]
You need to close the copy permission first, then open it, and then Copy, Parse is normal

**Comment by chmis8000** [comment]
In addition, the handle of the original file is not closed, if the original file is to be overwritten
