### ISSUE TITLE
full screen: mouse move doesn't reach the bottom pixels

### ISSUE THREAD

**Issue by avih** [rustdesk/rustdesk#3327]
### Bug Description

When in full screen and the remote has the task bar on auto-hide so that it shows only when the mouse is moved to the bottom - it's impossible to show the task bar by moving the mouse to the very bottom.

### How to Reproduce

Connect to a windows system (tested windows 10 to windows 7), where the remote has the taskbar at the bottom and on auto-hide, so that the mouse needs to move to the bottom to make the taskbar show up.

### Expected Behavior

In full screen, moving the mouse to the bottom should make the remote taskbar show up, but in practice the remote taskbar does not show up.

### Operating system(s) on local side and remote side

windows 10 -> windows 7

### RustDesk Version(s) on local side and remote side

On both systems: current latest 1.20 nightly (Build Date: 2023-02-21 00:33)

### Screenshots

N/A.

### Additional Context

Interestingly, when not in full screen, then it's very easy to move the mouse to the bottom edge of the window so that the remote taskbar shows up.

Interestingly No. 2, when in full screen, and dragging the mouse to the bottom, e.g. by making a rectangular selection at the desktop which reaches the bottom, then it looks like the selection does reach the very bottom, and when releasing the mouse the taskbar does show up.

So it seems that the issue only happens on mouse move without any mouse buttons held down.

If mouse buttons are held down, then the problem goes away.

**Comment by rustdesk** [comment]
close to favor https://github.com/rustdesk/rustdesk/issues/2883
