### ISSUE TITLE
Can't change path for recordings on macOS

### ISSUE THREAD

**Issue by rakleed** [rustdesk/rustdesk#3332]
### Bug Description

It is impossible to change the path for recordings in the macOS application.

### How to Reproduce

1. Open RustDesk settings
2. Go to `General`
3. On the `Recording` section, click `Change`

### Expected Behavior

A Finder window will appear with the option to select a new path.

### Operating system(s) on local side and remote side

macOS 13 → Windows 11

### RustDesk Version(s) on local side and remote side

1.2.0 nightly

### Screenshots

![image](https://user-images.githubusercontent.com/19418601/220759142-f2474a54-3239-4b55-a07b-5c6f9fcc0656.png)

### Additional Context

On Windows it works fine.

**Comment by rustdesk** [comment]
close as fix merged
