### ISSUE TITLE
[Feature Request]Show multiple monitors on menu bar at the same time.

### ISSUE THREAD

**Issue by ForsakenRei** [rustdesk/rustdesk#3333]
### Description

Currently if connected to a remote with multiple monitors, the workflow for switch monitors will be:
1. Click show menu bar button
2. Click select monitor button
3. Click the monitor you want to switch to
4. Once switched to another monitor, the select monitor menu will disappear
Even if you just want to take a look and switch back to the monitor you are looking at, you need one more click to bring up the the menu. And if you need swtich between different monitors frequently it added a lot of clicks. 

### Impact

If we can have multiple monitors all show up on the menu bar(or somewhere else?) at the same time without using multi level menus, it should give us a simplified workflow for a remote with more than one monitors.

### Additional Context

I like the idea Rustdesk only use 1 row for the title bar and connection banner to give user more real estate, and I'm not sure about the complexity of this feature since the menu bar need to change it width dynamicly depends on how many monitors the remote is connected to. After all it's not something I cannot live without but I think it's good to have especially for users like me who connected to a multi screen remote most of the times.

While the multiple connections to multiple remote montiors is on the road map, this feature will probably still benefit those only have a single monitor at host side. 

And not really related, but want to see if anyone is interested in the edge scrolling(avaliable in Anydesk) idea here
https://github.com/rustdesk/rustdesk/discussions/3053

P.S It seems the new feature request issue template didn't add [Feature Request] automatically to the title?

**Comment by rustdesk** [comment]
1.1.9 has this, but our team member remove this in 1.2.0, i was angry when i saw. But you know leading a team is not simple especially when you do not have enough finance support.

**Comment by rustdesk** [comment]
> add [Feature Request] automatically

i added before, but many people let title blank with only feature request, so i remove it. Many things you can not expect before you do it.

**Comment by ForsakenRei** [comment]
> > add [Feature Request] automatically
> 
> i added before, but many people let title blank with only `feature request`, so i remove it. Many things you can not know before you do it.

That's kinda sad but I felt the frustration.

Back to the feature request, I know we have it in 1.1.9 but it's gone in 1.2.0, to accomdate the new UI design. That's why I want it back, but I understand changes might not always be good for everyone. The two feature requests I brought up are both nice to have but not really something we cannot live with. I'm willing to help but unfortunately all my coding experience is in Python about Data Science. So things I can do now are only reporting bug and help test. 
If I want to actually help UI(or potentially other) dev, the first thing I should look at is Flutter/Dart and then Rust itself, right?

**Comment by rustdesk** [comment]
> help UI(or potentially other) dev

Yes, only dart.

**Comment by rustdesk** [comment]
> my coding experience is in Python about Data Science

That's enough.

**Comment by rustdesk** [comment]
Let me know, if you need any help.

**Comment by ForsakenRei** [comment]
> Let me know, if you need any help.

I will. Looking at the examples and it seems not that hard to start but I will definitely come back for questions after I got familiar with flutter.

**Comment by rustdesk** [comment]
This pr https://github.com/rustdesk/rustdesk/pull/3207 is a good example, very good job from our contributor @NicKoehler.

**Comment by ForsakenRei** [comment]
> This pr #3207 is a good example, very good job from our contributor @NicKoehler.

Thank you. I might need sometime to be there but I have a starting point now.

**Comment by ForsakenRei** [comment]
@rustdesk Went through some flutter basics and now have some (simple) questions if you don't mind I ask.

With a glance, code related to what I want to achiveve is L520 to L587, if I'm not missing anything?
https://github.com/rustdesk/rustdesk/blob/17f1c18c9239eee7067b3af221eabde781d77b3a/flutter/lib/desktop/widgets/remote_menubar.dart#L520

And I assume I can just use the `rustdesk/flutter` folder to build the app(Win + VSCode) to see what I changed, but I got a lot of not resolved packages in `main.dart`.
![image](https://user-images.githubusercontent.com/23041178/221443050-40b65996-c362-4fb5-a66d-40e5dd78bca6.png)
So I guess I need some additional setup in addition to the basic setup?

**Comment by rustdesk** [comment]
you need to go through all steps in the nightly ci.

**Comment by ForsakenRei** [comment]
> you need to go through all steps in the nightly ci.
https://github.com/rustdesk/rustdesk/actions/runs/4277632555/jobs/7446591816
Steps here?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/blob/master/.github/workflows/flutter-nightly.yml

**Comment by ForsakenRei** [comment]
> https://github.com/rustdesk/rustdesk/blob/master/.github/workflows/flutter-nightly.yml

Got it. I will go through the steps first, thanks.

**Comment by bilago** [comment]
I vote for this feature to be implemented. I do a lot of monitor switching

**Comment by rustdesk** [comment]
@NicKoehler do you have interest to do this? below is that we have in 1.1.9
https://github.com/rustdesk/rustdesk/blob/08f9b3760f643de642fd3b81df4cb7e3092185fe/src/ui/header.tis#L223
no idea how to make it look good in new menubar. it is better have a display option (display subpage on setting page) to turn on if showing multiple monitors on menubar, turn on by default.
![](https://user-images.githubusercontent.com/71636191/113112619-f705a480-923b-11eb-911d-97e984ef52b6.png)

**Comment by NicKoehler** [comment]
It seems like is duable, I'll take a look

**Comment by rustdesk** [comment]
👍

**Comment by rustdesk** [comment]
I still hope recovering old design.

**Comment by rustdesk** [comment]
Does this https://github.com/rustdesk/rustdesk/pull/3207#issuecomment-1463941861 satisfy your need?

**Comment by rustdesk** [comment]
> I still hope recovering old design. because it was cool when you have more than 3 displays and can see exactly where is the display.

Then we can wrap this in https://api.flutter.dev/flutter/material/Tooltip-class.html or handle hover ourself without breaking current menubar style.

**Comment by ForsakenRei** [comment]
> What about spawning a button for every monitor if there are more than one?
> 
> ![image](https://user-images.githubusercontent.com/53040044/224026744-fd9648c3-de84-417d-9dc4-7fae2d43dd62.png)

Thanks and I think that's what I want. Quite busy with my job so didn't really have time on this side recently...
I will give new nightly build a try later I got back home.


> > I still hope recovering old design. because it was cool when you have more than 3 displays and can see exactly where is the display.
> 
> Then we can wrap this in https://api.flutter.dev/flutter/material/Tooltip-class.html or handle hover ourself, without breaking current menubar style.
I agree it's really cool to let you know the orientation of the monitors, though how to show them properly makes me scratch my head. We probably don't want a lot of layers of menu, maybe just spwan the buttons based on their orientation instead of the real location. For example, I have 3 monitors 1, 2 and 3 where 1 is the main one, 2 is on the right of 1 and 3 is a vertical one on the left of 1. Instead of showing button 1, 2 and 3, how about we show button 3, 1 and 2 instead just based on their left to right order without the exact location like https://github.com/rustdesk/rustdesk/pull/3207#issuecomment-1463969629 (and ignore screen orientation as well).

**Comment by NicKoehler** [comment]
Should we conduct a poll before proceeding with the implementation?

**Comment by bilago** [comment]
To me, this feels like two different asks that could possibly be split into two different work items.

1. Display all monitors on the tool bar in numerical order
2. Implement a visualization of where monitors are in relative to the primary monitor

If that is something we could agree on, would it make sense to move forward with task 1, and then have further discussion on task 2, instead of holding up both tasks until task 2 has a resolution?

**Comment by ForsakenRei** [comment]
Personally, 1. is enough for me as long as I see all monitors as an option there to click, I can remember which is which anyway.

**Comment by bilago** [comment]
1 is enough for me as well. I could see it being useful knowing the positions when you're remoting into a computer you're not familiar with, but for my use-case it wouldn't be too beneficial.

**Comment by rustdesk** [comment]
> Should we conduct a poll before proceeding with the implementation?

Yes

**Comment by NicKoehler** [comment]
> To me, this feels like two different asks that could possibly be split into two different work items.
> 
>     1. Display all monitors on the tool bar in numerical order
> 
>     2. Implement a visualization of where monitors are in relative to the primary monitor
> 
> 
> If that is something we could agree on, would it make sense to move forward with task 1, and then have further discussion on task 2, instead of holding up both tasks until task 2 has a resolution?

this make more sense to me I'll move forward with task 1

**Comment by rustdesk** [comment]
Something like this? or make it more concise, replace display icon with simple rectangles. 

(2) can be shown as tooltip in task 2.

![image](https://user-images.githubusercontent.com/71636191/225244264-a753727a-8d70-47fc-bc13-0e334bbec61d.png)

**Comment by rustdesk** [comment]
Or use hover.

**Comment by NicKoehler** [comment]
Do you guys like this for task 1?

![image](https://user-images.githubusercontent.com/53040044/225248699-049b2f3a-36ea-4107-beed-d0af3e9e1dba.png)

**Comment by rustdesk** [comment]
@grummbeer

**Comment by grummbeer** [comment]
> Do you guys like this for task 1?

Blue is the current monitor, gray the others? 

LGTM. Clear and direct visible, no extra click to switch the monitor.

Task "3" is a tab/window for each monitor?

**Comment by rustdesk** [comment]
> Task "3" is a tab/window for each monitor?

Won't see it in 1.2.0, this is a big task.

**Comment by grummbeer** [comment]
> Frankly, I can not imagine if there are 6 displays.

:-) same, but there are four on the screenshot, two more ... not sure what a trader thinks about it. All monitors at a click or "wait" (time is money) until some kind of animation is completed before being able to change the monitor.

**Comment by rustdesk** [comment]
> configurable

Yes, I prefer it is configurable in `display` settings page, by default, not shown on menu bar.

**Comment by rustdesk** [comment]
Close as fix merged.
