### ISSUE TITLE
MacOS pasting with cmd+v is send to remote desk even when rustdesk window is not in focus

### ISSUE THREAD

**Issue by mhbacks** [rustdesk/rustdesk#3337]
### Bug Description

when pasting some text e.g in firefox, the clipboard will also be pasted in the rustdesk on remote desk

### How to Reproduce

1. open a connection to other desktop with rustdesk (in my case a windows desktop)
2. open on remote side a texteditor and set it as active application
3. open on local side a texteditor
4. mark a text on local side and put it to clipboard (cmd-c)
5. paste a text in texteditor on local side (cmd-v)
6. the text pasted in local texteditor is also in remote texteditor

### Expected Behavior

at point 6: the texteditor on remote side must be empty

### Operating system(s) on local side and remote side

osx -> Win10

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

for that detail hopefully not needed. please ask

**Comment by rustdesk** [comment]
try out nightly build.
