### ISSUE TITLE
Abnormal Chinese font display during remote desktop control

### ISSUE THREAD

**Issue by youhers** [rustdesk/rustdesk#3348]
### Bug Description

When I control part of the PC, the Chinese character display is very thin and the font display is not clear. Please refer to the figure below. It is strange that not all computer fonts have problems, but some are normal. I wonder if you can reproduce this problem

在我控制部分的pc时中文汉字显示很细，字体显示不清楚，请参照下图，很奇怪，并不是所有的电脑字体有问题，又有一部份却又是正常的，不知道您是否可以复现此问题

### How to Reproduce

Please pay attention to the recurrence of this problem. Not all PCs can reproduce this problem. I have five servers and two have this problem. The other three have no such problem

请您留意此问题的复现，并不是所有的pc都能复现此问题，我这里有5台服务器，有两台出现了这个问题。另外三台则没有这个问题

### Expected Behavior

The font should be displayed normally, not clearly

字体应该正常显示，而不是显示的看不清楚

### Operating system(s) on local side and remote side

win10 - win server2008r2

### RustDesk Version(s) on local side and remote side

1.2.0 - 1.2.0

### Screenshots

![企业微信截图_20230224112508](https://user-images.githubusercontent.com/106003909/221084592-de652f60-0911-4277-825b-49bc91f826a9.png)
![企业微信截图_20230224111422](https://user-images.githubusercontent.com/106003909/221084603-72f7b76e-626c-445a-ae2d-349518d84060.png)

**Comment by rustdesk** [comment]
common picture quality issue.

**Comment by rustdesk** [comment]
#2915

**Comment by youhers** [comment]
thank you
