### ISSUE TITLE
Add dedicated request elevation button in rustdesk

### ISSUE THREAD

**Issue by radiandedy** [rustdesk/rustdesk#3349]
### Description

Currently if we need to request elevation to other user we need open application that have administrator and then select elevation.
 
in this case the application uac will appear and if we click no rustdesk uac will appear, this will make users have to click no to application administrator uac and then click yes on rustdesk elevation uac.

using dedicated elevation button like anydesk make user only click ok on rustdesk uac and dont need to open other applications

![image](https://user-images.githubusercontent.com/40633520/221086142-4ea41132-6d54-43bf-9b3c-3aded79b11ba.png)

### Impact

Using dedicated elevation button will make elevation remote user fast and other user that we remote dont need to open application in administrator.

**Comment by rustdesk** [comment]
@21pages add this

**Comment by rustdesk** [comment]
test tommorow please
