### ISSUE TITLE
System Sound audio input device for macOS

### ISSUE THREAD

**Issue by rakleed** [rustdesk/rustdesk#3366]
### Description

You have this option in the Windows version, I would like to see it in the macOS app so when I reconnect the microphone to device, I do not have to separately configure it in RustDesk every time.

### Impact

When I reconnect the microphone to the device, I do not have to separately configure it in RustDesk every time.

### Additional Context

Screenshot of RustDesk for Windows:

![image](https://user-images.githubusercontent.com/19418601/221287943-3fa9b5d0-c860-44e8-995b-538284452411.png)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3134#issuecomment-1424068714
