### ISSUE TITLE
Make the offline status icon red

### ISSUE THREAD

**Issue by rakleed** [rustdesk/rustdesk#3367]
### Description

Make the offline status icon red to make it easier to see if the device is offline.

### Impact

Since for me yellow is something between green and red, and it’s not immediately clear that this means offline. AnyDesk uses red for offline status.

### Additional Context

![Screenshot 2023-02-24 at 23 51 03](https://user-images.githubusercontent.com/19418601/221289090-b4f7496f-1b48-4152-b36c-2eafbd444596.png)

**Comment by rakleed** [comment]
@rustdesk why is the request invalid?

@grummbeer what do you think?

**Comment by grummbeer** [comment]
rustdesk is the chief :) 

But since you ask me, I think red is the opposite of green, but I don't know what the reasons are for yellow.
