### ISSUE TITLE
Remote audio never works on any client regardless of operating system

### ISSUE THREAD

**Issue by breathless19** [rustdesk/rustdesk#3368]
### Bug Description

Remote audio never works correctly regardless of the operating system I am connecting to.   Windows to Mac, Mac to Windows, Android to Mac, Android to Windows, etc.    

Any audio (system sounds or otherwise) never are audible on the "connecting" side.    

The only hint of audio that I occasionally get is a loud buzzing noise that sort of associates with the remote audio.    So, for instance if I connect to a Windows 11 machine from a Windows 11 machine and click on the sound icon in the lower right hand corner, and move the slider or click on the slider, an audio noise should be heard.   What I hear instead is either nothing at all, or a buzzing noise in place of the appropriate noise.  

### How to Reproduce

My configuration is very standard. 

Rustdesk Server installed on Windows 11

Rustdesk client installed on various machines in my house, all working appropriately.    Mac... Windows...

Connect from any machine to any machine results in no remote audio being heard. 

I have the latest nightly of RustDesk installed and the latest version of the server.  

### Expected Behavior

I would expect to hear remote audio the same as I would with Anydesk / Teamviewer

### Operating system(s) on local side and remote side

Windows 11 - > Mac :    Mac - > Windows

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

.

**Comment by rustdesk** [comment]
close to favor https://github.com/rustdesk/rustdesk/issues/1189
