### ISSUE TITLE
Operations does not work on the locks screen (macOS -> Windows)

### ISSUE THREAD

**Issue by wakewon** [rustdesk/rustdesk#3371]
### Bug Description

When connected to a locked Windows device via macOS , it won't response to any mouse clicking or keyboard inputting.

### How to Reproduce

0. Connect to the remote side (Windows) and lock it (auto lock, or manual lock).
1. Disconnect.
2. Connect to the remote device (from macOS).
3. Drag the mouse/keyboard input unavailable. Auto unlock is also unavailable.

Mouse movement is visible on the local side, but I can't confirm whether it is visible on the remote side since **the remote device doesn't connect to a physical screen**. When the remote is connected via RDP service, RustDesk auto-login works well (and makes the RDP connection stopped).

It should also be noticed that when the local side becomes an iPadOS client (1.1.9), this issue disappeared (auto login also works well). So I think it's a bug of the macOS client.

### Expected Behavior

Drag mouse / any input -> come to the password input screen.

### Operating system(s) on local side and remote side

macOS 13.2.1 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0 Build Date: 2023-02-25 00:17 -> 1.2.0 Build Date: 2023-02-25 00:40

### Screenshots

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/40191996/221340035-d9283688-cca4-4b74-91aa-679a9a389d2c.png">

### Additional Context

The "Send Ctrl+Alt+Del" function can be used to override this issue. After triggering C+A+D from the menu, the remote side will come into the password input screen, and all control is responsible.

**Comment by rustdesk** [comment]
[#uac](https://github.com/rustdesk/rustdesk/issues/3266)

**Comment by rustdesk** [comment]
mac 1.1.9?

**Comment by wakewon** [comment]
> mac 1.1.9?

Nope. Latest nightly (1.2.0 Build Date: 2023-02-25 00:17).

(iPadOS client is 1.1.9, which didn't meet this issue)

**Comment by rustdesk** [comment]
Please try out mac 1.1.9, if it works?

**Comment by wakewon** [comment]
> Please try out mac 1.1.9, if it works?

Works well. Both manual and auto login.

**Comment by rustdesk** [comment]
@fufesou

**Comment by wakewon** [comment]
Well... It seems this problem disappeared now.

When I upgrade RustDesk from 1.1.9, it has a notice about adding input monitoring permission (I have no idea whether it has happened before since previous upgrades/downgrades never show me this notice):
https://github.com/rustdesk/rustdesk/issues/974#issuecomment-1185644923

It might be a permission glitch. but it's pretty weird that the input is only non-response before login (but not continue non-response after C+A+D).

p.s.
Upgrades from or downgrades to 1.1.9 is a terrible experience since each permission has to be manually removed and added again.
