### ISSUE TITLE
keyboard is wrong on latest nightly

### ISSUE THREAD

**Issue by test2a** [rustdesk/rustdesk#3373]
### Bug Description

for the last 3 days' nightlies i am facing wrong keyboard on remote side. I have attached screen recording from rustdesk itself which shows me attempting to type qwerty but it comes out wrong.

again, this was working properly 3-4 days ago but last 2 days it was intermittent but today i updated and it is wrong keyboard 100% of the time

### How to Reproduce

i don't know, just type

### Expected Behavior

correct keys should be transmitted

### Operating system(s) on local side and remote side

linux>windows

### RustDesk Version(s) on local side and remote side

1.20>1.1.8

### Screenshots

[c421231539_20230225114034.webm](https://user-images.githubusercontent.com/39449563/221341795-5fa3dd56-120e-4367-94ec-61de05e932dd.webm)

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
@test2a Hi, thanks for your feedback.
I've tested 1.2.0(Linux) -> 1.1.8(Win), but failed to reproduce this issue.

Which input method do you use on local Linux PC ?

BTW, RustDesk before the ngihtly build support only the "Legacy Mode", which has some wrong characters in non-US input method. The ngihtly build has introduced "Map Mode", a much better way for keyboard input.

![1677324304187](https://user-images.githubusercontent.com/13586388/221354329-d30de3ef-8942-4325-8988-5678b0bb9483.png)

**Comment by test2a** [comment]
![Screenshot_20230225_171942](https://user-images.githubusercontent.com/39449563/221355278-585ab7fd-8593-4650-99a7-1fd9dee2b8bc.png)


i use
````
 sudo apt-get remove rustdesk

````
 and then 
````
 sudo dpkg -i rustdesk-1.2.0-x86_64-unknown-linux-gnu-ubuntu-18.04.deb 

````

every morning on my local side. remote side is unchanged.

i don't have the keyboard icon, it did till some weeks ago but was gone recently.

the keyboard is "right now" working properly but sometimes it goes beserk. 

keyboard layout on remote side is "eng-us"

![Screenshot_20230225_172250](https://user-images.githubusercontent.com/39449563/221355406-53121eee-4081-45f1-8434-ebdcbe90c3b0.png)

**Comment by fufesou** [comment]
It seems you're using wayland.

I modified the input logic a few days ago.
If local side is wayland or macOS (does not support input monitor), the input mode is set to "Map Mode".
However the "Map Mode" is not supported by 1.1.9 and below versions.

Now it seems that this approach is still a bit sloppy. I will revise it later.

But I think it's better to upgrade the version. "Map Mode" is much better.
https://github.com/rustdesk/rustdesk/issues/2549#issuecomment-1365929440
https://github.com/rustdesk/rustdesk/issues/2549#issuecomment-1373119456

**Comment by test2a** [comment]
@fufesou you mean upgrade on remote side to nightly?

**Comment by fufesou** [comment]
> @fufesou you mean upgrade on remote side to nightly?

Yes. Though I'll try to fix this issue for compatibility.

**Comment by rustdesk** [comment]
> local side is wayland

only for wayland without uinput case, e.g. run in flatpak, appimage, or the other case uinput service not work

**Comment by fufesou** [comment]
@test2a Hi, I've fix this issue. And set "Legacy Mode" back if the remote side does not support "Map Mode".

https://github.com/rustdesk/rustdesk/pull/3375

**Comment by jjolmo** [comment]
> Hi, this is still an issue for me local linux 1.2.4 nightly, remote 1.2.3 Windows can someone confirm?

Same for me in latest Linux.
I've tested the three different input modes and all of them are not honoring my keyboard layout

**Comment by fufesou** [comment]
@mv-si @jjolmo Hi, what keyboard layout do you use on both sides?

I've tested Ubuntu(x11) -> Win, it works fine for me.

**Comment by jjolmo** [comment]
> @mv-si @jjolmo Hi, what keyboard layout do you use on both sides?
> 
> I've tested Ubuntu(x11) -> Win, it works fine for me.

Spanish in both ends. keys do American layout. I will doublecheck it is also in all users and not only the active user, I'm using "Spanish" on all ends

**Comment by fufesou** [comment]
<img width="723" alt="1714826723120" src="https://github.com/rustdesk/rustdesk/assets/13586388/637399ec-2929-4ba7-826e-695fb40160f2">

Are there two layouts for "Spanish"?

I've tested Ubuntu -> Ubuntu.

The keys use the layout on Windows.
The snapshot of layout on Ubuntu does not work, event I type directly using my keyboard.

**Comment by jjolmo** [comment]
> <img alt="1714826723120" width="723" src="https://private-user-images.githubusercontent.com/13586388/327948790-637399ec-2929-4ba7-826e-695fb40160f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NTIxMzcsIm5iZiI6MTcxNDg1MTgzNywicGF0aCI6Ii8xMzU4NjM4OC8zMjc5NDg3OTAtNjM3Mzk5ZWMtMjkyOS00YmE3LTgyNmUtNjk1ZmI0MDE2MGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDE5NDM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NjZmN2YxMzY1ZTAyYmNjZjU5MmQ4YTgxNmM4YjIwYTk0MzU3ZDcxMDc1MTQ1NmZiYWFmZDU3ZTIyNTk1ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jbFgTAjLUpGpLotX2lP8VsoABXJDpGAysKSbGfuKb9c">
> Are there two layouts for "Spanish"?
> 
> I've tested Ubuntu -> Ubuntu. The keys use the layout on Windows.
> 
> The snapshot of layout on Ubuntu does not work, event I type directly using my keyboard.

I'm sorry, my fault. I was not running the latest .deb package in the release tag list. With this version it works when you set the keyboard to "Translate mode".

@mv-si please, check it with this version https://github.com/rustdesk/rustdesk/releases/tag/1.2.3-2

**Comment by mv-si** [comment]
> @mv-si @jjolmo Hi, what keyboard layout do you use on both sides?
> 
> I've tested Ubuntu(x11) -> Win, it works fine for me.

Hi, I use fr-fr for both my Linux & Windows
Server is the docker version. 



> > <img alt="1714826723120" width="723" src="https://private-user-images.githubusercontent.com/13586388/327948790-637399ec-2929-4ba7-826e-695fb40160f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NTIxMzcsIm5iZiI6MTcxNDg1MTgzNywicGF0aCI6Ii8xMzU4NjM4OC8zMjc5NDg3OTAtNjM3Mzk5ZWMtMjkyOS00YmE3LTgyNmUtNjk1ZmI0MDE2MGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDE5NDM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NjZmN2YxMzY1ZTAyYmNjZjU5MmQ4YTgxNmM4YjIwYTk0MzU3ZDcxMDc1MTQ1NmZiYWFmZDU3ZTIyNTk1ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jbFgTAjLUpGpLotX2lP8VsoABXJDpGAysKSbGfuKb9c">
> > Are there two layouts for "Spanish"?
> > I've tested Ubuntu -> Ubuntu. The keys use the layout on Windows.
> > The snapshot of layout on Ubuntu does not work, event I type directly using my keyboard.
> 
> I'm sorry, my fault. I was not running the latest .deb package in the release tag list. With this version it works when you set the keyboard to "Translate mode".
> 
> @mv-si please, check it with this version https://github.com/rustdesk/rustdesk/releases/tag/1.2.3-2

I'd like the nightly to work as I paid pro and wish to use the shared adress book, but sure I can give it a try.

**Comment by rustdesk** [comment]
> @mv-si please, check it with this version https://github.com/rustdesk/rustdesk/releases/tag/1.2.3-2

@jjolmo do you mean 1.2.3-2 works for you, but nightly not work?

**Comment by mv-si** [comment]
Update : I uninstalled 1.2.4 nightly, installed 1.2.3-2 then tried : layout fr-fr OK
I then uninstalled 1.2.3-2 and reinstalled the nightly that was causing the issue (I kept the .deb from last week) : layout fr-fr was correct too... 

How can this be explained? It seems reinstalling a different version and back fixed the issue. 
However last week I tried uninstalling and reinstalling the same version without it fixing the issue

**Comment by rustdesk** [comment]
I can not explain either, :(

**Comment by jjolmo** [comment]
> > @mv-si please, check it with this version https://github.com/rustdesk/rustdesk/releases/tag/1.2.3-2
> 
> @jjolmo do you mean 1.2.3-2 (on both sides) works for you, but nightly (on both sides) not work?

I haven't tested nightly, I just downloaded the last .deb found in tags page, which I think is 1.2.3-2. It worked for me,

**Comment by slumbergod** [comment]
I'm having a keyboard issue too. I use English but both of my laptops have spanish keyboards. The symbols I type on my local machine are incorrect on the remote. It is as though  the remote is using anamerican keyboard.

Both machines are running Manjaro linux and both are up-to-date. I'm using RustDesk 1.3.5 on both, with Tailscale.

I have tried all three modes - legacy, map, and translate but they are all the same.

Yesterday I typed out this message and the keyboard started working properly. Today it is back to probems. I have no idea why it suddenly corrected itself yesterday so it is work posting properly today

**Comment by fufesou** [comment]
@slumbergod Hi, could you please also try 

1. Connect without `Tailscale`?
2. A third computer to test if the controlling side or the controlled side is wrong?

**Comment by juxuanu** [comment]
I have the same issue. Both layouts are Catalan (ca-ES) on both Android and Linux (wayland). But, the PC being controlled is writing as if I had a US layout.
Android ca-ES -- Linux ca-ES, but receives en-US

Both client on the latest stable.

**Comment by slumbergod** [comment]
> I have the same issue. Both layouts are Catalan (ca-ES) on both Android and Linux (wayland). But, the PC being controlled is writing as if I had a US layout. Android ca-ES -- Linux ca-ES, but receives en-US
> 
> Both client on the latest stable.

More often than not, the mapping is incorrect when I connect to my remote. I have no idea why, but if I close the remote window on my local machine and then open a new one, suddenly the mapping is correct. Does that happen for you?
