### ISSUE TITLE
Add menu "Add to favorite" to LAN items

### ISSUE THREAD

**Issue by attikov** [rustdesk/rustdesk#3387]
### Description

Add menu "Add to favorite" to LAN items

### Impact

Almost every user not having graphomania.

**Comment by rustdesk** [comment]
nightly build

**Comment by attikov** [comment]
Removed from the latesNightly builds. It was already implemented, it's gone.

**Comment by rustdesk** [comment]
@grummbeer

**Comment by grummbeer** [comment]
@21pages 

It depends on a new condition.  `if (inRecent) {}`

**Comment by 21pages** [comment]
https://github.com/rustdesk/rustdesk/blob/6ae2fbdbc81c55437aacd3186d7ffc216c2e8ff2/src/flutter_ffi.rs#L756
Only in recent can it be displayed

**Comment by grummbeer** [comment]
Is this a bug? Should a lan peer be markedable as a favorite at all?

**Comment by attikov** [comment]
If it's a giant programming challenge to beable to mark a peer as favourite despite its belonging, then just leave it and fix the other issue whereas it's not possible to connect to LAN peers if you have ID and Relay server on.

**Comment by rustdesk** [comment]
> https://github.com/rustdesk/rustdesk/blob/6ae2fbdbc81c55437aacd3186d7ffc216c2e8ff2/src/flutter_ffi.rs#L756
> 
> 
> lan peers are saved in RustDesk_lan_peers.toml, only in recent can it be displayed.

Since LAN peer can be displayed, it can also be displayed in fav.

**Comment by 21pages** [comment]
let me fix it.

**Comment by attikov** [comment]
Thank you all, it works again.
Don't forget, accessibility is half-win.
