### ISSUE TITLE
Proper updater

### ISSUE THREAD

**Issue by attikov** [rustdesk/rustdesk#3388]
### Description

I have no idea how an update should work, but the installer is just starts the new host like a protable application instead of updating the installation. This is rather strange.

### Impact

Almost every user used to ordinary things.

**Comment by rustdesk** [comment]
duplicate

**Comment by rustdesk** [comment]
#3347

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/3753
