### ISSUE TITLE
Can't connect to LAN clients if using custom relay/ID server

### ISSUE THREAD

**Issue by attikov** [rustdesk/rustdesk#3389]
### Bug Description

Can't connect to LAN clients if using custom relay/ID server.
Client yields "Remote PC is offline".

### How to Reproduce

-"-

### Expected Behavior

The opposite.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0+ Latest Nightly builds

### Screenshots

![grafik](https://user-images.githubusercontent.com/17452773/221415504-df9d7f8f-c321-4b75-9ac7-055c26cba070.png)

**Comment by rustdesk** [comment]
#763

**Comment by attikov** [comment]
Does not work in the lates Nightly build, again.
