### ISSUE TITLE
lock screen password can not be received correctly by win10

### ISSUE THREAD

**Issue by sixno** [rustdesk/rustdesk#339]
i am very sorry... close it...

**Describe the bug you encountered:**

When the controlled end locks the screen, it cannot send the lock screen password to unlock through the control end. In the unlocked state, the unlock password is sent, and the controlled end receives the open picture browsing signal.

**What did you expect to happen instead?**

unlock the controlled end.

**How did you install `RustDesk`?**

 Windows portable version

---

**RustDesk version and environment**

1.1.8

win10

**Comment by rustdesk** [comment]
It is windows UAC limitation. You have to install (not portable).

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/218

**Comment by sixno** [comment]
thank you, but i am not admin in the contrlled end, ==!
