### ISSUE TITLE
Double clicking on Tray Icon opens an extra client instead of bringing the current opened client to the front

### ISSUE THREAD

**Issue by attikov** [rustdesk/rustdesk#3391]
### Bug Description

Double clicking on Tray Icon opens an extra client instead of bringing the current opened to the front.

### How to Reproduce

Keep double-clicking on the Tray Icon.

### Expected Behavior

Open new if closed, bring current to the front if opened.

### Operating system(s) on local side and remote side

->

### RustDesk Version(s) on local side and remote side

1.2.0+

### Screenshots

N/A

**Comment by rustdesk** [comment]
fixed by latest commit.
