### ISSUE TITLE
Dark theme for Windows installation window

### ISSUE THREAD

**Issue by rakleed** [rustdesk/rustdesk#3394]
### Description

It would be nice if the installer window for Windows supports a dark theme so that all screens in the app are the same.

### Impact

All users of the Windows app, which is the majority.

### Additional Context

![Screenshot_20230226_113200](https://user-images.githubusercontent.com/19418601/221435719-3174b6bd-e54e-4c01-8c47-ff4458d43caf.png)

**Comment by rustdesk** [comment]
@21pages

**Comment by rakleed** [comment]
@21pages can you also use a custom title bar for the installation window so that it also changes its color?

![image](https://user-images.githubusercontent.com/19418601/221908590-cf6b262a-c17e-4e16-8dc8-4f877afbe392.png)

And can you make the text color light for the buttons after clicking Accept and Install?

![image](https://user-images.githubusercontent.com/19418601/221909220-9e56283e-f7f0-4cfd-afdc-04aee3eedcd1.png)
