### ISSUE TITLE
Tray dark theme support for Windows

### ISSUE THREAD

**Issue by rakleed** [rustdesk/rustdesk#3395]
### Description

It would be nice if the Windows tray menu would support a dark theme.

### Impact

All users of the Windows app, which is the majority.

### Additional Context

![Screenshot_20230226_113435](https://user-images.githubusercontent.com/19418601/221435925-67e4ec7c-77cf-477e-a7e5-a64c84663ca4.png)

**Comment by rustdesk** [comment]
close as fix merged

**Comment by rakleed** [comment]
@rustdesk but when using a dark theme in the system and in RustDesk, the tray menu still has a light background.
![Screenshot 2023-06-08 at 14 46 14](https://github.com/rustdesk/rustdesk/assets/19418601/6e24b779-5174-406a-bcd8-4c0cb1c369df)

**Comment by rustdesk** [comment]
We use https://github.com/tauri-apps/tray-icon

**Comment by rakleed** [comment]
https://github.com/tauri-apps/tauri/issues/6645

**Comment by rustdesk** [comment]
@sahilyeole can you try out https://github.com/tauri-apps/tao/blob/6df56c2dd1b0f4695dd40b70f75a22d1ba32c384/src/platform_impl/windows/dark_mode.rs#L63? https://github.com/tauri-apps/tauri/issues/6645#issuecomment-1676576972

**Comment by sahilyeole** [comment]
Yes, surely

**Comment by sahilyeole** [comment]
I tried using [tao's repository](https://github.com/tauri-apps/tao) (dev branch) as a dependency for `tao` and it works. Maybe we can implement/merge it with our dependency (https://github.com/rustdesk-org/tao/tree/muda) if it does not break other things. Or was I supposed to try it differently?

It automatically adapts to the system theme.

![Screenshot_2023-08-14_234208](https://github.com/rustdesk/rustdesk/assets/73148455/5ddeee3c-5827-4434-9bcc-27d9dc1319b9)
![Screenshot_2023-08-14_234241](https://github.com/rustdesk/rustdesk/assets/73148455/c460a79b-13e1-43b2-9fd6-9f3d8f18c12c)

**Comment by rustdesk** [comment]
I have synced dev branch, can you merge https://github.com/rustdesk-org/tao/commit/173f128608d282dc4036f213c1c42137464ff096 https://github.com/rustdesk-org/tao/commit/45c292ce8773850d75b1b2056ddd390a6dfff9ef to the dev branch?

**Comment by sahilyeole** [comment]
Ok, so should I make these changes (made in these two commits) in the dev branch and create a PR?

**Comment by rustdesk** [comment]
Yes
