### ISSUE TITLE
Keyboard doesn't work on remote machine.

### ISSUE THREAD

**Issue by elfzweik** [rustdesk/rustdesk#3398]
### Bug Description

When connecting to the remote machine, the display and mouse are working fine, except the keyboard. I remembered the keyboard worked in the before. But I did not log on this Ubuntu for long time. And this time I upgrade it to 22.04 with Wayland. I changed the ime to ibus rime. But the target Ubuntu is 22.04 with Xorg. I am not sure whether the problem lies in wayland or ibus ime. 

### How to Reproduce

Connect to the remote machine.

### Expected Behavior

Keyboard works fine.

### Operating system(s) on local side and remote side

Ubuntu 22.04 with wayland --> either Windows 10 or Ubuntu 22.04 with Xorg

### RustDesk Version(s) on local side and remote side

1.1.9-->1.1.8

### Screenshots

![image](https://user-images.githubusercontent.com/24219738/221461490-6955b2c9-0b1f-4891-b6e9-d076d43ef97d.png)

**Comment by rustdesk** [comment]
try out nightly lbuild.
