### ISSUE TITLE
Selecting text on android

### ISSUE THREAD

**Issue by dannkunt** [rustdesk/rustdesk#34]
I is difficult to work with text without selecting it .
Here is how it works on AnyDesk VS current version of RustDesk.

https://user-images.githubusercontent.com/32395839/118084374-460d3080-b3c9-11eb-98f8-bc640c8a4509.mp4

**Comment by rustdesk** [comment]
It is also easy to select text on RustDesk. Please click on the start point first, then click "mouse" button in the bottom toolbar, turn on "drag" option (at the top left of the screen), now you can select text, please turn off "drag" option after selection done.
