### ISSUE TITLE
"No Display" when windows10 connectiong to Ubuntu Server

### ISSUE THREAD

**Issue by wu-yang-work** [rustdesk/rustdesk#340]
hello，nice to meet you, I have a question, I use the Rustdesk，"No Display" when windows10 connectiong to Ubuntu Server，The Ubuntu Server has no display，but mtsc can，why?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/59

**Comment by grummbeer** [comment]
can be closed in favour of #59
