### ISSUE TITLE
hope to support http proxy

### ISSUE THREAD

**Issue by clack1987** [rustdesk/rustdesk#3403]
### Description

Many enterprise are using http web proxy servers. Don't support Socks proxy, could you help add support to it?

### Impact

Can't work under our internal network which used http/https web proxy.

**Comment by rustdesk** [comment]
#1414

**Comment by borondics** [comment]
This would be a great addition! I am also crippled by the proxies at my institute.

**Comment by rustdesk** [comment]
Done, https://twitter.com/rustdesk/status/1783468475480191022
