### ISSUE TITLE
 cursor (iOS -> macOS)  -> nightly mscOS not shown

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#3408]
### Bug Description

Another thing is that I found I cannot see my cursor (iOS -> macOS) when connecting to the latest nightly build for macOS. Maybe I will open a new issue for this problem later.

### How to Reproduce

`flutter run` works, but dmg installed version not work

### Expected Behavior

work

### Operating system(s) on local side and remote side

mobile -> mac

### RustDesk Version(s) on local side and remote side

1.1.9 -> nightly

### Screenshots

N/A

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3261#issuecomment-1445713907 enabling permission is embarrasing, it seems we make something wrong.

**Comment by wakewon** [comment]
> [#3261 (comment)](https://github.com/rustdesk/rustdesk/issues/3261#issuecomment-1445713907) enabling permission is embarrasing, it seems we make something wrong.

Maybe not. Permission management on macOS is extremely weird.
