### ISSUE TITLE
SQL uses TCP tunnel to execute query analysis SQL script 1 minute 4 seconds to stop tunnel network interruption

### ISSUE THREAD

**Issue by youhers** [rustdesk/rustdesk#3410]
### Bug Description

It seems that the connection is disconnected. I click Execute again, and the client TCP connection is displayed again. This phenomenon is repeated all the time. It automatically stops from 1:4 to 1:5 seconds after execution

似乎是断开了连接，我再次点击执行，客户端TCP连接再次显示，一直重复这个现象在执行后的1分4秒到1分5秒自动停止

### How to Reproduce

The master terminal is the latest version of 1.2.0, and the client is version 1.1.9

主控端是1.2.0最新版，客户端是1.1.9版

### Expected Behavior

It should not interrupt the network connection halfway

它不应该中途中断网络连接

### Operating system(s) on local side and remote side

WIN10 - WIN7

### RustDesk Version(s) on local side and remote side

1.2.0 - 1.1.9

### Screenshots

![Uploading 企业微信截图_20230227185501.png…]()

**Comment by youhers** [comment]
![企业微信截图_20230227185501](https://user-images.githubusercontent.com/106003909/221546260-940acb20-ad1d-4972-91e6-37bcd562cec1.png)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/918 

> refactoring port forward (all port forwards sharing the same connection)

**Comment by youhers** [comment]
thank you

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2835#issuecomment-1384816170
