### ISSUE TITLE
build failure 

### ISSUE THREAD

**Issue by yashpatel1598** [rustdesk/rustdesk#3414]
### Bug Description

at a time of built after running this  command and error occures 
command : cargo build
the error comes are: error: failed to run custom build command for `gstreamer-sys v0.9.1`

Caused by:
  process didn't exit successfully: `/home/ysh/Desktop/netdesk/rustdesk/rustdesk/target/debug/build/gstreamer-sys-5b9fc3fb8ffdd8a1/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=GSTREAMER_1.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=GSTREAMER_1.0_STATIC
  cargo:rerun-if-env-changed=GSTREAMER_1.0_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  `"pkg-config" "--libs" "--cflags" "gstreamer-1.0" "gstreamer-1.0 >= 1.10"` did not exit successfully: exit status: 1
  error: could not find system library 'gstreamer-1.0' required by the 'gstreamer-sys' crate

  --- stderr
  Package gstreamer-1.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gstreamer-1.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gstreamer-1.0' found
  Package gstreamer-1.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gstreamer-1.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gstreamer-1.0' found

warning: build failed, waiting for other jobs to finish...

### How to Reproduce

-

### Expected Behavior

built successful 

### Operating system(s) on local side and remote side

Ubuntu 20.04

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

-

**Comment by rustdesk** [comment]
#763
