### ISSUE TITLE
Building rustdesk fails with a gstreamer error on Mageia8

### ISSUE THREAD

**Issue by ericxuo** [rustdesk/rustdesk#3416]
### Bug Description

Hi,

I get the same issue than https://github.com/rustdesk/rustdesk/issues/1226 but I'm NOT using docker. Could you explain how to do to solve this issue ?

My (partial) commands :
setenv VCPKG_ROOT $HOME/vcpkg
cargo run

...
Compiling gdk-sys v0.16.0
error: failed to run custom build command for gstreamer-sys v0.9.1

Caused by:
process didn't exit successfully: /home/eric/Téléchargements/rustDesk/rustdesk/target/debug/build/gstreamer-sys-5b9fc3fb8ffdd8a1/build-script-build (exit status: 1)
--- stdout
cargo:rerun-if-env-changed=GSTREAMER_1.0_NO_PKG_CONFIG
cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG
cargo:rerun-if-env-changed=PKG_CONFIG
cargo:rerun-if-env-changed=GSTREAMER_1.0_STATIC
cargo:rerun-if-env-changed=GSTREAMER_1.0_DYNAMIC
cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
cargo:rerun-if-env-changed=PKG_CONFIG_PATH
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

--- stderr
"pkg-config" "--libs" "--cflags" "gstreamer-1.0" "gstreamer-1.0 >= 1.10" did not exit successfully: exit status: 1
error: could not find system library 'gstreamer-1.0' required by the 'gstreamer-sys' crate

--- stderr
Package gstreamer-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-1.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gstreamer-1.0', required by 'virtual:world', not found
Package 'gstreamer-1.0', required by 'virtual:world', not found

I'm running under Mageia8.

Regards.

Xuo.

### How to Reproduce

git clone https://github.com/microsoft/vcpkg
cd vcpkg
git checkout 2021.12.01
cd ..
vcpkg/bootstrap-vcpkg.sh
setenv VCPKG_ROOT $HOME/rustDesk/vcpkg
vcpkg/vcpkg install libvpx libyuv opus
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
setenv PATH $HOME/.cargo/bin:$PATH
git clone https://github.com/rustdesk/rustdesk
cd rustdesk
mkdir -p target/debug
wget https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin.lnx/x64/libsciter-gtk.so
mv libsciter-gtk.so target/debug
setenv VCPKG_ROOT $HOME/vcpkg
cargo run

### Expected Behavior

No compilation error.

### Operating system(s) on local side and remote side

Mageia8

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![ksnip_20230227-160702](https://user-images.githubusercontent.com/9089499/221600552-94caec7f-2025-4df2-86eb-2404c496f6be.png)

**Comment by rustdesk** [comment]
#763

**Comment by QYH2MMT4EVER** [comment]
> 

Have you solved this problem ? could you give me some help if so?

**Comment by ericxuo** [comment]
Hello,

I think I have installed the package lib64clang-devel to make it compile correctly.

Regards.

Xuo.

**Comment by dvorakchen** [comment]
enter `sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev` to install

reference: https://stackoverflow.com/questions/25558308/error-no-gstreamer-1-0-1-4-0-gstreamer-found#51665804
