### ISSUE TITLE
Custom public key value (RS_PUB_KEY) is ignored in latest nightly builds - no connection possible

### ISSUE THREAD

**Issue by nextgen-networks** [rustdesk/rustdesk#3417]
### Bug Description

Latest custom nightly builds do not connect via custom server configured in github repository secrets.
Seems like the variable RS_PUB_KEY is not taken into account anymore when github actions creates the build.
No connection is possible then with a RustDesk server that accepts encrypted connections only.

This has been observed with windows as well as with android clients and with builds created at least since 20th Feb 2023.

The connection successfully established as soon as the RS_PUB_KEY variable is passed manually in the Client GUI of the two participants of a remote session.

### How to Reproduce

Try to connect with a nightly build that was build with custom repository values for RENDEZVOUS_SERVER as well as RS_PUB_KEY.

### Expected Behavior

Encrypted connection should be possible without entering the Key (Server public key / RS_PUB_KEY) via GUI

### Operating system(s) on local side and remote side

Windows 10 & 11 and Android 13

### RustDesk Version(s) on local side and remote side

1.2.0 nightly

### Screenshots

![2023-02-27 rustdesk client does not connect](https://user-images.githubusercontent.com/21206978/221633266-4cd8b8da-4194-4172-81e5-ed68e8c348a3.png)

### Additional Context

Log snippets:
[2023-02-27 17:38:50.017646 +01:00] INFO [src\client.rs:225] rendezvous server: SUB.DOMAIN.TLD:21116
[2023-02-27 17:38:50.018135 +01:00] INFO [src\client.rs:237] #1 punch attempt with 001.001.001.001:55746, id: 274464936
[2023-02-27 17:38:50.170655 +01:00] INFO [src\client.rs:287] relay requested from peer, time used: 152.9532ms, relay_server: SUB.DOMAIN.TLD:21117
[2023-02-27 17:39:05.990394 +01:00] DEBUG [C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\reqwest-0.11.13\src\connect.rs:429] starting new connection: http://SUB.DOMAIN.TLD:21114/
[2023-02-27 17:39:14.726101 +01:00] INFO [src\rendezvous_mediator.rs:294] create_relay requested from 002.002.002.002:11314, relay_server: SUB.DOMAIN.TLD:21117, uuid: PART1-PART2-PART3-PART4-PART5, secure: true
[2023-02-27 17:39:14.834303 +01:00] ERROR [src\server.rs:242] Failed to create relay connection for 002.002.002.002:11314 with uuid PART1-PART2-PART3-PART4-PART5: Failed to receive public key

**Comment by rustdesk** [comment]
fix it then.

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
#3126 #3328

**Comment by nextgen-networks** [comment]
> fix it then.

... not sure if I got this right ... but what could be fixed by me here?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/blob/92b5cfb803a248602e2eab80d3ecfe87c108c93e/libs/hbb_common/src/config.rs#L47

https://github.com/rustdesk/rustdesk/blob/92b5cfb803a248602e2eab80d3ecfe87c108c93e/libs/hbb_common/src/config.rs#L84

https://github.com/rustdesk/rustdesk/blob/92b5cfb803a248602e2eab80d3ecfe87c108c93e/.github/workflows/flutter-nightly.yml#L21

I can not image why RENDEZVOUS_SERVER works but RS_PUB_KEY not, the source code part almost the same.

**Comment by nextgen-networks** [comment]
> I can not imagine why RENDEZVOUS_SERVER works but RS_PUB_KEY not, the source code parts are almost the same.

Hmm not sure also. I try to reproduce this with a second repository with older state.
Quick comprehension question at this point: If this is a known/accepted bug, why was the case status was set to closed?

**Comment by nextgen-networks** [comment]
> I can not imagine why RENDEZVOUS_SERVER works but RS_PUB_KEY not, the source code parts are almost the same.

Ok, the feature braking change must have been introduced between February 08th and 20th.
The windows based nightly build with codebase from February 07th is working like a charm with the existing custom rendezvous server and its keypair.

**Comment by rustdesk** [comment]
`I can not imagine` does not mean i had this issue.

**Comment by nextgen-networks** [comment]
> `I can not imagine` does not mean `i had this issue`.

Ok, I think I don't understand the background/intention of your answer ...
... may I ask you to give a little more info about what you want to express with it.

(e.g. RENDEZVOUS_SERVER and RS_PUB_KEY is a not supported feature that won't get investigation by rustdesk and should not get by the community when broken.)

Thanks
