### ISSUE TITLE
No vertical scroll bar (handlers) in Settings

### ISSUE THREAD

**Issue by mikekgr** [rustdesk/rustdesk#3428]
### Bug Description

As I observed in the last nightly release Build Date: 2023-02-28 00:34 it is impossible to scroll down the screen from vertical scroll bar, at least in dark theme that I use, this is completely missing. I can scroll it by using mouse weal though.
Windows 10

### How to Reproduce

Just open the settings using dark theme in windows 10

### Expected Behavior

to be able to scroll up / down by clicking the up / down arrow in vertical scroll bar or by dragging the scroll bar handler

### Operating system(s) on local side and remote side

Windows 10 / Windows 11

### RustDesk Version(s) on local side and remote side

1.2.0 Nightly release Build Date: 2023-02-28 00:34

### Screenshots

no

**Comment by rustdesk** [comment]
@Kingtous

**Comment by rustdesk** [comment]
Can not drag?

**Comment by rustdesk** [comment]
Draggable on my mac and linux

**Comment by rustdesk** [comment]
Show me your video please.

**Comment by mikekgr** [comment]
Dear Sirs,
I switch to light theme and I saw that **all are as it should be**. The problem is, in the dark theme its invisible !
If you need I can give you screenshots.
Many thanks

**Comment by rustdesk** [comment]
yes

**Comment by mikekgr** [comment]
![screen1](https://user-images.githubusercontent.com/15084551/221791875-ab3c3b81-f47c-43f7-af99-17a5d5311ba0.png)
![screen2](https://user-images.githubusercontent.com/15084551/221791955-cc0edea0-01e3-42f4-b83a-7b1564085f04.png)

**Comment by rustdesk** [comment]
@Kingtous scrollbar color should be changed according the theme, currently it is always the same color.

**Comment by rustdesk** [comment]
ImprovedScrolling does not expose this api.

**Comment by Kingtous** [comment]
`ImprovedScrolling` is responsible for listening the scroll event only. We could define it in our theme config.
