### ISSUE TITLE
Could limit allow ID to connect my pc?

### ISSUE THREAD

**Issue by akong77** [rustdesk/rustdesk#3444]
### Description

Generally, as long as everyone knows my ID and is set on the same server, he can connect to my computer. Then, can I set the ID that is allowed to connect to my computer?

### Impact

For information security users who want to have advanced functions

**Comment by rustdesk** [comment]
IP whitelist https://github.com/rustdesk/rustdesk/issues/2246

**Comment by akong77** [comment]
I know it's can use IP whitelist.But if user use dynamic ip like pppoe.It's not static ip address.How to set it?

**Comment by akong77** [comment]
I has build rustdesk server.I want limit connect my computer just via allow ID.Because I sometimes use a laptop to connect to my home computer outside, the outside IP will not be fixed, but the ID will be fixed. I hope that only specific IDs can be set to allow connections.
