### ISSUE TITLE
Different mouse cursor/pointers

### ISSUE THREAD

**Issue by RonaldKF** [rustdesk/rustdesk#3447]
### Description

While sharing, whoever moves his mouse gets control over it... seems logic :)

But in our hectic world - every user clicks and does things, even when they are getting help/remote support...

A - it could be an option to actively click on the remote screen to get control over the mouse,
     so whoever clicks on the screen, gets the control - mouse cursor could change into different pointer
OR
B - user, who needs help, gets a mouse pointer, with a glyph or something,
     user, who will give assistance, gets also a mouse pointer (with glyph)

### Impact

everyone

**Comment by rustdesk** [comment]
Close to favor https://github.com/rustdesk/rustdesk/issues/573 or similar.
