### ISSUE TITLE
Error: libtexture_rgba_renderer_plugin.so()(64bit)

### ISSUE THREAD

**Issue by KAMYSHAN** [rustdesk/rustdesk#3452]
### Bug Description

▐  Fedora 37
▐  6.1.13-200.fc37.x86_64 
▐  2329 (rpm), 40 (flatpak) 
▐  gnome-terminal 
▐  i7-6800K @ 3.4GHz [53.0°C] 
▐  7265MiB / 31994MiB (22%) 
▐  ATI Radeon RX 6600/6600 XT/6600M 

Install:
rustdesk-1.2.0-0.x86_64-fedora28-centos8.rpm 
(build to 28-02-2023)

Error:
libtexture_rgba_renderer_plugin.so()(64bit) is needed by rustdesk-1.2.0-0.x86_64

![Снимок экрана от 2023-03-01 20-35-20](https://user-images.githubusercontent.com/126684222/222153982-574d2bb1-2f5f-434c-a392-ad26d0d6a1c8.png)

### How to Reproduce

****

### Expected Behavior

****

### Operating system(s) on local side and remote side

Fedora 37

### RustDesk Version(s) on local side and remote side

****

### Screenshots

****

**Comment by rustdesk** [comment]
@Kingtous

**Comment by rustdesk** [comment]
close as fix merged
