### ISSUE TITLE
CTRL + C = Reset by peer

### ISSUE THREAD

**Issue by markuszkruger** [rustdesk/rustdesk#3454]
### Bug Description

I have noticed a bug when you want to copy something using kb shortcut ctrl+c (when you hold CTRL and press multiple times C it will reset the connection)

### How to Reproduce

Select some text, hold CTRL and press C multiple times.

### Expected Behavior

It shouldn't bream connection

### Operating system(s) on local side and remote side

Linux - Linux

### RustDesk Version(s) on local side and remote side

1.2.0 Nightly

### Screenshots

No needed

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
@chiehw please reproduce and confirm.

**Comment by chiehw** [comment]
@markuszkruger Hello, I need more info to reproduce this issue.
1. What version of Linux do you have on both sides? 
2. Is there a wayland? 
3. Which keyboard mode?

**Comment by rustdesk** [comment]
close since no response.
