### ISSUE TITLE
Windows --reinstall stopped working

### ISSUE THREAD

**Issue by NicKoehler** [rustdesk/rustdesk#3467]
### Bug Description

`rustdesk --reinstall` is actually uninstalling and not installing anymore.

### How to Reproduce

`rustdesk.exe --reinstall`

### Expected Behavior

reinstall rustdesk

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

nighly build - 02/03/2023

### Screenshots

Maybe because of changes made in  #3437?

**Comment by rustdesk** [comment]
@21pages I guess it is related to your yesterday's fix to uninstall.

**Comment by rustdesk** [comment]
> Maybe because of changes made in #3437?

@NicKoehler exactly. :)

**Comment by rustdesk** [comment]
close as fix merged.
