### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method minimize on channel window_manager))

### ISSUE THREAD

**Issue by grummbeer** [rustdesk/rustdesk#3468]
### Bug Description

Exception 

```
MissingPluginException (MissingPluginException(No implementation found for method minimize on channel window_manager))
```

thrown when trying to "accept" a second connection to an android device.

 

### How to Reproduce

Running debug mode on Android device.

1. Open an File Transfer Connection from (VM/Ubuntu; debug mode) > File transfer > Android
2. Trying to open a Screen Connection from a second machine (Tumbleweed; debug mode) > Screen Share > same Android.

The incoming connection has landed on the device, tab "accept" trigger the exception.

### Expected Behavior

No exeception

### Operating system(s) on local side and remote side

linux > android

### RustDesk Version(s) on local side and remote side

build from source

### Screenshots

![exception-second-connection](https://user-images.githubusercontent.com/67791701/222445073-af0af4aa-b8b9-4ed6-a381-0669edb7327f.png)

![exception](https://user-images.githubusercontent.com/67791701/222440041-07d0ab34-7a64-4263-8a16-4e3c89a6f042.png)

### Additional Context

This happen in debug mode, no idea if this relevant for released version.

**Comment by rustdesk** [comment]
@Kingtous

**Comment by rustdesk** [comment]
close as fix merged
