### ISSUE TITLE
1.2.0 build portable cannot start

### ISSUE THREAD

**Issue by pedjas** [rustdesk/rustdesk#3469]
### Bug Description

RustDesk nightly build 1.2.0 02. 03. 2023, run as portable
OS: Windows

When I double click RustDesk exe to start it it does not start. Sometimes it does start but most of the time it does not.

When it does not start I can find it in TaskManager but there are two processes. One is called RustDEsk and other RustDesk.exe. If I kill RustDesk process bot processes are killed.

If it does start properly, then TaskManager shows only one instance: RustDesk.exe.

This also happened with previous nightly build but rarely. With the latest build this is almost certain it will not start.

### How to Reproduce

Doble click on exe to start it.

### Expected Behavior

RustDesk should open and allow connection. 
Instead mouse cursor shortly shows hourglass and nothing else happens visually.
RustDesk process is run but as two processes as explained above.

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0 nighlty 2023-03-02

### Screenshots

no screenshot

**Comment by rustdesk** [comment]
@Kingtous

**Comment by rustdesk** [comment]
please upload a failing video including the task manager.

**Comment by rustdesk** [comment]
close as no response.
