### ISSUE TITLE
Android chat messages from controlling side not shown

### ISSUE THREAD

**Issue by grummbeer** [rustdesk/rustdesk#3471]
### Bug Description

Chat messages from controlling side are not shown

### How to Reproduce

Connect from linux to android, open the chat from android side connection manager, type messages.

### Expected Behavior

Messages should be in sync

### Operating system(s) on local side and remote side

linux > android

### RustDesk Version(s) on local side and remote side

source

### Screenshots

![chat-is-not-in-sync](https://user-images.githubusercontent.com/67791701/222458907-6f6d70f1-0a2e-4b20-9db6-9cb65fd0f1cb.png)

### Additional Context

All in debug mode, haven't tested in other constellations

**Comment by rustdesk** [comment]
left side is mobile?

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by rustdesk** [comment]
may be broken by msgbox refactory last time.

**Comment by grummbeer** [comment]
> left side is mobile?

yes
