### ISSUE TITLE
When will be service license out?

### ISSUE THREAD

**Issue by phdwilson** [rustdesk/rustdesk#348]
本人有意做一个集群式服务器，搭建多个公益免费G口中继，请给我一个RusTdesk server许可证开放购买时间。

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server/issues/15

**Comment by darkguy2008** [comment]
Any way we can have the message posted in Discord here to see for those who don't want, or can't use it? Thank you.

**Comment by rustdesk** [comment]
It is open source and free now.
