### ISSUE TITLE
Missing screen

### ISSUE THREAD

**Issue by giuliovale** [rustdesk/rustdesk#3485]
### Bug Description

The latest build causes connection problems

### How to Reproduce

Try to connect

### Expected Behavior

Good screen connection

### Operating system(s) on local side and remote side

windows 11 -> windows 11

### RustDesk Version(s) on local side and remote side

Last nightly build 1.2 -> 1.2

### Screenshots

![image](https://user-images.githubusercontent.com/6909743/222679859-8614b796-199e-4d5e-b71d-ab049a41a859.png)

**Comment by rustdesk** [comment]
Use the one we are building now.
