### ISSUE TITLE
Feature Request: exclusion list of hotkeys

### ISSUE THREAD

**Issue by hongwen000** [rustdesk/rustdesk#3488]
### Description

Allow specifying of a hotkey list, where the combination keys in the list will not be captured and sent to the remote computer.

### Impact

This feature will greatly facilitating switching between local and remote applications. When working with a remote server for development, specific applications are usually only run on the remote server, while other tasks such as searching for information, editing documents, taking screenshots, and sending messages are performed on the local machine. By ignoring specific hotkeys such as Alt+Tab, Alt+W, etc., from being sent to the remote computer, the workflow can be greatly improved.

### Additional Context

I have observed that only Real VNC Client provides a similar option (not sending certain modifier keys to the remote computer) among existing remote desktop services, and I have benefited from it.

**Comment by rustdesk** [comment]
@fufesou @chiehw let us put this in our todo list.

**Comment by hongwen000** [comment]
@rustdesk Thank you for your prompt reply. I look forward to the implementation of this feature.

**Comment by rustdesk** [comment]
But low priority.

**Comment by hongwen000** [comment]
@rustdesk The option key for this feature in Real VNC is "SendSpecialKeys". I hope that Rustdesk has a higher degree of configurability, as the hotkey list specified in this feature in Real VNC is built-in and unchangeable.

**Comment by hongwen000** [comment]
> But low priority.

Understood, thank you for your hard work.

**Comment by rustdesk** [comment]
@hongwen000 could you give me some pictures of this part in realvnc, it will help us design the ui and rules etc?

**Comment by hongwen000** [comment]
@rustdesk Of course. However, the option for this feature in RealVNC is only available as an advanced option buried within the options list. The vim plugin for Clion has implemented a UI that allows the user to choose how combination keys are handled, which may serve as a reference.
![image](https://user-images.githubusercontent.com/25456415/222706591-72bb6e0f-3b33-4134-8b34-60d185dfb490.png)
![image](https://user-images.githubusercontent.com/25456415/222707534-633f5dfb-3bde-4006-b656-79494403c74a.png)

**Comment by rustdesk** [comment]
Thanks

**Comment by hongwen000** [comment]
@rustdesk It's my great pleasure.

**Comment by rustdesk** [comment]
close this to favor https://github.com/rustdesk/rustdesk/issues/3488

**Comment by bernd-wechner** [comment]
How this was closed in favour of https://github.com/rustdesk/rustdesk/issues/3740 puzzles me. They seem completely unrelated. I need this feature. To be able to specify keys that rustdesk passes through tot he host OS!

**Comment by bernd-wechner** [comment]
I'd certainly be reopening it if I could ;-). This is one of the most sorely missing features in RustDesk IMHO. The ability to reserve certain user defined keystrokes for local use rather than remote use (don't send them).

**Comment by MMMikeM** [comment]
Agreed, wild that this isn't already a thing. Even things like Moonlight have some variation of this
