### ISSUE TITLE
Crashes when providing invalid arguments to executable.

### ISSUE THREAD

**Issue by dzatoah** [rustdesk/rustdesk#3489]
### Bug Description

RustDesk seems to crash when providing invalid command line arguments to its executable.
Happens in debug mode build also with `cargo build --release`

### How to Reproduce

`cargo run -- blablah`

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.24s
     Running `target/debug/rustdesk blablah`
[2023-03-03T11:40:35Z ERROR librustdesk::ui] Wrong command: ["blablah"]
[2023-03-03T11:40:36Z ERROR hbb_common::platform] Got signal 11 and exit. stack:
    backtrace::backtrace::libunwind::trace::hce46459021787141
    backtrace::backtrace::trace_unsynchronized::h26e6bc73bbbb2acf
    backtrace::backtrace::trace::h65944709538cb314
    hbb_common::platform::breakdown_signal_handler::h2837609f4740a5eb
    _ZN3gtk11application16clear_font_cacheEv
    exit
    __libc_start_main
    _start
```

### Expected Behavior

I expect RustDesk to print the usage of this program with a listing of all available commands and argument syntax.

### Operating system(s) on local side and remote side

Debian Bookworm

### RustDesk Version(s) on local side and remote side

latest master

### Screenshots

.

**Comment by rustdesk** [comment]
It is not an command line tool.

**Comment by dzatoah** [comment]
I don't agree. There are hidden command line arguments like `--service``.

It is *very* common in POSIX/Linux to start programs (even GUI applications) via the command line and most programs either ignore it completely or behave like a command line tool then.

Please consider to reopen this issue since it's very awkward for a program to just crash if you provide arguments.

**Comment by sunweaver** [comment]
Well, if an application segfaults on wrong input, it surely is a bug, isn't it?
