### ISSUE TITLE
1.2 Connect multi-window？

### ISSUE THREAD

**Issue by StrangerTA** [rustdesk/rustdesk#3491]
### Description

I like the new interface of v1.2 very much, but there is a problem that bothers me. When I connect multiple computers, the screens will be concentrated in the same window, unlike v1.1.9, which is separated, so I can watch multiple screens at the same time. , can it be done in v1.2? 
Thanks

### Impact

..

**Comment by rustdesk** [comment]
be patient.

**Comment by StrangerTA** [comment]
Sorry, I don't understand what you mean, may it be changed in the future or will it be maintained like this without any changes?
Thanks
sorry for disturbing

**Comment by rustdesk** [comment]
it will be like chrom tab window, which can be detached in the future. @Kingtous

**Comment by SonDG1974** [comment]
It's a really necessary function
