### ISSUE TITLE
Mouse Pointer randomly goes missing when remote controlling Target Machine

### ISSUE THREAD

**Issue by wazerstar** [rustdesk/rustdesk#3492]
### Bug Description

Having two multiple monitors as Remote, when you connect to another Machine, in this instance is Windows > Windows with nightly version.

Sometimes the mouse pointer insides Rustdesk is not drawn for you as Remote helper, you have to force mouse quickly over on the other monitor to see your actually mouse on your own screen, then put it back onto Rustdesk session to actually see the mouse pointer being drawn..

### How to Reproduce

I dont know how to trigger it but it happens randomly and very often in sessions.

### Expected Behavior

As connector, the mouse pointer should always be visible and not disappear randomly.

### Operating system(s) on local side and remote side

Windows 10 > Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0 Nightly > 1.2.0 Nightly

### Screenshots

N/A

Can try record a video when it happens again.

**Comment by rustdesk** [comment]
Close since no video, will reopen if video uploaded.
