### ISSUE TITLE
Android Theme Settings. Dialog always shows "Follow  System"

### ISSUE THREAD

**Issue by grummbeer** [rustdesk/rustdesk#3496]
### Bug Description

Dialog always shows "Follow  System" as selected value what is in two cases wrong.

### How to Reproduce

Open Settings tab "Theme". "Follow System" is checked

### Expected Behavior

Current theme is preselected

### Operating system(s) on local side and remote side

Android

### RustDesk Version(s) on local side and remote side

source

### Screenshots

![mobile-settings-theme-dialog](https://user-images.githubusercontent.com/67791701/222794083-6a763ac3-919e-4822-89d1-507aec1e5d7f.png)

### Additional Context

Two things i noticed.

1. MyTheme.getThemeModePreference(); always return `ThemeMode.system`
2. MyTheme.getCurrentThemeMode() `WidgetsBinding.instance.platformDispatcher.platformBrightness` is always "Brightness.light"

What is the right method on which i can rely to the get the current Thememode? When the context is available, can i use safety `Theme.of(context).brightness` (https://github.com/rustdesk/rustdesk/pull/3495)?

**Comment by rustdesk** [comment]
I just asked ChatGPT.

```import 'package:flutter/foundation.dart' show kIsAndroid;
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    bool isDarkMode = false;

    if (kIsAndroid) {
      var brightness = MediaQuery.of(context).platformBrightness;
      isDarkMode = brightness == Brightness.dark;
    }

    return MaterialApp(
      theme: isDarkMode ? ThemeData.dark() : ThemeData.light(),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Android Theme Detection'),
      ),
      body: Center(
        child: Text('This app is using ${Theme.of(context).brightness} theme.'),
      ),
    );
  }
}
```

**Comment by rustdesk** [comment]
I think your method is correct.

**Comment by grummbeer** [comment]
Its working again
Thanks to @Heap-Hop https://github.com/rustdesk/rustdesk/commit/8a083f40b0a560f18d673751c1ac54cd428aef25?
