### ISSUE TITLE
File Manager. "select all" > "delete" does nothing

### ISSUE THREAD

**Issue by grummbeer** [rustdesk/rustdesk#3499]
### Bug Description

Select all files via the three-dot menu "Select All" and click on "Delete", nothing happens.

### How to Reproduce

Open file manager select files via "select all" click the trash symbol.

### Expected Behavior

Confirm dialog opens and let me delete all files. Same behavior like selecting the files by click.

### Operating system(s) on local side and remote side

Linux > Android

### RustDesk Version(s) on local side and remote side

source

### Screenshots

![delete-select-all-does-not-work](https://user-images.githubusercontent.com/67791701/222815881-3532dcaf-5550-4c57-b162-5f315c2c86f5.gif)

### Additional Context

Log says:

```
flutter: Failed to removeFile, wrong path state
```

**Comment by rustdesk** [comment]
@Heap-Hop
