### ISSUE TITLE
Keyboard layouts and shortcuts

### ISSUE THREAD

**Issue by aolko** [rustdesk/rustdesk#35]
Please add the keyboard layout sync, so the remote pc layout matches the host.
(Currently if remote keyboard layout doesn't match you'll end up typing in both layouts at the same time like `ttyyppiinngg`)

Also please add the ability to use the keyboard shortcuts between host and remote pc (win/super shortcuts also don't work).

**Comment by rustdesk** [comment]
This may need the help of community. For me, I can only make sure standard US keyboard layout work. Because I do not use the other layout.

**Comment by rustdesk** [comment]
> win/super shortcuts

I will solve this.

**Comment by aolko** [comment]
also found out that default side mouse button actions (back/forward) don't work on the remote machine as well

![image](https://user-images.githubusercontent.com/581458/118105678-5b905380-b3e5-11eb-9ac4-2d4930758ba7.png)

**Comment by rustdesk** [comment]
oops, I even do not know such thing.

**Comment by alex498** [comment]
Also would be better to make shortcut for Alt + TAB or broadcast it directly
Now alt+tab working for host pc only

**Comment by Rheydskey** [comment]
Maybe close it

**Comment by rustdesk** [comment]
No, layout and  win/super shortcuts not solved yet

**Comment by Rheydskey** [comment]
Ok

**Comment by LambdAurora** [comment]
Hope the layout issue gets resolved soon since it literally makes this software unusable for AZERTY keyboard users. :(
Both client and host are in AZERTY but despite that it still looks like rustdesk forces QWERTY on it somehow.

**Comment by rustdesk** [comment]
Yes，I understand you. But without contribution, I can only put my limit resource on the most urgent issues. You have to wait longer.

**Comment by ChenZh1peng** [comment]
Win key can not use in remote pc, when host is Ubuntu，remote pc is windows.
whenever press win, it will only triggle super key in Ubuntu instead of sending win to remote pc.

**Comment by hengfei-wang** [comment]
I use my mac to control ubuntu server. I found that ctrl+tab shortcut doesn't work in ubuntu. By the way, I set ctrl+tab to switch among applications in ubuntu. And ctrl+tab is also the shortcut for switching input method in my mac. It seems like shortcuts on my mac have higher priority than server. So rustdesk always triggers mac's shortcuts instead of the server.

Can you add the option which allows server to take over keyboard input completely? Of course, not anyone needs this. So just set an option for that. 

Thank you for developing this great tool!

**Comment by jackbillstrom** [comment]
I'm currently running Win 10 Pro as a host, while connecting from Ubuntu 22.04.1 with the same keyboard layout I'm not available so use any keys at all.

However when dual-booted into Win 11 Pro on my client instead it works like a charm 🙂

**Comment by OliveTheFemboy** [comment]
I'm having some mapping issues.

Question mark is not mapped. In it's place is \ which is also mapped to it's appropriate key.
Open and closed braces are not mapped at all and in their place is nothing.

US QWERTY to US QWERTY (English) from Windows 10 (portable) to Manjaro.

**Comment by rustdesk** [comment]
try out nightly please

**Comment by cypherpunks03** [comment]
Custom shortcuts with Shift-modifier on the numeric row transmit incorrect characters in other keyboard layouts on  Windows. For example, on a Dvorak.
![image](https://user-images.githubusercontent.com/80201571/201087917-08521d47-8ba6-4105-93e8-4e4bcccc22be.png)

**Comment by rustdesk** [comment]
> Dvorak

which build? try out nightly build if not

**Comment by rustdesk** [comment]
> Update: Keyboard mapping issue is resolved in Nightly, however other more problematic issues are present.

Report your more please. So it is called nightly, not stable release.

**Comment by rustdesk** [comment]
#1547

**Comment by vorspohl** [comment]
I use it for remote form Windows to Mac Mini M1 (os: Ventura 13.2.1). On both German keyboard layout.

when I press:
 '{' (under Windows ALT GR + 7) on Mac appear: '|'
 '@' (under Windows: ALT GR + Q) on Mac appear: '«'
'~' (under Windows: ALT GR + '+') on Mac appear:  '+'
'\' (under Windows ALT GR + 'ß') on Mac appear: '¿'
'[' (under Windows ALT GR + 8) on Mac appear:  '{'
looks like all "ALT GR" key combinations make problems and are mixed.

'normal' keys are ok

it's possible to fix?

**Comment by rustdesk** [comment]
try nightly build both sides

**Comment by vorspohl** [comment]
with night build I can even not connect anymore...

**Comment by ACSSYNCTRAYZOR** [comment]
what is happening here is the following:

pc 1 connects to pc 2 remotely
use portuguese keyboard
on pc 1 there are characters that change position on the keyboard and others disappear and on pc2, to which pc 1 is connected, the same thing happens, adding that some of the keyboard keys simply stop working

**Comment by willDTF** [comment]
Azerty keyboard on ipad result a qwerty on pc
Both side language is set to french in settings

Please port keyboards from iOS too

**Comment by Baerbeisser** [comment]
Just wanted to report that on both PC with Linux set up as swiss german (ch_DE-UTF-8) results in US-Layout for remote access via Rustdesk.

I'm not adebt in Rust yet, but from what it looks like you are implementing your own keyboard mapping solution? Can't you use something like [key_mapping](https://docs.rs/key-mapping/latest/key_mapping/) for this?
