### ISSUE TITLE
File Manager. Linux. Symlink is not followed, shows empty list (link to network NAS device)

### ISSUE THREAD

**Issue by grummbeer** [rustdesk/rustdesk#3501]
### Bug Description

On Linux System (Local) the file manager shows an empty list on click a symlink.

Navigate to the directory works as expected.

### How to Reproduce

Create a symlink, open file manager click the new symlink entry. A empty list is shown.
 

### Expected Behavior

listing of files in the symlink goal.

### Operating system(s) on local side and remote side

Linux > Android

### RustDesk Version(s) on local side and remote side

source

### Screenshots

|home symlink | symlink goal|
|--|--|
|![file-transfer-symlink-empty](https://user-images.githubusercontent.com/67791701/222825448-2153fae5-f8c7-477a-99e2-294d8002a5cd.png)|![file-transfer-symlink-list](https://user-images.githubusercontent.com/67791701/222825444-c424cb04-d732-4bd8-a8c4-22b4e8e30d5a.png)|

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by rustdesk** [comment]
and another bug.

https://github.com/rustdesk/rustdesk/pull/3498#issuecomment-1454169188

**Comment by rustdesk** [comment]
Wierd, both @Heap-Hop and @fufesou can not reproduce this.

**Comment by grummbeer** [comment]
Ah! The goal is on a network NAS device. Links to the local fs work.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3402 i guess similar.

**Comment by grummbeer** [comment]
### Linux 

```
ln -s /nas-drive/dir link-to-nas-drive-dir
```

- Windows > Linux - Pass
- Linux > Linux - Pass

### Windows

```
mklink /d link-to-netdrive-dir z:\test-files 
mklink /d link-to-local-dir c:\test-files
mklink /j junction-to-local-dir c:\test-files
```

- Linux > windows - Pass
- Windows > Windows - Pass

Only this strange `*.lnk` thing doesn`t work, but … who cares :-)

I can't reproduce this bug for linux anymore and can confirm links are followed when connecting to windows. @rustdesk I think this issue can be closed. Waiting a while for a response from the other two issues?

**Comment by rustdesk** [comment]
@grummbeer Thanks
