### ISSUE TITLE
docker build can't work

### ISSUE THREAD

**Issue by shanjunmei** [rustdesk/rustdesk#3510]
### Bug Description

docker run rustdesk-builder
/entrypoint: 3: cd: can't cd to /home/user/rustdesk

### How to Reproduce

run  `docker build -t "rustdesk-builder" .`
run `docker run rustdesk-builder`

### Expected Behavior

run cargo build 

### Operating system(s) on local side and remote side

win11

### RustDesk Version(s) on local side and remote side

1.19? clone at today

### Screenshots

![image](https://user-images.githubusercontent.com/9591051/222906099-f9293741-f4b5-4b91-98c6-f1309ad11e0a.png)

**Comment by rustdesk** [comment]
#763
