### ISSUE TITLE
[flatpak] desktop launcher/shortcut is missing

### ISSUE THREAD

**Issue by ildar** [rustdesk/rustdesk#3517]
### Bug Description

after flatpak is installed there's no desktop launcher/shortcut in the menu

### How to Reproduce

install and see

### Expected Behavior

[rustdesk.desktop](https://github.com/rustdesk/rustdesk/blob/master/res/rustdesk.desktop) and [rustdesk-link.desktop](https://github.com/rustdesk/rustdesk/blob/master/res/rustdesk-link.desktop) installed

### Operating system(s) on local side and remote side

Linux any

### RustDesk Version(s) on local side and remote side

1.2.0

**Comment by rustdesk** [comment]
@Kingtous

**Comment by rustdesk** [comment]
close as fix merged

**Comment by ildar** [comment]
thanx. It's now as expected.
