### ISSUE TITLE
Can the switching function between self-built server and public server be added?

### ISSUE THREAD

**Issue by shengmean** [rustdesk/rustdesk#3518]
### Description

1. I use a self-built rustdesk server, and I have been using several computers of my own to use each other, which is very fast. But occasionally you need to help others remotely, or others help you remotely, but the self-built rustdesk server cannot communicate with the public rustdesk server. You must either cancel your relay ID, or tell the other party the KEY and enter it into the rustdesk client, no matter where Both methods are very troublesome, because the KEY is automatically generated, there is no way to remember it, and there are domain names and so on. I wonder if it is possible to create a switch that can manually switch between the public server and the relay server, and remember the domain name, ID, and KEY of the self-built relay server, because it is possible that there are several relay servers.
2. Can an automatic connection mechanism be added to automatically connect to the next relay server or public server when the self-built rustdesk server cannot be connected. Because sometimes the self-built server cannot guarantee 100% stability. When the server fails, the remote machine will always try to connect to the self-built server, and will not automatically connect to the public server after a few attempts.
3. Thank you very much, this is a very useful software, I have been using it, but my English is not good, so I can only use translation software.

### Impact

1. People who need to switch back and forth between self-built servers and public servers frequently.
2. The self-built server is unstable. When the self-built server fails, it can automatically connect to other relay servers or public servers.
3. People with multiple relay servers.

**Comment by rustdesk** [comment]
#3022
