### ISSUE TITLE
After the file is copied, the source file cannot be overwritten

### ISSUE THREAD

**Issue by chmis8000** [rustdesk/rustdesk#3527]
### Bug Description

1:local: WIN10:Ctrl+C,  a text file
2:remote: WIN10:Ctrl+V
3:local:From another place on this machine, copy the file with the same name and overwrite the file
file cannot be overwritten

Note: Notepad can still modify files
Note: After closing rustdesk, the file can be overwritten

### How to Reproduce

none

### Expected Behavior

none

### Operating system(s) on local side and remote side

Win10->Win10

### RustDesk Version(s) on local side and remote side

1.2.0->1.2.0

### Screenshots

![image](https://user-images.githubusercontent.com/19686229/223019169-98b31007-9bad-417a-9ede-69d5cd011063.png)

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
close this to favor https://github.com/rustdesk/rustdesk/issues/2283#issuecomment-1423451806

**Comment by fufesou** [comment]
@R-ohit-B-isht
