### ISSUE TITLE
Android Image Corrupted

### ISSUE THREAD

**Issue by homeusepb** [rustdesk/rustdesk#3532]
### Bug Description

So randomly, when I try to connect to an Android device running RustDesk (so control the Android device rather), sometimes 3/10 times I get this weird corrupted image.
I have attached a screenshot below.

### How to Reproduce

Honestly not sure how or why, but it happens randomly.

I usually try to use my Windows PC to remote into Android and it happens.
Also tried Android -> Android, still same result sometimes. I have tried 4 different phones (mine, grandparents, parents, friends, etc.) all have this issue randomly (not always but 3/10 times).

### Expected Behavior

A clear image that appears 7/10 times as usual.

### Operating system(s) on local side and remote side

Windows 11 -> Android 9/10/11/12/13 and Android 9/10/11/12/13 -> Android 9/10/11/12/13 

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0 & 1.1.9 -> 1.1.9

### Screenshots

![Corrupted Image](https://user-images.githubusercontent.com/115416248/223090881-84f54cba-7aa7-4af0-a7c1-ca0996ec26d5.png)
Controlling a Samsung S21 Ultra running Android 13
(previously same scenario on Note20 Ultra running Android 12)

![Screenshot_20230306_220020](https://user-images.githubusercontent.com/115416248/223092907-22e25879-ed04-4b40-83eb-56d313502a88.jpg)

Controlling a Samsung A51 running Android 12

### Additional Context

I'm thinking this might be because image packets aren't correctly sent over? But this happens on 5G connection, 4G connection and also on a Gigabit Fibre connection with Wi-Fi so not really a speed issue.

And this doesn't fix until I fully restart the targetting Android phone.

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by homeusepb** [comment]
Any updates?

**Comment by rustdesk** [comment]
close to favor https://github.com/rustdesk/rustdesk/issues/3893
