### ISSUE TITLE
Autostart - screen sharing service requires re-enabling after power loss

### ISSUE THREAD

**Issue by michalwitek1232** [rustdesk/rustdesk#3533]
### Bug Description

After power loss, when I try to connect to my Android device with newest RustDesk installed (nightly, 52ce3dd), even with RustDesk signed with system key (highest permissions) it requires re-enabling screen sharing service. 

Could you automate it?

### How to Reproduce

1. Disconnect device for external power or power it off* (* - not tested)
2. Wait +- 20 minutes (full power off)
3. Power on device
4. Try to connect from client to remote device

### Expected Behavior

I could successfully connect to my Android device, everything works like when you enable each service. 
I have video output and remote commands like mouse click works.

### Operating system(s) on local side and remote side

Windows 11 -> Android

### RustDesk Version(s) on local side and remote side

nightly -> nightly (52ce3dd)

### Screenshots

![obraz](https://user-images.githubusercontent.com/42500203/223094265-bd0e3bdf-f93a-4860-89be-a8e2a42962ed.png)

**Comment by rustdesk** [comment]
This can not be avoided.

**Comment by michalwitek1232** [comment]
@rustdesk  even with root-level permissions and system-elevated apk ?

**Comment by rustdesk** [comment]
Do not know how to do with root.

**Comment by rustdesk** [comment]
But we welcome PR.

**Comment by rustdesk** [comment]
> allow permission

How about input permission?

**Comment by adelobosko** [comment]
> How about input permission?
For me allowing PROJECT_MEDIA is enough to control my device without any dialog

**Comment by adelobosko** [comment]
For rooted devices, the code can be something like this.
P.S. It is my first Rust code, I have never written on it, i have used google.

```rust
use libc::getuid;
use std::process::Command;

fn isRooted() -> bool {
    unsafe {
        return getuid() == 0;
    }
}

fn enableAccessibilityService() {
    let output = Command::new("adb")
        .arg("shell")
        .arg("settings")
        .arg("put")
        .arg("secure")
        .arg("enabled_accessibility_services")
        .arg("com.carriez.flutter_hbb/.InputService")
        .output()
        .expect("Failed to execute command \"enableAccessibilityService\"");

    println!("Output: {}", String::from_utf8_lossy(&output.stdout));
}

fn allowScreenCast() {
    let output = Command::new("adb")
        .arg("shell")
        .arg("appops")
        .arg("set")
        .arg("com.carriez.flutter_hbb")
        .arg("PROJECT_MEDIA")
        .arg("allow")
        .output()
        .expect("Failed to execute command");

    println!("Output: {}", String::from_utf8_lossy(&output.stdout));
}

fn main() {
    if isRooted() {
        enableAccessibilityService();
        allowScreenCast();
    } else {
        println!("No root access");
    }
}
```
