### ISSUE TITLE
German translation is a bit inaccurate

### ISSUE THREAD

**Issue by lukas-cz-ger** [rustdesk/rustdesk#3535]
### Bug Description

The German translation for the word "close" is "schließen" in this case. Is there an easy way to change this?

### How to Reproduce

open the app and start one of the four services

### Expected Behavior

The word "schließen"

### Operating system(s) on local side and remote side

Android

### RustDesk Version(s) on local side and remote side

1.1.10-1

### Screenshots

just open the app

**Comment by grummbeer** [comment]
Interessing point. A bit tricky situation in communication.

"Open" means opening the system settings. But after permission is granted in the system settings, it's just a matter of app based "allow"/"disallow" (access/usage of) or grant/revoke (permission), and not longer of "open" or "close" system settings (expect "input control" and "Screen capture" which is the service itself). This part is under development to address this.

The german "aktivieren" oder "deaktivieren" match this situation better (after the system settings are set). You can't "eine erteilte Berechtigung schließen". But you can "(Die Berechtigung) 'Dateien übertragen' aktivieren" or "(Die Berechtigung) 'Dateien übertragen' deaktivieren". Try it and judge afterwards what the best wording is for it.

> Is there an easy way to change this?

https://github.com/rustdesk/rustdesk/blob/master/src/lang/de.rs#L273
https://github.com/rustdesk/rustdesk/blob/master/src/lang/de.rs#L274

There is also a "Tip", refers to this buttons (showing on top when service is not running). Please don't forget to change it accordingly.

https://github.com/rustdesk/rustdesk/blob/master/src/lang/de.rs#L293

**Comment by grummbeer** [comment]
@lukas-cz-ger Please close this, because the "OPEN/CLOSE" has been replaced by a switch. So the confusion about the wording is no longer an issue. try out the nightly build https://github.com/rustdesk/rustdesk/releases/tag/nightly
