### ISSUE TITLE
Unsupported  Display server, X11 or Wayland expected.

### ISSUE THREAD

**Issue by texstar** [rustdesk/rustdesk#3541]
### Bug Description

Today I tried using Rustdesk to connect to another PC  and I got the error -

Unsupported  Display server, X11 or Wayland expected.

Wondering if anyone else has run into this.

### How to Reproduce

Run Rustdesk and try to connect to another computer.

### Expected Behavior

I expected to connect to the other computer.

### Operating system(s) on local side and remote side

Linux

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

none

**Comment by rustdesk** [comment]
it should have a snapshot

**Comment by rustdesk** [comment]
and more information about remote linux.

**Comment by vince6794** [comment]
Same problem here

remote is on:
```
Arch Linux : Kernel: 6.2.2-zen1-1-zen 
wayland 1.21.0-2
xorg-xwayland 22.1.8-1
sway 1.8.1-1
```
I even tried running rustdesk on xwayland (I checked with xeyes that it was actually running through xwayland)

**Comment by rustdesk** [comment]
xwayland is not supported, because xwayland deos not support screen capture.

**Comment by rustdesk** [comment]
Please show us the "Unsupported display server" error dialog.

**Comment by texstar** [comment]
![rustdesk](https://user-images.githubusercontent.com/6324233/223613020-9f52719e-5e43-4516-bd86-a0d0a528f119.png)

**Comment by rustdesk** [comment]
I just put a fix, use x11 as default, please try out new nightly build later, still in building.

**Comment by rustdesk** [comment]
Try out the new build.
