### ISSUE TITLE
Rustdesk can't reactivate MacOs

### ISSUE THREAD

**Issue by reyesmfabian** [rustdesk/rustdesk#3549]
### Bug Description

With the latest version of Rustdesk for MacOs Ventura on a M1 Chip, you cannot reactivate the pc to accept connections.

### How to Reproduce

Install the last build from nightly

### Expected Behavior

When the PC is in power saving mode, the rustdesk application can wake up the system to accept connections.

### Operating system(s) on local side and remote side

MacOs

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

![image](https://user-images.githubusercontent.com/57076657/223447252-dea96465-a7d6-4f8e-96a6-54ceea13500d.png)

**Comment by rustdesk** [comment]
#981

**Comment by reyesmfabian** [comment]
Hi, I'm sorry but I didn't really understand what to do. Because from outside my network I can't connect via SSH to my computer at home and I think the solution should be integrated to Rustdesk and not have to do it externally. I apologize again but it was not very clear to me the step to follow.
