### ISSUE TITLE
Equivalents to TeamViewer QuickSupport and Host

### ISSUE THREAD

**Issue by MrSandvik** [rustdesk/rustdesk#3559]
### Description

I just started playing around with Rustdesk, and first impressions are very good. Thank you for your great work!

My goal would be to move away from the rather costly TeamViewer, but with that I see that I will/would miss equivalents to the Host and QuickSupport packages. It is not a problem having clients run the portable RustDesk client, per se, but I really like the QuickSupport and Host features in TeamViewer. 

Adding a couple of minor things which variably don't deserve their own feature requests are FreeBSD binaries/package and the ability to lightly customize the design of the RustDesk client.

### Impact

I believe most power users considering RustDesk as a TeamViewer replacement would appreciate and benefit from Host and QuickSupport analogs.

**Comment by rustdesk** [comment]
already dine
