### ISSUE TITLE
Connection directly to IP address on internal network no longer working/removed from latest release.

### ISSUE THREAD

**Issue by jamiegau** [rustdesk/rustdesk#356]
In the past I was able to enter an IP address into the connection number input and connect directly without a internet relay..
When I attemtp this now, it simply open window and tries to connect many times, timinig out and looping for about 3-5 times.

An option in the configuration menu use to have the option to enable direct IP connections.  This apears to have disappeared.

...
Expectations:
To be able to enter an IP address and directly connect to a rustdesk instance without the need for a relay host.

...

I have tried this with Linux, windows Mac.  using the current 1.1.8 version on each.

This looks more like the feature has been intentionally removed in 1.1.8
Can we please get an explanation as to why this has occured?
It appears counter intuitive to the goals of this tool.....

**Comment by jamiegau** [comment]
Any idea when the next release is due.  This BUG looks like an oversight, and I expect is trivial to make work again.
I will test it as soon as a version with a fix is made available.

I use to use this feature a lot and I would prefer not to backgrade.
It was also featured in a Youtube video (https://youtu.be/JhInEcXbYps) I created that gained nice views.  Its not good that the video shows the feature that is now gone.

**Comment by rustdesk** [comment]
It is not gone in 1.1.8, there may be some unknown bug. I have no reason to make it disappear.

**Comment by jamiegau** [comment]
Ok great,
I have given this another test.  From my home PC to system at work over a VPN.  It appears to be working as expected now.
I will go back into the office and try to reproduce the BUG as I initially saw it tomorrow.

**Comment by jamiegau** [comment]
One comment.
After I mage a connection to a system via IP..  then I rename it to something verbose..  here is no way to figure out a renamed items actual connection method, be it an IP or a ID.  Would be good to make that discoverable.

**Comment by rustdesk** [comment]
> One comment. After I mage a connection to a system via IP.. then I rename it to something verbose.. here is no way to figure out a renamed items actual connection method, be it an IP or a ID. Would be good to make that discoverable.

You can name it like this, <alias>_ip

**Comment by jamiegau** [comment]
No, I want the full IP address so I can check its connecting to the expected target.  It would be better to make its IP or ID fully discoverable after rename.   As you have no idea if you have an item already connecting to the target in your list of historical devices.  As you have no way to know after you rename it.

Even it this is just a unusable item in the  3 dots menu on the item.  Above where it says "Connect"  . or make it say "Connect 10.10.10.10" or "Connect 123 456 789"

**Comment by rustdesk** [comment]
> Connect 10.10.10.10

Good idea.
