### ISSUE TITLE
Translation of the contextual menu in Spanish

### ISSUE THREAD

**Issue by agamenabar** [rustdesk/rustdesk#3562]
### Bug Description

When the right mouse button is clicked, the options in the context menu are not translated

### How to Reproduce

Press the right mouse button on a new connection and also when entering the password of the destination computer

### Expected Behavior

That the translated texts appear in the selected language of the application

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

nightly

### Screenshots

![Captura de pantalla 2023-03-08 212656](https://user-images.githubusercontent.com/127346772/223848772-2e3b22fb-f856-4530-8e94-73bf98b229ad.png)

**Comment by rustdesk** [comment]
@Kingtous https://docs.flutter.dev/development/accessibility-and-localization/internationalization

**Comment by rustdesk** [comment]
close as fix merged
