### ISSUE TITLE
[Nightly] Top toolbar auto expands icons when clicking on one, causing potential misclicks

### ISSUE THREAD

**Issue by bilago** [rustdesk/rustdesk#3563]
### Bug Description

When I expand the Monitor select icon, the submenu for monitors 1 and 2 appear. If I move my mouse to Monitor 2 but slightly over steer my mouse past it, it automatically expands the lightning bolt icon, causing me to accidentally press on "OS Password" instead of Monitor 2. This has happened to me several times.

What's even more interesting, is if I do the above, every icon exands as I move my mouse - but as soon as I reach an icon that does not expand (rec or full screen) this issue stops itself, and now hovering over the expandable icons does not auto expand the menus.

### How to Reproduce

Click on the Monitor switch icon

![image](https://user-images.githubusercontent.com/8310293/223851838-d0bc434d-69f2-4dbb-a05e-aa4434e8bf74.png)

Move mouse over the lighting bolt without clicking, now the menu for this icon auto expands
![image](https://user-images.githubusercontent.com/8310293/223852004-b29dc9ed-1f26-4ae6-af59-80c3d50fd7e7.png)

Move mouse over the display settings icon without clicking, now the menu for this icon auto expands

![image](https://user-images.githubusercontent.com/8310293/223852131-28399a85-1860-448b-b69a-5e4db98658c2.png)

Move mouse left to the full screen icon without clicking

![image](https://user-images.githubusercontent.com/8310293/223852179-e936d3b0-1ec7-4a15-9493-ee968fe8bde8.png)

Now move back to the Monitor select icon

![image](https://user-images.githubusercontent.com/8310293/223852236-1da1be0e-dc67-4fea-835f-fc2a1a0e8e3f.png)

Now it does not auto expand (expected behavior IMO)

### Expected Behavior

Clicking on a icon should expand it's menu, but moving your mouse to other icons without clicking should not auto expand them.

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

Nightly Build Date: 2023-03-08 03:54

### Screenshots

![image](https://user-images.githubusercontent.com/8310293/223852515-815156df-a141-4f23-9682-bc730474b09b.png)

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
auto expand has been removed.
