### ISSUE TITLE
Make it compatible with Antix

### ISSUE THREAD

**Issue by samuraikid0** [rustdesk/rustdesk#3564]
### Bug Description

If I install the .deb there's no executable present, with the appimage works fine, but I can't change the settings has the root privilege pop-pop doesn't open

### How to Reproduce

Install appimage of Rustdesk 1.2.0
Try to change root needed settings

### Expected Behavior

Be able to change the root settings

### Operating system(s) on local side and remote side

Antix -> Antix

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0

### Screenshots

![unlock](https://user-images.githubusercontent.com/46766062/223884275-33b627b9-efea-4742-8e2d-6fc41d700212.jpg)

**Comment by rustdesk** [comment]
close to favor #3565

**Comment by samuraikid0** [comment]
It's working good now, check it has resolved
Thanks !
