### ISSUE TITLE
Problems with vps build-your-own servers

### ISSUE THREAD

**Issue by cengzhijie3** [rustdesk/rustdesk#3568]
### Bug Description

Hi, I have tried many times with vultr vps, all ports and my own ip are fine, but your rustdesk client always shows my id is not correct, is there something wrong with your system? I can't set it up successfully this way.

### How to Reproduce

Try using a vps to build against your docker-compose service protocol to see if it works

### Expected Behavior

id does not exit

### Operating system(s) on local side and remote side

mac os13.2.1 > androdid

### RustDesk Version(s) on local side and remote side

nightly version

### Screenshots

<img width="1381" alt="截圖 2023-03-09 下午2 04 16" src="https://user-images.githubusercontent.com/89333400/223934769-ff1a5cb1-15f8-4862-85fd-eb00e5d9c389.png">
<img width="912" alt="截圖 2023-03-09 下午2 04 33" src="https://user-images.githubusercontent.com/89333400/223934791-69f0dd81-2710-4bdb-a7f0-5ee67ced830b.png">
<img width="682" alt="截圖 2023-03-09 下午2 04 48" src="https://user-images.githubusercontent.com/89333400/223934809-da22a733-3318-4eaf-aa94-59b8c631d911.png">

### Additional Context

Hi, I have tried many times with vultr vps, all ports and my own ip are fine, but your rustdesk client always shows my id is not correct, is there something wrong with your system? I can't set it up successfully this way.

**Comment by rustdesk** [comment]
#763
