### ISSUE TITLE
RustDeskIddDriver.inf flagged as threat in Bitdefender

### ISSUE THREAD

**Issue by Eruthon** [rustdesk/rustdesk#3570]
### Bug Description

Happened suddenly today, never before if I can remember.

### How to Reproduce

OS: Win11 22H2
AV: Bitdefender Total Security
RD: Version: 1.2.0 - Build Date: 2023-03-09 00:37 (TZ: CET)

Happened after automatic installation via deployment management server.

### Expected Behavior

No prompts and quarantined files.

### Operating system(s) on local side and remote side

Win11 22H2

### RustDesk Version(s) on local side and remote side

1.2.0 - 2023-03-09 00:37 (TZ: CET)

### Screenshots

![image](https://user-images.githubusercontent.com/37985268/223964893-46020c0e-6280-4e67-aec4-657ca904b93a.png)

**Comment by rustdesk** [comment]
added newly.

**Comment by rustdesk** [comment]
#144
