### ISSUE TITLE
Memory spike and stalls on Debian aarch64 (Crostini, a lower power VM, optimize decoding buffer)

### ISSUE THREAD

**Issue by sam-ulrich1** [rustdesk/rustdesk#3572]
### Bug Description

There appears to be a memory spike and stall of the client on aarch64 for Debian. The behavior seems inline with the existing issues for frame decoding causing the in-memory frame buffer to fill. When there is a lot of change on the remote machine the client will have a large memory spike of a little over a GB and then stall for awhile. If the frequent changes on the remote machine stop the client will clear the memory after some amount of time and begin normal operation. However, if the change is constant like a video the client will stall until the program is restarted. Attached are some screenshots to show the memory spike an cpu behaior. The CPU screenshot is about 2 seconds ahead of the memory (that's how long it took to take abother screen shot).

This is running on the Debian VM of a ChromeOS Lenovo Duet 5 with 4GB of RAM and 8 Arm Cores.

### How to Reproduce

Use a lower power aarch64 linux machine then remote into a machine that is playing a video or has some other source of constant change.

### Expected Behavior

SImply, not to crash. In practice, if this is a frame decoding issue the frame rate could be lowered by dropping every X frame once the buffer is filled to better keep up with the buffer.

### Operating system(s) on local side and remote side

Crostini based Debian -> Ubuntu 20.04 & Windows 11

### RustDesk Version(s) on local side and remote side

Nightly (3/8/23) -> Nightly (3/7/23)

### Screenshots

![Screenshot 2023-03-09 4 19 22 AM](https://user-images.githubusercontent.com/40002776/223996782-fb903d2b-f08f-4324-91f0-45cf2f6703b5.png)
![Screenshot 2023-03-09 4 19 08 AM](https://user-images.githubusercontent.com/40002776/223996804-5b3e6972-1a2d-4aa7-9cd2-50348e90481e.png)

**Comment by sam-ulrich1** [comment]
Happy to debug if you want any info

**Comment by 21pages** [comment]
Did you feel operation delay and what's the codec? Check `Show Quality Monitor` and you can see it. If it's h264/h265, try change it to vp9 for test.

**Comment by sam-ulrich1** [comment]
I don't have the codec option. I've been trying to figure out why. It may be that I'm using the AppImage versions since the policy kit stuff with the deb wasn't working well.

I enabled the monitoring and it shows vp9. When I turn down the fps to 15 and the bitrate to 20% I get a more stable connection but it will still stall if I start a video or something that changes often.

The experience is very laggy and poor overall which is not what I see with others here so I assume that the hardware I'm on may not have some hardware acceleration that others get to take advantage of. Nevertheless, this tablet is basically a super beefy android phone so I'd imagine it could handle it with some caveats

**Comment by sam-ulrich1** [comment]
The web interface does not have the same issue so that has been my workaround

**Comment by rustdesk** [comment]
i did do some additional job for web decoding for memory spike.

**Comment by sam-ulrich1** [comment]
I've been thinking about using rustdesk in a project that I've been working on so I'd like to get acquainted with the codebase. If you could point me to where I should look first I'd be happy to attempt a PR for the bidirectional comm. With that said, I'm super busy right now so I'd expect it to take me awhile.

**Comment by rustdesk** [comment]
Let me know when you are not super busy.

**Comment by sam-ulrich1** [comment]
I'm looking it over at the moment

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/blob/e7bf41e6fc2fecf44da2190c5c092d412cdf1c54/flutter/web/js/src/connection.ts#L436

**Comment by sam-ulrich1** [comment]
Thanks. I've been looking at the rust side to understand the comm between the client and the server. Let me know if I'm missing something.

From what I gathered the two steps are:
  1. Implement the `video_ack_required` in the login request of the desktop client
  2. Pipe back an ack message once the frame has been decoded on the client side
  
 Other questions:
   - Should the video_ack_required be an optional parameter that defaults to false so that the original behavior is preserved? I know you said that this implementation is a performance compromise so it may be wise to allow people to toggle it.
   - Would we still buffer the frames in memory on the client side or would it become entirely a synchronous stream since each frame needs to be acked?

**Comment by rustdesk** [comment]
video_ack_required frame by frame is stupid so it is only used for web.

**Comment by rustdesk** [comment]
> i did do some additional job for web decoding to avoid memory spike, which sacrifice performance, controlled side only sends frame if controling side finished consumption, this bidirection confirmation is sent frame by frame. We should figure out better solution for desktop, or we send bidirectional confirmation every second, or reuse test delay.

We need to propose clever solution for non-web.

**Comment by sam-ulrich1** [comment]
I didn't remember the second part.

Okay, then my thoughts (as naive as they are) would be two routes.
  1. Frame rate must remain consistent and when a backlog occurs on the client side a chunk of time (video) is just not sent by the server and therefore lost to the client. It would effectively be a stall in time and a jump forward.
  2. Frame rate is a best-effort value and individual frames are dropped by the server to lighten the backlog so the video remains current in time but the appearance drops.
  
These ideas are under the assumption that we likely cannot solve the decoding performance on all machines and that there needs to be a solution for a backlog. If you believe that we could solve the video decoding performance entirely than this may be the wrong path.

Thoughts?

**Comment by sam-ulrich1** [comment]
As for the bidirectional comms - a tick once per second that informs the server of the client's operational state would probably be a good idea for both this issue and other issues down the line. Is there any other info you'd like sent back to the server on an interval?

**Comment by rustdesk** [comment]
> a tick once per second that informs the server of the client's operational state would probably be a good idea f

We reuse https://github.com/rustdesk/rustdesk/blob/123dccc826ba4f00a06438d9b6833315d80ed1d5/src/client.rs#L1736

**Comment by sam-ulrich1** [comment]
Okay I'll take a look at it

**Comment by rustdesk** [comment]
Here we know how many frames in the queue wait for being decoded.

https://github.com/rustdesk/rustdesk/blob/123dccc826ba4f00a06438d9b6833315d80ed1d5/src/client.rs#L1678

**Comment by rustdesk** [comment]
Maybe we can also try out drop some frames here.

https://github.com/rustdesk/rustdesk/blob/123dccc826ba4f00a06438d9b6833315d80ed1d5/src/client.rs#L1678

**Comment by sam-ulrich1** [comment]
1. Do you want to measure the buffer in time (ie. 600ms behind) or in frames (ie. 40 frames behind)
2. How large of a buffer should we permit before dropping frames (ie. max of 1s behind or max of 30 frames behind)

**Comment by sam-ulrich1** [comment]
If we're going to be dropping frames my suggestion is that it is measured in time and the buffer only permits the client to fall behind a max of 300ms before starting to drop frames. That way the video stream remains current it just gets a little choppy

**Comment by rustdesk** [comment]
I prefer time also.

**Comment by rustdesk** [comment]
> 2\. How large of a buffer should we permit before dropping frames (ie. max of 1s behind or max of 30 frames behind)

No need to decide for now, write code first.

**Comment by sam-ulrich1** [comment]
Fair. I'll tap you once I have something

**Comment by rustdesk** [comment]
👍

**Comment by sam-ulrich1** [comment]
In testing, if we drop the frames on the receiver side the cache still grows and causes an OOM since the decoding time can cause a hang and the buffer fills quickly. I'm now testing dropping the frames on the sender side linked below.

https://github.com/rustdesk/rustdesk/blob/123dccc826ba4f00a06438d9b6833315d80ed1d5/src/client/io_loop.rs#L828

One thing that needs to be investigated further is that a single frame on the decode operation can take a really long time which is actually where the issue comes. Most frames take a reasonable time and so the buffer stays within ~5 frames of current but as soon as there is a long decode operation the buffer fills and causes a giant memory spike. It might help to add some tracing to the frame handler to better understand where the large latency spike comes from.

**Comment by sam-ulrich1** [comment]
Also, I switched the stdlib channel for a crossbeam channel on the MediaSender and corresponding receiver since the stdlib channels don't have a length function. If there's another library or implementation you'd prefer I'm happy to change but for testing crossbeam is the easiest way I could thing of to get the buffer length

**Comment by sam-ulrich1** [comment]
The memory spike actually increases higher up the chain than the MediaSender channel. It appears to be buffering in the websocket. I'll have to look into it more but if I'm correct then a server-client comm about the client's buffer state would be necessary because we would have to drop frames on the server side

**Comment by rustdesk** [comment]
drop before pushing to channel / queue.

**Comment by sam-ulrich1** [comment]
Current test I'm running. Thoughts?

https://github.com/Gage-Technologies/rustdesk/blob/febb075c97b3b9fbc0ddc008d6406854cdebc5c5/src/client/io_loop.rs#LL829-L837C22

**Comment by sam-ulrich1** [comment]
I've never built cross platform on rust before. Is there a way to build the aarch64 on x86 without the Github Actions?

**Comment by rustdesk** [comment]
I have never either.

**Comment by rustdesk** [comment]
> Current test I'm running. Thoughts?
> 
> https://github.com/Gage-Technologies/rustdesk/blob/febb075c97b3b9fbc0ddc008d6406854cdebc5c5/src/client/io_loop.rs#LL829-L837C22

LGTM

**Comment by sam-ulrich1** [comment]
Update
I am still working on this but I'm tied up on a big project at work for a week or two so I don't have the free time to support but please leave open since I will finish this

**Comment by rustdesk** [comment]
close as fix merged
