### ISSUE TITLE
The controlled person's mouse is forcibly dragged to the position where the controller's mouse was before

### ISSUE THREAD

**Issue by Seamain** [rustdesk/rustdesk#3585]
### Bug Description

When my friend don't control my computer, my mouse will force to move to the previous position of the mouse. It causes me to be unable to do anything

### How to Reproduce

When contrller connects the controlled person's computer, the controlled person's move his/her mouse, it will be reproduced

### Expected Behavior

I have free control of my mouse

### Operating system(s) on local side and remote side

Windows11 Pro for Workstations 22621.1344 -> Windows11 Pro for Workstations 22621.1344

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

![](https://user-images.githubusercontent.com/92930091/224229342-40e8c541-d873-4dce-ab03-b60130b7df53.gif)

**Comment by rustdesk** [comment]
try out nightly build please on both side.

**Comment by Seamain** [comment]
This problem still exists in the nightly build

**Comment by rustdesk** [comment]
@fufesou @chiehw

**Comment by rustdesk** [comment]
Could you test again later? @Seamain

**Comment by Seamain** [comment]
Ok, I will try again later

**Comment by Seamain** [comment]
It's not work

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
The mouse movement of the controlled side has a higher priority.

I'm not sure what your problem is now:
1. The mouse cannot be moved.
2. The mouse is moved without interference, but after a while, the mouse will move to the position of the control side.

**Comment by rustdesk** [comment]
I guess the mouse is moving very slightly on controlling side (a poor mouse) though you can not sense.

**Comment by Seamain** [comment]
> The mouse movement of the controlled side has a higher priority.
> 
> I'm not sure what your problem is now:
> 1. The mouse cannot be moved.
> 2. The mouse is moved without interference, but after a while, the mouse will move to the position of the control side.

My problem is 2

**Comment by fufesou** [comment]
> The mouse is moved without interference, but after a while, the mouse will move to the position of the control side.

> I guess the mouse is moving very slightly on controlling side (a poor mouse) though you can not sense.

@Seamain You may need to check if your mouse on the controlling side.

**Comment by Seamain** [comment]
The problem was solved when I and my friend all turned on the display of the remote cursor

**Comment by rustdesk** [comment]
This PR https://github.com/rustdesk/rustdesk/pull/3600 is for you not turning on "remote cursor".
