### ISSUE TITLE
Unable to connect to ubuntu with dummy display. (Ver 1.2.0)

### ISSUE THREAD

**Issue by j7b3y** [rustdesk/rustdesk#3592]
### Bug Description

I use Rustdesk to connect to the virtual display of the ubuntu server I usually use and to exchange files.
I had no problems with this when I was using Rustdesk 1.1.9.
I updated to nightly to try a new element.
I have been unable to connect to this device with the message "Reset by the peer".
This problem did not occur when other devices connected to each other or when this device connected to other devices.
Also, the connection to the environment without the dummy display, which was created separately, worked without any problem.
We therefore assumed that the dummy display was the cause of the problem.

1.When you try to connect, a window appears momentarily asking if the connection is possible.
2.The server status display changes momentarily to "Not ready. Please check your connection."
3.The password on the remote side is forcibly reset.

This suggests that the dummy display is causing some problem, leading to the "reset on the other side" message.

[rustdesk_rCURRENT.log](https://github.com/rustdesk/rustdesk/files/10941873/rustdesk_rCURRENT.log)

### How to Reproduce

1.Install dummy driver.
```
# apt-get install xserver-xorg xserver-xorg-video-dummy
```
2.Put the right configurations in the right places.
```
# vim /etc/X11/xorg.conf
```
The config contents are on [my gist.github.com](https://gist.github.com/j7b3y/ad33a48bad815310697d33d50badcb49#file-xorg-conf)
3.Start the virtual display with the startx command.
```
startx -- :0
```
4.Run Rustdesk
```
DISPLAY=:0 rustdesk
```

### Expected Behavior

I honestly don't know, as I didn't have this problem in 1.1.9.

### Operating system(s) on local side and remote side

Windows 11 > Ubuntu 22.04 LTS

### RustDesk Version(s) on local side and remote side

1.2.0 > 1.2.0

### Screenshots

![image](https://user-images.githubusercontent.com/80038555/224312705-d5f0f7f7-e138-4e1d-bee5-66309b95be3b.png)

**Comment by rustdesk** [comment]
@fufesou this seems a good method to solve virtual display issue on Linux.

**Comment by rustdesk** [comment]
no need to consider wayland for headless linux.

**Comment by fufesou** [comment]
@j7b3y Thanks for your feedback. I'll try to learn more on "xserver-xorg-video-dummy".

I cannot open  [your gist.github.com](https://gist.github.com/j7b3y/ad33a48bad815310697d33d50badcb49#file-xorg-conf). Could you please attach the file here.

BTW, I guess the error may be caused by account login.
I see invalid `XAUTHORITY` from the log.

> [2023-03-10 21:00:30.240818 +09:00] INFO [src/server.rs:388] XAUTHORITY=Err(NotPresent)

**Comment by rustdesk** [comment]
If 1.1.9 can see the correct xauthority, we need to check our code again.

**Comment by j7b3y** [comment]
excuse me.
I have uploaded the file.
I'm out of town right now, so I'll check later.
[xorg.conf.txt](https://github.com/rustdesk/rustdesk/files/10948665/xorg.conf.txt)

**Comment by rustdesk** [comment]
@fufesou is this fixed?

**Comment by fufesou** [comment]
This PR may fix this issue. 
 https://github.com/rustdesk/rustdesk/pull/3855


I didn't test the same case.
I've tested starting an xrdp session. Rustdesk connection can be established.
They should be the same behavior.

I'm out of home. I'll test the same case later.

**Comment by rustdesk** [comment]
@j7b3y can you try out?
