### ISSUE TITLE
Unable to install on debian 12 testing

### ISSUE THREAD

**Issue by mjnck** [rustdesk/rustdesk#3599]
### Bug Description

rustdesk should require pulseaudio OR pipewire (pipewire-pulse?) now it cannot be installed on pipewire distros

### How to Reproduce

apt install ./rustdesk.deb

### Expected Behavior

rustdesk should install

### Operating system(s) on local side and remote side

Debian 12

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 rustdesk : Depends: pulseaudio
E: Unable to correct problems, you have held broken packages.

```

**Comment by rustdesk** [comment]
Removed in master.
