### ISSUE TITLE
Merge the display toggle with the display "icons"

### ISSUE THREAD

**Issue by aolko** [rustdesk/rustdesk#36]
Why not just merge the toggle buttons with the "icons" to avoid confusion for the end user?
![image](https://user-images.githubusercontent.com/581458/118102443-7791f600-b3e1-11eb-9697-2aade2b8fba9.png)

**Comment by rustdesk** [comment]
That's because you have two. You will not think so if you have 3 or more. Yes, you are right, there should be better design to avoid confusion.

![1620897085498](https://user-images.githubusercontent.com/71636191/118104876-4845ae00-b40e-11eb-8315-15dcf3a9daa4.jpg)

**Comment by aolko** [comment]
> That's because you have two. You will not think so if you have 3 or more. Yes, you are right, there should be better design to avoid confusion.
> 
> ![1620897085498](https://user-images.githubusercontent.com/71636191/118104876-4845ae00-b40e-11eb-8315-15dcf3a9daa4.jpg)

that can actually be a toggle setting or a conditional (if displayCount >= 3), or you can go with a dropdown menu route `[switch ▾]` which displays the larger toggleable diagram
![image](https://user-images.githubusercontent.com/581458/118109010-51705400-b3e9-11eb-9e80-14996127e343.png)
