### ISSUE TITLE
How to connect to linux host?

### ISSUE THREAD

**Issue by KestutisMa** [rustdesk/rustdesk#360]
Rustdesk states it is *open-source* but I see that you need to pay (and I can't see all sources) even for non-commercial use? Did I made a mistake? If no, then  not telling truth is frustrating from client side

**Comment by rustdesk** [comment]
pay for what?

**Comment by KestutisMa** [comment]
To be able to use remote desktop server?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server
