### ISSUE TITLE
Always dark theme when using Follow System on macOS

### ISSUE THREAD

**Issue by rakleed** [rustdesk/rustdesk#3609]
### Bug Description

Always dark theme when using Follow System in Theme settings on macOS.

### How to Reproduce

1. Go to macOS settings and enable Light theme
2. Go to RustDesk settings and enable Follow System theme

### Expected Behavior

The theme in RustDesk matches the macOS theme when using the Follow System theme.

### Operating system(s) on local side and remote side

macOS 13 → Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0 nightly

### Screenshots

![Screenshot 2023-03-11 at 16 16 08](https://user-images.githubusercontent.com/19418601/224486750-76d33d76-9773-4f15-8c40-2aeb0b8620e4.png)
![Screenshot 2023-03-11 at 16 16 29](https://user-images.githubusercontent.com/19418601/224486770-132e1364-a89b-4da9-aaf4-aa47c549c4f6.png)

**Comment by rustdesk** [comment]
@grummbeer it seems you mentioned this before.

**Comment by grummbeer** [comment]
yes https://github.com/rustdesk/rustdesk/issues/3496

Some confusion with "Brightness" in colorScheme? This point got some changes add/remove/add again/remove again/changed. Later on the issue was gone, so i closed it.

As the screenshot shows, macOS Theme "auto" is not "dark" and not "light"? Fallback to "dark"?

No clue, tested on mobile and linux, both work as expected … but all in debug mode, needs to tested with release/nightly donwload.

**Comment by grummbeer** [comment]
@rakleed how old is the nighly you use?

**Comment by rustdesk** [comment]
> 1. Go to macOS settings and enable Light theme

light or auto (on your picture)?

**Comment by rakleed** [comment]
I have installed the latest nightly from 2023-03-11 00:18.

In general, I have always had the Auto theme in my system. I thought it would be the same with Light, but now I installed Light, returned Auto, and everything is displayed correctly.

Perhaps there will be problems when the theme automatically changes in the system. Can you keep the issue open for now? I'll write in a couple of days if I managed to reproduce the problem.

**Comment by rustdesk** [comment]
I think the better to report is flutter repo, the theme is decided by flutter engine.

https://github.com/rustdesk/rustdesk/blob/13e18728d3f43ad54eb62dad09a93f733f8fda0d/flutter/lib/main.dart#L271


https://github.com/flutter/flutter/blob/f9ad42a32d7e116f321569ec118416f981806151/packages/flutter/lib/src/material/app.dart#L45

**Comment by rakleed** [comment]
@rustdesk @grummbeer I have updated the How to reproduce section. Can you try now? Could it be that when I launch RustDesk you don't check what the current theme is on the system in this particular case?

And in order to report a bug in Flutter, I need to provide a sample code and logs, and I don't know Flutter at all, so I can't do it.
