### ISSUE TITLE
Enter no longer works from android [Gnome Login Screen] (samsung keyboard)

### ISSUE THREAD

**Issue by NicKoehler** [rustdesk/rustdesk#3611]
### Bug Description

I used to login from my phone into my desktop, enter doesn't work android -> gnome shell

### How to Reproduce

Try to login from android

### Expected Behavior

When pressing enter login

### Operating system(s) on local side and remote side

Android -> Linux

### RustDesk Version(s) on local side and remote side

Nighly

### Screenshots

![Screenshot_20230311_174728](https://user-images.githubusercontent.com/53040044/224497230-444391a0-0a11-432b-b0f5-0da234c062a8.jpg)

### Additional Context

I dont know when this stopped working but it was working on february

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by rustdesk** [comment]
> I dont know when this stopped working but it was working on february

Before, you used what keyboard?

**Comment by NicKoehler** [comment]
Yes, I changed it now for debugging purpose

**Comment by rustdesk** [comment]
I did test different keyboards (but no samsung)  before, it may cause different behaviors. This seems a bug specific to some keyboards.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3893
