### ISSUE TITLE
Client using wrong port to server using IPv6

### ISSUE THREAD

**Issue by tuxmainy** [rustdesk/rustdesk#3622]
### Bug Description

Hi,
when connecting to my rustdesk server by IPv4 (DNS or IP given, does not matter) everything is fine. But using the same server and client with IPv6 fails: orange LED on the bottom of rustdesk client saying it tries to connect but can't.

Looking with tcpdump I noticed that the rustdesk client (on Ubuntu) was using port 443 instead of port 21116 when using IPv6 while the client uses port 21116 when using IPv4. The rustdesk server is only available on 21116 thus the IPv6 requests are failing.

I am wondering about this to be a "tuxmainy problem" but I cannot imagine what I could have done wrong. The problem is _always_ reproducible by switching between IPv4 and IPv6.

Can someone confirm?

regards
Daniel

### How to Reproduce

use IPv6 (I have only tried with entering a DNS)

### Expected Behavior

should behave like using IPv4

### Operating system(s) on local side and remote side

Ubuntu 22.04.2 LTS

### RustDesk Version(s) on local side and remote side

1.1.9 -> docker rustdesk/rustdesk-server:latest

### Screenshots

![grafik](https://user-images.githubusercontent.com/27895250/224567951-2618d3fe-5c3c-4f47-8f7e-49f1a6c2513f.png)

**Comment by rustdesk** [comment]
1.1.9 does not support ipv6
