### ISSUE TITLE
Fixed width on message box 'sort by'

### ISSUE THREAD

**Issue by tsarmis** [rustdesk/rustdesk#3625]
### Bug Description

In the address book when you click the available 'sort by' options, the opening windows has fixed width and does not show (fit) correctly the translations from other languages.

Same behavior is on Favorites and Discovered tabs as well.

### How to Reproduce

Change language to something different than English, ex. Greek (Ελληνικά)
Go to address book
Click on the top right at the sort by icon, to select desired sorting

### Expected Behavior

The translations should be visible in full

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

nightly build 2023-03-12 00:24

### Screenshots

![224580223-3150a159-3f23-45bf-934a-b4e47cab0b3f](https://user-images.githubusercontent.com/126983335/224637504-65f3faf9-8a08-49c3-a4eb-177c1752b1b4.png)

**Comment by rustdesk** [comment]
@NicKoehler

**Comment by rustdesk** [comment]
close as fix merged
