### ISSUE TITLE
Linux - RD ignores toml, tries to overwrite it on every software launch

### ISSUE THREAD

**Issue by working-name** [rustdesk/rustdesk#3637]
### Bug Description

I am trying to change the station ID on a station running kubuntu 22.10, and so I've put in my desired ID in `/root/.config/rustdesk/RustDesk.toml` which of course doesn't work. I had a sneaking suspicion you're overwriting it, so I made it immutable.

Now when rustdesk starts as a regular user, it creates a `/home/user/.config/rustdesk/RustDesk_pid_ThreadId(1)_timestamp.toml` which of course is generated by RD. So therefore I ask myself: wtf is the point of a config file if you're going to overwrite it at every damn startup? Might as well rely on hardcoded values. Anyway, I digress.

### How to Reproduce

Install rustdesk latest nightly. Edit the config to change ID. Marvel at the audacity of this software to do whatever it wants to.

### Expected Behavior

RustDesk should **not** ignore my config changes, and it should not be generating its own random config file name when it cannot "write" an existing file. Just read it. Don't like what's in it? Puke an error message, but don't bypass the user. What a ridiculous behavior.

### Operating system(s) on local side and remote side

kubuntu 22.10

### RustDesk Version(s) on local side and remote side

1.2.0 (2023-03-13 00:35)

### Screenshots

I'll do this when I figure out a software to do a screen recording.

**Comment by rustdesk** [comment]
close to favor #3092

**Comment by rustdesk** [comment]
Sorry， yes.
