### ISSUE TITLE
Web view

### ISSUE THREAD

**Issue by kpetrow** [rustdesk/rustdesk#364]
I am in process of looking for a replacement to vnc.  One vnc feature that is used often is a NOvnc/websocket implementation for in browser viewing and screen control.  Is this implemented in rustDesk?  Are there any ports using webAssembly? 
Thanks. This project looks great.

**Comment by rustdesk** [comment]
Not yet, but in to-do list

**Comment by rustdesk** [comment]
Flutter (UI) + JS (Communication + Decode)
https://github.com/jedisct1/libsodium.js/
https://pub.dev/packages/isolated_worker https://github.com/iandis/flutter_isolated_worker_fetch_example
https://gpalma.pt/blog/flutter-web-web-assembly/ https://github.com/Vanethos/rust-wasm-example-rsa

**Comment by open-trade** [comment]
Uploading video_20220121_144221.mp4…

**Comment by rustdesk** [comment]
https://user-images.githubusercontent.com/71636191/150481486-186c0831-f74f-4b38-9182-c0a3ab6abbea.mp4

**Comment by rustdesk** [comment]
https://chromium.googlesource.com/libyuv/libyuv

`emcc -Os -s STANDALONE_WASM -s EXPORTED_FUNCTIONS="['_free', '_malloc', '_I420ToABGR']" -Wl,--no-entry "./source/convert_argb.cc" source/row_common.cc -o "yuv.wasm" -I include/`

avg 20 ms

**Comment by rustdesk** [comment]
https://github.com/GoogleChromeLabs/wasm-av1

`AVX_YUV_to_RGB(unsigned char *dst, unsigned char* y, unsigned char* u, unsigned char* v, int width, int height) `

`emcc -Os -s STANDALONE_WASM -s EXPORTED_FUNCTIONS="['_AVX_YUV_to_RGB', '_free', '_malloc']" -Wl,--no-entry "yuv-to-rgb.c" -o "yuv.wasm"`

avg 12ms on my old i5 pc.

**Comment by rustdesk** [comment]
https://github.com/descampsa/yuv2rgb

emcc -Os -s STANDALONE_WASM -s EXPORTED_FUNCTIONS="['_free', '_malloc', '_yuv420_rgb24_std']" -Wl,--no-entry  -o "yuv.wasm" yuv_rgb.c 

avg 14ms on my old i5 pc.

**Comment by rustdesk** [comment]
Speed up wasm with simd: https://emscripten.org/docs/porting/simd.html

**Comment by rustdesk** [comment]
ogvjs slow,
maybe we can use <video> to play webm.

https://github.com/webrtc/samples/blob/gh-pages/src/content/capture/video-pc/index.html

**Comment by rustdesk** [comment]
opus pre-skip: https://datatracker.ietf.org/doc/html/rfc7845#section-4.2

**Comment by rustdesk** [comment]
Tried webgl, but copy data from webgl out is slow.

`let yuvWorker;
let yuvCanvas;
let gl;
let pixels;
if (YUVCanvas.WebGLFrameSink.isAvailable()) {
  var canvas = document.createElement('canvas');
  yuvCanvas = YUVCanvas.attach(canvas, { webGL: true });
  gl = canvas.getContext("webgl");
} else {
  yuvWorker = new Worker("./yuv.js");
}

export function draw(frame) {
  if (yuvWorker) {
    // frame's (y/u/v).bytes already detached, can not transferrable any more.
    yuvWorker.postMessage(frame);
  } else {
    var now = new Date().getTime();
    yuvCanvas.drawFrame(frame);
    console.log(new Date().getTime() - now);
    now = new Date().getTime();
    if (!pixels) pixels = new Uint8Array(canvas.width * canvas.height * 4);
    gl.readPixels(0, 0, canvas.width, canvas.height, gl.RGBA, gl.UNSIGNED_BYTE, pixels);
    console.log(new Date().getTime() - now);
  }
}`

drawFrame is 1ms,
but readPixels takes 30ms for 720p.
