### ISSUE TITLE
Build fail for web target 

### ISSUE THREAD

**Issue by hdcos** [rustdesk/rustdesk#3645]
### Bug Description

We followed the build steps for linux and build steps for the web client but running `flutter run -d chrome` gives us errors.

Running the linux client works but the web fails.
We can make a connection to the remote when using only vitejs. But it fails because apparently we need to run through `flutter run -d chrome` and this part fails.
Seems like the problem comes from the dart ffi and win32 even though we are compiling on ubuntu.

Platform : 
- ubuntu 22.04
- all dependencies installed (flutter, vcpkgs, webdeps etc)

Also there is a problem when decompressing the files for web it should be done inside the js folder and not in the web folder other wise index html can't find the web deps.
Also protoc does not compile the boolean `retry_for_relay` and tsc raises an exception.

### How to Reproduce

Just follow the documentation for building for the web on ubuntu, it should fail normally.

### Expected Behavior

Following the documentation should work.

### Operating system(s) on local side and remote side

ubuntu 22.04 LTS

### RustDesk Version(s) on local side and remote side

master

### Screenshots

![image](https://user-images.githubusercontent.com/6699550/224980725-f5114e33-1a25-44f8-894b-d38060af8db4.png)

**Comment by hdcos** [comment]
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:87:16:
Error: Only JS interop members may be 'external'.
  external int cVal;
               ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:89:16:
Error: Only JS interop members may be 'external'.
  external int uiVal;
               ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:91:16:
Error: Only JS interop members may be 'external'.
  external int ulVal;
               ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:93:16:
Error: Only JS interop members may be 'external'.
  external int ullVal;
               ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:95:16:
Error: Only JS interop members may be 'external'.
  external int intVal;
               ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:97:16:
Error: Only JS interop members may be 'external'.
  external int uintVal;
               ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:98:29:
Error: Only JS interop members may be 'external'.
  external Pointer<DECIMAL> pdecVal;
                            ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:99:26:
Error: Only JS interop members may be 'external'.
  external Pointer<Int8> pcVal;
                         ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:100:28:
Error: Only JS interop members may be 'external'.
  external Pointer<Uint16> puiVal;
                           ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:101:28:
Error: Only JS interop members may be 'external'.
  external Pointer<Uint32> pulVal;
                           ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:102:28:
Error: Only JS interop members may be 'external'.
  external Pointer<Uint64> pullVal;
                           ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:103:27:
Error: Only JS interop members may be 'external'.
  external Pointer<Int32> pintVal;
                          ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:104:28:
Error: Only JS interop members may be 'external'.
  external Pointer<Uint32> puintVal;
                           ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:105:33:
Error: Only JS interop members may be 'external'.
  external _VARIANT_Anonymous_3 __VARIANT_NAME_4;
                                ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:110:16:
Error: Only JS interop members may be 'external'.
  external int vt;
               ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:112:16:
Error: Only JS interop members may be 'external'.
  external int wReserved1;
               ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:114:16:
Error: Only JS interop members may be 'external'.
  external int wReserved2;
               ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:116:16:
Error: Only JS interop members may be 'external'.
  external int wReserved3;
               ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:117:33:
Error: Only JS interop members may be 'external'.
  external _VARIANT_Anonymous_2 __VARIANT_NAME_3;
                                ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:121:33:
Error: Only JS interop members may be 'external'.
  external _VARIANT_Anonymous_1 __VARIANT_NAME_2;
                                ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:122:20:
Error: Only JS interop members may be 'external'.
  external DECIMAL decVal;
                   ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:133:33:
Error: Only JS interop members may be 'external'.
  external _VARIANT_Anonymous_0 __VARIANT_NAME_1;
                                ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:408:16:
Error: Only JS interop members may be 'external'.
  external int vt;
               ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:410:16:
Error: Only JS interop members may be 'external'.
  external int wReserved1;
               ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:412:16:
Error: Only JS interop members may be 'external'.
  external int wReserved2;
               ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:414:16:
Error: Only JS interop members may be 'external'.
  external int wReserved3;
               ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:416:16:
Error: Only JS interop members may be 'external'.
  external int val1;
               ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/variant.dart:418:16:
Error: Only JS interop members may be 'external'.
  external int val2;
               ^
../../../../.pub-cache/hosted/pub.dev/win32-3.1.3/lib/src/combase.dart:24:37:
Error: Only JS interop members may be 'external'.
  external Pointer<Pointer<IntPtr>> lpVtbl;
                                    ^
Error: Compilation failed.


#0      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:225:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
<asynchronous suspension>
#7      buildWeb (package:flutter_tools/src/web/compile.dart:53:32)
<asynchronous suspension>
#8      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:135:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             28.3s
Exception: Failed to compile application for the Web.

**Comment by rustdesk** [comment]
#763

**Comment by TBG-FR** [comment]
@hdcos If you build with docker and output the log to a file, you can actually see the "real" error log (before all the generated lines with `Error: Only JS interop members may be 'external'.`)

```
#24 951.4 Target dart2js failed: ProcessException: Process exited abnormally:
#24 951.4 lib/generated_bridge.dart:12:8:
#24 951.4 Error: Dart library 'dart:ffi' is not available on this platform.
#24 951.4 import 'dart:ffi' as ffi;
#24 951.4        ^
#24 951.4 Info: The unavailable library 'dart:ffi' is imported through these packages:
#24 951.4 
#24 951.4     main.dart => package:flutter_hbb => dart:ffi
#24 951.4     main.dart => package:flutter_hbb => package:texture_rgba_renderer => dart:ffi
#24 951.4     main.dart => package:flutter_hbb => package:win32 => dart:ffi
#24 951.4     main.dart => package:flutter_hbb => package:win32 => package:ffi => dart:ffi
#24 951.4     ...
#24 951.4 
#24 951.4 Detailed import paths for (some of) the these imports:
#24 951.4 
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/ab_model.dart => package:flutter_hbb/common/widgets/peers_view.dart => package:flutter_hbb/models/peer_tab_model.dart => package:flutter_hbb/models/peer_model.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/ab_model.dart => package:flutter_hbb/common/widgets/peers_view.dart => package:flutter_hbb/models/peer_tab_model.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/ab_model.dart => package:flutter_hbb/common/widgets/peers_view.dart => package:flutter_hbb/models/peer_model.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/ab_model.dart => package:flutter_hbb/common/widgets/peers_view.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/ab_model.dart => package:flutter_hbb/common/widgets/peers_view.dart => package:flutter_hbb/common/widgets/peer_card.dart => package:flutter_hbb/common/widgets/dialog.dart => package:flutter_hbb/common/widgets/setting_widgets.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/ab_model.dart => package:flutter_hbb/common/widgets/peers_view.dart => package:flutter_hbb/common/widgets/peer_card.dart => package:flutter_hbb/common/widgets/dialog.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/ab_model.dart => package:flutter_hbb/common/widgets/peers_view.dart => package:flutter_hbb/common/widgets/peer_card.dart => package:flutter_hbb/common/widgets/dialog.dart => package:flutter_hbb/common/widgets/address_book.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/ab_model.dart => package:flutter_hbb/common/widgets/peers_view.dart => package:flutter_hbb/common/widgets/peer_card.dart => package:flutter_hbb/common/widgets/dialog.dart => package:flutter_hbb/common/widgets/address_book.dart => package:flutter_hbb/common/widgets/login.dart => package:flutter_hbb/common/hbbs/hbbs.dart => package:flutter_hbb/models/peer_model.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/ab_model.dart => package:flutter_hbb/common/widgets/peers_view.dart => package:flutter_hbb/common/widgets/peer_card.dart => package:flutter_hbb/common/widgets/dialog.dart => package:flutter_hbb/common/widgets/address_book.dart => package:flutter_hbb/common/widgets/login.dart => package:flutter_hbb/common/hbbs/hbbs.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/ab_model.dart => package:flutter_hbb/common/widgets/peers_view.dart => package:flutter_hbb/common/widgets/peer_card.dart => package:flutter_hbb/common/widgets/dialog.dart => package:flutter_hbb/common/widgets/address_book.dart => package:flutter_hbb/common/widgets/login.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/ab_model.dart => package:flutter_hbb/common/widgets/peers_view.dart => package:flutter_hbb/common/widgets/peer_card.dart => package:flutter_hbb/common/widgets/dialog.dart => package:flutter_hbb/common/widgets/address_book.dart => package:flutter_hbb/common/widgets/login.dart => package:flutter_hbb/models/user_model.dart => package:flutter_hbb/common/hbbs/hbbs.dart => package:flutter_hbb/models/peer_model.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/ab_model.dart => package:flutter_hbb/common/widgets/peers_view.dart => package:flutter_hbb/common/widgets/peer_card.dart => package:flutter_hbb/common/widgets/dialog.dart => package:flutter_hbb/common/widgets/address_book.dart => package:flutter_hbb/common/widgets/login.dart => package:flutter_hbb/models/user_model.dart => package:flutter_hbb/common/hbbs/hbbs.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/ab_model.dart => package:flutter_hbb/common/widgets/peers_view.dart => package:flutter_hbb/common/widgets/peer_card.dart => package:flutter_hbb/common/widgets/dialog.dart => package:flutter_hbb/common/widgets/address_book.dart => package:flutter_hbb/common/widgets/login.dart => package:flutter_hbb/models/user_model.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/ab_model.dart => package:flutter_hbb/common/widgets/peers_view.dart => package:flutter_hbb/common/widgets/peer_card.dart => package:flutter_hbb/models/peer_tab_model.dart => package:flutter_hbb/models/peer_model.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/ab_model.dart => package:flutter_hbb/common/widgets/peers_view.dart => package:flutter_hbb/common/widgets/peer_card.dart => package:flutter_hbb/models/peer_tab_model.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/ab_model.dart => package:flutter_hbb/common/widgets/peers_view.dart => package:flutter_hbb/common/widgets/peer_card.dart => package:flutter_hbb/models/peer_model.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/ab_model.dart => package:flutter_hbb/common/widgets/peers_view.dart => package:flutter_hbb/common/widgets/peer_card.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/ab_model.dart => package:flutter_hbb/models/peer_model.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/ab_model.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     main.dart => package:flutter_hbb/main.dart => package:flutter_hbb/models/state_model.dart => package:flutter_hbb/common.dart => package:flutter_hbb/models/desktop_render_texture.dart => package:flutter_hbb/models/model.dart => package:flutter_hbb/models/chat_model.dart => package:flutter_hbb/desktop/widgets/tabbar_widget.dart => package:flutter_hbb/desktop/pages/remote_page.dart => package:flutter_hbb/common/widgets/overlay.dart => package:flutter_hbb/common/widgets/chat_page.dart => package:flutter_hbb/mobile/pages/home_page.dart => package:flutter_hbb/mobile/pages/server_page.dart => package:flutter_hbb/mobile/widgets/dialog.dart => package:flutter_hbb/common/widgets/setting_widgets.dart => package:flutter_hbb/models/platform_model.dart => package:flutter_hbb/generated_bridge.dart => dart:ffi
#24 951.4     ...
#24 951.4 
#24 951.4 /home/user/.pub-cache/hosted/pub.dev/ffi-2.1.0/lib/src/allocation.dart:5:8:
#24 951.4 Error: Dart library 'dart:ffi' is not available on this platform.
#24 951.4 import 'dart:ffi';
#24 951.4        ^
#24 951.4 /home/user/.pub-cache/hosted/pub.dev/ffi-2.1.0/lib/src/arena.dart:8:8:
#24 951.4 Error: Dart library 'dart:ffi' is not available on this platform.
#24 951.4 import 'dart:ffi';
#24 951.4        ^
#24 951.4 /home/user/.pub-cache/hosted/pub.dev/ffi-2.1.0/lib/src/utf8.dart:6:8:
#24 951.4 Error: Dart library 'dart:ffi' is not available on this platform.
#24 951.4 import 'dart:ffi';
#24 951.4        ^
```
