### ISSUE TITLE
Active Directory user for elevation request does not work

### ISSUE THREAD

**Issue by shmsh9** [rustdesk/rustdesk#3648]
### Bug Description

Hello all,

First thank you for this amazing program.
Second : when you try to request elevation and use an active directory account it does not work.

I patched this to pass the domain to the CreateProcessWithLogonW function : 

```
diff --git a/src/platform/windows.rs b/src/platform/windows.rs
index 696a18ab..7fce4666 100644
--- a/src/platform/windows.rs
+++ b/src/platform/windows.rs
@@ -1763,8 +1763,9 @@ pub fn send_message_to_hnwd(

 pub fn create_process_with_logon(user: &str, pwd: &str, exe: &str, arg: &str) -> ResultType<()> {
     unsafe {
-        let wuser = wide_string(user);
-        let wpc = wide_string("");
+        let user_split = user.split("\\").collect::<Vec<&str>>();
+        let wuser = wide_string(user_split.get(1).unwrap_or(&user));
+        let wpc = wide_string(user_split.get(0).unwrap_or(&""));       
         let wpwd = wide_string(pwd);
         let cmd = if arg.is_empty() {
             format!("\"{}\"", exe)
```

Still not working GetLastError() returns 0x5 which seems to be [ERROR_ACCESS_DENIED ](https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-)

### How to Reproduce

Initiate a remote session and ask for elevation with credentials passing : 
![image](https://user-images.githubusercontent.com/16268716/225048822-ed91fa62-85e8-4775-bc40-5b9cd8d714fe.png)

### Expected Behavior

The process should be able to elevate itself

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

master branch commit d3430e4b69cb4145a12598fdcc58642ad4302c28

### Screenshots

![image](https://user-images.githubusercontent.com/16268716/225049238-4df8e1e7-fd9a-4d67-9f39-803705991df3.png)

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
BTW, @grummbeer 

- [ ] the two editbox together seems not look good.
- [ ]  The placehold `eg. admin` has no padding around.
- [ ] Do you plan to change the buttons right aligned?

> ![image](https://user-images.githubusercontent.com/16268716/225048822-ed91fa62-85e8-4775-bc40-5b9cd8d714fe.png)

**Comment by grummbeer** [comment]
@rustdesk agree on all points.

- 3x yes
- 1x yes, second sceenshot look fine
- plus darkmode dialogs too much dark in dark, low contrast > bad UX

**Comment by shmsh9** [comment]
@rustdesk of course I will try to make it work !

**Comment by rustdesk** [comment]
> @rustdesk of course I will try to make it work !

Great. Let us know if you need any help.

**Comment by shmsh9** [comment]
@rustdesk Ok I made some progress : 

Self-elevation works when `create_process_with_logon()` launch a binary that then call `run_uac()` (I just copied the 2 functions on a separate project)
I just don't understand what gets called when I press the submit button I got lost at : 
`bind.sessionElevateWithLogon()` in flutter/lib/mobile/widgets/dialog.dart

**Comment by 21pages** [comment]
It called https://github.com/rustdesk/rustdesk/blob/09c2fc9d7d952a8aee6e5c3723c3b19b0f25fbd5/src/flutter_ffi.rs#L521 in rust, and  client send request to remote, remote handle message at https://github.com/rustdesk/rustdesk/blob/09c2fc9d7d952a8aee6e5c3723c3b19b0f25fbd5/src/server/connection.rs#L1578, then it will call `CreateProcessWithLogonW`, run a new admin process which can elevate without UAC

**Comment by shmsh9** [comment]
@21pages 

Thanks !
I found the issue : 
`set_path_permission()` does nothing on C:\Users\%USERNAME%\AppData\Local\rustdesk If I manually add the rights the elevation works !
Do you know an easy way to make the program output debug ? println!() does nothing the process seems to have no stdout attached.

**Comment by 21pages** [comment]
> set_path_permission() does nothing
It's a problem.

It'll log to `C:\Users\<yourname>\AppData\Roaming\RustDesk\log` on release build , you can change the marco to make it log on debug. Remember use something like `log::info!`.
https://github.com/rustdesk/rustdesk/blob/09c2fc9d7d952a8aee6e5c3723c3b19b0f25fbd5/libs/hbb_common/src/lib.rs#L316

If this doesn't work, you can write to file manually.
```
pub fn flog(s: &str) {
    use hbb_common::chrono::prelude::*;
    use std::io::Write;
    let mut option = std::fs::OpenOptions::new();
    if let Ok(mut f) = option.append(true).create(true).open("D:/tmp/log.txt") {
        write!(&mut f, "{:?} {}\n", Local::now(), s).ok();
    }
}
```

**Comment by shmsh9** [comment]
Thank you ! I found the issue and will do a pull request : 
I tested on a french and a german windows install icacls Everyone does not work but changing by the SID of everyone does (*S-1-1-0)

**Comment by 21pages** [comment]
Great!

**Comment by shmsh9** [comment]
#3699

**Comment by rustdesk** [comment]
@shmsh9 does #3699 solve this? I just got from discord.

![image](https://user-images.githubusercontent.com/71636191/225957685-1f5b94da-3796-41b1-b48a-3d46a79d1118.png)

**Comment by shmsh9** [comment]
@rustdesk It probably does if his windows install is not in english

**Comment by rustdesk** [comment]
👍
