### ISSUE TITLE
Screen flickers. Screen resolution. Wayland detected when only X is installed

### ISSUE THREAD

**Issue by GogoFC** [rustdesk/rustdesk#3651]
### Bug Description

Full resolution not available.
Rustdesk thinks Wayland is running, it isn't. 
Screen flickers every 15 seconds or so.

### How to Reproduce

My Ubuntu 22 runs on XCP-ng
Server ISO.
Installed gnome-session and gnome-terminal
Installed Xrdp 
Logged in via RDP via Remmina using resolution 1920x1080
Installed Rustdesk everything worked fine, I got full resolution.
Rebooted and Rustdesk said Wayland is running. It wasn't as only Xorg is installed and GNOME detects X and also Xrdp works over X.
I edited the gdm3 config to wayland=false
Rustdesk now works and can get to the gdm3 login screen, but the resolution is nowhere near 1080. It maxes out at 768. And the screen flickers all the time.

### Expected Behavior

Expected no flickering and full resolution

### Operating system(s) on local side and remote side

Fedora --> Ubuntu

### RustDesk Version(s) on local side and remote side

1.2.0 --> 1.1.9

### Screenshots

![Screenshot from 2023-03-14 16-39-47](https://user-images.githubusercontent.com/9360410/225071909-9769d50f-d032-461e-a445-6ff404d7bb9b.png)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1053
