### ISSUE TITLE
Disable Local Input (view mode)

### ISSUE THREAD

**Issue by fragtion** [rustdesk/rustdesk#3652]
### Description

Hello!

I have a fairly simple request, which is to have the option to "Disable local input" ... In other words, when the option is enabled, the connecting side won't interfere with the remote input, but is essentially "Viewer Only" mode, similar to "Block user input" and should probably appear under the same menu. However, it would be nice if this option could be persistent when it is set for a given host, so that when reconnecting to that host, it will automatically be remembered/applied, until manually untoggled again.

It would be great to see this possibility further enhance the already rich featureset that RustDesk has to offer! Thanks for the continued great work on this awesome project.

### Impact

Consider a scenario where you need to connect to a remote system to be on "standby" support, but you don't want to accidentally move the mouse or click something while you're not supposed to (another operator is physically at the site).

Another case could be where you connect to a remote rustdesk session where the person at the remote computer believes you are interfering with their mouse movement. In that case you could assure them that you have completely disabled input, so its not possible to interfere with their mouse. At the moment, this is not possible from what I can see.

### Additional Context

It is possible using alternative solutions such as Moonlight streaming which I also use (CTRL+ALT+SHIFT+Z hotkey)... but RustDesk has improved immensely in recent months, to the point where I prefer to use RustDesk for remote desktop support in most cases, as it offers more bandwidth adjustment & codec flexibility amongst other things.

**Comment by rustdesk** [comment]
Do you mean this https://github.com/rustdesk/rustdesk/discussions/2755?

**Comment by rustdesk** [comment]
@fernandeusto @lm93129 Where is the `view mode` switch in the other remote desktop tool?

**Comment by fragtion** [comment]
> 
Yes! Sorry, I tried to search for "block input" and didn't find similar issue, but forgot to check discussions. Excited to see there are implementation plans and looking forward to the improvements  :)

**Comment by rustdesk** [comment]
@21pages disable keyboard and clipboard together. No idea how to represent on GUI yet (I prefer to put it under keyboard button on menubar). Check out if anydesk / teamviewer have this.

**Comment by fernandeusto** [comment]
I think the most comfortable thing would be to add a button to toggle between view mode and control mode on the toolbar.
![image](https://user-images.githubusercontent.com/87156183/225111559-20fd2d69-74d4-4b7d-b3a4-ff82b8c2bb35.png)

On the other hand, in the client configuration options, add a "default display option when connecting", that is, the way in which the connection starts when connecting, with a selectbox with "view mode" and "control mode"
![image](https://user-images.githubusercontent.com/87156183/225112827-4d3ee9af-da0e-4c55-b742-d5f6fb14489e.png)


Logically, if the default keyboard/mouse is disabled in the client configuration, then the toolbar button to toggle between modes will not be active or visible.

**Comment by fragtion** [comment]
If there's a "default option when connecting", no reason why there can't still be an option to toggle while in a session too, using the button :)

**Comment by fernandeusto** [comment]
This is an example of another payment software that I used many years ago and that had that option to change the mode easily.
![image](https://user-images.githubusercontent.com/87156183/225138253-016f1ddd-7611-490d-ad42-2dae541d3c2e.png)
https://youtu.be/-lBWs2KHLk0?t=298

**Comment by lm93129** [comment]
![image](https://user-images.githubusercontent.com/22451712/225176037-0aabd228-605e-4f39-a52c-d6ea48710de2.png)
![image](https://user-images.githubusercontent.com/22451712/225176675-ef764e80-5dba-4183-be26-47c8f278c965.png)
Similar software is shown in the figure. There is a choice of viewing mode on the panel of the target server. After remote control, you can select the control mode somewhere.

**Comment by rustdesk** [comment]
Thanks to all.

**Comment by rustdesk** [comment]
Please test later, nightly build will be ready soon.

**Comment by fernandeusto** [comment]
I have activated the default option "view mode" on the client side, but when I connect to it, it returns to the last mode before disconnecting and not to the default option, therefore the "default view mode" option of the config does not is working.
the Switch to activate the "view mode" in the toolbar works correctly

Thank you for your development

De: RustDesk
Enviado: jueves, 16 de marzo de 2023 8:05
Para: rustdesk/rustdesk
CC: fernandeusto; Mention
Asunto: Re: [rustdesk/rustdesk] Disable Local Input (view mode) (Issue #3652)

Please test later, nightly build will be ready soon.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/rustdesk/rustdesk/issues/3652#issuecomment-1471423572", "url": "https://github.com/rustdesk/rustdesk/issues/3652#issuecomment-1471423572", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by rustdesk** [comment]
> "default view mode"

That's how it works.

**Comment by 21pages** [comment]
`Default option` works at first connection, delete peer card at recent sessions, and it'll works.

**Comment by fragtion** [comment]
Why disable remote cursor in view mode? It would be more helpful to view the remote cursor (or at least keep the option to toggle this still, in view mode). Unless I'm missing something. thoughts? :)

**Comment by 21pages** [comment]
> Why disable remote cursor visibility in view mode?

Always show remote cursor, only hide the `Show remote cursor` checkbox.

**Comment by 21pages** [comment]
Thanks for your feedback.
> always enters with the default mode

reproduced
> connect in control mode again.

not reproduced but similar problem

**Comment by 21pages** [comment]
It should have been fixed and the option is moved under keyboard.
![image](https://user-images.githubusercontent.com/14891774/225809319-13b1a1fb-a91b-4aec-9ca4-379cee75c789.png)

**Comment by fernandeusto** [comment]
The "view mode" option is fine like this under the keyboard

But it not work

Maybe the problem is that it uses the default option on the control side instead of the one on the client side.:
https://github.com/rustdesk/rustdesk/issues/3704#issuecomment-1474539139

**Comment by fragtion** [comment]
It works but the remote/server side must also be running the patches/nightly version as the viewer mode functionality is implemented also in the serverside code

**Comment by fragtion** [comment]
I tried to make peer file (eg C:\Users\Administrator\AppData\Roaming\RustDesk\config\peers\192.168.0.1.toml) read-only, so that it will always enter view mode by default for that peer. However, RustDesk then starts to create garbage files in the peers directory, as follows:
192.168.0.1.6548_ThreadId(48)_1679484681599138000
192.168.0.1.6548_ThreadId(48)_1679484667651423600
192.168.0.1.6548_ThreadId(14)_1679484677578430700
Can we avoid creation of these files if the peers file is read-only? it should just silently continue even if it can't write new changes. Then we can make peers file read-only when we are happy with a default configuration set for that peer... Until it's possible to ever set persistent default presets per-host

**Comment by FloMaetschke** [comment]
@rustdesk its mid 2025, is there some kind of  remote pointer-mode available now? (a second/third, fourth... cursor in different colors showing the remote client name?
