### ISSUE TITLE
Nightly support for arm 32bit?

### ISSUE THREAD

**Issue by fragtion** [rustdesk/rustdesk#3653]
### Bug Description

The nightly apk failed to install on my Galaxy S5 running LineageOS v19, but F-Droid version worked fine. Is it possible to add support for these devices to the build script as well?

### How to Reproduce

Try to install the nightly apk on an arm 32 bit Android device

### Expected Behavior

It should work just as the official release does

### Operating system(s) on local side and remote side

Android 12

### RustDesk Version(s) on local side and remote side

nightly

### Screenshots

none unless requested

**Comment by rustdesk** [comment]
Low priority, but if you can not wait, you can do it yourself, https://github.com/rustdesk/rustdesk/blob/master/.github/workflows/flutter-nightly.yml, no hard.

**Comment by fragtion** [comment]
Yeah I tried to fork and build myself but something went wrong with dependencies and then I thought "Why going through this struggle if it's a simple fix to add the flag to the nightly build so others don't face the same problem" which is why I decided it would be worth it to log the issue. But I understand it's a low priority. Thank you for your consideration :)

**Comment by rustdesk** [comment]
added
