### ISSUE TITLE
Virtualbox can't receive keyboard linux -> win10

### ISSUE THREAD

**Issue by nigelsim** [rustdesk/rustdesk#366]
**Describe the bug you encountered:**

When I connect from Linux to Windows 10 the keyboard works in some apps, like notepad, but not in Virtualbox. Using Virtualbox locally or via TeamViewer works as expected.

**What did you expect to happen instead?**

Keyboard to work in all apps

**How did you install `RustDesk`?**

Linux: rustdesk-1.1.8.deb

Windows: rustdesk-1.1.8-windows_x64.zip

**RustDesk version and environment**

Ubuntu 21.04

Edition	Windows 10 Pro
Version	20H2
Installed on	‎8/‎02/‎2021
OS build	19042.1415
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by rustdesk** [comment]
I had this issue also, but I have no clue for now.

**Comment by rustdesk** [comment]
https://stackoverflow.com/questions/32881957/keyboard-emulation-not-working-when-typing-is-within-virtualbox

**Comment by nigelsim** [comment]
From my preliminary test using a Python app, VirtualBox only correct responds if you send the `SendInput` using `KEYEVENTF_SCANCODE`. I note that the in-tree copy of enigo uses the keycode, while the original code uses the scancode. 

I'm not sure of the history here, but perhaps someone who is setup for development in Windows can see if there is a way to change the in-tree implementation?

**Comment by rustdesk** [comment]
> Hi, great job with international characters (1.1.9 pre-release), but I have a problem with ":"
SHIFT + "." always shows "." instead of ":", windows italian

**Comment by rustdesk** [comment]
> russian keyboard, win8.1, not work at all, but english works

**Comment by rustdesk** [comment]
> From my preliminary test using a Python app, VirtualBox only correct responds if you send the `SendInput` using `KEYEVENTF_SCANCODE`. I note that the in-tree copy of enigo uses the keycode, while the original code uses the scancode.
> 
> I'm not sure of the history here, but perhaps someone who is setup for development in Windows can see if there is a way to change the in-tree implementation?

@asur4s  wondering if map mode has this problem

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1547
