### ISSUE TITLE
Compiling the rustdesk project failed to generate librustdesk.so under armeabi-v7a.

### ISSUE THREAD

**Issue by kukudetang** [rustdesk/rustdesk#3661]
### Description

According to this development link https://rustdesk.com/docs/en/dev/build/android/ , the librustdesk.so of arm64 has been generated and is running normally. However, when the librustdesk.so file under armeabi-v7a is generated, an error message is always reported that the native static libraries opus and yuv cannot be found. When I look at the development link again, I find that https://github.com/rustdesk/doc.rustdesk.com/releases/download/console/dep.tar.gz This link only provides the relevant information of arm64 under vcpkg, and does not provide the relevant information of armeabi-v7a. There is no other way。

### Impact

If you want to compile and run on Android devices, the arm series does not support

**Comment by rustdesk** [comment]
#763
