### ISSUE TITLE
Feench Keyboard mapping

### ISSUE THREAD

**Issue by Frereneo** [rustdesk/rustdesk#3662]
### Bug Description

Hello,

For my work, I need access to a windows computer.

I have a French AZERTY keyboard and when I type text, the input is transmitted in QWERTY on the control computer.

I am under Linux Fedora37 Gnome 43.3 Wayland and I use Rustdesk 1.2.0 (the problem is also present when I use X11 with Rustdesk 1.2.0).

I specify that since Windows (Rustdesk 1.1.9) > Windows (Rustdesk 1.1.9), the keyboard works perfectly.
I also specify that from Linux Fedora37 Gnome 43.3 X11 (Rustdesk 1.1.9) > Windows (Rustdesk 1.1.9), the keyboard also works

Thank you in advance for your help
Sincerely,

### How to Reproduce

Enter the letters a, q, m... with a Linux wayland graphic environment

The remote machine will write the letters q, a, ;...

### Expected Behavior

I would like the keys entered on the keyboard to be the ones sent to the remote control. You will find attached a screenshot of an AZERTY keyboard with in red the bad keys and in green the good keys.

### Operating system(s) on local side and remote side

Fedora37 -> Windows10

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.1.9

### Screenshots

In red wrong keys
![image](https://user-images.githubusercontent.com/9987919/225275312-cb2e6480-d8f5-424e-9a82-25c6cfe314e9.png)

**Comment by rustdesk** [comment]
1.2 -> 1.2 please.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2549

**Comment by rustdesk** [comment]
@fufesou @chiehw
