### ISSUE TITLE
Remote Support Client - or - "Real" portable which does not write anything to AppData/Roaming

### ISSUE THREAD

**Issue by jacotec** [rustdesk/rustdesk#3664]
### Description

When using RustDesk as a support tool to access a (customer) computer, it still writes the config into the "AppData" folder of the PC - even without being installed.

This will in my opinion prevent the client from working in case the customer itself is using RustDesk.

As it's very easy to create clients with hardcoded server/key information with the described GitHub actions, it would be awesome to have a "Quick Support build" which simply runs with the hardcoded information and which does not write anything on the disk (or accesses the AppData folder where a customer installation might have its configuration) at all.

That's what I understand by the term "real portable". ;-)

### Impact

Anyone using RustDesk as a remote support tool

**Comment by rustdesk** [comment]
#941
