### ISSUE TITLE
Building custom clients via GitHub Actions seems not to include server key from "RS_PUB_KEY" secret

### ISSUE THREAD

**Issue by jacotec** [rustdesk/rustdesk#3667]
### Bug Description

Building the clients with GitHub Actions exactly as described here: https://rustdesk.com/docs/en/dev/build/all/

I've set the secrets "RENDEZVOUS_SERVER" and "RS_PUB_KEY" to exactly meet my server's data. Unfortunately the built clients won't work via Relay server (they just "hang" in the connection process and then they time out).

When I set the exactly the same server URL and key manually in the network settings of the client and then click "Apply", the connection via relay works immediately!

Comparing the "RustDesk2.toml" before I manually set the URL and key shows, that the initial RustDesk2.toml which was generated with the installation of RustDesk does include the line

rendezvous_server = 'rust.mydomain.de:21116'

But the line

key = '******...'

is missing. The key line is added after the manual network configuration - and then the client works.

It looks for me as if the RS_PUB_KEY is not added correctly during the GitHub build.

### How to Reproduce

Building clients via GitHub Actions as described in the docs.
Windows Client won't work via Relay unless the network parameters are added manually in the client settings.

### Expected Behavior

The built client with the hardcoded credentials should work out of the box.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

Nightly -> Nightly

### Screenshots

Nothing special to see  - it does not connect via Relay server. Locally works.

**Comment by rustdesk** [comment]
Close to favor #3328
