### ISSUE TITLE
can't build for mac both using github actions and locally using the documentation

### ISSUE THREAD

**Issue by AnassKartit** [rustdesk/rustdesk#3674]
### Bug Description

locally I get:
error: /Library/Developer/CommandLineTools/usr/bin/strip: can't open file: target/release/bundle/osx/RustDesk.app/Contents/MacOS/rustdesk (No such file or directory)
Error occurred when executing: strip target/release/bundle/osx/RustDesk.app/Contents/MacOS/rustdesk. Exiting

Mac M2.

### How to Reproduce

followed the documentation:https://rustdesk.com/docs/en/dev/build/osx/

### Expected Behavior

rustdesk.app or pkg to be built

### Operating system(s) on local side and remote side

osx 

### RustDesk Version(s) on local side and remote side

latest

### Screenshots

warning: src/platform/macos.mm:86:30: warning: 'CGDisplayModeCopyPixelEncoding' is deprecated: first deprecated in macOS 10.11 - No longer supported [-Wdeprecated-declarations]
warning:         CFStringRef pixelEncoding = CGDisplayModeCopyPixelEncoding(mode);
warning:                                     ^
warning: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGDirectDisplay.h:177:34: note: 'CGDisplayModeCopyPixelEncoding' has been explicitly marked deprecated here
warning: CG_EXTERN CFStringRef __nullable CGDisplayModeCopyPixelEncoding(
warning:                                  ^
warning: 1 warning generated.
    Finished release [optimized] target(s) in 1m 59s
error: /Library/Developer/CommandLineTools/usr/bin/strip: can't open file: target/release/bundle/osx/RustDesk.app/Contents/MacOS/rustdesk (No such file or directory)
Error occurred when executing: strip target/release/bundle/osx/RustDesk.app/Contents/MacOS/rustdesk. Exiting.

**Comment by rustdesk** [comment]
#763
