### ISSUE TITLE
On MacOS, Dedicated GPU is forced, leading to more battery usage

### ISSUE THREAD

**Issue by noaho** [rustdesk/rustdesk#3677]
### Bug Description

On my Macbook 15inch, 2016 with Radeon Pro graphics, I notice the dedicated GPU is being forced by rustdesk, 

This causes extra battery drain while rustdesk is running, instead of using Intel graphics. 

### How to Reproduce

Install https://gfx.io/ to show graphics card status, open rustdesk. 

### Expected Behavior

Integrated graphics are used.

### Operating system(s) on local side and remote side

OS X 12.6.3

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

<img width="217" alt="Screen Shot 2023-03-16 at 12 40 00 pm" src="https://user-images.githubusercontent.com/7568339/225525392-54b016e6-623c-47c8-a7c4-57b8957dfe14.png">

**Comment by rustdesk** [comment]
try out nightly build.
