### ISSUE TITLE
Mute doesn't work

### ISSUE THREAD

**Issue by smash2004** [rustdesk/rustdesk#3682]
### Bug Description

If I go to settings ->display -> mute and I check the mute option I still need to turn off the sounds manually on every new connection.

### How to Reproduce

Jut go to settings -> display -> check mute. Create a new connection and you will see that the sounds are not muted.

### Expected Behavior

I expect the sound to get muted on every new connection automatically.

### Operating system(s) on local side and remote side

Windows 11 Pro

### RustDesk Version(s) on local side and remote side

1.2.0 (Build Date: 2023-03-16 07:56)

### Screenshots

![image](https://user-images.githubusercontent.com/34189260/225616164-84b61739-f2f1-458f-9178-f74fc7ca02ec.png)
![image](https://user-images.githubusercontent.com/34189260/225617333-f48e3bf7-6d59-44ce-a1ad-63c618a60ec1.png)

**Comment by rustdesk** [comment]
Your two snapshot has nothing to do with each other logically.

**Comment by smash2004** [comment]
I can hear the sound echoing so I need to turn off sound on every connection. I though this is the same option logically in default settings. So there is no such option yet?

**Comment by smash2004** [comment]
Just to explain. I am talking to remote user with another app, so I need to turn off sounds from rustdesk always as this can be done with anydesk for example.

**Comment by rustdesk** [comment]
@21pages test together with #3684

**Comment by rustdesk** [comment]
@bilago @smash2004 could u please test the new build?

**Comment by smash2004** [comment]
I tried the new build but with no success. I don't think you understand what is my issues so I will try to explain it again.

I want to have a default setting for this button 
![image](https://user-images.githubusercontent.com/34189260/225848596-7b89cef0-6271-4f56-95d1-f63c9b89af4a.png)

I want this button to be turned off everytime I make a new connection automatically without manually deselecting it. 

Please confirm that you understand what I mean. In case you understand, please try it on your side first. Maybe only I have this issue.

**Comment by rustdesk** [comment]
Go to `Security` tab

**Comment by smash2004** [comment]
I don't understand "Go to Security tab" and why is this issues closed? Can you clarify this for me? Thank you.

**Comment by rustdesk** [comment]
![image](https://user-images.githubusercontent.com/71636191/225859085-d9b74e0f-d42d-4ede-9a32-15d3cd3e6fa6.png)

**Comment by smash2004** [comment]
thank you very much :)

**Comment by bilago** [comment]
> @bilago @smash2004 could u please test the new build?

Was away for the weekend - I can confirm monitor selection is now working in the latest nightly, thank you
