### ISSUE TITLE
[Nightly] Cannot enable multiple monitors on toolbar feature

### ISSUE THREAD

**Issue by bilago** [rustdesk/rustdesk#3684]
### Bug Description

After installing the latest nightly, I now see an option in Display settings

![image](https://user-images.githubusercontent.com/8310293/225628375-15f687d2-3f64-4fb1-8825-96b6f927295e.png)

With this enabled, and the latest nightly installed locally and on the remote client, there is no option within the remote session to enable this feature.

![image](https://user-images.githubusercontent.com/8310293/225628588-17539efb-7b11-44d9-8f58-4286356d5632.png)

and the monitors are not separate

![image](https://user-images.githubusercontent.com/8310293/225628713-12068406-a9a7-4ee8-a8eb-52da81178368.png)

I've deleted the remote connection from my machine and created a new connection, with no avail.

### How to Reproduce

Enable Multiple monitor in the Display settings
Remote into a machine with multiple monitors
Observe that monitors are still stacked in a expanding menu

### Expected Behavior

Each monitor should have it's own button

### Operating system(s) on local side and remote side

Windows 10 > Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

![image](https://user-images.githubusercontent.com/8310293/225629221-7fceae0d-abf8-4c8a-bcf6-18999fd440a5.png)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3682 same

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/3671 some not modified.
