### ISSUE TITLE
Please enable High DPI awareness...

### ISSUE THREAD

**Issue by IPeluchito** [rustdesk/rustdesk#37]
The images are blurry on very high resolution screens and with screen scaling higher than 100%.

Windows 8.1
3840 x 2160 ( Scaling 250% )

**Comment by rustdesk** [comment]
can you try out https://github.com/rustdesk/rustdesk/releases/download/1.1.5/rustdesk-1.1.5.exe?  Otherwise, we may need community help also, because I have no high resolution screens for now.

**Comment by IPeluchito** [comment]
https://github.com/stella-emu/stella/issues/700

**Comment by rustdesk** [comment]
> stella-emu/stella#700

Thanks, but I need to get a such display first.

**Comment by rustdesk** [comment]
> The images are blurry on very high resolution screens and with screen scaling higher than 100%.
> 
> Windows 8.1
> 3840 x 2160 ( Scaling 250% )

Try out this new one https://github.com/rustdesk/rustdesk/releases/download/1.1.5/rustdesk-1.1.5.exe
It works well on win10, not sure about win8

**Comment by IPeluchito** [comment]
Fixed !!!!!

**Comment by rustdesk** [comment]
https://github.com/quadrupleslap/scrap/issues/20
