### ISSUE TITLE
key mismatch 

### ISSUE THREAD

**Issue by yash1597** [rustdesk/rustdesk#3701]
### Bug Description

i am on windows i successfully build release on windows 
i changed in \rustdesk\libs\hbb_common\src\config.rs 
pub const RENDEZVOUS_SERVERS: &[&str] = &[
    "my_server_ip",
];

pub const RS_PUB_KEY: &str = match option_env!("RS_PUB_KEY") {
    Some(key) if !key.isempty() => key,
     => "my_server_key",
};
to hardcoded my server ip and key
so after that i build release, when i send that release to my colleague and after that when we try to connect then this "key mismatch" error is coming

### How to Reproduce

i go through all you docs in fact from that i make successfully build for windows and also go through your client side hbbs/hbbr document page and from hardcoding custom server page 

### Expected Behavior

it should be connect without error

### Operating system(s) on local side and remote side

windows10

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![Screenshot 2023-03-17 192617](https://user-images.githubusercontent.com/126689983/225928513-957907ee-1fab-4d4d-abbc-3f77ee741b46.png)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3328#issuecomment-1473764233

**Comment by yash1597** [comment]
but there is no solution for my problem @rustdesk
