### ISSUE TITLE
remote control from mobile BUG

### ISSUE THREAD

**Issue by fernandeusto** [rustdesk/rustdesk#3703]
### Bug Description

I have discovered that when the options in the custom permisions "enable remore restart" or "enable recording session" are disable, when i connect to client from mobile, can see screen, but i can not control it.

### How to Reproduce

On client, set custom permissions  and disable "enable remote restart" or "enable recording session" or  both

### Expected Behavior

It should be possible to control the mouse and keyboard from a mobile when reboot or recording is disabled in the client

### Operating system(s) on local side and remote side

Iphone IOS --> Windows 10/11

### RustDesk Version(s) on local side and remote side

IOS version - Nightly 1.20 

### Screenshots

<img width="391" alt="image" src="https://user-images.githubusercontent.com/87156183/226069782-06c432a9-20ef-438f-a69e-0bb573d10b4b.png">

**Comment by rustdesk** [comment]
@21pages

**Comment by 21pages** [comment]
https://github.com/rustdesk/rustdesk/blob/7371b9b66b5edf3e37a3fae3bb86dc6f26b23e37/src/client/io_loop.rs#L1060

The old version does not have recording/restart permissions, and falls back to the keyboard

**Comment by rustdesk** [comment]
Close this issue because you have to use nightly build if you wanna disable xx and yy. Sadly, we have no nightly build for IOS for the time being.
