### ISSUE TITLE
Some default options don't work

### ISSUE THREAD

**Issue by fernandeusto** [rustdesk/rustdesk#3704]
### Bug Description

some default options do not apply.
even deleting the recent sessions peer, when connecting does not recover the default options.
These client-side defaults, should be applied every time you connect to the client, regardless of the last connection terminate state

view only mode is also not activated by default

### How to Reproduce

activate all the default options in the client and disconect, delete the favorite or recent session in the control side and connect again to the ID

### Expected Behavior

each time you make a new connection with the client, the default configuration values of that client must be retrieved and applied. It should not use the values from the last time you closed the connection.

### Operating system(s) on local side and remote side

Windows 11 --> Windows 10

### RustDesk Version(s) on local side and remote side

1.20 Nighty

### Screenshots

![image](https://user-images.githubusercontent.com/87156183/226070869-de44f234-254d-4b56-8e60-effd3d93f96a.png)

**Comment by fernandeusto** [comment]
I think maybe the problem is that the default options on the control side and on the client side are getting mixed up.
Some options as "view mode", "lock after session end", "mute", "disable clipboard" must be under "Client default options"
and other as "Show monitors..." "zoom cursor", "show quality monitor", or "privacy mode" must be under "Control default options"

**Comment by 21pages** [comment]
Let us assume A control B,
This is how it works:
* The option in the Display tab is set to A for the remote window toolbar menu, which is used to connect to the peer for the first time, and then the toolbar menu option will display the option set last time.
* The option in the Security tab is set to B, Show in the connection window.
There is a gif showing the default display options

![rustdesk_BwD6DWzizm](https://user-images.githubusercontent.com/14891774/226076197-5d29ac9d-c8fb-440f-8a6c-57323d248f6a.gif)

**Comment by rustdesk** [comment]
No further explanation here, will be in the document in the future.

**Comment by rustdesk** [comment]
> These client-side defaults, should be applied every time you connect to the client, regardless of the last connection terminate state

That's your `should`.

**Comment by rustdesk** [comment]
AnyDesk does not remember by default, we are not. @21pages noted, let's decide later.
![image](https://user-images.githubusercontent.com/71636191/226083333-62e56a70-f8ed-431d-9fd2-7b1621a06c2a.png)

**Comment by 21pages** [comment]
Anydesk requires a license to select.

**Comment by rustdesk** [comment]
Cool, need money to turn on `remember`.
