### ISSUE TITLE
Resolution Adjustment Flower Screen

### ISSUE THREAD

**Issue by youhers** [rustdesk/rustdesk#3707]
### Bug Description

Flower screen status after normal resolution switching, see GIF Motion Map

在正常切换分辨率后会出现花屏状态，请查看GIF动图

### How to Reproduce

After connecting the device, click on the resolution to change the resolution. After 3 seconds clicking on the controlled screen will display a floral screen. After closing the connection desktop, the resolution will be restored

连接设备后点击分辨率，更改分辨率，3秒后点击被控端屏幕会出现花屏现象，关闭连接桌面后分辨率会还原

### Expected Behavior

Click to change resolution should succeed instead of automatically restoring resolution after exiting the client and should not have a flowerscreen status

点击更改分辨率后应该成功，而不是退出客户端后分辨率自动还原，并且不应该出现花屏的状态

### Operating system(s) on local side and remote side

WIN10 - WIN7

### RustDesk Version(s) on local side and remote side

1.2.0 - 1.2.0

### Screenshots

![Uploading 截图_20230318120329.gif…]()
GIF

**Comment by youhers** [comment]
![截图_20230318120329](https://user-images.githubusercontent.com/106003909/226084130-7e62762d-8a7c-44bc-889a-e8f87cc4c0c6.gif)

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
How about win 10?

**Comment by rustdesk** [comment]
We won't test on win 7 any more.

**Comment by youhers** [comment]
Thank you. Let me test it

**Comment by youhers** [comment]
Tested server 2019 and found no problems

**Comment by rustdesk** [comment]
> 而不是退出客户端后分辨率自动还原

No, we insist restore after disconnect.

**Comment by rustdesk** [comment]
But we should remember the selected resolution for next-time connection. Not remembered?

**Comment by youhers** [comment]
"Yes, changing the resolution is invalid"
