### ISSUE TITLE
Autostart for Android

### ISSUE THREAD

**Issue by noaho** [rustdesk/rustdesk#3709]
### Description

I have granted permissions permanently using:

`adb shell cmd appops set com.carriez.flutter_hbb PROJECT_MEDIA allow`

Is there a way to get rustdesk to Autostart on Android? 

### Impact

Autostart will allow use cases such as leaving an old phone at home to check for sms messages from time to time. Sometimes restarts happen.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3533
