### ISSUE TITLE
Not ready. Please check your connection - on Windows

### ISSUE THREAD

**Issue by working-name** [rustdesk/rustdesk#3711]
### Bug Description

Rustdesk refuses to connect to the self-hosted server that many other stations do not have issues with - regardless of whether I give it an ipv4, ipv6, or a hostname.

This is related to https://github.com/rustdesk/rustdesk/discussions/2582 but I'm convinced this is a bug now that I've tried some 6+  versions of rustdesk (I'm including the nightlies).

### How to Reproduce

Turn off firewalls, make sure you can `nslookup` your selfhosted server, install **any** version of rustdesk, configure it to use your self hosted server. It will refuse to connect.

### Expected Behavior

Connect like every other computer.

### Operating system(s) on local side and remote side

Windows 11 21H2 Build 22000.1455

### RustDesk Version(s) on local side and remote side

1.2.0 build 2023-01-09 00:23 -> 1.2.0 build 2023-03-16 07:56

### Screenshots

![image](https://user-images.githubusercontent.com/16505052/226112201-6707ae59-270a-4f73-8b20-d1f8249d3aaf.png)

### Additional Context

As far as I can see, there's no network reason for this communication not to go through.
I cannot find logs of this nightly however to see what it thinks it's going on. Maybe you can guide me through a way to get to the logs or have a debug build?

**Comment by rustdesk** [comment]
#763
