### ISSUE TITLE
Encryption for Direct IP Access on a Local Network

### ISSUE THREAD

**Issue by Emphasize2** [rustdesk/rustdesk#3714]
### Description

When using "Direct IP Access" for a local network, instead of getting a green shield like usual, you instead get a red shield saying "Direct and unencrypted connection" instead.

So my request is to add encryption for that scenario.

It is a security risk for me since there are quite some people using my network and you never know who else could get access to it and be able to see my unencrypted connection between the local network.

### Impact

Everyone who uses the Direct IP Access feature will benefit from this.

**Comment by rustdesk** [comment]
#532

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/wiki/FAQ#i-only-use-rustdesk-for-a-few-devices-on-my-local-network-with-no-internet-connectivity-can-i-still-use-rustdesk-with-direct-ip-access

**Comment by frontyard** [comment]
+1

**Comment by okae** [comment]
+1

**Comment by Mahaaveer** [comment]
+1

**Comment by ShadowVoyd** [comment]
I cannot understand why this is still not implemented given the need for secure intranet connections.

**Comment by BlohoJo** [comment]
I'm uncomfortable using someone else's server. I just want to use direct IP and have it be encrypted. That should be doable. I guess this is something we can't have? Why not? At the very least it would be helpful to know the reason.

**Comment by ThreeDeeJay** [comment]
<img width="284" height="92" alt="Image" src="https://github.com/user-attachments/assets/9ee1b810-e015-47f0-9f0f-865560250e5a" />

I just found out about this and just like the others here I don't trust every device on my network.

> [the connection is unecrypted, please do not send us issue about this.](https://github.com/rustdesk/rustdesk/wiki/FAQ#i-only-use-rustdesk-for-a-few-devices-on-my-local-network-with-no-internet-connectivity-can-i-still-use-rustdesk-with-direct-ip-access)

@rustdesk Why such a dismissive attitude towards a potential vulnerability?
Doesn't this mean a malicious app on someone's device in my network could just snoop on the session?
And if there's a technical reason why local encryption isn't possible, why not just specify it?

I had such high hopes for RustDesk but this is a serious turn off.
So I even went looking for an alternative and stumbled upon HopToDesk which seems to support encryption when using a direct IP connection within my local network.

<img width="873" height="469" alt="Image" src="https://github.com/user-attachments/assets/6fbd5e40-8269-4648-b9ce-6beed7dd367d" />

But after reading [this thread](https://www.reddit.com/r/HopToDesk/comments/1bcwys4/how_is_hoptodesk_different_than_rustdesk_and_why/) about them being shady and a shameless fork of RD I wouldn't be surprised their app's just lying and it's still unencrypted despite showing the green shield which I assumed meant encrypted. Luckily I restricted it (and RD for that matter) to my local network.

So if anyone finds a *legit* alternative/fork/PR that allows secure local connections, please let us know so we can some regain trust and piece of mind.

**Comment by rustdesk** [comment]
> Everyone who uses the Direct IP Access feature will benefit from this.

We don’t plan to implement this directly, as it is designed for test initially, we do not recommend using RustDesk with a public IP alone, that's also why direct ip access is turned off by default.

For security and privacy, we strongly advise using it in combination with a VPN—the VPN tunnel already provides end-to-end encryption, so additional encryption within RustDesk is unnecessary in that setup.

That said, we welcome community contributions!
Many users express interest or share feedback—but very few take the next step and submit a pull request.
If you’re able to help, your PR would be greatly appreciated! 💙
