### ISSUE TITLE
Option to have a black screen to the connected device

### ISSUE THREAD

**Issue by Emphasize2** [rustdesk/rustdesk#3715]
### Description

Basically the "Privacy Mode" in AnyDesk

### Impact

I'm sure everyone at some pointed wanted to access his device remotely but didn't want everyone who's around that device to be able to see what they're doing, so everyone will benefit with this feature.

**Comment by rustdesk** [comment]
duplicate

**Comment by rustdesk** [comment]
#3254 search please before ask new issues
