### ISSUE TITLE
Can't contact your email by using ProtonMail

### ISSUE THREAD

**Issue by Emphasize2** [rustdesk/rustdesk#3716]
### Bug Description

I sent you an email with my ProtonMail and I got an email back saying this

<info@rustdesk.com>: host mx.yandex.net[77.88.21.249] said: 554 5.7.1 Message
    rejected under suspicion of SPAM; https://ya.cc/1IrBc

### How to Reproduce

Send and emal using ProtonMail, havent tried a different email provider.

### Expected Behavior

I expected for my email to be delivered so I can contact the developers privately since in the discord no mod is responding

**Comment by rustdesk** [comment]
i can receive emails
