### ISSUE TITLE
About touch pad

### ISSUE THREAD

**Issue by li-dianzheng** [rustdesk/rustdesk#3717]
### Bug Description

When I remotely control my archlinux computer on a windows computer using the latest build, swiping up and down using the touchpad is too much. This did not happen on version 1.1.9.

### How to Reproduce

Use trackpad to scroll up and down pages

### Expected Behavior

Scrolling can be done normally on the controlled side.

### Operating system(s) on local side and remote side

windows11>archlinux

### RustDesk Version(s) on local side and remote side

nightly>nightly

### Screenshots

no

**Comment by rustdesk** [comment]
close to favor #2655
