### ISSUE TITLE
Windows Taskbar Preview Window names - Show Custom Name if set.

### ISSUE THREAD

**Issue by DaveAuld** [rustdesk/rustdesk#3720]
### Description

On Windows Taskbar, the window preview of the remote machines only shows the device ID, not the Custom Name, this makes it harder to easily identify which remote machine you want to switch to. As you can see in the snapshot below, I am showing remote machine 'Rig 2' custom name, but the windows taskbar, has 3 instance of rust desk sessions running, but they only show the machine device IDs and not the custom names, so if I want to jump over to say Rig 1, I have to remember what device id is, or open each view until I find the machine I want to show.

![rustdesk](https://user-images.githubusercontent.com/4674288/226274531-a0dedc8a-2dc3-4ebe-9966-a50c5a5264b3.png)

### Impact

Frustrating when frequently switching between active sessions.

### Additional Context

Have the taskbar preview show the custom names instead of the device ids if it has been set.

**Comment by rustdesk** [comment]
try out nightly build.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2054
