### ISSUE TITLE
Blurred tray icon after returning from sleep

### ISSUE THREAD

**Issue by cetjunior** [rustdesk/rustdesk#3728]
### Bug Description

Hi there!

Tray icon gets more blurry with every resume from sleep. Icon is normal after a clean reboot. I noticed it before, but I formatted the system (for other reasons), hoping that would solve it, and I noticed that it keeps happening. Just happens with RuskDesk icon.

I compared this behaviour in 2 systems that I use daily, both laptops running Microsoft Windows 10 22H2. One never sleeps, always on; and my personal laptop, that I use on the move and usually suspending it (opening and closing the lid). The issue happens in the last one.

The issue is only cosmetic, it does not affect the functionality of the program.

After returning from sleep:
![after-return-from-sleep](https://user-images.githubusercontent.com/773135/226568143-ca718db6-57c8-46b2-a40c-be1072053f13.png)

After restarting the system:
![clean-boot](https://user-images.githubusercontent.com/773135/226568152-a9ddfcc1-b81a-4f59-a8b1-8fbb5c94a97c.png)

I hope I was clear and also I am available for further clarification if necessary.

Best regards.

### How to Reproduce

Keep suspending (or closing the lid) and returning the system, which makes the icon more blurred with each return. Maybe it's related to using nightly client (didn't tested it).

### Expected Behavior

The icon should be normal and clean, in good resolution, like the others in the screenshots.

### Operating system(s) on local side and remote side

Microsoft Windows 10 22H2

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![after-return-from-sleep](https://user-images.githubusercontent.com/773135/226569445-5e975f7c-d573-4551-b0b5-684ae8ee2437.png)
![Captura de tela 2023-03-21 064453](https://user-images.githubusercontent.com/773135/226569457-477551d6-810a-4ab0-8665-53f56167a6d0.png)
![clean-boot](https://user-images.githubusercontent.com/773135/226569462-e02996d8-ad11-4f0d-9a04-4d9cda68c048.png)

### Additional Context

Just to complement, I connect to the machine that is always connected with the nightly client (1.2.0 - because of the problem with special characters in the stable version), but both machines have the stable version (1.1.9) installed on the system. The problem happens with the machine I'm using to connect (guest), not the one receiving the connection (host).

**Comment by rustdesk** [comment]
close as fix merged

**Comment by Borber** [comment]
I would like to ask if this problem has been completely solved? And which part was repaired? I have encountered similar problems in other programs but I don't know how to solve it.
