### ISSUE TITLE
iPad physical keyboard/trackpad

### ISSUE THREAD

**Issue by jdanna** [rustdesk/rustdesk#3736]
### Bug Description

When using the iPad OS client with an iPad that has a connected keyboard/trackpad (like the Apple keyboard cover for the iPad pro) - the mouse doesn’t move or click when using the trackpad - and when typing on the keyboard, all keys are duplicated.

### How to Reproduce

Connect to a RustDesk desktop with the iPad client, and try to use the mouse and keyboard connected to the iPad

### Expected Behavior

Trackpad/Mouse/Keyboard should work with iPadOS and connected input devices

### Operating system(s) on local side and remote side

iPad OS -> macOS or windows

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

![CDB62441-A65A-44C2-8A9D-48C342C0739D](https://user-images.githubusercontent.com/25439364/226773700-d4b96a1b-7ee5-4c6e-a08f-971925e2517a.jpeg)

**Comment by rustdesk** [comment]
#1314
