### ISSUE TITLE
rustdesk-I.I.9.exe - Entry Point Not Found 

### ISSUE THREAD

**Issue by yardstudio** [rustdesk/rustdesk#3737]
### Bug Description

I am trying run installation or portable version on obsolete SBS 2008 Server, but get error:

rustdesk-I.I.9.exe - Entry Point Not Found 
The procedure entry point TryAcquire5RWLockExcIusive could not 
be located in the dynamic link library KERNEL 32. dll. 

### How to Reproduce

Simply start run rustdesk-1.1.9-putes.exe (in admin mode too)

### Expected Behavior

Installation and run

### Operating system(s) on local side and remote side

SBS2008

### RustDesk Version(s) on local side and remote side

rustdesk-1.1.9-putes.exe

### Screenshots

![2023-03-22_10-15-18](https://user-images.githubusercontent.com/25852179/226859282-ec954f43-8229-4499-a42f-a4760ee4ffda.png)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2980#issuecomment-1462001402
