### ISSUE TITLE
macos fullscreen auto hidden menu bar appears massive when unhidden

### ISSUE THREAD

**Issue by allywilson** [rustdesk/rustdesk#3738]
### Bug Description

If I change to fullscreen when controlling a remote machine, the small meu bar automatically dissappears, but if I move my mouse to the top to reveal it, it becomes massive.

### How to Reproduce

Full screen, move mouse to top

### Expected Behavior

TO be the same size as when not in full screen.

### Operating system(s) on local side and remote side

macos 13.3 (m2) -> WIndows 10 (x86_64)

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

![image](https://user-images.githubusercontent.com/470127/226891495-e1673775-31fe-4c23-8b38-3260efcdfeff.png)

**Comment by rustdesk** [comment]
try out nightly build please.
