### ISSUE TITLE
Print screen (Prt Scr) key doesn't work (shortcuts handle which can be chosen to be effective on local or remote side by user)

### ISSUE THREAD

**Issue by mtelis** [rustdesk/rustdesk#3740]
### Bug Description

I'm trying to take a screenshot of remote PC's screen by pressing either PrtScr or Ctrl-PrtScr key, but there is no response (I'm using ShareX).

The only way to take a screenshot is by clicking on the ShareX tray icon.

PrtScr works fine with Anydesk.

### How to Reproduce

Connect to remote, try pressing PrtScr.

### Expected Behavior

Screenshot taken

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.1.2

### Screenshots

No screenshots, they don't work

**Comment by rustdesk** [comment]
try out nightly build on both side please.

**Comment by mtelis** [comment]
Nightly build on both sides, it doesn't work.

> Mike

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
@fufesou  let's follow TV on Linux/Windows, Macos seems not such key.

![image](https://user-images.githubusercontent.com/71636191/226931382-101717a7-b79d-4d57-8d84-0e98311f80d8.png)

**Comment by rustdesk** [comment]
@fufesou TV has different behavior, which handle PrintScreen as a shortcut. Let us do it later together with optimizing shortcuts handle in the future.

![image](https://user-images.githubusercontent.com/71636191/226933162-3f76ccdc-13ec-4090-8bee-35499afc238d.png)

![image](https://user-images.githubusercontent.com/71636191/226933196-22e2c973-2342-40f3-9e26-6ef3a861d1f3.png)

**Comment by mtelis** [comment]
PrtScr under Anydesk does work locally, it activates ShareX. Rustdesk ignores PrtScr altogether, it doesn't do anything either locally or remotely.

**Comment by rustdesk** [comment]
tracked by #4367

**Comment by rustdesk** [comment]
also keymap https://github.com/rustdesk/rustdesk/issues/5027#issuecomment-1777133063
