### ISSUE TITLE
[Nightly] Multiple Monitor toolbar icons disappear if you connect to a second PC with only 1 monitor

### ISSUE THREAD

**Issue by bilago** [rustdesk/rustdesk#3746]
### Bug Description

When connecting to a computer with multiple monitors, each monitor spawns a button on the toolbar.
If you connect to a second computer with a single monitor at the same time, both toolbars no longer show any monitor icons.

To resolve, I have to disconnect from the sessions and start a new session on the multiple monitor PC.

### How to Reproduce

Connect to PC with 2 monitors, observe the icons are present
Connect to PC with 1 monitor, observe the icons are completely gone, for both sessions

### Expected Behavior

The multiple icons for switching monitors should re-appear if I switch back to a session that has multiple monitors.

### Operating system(s) on local side and remote side

Windows 10 > Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

Connection A:
![image](https://user-images.githubusercontent.com/8310293/227009509-216afbbd-56a3-4994-acc2-f6a794cea032.png)

Connection B:
![image](https://user-images.githubusercontent.com/8310293/227009582-b21077de-c1ce-4d8d-9fc0-3d95dedb30fd.png)

Switching back to connection A:
![image](https://user-images.githubusercontent.com/8310293/227009638-e50edb2c-5a11-4fd3-84f9-e0d8dd929b89.png)

**Comment by rustdesk** [comment]
@NicKoehler

**Comment by NicKoehler** [comment]
Probably something to do with the state of the widget. I'll try to fix it whenever I get some time.

**Comment by rustdesk** [comment]
close as fix merged. will reopen if not working, let me know.
