### ISSUE TITLE
[BUG] The sound is intermittent when the screen doesn't change

### ISSUE THREAD

**Issue by TenmaSennpai** [rustdesk/rustdesk#3748]
### Bug Description

If the controlled side is Windows 10/11, the sound is normal when the screen on the controlled side changes continuously. When the screen on the controlled side does not change, the sound is intermittent even stops.
The problem occurs when the control side is Android or Windows.
I connect on the LAN by directly typing in the ip address, the LAN network is good
The version is the latest nightly binary build

### How to Reproduce

control side is Android or Windows.
controlled side is Windows 10/11.

### Expected Behavior

none

### Operating system(s) on local side and remote side

nightly

### RustDesk Version(s) on local side and remote side

nightly

### Screenshots

![image](https://user-images.githubusercontent.com/64529818/227105867-3347f01e-39ef-42e0-9e0e-34777cb82e75.png)

**Comment by rustdesk** [comment]
@21pages I guess below part of code causes this.

https://github.com/rustdesk/rustdesk/blob/0ea7019a1624bdb69ac04fa678c2f9591bd5a3db/src/client.rs#L808

**Comment by 21pages** [comment]
reproduced

**Comment by rustdesk** [comment]
👍

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/534

**Comment by rustdesk** [comment]
@21pages let's revert https://github.com/rustdesk/rustdesk/pull/560 first, this solution looks bad for me.

**Comment by rustdesk** [comment]
let me revert first.
