### ISSUE TITLE
port blocked in some network

### ISSUE THREAD

**Issue by josephjosedev** [rustdesk/rustdesk#376]
Rust desk port is blocked in some network. so rustdesk application ID not shown.(Generating....).please check immediatelty.

**Comment by open-trade** [comment]
can you help?

**Comment by rustdesk** [comment]
Please show me your log: C:\WINDOWS\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\rustdesk_rCURRENT.log

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/314

**Comment by josephjosedev** [comment]
ok.

**Comment by rustdesk** [comment]
> ok.

log?

**Comment by rustdesk** [comment]
> some network

Which network?

**Comment by josephjosedev** [comment]
some mobile networks rust desk not working properly.

**Comment by ant0nwax** [comment]
I am able to confirm this externally caused issue on a Note 8 and a Note 10 and Ubuntu 22.04 for Android
It writes "Connecting to rust-desk network..." and will freeze

i tried to show you the network console log from rustdesk.com 

![image](https://user-images.githubusercontent.com/33480652/212551683-b216da6c-4b58-4138-b988-6627bdf43f26.png)
