### ISSUE TITLE
Desktop Shortcut must be started twice to work!

### ISSUE THREAD

**Issue by FCrane** [rustdesk/rustdesk#3770]
### Bug Description

Since a few nightlys ago, the desktop shortcut to my PC in the local network needs to be double-clicked twice before it works. The first double-click just makes the mouse cursor flash the "Busy" symbol shortly, but doesn't open the connection. The second one then works.

### How to Reproduce

Double-click a desktop shortcut to a connection.

### Expected Behavior

Immediately open the connection (as it always did)...

### Operating system(s) on local side and remote side

Windows 11 x64

### RustDesk Version(s) on local side and remote side

1.20 latest nightly from 24.03.2023

### Screenshots

n/a

**Comment by rustdesk** [comment]
@Kingtous

**Comment by rustdesk** [comment]
fixed as fix merged

**Comment by FCrane** [comment]
Thanks for fixing it - it now starts correctly.

However, When double-clicking the desktop shortcut, the mouse cursor still flashes the "Busy" symbol for quite some time (significantly noticeable) before the connection is established. This was not the case in previous versions (which connected almost instantly when double.clicking) and it makes opening the connection noticeably slower. Is there a reason behind this that can be fixed? I liked the extremely fast connection of RustDesk which is now somewhat slower...

Thanks!

**Comment by rustdesk** [comment]
@Kingtous

**Comment by Kingtous** [comment]
> Thanks for fixing it - it now starts correctly.
> 
> However, When double-clicking the desktop shortcut, the mouse cursor still flashes the "Busy" symbol for quite some time (significantly noticeable) before the connection is established. This was not the case in previous versions (which connected almost instantly when double.clicking) and it makes opening the connection noticeably slower. Is there a reason behind this that can be fixed? I liked the extremely fast connection of RustDesk which is now somewhat slower...
> 
> Thanks!


The execution order not changed these days...btw
lets try leverage the execution order of the connection first.
