### ISSUE TITLE
Configuration Server ID

### ISSUE THREAD

**Issue by ts2050** [rustdesk/rustdesk#3784]
### Bug Description

Rustdesk application
I am using a custom Rustdesk server and it is working well.

However, when I install the software on a client, the settings are not registered in the graphical interface. To check if the server is correct and configured, one needs to access the TOML files.

### How to Reproduce

.

### Expected Behavior

.

### Operating system(s) on local side and remote side

Windows 10/11

### RustDesk Version(s) on local side and remote side

version:: 1.1.9

### Screenshots

![WhatsApp Image 2023-03-25 at 20 17 33](https://user-images.githubusercontent.com/98055867/227746940-3d02fe80-b27c-46df-adb4-e0c0035f08e3.jpeg)

### Additional Context

.

**Comment by rustdesk** [comment]
#763
