### ISSUE TITLE
Trusting Generated Application on Windows

### ISSUE THREAD

**Issue by ts2050** [rustdesk/rustdesk#3786]
### Bug Description

I performed the process of building my agents with the already configured parameters via GitHub, making a fork, as instructed.

However, I am having a problem that after generating the agents, in the case of Windows, both the browser and Windows begin to issue alerts about the software, as shown in the image. Is there a way to include a signature or something that will make Windows trust this application generated by the action?

Is there anything I can do to fix this?

### Operating system(s) on local side and remote side

Windows 10/11

### RustDesk Version(s) on local side and remote side

version: 1.2

### Screenshots

![WhatsApp Image 2023-03-25 at 21 34 47 (1)](https://user-images.githubusercontent.com/98055867/227749074-432a683a-d6ff-46b5-9a33-8ed2e9baf0e3.jpeg)

**Comment by rustdesk** [comment]
#763
