### ISSUE TITLE
An existing connection was forcebly closed by the remote host OS ERROR 10054

### ISSUE THREAD

**Issue by stevecerr** [rustdesk/rustdesk#379]
New install, typical Windows 10 64bit machine.

When trying to access it from another computer on the same network I get the following error,

An existing connection was forcebly closed by the remote host OS ERROR 10054

Turned off firewall and anything else
Reinstalled Rustdesk
Added SchUseStrongCrypto to Registry 

Ideas?
![Error](https://user-images.githubusercontent.com/47087446/150597952-d4b5583b-79c9-410b-a510-060359f86d78.png)

**Comment by open-trade** [comment]
Crash on remote side can also cause this.

**Comment by open-trade** [comment]
wondering if you can build the source and run

**Comment by stevecerr** [comment]
When I build without installing and try to connect it doesnt give me same error. However, it just gets stuck waiting for an image. I tried it 3 times. I have never had any issues with outgoing connections, its always incoming. Ideas?
![Build Run](https://user-images.githubusercontent.com/47087446/150688758-f7e8b534-4382-41fb-a2ae-0d5668a53d34.png)

**Comment by stevecerr** [comment]
I just noticed that after about 2-3 minutes of waiting on the image, it will throw a lost connection error.

**Comment by rustdesk** [comment]
> lost connection error

Looks like server side got stuck somewhere. https://github.com/rustdesk/rustdesk/blob/master/src/server/connection.rs#L299

**Comment by rustdesk** [comment]
Can you check here https://github.com/rustdesk/rustdesk/blob/master/src/server/video_service.rs#L254 to see if there is image captured? Is gdi or dxgi used?

**Comment by rustdesk** [comment]
close this so that we can focus on its dup https://github.com/rustdesk/rustdesk/issues/1113.
