### ISSUE TITLE
macOS arm64 app appears as for Intel

### ISSUE THREAD

**Issue by rakleed** [rustdesk/rustdesk#3795]
### Bug Description

macOS arm64 app appears as for Intel.

### How to Reproduce

1. Install [rustdesk-1.2.0-aarch64-apple-darwin.dmg](https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-aarch64-apple-darwin.dmg)
2. Open app Info or Activity Monitor

### Expected Behavior

The app type is displayed as Apple Silicon or Universal.

### Operating system(s) on local side and remote side

N/A

### RustDesk Version(s) on local side and remote side

1.2.0 nightly latest

### Screenshots

![Screenshot 2023-03-26 at 22 51 12](https://user-images.githubusercontent.com/19418601/227800887-78e65ec6-950e-441b-bc2b-4418839aebe6.png)

**Comment by ithakaa** [comment]
I can can confirm that I am being asked to install Rosetta before the application will run

**Comment by rustdesk** [comment]
Sorry, github CI does not support it, I will remove the wrong build.

https://github.com/actions/runner-images/issues/768
https://github.com/actions/runner-images/issues/2187

**Comment by fragtion** [comment]
no support yet for arm64 dmg? any roadmap for this returning?
