### ISSUE TITLE
My self-built server IP is not resolving on the rust desk on my macbook

### ISSUE THREAD

**Issue by cengzhijie3** [rustdesk/rustdesk#3799]
### Bug Description

I can access my macbook with the ip of my vps in android, but my macbook cannot access my android rustdesk
![WechatIMG22](https://user-images.githubusercontent.com/89333400/227876245-76a8c381-abe6-4a85-831c-4c5624c4dbbd.jpeg)
![WechatIMG23](https://user-images.githubusercontent.com/89333400/227876286-9c894789-bdcd-4b4c-ac8b-d5f529e65132.jpeg)
<img width="1381" alt="截圖 2023-03-26 下午12 24 50" src="https://user-images.githubusercontent.com/89333400/227876307-c6c4cb38-df58-4335-b71c-bc0e9d91d130.png">
<img width="912" alt="截圖 2023-03-26 下午12 24 57" src="https://user-images.githubusercontent.com/89333400/227876332-17cbd90a-6181-4d5e-b87b-21d3c2b96dbd.png">

### How to Reproduce

try building a service ipv6 or ipv4 and use macos rustdesk nightly build to try connecting the Android smartphone

### Expected Behavior

My self-built server IP is not resolving on the rust desk on my macbook

### Operating system(s) on local side and remote side

mac os13.2.1 > androdid13

### RustDesk Version(s) on local side and remote side

latest nightly version->android version

### Screenshots

![WechatIMG22](https://user-images.githubusercontent.com/89333400/227878130-8b95e1b8-981d-4715-8b73-c774cae2adf4.jpeg)
![WechatIMG23](https://user-images.githubusercontent.com/89333400/227878151-477420ff-71b1-435a-9ff4-6212d13240a6.jpeg)
<img width="912" alt="截圖 2023-03-26 下午12 24 57" src="https://user-images.githubusercontent.com/89333400/227878206-61ced7c6-0c27-47aa-8adc-332b71745490.png">
<img width="1381" alt="截圖 2023-03-26 下午12 24 50" src="https://user-images.githubusercontent.com/89333400/227878237-0ac3c287-8473-4b83-afc8-32239e8efe4d.png">

**Comment by rustdesk** [comment]
#763
