### ISSUE TITLE
Background requests each hour even when service disabled

### ISSUE THREAD

**Issue by Surendrajat** [rustdesk/rustdesk#38]
I've installed the `.deb` package few days ago and was going through DNS logs today when I noticed a lot of requests from rustdesk app even though I've not opened that and have rebooted system few times. It's like a few requests every hour. Can you tell if it's necessary?
![image](https://user-images.githubusercontent.com/11215000/118223626-598acb00-b49f-11eb-9392-2f28f496e182.png)

**Comment by rustdesk** [comment]
because there is rustdesk service running, if you do not like this service, please open rustdesk main window, click menu button at the right side of your "ID", choose "stop service", but the other rustdesk can not connect to you any more, you can still connect to the other rustdesk.

**Comment by rustdesk** [comment]
![IMG_20210514_131128](https://user-images.githubusercontent.com/71636191/118224580-06704280-b4b6-11eb-8b75-39f95ee23936.jpg)

**Comment by Surendrajat** [comment]
Thanks for the reply. I understand that the service might run in background and because I don't need that I had that service stopped when I installed and tested rustdesk as you can see in the below screenshot:
![image](https://user-images.githubusercontent.com/11215000/118224610-1fbac400-b4a1-11eb-87ad-0cb1fbc99976.png)
The weird thing is that it's making those requests and that's why opened this issue.

**Comment by Surendrajat** [comment]
Also, I can confirm that the rustdesk service runs on boot even when the service disabled. It seems like a bug.

![image](https://user-images.githubusercontent.com/11215000/118225093-06fede00-b4a2-11eb-9428-a97e57b4f829.png)

**Comment by rustdesk** [comment]
you remind me. the service restarted every hour when there is no incoming connection. I will fix this bug to avoid useless network request after restart.

**Comment by Surendrajat** [comment]
Basically I don't want any incoming connection and hence any service running.

**Comment by rustdesk** [comment]
my implentation does not stop service process   just tell it is turned off. if you do not like the process, please sudo service rustdesk stop.

**Comment by rustdesk** [comment]
> Also, I can confirm that the rustdesk service runs on boot even when the service stopped from UI. It seems like a bug.
> 
> ![image](https://user-images.githubusercontent.com/11215000/118225093-06fede00-b4a2-11eb-9428-a97e57b4f829.png)

yes the linux service is running, but is not servicing.

**Comment by Surendrajat** [comment]
I've done `sudo systemctl disable rustdesk.service` for now, and it even works fine when I start/stop service from UI. I think you can give an option similar to anydesk's `Unatteneded access` where you completely enable/disable this service based on user preference.

**Comment by Surendrajat** [comment]
> yes the linux service is running, but is not servicing.

But I can still see those requests in DNS logs somehow.

**Comment by rustdesk** [comment]
> > yes the linux service is running, but is not servicing.
> 
> But I can still see those requests in DNS logs somehow.

here is a bug. but it is really not servicing, you can try.

**Comment by rustdesk** [comment]
> I've done `sudo systemctl disable rustdesk.service` for now, and it even works fine when I start/stop service from UI. I think you can give an option similar to anydesk's `Unatteneded access` where you completely enable/disable this service based on user preference. Also, the option where it listens for incoming connections only when UI is open.

After you do "sudo systemctl stop service",  it will listen for incoming connections only when UI is open.

**Comment by Surendrajat** [comment]
> After you do "sudo systemctl stop rustdesk" and "start service" from GUI, it will listen for incoming connections only when UI is open.

Yeah. I meant that you can expose `sudo systemctl stop rustdesk` thing as an option in UI too if possible.

**Comment by rustdesk** [comment]
> > After you do "sudo systemctl stop rustdesk" and "start service" from GUI, it will listen for incoming connections only when UI is open.
> 
> Yeah. I meant that you can expose `sudo systemctl stop rustdesk` thing as an option in UI too if possible.

Good idea

**Comment by Surendrajat** [comment]
Much like anydesk does:
![image](https://user-images.githubusercontent.com/11215000/118228127-51368e00-b4a7-11eb-8f90-08394d5a4d2c.png)

**Comment by rustdesk** [comment]
> Much like anydesk does:
> ![image](https://user-images.githubusercontent.com/11215000/118228127-51368e00-b4a7-11eb-8f90-08394d5a4d2c.png)

Thanks, I have not noticed this before.

**Comment by rustdesk** [comment]
> > Much like anydesk does:
> > ![image](https://user-images.githubusercontent.com/11215000/118228127-51368e00-b4a7-11eb-8f90-08394d5a4d2c.png)
> 
> Thanks, I have not noticed this before.

I just tested AnyDesk, it does not stop the service process either when you choose "only show ... if AnyDesk windows is open". I can also have similar design.

**Comment by Surendrajat** [comment]
> I just tested AnyDesk, it does not stop the service process either...

And that, to me, is a bug because normally you would keep a system-wide service running only if it's useful otherwise it should be stopped with UI. I know I don't want to report that bug to anydesk but if possible you can avoid that.

**Comment by rustdesk** [comment]
Windows users proposed this issue laso

**Comment by dpantel** [comment]
@rustdesk 

I'm a little confused.  Did you decided to keep the linux systemd service enabled and running even when RustDesk "service is not running"?

If so, what is the reason to keep the systemd service active and taking up resources?

Thanks

**Comment by rustdesk** [comment]
> deb

In milestone already, https://github.com/rustdesk/rustdesk/discussions/918#discussioncomment-3289105

**Comment by TechD123** [comment]
Hi, I'm a bit confused about the current behavior. Is RustDesk (.deb on Linux) supposed to be making hundreds of DNS requests a week, even when the GUI is not open? There is no tray icon displayed and I wasn't aware of RustDesk's activity until I looked through my DNS logs. Feel like this background activity should be disabled by default, as this is akin to malicious behavior.

If these constant network connections are indeed the intended/default behavior, is it now possible to stop this service via the GUI, so it is only active when the GUI is open? I only want the device to be remote-controlled when the GUI is open (or if a tray icon were to be shown). From the conversation above, it seemed like manually disabling rustdesk via systemctl was necessary in the past.
