### ISSUE TITLE
No need password

### ISSUE THREAD

**Issue by Ericliu68** [rustdesk/rustdesk#380]
mac连接windows
mac is client，windows is server，
mac 输入对方的id，点击连接，不需要密码等10几秒就可以了
mac enter the id of the other party, click connect, no password is required and wait for 10 seconds.

**Comment by rustdesk** [comment]
Two possible situations.
1, The remote side clicked "Accept" button.
2, You chose to remember password at your last connection.

**Comment by rustdesk** [comment]
Can you help record with a video?

**Comment by rustdesk** [comment]
@Ericliu68 What happend? You deleted your reply, 

> first connect，and no clicked "Accept" button， and no remember

**Comment by rustdesk** [comment]
No reply
