### ISSUE TITLE
Strange keyboard issue with VMware and Thunderbird

### ISSUE THREAD

**Issue by FCrane** [rustdesk/rustdesk#3801]
### Bug Description

Hi!

I've encountered a strange keyboard issue when remote controlling a machine where a VMware virtual machine is running: when using Thunderbird in this VMware, the left Ctrl and Shift keys do not work in combination with mouse clicks when using them for multiple selections of list items. E.g. when I want to select a couple of emails in the Inbox by selecting one, holding shift and clicking the last, it does not work. If I use the right Shift key, it works as expected. Same applies to the left Control key: when holding it down and clicking some emails (or folders in the folder tree), all the clicked items should be selected, but it does not work. Using the right Control key works as expected.

Really strange, because Shift and Control generally work in Thunderbird in the VMware. It's just the combination of left Shift / Control with a left mouse button click that does not work. Using Left Shift + Arrow Down for example also works for selecting. The keys also work correctly in other programs, e.g. Explorer windows, where selection works as expected with the left keys.

Maybe this is not even a RustDesk Issue but should be fixed by Thunderbird developers, but on the other hand it works fine with other remote control software (e.g. Parsec). So maybe it still is a key mapping issue? I'm using "Map mode", which is the only one that works correctly inside the VMware ("Legacy" has problems with stuck German Umlaute and "Translate" does not produce any keystrokes at all inside the VMware).

Thanks!

### How to Reproduce

See bug description.

### Expected Behavior

Default function of left Shift and Control when selection list items in Thunderbird.

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.2.0 Latest Nightly

### Screenshots

n/a

**Comment by rustdesk** [comment]
so use map mode please

**Comment by FCrane** [comment]
Sorry, I was unclear: "Map mode" shows the issue I described! It's just the only mode where the rest works...

**Comment by rustdesk** [comment]
Does work without vmware?

**Comment by FCrane** [comment]
Sorry, I do no that Thunderbird installed on the remote computer outside VMware - maybe someone else has and can test this?

**Comment by rustdesk** [comment]
> maybe someone else has and can test this?

close before some one can confirm above.

**Comment by FCrane** [comment]
I can now confirm that it works fine outside the VMware, but not inside the VMware. Seems to be a keyboard mapping issue inside VMware machines (like the old one concerning the German Umlaute, etc.)

BTW: "Mouse Back" and "Mouse Forward" buttons also don't work inside the VMware. Outside they work.

**Comment by FCrane** [comment]
@rustdesk: so what about opening this issue again?
