### ISSUE TITLE
transfer file and chat can not work after install, runing service model on windows 10 (Sciter version broken)

### ISSUE THREAD

**Issue by Frankzhang74** [rustdesk/rustdesk#3810]
### Bug Description

I build rustdesk (version: 1.2.0) for windows, I have tried many times. windows 10 new system, without a firewall or virus protection software, The issue are as follows:
1. if i use “cargo run”, all work well.
2. if i istall by the install button of rustdesk window, transfer file can not work, and if send message by chat, the chat window (receiver) don't open

### How to Reproduce

1. new windows 10
2. use "cargo run" command, rustdesk all function work well.
3. i istall by the install button of rustdesk window, transfer file can not work, and if send message by chat, the chat window (receiver) don't open

### Expected Behavior

Rustdesk runing on service model, transfer and chat can not work

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

![图片](https://user-images.githubusercontent.com/55676747/228139109-8894070e-1cc0-4b5a-807e-939de380b77d.png)

**Comment by rustdesk** [comment]
#763

**Comment by Frankzhang74** [comment]
@rustdesk , thands for you answer, i build successed. i use "cargo run" and "cargo build --relase" to runing, rustdesk work well, only i use install button of rustdesk window to install, after install rustdesk runing on service model, i find transfer and chat can not work, please check when you have time.

**Comment by rustdesk** [comment]
@Kingtous

**Comment by rustdesk** [comment]
Sciter version broken

**Comment by rustdesk** [comment]
#763
