### ISSUE TITLE
Building vcpkg with command (git checkout 2021.12.01) according to the rustdesk build instructions fails on Windows, Git-Bash.

### ISSUE THREAD

**Issue by Dolphi2** [rustdesk/rustdesk#3817]
### Bug Description

The guide at https://rustdesk.com/docs/en/dev/build/windows/
for creating an environment to build rustdesk on Windows should be fixed.

Building version 2021.12.01 of vcpkg on Windows, git-bash, fails with error:

Failed to download mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst

The dependency package,  mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst,  for vcpkg version 2021.12.01 does not exist in any of the repositories that the build process of vcpkg uses.

I was able to build vcpkg, with alternate command:
git checkout 2022.02.23 (instead of git checkout 2021.12.01 that the guide suggests.)

and eventually complete the build of rustdesk with that slightly newer version of vcpkg.

### How to Reproduce

Follow the build instructions for building vcpkg
git clone https://github.com/microsoft/vcpkg
cd vcpkg
git checkout 2021.12.01
cd ..
vcpkg/bootstrap-vcpkg.bat
export VCPKG_ROOT=$PWD/vcpkg
vcpkg/vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static

### Expected Behavior

Successful build of vcpkg

### Operating system(s) on local side and remote side

Windows11

### RustDesk Version(s) on local side and remote side

Any

### Screenshots

![image](https://user-images.githubusercontent.com/5039379/228271410-3d48cf0b-a6e3-44ee-bcb3-c9f553a96d67.png)

**Comment by rustdesk** [comment]
#763
