### ISSUE TITLE
failed to build on Windows 10 "failed to select a version for `bitflags`."

### ISSUE THREAD

**Issue by alexmacd1** [rustdesk/rustdesk#383]
When I try to compile a program for Windows, I get this message. I tried on two computers, both running Windows 10 LTSC x64

```
    Updating git repository `https://github.com/open-trade/cpal`
    Updating crates.io index
error: failed to select a version for `bitflags`.
    ... required by package `alsa v0.6.0`
    ... which satisfies dependency `alsa = "^0.6"` of package `cpal v0.13.4 (https://github.com/open-trade/cpal#3a305696)`
    ... which satisfies git dependency `cpal` of package `rustdesk v1.1.6 (E:\myproj\rustdesk)`
versions that meet the requirements `^1.3.2` are: 1.3.2

all possible versions conflict with previously selected packages.

  previously selected package `bitflags v1.3.1`
    ... which satisfies dependency `bitflags = "^1.0.3"` (locked to 1.3.1) of package `bindgen v0.59.1`
    ... which satisfies dependency `bindgen = "^0.59"` (locked to 0.59.1) of package `magnum-opus v0.3.4-2 (https://github.com/open-trade/magnum-opus#ad083616)`
    ... which satisfies git dependency `magnum-opus` (locked to 0.3.4-2) of package `rustdesk v1.1.6 (E:\myproj\rustdesk)`

failed to select a version for `bitflags` which could resolve this conflict
```

**Comment by fufesou** [comment]
I see you build tag v1.1.6, you can try build master branch or other tag.
bitflags v1.3.2 is not attached with a version or commit tag, which may cause conflict.I'm not very sure about it, Cargo.lock should handle the dependencies correctly.)

**Comment by alexmacd1** [comment]
> I see you build tag v1.1.6, you can try build master branch or other tag. bitflags v1.3.2 is not attached with a version or commit tag, which may cause conflict. But I'm not very sure about it, Cargo.lock should handle the dependencies correctly.

I don't know, but I downloaded the latest version of rustdesk (1.1.8). Even the archive downloaded from github was called `rustdesk-1.1.8.zip`. I didn't have any experience in cargo and rust before, so if you know how to solve the problem, you can write what commands I should execute and what changes to make to the files, if necessary.

**Comment by alexmacd1** [comment]
I don't know why, but when I ran the command `cargo build` from git bash instead of the standard Windows cmd, the program compiled

**Comment by rustdesk** [comment]
Everything is possbile.

**Comment by rustdesk** [comment]
https://rustdesk.com/docs/en/dev/build/windows/

**Comment by grummbeer** [comment]
https://github.com/rustdesk/rustdesk/discussions/763
