### ISSUE TITLE
Tooltip blocks clicks in file transfer window

### ISSUE THREAD

**Issue by taob** [rustdesk/rustdesk#3837]
### Bug Description

In file transfer window, the tooltip blocks clicks.

Local: MacOS Ventura
Remote: Windows 10

<img width="764" alt="Screenshot 2023-03-29 at 8 51 42 AM" src="https://user-images.githubusercontent.com/5474755/228597997-4b28147e-c566-4005-90cd-e06a2a79c41a.png">

### How to Reproduce

1. Start a file transfer.
2. Hover mouse pointer over "X" close button .
3. Wait for tooltip to appear.
4. Attempt to click close button.

### Expected Behavior

Tooltip should either pass click through to control underneath it, or tooltip should be positioned slightly above hotspot of mouse pointer.

### Operating system(s) on local side and remote side

MacOS Ventura -> Windows 10

### RustDesk Version(s) on local side and remote side

Unknown (where is "About RustDesk" menu item?)

### Screenshots

This section should not be mandatory, since screenshots can be attached to the other fields. Attaching duplicate screenshot here.

<img width="764" alt="Screenshot 2023-03-29 at 8 51 42 AM" src="https://user-images.githubusercontent.com/5474755/228599233-f50f667e-bb25-4223-9c73-a0e93ff0bd7a.png">

**Comment by rustdesk** [comment]
nightly build please.

**Comment by taob** [comment]
UI on the 1.2.0 nightly build has changed substantially. The "X" close button is much larger now, so it isn't completely blocked by the tooltip. The tooltip still does not pass through clicks, but it does disappear when clicked, so it's a little better. There are many new issues with the new UI, however, but I'll wait for the stable build first since I expect most of them to be fixed by then. :)

<img width="606" alt="Screenshot 2023-03-29 at 9 29 24 AM" src="https://user-images.githubusercontent.com/5474755/228606593-82cbab08-c83e-4476-a925-e4a4adb3997c.png">

**Comment by rustdesk** [comment]
@NicKoehler @grummbeer

**Comment by rustdesk** [comment]
> many new issues

Write down please.

**Comment by grummbeer** [comment]
Tested with master on Windows, tooltip doesn’t block the "X".

wait … what exacly is the issue here?

@taob You want click the "X" but you can’t because the toolip prevents this?

**Comment by taob** [comment]
@grummbeer: Yes, in version 1.19 (MacOS Ventura), the tooltip blocks the X and I cannot click through it. I can work around it by clicking the X before the tooltip pops up.

The UI has changed in the 1.20 nightly build, so while the problem is still there (can't click through a tooltip), it is not as serious because the X button is much larger and always reachable, as you say.

I have temporarily reverted back to 1.19 in the meantime since there are some serious bugs with 1.20 that make it almost unusable. I'll submit more bug reports when I have more time soon.
