### ISSUE TITLE
Menubar pin button doesn't appear to do anything & Can't hide/move the expand button

### ISSUE THREAD

**Issue by Samius12** [rustdesk/rustdesk#3842]
### Bug Description

Is there an existing issue for this?
- [x]  I have searched the existing ones - no match

Several points - They seem kind of related
1. There is a pin button. This does not appear to do anything. No matter if it is checked or unchecked it does not  autohide, nor can you move the menubar

![image](https://user-images.githubusercontent.com/126451912/228689854-526b9ecc-165a-44fe-a7bd-163b19b05361.png)

2. The tiny collapsible thing moves separately from it
![image](https://user-images.githubusercontent.com/126451912/228690038-a2e1459d-9758-4254-98c6-547d2fe4acb4.png)
![image](https://user-images.githubusercontent.com/126451912/228690110-a68fb69b-11f2-4484-9b4b-aca94ff09105.png)

3. The tiny collapsible thing on ultrawide monitors (e.g. 2560 x 1080) cannot be moved to the corners but stops around 1/3 the way to the left or right. It cannot be moved to the bottom corners or hidden either

### How to Reproduce

1. Download latest nightly on both devices
2. Click the update option
3. Join/connect two windows pcs on nightly

### Expected Behavior

1. Can move menu bar
2. Can hide menu  bar fully like non-nightly version (e.g. useful if you don't want it to appear during video calls)
3. Can hide the tiny expand button or move it to a corner

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

for remote - nightly/ for server - regular/ for local - nightly || All on windows 10

### Screenshots

Screenshots attached above

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
Thanks for you feedback.

1. Pin button. There's a bug for triggering autohide. https://github.com/rustdesk/rustdesk/pull/3881
2. This is intended.
3. This is intended.
```dart
        if (widget.fractionX.value < 0.35) {
          widget.fractionX.value = 0.35;
        }
        if (widget.fractionX.value > 0.65) {
          widget.fractionX.value = 0.65;
        }
```
https://github.com/rustdesk/rustdesk/blob/d56f92eaac5fb0abd076bd3ee9aa42a9e758818d/flutter/lib/desktop/widgets/remote_toolbar.dart#L2179

https://user-images.githubusercontent.com/13586388/229273403-952a7dd6-06ef-4bd3-a8ab-d10c4d6fe4e0.mp4

I'm not very sure the second and third point can be improved if it behave like what you've methioned.

**Comment by rustdesk** [comment]
👍

**Comment by rustdesk** [comment]
Let's keep our intended.
