### ISSUE TITLE
--password or --get-id not working

### ISSUE THREAD

**Issue by djordans** [rustdesk/rustdesk#3848]
### Bug Description

Calling rustdesk from the command line with the --password or --get-id parameters has no effect

### How to Reproduce

"C:\Program Files\RustDesk\rustdesk.exe" --get-id > nothing

"C:\Program Files\RustDesk\rustdesk.exe" --password x26x26x > nothing

### Expected Behavior

"C:\Program Files\RustDesk\rustdesk.exe" --get-id  > 1326646497

"C:\Program Files\RustDesk\rustdesk.exe" --password x26x26x > set permanent password

### Operating system(s) on local side and remote side

all version

### RustDesk Version(s) on local side and remote side

all version

### Screenshots

![rustdesk_64fz6f54z](https://user-images.githubusercontent.com/5314498/228804712-346527df-1015-4a54-a484-56bcd08d845b.png)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/blob/d3e3c3999751e86167fd337804b954aad1c57398/src/main.rs#L3
