### ISSUE TITLE
No Sound for screen recording

### ISSUE THREAD

**Issue by imsoso** [rustdesk/rustdesk#3849]
### Bug Description

Click 「开始录屏」 button
Open the recorded file
No sound, the picture works fine.
The sound is playing well while remoting
But not working after recorded.

### How to Reproduce

like I said.

### Expected Behavior

Sound in webm file

### Operating system(s) on local side and remote side

Windows 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.19

### Screenshots

【金山文档】 c166254901_20230330182715
https://kdocs.cn/l/ckNCmu1OCAm1

**Comment by rustdesk** [comment]
no plan shortly.
