### ISSUE TITLE
ID no exists on windows

### ISSUE THREAD

**Issue by irfan11111111** [rustdesk/rustdesk#385]
When I try to connect to ubuntu 18.0.4 computer on an Windows 10 computer, rustdesk reported " ID no exists ". The problem showed suddenly after normally operating 16 days ago.

**Comment by rustdesk** [comment]
I migrated the server yesterday，but forgot to stop the original server, so that your ubuntu and windows connected to different servers. I just stopped the original server.

**Comment by irfan11111111** [comment]
> I migrated the server yesterday，but forgot to stop the original server, so that your ubuntu and windows connected to different servers. I just stopped the original server.

My local rustdesk still reported " ID no exists ".  Do I need to restart the rustdesk on remote ubuntu system?

**Comment by rustdesk** [comment]
> restart

Just do it

**Comment by grummbeer** [comment]
@irfan11111111 solved?
