### ISSUE TITLE
App won't install on android 

### ISSUE THREAD

**Issue by nikunjkumarnakum** [rustdesk/rustdesk#386]
I have android 10 running on my redmi,
But it won't install says device is incompatible with this version so i tried rest of the previous versions but no use.
And searching for the app on play store don't provide any results idk why only way it opens is by using link on website.

**Comment by rustdesk** [comment]
I only built ARM64

**Comment by nikunjkumarnakum** [comment]
In future rustdesk will support other arm hardware?

**Comment by rustdesk** [comment]
arm32 ready in nightly build
