### ISSUE TITLE
Ubuntu 23.04(beta) Install/Dependencies Error

### ISSUE THREAD

**Issue by area51pilot** [rustdesk/rustdesk#3860]
### Bug Description

Clean install on Ubuntu 23.04 beta in XORG environment.
Unable to install due to pulse audio dependencies
Ignored pulseaudio and installed via: sudo dpkg -i --ignore-depends=pulseaudio rustdesk-1.1.9.deb

Package installed but with python errors:

> Setting up rustdesk (1.1.9) ...
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
dpkg: error processing package rustdesk (--install):
 installed rustdesk package post-installation script subprocess returned error exit status 1
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1.1ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu5) ...
Errors were encountered while processing:
 rustdesk

### How to Reproduce

Install on Ubuntu 23.04 using the following command: sudo dpkg -i --ignore-depends=pulseaudio rustdesk-1.1.9.deb

### Expected Behavior

Rustdesk application starts with no errors

### Operating system(s) on local side and remote side

Ubuntu 23.04(beta)

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![Screenshot from 2023-03-31 10-03-08](https://user-images.githubusercontent.com/9905239/229157684-052f052c-329f-4417-9487-2c2ec67ca3df.png)

### Additional Context

Remote input lags severely or stops working and Rustdesk crashes.

**Comment by rustdesk** [comment]
fixed in master branch.
