### ISSUE TITLE
Windows to Mac OS: Command-Tab key combo (Windows-Tab) to switch between open apps constantly scrolls to end of list

### ISSUE THREAD

**Issue by godzfire** [rustdesk/rustdesk#3863]
### Bug Description

Rustdesk 1.1.9. Windows 10 PC remoting to Mac OS Mont 12.6.4. When using Windows-Tab which emulates Command-Tab on the Mac to switch between open apps it will constantly scrolls to end of the app list so you can't choose. It's like the forward key is stuck down. It also closes the list if you let go of the keys.

On TeamViewer or Anydesk it does the proper functionality of simply opening and keeping open the app switch list and then letting you either use the Tab key or the mouse to select the app you want.

### How to Reproduce

From a Windows PC remote to a Mac and try to use the Windows Tab combo to emulate Command Tab

### Expected Behavior

App list shows up and stays selected on the current app, instead of scrolling the list all the way to the right.

### Operating system(s) on local side and remote side

Windows -> Mac

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

Not able to capture screenshot.

**Comment by rustdesk** [comment]
try out nightly build please

**Comment by godzfire** [comment]
I cannot try 1.2.0 because of the [Bug] Screen Recording permission invalid on macOS #3261 (https://github.com/rustdesk/rustdesk/issues/3261), where Rustdesk will keep erroring out and saying "the program is not open".

**Comment by godzfire** [comment]
<img width="260" alt="SS 2023-04-02 at 9 45 12 PM" src="https://user-images.githubusercontent.com/2067820/229399882-ead3fd8d-1b27-4f69-a9d1-2a0fb7fb421a.png">
