### ISSUE TITLE
Forced out of Remote Desktop when disconnecting mouse on Android

### ISSUE THREAD

**Issue by Typhonling** [rustdesk/rustdesk#3864]
### Bug Description

When I disconnect the mouse on Android, the remote desktop is automatically disconnected.

### How to Reproduce

Connecting the mouse
Connecting to a remote desktop
Disconnecting the mouse

### Expected Behavior

Do not exit Remote Desktop after disconnecting the mouse.

### Operating system(s) on local side and remote side

Android 13 > Windows 10

### RustDesk Version(s) on local side and remote side

1.1.10-1 > 1.1.9

### Screenshots

.

**Comment by rustdesk** [comment]
how about nightly build on both side?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/tag/nightly

**Comment by Typhonling** [comment]
Thanks. I'll try.
