### ISSUE TITLE
Stuck in waiting for image in GDM login screen [Android -> Linux (Gnome)]

### ISSUE THREAD

**Issue by NicKoehler** [rustdesk/rustdesk#3865]
### Bug Description

On the last nightly build from today I cannot longer login into my desktop

### How to Reproduce

Install the last nighly update as of 31.03.2023

### Expected Behavior

See the login screen

### Operating system(s) on local side and remote side

Android -> Linux

### RustDesk Version(s) on local side and remote side

Nighly

### Screenshots

![image](https://user-images.githubusercontent.com/53040044/229204058-ba1e0ad1-89d0-47d7-9fc0-4bfebf1b76ed.png)

### Additional Context

After I log in manually I can see the screen

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
@NicKoehler Thanks for your feedback. 

I've reproduced this issue by disable the Wayland login screen.
https://rustdesk.com/docs/en/manual/linux/#login-screen

Is the issue same to you? Or can you please run 
```bash
$ grep -i 'Wayland' /etc/gdm3/custom.conf /etc/gdm/custom.conf
```

**Comment by rustdesk** [comment]
@NicKoehler could you try out the new build?

**Comment by NicKoehler** [comment]
> @NicKoehler Thanks for your feedback. 
> 
> I've reproduced this issue by disable the Wayland login screen.
> https://rustdesk.com/docs/en/manual/linux/#login-screen
> 
> Is the issue same to you? Or can you please run 
> ```bash
> $ grep -i 'Wayland' /etc/gdm3/custom.conf /etc/gdm/custom.conf
> ```

I have an nvidia graphic card and currently wayland is disabled by default

**Comment by NicKoehler** [comment]
> @NicKoehler could you try out the new build?

The new build is working as expected

**Comment by rustdesk** [comment]
👍
