### ISSUE TITLE
When connected to a remote computer, accented letters cannot be typed on Czech keyboard on the local computer

### ISSUE THREAD

**Issue by vadamovsky** [rustdesk/rustdesk#3868]
### Bug Description

After connecting to a remote computer, the Czech keyboard stops working properly on the local computer. Some Czech letters contain a comma or a caron. Letters with a comma are entered by pressing the [=] key (to the left of the Backspace key) and then pressing the letter to get the comma. To write a caron, press SHIFT + [=] followed by the given letter to get the caron.

On a local computer, when connected to a remote computer, the [=] key stops working altogether, so some letters cannot be typed at all. In some cases, writing Czech characters does not work correctly even on the remote computer.

### How to Reproduce

1. Install Czech and English keyboard layout.
2. Start RustDesk and connect to a remote computer.
3. Select Czech keyboard in Windows on the local machine.
4. Open Notepad.
5. Press key [=] and then key "e".
6. You see "e". But you should get "é".
7. Press Shift + key [=] and then key "e".
8. You see "e". But you should get "ě".
9. Switch to remote computer.
10. Try to type the same letters.
11. Sometimes it works, sometimes you get "´é" and "ˇé". But you should get "é" and "ě".

### Expected Behavior

I would expect that after the connection there will be no change in the functioning of the [=] key on the Czech keyboard on the local computer for writing letters with a comma and a caron.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

![scr](https://user-images.githubusercontent.com/5308076/229212576-76f2fff9-852b-4011-b04d-550faac641c2.png)

**Comment by rustdesk** [comment]
#1547

**Comment by vadamovsky** [comment]
I confirm, this problem is fixed in the latest nightly build.

**Comment by yardstudio** [comment]
I have this issue still, and I am using latest downloaded versions

**Comment by fufesou** [comment]
@yardstudio @morphx666  Hi, thanks for your feedback.

I cannot reproduce this issue.

Can you please give me more details or how to reproduce?

I've tried 1.2.3(win) -> 1.2.3(win).

"Legacy mode", "Map mode" and "Translate mode" do not have this issue.
Thought the remote results "/é" when pressing "=" + "e" using "Legacy mode".
