### ISSUE TITLE
I can't control the android with the mouse on the macbook, he doesn't seem to have any effect, I can only use the blue buttons

### ISSUE THREAD

**Issue by cengzhijie3** [rustdesk/rustdesk#3871]
### Bug Description

I can't control the android with the mouse on the macbook, he doesn't seem to have any effect, I can only use the blue buttons

### How to Reproduce

use macbook to control android and use mouse to control it

### Expected Behavior

can't control the android with the mouse on the macbook, he doesn't seem to have any effect, I can only use the blue buttons

### Operating system(s) on local side and remote side

mac os13.3 > androdid13

### RustDesk Version(s) on local side and remote side

latest nightly version->android version

### Screenshots

<img width="1381" alt="截圖 2023-04-01 上午9 08 18" src="https://user-images.githubusercontent.com/89333400/229259189-84d1ac89-6e68-4a73-986c-795334820928.png">
<img width="1381" alt="截圖 2023-04-01 上午9 08 23" src="https://user-images.githubusercontent.com/89333400/229259207-1e2c1b38-a514-44f5-94ea-4ff17cdd65d5.png">

**Comment by rustdesk** [comment]
@grummbeer do you have this issue from your linux to android?

**Comment by rustdesk** [comment]
@cengzhijie3 now your https://github.com/rustdesk/rustdesk/issues/3802 is working?

**Comment by cengzhijie3** [comment]
I don't know, but actually, i could not use my mouse to control my android phone but I could use my android phone to control my MacBook because it has an option I could choose touch screen function to use

**Comment by rustdesk** [comment]
> I don't know, but actually, i could not use my mouse to control my android phone but I could use my android phone to control my MacBook because it has an option I could choose touch screen function to use

I meant your last issue https://github.com/rustdesk/rustdesk/issues/3802

**Comment by cengzhijie3** [comment]
i think it is working

**Comment by rustdesk** [comment]
I guess you can also make this work soon. Good luck.

**Comment by grummbeer** [comment]
> @grummbeer do you have this issue from your linux to android?

no, working.

@cengzhijie3 It may sound silly, but … do your permissions look like this?

![mobile-permissions-input-control](https://user-images.githubusercontent.com/67791701/229285932-0f9107cd-4a4a-4bf9-8e77-c4e8d9b295f3.png)

**Comment by rustdesk** [comment]
@grummbeer Thanks
@cengzhijie3 you have created too many issues even without any search and attemption. Again, `github discussions` is not a support forum.
