### ISSUE TITLE
Please add ipv6 resolution to rustdesk, now rustdesk only recognises ipv4 addresses, not ipv6 address

### ISSUE THREAD

**Issue by cengzhijie3** [rustdesk/rustdesk#3874]
### Bug Description

Please add ipv6 resolution to rustdesk, now rustdesk only recognises ipv4 addresses, not ipv6 address
The domain name resolves to ipv6 but is still not recognizable, while the domain name resolves to ipv4 and is directly recognizable.

### How to Reproduce

Please add ipv6 resolution to rustdesk, now rustdesk only recognises ipv4 addresses, not ipv6 address

### Expected Behavior

Please add ipv6 resolution to rustdesk, now rustdesk only recognises ipv4 addresses, not ipv6 address
The domain name resolves to ipv6 but is still not recognizable, while the domain name resolves to ipv4 and is directly recognizable.

### Operating system(s) on local side and remote side

mac os13.3 > androdid13

### RustDesk Version(s) on local side and remote side

latest nightly version->android version

### Screenshots

<img width="912" alt="截圖 2023-04-01 上午10 12 21" src="https://user-images.githubusercontent.com/89333400/229261281-875c3679-f13b-4a82-b798-8462fbf2bade.png">
<img width="912" alt="截圖 2023-04-01 上午10 12 06" src="https://user-images.githubusercontent.com/89333400/229261286-2ece15ed-20e1-4daf-a1df-855faaab5d9b.png">
<img width="912" alt="截圖 2023-04-01 上午10 15 49" src="https://user-images.githubusercontent.com/89333400/229261303-0a21a4d6-ae29-466b-a7e8-186a28c31831.png">
<img width="912" alt="截圖 2023-04-01 上午10 13 09" src="https://user-images.githubusercontent.com/89333400/229261313-21d1d811-226e-45f0-879f-000791d9ed75.png">

**Comment by rustdesk** [comment]
if you continue to repeat duplicate issue, i will block you.
