### ISSUE TITLE
Failed to connect via rendezvous server: Please try later

### ISSUE THREAD

**Issue by Noexpert** [rustdesk/rustdesk#388]
I keep receiving this message when trying to connect from a Win10 to a Win10 machine. I've tried both the portable and installed version.

I can connect locally on LAN over WiFi, but not over WAN to a remote machine.

**Comment by rustdesk** [comment]
Can you tell me the remote machine id? and which coutnry?

**Comment by Noexpert** [comment]
This was a firewall issue, so it's now resolved.
By the way, can the app be allowed to connect without the remote machine accepting the connection?

**Comment by maofig** [comment]
Hello. I have been using RustDesk to connect via WiFi from a Macbook (MacOs 12.5) to 3 different Win10 machines successfully (all the machines have RustDesk version 1.1.9 installed).

However, recently one of the Win10 machines is not connecting any more and it displays this error message "Failed to connect via rendezvous server, please try later". I have also tried to connect RustDesk from this Win10 machine to the Macbook, but it is not connecting either. The machine ID is 453 837 763 and the country is Colombia. It is important to mention that I can still connect to the other two Win10 machines without any problem.

**Comment by davidpencoba** [comment]
This case also occurs where the client PC cannot be remote. The PC client uses Windows 7 and the server uses Windows 10

**Comment by JesusSanRey** [comment]
ERROR failed to connect to rendezvous server
Can you tell me the remote machine id? and which country?
Mexico 1 428 919 312

**Comment by rustdesk** [comment]
Our public servers are not stable lately.

**Comment by ShoaibHassan18** [comment]
Hello team, I have just started Rusk desk for my organization, when i test connecting two different systems on public network , i get the following response; ERROR failed to connect to rendezvous server

Please support, I am from Pakistan and Remote Desktop ID is 1928149039

**Comment by ShoaibHassan18** [comment]
Hello team, I have just started Rusk desk for my organization, when i test connecting two different systems on public network , i get the following response; ERROR failed to connect to rendezvous server

Please support, I am from Pakistan and Remote Desktop ID is 1928149039

**Comment by ohidxy** [comment]
> This was a firewall issue, so it's now resolved. By the way, can the app be allowed to connect without the remote machine accepting the connection?
> 
> EDIT: unattended connection works with password.

I actually did allow all ports. Checked with Telnet. Still the same errors. Any idea?

**Comment by JfiungoM** [comment]
Hi team, I have the same issue when try to connect to win7 VM(Virtualbox) hosted by Ubuntu. With anydesk or DWservice, it works perfect.

**Comment by sneaker-net** [comment]
RustDesk v1.1.9
macOS Ventura 13.3 to macOS Ventura 13.3
UK 🇬🇧

<img width="512" alt="RustDesk-3" src="https://user-images.githubusercontent.com/73359050/230050352-1c3f7c4c-8345-4059-a2e8-82721b022f9e.png">
<img width="512" alt="RustDesk-4" src="https://user-images.githubusercontent.com/73359050/230050396-601a42fc-6129-4fd5-a9ff-d7b96d1514dc.png">
<img width="512" alt="RustDesk-2" src="https://user-images.githubusercontent.com/73359050/230050438-b93cc6a0-1ba2-4ac7-87e9-66633caa00ab.png">
<img width="512" alt="RustDesk-1" src="https://user-images.githubusercontent.com/73359050/230050454-e2f0c1fb-b8b0-4c2c-92ec-a1cf47b366aa.png">

**Comment by maprfsousa** [comment]
Estou com o mesmo problema acima referido. Erro de falha ao conectar ao servidor de rendezvous. Ou desktop remoto está offline. Uma ligação existente foi forçada a fechar pelo anfitrião remoto. (os error 10054).
Como posso resolver.
Preciso de uma ajuda vossa, obrigado

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1597#issuecomment-1427040649

**Comment by porteusconf** [comment]
### Workaround/Fix On win10 (for me ;-)
Win10 on home wifi trying to connect to remote linux host at work, I also  was getting ` Failed to connect via rendezvous server...` after a long timeout. The fix for me was to turn off the firewall on win10 at home: Settings : (search for "firewall")...
After turning off win10 firewall, RustDesk connected immediately. I did not have to change firewall settings in my wifi router.
Microsoft Windows [Version 10.0.19045.3930] running RustDesk v 1.2.3

**Comment by edinsonciganda** [comment]
![rustdesk](https://github.com/rustdesk/rustdesk/assets/1062876/a28dc4ae-174d-4ed8-a77c-049135e01389)


nesesito ayuda no conecta rustdesk esta todo liberado firemware y router
