### ISSUE TITLE
I don't know why the latest version I just downloaded shows the other side of the MacBook when my Android phone has rust desk turned on.

### ISSUE THREAD

**Issue by cengzhijie3** [rustdesk/rustdesk#3882]
### Bug Description

I don't know why the latest version I just downloaded shows the other side of the MacBook when my Android phone has rust desk turned on.

### How to Reproduce

I don't know why the latest version I just downloaded shows the other side of the MacBook when my Android phone has rust desk turned on.

### Expected Behavior

I don't know why the latest version I just downloaded shows the other side of the MacBook when my Android phone has rust desk turned on.

### Operating system(s) on local side and remote side

mac os13.3 > androdid13

### RustDesk Version(s) on local side and remote side

latest nightly version->android version

### Screenshots

![WechatIMG25](https://user-images.githubusercontent.com/89333400/229273765-176f9b74-f6aa-4a57-9bbd-6966ca1faac6.jpeg)
<img width="1381" alt="截圖 2023-04-01 下午3 58 14" src="https://user-images.githubusercontent.com/89333400/229273774-2c972c15-2940-44c0-b2a2-e93f95080f81.png">

**Comment by rustdesk** [comment]
i do not know either.
