### ISSUE TITLE
File transfer GUI

### ISSUE THREAD

**Issue by giuliovale** [rustdesk/rustdesk#3885]
### Bug Description

Text in some columns overlaps text in others

### How to Reproduce

See screenshot

### Expected Behavior

No overlap

### Operating system(s) on local side and remote side

Windows 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

Nightly build ->Nightly build

### Screenshots

![image](https://user-images.githubusercontent.com/6909743/229278331-7569b501-a36c-4f8c-8809-9c330bad9a5c.png)

**Comment by rustdesk** [comment]
@grummbeer Wondering if it is necessary to fix this extreme case.

**Comment by rustdesk** [comment]
@NicKoehler there are also some other overflows, could you follow up?

<img width="670" alt="Screenshot 2023-04-01 at 17 54 36" src="https://user-images.githubusercontent.com/71636191/229279287-5e0d1fe5-e537-4925-a79a-13b714955820.png">

**Comment by NicKoehler** [comment]
I can try to fix this later

**Comment by NicKoehler** [comment]
The only solution I came up with is to limit the width of the windows to a minimum size, every other solution makes the UI not readable. What do you think @rustdesk @grummbeer ?

**Comment by grummbeer** [comment]
You are right.

At the moment there is a minimum width, even if the file list container is scrollable 

![file-manager-minimum-width](https://user-images.githubusercontent.com/67791701/229289543-6a10321a-d555-486a-b2be-94220e8bc687.png)

The toolbars, path, etc are affected. Transfer list becomes absurdly small.

![file-manager-minimum-width-smaller](https://user-images.githubusercontent.com/67791701/229289596-a5df5f66-b934-4cb7-8e64-ece07aad98ae.png)

Making this fully responsive is not that easy … some points

- Transfer list floating/overlay
- Overflowed items in toolbar goes to the "three dot" menu
- New "three dot" pulldown for path stuff
- When smaller as the minimum width, it should turn into the mobile view.

**Comment by grummbeer** [comment]
> limit the width of the windows to a minimum size

Also related on translations, longer words needs more width.

**Comment by rustdesk** [comment]
@NicKoehler this icon looks bad in light theme.

![image](https://user-images.githubusercontent.com/71636191/229359903-c25bbc1a-b156-4c25-9693-c710267232d5.png)

**Comment by NicKoehler** [comment]
Mine looks like this.

<img width="130" alt="immagine" src="https://user-images.githubusercontent.com/53040044/229362816-110788bd-a651-483b-a080-91d943e9327d.png">

**Comment by rustdesk** [comment]
It looks bad on Windows, it is fine on mac.
