### ISSUE TITLE
Right edge of the screen can't be reached with mouse remotely

### ISSUE THREAD

**Issue by reyaz006** [rustdesk/rustdesk#3887]
### Bug Description

I think there was already such an issue with the bottom edge of the screen.

I see that it works similarly with the right edge of the screen.

### How to Reproduce

When remotely connected to Windows machine, minimize all windows and on the desktop, start mouse selection (blue rectangle) and move the mouse to the right side of the screen. It doesn't matter if you use full screen or adaptive screen - the selection will not reach the right edge of the desktop. You will notice 1-2 pixels that are left outside of the mouse selection.

### Expected Behavior

All screen pixels should be reachable with mouse.

### Operating system(s) on local side and remote side

Windows 11 -> Windows 8.1

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0

### Screenshots

![image](https://user-images.githubusercontent.com/6751344/229285111-32f03281-fd50-4d8f-b246-14d5544ff98c.png)

**Comment by rustdesk** [comment]
duplicate

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2883

**Comment by fufesou** [comment]
Hi, I've tested with remote 1920x1080.

The cusor position range should be (0, 0) - (1919, 1079).

And the prints are in the correct range.

![ASD](https://user-images.githubusercontent.com/13586388/230908447-3ab3850c-c51d-4d5f-b0a5-ffa0b260c504.png)

**Comment by fufesou** [comment]
Can you please upload a video to show your issue more clearly, thanks.

**Comment by rustdesk** [comment]
can taskbar be triggered if you move taskbar to left side or right side in fullscreen mode or non-fullscreen mode?

**Comment by fufesou** [comment]
I've tested Win and MacOS, the taskbar can be triggered.

For linux, the "Auto-hide" has another meaning.
![1681175855717](https://user-images.githubusercontent.com/13586388/231030280-53ed9817-e2cd-48d2-b010-1fb01c48c0be.png)

**Comment by fufesou** [comment]
@reyaz006 I know what you mean.

But I've tested mouse selection on local side and via the RustDesk control. They do not seem to have much difference.



![Untitled](https://user-images.githubusercontent.com/13586388/231032119-c9fbc7fa-a607-42cb-bf8b-e9b4007cb8d2.png)

Selection via RustDesk (left) vs Selection on local (right)
