### ISSUE TITLE
Installation problem Win7

### ISSUE THREAD

**Issue by Oszy88** [rustdesk/rustdesk#3889]
### Bug Description

Hi!

I got a problem when I want to install Rustdesk to a win 7 PC!
I want to install it while I remote controlled the PC with anydesk.

What am I do step-by-step:
- download the installer 
- start the installer, and klick install button 
- installing window open, I choose file path, and start install
- installation starting, Windows popup window ask the permission, I click yes, installation go forward
- after that no one happening, don't get a message about installation finished or something error, just rustdesk start and say that I must install it, because of UAC
- I checked the installation path, and only the empty folder there, no exe, or executable file.

Is there any solution for this installation problem??

Sorry for ma bad English, I hope you understand me! Thanks the answer!

### How to Reproduce

- download the installer 
- start the installer, and klick install button 
- installing window open, I choose file path, and start install
- installation starting, Windows popup window ask the permission, I click yes, installation go forward
- after that no one happening, don't get a message about installation finished or something error, just rustdesk start and say that I must install it, because of UAC
- I checked the installation path, and only the empty folder there, no exe, or executable file.

### Expected Behavior

I hope you can help me to install and use this very good software!

### Operating system(s) on local side and remote side

Windows 7

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![uac](https://user-images.githubusercontent.com/129609011/229298161-946a6d4b-3e3b-4bf8-9699-d0cce3930614.png)

### Additional Context

Don't have more information!

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/tag/nightly
