### ISSUE TITLE
Add ability to minimize to the System Tray

### ISSUE THREAD

**Issue by Noexpert** [rustdesk/rustdesk#389]
On Windows, it would be helpful to have the ability to minimize to the System Tray.

Especially as a way to set up unattended access, whereby Rustdesk can start at startup and minimized, without distracting the user or taking up space in the taskbar.

**Comment by AClon-official** [comment]
Me too

**Comment by rustdesk** [comment]
You can do it yourself, remove it from C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Startup

**Comment by Noexpert** [comment]
I've removed the shortcut from the Startup, but it didn't work.
What worked was:
(1) to manually create a new shortcut from the exe
(2) add the `--tray` flag
(3) place in the Startup folder

I think the problem with the default shortcut is that the `Start in:` is empty.
When you create the shortcut manually, the `Start in:` is populated with `"C:\Program Files\RustDesk"`.

**Comment by lijy91** [comment]
This can be achieved using tray_manager + window_manager, these two plugins support both windows, macos and linux.

https://github.com/leanflutter/tray_manager
https://github.com/leanflutter/window_manager

**Comment by tristan-k** [comment]
So is there a way to start rust minimized or do I have to rely on a thrid party software?

**Comment by Mossy93** [comment]
This would be great to have on Linux with Desktops that support it; for example KDE Plasma

**Comment by Zero3K** [comment]
The tray parameter is broken for me. It doesn't stay open in the system tray when I use it when running it on Windows 10.

**Comment by gusarg81** [comment]
Hi,

I would like this too, specially for Linux (KDE).

**Comment by IOTech17** [comment]
@rustdesk I would like to have this feature for Linux and windows. This will Allow to do unattended access when the agent is loaded at startup in the system tray.

Do you have an ETA?

**Comment by ixianhao** [comment]
> 我已经从启动中删除了快捷方式，但它没有用。 有用的是： （1）从exe手动创建一个新的快捷方式 （2）添加`--tray`标志 （3）放在启动文件夹中
> 
> 我认为默认快捷方式的问题是它`Start in:`是空的。 当您手动创建快捷方式时，`Start in:`会填充`"C:\Program Files\RustDesk"`.

这个参数会报错

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3395

**Comment by Dex321x** [comment]
Is there a way to minimize RustDesk to the try? I didn't get it working, but as the ticket was closed earlier, I thought it is implemented? But here, I can't minimize it.

**Comment by kingmustard** [comment]
I would also like the ability to minimise to the system tray (Windows 11).

**Comment by Avrution** [comment]
Still waiting on this.  Such a basic thing to be missing on a remote desktop app.

**Comment by softyoda** [comment]
Well since the issue is still not resolved, i vote we reopened it since all user seem to still waiting for such option (start minimized) to ever exist...
