### ISSUE TITLE
International Keyboard not usable - keymappings - german and us-english mappings

### ISSUE THREAD

**Issue by zash1958** [rustdesk/rustdesk#3896]
### Bug Description

The keyboard mapping is not really usable. The mappings of extra keys does not follow any known keyboard mapping. Also the input of signs like

\

is not possible

### How to Reproduce

Start a remote session and try to input the following key

\

### Expected Behavior

Correct keys an the remote machine

### Operating system(s) on local side and remote side

Archlinux x64 KDE to windows or even Linux

### RustDesk Version(s) on local side and remote side

1.2 nightly

### Screenshots

![Bildschirmfoto_20230402_154144](https://user-images.githubusercontent.com/7055809/229356591-b599634b-9e3e-4cdb-a7d7-d8d9b726ca81.png)

### Additional Context

Regardless of using english-us or german keyboard on the PC on this side

**Comment by langfingaz** [comment]
This might be related to issue #1892 where it is e.g. not possible to enter `{`.
