### ISSUE TITLE
Unable to unlock

### ISSUE THREAD

**Issue by evelynEdison** [rustdesk/rustdesk#39]
If the remote computer is locked, cannot enter the password via keyboard and cannot be unlocked, both computers are win10

**Comment by rustdesk** [comment]
Install it

**Comment by rustdesk** [comment]
https://www.ixigua.com/6960314189340475941?id=6961842623388582431&logTag=41b1db6eea98672a50bd

**Comment by evelynEdison** [comment]
Got it. Thanks
