### ISSUE TITLE
Nightly build empty screen on Mac OS Ventura 13.3 (and some windows with gpu)

### ISSUE THREAD

**Issue by SoftwareMagicIT** [rustdesk/rustdesk#3900]
### Bug Description

Sometimes they come back! Blank screen on MacOS Ventura 13.3. see #132

### How to Reproduce

Performe clean installation of Rustdesk 1.2.0 Nightly Build on MacOS Ventura 13.3 and launch it.

### Expected Behavior

Show main screen

### Operating system(s) on local side and remote side

MacOS Ventura

### RustDesk Version(s) on local side and remote side

1.2.0 Nightly Build

### Screenshots

No screenshot available at this time

### Additional Context

If move mouse, elements is presents because pointer of mouse change, only not showed

**Comment by TLCFEM** [comment]
Latest commit: 14e947e

```bash
./rustdesk-1.2.0-x86_64.AppImage 
load librustdesk.so failed

(rustdesk:299136): Gtk-WARNING **: 04:26:19.905: Theme parsing error: gtk.css:9112:19: negative values are not allowed.

(rustdesk:299136): Gtk-WARNING **: 04:26:19.905: Theme parsing error: gtk.css:9116:19: negative values are not allowed.

(rustdesk:299136): Gtk-WARNING **: 04:26:19.905: Theme parsing error: gtk.css:9164:19: negative values are not allowed.

(rustdesk:299136): Gtk-WARNING **: 04:26:19.906: Theme parsing error: gtk.css:9172:19: negative values are not allowed.
Gtk-Message: 04:26:19.980: Failed to load module "canberra-gtk-module"
Gtk-Message: 04:26:19.982: Failed to load module "pk-gtk-module"
Gtk-Message: 04:26:19.984: Failed to load module "canberra-gtk-module"
Gtk-Message: 04:26:19.985: Failed to load module "pk-gtk-module"
flutter: launch args: []
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'librustdesk.so': libnsl.so.1: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
#2      PlatformFFI.init (package:flutter_hbb/models/native_model.dart:150)
#3      initEnv (package:flutter_hbb/main.dart:108)
#4      runMainApp (package:flutter_hbb/main.dart:121)
#5      main (package:flutter_hbb/main.dart:102)
<asynchronous suspension>
```

**Comment by rustdesk** [comment]
@Kingtous

**Comment by Kingtous** [comment]
> 

I confirm the nightly build from our release page works well. Are you trying to build your own AppImage but forget to copy the library to the dest?

**Comment by TLCFEM** [comment]
> > Latest commit: [14e947e](https://github.com/rustdesk/rustdesk/commit/14e947e32d7252bf07f00bc0f805265edcc941bd)
> > ```shell
> > ./rustdesk-1.2.0-x86_64.AppImage 
> > load librustdesk.so failed
> > 
> > (rustdesk:299136): Gtk-WARNING **: 04:26:19.905: Theme parsing error: gtk.css:9112:19: negative values are not allowed.
> > 
> > (rustdesk:299136): Gtk-WARNING **: 04:26:19.905: Theme parsing error: gtk.css:9116:19: negative values are not allowed.
> > 
> > (rustdesk:299136): Gtk-WARNING **: 04:26:19.905: Theme parsing error: gtk.css:9164:19: negative values are not allowed.
> > 
> > (rustdesk:299136): Gtk-WARNING **: 04:26:19.906: Theme parsing error: gtk.css:9172:19: negative values are not allowed.
> > Gtk-Message: 04:26:19.980: Failed to load module "canberra-gtk-module"
> > Gtk-Message: 04:26:19.982: Failed to load module "pk-gtk-module"
> > Gtk-Message: 04:26:19.984: Failed to load module "canberra-gtk-module"
> > Gtk-Message: 04:26:19.985: Failed to load module "pk-gtk-module"
> > flutter: launch args: []
> > [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'librustdesk.so': libnsl.so.1: cannot open shared object file: No such file or directory
> > #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
> > #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
> > #2      PlatformFFI.init (package:flutter_hbb/models/native_model.dart:150)
> > #3      initEnv (package:flutter_hbb/main.dart:108)
> > #4      runMainApp (package:flutter_hbb/main.dart:121)
> > #5      main (package:flutter_hbb/main.dart:102)
> > <asynchronous suspension>
> > ```
> 
> I confirm the nightly build from our release page works well. Are you trying to build your own AppImage but forget to copy the library to the dest?

This is downloaded from CI/CD artifacts.

**Comment by TLCFEM** [comment]
Building it locally via docker creates a `liblibrustdesk.so` library if I remember correctly.

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
https://github.com/thkukuk/libnsl

it may miss in newest distro

**Comment by TLCFEM** [comment]
I am using f36, building with docker with commands in readme.

**Comment by TLCFEM** [comment]
> I am using f36, building with docker with commands in readme.

But it does not happen to local build, I downloaded the appimage from the release page.

**Comment by TLCFEM** [comment]
Full:

```bash
╭─[theodore@abyss]─[~/Downloads]                                                                             ()─[ 100%]─[ 1,15:47]
╰─ﬀ sha256sum ./rustdesk-1.2.0-x86_64.AppImage 
4f464a7cac0fac8b7a478088926d2495fc9610c321bdb0af4762a34177430e13  ./rustdesk-1.2.0-x86_64.AppImage
╭─[theodore@abyss]─[~/Downloads]                                                                             ()─[ 100%]─[ 1,15:47]
╰─ﬀ ./rustdesk-1.2.0-x86_64.AppImage 
load librustdesk.so failed

(rustdesk:196213): Gtk-WARNING **: 15:47:30.750: Theme parsing error: gtk.css:9112:19: negative values are not allowed.

(rustdesk:196213): Gtk-WARNING **: 15:47:30.750: Theme parsing error: gtk.css:9116:19: negative values are not allowed.

(rustdesk:196213): Gtk-WARNING **: 15:47:30.751: Theme parsing error: gtk.css:9164:19: negative values are not allowed.

(rustdesk:196213): Gtk-WARNING **: 15:47:30.751: Theme parsing error: gtk.css:9172:19: negative values are not allowed.
Gtk-Message: 15:47:30.879: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:47:30.882: Failed to load module "pk-gtk-module"
Gtk-Message: 15:47:30.888: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:47:30.890: Failed to load module "pk-gtk-module"
flutter: launch args: []
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'librustdesk.so': libnsl.so.1: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
#2      PlatformFFI.init (package:flutter_hbb/models/native_model.dart:150)
#3      initEnv (package:flutter_hbb/main.dart:108)
#4      runMainApp (package:flutter_hbb/main.dart:121)
#5      main (package:flutter_hbb/main.dart:102)
<asynchronous suspension>

```

**Comment by Kingtous** [comment]
> > ### Bug Description
> > Sometimes they come back! Blank screen on MacOS Ventura 13.3. see #132
> > 
> > ### How to Reproduce
> > Performe clean installation of Rustdesk 1.2.0 Nightly Build on MacOS Ventura 13.3 and launch it.
> > 
> > ### Expected Behavior
> > Show main screen
> > 
> > ### Operating system(s) on local side and remote side
> > MacOS Ventura
> > 
> > ### RustDesk Version(s) on local side and remote side
> > 1.2.0 Nightly Build
> > 
> > ### Screenshots
> > No screenshot available at this time
> > 
> > ### Additional Context
> > If move mouse, elements is presents because pointer of mouse change, only not showed
> 
> I do have the exact same problem with the most recent nightly build.
> https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64.dmg
> Version 1.2.0 (1.2.0)
> Ventura 13.3.1 (22E261)
> 
> 1.1.9 works as expected.
> 
> Can I somehow help to debug this?

any logs when running from your terminal?

**Comment by lxne** [comment]
> any logs when running from your terminal?

Strangely now it works.
I booted macOS in safe mode and now it works.
Maybe the system corrected something.

I will get back if the problem occurs again.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4490#issuecomment-1565995893 wondering if you can test the latest nightly build. We upgrade flutter to 3.10.1, it may solve it.

**Comment by lxne** [comment]
So far no issues on my intel macbook pro running Ventura 13.4 (22F66) and the most recent nightly.

**Comment by Keerp96** [comment]
Still having this issue even with latest nightly on Windows 10 (19042).
![Screenshot_1](https://github.com/rustdesk/rustdesk/assets/1152200/985e0a9e-848f-4e01-abe5-4b64af1bddc0)
