### ISSUE TITLE
Displays are not properly positioned when using nvidia meta mode with a different viewport. (ubuntu 22.04 with nvidia meta mode)

### ISSUE THREAD

**Issue by davidkisvari** [rustdesk/rustdesk#3906]
### Bug Description

If a display doesn't have other resolutions but the native one and nvidia meta mode is configured with a smaller viewport to set a smaller resolution, RustDesk will combine 2 displays as one and display them with the lower part cut off. This is not an issue with any other application, including Anydesk.

### How to Reproduce

Configure a meta mode with a smaller viewport in in nvidia settings, e.g. viewport in is 1920x1080, viewport out is 2560x1440. With 2 displays with the above example on native resolution they would appear normally, but with nvidia meta mode applied you still see individual displays listed, but they will be combined on the first one, with lower part cut off, and switching to 2nd display will show a blank one. 

### Expected Behavior

It should display 2 individual displays with their normal aspect ratio and resolution (which is the viewport in in this case) without any cut off.

### Operating system(s) on local side and remote side

Ubuntu 22.04 -> Ubuntu 22.04 (same with Windows 10 -> Ubuntu 22.04)

### RustDesk Version(s) on local side and remote side

1.2.0 nightly on both sides

### Screenshots

In the below example 2nd and 3rd displays are using nvidia meta mode. When 2nd display is selected it has both displays combined, lower part cut off. When 3rd is selected it is completely blank. Tested on X11.

![image](https://user-images.githubusercontent.com/37174852/229472239-82f8bc8e-c5ce-448e-b47d-aa5b95e4916a.png)
![image](https://user-images.githubusercontent.com/37174852/229472305-329fd353-f599-4213-8864-7d7b488269d2.png)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565 since this corner case
