### ISSUE TITLE
Alt-Codes doesn't work

### ISSUE THREAD

**Issue by El-Devoper** [rustdesk/rustdesk#3907]
### Bug Description

Typing an Alt-Code doesn't work. Both Keyboards are german and in legacy mode. Typing numbers on the numpad works.

### How to Reproduce

Open an Editor on the remote PC and Type e.g. Alt+0149 on the numpad. There is no character showing up in the editor.

### Expected Behavior

Typing Alt+0149 on the numpad should bring up a middle dot: •
Typing Alt+0150 on the numpad should bring up a dash: –
Typing Alt+0151 on the numpad should bring up a long dash: —
etc.

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

No Screenshot, since there is nothing to see

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1547

**Comment by grummbeer** [comment]
Nighly 1.2

### Linux > Windows (both german)

![windows-alt](https://user-images.githubusercontent.com/67791701/229492486-4e0b1d01-ba5c-4ed2-8d24-aaf25fb15b84.png)

In this case i must use the "legacy mode", can not remember when using it last.

🗹 Alt+0149 expect: `•`; got: `•`
🗹 Alt+0150 expect: `–`; got: `–` 
🗹 Alt+0151 expect: `—`; got: `—`
