### ISSUE TITLE
Double click during using Rustdesk

### ISSUE THREAD

**Issue by Apohey** [rustdesk/rustdesk#3908]
### Bug Description

I use rutdesk to connect to my pc from Samsung galaxy tab s8 plus using Samsung keyboard (tablet cover with keyboard). While using it on tablet everything works fine, but during remote control session I face double-clicking (instead of 1 charachter i get it doubled). How can I fix that (maybe something in setting or drivers? 

### How to Reproduce

Use same set up maybe

### Expected Behavior

One click gives one charachter 

### Operating system(s) on local side and remote side

Android - > Windows 10

### RustDesk Version(s) on local side and remote side

1.1.10-1 - > 1.1.10-1

### Screenshots

![16805215943012107363756950514944](https://user-images.githubusercontent.com/115190987/229497555-440edc59-0740-4b54-91d9-f80e3a178e57.jpg)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2137

**Comment by Apohey** [comment]
Tried out nightly build (https://github.com/rustdesk/rustdesk/releases/tag/nightly). Downloaded [rustdesk-1.2.0-x86_64-pc-windows-msvc.exe] on pc and [rustdesk-1.2.0-armv7-linux-androideabi-release.apk] according to architecture. Keyboard stopped responding. Have I downloaded wrong builds? Where might be the problem?
