### ISSUE TITLE
macOS app is not signed

### ISSUE THREAD

**Issue by rakleed** [rustdesk/rustdesk#3909]
### Bug Description

macOS application is not signed or some problems with the signature, which started either in today's build (maybe a little earlier)

### How to Reproduce

1. Install latest [rustdesk-1.2.0-x86_64-apple-darwin.dmg](https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64-apple-darwin.dmg)
2. Open app

### Expected Behavior

When you open it for the first time, a warning popup will appear, but there will be an Open button

### Operating system(s) on local side and remote side

macOS

### RustDesk Version(s) on local side and remote side

1.2.0 nightly latest

### Screenshots

![Screenshot 2023-04-03 at 14 35 31](https://user-images.githubusercontent.com/19418601/229498399-2445ffbc-9296-4864-b538-a28c18fa3c1f.png)

### Additional Context

I know that this can be bypassed by opening the application with Ctrl pressed, but previously it was not necessary to do this

**Comment by rustdesk** [comment]
@Kingtous yesterday's ci change broke all signs.

**Comment by rakleed** [comment]
@rustdesk because of this, RustDesk on macOS does not open at all.

**Comment by rakleed** [comment]
Because of this, the application does not start at all. I found a build from March 30, maybe it will be useful to someone: [rustdesk-1.2.0-x86_64-apple-darwin.dmg.zip](https://github.com/rustdesk/rustdesk/files/11137911/rustdesk-1.2.0-x86_64-apple-darwin.dmg.zip)

**Comment by rustdesk** [comment]
https://github.com/actions/runner/issues/1413#issuecomment-1197936320
