### ISSUE TITLE
Mouse and keyboard events only apply when mouse is over remote context

### ISSUE THREAD

**Issue by jacoblockett** [rustdesk/rustdesk#3913]
### Bug Description

When the mouse on the host is not hovering over the window of the remote machine, even while the program is the active window, no keyboard and mouse events are detected on the remote. For example, if my remote desktop is visually configured to "shrink" and has a black/gray background behind the actual remote context, if I'm click/dragging beyond the context of the remote display into the background area or beyond, the remote's mouse will stay mouse-downed and will not register any mouse-up events. This makes dragging windows and highlighting text near the edge of the display nearly impossible.

https://user-images.githubusercontent.com/24402122/229597854-607868b2-6c5f-4062-b74d-59a9d073a6a6.mp4

In this video, I'm attempting to drag the window to snap to both the right and top edge and highlight text near the left edge. When my mouse leaves the context of the remote machine into the background area and another "monitor" on my setup, I attempt to release the mouse but it doesn't register on the remote machine. When returning to the remote machine's context, although my mouse is not down, it retains the down event on the remote machine.

https://user-images.githubusercontent.com/24402122/229601009-8732c7d7-e51b-43e5-b3ff-ccdd0d610176.mp4

In this video, I'm attempting to copy and paste some text back and forth between host and remote contexts. You can assume that after highlighting the text in question, wherever I place the mouse before pasting is precisely where I attempted to execute "ctrl+c" on the keyboard. Notice when I attempt to paste "text 2" with the mouse outside of the remote context it fails and only succeeds when I place the mouse back into the remote context. When I attempt the opposite with "text 4", meaning the mouse was in the remote context although the active window and expected recipient of the paste op was outside of it, it registered the event in both windows and pasted in both windows.

### How to Reproduce

Follow the steps above within the video and video descriptions. Please let me know if more steps or details are needed.

### Expected Behavior

Coming from both AnyDesk and TeamViewer, I would expect that all mouse and keyboard events would be forwarded to the remote machine if the RustDesk window is active. Of course, user options to control this might be good, but I'd expect that to be the default. This not only solves annoying issues like windows not snapping and text highlighting but also I/O copy/paste ops between host and remote among other things.

### Operating system(s) on local side and remote side

Windows 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

See description

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/tag/nightly
