### ISSUE TITLE
Holding ctrl and alt keys interprets as multiple pressings

### ISSUE THREAD

**Issue by dkoliasnikov** [rustdesk/rustdesk#3922]
### Bug Description

Rustdesk interprets holding ctrl and alt as multiple pressings.
If i press and hold ctrl or alt remote system accepts multiple key pressings messages. Messages stops when i stop pressing the button.

### How to Reproduce

Establish connection. Open any software than prints info about pressed buttons. Press and hold ctrl or alt button.

### Expected Behavior

If you press and hold ctrl or alt button remote system gets only one message about the button being pressed

### Operating system(s) on local side and remote side

Windows 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

![image](https://user-images.githubusercontent.com/47827053/229782776-6cb462d8-1ae9-4cf1-8524-0061e0fbe088.png)

**Comment by rustdesk** [comment]
#1547
