### ISSUE TITLE
Shutdown/exit option on options on Id text, or maybe tray right click menu?

### ISSUE THREAD

**Issue by Kambaa** [rustdesk/rustdesk#3927]
### Description

Hello, 
How about adding an exit menu item options on ID and maybe on tray menu?
Thank you
![resim](https://user-images.githubusercontent.com/5601326/229886079-5a172f8b-080e-4fd7-9be7-9bce6fd4158a.png)

### Impact

Just exiting from clicking the X is not enough sometimes, on windows and linux(mint) i found myself killing the executable from process managers.

**Comment by rustdesk** [comment]
close to favor #912
