### ISSUE TITLE
Show cursor of non-presenting client when not in control

### ISSUE THREAD

**Issue by philippthiele** [rustdesk/rustdesk#3935]
### Description

If my friend shares his screen with me, we are usually working on some project together. To show him things on the screen, it would be great to have an option to show a pointer on the screen, when the client clicks it. 

Similar to what TeamViewer or Slack supports while screen sharing, but not allowing to control the screen.

### Impact

Anyone working together remotely

**Comment by rustdesk** [comment]
there is "show remote cursor" option on the display menu

**Comment by philippthiele** [comment]
@rustdesk this is the wrong way around. I can show the cursor of the presenter. But when I as a client am not in control, the presenter cannot see my cursor. This feature would enabled us to show things, like: "You have to click here"

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/573
