### ISSUE TITLE
Pulseaudio conflicts Ubuntu 23.04 Beta

### ISSUE THREAD

**Issue by Heljick** [rustdesk/rustdesk#3938]
### Bug Description

got error:
pipewire-alsa : Conflicts: pulseaudio but 1:16.1+dfsg1-2ubuntu3 is to be installed
pipewire-audio : Conflicts: pulseaudio but 1:16.1+dfsg1-2ubuntu3 is to be installed

### How to Reproduce

When trying to install rusdesk-1.1.9.deb on Ubuntu 23.04 beta

### Expected Behavior

Rustdesk to be install

### Operating system(s) on local side and remote side

Ubuntu 23.04 beta

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![Screenshot 2023-04-05 224605](https://user-images.githubusercontent.com/16709043/230207599-61dcfed2-f943-4f83-a27b-651f40542506.png)

**Comment by rustdesk** [comment]
seach please

**Comment by Heljick** [comment]
That's a great help thx.
I looked for Ubuntu, pulseaudio, pipewire, conflicts in the issues section and didn't found anything.

**Comment by Heljick** [comment]
And BTW I am not here to complain but to tell you rustdesk is not compatible with ubuntu 23.04 !

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3203
