### ISSUE TITLE
Latest linux nighties have wrong architecture 

### ISSUE THREAD

**Issue by knro** [rustdesk/rustdesk#3939]
### Bug Description

All the armv7 and aarach64 debian packages have control file that includes only amd64. When you try to install them they give you an architecture conflict and aborts. The rest of the package is indeed correct, except for the debian/rules/control file.

### How to Reproduce

Download nightly aarch64 package

### Expected Behavior

Installs on target architecture

### Operating system(s) on local side and remote side

Linux

### RustDesk Version(s) on local side and remote side

1.2.0 nightly

### Screenshots

Not required.

**Comment by rustdesk** [comment]
@Kingtous

**Comment by rustdesk** [comment]
fix merged, try it out later please.
