### ISSUE TITLE
Solved "An existing connection was forcedly closed by the remote host OS ERROR 10054" after Windows update

### ISSUE THREAD

**Issue by nikkdevic** [rustdesk/rustdesk#3942]
### Bug Description

I started getting this error after updating Windows.
"An existing connection was forcedly closed by the remote host OS ERROR 10054"
Sometimes I would also get "Remote desktop offline"

I downloaded the installer from rustdesk website and updated(reinstalled) Rustdesk.
That fixed the problem.

I could not find this error or solution in any of the Issues so I am posting this for anyone else who might have this Issue.

### How to Reproduce

I started getting this error after updating Windows.
"An existing connection was forcedly closed by the remote host OS ERROR 10054"
Sometimes I would also get "Remote desktop offline"

### Expected Behavior

Should connect to remote machine.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![rustdesk10054](https://user-images.githubusercontent.com/97282126/230251057-eebf224a-78c0-444f-92ae-7104c26c474a.png)

**Comment by AtlantisDe** [comment]
+1
