### ISSUE TITLE
Ubuntu can connect to Windows, but Windows can't connect to Ubuntu

### ISSUE THREAD

**Issue by dr1ver1** [rustdesk/rustdesk#3951]
### Bug Description

I've tried 2 set ups of RustDesk Server on my home network that has the follows machines:
Ubuntu 22.04 running X11
Windows 10 PC
Windows 11 Laptop

I can connect as follows:
- Ubuntu machine to Windows machines
- Windows machine to Windows machine

I'm unable to connect from Windows to Ubuntu - and this is my main requirement.

I've set up RustDesk Server on Ubuntu, using the docker-compose.yml at https://rustdesk.com/docs/en/self-host/install/
When I try to connect to Ubuntu I get the error: "Failed to connect via relay server... Please try later"

I've also set up RustDesk Server on the Windows 10 machine using the instructions at https://pedja.supurovic.net/setting-up-self-hosted-rustdesk-server-on-windows
When I try to connect to Ubuntu I get the error: "x11 error connection refused"

I was previously using the public RustDesk server to access Ubuntu from Windows.

All machines running RustDesk Desktop 1.1.9
Windows RustDesk Server 1.1.7-4
Ubuntu RustDesk Server using docker image rustdesk/rustdesk-server:latest

On Ubuntu I've run:
```
ufw allow 21115:21119/tcp
ufw allow 8000/tcp
ufw allow 21116/udp

```
On Windows I've created rules in the firewall for those ports.

I've tried the Discord, but none of the suggestions helped.

From Windows Powershell I've run Test-NetConnection to check that the relevant ports are open on the Ubuntu machine.

### How to Reproduce

Set up RustDesk Server on Ubuntu 22.04 and try to access Ubuntu from Windows

### Expected Behavior

Expect to be able to connect to Ubuntu from Windows

### Operating system(s) on local side and remote side

Windows 10, Windows 11 -> Ubuntu 22.04

### RustDesk Version(s) on local side and remote side

All machines running RustDesk Desktop 1.1.9; Windows RustDesk Server 1.1.7-4; Ubuntu RustDesk Server using docker image rustdesk/rustdesk-server:latest

### Screenshots

N/A

**Comment by rustdesk** [comment]
#763 #440

**Comment by xlinx** [comment]
`
services:
  hbbs:
    container_name: hbbs
    ports:  
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    environment:
      - ALWAYS_USE_RELAY=Y
    command: hbbs
    volumes:
      - ./data:/root
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:  
      - 21117:21117
      - 21119:21119    
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    restart: unless-stopped
`
