### ISSUE TITLE
can not type Vietnamese with ibus-bamboo with nightly, 1.1.9 worked

### ISSUE THREAD

**Issue by superthin** [rustdesk/rustdesk#3954]
### Bug Description

Cannot type Vietnamese with ibus-bamboo in target PC Ubuntu 22.04.

### How to Reproduce

Recently, I could not connect from Windows 10 (22H2 build 19045.2728) to Ubuntu 22.04 (Wayland was off, I used X11), and I cannot find solution (os error 10054): An existing connection was forcibly closed by the remote host.). By the time, it was version 1.1.9  May 2, 2022 and had worked well before that time (3 days ago).

So, I download new version RustDesk 1.2 nightly version for 2 PC. Connect was OK. But a problem occured: I cannot type Vietnamese language (I use ibus-bamboo to type Vietnamese language). Keyboard with Legacy, Map mode or Translate... was useless.

A few minutes ago, I removed RustDesk 1.2 on my Ubuntu 22.04 and reinstall  version 1.1.9 (my Windows remains RustDesk version 1.2). It connects and can type Vietnamese, it is OK as before. Wonderfully! When I look at top bar: keyboard is now only Legacy mode and View mode (blur and cannot choose).

Another problem is: type less than character **<** (ASCII with hex 3C, decimal 60) always display **>** in remote (my Ubuntu) but in Windows, it is OK.

What happened?

### Expected Behavior

Can input Vietnamese in remote side/ target PC Ubuntu 22.04.

### Operating system(s) on local side and remote side

Windows 10 (22H2)

### RustDesk Version(s) on local side and remote side

1.2 to 1.2

### Screenshots

![2023-04-07-11-19](https://user-images.githubusercontent.com/3869829/230540206-637925c5-f829-4547-ba3d-fb53441d22c5.png)

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
> I cannot type Vietnamese language (I use ibus-bamboo to type Vietnamese language). Keyboard with Legacy, Map mode or Translate... was useless.

Thanks for your feedback. 

But I'm not sure what the problem is.
Ibus-bamboo does not work, keyboard does not work, or input control does not work?

I've tried today's ngihtly build. 
Win -> Ubuntu 20.04(X11)
US -> VI    (Default input method, not  ibus-bamboo)

Is the default input method works? Can you please try some other language inputs, such as US?
Is mouse control work? (Remote control)

**Comment by rustdesk** [comment]
@superthin you should upload two videos, one is the not working nightly version, the other is the working 1.1.9 version. Do not assume we can understand easily.

**Comment by superthin** [comment]
> @superthin you should upload two videos, one is the not working nightly version, the other is the working 1.1.9 version. Do not assume we can understand you easily.

Remove and reinstall to record video is very complicated. And I summary like:

RustDesk version 1.2 same release date on Windows 10 and Ubuntu 22.04, and connect from Win to Ubuntu => Cannot type Vietnamese in Ubuntu, keyboard use ibus-bamboo.

But, removing RustDesk version 1.2 from Ubuntu 22.04 and install RustDesk version 1.9 (May 2, 2022) => Can type Vietnamese in Ubuntu.

In the past, 1.9 on Windows and 1.9 on Ubuntu => worked OK, can type Vietnamese. But some days ago, I cannot use 1.9 on 2 PC because of "(os error 10054): An existing connection was forcibly closed by the remote host".

**Comment by fufesou** [comment]
@superthin Do you mean you can type letters. But unable to type Vietnamese using `ibus-bamboo`?

I've tested `ibus-bamboo`:

1. "Translate mode" does not work fine. `â` and `á` are not transmited. Instead `aa` and `as` are transmited.
2. "Map mode" works fine.

https://user-images.githubusercontent.com/13586388/230587642-55264d64-1da5-46a5-a95a-0c0a0c39aae6.mp4

**Comment by superthin** [comment]
> @superthin Do you mean you can type letters. But unable to type Vietnamese using ibus-bamboo?

Yes.

>I've tested ibus-bamboo:

>    "Translate mode" does not work fine. â and á are not transmited. Instead aa and as are transmited.
>    "Map mode" works fine.

I cannot type as in your clip with any mode. I (re)installed version 1.1.9 to Ubuntu, I could and when connecting, only Legacy mod only. Another problem (Windows 10 with RustDesk 1.2 remote to Ubuntu 22.04 version 1.1.9): type < will display > on Ubuntu, but in Windows it is OK. Keyboard QWERT hardware, US standard on Windows and Ubuntu.

**Comment by rustdesk** [comment]
Try out latest nightly build.

**Comment by rustdesk** [comment]
> Another problem (Windows 10 with RustDesk 1.2 remote to Ubuntu 22.04 version 1.1.9): type < will display > on Ubuntu

@fufesou confirm this please.

**Comment by rustdesk** [comment]
> > Another problem (Windows 10 with RustDesk 1.2 remote to Ubuntu 22.04 version 1.1.9): type < will display > on Ubuntu
> 
> @fufesou confirm this please.

no need to fix if work fine 1.2 to 1.2

**Comment by fufesou** [comment]
> Another problem (Windows 10 with RustDesk 1.2 remote to Ubuntu 22.04 version 1.1.9): type < will display > on Ubuntu

1.2.0 -> 1.2.0 works fine.

**Comment by superthin** [comment]
> > Another problem (Windows 10 with RustDesk 1.2 remote to Ubuntu 22.04 version 1.1.9): type < will display > on Ubuntu
> 
> 1.2.0 -> 1.2.0 works fine.

I wil try again today with newest build. Thank @fufesou and @rustdesk so much! I will give more info after try again.

**Comment by fufesou** [comment]
I didn't change anything.

Maybe you can try "Map mode"again.
I can't understand why it didn't work in your test before.

**Comment by superthin** [comment]
Everything is OK now. I can type Vietnamese with ibus-bamboo in any Keyboard mod (Legacy, Map, translate) and **<** character is correct.

Thank you all! Closed as solved.
