### ISSUE TITLE
Debian package from Release demands pulseaudio as dependency, should be pulseaudio|pipewire

### ISSUE THREAD

**Issue by revast** [rustdesk/rustdesk#3958]
### Bug Description

When installing, it wants pulsaudio to be installed as well, whereas when pipewire is installed, this makes no sense

### How to Reproduce

Install debian package, while having pipewire installed and pulseaudio uninstalled.

Problem Line in Debian/control
Depends: libgtk-3-0, libxcb-randr0, libxdo3, libxfixes3, libxcb-shape0, libxcb-xfixes0, libasound2, libsystemd0, **pulseaudio**, python3-pip, curl

### Expected Behavior

Package is also happy when pipewire is installed.

Fix
Depends: libgtk-3-0, libxcb-randr0, libxdo3, libxfixes3, libxcb-shape0, libxcb-xfixes0, libasound2, libsystemd0, **pulseaudio|pipewire**, python3-pip, curl

### Operating system(s) on local side and remote side

Ubuntu22.04

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![image](https://user-images.githubusercontent.com/8189198/230597103-21b7fafe-5fdf-49b2-9af1-2dc701a63f03.png)

### Additional Context

Also, there is no Description (Yet) in the Package.

Suggestion:

A remote desktop software, the open source TeamViewer alternative.
Works out of the box, no configuration required. 
.
You have full control of your data, with no concerns about security. 
You can use our public rendezvous/relay server, or self-hosting, or write your own server. 
.
.
Secure, Fast and Simple
 \- End-to-end encryption.
 \- Own your data. Easily setup RustDesk self-hosted solution on your infrastructure.
 \- Track access log and manage permissions from a modern UI.
 \- No administrative privileges or installation needed for Windows.
 \- Works on Windows, macOS, Linux, iOS, Android, Web.
 \- We keep things simple and try to make simpler when possible.
.

**Comment by rustdesk** [comment]
Could you search old issues please before submit new issue?

**Comment by revast** [comment]
Actually I did, maybe I did it wrong?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3203
