### ISSUE TITLE
Addition of a Code of Conduct

### ISSUE THREAD

**Issue by FahimFBA** [rustdesk/rustdesk#396]
The project is missing the **Code of Conduct** which can be added in the root branch with a `CODE_OF_CONDUCT.md` file. A Code of Conduct defines standards for how to engage in a community. If you are interested in adding one, then I would submit a PR with that.

**Comment by rustdesk** [comment]
Please, Thx.

**Comment by rustdesk** [comment]
But we have this https://github.com/rustdesk/rustdesk/blob/master/CONTRIBUTING.md#conduct

**Comment by FahimFBA** [comment]
> But we have this https://github.com/rustdesk/rustdesk/blob/master/CONTRIBUTING.md#conduct

If you add a `CODE_OF_CONDUCT.md` in the root branch, then it shows like this in a repo.
![Screenshot from 2022-02-14 01-43-45](https://user-images.githubusercontent.com/64195132/153771977-8d7682a8-d9a3-4993-ab52-5a5b6aaaafd3.png)

Please have a look at the PR, and please let me know what do you think about that. If you want to make a change then obviously we can have that, and if you don't want that then that's fine also, of course! I just wanted to know whether you want that Code of Conduct to appear on the right side of the project repo or not.


Thanks!

**Comment by rustdesk** [comment]
Thanks!

**Comment by FahimFBA** [comment]
You are welcome!
