### ISSUE TITLE
Connection Error - Operation not permitted (os error 1)

### ISSUE THREAD

**Issue by luckman212** [rustdesk/rustdesk#3960]
### Bug Description

I am selfhosting my own relay server and have set up encryption key (all working). 

When on 5G/LTE network I cannot connect to any of my Rustdesk hosts from my iPhone.

I get this:

![IMG_4351](https://user-images.githubusercontent.com/1992842/230628279-b4191f5a-68c4-4a0c-9b74-1ac373708f77.jpeg)

I read and seems like it's some sort of IPv6/NAT64 issue(?)

So, I tried disabling IPv6 completely on my relay server docker host/container but it didn't make any difference.

Is there any workaround or fix for this? 🙏 

### How to Reproduce

Switch off WiFi

Try to connect to remote host

### Expected Behavior

Connects...

### Operating system(s) on local side and remote side

iOS 16.4 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.1.10 -> 1.1.9

### Screenshots

see above

**Comment by rustdesk** [comment]
#2942

**Comment by luckman212** [comment]
Ok, I guess you mean this comment? https://github.com/rustdesk/rustdesk/issues/152#issuecomment-1367696431 

Still I am wondering if there is any workaround I can use today? If not then I guess we just wait for the next iOS release.
