### ISSUE TITLE
Multi-button mouse support

### ISSUE THREAD

**Issue by 4C3T** [rustdesk/rustdesk#3963]
### Bug Description

I have not seen any options regarding mouse buttons, and it would appear that not even middle click works.
Had this been 25 years ago I would have been fine with that, but today no computer is a good computer without at least a 5-button mouse

### How to Reproduce

Using any other button than right and left...

### Expected Behavior

At the very least, most apps can send the middle key, but this can't even do that. 5 buttons are pretty much standard for all apps today

### Operating system(s) on local side and remote side

Windows 10 Enterprise->Professional

### RustDesk Version(s) on local side and remote side

1.1.9->1.1.9

### Screenshots

None, not necessary

### Additional Context

Using [X-Mouse](https://www.highrez.co.uk/downloads/XMouseButtonControl.htm) which isn't detecting any other buttons in its control panel which it normally does otherwise.

Perhaps the guy who makes this software (He's active with frequent updates and is very helpful btw) can help out with coding? Just an idea if that's where the problem lies

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/tag/nightly

**Comment by 4C3T** [comment]
> https://github.com/rustdesk/rustdesk/releases/tag/nightly

Ok, nice that there was an update, but you could've at least written a word or two about what the files was for (rustdesk-1.2.0-x86_64.exe).
I guessed that it was a replacement for the "Rustdesk,exe" so I renamed the existing one in c:\Program Files\Rustdesk.
Then started it, and it said something about Desktop being old, with a button which didn't quite specify what it was supposed to "fix".
Did the same thing on the remote computer, and there i got a very different result.
c:\program files\ was only containing 1 file at the time when I replaced the "Rustdesk.exe", and after I clicked the "Fix"-whatever it said-button, I got a whole bunch of files there. Not sure if it did some copying in the background, or if the computer was just being slow. I did have a power outage earlier today so things has been a bit off with all computers, plus this computer has some GPU-driver issues.
Also, not sure if it was in the updated version, but when I clicked the three dots in the upper right corner, right next to the ID, suddenly the configuration menu appeared instead of a drop-down menu. 

Anywhoo, I tested it, and it didn't want to connect, and as it turned out, the connection permissions had been revoked, so I fixed that and now it works.
All buttons works now, so thanks for the update!
