### ISSUE TITLE
Allow the connecting client to disable mouse/keyboard control locally

### ISSUE THREAD

**Issue by Hubro** [rustdesk/rustdesk#3971]
### Description

I use Rustdesk primarily for education and pair programming. This means that most of the time, I'm not controlling the host, just observing the monitor. Remote control needs to be enabled however, because I often need to control the mouse for gesturing or take over writing for a minute.

Having the other person open the Rustdesk client and enable/disable mouse/keyboard control any time I need to point something out or demonstrate something is extremely tedious, so we keep it enabled at all times.

This constantly results in accidental inputs into Rustdesk as I move the mouse to another window or press Alt+Tab or Super+Tab to switch window or workspace.

It would be a massive quality of life improvement if I could disable mouse/keyboard control on my end, especially if I could map it to a keyboard shortcut such as AltGr+F10.

### Impact

This would make Rustdesk much more pleasant to use for long educational or pair-programming sessions as accidental inputs could be completely eliminated.

**Comment by rustdesk** [comment]
#2754

**Comment by rustdesk** [comment]
no more duplicates please
