### ISSUE TITLE
Hangs on Launch: Failed to read XDG desktop portal settings

### ISSUE THREAD

**Issue by dotaxis** [rustdesk/rustdesk#3973]
### Bug Description

After installing the flatpak on my Steam Deck the app just hangs  on start and shows no window. Opening it via terminal gives this output:

```(130)(deck@steamdeck bin)$ com.rustdesk.RustDesk 
load librustdesk.so failed
Gtk-Message: 16:06:33.205: Failed to load module "canberra-gtk-module"

** (rustdesk:2): CRITICAL **: 16:06:33.442: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (rustdesk:2): CRITICAL **: 16:06:33.447: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (rustdesk:2): CRITICAL **: 16:06:33.449: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (rustdesk:2): CRITICAL **: 16:06:33.452: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (rustdesk:2): CRITICAL **: 16:06:33.454: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
flutter: launch args: []
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'librustdesk.so': libpam.so.0: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
#2      PlatformFFI.init (package:flutter_hbb/models/native_model.dart:150)
#3      initEnv (package:flutter_hbb/main.dart:108)
#4      runMainApp (package:flutter_hbb/main.dart:121)
#5      main (package:flutter_hbb/main.dart:102)
<asynchronous suspension>

^C
```

### How to Reproduce

1. Install flatpak using 
`flatpak install <path_to_rustdesk.flatpak>
2. Launch through applications menu or terminal

### Expected Behavior

Expected app to open

### Operating system(s) on local side and remote side

SteamOS

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

![image](https://user-images.githubusercontent.com/11805686/230744905-0f73b6f1-d4cc-4e1b-80be-62512b057123.png)

![image](https://user-images.githubusercontent.com/11805686/230744935-ac495b70-325b-4ac7-8ef9-3898e49ada49.png)

### Additional Context

Apparently an older flatpak didn't have this issue as I have a friend who has this working, but I can't find any older versions of the nightly on the web.

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
close as fix merged

**Comment by dotaxis** [comment]
Can someone update the flatpak?

**Comment by dotaxis** [comment]
This is a bug report which was fixed and closed 3 years ago. Using AI to crawl ancient GitHub issues and advertise your decky plugin on them is not a good look.
