### ISSUE TITLE
Keyboard not working in Terminal window

### ISSUE THREAD

**Issue by FCrane** [rustdesk/rustdesk#3977]
### Bug Description

The keyboard does not work at all in a terminal window on the remote machine.

### How to Reproduce

Right-click the desktop (or anywhere) and select "Open in Terminal". A Powershell window opens but it does not accept any keyboard input.

### Expected Behavior

Working keyboard in Terminal window.

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

Both 1.2.0

### Screenshots

n/a

**Comment by rustdesk** [comment]
installed?

**Comment by FCrane** [comment]
Yes, on both sides.

**Comment by Jafar313** [comment]
Hi @FCrane 
I had this trouble too in Ubuntu 22.04 with Wayland desktop environment. after change it to x11 environment, problem fixed.

**Comment by weirdal3333** [comment]
I've had this issue intermittently on Linux Mint Vera. Reconnecting to the machine seems to fix it, but it sure is annoying!

**Comment by FCrane** [comment]
On my Windows 11 machine, it's 100% reproducible. Keyboard never works in a terminal window...

**Comment by JPDucky** [comment]
Suggesting that users switch something as important as their compositor to a legacy program just to maintain app compatibility isn't prudent. We should work on a better implementation for supporting wayland.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367
