### ISSUE TITLE
Translate Mode Keyboard numpad keys not sending.

### ISSUE THREAD

**Issue by Kambaa** [rustdesk/rustdesk#3996]
### Bug Description

Hello, 
After testing Rustdesk Nightly, i found out that sending numpad keys not working for me. I have installed on both sides, is this an issue? 

### How to Reproduce

Connect to a laptop ( mine don't have any numpad keys ) from PC and send keyboard numpad keys. It did not matter NumLock is on or off.

### Expected Behavior

A keyboard press should be understood on controlled side.

### Operating system(s) on local side and remote side

Win 10 PC > Win 10 Laptop

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0 (Both Nightly versions installed)

### Screenshots

https://user-images.githubusercontent.com/5601326/230858260-5a5770aa-bfc4-4a29-a05a-5e6780ce0bfb.mp4

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
Thanks for your feedback.
This issue should be fixed by PR 4000.

**Comment by rustdesk** [comment]
close since fix merged
