### ISSUE TITLE
现在Windows不能安装了....

### ISSUE THREAD

**Issue by zhangbo8418** [rustdesk/rustdesk#4]
![QQ截图20201027203145](https://user-images.githubusercontent.com/46797568/97302076-870d7f80-1893-11eb-85d4-446a3c109532.png)
![QQ截图20201027203216](https://user-images.githubusercontent.com/46797568/97302094-8c6aca00-1893-11eb-9862-1a12fc4ff87b.png)
好像是因为中文用户名。。。。

**Comment by rustdesk** [comment]
哇，你还在折腾啊

**Comment by rustdesk** [comment]
为了你的执着，我现在就装个win7试试

**Comment by zhangbo8418** [comment]
一堆BUG。。。。唉，没意思。。。。

**Comment by zhangbo8418** [comment]
我这边控制Mac输入一个字母Mac端就奔溃。。。。

**Comment by rustdesk** [comment]
我刚刚测试了mac连mac，mac连win10， win10连mac，输入都很正常，不过的确没测过win7

**Comment by rustdesk** [comment]
为啥你还在用win7?

**Comment by zhangbo8418** [comment]
因为不喜欢Win10，所以我换了Mac
