### ISSUE TITLE
Pipewire

### ISSUE THREAD

**Issue by jerome-diver** [rustdesk/rustdesk#4007]
### Description

RustDesk is depending about Pulseaudio, but on Pop!_OS, the system is runnig with Pipewire. Pipewire is the next audio library to be used by many Linux's distributions. Do you plan to use Pipewire at any time, so that i can use RustDesk ?

### Impact

All the one that are using a Linux distribution using Pipewire.

**Comment by rustdesk** [comment]
search first please

**Comment by jerome-diver** [comment]
i did. Please, show me the link beforer to close.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3203
