### ISSUE TITLE
Failed to run in UOS1022 on HuaiWei kirin990

### ISSUE THREAD

**Issue by iamfoolberg** [rustdesk/rustdesk#4011]
### Bug Description

```
(rustdesk:12580): GLib-GObject-CRITICAL **: 08:17:19.998: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(57)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed
```

### How to Reproduce

download the latest aarch64.deb, install and run it. You may need
``` xhost +```

### Expected Behavior

It seems that, the following init lines may work. 
```
#include <iostream> 
#include <GL/freeglut.h> 

int main(int argc, char **argv) { 
    glutInit(&argc, argv); 
    glutInitDisplayMode(GLUT_RGBA); 
    glutCreateWindow("test"); 
    glutFullScreen(); 
    std::cout << glGetString(GL_VERSION) << std::endl; 
    return 0; 
} 
```

### Operating system(s) on local side and remote side

UOS1022

### RustDesk Version(s) on local side and remote side

1.1.9-1.2.0(nightly)

### Screenshots

wowww

**Comment by rustdesk** [comment]
#3565

**Comment by rustdesk** [comment]
https://github.com/flutter/flutter/issues/72987#issuecomment-756895010

**Comment by rustdesk** [comment]
try out `LIBGL_ALWAYS_SOFTWARE=1 rustdesk`
