### ISSUE TITLE
Add an entry for fully exiting RustDesk

### ISSUE THREAD

**Issue by byyxx128** [rustdesk/rustdesk#4014]
### Description

Consider adding an entry for fully exiting RustDesk. There are two usage scenarios.
1. Allow users to choose whether to completely exit the program or leave a tray icon when closing the main window.
2. Allow users to completely exit RustDesk (not just stop the service) by right-clicking the context menu of the tray icon.

### Impact

It is reasonable for software to provide a way to exit itself. RustDesk is currently designed to run in the background and remain active all the time, which is useful for unmanned servers. However, for personal desktop users, we still hope to be able to manually exit the RustDesk process completely.

**Comment by rustdesk** [comment]
#912
