### ISSUE TITLE
Add an option to load external language file (.rs) for translator testing

### ISSUE THREAD

**Issue by bovirus** [rustdesk/rustdesk#4019]
### Description

@rust

Add an option to load external language file (like .rs file avaiable in gihub language page.

https://github.com/rustdesk/rustdesk/tree/master/src/lang

it can help the translators to check in place the translation without wait next build.

### Impact

Help the translator in their job.

### Additional Context

Add an option to laod external language file (like .rs file avaible in gihuyb)

https://github.com/rustdesk/rustdesk/tree/master/src/lang

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1046#issuecomment-1194360218

**Comment by bovirus** [comment]
@rustdesk 

Probably I didn't understand the relation between my request and a translation platform.

My reuest is to modify source code to add an option (via command line o copying the language file ina specific position) to trst a new translation without waiting a new build.

It seems different request then explanation in the comment.

If it's true and it's a different request please reopen this enhancement request.

**Comment by rustdesk** [comment]
still wontfix, I added `csv <-> rs` per a request, but then the requestors never used it. We won't waste any time on this. Our translation contributors have been familiar with current flow, no need to chagne anyhthing.

**Comment by bovirus** [comment]
@rustdesk

I believe that most of the translator know the flow of translation.

The problem that now the translator can translate the strings without know exactly the context of the strings.

In Italian/German/French etc the strings can be male/female/neutral basing on the context (in english is one string) and same string in english can have different translation in italian basing in the context.

Then as I did I translate the strings without know the context, then I should wait next build to test the translation in place, then apply the fixes, then wait  new build, check and again.

If you can add to load an external file (in the way that you like) it's possible to check all strings without way a new build.

For the same reason I asked you to update master language (english) with all strings because ius the base for translation.

How can update translation if most of the strings are not available in master english file?

For me if you want to push up in a positive direction the update of the translation it's important too provide the basic tools

master english language updated
way to test the translation without wait next build.

Thanks.

**Comment by yurtpage** [comment]
This may be partially solved by integrating a translation platform (Weblate) #1046 
It allows to put a screenshot of the page that you are translating so you may see the context and place.
