### ISSUE TITLE
Impossible to get Android input permission on RustDesk Nightly release 12 April 2023

### ISSUE THREAD

**Issue by mikekgr** [rustdesk/rustdesk#4023]
### Bug Description

I installed Android apk  nightly release 12 April 2023 file name: rustdesk-1.2.0-aarch64-signed.apk)
My Android phone is: OnePlus 9 Pro running Android 13.
As you can see from the screenshots, in the final activation step the Android informing me that For  security settings this activation is currently unavailable.

### How to Reproduce

Please install the nightly release 12 April 2023 file name: rustdesk-1.2.0-aarch64-signed.apk) in an Android 13 phone and try it

### Expected Behavior

The expected behavior is to accept the accessibility allowance when the user set it 

### Operating system(s) on local side and remote side

Android 13

### RustDesk Version(s) on local side and remote side

nightly release 12 April 2023 file name: rustdesk-1.2.0-aarch64-signed.apk)

### Screenshots

![RustDesk_OnePlus9Pro1](https://user-images.githubusercontent.com/15084551/231358418-102f1531-ce55-4c35-b375-92ec79fd95ad.jpg)
![RustDesk_OnePlus9Pro2](https://user-images.githubusercontent.com/15084551/231358459-d3408540-e419-4565-b69d-1715e8aa5df8.jpg)
![RustDesk_OnePlus9Pro3](https://user-images.githubusercontent.com/15084551/231358492-aa67eb4c-da21-45a0-8338-60d45f35b437.jpg)

**Comment by rustdesk** [comment]
#3893

**Comment by LarsK1** [comment]
@mikekgr @rustdesk 
You can momentarily overcome this:
- On your Android device, open the Settings app.
- Tap Apps.
- Tap the app that you want to turn on a restricted setting for.
Tip: If you can't find it, first tap See all apps or App info.
- Tap More  and then Allow restricted settings.
- Follow the on-screen instructions.

**Comment by mikekgr** [comment]
Dear Sir, it doesn't allow me see the screenshot 
![Screenshot_2023-05-29-09-33-15-24_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/rustdesk/rustdesk/assets/15084551/51c905f5-caae-435c-b641-6fc30b31be44)
![Screenshot_2023-05-29-09-33-20-38_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/rustdesk/rustdesk/assets/15084551/14f19b20-f368-4d78-8488-650846804184)

**Comment by LarsK1** [comment]
@mikegr you didn't understand. Go to the phone's settings app. Go to apps, find Rustdesk. There you'll find the three dots to enable the special mode. Afterwards you can go to Rustdesk to enable the services

**Comment by mikekgr** [comment]
> @mikegr you didn't understand. Go to the phone's settings app. Go to apps, find Rustdesk. There you'll find the three dots to enable the special mode. Afterwards you can go to Rustdesk to enable the accessibility services
@LarsK1 
I did that initially but there is not special mode in Rustdesk application. I am running Android 13 if that matters.
Do you need screenshots?

**Comment by LarsK1** [comment]
@mikekgr please see:
https://1drv.ms/v/s!AnRIWP-3awPOhsZyzhKUgzWJJACwfQ

**Comment by mikekgr** [comment]
Please see : (there's not settings like yours)
https://photos.app.goo.gl/BCYtsvm1nzgFPoLe7

**Comment by vladimirvanchytsky** [comment]
> @mikekgr @rustdesk You can momentarily overcome this:
> 
> * On your Android device, open the Settings app.
> * Tap Apps.
> * Tap the app that you want to turn on a restricted setting for.
>   Tip: If you can't find it, first tap See all apps or App info.
> * Tap More  and then Allow restricted settings.
> * Follow the on-screen instructions.

Working, didn't know about such option, thanks!

**Comment by grannymaster** [comment]
> @mikekgr @rustdesk You can momentarily overcome this:
> 
>     * On your Android device, open the Settings app.
> 
>     * Tap Apps.
> 
>     * Tap the app that you want to turn on a restricted setting for.
>       Tip: If you can't find it, first tap See all apps or App info.
> 
>     * Tap More  and then Allow restricted settings.
> 
>     * Follow the on-screen instructions.

For anyone following these instructions, if the "Allow restricted settings" doesn't seem to stick (i.e., it resets itself every time). Before allowing the restricted settings, "Force stop" RustDesk, then allow, and then go back to the RustDesk "Share screen" tab and enable input permissions.

I had this issue with the OnePlus Tab.

**Comment by MohammadAli-Kadiwal** [comment]
Still facing same error on Samsung S22 ULTRA
