### ISSUE TITLE
Add localization info on github home page

### ISSUE THREAD

**Issue by bovirus** [rustdesk/rustdesk#4025]
### Description

@rustdesk 

Please add in github home page 

https://github.com/rustdesk/rustdesk

after how to compile small explanation how to localize your program.

Please fill in the strings in english file

https://github.com/rustdesk/rustdesk/blob/master/src/lang/en.rs

that it's the base for translator
For example to translate last string in language file I should check on German/French language because are not available in english language file.

if you can please modify the source code to use an external language file for testing.
The external language file could be loaded via command line or copying it in a specific path an external language file.

Thanks.

### Impact

Help all translators to create new translation/update current translation.

**Comment by rustdesk** [comment]
template.rs is the base.

**Comment by bovirus** [comment]
Then the problem is en.rs (en=english) that contains only same strings and can contain only some strings translation.

Please add this info in home page about master template.

Please consider that most of the strings are text strings and iare easiet to translate but these strings

        ("confirm_idd_driver_tip", ""),
        ("empty_recent_tip", ""),
        ("empty_favorite_tip", ""),
        ("empty_lan_tip", ""),
        ("empty_address_book_tip", ""),
        ("login_linux_tip", ""),
        ("verify_rustdesk_password_tip", ""),
        ("remember_account_tip", ""),
        ("os_account_desk_tip", ""),
        ("another_user_login_title_tip", ""),
        ("another_user_login_text_tip", ""),
        ("xorg_not_found_title_tip", ""),
        ("xorg_not_found_text_tip", ""),
        ("no_desktop_title_tip", ""),
        ("no_desktop_text_tip", ""),


are not text string.
Infact I should get the text strings from German/French language.
I believe that the string above should be text string (as the other) and not as seems now variable name.
Otherwise is not possible to translate it without knowing the text strings.
