### ISSUE TITLE
Keyboard input of the remote client doesn't work in session to an Android Host

### ISSUE THREAD

**Issue by 29039** [rustdesk/rustdesk#4026]
### Bug Description

I installed rustdesk-1.2.0-aarch64-signed.apk (built 7 hours ago)
I can remotely control the Android host with mouse inputs, but using the keyboard on my PC, no inputs such as typing text is being sent to the Android host.

Tested Android 8.0.0 (Galaxy S7 edge) and Android 12 (Galaxy Z Flip4)

### How to Reproduce

Install rustdesk-1.2.0-aarch64-signed.apk
Remote control from a PC
access a text box where virtual keyboard appears
Try typing next with PC keyboard

### Expected Behavior

Letters should be sent across

### Operating system(s) on local side and remote side

Windows 10 > Android 8.00 & Android 12

### RustDesk Version(s) on local side and remote side

1.1.9 > 1.2.0

### Screenshots

![image](https://user-images.githubusercontent.com/61966298/231387502-07c76e26-4af4-4296-bc2b-cc801882733b.png)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3556

**Comment by 29039** [comment]
I have tested Microsoft Phone Link app and it is able to remote control with keyboard input from the host. When I start typing, the onscreen keyboard disappears while it is typing, suggesting that it is some kind of emulation of a physical keyboard  where the device thinks that a physical keyboard has been connected.

![image](https://user-images.githubusercontent.com/61966298/231423265-f7b22348-558c-4c68-a3da-0f1acb75f1d6.png)

**Comment by 29039** [comment]
Yup, in the settings, the phone thinks that there is a physical keyboard called "Samsung_MDX_virtual_keyboard"
