### ISSUE TITLE
Windows to macOS connection fails

### ISSUE THREAD

**Issue by z16166** [rustdesk/rustdesk#4033]
### Bug Description

Windows to macOS connection fails, with direct LAN IP.

### How to Reproduce

1. boot macOS to login screen.
2. use RustDesk 1.19  to connect to macOS from Windows, with direct LAN IP of macOS. 
It works before entering macOS account password.
3. entering the macOS account password to login. RustDesk disconnects and sometimes can't connect again with "os error 10061".

### Expected Behavior

RustDesk can connect to macOS after logining into macOS account.

### Operating system(s) on local side and remote side

Winows 11 -> macOS Ventura 13.2.1 ARM64

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

![rustdesk](https://user-images.githubusercontent.com/776163/231619997-a31cb5ff-6d34-4808-88ab-45c19b694b76.png)

**Comment by rustdesk** [comment]
https://www.google.com/search?q=os+error+10061&sourceid=chrome&ie=UTF-8

**Comment by z16166** [comment]
I think it's really a bug, even if I manually run RustDesk(server) in macOS after login. 
I will debug it myself if I have time.
