### ISSUE TITLE
RustDesk Client attempting to use port 21114 when logging into selfhosted server?

### ISSUE THREAD

**Issue by akidburn** [rustdesk/rustdesk#4034]
### Bug Description

Hello,
i installed the rustdesk server on my own linuxbox with the normal install.sh variant, followed the steps (not that many),
but when attempting to login using the rustdesk client i get this error, after opening an additional port 21114:

process explorer shows clearly the client attempting to contact the server on 21114 for some reason, no idea why, my second client did the same thing.

remote connections using the id are working, but thats not the plan with the login

### How to Reproduce

no idea

### Expected Behavior

i expected the client to show all live clients in the admin view

### Operating system(s) on local side and remote side

win 10 both

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![err](https://user-images.githubusercontent.com/25623510/231625943-d1922582-343c-434f-ae5c-f783bc2d7cc2.jpg)

**Comment by choujar** [comment]
hi! what does marking this as invalid mean? I'm having the same issue!

**Comment by coucoy** [comment]
See issue #522

**Comment by KB8DOA** [comment]
Can someone help me understand how issue #522 is related to this?
I have a licensed Rust Desk Pro Server and am trying to login as admin (like pictured above) and am getting the same error.
Issue #522 is addressing stopping the communications from clients by dropping the port 21114 packets in the firewall.
How does this fix our Android Clients that cannot log in as mentioned above??????

**Comment by rustdesk** [comment]
> I have a licensed Rust Desk Pro Server and am trying to login as admin (like pictured above) and am getting the same error.


This https://github.com/rustdesk/rustdesk/wiki/FAQ#failed-to-log-in-with-custom-client-build-or-public-release-with-wrong-api-settings can help you.

**Comment by KB8DOA** [comment]
> > I have a licensed Rust Desk Pro Server and am trying to login as admin (like pictured above) and am getting the same error.
> 
> This https://github.com/rustdesk/rustdesk/wiki/FAQ#failed-to-log-in-with-custom-client-build-or-public-release-with-wrong-api-settings can help you.

But I am NOT running a "custom client" - I am simply running the client downloaded from F-Droid
