### ISSUE TITLE
Command line command/parameters section in github home page

### ISSUE THREAD

**Issue by bovirus** [rustdesk/rustdesk#4042]
### Description

@rustdesk 

Could you please create in the github home page a command line section where you can specifiy the various command that can use via command line?

How can get the help with all command llst regarding command line?

I chechkd that --tray run the program 

It's important mention that configuration file is located in 

C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml

### Impact

Better use with command line.

**Comment by rustdesk** [comment]
it will be in https://github.com/rustdesk/doc.rustdesk.com, once we get ready, no hurry please.
