### ISSUE TITLE
Could not connect to my server - problems with ethernet drivers or what?

### ISSUE THREAD

**Issue by albgen** [rustdesk/rustdesk#4046]
### Bug Description

Simply could not connect to my server deployed with docker compose.

### How to Reproduce

Windows Server running on Proxmox.

Rustdesk server running on another virtual infrastructure elsewhere. Docker compose file as follows 
[docker compose.txt](https://github.com/rustdesk/rustdesk/files/11223257/docker.compose.txt)

On Proxmox, set the network card of Windows Server as e1000 model, result is everything working correct.
On Proxmox, Set the network card of Windows Server as VirtIO model, result is "Could not connect".
Please note that, internet connectivity is working normally and also other services are working normally in both cases. Only Rustdesk has the issue.

See screenshot for the logs of the hbbs server which shows several attempts with tcp closed.
It shows also a successfull attempt when the network card was set to e1000

### Expected Behavior

Connect on server as usual.

### Operating system(s) on local side and remote side

Windows Server 2019, Windows Server 2012

### RustDesk Version(s) on local side and remote side

1.1.9 but also 1.2.0 the same issue

### Screenshots

What you see on the following, are different attempts to connect on the server and the one that worked
![image](https://user-images.githubusercontent.com/7231968/231789876-adcb42c1-78b3-4364-b5cd-625780a19017.png)

Settings of proxmox on network card
![image](https://user-images.githubusercontent.com/7231968/231790163-b2706a35-7e84-47d8-b9c4-2eb03ca6e090.png)

**Comment by rustdesk** [comment]
#763
