### ISSUE TITLE
direction keys not working connecting form osx to windows

### ISSUE THREAD

**Issue by neroita** [rustdesk/rustdesk#4052]
### Bug Description

Hi all ,
my desktop is a osx ventura and I use rustdesk mainly to connect to windows machines.

It work without problem but in soma app cursor keys and some special keys don't work.
App that don't work: putty , vnc , any cygwin/x11 apps.
App that work: notepad and other windows classics apps.

When don't work I see that pressing cursor keys generate numbers like the numpad , somethink like 8 for up , 4 for left and so on.

Other remote management apps like anydesk or meshcentral don't have the problem.

Is there a solution ? rustdesk is the latest both server and client.

Thank's in advance,
Marco.

### How to Reproduce

- Connect from osx to windows
- open putty and "vi" some file
- try to move with cursor keys

### Expected Behavior

I'm expecting cursor keys work normally.

### Operating system(s) on local side and remote side

osx -> windows 10

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

none

**Comment by rustdesk** [comment]
#1547
