### ISSUE TITLE
No keyboard input

### ISSUE THREAD

**Issue by BenK885** [rustdesk/rustdesk#4054]
### Bug Description

After connecting to a Windows 11 client, no keyboard input is possible, despite being activated.
Mouse input is working just fine.

### How to Reproduce

Connect to a remote Windows 11 client with RustDesk 1.1.9 oder 1.2.0

### Expected Behavior

Typing on the keyboard should send keyboard input to the client, but actually doesn't.

### Operating system(s) on local side and remote side

Local: macOS 10.14.6 (Mojave) or Windows 10 / remote: Windows 11

### RustDesk Version(s) on local side and remote side

Tested with 1.1.9 on both sides and 1.2.0 on both sides

### Screenshots

no screenshot

**Comment by rustdesk** [comment]
#974

**Comment by BenK885** [comment]
Thank you @rustdesk
In macOS 10.14.6 (Mojave), I had to manually grant accessibility permissions by adding the RustDesk application to 'System Preferences -> Security & Privacy -> Privacy -> Accessibility'
