### ISSUE TITLE
Add an option for persistent background operation on Ubuntu

### ISSUE THREAD

**Issue by lrf19991230** [rustdesk/rustdesk#4056]
### Description

I have been using RustDesk on Ubuntu and  I have encountered a problem: when I close the RustDesk window (by clicking on the 'X' button in the top-right corner), I can no longer connect to the remote computer, as it shows the remote computer as being offline.
I would like to request a feature where RustDesk can continue to run in the background even after the window is closed, similar to the behavior of TeamViewer. This would allow users to maintain remote connections without having to keep the RustDesk window open at all times.

### Impact

all ubuntu or linux users

**Comment by lrf19991230** [comment]
maybe there is another way to make it run background?

**Comment by rustdesk** [comment]
there is an issue to ask us how to stop our background service, please search.
