### ISSUE TITLE
Keyboard not working as unprivileged user with nightly

### ISSUE THREAD

**Issue by woodyst** [rustdesk/rustdesk#4059]
### Bug Description

When I start rustdesk as a normal user, keyboard input does not work. Launching rustdesk as root does.

Using version 1.1.9 it does work with unprivileged user too.

I have a laptop with same version and it works too. I think it may be a file permission issue, but I am unable to find it.

### How to Reproduce

Using rustdesk normally.

### Expected Behavior

Keyboard key presses working in remote machine.

### Operating system(s) on local side and remote side

linux -> anyone

### RustDesk Version(s) on local side and remote side

1.2.0 -> anyone

### Screenshots

not needed

**Comment by rustdesk** [comment]
we can not find either for such special case.

**Comment by rustdesk** [comment]
close this because unproducible and clueless.

**Comment by dominikegert** [comment]
I am having the same issue, keyboard not working with nnormal user, but as root user it works.

Environment: Gnome/Wayland, Fedora 38
Rustdesk Version 1.1.9

Unfortunate, I have no idea what to provide to track the issue. Therefore here what I get when loading rustdesk as root:

[dominik@fedora ~]$ sudo rustdesk
[sudo] password for dominik: 
INFO:TIS: scaleFactor 1
INFO:TIS: current platform: Linux
INFO:TIS: is_xfce:  false

(rustdesk:603031): Gtk-WARNING **: 11:55:55.069: gtk_window_set_titlebar() called on a realized window
INFO:TIS: scaleFactor 1

(rustdesk:603031): Gdk-CRITICAL **: 11:55:55.091: gdk_screen_get_monitor_at_window: assertion 'GDK_IS_WINDOW (window)' failed

(rustdesk:603031): Gdk-CRITICAL **: 11:55:55.091: gdk_screen_get_monitor_workarea: assertion 'monitor != NULL' failed

(rustdesk:603031): Gdk-CRITICAL **: 11:55:55.091: gdk_screen_get_monitor_geometry: assertion 'monitor != NULL' failed

(rustdesk:603031): Gtk-CRITICAL **: 11:55:55.091: gtk_window_resize: assertion 'width > 0' failed
INFO:TIS: state changed from 0 -> 1
INFO:TIS: Update cursor, system: false
INFO:TIS: state changed from 1 -> 3
INFO:TIS: enter
Traceback (most recent call last):
  File "/usr/share/rustdesk/files/pynput_service.py", line 1, in <module>
    from pynput.keyboard import Key, Controller
ModuleNotFoundError: No module named 'pynput'
INFO:TIS: leave
INFO:TIS: state changed from 3 -> 1
INFO:TIS: enter
INFO:TIS: leave
INFO:TIS: enter
INFO:TIS: leave
INFO:TIS: enter
INFO:TIS: leave
INFO:TIS: enter
INFO:TIS: leave
INFO:TIS: enter
INFO:TIS: leave
INFO:TIS: Update cursor, system: false
INFO:TIS: Update cursor, system: false
INFO:TIS: recent sessions updated
[dominik@fedora ~]$ 



and as normal user:
[dominik@fedora ~]$ rustdesk
INFO:TIS: scaleFactor 1
INFO:TIS: current platform: Linux
INFO:TIS: is_xfce:  false
INFO:TIS: scaleFactor 1
INFO:TIS: state changed from 0 -> 1
INFO:TIS: Update cursor, system: false
INFO:TIS: Update cursor, system: false
INFO:TIS: Update cursor, system: false
INFO:TIS: enter
INFO:TIS: leave
INFO:TIS: enter
INFO:TIS: leave
INFO:TIS: enter
INFO:TIS: Update cursor, system: false
INFO:TIS: Update cursor, system: false
INFO:TIS: leave
INFO:TIS: Update cursor, system: false
INFO:TIS: Update cursor, system: false
INFO:TIS: Update cursor, system: false
INFO:TIS: Update cursor, system: false
INFO:TIS: Update cursor, system: false
INFO:TIS: enter
INFO:TIS: leave
INFO:TIS: recent sessions updated
[dominik@fedora ~]$ rustdesk --help
Segmentation fault (core dumped)
[dominik@fedora ~]$ rustdesk /?
Segmentation fault (core dumped)
[dominik@fedora ~]$
