### ISSUE TITLE
iOS Nightly Builds

### ISSUE THREAD

**Issue by larryqiann** [rustdesk/rustdesk#4068]
### Description

Would it be possible to have nightly iOS builds in .ipa format to go with all of the other platforms' nightlies? The version in the App Store is from quite a long time ago.

The app doesn't have to be signed as many methods exist for users to sideload ipa applications using their own free Apple account

Thanks!

### Impact

iOS users who wish to use nightly builds

**Comment by rustdesk** [comment]
@Kingtous https://github.com/rustdesk/rustdesk/issues/3703#issuecomment-1474740035

**Comment by Kingtous** [comment]
> @Kingtous [#3703 (comment)](https://github.com/rustdesk/rustdesk/issues/3703#issuecomment-1474740035)

I'll try it, but due to the lack of Mac devices these days, maybe a little late. :)

**Comment by rustdesk** [comment]
@larryqiann we can build it, but how do you install it then?

**Comment by larryqiann** [comment]
One popular method is using AltStore, which is the most popular method because it's free and easy.
I also personally have my device registered on a UDID registration site, which allows me to upload and sign IPAs with a developer account so that they work for a whole year. It does, however, cost money.

**Comment by trinvh** [comment]
@rustdesk please build it. I had to build it manually and successfully sideloaded into my phone but it's just showing blank white screen

In the ios build guide the dependent files are missing aom https://github.com/rustdesk/rustdesk/issues/708
