### ISSUE TITLE
Apply language PR before to build a new nightly version

### ISSUE THREAD

**Issue by bovirus** [rustdesk/rustdesk#4073]
### Description

@rustedersk

If you can please check and apply language PR before to build  anew nightly version.

Otherwise to see the changes with new language PR should be wait next day.

Thanks. 

### Impact

To have translation always updated.

### Additional Context

@rustedersk

If you can please check and apply language PR befroe to build  anew nightly version.

Otherwise to see the chanegs with new language PR should be wait next day.

Thanks.

**Comment by rustdesk** [comment]
discussion next time please.
