### ISSUE TITLE
RELAY_SERVER address variable

### ISSUE THREAD

**Issue by ivan-ivanov-1** [rustdesk/rustdesk#4078]
Hello!
How can I set RELAY_SERVER secret with my own server to build custom clients with github actions?
RENDEZVOUS_SERVER and RS_PUB_KEY work fine, but in flutter-build.yml I don't see any mentions of relay server.
Can I hardcode this parameter? How should it be named?  
![Screenshot_1](https://user-images.githubusercontent.com/77321248/231543179-695d6ba6-130e-4491-b9df-161194c80bdb.png)

_Originally posted by @ydrob in https://github.com/rustdesk/rustdesk/discussions/4030_

**Comment by rustdesk** [comment]
#763
