### ISSUE TITLE
Rustdesk logo

### ISSUE THREAD

**Issue by giuliovale** [rustdesk/rustdesk#4079]
### Bug Description

The Rustdesk logo on the site is the previous one

### How to Reproduce

Visit the site

### Expected Behavior

New logo

### Operating system(s) on local side and remote side

Windows -> Windows

### RustDesk Version(s) on local side and remote side

Nightly -> Nightly

### Screenshots

![image](https://user-images.githubusercontent.com/6909743/232330232-b953a7db-1b37-42da-9c0b-609c15043383.png)

**Comment by rustdesk** [comment]
Of course, we know.
