### ISSUE TITLE
When Rustdesk 1.2.0 is used in a Hyper-V virtual machine, the response will be very slow

### ISSUE THREAD

**Issue by bgycn** [rustdesk/rustdesk#4080]
### Bug Description

When Rustdesk 1.2.0 is used in a Hyper-V virtual machine, the response will be very slow and very high latency when connected from another computer for remote control. Rustdesk 1.1.9 does not have this problem.

### How to Reproduce

Start Rustdesk on the Hyper-V host and connect to Rustdesk in the virtual machine. This problem occurs when the Rustdesk in the virtual machine is 1.2.0. If the Rustdesk in the virtual machine returns to 1.1.9, there will be no problem.This becomes especially severe when encoding with h.265

### Expected Behavior

In virtual machines, 1.2.0 should not be slower than 1.1.9 to respond

### Operating system(s) on local side and remote side

windows 11 -> windows 11

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0

### Screenshots

The screenshot does not explain the problem, please try it in a Hyper-V virtual machine, my computer is Intel 12700K, 32GB memory, RTX 3050

**Comment by rustdesk** [comment]
#3434

**Comment by bgycn** [comment]
I feel that this problem is different from #3434. Please see this video. The left side is an enhanced session of Hyper-V, and the right side is Rustdesk 1.2.0. Hardware acceleration is canceled and VP9 encoding is used. When directly dragging the left Hyper- In the V window, the video transmission is very smooth, but when dragging the Rustdesk window on the right, it becomes very stuck, and it feels like the event transmission of the mouse and keyboard has lost packets.

https://user-images.githubusercontent.com/78190214/232437459-49076c1c-1c2b-4226-abfd-4557819172a5.mp4

**Comment by isential-gmbh** [comment]
RustDesk 1.3.8

I have the same issue: I installed RustDesk on a virtual PC (Hyper-V). When I try to remote control this virtual PC, the performance is extremely slow, making normal work impossible. Is this issue still being investigated?
