### ISSUE TITLE
CLI SSH/WinRM mode

### ISSUE THREAD

**Issue by Doumor** [rustdesk/rustdesk#4084]
### Description

Some computers are behind NAT or do not have static ip, so direct access via SSH or WinRM to them is not possible. Remote desktop applications like RustDesk allow you to enter graphical mode, or file transfer mode, but you may only need to work in and through the console.

Therefore, I propose to make the console mode, which will give access as SSH or WinRM and therefore will not require direct access via ip.

It could look like the current Wayland startup, that is, when in the console we run the service, and work to gain access from the console to the remote console through a layer rustdesk-cli, or command-line arguments.

I'd like to help with the code, but I'm weak in Rust and I just can't understand the current codebase, but would like to.

### Impact

After the appearance of this feature RustDesk can be used not only to maintain computers with a graphical shell, but also without. This may become important for jobs where SSH or WinRM are sufficient.

**Comment by rustdesk** [comment]
#49
