### ISSUE TITLE
Android - Screen capture dialog on boot and blank applications

### ISSUE THREAD

**Issue by sebastianschauenburg** [rustdesk/rustdesk#4087]
### Bug Description

Thanks for this terrific project! I am aiming to use it to help out a certain, very non-technical, elderly, "friend", for which provide assistance.  (I'm purposely being a bit vague, because I don't want to embarrass him/her)

To test the 'user experience' (because I will get all the questions), I am using my own [Fairphone 4](https://www.fairphone.com/en/) with Android 12.  The unattended mode works quite great, but I have some feedback.

- when the phone is rebooted, a pop-up "Screen capture" pop-up is displayed to allow Rustdesk to record the screen. Is there a way to disable this? (e.g. allow by default)
- when I look at [Signal messenger](https://signal.org/) it is displayed as a blank application (a big black screen). Is there a way to workaround this? (because I already get questions about specific bits inside certain apps).
- somehow Input control broke (it worked for the first 3-5 times).
- I am unable to remotely unlock the phone. I also cannot see the 'pattern' dialog, for which I know the pattern.

### How to Reproduce

- Set up Rustdesk on Android
- enable unattended mode with a fixed password
- test the connection (also test re-connecting)
- reboot the phone
- try to unlock the phone / see the pop-up when logged in manually

The input control issue might be something completely unrelated, but I'm putting in here, in case anyone else also notices it.

### Expected Behavior

- after a phone reboot, Rustdesk would 'just work', no pop-ups displayed
- input always working, or if it breaks, a proper error message

### Operating system(s) on local side and remote side

Ubuntu 22.10 -> Android 12

### RustDesk Version(s) on local side and remote side

1.1.9 -> nightly

### Screenshots

![image](https://user-images.githubusercontent.com/8626247/232505879-6ddea133-62cc-44a3-9de4-4ce4ed6ac03f.png)

**Comment by rustdesk** [comment]
#3990

**Comment by sebastianschauenburg** [comment]
#3893
