### ISSUE TITLE
Cannot paste text in WSL console

### ISSUE THREAD

**Issue by Noexpert** [rustdesk/rustdesk#409]
I cannot paste in the WSL terminal window using  [CTRL] + [SHIFT] + [V]
https://devblogs.microsoft.com/commandline/copy-and-paste-arrives-for-linuxwsl-consoles/

This is on version 1.1.8 and installed on the remote machine.

**Comment by rustdesk** [comment]
Could u please help try out this one https://github.com/rustdesk/rustdesk/releases/download/tmp/rustdesk-1.1.9-putes.exe? please install on both side.

**Comment by grummbeer** [comment]
@Noexpert please try with a nightly version: https://github.com/rustdesk/rustdesk/releases/tag/nightly
Is this issue still exists?
