### ISSUE TITLE
Can't select words with double click

### ISSUE THREAD

**Issue by DiThi** [rustdesk/rustdesk#4090]
### Bug Description

What the title says. In any text editor, browser, etc. when double clicking to select words, or when double click-drag to select multiple words, it selects the whole line or paragraph, as if I actually did a triple click.

### How to Reproduce

Double click a word in a text editor, or double click-drag multiple words.

### Expected Behavior

The word or words should selected, not the whole line or paragraph.

### Operating system(s) on local side and remote side

Arch Linux (KDE Plasma) -> Windows 10

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

Not needed.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/tag/nightly
