### ISSUE TITLE
Shift is not correctly interpreted in non-English keyboard layout

### ISSUE THREAD

**Issue by pavel-krivanek** [rustdesk/rustdesk#4092]
### Bug Description

Machine 1 with the Czech keyboard layout is connected to a Machine 2 with the German layout (which is probably not important). 
The standard behavior of Czech keyboard layout:
- pressing key corresponding to 3 on the English keyboard - writes š (s with hook)
- pressing key corresponding to 3 on the English keyboard + Shift - writes 3

In RustDesk:
- pressing the key corresponding to 3 on the English keyboard - writes š (s with a hook), correct
- pressing the key corresponding to 3 on the English keyboard + Shift - writes Š (uppercase S with a hook)

So it looks like RustDesk detects if the input character is a letter and makes it uppercase when Shift is pressed. Numbers cannot be written.

This issue is the same for the other keys in that row, not only Š.

There is a related issue with the correct writing of uppercase Š in RustDesk. The Czech keyboard uses dead keys to write accents so the key two keys right from English 0, if pressed, writes a comma above the next entered character (like é) and with pressed with Shift, it adds a hook (like ě). In RustDesk, it always adds only a comma above the character, so it looks like Shift is ignored for the key.

I expect that the issue is general and not specific to the Czech keyboard layout.

### How to Reproduce

- On Windows for both machines, connect with Czech keyboard layout installed and set
- press Shift + 3
- writes Š

### Expected Behavior

- On Windows for both machines, connect with Czech keyboard layout installed and set
- press Shift + 3
- writes 3

### Operating system(s) on local side and remote side

Windows 10 (both)

### RustDesk Version(s) on local side and remote side

1.1.9 (both, installed version)

### Screenshots

Layout picture of the Czech keyboard: https://upload.wikimedia.org/wikipedia/commons/9/98/Windows_Czech_keyboard_layout.svg

**Comment by rustdesk** [comment]
#1547
