### ISSUE TITLE
Scroll not working from touchpad (Linux Wayland client, nightly)

### ISSUE THREAD

**Issue by cheywood** [rustdesk/rustdesk#4101]
### Bug Description

Firstly, bravo for RustDesk! I've just migrated. Excellent work!

Using a nightly from 18 April scroll events aren't going through from a touchpad.

I haven't had the opportunity to try an Xorg session yet, but I can confirm that scroll events from a conventional mouse get through.

Related to, but more specific than, #3744.

### How to Reproduce

1. Running under a client Wayland session launch the nightly and connect to any type of host
2. Attempt to scroll (vertically) from touchpad

### Expected Behavior

Scrolling events should be passed through

### Operating system(s) on local side and remote side

Debian testing (Wayland) > any

### RustDesk Version(s) on local side and remote side

Nightly (pre 1.2.0) > 1.1.9

### Screenshots

.

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
@cheywood try out nightly -> nightly please.

**Comment by cheywood** [comment]
Brilliant thanks, that's working. However unfortunately it's borderline too fast to be useful (Debian testing Wayland to Ubuntu LTS Xorg). Will comment in #2655, closing here.
