### ISSUE TITLE
The .exe file I compiled on Win10 cannot run on Win7 and prompts error code 0xc000007b

### ISSUE THREAD

**Issue by 82kg** [rustdesk/rustdesk#4103]
### Bug Description

I compiled  rustdesk on Win10 ，it runs well.
but when i run it on win7 x64  ，it can not run. and  prompts error code 0xc000007b

![pic2](https://user-images.githubusercontent.com/31686230/232942853-a251fb9d-346d-4a5e-99ce-a17e33bb1252.png)

I don't know where it went wrong

please help

### How to Reproduce

just in my environment

### Expected Behavior

just in my environment

### Operating system(s) on local side and remote side

win7 x64

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![pic1](https://user-images.githubusercontent.com/31686230/232943151-2a60ae25-4234-494b-a1ff-1e823ffffac0.png)
i solved dll problem, then it has a new porblem with  pic2
![pic2](https://user-images.githubusercontent.com/31686230/232943154-ddf5902b-5b0c-4c01-95b5-0010b88f9b0b.png)

**Comment by rustdesk** [comment]
#763
