### ISSUE TITLE
In the keyboard translate mode, Ctrl key is not auto-repeated

### ISSUE THREAD

**Issue by pavel-krivanek** [rustdesk/rustdesk#4108]
### Bug Description

We are trying to connect from a Czech keyboard Windows 10 client to an English keyboard Windows 10 host with the translate mode. The application we operate (Pharo IDE) uses custom GUI drawing based on SDL drawing and events handling. The translated keyboard mode works well with one exception - combinations of Ctrl+any key. For other applications like Notepad, it works, so I tried to find some other case that could be easier to reproduce for you. And I found that the Ctrl key presses are not correctly auto-repeated - which may be related. The SDL may not be informed that the key is still pressed.

### How to Reproduce

- connect from Windows client to a Windows host 
- set keyboard Translate mode
- in the host, open browser and go to web keyboard events viewer, like https://w3c.github.io/uievents/tools/key-event-viewer.html
- press Ctrl, hold it a few moments and then press C
- you will see that Ctrl key press is auto-repeated

- in the client, open browser and go to web keyboard events viewer, like https://w3c.github.io/uievents/tools/key-event-viewer.html
- press Ctrl, hold it a few moments and then press C
- there is only one Ctrl event

see the screenshots

### Expected Behavior

Control key press events should be auto-repeated as in case of local host.

### Operating system(s) on local side and remote side

Windows 10 (both)

### RustDesk Version(s) on local side and remote side

rustdesk-1.2.0 nightly

### Screenshots

on host:

![image](https://user-images.githubusercontent.com/572494/233042246-55aebb6d-68ff-4186-93c3-0450e3dc3fd7.png)

on client:

![image](https://user-images.githubusercontent.com/572494/233042416-41e6685d-25d8-4a95-a565-7d675afd95cf.png)

**Comment by rustdesk** [comment]
Repeated in AnyDesk / TeamViewer?

**Comment by pavel-krivanek** [comment]
Yes, result from TeamViewer. 

![image](https://user-images.githubusercontent.com/572494/233050671-55ffebaf-ba81-4470-ad93-a802654b4a6c.png)

**Comment by rustdesk** [comment]
@fufesou

**Comment by pavel-krivanek** [comment]
It has the same result in Map mode, which means it is probably not really related to the original SDL issue because in Map mode, the Ctrl works in SDL as expected. In AnyDesk, there isn't this issue with SDL events while it translates keyboard layout a similar way as the Translate mode does (while it has some small issues with dead characters).

**Comment by rustdesk** [comment]
Frankly, we can only put this issue in low priority.

**Comment by rustdesk** [comment]
Can you make a table like this? 

|         | anydesk     | teamview | rustdesk |
|--------------|-----------|------------|----|
| map mode | ok      | ok      | ok |
| translate mode | ok      | ok      | no |

**Comment by fufesou** [comment]
Hi @pavel-krivanek, long-press modifiers are ignored in rustdesk,

https://github.com/rustdesk/rustdesk/blob/f7db94587cb5ddc483ab4dc8820c7b6f06ff27ec/src/keyboard.rs#L107

Both "Map mode" and "Translate mode" do not repeate `Ctrl` key.
I'm not sure if this logic is appropriate.

But your issue may be caused by some other reasons.

> The translated keyboard mode works well with one exception - combinations of Ctrl+any key. For other applications like Notepad, it works, so I tried to find some other case that could be easier to reproduce for you.
> ...in Map mode, the Ctrl works in SDL as expected. 

Maybe SDL cann't handle the hotkey well with rustdesk's "Translate mode".

Can you please test with this tool
https://github.com/rustdesk/rustdesk/issues/3928#issuecomment-1498551173

https://user-images.githubusercontent.com/13586388/233062312-a9779edf-5d16-4c48-aa60-574748042b6d.mp4

**Comment by pavel-krivanek** [comment]
## Ctrl auto-repeat
| Item         | RustDesk | AnyDesk | TeamViewer
|--------------|-----------|------------|------------|
| Map mode | no     | ok        | ok
| Translate mode | no  | ok | ok 

## Ctrl+A in SDL

| Item         | RustDesk | AnyDesk | TeamViewer
|--------------|-----------|------------|------------|
| Map mode | ok     | ok        | ok
| Translate mode| no  | ok | ok

**Comment by pavel-krivanek** [comment]
The utility helps a lot! For pressing of Ctrl+A

## localhost

VK Code: 0x41 (65) VK_A
Scan Code: 0x1E  (30)

## Map mode (ok)

VK Code: 0x41 (65) VK_A
Scan Code: 0x1E  (30)

## Translate mode (fail)

VK Code: 0x41 (65) VK_A
**Scan Code: 0x00  (0)**

**Comment by fufesou** [comment]
`VK_A` should be enough to simulate the hotkey in previous tests.

Does `Ctrl + A` work with notepad or brower?

If it works on the other applications.

> The application we operate (Pharo IDE) uses custom GUI drawing based on SDL drawing and events handling.

Maybe for this application, `Scan Code` should also be specified.
This may not be a common case.

Anyway it is possible to emulate `Scan Code` while emulating the `VK_`.

**Comment by rustdesk** [comment]
@pavel-krivanek can you try the new build? 
Ctrl + A should work in sdl 2 now

**Comment by pavel-krivanek** [comment]
It works! 

But there is a strange side-effect - the SDL application then thinks that the Ctrl is pressed forever (until the host side changes state locally). A quick investigation showed that SDL does not pass the keyboard up events.

For key presses Ctrl down, A down, A up, Ctrl up:

## Local (number is order)

13130 SDL_KeyDownEvent
13131 SDL_KeyDownEvent
13132 SDL_KeyUpEvent
13133 SDL_KeyUpEvent

## Remote Translate mode (fail)

13134 SDL_KeyDownEvent
13135 SDL_KeyDownEvent

## Remote Map mode

13150 SDL_KeyDownEvent
13151 SDL_KeyDownEvent
13152 SDL_KeyUpEvent
13153 SDL_KeyUpEvent

**Comment by fufesou** [comment]
Yes, "Translate mode" release the `VK_` code rather than the `Scan Code`. I've fixed it.

**Comment by pavel-krivanek** [comment]
Perfect! Works now. 

Will you keep this issue opened for Ctrl auto-repeat?

**Comment by fufesou** [comment]
The previous code intentionally ignores `Ctrl` long-pressing.

https://github.com/rustdesk/rustdesk/blob/f7db94587cb5ddc483ab4dc8820c7b6f06ff27ec/src/keyboard.rs#L107
