### ISSUE TITLE
os error 10054

### ISSUE THREAD

**Issue by qintian95** [rustdesk/rustdesk#411]
连接远程桌面报这错，是啥原因呢
![1645410756(1)](https://user-images.githubusercontent.com/39986452/154879617-d4071600-742c-455a-8952-5981c419c3d2.jpg)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/106

**Comment by rustdesk** [comment]
Could u please help try out this one https://github.com/rustdesk/rustdesk/releases/download/tmp/rustdesk-1.1.9-putes.exe? please install on both side.

**Comment by qintian95** [comment]
ok

**Comment by neyuki** [comment]
rustdesk, is it a problem on a client or a server side?

**Comment by rustdesk** [comment]
> rustdesk, is it a problem on a client or a server side?

Client side, our server is also open source now, https://github.com/rustdesk/rustdesk-server

**Comment by 21pages** [comment]
Do you know how to reproduce？

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1113#issuecomment-1200250142

**Comment by rustdesk** [comment]
close this so that we can focus on its dup https://github.com/rustdesk/rustdesk/issues/1113.
