### ISSUE TITLE
[Feature Request] Add support for a preconfigured id/relay server

### ISSUE THREAD

**Issue by 0xlord** [rustdesk/rustdesk#4110]
### Description

We can put host ip/name and the secret as a parameter on the file. But can we do the same with the relay server. This would be incredible helpfull to preconfigure an executable to use a certain self hosted id/relay server so customers just need to give the id/password.

For example I am giving a customer the file rustdesk-relay=help.acme.net.exe. He opens it and it already uses help.acme.net as an id/relay server.

We would like to roll out RustDesk as a remote help tool in our environment but this is like the last straw which needs to be addressed to make sure people are being relayed through our internal servers.

### Impact

Every admin can enforce usage of his server and thus put away the need of configuration from every form of user. 
This would make the client deployment seamless without the need of any action on side of the "customer".

### Additional Context

Preferably a exe creation which includes various settings like id/relay server, public key and so on would be incredible helpful. But for now setting a custom filename like with ip and key parameters would be enough.

**Comment by 0xlord** [comment]
Sad that you "wontfix" this issue. Bit of context would be nice. Or did I oversee something and thus this can be set already?

**Comment by spiderfudge** [comment]
Please re-open this issue. Or provide another way to bundle the configuration. This is a huge limitation.

**Comment by gehkah** [comment]
> Sad that you "wontfix" this issue. Bit of context would be nice. Or did I oversee something and thus this can be set already?

https://github.com/rustdesk/rustdesk/discussions/763  -> he won't answer compiling questions anymore 
(what I do understand)

https://github.com/rustdesk/rustdesk/issues/3328

**Comment by gehkah** [comment]
> [@0xlord](https://github.com/0xlord) Both of those pages ware sent down, now only showing `404 Page Not Found`

https://www.reddit.com/r/rustdesk/s/fNLeHcVJao
