### ISSUE TITLE
Caret typing not possible with Translate mode on German and Czech layout on Windows

### ISSUE THREAD

**Issue by pavel-krivanek** [rustdesk/rustdesk#4126]
### Bug Description

The caret character has these ways of typing on German and Czech layouts:

## German layout

- type ``` key (backtick key, one key left from `1` on the English keyboard, the key in top left corner)
- type `Space`

## Czech layout

- type `AltGr+3` key 
- type `Space`

It is very strange way of doing it (the Czech keyboard for Linux usually maps it differently, for example), but it is done this way because it partly plays the role of a dead key. So, if you 
- press `AltGr+3` and then press Space, it outputs `^` (standalone caret symbol)
- press `AltGr+3` and then press `A`, it outputs `â` (standalone caret symbol)

It is not only specific to the caret symbol, it is similar for ˇ˘°˛`´
They are written by a combination of `AltGr+some number key` followed by Space or desired letter. 

In Map mode, it works as expected.

### How to Reproduce

- connect from a client with a German layout to a host with any layout
- switch keyboard mode to Translate mode
- open Notepad and press the backtick key, release that key and press Space
- writes space, should write `^`

Note, for playing with different crazy Windows configurations, you may use Windows Sandbox

Windows Sandbox
https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview
Windows Sandbox configuration 
https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file

### Expected Behavior

pressing the backtick key, followed by Space should write `^`

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0 nightly

### Screenshots

(not useful)

**Comment by rustdesk** [comment]
work in anydesk?

**Comment by rustdesk** [comment]
@fufesou confirm if it is feasible in translation mode.

**Comment by rustdesk** [comment]
@pavel-krivanek could you try the new build?

**Comment by pavel-krivanek** [comment]
Amazing, everything works as expected! 

I'm closing the issue then.
