### ISSUE TITLE
Using "Direct IP" only with plain hostname - no server, no port number

### ISSUE THREAD

**Issue by zackholz** [rustdesk/rustdesk#4131]
### Bug Description

Concerning the use of "Direct IP" (only this, no server): Can RustDesk actually connect with entering only a hostname? 
In my tests it did not, only when entering an IP (with or without port number). 
So I decided to batch-script nslookup, which helped to get to the target by entering only a hostname, e.g. "ABCD1234" (without quotation marks).
I just would like to have this mechanism built in into RustDesk itself. 
(Maybe it already is, but my network needs to allow something it does not?)

### How to Reproduce

Enter a hostname of your local network in the form "Control Remote Desktop" / "Enter Remote ID".

### Expected Behavior

Establish connection to the host "ABCD1234".

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0

### Screenshots

![unnamed](https://user-images.githubusercontent.com/131375913/233399035-4ee690db-90e1-4a6e-b67e-8994da7646ab.png)

### Additional Context

Tested with nightly of 2023-02-01 06:47.

**Comment by rustdesk** [comment]
#2847

**Comment by zackholz** [comment]
![2023-04-20-RustDesk-error-hostname-only](https://user-images.githubusercontent.com/131375913/233400802-107b22ec-4df3-42f4-a0ea-4c146a435432.png)

Error message

**Comment by zackholz** [comment]
Could you give an example for "url regex plus :\d+", which should be enough?
