### ISSUE TITLE
If RustDesk connected, then hosting machine can´t type some diacritics characters

### ISSUE THREAD

**Issue by yardstudio** [rustdesk/rustdesk#4135]
### Bug Description

I observe, that if RustDesk is connected to remote PC, then I can´t type some diacritics characters with ˇ or ´ ?

I am using Slovak language and can´t type Óó ĽĹ Ňň .. or any diacritics where need push SHIFT + ˇ or SHIFT + ´ and next step type character (oO or similar)

### How to Reproduce

1. Install Slovak QWERTY language keyboard, 
2. open Notepad
3. type ľĽ Šš Čč óÓ or some similar  characters with diacritics (hold SHIFT + ˇ + L for example)
4. Open RustDesk and connect to remote pc
5. Repeat step 3

Button ˇ stop working after connection

### Expected Behavior

must working type ľĽ Šš Čč óÓ or some similar  characters with diacritics (hold SHIFT + ˇ + L for example) if RustDesk is opened

### Operating system(s) on local side and remote side

Windows 10 22H2

### RustDesk Version(s) on local side and remote side

newest

### Screenshots

![2023-04-20_20-13-31](https://user-images.githubusercontent.com/25852179/233452527-79071691-4107-4578-a21f-db0ed72ccd07.png)

**Comment by rustdesk** [comment]
#1547
