### ISSUE TITLE
Connection refused after rustdesk password was entered | Linux <-> Linux

### ISSUE THREAD

**Issue by awalon** [rustdesk/rustdesk#4136]
### Bug Description

"Connection refused" running recent nightly version (both sides):

Log from remote side (linux as qemu guest):
`[2023-04-21 00:05:04.347353 +02:00] INFO [src/platform/linux.rs:211] DISPLAY: :0
[2023-04-21 00:05:04.347457 +02:00] INFO [src/platform/linux.rs:212] XAUTHORITY: /var/lib/sddm/.Xauthority`

File is missing: /var/lib/sddm/.Xauthority

### How to Reproduce

1. start connection to linux remote (running X11, plasma with sddm) from another linux instance
2. enter correct permanent password
3. Error: connection refused

### Expected Behavior

Connection is working after successful login.

### Operating system(s) on local side and remote side

Linux -> Linux

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

-

### Additional Context

Found:
`/var/run/sddm/{8ed08636-0dad-4fd7-9740-ea2d04831a3e}`
used by sddm process running on remote side by checking all processes:
`sudo cat /proc/*/environ|tr "\0" "\n" | grep -a "^XAUTHORITY=" | sed 's/XAUTHORITY=//g'`

Workaround
`sudo ln -s "/var/run/sddm/{8ed08636-0dad-4fd7-9740-ea2d04831a3e}" "/var/lib/sddm/.Xauthority"`
Restarted rustdesk service on remote side but not sure if needed.
As result: Connection to sddm Login screen works as expected

**Comment by awalon** [comment]
In addtion to initial bug report "connection refused" occures after remote login (sddm)  as well.
```
sudo loginctl list-sessions:

SESSION       UID USER               SEAT  TTY
   2897 384700801 user@domain seat0
   4195 384700801 user@domain       pts/0
   4253 384700801 user@domain seat0
```
Rustdesk log:
```
[2023-04-21 00:23:56.810089 +02:00] INFO [src/platform/linux.rs:211] DISPLAY: :0
[2023-04-21 00:23:56.810198 +02:00] INFO [src/platform/linux.rs:212] XAUTHORITY: /var/lib/user@domain/.Xauthority
```
File not found as well

With:
`sudo ls -1 /proc/*/environ|xargs -I___ sudo grep -a -H -o -P "(?<=XAUTHORITY=)(.+?)(?=\x0)" "___"
`
This was detected at process: "/usr/lib/rustdesk/rustdesk --server"

Maybe files (have to exist) should be initialy checked against all candidates:
`sudo loginctl list-sessions 2>&1| grep -o -P "^\s*\d+" | xargs -Ixxx grep -H xxx /proc/*/sessionid | cut -d"/" -f3 | xargs -I___ sudo grep -a -o -P "(?<=XAUTHORITY=)(.+?)(?=\x0)" "/proc/___/environ"| sort --unique`

Or ask user which session should be used for connection.

**Comment by rustdesk** [comment]
#3565

**Comment by awalon** [comment]
@rustdesk 
I can fix this problem during next days, there are multiple places where user home pathes are just generated instead of read from system configuration. That's why the auth file path is pointing to wrong (none existing) user folders.  
How (by which issue) can a fix be provided as this ticket was already closed?

**Comment by rustdesk** [comment]
You can submit a PR.

**Comment by rustdesk** [comment]
Close as fix merged
