### ISSUE TITLE
Self-hosted server. The client shows Not ready. Please check your connection. I've tried all the method to solve this problem but anything worked.

### ISSUE THREAD

**Issue by wxf26054** [rustdesk/rustdesk#4139]
### Bug Description

Not ready. Please check your connection. I've tried all the method to solve this problem but no any works.

### How to Reproduce

1. Open the client
2. setup the connection server
3. the client shows me Not ready. Please check your connection.

### Expected Behavior

Client shows me Ready for connection.

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

Latest docker container

### Screenshots

![image](https://user-images.githubusercontent.com/22016320/233520024-f26bd192-1352-48c6-82f1-0392b6a6aada.png)
![image](https://user-images.githubusercontent.com/22016320/233520412-3367dce7-ac34-4868-96ca-f21415d40ef7.png)

All the necessary ports are opended by software default. And no any firewalls running.

**Comment by rustdesk** [comment]
#763

**Comment by wxf26054** [comment]
Solved! Thank you for your help!
