### ISSUE TITLE
Low performance of website on Firefox

### ISSUE THREAD

**Issue by kubukoz** [rustdesk/rustdesk#414]
**Describe the bug you encountered:**

The website performs at a consistent <2fps in Firefox.
...

Reasonable performance like in Chrome

...

**How did you install `RustDesk`?**

I didn't 😅 

---

**RustDesk version and environment**

N/A

---

Some screenshots from the profiler:

<img width="3173" alt="image" src="https://user-images.githubusercontent.com/894884/155172406-0ece0905-2892-41de-8238-28f7d6c345ee.png">

<img width="974" alt="image" src="https://user-images.githubusercontent.com/894884/155172495-9af1b53c-7984-4f6c-a0bd-b59ca46e22ac.png">

<img width="3182" alt="image" src="https://user-images.githubusercontent.com/894884/155172523-788470a4-c462-41f3-9523-3cdfffbac1d1.png">

(I don't know if this can be exported in any other way)

**Comment by rustdesk** [comment]
I just disabled svg animation for firefox.
