### ISSUE TITLE
Problem connecting via Domain after DNS record change

### ISSUE THREAD

**Issue by Hugo7650** [rustdesk/rustdesk#4142]
### Bug Description

 have already used DDNS to bind my IP to a domain name, and I can connect to it using {domain name}:{port}. It works well. However, when the IP changes, even if the DNS record is refreshed, it always shows Login Error: Offline.

### How to Reproduce

bind a ip to a domain name
connect the device via {domain name}:{port}
change the ip of the devices and rebind
reconnect the device

### Expected Behavior

After the ip is changed, the device can still be connected

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

nightly -> 1.1.9

### Screenshots

![rustdesk_EUzkfAmOtA](https://user-images.githubusercontent.com/31364658/233543530-1a6dc31b-1e64-41d4-a86c-4a60dc4cfa05.png)

**Comment by rustdesk** [comment]
#2245

**Comment by Hugo7650** [comment]
I replaced both server and client with the latest nightly, and reinstalled the service, it still doesn't work
