### ISSUE TITLE
Bad translation in error message - SLOVAK

### ISSUE THREAD

**Issue by yardstudio** [rustdesk/rustdesk#4143]
### Bug Description

If I am trying connect to disabled computer, then warning displayed correctly, but Slovak text is wrong

### How to Reproduce

Connect to disabled computer

### Expected Behavior

Error message "Chyba spojenia" "Vzdialená plocha je pripojená"

Correct text is "Chyba spojenia" "Vzdialená plocha nie je pripojená"

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

latest

### Screenshots

![image](https://user-images.githubusercontent.com/25852179/233567155-b42db914-5686-45df-a1df-11c9fa5ff4fd.png)

**Comment by rustdesk** [comment]
Please submit a PR to fix it.
