### ISSUE TITLE
SOCKS proxy (danted) tries Connecting and results in Not Ready

### ISSUE THREAD

**Issue by sebastianschauenburg** [rustdesk/rustdesk#4149]
### Bug Description

Connecting to a locally installed `danted` SOCKS proxy server, does not work.
On the local Ubuntu 22.10 desktop it states: `Connecting to the RustDesk network`
And on the local Windows machine it states: `Not ready. Please check your connection` (but it also showed `Connecting to the RustDesk network` at first, for about 11 seconds)

### How to Reproduce

- `apt-get install dante-server`
- apply a basic config in `/etc/danted.conf` such as:

```
logoutput: stdout syslog
internal: eth0 port = 1080
external: eth0
socksmethod: none
clientmethod: none
user.privileged: proxy
user.unprivileged: nobody
user.libwrap: nobody
client pass {
        from: 192.168.1.0/24 port 1-65535 to: 0.0.0.0/0
}
socks pass {
        from: 192.168.1.0/24 to: 0.0.0.0/0
        log: connect error
}
```
- try using the proxy server from the other VLAN, for example `192.168.1.0/24`

### Expected Behavior

Expected a connection to Rustdesk (and then be able to use it normally)

### Operating system(s) on local side and remote side

Ubuntu 22.10 / Windows 11 (both local)

### RustDesk Version(s) on local side and remote side

1.1.9 (Ubuntu) / 1.2.0 nightly (Windows) (both local)

### Screenshots

![image](https://user-images.githubusercontent.com/8626247/233635185-7a4cf7a7-d8ad-454b-90ec-41299b2f1924.png)

### Additional Context

- VLAN with IP range `192.168.1.0/24`
  - Ubuntu desktop
  - Windows desktop
- VLAN with IP range `192.168.2.0/24`
  -  DANTE proxy
- both VLANs have internet access)
- custom RustDesk server is running on a cloud VPS
- When _not_ using the SOCKS proxy, it works fine.
- Proxy server works (tested with Firefox, using its internal proxy configuration)

# logs

I see log entries like the following (which indicate an initial connection is made) from the Windows machine:

```
apr 21 01:33:42 server danted[2095]: info: pass(1): udp/udpassociate [: 0.0.0.0.51612 192.168.2.2.38242
apr 21 01:33:42 server danted[2095]: Apr 21 14:33:42 (1682010422.451412) danted[2095]: info: pass(1): udp/udpassociate [: 0.0.0.0.51612 192.168.2.2.38242
```
and when I close RustDesk I see:
```
apr 21 01:35:45 server danted[2014]: info: pass(1): udp/udpassociate ]: 0/0 -> 192.168.1.2.51612 192.168.2.2.38242 -> 2387/77, 1078/77 -> 192.168.2.2.51612 ip.of.cloud.server.21116 -> 154/77: local client error (Connection reset by peer).  Session duration: 123s
apr 21 01:35:45 server danted[2014]: Apr 21 14:35:45 (1682010545.696064) danted[2014]: info: pass(1): udp/udpassociate ]: 0/0 -> 192.168.1.109.51612 192.168.2.2.38242 -> 2387/77, 1078/77 -> 192.168.2.2.51612 ip.of.cloud.server.21116 -> 154/77: local client error (Connection reset by peer).  Session duration: 123s
```

From the Linux machine, I see 2 connections being made, but nothing when I close Rustdesk:
```
apr 21 01:39:25 server danted[2098]: info: pass(1): udp/udpassociate [: 0.0.0.0.45090 192.168.2.2.55767
apr 21 01:39:25 server danted[2098]: Apr 21 01:39:25 (1682010765.749219) danted[2098]: info: pass(1): udp/udpassociate [: 0.0.0.0.45090 192.168.2.2.55767
apr 21 01:39:28 server danted[2100]: info: pass(1): udp/udpassociate [: 0.0.0.0.49123 192.168.2.2.38238
apr 21 01:39:28 server danted[2100]: Apr 21 01:39:28 (1682010768.984646) danted[2100]: info: pass(1): udp/udpassociate [: 0.0.0.0.49123 192.168.2.2.38238
```

**Comment by rustdesk** [comment]
#2232

**Comment by sebastianschauenburg** [comment]
@rustdesk 

https://github.com/rustdesk/rustdesk/issues/2232 seems similar but not the same. I read through it and the submitter seems to have had firewall issues (which is not the case here, I assume). Currently: on the server on which `dante` is running, iptables has the default INPUT policy ACCEPT. Please note that my selfhosted Rustdesk server seems to run fine (it works when I do not use the SOCKS proxy)

**Comment by jm789** [comment]
I'm running into the same issue - has there been an update tot his please?

**Comment by miyouzi** [comment]
I have the same problem.
My self-built Rustdesk Server and Socks5 Proxy Server both function normally when used separately, but encounter errors when used together. I have no idea why this is happening.
