### ISSUE TITLE
Cannot compile under Win64

### ISSUE THREAD

**Issue by aschegolskiy** [rustdesk/rustdesk#4152]
### Bug Description

[16:55, 21.04.2023] Сергей Кравцов: git clone https://github.com/rustdesk/rustdesk
[16:55, 21.04.2023] Сергей Кравцов: CMake Error at flutter/CMakeLists.txt:7 (include):
  include could not find requested file:

    C:/Projects/rustdesk-master/flutter/windows/flutter/ephemeral/generated_config.cmake

CMake Error at CMakeLists.txt:71 (include):
  include could not find requested file:

    flutter/generated_plugins.cmake
[16:57, 21.04.2023] Сергей Кравцов: Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19045.
The CXX compiler identification is MSVC 19.35.32217.1
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
CMake Error at flutter/CMakeLists.txt:7 (include):
  include could not find requested file:

    C:/Projects/rustdesk-master/flutter/windows/flutter/ephemeral/generated_config.cmake

CMake Error at CMakeLists.txt:71 (include):
  include could not find requested file:

    flutter/generated_plugins.cmake

rustdesk lib build type: $<IF:$<CONFIG:Debug>,debug,release>
Configuring incomplete, errors occurred!
See also "C:/Projects/vcpkg-master/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/CMakeFiles/CMakeOutput.log".

### How to Reproduce

[16:55, 21.04.2023] Сергей Кравцов: git clone https://github.com/rustdesk/rustdesk
[16:55, 21.04.2023] Сергей Кравцов: CMake Error at flutter/CMakeLists.txt:7 (include):
  include could not find requested file:

    C:/Projects/rustdesk-master/flutter/windows/flutter/ephemeral/generated_config.cmake

CMake Error at CMakeLists.txt:71 (include):
  include could not find requested file:

    flutter/generated_plugins.cmake
[16:57, 21.04.2023] Сергей Кравцов: Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19045.
The CXX compiler identification is MSVC 19.35.32217.1
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
CMake Error at flutter/CMakeLists.txt:7 (include):
  include could not find requested file:

    C:/Projects/rustdesk-master/flutter/windows/flutter/ephemeral/generated_config.cmake

CMake Error at CMakeLists.txt:71 (include):
  include could not find requested file:

    flutter/generated_plugins.cmake

rustdesk lib build type: $<IF:$<CONFIG:Debug>,debug,release>
Configuring incomplete, errors occurred!
See also "C:/Projects/vcpkg-master/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/CMakeFiles/CMakeOutput.log".

### Expected Behavior

Should be compiled

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

Log included

**Comment by simonclouds** [comment]
same problem to me , no idea
