### ISSUE TITLE
i con't enable h265 codec in version 1.2.0.

### ISSUE THREAD

**Issue by mbtolou** [rustdesk/rustdesk#4155]
### Bug Description

https://github.com/rustdesk/rustdesk/discussions/4146#discussion-5114422

i con't enable h265 codec in version 1.2.0.
only vp9 codec worked for me.

### How to Reproduce

i dont know.

### Expected Behavior

i dont know.

### Operating system(s) on local side and remote side

windows 10 > windows 10

### RustDesk Version(s) on local side and remote side

1.2.0>1.2.0

### Screenshots

![image](https://user-images.githubusercontent.com/6413705/233677985-23fdf154-155a-4aae-8c0e-1e2cf4da4d07.png)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/4095
