### ISSUE TITLE
rustdesk.com domain expiry

### ISSUE THREAD

**Issue by zontreck** [rustdesk/rustdesk#4157]
### Bug Description

The rustdesk.com domain appears to have expired. I get a godaddy webpage when going there. HTTPS returns a error, HTTP returns godaddy.

### How to Reproduce

Visit http://rustdesk.com/

### Expected Behavior

To see the rustdesk.com website

### Operating system(s) on local side and remote side

N/A

### RustDesk Version(s) on local side and remote side

N/A

### Screenshots

![rustdesk_error](https://user-images.githubusercontent.com/1643882/233749901-61cb46d2-53ed-4580-8fb9-cd915713273e.png)

**Comment by rustdesk** [comment]
just fixed, may recover after TTL
