### ISSUE TITLE
Don't take over mouse control when window not in focus

### ISSUE THREAD

**Issue by jerryc05** [rustdesk/rustdesk#4158]
### Description

Assume that I am controlling other clients, and when the rust desk window is not in focus, my client's mouse pointer still got overridden by my mouse pointer when I accidently hover my mouse over the window. This can sometimes be annoying.

### Impact

Add an option so that I (or controllers) can only override client's mouse pointer position when rustdesk window is in focus

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1934
