### ISSUE TITLE
RustDesk for Windows does not read the correct key from the filename when Windows appends  version (#)

### ISSUE THREAD

**Issue by Benny7587** [rustdesk/rustdesk#4162]
### Bug Description

When I set the -k _  optinon on the self hosted server the public key is checked. When on Windows client B the client application is downloaded for a second time, Windows appends (1) to the filename. The Rustdesk Windows client reads the key including the (1) from the filename. When i try to connect from Client A (with the correct key) to client B the connection between the two clients is not established because the keys are different.

### How to Reproduce

First of all on the local server set the -k _ option.
Start Rustdesk with the correct key on client A. Download the Rustdesk application on client B several times and run it from the last downloaded file (with the (#) appended).

### Expected Behavior

I think the RustDesk application should read the key from the filename without the appended (#) so the connection would be established. An extra delimiter in the filename could resolve the issue because then the Rustesk for Windows application knows where the key ends.

### Operating system(s) on local side and remote side

Both Windows 11

### RustDesk Version(s) on local side and remote side

Both 1.2.0

### Screenshots

n/a

### Additional Context

n/a

**Comment by rustdesk** [comment]
close as #4124 reverted

**Comment by madpilot78** [comment]
@Benny7587 

Hi, I filed a patch in #4124 to do exactly what you ask, using # as a delimiter.

That patch was reverted. I'm not sure why but it looks like there is a misunderstanding with the fact that you say windows appends `(#)` to the file name. You mean `(1)`, `(2)` etc., not the actual # symbol, am I correct?

Could you test the patch i filed at #4124 and confirm it works for you?

The patch allows to append a `#` (literal) symbol to the filename, before the `.exe` part so the (1) appended by windows is ignored.

**Comment by rustdesk** [comment]
@madpilot78 Thanks

**Comment by Benny7587** [comment]
Hi Guido, 

 

That is exactly what I mean. There should be a delimiter separating the key from the (1) or (2) etc. that Windows appends to next downloads.

A # would indeed be a good choice. 

I just tested with the latest nightly (Version date: 23-04-23 00:21) and it seems this solution is not implemented here.

Under About RustDesk I still see: key# (2) where I would expect to see only the key.

 

Regards, Benny

 

Van: Guido Falsi ***@***.***> 
Verzonden: zondag 23 april 2023 09:15
Aan: rustdesk/rustdesk ***@***.***>
CC: Benny7587 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [rustdesk/rustdesk] RustDesk for Windows does not read the correct key from the filename when Windows appends version (#) (Issue #4162)

 

@Benny7587 <https://github.com/Benny7587> 

Hi, I filed a patch in #4124 <https://github.com/rustdesk/rustdesk/pull/4124>  to do exactly what you ask, using # as a delimiter.

That patch was reverted. I'm not sure why but it looks like there is a misunderstanding with the fact that you say windows appends (#) to the file name. You mean (1), (2) etc., not the actual # symbol, am I correct?

Could you test the patch i filed at #4124 <https://github.com/rustdesk/rustdesk/pull/4124>  and confirm it works for you?

The patch allows to append a # (literal) symbol to the filename, before the .exe part so the (1) appended by windows is ignored.

**Comment by rustdesk** [comment]
I am not sure if you download version has the patch or not. @madpilot78 if possbile, please provide a build with your patch.

**Comment by Benny7587** [comment]
Think i tested with the latest nightly where your patch was reverted. I’m not that familiar with github that I can find where to download your version of rustdesk so I can test with that specific version.

 

Van: Guido Falsi ***@***.***> 
Verzonden: zondag 23 april 2023 09:15
Aan: rustdesk/rustdesk ***@***.***>
CC: Benny7587 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [rustdesk/rustdesk] RustDesk for Windows does not read the correct key from the filename when Windows appends version (#) (Issue #4162)

 

@Benny7587 <https://github.com/Benny7587> 

Hi, I filed a patch in #4124 <https://github.com/rustdesk/rustdesk/pull/4124>  to do exactly what you ask, using # as a delimiter.

That patch was reverted. I'm not sure why but it looks like there is a misunderstanding with the fact that you say windows appends (#) to the file name. You mean (1), (2) etc., not the actual # symbol, am I correct?

Could you test the patch i filed at #4124 <https://github.com/rustdesk/rustdesk/pull/4124>  and confirm it works for you?

The patch allows to append a # (literal) symbol to the filename, before the .exe part so the (1) appended by windows is ignored.

**Comment by rustdesk** [comment]
> ### Operating system(s) on local side and remote side
> Both Windows 11
> 
> ### RustDesk Version(s) on local side and remote side
> Both 1.2.0

When was this build download?

**Comment by Benny7587** [comment]
I'm not sure if i tested with the latest build at the moment that i reported the issue but i found the issue in several builds. Furthermore i was not aware of the delimiter that was impemented at that moment.
For what i know now, my issue was exactly the same as in [#4124](https://github.com/rustdesk/rustdesk/pull/4124) 
The solution seems to be reverted because when i test with the latest version the # delimiter is not working.
Please let me know when the delimiter solution is implemented again in the nightly build and i would be glad to test this.

**Comment by Benny7587** [comment]
I found back the version of RustDesk where the # delimiter patch was implemented.
The good news is that the delimiter works however the # is not usable as a delimiter when you want to download a file with a hashtag in the filename because the # is defined as a special character in a url.
Wouldn't it be possible to use the comma as a delimiter? It has already been used as a separator between the hostname and the key. When you take the second comma in the filename as a delimiter for the key it would work i guess. But hey i'm not a programmer.

**Comment by madpilot78** [comment]
@Benny7587 I have a rustdesk executable compiled with the patch here:

https://github.com/madpilot78/rustdesk/releases

Can you test with that?

**Comment by rustdesk** [comment]
> # issue in the url

Since this, I will not recover the patch.

**Comment by Benny7587** [comment]
@madpilot I did download the version from the link and i see that in this version the # is used as a delimiter, not the comma. This works but the issue with the hashtag (#) is that when you want a customer to download the file with hostname and key from a webserver you have to translate the # into %23.
**Example:**
- filename: rustdesk-host=my.domain,key=my.key#.exe 
- download link: downloads\rustdesk-host=my.domain,key=my.key%23.exe
For me this works fine now but i think it needs more explanation to self hosting users than when the comma would be used in stead of the #.

**Comment by madpilot** [comment]
You're looking for @madpilot78

**Comment by madpilot78** [comment]
@Benny7587 

I see. I did choose # as a delimiter because it looked like a good idea to me. The patch is quite simple and is easily modified to recognize any symbol.

@rustdesk Would it be acceptable to use a comma (`,`) as a final delimiter?

**Comment by Benny7587** [comment]
@madpilot78 I've tested the Windows exe and it works fine now. 
- The comma works as a delimiter for the key;
-  The file name has no special characters anymore. So translating the url is not necessary like it was with the # character.
Thanks!

**Comment by Benny7587** [comment]
@madpilot78 Just tested with the latest nightly and it works flawless.
@rustdesk In the documentation (https://rustdesk.com/docs/en/self-host/install/) the # should be changed in comma so the rest of the world is also aware.

**Comment by madpilot78** [comment]
@Benny7587 @rustdesk 

I plan to submit an update for the documentation, today or maybe tomorrow.

**Comment by madpilot78** [comment]
Pull request here: rustdesk/doc.rustdesk.com#188
