### ISSUE TITLE
Login Error: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop

### ISSUE THREAD

**Issue by Aqua1ung** [rustdesk/rustdesk#4164]
### Bug Description

Attempting to remote into my [Clear Linux (Wayland)](https://clearlinux.org/) computer running [latest nightly rustdesk flatpak](https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64.flatpak), from my iPad. Got error message in subject line above: "Login Error: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop."

### How to Reproduce

See bug description above.

### Expected Behavior

No login error.

### Operating system(s) on local side and remote side

iPadOS 16.4.1 -> Clear Linux 38860

### RustDesk Version(s) on local side and remote side

1.1.10 -> 1.2.0

### Screenshots

![Screenshot from 2023-04-22 16-13-44](https://user-images.githubusercontent.com/12104779/233804512-8a708d5b-1a34-4e25-81e3-f50e603efd89.png)
![IMG_0275](https://user-images.githubusercontent.com/12104779/233804613-1050bfe2-1a6a-4616-868b-7ca1140257f7.PNG)

**Comment by Aqua1ung** [comment]
Same behavior encountered while running the corresponding AppImage. Here's the AppImage output:
```
dad@Spectre~/Downloads $ ./rustdesk-1.2.0-x86_64.AppImage 
Gtk-Message: 17:20:27.703: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:20:27.714: Failed to load module "canberra-gtk-module"
*** MESA_GLSL_CACHE_DISABLE is deprecated; use MESA_SHADER_CACHE_DISABLE instead ***
Fontconfig error: Cannot load default config file
flutter: launch args: []
flutter: initializing FFI main
flutter: _appType:main,info1-id:97999a8a1ccb4df281255daca2437d1b,info2-name:Clear Linux OS,dir:/home/dad/Documents
flutter: _globalFFI init
flutter: _globalFFI init end
Fontconfig error: Cannot load default config file
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
flutter: handled by uni links: false
flutter: [MultiWindowHandler] active window changed: [0]
LaunchProcess: failed to execvp:
/app/extra/nacl_helper
[1:1:0422/172040.156902:ERROR:nacl_fork_delegate_linux.cc(313)] Bad NaCl helper startup ack (0 bytes)
Gtk-Message: 17:20:40.218: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:20:40.219: Failed to load module "canberra-gtk-module"
*** MESA_GLSL_CACHE_DISABLE is deprecated; use MESA_SHADER_CACHE_DISABLE instead ***
Opening in existing browser session.

** (rustdesk:33826): WARNING **: 17:20:53.552: atk-bridge: get_device_events_reply: unknown signature
flutter: [MultiWindowHandler] active window changed: []
flutter: Start closing RustDesk...
```

**Comment by rustdesk** [comment]
#3565

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4276#issuecomment-1537105758

**Comment by bkerler** [comment]
Rustdesk 1.2.3-2 seems to be still affected
