### ISSUE TITLE
Windows 7 crash

### ISSUE THREAD

**Issue by zkteco-home** [rustdesk/rustdesk#4172]
### Bug Description

under windows 7 64bit

rustdesk 1.2.0 latest

if double click,sometimes working,sometimes not working.

but 4month ago,working fine

### How to Reproduce

![image](https://user-images.githubusercontent.com/66519168/233935987-5e81e85a-8ba0-48dc-8db7-0f1e06a30b52.png)

### Expected Behavior

according to screenshot,can reproduce it.

### Operating system(s) on local side and remote side

windows 7

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

![image](https://user-images.githubusercontent.com/66519168/233936274-6235f568-1d78-4521-a11d-bc2a3f684127.png)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3117#issuecomment-1422242788

**Comment by rustdesk** [comment]
try out https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86-sciter.exe

**Comment by zkteco-home** [comment]
> try out https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86-sciter.exe

mainly i have doubt,flutter can run under windows 7,before it works fine,recently i began to use new version and found this issue.

**Comment by rustdesk** [comment]
Nothing wierd, because we upgraded flutter from 3.0.5 to 3.7.

**Comment by zkteco-home** [comment]
@deep-soft I copied API-MS-WIN-SHCORE-SCALING-L1-1-1.dll to windows/system32,but it didnt work for rustdesk-1.2.0-x86_64.exe,maybe it works for sciter package

**Comment by deep-soft** [comment]
Yes fix is for sciter version.
If flutter version does not work on you're windows 7 version maybe you need to apply Windows update and Microsoft Visual C++ 2015-2022 Redistributable (x64)

**Comment by bt4ibwem8** [comment]
@deep-soft 
do you know how to fix this error? I got it for the latest version of flutter Rustdesk. But after i click on OK, then the same error occurs few more times and then Rustdesk open and works just fine.
When i run Rustdesk in win7 SAFE MODE, Rustdesk opens fine without this error. I get this error also with other 2-3 apps too...

![image](https://github.com/user-attachments/assets/bf5309c4-9537-4441-baf9-0030dca0ce54)

**Comment by deep-soft** [comment]
@bt4ibwem8

I tested RustDesk 1.3.0 on Windows 7, no runtime errors.

I have not installed Redistributable Runtimes from other sources than Microsoft!

I have installed these:
### Microsoft Visual C++ 2015-2018 Redistributable (x64) - 14.29.30139
https://aka.ms/vs/16/release/vc_redist.x64.exe

### Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.30.30704
https://aka.ms/vs/17/release/vc_redist.x64.exe

### Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.32.31332
https://aka.ms/vs/17/release/vc_redist.x64.exe

### Visual Studio 2015, 2017, 2019, and 2022
  This table lists the latest supported English (en-US) Microsoft Visual C++ Redistributable packages for Visual Studio 2015, 2017, 2019, and 2022. 
  The latest supported version has the most recent implemented C++ features, security, reliability, and performance improvements. 
  It also includes the latest C++ standard language and library standards conformance updates. 
  We recommend you install this version for all applications created using Visual Studio 2015, 2017, 2019, or 2022.

**Comment by bt4ibwem8** [comment]
i just tried all 3 .exe installers but the issue is still here. So i suppose the cause will be somewhere elso, not in c++ redistributable... Especially if Rustdesk runs without errors in the Safe mode of win7

**Comment by jzdcf** [comment]
> **Fix for missing: API-MS-WIN-SHCORE-SCALING-L1-1-1.dll on Windows 7**
> 
> Download and unpack attached archive: win7-API-MS-WIN-SHCORE-SCALING-L1-1-1.zip Compile using Visual Studio Version 17 and place API-MS-WIN-SHCORE-SCALING-L1-1-1.dll in Windows/System32 folder.
> 
> [win7-API-MS-WIN-SHCORE-SCALING-L1-1-1.zip](https://github.com/rustdesk/rustdesk/files/11310984/win7-API-MS-WIN-SHCORE-SCALING-L1-1-1.zip)

One thing to note: Compile the 64 bit DLL and place it in C:\Windows\System32
