### ISSUE TITLE
When controlling Win10 from Deepin, keyboard input appears as garbled characters.

### ISSUE THREAD

**Issue by coolxy** [rustdesk/rustdesk#4173]
### Bug Description

When controlling Win10 from Deepin, keyboard input appears as garbled characters.

### How to Reproduce

From Deepin Control Windowns10 ,the app is the newst,1.20

### Expected Behavior

When controlling Win10 from Deepin, keyboard input appears as garbled characters.

### Operating system(s) on local side and remote side

Linux(deepin) -> windows10

### RustDesk Version(s) on local side and remote side

1.2.0->1.2.0

### Screenshots

![Uploading rustdesk.png…]()

**Comment by rustdesk** [comment]
#3565

**Comment by rustdesk** [comment]
BTW, your image is not uploaded.

**Comment by coolxy** [comment]
The keyboard input is not corresponding and appears as garbled characters. This is the situation when I try to input "hello world."

**Comment by rustdesk** [comment]
@fufesou

**Comment by coolxy** [comment]
No, switch to English mode.
I'm using Chinese input method.

**Comment by rustdesk** [comment]
How about if turn off IME (Chinese input method)?

**Comment by coolxy** [comment]
Type the shift to switch to English mode.
