### ISSUE TITLE
windows10 x86 cargo run error

### ISSUE THREAD

**Issue by SamGenTLEManKaka** [rustdesk/rustdesk#4180]
### Bug Description

cargo run --target i686-pc-windows-msvc
I received an error message:
  C:\Users\sunny\.cargo\git\checkouts\magnum-opus-4bb999f3bcbf6ab0\79be072\opus_ffi.h:1:10: fatal error: 'opus/opus_multistream.h' file not found
  C:\Users\sunny\.cargo\git\checkouts\magnum-opus-4bb999f3bcbf6ab0\79be072\opus_ffi.h:1:10: fatal error: 'opus/opus_multistream.h' file not found, err: true
E:\rustdesk\rustdesk-1.1.9\rustdesk\libs\scrap\vpx_ffi.h:1:10: fatal error: 'vpx/vp8.h' file not found

### How to Reproduce

cargo run --target i686-pc-windows-msvc

### Expected Behavior

It should be build success

### Operating system(s) on local side and remote side

windows10 x86

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

Periodictasks

failed to run custom build command for `scrap v0.5.0

error: failed to run custom build command for `magnum-opus v0.4.0 (https://github.com/rustdesk/magnum-opus#79be072c)`

Caused by:
  process didn't exit successfully: `E:\rustdesk\rustdesk-1.1.9\rustdesk\target\debug\build\magnum-opus-eaf7d5f2ac93bc41\build-script-build` (exit code: 101)
  --- stdout
  cargo:info=x86-windows-static
  cargo:rustc-link-lib=static=opus
  cargo:rustc-link-search=E:\rustdesk\vcpkg_211201\vcpkg\installed\x86-windows-static\lib
  cargo:include=E:\rustdesk\vcpkg_211201\vcpkg\installed\x86-windows-static\include
  rerun-if-changed=C:\Users\sunny\.cargo\git\checkouts\magnum-opus-4bb999f3bcbf6ab0\79be072\opus_ffi.h
  rerun-if-changed=E:\rustdesk\vcpkg_211201\vcpkg\installed\x86-windows-static\include

  --- stderr
  C:\Users\sunny\.cargo\git\checkouts\magnum-opus-4bb999f3bcbf6ab0\79be072\opus_ffi.h:1:10: fatal error: 'opus/opus_multistream.h' file not found
  C:\Users\sunny\.cargo\git\checkouts\magnum-opus-4bb999f3bcbf6ab0\79be072\opus_ffi.h:1:10: fatal error: 'opus/opus_multistream.h' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', C:\Users\sunny\.cargo\git\checkouts\magnum-opus-4bb999f3bcbf6ab0\79be072\build.rs:128:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `scrap v0.5.0 (E:\rustdesk\rustdesk-1.1.9\rustdesk\libs\scrap)`

Caused by:
  process didn't exit successfully: `E:\rustdesk\rustdesk-1.1.9\rustdesk\target\debug\build\scrap-7ce8680a0d7001d4\build-script-build` (exit code: 101)
  --- stdout
  cargo:info=x86-windows-static
  cargo:rustc-link-lib=static=yuv
  cargo:rustc-link-search=E:\rustdesk\vcpkg_211201\vcpkg\installed\x86-windows-static\lib
  cargo:include=E:\rustdesk\vcpkg_211201\vcpkg\installed\x86-windows-static\include
  cargo:info=x86-windows-static
  cargo:rustc-link-lib=static=vpx
  cargo:rustc-link-search=E:\rustdesk\vcpkg_211201\vcpkg\installed\x86-windows-static\lib
  cargo:include=E:\rustdesk\vcpkg_211201\vcpkg\installed\x86-windows-static\include
  rerun-if-changed=E:\rustdesk\rustdesk-1.1.9\rustdesk\libs\scrap\vpx_ffi.h
  rerun-if-changed=E:\rustdesk\vcpkg_211201\vcpkg\installed\x86-windows-static\include

  --- stderr
  E:\rustdesk\rustdesk-1.1.9\rustdesk\libs\scrap\vpx_ffi.h:1:10: fatal error: 'vpx/vp8.h' file not found
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ClangDiagnostic("E:\\rustdesk\\rustdesk-1.1.9\\rustdesk\\libs\\scrap\\vpx_ffi.h:1:10: fatal error: 'vpx/vp8.h' file not found\n")', libs\scrap\build.rs:134:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Additional Context

Periodictasks

failed to run custom build command for `scrap v0.5.0

error: failed to run custom build command for `magnum-opus v0.4.0 (https://github.com/rustdesk/magnum-opus#79be072c)`

Caused by:
  process didn't exit successfully: `E:\rustdesk\rustdesk-1.1.9\rustdesk\target\debug\build\magnum-opus-eaf7d5f2ac93bc41\build-script-build` (exit code: 101)
  --- stdout
  cargo:info=x86-windows-static
  cargo:rustc-link-lib=static=opus
  cargo:rustc-link-search=E:\rustdesk\vcpkg_211201\vcpkg\installed\x86-windows-static\lib
  cargo:include=E:\rustdesk\vcpkg_211201\vcpkg\installed\x86-windows-static\include
  rerun-if-changed=C:\Users\sunny\.cargo\git\checkouts\magnum-opus-4bb999f3bcbf6ab0\79be072\opus_ffi.h
  rerun-if-changed=E:\rustdesk\vcpkg_211201\vcpkg\installed\x86-windows-static\include

  --- stderr
  C:\Users\sunny\.cargo\git\checkouts\magnum-opus-4bb999f3bcbf6ab0\79be072\opus_ffi.h:1:10: fatal error: 'opus/opus_multistream.h' file not found
  C:\Users\sunny\.cargo\git\checkouts\magnum-opus-4bb999f3bcbf6ab0\79be072\opus_ffi.h:1:10: fatal error: 'opus/opus_multistream.h' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', C:\Users\sunny\.cargo\git\checkouts\magnum-opus-4bb999f3bcbf6ab0\79be072\build.rs:128:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `scrap v0.5.0 (E:\rustdesk\rustdesk-1.1.9\rustdesk\libs\scrap)`

Caused by:
  process didn't exit successfully: `E:\rustdesk\rustdesk-1.1.9\rustdesk\target\debug\build\scrap-7ce8680a0d7001d4\build-script-build` (exit code: 101)
  --- stdout
  cargo:info=x86-windows-static
  cargo:rustc-link-lib=static=yuv
  cargo:rustc-link-search=E:\rustdesk\vcpkg_211201\vcpkg\installed\x86-windows-static\lib
  cargo:include=E:\rustdesk\vcpkg_211201\vcpkg\installed\x86-windows-static\include
  cargo:info=x86-windows-static
  cargo:rustc-link-lib=static=vpx
  cargo:rustc-link-search=E:\rustdesk\vcpkg_211201\vcpkg\installed\x86-windows-static\lib
  cargo:include=E:\rustdesk\vcpkg_211201\vcpkg\installed\x86-windows-static\include
  rerun-if-changed=E:\rustdesk\rustdesk-1.1.9\rustdesk\libs\scrap\vpx_ffi.h
  rerun-if-changed=E:\rustdesk\vcpkg_211201\vcpkg\installed\x86-windows-static\include

  --- stderr
  E:\rustdesk\rustdesk-1.1.9\rustdesk\libs\scrap\vpx_ffi.h:1:10: fatal error: 'vpx/vp8.h' file not found
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ClangDiagnostic("E:\\rustdesk\\rustdesk-1.1.9\\rustdesk\\libs\\scrap\\vpx_ffi.h:1:10: fatal error: 'vpx/vp8.h' file not found\n")', libs\scrap\build.rs:134:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by rustdesk** [comment]
#763
