### ISSUE TITLE
There is a problem with the progress of the file transfer

### ISSUE THREAD

**Issue by wu1994a** [rustdesk/rustdesk#4183]
### Bug Description

When I hit the send button, the progress on the right side shows 100%, but it's actually still in transit.

### How to Reproduce

Send file

### Expected Behavior

Display correct progress

### Operating system(s) on local side and remote side

win10 -> ubuntu

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

![image](https://user-images.githubusercontent.com/23646424/234157967-efcf2259-095d-474c-99d3-fc2f857af837.png)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/tag/nightly please
