### ISSUE TITLE
During call there is echo coming from client.

### ISSUE THREAD

**Issue by GOR4X** [rustdesk/rustdesk#4190]
### Bug Description

When I try to use Element app for communication call with enduser box while connected via rustdesk, I can hear myself talking, coming from audio output on enduser box with slight delay.

I have also tried to use "options - audio input - mute" on both my and enduser machine but it did not mute the sound on device, and tried all kind of combination there.

### How to Reproduce

When I try to use Element app for communication call with enduser box while connected via rustdesk, I can hear myself talking, coming from audio output on enduser box with slight delay.

### Expected Behavior

Do not hear myself while in call with enduser. 

I guess simple Mute all sound from enduser device as in Teamviewer app would resolve the issue.

### Operating system(s) on local side and remote side

Windows 11 - Windows 10

### RustDesk Version(s) on local side and remote side

1.1.9.0 - 1.1.9.0

### Screenshots

mute enabled

**Comment by rustdesk** [comment]
> I have also tried to use "options - audio input - mute" on both my and enduser machine but it did not mute the sound on device, and tried all kind of combination there.

@21pages please confirm if mute work in nightly build.

**Comment by rustdesk** [comment]
@GOR4X local side "option: audio-input mute" has nothing to do with this case, the option on controlled (remote) side should work, but you need to reconnect.

**Comment by GOR4X** [comment]
I might have missed this option, many thanks works like charm.
