### ISSUE TITLE
Rustdesk 1.1.10-1 (Android) - Italian language issue

### ISSUE THREAD

**Issue by bovirus** [rustdesk/rustdesk#4192]
### Bug Description

@rustdesk 

I found some issues in Italian translation.

I checked that some strings in Android app seems are not present in .rs file.
Then I didn't understand where I have to check English and Italian language for the Android app

### How to Reproduce

@rustdesk 

I found some issues in Italian translation.

I checked that soem strings in Android app seems are not rpesent in .rs file.
Then I didn't udnerstand where I ahve to check english and italian language for the app

### Expected Behavior

Please check screenshots:
Please create language file for Android system

### Operating system(s) on local side and remote side

Android 11

### RustDesk Version(s) on local side and remote side

1..1.10-1

### Screenshots

![Screenshot_20230425_150151](https://user-images.githubusercontent.com/1262554/234300632-979b981c-e823-40e0-ac68-a5f09c3de1c7.jpg)

![Screenshot_20230425_150132](https://user-images.githubusercontent.com/1262554/234300675-ad37ee80-2468-44b4-9010-ad712c4ee53c.jpg)

![Screenshot_20230425_150234](https://user-images.githubusercontent.com/1262554/234300696-c6da694c-c364-4d6e-9c29-89e51ee07861.jpg)

**Comment by rustdesk** [comment]
I think these have been fixed in master.

**Comment by dinger1986** [comment]
apk is available on GitHub

**Comment by Apashh** [comment]
But on PlayStore and AppStore ?
