### ISSUE TITLE
Cannot unlock security settings in nightly on wayland

### ISSUE THREAD

**Issue by Yaikava** [rustdesk/rustdesk#4195]
### Bug Description

Clicking the "unlock security settings" button does nothing.
It prompts me for superuser password, but nothing after.

### How to Reproduce

Click the "unlock security settings" button. Enter the password.

### Expected Behavior

I will be able to change the security settings.

### Operating system(s) on local side and remote side

Android --> Nobara 37

### RustDesk Version(s) on local side and remote side

does not matter --> rustdesk-1.2.0-0.x86_64-fedora28-centos8.rpm

### Screenshots

![image](https://user-images.githubusercontent.com/83710104/234355200-dd79eac1-8827-4ead-b74d-348fed7fd91e.png)

### Additional Context

Is this intended, because it is nightly version?

**Comment by rustdesk** [comment]
#2756

**Comment by Yaikava** [comment]
btw turns out it works when I run rustdesk from terminal.
