### ISSUE TITLE
Can not show windows UAC modal

### ISSUE THREAD

**Issue by xialvjun** [rustdesk/rustdesk#42]
when you uninstall an application which was install in `C:\Program Files` , the windows will open a modal to notify you for the `administrator` permission, but `rustdesk` can not show that modal.

**Comment by rustdesk** [comment]
![image](https://user-images.githubusercontent.com/71636191/119084683-d2a49800-ba34-11eb-81df-e58ca7ece4e0.png)
Maybe windows update can help you.

**Comment by dpschen** [comment]
I have the same issue.

**Comment by rustdesk** [comment]
You need install RustDesk

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/51

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/108
