### ISSUE TITLE
RustDesk 1.2.0 (Android) - GUI issues

### ISSUE THREAD

**Issue by bovirus** [rustdesk/rustdesk#4201]
### Bug Description

Hi.

Please check screenshot

**Language**
Don't show current Language settings - Just "Language"

**Theme**
Don't show current setting in right way

When you select "System" show it in Setting panel as  "Light theme"
When you select "Dark" show it in Setting panel as "Light theme"
When you select "Light" show it in Setting panel as "Dark theme"

If I select "System" it show in Settings panel as "System theme" (or Theme: System")
If I select "Light" it show in Settings panel as "Light theme"(or Theme: Light")
If I select "Dark" it show in Settings panel as "Dark Theme"(or Theme: Dark")

I propose to change the "Language" and "Theme" string/values in two part

Language: xxxx
Theme: xxxx

Where xxx is the current value.

Add to version info also build date.

### How to Reproduce

Use latest app build

### Expected Behavior

As I explained

### Operating system(s) on local side and remote side

Android 11

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

![Screenshot_20230426_105506](https://user-images.githubusercontent.com/1262554/234528515-24b46874-0d0e-4b79-844c-2a95d4afe25a.jpg)

![Screenshot_20230426_105519](https://user-images.githubusercontent.com/1262554/234528523-4eca078e-c122-4edb-91af-5b97b2e57d48.jpg)

![Screenshot_20230426_105531](https://user-images.githubusercontent.com/1262554/234528525-c9e0cd0d-aa8a-4eb3-ad1c-2158b8fd36c5.jpg)

**Comment by rustdesk** [comment]
Thanks, mobile settings page is going to be rewritten to share the same code with desktop, and current desktop settings code is also very verbose, must be refactored.
@21pages

**Comment by rustdesk** [comment]
Close this, since it will be fixed togehter with refactory.
