### ISSUE TITLE
App crashes on Tv box

### ISSUE THREAD

**Issue by FelipeGCaetano** [rustdesk/rustdesk#4204]
### Bug Description

Every time I try to connect from my phone to my tvbox(android), the apps on android crashes, no explanation, just crash, qual should I do?

### How to Reproduce

Download RustDesk in a tvbox and try to access

### Expected Behavior

Connected successfully

### Operating system(s) on local side and remote side

IOS -> Android

### RustDesk Version(s) on local side and remote side

1.1.10 -> 1.1.10

### Screenshots

![rustdesk](https://user-images.githubusercontent.com/107513409/234581345-bc5c5df9-b387-44b6-ac48-91e7bef823c9.jpg)

https://user-images.githubusercontent.com/107513409/234581380-29feb717-78f6-4f24-972e-0037d4fded76.mp4

### Additional Context

Anyone can help me?

**Comment by rustdesk** [comment]
#497
