### ISSUE TITLE
Installation failed on Ubuntu 22.04 fresh machine

### ISSUE THREAD

**Issue by ksingh7** [rustdesk/rustdesk#4207]
### Bug Description

@rustdesk  i just tried installing rustdesk.deb on a freshly created Ubuntu Desktop latest release, and encountered this . It seems like one has to install all dependencies before installing rustdesk.deb file ? any thoughts ? 
<img width="709" alt="image" src="https://user-images.githubusercontent.com/9701902/234686399-7543394c-1cd0-48a1-a4d6-88b47cc459c0.png">

### How to Reproduce

Launch a fresh ubuntu 22.04 > Download rustdesk.deb > install it using `apt install -fy ./rustdesk.dev`

### Expected Behavior

Rustdesk is supposed to be a single binary that should have all dependencies baked into it. If dependencies needs to be installed manually prior to installation , it needs to be documented.

### Operating system(s) on local side and remote side

Ubuntu 22.04

### RustDesk Version(s) on local side and remote side

Latest

### Screenshots

<img width="709" alt="image" src="https://user-images.githubusercontent.com/9701902/234686399-7543394c-1cd0-48a1-a4d6-88b47cc459c0.png">

**Comment by ksingh7** [comment]
Just for the community, to make it work on Ubuntu, run these

```
# First Download the deb file
sudo dpkg -i file_name.deb

# You might end up getting errors above, so first install dependencies

sudo apt install -f 
#once dependencies are installed , retry installation

sudo dpkg -i file_name.deb

which rustdesk

# Invoke rustdesk
rustdesk 

```

**Comment by TanishqSharma2022** [comment]
I get this error


dpkg: error processing archive rustdesk-1.4.0-aarch64.deb (--install):
 package architecture (arm64) does not match system (amd64)
Errors were encountered while processing:
 rustdesk-1.4.0-aarch64.deb
