### ISSUE TITLE
Blank screen when laptop lid is closed 

### ISSUE THREAD

**Issue by rginus** [rustdesk/rustdesk#4211]
### Bug Description

When the lid is closed of the Windows 10 laptop using version 1.1.9/1.2.0 the detail part of PowerPoint is blank.

<img width="723" alt="image" src="https://user-images.githubusercontent.com/8409270/234836871-00f3d328-4cbe-472b-bb58-34796e123340.png">

### How to Reproduce

Connect to remote computer
Open PowerPoint

### Expected Behavior

See image:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/8409270/234836788-0ec5dfc0-b1be-4547-9330-8a01f25387c6.png">

### Operating system(s) on local side and remote side

Windows 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

See above

**Comment by rustdesk** [comment]
out of our control.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4296
