### ISSUE TITLE
installation failed Child process exited with code 100 

### ISSUE THREAD

**Issue by KelvinJPS** [rustdesk/rustdesk#4212]
### Bug Description

When I try to install the deb file in pop os. which it uses edgy happens the error

### How to Reproduce

download the deb file
try to install it

### Expected Behavior

open the app?

### Operating system(s) on local side and remote side

pop os 22.04

### RustDesk Version(s) on local side and remote side

1.1.19

### Screenshots

![image](https://user-images.githubusercontent.com/75276742/234936175-c8795276-6b39-4f7d-8e15-13597bb59db6.png)

**Comment by rustdesk** [comment]
#4083
