### ISSUE TITLE
SSL Error with Beta Web View

### ISSUE THREAD

**Issue by Jax-Hax** [rustdesk/rustdesk#4213]
### Bug Description

When trying to visit web.rustdesk.com in firefox, I get the following error:
Did Not Connect: Potential Security Issue
Firefox detected a potential security threat and did not continue to web.rustdesk.com because this website requires a secure connection.
Error code: SSL_ERROR_BAD_CERT_DOMAIN

### How to Reproduce

Visit the link in Firefox with default security settings

### Expected Behavior

It should take me to the website with no errors

### Operating system(s) on local side and remote side

Linux Mint

### RustDesk Version(s) on local side and remote side

NA

### Screenshots

![image](https://user-images.githubusercontent.com/94689952/234985118-5155884e-57c6-4294-85e8-2b1f36534037.png)

**Comment by rustdesk** [comment]
#856
