### ISSUE TITLE
DNS query flooding for domain `curl`.

### ISSUE THREAD

**Issue by cubercsl** [rustdesk/rustdesk#4218]
### Bug Description

DNS query flooding for domain `curl`.

### How to Reproduce

Doing nothing after setting up the ID Server

### Expected Behavior

No process should be trying to resolve a meaningless domain like `curl` anyway.

But I actually found that every once in a while a process named curl would initiate a resolution for both the `curl` and my id server domain.

### Operating system(s) on local side and remote side

linux

### RustDesk Version(s) on local side and remote side

nightly

### Screenshots

![image](https://user-images.githubusercontent.com/22931465/235050280-d7ed8622-f0dc-48db-bfcf-5a37f01b38d3.png)

### Additional Context

https://github.com/rustdesk/rustdesk/blob/8a9af3a75585fd555fce5b60600f19ee2447a3e4/src/common.rs#L848-L875

https://docs.rs/async-process/latest/async_process/

So, I think `curl curl` happens here as line 851 has an extra `curl`.

or Why not use `reqwest` like other operating systems?

**Comment by mochaaP** [comment]
Why wontfix? This is clearly a problem.

**Comment by hack3ric** [comment]
I would like to know the motivation of using command-line `curl` on Linux. If reusing system component is desirable, using `libcurl` bindings could be a better solution. Otherwise keep the behaviour consistent across platform is much more important in my opinion.

After all, this is undoubtedly a mistake. It should be fixed instead of skimming through and say "I won't fix such a small bug like this".

**Comment by rustdesk** [comment]
Using curl is for removing dependency to libssl, which make one deb hard to work on all different Ubuntu versions.

**Comment by rapiz1** [comment]
> So, I think curl curl happens here as line 851 has an extra curl.

AFAIK, simply removing L851 would fix this bug.

See also the example from async_process, as mentioned in the issue.
```
let out = Command::new("echo").arg("hello").arg("world").output().await?;
```
The program name does not need to be included in `arg`

**Comment by XieJiSS** [comment]
I suspect that the whole call to curl can be removed. Clearly currently it is sending request to http://curl instead of the correct url, but (it seems like) this is not affecting any rustdesk's function. So... is this request unnecessary / redundant at all?

**Comment by rustdesk** [comment]
Yes, you are right, let me remove "curl" arg.

**Comment by rustdesk** [comment]
A PR is welcome with better test.

**Comment by rustdesk** [comment]
curl is removed https://github.com/rustdesk/rustdesk/commit/e3ee95737010a86a3704932d1613f8747ae3f015
