### ISSUE TITLE
Panel is hidden during rustdesk connection

### ISSUE THREAD

**Issue by MarcelRobitaille** [rustdesk/rustdesk#422]
**Describe the bug you encountered:**

When I open a connection to another computer, my panel is hidden. The space below the rustdesk window is still there, but the panel disappears.

https://user-images.githubusercontent.com/8503756/156626546-aeb8b73f-2811-4673-84bc-bb117e16f2bc.mp4

**What did you expect to happen instead?**

The panel is still visible

**How did you install `RustDesk`?**

`rustdesk-bin` from the AUR.

**RustDesk version and environment**

RustDesk version: 1.1.8

Panel is tint2
DE is openbox
I am using X11 not wayland

**Comment by rustdesk** [comment]
try out nightly build.
