### ISSUE TITLE
Metal Acceleration for macOS

### ISSUE THREAD

**Issue by td512** [rustdesk/rustdesk#4225]
### Description

I'd love to see more codecs/hardware acceleration on macOS.

### Impact

Any user that has a Mac will notice the performance gains. VP9 is great, but it is very slow compared to Metal accelerated H264 and H265.

**Comment by rustdesk** [comment]
we have our plan, you do not need to create a specific issue for this.

**Comment by rustdesk** [comment]
Except you wanna submit a PR for this to accelerate our dev.
