### ISSUE TITLE
Can't connect to devices outside my network

### ISSUE THREAD

**Issue by luiscaroca99** [rustdesk/rustdesk#4229]
### Bug Description

Hello,

I'm having a problem. A few days ago, I installed my RustDesk Server in my Allways Free Oracle Cloud account.
I installed it in a Instance with Ubuntu 22, 1CPU, 1GB Memory and 0.5Gbps Network Bandwith (Shape VM.Standard.E2.1.Micro), with help of this video: https://www.youtube.com/watch?v=5WmoLqPkn98 and this website: https://syncbricks.com/rustdesk-server-setup-a-comprehensive-guide
My Instance public IP address is redirecting in my No-IP account in a hostname created by me.
Then I installed RustDesk with the server configurations (ID, Relay and API server, and the key) in my 2 computers, my 2 laptops and my phone (everything in my house).
The problem come next, when I did the same installation on my uncle's computer in his house, and when I came back to my house, I couldn't connect to his laptop. My RustDesk never says that the laptop is offline, it just stays stuck in "connecting" and never asks for the password.
I checked a lot. The servers configuration is the same in every RustDesk client that I've installed, but I only can access the computers in my home network.
The last test I made yesterday: I took my laptop (who works right with RustDesk in my house) to my uncle's house, then I came back to my house and tried to connect to my laptop. Same problem: "connecting..." and never asks for password but never says it's offline.
Maybe it's my home's router firewall blocking the connection?
I work in IT for some years, but I'm new in this type of installations and configurations. I used to work with AnyDesk, but I'm now a fan of RustDesk, that's why I wanted to have my RustDesk Server.
Thanks!

### How to Reproduce

Install RustDesk Server in an Allways Free Oracle Cloud instance and redirect to a hostname in No-IP.
Install and configure some RustDesk clients and try to connect outside of the network.

### Expected Behavior

I expected to get some help resolving this problem.
Maybe it's just some basic feature, but for now I don't have any ideais.
Thanks!

### Operating system(s) on local side and remote side

Windows 11 -> Windows 11 (I tried with Android 13 too)

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9 (I tried Nightly version but it have the same problem)

### Screenshots

Oracle Cloud Firewall:

![1](https://user-images.githubusercontent.com/83612693/235196752-ab131239-e72a-403a-8e90-2fbd157a0816.png)

Ubuntu firewall:

![2](https://user-images.githubusercontent.com/83612693/235196815-94b4b53e-226f-4783-8fb9-32b2561460ca.png)

RustDesk Client status:

![3](https://user-images.githubusercontent.com/83612693/235196903-207a3d96-f23d-4f83-994a-9b9648b573cd.png)

Problem:

![4](https://user-images.githubusercontent.com/83612693/235196983-22688e2f-4dce-43a2-b6f5-8bab3d2774f3.png)

**Comment by rustdesk** [comment]
#763
