### ISSUE TITLE
Double-clicking the tray icon repeatedly will report an error.

### ISSUE THREAD

**Issue by YamatoRyou** [rustdesk/rustdesk#4235]
### Bug Description

On the premise that the main RustDesk window is displayed on the desktop, double-clicking the tray icon repeatedly will cause an error.

### How to Reproduce

n/a

### Expected Behavior

n/a

### Operating system(s) on local side and remote side

x64 Windows 7

### RustDesk Version(s) on local side and remote side

1.2.0 (202304240024)

### Screenshots

Another one appears if you click Cancel.
![{FD984EC7-FC2E-1420-2E22-E105E7025895}](https://user-images.githubusercontent.com/48104960/235331468-39a27ecf-41be-4970-9053-657a3a77663f.png)
![{2E4139AB-7236-51B9-8A69-87EBB3F31BD8}](https://user-images.githubusercontent.com/48104960/235331467-3097e89d-73c0-4c0c-ab00-46f84083d1d9.png)

### Additional Context

Not installed to the system, boots in portable mode.
```
RustDesk.exe --server
RustDesk.exe --tray
```

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3117#issuecomment-1422242788
