### ISSUE TITLE
The ubuntu 22 LTS system uses the latest version 1.2.0 and cannot transfer files to win11

### ISSUE THREAD

**Issue by ApacheAlpha** [rustdesk/rustdesk#4241]
### Bug Description

One of my computers is an ubuntu 22 LTS system, and the other is a win11 system. I use the latest version 1.2.0, the liunx system computer can be linked to the win11 system computer, but the file cannot be transferred, and it always shows that it is connecting.

Why is version 1.1.9 not used, because version 1.1.9 controls the win11 system on the ubuntu 22 LTS system, and the keyboard cannot perform text input on win11.

### How to Reproduce

Use a computer with ubuntu22LTS system installed and a win11 system computer. Install version 1.2.0 separately, and then perform file transfer.

### Expected Behavior

I want a quick connection to the remote side，Instead of showing always connected

### Operating system(s) on local side and remote side

ubuntu22 LTS--->windows11

### RustDesk Version(s) on local side and remote side

1.2.0-->1.2.0

### Screenshots

![image](https://user-images.githubusercontent.com/53244971/235349095-f9e22e6d-68e6-45f8-9865-f4cc4db5b2ee.png)

![image](https://user-images.githubusercontent.com/53244971/235349311-fff76e7b-6657-4a16-9d32-623c7e04b58e.png)
![image](https://user-images.githubusercontent.com/53244971/235349260-11745140-6de0-49ba-8f09-d691b96aba64.png)

**Comment by rustdesk** [comment]
#4230
