### ISSUE TITLE
"error: externally-managed-environment" with "dpkg -i rustdesk-1.1.9.deb" on Ubuntu 23.04

### ISSUE THREAD

**Issue by mirogl** [rustdesk/rustdesk#4243]
### Bug Description

Wehen I try to install rustdesk-1.1.9.deb on Ubuntu 23.04 with "dpkg -i rustdesk-1.1.9.deb" I get the following error:

```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
```

I found an article, how this could be fixed manually, but I think this should be fixed in the source "https://www.reddit.com/r/rustdesk/comments/12eyx3e/error_externallymanagedenvironment_debian/"

### How to Reproduce

1. Install Ubuntu 23.04
2. Download latest Rustdesk package 
3. Install package with "dpkg -i rustdesk-1.1.9.deb"

### Expected Behavior

Installation without error

### Operating system(s) on local side and remote side

Ubuntu 23.04

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![grafik](https://user-images.githubusercontent.com/46027543/235354849-c1cb207a-0106-4151-bd68-696cbe56433d.png)

**Comment by rustdesk** [comment]
Nightly build please.

**Comment by mirogl** [comment]
Thanks - Nightly Release fixed it !
