### ISSUE TITLE
rust desk bug report in manjaro 

### ISSUE THREAD

**Issue by majdidraouil** [rustdesk/rustdesk#4246]
### Bug Description

problem concocting from  win 10 to  @@Manjaro  is no dislpay [showing](url) after entering password and ID

### How to Reproduce

fixed soon as posible 

### Expected Behavior

just not display 

### Operating system(s) on local side and remote side

Manjaro

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![Screenshot from 2023-04-30 23-38-43](https://user-images.githubusercontent.com/45218146/235379200-883cfe44-7f7f-475b-a594-893432daa1d4.png)

### Additional Context

pls help

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/wiki/Headless-Linux-Support
