### ISSUE TITLE
Security: Connection without password

### ISSUE THREAD

**Issue by SkyBeam** [rustdesk/rustdesk#4250]
### Bug Description

I noticed a weird and unexpected thing: After connecting to a remote desktop using one of the previously used configurations I noticed it's asking me for the password but already during this phase the remote screen (black) showing mouse cursor movements from the remote system while sitting at the "Password Required" prompt (not being authenticated yet at all.

This is scaring me that potentially anyone knowing a valid ID can at least connect and see mouse movements without any authentication.

### How to Reproduce

- Connect to a remote system using ID and password (do not save paassword)
- Enable show remote cursor
- Disconnect
- Then re-connect using the same ID (or use recent connections shortcut)
- Leave the connection window open, do not enter a password

### Expected Behavior

Need to enter a password before being able to see any data from the remote system.
Instead you can see mouse/cursor movements from the remote system without even entering a password at all.

### Operating system(s) on local side and remote side

Windows 10 on host, Windows 11 client

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![image](https://user-images.githubusercontent.com/1265512/235443416-5c4c1b0f-f538-4056-af18-3ba732b0c309.png)

**Comment by rustdesk** [comment]
try out nightly build。please
