### ISSUE TITLE
Cannot start rustdesk as service (ServiceProfiles Folder Broken)

### ISSUE THREAD

**Issue by zhaodice** [rustdesk/rustdesk#4252]
### Bug Description

When I install rustdesk as service, the mouse will blink , process exit and start, show the wait ring and hide, then show and hide again.
I have to uninstall the software .(remote side)

PS: this issue doesn't exist at past days, only today , and it doesn't resolve if I uninstall and reinstall it.

```
[2023-05-02 12:48:07.704624 +08:00] INFO [src\server.rs:435] server not started (will try to start): 系统找不到指定的文件。 (os error 2)
```

### How to Reproduce

Install as Service.

### Expected Behavior

Work fine.

### Operating system(s) on local side and remote side

Ubuntu 22.04, Windows 11

### RustDesk Version(s) on local side and remote side

1.2.0,1.2.0(latest nightly 2023-05-02 00:29)

### Screenshots

![Screenshot_20230502_123022](https://user-images.githubusercontent.com/63996691/235580480-be6a3d0a-78d3-4a02-9451-2abfc59e959a.png)
![Screenshot_20230502_124151](https://user-images.githubusercontent.com/63996691/235580823-c6e46cde-aaae-4d70-aa0d-43c91cdefcbc.png)

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
PR is welcome
