### ISSUE TITLE
Multiple public and private key pairs

### ISSUE THREAD

**Issue by karabelnikov** [rustdesk/rustdesk#4254]
### Description

Hello!

Great project! Thanks to the authors for their work. Please tell me if the server works with several or more pairs of private keys?

The bottom line is that I have several organizations that I serve and support. I have raised my server and I want to make my own public and private key pair for each organization. If I terminate cooperation with the organization, I delete the private and public key pair from the server so that the organization cannot use the client through my server.

I think this is a very important function for those who are engaged in technical support of organizations and do it through their resources. Do you have any ideas how to organize it?
Thanks.

### Impact

Technical support specialists

**Comment by rustdesk** [comment]
#3022
#1873 
#763

**Comment by karabelnikov** [comment]
I have not found a definitive answer to my question. I have read the discussions on your links. Is this a future implementation? I understand there is no such possibility now?
