### ISSUE TITLE
Allow standard ports to be used, ie ports 80 and 443

### ISSUE THREAD

**Issue by deajan** [rustdesk/rustdesk#4260]
### Description

Since rustdesk works with specific ports 21115-21119, a great number of public wifi networks as well as some corporate environment will not allow rustdesk connections.

Most networks always allow ports 80, 110, 143 and 443 but filter anything else.
It would be great if rustdesk could make usage of those default ports, 80 and 443 being the best, for both self hosted or public hbbs/hbbr servers.

As ideal scenario, rustdesk would try to connect to port 21116, and fallback to 443 then to 80 if not successful.
Teamviewer for example uses this exact connection schema, with a proprietary port and then some fallback ports, see https://community.teamviewer.com/English/kb/articles/4139-ports-utilises-par-teamviewer

### Impact

Litterally anybody that ever used a filtered network like a wifi hotspot in a café in Europe for example will enjoy this feature ;-D

### Additional Context

I've played with NATs and port reconfiguration without success already, see https://github.com/rustdesk/rustdesk/discussions/984#discussioncomment-5785676

It doesn't seem that rustdesk can be configured to use those ports properly as of today.

**Comment by deajan** [comment]
Sorry if I am asking a question that might have been asked multiple times already.
I've tried to find the info before in the issues and discussions.

I'm not arguing the `wontfix` label, but would you mind giving an explanation ?
I know multiplexing connections isn't easy, especially with UDP punching, but I am puzzled why you would keep non standard ports ?

Thank you.

**Comment by foorschtbar** [comment]
Same question here. Without support for 80/443 it's useless for me.
