### ISSUE TITLE
 The cursor you see does not match the actual cursor position.

### ISSUE THREAD

**Issue by zhangbo8418** [rustdesk/rustdesk#4261]
### Bug Description

The cursor you see does not match the actual cursor position.

### How to Reproduce

Move the mouse quickly to appear randomly.

### Expected Behavior

The cursor position is synchronized.

### Operating system(s) on local side and remote side

MacOS Ventura1 3.2.1

### RustDesk Version(s) on local side and remote side

1.20

### Screenshots

see the cursor
![see-the-cursor](https://user-images.githubusercontent.com/46797568/235817630-c5c8dfbf-dc91-483f-8670-aa605e7ed04f.png)

actual cursor
![actual-cursor](https://user-images.githubusercontent.com/46797568/235817686-ea2b4447-4120-4fc9-8232-c5c26db7dae6.png)

**Comment by rustdesk** [comment]
Let me know again if you see it on Win 10 / 11.

**Comment by fufesou** [comment]
@zhangbo8418 Thanks for you feedback.

It should be fixed by #4269.

But this issue is not the same to #3068.

**Comment by rustdesk** [comment]
@zhangbo8418 updated, please help test

**Comment by zhangbo8418** [comment]
> @zhangbo8418 nightly build updated, please help test, our old pal.

It seems to be ok.

**Comment by zhangbo8418** [comment]
> @zhangbo8418 nightly build updated, please help test, our old pal.

The mouse control mode for controlling PC with an Android phone has failed.

**Comment by fufesou** [comment]
@zhangbo8418 Hi, Android -> PC failed, which OS is on the PC?

**Comment by zhangbo8418** [comment]
> @zhangbo8418 Hi, Android -> PC failed, which OS is on the PC?

Android -> Android
Android -> Windows
Android -> MacOS

**Comment by rustdesk** [comment]
Wondering if this https://github.com/rustdesk/rustdesk/pull/4265 related, today's PR

**Comment by fufesou** [comment]
> Wondering if this #4265 related, today's PR

Yes, the failure is caused by this PR.
I thinks we can revert it first.

**Comment by rustdesk** [comment]
let me revert it

**Comment by rustdesk** [comment]
@zhangbo8418 nightly build is updated

**Comment by JSP6668** [comment]
I have the exact sam behaviour in the latest release 1.4.0.0 on Debian Wayland

**Comment by 4f1sh3r** [comment]
same here on Fedora 42 Wayland, tested with 1.4.0 and 1.4.1

**Comment by rustdesk** [comment]
@AleXburnA you can create a new issue for this, please state more details, e.g.  is it primary display? resoluiton? scale factor? kde / gnome or others?
This issue is not for linux wayland (wayland is totally different story).

**Comment by 4f1sh3r** [comment]
> [@AleXburnA](https://github.com/AleXburnA) you can create a new issue for this, please state more details, e.g. is it primary display? resoluiton? scale factor? kde / gnome or others? This issue is not for linux wayland (wayland is totally different story).

will do, thanks!
