### ISSUE TITLE
.deb install fails with "Sorry, user root is not allowed to execute '/usr/bin/pip3 install pynput' as root"

### ISSUE THREAD

**Issue by schweini** [rustdesk/rustdesk#4266]
### Bug Description

When trying to install the .deb package with "dpkg -i /home/caja/Downloads/rustdesk-1.1.9.deb" (either directly as root, or via sudo), the install fails with 

 "Sorry, user root is not allowed to execute '/usr/bin/pip3 install pynput' as root"
 
 This is on Linux Mint Debian Edition 5, which is basically Debian 11 Bullseye

### How to Reproduce

 dpkg -i /home/caja/Downloads/rustdesk-1.1.9.deb

### Expected Behavior

I would like rustdesk to install successfully

### Operating system(s) on local side and remote side

LMDE 5 (Debian 11)

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

N/A

**Comment by schweini** [comment]
I ran "pip install pynput" manually and it succesfully installed that module - but I still can't install the .deb package.

**Comment by schweini** [comment]
I had to uncommment the line

root    ALL=(ALL:ALL) ALL

in the sudoers file via visudo, and now it installs correctly.

**Comment by rustdesk** [comment]
This dep is removed in nightly build.
