### ISSUE TITLE
Sync clipboard when connection is established

### ISSUE THREAD

**Issue by fufesou** [rustdesk/rustdesk#427]
mstsc can copy contents in clipboard before connection is established, which is a nice experience.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/d313fa92e192faacb64913abcccde1dd41a3de17

**Comment by fufesou** [comment]
Not only string contents, but also file conents.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3952#issuecomment-1501146555
