### ISSUE TITLE
Keyboard not working (macOS Ventura 13.3.1)

### ISSUE THREAD

**Issue by anon4747** [rustdesk/rustdesk#4272]
### Bug Description

Keyboard not working.

### How to Reproduce

Enable input monitoring, accessibility, screen recording, reboot, make connection to client and type anywhere.

### Expected Behavior

That I can use the keyboard.

### Operating system(s) on local side and remote side

macOS Ventura 13.3.1

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

N/A

**Comment by rustdesk** [comment]
#974

**Comment by rustdesk** [comment]
#974
