### ISSUE TITLE
what happend

### ISSUE THREAD

**Issue by qintian95** [rustdesk/rustdesk#428]
**Describe the bug you encountered:**

![image](https://user-images.githubusercontent.com/39986452/157831278-208e57d1-0cbf-4ac5-95e3-c86cd9645813.png)

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

**Comment by rustdesk** [comment]
Please both side use the same version. 1.1.9 is not compatible with 1.1.8
