### ISSUE TITLE
Android Client unable to connect to the server stably

### ISSUE THREAD

**Issue by laozhoubuluo** [rustdesk/rustdesk#4285]
### Bug Description

I tried to install the Android client on my Android device (the specific model is Huawei Mate 9) and try to control the device. When I just started the client, it can work stably, but after a few hours, even if the client works normally, when I pass When the control terminal is connected, it will also prompt "the remote computer is not online". Sometimes turning on the phone and entering the RustDesk application can return to normal, and sometimes you must restart the service in the RustDesk application to recover, but when I turn on the phone, the phone always prompts that the RustDesk service is running, indicating that the process has not been killed.

### How to Reproduce

Stating RustDesk Android application, Click starting sharing screen on application and connecting the devices after serval hours.

### Expected Behavior

Control terminal always can connection the phone.

### Operating system(s) on local side and remote side

Windows 10 -> Android 9

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

![image](https://user-images.githubusercontent.com/31075951/236606065-ed326928-fe1f-419c-a6cf-8f0235ecb6c3.png)

### Additional Context

this issue only tested on mobile network, not tested on WiFi network for now.

Issue #3322 mentioned in same problem and gave what he thinks is the cause, and I don't know if it will help to solve the problem.
> It sometimes fails to connect to self hosted/public server because the UDP Heartbeat maybe fails to properly keep connection punched (this is discussed on reddit rustdesk but not here I believe) - and this issue I have not seen on Windows Mac Or Linux however, only on Android for now

**Comment by rustdesk** [comment]
will be tracked by  #3893
