### ISSUE TITLE
Cursor does not match the actual position on secondary screen (wayland, cursor controlling always on the primary screen)

### ISSUE THREAD

**Issue by amenk** [rustdesk/rustdesk#4288]
### Bug Description

I am using two screens:

only screen 2 is shared (which is fine, while I am not sure how to select the screen at all)

The mouse courser on the controlling mobile is on the second screen, but on the controlled side it is on the primary screen.

### How to Reproduce

1. Set up two screens
2. connect and share the 2nd one
3. allow mouse cursor control
4. mouse coursers don't match

### Expected Behavior

The blue and the green arrow should match.

But in my case I see the green cursor on Android while on my desktop I see it and click on the blue position.

So controlling is actually not possible.

### Operating system(s) on local side and remote side

Ubuntu 22.04 with Wayland > Android Phone (phone is the controllnig side, wayland is the controlled side)

### RustDesk Version(s) on local side and remote side

local: nightly as of today (md5sum 2fc23126e0dd6eadfb3d70cf7a83a85d  rustdesk-1.2.0-x86_64.deb)
remote: downloaded from appstore

Should not be identical with https://github.com/rustdesk/rustdesk/issues/4261

### Screenshots

![image](https://user-images.githubusercontent.com/1087128/236610114-11b1abd8-79aa-41aa-a360-f675b8642ef3.png)

### Additional Context

Looks like the primary screen offset is not taken into account?

I also switched positions of the screens in the Display config - this did not seem to help.

**Comment by amenk** [comment]
Maybe that also causes what I already mentioned here:

https://github.com/rustdesk/rustdesk/issues/4276#issuecomment-1536479078

I do not see any cursor from the controlling side (also not a circle).

I was pointed out here that there is no good API to capture the cursor name: 

https://github.com/rustdesk/rustdesk/issues/4276#issuecomment-1536481651

But I don't even see a generic circle or so. (I would not care so much about the actual cursor image, just the position would be great to point out things to a colleague especially when screen sharing without input-control)

**Comment by rustdesk** [comment]
@fufesou let's put in low prioritty, we have no reesource to continue dev on wayland lately.

**Comment by oenu** [comment]
Use of X11 is deprecated in KDE 6.0, many many systems are shipping wayland by default and X11 has basically been EOL'd with most of their devs moving to wayland. 

Not sure how development can continue with X11 being high priority

**Comment by mishi321** [comment]
Meet the same problem, need help here.

**Comment by rustdesk** [comment]
@sahilyeole let's take care of this with higher priority than cursor capture.

**Comment by fufesou** [comment]
@sahilyeole The wayland use uinput as the keyboard and mouse input. It must set the mouse resolution before sending input.

You can start from these places:

https://github.com/rustdesk/rustdesk/blob/master/src/server/wayland.rs#L183

https://github.com/rustdesk/rustdesk/blob/master/src/server/uinput.rs


For now it is called only one time if `*CAP_DISPLAY_INFO.read().unwrap() == 0` which means `CAP_DISPLAY_INFO` is not initialized.

**Comment by eugenio-jefferson** [comment]
I'm having the same problem on COSMIC with Wayland and 2 displays.
