### ISSUE TITLE
When connection is left idle after a while, left click will ALWAYS bring up windows start menu

### ISSUE THREAD

**Issue by jonatino** [rustdesk/rustdesk#4293]
### Bug Description

Hi, I'm using rustdesk to connect to a windows 10 vm from my windows 11 pc. I notice after sometime of being connected, if I try to interact with the vm at all, the windows start menu opens. Even if my mouse is no where near the start button, it will always open the start menu. 

### How to Reproduce

Connect to windows machine and leave connection idle for a while

### Expected Behavior

The start menu should only open when clicked and my cursor is over it.

### Operating system(s) on local side and remote side

Windows 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

N/A

### Additional Context

Maybe related to #824

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/tag/nightly try it out
