### ISSUE TITLE
[Task]: web.rustdesk.com SSL Certificate configuration error

### ISSUE THREAD

**Issue by by123456by** [rustdesk/rustdesk#4295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Due to the incorrect SSL certificate configuration of web.rustdesk.com, enabling HSTS has led to access issues. The certificate for this domain should be correctly configured.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/856

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/856

**Comment by by123456by** [comment]
> #856

If web.rustdesk.com is not going to fix it, why keep the link pointing to it if it cannot be accessed?

**Comment by by123456by** [comment]
> #856

Due to the activation of HSTS, this domain can only be accessed via HTTPS. Without proper certificate configuration, it is not possible to access it.

**Comment by rustdesk** [comment]
updated to http://45.76.181.120:8080/#/

**Comment by bjwo** [comment]
I am currently experiencing an HSTS issue again, blocking me from opening the rustdesk.com site or web client. @rustdesk
