### ISSUE TITLE
What commands do I need to enter to build Windows using Docker under Linux. The commands on the document can only generate Linux programs after execution. Do I need to use Docker to build Android iOS Windows and other clients separately? May I ask how to write commands?

### ISSUE THREAD

**Issue by anan1213095357** [rustdesk/rustdesk#4302]
### Description

What commands do I need to enter to build Windows using Docker under Linux. The commands on the document can only generate Linux programs after execution. Do I need to use Docker to build Android iOS Windows and other clients separately? May I ask how to write commands?

### Impact

What commands do I need to enter to build Windows using Docker under Linux. The commands on the document can only generate Linux programs after execution. Do I need to use Docker to build Android iOS Windows and other clients separately? May I ask how to write commands?

### Additional Context

What commands do I need to enter to build Windows using Docker under Linux. The commands on the document can only generate Linux programs after execution. Do I need to use Docker to build Android iOS Windows and other clients separately? May I ask how to write commands?

**Comment by rustdesk** [comment]
#763

**Comment by anan1213095357** [comment]
> #763 Your tutorial did not clearly state how to use Docker to build a Windows client. Or is it possible to have relevant documentation?

**Comment by Aqua1ung** [comment]
Wouldn't it be a lot simpler to just provide a downloadable Docker image, just like you do with [rustdesk-server](https://hub.docker.com/r/rustdesk/rustdesk-server)? Why is it that you don't do the same with the main Rustdesk binary?
