### ISSUE TITLE
Auto start service on Android

### ISSUE THREAD

**Issue by shaqaruden** [rustdesk/rustdesk#4318]
### Description

I have some tablets that are powered off every week. Currently I need to manually go to them to enable the service. Would be nice to have the option to keep it enabled after the device has been turned on if the service was previously running.

### Impact

Maintain consistent reliable connection to devices.

### Additional Context

I am currently using RustDesk on 3 tablets in a production facility. The tablets power comes from the production machine which is turned off on the weekend. When Monday rolls around I no longer have access to these devices unless I remember to go out to the line and start the service again.

**Comment by rustdesk** [comment]
#2529
