### ISSUE TITLE
Selected text background in chat is poorly visible against chat background

### ISSUE THREAD

**Issue by rakleed** [rustdesk/rustdesk#4321]
### Bug Description

The background of the selected text in the chat is poorly visible against the background of the entire chat.

### How to Reproduce

1. Connect to device
2. Open text chat
3. Send a message
4. Select text in that chat

### Expected Behavior

The background of the selected text in the chat is clearly visible against the background of the entire chat.

### Operating system(s) on local side and remote side

macOS 13 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.0 nightly

### Screenshots

![Screenshot 2023-05-10 at 02 41 44](https://github.com/rustdesk/rustdesk/assets/19418601/4826fa62-b258-439b-84a2-0f7a653003f2)

**Comment by rustdesk** [comment]
wontfix for the time being, because out of our control technically, wait for flutter update
