### ISSUE TITLE
The nightly version cannot use rdp to connect to the computer

### ISSUE THREAD

**Issue by cnhongv** [rustdesk/rustdesk#4326]
### Bug Description

The server is self-built and the version is the latest docker version (installed through `docker pull rustdesk/rustdesk-server:latest`).
The  remote side installs the latest version of nightly (build time 2023-05-10 00:21).

The local side uses version 1.1.9, and can normally connect to the remote side in rdp mode.
The local side uses version 1.2.0 and cannot create a rdp tunnel, which is represented by staying on the "hole page".

服务器为自建，版本为最新的docker版本（通过docker pull rustdesk/rustdesk-server:latest安装）；
被控端安装的是最新版nightly版本(构建时间2023-05-10 00:21)

控制端使用1.1.9版本，可以正常使用rdp方式连接到被控端端；
控制端使用1.2.0版本，无法创建rdp隧道，具体表现是停留在“打洞页面”。

### How to Reproduce

As Bug Description described above

### Expected Behavior

As Bug Description described above

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0

### Screenshots

The remote side has checked these options：
![image](https://github.com/rustdesk/rustdesk/assets/19757650/2488124e-52d6-4eab-af97-57dc560b6ea1)

The local side stays in this interface:
![image](https://github.com/rustdesk/rustdesk/assets/19757650/03ebcab0-29c3-48bb-bfb2-31f27403ebb7)

**Comment by rustdesk** [comment]
@Kingtous

**Comment by rustdesk** [comment]
@Kingtous 
There are two ways to invoke rdp
- [ ] from peer card menu
- [ ] from port forward window (shown after above invocation)

**Comment by rustdesk** [comment]
close as fix merged

**Comment by cnhongv** [comment]
@rustdesk 
find new bug!
![image](https://github.com/rustdesk/rustdesk/assets/19757650/909e830a-f8cf-442e-b5ed-0951495bb12f)
Versions built at 00:31 on 2023-05-15 will automatically launch remote desktops using remote Desktop connections, but there is a new problem (there is no problem with the 2023-05-14 00:23 version of nightly). 
The new problem is that when connecting to the remote desktop, the prompt "this session will be interrupted due to a protocol error (0x1104) detected on the client." 
Please reconnect to the remote computer (as shown above) and try again. 
I have tested it on the real machine and sandboxie, the same error; let my partner test on his computer, it is a similar error, but the code is different (see figure below).
构建于2023-05-15 00:31的版本在使用远程桌面的连接会自动启动远程桌面了，但是有了新的问题（2023-05-14 00:23构建的nightly版本是没这个问题的）。
新问题是连接远程桌面时，提示“由于在客户端检测到一个协议错误(0x1104)，这个会话将会中断。请重新连接到远程计算机”（如上图），再次尝试依然如此。
我已在实体机和沙盒进行了测试，同样的错误；让我的同伴在他电脑测试，也是类似的错误，只是代码不同（如下图）。
![956d3f10310865a98ff47a84519abbb](https://github.com/rustdesk/rustdesk/assets/19757650/315e1219-a4b9-45d6-ae13-d853a2965aa6)

**Comment by cnhongv** [comment]
@rustdesk @Kingtous
find new bug!
![image](https://github.com/rustdesk/rustdesk/assets/19757650/909e830a-f8cf-442e-b5ed-0951495bb12f)
Versions built at 00:31 on 2023-05-15 will automatically launch remote desktops using remote Desktop connections, but there is a new problem (there is no problem with the 2023-05-14 00:23 version of nightly). 
The new problem is that when connecting to the remote desktop, the prompt "this session will be interrupted due to a protocol error (0x1104) detected on the client.Please reconnect to the remote computerand try again. "  (as shown above) 
I have tested it on the real machine and sandboxie, the same error; let my partner test on his computer, it is a similar error, but the code is different (see figure below).
构建于2023-05-15 00:31的版本在使用远程桌面的连接会自动启动远程桌面了，但是有了新的问题（2023-05-14 00:23构建的nightly版本是没这个问题的）。
新问题是连接远程桌面时，提示“由于在客户端检测到一个协议错误(0x1104)，这个会话将会中断。请重新连接到远程计算机”（如上图），再次尝试依然如此。
我已在实体机和沙盒进行了测试，同样的错误；让我的同伴在他电脑测试，也是类似的错误，只是代码不同（如下图）。
![956d3f10310865a98ff47a84519abbb](https://github.com/rustdesk/rustdesk/assets/19757650/315e1219-a4b9-45d6-ae13-d853a2965aa6)

**Comment by rustdesk** [comment]
1.1.9 OK? 
@Kingtous

**Comment by cnhongv** [comment]
> 1.1.9 OK? @rustdesk @Kingtous

This problem has not occurred before with version 1.1.9; including the version of nightly that was built yesterday, the error will not occur in the rdp connection. 
So I suspect it's caused by some recent code changes.

之前用1.1.9版本未出现过该问题；包括使用昨日的构建的nightly版本，rdp连接也不会出现该错误。所以我怀疑是最近的某些代码改动造成的。
