### ISSUE TITLE
privilege escalation

### ISSUE THREAD

**Issue by SergeyMy** [rustdesk/rustdesk#4327]
### Bug Description

changing settings without privileges.
(linux desktop)

### How to Reproduce

1.    service started as root
2.    run rustdesk from anywhere other than /usr
    bingo we change the service settings without any rights!.

### Expected Behavior

The application client should never be able to change server settings!

### Operating system(s) on local side and remote side

linux EL8 (RL8)

### RustDesk Version(s) on local side and remote side

1.2.0+ local: nightly as of today

### Screenshots

n/a

### Additional Context
https://github.com/rustdesk/rustdesk/discussions/4273

**Comment by rustdesk** [comment]
submit a pr if u do not like this /usr check.
