### ISSUE TITLE
font not showing

### ISSUE THREAD

**Issue by Fcukcpp** [rustdesk/rustdesk#434]
font not showing
![image](https://user-images.githubusercontent.com/66298978/159356072-df9ced4e-03e1-41b0-a68f-2e8a3d51fc83.png)

...
how to solve？

**How did you install `RustDesk`?**
According to the documentation

---

**RustDesk version and environment**
latest 
2022 3-21   16:17
 ██████████████████  ████████     OS: Manjaro 21.2.5 Qonos
 ██████████████████  ████████     Kernel: x86_64 Linux 5.4.184-1-MANJARO
 ██████████████████  ████████     Uptime: 1d 23h 32m
 ████████  ████████  ████████     Shell: zsh 5.8.1
 ████████  ████████  ████████     Resolution: 1920x1080
 ████████  ████████  ████████     DE: GNOME 41.4
 ████████  ████████  ████████     WM: Mutter
 ████████  ████████  ████████     WM Theme: WhiteSur-dark
 ████████  ████████  ████████     GTK Theme: WhiteSur-dark [GTK2/3]
 ████████  ████████  ████████     Icon Theme: BigSur-black
 ████████  ████████  ████████     Font: Noto Sans 11
 ████████  ████████  ████████     Disk: 441G / 1.2T (41%)
                                  CPU: Intel Core i5-9300H @ 8x 4.1GHz [54.0°C]
                                  GPU: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630]

**Comment by rustdesk** [comment]
Try install ttf-arphic-uming please.
