### ISSUE TITLE
Always Relayed connection

### ISSUE THREAD

**Issue by Swiftgti** [rustdesk/rustdesk#4348]
### Bug Description

Using 1.2.0 as Local, always connects in Relayed connection to ALL 1.1.9 remote side

### How to Reproduce

1.2.0 => 1.1.9

### Expected Behavior

Connect directly as occurs using 1.1.9 => 1.1.9 to the same remote side.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0 => 1.1.9

### Screenshots

non

**Comment by rustdesk** [comment]
@21pages please follow up. @Swiftgti wondering if we can connect to your machine for test.

**Comment by 21pages** [comment]
Please Check this option, 1.1.9 doesn't have this option.
![1683945586577](https://github.com/rustdesk/rustdesk/assets/14891774/0b836f93-3033-4e82-a90c-cbdc1cd6b355)

**Comment by 21pages** [comment]
Please Check this option, 1.1.9 doesn't have this option.
![1683945586577](https://github.com/rustdesk/rustdesk/assets/14891774/0b836f93-3033-4e82-a90c-cbdc1cd6b355)

**Comment by Swiftgti** [comment]
Hi, that option is NOT checked.
I have this issue not only connecting to only one remote side, the issue is with all off them, tested with 10 remote side with windows 10 and windows 11, all of them with 1.1.9

**Comment by 21pages** [comment]
I can't reproduce it, can you tell me more information like whether it's self hosted, encrypted or LAN

**Comment by rustdesk** [comment]
I can not either.

**Comment by rustdesk** [comment]
Please remove connection from the recent sessions, and reconnect.

**Comment by rustdesk** [comment]
Close as noreproduciable, will reopen if you can provide more obvious clue and more feedback from the other users.

**Comment by rustdesk** [comment]
Let me know your `nat_type` value in `RustDesk2.toml` on controlling side (1.2), this file should locate in your %APP_DATAT%/rustdesk/...

**Comment by Swiftgti** [comment]
Hi, it's:
nat_type = 2

**Comment by Swiftgti** [comment]
and nat_type = 1 in the other side.
so its:
nat_type=2 --> nat_type =1

**Comment by Swiftgti** [comment]
Whats are nat type 1 and 2? 
In this same PC (Windows 11) with Rustdesk 1.19 appears nat_type =1 and connects fine to all remote sides, but in this same pc the version 1.2.0 appears nat_type =2, and if i change it, after opening Rustdesk again appears in 2
Probably this is the issue, what can i do. Thanks

**Comment by rustdesk** [comment]
put a fix, try it tommorow when new nightly build is ready.

**Comment by Swiftgti** [comment]
Hi, thanks for the fix. I confirm you that now it's working fine!!

**Comment by RichardFevrier** [comment]
> Please check whether this option (force-always-relay - always connect via relay) is selected, 1.1.9 doesn't have this option.

Can you please tell me where is this option @21pages ?
(using Fedora for remote & iPad for client)

**Comment by 21pages** [comment]
> Please check whether this option (`force-always-relay` - always connect via relay) is selected, 1.1.9 doesn't have this option. ![1683945586577](https://user-images.githubusercontent.com/14891774/238108170-0b836f93-3033-4e82-a90c-cbdc1cd6b355.png)

@RichardFevrier

**Comment by K2M74** [comment]
It is recommended that in the state of relay connection, the software background try to connect directly.
