### ISSUE TITLE
The latest nightly version is unable to display the picture when connected to Android.

### ISSUE THREAD

**Issue by zhangbo8418** [rustdesk/rustdesk#4351]
### Bug Description

The latest nightly version is unable to display the picture when connected to Android.

### How to Reproduce

Android -> Android
Windows -> Android
MacOS -> Android
None of them are able to display.

### Expected Behavior

Display normally.

### Operating system(s) on local side and remote side

Windows -> Android

### RustDesk Version(s) on local side and remote side

1.20

### Screenshots

Connect to the TV.
![6E{SBA(~0G @U)@` NWX0@S](https://github.com/rustdesk/rustdesk/assets/46797568/bde92d08-5d8b-4ac0-8c18-ef7785d6a654)

Connect to Xiao Ai Smart Speaker.

![@O36@TG @PDYYR9AJ@1SH$X](https://github.com/rustdesk/rustdesk/assets/46797568/4625f82e-7479-4661-a128-3e48fe89f798)

**Comment by rustdesk** [comment]
@21pages should be related to yesterday jni change

**Comment by rustdesk** [comment]
The new nightly build will be ready soon.
