### ISSUE TITLE
slow startup on kde wayland (gentoo)

### ISSUE THREAD

**Issue by st0nie** [rustdesk/rustdesk#4352]
### Bug Description

When I use rustdesk in kde wayland, the window of rustdesk does not appear immediately, but after some time

It can be reproduced when using nightly's appimage and tar.zst

The terminal does not output anything for the first 5-10 seconds, after that it outputs
```
flutter: launch args: []

** (rustdesk:16493): WARNING **: 12:00:48.117: Unable to retrieve framework response: Message is not valid JSON

** (rustdesk:16493): WARNING **: 12:00:48.117: Unable to retrieve framework response: Message is not valid JSON

** (rustdesk:16493): WARNING **: 12:00:48.117: Unable to retrieve framework response: Message is not valid JSON

** (rustdesk:16493): WARNING **: 12:00:48.117: Unable to retrieve framework response: Message is not valid JSON

** (rustdesk:16493): WARNING **: 12:00:48.117: Unable to retrieve framework response: Message is not valid JSON

** (rustdesk:16493): WARNING **: 12:00:48.117: Unable to retrieve framework response: Message is not valid JSON

** (rustdesk:16493): WARNING **: 12:00:48.117: Unable to retrieve framework response: Message is not valid JSON

** (rustdesk:16493): WARNING **: 12:00:48.117: Unable to retrieve framework response: Message is not valid JSON
flutter: initialize FFI main
flutter: _appType:main,info1-id:a8cc6346af8d8f3ac715370263676750,info2-name:Gentoo,dir:/home/ston/Documents
flutter: _globalFFI init
flutter: _globalFFI init end
flutter: registerEventHandler native_ui native_ui
```

After another 5s, it will output
```
flutter: handled by uni link: false
flutter: [MultiWindowHandler] active window change: [0]
```

### How to Reproduce

Open konsole, type rustdesk, enter

### Expected Behavior

The rustdesk window should appear immediately

### Operating system(s) on local side and remote side

gentoo linux ~amd64

### RustDesk Version(s) on local side and remote side

nightly

### Screenshots

![Screenshot_20230513_114447](https://github.com/rustdesk/rustdesk/assets/42872734/5736a3a6-5f85-4b44-aa14-46b2e8a70fa3)
![Screenshot_20230513_114454](https://github.com/rustdesk/rustdesk/assets/42872734/64a5aa05-abc6-4c76-a9a8-2753b386f65f)
![Screenshot_20230513_114509](https://github.com/rustdesk/rustdesk/assets/42872734/516fc7e4-6824-4d86-b612-ce22f709c139)

**Comment by rustdesk** [comment]
tracked by #3565

**Comment by rustdesk** [comment]
Wondering if you can build and run from source code to get more clue. Frankly, we do not dev on gentoo, and wont setup env on it lately.

**Comment by st0nie** [comment]
Thank you, the rustdesk compiled from source in gentoo is working fine, 
I also want to compile rustdesk from source on gentoo, but vcpkg needs 
to be networked, and gentoo's packaging environment has a network 
sandbox, so vcpkg has become my biggest obstacle to packaging, is there 
any way to use vcpkg without network? Or is there any way to package 
without vcpkg?

在 2023/5/13 12:26, RustDesk 写道:

**Comment by rustdesk** [comment]
https://github.com/Kingtous/rustdesk_thirdparty_lib

**Comment by st0nie** [comment]
> https://github.com/Kingtous/rustdesk_thirdparty_lib

https://github.com/Kingtous/rustdesk_thirdparty_lib/tree/main/vcpkg/installed/x64-linux/lib

no opus here

So do I have to install an opus via vcpkg and pack it in myself?

**Comment by rustdesk** [comment]
You can install on Ubuntu, then move to gentoo.

**Comment by st0nie** [comment]
> You can install vcpkg on Ubuntu via VM or docker, then move to gentoo. Be clever. :)

https://github.com/microcai/gentoo-zh/pull/3245#issuecomment-1546664288

Now I managed to package it in gentoo and it works fine

**Comment by rustdesk** [comment]
let us know if you get any clue. @fufesou
