### ISSUE TITLE
Mouse-cursor only half-size in VMware machine

### ISSUE THREAD

**Issue by FCrane** [rustdesk/rustdesk#4356]
### Bug Description

Hi!

I'm using the latest nightly (13.05.23) and it shows the strange issue, that the mouse cursor is only 50% of the normal size in a VMware machine. Previous versions had a double-sized cursor in the whole Rustdesk window (inside and outside the VMware machine on the remote machine), the latest version now shows correctly sized (100%) cursor in the Rustdesk window exervwhere except in a VMware window (where it is half sized).

I'm using scale mode "Scale original", all OSes use 100% DPI. I'm using a TouchPad mouse driver on the remote machine, because there is no physical mouse attached and without that driver, the mouse cursor is only a blue dot everywhere, which is unusable, of course.

Regards!

### How to Reproduce

See description.

### Expected Behavior

Correct mouse cursor size (100%) everywhere (inside and outside a VMware machine).

### Operating system(s) on local side and remote side

Windows 11 x64

### RustDesk Version(s) on local side and remote side

Latest nightly

### Screenshots

Can't take screenshot of this.

**Comment by rustdesk** [comment]
tracked by #4357

**Comment by rustdesk** [comment]
@fufesou low priority.

**Comment by FCrane** [comment]
What's even worse is that the "text cursor" (when you move the mouse inside an edit control., etc.) is completely messed up. Not only half size, but just some dots, which makes it impossible to use it to set the caret! This all used to work in previous versions...

Also, since you can emulate a virtual display driver for headless systems, could you maybe also provide a "virtual mouse driver" that makes the cursor shapes work when no mouse is attached? Currently, this only works when I install some 3rd party Touchpad mouse driver, but it should work out-of-the-box without 3rd party software...

Thanks!

**Comment by alexandru-bagu** [comment]
> What's even worse is that the "text cursor" (when you move the mouse inside an edit control., etc.) is completely messed up. Not only half size, but just some dots, which makes it impossible to use it to set the caret! This all used to work in previous versions...
> 
> Also, since you can emulate a virtual display driver for headless systems, could you maybe also provide a "virtual mouse driver" that makes the cursor shapes work when no mouse is attached? Currently, this only works when I install some 3rd party Touchpad mouse driver, but it should work out-of-the-box without 3rd party software...
> 
> Thanks!

Did you try privacy mode? Privacy mode 2 installs a virtual monitor and makes it the main display. From my experience the cursor is doubled but it's working pretty well otherwise.
