### ISSUE TITLE
Installation options should be remembered when upgrading

### ISSUE THREAD

**Issue by FCrane** [rustdesk/rustdesk#4360]
### Bug Description

Hi!

When upgrading Rustdeks (e.g. installing a new nightly by renaming it to "rustdesk-install.exe", the options are not remembered, which is quite annoying. The "Installation path", "Create start menu shortcut", "Create desktop icon" and "Install virtual display driver" should be remembered from the last installation for quicker, more consistent and convenient upgrading.

Regards!

### How to Reproduce

Upgrade Rustdesk

### Expected Behavior

All options should be remembered from previous installation

### Operating system(s) on local side and remote side

Windows 11 x64

### RustDesk Version(s) on local side and remote side

Latest nightly

### Screenshots

n/a

**Comment by FCrane** [comment]
Why? Who would want to specify all options again and again when upgrading a program??? There is a reason when a user changed the default installation options and the chances are almost 100% that he wants them the same way the next time he upgrades the program...

Always reverting back to unwanted defaults is bad UI design.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4331
