### ISSUE TITLE
Key sequence doesn't switch languages in the local machine

### ISSUE THREAD

**Issue by mtelis** [rustdesk/rustdesk#4362]
### Bug Description

Both local and remote machine have EN-RU keyboard; Ctrl-Shift is used to switch between languages. When remote window (Rustdesk) is active, Ctrl-Shift switches language bar EN->RU-EN in the remote but not in the local machine. In result, you always typing in latin (EN).

### How to Reproduce

Connect to remote machine, try pressing language switching key sequence and notice that language bar (in the taskbar) is switching in the remote but not in the local machine.

Open notepad on the remote and try to type in cyrillic -- it won't work unless you switch (with mouse, for example) local language bar to cyrillic.

### Expected Behavior

Key sequence is switching language in both local and remote machines. That's how it works in Teamviewer and Anydesk

### Operating system(s) on local side and remote side

Windows 10 -> Windows 7

### RustDesk Version(s) on local side and remote side

1.2.0 both local and remote

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/335301/6b11cd73-2c08-4ad0-8b1b-80803a215a69)

**Comment by rustdesk** [comment]
> Ctrl-Shift switches language bar EN->RU-EN in the remote but not in the local machine

expected behavior

**Comment by rustdesk** [comment]
@fufesou may need handle ctrl shift specially as tv.

**Comment by Touska** [comment]
please put priority on this, because every a need for non-English language person

**Comment by rustdesk** [comment]
> Mac (UK keyboard) to Windows (UK keyboard) does not map correctly either.
> 
> \ on local keyboard maps to # to remote machine. I have to locally press ~ to get remote \

https://github.com/rustdesk/rustdesk/issues/1547

**Comment by fufesou** [comment]
@RichardBurt65 Hi, thanks for your feedback. 

1. "Map mode" simulates positioned key on the remote side.
2. "Translate mode" simulates char on the remote side.

Did use the "Map mode"? 

![1688293553893](https://github.com/rustdesk/rustdesk/assets/13586388/64520687-eb85-4566-a08e-298b24b89f8b)


Which input source did you use on macOS?

![1688293127507](https://github.com/rustdesk/rustdesk/assets/13586388/4805e8e8-eaa9-4247-923e-cc9c49278653)

`British - PC` on macOS has the same layout to windows.

You can try
1. `British - PC` input source with "Map mode"
3. "Translate mode"

`British` input source with "Map mode"
```
local ----- remote
\`   -----  #\
```

`British - PC` input source with "Map mode"
```
local ----- remote
#\  -----  #\
```
