### ISSUE TITLE
error: failed to run custom build command for `scrap v0.5.0 

### ISSUE THREAD

**Issue by MhTakwa** [rustdesk/rustdesk#4364]
### Bug Description

while building build rust desk 1.1.9, I get the following error:
OS: windows 10
I have LLVM and VCPKG installed
![image](https://github.com/rustdesk/rustdesk/assets/38882375/7d468d6b-07ff-4372-8a88-da82d2d48fed)

### How to Reproduce

I followed the documentation

### Expected Behavior

build success

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/38882375/b78e4e46-214b-4860-a07f-ba3d224672db)

**Comment by rustdesk** [comment]
#763
