### ISSUE TITLE
Freezing window in windows 10

### ISSUE THREAD

**Issue by TeamPattuki** [rustdesk/rustdesk#4368]
### Bug Description

Not sure if it is a security feature or bug but when I tried to configure the network settings or uninstall some applications via control panel, their window freezes.

### How to Reproduce

Remote to windows 10 and try to configure network settings such as IP address, Default Gateway or DNS server and try to uninstall app using control panel of windows 10.

### Expected Behavior

Network configuration and app uninstall should work normally.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

![Untitled](https://github.com/rustdesk/rustdesk/assets/42864522/97f3f35d-92b9-4bd8-9909-df91b55a0c6d)

**Comment by rustdesk** [comment]
search uac related issue please
