### ISSUE TITLE
Under Portrait(flipped)  or Landscape(flipped) mode in Win10, RustDesk throws "An existing connection was forcibly closed by the remote host"

### ISSUE THREAD

**Issue by marcus1877** [rustdesk/rustdesk#437]
**Describe the bug you encountered:**
In Windows 10 , the Protrait(flipped) of Display Orientation disconnect prevent RustDesk to connect. "An existing connection was forcibly closed by the remote host" is thrown at master machine
...

**What did you expect to happen instead?**
Display Orientation in Windows 10 shouldN't stop RustDesk from connecting
...

**How did you install `RustDesk`?**
Download from github and install

---

**RustDesk version and environment**
Version=1.1.8.0
OS=Windows 10 Pro

Windows 10 Pro

**Comment by rustdesk** [comment]
try out https://github.com/rustdesk/rustdesk/releases/download/tmp/rustdesk-1.1.9-putes.exe
