### ISSUE TITLE
RustDesk 1.1.9 appear Crash after opening the application.

### ISSUE THREAD

**Issue by UnNew90** [rustdesk/rustdesk#4375]
### Bug Description

Hi RustDesk Support Team,

It appears to RustDesk appear Crash dialog box after run the application.

Below are the details:-

Exception Name: NSInvalidArgumentException
Description: _createMenuRef called with existing principal MenuRef already associated with menu
User Info: (null)

0   CoreFoundation                      0x00007ff80f730bc2 __exceptionPreprocess + 242
1   libobjc.A.dylib                     0x00007ff80f25875c objc_exception_throw + 48
2   CoreFoundation                      0x00007ff80f730a28 +[NSException raise:format:] + 206
3   AppKit                              0x00007ff8126a5008 -[NSCarbonMenuImpl _createMenuRef] + 55
4   AppKit                              0x00007ff8126a49d7 -[NSCarbonMenuImpl _instantiateCarbonMenu] + 133
5   AppKit                              0x00007ff81269def9 -[NSApplication finishLaunching] + 690
6   AppKit                              0x00007ff81269d998 -[NSApplication run] + 250
7   rustdesk                            0x0000000102dafb21 rustdesk + 2657057
8   rustdesk                            0x0000000102b42578 rustdesk + 111992
9   rustdesk                            0x0000000102b2dd26 rustdesk + 27942
10  rustdesk                            0x0000000102b4557c rustdesk + 124284
11  dyld                                0x000000020372341f start + 1903

### How to Reproduce

Waiting for RustDesk team to fix as the 1.2.0 version having a problem with Screen Recording issue.

### Expected Behavior

N/A

### Operating system(s) on local side and remote side

macOS Ventura 13.4

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

<img width="910" alt="SCR-20230514-rfit" src="https://github.com/rustdesk/rustdesk/assets/38325821/92c07ad7-c783-4995-8d6f-e4f9f27c33a0">

**Comment by rustdesk** [comment]
sorry, we wont fix 1.1.9, you can omly wait 1.2 matute.
