### ISSUE TITLE
AZERTY, no support for the ^¨ key

### ISSUE THREAD

**Issue by TKMankind** [rustdesk/rustdesk#4377]
### Bug Description

Hello,

So... I found 2 issues with AZERTY layout. I am unsure if the second one is really from this or from a specific software. I will let you judge.

1)
First, there is no support for the symbols ¨^ who have a dedicated key on every AZERTY keyboard. See the attached screenshot from Wikipedia, it is at the left of the main ENTER/ENTREE key, you will find them in red on one key : 

This is a very special key in the AZERTY layout. Press it, and nothing will happen right now because the computer is waiting for you for the second key, where the symbol must be applied.

With a normal AZERTY keyboard, if I want the "ô" like in the french word **"impôts"**, I must press the "¨^" key, release it, and press the "o" one.
If I want to get the "ë" like for the word **"noël"**, I must press SHIFT+"¨^", release them, and the "e" one.
For the record, if I do it to a letter who shouldn't get one of said symbols, like "p", I will get "^p" and "¨p" and this is as expected.

But with RustDesk, I get funny results. Pressing the "¨^" will give a ")" first hand and the targetted key will get me the "ô". So for "impôts", I will get "imp)ôts". The ")" is a bonus ? XD
For "noël" it is even better. After pressing SHIFT+"¨^", I will get a ° first hand and the targetted key will result to a "no°êl" at the end. Yes, the two points if I can call them like that aren't even there.

ALT CODES don't work.

The issue was reproducted on VMs and real hardware.

2)
On the Legion laptop of a friend I helped today, pressing a number on the numpad while the NumLock is activated will cause the appareance of the NumLock indicator, this at EVERY number pressed. I mean this :
![image](https://github.com/rustdesk/rustdesk/assets/8639768/068e7f7b-7095-49cc-9570-ae0bb460367e)
This is also the case with the Capslock indicator, when I pressed a number while CapsLock is activated : 
![image](https://github.com/rustdesk/rustdesk/assets/8639768/d6c6a6e5-3ef8-42f8-b9f5-745c5a06031e)

I think this is because of the _Lenovo Vantage_ software, but I can't be sure of that as I can't keep the control of said laptop all the time for my personal enjoyment :)

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/8639768/861eaa0b-42a7-4f06-8509-fc0a4289081b)

**Comment by rustdesk** [comment]
#1547

**Comment by rustdesk** [comment]
sorry, second one is expected, shortly wont be fixed.
