### ISSUE TITLE
The remote control can be connected but cannot be operated after the mac screen is off

### ISSUE THREAD

**Issue by zzw6776** [rustdesk/rustdesk#4378]
### Bug Description

The remote control can be connected but cannot be operated after the mac screen is off

### How to Reproduce

After closing the cover of the mac, connect two external monitors. After the mac locks the screen with the shortcut key Control-Command-Q, wait for the mac to turn off the screen. At this time, use rustdesk to connect to the mac, and the link can be successfully established, but the screen is completely black after establishment. Unable to perform any operations, test todesk, in the same scenario, you can directly wake up the mac from the off-screen state

mac 合盖后外接两个副显示器,在mac使用Control-Command-Q快捷键锁屏后,等待mac自己息屏,这时使用rustdesk链接mac,可以成功建立链接,但是建立后画面为全黑,无法进行任何操作,测试todesk,同样的场景下可以将mac从息屏状态直接唤醒

### Expected Behavior

work

### Operating system(s) on local side and remote side

Windows10 & Android -> mac 12.6.5

### RustDesk Version(s) on local side and remote side

1.1.9-> 1.1.9

### Screenshots

![CBF9DC67971707C5FEA5D04ECEEA3ABE](https://github.com/rustdesk/rustdesk/assets/14048998/4df0e3fc-3911-41a8-90d0-6a620e7ff12c)

**Comment by rustdesk** [comment]
#2022

**Comment by rustdesk** [comment]
[#wake up](https://github.com/rustdesk/rustdesk/issues/981)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/981
