### ISSUE TITLE
Win11 -> Ubuntu18.04, cannot use alt+tab to switch window

### ISSUE THREAD

**Issue by HansRen1024** [rustdesk/rustdesk#438]
Hi there,

Me again! I am using a win11 device to control an Ubuntu18.04 device, and I found that I cannot use alt+tab to switch remote windows. May I ask for a feature of that, please? Many thanks.

**Comment by grummbeer** [comment]
Do you have already tried the nightly versions? https://github.com/rustdesk/rustdesk/releases/tag/nightly
if its not any sort of keyboard issue, then it should work. Does it?

**Comment by rustdesk** [comment]
#1547
