### ISSUE TITLE
Wrong translation in Spanish Language (and solution)

### ISSUE THREAD

**Issue by DogAndCode** [rustdesk/rustdesk#4384]
### Bug Description

Hi there, I have installed the Rust Desktop in Spanish but part of the translation is in italian

### How to Reproduce

When I click on the RustDesk icon on my pc desktop it appear a dashboard, where the translation under the title "Tu escritorio" on the left side of the dashboard is incorrect. 

### Expected Behavior

It said this in italian: "Puoi acceder al tuyo...riportati qui." instead of said in spanish (the installation language): "Puedes acceder a tu escritorio usando este ID y contraseña"

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![Sin título](https://github.com/rustdesk/rustdesk/assets/78352930/094fe744-969f-49d3-bb1d-d642cd3593c9)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/blob/2d7bebb54be71da4f2256672c011e27ae97ffc62/src/lang/es.rs#L6
