### ISSUE TITLE
Unable to Use RDP Function (Client 1.2, Remote End 1.1.9)

### ISSUE THREAD

**Issue by popomi** [rustdesk/rustdesk#4385]
### Bug Description

After upgrading the client to version 1.2.0, I tried to use the RDP function for remote connection, but clicking the "New RDP" button cannot create a new connection. However, I was able to create a new port for LAN penetration using TCP connection. What could be the reason for this? Is it a bug?

### How to Reproduce

1.2Click "New RDP" when clicking on the remote host in the version.

### Expected Behavior

No response

### Operating system(s) on local side and remote side

windows10->windows10

### RustDesk Version(s) on local side and remote side

1.2->1.1.9

### Screenshots

1.2->1.1.9

**Comment by rustdesk** [comment]
#4326
