### ISSUE TITLE
Double click does something else

### ISSUE THREAD

**Issue by AdamRGrey** [rustdesk/rustdesk#4398]
### Bug Description

when double clicking text, it seems to triple-click instead, meaning selecting text is strange and offputting

### How to Reproduce

1. on host, have text on screen. text editors, web browsers, etc all work.
2. from client, double click text.

### Expected Behavior

a word is selected

### Operating system(s) on local side and remote side

debian 11 -> windows 10, debian 11 -> windows 11

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

expected: double clicking a word. it works if you use the remote's mouse. ![expected](https://github.com/rustdesk/rustdesk/assets/3400463/197403c4-b22a-4892-949d-c74f7b355084)
observed: as though the word was triple-clicked. ![observed](https://github.com/rustdesk/rustdesk/assets/3400463/7e5d833f-eb8a-4492-aaec-15a8b70b8d53)

**Comment by rustdesk** [comment]
#4090
