### ISSUE TITLE
X11 error: connection refused after login on gnome (arch/manjaro gnome)

### ISSUE THREAD

**Issue by NicKoehler** [rustdesk/rustdesk#440]
## Describe the bug you encountered:
I enabled the service on my personal computer at home.
I usually turn on my computer using Wake on wan and connect from remote.
I received the following error on my client after I entered my password from the login screen:
`X11 error: connection refused`

## What did you expect to happen instead?
Login as normal.

##  How did you install `RustDesk`?
I installed it from the [AUR](https://aur.archlinux.org/packages/rustdesk-bin) repo.

---

## RustDesk version and environment:

Rustdesk 1.1.8

OS: Archlinux
DE: Gnome on XORG
Kernel: 5.17.1

---

## Workaround:

I can successfully connect if I restart the rustdesk service via SSH after I logged in with:
```bash
systemctl restart rustdesk
```

**Comment by ceewanna** [comment]
My recent Manjaro/Gnome couldn't get rustdesk running even login with Gnome Xorg. I tried restarting rustdesk after login but it still couldn't run. However, if I activate rustdesk from command line, the login screen showed up but with warning that I couldn't login as it is on wayland (even I was actually on x11, checked from echo $XDG_SESSION_TYPE )

The above was observed from rustdesk 1.2.0 and 1.1.9.

On the same machine above, I had anydesk on. Anydesk could work properly, connecting to another Manjaro/XFCE. However, connection to itself from another machine isn't possible and was reported on screen that the remote is on wayland.

**Comment by rustdesk** [comment]
root?

**Comment by ceewanna** [comment]
You mean the user in the context above? No, just typical user which was created along linux setup.

I have been using rustdesk on Manjaro/XFCE for quite sometime without problem but recently there is a need to set up a certain package which requires wayland. Then I thought Gnome would be fine as it caters both x11 and wayland.

**Comment by rustdesk** [comment]
Now it is x11 or wayland?

**Comment by ceewanna** [comment]
Manjaro/Gnome has both Xorg (x11) and Wayland. I am talking about rustdesk on Manjaro/Gnome on Xorg that is not working.

**Comment by ceewanna** [comment]
1) Activating rustdesk from icon not working.
2) Activating rustdesk from command line has this screen. 

![anydesk00001-1](https://user-images.githubusercontent.com/84608596/222043241-8a1626a8-7330-4250-a63b-18b8817708bb.png)

**Comment by rustdesk** [comment]
> 1. Activating rustdesk from icon not working.
> 2. Activating rustdesk from command line has this screen.
> 
> ![anydesk00001-1](https://user-images.githubusercontent.com/84608596/222043241-8a1626a8-7330-4250-a63b-18b8817708bb.png)

Icon is old, seems an old nightly build.

**Comment by ceewanna** [comment]
It is 1.2.0, taken probably last month.

**Comment by rustdesk** [comment]
> It is 1.2.0, taken probably last month.

Try out latest nightly, we modified rustdesk.desktop 20th last month, it should work for you.

**Comment by ceewanna** [comment]
1.2.0 as of today
1) Upon Linux login, activating rustdesk icon requires hitting the icon at least the second time to see the main screen pop up.
2) The main screen still shows "Warning: Login screen using Wayland is not supported." though it is actually x11.
3) Able to enter id and remote login to another pc.

**Comment by rustdesk** [comment]
> 2\. The main screen still shows "Warning: Login screen using Wayland is not supported." though it is actually x11.

`Login screen` is different.

**Comment by rustdesk** [comment]
Could you test latest build? #4136 may fix this.
https://github.com/rustdesk/rustdesk/releases/tag/nightly

**Comment by NicKoehler** [comment]
I can test it, but the issue did not occur every time. I am unsure how to replicate the behavior, as it rarely occurred

**Comment by NicKoehler** [comment]
It didn't happen anymore for now. I'll reopen the issue if I see it happening again.

**Comment by rustdesk** [comment]
again https://github.com/rustdesk/rustdesk/discussions/5095

**Comment by vanillyn** [comment]
i think there may be another cause, as sometimes rustdesk resets the configuration when on arch linux
however, even after setting the config back, it will not work
though it sometimes does work, but we havent figured out how or when

**Comment by vanillyn** [comment]
issue also appears when self-hosting the rustdesk server
when self-hosting, both journalctl and systemctl status do not show any errors
neither do the client-side logs or the logs of the other computer

**Comment by rustdesk** [comment]
@vanillyn please try out latest nightly build.
