### ISSUE TITLE
Why not use libsciter-js

### ISSUE THREAD

**Issue by Technetium1** [rustdesk/rustdesk#442]
From the [download page](https://sciter.com/download/):
> Sciter.JS is now mainstream version of former Sciter. Sciter.JS is the same engine that uses standard JavaScript instead of TIScript.

> Note: Sciter.TIS is supported and will be supported in foreseeable future but its script feature set is frozen. Please consider Sciter.JS if you are starting new project.

How difficult would it be to move to the new version?

**Comment by rustdesk** [comment]
Because we are going to discard Sciter.
