### ISSUE TITLE
Keyboard cannot be used

### ISSUE THREAD

**Issue by lucky-wh** [rustdesk/rustdesk#4432]
### Bug Description

My situation is using my Mac to control the win computer, and the built-in keyboard cannot be used

Macbook built-in keyboard

### How to Reproduce

I didn't use too many settings, the keyboard can't be used normally after the software is installed for the first time

### Expected Behavior

My situation is using my Mac to control the win computer, and the built-in keyboard cannot be used

### Operating system(s) on local side and remote side

mac -> win

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

The screenshot doesn't seem to reflect the problem

**Comment by rustdesk** [comment]
#974
