### ISSUE TITLE
Remote desktop unexpectedly disconnected, returning to the welcome login screen

### ISSUE THREAD

**Issue by lvmingzhe** [rustdesk/rustdesk#4433]
### Bug Description

I have been using Rustdesk continuously for more than three months and it used to be normal.
My local computer is a Windows 11 laptop, and my remote computer is a Ubuntu 20.04 desktop computer. Both machines are in my office.
I used a self built server for Rustdesk, which has a very fast connection speed and stable network speed.
But recently, I have found that it often appears in normal use. After flashing back to the welcome login screen and logging in again, the original running programs on the desktop disappear.
In order to fix this issue, I have made the following attempts:
1. Directly using the ubuntu20.04 physical machine, no issues with the rollback welcome login screen were found, and everything was normal.
2. Scanned/var/log/syslog, and according to the interpretation of chatgpt-4.0:
It believes that the Rustdesk application encountered a problem while attempting to import Python's pynput module. Specifically, this is a platform issue as pynput cannot run on the current platform. The error message is ImportError: This platform is not supported: ("failed to acquire X connection: No module named 'tkiner'", ModuleNotFoundError ("No module named 'tkiner'"), indicating that Python's tkiner module cannot be found.
The tkiner module in Python is a standard graphical user interface (GUI) library for creating desktop applications. The problem here may be that tkinder is not installed in your Python environment.
One possible way to solve this problem is to install Tkinter. "
(base)  hello@hello-PowerEdge-T640 :~$ python
Python 3.8.13 (default, Mar 28 2022, 11:38:47) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
>>> 
>>> print(tkinter.TkVersion)
8.6
So I reinstalled Tkinter, but the problem remained unresolved.
3. I used ClamAV and rkhunter for a full virus scan, but no issues were found.
4. I turned off the system's automatic sleep, settings power automatic suspend off, but the problem still persists.
5. I closed the settings privacy screen lock automatic screen lock
6. I closed the settings privacy screen lock lock screen on suspend
7. I have turned off settings keyboard shortcuts, and all shortcuts are disabled
8. I closed the settings power save black screen and set it to none
9. settings-users-authentication and login： automatic login ON.
10. I tried using another remote desktop software, VNC Viewer, which appears approximately every half hour to return to the welcome login screen, with a frequency similar to that of RUSTDESK.

### How to Reproduce

I'm not sure if you can reproduce this error. I just encountered this issue during normal use, which seems to be a stability issue.
It appears approximately once or twice an hour.

### Expected Behavior

I hope it can return to normal and not fall back to the welcome screen, and cause me to lose all the content I am currently working on.

### Operating system(s) on local side and remote side

Windows 11 -> Ubuntu 20.04

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/35017560/3483d30d-a556-4419-abdd-e3edbd3f4526)
![image](https://github.com/rustdesk/rustdesk/assets/35017560/2c09812d-a580-4a46-832b-15b2f0c8818f)
![image](https://github.com/rustdesk/rustdesk/assets/35017560/eee5ce1c-aebc-47db-bdcd-28e2009a2c3f)
![image](https://github.com/rustdesk/rustdesk/assets/35017560/82850bb3-bd58-4299-bd2d-666c4141ed21)
![image](https://github.com/rustdesk/rustdesk/assets/35017560/ceaea980-4b32-4fec-ade1-0bf351988714)
![image](https://github.com/rustdesk/rustdesk/assets/35017560/54c109dc-44bd-459f-a4d3-7228761a2fbd)
![image](https://github.com/rustdesk/rustdesk/assets/35017560/8eb52f90-6752-4b61-a66b-26ec011fe770)
![image](https://github.com/rustdesk/rustdesk/assets/35017560/64dfc423-185a-46e1-b64a-4fb76956d97d)
![image](https://github.com/rustdesk/rustdesk/assets/35017560/163ddaa0-6729-4a7f-ac40-c190eb04b686)
![image](https://github.com/rustdesk/rustdesk/assets/35017560/9f009a00-4721-4112-b83e-ee5a3aaa04e5)
![image](https://github.com/rustdesk/rustdesk/assets/35017560/bba5253f-5edb-48ce-9602-df04e6bb89bc)
![image](https://github.com/rustdesk/rustdesk/assets/35017560/1e56f5cd-307d-4af3-8e94-b8e12d5fd115)
![image](https://github.com/rustdesk/rustdesk/assets/35017560/72001f4b-7932-438b-90c2-3be6764e3813)

### Additional Context

[syslog.txt](https://github.com/rustdesk/rustdesk/files/11521512/syslog.txt)

**Comment by rustdesk** [comment]
Sorry, I do not think we can do anything to help you.

**Comment by rustdesk** [comment]
You can try out https://github.com/rustdesk/rustdesk/releases/tag/nightly, which does not use python anymore.

**Comment by lvmingzhe** [comment]
Thanks for your quick reply. I would have a try with the recommended version.
