### ISSUE TITLE
Rustdesk Nightly Custom Built for macOS doesn't Work

### ISSUE THREAD

**Issue by dissidius** [rustdesk/rustdesk#4444]
### Bug Description

The Client App of Rustdesk Nightly 1.2.0 if downloaded from the official repo releases works, custom builds via gitactions doesn't.

For all other OSs everything works flawlessly.

Can you please fix as this pervents or makes it very difficult and time consuming for mass deployment when hostin a private server ?

### How to Reproduce

Build From GitActions, install the *.dmg in macOS and Launch the App.

### Expected Behavior

Expected the App to Launch, instead it just does't launch and generates the attached log in diagnostics folder in macOS, no crash log at all
[RustDesk-2023-05-18-104817.zip](https://github.com/rustdesk/rustdesk/files/11529112/RustDesk-2023-05-18-104817.zip)

### Operating system(s) on local side and remote side

macOS all versions

### RustDesk Version(s) on local side and remote side

1.2.0 Nightly Custom Build

### Screenshots

![Log Screenshot](https://github.com/rustdesk/rustdesk/assets/10442022/d2ee59e7-3701-48ba-bcad-617560662d68)

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
our time is not free either
