### ISSUE TITLE
When opening some apps on remote Android phones, the screen cannot be viewed, and the screen will become very blurry, such as WeChat, mobile phone SMS and other software involving chat will not be viewable

### ISSUE THREAD

**Issue by ooil929** [rustdesk/rustdesk#4449]
### Bug Description

When opening some apps on remote Android phones, the screen cannot be viewed, and the screen will become very blurry, such as WeChat, mobile phone SMS and other software involving chat will not be viewable Other non - chat software can be viewed normally

### How to Reproduce

Open WeChat, SMS and other apps that involve chat input

### Expected Behavior

No matter what app I open, I can see the screen remotely

### Operating system(s) on local side and remote side

1.1.9

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

https://github.com/rustdesk/rustdesk/assets/39184577/fd18fd56-5440-4485-8da4-3f11bb7a3223

![AKLR%81`}H1BOOZ4A12PW@1](https://github.com/rustdesk/rustdesk/assets/39184577/4b92810b-4c75-4c2e-a7db-8abe9426494f)
![`7YVJEABD7 A71ON$SY(%OC](https://github.com/rustdesk/rustdesk/assets/39184577/1cd1fa66-2c75-442b-88aa-35c1ec37cc78)

**Comment by rustdesk** [comment]
Out of our control.
