### ISSUE TITLE
Manual entry into local or remote "folder location" input on File Transfer window doesn't work correctly.

### ISSUE THREAD

**Issue by pbarney** [rustdesk/rustdesk#4462]
### Bug Description

When manually entering a folder location into form inputs on the File Transfer window, the cursor keeps jumping back to the very beginning of the field, making it unusable for manual entry. 

See the screenshot for specifics. I have verified that this occurs under both Windows 10 and Windows 7.

### How to Reproduce

1. From the RustDesk main window, click "Transfer File"
2. In either form field, begin typing a folder location manually.
3. Witness the cursor move to the beginning of the field over and over.

### Expected Behavior

Expected behavior is that the cursor position stays at the end of the text in the input field.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 7

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/428178/b3bdc10f-48c6-4f87-a5bd-6d607a65706a)

**Comment by rustdesk** [comment]
try out nightly build please
