### ISSUE TITLE
Windows come to front on mouse contact (Linux)

### ISSUE THREAD

**Issue by paulsommer** [rustdesk/rustdesk#4466]
### Bug Description

When I work inside a window that's above a rustdesk window and I accidentally touch (no click) that rustdeck window it immediately comes to front. That's not the correct behavior.

### How to Reproduce

- have Kubuntu 22.04 installed (maybe on any KDE- desktop)
- Install rustdeck
- go to the settings->window-settings->window-behaviour and select "activation on mouse contact"  for "rules for window activation"
- open rustdeck
- place another window above the rustdeck window (overlapping)
- move the mouse over the rust window
- see the rust window coming to front

### Expected Behavior

When the mouse touches the rust window (intentionally or unintentionally) the window should get the input focus but should **not** come to front. It should only come to front upon mouse click.

### Operating system(s) on local side and remote side

Kubuntu Linux 22.04 and 23.04

### RustDesk Version(s) on local side and remote side

1.1.9->1.1.9

### Screenshots

The problem only exists with partly overlapping windows off cause.

**Comment by rustdesk** [comment]
try out nightly build please.

**Comment by paulsommer** [comment]
Thanks for that.

Unfortunately the corrent version has a build error. 

```
$ build.py 
features: ['inline']
False
error: no such subcommand: `bundle`

        Did you mean `build`?

        View all installed commands with `cargo --list`
Error occurred when executing: cargo bundle --release --features inline. Exiting.
```

It's in line 532 of build.py
When I fix that the build ends up with
`error: could not find system library 'xi' required by the 'x11' crate`
libx11-dev is already installed

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/tag/nightly

**Comment by paulsommer** [comment]
WOHW!. I'm really impressed.
It gained some waight but it relly worth it 
Many thanks.

A few hours ago I requested the client name for the window title; and there it is already. Thumbs up!
