### ISSUE TITLE
Two bugs

### ISSUE THREAD

**Issue by zhangbo8418** [rustdesk/rustdesk#4469]
### Bug Description

Two bugs: 1. There is no input box in the chat window and the content box is not centered. 2. When the chat window is opened and then trying to close the remote connection, a glitch occurs.

### How to Reproduce

Watch the video demo below.

### Expected Behavior

normal display.

### Operating system(s) on local side and remote side

Android -> Android 

### RustDesk Version(s) on local side and remote side

1.20

### Screenshots

https://github.com/rustdesk/rustdesk/assets/46797568/8c62da07-433f-419e-bec2-14251d84bbe4

**Comment by rustdesk** [comment]
@NicKoehler could you take a look? it seems related to latest code change.

**Comment by NicKoehler** [comment]
I don't know about the keyboard, I know how to fix the not centered chat

**Comment by rustdesk** [comment]
As for 2), @NicKoehler could you help write some code to close the chat window if it is open before close connection. I guess it can fix the problem.

**Comment by NicKoehler** [comment]
I'll try my best

**Comment by rustdesk** [comment]
👍

**Comment by rustdesk** [comment]
BTW, we updated to flutter 3.10.1 today.

**Comment by NicKoehler** [comment]
@rustdesk Having issues compiling now

![immagine](https://github.com/rustdesk/rustdesk/assets/53040044/d3a0414c-721f-4d13-a05a-7938b72c17c6)

**Comment by rustdesk** [comment]
yes, aom is newly added, you need to download precompiled libs again like last time.

**Comment by zhangbo8418** [comment]
> close as fix merged. Our CI on android has some problem, you may not get new build lately.
> 
> `2.` can not be reproduced, it may be specific to your phone, or it is fixed by new Flutter 3.10.1.

<img width="303" alt="wireframe" src="https://github.com/rustdesk/rustdesk/assets/46797568/d55cb786-2470-429d-be9e-17b0f7b327a8">

No sure if it's my phone issue, but I think it's better to check and close the chat window before closing the connection.

https://github.com/rustdesk/rustdesk/assets/46797568/1a5d36e8-b3b7-486c-ab03-b5301bffbe8e

**Comment by rustdesk** [comment]
@NicKoehler 

![image](https://github.com/rustdesk/rustdesk/assets/71636191/bcf8eb20-b37b-45cf-9b0b-9a5e305b7720)

**Comment by rustdesk** [comment]
@21pages follow up this issue.

- [ ] add border to message input box
- [ ] remove padding <img width="303" alt="wireframe" src="https://github.com/rustdesk/rustdesk/assets/71636191/154098dd-f970-4599-9909-6ed27ecf3db0">
- [ ] close message box before connection close.

**Comment by NicKoehler** [comment]
@rustdesk 
Sorry, as I currently have no time to do this

**Comment by rustdesk** [comment]
@NicKoehler no worries. We will follow up.

**Comment by zhangbo8418** [comment]
And it didn't solve the problem. It caused keyboard malfunction when the confirmation window popped up.
