### ISSUE TITLE
Can't login on Windows 10 when privacy mode is turned on

### ISSUE THREAD

**Issue by Karbust** [rustdesk/rustdesk#4481]
### Bug Description

Can't login on Windows when privacy mode is on, it's like the image is locked but the keystrokes are being registered. As soon as I disable it, I can see that I'm writing the password.

It happens when either I turn on the Privacy Mode on the lock screen or when privacy mode was used on the previous session and it got turned on automatically.

### How to Reproduce

Turn on Privacy Mode when on login screen of Windows 10.

### Expected Behavior

Being able to see that I'm inputting the password.

### Operating system(s) on local side and remote side

Windows 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0 Nightly -> 1.2.0 Nightly 

### Screenshots

https://github.com/rustdesk/rustdesk/assets/20361229/767dfa1f-f0d1-440e-8001-8227f1cbf2dc

**Comment by rustdesk** [comment]
Current privacy is going to be phased out, wait for our new implementation please.

@fufesou
