### ISSUE TITLE
Broken link on README.rd

### ISSUE THREAD

**Issue by generalworksinc** [rustdesk/rustdesk#449]
**Describe the bug you encountered:**
Broken link on README.rd
[set up your own](https://rustdesk.com/blog/id-relay-set/)
...

**What did you expect to happen instead?**
It displays correct page.

...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

**Comment by rustdesk** [comment]
Thanks, fixed, https://github.com/rustdesk/rustdesk/commit/c0af51e1bdc7eda05d494e6c37bcfba9d4bd296b
