### ISSUE TITLE
macOS - RustDesk Application Screens stays black on startup on server with 1.2.0 but works with 1.1.9 under Mac OSX 

### ISSUE THREAD

**Issue by mirogl** [rustdesk/rustdesk#4490]
### Bug Description

Hi,
I habe a Mac Mini 2012, where I have currently macOS Monterey running with OpenCore Legacy Patcher including PatchHD4000, since macOS Monterey  is not official supported on Mac Mini 2012.
I run RuskDesk on this machine as a server, where I connect from a Windows machine to it.
With RuskDesk 1.1.9 everything worked, but with 1.2.0 i tried many diefferent nightly builds and had always the problem, that the application screen form RuskDesk at start is completly black - therefore I can't make any configuration on it.
I thought, that it was to the nightly build nature - but since it is still not working since months, I created this ticket, since it seems not to be a known bug.

### How to Reproduce

Start RuskDesk on a Mac Mini 2012 with macOS Monterey running with OpenCore Legacy Patcher including PatchHD4000 -> Application Screen stays black. Important - the application screen is black, before I connect with anything - so i see it on the monitor black on the mac mini itself.

### Expected Behavior

The RustDesk Application screen on the server (connected to an external monitor via HDMI) should be not black but visible

### Operating system(s) on local side and remote side

Windows 11 -> macOS Monterey 

### RustDesk Version(s) on local side and remote side

1.2.0  (latest nightly build) -> 1.2.0 (latest nightly build) 

### Screenshots

RustDesk 1.2.0
![RustDesk](https://github.com/rustdesk/rustdesk/assets/46027543/21d5a155-215c-4e91-8695-f05bcde09345)

RustDesk 1.1.9
![RustDesk119](https://github.com/rustdesk/rustdesk/assets/46027543/e8b4b40f-f7cf-4351-a0d8-d5122fc4298c)

**Comment by rustdesk** [comment]
dup with https://github.com/rustdesk/rustdesk/issues/3900, nightly build is rewritten with flutter, i can only wish google's flutter fix this problem. @Kingtous

**Comment by mirogl** [comment]
Hi - just as an info. After upgrading to macOS Ventura the black windows was not there anymore.

**Comment by ssssamstrup** [comment]
Hi @mirogl did you update to Ventura using OCLP as well? I'm experiencing this issue and would like to solve it.

**Comment by mirogl** [comment]
> Hi [@mirogl](https://github.com/mirogl) did you update to Ventura using OCLP as well? I'm experiencing this issue and would like to solve it.

Yes - it was Ventura with OCPL - but currently I'm. on macOS Sonoma and RuskDesk will not even start there. So I gave up on using RuskDesk and use the native VNC Server.

Good Luck
