### ISSUE TITLE
unable to install on ubuntu 22.04LTS

### ISSUE THREAD

**Issue by Nicon4454** [rustdesk/rustdesk#4491]
### Bug Description

When trying to install it reports unable to install due to dependencies ver 1.1.9

### How to Reproduce

try to install it

### Expected Behavior

for it to install

### Operating system(s) on local side and remote side

ubuntu 22.04 LTS

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![Screenshot from 2023-05-27 14-47-17](https://github.com/rustdesk/rustdesk/assets/3824774/e9bf8d00-d029-46b0-abf3-7d67b88a5038)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/nightly

**Comment by Nicon4454** [comment]
still can not install. not sure where to find logs but this is the error i got. using [rustdesk-1.2.0-x86_64.deb](https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64.deb)
![Screenshot from 2023-05-27 22-12-16](https://github.com/rustdesk/rustdesk/assets/3824774/c7cc34a5-e72f-42d4-a2e6-8cf9478dbb9a)
