### ISSUE TITLE
Error while downloading from NAS disks (upload works fine)

### ISSUE THREAD

**Issue by Weazwon** [rustdesk/rustdesk#4492]
### Bug Description

When trying to download and upload files to remote machine's internal disks it works fine. e.g. local disk C
But when you try to download from disks that are connected to remote PC from NAS server it gives an error
Although it allows to upload files to NAS disks but gives an error when you hit download on files
Transfer File menu shows all disks that are connected to remote PC and you can browse folders that are located on NAS disks and it shows files
Disks are connected to remote PC from TrueNAS Core server

### How to Reproduce

Connect a disk from TrueNAS system (or another NAS or not internal/local disk) to remote PC
Select remote PC and choose Transfer File option
Choose some file from a not internal/local (NAS) disk and press download
Download gives an error

### Expected Behavior

When selecting a file It should download it the same way it downloads from internal disks

### Operating system(s) on local side and remote side

Windows 10 ; Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0 Nightly ; 1.2.0 Nightly

### Screenshots

![rustdesk_oIpJhxqCkL](https://github.com/rustdesk/rustdesk/assets/133371606/2859f43d-9e05-4725-8081-71e79a621969)

**Comment by rustdesk** [comment]
#3501

**Comment by grummbeer** [comment]
@Weazwon 

Linux > Windows 10

- send to a net drive - OK
- receive from a net drive - OK

files are in place and not broken. 

Both, send and receive to a windows network drive works as expected.

Could you confirm this is still an issue at your site?

**Comment by grummbeer** [comment]
> I can not test Windows > Windows, could you do?

I has firing up a second Windows (VM) to test this, works

**Comment by rustdesk** [comment]
Thanks @grummbeer
