### ISSUE TITLE
Remote's cursor shape changes to cross and never turns back into arrow

### ISSUE THREAD

**Issue by mtelis** [rustdesk/rustdesk#4498]
### Bug Description

Remote cursor changes to cross when I'm viewing remote document (it's correct behavior) but doesn't change back into arrow when I close/minimize the document.

### How to Reproduce

Connect to remote and open a program that would change mouse cursor shape,

### Expected Behavior

Mouse cursor shape should match those on the remote.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 7

### RustDesk Version(s) on local side and remote side

1.2.0 both local and remote, the latest nightly build

### Screenshots

https://github.com/rustdesk/rustdesk/assets/335301/00e86ef0-0666-44d2-b03b-fbee0435de5e

**Comment by rustdesk** [comment]
#763 let me know you have the same issue if controling win 10.

**Comment by mtelis** [comment]
No, Win10 -> Win10 works as it should

**Comment by juangea** [comment]
We have this problem controlling Win10 too

**Comment by codeyoulateralligator** [comment]
Same problem with RustDesk 1.2.3

Win10->Win10
