### ISSUE TITLE
Could rustdesk provide directly connect in lan without relay server?

### ISSUE THREAD

**Issue by mokeyish** [rustdesk/rustdesk#45]

**Comment by rustdesk** [comment]
Most of case, we can make direct connection in lan. but we do see rustdesk failed sometimes, e.g. in different subnet, or configured with different gateway, or some firewall reasons, or some unknown reasons.

**Comment by rustdesk** [comment]
if you can figure out why rustdesk failed, maybe can help me figure out better solution, e.g. multicast

**Comment by mokeyish** [comment]
> if you can figure out why rustdesk failed, maybe can help me figure out better solution, e.g. multicast

Considering about different subnet is too diffcult. I think it is enough just like Windows Remote Desktop, which can set up a gateway for connecting over different subnet .

P2P may be another way. `libp2p` provide rust implemention  https://libp2p.io/.

**Comment by rustdesk** [comment]
> > if you can figure out why rustdesk failed, maybe can help me figure out better solution, e.g. multicast
> 
> Considering about different subnet is too diffcult. I think it is enough just like Windows Remote Desktop, which can set up a gateway for connecting over different subnet .
> 
> P2P may be another way. `libp2p` provide rust implemention https://libp2p.io/.

looking forward to your contribution

**Comment by rustdesk** [comment]
As a simple solution, will add direct link via IP in 1.1.6.

**Comment by mokeyish** [comment]
> As a simple solution, will add direct link via IP in 1.1.6.

That's great!!! I'll try later.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/113

**Comment by ceewanna** [comment]
From my experience so far, direct connection can be done only when firewall on remote machine is disabled. I have tried allow in/out of various ports 21115:21119 and 21116 but there has been no success so far. I also tried direct IP with port 21116 allow in on remote machine. That doesn't work for me either.
