### ISSUE TITLE
Can't multiple windows overlap links on the windows side? Why is each link a separate window?

### ISSUE THREAD

**Issue by ztdacq1** [rustdesk/rustdesk#4509]
### Bug Description

I saw that the mac section of the official website can be linked with multiple windows. I don’t know if there is such a function on the windows side, because I didn’t find the option to link with multiple windows from the top options of the controlled terminal. Every link pops up. A separate window is not friendly to multi-window links.

### How to Reproduce

![image](https://github.com/rustdesk/rustdesk/assets/100158620/4da6a693-4e2c-4499-a47c-9a59656dbc88)

![image](https://github.com/rustdesk/rustdesk/assets/100158620/52bcd150-7c42-49bf-a753-20f3c92829e5)

### Expected Behavior

I hope that the windows side can overlap links in multiple windows

### Operating system(s) on local side and remote side

windows10

### RustDesk Version(s) on local side and remote side

1.1.9-1.1.9

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/100158620/4da6a693-4e2c-4499-a47c-9a59656dbc88)

![image](https://github.com/rustdesk/rustdesk/assets/100158620/52bcd150-7c42-49bf-a753-20f3c92829e5)

**Comment by rustdesk** [comment]
@DrFunkenbreakz thanks for your answer
