### ISSUE TITLE
All Connections are unencrypted

### ISSUE THREAD

**Issue by Swiftgti** [rustdesk/rustdesk#451]
Hi since today all connections made to all my computers are unencrypted, this problem started today.
The issue is with all the pc´s I connected to it, all running windows (7, 10 and 11) with official version 1.1.8

Thanks

**Comment by rustdesk** [comment]
Upgrade to https://github.com/rustdesk/rustdesk/releases/download/tmp/rustdesk-1.1.9-putes.exe please.

**Comment by 3por2** [comment]
Hi.
Under Ubuntu 20.04 LTS the problem with the unencrypted connection also occurs. Here we also use the official version 1.1.8.

Thank you very much.

**Comment by rustdesk** [comment]
We will publish 1.1.9 tomorrow. To enhance the encryption, we upgraded the server program.

**Comment by 3por2** [comment]
> We will publish 1.1.9 tomorrow. To enhance the encryption, we upgraded the server program today.

Perfect. Thank you very much.

**Comment by ChrisIossa** [comment]
Is there any update on when the 1.1.9 release will be published? I am also seeing this issue.

**Comment by chenjianhua** [comment]
In 1.1.9, this issue has been resolved.

**Comment by VikingKing** [comment]
I'm running 1.1.9 on both windows and Mac and still get unencrypted connections.

**Comment by VikingKing** [comment]
Ah... The docker "latest" images is 1.1.5. Could you please fix that?

**Comment by rustdesk** [comment]
https://rustdesk.com/docs/en/self-host/install/#key

**Comment by notramo** [comment]
Could you provide more details on what was the issue? This is not how security vulnerabilities are managed.
It is possible that it was an intentional backdoor that got noticed, and the devs simply removed it in the next release.
