### ISSUE TITLE
Cant't stop service on Nightly 

### ISSUE THREAD

**Issue by GMYXDS** [rustdesk/rustdesk#4521]
### Bug Description

when exiting the program
Click on the tray icon in the lower right corner
Out of service
But in the task manager, the rustdesk service is still not stopped

### How to Reproduce

Click on the tray icon in the lower right corner
Click to stop service

### Expected Behavior

rustdesk completely stopped
Services included in the background

### Operating system(s) on local side and remote side

WIndows 10

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/42828788/61205442-91d5-4917-93fc-48a8e9214d51)

**Comment by 21pages** [comment]
It is designed to refuse to accept connections and disconnect all existing connections.

**Comment by GMYXDS** [comment]
> It is designed to refuse to accept connections and disconnect all existing connections.

I got it .
But sometimes I want quit rustdesk completely.
So should there be an exit button?

**Comment by 21pages** [comment]
Maybe in the future, now you can use task manager.

**Comment by GMYXDS** [comment]
Thanks, got it.

> Maybe in the future, now you can use task manager.
