### ISSUE TITLE
Cannot type on remote rustdesk machine. (keyboard)

### ISSUE THREAD

**Issue by dgleba** [rustdesk/rustdesk#4527]
### Bug Description

Sometimes I cannot type anything in the remote. I can use the mouse.

### How to Reproduce

Try to type something in the remote.

### Expected Behavior

The typing shows up on the remote.

### Operating system(s) on local side and remote side

Win10 or Ubuntu > Ubuntu 20.04

### RustDesk Version(s) on local side and remote side

1.1.9 > 1.1.9

### Screenshots

NA

### Additional Context

local is in Canada. 
remotes are in:
- Canada with english(US) keyboard layout.
- Israel ( I will ask keyboard layout )

**Comment by rustdesk** [comment]
#1547

**Comment by dgleba** [comment]
Thank you for this. I looked for other similar issues, but I didn't see this one.
