### ISSUE TITLE
The number will be misplaced when entering the remote ID

### ISSUE THREAD

**Issue by SamGenTLEManKaka** [rustdesk/rustdesk#4529]
### Bug Description

The number will be misplaced when entering the remote ID

### How to Reproduce

Just enter the remote ID and it will reappear

### Expected Behavior

Just enter the remote ID and it will reappear

### Operating system(s) on local side and remote side

Windows server2016 && Windows server2019

### RustDesk Version(s) on local side and remote side

nightly

### Screenshots

https://github.com/rustdesk/rustdesk/assets/24671601/e3cb3483-c771-4cfa-8214-2ebdedd01e38

**Comment by Apashh** [comment]
Same problem with nightly on Windows 11 ! ;)

**Comment by rustdesk** [comment]
Interesting, but not on my windows. Your font also has problem.

**Comment by rustdesk** [comment]
Which day's nightly?

**Comment by SamGenTLEManKaka** [comment]
> Which day's nightly?

There's a problem with the latest one

**Comment by rustdesk** [comment]
I jsut reproduced this issue when turning on IME, no problem without IME.

**Comment by rustdesk** [comment]
close as fix merged
