### ISSUE TITLE
External keyboard control problem on iPadOS

### ISSUE THREAD

**Issue by joezhouchenye** [rustdesk/rustdesk#4530]
### Bug Description

If external keyboard is disabled, touch the show keyboard button and everything works fine because it uses the native iPadOS input method.

However, when external keyboard is enabled, it seems to use the host pc's native input method. Everytime I press a key, two keys will be send once connection is established. If I touch the show keyboard button in this case, two keys problem is gone, but I was not able to change the input method or switch between lower and upper cases (I can switch to upper case, but cannot switch back using shift or caps-lock).

### How to Reproduce

Use external keyboard with iPad.

### Expected Behavior

External keyboard should work.

### Operating system(s) on local side and remote side

Both iPadOS 16.5 -> Ubuntu 22.04 and iPadOS 16.5 -> Windows 10

### RustDesk Version(s) on local side and remote side

I tried both 1.1.10 -> 1.1.9 and 1.1.10 -> 1.2.0

### Screenshots

I will upload later.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/907 but we have no ios nightly version yet, https://github.com/rustdesk/rustdesk/discussions/4516
