### ISSUE TITLE
Rustdesk is always using relayed connection

### ISSUE THREAD

**Issue by stevenmccormack** [rustdesk/rustdesk#4531]
### Bug Description

I am facing an issue similar to https://github.com/rustdesk/rustdesk/issues/4348. After upgrading to version 1.2 I am always getting a relayed connection (also if hosts are on same site).
My setup has 2 sites with client PCs as well as a central datacenter with my self hosted server. All sites are connected via VPN.
After reading issue 4348 I checked RustDesk2.toml and found that on all machines I have the following in `/root/.config/rustdesk/RustDesk2.toml` :
```
nat_type = 2
```
In 1.19 nat_type was 1. If I manually set nat_type to 1 in the config, it will revert to 2 after restart / connection attempt.
I checked all firewalls involved but could not see any blocked traffic between the clients and the server.

### How to Reproduce

I am unsure on how to reproduce

### Expected Behavior

Direct connection as with 1.19

### Operating system(s) on local side and remote side

local: Debian 12  remote: Debian 12 / Ubuntu 22.04

### RustDesk Version(s) on local side and remote side

1.2.0 (2023-05-05 00:26)

### Screenshots

![grafik](https://github.com/rustdesk/rustdesk/assets/61007020/5310f764-69cc-4008-b38c-dfeec986a652)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4348#issuecomment-1548176891
