### ISSUE TITLE
macOS connection shows image but overlay `Connected, waiting for image…` never vanishes 

### ISSUE THREAD

**Issue by foss-** [rustdesk/rustdesk#4533]
### Bug Description

macOS 13.4
Rustdest Nightly 2023-06-02

connected to

macOS 12.6.5
Rustdest Nightly 2023-06-02

RustDesk shows image but overlay `Connected, waiting for image…` never vanishes.

### How to Reproduce

Create RustDesk connection, enter password, a connection is created with dark overlay and dialog that does not vanish.

### Expected Behavior

Once connection is made, hide dialog.

### Operating system(s) on local side and remote side

macOS

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

![1](https://github.com/rustdesk/rustdesk/assets/5708172/2ee0380e-2265-4250-9aaa-713b60b0d7c1)

**Comment by rustdesk** [comment]
@21pages

**Comment by fabrififi** [comment]
same issue +1

**Comment by rustdesk** [comment]
@foss- @fabrififi does this happen every time?

**Comment by lws-hosting** [comment]
Yes it append every time, waiting some hours and dialog stay here.

If i move some window on the MacOS, i can see in the backgroup they are moving too

**Comment by rustdesk** [comment]
Interesting， I can not reproduce

**Comment by lws-hosting** [comment]
If it can help, in my case i use a self hosted server

`# ./hbbr -V    
hbbr 1.1.7-1
# ./hbbs -V
hbbs 1.1.7-1`

**Comment by zhaixuepan** [comment]
same issue +1

But my mac mini m1 remote has no display

**Comment by zhaixuepan** [comment]
![image](https://github.com/rustdesk/rustdesk/assets/15258081/afdccb88-54e2-4bbd-8411-2691850dda94)

**Comment by larryqiann** [comment]
Same problem on macOS Ventura M1, connecting from Android. Using TeamViewer, it looks like the RustDesk session is established, but there is no video and no input forwarding to the remote system.

**Comment by 21pages** [comment]
@larryqiann It is the first connection after the system restarts or the connection after the first connection.

**Comment by larryqiann** [comment]
It is a problem on all connections, since updating no connections work

**Comment by 21pages** [comment]
https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64_log_waiting_for_image_to_tmp_log_txt.dmg

This program will print log to `/tmp/log.txt`.

**Comment by lws-hosting** [comment]
Your test build won't start here :

```
% /Applications/RustDesk.app/Contents/MacOS/RustDesk 
dyld: Library not loaded: @rpath/FlutterMacOS.framework/Versions/A/FlutterMacOS
  Referenced from: /Applications/RustDesk.app/Contents/MacOS/RustDesk
  Reason: no suitable image found.  Did find:
	/Applications/RustDesk.app/Contents/MacOS/../Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS: code signature in (/Applications/RustDesk.app/Contents/MacOS/../Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
	/Applications/RustDesk.app/Contents/MacOS/../Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS: code signature in (/Applications/RustDesk.app/Contents/MacOS/../Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
zsh: abort      /Applications/RustDesk.app/Contents/MacOS/RustDesk
```

**Comment by 21pages** [comment]
Ok, thanks anyway

**Comment by dieskim** [comment]
Same issue here..any way I can help debug?

**Comment by verymilan** [comment]
Same for me, using the current nightly build.

**Comment by dieskim** [comment]
I was able to get the "Connected, waiting for image.." to not show up by disabling "Enable Keyboard/Mouse" under the Permission settings...hope this helps to figure this out

![Screenshot 2023-06-08 at 9 04 46 AM](https://github.com/rustdesk/rustdesk/assets/9603625/59269f65-7729-4cc9-b7d0-883c7f001f84)

**Comment by rustdesk** [comment]
@dieskim Thanks. Can we connect to your machine for debugging? We still can not reproduce.

**Comment by rustdesk** [comment]
> Can we connect to your machine for debugging?

@zhaixuepan

**Comment by 21pages** [comment]
@dieskim If Enabling "Enable Keyboard/Mouse", Each time it is "Connected, waiting for image.."? My Email is pages21@163.com

**Comment by dieskim** [comment]
yeah every time

**Comment by 21pages** [comment]
Ok, should have something to do with "Enable Keyboard/Mouse"

**Comment by rustdesk** [comment]
@dieskim can you try out disable audio instead of keyboard?

**Comment by dieskim** [comment]
I tried them all one by one yes - only keyboard / mouse caused the issue - I can enable keyboard and mouse after the connection is made and then it works fine

**Comment by rustdesk** [comment]
@dieskim Good finding.

**Comment by zhaixuepan** [comment]
> > Can we connect to your machine for debugging?
> 
> @zhaixuepan

Yes, how can I cooperate? Send us the ID and password, but I use a custom server？

**Comment by zhaixuepan** [comment]
![image](https://github.com/rustdesk/rustdesk/assets/15258081/7418e9ac-aac0-4f47-8588-a88915a7cd00)
win11-->mac mini m1 ，都是构建的最新版本，禁用键鼠和音频，问题依旧。
![image](https://github.com/rustdesk/rustdesk/assets/15258081/fe393b52-dcf5-453c-8f39-0c659a35d427)
@rustdesk

**Comment by rustdesk** [comment]
@zhangbo8418 can you remember when did you start to see such problem?

**Comment by foss-** [comment]
Connecting from Android 1.1.10-1 to mac 1.2.0 (2023-06-08) was not a problem and even mouse was controllable.
Connecting from mac to Android was not a problem.

However when connecting from one mac to another mac the issue is 100 % reproducible. Maybe you tested a different connection setup and thus were unable to reproduce?

**Comment by rustdesk** [comment]
Thanks, maybe because I always run with debug. Let me download nightly build and try more times.

**Comment by rustdesk** [comment]
I reproduced the problem 100%, and put a fix, now it works on my machines. 
This issue occured after uprading to Flutter 3.10 from 3.7, `await (messge in stream_sink)` stops to work after a while, but `stream_sink.listen` can always work.
A similar issue https://github.com/fzyzcjy/flutter_rust_bridge/issues/1031

**Comment by larryqiann** [comment]
Latest build fixes this problem for me. Need to update both client and host for changes to take effect. Thank you!!

**Comment by lws-hosting** [comment]
I confirm that updating both client and host from nightly fix the problem, nice work

**Comment by larryqiann** [comment]
There is one remaining bug that it seems like once the connection ends, it is necessary to close the client app and reopen it, otherwise the problem will return.

**Comment by 21pages** [comment]
@larryqiann When reopen it, what's the dialog there, still "Connected, waiting for image" ?

**Comment by larryqiann** [comment]
Yes, still that dialog

**Comment by larryqiann** [comment]
No, now it just shows "Connecting", but on the host side it is already connected

**Comment by rustdesk** [comment]
This one I do can not reproduce.

**Comment by rustdesk** [comment]
> There is one remaining bug that it seems like once the connection ends, it is necessary to close the client app and reopen it, otherwise the problem will return.

This one I do can not reproduce. @lws-hosting could you confirm?

**Comment by larryqiann** [comment]
Android connecting to macOS, both on same version, the latest

**Comment by rustdesk** [comment]
Reproduced.

**Comment by rustdesk** [comment]
@fzyzcjy do you have any idea? 
Stream does not work well since we upgraded Flutter from 3.7 to 3.10. 
I changed `await (messge in stream_sink)` to `stream_sink.listen` (https://github.com/rustdesk/rustdesk/commit/a9098960d1a97d5ef9da7f7af2e6e0eda64b6a48), it works on desktop, but still some problems on android.

**Comment by rustdesk** [comment]
@larryqiann please try out the new nightly build.

**Comment by foss-** [comment]
Tested todays build and can not reproduce Anddroid to Mac problems. Connection worked fine.
Mac to Mac also worked fine. The issue mention where on a reconnect an issue happens is not reproducible for me.

Confirming this is no longer a problem and closing. I think it is best for remaining issues to fill a new case as the original problem has been addressed.

Big kudos to @rustdesk and @21pages for your work.

**Comment by zhangbo8418** [comment]
> @larryqiann请尝试新的夜间构建。

Why is the remote control mouse for Mac now a dot instead of an arrow?

**Comment by rustdesk** [comment]
> Why is the remote control mouse for Mac now a dot instead of an arrow?

https://github.com/rustdesk/rustdesk/pull/4605
