### ISSUE TITLE
resource manager crashed with autostart of rustdesk, really serious..

### ISSUE THREAD

**Issue by MMMMMoris** [rustdesk/rustdesk#454]
latest version from github installed in my PC ,win11, as a client
after i successfully ran rustdesk with my own relay server, i shut it down and tried to run for a second time,
however, all of a sudden, my whole resource manager(explorer.exe)was down, the screen went black and the system stayed unresponsive.
the other day, i try to open my resource manager to access my hard disk, and it crashed again, the case is actually the same like the first time this problem occurred, however, a lot more severe. Well, i found something different, the rustdesk i didn't open before my resource manager crash just showed up itself, which means this program run automatically without my request and permission, and crashed my resource manager and interrupted my work... this is a very serious problem...
![IMG_20220420_195003](https://user-images.githubusercontent.com/63332824/164235371-b82b9d8d-b7f3-40a0-9c2f-5a8e11cbbfe4.jpg)

when the system is down, it is just like the picture upon

![屏幕截图 2022-04-20 205827](https://user-images.githubusercontent.com/63332824/164235912-728be13b-7893-4ae5-adad-9c8235278bf1.png)
and this is how it looks like after i open another explorer.exe, i got two rustdesks down there in my taskbar, but one of it has no response when i click it. the thing is, I AM NOT EVEN USING IT WHEN MY RESOURCE MANAGER CRASHED...

**Comment by rustdesk** [comment]
We are sorry about this. Do you run RustDesk after installation or run the portable one?

**Comment by MMMMMoris** [comment]
> We are sorry about this. Do you run RustDesk after installation or run the portable one?

at the begining, i run the portable one, but i install it after i see the notice beside reconmmending me to install

**Comment by rustdesk** [comment]
You do not need to install if you only wanna control the other PC rather than being controlled. If RustDesk is installed. there will be RustDesk background process running even after you reboot your PC, the background process is used to listen on incomming connection request. The background process does not have GUI, it should not destroy your explorer. There is also a RustDesk tray process running,  you can see a RustDesk tray icon in the Windows task bar notification area. Anyway We will thoroughly check our code though we can not reproduce the problem. If you still see the problem, please uninstall RustDesk.

**Comment by MMMMMoris** [comment]
> You do not need to install if you only wanna control the other PC rather than being controlled. If RustDesk is installed. there will be RustDesk background process running even after you reboot your PC, the background process is used to listen on incomming connection request. The background process does not have GUI, it should not destroy your explorer. There is also a RustDesk tray process running, you can see a RustDesk tray icon in the Windows task bar notification area. Anyway We will thoroughly check our code though we can not reproduce the problem. If you still see the problem, please uninstall RustDesk.

Thanks a lot, I will also try to find a solution
