### ISSUE TITLE
"Scale original" is blurry depending on scroll mode and rustdesk window size. [Nightly]

### ISSUE THREAD

**Issue by po0p** [rustdesk/rustdesk#4542]
### Bug Description

When "Scale original" is selected:
Selecting scrollbar gives clean image (at least for text)
Selecting ScrollAuto makes text a little bit blurry.
Autoscroll works without blur on AnyDesk, so I'm sure there is a way to fix it :)
making Rustdesk window more than remote resolution size makes image blurry, making is smaller makes image be okay.
Host desktop resolution: 3840x2160.
Remote screen resolution: 1920x1080.

### How to Reproduce

>Select "Scale Original"
>Alternate between different scroll modes and windows sizes
>Change rustdesk window size with scrollmode = scrollbar and "scale original", from very small window to window larger than remote screen resolution

### Expected Behavior

Expecting image to be clear and non blurry at all times 👍🏻 

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0 (both nightly)

### Screenshots

1. Window size on host is ~1920x1080. So not **whole** remote window fits (as it is 1920x1080 resolution).
1.0 Scale original + **Scrollbar** -> https://imgur.com/a/SJwT6GH -> text is perfectly fine
1.1 Scale original + **ScrollAuto** -> https://imgur.com/a/bJwtwca (text becomes blurry)

2. Changing rustdesk window size on host (from very small to very big), using **Scrollbar** and **Scale Original**
2.0 Very small window -> text is fine https://imgur.com/a/b34Jv1C
2.1 Window matching remote screen size + a little bit more space at top (basically i resized rustdesk window to 1080p, then made it taller) -> text is fine https://imgur.com/a/9iK1HTk
2.2 Rustdesk window ~1-10px wider than host resolution (any amount of making it wider than remote resolution produces this for me) -> text is blurry https://imgur.com/a/6g9fZTp

**Comment by po0p** [comment]
Edit: fitting whole remote screen into rustdesk window (using "Adjust Window" under screen settings) make text and image clear and non blurry.

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
I just tested, both scrollbar/auto can have blurry text, even it is clear, it can also become blurry after moving mouse.

**Comment by rustdesk** [comment]
Another bug, when I start rustdesk, below scale original/adaptive are both unselected, I can not see scrollauto/scroolbar options, until I click on scale original or scale adaptive.

![image](https://github.com/rustdesk/rustdesk/assets/71636191/73300a8d-8c9b-46ed-8c27-1f6ebcfdc9ec)

**Comment by fufesou** [comment]
@po0p Hi, this issue should be fixed by PR 4544. It is related to https://github.com/flutter/flutter/issues/115653

PR 4544 is a workaround for now.

**Comment by po0p** [comment]
Hey @fufesou, thanks, i'll check once new nightly is released!

**Comment by rustdesk** [comment]
New build is ready.

**Comment by po0p** [comment]
![image](https://github.com/rustdesk/rustdesk/assets/68482185/cede05af-ec1c-4be9-9d6d-db2147387bf3)
@fufesou Thanks a lot. So much better!
