### ISSUE TITLE
Does not follow the system's theme

### ISSUE THREAD

**Issue by tio-trom** [rustdesk/rustdesk#4545]
### Bug Description

As the title says. Despite 99% of all applications that I use, and I tested thousands so far for our TROMjaro custom Linux distro, RustDesk does not work with the system's theme. And I wonder why. We use XFCE (thus, GTK).
![2023-06-04_22-33](https://github.com/rustdesk/rustdesk/assets/38043315/c397b90f-785f-4fed-8c0c-89d4d8e3d554)
Even the window decoration is not respected.

### How to Reproduce

Change the theme to system's theme.

### Expected Behavior

Change the theme according to the system.

### Operating system(s) on local side and remote side

Arch Linux with XFCE - kernel 6.1

### RustDesk Version(s) on local side and remote side

Version: 1.2.0

### Screenshots

![2023-06-04_22-33](https://github.com/rustdesk/rustdesk/assets/38043315/1b670e6a-479d-4d39-9503-e71ec635c225)

**Comment by rustdesk** [comment]
tracked by #3565
