### ISSUE TITLE
Waiting for image transmission

### ISSUE THREAD

**Issue by lws-hosting** [rustdesk/rustdesk#4551]
### Bug Description

Installing  nightly build on MacOS Catalina (10.15.7).

When trying to connect from Debian 11 (using nightly build too) or Windows 10 (same, nightly build) to the MacOS, resulting hangling on a message "Connected, awaiting image transmission".

In the background of this message, i can see video transmission is OK (i can see the screen of the MacOS)

### How to Reproduce

Install nightly build on both MacOS, Debian 11 and/or Windows 10 and try to connect to the MacOS from Windows nor Debian

### Expected Behavior

No message hanging

### Operating system(s) on local side and remote side

Debian 11 -> MacOS 10.15.7

### RustDesk Version(s) on local side and remote side

1.2 -> 1.2

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/108014521/9cfac6a2-7c14-4a1e-9053-bcc5e6e1d4a3)

**Comment by 21pages** [comment]
Thanks, it has been reproduced.

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/4533

**Comment by rustdesk** [comment]
Does this happen every time?
