### ISSUE TITLE
GDK_IS_PIXBUF or something, idk i'm too sleepy （Artix Linux）

### ISSUE THREAD

**Issue by DNDEBUG** [rustdesk/rustdesk#4565]
### Bug Description

(rustdesk:11613): GdkPixbuf-CRITICAL **: 15:32:56.055: gdk_pixbuf_copy: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(rustdesk:11613): Gdk-CRITICAL **: 15:32:56.055: gdk_cursor_new_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

### How to Reproduce

./rustdesk-1.2.0-x86_64.AppImage
try to connect
crash
also happens to 1.1.9

### Expected Behavior

not crash

### Operating system(s) on local side and remote side

Artix Linux

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

wut

### Additional Context

it just started happening out of nowhere, no explanation

**Comment by rustdesk** [comment]
tracked by #3565
