### ISSUE TITLE
Touchpad scrolling issues

### ISSUE THREAD

**Issue by xboxhaxorz** [rustdesk/rustdesk#4567]
### Bug Description

Using touchpad to line scroll on client is scrolling aggressively/ too far, using mouse on host scrolls normally ie; just a few lines

### How to Reproduce

Use touchpad for client

### Expected Behavior

Aggressive scrolling

### Operating system(s) on local side and remote side

Win 10

### RustDesk Version(s) on local side and remote side

Win 11

### Screenshots

https://github.com/rustdesk/rustdesk/assets/80492476/15c70969-d44c-4184-8d88-00a0d610afef

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2655
