### ISSUE TITLE
not possible to use local keyboard for android phones

### ISSUE THREAD

**Issue by mr2017x** [rustdesk/rustdesk#4571]
### Bug Description

Hello colleagues,

i wanted to remote help a private android phone, works so far. but i cannot input anything by my local windows keyboard - it's not transfered to android phone. which means i need to click each letter on androids user keyboard...that's a hazzle...

### How to Reproduce

every connection to various android phones.

### Expected Behavior

inputs by local keyboards are transferred to androids phones

### Operating system(s) on local side and remote side

Windows 10,x86, standard - android 12

### RustDesk Version(s) on local side and remote side

most up2date 1.1.9

### Screenshots

-

**Comment by rustdesk** [comment]
#3556
