### ISSUE TITLE
Webclient build with newest rustdesk version fails

### ISSUE THREAD

**Issue by JelleBuning** [rustdesk/rustdesk#4579]
### Bug Description

Trying to use the rustdesk master branch instead of jellebuning/fix_build in the current build documentation: https://rustdesk.com/docs/en/dev/build/web/

Following the instructions gets you pretty far, only the last step fails. This results in the following output:
![image](https://github.com/rustdesk/rustdesk/assets/37436672/de601fb0-9b77-43f7-88c0-8e099d07099c)

### How to Reproduce

git clone https://github.com/rustdesk/rustdesk.git

cd flutter/web/js
npm install ts-proto
npm install vite@2.8
npm install yarn -g
npm install typescript -g
npm install protoc -g
yarn build

cd ..

wget https://github.com/rustdesk/doc.rustdesk.com/releases/download/console/web_deps.tar.gz
tar xzf web_deps.tar.gz

cd ..

flutter run -d chrome

### Expected Behavior

executing the 'flutter run -d chrome' should start a chrome instance with the webclient running.

### Operating system(s) on local side and remote side

Windows 10 -> _

### RustDesk Version(s) on local side and remote side

1.1.9 -> _

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/37436672/04e77384-5583-45bd-b7b1-76fd3ffb0aa2)

**Comment by rustdesk** [comment]
#763

**Comment by JelleBuning** [comment]
I don't think you should close this issue, you're saying the web build already a detailed tutorial. well it does, but i had to completely rewrite it for it to work. The web instructions do work, however it currently uses a branch based on the rustdesk branch from a year ago. In addition, there is no CI present for web right?
