### ISSUE TITLE
ctrl+tab shortcuts doesn't work in controlled ubuntu server 

### ISSUE THREAD

**Issue by hengfei-wang** [rustdesk/rustdesk#458]
**Describe the bug you encountered:**

I use mac to control a ubuntu server. I set ctrl+tab in server to switch applications. But it doesn't work.

**What did you expect to happen instead?**

I have checked whether 'ctrl+tab' shortcut is occupied on my mac. It isn't occupied. So I expect this shortcut should work on the server.

**How did you install `RustDesk`?**

---GitHub release

**RustDesk version and environment**

1.1.8

**Comment by chenjianhua** [comment]
I also had the same problem, ctrl was intercepted by mac.

**Comment by rustdesk** [comment]
Can you try out https://github.com/rustdesk/rustdesk/releases/tag/1.1.9?

**Comment by chenjianhua** [comment]
> Can you try out https://github.com/rustdesk/rustdesk/releases/tag/1.1.9?
In 1.1.9, this issue has been resolved.

**Comment by hengfei-wang** [comment]
I have tried 1.1.9. But I found I cannot use my keyboard even though I enable mouse and keyboard. And cursor location seems wired. The cursor does not focus on the position where it is but another postion which is close to original position.

**Comment by hengfei-wang** [comment]
When I returned back to 1.1.8, I can use keyboard again. Wired....

**Comment by rustdesk** [comment]
> When I returned back to 1.1.8, I can use keyboard again. Wired....

Ubuntu version?

**Comment by hengfei-wang** [comment]
> 

Ubuntu version: 20.04
Gnome: 3.36.8

**Comment by grummbeer** [comment]
@hengfei-wang still an issue with the nightly? https://github.com/rustdesk/rustdesk/releases/tag/nightly
A lot of keyboard issues are fixed #1547

**Comment by rustdesk** [comment]
close as no response
