### ISSUE TITLE
Tray bar - "Open" and "Exit" not translated

### ISSUE THREAD

**Issue by bovirus** [rustdesk/rustdesk#4583]
### Bug Description

In tray bay there are two options

- Open
- Exit

Please add these two strings to language file.
The program is multilanguage and is not so good to have them in english.

### How to Reproduce

Check on tray bar

### Expected Behavior

To have these strings translated.

### Operating system(s) on local side and remote side

Windows 10 22H2 64bit italian

### RustDesk Version(s) on local side and remote side

1.20 beta 07.06.2023

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/1262554/25f30e09-ecd9-451b-9e65-2b824a307004)

**Comment by rustdesk** [comment]
No hurry.

**Comment by bovirus** [comment]
@rustdesk 

Why "not hurry"?
Is not so a big job to fix it and you will have no mix of english/not english GUI.
Please leave ticket open until we'll fix it.

**Comment by rustdesk** [comment]
Because I may change open/exit soon.
