### ISSUE TITLE
[Ubuntu 22.04.2] App not saving any changes to the settings

### ISSUE THREAD

**Issue by IanRawz** [rustdesk/rustdesk#4593]
### Bug Description

A few days ago I installed RustDesk for the first time on my Ubuntu 22.04.2 LTS machine. Performance wasn't particularly good, so I installed the server shortly thereafter as well. That's when I noticed that the app wasn't saving any changes to the settings. I Added the IP & key of the server to the settings, but after restarting ubuntu, any changes were gone. 

### How to Reproduce

1. Install app (from webserver or github)
2. Make changes to the settings
3. Restart app/pc

### Expected Behavior

Settings should be saved

### Operating system(s) on local side and remote side

Ubuntu 22.04.2 LTS

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

-

**Comment by rustdesk** [comment]
it is x11 or wayland?

**Comment by IanRawz** [comment]
Initial install was on wayland. Switched to x11 and reinstalled rustdesk. Seems to be working now.
