### ISSUE TITLE
Cursor stuck on Windows (drag state not change)

### ISSUE THREAD

**Issue by riyadist** [rustdesk/rustdesk#4601]
### Bug Description

Cursor stuck and can not control the window edges

### How to Reproduce

when I click drag

### Expected Behavior

I need to have cursor control 

### Operating system(s) on local side and remote side

windows 11

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

https://github.com/rustdesk/rustdesk/assets/71445840/52561de1-ca46-4d6e-84b0-0743c5cc2ade

**Comment by rustdesk** [comment]
How about 1.1.9?

**Comment by riyadist** [comment]
I tried. Same problem

**Comment by fufesou** [comment]
@riyadist Hi, can you please try the latest nightly build?  https://github.com/rustdesk/rustdesk/releases/tag/nightly

I can not reproduce this issue.

https://github.com/rustdesk/rustdesk/assets/136106582/25e564d5-9986-49e0-b91a-2643c29ee5be

**Comment by rustdesk** [comment]
close since no response.
