### ISSUE TITLE
Multi icon in tray in ubuntu, & it's also not working

### ISSUE THREAD

**Issue by mudassar1** [rustdesk/rustdesk#4604]
### Bug Description

hi.. 
i recently installed rustdesk nightly on ubuntu desktop 22.04

i started the service & after this an icon appears in the tray. 
after some time the icon doubles (around 1 to 2 hours)
after some time one more icon added to tray (around 1 to 2 hours)

### How to Reproduce

just started the app & it happens after some time interval

### Expected Behavior

no of icon are increasing as told in description
& open is not working
exit is also not working

### Operating system(s) on local side and remote side

Ubuntu 22.04

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

& it is doubling the icon every 1 to 2 hours in the tray. 
![image](https://github.com/rustdesk/rustdesk/assets/32808751/94b1987d-20e2-46d2-8e8d-315a454bc35f)
& again after some time 
![image](https://github.com/rustdesk/rustdesk/assets/32808751/a79dc41f-0e4c-4a4f-b5d6-19530b79286a)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4602
