### ISSUE TITLE
Audio not working in macOS

### ISSUE THREAD

**Issue by larryqiann** [rustdesk/rustdesk#4606]
### Bug Description

The audio capture does not appear to work as intended. I am using Loopback for macOS (free trial download available) to create a virtual audio device to capture the system audio, and directing RustDesk to use that audio device to forward audio to the remote host.

In the past, the audio would be functional on the first connection, but garbled on the next until the RustDesk app was restarted.

On the latest nightlies, usually there will be simply no audio. The audio functioned once, but was garbled. After changing from 48000Hz to 44100 Hz, the audio never worked again even after changing back or restarting RustDesk

### How to Reproduce

Install latest Nightlies on macOS, Android, Windows
Install Loopback and create virtual device, set system output to virtual device
Connect from Android or Windows to macOS

Listen to the audio and determine whether it is audible or garbled.

### Expected Behavior

The audio should play on the remote device.

### Operating system(s) on local side and remote side

Windows 10/Android -> macOS Ventura

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0

### Screenshots

unable to screenshot audio

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3134
