### ISSUE TITLE
No autofocus when switching to rustdesk

### ISSUE THREAD

**Issue by hengfei-wang** [rustdesk/rustdesk#461]
**Describe the bug you encountered:**

cannot autofocus on rustdesk when switching from another application on mac. When I switch from another application, I must move the cursor before I can control the remote screen like inputing password.

**What did you expect to happen instead?**

I can control the remote server once I switch to it.

**How did you install `RustDesk`?**

GitHub release

**RustDesk version and environment**

1.1.8

**Comment by rustdesk** [comment]
Let's confirm the other vendors' behavior first.

**Comment by rustdesk** [comment]
fixed in master flutter version
