### ISSUE TITLE
Update in manjaro

### ISSUE THREAD

**Issue by datatux** [rustdesk/rustdesk#4618]
### Bug Description

Hi,
Impossible to update in Manjaro. this error occurs:
      |                                 wint_t
../include/vcpkg/base/strings.h:297:45: erreur: expected « , » or « ; » before « noexcept »
  297 |     std::string b32_encode(std::uint64_t x) noexcept;
      |                                             ^~~~~~~~
ninja: build stopped: subcommand failed.
==> ERREUR : Une erreur s’est produite dans build().
    Abandon…

### How to Reproduce

Using Update manager in Manjaro 
or use
yay -i rustdesk
or
yay -Suy rustdesk

### Expected Behavior

I hope it'll uptate well.

### Operating system(s) on local side and remote side

Manjaro

### RustDesk Version(s) on local side and remote side

1.1.9 -0 ->1.1.9-7

### Screenshots

![rdsesk](https://github.com/rustdesk/rustdesk/assets/136238354/67c45033-6323-4421-91c1-f8d2f0117140)

**Comment by rustdesk** [comment]
This is not maintained by us.
