### ISSUE TITLE
Mouse wheel not working on latest nightly!

### ISSUE THREAD

**Issue by FCrane** [rustdesk/rustdesk#4621]
### Bug Description

In the nightly build of June 12th, the mouse wheel is not working at all! Host and remote machine are both Windows 11. Rolling back to a previous nightly (e.g. 26.5.2023) restores mouse wheel functionality.

### How to Reproduce

Turn the mouse wheel in the remote window and no scrolling occurs in any program.

### Expected Behavior

Normal mouse wheel scrolling.

### Operating system(s) on local side and remote side

Win11->Win11

### RustDesk Version(s) on local side and remote side

Nightly Build of 12.06.2023

### Screenshots

n/a

**Comment by fufesou** [comment]
@FCrane Thanks for your feedback.
I made a mistake yesterday.

**Comment by rustdesk** [comment]
Please try out the new nightly build (controlled side) and confirm.

**Comment by FCrane** [comment]
Yes, works again with the new version! Thanks!
