### ISSUE TITLE
can not connect with ipv6

### ISSUE THREAD

**Issue by fcwys** [rustdesk/rustdesk#4623]
### Bug Description

Prompt for login error when using ipv6 connection

### How to Reproduce

Connect to clients using ipv6 addresses

### Operating system(s) on local side and remote side

Windows11

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

local：
![image](https://github.com/rustdesk/rustdesk/assets/28641034/edb0651a-b866-41d8-a1e5-bf666817d860)

remote：
![image](https://github.com/rustdesk/rustdesk/assets/28641034/1fd71d9a-c44f-4716-85f1-33b841f161e0)

**Comment by rustdesk** [comment]
direct ip?

**Comment by rustdesk** [comment]
I have no env to test direct ipv6 connection. You have to wait for long.

**Comment by rustdesk** [comment]
close as fix merged
