### ISSUE TITLE
Restarting Explorer cause a empty window pop up in the taskbar

### ISSUE THREAD

**Issue by kgggggb** [rustdesk/rustdesk#4626]
### Bug Description

Restarting the Explorer cause a empty window pop up in the taskbar
Clicking it won't do anything, and you can't close it by clicking close.
Switching between virtual desktops won't do anything either.
It seems like the process `--server` cause this problem, but the user who running this is `SYSTEM`, maybe because of the [Interactive Services](https://learn.microsoft.com/en-us/windows/win32/services/interactive-services)?

### How to Reproduce

Restarting the Explorer

### Expected Behavior

As the Bug Description

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![Untitled](https://github.com/rustdesk/rustdesk/assets/47137779/51d5073c-5560-4032-b028-bb4697f82d61)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/nightly
