### ISSUE TITLE
DDNS domain name resolution to ipv6 address is not available

### ISSUE THREAD

**Issue by fcwys** [rustdesk/rustdesk#4628]
### Bug Description

DDNS domain name resolution to ipv6 address is not available

### How to Reproduce

DDNS domain name resolution to ipv6 address is not available, indicating that ID does not exist

### Expected Behavior

Directly connect to remote clients through domain name resolution of ipv6 addresses

### Operating system(s) on local side and remote side

Windows11

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/28641034/81f8768f-b6d0-41f3-b258-25984ab1db57)

**Comment by rustdesk** [comment]
Domain direct connection is not supported, because we do not know it is id or domain.
