### ISSUE TITLE
openSUSE support or for All Linux?

### ISSUE THREAD

**Issue by yhm-amber** [rustdesk/rustdesk#463]
我尝试用 opensuse （ Leap 15.2 ） 的包管理器 `zypper` 执行本地安装：

![image](https://user-images.githubusercontent.com/103625580/165071755-ee84d62f-fa26-4582-9427-90526b432351.png)

这是结果。当然，这也是不出意料的， RPM 的名字上并没有写 suse 。

我另外尝试寻找办法，用容器来完成 rustdesk 客户端在本地的部署。

我失败了，并没有找到这样用的使用方式。

再其它手段就没想到了。

----

请问后续会有某种方式对【各种 Linux 发行版】予以支持吗？

（或者如果可以的话，不限于这两种方式，能在所有 Linux 发行版用就可以。）

（我在一些项目（如 `starship` ）中看到，用 Rust 做的软件似乎可以通过 `cargo` 命令安装，这或许也是种办法，但我不确定是否适用于本项目。）

**Comment by rustdesk** [comment]
We will support snap later.

**Comment by yhm-amber** [comment]
> We will support snap later.

got it

**Comment by yhm-amber** [comment]
> We will support snap later.

但……其实最好还是有一个能用 docker/podman 的 `run` 来启动桌面客户端的支持。

（这样也会明确它的影响范围，即那些我必须用 `rw`/`ro` 来 `-v` 挂载的目录就能体现软件的影响范围。）

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-suse.rpm

**Comment by yhm-amber** [comment]
> https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-suse.rpm

THANKS !!!! ❤❤❤❤
