### ISSUE TITLE
Failed to obtain screen capture (Wayland, clearlinux)

### ISSUE THREAD

**Issue by Aqua1ung** [rustdesk/rustdesk#4640]
### Bug Description

Attempting to remote into my RustDesk on Clear Linux: after typing in the password (on the client side) I am asked (on the server side) _twice in a row_ to pick the monitor I want to share. After I do that (twice), I get [this](https://i.imgur.com/UVIZGuH.png) (on the client side): "Failed to obtain screen capture."

### How to Reproduce

See bug description above.

### Expected Behavior

1. Rustdesk should ask _only once_ for the monitor to be shared;
2. Client should not display "Failed to obtain screen capture" error, but the actual server screen instead.

### Operating system(s) on local side and remote side

iPadOS 16.5 -> Clear Linux 39370

### RustDesk Version(s) on local side and remote side

1.1.10 -> 1.2.0 (latest Git nightly)

### Screenshots

![IMG_0318](https://github.com/rustdesk/rustdesk/assets/12104779/adbd4f79-e979-4527-87b9-47199d080599)

**Comment by rustdesk** [comment]
traced by https://github.com/rustdesk/rustdesk/issues/3565
