### ISSUE TITLE
 Can't capture screen on android

### ISSUE THREAD

**Issue by parkerpeng** [rustdesk/rustdesk#465]
Can't capture screen on android

**Comment by rustdesk** [comment]
https://play.google.com/store/apps/details?id=com.carriez.flutter_hbb？

**Comment by parkerpeng** [comment]
> [https://play.google.com/store/apps/details?id=com.carriez.flutter_hbb？](https://play.google.com/store/apps/details?id=com.carriez.flutter_hbb%EF%BC%9F)

yes，1.1.9

**Comment by Heap-Hop** [comment]
@parkerpeng hi,can you contact my email? I want check some detail about your device.  csf@breakbeat.cn

**Comment by parkerpeng** [comment]
> @parkerpeng hi,can you contact my email? I want check some detail about your device. [csf@breakbeat.cn](mailto:csf@breakbeat.cn)

Huawei p30 pro

**Comment by Heap-Hop** [comment]
@parkerpeng Can you provide Android and PC screenshots when the screen cannot be captured? or you can contact me by email,if you want. I need more detail ,thx

**Comment by Heap-Hop** [comment]
@parkerpeng How is it going?  we do care about your problem, by the way, what's your desktop rustdesk version? try 1.1.9 please,https://github.com/rustdesk/rustdesk/releases/tag/1.1.9

**Comment by rustdesk** [comment]
close to favor https://github.com/rustdesk/rustdesk/issues/2941
