### ISSUE TITLE
Clipboard stops working after using file transfer while connected to Windows 10

### ISSUE THREAD

**Issue by rakleed** [rustdesk/rustdesk#4657]
### Bug Description

Clipboard stops working after using file transfer while connected to Windows 10.

### How to Reproduce

1. Connect to remote device
2. Copy some text on your computer and paste it on the device you are connected to
3. Send a file to your device via file transfer
4. Copy new text on your computer and try to paste it on the device you are connected to

### Expected Behavior

The text from the clipboard is pasted on the device you are connected to.

### Operating system(s) on local side and remote side

macOS 13/Windows 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0 nightly

### Screenshots

N/A

### Additional Context

I tried to reproduce it locally, but I can only connect to Windows 11/macOS 13, but in this case, the problem could not be reproduced.

**Comment by rustdesk** [comment]
can reproduce on @21pages machine

**Comment by fufesou** [comment]
@rakleed Hi, thanks for your feedback. Do you mean this function breaks clipboard?

<img width="283" alt="1687235553684" src="https://github.com/rustdesk/rustdesk/assets/13586388/57209bdd-061d-44d2-ba14-62d44e2187c0">

I cannot reproduce it.

Is this issue reproducible every time on your computer? ( macOS 13/Windows 11 -> Windows 10 )

Can you please upload a video about this issue, from connecting the session to stopping the clipboard.

**Comment by rakleed** [comment]
@rustdesk previously wrote that @21pages was able to reproduce the problem on his device. Now again you can not reproduce the problem?

Yes, I meant the Transfer File function.

I tried to make a Windows 10 virtual machine but couldn't reproduce the issue. But on real computers, I can reproduce the problem every time.

Can I privately send a screen recording, for example, to your email, @fufesou?

**Comment by rustdesk** [comment]
> @rustdesk previously wrote that @21pages was able to reproduce the problem on his device. Now again you can not reproduce the problem?

It was my misunderstanding.

**Comment by rustdesk** [comment]
Video please

**Comment by rakleed** [comment]
@rustdesk can I privately send a screen recording, for example, to your email?

**Comment by rustdesk** [comment]
linlong1265@gmail.com

**Comment by rustdesk** [comment]
@AllevatoreAnonimo upload a video please, or send to this [mail](mailto:shuanglongchen@yeah.net)

**Comment by SergeyMy** [comment]
Recently there have been complaints that something is wrong with Windows 10....
to the younger, many of the group with updated Windows could not connect for games

PS The issue does not reproduce on other OSes.

**Comment by ethpsantos** [comment]
> @ethpsantos a video please. i am not sure if i can understand you well.

I did more tests...

- The clipboard is shared between Host and Remote (I copy a text in my local machine and it paste it in the remote machine)
- The clipboard doesn't work between Remote and Host (I copy text in remote machine and it doesn't paste anyting in my local machine)

I thought it was working until two days ago.
But I had a big update yesterday on the machine.

Are there anything that the adminstrator can do on Windows that prevent the clipboard share from Remote to Local? Maybe htat is the issue... the copy/past from remote to local was blocked in Windows 10.

**Comment by ethpsantos** [comment]
After some months and a lot of tests I finally understood my issue.

My rustdesk works in the remote without UAC and the machine probably have policies to not allow clipboard copy/paste from remote access... that generate some uncommon issues I believe.

The rustdesk panel in remote shows it with clipboard copy/paste enabled.
But when you try it you can only copy from Host to Remote and not vice-versa.
The Remote to Host clipboard copy/paste will always fail.

So my issue was not related to the issue the OP said.
Sadly I can't make clipboard copy past works from Remote to Host.

Thanks for all the attention.

**Comment by fufesou** [comment]
@ethpsantos Thanks for your feedback.

Do you mean:
1.  Local RustDesk is not installed.
2. Just click and run, then connect to Remote.
3. The clipboard from Remote to Host does not work.

My clipboard works fine.


> the machine probably have policies to not allow clipboard copy/paste from remote access

It may not be true.

Copy/paste of Remote to Local:

1. Get text from Remote clipboard.
2. Send text to Local.
3. Set text to Local clipboard.

But there may be some policies that prevent the applications to read or write contents to the clipboard.

Can you please help test more:
1. Use another PC to connect the original Remote.
2. Use the original Local, connect to another PC.

**Comment by rustdesk** [comment]
Close since OP can not reproduce.

**Comment by fufesou** [comment]
@ethpsantos Thank you for your detailed reply.

> The 3rd point I didn't understand very well.

I mean, use the same local side, and another remote side, to test if text coping from the remote to local is ok.

But if it is confirmed that the issue is with the security settings, there should be no need to test.
