### ISSUE TITLE
Cannot call sogou input method in Deepin20.5

### ISSUE THREAD

**Issue by Ives0721** [rustdesk/rustdesk#466]
When trying to change the name of remote PC I recently logged in, I found that I cannot call sogou input method by using <kbd>Ctrl</kbd>+<kbd>LShift</kbd>

**RustDesk version and environment**

RustDesk version:1.1.8
OS: Deepin 20.5 apricot
Kernel: x86_64 Linux 5.10.101-amd64-desktop
Shell: bash
DE: Deepin 20.5
CPU: Intel Core i5-8300H @ 8x 4GHz
GPU: NVIDIA GeForce GTX 1050

**Comment by rustdesk** [comment]
try out nightly build please

**Comment by rustdesk** [comment]
#1547

**Comment by fufesou** [comment]
@Ives0721  Hi, can you please try the nightly build, with "Map mode"?
 And then tell us if this issue is fixed? 
Thanks.
<img width="235" alt="20230104201351" src="https://user-images.githubusercontent.com/13586388/210715578-13b62bb1-7e67-4ff5-8ad5-4afa34d4740d.png">
