### ISSUE TITLE
Linux -> MacOS keyboard sometimes slow and not all characters working

### ISSUE THREAD

**Issue by Kukulkano** [rustdesk/rustdesk#467]
**Describe the bug you encountered:**

I tried to control MacOS Mojave (10.14.6) from Linux (openSuse 15.3). Both machines inside my local network but using the built-in online server of you. I can manipulate windows and stuff with the mouse but keyboard is sometimes horrible slow. It takes seconds until the typed keys arrive on the Mac.

I found that keyboard gets fast and realtime if I move around some window on the mac. If I wait for a few seconds, keyboard input turns slow again. Looks like it goes to some sleep and keyboard input does not wake it up?

Also, if I type german umlaute (like öäüß), they do not appear on MacOS (they do it using TeamViewer or AnyDesk, so it seems a technical thing).

**What did you expect to happen instead?**

I expected to be able to type near realtime even if no windows are moved. I also expected to get all the keys from my keyboard working :-)

**How did you install `RustDesk`?**

On **openSuse** I installed the rustdesk-**1.1.8**-fedora28-centos8.rpm which installed fine (except a font missing).
On **MacOS** I installed rustdesk-**1.1.8**.dmg which installed with no issues. I then allowed Rust to remote control the Mac.

**Comment by rustdesk** [comment]
We are working hard for these issues. Thanks!

**Comment by Kukulkano** [comment]
I'm happy you do that. It is already a great product and I really like it! Very good work! It may become a very good open source replacement for the commercial engines, which are both expensive and also unclear about security. I especially like the simplicity!

**Comment by Z0pyrus** [comment]
I have a similar issue, but I can't type anything from my linux system (Manjaro, Rust 1.1.9) to my MacBook Pro

**Comment by rustdesk** [comment]
dup: #1547 (all keyboard issues here)
