### ISSUE TITLE
Typo: "deos" instead of "does" in Wiki FAQ page

### ISSUE THREAD

**Issue by otelo2** [rustdesk/rustdesk#4681]
### Bug Description

When navigating to the Wiki FAQ page, the first header says "How deos RustDesk work?". I would expect it to instead say "How does RustDesk work?"

Very minor issue. I would have made a PR to fix it myself but I think GitHub doesn't allow PR's to wikis.

### How to Reproduce

Navigate to this URL: https://github.com/rustdesk/rustdesk/wiki/FAQ

### Expected Behavior

The first heading says "How does RustDesk work?"

### Operating system(s) on local side and remote side

N/A

### RustDesk Version(s) on local side and remote side

N/A

### Screenshots

![Screenshot_2023-06-17-10-03-14-365_com android chrome](https://github.com/rustdesk/rustdesk/assets/10353204/383cfeb7-0c90-42eb-b35e-4f9aee8fad4d)

**Comment by rustdesk** [comment]
fixed
