### ISSUE TITLE
Mac menu bar icon should not always be black

### ISSUE THREAD

**Issue by bilogic** [rustdesk/rustdesk#4683]
### Bug Description

Mac menu bar icons will change color based on wallpaper, but rustdesk icon does not adapt

### How to Reproduce

Set wallpaper to a darker color, e.g. purple

### Expected Behavior

rustdesk icon should turn white like the other icons

### Operating system(s) on local side and remote side

OSX

### RustDesk Version(s) on local side and remote side

1.1.9

## Black icons
<img width="305" alt="image" src="https://github.com/rustdesk/rustdesk/assets/946010/3c453904-e0e6-44fc-87c6-572edf375aaf">

## White icons
<img width="306" alt="image" src="https://github.com/rustdesk/rustdesk/assets/946010/ae93319d-a2ff-4488-a161-52a1932e8e9d">

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/nightly

**Comment by bilogic** [comment]
Why not make a stable release? Piling up features for over 1 year will certain cause surprises, both pleasant and unpleasant.

**Comment by bilogic** [comment]
@rustdesk 

I just tested nightly 1.2.0, the icon is still black, not white when in dark mode.

**Comment by rustdesk** [comment]
<img width="131" alt="image" src="https://github.com/rustdesk/rustdesk/assets/71636191/336c83e9-fe9b-47c2-841b-dc336d3237f5">

**Comment by rustdesk** [comment]
![image](https://github.com/rustdesk/rustdesk/assets/71636191/27adae70-12a6-4245-a879-798403a427b8)
<img width="173" alt="image" src="https://github.com/rustdesk/rustdesk/assets/71636191/0d81bbfd-0183-4028-898b-20e875aad97b">
