### ISSUE TITLE
Cursor state (style) does not go back to original state after resize action

### ISSUE THREAD

**Issue by Simulator88** [rustdesk/rustdesk#4685]
### Bug Description

Hi all,

I just noticed that once you start to resize a window, the cursor does not go back to the original display state. Does not matter if you resize it horizontally or vertically.

### How to Reproduce

Login to the remote side, open up a window app and start to resize it either way. Watch the displayed cursor style.

### Expected Behavior

Cursor to change back to original display form after the resize action finished.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

Nightly -> 1.1.9 and Nightly -> Nightly 

### Screenshots

![355221821_1356418434966297_3880619900688999490_n](https://github.com/rustdesk/rustdesk/assets/63598513/c0162ebb-b58e-4340-9527-5d8315fd25d6)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4601
