### ISSUE TITLE
Android version not updating screen

### ISSUE THREAD

**Issue by FCrane** [rustdesk/rustdesk#4690]
### Bug Description

Hi! I'm using the latest nightly of the Android version and the Windows version. When I use the Android app to connect to a Windows PC, it works for a short time, but after a few mouse clicks (or better "finger taps"), the4 Android app does not update the display anymore. It still remotely controls the PC, meaning it passes mouse clicks, movements, etc. to the remote machine and I can still move and zoom the screen, but it is frozen. I need to close the connection and reconnect. And this is necessary every few seconds. So the Android app clearly has some kind of issue. It does not happen if I connect from a Windows machine. So the Android app clearly has some kind of issue, which makes it unusable (if you don't want to reconnect every few seconds).

### How to Reproduce

Use Android app to connect to a Windows 11 remote desktop.

### Expected Behavior

Should work more than a few seconds.

### Operating system(s) on local side and remote side

Android 12 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.0 latest nightlies

### Screenshots

n/a

**Comment by rustdesk** [comment]
tracked by #3893

**Comment by lucidnx** [comment]
I have found that it's also laggy, after connection, it does not immedialy update screen. After few seconds it fast forward do everything and it's delayed/laggy since then until it stops updating screen. On stable version this was okay, almost none lag/delay I have mentioned, working indefinitely.
