### ISSUE TITLE
Very strange Keyboard layout - no useable

### ISSUE THREAD

**Issue by boospy** [rustdesk/rustdesk#4696]
### Bug Description

I connect from my KDE (Ubuntu 22.04) to an remote Deskop (also Ubuntu 22.04 or Debian 11/10). Keyboard model pc105 layout de is in use. 

But if i would like to use "#" i get an "3" on "-" there is an "ß" and other strange things. 

### How to Reproduce

Connect from one, to another machine. Use the keyboard. I don't know if it happens on Windows, I don't have one.

### Expected Behavior

Normaly the same Keyboardlayout should used on remoteside, or at least this layout which is set on the remotemachine.

### Operating system(s) on local side and remote side

KDE Neon Ubuntu 22.04 --> Debian 11 or (K)Ubuntu 22.04

### RustDesk Version(s) on local side and remote side

1.1.9

### Additional Context

What Keyboard Layout is this? I tried to set it with this command, but without success. And in the current nightly build, this behavior does not occur. (19.07.2023)

`setxkbmap -model pc105 -layout de`

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1547

**Comment by boospy** [comment]
Ok, I see, then I assume that this is no longer fixed in the current stable?
