### ISSUE TITLE
 An existing connection was forcibly closed by the remote host. (os error 10054)

### ISSUE THREAD

**Issue by mohammedyousef2** [rustdesk/rustdesk#4698]
### Bug Description

 An existing connection was forcibly closed by the remote host. (os error 10054)

### How to Reproduce

 An existing connection was forcibly closed by the remote host. (os error 10054)

### Expected Behavior

 An existing connection was forcibly closed by the remote host. (os error 10054)

### Operating system(s) on local side and remote side

Windows 10,11

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

 An existing connection was forcibly closed by the remote host. (os error 10054)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1113

**Comment by tasbox** [comment]
妈个比的傻逼官方，那么多10054的问题不解决，草他妈的。
