### ISSUE TITLE
use docker build error

### ISSUE THREAD

**Issue by xianxian0703** [rustdesk/rustdesk#471]
[root@VM-0-9-centos rustdesk]# docker run --rm -it -v $PWD:/home/user/rustdesk -v rustdesk-git-cache:/home/user/.cargo/git -v rustdesk-registry-cache:/home/user/.cargo/registry -e PUID="$(id -u)" -e PGID="$(id -g)" rustdesk-builder
/entrypoint: 3: cd: can't cd to /root/rustdesk
/entrypoint: 4: .: cannot open /root/.cargo/env: No such file

**Comment by asur4s** [comment]
I just solved this problem by modifying the dockerfile. 

I had this problem when I compiled code from another branch(sciterjs), In the dockerfile, add the following line of code to fix it.
```sh
ENV HOME=/home/user
```

Besides, It's better to wrap the code with ``(markdown syntax).
