### ISSUE TITLE
rustdesk client crashes Windows 11 display driver after closing the remote window

### ISSUE THREAD

**Issue by claychinasky** [rustdesk/rustdesk#4714]
### Bug Description

Using Windows 11 pro with RTX 2080 (532.03)
I'm making connection to Debian 12 X11 / 4090 (525.105.17) remote pc.
Rustdesk client crashes Windows 11 display driver after closing the remote window. Mouse freezes for a second then monitors goes black then it restores itself. (this happens sometimes, probably more chance to happening on longer sessions)
(no errors apperant) (AV1 codec, keyboard: map mode, scale adaptive, resolution lowered to 2560x1080)
if there is a way to debug this for more information, I might as well do it.

### How to Reproduce

Close the rustdesk remote window by pressing X icon top right.

### Expected Behavior

close without crashing the driver.

### Operating system(s) on local side and remote side

windows 11 - Debian 12 X11

### RustDesk Version(s) on local side and remote side

local and remote both build date: 1.2.0 2023-06-16 13:43

### Screenshots

none

**Comment by hkpD** [comment]
Experiencing the same issue here.

**Comment by rustdesk** [comment]
low end machine as this https://github.com/rustdesk/rustdesk/issues/4780#issuecomment-1609304188?

**Comment by claychinasky** [comment]
I updated the client only for now, to see if the issue still exists. Yet it looks likely random to occurring issue.

**Comment by claychinasky** [comment]
Haven't got the same issue yet, using Rustdesk everyday. So its fair to close the issue.
Thanks
