### ISSUE TITLE
Connect without self-built server

### ISSUE THREAD

**Issue by ls148478** [rustdesk/rustdesk#4715]
### Bug Description

Since English is not my mother tongue, the following source translation
I built a server using iPv6, and it was running normally at the beginning. After I ran it for a day, I found that I couldn’t connect to the self-built server. The special thing is that I used the self-built server on more than one computer, and other devices were normal.
I tried uninstalling and reinstalling, but it didn't work
It should be noted that after I ran it for a day, that is, just now, I modified the firewall of the server and restarted the device. I don’t think there is a problem with the server here. As I said before, other computers are running normally

### How to Reproduce

Reproducibility is temporarily uncertain, this seems to be a bizarre problem

### Expected Behavior

Can connect to the server normally

### Operating system(s) on local side and remote side

Windows11 -> Windows7

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/38435967/6b9e9664-fdec-4888-bbc8-ab1d4b7199d6)

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4671
