### ISSUE TITLE
Excessive memory usage

### ISSUE THREAD

**Issue by Euraxluo** [rustdesk/rustdesk#4717]
### Bug Description

in mac os，RAM cost 2.0GB
![image](https://github.com/rustdesk/rustdesk/assets/34028978/091d7c67-967d-4f5c-bd29-a7fa2c4888f6)

### How to Reproduce

run rustdesk  3day on macos

### Expected Behavior

No significant increase in memory，There may be a memory leak

### Operating system(s) on local side and remote side

macOS Ventura 13.2.1

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/34028978/532c2043-e1c7-4669-ab5f-292360450727)
![image](https://github.com/rustdesk/rustdesk/assets/34028978/091d7c67-967d-4f5c-bd29-a7fa2c4888f6)

**Comment by Euraxluo** [comment]
Additional information：
windows 11 control-> mac mini m2,mac os 13.2.1
rustdesk client run 7*24 h on mac os,then that run 3 days. memory use 2 GB.

**Comment by rustdesk** [comment]
try out https://github.com/rustdesk/rustdesk/releases/nightly

**Comment by rustdesk** [comment]
close since no response.
