### ISSUE TITLE
transfer file does not work in privacy mode

### ISSUE THREAD

**Issue by test2a** [rustdesk/rustdesk#4726]
### Bug Description

I enabled privacy mode but the file transfer window does not work. 

### How to Reproduce

enable privacy mode
try to open transfer file
error

### Expected Behavior

file transfer should work

### Operating system(s) on local side and remote side

linux>windows

### RustDesk Version(s) on local side and remote side

1.2 (build 15/6/23) > 1.2 (build 16.6.2023)

### Screenshots

![Screenshot_20230621_170618](https://github.com/rustdesk/rustdesk/assets/39449563/5075e491-38d3-4823-8481-29e2c6b89157)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/3e27f82765c8af5be6d2dcd7006767f0b89624d7
