### ISSUE TITLE
login button does not work

### ISSUE THREAD

**Issue by test2a** [rustdesk/rustdesk#4727]
### Bug Description

checked login button on address book and in settings. both do not work

### How to Reproduce

click on login button

### Expected Behavior

login should work somehow

### Operating system(s) on local side and remote side

linux

### RustDesk Version(s) on local side and remote side

1.2 (build 15/6/23)

### Screenshots

https://github.com/rustdesk/rustdesk/assets/39449563/e9be87d0-6cba-445c-9d5d-e94909cdcb23

**Comment by rustdesk** [comment]
Pro
