### ISSUE TITLE
iOS recent connections does not show up

### ISSUE THREAD

**Issue by takov751** [rustdesk/rustdesk#473]
Hey I am big fan of the project. After recent update on iOS the app does not shows recent connections, not even when I select save password. It's a wee bit annoying, but not the end of the world. 

Sidenote: while I used the app I had my first systemwide freeze on iOS which is weird, but I doubt it has anything to do RustDesk app specifically. 

Keep up the great work 👍👍👍

**Comment by rustdesk** [comment]
Sorry for this. I can not reproduce this issue, I will try to test more devices.

**Comment by takov751** [comment]
Thank you I will do a fresh install of the app and test it one more time

**Comment by takov751** [comment]
I have Finnaly was able to test again as my phone broke and got fixed . So the issue is that only id based devices stored , however when you use direct ip address to connect to . It's not getting stored in the iOS app.
