### ISSUE TITLE
1.2.0 nightly for macOS hasn't been updated for more than 4 days

### ISSUE THREAD

**Issue by rakleed** [rustdesk/rustdesk#4742]
### Bug Description

1.2.0 nightly for macOS has not been updated for more than 4 days, although everything is correctly updated for other platforms.

### How to Reproduce

1. Go to https://github.com/rustdesk/rustdesk/releases/tag/nightly
2. Open Assets details

### Expected Behavior

1.2.0 nightly for macOS is updated once a day, just like for other platforms.

### Operating system(s) on local side and remote side

macOS -> macOS

### RustDesk Version(s) on local side and remote side

1.2.0 nightly

### Screenshots

![Screenshot 2023-06-22 at 19 29 20](https://github.com/rustdesk/rustdesk/assets/19418601/6870a6e6-e56f-41a8-bf63-cd8319c172c7)

**Comment by rustdesk** [comment]
we know
