### ISSUE TITLE
cannot open a folder from File when controlling Android

### ISSUE THREAD

**Issue by luca-e075e** [rustdesk/rustdesk#4743]
### Bug Description

I am controlling an Android device from debian and cannot open a folder with File app since clicking on the folder does nothing

### How to Reproduce

_ connect the devices
_ open an app that can use the stock File to pick a file. I used Snapseed
_ open a folder from the chosen app

### Expected Behavior

the folder opens, permitting to select its files

### Operating system(s) on local side and remote side

Debian 12 > Android 10

### RustDesk Version(s) on local side and remote side

1.2.0 (Build Date: 2023-06-22 02:29) > 1.1.10-1 (fdroid)

### Screenshots

[Screencast from 2023-06-22 21-37-04.webm](https://github.com/rustdesk/rustdesk/assets/15078341/1a7b2138-e63a-4df9-881e-b9f5b53256cd)

**Comment by rustdesk** [comment]
traced by https://github.com/rustdesk/rustdesk/issues/3893
