### ISSUE TITLE
Failed to connect via rendezvous server in docker self host

### ISSUE THREAD

**Issue by sanoj-m** [rustdesk/rustdesk#4772]
### Bug Description

All our desktops as not connecting to each other within even the same local Network. Showing Failed to connect via rendezvous server. Please help

### How to Reproduce

Connecting to any device within the local Network or via remote. 

### Expected Behavior

Should be connecting fine as it's connected to the relay server. This was working fine yesterday.

### Operating system(s) on local side and remote side

Windows 10, 11

### RustDesk Version(s) on local side and remote side

Latest nightly builds

### Screenshots

<img width="515" alt="image" src="https://github.com/rustdesk/rustdesk/assets/72506041/c1c188ef-99cb-4cae-8d3f-b3b42e690da2">

**Comment by rustdesk** [comment]
#763

**Comment by sanoj-m** [comment]
hello, i have went though the link above multiple times. i have even recreated a new docker and used docker compose to pull the latest build. still facing the same issue. all my clients are showing offline now. Please help

![image](https://github.com/rustdesk/rustdesk/assets/72506041/66cf82a9-0c07-4bd9-bf5e-13e1b6662e2e)
