### ISSUE TITLE
Rustdesk not connecting

### ISSUE THREAD

**Issue by sanoj-m** [rustdesk/rustdesk#4776]
### Bug Description

![image](https://github.com/rustdesk/rustdesk/assets/72506041/36fd0640-fb80-4cf3-83fa-270284bf1859)
my ddns is up, all ports are open, docker have changed from debian to ubuntu 20. still shows ready not connecting.

![image](https://github.com/rustdesk/rustdesk/assets/72506041/19e478c3-949d-464d-95f1-bde325efa645)
all users are showing ready but not online

hbbs and hbbr is running in containers

what else am i missing?

### How to Reproduce

reinstalled docker

### Expected Behavior

should be connecting to the clients as i have done the same installation process following the self hosting docs

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/72506041/a06de8aa-f686-45bb-91ee-5297ad699c20)

**Comment by rustdesk** [comment]
#763

**Comment by sanoj-m** [comment]
Please guide me where I can find some help?
