### ISSUE TITLE
Keyboard inputs are recognized when RustDesk window is out of focus

### ISSUE THREAD

**Issue by robertschifferli** [rustdesk/rustdesk#4779]
### Bug Description

While using Rustdesk, I frequently notice that it recognizes keyboard inputs even when the window is not in focus.  RustDesk has easily become my favorite remote desktop software (I've used them all...) but to be honest I have never seen any other remote desktop software behave this way, nor can I understand why anyone would want it to.  If this is a "feature" then please add an option to disable this (checkbox in settings list or something?)

For example, a frequent scenario would be I have a remote desktop with some kind of social media website open (facebook, twitter, youtube etc.) and then I get an IM on my local machine so I open up my IM client and start responding.  Next thing I know, my entire IM convo has been posted as comments on whatever facebook/twitter/youtube convo I was reading at the time.

This can also happen while working on a Word document etc. on the remote machine.  Next thing you know, I somehow replaced all the text in my document I was working on in the remote machine with what I was typing on my local machine.

The only way to avoid this is to constantly remember to minimize my RustDesk windows when switching back to my local machine, or to minimize whatever window I was looking at in the Remote desktop.  This is extremely annoying and cumbersome, especially when I have a lot of windows open and I have to constantly do this every time I switch between desktops and then search to find the window I was working on.

### How to Reproduce

1. Have a RustDesk remote session open.
2. In the remote session leave an active cursor in any kind of text field.  Let's open a notepad window as an example
3. Open a new window on top of that RustDesk window on the local machine.  The RustDesk window will now be out of focus
4. Begin typing in the new window that is now in focus, whatever it may be (IM client, MS word, email client, notepad etc.)
5. You will notice that everything you type appears in the now in focus window on the local machine (as expected), yet it is also being duplicated wherever your text cursor was in the remote session

### Expected Behavior

The text should only appear in the in-focus window on the local machine.  It should NOT be duplicated in the now out-of-focus RustDesk session.

### Operating system(s) on local side and remote side

Any combination of Windows 10, Windows 11 as local/remote

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

Theres no way to demonstrate this in screenshots

https://github.com/rustdesk/rustdesk/assets/6600592/18188915-4b25-4495-a78d-054de1343578

### Additional Context

While putting this bug report together it seems this may only happen if the mouse cursor is hovering over the out-of-focus RustDesk window.  If you are sure to keep your mouse cursor only within the bounds of the window you are working in on the local machine, then you may be able to avoid this scenario.  This is still not the behavior I would expect.

**Comment by rustdesk** [comment]
duplicate
