### ISSUE TITLE
numlock turned off everytime after being controlled.

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#478]

**Comment by heitorfmc** [comment]
I have this issue, after connection is estabilished num lock gets disabled on remote computer.

**Comment by rustdesk** [comment]
@fufesou

**Comment by heitorfmc** [comment]
I have also noticed that after any num pad key is pressed on my computer NumLock gets enabled and disabled on remote computer. That's may be causing the problem.

**Comment by rustdesk** [comment]
> enabled and disabled

1.1.9 has this behavior，nightly build changes

**Comment by chiehw** [comment]
> 我有这个问题，在建立连接后，远程计算机上的 num lock 被禁用。

假设 client 控制 remote，client 会自动同步 remote 的 numlock 状态。你说 num lock 被禁用，是不是 client 的 numlock 是禁用状态？

我需要更多的信息，控制端和被控端是什么系统的？你做了什么操作？期待什么效果？ @heitorfmc

**Comment by angel6700** [comment]
My suggestion would be to allow the user to change behavior (to sync or not to sync) of the num-lock.
If remote computer is a laptop. Setting the num-lock on is quite annoying for the person who is using it.
Otherwise, not syncing at all both modifiers (caps-lock & num-lock).

**Comment by fufesou** [comment]
I think a better way to handle it is:

1. Synchronize the CapsLock state when any key is pressed.
2. Only synchronize the NumLock state when a key on the numpad is pressed.

**Comment by rustdesk** [comment]
Let's continue to use our legacy mode (same with TV).
