### ISSUE TITLE
[Nightly] BSOD caused by nvlddmkm.sys

### ISSUE THREAD

**Issue by Eruthon** [rustdesk/rustdesk#4780]
### Bug Description

When I close Rustdesk window of remote connection, I get BSOD (see image).

### How to Reproduce

1. Connect to remote desktop
2. Close remote desktop window by clicking X in top right corner.

### Expected Behavior

No BSOD

### Operating system(s) on local side and remote side

Win11 -> Win10

### RustDesk Version(s) on local side and remote side

Nightly 2023-06-27 -> Nightly 2023-06-27

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/37985268/57aa25fe-5a8f-4717-ac52-7fe3ff85ac0d)

### Additional Context

RustDesk server is self-hosted;
RustDesk client is built with my custom ENV;
Nightly is automatically updated daily on all PCs in work via script with --reinstall option;
This error isn't happening every time, but so far I've seen it only on my PC at work;
NVidia driver is updated; card is 3070Ti;
My Win11 machine is recently installed (month old)

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/4714

**Comment by rustdesk** [comment]
How about if there is no image? e.g. connect to an invalid id.

**Comment by Eruthon** [comment]
Nothing, that works correctly. It seems only connections to some specific PCs is causing this.

**Comment by rustdesk** [comment]
> specific PCs

Anything specific?

**Comment by Eruthon** [comment]
All I can say rn is that it's an older notebook with VLC and OBS managing TVs.

**Comment by rustdesk** [comment]
Is the main window open or close when crash?

**Comment by Eruthon** [comment]
In both cases it crashes.

**Comment by Eruthon** [comment]
I also found out that the view mode of connections in main window, recent connection, gets reset into the large icons mode from the list mode I use. And the problematic PC gets deleted from the list.

**Comment by rustdesk** [comment]
@Eruthon can you try out latest build? I did some little change, not sure if help.

**Comment by Eruthon** [comment]
Seems it did the trick
