### ISSUE TITLE
software name about config

### ISSUE THREAD

**Issue by SmileZD** [rustdesk/rustdesk#479]
I would like to ask, in which code is the function of reading the software name and automatically configuring implemented?

**Comment by fufesou** [comment]
Most configs are implemented in libs\hbb_common\src\config.rs. Auto id is generated [here](https://github.com/rustdesk/rustdesk/blob/6cfbbbc06746d9f182f2349f1466e4d9b9ac9252/libs/hbb_common/src/config.rs#L526).

**Comment by SmileZD** [comment]
I mean, in version 1.1.9, you can directly obtain the ID server ip config by modifying the software name. Where is this realized
[https://rustdesk.com/docs/en/self-host/console/images/console-home.png?v2](url)

**Comment by SmileZD** [comment]
https://rustdesk.com/docs/en/self-host/console/#windows-exe
