### ISSUE TITLE
After a power outage, I cannot take a good connection

### ISSUE THREAD

**Issue by ikunpy** [rustdesk/rustdesk#4791]
### Bug Description

After a power outage, I cannot take a good connection on windows. I guess this may caused by threads illegally shutdown or cache mirroring may be in my computer or in the server. I try to valid this, and I found when I try to change my ID, it encounters an error that this software cannot connect to the official server. But in fact, I have successfully connected to the server just as the character at the bottom of the software.
In this state, I tried several times and successfully connects to my computer but the creen cannot be captured and the connection will soonly be shutdown.

 After I use the local area network, it works, and I change the network, it still keep the connect. But when I quit this connection, I cannot connect again.
### How to Reproduce

on a windows computer *64 and take the power off, finnaly restart the computer.

### Expected Behavior

solve the problem

### Operating system(s) on local side and remote side

Win 10 professional

### RustDesk Version(s) on local side and remote side

newest on rustdesk website

### Screenshots

![1](https://github.com/rustdesk/rustdesk/assets/113223580/a1c962e0-b2ef-4189-b34b-7a6dbe20e274)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4671
