### ISSUE TITLE
Double mouse cursor and keyboard input on ipados

### ISSUE THREAD

**Issue by FerdinandSukhoi** [rustdesk/rustdesk#4794]
### Bug Description

Hi, I am using my iPad OS 16.5 device connecting to my windows 11 host through self-hosted server. The connection established quite fast, but it did not work properly.
1. There are two overlap mouse cursors on my screen, one is the round one of ipados, and the other is the normal one for windows.
2. physical Keyboard inputs two characters with one press on the key, so all of my input is doubled 

### How to Reproduce

I think this is a issue with ipad client on ipados 16.5, and not concerned with the host or server, because it worked well before I updated my ipados version.

### Expected Behavior

1. only one regular windows cursor display on the screen
2. only one character inout after a key press

### Operating system(s) on local side and remote side

ipadOS 16.5 -> windows 11

### RustDesk Version(s) on local side and remote side

1.1.10->1.1.9

### Screenshots

https://github.com/rustdesk/rustdesk/assets/54871796/b169d2ff-ecdd-429a-a82c-f7741091de9b

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3083#issuecomment-1424353203

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1739
