### ISSUE TITLE
Unable to install 1.2.0-x86_64.exe

### ISSUE THREAD

**Issue by DenimDev** [rustdesk/rustdesk#4796]
### Bug Description

After install, no changes are visible on the system.

### How to Reproduce

Attempt to install the 1.2.0-x86_64.exe

### Expected Behavior

I expected that I would be able to install the program, including creating directories, shortcuts, and the like.

### Operating system(s) on local side and remote side

Windows 10 -> N/A

### RustDesk Version(s) on local side and remote side

1.2.0-x86_64.exe

### Screenshots

https://github.com/rustdesk/rustdesk/assets/25937751/7b56d1c2-93f4-40f6-8121-582449081b46

### Additional Context

This is being run on a hyper v VM with the hypervisor being a win10 box. I was able to successfully install v1.1.9 on this computer.

**Comment by yuhuan-wu** [comment]
I met the same error in a real machine (client side). The system version is Windows LTSC 21H2 (Version 19044.2486).

I applied a temporary workaround by downgrading Rustdesk to version 1.1.9, which resolved the issue.

**Comment by ROdoka** [comment]
I know, I know, Win7 ... but on my work PC right now I have the same problem

**Comment by ScriblJ** [comment]
@DenimDev > Right mouse button > Run as administrator

**Comment by rustdesk** [comment]
[fixed.](https://github.com/rustdesk/rustdesk/pull/4801)
