### ISSUE TITLE
can't get rustdesk-server-demo  work

### ISSUE THREAD

**Issue by vjeson** [rustdesk/rustdesk#48]
1. first run  serverdemo
IP=192.168.2.231 cargo run

2.set ID/Relay address on client
connect to another pc 

the server log output

register_peer 192.168.2.3:53374
punch_hole_request 192.168.2.3:49650
relay_response 192.168.2.231:46299
block here

client throw exception  Connection Error , Failed to connect to relay server

**Comment by rustdesk** [comment]
I did not test on intranet, and did not run  rustdesk-server-demo and rustdesk on the same machine (192.168.2.231). Can you help debug?

**Comment by rustdesk** [comment]
You do not need to set relay server, relay server is already implicit used.

**Comment by vjeson** [comment]
Yes , I tested in intranet ,  at first ,I run one client and server on one pc , another client on another pc , not work ,So I depoly the serverdemo to the server ,still can't get it work  . I also tested to remove relay server address as you said, got same error 
I can debug , but i'm new to rust , so i can't figure out what's wrong

**Comment by vjeson** [comment]
Because I only want use it in intranet ,So i comment the default relay server, 
pub const RENDEZVOUS_SERVERS: &'static [&'static str] = &[
    // "rs-cn.rustdesk.com",
    // "rs-sg.rustdesk.com",
];

**Comment by rustdesk** [comment]
I did test yesterday before deploy the code.

**Comment by rustdesk** [comment]
try to do below change in main.rs line 40

```
                            Some(rendezvous_message::Union::relay_response(_)) => {
                                println!("relay_response {:?}", addr);
                                let mut msg_out = RendezvousMessage::new();
                                msg_out.set_relay_response(RelayResponse {
                                    relay_server: relay_server.clone(),
                                    ..Default::default()
                                });
                                if let Some(mut stream) = saved_stream.take() {
                                    if let Ok((stream_a, _)) = rlistener.accept().await {
                                        let mut stream_a = FramedStream::from(stream_a);
                                        stream.send(&msg_out).await.ok();   
                                        if let Ok((stream_b, _)) = rlistener.accept().await {
                                            let mut stream_b = FramedStream::from(stream_b);
                                            stream_a.next_timeout(3_000).await;
                                            stream_b.next_timeout(3_000).await;
                                            relay(stream_a, stream_b, &mut socket, &mut id_map).await;
                                        }
                                    }
                                }
                            }
```

**Comment by rustdesk** [comment]
also make sure 21117 port work, relay uses 21117

**Comment by rustdesk** [comment]
If still not work, I can not help you. Up to yourself to solve it.

**Comment by vjeson** [comment]
It's my fault. I changed the server defualt port to 15000 and 15111 ,and set ID server addr ip:15000 ip:15111 , but the defualt port is fixed in config.rs file , if I change server port , I need to change RENDEZVOUS_PORT and RELAY_PORT
Thanks anyway .It's really a great project.
