### ISSUE TITLE
Changing a static password

### ISSUE THREAD

**Issue by ScriblJ** [rustdesk/rustdesk#4802]
### Bug Description

I want to deploy the night version on my network, but when using the "--password" key, nothing happens :(

### How to Reproduce

CMD run as admin:
rustdesk.exe --password SomePassword

### Expected Behavior

Setting a static password for RustDesk.

### Operating system(s) on local side and remote side

Windows 10 21H2 - 19044.3086 (LOCAL)

### RustDesk Version(s) on local side and remote side

1.2.0 (Build 2023-06-29 03:01)

### Screenshots

![Screenshot_25](https://github.com/rustdesk/rustdesk/assets/106529260/98399a3a-e783-4e17-be00-bef0f131e690)
![Screenshot_24](https://github.com/rustdesk/rustdesk/assets/106529260/01911a96-ab0e-445d-9557-84d460991b43)

![Screenshot_27](https://github.com/rustdesk/rustdesk/assets/106529260/c8b035f4-9717-45ad-a7d8-46d6c0c88cf3)

### Additional Context

Config:
![Screenshot_23](https://github.com/rustdesk/rustdesk/assets/106529260/6acd5617-c70c-4f12-8ba8-a1e3da8a8d56)

No matter what I do, but the key does not seem to work, maybe I don’t understand something...
Tried in different ways, from CMD/PowerShell admin. Each log re-read no errors encountered with the password.
~ Works as a service.
![Screenshot_26](https://github.com/rustdesk/rustdesk/assets/106529260/3ad706d4-4995-4c6c-b871-88b394a4a902)
~~ In the screenshot, I'm worried about the insoles with
#[cfg(any(target_os = "android", target_os = "ios"))]

**Comment by rustdesk** [comment]
#763
