### ISSUE TITLE
Deploy setup sliently nightly version

### ISSUE THREAD

**Issue by trisosamu** [rustdesk/rustdesk#4803]
### Bug Description

why ther isn't setup in the nitghtly??

### How to Reproduce

why ther isn't setup in the nitghtly??

### Expected Behavior

why ther isn't setup in the nitghtly??

### Operating system(s) on local side and remote side

Windows 10/11

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

why ther isn't setup in the nitghtly??
![Screenshot 2023-06-30 102938](https://github.com/rustdesk/rustdesk/assets/78987040/da47db31-1824-4269-b08a-d493415c0ec3)
![Screenshot 2023-06-30 102938](https://github.com/rustdesk/rustdesk/assets/78987040/4a859f55-3ed3-402b-9df8-f39631116274)

**Comment by ScriblJ** [comment]
@trisosamu 
For a silent install, run cmd as administrator and execute:
`[PATH]\rustdesk-1.2.0-x86_64.exe --silent-install`
Do not add other keys!
A shortcut on the desktop will be created, but this is not a problem - one command can delete СMD.

**Comment by rustdesk** [comment]
#763
