### ISSUE TITLE
Version 1.1.9, self-built server, ubuntu client cannot log in

### ISSUE THREAD

**Issue by chenjianhua** [rustdesk/rustdesk#481]
Like the title, but I can log in with the same account on the Windows client. I can provide more information if needed.
![QQ图片20220506172318](https://user-images.githubusercontent.com/2851859/167104869-3ca940eb-ba4f-4ed8-ad97-dbc4f2028dc1.png)

**Comment by chenjianhua** [comment]
The server software is also up to date

**Comment by rustdesk** [comment]
Thanks, I reproduced the problem.

**Comment by chenjianhua** [comment]
![QQ截图20220506172921](https://user-images.githubusercontent.com/2851859/167105857-27194b48-80b6-402e-8f3c-146bbc56f45d.png)
There is also a crash message

**Comment by rustdesk** [comment]
> ![QQ截图20220506172921](https://user-images.githubusercontent.com/2851859/167105857-27194b48-80b6-402e-8f3c-146bbc56f45d.png) There is also a crash message

When?

**Comment by chenjianhua** [comment]
> > There is also a crash message
> 
> When?
Just now
