### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by kouzhudong** [rustdesk/rustdesk#4810]
### Bug Description

![1688180271885](https://github.com/rustdesk/rustdesk/assets/18212165/dca0bba8-9783-4d65-9af4-242460627d31)

### How to Reproduce

![1688180271885](https://github.com/rustdesk/rustdesk/assets/18212165/cafbfd91-5399-403d-882f-13417991d241)

### Expected Behavior

![1688180271885](https://github.com/rustdesk/rustdesk/assets/18212165/df5191a4-8671-498d-9ee4-831e69f39b98)

### Operating system(s) on local side and remote side

windows 10

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

![1688180271885](https://github.com/rustdesk/rustdesk/assets/18212165/ac168c20-8df1-45c1-920b-3b94e3440822)

**Comment by rustdesk** [comment]
#763
