### ISSUE TITLE
In the 1.1.9 version of mac, permissions have been given, but the software also prompts that permissions need to be set.

### ISSUE THREAD

**Issue by chenjianhua** [rustdesk/rustdesk#482]
In the 1.1.9 version of mac, permissions have been given, but the software also prompts that permissions need to be set.
<img width="651" alt="iShot2022-05-06_21 07 29" src="https://user-images.githubusercontent.com/2851859/167137521-b6b5b5f3-f430-480b-9e84-b3bdcb933a6a.png">

**Comment by rustdesk** [comment]
https://rustdesk.com/docs/en/manual/mac/

> If you have enabled it in the settings window, but RustDesk still warns. Please Remove RustDesk from the settings windows by the - button, and click on + button, select RustDesk in /Applications

**Comment by chenjianhua** [comment]
> https://rustdesk.com/docs/en/manual/mac/
> 
> > If you have enabled it in the settings window, but RustDesk still warns. Please Remove RustDesk from the settings windows by the - button, and click on + button, select RustDesk in /Applications
Perfect, solved. But the operation is more complicated and not very friendly.

**Comment by rustdesk** [comment]
> Perfect, solved. But the operation is more complicated and not very friendly.

The police is designed by Apple, we can not avoid.

**Comment by chenjianhua** [comment]
OK, this issue has been resolved.
