### ISSUE TITLE
The window is transparent?

### ISSUE THREAD

**Issue by zkteco-home** [rustdesk/rustdesk#4824]
### Bug Description

main window is transparent under win 10,win11 is ok

### How to Reproduce

to run under win10

### Expected Behavior

not transaparent

### Operating system(s) on local side and remote side

windows 10

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/66519168/cf5859b2-ecf1-4f0f-903d-d47cb9a2376c)

**Comment by zkteco-home** [comment]
![image](https://github.com/rustdesk/rustdesk/assets/66519168/cd1a75a9-be6b-482f-b5ce-785c57dceeaf)

**Comment by rustdesk** [comment]
which build? when do you start to see this?

**Comment by zkteco-home** [comment]
yesterday downloaded it from nightly

**Comment by rustdesk** [comment]
show me the build date and time. Yesterday we have uploaded twice.

**Comment by rustdesk** [comment]
Anyway try out today's build.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/4819#discussioncomment-6339737

**Comment by zhangbo8418** [comment]
<img width="890" alt="微信图片_20230703105127" src="https://github.com/rustdesk/rustdesk/assets/46797568/85cb6a51-2f54-4ff7-884f-1b044628fafa">

**Comment by rustdesk** [comment]
@zhangbo8418 Thanks

**Comment by djjaam** [comment]
Same here but until now in version 22H2 (build 19045.3693). I'm running in a VM RustDesk version 1.2.3 Build date: 2023-10-13 10:57.

Tried in another VM with Win10 22H2 (build 19045.3803) and it works well

**Comment by sysop84** [comment]
Can confirm, this is a bug. Win10 21H2 LTSC in VMware Workstation.

![2024-01-29_091557](https://github.com/rustdesk/rustdesk/assets/99490917/1c713e14-165b-4b55-8162-802b65b0c9f0)

**Comment by gusarg81** [comment]
Hi, I am having similar problem, by my Host machine is Ubuntu (KDE Neon) 24.04 and Since I've switched my Radon RX580 to a nVidia RTX2060 the same things is happening to me.... impossible to use RustDesk.
