### ISSUE TITLE
Android App: Direct IP connection does not work anymore!

### ISSUE THREAD

**Issue by FCrane** [rustdesk/rustdesk#4827]
### Bug Description

In the latest nightly of the Android app, the direct IP connection does not work anymore! Also, the stopping screen update issue still is not fixed.

### How to Reproduce

Try to connect to an the Android app via direct IP address.

### Expected Behavior

Connection should work.

### Operating system(s) on local side and remote side

Windows 11 -> Android 12

### RustDesk Version(s) on local side and remote side

Latest nightlies

### Screenshots

n/a

**Comment by rustdesk** [comment]
![image](https://github.com/rustdesk/rustdesk/assets/71636191/6b35e80f-b54f-4946-a31a-3f8cee93065b)

**Comment by rustdesk** [comment]
It works anyway on my mobile, latest nightly.
