### ISSUE TITLE
In the 1.1.9 version of mac, when remote windows and ubuntu are used, the keyboard fails and cannot enter text

### ISSUE THREAD

**Issue by chenjianhua** [rustdesk/rustdesk#483]
In the 1.1.9 version of mac, when remote windows and ubuntu are used, the keyboard fails and cannot enter text

**Comment by chenjianhua** [comment]
Permissions lost after upgrade. After a complex re-empowerment, it's ok.

**Comment by rustdesk** [comment]
Unsigned app has this problem. Since 1.1.9, RustDesk is signed, will not lost permissions.

**Comment by chenjianhua** [comment]
I hope it can be listed on the app store, so it is a formal software. I wish you success.

**Comment by rustdesk** [comment]
> I hope it can be listed on the app store, so it is a formal software. I wish you success.

Sure, will do, including WIndows store.

**Comment by javajeans** [comment]
@chenjianhua How did you set it up, I have the same problem

**Comment by rustdesk** [comment]
https://rustdesk.com/docs/en/manual/mac/#enable-permissions
