### ISSUE TITLE
macos client crash when android clien connect

### ISSUE THREAD

**Issue by cctyl** [rustdesk/rustdesk#4835]
### Bug Description

when i try to connect macos,type passwd on the android client. It was only turned on for a moment and then prompted for an issue, displaying the connection being closed on the Android client.
The system prompts to reopen the window and report the issue.
crash log as below:
[crash.log](https://github.com/rustdesk/rustdesk/files/11936343/crash.log)

### How to Reproduce

it happen on after configuring the relay server,directly input id and pwd connect  

### Expected Behavior

Normally, it should establish the connection correctly and then proceed with remote control smoothly

### Operating system(s) on local side and remote side

android10 --> macos 10.14

### RustDesk Version(s) on local side and remote side

1.1.10-1 --> 1.1.6

### Screenshots
![after crash](https://github.com/rustdesk/rustdesk/assets/34262992/f8aa5b05-6802-4713-aa6e-6cde5074f83b)
![reopen prompt](https://github.com/rustdesk/rustdesk/assets/34262992/f7841ec7-3f75-4dd0-bcdb-9297c318bf7c)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/nightly I will reopen if you still see problem with nightly build.
