### ISSUE TITLE
Corsair iCue Makros does not work after using Rustdesk 1.2.0

### ISSUE THREAD

**Issue by slewantoski** [rustdesk/rustdesk#4842]
### Bug Description

Hi, i just upgraded from Version 1.1.9 to Version 1.2.0.
Now i have a problem with Corsair iCue:
After using Rustdesk the Keyboard Makros defined in iCue on the host does no longer work.
Restarting iCue fixes the problem until connecting with Rustdesk.

Tried it from mobile or another Windows Client.

Downgraded Version to 1.1.9 and it works again.

### How to Reproduce

Having a Corsair Keyboard with makro Keys (I use a K95) an the up to date iCue Software (I use 5.3.102 at the moment).
- Define a makro for some Keypresses
- Connect to this machine via Rustdesk 1.2.0 (for example from a mobile phone)
- Disconnect from this machine
- Try to use the makro Key > it does no longer work
- Restart iCue Software to fix it
- Try the same with old 1.1.9 and it works

### Expected Behavior

At least after disconnecting from Rustdesk the makro keys should work again.

### Operating system(s) on local side and remote side

Windows 11 Version 22621.1928

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0

### Screenshots

I don't know how i should take a screenshot of a makro key.

**Comment by rustdesk** [comment]
You can still use the legacy mode (on toolbar). Frankly, we won't spend time to reproduce your specific case for the time being.

**Comment by slewantoski** [comment]
Legacy mode does not change the behaviour.
I have to accept your decision and now search for another remote Software as i use macro keys a lot and restarting iCue everytime  is to uncomfortable.
Thanks for your work.

**Comment by rustdesk** [comment]
@fufesou check out how do the others handle remote side macro keys. and why legacy mode has different behavior with 1.1.9?

**Comment by slewantoski** [comment]
I think this is misunderstood:
I connect from Computer 2 to Computer 1.
After using rustdesk i can no longer use the macro keys local on Computer 1
![Computer macro](https://github.com/rustdesk/rustdesk/assets/50290847/2bcd4fd3-b293-43ae-be9f-dd6e39fd4ee9)

**Comment by fufesou** [comment]
@sakiodre Hi, thanks for your feedback.

Did you use the portable version or the installed version?

Can you please help test if the macros woks after following steps with 1.2.0 ?
1. Disconnect the session.
2. Do not restart iCue. Just kill rustdesk by running `taskkill /F /IM rustdesk.exe` on the cmd or uninstall rustdesk?

**Comment by sakiodre** [comment]
@fufesou I believe you were mentioning @slewantoski instead of me

**Comment by slewantoski** [comment]
Hi, i just tried is with taskkill.
Does not help. Have to restart iCue to get it working again.

**Comment by fufesou** [comment]
@slewantoski  Hi, I've tested Corsair iCue, the macros are not broken after connection and input, both the local and remote sides.

```
iCue v. 4.33.138

Device: K55 RGB PRO v.1.1.13

Macro: Enter -> qwert
```

I will try upgrading iCue.

Should I test some other macros?

> I have to accept your decision and now search for another remote Software as i use macro keys a lot

Did you find some alternatives?

Can you please also help test with rustdesk 1.2.0, thanks.

1. Connect from Computer 2 to Computer 1. Do not input any keys.
    a. Go back to Computer 1. Test if iCue macros work?
    b. Then do some key inputs on Computer 2. Test if iCue macros work?
    c. Then disconnect. Test if iCue macros work?
2. Connect from Computer 2 to Computer 1. Do not input any keys. Then disconnect. Test if iCue macros work?

**Comment by fufesou** [comment]
I've upgraded iCUE to 5.3.
The macros work fine too.

And the local macros can be passed through the RustDesk session.

I can control the remote side like the keyboard is connected and iCUE is installed on the remote side.

**Comment by rustdesk** [comment]
Let's stop wasting time on this.
