### ISSUE TITLE
GUI: "Enable direct IP access" option is missing

### ISSUE THREAD

**Issue by cw2k** [rustdesk/rustdesk#4843]
### Bug Description

In short it's about this setting is:
![image](https://github.com/rustdesk/rustdesk/assets/3834079/31b0e4b5-d20a-4e89-a414-c136fbc5d424)
is missing on the Android clients.

### How to Reproduce

To TEST the setting **Enable direct IP access** I use to connecting to 127.0.0.1.
If it is not enable it says "Connection refused (os error 111)"

### Expected Behavior

On Linux and Windows this works as expected. 
However on Android connecting to 127.0.0.1 always 'says'  "Connection refused (os error 111)".

Of course later on I'll use some useful IP addresses like for ex. 10.0.0.36. 
However for debugging purpose and to minimize issue like local firewall blocks network access or client server version dont work together rustdesk must pass the "self-connect test".

Hmm is the maybe some "adb shell" hack to set that setting beside the GUI?
Background: I planning to use a smartphone with a broken display to turn a midi-keyboard into a "real" one.

### Operating system(s) on local side and remote side

Android 13

### RustDesk Version(s) on local side and remote side

1.1.10-1 -> 1.1.10-1

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/3834079/31b0e4b5-d20a-4e89-a414-c136fbc5d424)

**Comment by rustdesk** [comment]
They share the same code.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4827#issuecomment-1617103791
