### ISSUE TITLE
no gui in linux and enlightenment

### ISSUE THREAD

**Issue by Darkmagister** [rustdesk/rustdesk#4844]
### Bug Description

i can not see the rustdesk client window, i run the comand from a shell i see it running, i have the application running in the taskbar) but no window is showing

### How to Reproduce

```
$ rustdesk 
flutter: launch args: []
flutter: initializing FFI main
flutter: _appType:main,info1-id:404b9146d6d042789857480076a6cecd,info2-name:Debian GNU/Linux,dir:/home/dm/Documenti
flutter: _globalFFI init
flutter: _globalFFI init end
flutter: registerEventHandler native_ui native_ui
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
flutter: handled by uni links: false
flutter: [MultiWindowHandler] active window changed: [0]
```

### Expected Behavior

the normal window to show 

### Operating system(s) on local side and remote side

debian testing

### RustDesk Version(s) on local side and remote side

1.2.0 nightly of today

### Screenshots

```
$ rustdesk 
flutter: launch args: []
flutter: initializing FFI main
flutter: _appType:main,info1-id:404b9146d6d042789857480076a6cecd,info2-name:Debian GNU/Linux,dir:/home/dm/Documenti
flutter: _globalFFI init
flutter: _globalFFI init end
flutter: registerEventHandler native_ui native_ui
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
flutter: handled by uni links: false
flutter: [MultiWindowHandler] active window changed: [0]
```

### Additional Context

i also have gnome on the same machine and same OS, in gnome rustdesk works ok (i'm using the nightly because of the better keyboard support and wayland support)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by rustdesk** [comment]
> ### RustDesk Version(s) on local side 

in what not working?

**Comment by Darkmagister** [comment]
> > in gnome rustdesk works ok
> 
> in what not working?

as i wrote in enlightenment no windows is showing, it start but no gui (like it make the windows size 0,0) just the process running and windows is showing in taskbar but nothing to see to use it, in  gnome it's opening and showing up as normal

if you have any command that i can use to get more debug info i will help

**Comment by 21pages** [comment]
Can you uninstall it and check again?

**Comment by skydiablo** [comment]
same here on manjaro, if i start rustdesk via launcher icon, no windows is shown. if i run `rustdesk` via terminal all is working fine.

**Comment by darklinkworker** [comment]
@skydiablo are you adding any flags or arguments when running off the terminal?  I have no window with both the launcher icon and the terminal. I have tried the rpm version and the appImage. Which installed version are you using?

**Comment by skydiablo** [comment]
@darklinkworker no arguments on running in terminal, it is also unintended if rustdesk server service is running or not. i'm running manjaro and install it via:

```
pamac install rustdesk                                                                                                                   INT ✘ 
Warning: rustdesk is only available from AUR
Preparing...
Cloning rustdesk build files...
Generating rustdesk information...
Checking rustdesk dependencies...
Resolving dependencies...
Checking inter-conflicts...

To build (1):
  rustdesk  1.2.3-1    AUR
```

this is starting a complete compiling from sources, so i'm using the newest stuff, i think so. i also tried to delete the configs (`~/.config/rustdesk`) no success...

**Comment by skydiablo** [comment]
funny effects, if someone try to connect to my desktop, i get the "remote access allow" window and i can accept the request and all is working fine.

**Comment by darklinkworker** [comment]
I just saw that there is a flatpak version. I just installed it locally and I don't have an icon launcher to run it but off the terminal with `flatpak run com.rustdesk.RustDesk getid` it works and a window pops up. if I run that command without the `getid` part nothing happens. I am not seeing anything in the journal for logs so I can't comment if there is any errors. Still wondering if there is a verbose flag of some kind

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/5986

**Comment by rustdesk** [comment]
We still not find the cause, because we can not reproduce it.
Please try out the sciter version, I believe this can work as a workaround.
https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.7-x86_64-sciter.deb
https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.7-x86_64-sciter.flatpak

**Comment by rustdesk** [comment]
Could try out `export LIBGL_ALWAYS_SOFTWARE=1`

or run
`LIBGL_ALWAYS_SOFTWARE=1 rustdesk`

**Comment by rustdesk** [comment]
We can not fix Flutter, but you can now use the Sciter version, https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.3.0-x86_64-sciter.deb

**Comment by darklinkworker** [comment]
the sciter flatpak version works on my system. I don't know what the difference is but there is no flutter error and the id and password load now as well. Thanks for coming up with a solution and fix.
