### ISSUE TITLE
Fedora Build of 1.2.0 is dysfunctional

### ISSUE THREAD

**Issue by Cyborgscode** [rustdesk/rustdesk#4854]
### Bug Description

besides the current Server issue, all releases have, the Fedora 28 ( we have 38 now!! ) and centOS release are dysfunctional after installation:

- binary not in path
- desktop file not in path / FreeDesktop Rule Violation

Result: 

no desktopmenu entry to start rustdesk

How to Fix:

mv rustdesk.desktop to /usr/share/applications
edit rustdesk.desktop:
-Exec=rustdesk %u
+Exec=/usr/lib/rustdesk/rustdesk %u
OR mv /usr/lib/rustdesk/rustdesk /usr/bin/ 

### How to Reproduce

install it via dnf and try to start it

### Expected Behavior

-- see above

### Operating system(s) on local side and remote side

does not matter

### RustDesk Version(s) on local side and remote side

does not matter

### Screenshots

does not matter

**Comment by Cyborgscode** [comment]
$ ls -la /usr/bin/rustdesk
ls: Zugriff auf '/usr/bin/rustdesk' nicht möglich: Datei oder Verzeichnis nicht gefunden

as said: desktop file and binary are not in place 

and pls update to a current version of fedora for testing, F28 is 5 years old and obsoleted. Fedora is no LTS distro like Centos was ( which does not exists either anymore ) .

**Comment by Cyborgscode** [comment]
misclicked? :D

**Comment by 21pages** [comment]
Fedora 38 after install
![1688470193336](https://github.com/rustdesk/rustdesk/assets/14891774/6d42dfc4-67a5-45f5-b178-2dbe7892cd43)

**Comment by Cyborgscode** [comment]
Solved: 

After "dnf reinstall ./rustdesk-1.2.0-0.x86_64-fedora28-centos8.rpm"  symlink is present and rustdesk.desktop is in place and Desktop menu entry is present and functional.

**Comment by Cyborgscode** [comment]
The first install on a system does not create the links, the second ( reinstall ) does. So there is an issue with the rpm.

I confirmed this on a blank F37 installation.

**Comment by 21pages** [comment]
Could you uninstall it and check again?

**Comment by Cyborgscode** [comment]
the postinstall script looks fine to me.  Just one minor improvement: usr absolute paths to system cmds, you never know ;)

I uninstalled it, checked for binary and desktop file, both where correctly missing'
After installing it again, the first try succeeded.

**Comment by Cyborgscode** [comment]
There is nothing fancy about your postinstall script. It should work anytime.

**Comment by Cyborgscode** [comment]
Can you post the spec file pls?

**Comment by 21pages** [comment]
https://github.com/rustdesk/rustdesk/blob/master/res/rpm-flutter.spec

**Comment by Cyborgscode** [comment]
I'm not sure the install section is correct:

mkdir -p "%{buildroot}/usr/lib/rustdesk" && cp -r ${HBB}/flutter/build/linux/x64/release/bundle/* -t "%{buildroot}/usr/lib/rustdesk"
mkdir -p "%{buildroot}/usr/bin"
install -Dm 644 $HBB/res/rustdesk.service -t "%{buildroot}/usr/share/rustdesk/files"
install -Dm 644 $HBB/res/rustdesk.desktop -t "%{buildroot}/usr/share/rustdesk/files"
install -Dm 644 $HBB/res/rustdesk-link.desktop -t "%{buildroot}/usr/share/rustdesk/files"
install -Dm 644 $HBB/res/128x128@2x.png "%{buildroot}/usr/share/rustdesk/files/rustdesk.png"

i.e. /usr/share/rustdesk/files/ is implicit created by the %files section, you do not need to do it yourself.
Put this /usr/share/rustdesk/files/rustdesk.png also in the %files section and you won't need Install anymore.

I can see, that the $post scriptlet is executed , so all symlink cmds are run. There can only be some sort of race happening between the different sections.

BTW: Why are you using this complex construct "/usr/share/rustdesk/files" anyway? if you place the files at the correct places before you run the rpmbuild cmd, you can refer to the absolut paths and you do not need any other place you need to  link to. 

instead of cping /etc/systemd/system/rustdesk.service in place, just put it in place and refer to it in the %files section. This ensures 
a) it's correctly setupped in your buildroot, otherwise rpmbuild will fail, and 
b) rpm creates and deletes it , so you do not care about it, which you now do in your post and postun scripts.

This will make thing easier and has less chance to produce sideeffects  we see atm.

**Comment by Cyborgscode** [comment]
I called in some testers for other Fedora installtions and hope to get some more base data tonight.

**Comment by 21pages** [comment]
Ok, could you make a pull request ?

**Comment by Cyborgscode** [comment]
for a new spec file? You need more than just that change, as a script/buildsystem needs to prepare the buildroot before the build happens like this does:

[build.sh.zip](https://github.com/rustdesk/rustdesk/files/11949460/build.sh.zip)

**Comment by uber6** [comment]
I'm no developer and sorry if my input isn't any valuable, but I installed Rustdesk 1.20 on Fedora 38 and I'm experiencing the same issue. I can see the binary in `/usr/lib/rustdesk` but there is neither bin or symlink in the `/usr/bin`.

**Comment by Cyborgscode** [comment]
just "reinstall" the rpm.

**Comment by uber6** [comment]
There was error on my post. I installed 1.2.1, and it was installed in this morning. I just reinstalled it and the problem is fixed. What would cause such error? (Only trying to learn).

**Comment by Cyborgscode** [comment]
Best would be, to ask the RPM dev team.
