### ISSUE TITLE
Siki info about Flatpak needs updating

### ISSUE THREAD

**Issue by Marzal** [rustdesk/rustdesk#4855]
### Bug Description

https://github.com/rustdesk/rustdesk/wiki/Run-flatpak
Shows
`flatpak run org.rustdesk.rustdesk`
but once installed is
`RustDesk                   com.rustdesk.RustDesk                         master      rustdesk-origin user
`

### How to Reproduce

`flatpak run org.rustdesk.rustdesk`

### Expected Behavior

Wiki points to `com.rustdesk.RustDesk`

### Operating system(s) on local side and remote side

Linux

### RustDesk Version(s) on local side and remote side

1.2

### Screenshots

![imagen](https://github.com/rustdesk/rustdesk/assets/2069735/ba9a86a6-1299-4cae-a328-c6a22e211027)

### Additional Context

In the code there are mentions to both com.* and org.*

https://github.com/search?q=repo%3Arustdesk%2Frustdesk+.rustdesk.rustdesk&type=code

**Comment by rustdesk** [comment]
chagned

**Comment by rustdesk** [comment]
changed
