### ISSUE TITLE
OS Password function does not enter the password

### ISSUE THREAD

**Issue by silmaril42** [rustdesk/rustdesk#4856]
### Bug Description

In Rustdesk 1.2.0 release (as well as some nightlies) I cannot use the function "OS Password" any more.

When clicking on the menu item
![grafik](https://github.com/rustdesk/rustdesk/assets/31900904/7b14836c-10a0-48dd-b926-f40607c35bf2)
the dialog to enter the password opens and there seems to be no way to make Rustdesk type this password into the connected host system.

It makes no difference whether I click on the text "OS Password" or on the pencil icon.

### How to Reproduce

Open a Rustdesk connection and try to use the "OS Password" function to enter a password into the host system.

### Expected Behavior

Clicking on the pencil icon should open the dialog where the password can be set (this works as expected).

Clicking on the menu item text should not open this dialog and directly enter the password into the host system (instead this currently opens the same dialog).

### Operating system(s) on local side and remote side

Windows 11 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0

### Screenshots

![grafik](https://github.com/rustdesk/rustdesk/assets/31900904/7b14836c-10a0-48dd-b926-f40607c35bf2)

### Additional Context

This looks like a small bug in the UI code.
It seems the clickable area of the pencil icon is using the same room as the menu item text, which makes it impossible to click onto the text.

This war different in Rustdesk 1.1.9, in which the pencil icon could be clicked separately.

Using 1.1.9 on the client side is the only workaround I was able to find.

I'd appreciate a hint if there is a workaround in 1.2.0 to use this function!
Maybe there already is a keyboard shortcut that can be used?

**Comment by rustdesk** [comment]
fix merged, please try out tomorrow's nightly build.

**Comment by silmaril42** [comment]
That was really quick - I am impressed!

And I can confirm it's working now :-)

**Comment by matthiasg** [comment]
I have that issue from ios towards macos just now. I can enter a passeord in the dialog inside rustdesk , but nothing happens anywhere else
