### ISSUE TITLE
404: https://rustdesk.com/server  

### ISSUE THREAD

**Issue by Cyborgscode** [rustdesk/rustdesk#4858]
### Bug Description

https://rustdesk.com/server is refered to in the bottom line as "for a faster connection set your own Server up."
but the webserver does not know about it:

404 Not Found
nginx/1.18.0 (Ubuntu)

### How to Reproduce

click on "for a faster connection set your own Server up."

### Expected Behavior

a data driven webpage ;)

### Operating system(s) on local side and remote side

--

### RustDesk Version(s) on local side and remote side

--

### Screenshots

none

### Additional Context

---

**Comment by 21pages** [comment]
reproduced

**Comment by rustdesk** [comment]
fixed by change nginx settings.
