### ISSUE TITLE
Dual screen remote dual screen

### ISSUE THREAD

**Issue by chenjianhua** [rustdesk/rustdesk#486]
I use a computer with two screens to remotely control a computer with two screens. It is hoped that two screens can be displayed at the same time. This is an awesome idea.

**Comment by rustdesk** [comment]
Yes, it is awesome, but this involves a lot of code change, already in the to-do list many month ago.

**Comment by techflashYT** [comment]
Any update on this?  Would love to use rustdesk as a software-based dual monitor solution over my LAN.

**Comment by ForsakenRei** [comment]
I hope we can do this as well, currently I think we can have two connections to one PC(though in my case I need reopen rustdesk windows to start a new connection) but the problem is the two different sessions follows the remote focus, which means I cannot use the two screen on the remote side as both sessions will always display the same focusd screen.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/918

**Comment by daTony16822** [comment]
@ForsakenRei 
How could you get 2 connections to same computer? I am trying but failing.

thank you

**Comment by daTony16822** [comment]
@ForsakenRei 
I am getting the same problem. Did you have a chance to look into that?
Do you need help?

**Comment by wizzyto12** [comment]
Is there any plans for implementing this soon? Its kind of a bummer for us...

**Comment by oodonnell** [comment]
was looking to change to rustdesk after my teamviewer gave issues

this is stopping me from being able to, I usually sign in twice to the same desktop and use monitor 1 on one client and monitor 2 on the other.. but both connections will follow what i select on the other nullifying the objective

I can't continue to use this software while this isnt a functionality

**Comment by Lordvader81** [comment]
This application works great for single monitor remote login sessions and while you really can't complain considering that it's free, however if the Devs did add in the ability to display two different screens at the same time somehow i'm sure there are plenty of people that would be willing to pay a small but fair amount ...1$ Per Month or somthing like that.
with emphasis on small & fair .... 
A reminder to the Dev team that this is the reason why millions and millions of users are users are moving away from application applications that were supposed to be free or have very low user fees such as anydesk ..... I understand that a lot of these companies moved in this direction because well they are companies and they need to make money However most of them are just plain greedy with their charge per user per PC mentality...

think about it .... there are billions of active PC users that require remote login capabilities especially now but times are changing with the workforce ... if you're charging an average of$1.00 a month with no other restrictions you're making a billion dollars a month just in subscription fees....... Why get greedy ??.. I mean it really makes no sense to me to be honest.

**Comment by oodonnell** [comment]
> This application works great for single monitor remote login sessions and while you really can't complain considering that it's free, however if the Devs did add in the ability to display two different screens at the same time somehow i'm sure there are plenty of people that would be willing to pay a small but fair amount ...1$ Per Month or somthing like that. with emphasis on small & fair .... A reminder to the Dev team that this is the reason why millions and millions of users are users are moving away from application applications that were supposed to be free or have very low user fees such as anydesk ..... I understand that a lot of these companies moved in this direction because well they are companies and they need to make money However most of them are just plain greedy with their charge per user per PC mentality...
> 
> think about it .... there are billions of active PC users that require remote login capabilities especially now but times are changing with the workforce ... if you're charging an average of$1.00 a month with no other restrictions you're making a billion dollars a month just in subscription fees....... Why get greedy ??.. I mean it really makes no sense to me to be honest.

I ended up finding one online that I've been using for a week now that I paid $6.95 for the full year and has this functionality and rthe rest of the thing I was looking for, but im not about to advertise it on here as that would be disrespectful

**Comment by rustdesk** [comment]
In our milestone.

**Comment by paulb39** [comment]
Could I get clarification on this enhancement? Since there many different levels of multi-monitor support. In the above request, the user has 2 monitors on the computer they are remoting into. But if I had 2 monitors on my computer, and 1 on the computer I was remoting into, would I be able to use dual monitors? I have been on a quest for remote software that can do that, but only thing that seems to have that ability is rdp / xrdp (and nothing for osx)

**Comment by paulb39** [comment]
Could we update the enhancement request to work the other way? Only care about the client machine monitors? If I remote into a laptop without any monitors connected, but I have 2 on my machine, I'd want to be able to use my 2 monitors in extended mode.

**Comment by ForsakenRei** [comment]
Since you are asking for something totally different from the original request it will probably be a separate feature request then.

And I'm not quiet understand what do you mean in extended mode, unless you have a dummy plug which support ultrawide then you can drag the window across multiple monitors from host, otherwise I don't think it's possilbe to attach host monitors to the remote by any means?

**Comment by paulb39** [comment]
The only protocol I been able to find that supports it is RDP. I have 2 monitors on my computer, I remote into a laptop without any monitors attached - RDP does all the display rendering from the client machine, so I can just extend the displays- it renders it like if I had 2 monitors hooked up directly to the laptop.

**Comment by Lordvader81** [comment]
Ultraviewer does this.

 

It doesn't allow multiple streams to the same PC … Yet… 

But you can view both monitors at the same time and drag the remote screen box across both of your monitors essentially allowing you to dual screen the remote machine…

 

Hope this helps.

**Comment by daTony16822** [comment]
Thank you for the suggestion.
There is plenty of paid programs doing it. The topic of this group is about improving Rustdesk which is a free solution.

**Comment by fragtion** [comment]
What about connecting to more than one remote computer? At the moment all of the tabs consolidate in the same window. This can make it difficult to work between several remote computers because you need to switch tabs in the same Rustdesk instance. It would be nice if we could detach a tab from that tab group, into a new tabbed window. It's possible to do this with most browsers for instance. This was always a headache for me with AnyDesk, so it's a bit disappointing to see that RustDesk shares the same inherent limitation ..

**Comment by ForsakenRei** [comment]
> What about connecting to more than one remote computer? At the moment all of the tabs consolidate in the same window. This can make it difficult to work between several remote computers because you need to switch tabs in the same Rustdesk instance. It would be nice if we could detach a tab from that tab group, into a new tabbed window, and move that to another monitor... Similar to what most Web Browsers do when you drag a tab out of the window. It creates a new window with the new tab, and additional tabs can be added to that.
> 
> This was always a headache for me with AnyDesk, so it's a bit disappointing to see that RustDesk shares the same inherent limitation ..

Anydesk allows open two different instances but connect to same remote to display different screens of one machine. But since they changed their price model this is only available to paid users...

**Comment by Lordvader81** [comment]
Ultra viewer does that too bro …

Look, I really hate to say it and I love rust desk but it just simply does not offer any of the options that I require therefore I only use it as an emergency redundant fall back….

 

ultra viewer does exactly what I needed to do and it works 95% of the time ….

obviously because it's not open source we know what it's doing … it's offering a good product with lots of updates and bug fixes trying to gather as many users as possible, once that happens they are going to sell to a larger conglomerate for hundreds of millions of dollars which in turn means that they are going to start charging a monthly subscription like everybody else but until then ultra viewer is what I'm using because it just works.

 

Skye Perez

C: 281-541-5038

6315-B  FM 1488 Rd # 243 Magnolia, Texas 77354

**Comment by daTony16822** [comment]
> What about connecting to more than one remote computer? At the moment all of the tabs consolidate in the same window. This can make it difficult to work between several remote computers because you need to switch tabs in the same Rustdesk instance. It would be nice if we could detach a tab from that tab group, into a new tabbed window, and move that to another monitor... Similar to what most Web Browsers do when you drag a tab out of the window. It creates a new window with the new tab, and additional tabs can be added to that.
> 
> This was always a headache for me with AnyDesk, so it's a bit disappointing to see that RustDesk shares the same inherent limitation ..

> 

Hi,
I am able to open 2 instances of RustDesk and connect to 2 different computers. I have one instance on my screen #1 and another one on my screen #2.  
Try opening 2 instances before connecting maybe?

**Comment by rustdesk** [comment]
@Kingtous it is time to start this project.

**Comment by yass-SC** [comment]
I also want to note that this feature will be very useful for me.

**Comment by iwottan** [comment]
Great work on RustDesk. The devs had done amazing job so far. I see it as a very good balance between needed features and effectivenes.
If it is possible to run multiple instances of Rustdesk on the local machine (I know you can do it now)  and the remote side has two monitors and you are also able to choose different monitors for the different instances, that would be great. The use case I can see here is 1. When the local side also has two monitors, you can run once instance on every monitor and the experience will be the same as if you are working on the remote side (when you are in full screen). 2. When you have one monitor on the local side (like a laptop), you can use Virtual desktop (Win10/11, Linux has it integrated) and you can have an instance for every virtual desktop and switch faster between the two monitors on the remote.
As for the suggested payment part. I personally support very much the model to have a completely free (community) edition that can be used by everyone and a paid one (enterprise) solution that can be either customized and/or different level of support. And the donation (crypto, buy me a coffee) should always be on the table as an option.

**Comment by solo2424** [comment]
@Kingtous have you looked into this at all? I think many people would benefit from this feature. I beleive most people drawn to open source in general are typically a little more tech savvy, and all the tech savvy people I know have multiple monitors.

**Comment by lucasmontec** [comment]
Is it possible to have dual screens from a pc streaming with only 1 screen?

**Comment by fragtion** [comment]
> Is it possible to have dual screens from a pc streaming with only 1 screen?
You can try with usbmmidd, or similar software, to create a virtual monitor on the system which Rustdesk can then pass through

**Comment by caburet** [comment]
I also want to note that this feature will be very useful for me too!

**Comment by solo2424** [comment]
This feature would be greatly appreciated.

**Comment by Bradtus** [comment]
just chiming in to say this would be very useful to me too

**Comment by pantxu** [comment]
Love to see this feature too! I have just test rustdesk and I love it but can't use it due need for dual monitor setup

**Comment by Fr1z** [comment]
I'm with you guys, this feature will be something that takes rustdesk to the next level!

**Comment by dignow** [comment]
Hi guys. Would you mind implementing multiple controls like anydesk?

The connections appear to be independent of each other.
You may have to connect several times to do the work.

https://github.com/rustdesk/rustdesk/assets/136106582/a27f5f09-2396-4bac-8653-6df2dc18d789

**Comment by ForsakenRei** [comment]
> Hi guys. Would you mind implementing multiple controls like anydesk?
> 
> The connections appear to be independent of each other. You may have to connect several times to do the work.
> 
>  ad.mp4

I forgot which version but you can connect to identical connections to the same machine which has multiple monitors(which techincally enabled multi monitors support), the only thing is that at that time they shared the same focus from remote side, which means if your remote focus goes from one monitor to another, both connection will jump to the same monitor. I'm not too familiar with the actual implementation but I guess it's something about decoupling remote focus and current session...?

**Comment by dignow** [comment]
> it's something about decoupling remote focus and current session...?

The remote side currently share the same screen capturer.
The screen capturer does not care about the sessions. It sends the pictures to all the subscribers(the sessions).

**Comment by iwottan** [comment]
Great work!! Is the last merge included in 1.2.3 nightly?

**Comment by dignow** [comment]
No, more tests are needed. And there's still a bug.

**Comment by MoHara23** [comment]
Dear, I saw the video from [dignow](https://github.com/dignow) commented [3 weeks ago](https://github.com/rustdesk/rustdesk/issues/486#issuecomment-1708657433) •

I try to to the same on my free Rustdesk, but can't get it to work to see simultaneously all monitors .

Is it only for paid versions?

**Comment by msymeonides** [comment]
This would be a fantastic feature to have!

**Comment by rustdesk** [comment]
Ready in nightly build now. https://twitter.com/rustdesk/status/1714199082640581039

**Comment by Lordvader81** [comment]
Well, I must be an idiot because I can't figure it out ...

Is there some feature or new button that I'm missing?
This thread has been closed as solved but I still can't figure out how to get multi-instances of rest desk open to the same computer so that it can be multi monitor which was the whole reason for the original request ...

Can somebody guide me through what needs to be done or a specific option that needs to be selected to make it work ?

**Comment by MoHara23** [comment]
I just tried it : installed on the local computer.  Connected to the remote pc with 3 screens , no luck even after configuring the settings as is shown on the video in this thread. 2nd : Installed it on the remote pc. Same settings .

and it works .

so what is your issue ?


Some bugs with keyboard strikes .. but worked with it an hour and screens are connected very good.

**Comment by msymeonides** [comment]
Yeah this works really nicely if you just make sure to update Rustdesk on both sides of the connection.

**Comment by Lordvader81** [comment]
What video on the other thread ?
Can somebody please hot link the video here please ?

And yes I already have the latest version downloaded from Github installed on both computers but I see no obvious configuration options for it ....

**Comment by cchc-tliu** [comment]
> What video on the other thread ? Can somebody please hot link the video here please ?
> 
> And yes I already have the latest version downloaded from Github installed on both computers but I see no obvious configuration options for it ....

Are you running the nightly build?

**Comment by Jodu555** [comment]
The Video of this is shown in the Twitter Thread: https://twitter.com/rustdesk/status/1714214654174490829

**Comment by MoHara23** [comment]
Video :

https://github.com/rustdesk/rustdesk/pull/6064

**Comment by Lordvader81** [comment]
I have the newest version available here on Github but I don't have those options ...

![image](https://github.com/rustdesk/rustdesk/assets/120199915/761437af-e215-49e0-8c1e-4af7333020ce)

![image](https://github.com/rustdesk/rustdesk/assets/120199915/2e35331c-0fe7-4eff-b331-4b8d51b9d1d2)

**Comment by MoHara23** [comment]
It's must be version 1.2.4 (nightbuild )

**Comment by Simbaclaws** [comment]
when will we see a arm m2 mac os build that I can test for multiple monitors? my server runs on mac os.

Would love to ditch teamviewer for this...

**Comment by xjoker** [comment]
3 monitors only show 2 😂

**Comment by dignow** [comment]
@xjoker Do you have 3 or more monitors on both sides? If one side has only 2 monitors, RustDesk will open 2 remote windows.

**Comment by xjoker** [comment]
> @xjoker Do you have 3 or more monitors on both sides? If one side has only 2 monitors, RustDesk will open 2 remote windows.

Yes, there are 3 monitors being remotely accessed, with 2 monitors on the initiating side. How can all 3 monitors be viewed?

**Comment by dignow** [comment]
You need to open an individual remote window manually.

https://github.com/rustdesk/rustdesk/assets/136106582/c9cb29ab-d25f-4083-a3cb-3cd538260ccd

**Comment by xjoker** [comment]
> You need to open an individual remote window manually.
> 
>  new-individual.mp4

![image](https://github.com/rustdesk/rustdesk/assets/7802841/dc421a5c-dd4e-4796-9470-0ab405de3a8c)


Sorry, I didn't see this feature. My current version is 1.2.4, build date 2023-11-25 00:23.

**Comment by dignow** [comment]
![image](https://github.com/rustdesk/rustdesk/assets/136106582/af39b0c4-2241-43d9-bb9e-cb2ab62877fa)

There should be a monitor selecting menu if the remote side has multiple monitors. Are you sure about it?

Or there's a bug in this case, 2 monitors -> 3 monitors

**Comment by xjoker** [comment]
> ![image](https://private-user-images.githubusercontent.com/136106582/285597339-af39b0c4-2241-43d9-bb9e-cb2ab62877fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjM1NjUsIm5iZiI6MTcwMDkyMzI2NSwicGF0aCI6Ii8xMzYxMDY1ODIvMjg1NTk3MzM5LWFmMzliMGM0LTIyNDEtNDNkOS1iYjllLWNiMmFiNjI4NzdmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxNDQxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Zjg1ODI2NjVkYjZkNDkyM2YyN2NiNWFkNzVlNThlNWNiNDE5MzkxMjc4Mjc0ZGQxNjc2MWNiODRjOGY0NDE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fOq6mNjp5vxDlGWGiuxEl1Orz4nwbeKSYFx7KVUSESg)
> 
> There should be a monitor selecting menu if the remote side has multiple monitors. Are you sure about it?
> 
> Or there's a bug in this case, 2 monitors -> 3 monitors

I vaguely remember that when I first opened it, there indeed was a monitor selection option, but it disappeared quickly. I haven't seen it since then.

**Comment by dignow** [comment]
I've tried this case, but cannot reproduce your issue.
I can always see the monitor selecting menu.

Can you please upload a video to show how to reproduce it?

**Comment by dignow** [comment]
Can you see the monitor selecting menu after unchecking this options?

![image](https://github.com/rustdesk/rustdesk/assets/136106582/528ae9a3-14b0-45a9-b2a8-7e7c4ec15c7e)

**Comment by xjoker** [comment]
> I've tried this case, but cannot reproduce your issue. I can always see the monitor selecting menu.
> 
> Can you please upload a video to show how to reproduce it?


https://github.com/rustdesk/rustdesk/assets/7802841/d407ff23-ca89-4b18-94ed-ee0070f21160

**Comment by xjoker** [comment]
> Can you see the monitor selecting menu after unchecking this options?
> 
> ![image](https://private-user-images.githubusercontent.com/136106582/285598531-528ae9a3-14b0-45a9-b2a8-7e7c4ec15c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjU3MDcsIm5iZiI6MTcwMDkyNTQwNywicGF0aCI6Ii8xMzYxMDY1ODIvMjg1NTk4NTMxLTUyOGFlOWEzLTE0YjAtNDVhOS1iMmE4LTdlN2M0ZWMxNWM3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxNTE2NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDM4MWE1ZDI1NzZjNDZiMmRjODk2M2ZlMDg5OWFiODY0Mzg2ZjRiYzk2YzNjNmM0MzBjNTU2NzBhNGM4NzAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n6O2DZFs8aiw8gRCfSQewKrtw0TLKSWa3WT7lVwqlxI)

I have tested selecting some options and also tried not selecting any, but none appeared.

**Comment by dignow** [comment]
> I have tested selecting some options and also tried not selecting any, but none appeared.

So  you cannot see the menu even you do not open multi remote windows?

Can you please try 1.2.3 on both sides? To check if the monitor selecting menu is there.

**Comment by xjoker** [comment]
> > I have tested selecting some options and also tried not selecting any, but none appeared.
> 
> So you cannot see the menu even you do not open multi remote windows?
> 
> Can you please try 1.2.3 on both sides? To check if the monitor selecting menu is there.

Before upgrading to version 1.2.4, I had already tested version 1.2.3. It was completely unable to see any screens other than screen number 1.

**Comment by xjoker** [comment]
> **[dignow](/dignow) ** c

 am currently using the latest nightly version and can now use the multi-screen remote feature normally. Many thanks to @dignow 
 for the thorough troubleshooting.”

**Comment by marktohark** [comment]
https://github.com/rustdesk/rustdesk/discussions/6676#discussion-5958947

**Comment by maxlieb** [comment]
got this working withe the nightly version, now there is just one problem left....
how do I a window open on the remote computer from one screen to the other?
when I try doing that... the mouse stops at the edge of the display and does not continue to the next screen!

**Comment by BMI24** [comment]
I second @maxlieb. It would be nice to be able to drag Windows (maybe files too) from one screen to the next. Otherwise, this feature is great

**Comment by solo2424** [comment]
Being able to save layouts would be great too. Currently, I have to move
the displays to the correct window (sometimes) and then toggle full screen,
then toggle to minimize the menu bar. It would be great to set all that and
have it stay consistent.

But this feature is amazing and has now allowed me to completely ditch
TeamViewer!

**Comment by Lordvader81** [comment]
I think they have done an amazing job adding this feature in which was previously lacking...
Even though I could probably use some more tweaking I think overall it does a very good job ... Thanks rust desk team !!

**Comment by rzmuda** [comment]
So if my client and I have the latest version. Mult monitor for me to see on the client will work now. 
Does the client version have to be installed not just executed?

**Comment by FurqanSaeed** [comment]
Great job, team @rustdesk  💖

Implementing the remote dual screen display feature is a huge achievement. This will make a big difference in productivity by reducing the time spent swapping between remote windows. Your hard work and dedication are truly appreciated. Bundle of thanks for making this happen!

**Comment by FraYoshi** [comment]
I'm guessing this is a Desktop only feature.. as on Android seems like it is not (currently) possible... 🤔
Which is the main use-case, at least for me.. to monitor and use on the go, with a keyboard attached at the phone, eventually with an attached monitor.

Hope it will be ported to Android too :)
