### ISSUE TITLE
1.2.0  still with Linux to Linux keyboard layout issues

### ISSUE THREAD

**Issue by Cyborgscode** [rustdesk/rustdesk#4861]
### Bug Description

OS on both sides: Fedora 37
both regional settings: german

instead of a german keyboard layout, the remote side uses an english keyboard.

### How to Reproduce

--

### Expected Behavior

--

### Operating system(s) on local side and remote side

Fedora Linux -> Fedora Linux 

### RustDesk Version(s) on local side and remote side

1.2.0 > 1.2.0

### Screenshots

--

### Additional Context

--

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
