### ISSUE TITLE
Can't use Hostname for direct ip access

### ISSUE THREAD

**Issue by deganl** [rustdesk/rustdesk#4862]
### Bug Description

I try to connect to a other client in my lan network. When i use the IP address as ID, everything work as expected. When i use the hostname, then i get the error message "ID not found".
Like in the FAQ "I only use RustDesk for a few devices on my local network with no Internet connectivity... Can I still use RustDesk with direct ip access?" described: "On the client you are connecting from you can now input the Local IP address or host name the address box and click connect.".

### How to Reproduce

Try to connect via hostname

### Expected Behavior

Should work with ip and hostname

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0 (tried also with 1.1.9)

### Screenshots

---

**Comment by rustdesk** [comment]
https://github.com/search?q=repo%3Arustdesk%2Frustdesk+hostname&type=issues
