### ISSUE TITLE
crash on startup on linux mint 

### ISSUE THREAD

**Issue by Benance** [rustdesk/rustdesk#4877]
### Bug Description

apter upgrade to 1.2.0, the rustdesk app crashes on startup without any error message
here are the logs when I launch rustdesk app in command line:
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(57)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed
Abandon (core dumped)

### How to Reproduce

update rustdesk from 1.1.9 to 1.2.0 on linux mint 20.3 cinnamon then launch rustdesk app

### Expected Behavior

the app launches correctly

### Operating system(s) on local side and remote side

linux mint

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

![screenshot](https://github.com/rustdesk/rustdesk/assets/33089007/b86e52b8-7196-4719-8eff-ea815e1b80c0)

**Comment by rustdesk** [comment]
https://github.com/flutter/flutter/issues/85460

**Comment by rustdesk** [comment]
try out  `LIBGL_ALWAYS_SOFTWARE=1 rustdesk`
