### ISSUE TITLE
Build with Github Actions broken

### ISSUE THREAD

**Issue by jacotec** [rustdesk/rustdesk#4881]
### Bug Description

Building my own version with hardcoded secrets via GitHub Actions does not work anymore since the last commit to the workflow files.

Error message:

```
[Invalid workflow file: .github/workflows/flutter-nightly.yml#L15](https://github.com/jacotec/rustdesk/actions/runs/5464754737/workflow)
The workflow is not valid. .github/workflows/flutter-nightly.yml (Line: 15, Col: 19): Invalid input, upload-tag is not defined in the referenced workflow.
```

### How to Reproduce

Just start the Github Action as usually

### Expected Behavior

The build should work

### Operating system(s) on local side and remote side

Github

### RustDesk Version(s) on local side and remote side

Github

### Screenshots

See error message above

**Comment by jacotec** [comment]
Found the issue, created PR #4882

**Comment by rustdesk** [comment]
Thx
