### ISSUE TITLE
Windows 8 not supported in version 1.2.0

### ISSUE THREAD

**Issue by Lunixfan** [rustdesk/rustdesk#4886]
### Bug Description

The version 1.1.9 worked wonderfully, but when I start the version 1.2.0 I only get a black screen. 
Can you do something about it and make it backwards compatible? 

Why does version 1.1.9 work without problems but not 1.2.0?

### How to Reproduce

starting the 1.2.0 exe file and it only shows black  you cannot see ID or Passwort but if you click ok then it will connect but if you are connected then the screen is black.

### Expected Behavior

maybe fix ? ^^

### Operating system(s) on local side and remote side

Windows 8

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/130404873/192a94a5-9a43-4a13-a65c-672e700a5a41)

**Comment by dinger1986** [comment]
Windows 8 isnt supported by MS anymore, did you try this version of RustDesk? https://github.com/rustdesk/rustdesk/releases/download/1.2.0/rustdesk-1.2.0-x86-sciter.exe

**Comment by Lunixfan** [comment]
Okay, the rustdesk-1.2.0-x86-sciter.exe also had the black screen just now, I tried it again and it worked the second time. Thank you, then I will use the sciter version for older PCs :)

Why is the version not listed or did I miss it in the releases?

**Comment by dinger1986** [comment]
must have missed it, it was in the list :)

**Comment by Lunixfan** [comment]
I had not clicked on Show all assets xD 

What is the difference in the scite between the one without scite?

**Comment by dinger1986** [comment]
must have been that.

I have no idea, just assumed there was a reason for the other one and with it being x86 I assumed it would be for older computers.

**Comment by Lunixfan** [comment]
All right :) Thank you for the quick help. This fixes the error now :)

I just see that the one-time password is empty, that seems to be a bug in the scite version.

**Comment by Lunixfan** [comment]
Okay, after another restart, the one-time password is also available, funny. But happy with that. Thank you
