### ISSUE TITLE
1.2.0 prevent screensaver and monitor off on Windows at local side

### ISSUE THREAD

**Issue by Max33Verstappen** [rustdesk/rustdesk#4888]
### Bug Description

On 1.2.0, when the window of the remote side is **not minimized**, at the local side, the screensaver is prevented from running and the display never turned off (set in the "Power Option").

### How to Reproduce

Establish a connection. Do not minimize that window.

### Expected Behavior

The local side shall turn off the monitor and run the screensaver as intended.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0

### Screenshots

N/A

**Comment by rustdesk** [comment]
expected
