### ISSUE TITLE
Can Rustdesk forward traffic between two PC

### ISSUE THREAD

**Issue by freebooterish** [rustdesk/rustdesk#489]
Thank you very much for your excellent project. I have a question to ask. As shown in the attached image, Can A access Web service in C  through RUST Server and  B, I have installed Rust Client on A,B.
Thanks.

<img width="525" alt="temp" src="https://user-images.githubusercontent.com/1250352/167296371-e2406db4-16c4-43e9-91e2-6cdd1aba7135.png">

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/487
