### ISSUE TITLE
rdp via shortcut

### ISSUE THREAD

**Issue by IzunaMoon** [rustdesk/rustdesk#4890]
### Bug Description

hi i use to use shortcut for rdp session by changing connect in de shortcut to rdp

here is a axample
changing this
"C:\Program Files\RustDesk\rustdesk.exe" -connect xxx xxx xxx
to this
"C:\Program Files\RustDesk\rustdesk.exe" -rdp xxx xxx xxx

in 1.19 this did owrk perfect a opens as a rdp session but seems in 1.2.0 rdp sessions refuse to start this way it works when i do it via de cleint right mouse a saying rdp but i cant do it anymore in 1 shortcut

extra behavour i notice is dat de russtdesk cleint does open but it is unable to coneect to de server at all until i re open it or use a connect shortcut

### How to Reproduce

changing this
"C:\Program Files\RustDesk\rustdesk.exe" -connect xxx xxx xxx
to this
"C:\Program Files\RustDesk\rustdesk.exe" -rdp xxx xxx xxx

### Expected Behavior

when i change this
"C:\Program Files\RustDesk\rustdesk.exe" -connect xxx xxx xxx
to this
"C:\Program Files\RustDesk\rustdesk.exe" -rdp xxx xxx xxx

rustdesk should open a rdp session like in 1.1.9

### Operating system(s) on local side and remote side

windows 11 pro to windows server 2022

### RustDesk Version(s) on local side and remote side

1.2.0 to 1.1.9

### Screenshots

![example](https://github.com/rustdesk/rustdesk/assets/132285275/79d441a8-195e-49a2-9bbc-f6c25b621d1f)

### Additional Context

running a local server sins version 1.1.9

**Comment by test2a** [comment]
Yes. 

I concur with this bug. 

Rdp connection should be easier. The second window to be kept open, why Is that necessary and can it be made easier to use rdp ? 

If there is a checkbox in the dropdown "use rdp" so when you click on the computer, it should open rdp connection automatically.

**Comment by IzunaMoon** [comment]
we use it for hour business as we have over 300 computers a dat allow de entire it team to easy allow to connect to pc a servers

sins de address book feature doesnt work we use shortcuts as hour addres book essentaily

**Comment by IzunaMoon** [comment]
> Yes.
> 
> I concur with this bug.
> 
> Rdp connection should be easier. The second window to be kept open, why Is that necessary and can it be made easier to use rdp ?
> 
> If there is a checkbox in the dropdown "use rdp" so when you click on the computer, it should open rdp connection automatically.

we use it for hour business as we have over 300 computers a dat allow de entire it team to easy allow to connect to pc a servers

sins de address book feature doesnt work we use shortcuts as hour addres book essentaily

**Comment by rustdesk** [comment]
fix is merged, please test the nightly later (under buiding)

**Comment by IzunaMoon** [comment]
it is resolve thanks for de quick fix
