### ISSUE TITLE
Specific but unknown ID keeps appearing in list of recent sessions

### ISSUE THREAD

**Issue by chris-31337** [rustdesk/rustdesk#4891]
### Bug Description

In the list of recent sessions, an unknown ID 1640075623 keeps appearing in my Rustdesk client (on Windows 10) for no obvious reasons. It was certainly not manually entered and connected to. It is also always shown as offline.

Interestingly, the same happened on another Client running Kubuntu and it was the SAME ID that appeared there (1640075623), so it is probably an OS-independent phenomenon. 

Note: We are hosting our own rustdesk-server with Docker.

### How to Reproduce

It occurs randomly after several normal connections and if deleted, returns after a while. 

### Expected Behavior

Only connections that actually happened should be listed as recent sessions.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0

### Screenshots

<img width="175" alt="weirdID" src="https://github.com/rustdesk/rustdesk/assets/136456291/a11adc9b-67b8-4132-bf6a-5c21057aec9b">

**Comment by rustdesk** [comment]
fixed in nightly.
