### ISSUE TITLE
The desktop file will be created auto after opening the app

### ISSUE THREAD

**Issue by YHYJ** [rustdesk/rustdesk#4896]
### Bug Description

If the `~/.config/autostart/rustdesk.desktop` file does not exist, it will be created auto after opening the app, which will cause rustdesk to auto start unexpectedly.
Currently I create an empty `~/.config/autostart/rustdesk.desktop` file to avoid this problem.

### How to Reproduce

Just open rustdesk.

### Expected Behavior

No `~/.config/autostart/rustdesk.desktop` file.

### Operating system(s) on local side and remote side

local side: Arch Linux

### RustDesk Version(s) on local side and remote side

Arch Linux rolling

### Screenshots

Before opening rustdesk: `~/.config/autostart/rustdesk.desktop` file does not exist.
After opening rustdesk: `~/.config/autostart/rustdesk.desktop` file exist

### Additional Context

The rustdesk-git package installed from the AUR, but I think it might not be an issue with the packager

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/1954f905af3293c0b3e7ead782978fb743af5932 it still auto creates, but only if there are `--server` process, no plan to change this behavior for the time being.
