### ISSUE TITLE
After the program is installed, file transfer cannot be used. 

### ISSUE THREAD

**Issue by BSLZNB-XCT** [rustdesk/rustdesk#4897]
### Bug Description

After the program is installed, file transfer cannot be used. 

### How to Reproduce

1. After closing all software programs in the task manager, re-run the software to use file transfer.
2. But at this time, after closing the software, all connections are disconnected;
3. I found that after the second step, the software service is not started.
What should I do.

### Expected Behavior

Use file transfer normally.

### Operating system(s) on local side and remote side

window 11-> 10

### RustDesk Version(s) on local side and remote side

https://github.com/rustdesk/rustdesk/releases/tag/1.2.0

### Screenshots

![Screenshot 2023-07-07 102959](https://github.com/rustdesk/rustdesk/assets/53990362/318d78c7-12bd-4c16-a498-d4db7f3fdceb)

**Comment by rustdesk** [comment]
1.2 both sides please.
