### ISSUE TITLE
Cannot connect through SOCKS5 proxy

### ISSUE THREAD

**Issue by 1plus-1** [rustdesk/rustdesk#4898]
### Bug Description

Cannot connected to the service through SOCKS5 proxy.

### How to Reproduce

I have a windows laptop with below settings. It connects to my LAN network from WAN through a shadowsocks SOCKS5 proxy.
  ID server: 192.168.0.50
  Relay server: 192.168.0.50
  SOCKS5 proxy: 127.0.0.1:1080

In my LAN network, the machine with address 192.168.0.50 hosted both the rustdesk server and shadowsocks server. From the laptop I can control the desktop of one Windows PC in the LAN successfully. This proofs the proxy works. But as the opposite the laptop cannot start the service. The status bar always shows "Not ready. Please check your connection". And if I try to connect this laptop from the LAN windows PC it just prompt "ID does not exist"

The server was installed with the official rustdesk docker image and docker-compose yaml file. Only changed the IP address to 192.168.0.50 in the hbbs command option.

### Expected Behavior

The laptop and windows PC can connect to each other.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/25856364/0743a637-c27d-4e1d-a273-5a8b63a7b717)
![image](https://github.com/rustdesk/rustdesk/assets/25856364/c02c69ef-7e68-42a3-8745-1c70d7481b50)

**Comment by dignow** [comment]
@1plus-1  Thanks for your feedback. But I can't understand the issue you describe.

The laptop is in the WAN? Why do you set socks config to `127.0.0.1`?

<img width="613" alt="1688708366160" src="https://github.com/rustdesk/rustdesk/assets/13586388/7dde008e-e2d2-407d-91bf-37403c7d7277">

**Comment by rustdesk** [comment]
My socks works fine, we have no way to solve your network problem.
