### ISSUE TITLE
"Failed to connect to rendezvous server" when changing the ID

### ISSUE THREAD

**Issue by Karmalakas** [rustdesk/rustdesk#4899]
### Bug Description

On Windows, when I try to change ID and click OK, after a few seconds of progress bar, I get this error:
> Failed to connect to rendezvous server

Tried multiple times in a span of ~12 hours
Remote connection itself with numeric ID works fine both to the phone and from the phone

### How to Reproduce

Try to change ID

### Expected Behavior

ID changes

### Operating system(s) on local side and remote side

Win 10

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/3602819/d9ae3338-d231-4563-a616-2bf52126ef09)

**Comment by rustdesk** [comment]
`change id` is not supported.

**Comment by rustdesk** [comment]
But the respond message looks wrong.

**Comment by rustdesk** [comment]
That's because one of our public servers is down.
