### ISSUE TITLE
Multiple, simultaneous users/sessions possible (as with native Windows RDP)?

### ISSUE THREAD

**Issue by strarsis** [rustdesk/rustdesk#490]
Are also multiple, simultaneous users/sessions possible, like with native Windows RDP?
User A can log in, user B can also log in at the same time, both can use the same system separately.
Can RustDesk also do this? Or is this something so low-level that it isn't practically feasible?

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/323
