### ISSUE TITLE
Desktop link starts on wrong display on client

### ISSUE THREAD

**Issue by psflachglas** [rustdesk/rustdesk#4905]
### Bug Description

The Rustdesk session is always started on monitor 1 when using the desktop shortcut.

### How to Reproduce

- Running Rustdesk (rustdesk-1.2.0-x86_64.exe) on a computer with multiple monitors (local side)
- Connect to the remote computer
- Move the Rustdesk session window full screen to the second monitor, pin it and close the connection.
- Create a desktop shortcut to this Rustdesk session
- Launch the Rustdesk shortcut

It works as expected, the remote session starts on monitor 2

**When you fully close the Rustdesk application and run the desktop shortcut, the session will start on monitor 1 instead of monitor 2.**

### Expected Behavior

When I use the desktop shortcut the session should be started on monitor 2, where it was configured.

In version 1.1.9 it worked.
The problem is only since 1.2.0,
Nightly build is affected to.

### Operating system(s) on local side and remote side

Windows 10 64x

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0

### Screenshots

Please report if pictures are necessary.

**Comment by rustdesk** [comment]
Sorry, this problem is hard to be solved in 1.2, because 1.2 use tabbed window.

**Comment by rustdesk** [comment]
Marked as wontfix for the time being before Flutter has offical multiple window support.
