### ISSUE TITLE
Multiple windows display each other's different screens in the same session

### ISSUE THREAD

**Issue by itbencn** [rustdesk/rustdesk#4907]
### Bug Description

In the same remote connection session, the other party has multiple screens, and I also have multiple screens myself. It is completely possible to use multiple windows to independently display different screens, improving work efficiency.

### How to Reproduce

Even when the other party only has one screen, they can directly extend a remote virtual secondary screen for their own use, which may be difficult and can be ignored.

### Expected Behavior

.

### Operating system(s) on local side and remote side

windows11

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

.

**Comment by rustdesk** [comment]
duplicate
