### ISSUE TITLE
Configuration and selection of multiple different self built server lists

### ISSUE THREAD

**Issue by itbencn** [rustdesk/rustdesk#4908]
### Bug Description

Configuration and selection of multiple different self built server lists

### How to Reproduce

When there are two or more self built server nodes, client configuration is cumbersome, and only one configuration information can be saved at the same time

### Expected Behavior

.It is recommended to add a server node selection function in the status bar at the bottom of the homepage, as well as better support for saving node configurations in the form of local files, to facilitate migration

### Operating system(s) on local side and remote side

windows11

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4331

**Comment by rustdesk** [comment]
also many duplicate discussion about this.
