### ISSUE TITLE
Keyboard input is sometimes sent incorrectly （garuda Linux)

### ISSUE THREAD

**Issue by zany130** [rustdesk/rustdesk#4915]
### Bug Description

when using both the client (windows) and the host (garuda Linux) at the same time (client on one monitor, host on another(
Keyboard input is sent incorrectly sometimes. For example, `d` may be sent as `&`  

seems to happen more when I use hotkeys on my host system

I guess I am using map as the keyboard mode? if I click the keyboard icon in the toolbar, it says map.,

### How to Reproduce

simultaneously use the host (garuda in my case) and client (windows in my case) at the same time

Use hotkeys on both systems (like ctrl+c, ctrl+v alt+tab, etc). The 

### Expected Behavior

Keyboard input is consistently sent correctly

### Operating system(s) on local side and remote side

Garuda Linux -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0

### Screenshots

N/A

### Additional Context

```
inxi -b
System:
  Host: Garuda-Linux Kernel: 6.4.1-zen2-1-zen arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.27.6 Distro: Garuda Linux
Machine:
  Type: Desktop Mobo: ASRock model: X470 Taichi serial: <superuser required>
    UEFI: American Megatrends v: P5.10 date: 10/20/2022
CPU:
  Info: 6-core AMD Ryzen 5 5600X [MT MCP] speed (MHz): avg: 4194
    min/max: 2200/4650
Graphics:
  Device-1: AMD Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT]
    driver: amdgpu v: kernel
  Display: wayland server: X.org v: 1.21.1.8 with: Xwayland v: 23.1.2
    compositor: kwin_wayland driver: N/A resolution: 1: 2048x864 2: 1536x864
    3: 1536x864
  API: OpenGL v: 4.6 Mesa 23.1.3 renderer: AMD Radeon RX 6700 XT (navi22
    LLVM 15.0.7 DRM 3.52 6.4.1-zen2-1-zen)
Network:
  Device-1: Intel Dual Band Wireless-AC 3168NGW [Stone Peak] driver: iwlwifi
  Device-2: Intel I211 Gigabit Network driver: igb
Drives:
  Local Storage: total: 2.96 TiB used: 2.3 TiB (77.9%)
Info:
  Processes: 563 Uptime: 11h 26m Memory: available: 31.26 GiB
  used: 16.27 GiB (52.0%) Shell: fish inxi: 3.3.27
  ```

**Comment by rustdesk** [comment]
tracked by #3565

**Comment by pormr** [comment]
Here is a little hack/workaround if you are using KDE Plasma. You can set a KWin rule (Press Alt+F3 -> More actions -> Special Window Settings) that make the desktop environment **ignore global shortcuts** when focusing on the RustDesk window. Other DE or WM might have similar setting.
It works for me, except for a few shortcuts still not working (e.g. Win+L, I think the Meta key is handled differently by the desktop environment)

KWin rules like "Focus stealing prevention" and "Skip switcher" might be useful, too.
