### ISSUE TITLE
crash problem

### ISSUE THREAD

**Issue by chenjianhua** [rustdesk/rustdesk#492]
In the ubuntu environment, there will be a crash problem. There is a high probability.

https://user-images.githubusercontent.com/2851859/167328159-451c4817-c948-47d6-8fce-56254ef51b04.mp4

**Comment by rustdesk** [comment]
new mp4 please?

**Comment by jkhsjdhjs** [comment]
@rustdesk You can watch the video locally by copying the link. It plays fine with mpv for example.
