### ISSUE TITLE
Mac menu bar icon not reacting to wallpaper

### ISSUE THREAD

**Issue by bilogic** [rustdesk/rustdesk#4933]
### Bug Description

From https://github.com/rustdesk/rustdesk/issues/4683 Locking the issue just makes it harder to report a legitimate issue.

MacOS is able to have black/white wallpaper together. All other icons react except rustdesk

https://i.imgur.com/sxkB6K8.mp4

### How to Reproduce

See video

### Expected Behavior

Change icon color based on wallpaper background

### Operating system(s) on local side and remote side

OSX

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

See video

**Comment by rustdesk** [comment]
wontfix for time being. we have much more important things to do than this one.
