### ISSUE TITLE
Connection black screen no screen

### ISSUE THREAD

**Issue by FMYC2015** [rustdesk/rustdesk#494]
Android remote connection PC black screen no screen, PC remote connection Android normal screen, is this a bug?

**Comment by rustdesk** [comment]
How about PC 2 PC?

**Comment by FMYC2015** [comment]
External display, on these two days there is a black screen no screen

**Comment by rustdesk** [comment]
Could you the latest file C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server to me? Please remove your id/password info in the file.

**Comment by FMYC2015** [comment]
Packed and sent to email

**Comment by rustdesk** [comment]
Worked before, but not working those two days?

**Comment by FMYC2015** [comment]
yes

**Comment by grummbeer** [comment]
@FMYC2015 have you already tried the nightly version? https://github.com/rustdesk/rustdesk/releases/tag/nightly

Still any issues? maybe related to #80
