### ISSUE TITLE
Up, down, left, right, page up, page down, abnormal buttons

### ISSUE THREAD

**Issue by yyusea** [rustdesk/rustdesk#495]
Version 1.1.19 , Laptop , function keys mixed with numeric keypad? Up->8 Down->2 Left->4 Right->6 Page Up->9 Page Down->3

**Comment by rustdesk** [comment]
How does your small keyboard look like? Can you take a picture, I can not reproduce on my laptop and PC.

**Comment by yyusea** [comment]
![image](https://user-images.githubusercontent.com/16720041/167439489-2ac39de0-25d4-43d0-9b6e-b18b1de1d085.png)

**Comment by rustdesk** [comment]
Strange, what's OS version?

**Comment by yyusea** [comment]
local side win7,    remote side win10 or win 11

**Comment by yyusea** [comment]
sorry ,this problem is in romote side's  virtual machine(vmware ubuntu)

**Comment by yyusea** [comment]
向日葵is ok

**Comment by rustdesk** [comment]
Sadly I failed to reproduce it , by controlling Ubuntu in vmware from Win11.

**Comment by yyusea** [comment]
local side win7      remote side win11      ,virtual machine (vmware ubuntu) is in win11

**Comment by Lqinggang** [comment]
hi, bro, I have the same problem, local side wind11 and the remote side is wind10

**Comment by Lqinggang** [comment]
so how should i fix it

**Comment by asur4s** [comment]
We have implemented a new keyboard mode, and switching to the new mode after the merge will fix this. #964

**Comment by rustdesk** [comment]
#1547

**Comment by fufesou** [comment]
@yyusea @Lqinggang Hi, can you please try the nightly build, with "Map mode"?
<img width="235" alt="20230104201351" src="https://user-images.githubusercontent.com/13586388/210715578-13b62bb1-7e67-4ff5-8ad5-4afa34d4740d.png">
