### ISSUE TITLE
Rustdesk high CPU usage on Wayland kde neon

### ISSUE THREAD

**Issue by linlinxza** [rustdesk/rustdesk#4961]
### Bug Description

Rustdesk has high CPU usage on Wayland.

### How to Reproduce

1. Switch to Wayland.
2. Install Rustdesk 1.2.0
3. Connect to it from another computer.

### Expected Behavior

Lower CPU usage.

### Operating system(s) on local side and remote side

KDE Neon

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

![Rustdesk High CPU](https://github.com/rustdesk/rustdesk/assets/11242593/b0de9d3d-183b-425d-8150-b71f648a60a5)

**Comment by rustdesk** [comment]
tracked by #3565
