### ISSUE TITLE
v1.2.1: TCP Tunneling feature doesn't work

### ISSUE THREAD

**Issue by mherrmann3** [rustdesk/rustdesk#4964]
### Bug Description

I updated to v1.2.1 to benefit from fixing #4880, but now the TCP tunneling window is gray (see screenshot) and the feature doesn't work.

### How to Reproduce

Update to v1.2.1, activate _TCP Tunneling_ to one remote device.
When downgrading to v1.2.0, it works as expected (well, with the #4880 issue).

### Expected Behavior

(implied, see above)

### Operating system(s) on local side and remote side

Windows 10 -> Arch Linux

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.0

### Screenshots

![Clipboard Image](https://github.com/rustdesk/rustdesk/assets/3447479/f2af85e9-6a56-4865-9723-969dcde55f8d)

**Comment by rustdesk** [comment]
close as fix merged

**Comment by rustdesk** [comment]
I will rebuild 1.2.1 later since it is still in pre-release status.

**Comment by rustdesk** [comment]
Please try out the new 1.2.1 build.
