### ISSUE TITLE
The latest version 1.2.1 and night cannot use tcp tunnel and rdp

### ISSUE THREAD

**Issue by yzbleaf** [rustdesk/rustdesk#4966]
### Bug Description

The latest 1.2.1 and night versions cannot use tcp tunnel and rdp. Whether you click on tcp tunnel or rdp to connect, only a blank window pops up. This is the case on my three windows11 computers. Return the software Up to 1.2.0, it can be used normally.

### How to Reproduce

Use the latest 1.2.1 and night version, click tcp tunnel or rdp to connect.

### Expected Behavior

Hope tcp tunnel and rdp can work normally in latest version.

### Operating system(s) on local side and remote side

Windows11----Windows11

### RustDesk Version(s) on local side and remote side

1.2.1----1.2.1

### Screenshots

![20230712_145233](https://github.com/rustdesk/rustdesk/assets/86590318/c59efdea-68dd-4656-bcf7-9345bcb0154f)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4964
