### ISSUE TITLE
Android TV

### ISSUE THREAD

**Issue by paolosezart** [rustdesk/rustdesk#497]
Is a server version running on android TV expected? What would it be possible to control an ATV from a computer/android smartphone?

**Comment by rustdesk** [comment]
Yes, in the future.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1038

**Comment by wazerstar** [comment]
I'm testing both the f-droid version 28 and https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9.apk


I can install on nvidia shield android 11 and start the app, and that's about it, cannot touch any settings nor can I get an ID to connect to, I made sure to enable accessibility settings for rustdesk under android tv > settings.

**Comment by rustdesk** [comment]
close to favor #1038

**Comment by FelipeGCaetano** [comment]
Any new information about?

**Comment by hapishyguy** [comment]
> I'm testing both the f-droid version 28 and https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9.apk
> 
> I can install on nvidia shield android 11 and start the app, and that's about it, cannot touch any settings nor can I get an ID to connect to, I made sure to enable accessibility settings for rustdesk under android tv > settings.

Just adding to it that I have the same issue with similar kind of non phone device. I read somewhere a comment from someone that those low gadgets wont work as of now. I am alos able to install but all options at the bottom are greyed out and no code appears to be able to login into.
