### ISSUE TITLE
Virtual display driver still not working in v1.2.1

### ISSUE THREAD

**Issue by FCrane** [rustdesk/rustdesk#4972]
### Bug Description

Virtual display driver does not work at all.

See https://github.com/rustdesk/rustdesk/issues/4359

My latest comment from today.

### How to Reproduce

See desctiption

### Expected Behavior

Working virtual display driver

### Operating system(s) on local side and remote side

Windows 11 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

n/a

**Comment by rustdesk** [comment]
Stop create duplicate
