### ISSUE TITLE
Virtual Display Driver is glitchy on Windows 10/11

### ISSUE THREAD

**Issue by lrq3000** [rustdesk/rustdesk#4974]
### Bug Description

On Windows 11 Pro, it seems the Virtual Display driver does not do its job properly. It works and allows for remote connection without a monitor attached, but it does not render windows properly (ie, I can see the desktop as if there was no window, but there is one and I can type in its text fields for example). This happens with any type of window: applications, Windows start menu, Windows search results, etc.

A solution is to install an [Indirect Display Driver](https://msdn.microsoft.com/en-us/library/windows/hardware/mt761968(v=vs.85).aspx) (a new API Microsoft released in 2022). There is an open-source implementation that is readily installable here: https://github.com/ge9/IddSampleDriver

(Note that I found this solution in the following discussion of another app, there are other implementations listed and particularly for other OSes including Linux and Mac OSX if this may interest you: https://github.com/pavlobu/deskreen/discussions/86 ).

I tested by installing via Scoop.sh, it works very well. Just make sure to increase the default virtual monitor resolution (I set up 1920x1080 instead of the default 640x480), otherwise it seems that when the screen resolution, RustDesk has some issues to connect (or maybe it was a temporary bug on my computer, just keep this in mind if you have issues connecting after installing the driver).

### How to Reproduce

Just try to connect with RustDesk to a computer under Windows 11 without a monitor attached. Try to launch any window, it will not be displayed properly.

### Expected Behavior

Windows should be displayed properly as if a monitor was attached.

### Operating system(s) on local side and remote side

Windows 11 Pro -> Windows 11 Pro

### RustDesk Version(s) on local side and remote side

1.2.0 nightly (commit: 7d7cfe391a04a0a5313a4989981dfffd53e855e8 )

### Screenshots

https://youtu.be/QzjXOyd_PnY

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
@lrq3000 could you help test if AnyDesk/TeamViewer has the same issue.

**Comment by fufesou** [comment]
It seems that RustDesk Virtual Display is not running on your computer. You're using the dummy display on windows.
Can you please check the "Display adapters" and "Monitors" in you "Device Manager?

<img width="332" alt="1689180152155" src="https://github.com/rustdesk/rustdesk/assets/13586388/a5018eff-c567-4ff9-96f9-5ee70040a40b">

**Comment by lrq3000** [comment]
I can confirm I do NOT have the "RustDesk IddDriver Device" on any of my host computers despite enabling the installation of the Virtual Display Driver in RustDesk installer.

I’m going to try with v1.2.1 nightly since I saw it was released today.

I did not test with TeamViewer but the same issue happens with Parsec without their Virtual Display Driver, but when it is installed and enabled as a fallback, then Parsec works fine (and once it is launched and their Virtual Display enabled, RustDesk works fine then). So I don’t think it’s necessary to test with TeamViewer: the issue seems to stem from RustDesk IddDriver not being installed for some reason.

How can I debug what’s happening? Is there a log somewhere?

**Comment by lrq3000** [comment]
Same issue with v1.2.1 nightly, driver is not installed (I uninstalled v1.2.0 before). Also, the same issue happens on Windows 10 pro. So far, I have tested on 3 host computers: one under Windows 11 Pro, one under Windows 10 Pro, and one under Windows Server 2019 S2, the same issue happens in all of these environments for some reason.

**Comment by lrq3000** [comment]
I tried disabling firewalls and antiviruses, no change.

**Comment by fufesou** [comment]
@lrq3000 @zbynekdrlik


Thanks for your feedback.

The "RustDeskIddDriver" will only run when there's no displays.
Windows seems add a dummy display in may machines when there's no physical display.

But currently do no have a good way detect the dummy display.

For now, we just take a display with both sides <= 800 as a dummy display.

https://github.com/rustdesk/rustdesk/blob/cdc412afd06121670f121ae3b82fb787ed8c5371/src/server/video_service.rs#L996

For parsec, there're two settings for virtual display.

1. Add virtual displays directly.
2. Add virtual display if no displays on the remote side.

<img width="649" alt="1689202345057" src="https://github.com/rustdesk/rustdesk/assets/13586388/9d075fa6-1609-42d7-9ebc-0614dcbfcd55">

**Comment by lrq3000** [comment]
Yes I only have the Fallback To Virtual Display enabled (because it’s free 😅 ), but I guess the other one would work as well.

Ok I understand the logic you are trying to do but it seems it’s failing on my machines for some reason. For one machine it’s because there is a USB dongle, but the others have nothing, and yet the idd driver does not appear.

I would like to suggest 2 alternative approaches:

1. Let the driver always be there, but add/remove the virtual display dynamically. If you are using the same idd driver, it says the minimum is 1, but maybe the driver sourcecode can be modified to support 0 displays.
2. Add a setting in RustDesk options to choose between No virtual display, Fallback (like Parsec does and as you are trying to do now), or Always enabled (so the virtual display would always be there, which would mimic the solution I have manually done by myself).

**Comment by lrq3000** [comment]
@fufesou Pinging, please see my reply above (sorry I thought you were assigned to this thread).

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4974#issuecomment-1633308140

> Thanks for your feedback.
> 
> We will continue working on it. But we may not work on it promptly.
> 
> All issues are actually two:
> 
> 1. For installation. https://github.com/rustdesk/rustdesk/pull/4838 may implement a better  installation. But we need more feedbacks.
> 2. For most cases. The driver does not work properly. There're some others reporting the same issue.  #4359 #4974
> 
> > We are considering your proposal, but it does not mean we will work on it promptly. You can create a feature request about this.
> 
> Parsec has a setting to add additional virtual displays during the connections.
> 
> https://github.com/rustdesk/rustdesk/issues/4974#issuecomment-1633308140
> 
>

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4359#issuecomment-1633320453

> Thanks for your feedback.
> 
> We will continue working on it. But we may not work on it promptly.
> 
> All issues are actually two:
> 
> 1. For installation. https://github.com/rustdesk/rustdesk/pull/4838 may implement a better  installation. But we need more feedbacks.
> 2. For most cases. The driver does not work properly. There're some others reporting the same issue.  #4359 #4974
> 
> > We are considering your proposal, but it does not mean we will work on it promptly. You can create a feature request about this.
> 
> Parsec has a setting to add additional virtual displays during the connections.
> 
> https://github.com/rustdesk/rustdesk/issues/4974#issuecomment-1633308140
> 
>

**Comment by zbynekdrlik** [comment]
Only note that my issue #4971 is related windows 10, so issues are not only in Windows 11 and maybe if this would be main ticket , it should be renamed.

**Comment by lrq3000** [comment]
@zbynekdrlik I agree with the renaming, I also have the issue on Windows 10 (I tested it later on other platforms than Win11).

@rustdesk I understand open-source development, being myself an OSS dev :-) Thank you very much to you, @fufesou and the rest of the team for your amazing work on RustDesk!

Meanwhile this gets fixed, I recopy here the tips I gave in another now closed issue as it may help others use RustDesk to its fullest capacity:

Here are the manual modifications I did on my system to make RustDesk fully functional headless:

1. About the inability to update RustDesk when remote controlling with RustDesk (the RustDesk window turns grey), it’s because you did not enable the ability to change its configuration parameters remotely on the host computer. So either you need to access the host physically, or install another remote control software such as TeamViewer or Parsec, and then use that to modify RustDesk options. It’s the "Enable remote configuration modification" below. @rustdesk @fufesou maybe instead of just graying out the RustDesk window, a more explicit message could be shown in the middle on top of the graying, to say that "Remote configuration is not allowed in settings"?

![253121932-6e75b24d-9790-4123-b452-3b6c809e3830](https://github.com/rustdesk/rustdesk/assets/1118942/02a00bb4-dad7-4105-ba9e-7fb670dd75a1)

2. About the lack of a mouse cursor, this is a common issue for all remote desktop softwares, Parsec has similar issues. And a similar, easy solution: just enable the "Numpad mouse" option that is native to Windows. See [this tutorial](https://support.parsec.app/hc/en-us/articles/115002683491-Running-Parsec-On-A-Headless-Gaming-PC-Or-A-Server). The mouse cursor should reappear as soon as this option is enabled, no need to reconnect or reboot.

3. About the display issues when no external monitor is installed, and the lack of the RustDesk virtual display driver, you can install a similar (the same?) driver by yourself from https://github.com/ge9/IddSampleDriver . Of course, you will not be able to install it using RustDesk without a monitor, so you need to attach a monitor first, or use another software such as Parsec with an already installed and configured virtual display driver (with fallback enabled). But once this driver is installed, you can go to Windows settings to change the virtual monitor default resolution to your liking, and then reboot your computer, without a monitor attached, and RustDesk should now work fine!

**Comment by FCrane** [comment]
@lrq3000: thanks for the tips! Here are my findings:

1) Yes, I found the "Enable remote configuration..." option and I even was able to switch it on remotely! There is a short time delay when the mouse cursor enters the options window until it is grayed out and with a few tries I managed to click "Unlock security settings" just in time before the dialog was gray. From then on, graying does not occur anymore and I could switch the remote config option on.

2) The mouse cursor work around leads to 2 mouse cursors:
![2 Cursors](https://github.com/rustdesk/rustdesk/assets/14123400/0df2fd90-d164-4dd6-b6a7-707c7e80691f)
Of course I disabled "Show remote mouse cursor", but still I always get 2 cursors, which is not only ugly but also makes it impossible to work with...
So the only way to get correct mouse cursors is to either attach a physical mouse or use the Wacom Touchpad driver (which works perfectly, btw., so it's my preferred choice).

3) I was able to install the driver you linked:
![Driver](https://github.com/rustdesk/rustdesk/assets/14123400/80197b49-4c07-47bf-af0c-3520984c7c96)
However, nothing ever shows up anywhere. Not in the device manager, nor the Display Settings, nowhere. It's as if it hadn't installed at all. I did create the "C:\IddSampleDriver" and copied all files of the zip there, then right-clicked the inf and selected "Install". It installs, but nothing ever shows up. I also installed the certs, etc. Not sure what else I could do - does not seem to work on a clean Win11 installation...

Regards!

**Comment by lrq3000** [comment]
@FCrane About 2, it’s strange that you experience this issue, I tried on 3 different machines and none displayed this issue. Also, even without the fix I suggest, RustDesk anyway displays the cursor position on its own, although not a contextualized cursor without the fix.

About 3, please re-read the instructions, this is not how the idd driver should be installed, what you did is expected to fail, the proper installation requires different manipulations.

**Comment by lrq3000** [comment]
@FCrane About 2, it’s strange that you experience this issue, I tried on 3 different machines and none displayed this issue. Also, even without the fix I suggest, RustDesk anyway displays the cursor position on its own, although not a contextualized cursor without the fix.

About 3, please re-read the instructions, this is not how the idd driver should be installed, what you did is expected to fail, the proper installation requires different manipulations.

**Comment by FCrane** [comment]
@lrq3000:

Yes, I always get 2 cursors with the accessibility fix. "Show remote cursor" does not make any difference (neither does it with the Wacom Touchpad driver - this always shows 1 cursor correctly, the "remote" second cursor is never displayed). The contextual cursor is absolutely necessary, because without it, you cannot write texts, resize windows, etc. reasonably.

Thanks for pointing me to the correct installation of the display driver - this seems to work now. However, I think I will still simply use my 10,- HDMI dongle, which simulates a monitor perfectly and never causes any issues. But I only have 1 of those, so the virtual display driver is good for my other headless test systems. Now it would be nice if RustDesk could make this work with their driver reliably, so that we don't need to manually install the other driver...

Regards!

**Comment by lrq3000** [comment]
@FCrane Yes the installation of the IddDriver is a bit tricky, glad it works now! I also use one HDMI dongle on a computer on which I already had one, it’s more reliable than drivers, but for computers for which I do not have a dongle, it’s great to have the driver!

Also BTW the driver itself has the issue of resetting the resolution to the minimum it supports after each reboot. The solution I found is to simply delete any lower resolution I do not want in the C:\IddSampleDriver\option.txt config file.

**Comment by FCrane** [comment]
On my test system, the driver does not reset the resolution after reboot - it always keeps the selected resolution just fine (reboot, shutdown, sleep, whatever). Strange!

**Comment by lrq3000** [comment]
@FCrane Mmm maybe the reset happens not after reboot but after plugging and unplugging an external monitor? I’ll retest that, maybe I am misremembering something, thank you for pointing this out!

**Comment by rustdesk** [comment]
@FCrane  @lrq3000 
Please try out the latest nightly build, we have some fix for this. https://github.com/rustdesk/rustdesk/releases/nightly

https://github.com/rustdesk/rustdesk/pull/6199

**Comment by VocalFan** [comment]
Let me test myself as I also have this issue

**Comment by VocalFan** [comment]
Even with the nightly build on both clients, it seems like there's still display issues. Mainly, slow/displaced windows, unable to open Start menu (can click it, but doesn't visually open), Settings only refreshes when alttabbed out of and back into.

**Comment by rustdesk** [comment]
> Even with the nightly build on both clients, it seems like there's still display issues. Mainly, slow/displaced windows, unable to open Start menu (can click it, but doesn't visually open), Settings only refreshes when alttabbed out of and back into.

Do you have these problem with AnyDesk / Teamviewer?

**Comment by fufesou** [comment]
> Even with the nightly build on both clients, it seems like there's still display issues. Mainly, slow/displaced windows, unable to open Start menu (can click it, but doesn't visually open), Settings only refreshes when alttabbed out of and back into.

Hi, do you have rustdesk installed? It seems the limit of the windows dummy display.

**Comment by rustdesk** [comment]
Since no active response, close to favor https://github.com/rustdesk/rustdesk/issues/6280

**Comment by lrq3000** [comment]
Ah sorry, i cannot test right now because my test computer literally burnt, but I will try once I repair it. However @VocalFan's description in the last message above sounds very much like what I experienced, slow windows and especially the start menu being clickable but not opening visually, so it seems to me the suggested fix doesn't fully work yet unfortunately.

**Comment by Swiftgti** [comment]
Hi, i have same issue in windows 11, using  both computers RustDesk 1.2.3-1, the remote computer has the monitor off. 

You asked what happens with anydesk? Ok is worst, because initiates the connection and keeps endless time in getting the image, and never continues. At least RustDesk it connects, and you can see something.

That the nightly version solved this issue?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/6444#discussioncomment-8521217

**Comment by AD2011** [comment]
Thank You @lrq3000 I was facing the same issue when the display of the remote desktop was turned off, your fix of installing the Virtual Display Driver worked for me.
Note - This was not an issue when using TeamViewer
