### ISSUE TITLE
Does Rustdesk support modifying the remote desktop resolution?

### ISSUE THREAD

**Issue by lllAlex2333** [rustdesk/rustdesk#498]
I'm using  rustdesk, but the resolution issue is bothering me. The window is too small now, and when I choose to stretch, the content becomes blurry.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1053

**Comment by rustdesk** [comment]
We are screen capturing, not creating new session as what mstsc does. But in some special case (e.g. no physical display), we can create a virtual display with some resolution, but still impossible as flexible as mstsc. If you insist it, please our RDP sharing feature https://github.com/rustdesk/rustdesk/issues/914#issuecomment-1173839858.

**Comment by jwgn** [comment]
Ok so we are unable to fully control clients which have a higher screen resolution. Workaround: ask the client to lower the resolution below ours, then restart the service. Works, yea. Pretty messy solution, though.

Products like TeamViewer are able to scale the resolution to fit the operator's screen. Why is this not possible here?

**Comment by rustdesk** [comment]
goto  toolbar, there is shrink/scale button.
