### ISSUE TITLE
Typo in Wiki FAQ

### ISSUE THREAD

**Issue by icher** [rustdesk/rustdesk#4982]
### Bug Description

Typo in subheading, body and link.

`s/Sever/Server/g`

https://github.com/rustdesk/rustdesk/wiki/FAQ#where-can-i-download-rustdesk-sever

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/8604717/1082a7d1-ec2b-4f8f-980d-1cb52149f8d8)

**Comment by rustdesk** [comment]
thx, fixed
