### ISSUE TITLE
Typo in the rustdesk.com webpage

### ISSUE THREAD

**Issue by Wayrow** [rustdesk/rustdesk#4985]
### Bug Description

There is a typo in the rustdesk.com webpage in the Resources section. "Changlog" should be "Changelog".

### How to Reproduce

Look under the "Resources" section in the rustdesk.com webpage.

### Expected Behavior

"Changlog" text should be "Changelog".

### Operating system(s) on local side and remote side

N/A

### RustDesk Version(s) on local side and remote side

N/A

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/139426789/44341633-2312-4dc6-84f2-0897062229e6)

**Comment by rustdesk** [comment]
noted
