### ISSUE TITLE
When the computer is remote, it is not possible to switch capitalization

### ISSUE THREAD

**Issue by yaoxipenga** [rustdesk/rustdesk#4988]
### Bug Description

When using a remote computer, I cannot switch to uppercase. I am using a remote computer, but my remote computer password has uppercase, so I cannot input uppercase, even if the computer I control has already switched to uppercase

### How to Reproduce

Handle it as soon as possible

### Expected Behavior

Can switch case normally

### Operating system(s) on local side and remote side

windows10 ---> windows10 

### RustDesk Version(s) on local side and remote side

1.2.1--->1.2.1

### Screenshots

![企业微信截图_1689233239545](https://github.com/rustdesk/rustdesk/assets/61485464/45249f47-f052-4491-91a2-68a68ec34fd9)

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
Cap switch works fine  in my test. BTW, Cap is determined by local side not remote side.

**Comment by fufesou** [comment]
Both "Shift" + Letters and "CapsLock" work fine for me.

<img width="204" alt="1689236526209" src="https://github.com/rustdesk/rustdesk/assets/13586388/5e446c3a-5e4e-4d93-80d3-a6fbbb73c389">
