### ISSUE TITLE
Unable to connect due to update

### ISSUE THREAD

**Issue by be-nito** [rustdesk/rustdesk#4989]
### Bug Description

After updating to version 1.2.0 on 3 computers (all on fedora 38), I can't connect. When I launch a connection, it doesn't succeed on the remote computer (no connection request). 

### How to Reproduce

2 computers with fedora 38

### Expected Behavior

Nothing

### Operating system(s) on local side and remote side

Fedora 38 -> Fedora 38

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

![Capture d’écran du 2023-07-13 10-02-12](https://github.com/rustdesk/rustdesk/assets/25792867/0e6ab2a1-cbd8-4d0c-a512-06a9ebb5180b)
![Capture d’écran du 2023-07-13 10-01-56](https://github.com/rustdesk/rustdesk/assets/25792867/65c1a36a-8972-4323-8149-687d0830db82)
![Capture d’écran du 2023-07-13 10-10-19](https://github.com/rustdesk/rustdesk/assets/25792867/0e726c5f-5370-4589-92ba-6cce08200866)

### Additional Context

J'ai tenté d'installer la version 1.2.1 sur les ordinateurs, problème toujours présent. J'arrive de nouveau à me connecter si je repasse sur la version 1.9.0 sur l'ordinateur distant, tout en restant sur la version 1.2.1 sur l'ordinateur local (qui demande la connexion). J'ai également testé de Fedora 38 vers Android, la connexion aboutie bien. Les 2 ordinateurs en version 1.2.1 se voient bien puisqu'il est bien détecté en ligne quand celui-ci est allumé.

**Comment by rustdesk** [comment]
#763
