### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by Dmitry9292** [rustdesk/rustdesk#499]
Hi there!
I am testing your program and its working good with mac systems, but windows is not working. It says "Connection reset by peer".
I am using self-hosted server by docker. All ports are open on server-side.
Tried client version: 1.1.8 and 1.1.9
Would be much appreciated if there is any tips or suggestions how I can fix it.
Thanks in advance!

**Comment by rustdesk** [comment]
Hope you can run from source code, and figure out the problem? We had such report before, but still can not reproduce. Really need your help.

**Comment by yyusea** [comment]
https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: failed: status code 404

for
  git clone https://github.com/microsoft/vcpkg
  cd vcpkg
  git checkout 2021.12.01

**Comment by rtest12** [comment]
> https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: failed: status code 404
> 
> for git clone https://github.com/microsoft/vcpkg cd vcpkg git checkout 2021.12.01

Same error, how to get around it?

**Comment by shayaknyc** [comment]
Hi folks. Found this thread while looking for a solution to the same problem. Currently running hbbs/hbbr in docker containers using docker-compose. 

The docker-compose.yml file does contain `hbbs -r url.com:21117 -k _` in the Execute section. Have no problems connecting between clients on local LAN, or through VPN. However, when not on the same LAN or VPN, the client constantly cycles between trying to connect and "reset by the peer" until it times-out and I have to click on "OK" or "Retry". I can confirm that the ID/Relay Server section has the correct ID server, relay server, and Key set up - as the destination client is showing "Ready".

Firewall ports are all open (TCP/UDP) on all machines that have RustDesk. Any ideas?

**Comment by monosoul** [comment]
Having the same issue. I run rustdesk in a container, connection only works when in the same network

**Comment by monosoul** [comment]
OK, figured it out.

@shayaknyc make sure `hbbr` and `hbbs` volumes have the same `id_ed25519` and `id_ed25519.pub`.

@rustdesk probably it makes sense to change this line: https://github.com/rustdesk/rustdesk-server/blob/063b4543682815bbd6fa329f3c977c00c6b1475f/docker-compose.yml#L33 to use the same volume for both `hbbr` and `hbbs`

**Comment by shayaknyc** [comment]
Ah! Let me try it and see if that fixes the issue.

**Comment by Dmitry9292** [comment]
> OK, figured it out.
> 
> @shayaknyc make sure `hbbr` and `hbbs` volumes have the same `id_ed25519` and `id_ed25519.pub`.
> 
> @rustdesk probably it makes sense to change this line: https://github.com/rustdesk/rustdesk-server/blob/063b4543682815bbd6fa329f3c977c00c6b1475f/docker-compose.yml#L33 to use the same volume for both `hbbr` and `hbbs`

Thank you! With this workaround connection is working as expected. Might need to be mentioned on FAQ or other section.

**Comment by ll3N1GmAll** [comment]
I have this same issue; but am not using the docker container. Client connects, then hangs on "waiting for image" for a second, and then i get the "reset by peer" error. This just keeps looping indefinitely until i stop it. All other clients are working fine except this one. This is a linux client; but other linux clients work fine. This client is running PopOS. So, it's possible the GUI is having an issue with RustDesk.

**Comment by vyncusp** [comment]
> I have this same issue; but am not using the docker container. Client connects, then hangs on "waiting for image" for a second, and then i get the "reset by peer" error. This just keeps looping indefinitely until i stop it. All other clients are working fine except this one. This is a linux client; but other linux clients work fine. This client is running PopOS. So, it's possible the GUI is having an issue with RustDesk.

Same issue, im using centos os and install itu without using docker.
Rustdesk working fine if the client is LAN.

**Comment by shayaknyc** [comment]
Have you tried using the same key for both services? See here: https://github.com/rustdesk/rustdesk/issues/499#issuecomment-1160578895

While this pertains to using the docker container, the process is the same, make sure that hbbr and hbbs are using the same keypair.

**Comment by LESHIY-ODESSA** [comment]
1. Please explain where exactly to insert files id_ed25519 and id_ed25519.pub?

2. How do I activate the -k parameter?

3. How can I check if the encryption works?

P.S. MikroTik container (ARM) + rustdesk/**rustdesk-server-s6**:latest.

 

![alt text](https://i.imgur.com/FXk680f.png)

**Comment by ZEV1416** [comment]
Faced the same problem. Resolved by restarting the daemons. It seems that the config is created by one of the processes, and the second does not pick it up. If you stop both processes and start again when the configs have already been created, everything works correctly.

**Comment by behrooz3500** [comment]
> OK, figured it out.
> 
> @shayaknyc make sure `hbbr` and `hbbs` volumes have the same `id_ed25519` and `id_ed25519.pub`.
> 
> @rustdesk probably it makes sense to change this line: https://github.com/rustdesk/rustdesk-server/blob/063b4543682815bbd6fa329f3c977c00c6b1475f/docker-compose.yml#L33 to use the same volume for both `hbbr` and `hbbs`

My problem was solved using the same approach. Thank you very much!

**Comment by rustdesk** [comment]
> OK, figured it out.
> 
> @shayaknyc make sure `hbbr` and `hbbs` volumes have the same `id_ed25519` and `id_ed25519.pub`.
> 
> @rustdesk probably it makes sense to change this line: https://github.com/rustdesk/rustdesk-server/blob/063b4543682815bbd6fa329f3c977c00c6b1475f/docker-compose.yml#L33 to use the same volume for both `hbbr` and `hbbs`

@paspo

**Comment by rustdesk** [comment]
Can you try out nightly build? There is a fix, though not good enough, not sure if it works in your scenario.

**Comment by Snuupy** [comment]
I have encryption working if hbbs and hbbr use the same mount point to reference the same id_ed25519 and id_ed25519.pub. However encryption stops working if I add `-k` parameter to hbbs and hbbr in docker-compose.

**Comment by Sora233** [comment]
> OK, figured it out.
> 
> @shayaknyc make sure `hbbr` and `hbbs` volumes have the same `id_ed25519` and `id_ed25519.pub`.
> 
> @rustdesk probably it makes sense to change this line: https://github.com/rustdesk/rustdesk-server/blob/063b4543682815bbd6fa329f3c977c00c6b1475f/docker-compose.yml#L33 to use the same volume for both `hbbr` and `hbbs`

great!

**Comment by rustdesk** [comment]
@Sora233 Submit a PR please.

**Comment by cocodee** [comment]
> I have encryption working if hbbs and hbbr use the same mount point to reference the same `id_ed25519` and `id_ed25519.pub` pairs. However encryption stops working if I add `-k` parameter to hbbs and hbbr in docker-compose.
> 
> Edit:
> 
> ok I fixed it, it was because I was confused about the documentation. the -k _ parameter literally means add an understore (-) after the -k, the underscore does not signify to add the key into that line I added -k _ and that fixed it, now the connection is secure again this was my mistake, solution above works.

This solved my problme,thank you.

**Comment by darkworks** [comment]
@rustdesk can you guide how to apply this fix to non doctor systems. i had installed rust server relay basic version on debian 11 then upgraded to rust server pro version now getting this key mismatch error , although had change public key on client sides too but same issue. so how to apply the @Sora233  patch to non docker system i  went to `/var/lib/rustdesk-server` there  found `id_ed25519` and `id_ed25519.pub` files  so from where i can get `id_ed25519` and `id_ed25519.pub` files to replace mine one as i do not have hbbs directory 

thanks

**Comment by rustdesk** [comment]
![image](https://github.com/rustdesk/rustdesk/assets/71636191/ebbbde26-4e1f-4e8f-97d2-56d3630a8ee0)

**Comment by ashoktvm** [comment]
work perfectly if connecting to systems with in the lan. But shows reset by peer even after copying the files from hbbs to hbbr and restarting container

**Comment by SparKgod1** [comment]
> I have encryption working if hbbs and hbbr use the same mount point to reference the same `id_ed25519` and `id_ed25519.pub` pairs. However encryption stops working if I add `-k` parameter to hbbs and hbbr in docker-compose.
> 
> Edit:
> 
> ok I fixed it, it was because I was confused about the documentation. the -k _ parameter literally means add an understore (-) after the -k, the underscore does not signify to add the key into that line I added -k _ and that fixed it, now the connection is secure again this was my mistake, solution above works.

the same problem as me

**Comment by Sdongmaker** [comment]
The issue I'm currently facing is that both hbbs and hbbr are mounted with the same id_ed25519 and id_ed25519.pub, but still show "Connection reset by peer".
