### ISSUE TITLE
Mac OSX Ventura, German keyboard layout not supported

### ISSUE THREAD

**Issue by hensiek** [rustdesk/rustdesk#4995]
### Bug Description

While typing z on a  German mac-keyboard it types a y on the remote screen. Other German keys are also incorrect.

### How to Reproduce

Type y on a Mac and it gives you z.

### Expected Behavior

if I press y it should print a y.

### Operating system(s) on local side and remote side

Osx - > win1x

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1 -> 1.1.9

### Screenshots

y

**Comment by rustdesk** [comment]
not work on 1.1.9 is expected
