### ISSUE TITLE
Rendering distorted depending on rotation of screen (Tablet using Wayland)

### ISSUE THREAD

**Issue by linlinxza** [rustdesk/rustdesk#4996]
### Bug Description

If the screen is rotated in any way other than in its default position, the rendering becomes distorted.

### How to Reproduce

1. Use a tablet with Linux. (I'm using an old Asus Transformer with KDE Neon).
2. Run it in a Wayland session
3. Remote into it with Rustdesk.

### Expected Behavior

Should not distort image regardless of rotation.

### Operating system(s) on local side and remote side

KDE Neon

### RustDesk Version(s) on local side and remote side

1.2.1

### Screenshots

![Screenshot_20230713_133433](https://github.com/rustdesk/rustdesk/assets/11242593/84b1c8ac-48ed-42a8-a1d3-1c3b82829237)

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
@linlinxza please try out the nightly build https://github.com/rustdesk/rustdesk/releases/nightly

**Comment by rustdesk** [comment]
Sorry, CI had some problem, the build is not ready.

**Comment by rustdesk** [comment]
Nightly build is updated

**Comment by rustdesk** [comment]
Close as fix merged, let us know if you still have problem.

**Comment by rustdesk** [comment]
how about if it is portrait before connection?

**Comment by linlinxza** [comment]
> how about if it is portrait before connection?

You mean landscape? I can change landscape mode before I connect. Same problem still.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565 to mark as low priority since we have no device to test this.

**Comment by linlinxza** [comment]
> tracked by #3565 to mark as low priority since we have no device to test this.

No worries. The device was crap. It died.
