### ISSUE TITLE
Rustdesk client crashes when the mouse moves quickly on the screen (Ubuntu KDE, gnome having no this problem)

### ISSUE THREAD

**Issue by aguerra-ar** [rustdesk/rustdesk#4997]
### Bug Description

When the mouse moves quickly on the screen (no buttons pressed) rustdesk finally crashes.

The problem can be repeated when required.

### How to Reproduce

Open rustdesk, connect to a remote computer amd move the mouse quickly over the rustdesk window, particularly near the borders. 

With version 1.9 it was stable, the issue started with version 1.2.0 and 1.2.1
This is Ubuntu 22.04 + KDE Desktop.
The same Rustdesk versions have no problems on Ubuntu + Gnome.

### Expected Behavior

No crashes.

### Operating system(s) on local side and remote side

Ubuntu 22.04 (KDE) , Ubuntu 22.04 (Gnome)

### RustDesk Version(s) on local side and remote side

1.2.1 , 1.2.1

### Screenshots

I ran the program in a terminal until the crash and then captured the output, twice.
Please let me know if you need any other log file, just let me now how to get it.
See also the video capture  [https://mega.nz/file/COBXEAZZ#aa7jvQrO4YL0jBmMoA7Rvzottn1b62YINTfKfUknuFc](url)

<ubuntu-alberto:~>$ rustdesk 
flutter: launch args: []
flutter: initializing FFI main
flutter: _appType:main,info1-id:84dea2c185384620b32755f66700a6d9,info2-name:Ubuntu,dir:/home/alberto/Documents
flutter: _globalFFI init
flutter: _globalFFI init end
flutter: registerEventHandler native_ui native_ui
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
flutter: handled by uni links: false
flutter: [MultiWindowHandler] active window changed: [0]
flutter: [MultiWindowHandler] active window changed: [0, 1]
flutter: launch args: [multi_window, 1, {"type":1,"id":"1668429749","password":null,"forceRelay":false}]
flutter: initializing FFI remote
flutter: _appType:remote,info1-id:84dea2c185384620b32755f66700a6d9,info2-name:Ubuntu,dir:/home/alberto/Documents
flutter: _globalFFI init
flutter: _globalFFI init end
flutter: registerEventHandler theme theme
flutter: registerEventHandler language language
flutter: registerEventHandler native_ui native_ui
flutter: no window position saved, ignoring position restoration
flutter: [Main] call get_window_info with args  from window 1
flutter: onFocusChange(window active:true) true
flutter: no window position saved, ignoring position restoration
flutter: id: 37822128, texture_key: 0
flutter: [Main] call get_window_info with args  from window 1
flutter: onFocusChange(window active:true) false
flutter: isMaximized false
flutter: [Main] call get_window_info with args  from window 1
flutter: onFocusChange(window active:true) true
flutter: onFocusChange(window active:true) false
flutter: [Main] call get_window_info with args  from window 1
flutter: onFocusChange(window active:true) true
flutter: onFocusChange(window active:true) false
flutter: [Main] call get_window_info with args  from window 1
flutter: onFocusChange(window active:true) true
flutter: onFocusChange(window active:true) false
flutter: [Main] call get_window_info with args  from window 1
flutter: onFocusChange(window active:true) true
flutter: Register custom cursor with key 1668429749_676_240000000_240000000
flutter: onPointDownImage
flutter: onPointDownImage
<ubuntu-alberto:~>$ rustdesk 
flutter: launch args: []
flutter: initializing FFI main
flutter: _appType:main,info1-id:84dea2c185384620b32755f66700a6d9,info2-name:Ubuntu,dir:/home/alberto/Documents
flutter: _globalFFI init
flutter: _globalFFI init end
flutter: registerEventHandler native_ui native_ui
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
flutter: handled by uni links: false
flutter: [MultiWindowHandler] active window changed: [0]
flutter: [MultiWindowHandler] active window changed: [0, 1]
flutter: launch args: [multi_window, 1, {"type":1,"id":"1668429749","password":null,"forceRelay":false}]
flutter: initializing FFI remote
flutter: _appType:remote,info1-id:84dea2c185384620b32755f66700a6d9,info2-name:Ubuntu,dir:/home/alberto/Documents
flutter: _globalFFI init
flutter: _globalFFI init end
flutter: registerEventHandler theme theme
flutter: registerEventHandler language language
flutter: registerEventHandler native_ui native_ui
flutter: no window position saved, ignoring position restoration
flutter: [Main] call get_window_info with args  from window 1
flutter: onFocusChange(window active:true) true
flutter: no window position saved, ignoring position restoration
flutter: id: 11856080, texture_key: 0
flutter: [Main] call get_window_info with args  from window 1
flutter: onFocusChange(window active:true) false
flutter: isMaximized false
flutter: [Main] call get_window_info with args  from window 1
flutter: onFocusChange(window active:true) true
flutter: onFocusChange(window active:true) false
flutter: [Main] call get_window_info with args  from window 1
flutter: onFocusChange(window active:true) true
flutter: Register custom cursor with key 1668429749_676_240000000_240000000
<ubuntu-alberto:~>$

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
@fufesou another report, we need to pay attention to this issue now.

**Comment by fufesou** [comment]
I'm not sure if it the same issue.

`window manager` example always crash on my machine.

The call chain is `window manager` -> `screen_retriever` -> `flutter engine (fl_method_call_respond)`.

https://github.com/flutter/engine/blob/12ce9f013cef3fb0d18a67e6fca9b257976e3818/shell/platform/linux/fl_method_call.cc#L77

It may take me some time to find out the reason.

I'll also try to report this issue to flutter.

https://github.com/rustdesk/rustdesk/assets/13586388/dc268731-664b-4527-89b4-e0cc6b83b07e

**Comment by rustdesk** [comment]
Please try out the nightly build, we put a fix, not sure if it works for you.

**Comment by aguerra-ar** [comment]
I tried the nightly build rustdesk-1.2.2-x86_64.deb and seems to work great, no crashes so far. thank you
