### ISSUE TITLE
screen is not refresh at Windows 10 login page

### ISSUE THREAD

**Issue by Sun-FreePort** [rustdesk/rustdesk#4999]
### Bug Description

I use Windows 10 and RustDesk 1.1.9, in my two computer.

Now, when I use PC connect my Notepad, Windows welcome page is ok, i can move point and show infomation.

But, if i enter "Enter", the screen will not refesh. (Refresh screen is not work)

I use monitor camera, and find my Notepad are goto login page, but RustDesk screen not refesh.

---

When I use Notepad connect PC, all is right working...

### How to Reproduce

I don't know how to reproduce.

### Expected Behavior

Rustdesk right work.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

Login page is locking...
![screenshot-20230714-093000](https://github.com/rustdesk/rustdesk/assets/19473984/caffa338-6997-48a2-83fe-04fd3c516610)

Real login page is done: (in monitor camera)
![screenshot-20230714-093810](https://github.com/rustdesk/rustdesk/assets/19473984/f1224be4-bb18-4177-bcd8-404759b4a645)

Welcome page is right work:
![screenshot-20230714-092852](https://github.com/rustdesk/rustdesk/assets/19473984/7238863c-0759-468f-9fe6-7262adf8cf48)

**Comment by rustdesk** [comment]
#4993
