### ISSUE TITLE
Reinstall command-line no longer works in nightly

### ISSUE THREAD

**Issue by bilago** [rustdesk/rustdesk#5004]
### Bug Description

I use this powershell script to quickly upgrade to the newest nightly:

$WebClient = New-Object System.Net.WebClient
$url = 'https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.1-x86_64.exe'
$dst = 'C:\Temp'
$WebClient.DownloadFile($url, (Join-Path $dst 'RustDeskInstaller.exe'))
Start-Process (Join-Path $dst 'RustDeskInstaller.exe') --reinstall

It's been working for months, but now with 1.2.1, --reinstall does not work anymore

Is this intentional? Is there a replacement commandline argument to silently reinstall rustdesk?

### How to Reproduce

download rustdesk latest nightly
open powershell or cmd prompt
provide --reinstall as a command line argument
Rustdesk no longer installs

### Expected Behavior

Rustdesk should reinstall automatically without user input

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.2.1

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/8310293/fffd7630-36ff-4e8d-81e7-8821652c080a)

**Comment by rustdesk** [comment]
--silent-install
