### ISSUE TITLE
Scaling issues at KDE 5.27 high resolution

### ISSUE THREAD

**Issue by yuhldr** [rustdesk/rustdesk#5010]
### Bug Description

- archlinux lastest
- KDE Plasma 5.27.6 
- Resolution: 2880x1800
- Plasma Global zoom 200%
but Rustdesk is not scaled and looks small, as shown in the image

![image](https://github.com/rustdesk/rustdesk/assets/25719023/8ea8ecde-36df-4a3b-ae6b-963e6b13464f)

### How to Reproduce

always

### Expected Behavior

always

### Operating system(s) on local side and remote side

archlinux lastest, only client

### RustDesk Version(s) on local side and remote side

1.2.1, only client

### Screenshots

like Bug Description

**Comment by rustdesk** [comment]
Yes, not support yet.

**Comment by ironhak** [comment]
is this supported now?
