### ISSUE TITLE
Copying and pasting files doesn't work

### ISSUE THREAD

**Issue by HandSonic** [rustdesk/rustdesk#5013]
### Bug Description

After connecting two computers and turning on allow copy and paste files, copying files on one computer cannot be pasted to the other computer.

### How to Reproduce

First establish a remote connection, then turn on allow copy and paste files, then copy files on one computer, on the other computer the clipboard is empty and can't paste files.

### Expected Behavior

Can copy and paste files normally.

### Operating system(s) on local side and remote side

windows10 -> windows10

### RustDesk Version(s) on local side and remote side

1.2.1->1.2.1

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/8078023/ffaebb53-aef9-4d3e-9dcd-12bb760b0566)
As shown in the picture, it has been turned on to allow copying and pasting of files, but it doesn't work.

**Comment by rustdesk** [comment]
no duplicate please.
