### ISSUE TITLE
french (azerty)  key mapping problem on both Manjaro

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#502]
> But have test 3 pc with manjaro
> And on 2 pc keyboard is not really good
> I cannot make "./" 
> that change keyboard but is the same layout and change setxkeymap not work too. 
> only "::"

> Manjaro to Manjaro
> Have test on 3 Linux PC (Manjaro fr) 
> 2 have issue with keyboard 1 is ok

**Comment by grummbeer** [comment]
#1547

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1518
