### ISSUE TITLE
iOS App doesn't work

### ISSUE THREAD

**Issue by chaunnt** [rustdesk/rustdesk#5020]
### Bug Description

I run github action to build and upload artifact (xachive file) and make adhoc IPA from this but after installing, app did'nt show anything

### How to Reproduce

1. config github action to upload artifact for ios build, change package name to prevent failure distribute on xcode
2. run build (1.2.1) and get xachive file
3. download xachive file and run xocde server to distribute adhoc app
4. run adhoc app on test device
5. open app and nothing show (only white screen)

### Expected Behavior

5. we can run normally

### Operating system(s) on local side and remote side

window 10 > iphone

### RustDesk Version(s) on local side and remote side

1.2.1 > 1.2.1

### Screenshots

N/A

**Comment by rustdesk** [comment]
You need your help to make it run. Frankly, I have no iOS device yet.

**Comment by chaunnt** [comment]
I can help but I can not completely setup this project on my MAC PRO. I tried to fix and rebuild many time for any thing suspected but it's quiet hard to see when there is not any way to see debug log. IPA installed and can not get any logs. do you have any hint that I can get the app log ?

**Comment by chaunnt** [comment]
as you speak, is there any version work with iOS ?
