### ISSUE TITLE
iOS App - RustDesk

### ISSUE THREAD

**Issue by it-boerner** [rustdesk/rustdesk#5022]
### Bug Description

In the iOS app, the API server is not accepted when registering the connection server.

When I specify this as http://xxxx, I always get the error "failed to lookup address information:..."

### How to Reproduce

When you try to change the connection data in the iOS app

### Expected Behavior

correct storage and acceptance of the API server

### Operating system(s) on local side and remote side

iOS 16.5

### RustDesk Version(s) on local side and remote side

1.1.10

### Screenshots

![WhatsApp Bild 2023-07-16 um 12 36 32](https://github.com/rustdesk/rustdesk/assets/118393600/884f2e6e-5926-47d9-a217-b06fd78e91b0)

**Comment by rustdesk** [comment]
This iOS version is very old, please wait for our new release online.

**Comment by it-boerner** [comment]
Tanks :)
