### ISSUE TITLE
Font / Alphabet issue

### ISSUE THREAD

**Issue by DarkZo0m** [rustdesk/rustdesk#5023]
### Bug Description

There is some alphabet or font issue

### How to Reproduce

-

### Expected Behavior

-

### Operating system(s) on local side and remote side

windows 11

### RustDesk Version(s) on local side and remote side

1.2.1

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/59771519/2880389c-8808-4e04-929c-dbbd54fb1446)
![image](https://github.com/rustdesk/rustdesk/assets/59771519/3453434e-f068-46e1-9f52-156f88326d09)
![image](https://github.com/rustdesk/rustdesk/assets/59771519/59fcd28e-d44a-4361-90ff-62677018a7bc)

**Comment by rustdesk** [comment]
Only dropbox?

**Comment by rustdesk** [comment]
Do you have any special font settings on your system?

**Comment by DarkZo0m** [comment]
no

**Comment by rustdesk** [comment]
This is related to underlying flutter framework, close this first because we can do nothing about this for the time being.
