### ISSUE TITLE
Key presses don't work when remoting into Android TV device

### ISSUE THREAD

**Issue by frozen905** [rustdesk/rustdesk#5028]
### Bug Description

Formuler Z10 Pro Max with latest RustDesk apk installed directly from github

Went through the steps of enabling accessibility and the other required permissions with no problems.  Can connect to desktop and can click items with the mouse, drag, etc. but ZERO key presses are being sent.  Have tried everything I can possibly find with no way to send keystrokes to the Android device.

Client computer:  Windows 11
Host computer:  Formuler Z10 Pro Max / Android OS

### How to Reproduce

Run RustDesk on an Android device

### Expected Behavior

Keystrokes to be sent, not just mouse input

### Operating system(s) on local side and remote side

Windows 11 -> Android

### RustDesk Version(s) on local side and remote side

Latest

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/15615481/35846cfb-37a7-4d17-9a49-cf0aa27262ca)

**Comment by rustdesk** [comment]
no duplicate plealse.
