### ISSUE TITLE
Control android

### ISSUE THREAD

**Issue by dingge9527** [rustdesk/rustdesk#503]
可以苹果控制安卓吗

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/138

**Comment by rustdesk** [comment]
Google play version can, but still not stable.

**Comment by dingge9527** [comment]
谢谢，
