### ISSUE TITLE
No send Ctrl + alt + del option

### ISSUE THREAD

**Issue by Lordingard** [rustdesk/rustdesk#5035]
### Bug Description

Hello,

The option "send Ctrl + alt + del" does not appear in menu and I have no idea how to send this keys.
Same problem on last stable version or last nightly.
Please could-you help ?
Thanks.

### How to Reproduce

No option "send Ctrl + alt + del" in menu after connexion on Windows Server 2016 host from Windows 10 client.
Same after : 
-Installing nightly
-Uninstall, remove rustdesk folders in Roaming and Local and reinstall last nightly

### Expected Behavior

The option "send Ctrl + alt + del" appear in menu

### Operating system(s) on local side and remote side

Windows 10 -> Windows Server 2016

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.1.9 | 1.2.1 -> 1.1.9 | Nightly -> 1.1.9

### Screenshots

<img width="286" alt="Capture" src="https://github.com/rustdesk/rustdesk/assets/100278277/2d9e156f-149b-4b8b-8924-42ba05f71f23">

### Additional Context

I tried from multiple versions of client included the last nightly.

**Comment by rustdesk** [comment]
How about 1.1.9 (as controlled side).

**Comment by Lordingard** [comment]
Er, sorry, I have 1.1.9 on the destination host (I have corrected my ticket), I have to update it.
I'm back to you when it's done (probably tomorow).
Thanks.

**Comment by rustdesk** [comment]
let us know aftet you done

**Comment by Lordingard** [comment]
I have updated the target in 1.2.1 and all is good now. Thanks !

**Comment by mac-linux-free** [comment]
on 1.2.2 I also have no ctrl-alt-del option

client linux destination windows 2016

**Comment by argusro** [comment]
Hello, I have a fresh install of version 1.2.3 on both sides, Windows 10, don't see ctrl-alt-del option. When running the client side on Raspberry Pi 5, on the same version, there is the ctrl-alt-del. On iOS app client also see the ctrl-alt-del option. Using private server.
