### ISSUE TITLE
ios RD ver 1.1.10 BUG

### ISSUE THREAD

**Issue by Xinelin** [rustdesk/rustdesk#5037]
### Bug Description

IOS app Rustdesk 1.1.10 cant connect ipv6 DDNS ID server client
But web rd can do it

### How to Reproduce

ID server is an ipv6 domain 
API server none
with key or not.

### Expected Behavior

cant connect

### Operating system(s) on local side and remote side

ios

### RustDesk Version(s) on local side and remote side

1.1.10

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/43874766/c97aad2a-39d6-4a56-a933-a4023730f262)

**Comment by rustdesk** [comment]
mnay duplicate about this
