### ISSUE TITLE
With busybox installed, it keeps poping up command-line window.

### ISSUE THREAD

**Issue by fightingcat** [rustdesk/rustdesk#504]
**Describe the bug you encountered:**

I have busybox installed (with scoop), it keeps poping up command line window when I run rustdesk, I managed to capture the window, turns out it's running "echo" which is a program belongs to busybox.
I'm assuming rustdesk is invoking echo directly, maybe considering invoke cmd or powershell instead?

**What did you expect to happen instead?**

No command line windows should be displayed.

**How did you install `RustDesk`?**

[rustdesk-1.1.9-windows_x64-portable.zip](https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-windows_x64-portable.zip) from GitHub release.

---

**RustDesk version and environment**

RustDesk: 1.1.9-windows_x64-portable
OS: Windows 11 21H2 Home Edition, 22000.613

**Comment by rustdesk** [comment]
Only happened with busybox?

**Comment by rustdesk** [comment]
We do call "echo", https://github.com/rustdesk/rustdesk/blob/master/src/platform/windows.rs#L784, but it seems only called when installing.

**Comment by fightingcat** [comment]
> Only happened with busybox?

Yes, I removed "echo.exe" from scoop shims folder, problem solved. Glad to hear it's fixed, thank you!
