### ISSUE TITLE
1.2.1 - Generating...

### ISSUE THREAD

**Issue by luckman212** [rustdesk/rustdesk#5041]
### Bug Description

Same issue as #314

- RustDesk 1.2.1
- macOS 13.4.1

### Telnet OK

<img width="373" alt="image" src="https://github.com/rustdesk/rustdesk/assets/1992842/aa2c03c1-0228-4ef1-8b04-6ff4302fd9a1">

### UI just says "Generating..."

<img width="800" alt="screenshot_3LrTRLUS_gh" src="https://github.com/rustdesk/rustdesk/assets/1992842/3ac3a830-121d-452e-a0e8-49c2bf370490">

### How to Reproduce

Launch app

### Expected Behavior

Shows ID

### Operating system(s) on local side and remote side

macOS 13.4.1

### RustDesk Version(s) on local side and remote side

1.2.1

### Screenshots

see above

**Comment by rustdesk** [comment]
many duplicate about this

**Comment by rustdesk** [comment]
maybe https://github.com/rustdesk/rustdesk/discussions/5209
