### ISSUE TITLE
--get-id only puts id into clipboard after first start of rustdesk

### ISSUE THREAD

**Issue by thalion0** [rustdesk/rustdesk#5043]
### Bug Description

Silently deploying Rustdesk v1.2.1 and trying to get the ID with parameter --get-id results in empty result

### How to Reproduce

- install rustdesk silently with --silent
- after installation directly:
`c:\program files\rustdesk\rustdesk.exe --get-id`

ends up in an empty result

using powershell the script will be

```
'c:\program files\rustdesk\rustdesk.exe --get-id'
Get-Clipboard
```

### Expected Behavior

- to get the id in commandline instead of clipboard
- get id as soon as using the parameter

### Operating system(s) on local side and remote side

Windows 10 -> Linux and Windows 10 -> Windows 10 and on local machine same

### RustDesk Version(s) on local side and remote side

1.2.1

### Screenshots

![Bildschirmfoto vom 2023-07-17 22-01-30](https://github.com/rustdesk/rustdesk/assets/8501714/9cb3cd98-bda6-49ec-b348-d1980a850594)

**Comment by dinger1986** [comment]
sorry I now follow what you mean. Id imagine this is by design however I would agree that it would be good for it to output directly, using the command `'C:\Program Files\RustDesk\rustdesk.exe' --get-id | get-clipboard`

**Comment by rustdesk** [comment]
it can not output because it is a gui windows program which can not output to current console.

**Comment by rustdesk** [comment]
i dont understand why 1.2.0 can output in rmm as @dinger1986 said，in my test, both 1.9 and 1.2 can not in cmd or powershell.

anyway, get clipboard is a good solution.

i planned to write a separate cmd program for this, since get clipboard works, i give up the plan.

**Comment by dinger1986** [comment]
Clipboard works! I have added it to the docs

**Comment by jplandry908** [comment]
Does anyone know if there is a way to retrieve the id (--get-id) and set the password (--password) in Windows without producing the GUI dialog box?

**Comment by dinger1986** [comment]
Do it from some background process using powershell. Psexec or something would work or an rmm? Or intune, there's loads of options.

Can use get-clipboard with powershell to get the id, set password needs to be ran from SYSTEM.

**Comment by Eruthon** [comment]
Managed to get the ID with this:

```
Start-Job -Name RustDesk-ID -ScriptBlock { cmd.exe /c "C:\Program Files\RustDesk\rustdesk.exe" --get-id }
Wait-Job -Name RustDesk-ID -timeout 1
Get-Clipboard
```

**Comment by thalion0** [comment]
Yes, this solves the issue. Thanks  @Eruthon

**Comment by ssendev** [comment]
@rustdesk in powershell it's possible to get the version like this
```ps1
& 'C:\Program Files\RustDesk\rustdesk.exe' --version | Out-String
```
so can you please make `--get-id` do the same

**Comment by rustdesk** [comment]
> @rustdesk in powershell it's possible to get the version like this
> 
> ```powershell
> & 'C:\Program Files\RustDesk\rustdesk.exe' --version | Out-String
> ```
> 
> so can you please make `--get-id` do the same

@dinger1986 how about removing dialog totally and also removing clipboard? Revert back to 1.1.9.

**Comment by dinger1986** [comment]
yes not a bad idea, but would be good that you dont need to have system privileges and but should be elevated

**Comment by rustdesk** [comment]
--get-id can remove priviledge requirement, but --set-id / --password is required, but on GUI, it is required, so it must be unified.

**Comment by dinger1986** [comment]
No it should only be accessible with admin privileges via elevation (right click powershell run as administrator for example) but previously with 1.1.9 it needed to run in the SYSTEM context which meant others couldn't access it.
