### ISSUE TITLE
No connection to server outside local network

### ISSUE THREAD

**Issue by Sasalino** [rustdesk/rustdesk#5050]
### Bug Description

Hi,

I have RustDesk server installed on my Synology in a docker. Version 1.1.9 worked fine, but since 1.2.1 update I get no connection when I try to connect outside of my local network.

DynDNS, ports, etc. has not been changed since 1.1.9 and I already resetted both, router and nas. Access to my DDNS is ok. I also completely deleted docker and reinstalled - unfortunately all without success.

Any ideas what could cause blocking access from outside? As said connection within my local network is no problem.

S.

### How to Reproduce

Installation on Synology docker using this guide: [https://mariushosting.com/how-to-install-rustdesk-on-your-synology-nas/](url)

### Expected Behavior

Connection only works in local network or when not using own server

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.2.1 > 1.2.1 or 1.1.9

### Screenshots

![0012 - 2023-07-18](https://github.com/rustdesk/rustdesk/assets/139803486/908cb796-b056-4c2a-baed-a6bb281211c8)

**Comment by rustdesk** [comment]
#763

**Comment by zhangbo8418** [comment]
The old problem has reappeared in the latest version 1.2.4.

**Comment by zhangbo8418** [comment]
> #763

The old problem has reappeared in the latest version 1.2.4.
