### ISSUE TITLE
macOS - keyboard behaving unexpectedly after some time

### ISSUE THREAD

**Issue by JohnG340** [rustdesk/rustdesk#5051]
### Bug Description

When remote controlling a mac computer, after some time the keyboard will not behave properly. Pressing certain letters such as “a” or “t” does not produce those typed letters. Rather, it does something completely different as if it were a shortcut.

One example of this is when typing the letter “a”, it will highlight an application on the dock rather than actually type out “a”. The letter “t” also does something unexpected.

### How to Reproduce

Connect to a macOS machine (local can be windows or macOS) and continue to type on the remote machine. Issue will eventually show. Can’t figure out exact reproducibility steps.

### Expected Behavior

pressing letters should print out the letters rather than acting as some sort of shortcuts 

### Operating system(s) on local side and remote side

osx -> osx and windows -> osx

### RustDesk Version(s) on local side and remote side

1.2.0 > 1.1.9

### Screenshots

N/A

**Comment by rustdesk** [comment]
both 1.2.1 please.
