### ISSUE TITLE
Server and a key are visible to users (ubuntu 23.04 polkit)

### ISSUE THREAD

**Issue by regs01** [rustdesk/rustdesk#5057]
### Bug Description

Back in 1.2.0 nightlies servers and a key were not visible to a user and required elevation to see and change them. But in 1.2.1 they are free to see and change again.

### How to Reproduce

Settings - Network options

### Expected Behavior

Servers and a key better to be not exposed.

### Operating system(s) on local side and remote side

Ubuntu 2304

### RustDesk Version(s) on local side and remote side

1.2.1

### Screenshots

-

**Comment by rustdesk** [comment]
It works well on my ubuntu 22.

![image](https://github.com/rustdesk/rustdesk/assets/71636191/d322d328-3bb2-4b4d-8424-90c8cd65e97b)

**Comment by rustdesk** [comment]
Close as tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by rustdesk** [comment]
AppImage does not have this.

**Comment by rustdesk** [comment]
Removed from https://github.com/rustdesk/rustdesk/issues/3565
