### ISSUE TITLE
File Transfer requests password even if a Desktop session is active

### ISSUE THREAD

**Issue by jacotec** [rustdesk/rustdesk#5063]
### Bug Description

When you already have a Desktop session active and start a file transfer from the desktop session window, you are asked for the password again.

If you are helping someone who gave you the random generated password, you need to ask the remote side again for the password (in case you have not written it down). It'll be more convenient if in this case the file transfer session is treated as authenticated if a desktop session is already active.

### How to Reproduce

- Open a remote desktop session to a different PC using the random gerenrated password
- In the session window, start a file transfer
- Rustdesk asks again for the password to connect the file transfer session

### Expected Behavior

Rustdesk should treat the session as authenticated if a remote desktop session is already active

### Operating system(s) on local side and remote side

Windows <-> Windows

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

N/A

**Comment by rustdesk** [comment]
I understand your request, but we have no plan to do the change.

**Comment by rustdesk** [comment]
I will handle this https://github.com/rustdesk/rustdesk/issues/9723
