### ISSUE TITLE
Windows compiled EXE full install problem

### ISSUE THREAD

**Issue by stanymanman86** [rustdesk/rustdesk#5064]
### Bug Description

My EXE was compiled with no problem on Windows.
In portable mode no problem all is working.
But when I launch the install as a service, the exe copy all files present in the same folder as the exe in "c:\program files\rustedesk".
This is not appenning with the official exe.

### How to Reproduce

Launch a full install of a compiled EXE on Windows

### Expected Behavior

That only the exe, the broker exe and the uninstall shortcut is copied to "c:\program files\rustdesk"

### Operating system(s) on local side and remote side

Windows 11 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/140049998/ca3cd39a-7dce-4a02-bf1e-1b3e85621f96)
![image](https://github.com/rustdesk/rustdesk/assets/140049998/63774388-03ef-45e9-b913-bbb39d745241)

**Comment by rustdesk** [comment]
#763
