### ISSUE TITLE
Cannot enter with the mouse

### ISSUE THREAD

**Issue by albgen** [rustdesk/rustdesk#5065]
### Bug Description

As soon as i enter the screen, it goes out automatically.
A video will explain better the behaviour.

https://github.com/rustdesk/rustdesk/assets/7231968/86e21f22-8694-4e69-a787-43d8587d657b

### How to Reproduce

This happens only if on the background i open the same server with rdc.

### Expected Behavior

to work properly.

### Operating system(s) on local side and remote side

Local win11, remote win server 2012R2

### RustDesk Version(s) on local side and remote side

1.21 on both sides.

### Screenshots

no need. The video explains it.

**Comment by rustdesk** [comment]
#763
