### ISSUE TITLE
Permanent password not deployable without user interaction

### ISSUE THREAD

**Issue by zackholz** [rustdesk/rustdesk#5074]
### Bug Description

Using software deployment to configure RustDesk automatically.

In v1.1.9 it was possible to do the following steps:
1.	Install RustDesk silently by --silent-install
2.	Stop RustDesk service
3.	Set a client-wide permanent password (clear text) by copying a pre-configured RustDesk.toml located in C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config
4.	Start RustDesk service again
5.	Then you could enter a remote session on this machine without user interaction using the password defined by the deployed RustDesk.toml. (This toml-file and its password were also copied to any existing user’s RustDesk.toml.)

Was this mechanism removed for security reasons?

This is immensely important for me to enter remote sessoins on vanilla installed machines, where no user has been logged on yet.

This works no longer.
The password (meanwhile hashed) is overwritten by another (maybe a default or empty or unguessable?) value, which destroys the deployment of a pre-configured client-wide password.

### How to Reproduce

See the steps 1-5 from description above.

### Expected Behavior

The password value in C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml should not be overwritten when RustDesk service is started. Instead, the pre-configured password should be applied.
Moreover, RustDesk.toml from service profile should be applied to all users existing on this machine – at least if the machine never ever had a logged on user.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

![rustdesk-wrong-pw](https://github.com/rustdesk/rustdesk/assets/131375913/cc1b3611-0ad1-407a-9343-2c69d6ed64bb)

**Comment by dinger1986** [comment]
not a bug, this has been changed to a flag `--password` as these files should now be encrypted with 1.2.0 >

https://github.com/rustdesk/rustdesk/blob/072338afae07355129e8d56d869ca62525e667ac/src/core_main.rs#L239

**Comment by dinger1986** [comment]
please close :)
