### ISSUE TITLE
Web Client not popping up keyboard

### ISSUE THREAD

**Issue by tschettervictor** [rustdesk/rustdesk#5081]
### Bug Description

The Web Client (I know it’s beta) is not popping up the keyboard on iOS (brave chrome safari)

### How to Reproduce

Connect to server with Web Client and try to open keyboard.

### Expected Behavior

I expect the keyboard to show when clicking the keyboard icon.

### Operating system(s) on local side and remote side

iOS 16.5/17 > Windows 10

### RustDesk Version(s) on local side and remote side

1.1.10 > 1.2.1

### Screenshots

No screenshots at this time.

**Comment by rustdesk** [comment]
This web client is not maintained.
