### ISSUE TITLE
Can't chose original resolution 3840x2160

### ISSUE THREAD

**Issue by fixsssator** [rustdesk/rustdesk#5082]
### Bug Description

![image](https://github.com/rustdesk/rustdesk/assets/74709706/c1d32855-8356-4ff0-8a4c-14bc09da5bc1)
The issue is - I can't choose the original resolution 3840x2160
Rustdesk doesn't do anything at all.

### How to Reproduce

Try to chose original resolution 3840x2160

### Expected Behavior

I'm expect resolution 3840x2160

### Operating system(s) on local side and remote side

windows 11

### RustDesk Version(s) on local side and remote side

rustdesk-1.2.1-nightly

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/74709706/910f8543-5e82-4d17-b362-9db62ee1e777)

**Comment by rustdesk** [comment]
@fufesou why do we have this stupid bug again? I had emphasised on this.

**Comment by fufesou** [comment]
@fixsssator Hi, thanks for your feedback.

How did you change the resolution?
It seems `3840x2160` is the resolution before the rustdesk session, but the resolution is not supported on current state of the remote side.

![1689999017511](https://github.com/rustdesk/rustdesk/assets/13586388/a51f3656-da56-4c34-950d-d957329f0268)

Can you please open the "Display settings" to see what resolutions are supported for now?

![1689999167708](https://github.com/rustdesk/rustdesk/assets/13586388/f942b9fb-135d-457c-88f5-7bd8115fc5ab)

**Comment by fufesou** [comment]
Did the resolution on the remote side revert back after you disconnected the rustdesk session?

**Comment by fixsssator** [comment]
Hi @fufesou
That's so strange because before I chose 2560x1600 resolution it could connect and use 3840x2160 resolution. 
But I can't revert back and chose original resolution now because I changed it in the rustdesk.
Yes resolution on the remote side revert back after I disconnected the rustdesk session

**Comment by fufesou** [comment]
Can you please make a test without rustdesk, just operate on the remote side?
If you manually change the resolution to 2560x1600, is 3840x2160 still in the resolution list?

It seems that there're some missing steps or parameters in our change resolution call.

**Comment by rustdesk** [comment]
close to favor https://github.com/rustdesk/rustdesk/issues/6071
