### ISSUE TITLE
Can't open it again.

### ISSUE THREAD

**Issue by LanYunDev** [rustdesk/rustdesk#5083]
### Bug Description

Unable to open the app again.
<img width="296" alt="image" src="https://github.com/rustdesk/rustdesk/assets/95263282/e15bf398-42ef-4099-b81e-2f2b551796a8">
<img width="979" alt="image" src="https://github.com/rustdesk/rustdesk/assets/95263282/59bee41e-851c-436a-a258-ad074eab916b">
There is no icon for the app in the menu bar.
This is the only way to open it again at the moment: open /Applications/RustDesk.app/Contents/MacOS/RustDesk

### How to Reproduce

System version: macOS 14.0 Beta(23A5286i)
Software version: 1.2.1 or  52ce3dd:[rustdesk-1.2.1-x86_64.dmg](https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.1-x86_64.dmg)
When the first installation is completed, it opens without any problem, but after closing the window, it will not open again.

### Expected Behavior

It should open properly.

### Operating system(s) on local side and remote side

Any

### RustDesk Version(s) on local side and remote side

1.2.1

### Screenshots

<img width="296" alt="image" src="https://github.com/rustdesk/rustdesk/assets/95263282/e15bf398-42ef-4099-b81e-2f2b551796a8">
<img width="979" alt="image" src="https://github.com/rustdesk/rustdesk/assets/95263282/59bee41e-851c-436a-a258-ad074eab916b">

**Comment by rustdesk** [comment]
macOS 14.0 Beta

**Comment by rustdesk** [comment]
https://www.reddit.com/r/rustdesk/comments/1593k1q/better_image_quality/

<img width="569" alt="image" src="https://github.com/rustdesk/rustdesk/assets/71636191/d9855a05-d88b-47aa-bc90-b7980968bd16">
