### ISSUE TITLE
RustDesk on macOS has no sound when being remotely controlled

### ISSUE THREAD

**Issue by nanyina** [rustdesk/rustdesk#5086]
### Bug Description

I attempted to use loopback software to allow the other party to hear the sound from my Mac. I selected Loopback as the audio input device in RustDesk, but the other party couldn't hear my audio. My system version is 13.4.1. I also tried on another Mac with version 12, but encountered the same issue. Even when not using loopback audio and using my sound card, the problem remains – the other party can't hear the sound. I've confirmed that there are no issues with my server because it works fine on systems other than Mac.

### How to Reproduce

You can use an external sound card or Loopback on Mac

### Expected Behavior

I hope to have the sound transmitted properly on the Mac system

### Operating system(s) on local side and remote side

mac os 13-> mac os 13

### RustDesk Version(s) on local side and remote side

1.2.1-> 1.2.1

### Screenshots

<img width="1200" alt="image" src="https://github.com/rustdesk/rustdesk/assets/140255424/f316d5cf-7413-4681-94cd-0b908ab8f34d">
<img width="800" alt="image" src="https://github.com/rustdesk/rustdesk/assets/140255424/d31e1956-0e7e-49dc-9ffe-dbad61141b24">

**Comment by rustdesk** [comment]
no duplicate please
