### ISSUE TITLE
where is the web control panel on latest version?

### ISSUE THREAD

**Issue by MMMMMoris** [rustdesk/rustdesk#509]
I remember there was a port 21114 especially set for web control panel, and I was also asked to register with email when I build my own relay server just a month ago!!!
However, now I cannot find any docs or tutorials to setup the web control panel. 
WHY? I DON'T UNDERSTAND!
Is there any problem with this feature? I think it's great! Why had it remove?

**Comment by rustdesk** [comment]
It is temporarily removed, because I am still thinking about how to do our RustDesk Server Pro version.

**Comment by MMMMMoris** [comment]
> It is temporarily removed, because we am still thinking about how to do our RustDesk Server Pro version for adavanced business users.

it costs? I mean the pro version

**Comment by rustdesk** [comment]
> it costs? I mean the pro version

Of course, we need to feed our family also.

**Comment by MMMMMoris** [comment]
> > it costs? I mean the pro version
> 
> Yes, we need to feed our family also. The open source version is enough for non-business users and most of small business users.

I support you charging for it's a great software, however I want to ask that if a common user has the opportunity to use the web console in the future? I long for it, it's convenient

**Comment by SmileZD** [comment]
> > > it costs? I mean the pro version
> > 
> > 
> > Yes, we need to feed our family also. The open source version is enough for non-business users and most of small business users.
> 
> I support you charging for it's a great software, however I want to ask that if a common user has the opportunity to use the web console in the future? I long for it, it's convenient

https://github.com/rustdesk/rustdesk-server-demo
I suggest you continue to develop according to this, and I'm doing the same

**Comment by MMMMMoris** [comment]
> > > > it costs? I mean the pro version
> > > 
> > > 
> > > Yes, we need to feed our family also. The open source version is enough for non-business users and most of small business users.
> > 
> > 
> > I support you charging for it's a great software, however I want to ask that if a common user has the opportunity to use the web console in the future? I long for it, it's convenient
> 
> https://github.com/rustdesk/rustdesk-server-demo I suggest you continue to develop according to this, and I'm doing the same

I am afraid that I don't have the ability to develop this demo as good as the author, I am not a rust-learning as well, it's challenging

**Comment by rustdesk** [comment]
> > > > it costs? I mean the pro version
> > > 
> > > 
> > > Yes, we need to feed our family also. The open source version is enough for non-business users and most of small business users.
> > 
> > 
> > I support you charging for it's a great software, however I want to ask that if a common user has the opportunity to use the web console in the future? I long for it, it's convenient
> 
> https://github.com/rustdesk/rustdesk-server-demo I suggest you continue to develop according to this, and I'm doing the same

Yes, demo[rustdesk-server-demo](https://github.com/rustdesk/rustdesk-server-demo)  is good start.  https://github.com/rustdesk/rustdesk-server looks a little complex for starter.

**Comment by MMMMMoris** [comment]
> > > > > it costs? I mean the pro version
> > > > 
> > > > 
> > > > Yes, we need to feed our family also. The open source version is enough for non-business users and most of small business users.
> > > 
> > > 
> > > I support you charging for it's a great software, however I want to ask that if a common user has the opportunity to use the web console in the future? I long for it, it's convenient
> > 
> > 
> > https://github.com/rustdesk/rustdesk-server-demo I suggest you continue to develop according to this, and I'm doing the same
> 
> Yes, https://github.com/rustdesk/rustdesk-server-demo is a good start. https://github.com/rustdesk/rustdesk-server looks a little complex for starter.

So web console is gonna be a pro feature? Upset🥲

**Comment by rustdesk** [comment]
> use the web console in the future

Yes,  it is possible, we just choose to be conservative for the time being.

**Comment by Arrmm** [comment]
What is the default username and password for the current version?  I understand you want to make money and remove it in the future but I need it for the current version that I have installed.

**Comment by rustdesk** [comment]
admin/test1234

**Comment by whoruthen** [comment]
> What is the default username and password for the current version? I understand you want to make money and remove it in the future but I need it for the current version that I have installed.

May i have a copy? I need it at present, indeed. I will pay for it when the lastest version come out with this feature. I just need this now. I will be really appreciative if you can send me a copy to lacus@transc1ear.com

**Comment by wu0lei** [comment]
> 管理员/test1234

I forgot my web console account and password, how to retrieve it

**Comment by rustdesk** [comment]
> > 管理员/test1234
> 
> I forgot my web console account and password, how to retrieve it

I have replied to you twice both by mail and issue on doc.

**Comment by rustdesk** [comment]
>  I forgot admin password, how to reset?

I am sorry to tell you, we have no interface to modify the admin password if you forget it. But you can remove db_v2.sqlite3 file and then restart hbbs/hbbr, and you will lose all the other user info. New admin password will be test1234.
