### ISSUE TITLE
Fedora 38 Rustdesk 1.2.x and SELinux

### ISSUE THREAD

**Issue by JeffreyKopcak** [rustdesk/rustdesk#5098]
### Bug Description

Have a bunch of issues connecting using Fedora 38 with 1.2.x.  They appear to be SELinux related.

### How to Reproduce

- Clean install of Fedora 38 (remote side)
- performed `sudo dnf -y update`
- reboot
- Downloaded rustdesk-1.2.1-0.x86_64.rpm
- `sudo dnf -y install ./rustdesk-1.2.1-0.x86_64.rpm`

Shortly after install, SELinux starts spewing denial messages.

- From another machine (local side), enter ID for Control Remote Desktop.
- Click Connect.  Error is:

> Failed to connect via rendezvous server: Please try later

- On the remote side, `sudo setenforce 0`
- From the local side, click Connect.
- This time, receive the password prompt.  After entering the generated password:

> connection refused

### Expected Behavior

No SELinux messages, connection completes. Did not have these issues using 1.1.9 on both sides.

### Operating system(s) on local side and remote side

Fedora 38 -> Fedora 38

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.2.1-0

### Screenshots

[rustdesk_logs.tar.gz](https://github.com/rustdesk/rustdesk/files/12141712/rustdesk_logs.tar.gz)
Rustdesk logs (sanitized, removed IPs) and grepped messages log for relevant SELinux messages from the remote.  I can provide unedited logs upon request via E-mail or other non-public method.

![Screenshot from 2023-07-23 23-17-23](https://github.com/rustdesk/rustdesk/assets/2723529/692abaa3-6bef-40aa-83fd-ec7510ac1b53)
Local, error connecting after program install on remote

![Screenshot from 2023-07-23 23-20-04](https://github.com/rustdesk/rustdesk/assets/2723529/20f0c7ea-e34c-4c4d-ab7f-db465713a918)
Local, error connecting after setenforce 0 on remote

### Additional Context

A full system install of the remote machine includes Nvidia's Linux drivers. I have seen messages referencing Nvidia programs on that install - they might be SELinux related too - and there could be more issues than already provided.  On the test install of the remote machine, I didn't get to the point of installing the Nvidia drivers before having connection issues.

For reference, Rustdesk (via dnf) installed at

> Jul 23 23:04:11

setenforce 0 at

> Jul 23 23:18:55

Let me know if you need anything else.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4267
