### ISSUE TITLE
远程控制对方时候，有时候对方的电脑弹出个msgbox框，就无法控制了

### ISSUE THREAD

**Issue by HeliusHao** [rustdesk/rustdesk#51]
对方电脑是windows 10 ，不知道这是因为哪里的问题

**Comment by rustdesk** [comment]
install

**Comment by HeliusHao** [comment]
> install

No more problems after installation?
Console installation? Or is it a control-side installation?

**Comment by rustdesk** [comment]
controlled side

**Comment by HeliusHao** [comment]
> controlled side

think

**Comment by HeliusHao** [comment]
> controlled side

Is there a parameter for double-clicking to perform automatic installation?

**Comment by rustdesk** [comment]
![image](https://user-images.githubusercontent.com/71636191/120605267-71db7d80-c480-11eb-9349-ac62d8b89749.png)

**Comment by HeliusHao** [comment]
cmd >  RustDesk.exe -install 
Is there a way to do this?

**Comment by rustdesk** [comment]
> cmd > RustDesk.exe -install
> Is there a way to do this?

Why do u need this?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/108
