### ISSUE TITLE
"swiss german keyboard" one key does not work

### ISSUE THREAD

**Issue by jfdelphi** [rustdesk/rustdesk#5101]
### Bug Description

i use windows .

i have on both sides same keyboard settings "swiss german keyboard"

only ONE key is not forwarded to the remote client 
it is the "]" 

thanks for your quick fix :-)

### How to Reproduce

just use "swiss german keyboard" on both sides

### Expected Behavior

it shold for ward the y key :-)

### Operating system(s) on local side and remote side

windows 11 => windows 2019

### RustDesk Version(s) on local side and remote side

1.1.9 - 1.1.9

### Screenshots

not required

**Comment by rustdesk** [comment]
1.2.1 please.
