### ISSUE TITLE
After updating to version 1.2.1, it is not possible to control the computer with the mouse.

### ISSUE THREAD

**Issue by Bob-ju** [rustdesk/rustdesk#5102]
### Bug Description

1. When using the mobile client to initiate a request, it can display the computer's screen information, but only for viewing purposes, mouse clicking operations are not possible.
2. Another person needs to click on the button on the computer screen to disable keyboard/mouse control, and then click again to allow it, in order for the mobile side to be able to control the computer with the mouse properly.
3. Tried using the mobile device to control both PC and Mac computers, the situation is the same.

![Snipaste_2023-07-24_14-57-32](https://github.com/rustdesk/rustdesk/assets/10295975/03a4fc91-6e33-4690-ad48-626b6fbed596)

Computer System Version: win 10; RustDesk Version: 1.2.1
Computer System Version: MAC OS 13.4.1; RustDesk Version: 1.2.1
Mobile System Version: iOS 16.0.3; RustDesk Version: 1.1.10

### How to Reproduce

When initiating a request from the mobile device to connect to the computer, you are able to see the computer screen, but unable to use the mouse to operate anything.

### Expected Behavior

After connecting the mobile device to the computer, you can directly use the mouse to control the computer. There is no need to click or perform any operation on the computer to allow control from the mobile device.

### Operating system(s) on local side and remote side

iOS -> windows 10 ; iOS -> Mac OS

### RustDesk Version(s) on local side and remote side

1.1.10 -> 1.2.1

### Screenshots

https://github.com/rustdesk/rustdesk/assets/10295975/208d394b-be2a-4e9c-8198-79f285b52c28

### Additional Context

In a previous older version, this situation would not occur.

**Comment by rustdesk** [comment]
Wait for new iOS please. No ETA yet.
