### ISSUE TITLE
Custom Windows cursor appear in white square on Android

### ISSUE THREAD

**Issue by Ceotom** [rustdesk/rustdesk#5105]
### Bug Description

[Amiga Workbench 2.0 Cursor ](https://github.com/sonninnos/Amiga-Workbench-Mouse-Cursors#workbench-20) appear in white square on Android client.

### How to Reproduce

1) Set cursor to Amiga Workbench 2.0 in mouse settings
2) Connect to remote computer and see issue

### Expected Behavior

Cursor should appear without white square like on local machine.

### Operating system(s) on local side and remote side

Android 13 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

![Screenshot_2023-07-24-16-41-52-14_68ed9935803a63844709bbd59cb0bdde](https://github.com/rustdesk/rustdesk/assets/36301121/a31f6556-5e93-4dfe-8f36-e8513bf7bbbb)

### Additional Context

There's no such issue with Linux and web client.

**Comment by rustdesk** [comment]
Not support yet.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893
