### ISSUE TITLE
Rustdesk does not retain Monitor locations/positions after program close/reopen

### ISSUE THREAD

**Issue by godzfire** [rustdesk/rustdesk#5109]
### Bug Description

The main Rustdesk window nor the connection window remember/retain which monitor they are on and where after closing and reopening the app.

### How to Reproduce

1- Open Rustdesk
2- Connect to a remote session
3- Move either windows to a different monitor
4- Quit the program and reopen

The windows will always revert back to the default main monitor and screen location.

### Expected Behavior

The windows will retain their monitor and location placement information and reappear back in those spots after closing and reopening.

### Operating system(s) on local side and remote side

Windows 10 -> Mac

### RustDesk Version(s) on local side and remote side

1.2.0 build 2023 06-28

### Screenshots

N/A

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
close as fix merged, please try out the latest nightly build.

**Comment by RichardBurt65** [comment]
Confirmed fixed on 1.2.2 nightly.
