### ISSUE TITLE
1.2.0+ Not run on MacMini

### ISSUE THREAD

**Issue by dateno1** [rustdesk/rustdesk#5112]
### Bug Description

1.1.9 is Work Well

But 1.2.0/1 is not

### How to Reproduce

1. Turn off RustDesk v1.1.9 and Update to v1.2.1 Can't run it
2. Change to 1.2.0 Same Result
3. Remove RustDesk and Install v1.2.1 Same Result
4. Remove RustDesk and ReInstall v1.1.9 Worked
5. Copy&Run v1.2.1 to Desktop while v1.1.9 is running It can run (Remove v1.1.9 and Replace to v1.2.1 Run tested)
6. but Can get permission (Remove permission -> Permit permission -> ReRun)
7. Downgrade to v.1.1.9 everything is worked

### Expected Behavior

Can't run or Can't get permission

### Operating system(s) on local side and remote side

Windows 10 x64 -> Moterey 12.6.8 (MacMini7,1)

### RustDesk Version(s) on local side and remote side

1.1.9/1.2.1 -> 1.1.9/1.2.0/1.2.1

### Screenshots

![RustDesk](https://github.com/rustdesk/rustdesk/assets/12645246/b1d0c034-a77c-40d4-aa10-2eec4f94e036)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3261

**Comment by dinger1986** [comment]
works fine for me
