### ISSUE TITLE
1.21 night build (25.07.2023) - GUI issue

### ISSUE THREAD

**Issue by bovirus** [rustdesk/rustdesk#5119]
### Bug Description

@rust

GUI issues
Please check screenshot.

### How to Reproduce

Check screenshots

### Expected Behavior

Fix issues

### Operating system(s) on local side and remote side

Windows 10 22H2 64bit italian

### RustDesk Version(s) on local side and remote side

1.2.1 night build

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/1262554/9b6a498e-539a-4c6c-9d90-9807a2d89a8a)
Untranslated strings

![image](https://github.com/rustdesk/rustdesk/assets/1262554/320c60b1-cbc2-47f5-8148-3883bcd761cd)
Beta (night build) has some version of stable version.
Suggested to add +1 as version for night build.

**Comment by bovirus** [comment]
@ruastdesk

The second is not really a GUI issue is just a "pro" GUI beauty improvement.
Appear more "pro" as GUI.

**Comment by bovirus** [comment]
@rustdesk 

Sure.
Please don't forget the version step up (+1) of beta vs stable version.

**Comment by rustdesk** [comment]
another gui pro issue.

![image](https://github.com/rustdesk/rustdesk/assets/71636191/8a44401c-ebc1-46ab-ad6b-f1abd6616671)

**Comment by rustdesk** [comment]
Frankly, there are a lot of gui "pro" issues per my standard.

**Comment by bovirus** [comment]
@rustdesk 

Sorry I didn't know russian.
What's the issue?

**Comment by rustdesk** [comment]
label not aligned
<img width="449" alt="image" src="https://github.com/rustdesk/rustdesk/assets/71636191/ac7fba1c-5df4-4f66-8930-b14b9604a83c">

**Comment by bovirus** [comment]
@rustdesk


In your case you should redesign the GUI.
regarding the issue for "Fingeprint" it' quite easy to fix.
it's enough a small change in the code without redisge the UI.

**Comment by rustdesk** [comment]
> regarding the issue for "Fingeprint" it' quite easy to fix.

Actually it is not that easy, I knew this very earlier.

**Comment by bovirus** [comment]
@rustdesk 

The last night build (today 3 hours ago) seems again 1.2.1 (not 1.2.2).

https://github.com/rustdesk/rustdesk/releases/tag/nightly
