### ISSUE TITLE
Copy and paste (ctrl+c/ctrl+v, right-click->copy/paste) not working

### ISSUE THREAD

**Issue by jpnws** [rustdesk/rustdesk#5123]
### Bug Description

Edit: I just realized that this issue doesn't occur when I remote into the computers with the RustDesk IDs. I have no idea why copy/paste wouldn't work if I connect to the computers through the IP addresses.

I'm currently using Windows 11. I used to use RustDesk 1.1.9 to remotely control multiple computers. I frequently use the copy and paste function (either via ctrl+c or right-click->copy) for texts and files, primarily files, transferring them from the remote computers to my own.

Occasionally, the copy and paste function would fail on v1.1.9, but a simple restart of the application would resolve the issue. This was not a frequent problem, so I didn't consider it a significant concern.

> I made sure to enable the clipboard functionality.

However, since the update to version 1.2.0, the copy and paste feature has been completely unresponsive, even after rebooting my computer or restarting the RustDesk application. I've since updated to version 1.2.1, but I still can't copy and paste using ctrl+c and ctrl+v, or by using the right-click->copy/paste method. I have updated the remote computers to 1.2.1, as well, but that didn't resolve the issue either.

I'm using the file transfer feature for the time being, which works, but it is much less user-friendly than simply using the keyboard shortcuts.

### How to Reproduce

Windows 11, RustDesk v1.2.1, connect to remote computer through IP address, enable clipboard functionality (by unchecking "Disable clipboard"), disconnect from the remote computer and reconnect, and then try ctrl+c to copy any file, and ctrl+v to paste it to your own computer.

### Expected Behavior

The file gets copied and pasted across the remote to local computer.

### Operating system(s) on local side and remote side

Windows 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

There isn't anything in particular that happens when this copy/paste functionality is not working. There is just simply no response or any explicit visual indication that it did not work, it just doesn't copy/paste, so there is no screenshot to show.

### Additional Context

My local computer is Windows 11, using v1.2.1, the remote is Windows 10 with v1.2.1 as well. I'm connecting through the IP addresses.

**Comment by rustdesk** [comment]
no duplicate issue please

**Comment by fufesou** [comment]
https://github.com/rustdesk/rustdesk/issues/2283#issuecomment-1652137344

Hi, @jpnws , can you let me connect your test computer ?

**Comment by jpnws** [comment]
@fufesou, if this was on my personal computer I could, since the computers that I'm using and connecting to are used at a company I work for, it would be difficult to do so. Not sure if this has anything to do with it but one thing for sure is that this issue occurs only when I connect with IP addresses, not with RustDesk IDs.

**Comment by fufesou** [comment]
Thanks. I've tested connect with IP address. The "file copy & paste" also works for me. 😂

**Comment by rustdesk** [comment]
I guess there is initializing issue sensitive to time sequence.

**Comment by jpnws** [comment]
> Thanks. I've tested connect with IP address. The "file copy & paste" also works for me. 😂

Now connecting with IDs are not working 🤔

**Comment by Creling** [comment]
I have the same problem. I am willing to provide my laptop for the test. Please email me at penurious_netconf@simplelogin.com for more details. :)

**Comment by fufesou** [comment]
@Creling Thanks.

I've sent you two emails, but received no reply. Did you receive my emails?

**Comment by fufesou** [comment]
@jpnws @Creling Can you please help test the next nightly build tomorrow.
I've added some logs. If the feature still does not work, the log may tell me something.

**Comment by jpnws** [comment]
> @jpnws @Creling Can you please help test the next nightly build tomorrow. I've added some logs. If the feature still does not work, the log may tell me something.

@fufesou , thanks 🙂, I will, where can I get the nightly? I checked just now, but I don't see it under the Releases page. Is there somewhere else I can download it? or is it yet to come out?

**Comment by dignow** [comment]
@jpnws Thanks. You can download and update here. https://github.com/rustdesk/rustdesk/releases/tag/nightly

Please send me(shuanglongchen@yeah.net) your log files after your tests.

The log files are located at "%appdata%\rustdesk\log".

**Comment by fufesou** [comment]
@jpnws Thanks. You can download and update here. https://github.com/rustdesk/rustdesk/releases/tag/nightly

Please send me(shuanglongchen@yeah.net) your log files after your tests.

The log files are located at "%appdata%\rustdesk\log".

**Comment by mikekgr** [comment]
@fufesou 
I happily confirm that RustDesk nightly 1.2.2 Build Date: 2023-08-01 12:59 has copy / paste working again !!! 
Congratulations for your fine work

**Comment by gusarg81** [comment]
Hi, I am using Rustdesk 1.2.3 and Paste the ID with the keyboard Ctrl +V does not work for me in one of my computers (works with mouse right click and Paste), but does work in the rest with same version (same OS).

Tried to reinstall, deleting all config folders and no success.

Any ideas?

OS: Ubuntu 22.04  (KDE Neon Version).

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/6859#issuecomment-1961959227

**Comment by gusarg81** [comment]
> [#6859 (comment)](https://github.com/rustdesk/rustdesk/issues/6859#issuecomment-1961959227)

Installed latest, same thing: Paste works as Ctrl + C instead of Ctrl + V in the main Window (which I use to Paste computers ID).

**Comment by rustdesk** [comment]
How about double click?

**Comment by rustdesk** [comment]
because I undertand now, removing noisy message, I will this message and your why later either.

**Comment by Elmojomo** [comment]
This issue does not appear to be resolved.  I'm having the same problem on 1.2.3-1, Win10x64.
Both CTRL+C/V and right-clicks fail to transfer files.

**Comment by fufesou** [comment]
@Elmojomo Hi, do you use Windows and 1.2.3-1 on both sides?
Please also make sure the option is enabled.

![image](https://github.com/rustdesk/rustdesk/assets/13586388/f6470937-e95d-4c71-9d1e-3daa7824ab59)

**Comment by Elmojomo** [comment]
> @Elmojomo Hi, do you use Windows and 1.2.3-1 on both sides? Please also make sure the option is enabled.
> 
> ![image](https://private-user-images.githubusercontent.com/13586388/322197037-f6470937-e95d-4c71-9d1e-3daa7824ab59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMTY1MzYsIm5iZiI6MTcxMzAxNjIzNiwicGF0aCI6Ii8xMzU4NjM4OC8zMjIxOTcwMzctZjY0NzA5MzctZTk1ZC00YzcxLTlkMWUtM2RhYTc4MjRhYjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDEzNTAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4MWI2Mjg4M2E3OTRlZTU0NGNiMTYwZTNjZDM2M2JlNDg4Y2MyNTg4M2Y5YmU0MmNmNTU3NzNiYzczZjE0MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KXWfaio3InSI0KYxs1V507QRgdJGHhQ1Vrab1z0sTaA)

Yes, same version, both sides.
Hey, I never saw that option before!  That's odd.  Why would I need to enable it again on the client side, when I already set up file transfers when I installed the app?  Weird.  Anyway, that seemed to fix it, thanks!

**Comment by b-trope** [comment]
> @Elmojomo Hi, do you use Windows and 1.2.3-1 on both sides? Please also make sure the option is enabled.
> 
> ![image](https://private-user-images.githubusercontent.com/13586388/322197037-f6470937-e95d-4c71-9d1e-3daa7824ab59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MTQwOTUsIm5iZiI6MTcxNDcxMzc5NSwicGF0aCI6Ii8xMzU4NjM4OC8zMjIxOTcwMzctZjY0NzA5MzctZTk1ZC00YzcxLTlkMWUtM2RhYTc4MjRhYjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDA1MjMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxZjc1ODE2ZjNkZTBjZjVkMmQwN2M1MGY0MzViNTZhZTFhOGNjY2MyOTBhNjBlMTk4OWFjZTljOGMzNTlkNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cfFhUB-5ueJJvgYjOjdjDeaaqk-l6ZDBf2-E2kmjq_4)

Copy-paste doesn't work at all for me, and the menu you've shown looks different for on my screen.  There is no "allow file copy and paste" option present (pic attached).

I've enabled the option in the settings everywhere else i've been able to find it on both the client and host.

Please help! RealVNC started charging $$ to use it, and I keep spending all my money on avocado toast and SBC's :(

![Rustdesk mission option](https://github.com/rustdesk/rustdesk/assets/80764748/467ec370-d99e-4f1c-9105-2de8eed55ced)

Host Device: Raspberry Pi 4
OS: Raspberry Pi OS 2024-03-15
Rustdesk version: rustdesk-1.2.3-2-aarch64.deb

Client Device: Lenovo Legion 5
OS: Windows 11 Home x64
Version: 1.2.3-2

**Comment by fufesou** [comment]
@b-trope Both sides, Windows are required for now.

**Comment by eduarboxx** [comment]
Today I started using RustDesk and encountered an issue with clipboard functionality: copying and pasting text or files from the host device to the client didn’t work. I searched forums but couldn’t find any solution that worked for me.

Since RustDesk is configured by default to prevent changes to settings while connected, I initially thought I’d need to adjust the settings using AnyDesk as an alternative for testing. Later, I realized I could enable these options directly in RustDesk (my bad for not checking earlier! 😅).

During these tests, I noticed that copying text and files from the clipboard worked at times but then stopped working. That’s when I realized that RustDesk’s clipboard functionality only worked while AnyDesk was open and connected to the same device that RustDesk was connected to.

After conducting further tests, I confirmed the following:

    Text and files: Copying and pasting from the clipboard works correctly if AnyDesk is open and connected to the same device that RustDesk is connected to.
    Images: It is not possible to copy and paste images directly from the clipboard, even if AnyDesk is open and connected.
    
    **System Information**
    Host Device:
        Operating System: Arch Linux x86_64
        Kernel: Linux 6.12.6-zen1-1-zen
        Desktop Environment: GNOME 47.2
        Window Manager: Mutter (Wayland)
        RustDesk Version: 1.3.6 (Flatpak)
        AnyDesk Version: 6.4.0
        File Manager: (specify here, e.g., Nautilus, Dolphin, Thunar, etc.)
        GPU: AMD Radeon RX 7600 XT
        CPU: AMD Ryzen 7 3700X

    Client Device:
        Operating System: Windows 11 (latest version as of January 2, 2025)

**Comment by fufesou** [comment]
@eduarboxx Thanks for your feedback.

Your "copy&paste" is actually performed by anydesk.

File "copy&paste" only works for `Win->Win` now.

> opying and pasting text or files from the host device to the client didn’t work.

How about copying text from the client to the host?

AppImage works for me. flatpak should work tool. I'll test flatpak later.

**Comment by fufesou** [comment]
Reproduced. 

Clibpboard

| Type | Wayland/X11 |  |
| :--: | :--: | :--: |
| Flatpak | Wayland | ❌  |
|  Flatpak | X11 | ✅   |

I'll try to fix it.

**Comment by eduarboxx** [comment]
Hi @fufesou,

Thank you for looking into this issue and for your detailed response! I wanted to share a few clarifications based on my testing:

Clipboard for text:
-  Clipboard functionality for text works bidirectionally. I can copy and paste text both from the client to the host and from the host to the client without issues.

Clipboard for files:
-   Copying files works only from the host to the client. However, copying files from the client to the host does not work.

Environment:
-  I’m using Wayland with the Flatpak version of RustDesk. Based on your table, I understand this configuration currently has issues.

Thank you again for reproducing this issue and working on a fix. Let me know if you need any additional testing or logs from my setup.
