### ISSUE TITLE
After restarting the Linux system: connection refused (Debian12 xfce)

### ISSUE THREAD

**Issue by Baloneo** [rustdesk/rustdesk#5126]
### Bug Description

After restarting the system. stay on the login screen.

then remote control through RustDesk.

rustdesk: connection refused

log in via ssh, check the log

sudo journalctl -f
```
7月 26 17:09:59  rustdesk[2851]: No protocol specified
7月 26 17:09:59  rustdesk[2851]: No protocol specified
7月 26 17:10:01  systemd[1]: todeskd.service: Scheduled restart job, restart counter is at 366.
7月 26 17:10:01  systemd[1]: Stopped todeskd.service - ToDesk Daemon Service.
7月 26 17:10:02  systemd[1]: Started todeskd.service - ToDesk Daemon Service.
7月 26 17:10:02  kernel: traps: ToDesk_Service[25962] trap invalid opcode ip:4d06da sp:7ffd9c3c96a0 error:0 in ToDesk_Service[400000+140f000]
7月 26 17:10:02  systemd[1]: todeskd.service: Main process exited, code=killed, status=4/ILL
7月 26 17:10:02  systemd[1]: todeskd.service: Failed with result 'signal'.
7月 26 17:10:03  sudo[26003]:  user1 : TTY=pts/1 ; PWD=/home/user1 ; USER=root ; COMMAND=/usr/bin/journalctl -f
```

### How to Reproduce

After restarting the system. stay on the login screen.

then remote control through RustDesk.

It is normal after logging in to Linux.

### Expected Behavior
-

### Operating system(s) on local side and remote side

Debian12 xfce

### RustDesk Version(s) on local side and remote side

1.2.1

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/16448666/9b56e82d-36ca-4ac3-bf72-4ada48e9835f)

![image](https://github.com/rustdesk/rustdesk/assets/16448666/02e76541-267b-49f1-9b11-71fef34fe877)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
