### ISSUE TITLE
ubuntu arm架构部署1.2.1版本客户端，软件打开闪退，无法进入页面

### ISSUE THREAD

**Issue by cwy1996** [rustdesk/rustdesk#5127]
### Bug Description

Ubuntu 20.04.6 LTS  arm架构安装1.2.1版本，出现点击软件后，在等待几秒后，软件自动退出显现

### How to Reproduce

正常安装

### Expected Behavior

软件能正常打开

### Operating system(s) on local side and remote side

Win10  -->  Ubuntu

### RustDesk Version(s) on local side and remote side

1.2.1  -->  1.2.1

### Screenshots

https://github.com/rustdesk/rustdesk/assets/76695859/5199705f-ce77-4df4-ba2a-9e3265eabff8

### Additional Context

uname -a
Linux firefly 5.10.110 #2 SMP Wed Apr 26 15:55:28 CST 2023 aarch64 aarch64 aarch64 GNU/Linux

-----------------------------------------------------------------------------------------------------------------

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by cwy1996** [comment]
在命令行执行rustdesk后获得如下报错

libGL error: failed to create dri screen
libGL error: failed to load driver: rockchip
libGL error: failed to create dri screen
libGL error: failed to load driver: rockchip
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(57)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed
Aborted (core dumped)

**Comment by rustdesk** [comment]
https://www.reddit.com/r/FlutterDev/comments/159tt8i/flutter_desktop_compatibility_is_getting_worse/

**Comment by rustdesk** [comment]
https://news.ycombinator.com/item?id=36872677

**Comment by cwy1996** [comment]
这需要等待更新或者更换desktop么

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2543#issuecomment-1352938954

**Comment by cwy1996** [comment]
好像没有效果，ubuntu-drivers devices  无信息出现

**Comment by rustdesk** [comment]
try out LIBGL_ALWAYS_SOFTWARE=1 rustdesk
