### ISSUE TITLE
Please correct `MimeType`

### ISSUE THREAD

**Issue by sukanka** [rustdesk/rustdesk#513]
**Describe the bug you encountered:**
rustdesk becomes the default HTML viewer, and the default viewer for many other files, but actually, it can't open any files. 
The following line should be changed or removed.
https://github.com/rustdesk/rustdesk/blob/d01eb70b48df0f786889b9510fcda507228dbe72/snap/gui/rustdesk.desktop#L10
...

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**
https://aur.archlinux.org/packages/rustdesk-bin

---

**RustDesk version and environment**
rustdesk-bin-1.1.8 running on archlinux.

**Comment by rustdesk** [comment]
Thanks, we will modify. BTW, https://aur.archlinux.org/packages/rustdesk-bin is not maintained by us.

**Comment by sukanka** [comment]
Thanks, i know that. AUR just repacks the package. But I feel it will be better that the upstream solves this issue than just aur. So I also reported it here. Thanks for your swift response.

**Comment by rustdesk** [comment]
> Thanks, i know that. AUR just repacks the package. But I feel it will be better that the upstream solves this issue than just aur. So I also reported it here. Thanks for your swift response.

AUR does not use the above desktop file.

**Comment by sukanka** [comment]
> AUR does not use the above desktop file.

So where does the `.desktop` in the released tarball (see https://github.com/rustdesk/rustdesk/releases/download/1.1.8/rustdesk-1.1.8-manjaro-arch.pkg.tar.zst) come from?
If newer releases have the correct desktop file, aur maintainer does not need to do any change.

**Comment by rustdesk** [comment]
> > AUR does not use the above desktop file.
> 
> So where does the `.desktop` in the released tarball (see https://github.com/rustdesk/rustdesk/releases/download/1.1.8/rustdesk-1.1.8-manjaro-arch.pkg.tar.zst) come from? If newer releases have the correct desktop file, aur maintainer does not need to do any change.

I meant for AUR only, our packages did use the desktop file.

**Comment by sukanka** [comment]
> I meant for AUR only, our packages did use the desktop file.
Oh thanks, that is the solution I want. The aur package uses the desktop file in your release.

**Comment by rustdesk** [comment]
> The aur package uses the desktop file in your release.

Thanks

**Comment by AngelSherry** [comment]
Rust desktop files on Linux are once again appearing with a MIME type claiming to handle HTML, and they are hijacking the default file association for the “Browser” category.

```
cat /usr/share/applications/rustdesk.desktop 
 
 [Desktop Entry] 
 Version=1.4.6 
 Name=RustDesk 
 GenericName=Remote Desktop
 GenericName[zh_CN]=远 程 桌 面
 Comment=Remote Desktop
 Comment[zh_CN]=远 程 桌 面
 Exec=rustdesk %u
 Icon=rustdesk 
 Terminal=false
 Type=Application
 MimeType=text/html;text/xml;application/xhtml+xml;application/vnd.mozilla.x 
 ul+xml;text/mml;x-scheme-handler/http;x-scheme-handler/https; 
 StartupNotify=true
 Categories=Network;RemoteAccess;GTK;
 Keywords=internet;
 Actions=new-window;
```
