### ISSUE TITLE
File copy and paste not wotking in 1.2.1

### ISSUE THREAD

**Issue by a-nouri** [rustdesk/rustdesk#5131]
### Bug Description

File copy and paste not working.
windows 11=> windows 11 not working
windows 11 (1.2.1) => windows 7 (1.1.9) also not working

I select File copy and paste option in menu.

### How to Reproduce

Copy File and paste in remote side. or copy from remote to local.

### Expected Behavior

Copy file from source to destiniation

### Operating system(s) on local side and remote side

windows 11 , windows 7

### RustDesk Version(s) on local side and remote side

1.2.1 => 1.2.1

### Screenshots

no need it is clear problem.

**Comment by rustdesk** [comment]
no duplicate issue please.

**Comment by fufesou** [comment]
https://github.com/rustdesk/rustdesk/issues/2283#issuecomment-1652137344

Hi, @a-nouri , can you let me connect your test computer ?
