### ISSUE TITLE
Cannot access hidden folders in File Transfer window

### ISSUE THREAD

**Issue by Wayrow** [rustdesk/rustdesk#5133]
### Bug Description

Cannot access hidden folders in File Transfer window.

### How to Reproduce

Attempt to open a folder in File Transfer window after it's been revealed by checking "Show hidden files".

### Expected Behavior

Hidden folder can be accessed in File Transfer window.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.1.9

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/139426789/b1606440-f1fb-497d-8717-30cc434be08d)

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
Do you have the permission to access it?

**Comment by 21pages** [comment]
![1690374705648](https://github.com/rustdesk/rustdesk/assets/14891774/1591af6c-a830-477a-b3da-ca3548277376)

check this option

**Comment by rustdesk** [comment]
It works fine in m
