### ISSUE TITLE
RuskDesk keyboard mapping is broken

### ISSUE THREAD

**Issue by hcarsten** [rustdesk/rustdesk#5136]
### Bug Description

I used use a Mac to connect to a Win10 Box. I use the Win10 box as a jumper to other machine e.g. using putty to ssh into other box.
<img width="391" alt="image" src="https://github.com/rustdesk/rustdesk/assets/3694287/7df3bb5d-0689-4258-aef7-8db1e7555a86">
on the putty I often get the "unbound key" message. This is coming from the nano editor in the ssh terminal, but actually I never saw this.
Then sometimes the systems systems to detect a shortcut, so suddently the "Edge Browser" opens and open a couple of times the "office login page".
<img width="1429" alt="image" src="https://github.com/rustdesk/rustdesk/assets/3694287/979cd4f8-a753-4797-8085-036f12ccca45">

Actually the remote box has a "Sophos FW" Solution but IT-Services said, it should be deactivated.

You have the "Keyboard Mode"-Button, anyway I do not understand what are the various options and which setup is the one I need ?
<img width="398" alt="image" src="https://github.com/rustdesk/rustdesk/assets/3694287/bd0d5ec2-7b52-417e-a91e-c8a8a33098b9">

### How to Reproduce

login on the box

### Expected Behavior

keyboard should work

### Operating system(s) on local side and remote side

OSX > Win10

### RustDesk Version(s) on local side and remote side

1.2.0 > 1.2.0.0

### Screenshots

<img width="391" alt="image" src="https://github.com/rustdesk/rustdesk/assets/3694287/7df3bb5d-0689-4258-aef7-8db1e7555a86">
<img width="1429" alt="image" src="https://github.com/rustdesk/rustdesk/assets/3694287/979cd4f8-a753-4797-8085-036f12ccca45">
<img width="398" alt="image" src="https://github.com/rustdesk/rustdesk/assets/3694287/bd0d5ec2-7b52-417e-a91e-c8a8a33098b9">

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/wiki/FAQ#keyboard-translation-modes
