### ISSUE TITLE
On mac M1 closing UI no remote connection available

### ISSUE THREAD

**Issue by bovirus** [rustdesk/rustdesk#5137]
@rustdesk 

### Bug Description

Installaing the night build 26.07.2023 on mac M1 if UMainw indow UI is open I can cooncet remotely to this Mac.

Closing the UI (also if service is active) the connection is not available anymroe.

Only re--opening teh GUI I can connect to the mac remotely 

### How to Reproduce

Install and use on mac M1 with macOS 13.5.

All macOS rights enabled fro RustDesk.

### Expected Behavior

If the service is on, should works also with GUI close.

### Operating system(s) on local side and remote side

Apple mac mini M1 with macOS 13.5

### RustDesk Version(s) on local side and remote side

night build 26.07.2023

### Screenshots

No screenshots

### Additional Context

No addition info

**Comment by rustdesk** [comment]
![image](https://github.com/rustdesk/rustdesk/assets/71636191/a10a8c95-8f09-4783-b630-fc088ecb7e97)

**Comment by rustdesk** [comment]
I know your concern, this is a little confusing. We may change this in next version, may not, depends on feedback from more users.

**Comment by bovirus** [comment]
@rustdesk 

I didn' see this message about service at the installation.
I Just saw the message on the left about change OS permission regarding the application.

I checked in rustdesk app and the service is ON (button Stop available).

Then there is no raeson that closing UI renote connection is close.

**Comment by rustdesk** [comment]
This occurs after you installation (move app to /Application) and granting all permissions (all left side permission messages disappear).

> ![image](https://user-images.githubusercontent.com/71636191/256401254-a10a8c95-8f09-4783-b630-fc088ecb7e97.png)

**Comment by bovirus** [comment]
@rustdesk 

Please leave it open because for me a bug.

If  you close the UI (on mac and on Windows) you lose the connection with remote desktop.

But if you enable in the starting function as service should work also if you close the GUI.
