### ISSUE TITLE
Rustdesk 1.2.1 crashes seemingly randomly on LMDE/Deb11 with Cinnamon DE

### ISSUE THREAD

**Issue by zeldatp151** [rustdesk/rustdesk#5140]
### Bug Description

After updating from 1.1.9 to 1.2.1, I get random crashes of the local client when connecting to anything from my rustdesk client on LMDE 5. 

### How to Reproduce

install the deb version of Rustdesk 1.2.1 on LMDE 5 / Deb 11
connect to a W10 or W11 host running Rustdesk 1.2.1
move the mouse too fast, change active displays, change full screen applications, do something that causes a large or fast change to the displayed portion of the screen. (this isn't exact because I haven't been able to narrow it down to exactly what causes it.)
Right before it crashes, the remote side will stop responding to mouse clicks or keyboard input, this usually lasts for about 2-15 seconds before the crash

### Expected Behavior

local client does not crash

### Operating system(s) on local side and remote side

LMDE 5 -> W10/W11

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

I am unable to provide screenshots or video, but I will provide some logs I took. The first log <rustlog.txt> is the redirected output of running rustdesk via cli. The second log <rustlog2.txt> is the actual capture from that cli session.
[rustlog.txt](https://github.com/rustdesk/rustdesk/files/12175236/rustlog.txt)
[rustlog2.txt](https://github.com/rustdesk/rustdesk/files/12175237/rustlog2.txt)

### Additional Context

This issue only started after I updated the local client to 1.2.1, and I use rustdesk through my own hosted server and relay.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4997
