### ISSUE TITLE
Focus Session for Keyboard, No Context Menu, Menues are not opened

### ISSUE THREAD

**Issue by hcarsten** [rustdesk/rustdesk#5155]
### Bug Description

These a various tasks regarding to keyboard and mouse handling:

1) sometime the Ruskdesk Session will loose the keyboard focus
so the focus remains on the remote host, or vice versa. At the end either side can not work with the "native" keyboard anymore

2) I am not able to open the context menu with a right click

3) If remote is a windows box. All Menues open only when the mouse button is pressed and NOT released. The normal behavior like a single click opens the menue does not work.

### How to Reproduce

mac > pc (win10)

### Expected Behavior

normal keyboard and mouse handling

### Operating system(s) on local side and remote side

OSX > Win10

### RustDesk Version(s) on local side and remote side

1.2.0 > 1.2.0.0

### Screenshots

see description

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by earthsound** [comment]
I, too, am going from macOS > Windows 10. After recently updating rustdesk on the macOS side (1.2.2), but not on the Windows 10 side (1.2.0), I am noticing that rustdesk (I'm assuming) is sending Shift & Windows key (sometimes, just Shift, sometimes both simultaneously) to the remote PC at the minimum when I left click. 

If I'm running open-shell on the remote PC it results in the start menu opening all the time and interrupts often. 

[Screen recording of behavior.](https://youtu.be/52m80SYDiEM) I have the Windows On-Screen Keyboard visible to show what's happening. I don't ever touch my keyboard in the recording.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4367#issuecomment-1718334648
