### ISSUE TITLE
macOS RD does not remember last open position or windows size

### ISSUE THREAD

**Issue by RichardBurt65** [rustdesk/rustdesk#5158]
### Bug Description

Whenever I open RD it defaults to opening a smaller window than I want.

### How to Reproduce

Open RD, adjust size of RD window, close RD and then reopen. 

### Expected Behavior

RD should remember screen position and windows size. 

### Operating system(s) on local side and remote side

macOS 

### RustDesk Version(s) on local side and remote side

1.2.1

### Screenshots

.

**Comment by rustdesk** [comment]
no duplicate issue please.

**Comment by rustdesk** [comment]
#5109
