### ISSUE TITLE
P2P connect doesnt work if other machine isnt on same subnet

### ISSUE THREAD

**Issue by si458** [rustdesk/rustdesk#516]
**Describe the bug you encountered:**
even if your client machine has direct access to the remote computer and is ping able etc,
the software ignores P2P and uses relay

**What did you expect to happen instead?**
to allow P2P connection without using a relay as the client computer has direct access to the remote computer

**How did you install `RustDesk`?**
installed via exe / build from gitrepo

---

**RustDesk version and environment**
Windows 10 + Windows 11, Version 1.19.0
Computer A is on 192.168.1.100,
Computer B is on 192.168.2.100
both computers connected to the same router just have their own gateway ip (192.168.1.254, 192.168.2.254)
both computers can ping each other and can also telnet into port 21118 directly on each other too

**Comment by rustdesk** [comment]
You still need to solve this issue by you, because we can not reproduce it in our intra network.

**Comment by rustdesk** [comment]
I will do my best to assist you。

**Comment by rustdesk** [comment]
Can you get correct intranet ip here https://github.com/rustdesk/rustdesk/blob/master/src/client.rs#L198?

**Comment by si458** [comment]
ok i think i found the issue,

i created a test VM, bridged it to my home network (so its on the same network as my laptop)
ran the debuged version on my lappy, then tried connecting to the testvm, and it does indeed directly connect!

HOWEVER if i then enable my works VPN to send everything out through them, and then try connecting again to the test vm, its not directly connecting but relaying and it seems to be because its only punching attempt the default route IP which in my case is my VPN, even though i can still ping the test vm no problem from my terminal

ill get logs soon for you

**Comment by si458** [comment]
without vpn - direct - https://pastebin.com/J4Fy1ZJf

with my vpn - relayed - https://pastebin.com/DDA0hLRf

it would seem its only trying hole punching from the default route IP address rather than trying ALL interfaces with IP addresses on

**Comment by rustdesk** [comment]
Yes, VPN is a big problem.

**Comment by si458** [comment]
> Yes, VPN is a big problem.

that is correct BUT the issue i originally refered to is the remote computer being on a different IP range, BUT my laptop can ping it directly and even connect to the port 21118 directly on the remote computer

i can even connect to it directly using the ip in rustdesk no problem, BUT the software keeps relaying the connection, when using the ID number?

**Comment by rustdesk** [comment]
Yes, could you figure out?

**Comment by rustdesk** [comment]
It is a good chance to learn Rust, :)

**Comment by ZegWe** [comment]
Any new updates recently? I have met the same issue

**Comment by JaCh0o** [comment]
Same here can connect by direct up while clients are in different vlans

**Comment by Earthones** [comment]
I have do some test, two computer's nat type both are full cone, but can't link each other through p2p, I will use relay server to transport data.
