### ISSUE TITLE
Whitelisting on 1.2.1 not working - Working Fine on 1.1.9

### ISSUE THREAD

**Issue by andy-page-developer** [rustdesk/rustdesk#5163]
### Bug Description

I have 2 computers

Fedora 38 Laptop
Windows 11 Desktop

On 1.1.9 these connect directly via LAN using the local 192.168.1.xxx  IP Addresses of each machine.
They are both password protected and on the Fedora 38 Laptop I have a whitelist of the Windows 11 Desktop and visa versa for the Laptop and Desktop.

This works great. I can connect to my Desktop from my Laptop and my Laptop to my Desktop.

It's a great setup and works seamlessly.

I decided to update both the Laptop and Desktop to 

Windows 11
Version: 1.2.1
Build Date: 2023-07-14 11:14

Fedora 38
Version: 1.2.1
Build Date: 2023-07-18 03:27

Now,when I try to connect from my Fedora Laptop to the Windows 11 Desktop I get "Your ip is blocked by the peer"

So on the Windows 11 Desktop I removed the whitelist. I could then connect to the Windows 11 Desktop with no issues.

If I put the whitelist back in I get the Your ip is blocked by the peer message again.

So as a test I reverted back to 1.1.9 on both Laptop and Desktop. Put the whitelist in and it worked fine, just like before.

I updated again to 1.2.1 and the whitelist does not work.

I'm not sure what's going on or if this is a bug?

### How to Reproduce

Add a whitelist to the Windows 11 Desktop of the IP of my Laptop and I can not longer connect.

Remove the whitelist and I can access.

### Expected Behavior

With the known IP whitelist I should be able to connect in the same way I could with 1.1.9

### Operating system(s) on local side and remote side

Fedora 38 (Laptop) - Windows 11 (Desktop)

### RustDesk Version(s) on local side and remote side

1.2.1 > 1.2.1

### Screenshots

![Screenshot_20230727_095357](https://github.com/rustdesk/rustdesk/assets/132894646/2ab1ae42-589e-440c-bd23-1fd5e5d7cc85)

**Comment by rustdesk** [comment]
thanks for you report, fix just merged, please try out tommorrow's nightly build.

**Comment by andy-page-developer** [comment]
Thank you very much for the quick turnaround.
