### ISSUE TITLE
build.py trying error moving file

### ISSUE THREAD

**Issue by DrMondGnu** [rustdesk/rustdesk#5164]
### Bug Description

When trying to compile rustdesk with build.py it works until its trying to move something and then it crashes.
This is the log:
```
executable path: .\rustdesk-1.2.1-win7-install.exe
processing .\RustDesk.exe...
processing .\WindowInjection.dll...
metadata had written to C:\dev\rustdesk\libs\portable\data.bin
mv: cannot stat '../../res_dir/rustdesk-version-win7-install.exe': No such file or directory
features: ['inline', 'virtual_display_driver']
False
Build with features ['PrivacyMode']
PrivacyMode download begin
PrivacyMode download end. extract bein
extract file WindowInjection.dll
PrivacyMode extract end
Not signed
Error occurred when executing: mv ../../{res_dir}/rustdesk-{version}-win7-install.exe ../... Exiting.
```

### How to Reproduce

No idea seems to be somthing only with my system

### Expected Behavior

Moving the file or not even bothering with it because i dont know why it wants to do anything related to Windows 7 becaus eim on windows 10

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

Commit: 954df86f3cc06b71775cbb023942ca5b4c2cff37

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/89934669/fc5d8b3c-ef32-45a6-b59f-746282900771)

**Comment by rustdesk** [comment]
#763
