### ISSUE TITLE
1.2.1 version has significantly slower connection speed compared to 1.1.9 version.

### ISSUE THREAD

**Issue by wes1997** [rustdesk/rustdesk#5165]
### Bug Description

The same self-built server, version 1.2.1 is several times slower than version 1.1.9. Version 1.2.1 often takes more than 10 seconds and fails to connect successfully, while version 1.1.9 connects successfully in just a few seconds.
The speed is normal after the connection is established.

### How to Reproduce

Comparison between Installation of Version 1.1.9 and Version 1.2.1

### Expected Behavior

The connection speed is normal.

### Operating system(s) on local side and remote side

windows11-> Android 

### RustDesk Version(s) on local side and remote side

1.2.1->1.1.8-2

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/23024421/3fdb1ebc-4cdb-419e-a723-a13ecaea82b3)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/5002
