### ISSUE TITLE
1.21 - Fedora to Fedora mouse not clicking/selecting - Works in 1.1.9

### ISSUE THREAD

**Issue by andy-page-developer** [rustdesk/rustdesk#5167]
### Bug Description

I have 3 computers

Fedora 38 Laptop
Fedora 38 Desktop
Windows 11 Desktop

On 1.1.9 these connect directly via LAN using the local 192.168.1.xxx IP Addresses of each machine.

This works great with 1.1.9, I can connect to all machines from all other machines.

There is no whitelisting.

It's a great setup and works seamlessly.

I decided to update all 3 to 1.2.1

Windows 11
Version: 1.2.1
Build Date: 2023-07-14 11:14

Fedora 38 Desktop
Version: 1.2.1
Build Date: 2023-07-18 03:27

Fedora 38 Laptop
Version: 1.2.1
Build Date: 2023-07-18 03:27

I can connect my Windows Computer to my Fedora Laptop and control using mouse/keyboard
I can connect my Windows Computer to my Fedora Desktop  and control using mouse/keyboard
I can connect my Fedora Laptop to my Windows Computer and control using mouse/keyboard
I can connect my Fedora Desktop to my Windows Computer and control using mouse/keyboard

However when I connect Fedora Laptop to Fedora Desktop , or my Fedora Desktop to my Fedora Laptop the keyboard works and I see the mouse but the mouse does not appear to work.

I can move the mouse around but I can't click/select anything.

So as a test I reverted back to 1.1.9 on all 3 computers.

This works fine. I could control all computers from all other computers with no issue. Mouse and Key board work great.

I updated again to 1.2.1 and again the mouse does not work when I try to control a fedora computer from a another fedora computer. 

I'm not sure what's going on or if this is a bug?

### How to Reproduce

Connect to a Fedora computer from a Fedora computer and try to click/select with the mouse

### Expected Behavior

I should be able to click items, menus and select text etc

### Operating system(s) on local side and remote side

Fedora 38 -> Fedora 38

### RustDesk Version(s) on local side and remote side

1.2.1

### Screenshots

N/A

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by rustdesk** [comment]
sorry, this time you wont be that lucky as whitelist issue, this issue can not left for future investigation.
