### ISSUE TITLE
windows 10 copy and paste problem

### ISSUE THREAD

**Issue by mahdinuri** [rustdesk/rustdesk#5172]
### Bug Description

i have windows 11( version 22h2 (OS Build 22621.1992) ) and  remote side is windows 10 (version 1909).
I use version 1.2.1 on both sides.
When I copy a file from my computer to the remote side, the explorer on the remote side get not responding.
I have seen this problem several times on different computers with Windows 10.
I don't have this problem in Windows 10,  22H2 version.
There is no problem when the rustdesk version 1.1.9 is installed on the remote side and 1.2.1 on my windows11.
According to my review, apparently, the problem occurs in lower versions of Windows 10.

### How to Reproduce

Please check and solve the problem in the next versions. Because in some cases, you can't wait for the remote side to update its Windows

### Expected Behavior

without this bug

### Operating system(s) on local side and remote side

windows 11 -> windows 10 (version 1909)

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

![rust](https://github.com/rustdesk/rustdesk/assets/134304579/af919882-0628-42a7-8ac6-16e92efd2806)

**Comment by rustdesk** [comment]
no duplicate please
