### ISSUE TITLE
Privacy mode compromise the refresh rate

### ISSUE THREAD

**Issue by Creling** [rustdesk/rustdesk#5175]
### Bug Description

Hi,

I found that enabling privacy mode will reduce the refresh rate. 

The refresh rate is set to 60Hz manually in the remote Rustdesk. The local side connects to the remove side via LAN, so I believe the network is not the bottleneck.

### How to Reproduce

Just enable the privacy mode and observe the mouse's trajectory.

### Expected Behavior

Enabling the privacy mode won't reduce the refresh rate.

### Operating system(s) on local side and remote side

Window 10 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.2

### Screenshots

Privacy mode is disabled:

https://github.com/rustdesk/rustdesk/assets/43109504/dbfe19ea-67c4-4a43-83f6-58ef3b338c23

Privacy model is enabled:

https://github.com/rustdesk/rustdesk/assets/43109504/45b8921a-d4bb-4735-b5be-1c827b368452

**Comment by rustdesk** [comment]
Yes, known.
