### ISSUE TITLE
Several characters are wrong when typing in cmd.exe on a remote machine

### ISSUE THREAD

**Issue by Wayrow** [rustdesk/rustdesk#5179]
### Bug Description

Several characters are wrong when typing in cmd.exe on a remote machine with Czech keyboard layout. Most notably Alt+q ("\");  ":" and "()" write completely different characters.

### How to Reproduce

Write in cmd.exe on a remote Windows 10 64-bit machine with Czech keyboard layout activated.

### Expected Behavior

All characters are correctly written according to the Czech keyboard layout.

### Operating system(s) on local side and remote side

Windows 10 Pro 64-bit -> Windows 10 Pro 64-bit

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

![Rustdesk_characters](https://github.com/rustdesk/rustdesk/assets/139426789/feaf45e6-c1b6-443c-8485-333a4050d6e1)

**Comment by rustdesk** [comment]
only in cmd? have you tried the other mode which you can choose when you click on keyboard icon on the menubar.

**Comment by Wayrow** [comment]
Yeah, only in cmd and I've just realized that only in "Legacy Mode" Other modes work fine.

**Comment by dinger1986** [comment]
> Yeah, only in cmd and I've just realized that only in "Legacy Mode". Other modes work fine.

do you need to use legacy mode for anything else?

**Comment by Wayrow** [comment]
No, it's fine, I forgot about the other modes O_o

**Comment by dinger1986** [comment]
so not a bug
