### ISSUE TITLE
RustDesk's remote view disappeared when the portable display detached.

### ISSUE THREAD

**Issue by lexchou-aspose** [rustdesk/rustdesk#5185]
### Bug Description

I started the remote session with dual screen, and the remote view is placed in secondary view.

Then another day I try to continue the remote session but without a secondary screen, this happened, the remote view is out side of the display, and I can't move it to my working area.

### How to Reproduce

1. Use a computer with secondary screen, and move the remote view into the secondary screen.
2. Close the session
3. Detach the secondary screen
4. Open RustDesk and continue previous session

### Expected Behavior

When Second display is removed, remote view should be displayed in the primary display, but it looks like it remembered the window position which is out side of the primary screen.

### Operating system(s) on local side and remote side

Windows 11 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

No screenshots.

### Additional Context

If I remove the secondary display during the remote session, the remote view can be placed into primary screen as expected(looks like Windows' behavior).
This only happens when the secondary display was removed and try to continue previous session.

**Comment by rustdesk** [comment]
sorry, we won't fix this corner case.
