### ISSUE TITLE
Unsupported Display server, X11 or Wayland expected.

### ISSUE THREAD

**Issue by kbirabwa** [rustdesk/rustdesk#5195]
### Bug Description

I installed and started rustdesk and it gave this error:

`Unsupported Display server, X11 or Wayland expected.`

The rustdesk is version 1.2.0
I am running PCLinuxOS where the commandline input `ps -e | grep tty` reports Xorg as the display server.
![RustDesk_error](https://github.com/rustdesk/rustdesk/assets/65370139/7676ed76-b63a-4fe0-ada2-19b5b9b2bb08)
![Remote Desktop - RustDesk](https://github.com/rustdesk/rustdesk/assets/65370139/2e888a0b-5a59-4de5-a9df-7d102fcee5f6)

### How to Reproduce

Run rustdesk with Xorg as the display server and attempt to login to a remote desktop.

### Expected Behavior

After giving it the remote computer ID and password I expected rustdesk to log me into the remote machine desktop.

### Operating system(s) on local side and remote side

PCLinuxOS on the local and the remote sides

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0

### Screenshots

![RustDesk_error](https://github.com/rustdesk/rustdesk/assets/65370139/49df6503-4b40-44d4-bc24-f6c61203e6bf)
![Remote Desktop - RustDesk](https://github.com/rustdesk/rustdesk/assets/65370139/95ce9934-d75a-470f-819c-2e877a3d733d)
![rustdesk_display_server](https://github.com/rustdesk/rustdesk/assets/65370139/06d3157a-f821-46d6-aa3d-d43286f164d7)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
