### ISSUE TITLE
resolution change not working (under rdp session sharing)

### ISSUE THREAD

**Issue by doudoupower** [rustdesk/rustdesk#5200]
### Bug Description

I can't change my rustdesk resolution to any size ,  it is always 1024*768.

### How to Reproduce

Try to chose 1920*1080

### Expected Behavior

I'm expect resolution 1920*1080

### Operating system(s) on local side and remote side

windows 10 -> windows10

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/6251562/7ed0c951-268c-4ce8-8d1c-86ade05a7207)

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
Show us your resolution list on your control machine please.

**Comment by doudoupower** [comment]
@rustdesk 
![image](https://github.com/rustdesk/rustdesk/assets/6251562/4917c7cb-ffc7-4c4a-9cc6-e7c276dc3d7e)

**Comment by rustdesk** [comment]
The two lists are not the same. I guess it may be the problem. @fufesou

**Comment by doudoupower** [comment]
@rustdesk The image just now shows not all resolutions, so I added another image


![image](https://github.com/rustdesk/rustdesk/assets/6251562/59c2b0d3-f689-4437-a6fe-be33ae73fd3c)

**Comment by fufesou** [comment]
@doudoupower Can you change the resolution directly? Without choose the resolution in the toolbar?

**Comment by doudoupower** [comment]
@fufesou no i can't

**Comment by rustdesk** [comment]
> @fufesou no i can't

The "can't" is because you are not front of the controlled machine?

**Comment by fufesou** [comment]
Can you please also try just operate on the remote side, without do it through a RustDesk connection.

Is the remote side a virtual machine? Maybe resolution changing is restricted by your virtual machine setting or some other settings.

**Comment by doudoupower** [comment]
@fufesou, it's not a virtual machine, but it's physical monitor is powerd off(i guesst it may be the problem). I can change the resolution using microsoft remote desktop now.

**Comment by fufesou** [comment]
After establishing a connection of mstsc, you can change the resolution through the RustDesk connection?

I guess you are right.
Without physical monitor, the display resolution may not be able to change.
mstsc create a virtual display. It can change the resolution to any values.

**Comment by doudoupower** [comment]
@fufesou i use rdp option in rustdesk but how do I know it is working on rdp?

**Comment by fufesou** [comment]
I don't know what do you mean. You want to make sure the connection is working on rdp?

**Comment by doudoupower** [comment]
@fufesou Because you mentioned that mstsc can freely modify the resolution in RDP mode, I would like to give it a try and see if it works

**Comment by doudoupower** [comment]
@fufesou Maybe I need to buy a fake HDMI plug to use RustDesk.

**Comment by rustdesk** [comment]
> @fufesou i use rdp option in rustdesk but how do I know it is working on rdp?

https://github.com/rustdesk/rustdesk/issues/914#issuecomment-1174725280

**Comment by fufesou** [comment]
I rememeber I can change the resolution by change the window size.
But I can't do it anymore. Maybe I remember wrong.


mstsc has provided the initial resolution option.

<img width="308" alt="1690779243065" src="https://github.com/rustdesk/rustdesk/assets/13586388/349a946b-1ebc-403a-ac34-72b7f69e119d">


RustDesk does not provide options to set the initial resolution.

**Comment by rustdesk** [comment]
> @fufesou Maybe I need to buy a fake HDMI plug to use RustDesk.

https://github.com/rustdesk/rustdesk/issues/4974 we also have virtual display, but we do need to polish it.

**Comment by rustdesk** [comment]
No need to discuss about this any more, a lot of misunderstanding here and wasting time.

**Comment by fufesou** [comment]
> https://github.com/rustdesk/rustdesk/issues/4974 we also have virtual display, but we do need to polish it.

@doudoupower  For a temporary use, you can try https://github.com/fufesou/RustDeskIddDriver/releases
