### ISSUE TITLE
COPY AND PASTE BUG

### ISSUE THREAD

**Issue by TheMaylkol** [rustdesk/rustdesk#5201]
### Bug Description

I have updated to the new version of rustdesk on all the computers where I use the software, but I have noticed that now I cannot copy and paste to any computer with the new version, which with the old version I could do without problems.

### How to Reproduce

Copy a file from one computer and paste the file directly to another computer with rustdesk

### Expected Behavior

I thought that with the new update I could copy and paste files directly like I did before, but apparently that's not the case.

### Operating system(s) on local side and remote side

Windows 11 >> Win 10 & 7

### RustDesk Version(s) on local side and remote side

1.2.1 >> 1.2.1 ALL PC'S

### Screenshots

to big video.

**Comment by rustdesk** [comment]
#2283

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2283#issuecomment-1652137344

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
@TheMaylkol Hi, thanks for your feedback. Can you please check if the "Allow file copy&paste" option is on?

<img width="287" alt="1690779662598" src="https://github.com/rustdesk/rustdesk/assets/13586388/abe221de-f86a-4733-a55a-ca31e16dae6d">


If it is on, can you send the log files to me (c2h1YW5nbG9uZ2NoZW5AeWVhaC5uZXQ=, the base64 encoded email address), thanks. `%appdata%\RustDesk\log` on both sides.

**Comment by fufesou** [comment]
@TheMaylkol The logs are added yesterday. Please upgrade to the latest nightly build.

https://github.com/rustdesk/rustdesk/releases/tag/nightly

**Comment by mikekgr** [comment]
Dear @fufesou  ,,
I have the exact same problem. I use self hosting server and it  not possible to copy paste file(s) from my windows 10/11 pc to the remote pc that is windows 10/11. In all cases the copy / paste is activated. I have tested both 1.2.1 released AND 1.2.2 nightly in both ends. Please help.

Thanks and Best Regards,
Mike Kranidis

**Comment by fufesou** [comment]
@mikekgr Can I (c2h1YW5nbG9uZ2NoZW5AeWVhaC5uZXQ=, the base64 encoded email address) use your machine for debug?

Or can you just run the latest nightly build. And send me the log files.

**Comment by fufesou** [comment]
I want to fix issue. But it is not easy for me to reproduce it.

**Comment by mikekgr** [comment]
> @mikekgr Can I (c2h1YW5nbG9uZ2NoZW5AeWVhaC5uZXQ=, the base64 encoded email address) use your machine for debug?
> 
> Or can you just run the latest nightly build. And send me the log files.

Yes you can but I did not understand what is necessary to do.  How can use your base64 encoded email address ? Please give me the info and I will give you access

**Comment by fufesou** [comment]
@mikekgr Thanks. I'll try my virtual machine first. I'll contact you if I need to.

**Comment by fufesou** [comment]
@mikekgr   shuanglongchen@yeah.net
Can you please set a permanent password? So I can connect to your computer more easily.

<img width="586" alt="1690788364495" src="https://github.com/rustdesk/rustdesk/assets/13586388/dae95806-9737-4586-9fb8-1d85a3106069">

You can change the permanent password later after my connections.

**Comment by mikekgr** [comment]
> @mikekgr [shuanglongchen@yeah.net](mailto:shuanglongchen@yeah.net) Can you please set a permanent password? So I can connect to your computer more easily.
> 
> <img alt="1690788364495" width="586" src="https://user-images.githubusercontent.com/13586388/257147239-dae95806-9737-4586-9fb8-1d85a3106069.png">
> You can change the permanent password later after my connections.

I have permanent password from the beginning. What info do you want to sent you in your email? (I am running my own rustdesk server)

**Comment by fufesou** [comment]
Thanks. I'm trying to find out the reason on my env.

Please send me an email with any text, so I can get your email address.
I'll connect your machine if I need.

**Comment by mikekgr** [comment]
> Thanks. I'm trying to find out the reason on my env.
> 
> Please send me an email with any text, so I can get your email address. I'll connect your machine if I need.

I just sent you email with subject: Mike Kranidis github RustDesk
I am at your disposal !

**Comment by mikekgr** [comment]
> @mikekgr Hi, how did you establish the connection? By input the password (or remember password) or by click "Accept" on the controlled side?

I am always establish my connections using remembered password way.

**Comment by TheMaylkol** [comment]
With the latest nightly build I can copy text from one computer to another without problems, but it still doesn't allow me to copy files from my computer or vice versa. Tested on Win 11 >> Win 10, both with latest nightly build

**Comment by fufesou** [comment]
@TheMaylkol Can you please send me(shuanglongchen@yeah.net) your log files (%appdata%\rustdesk\log)？Thx

**Comment by mikekgr** [comment]
> > @mikekgr Hi, how did you establish the connection? By input the password (or remember password) or by click "Accept" on the controlled side?
> 
> I am always establish my connections using remembered password way.

@fufesou I just tested the today nightly release. Same problem, not possible to copy - paste file(s) from local to remote. I both tested Ctrl-C  Ctrl-V or right mouse button ... If I can somehow to help you debug this problem just let me know. I also sent you (yesterday) an email, I did not received anything from you, although I am not sure if my email server can accept emails from China (long story why...)

**Comment by fufesou** [comment]
@mikekgr Thanks for your feedback. I've located one reason that causes this issue.
"File copy&paste" may be Ok in the next nightly build.

**Comment by mikekgr** [comment]
@fufesou 
I happily confirm that RustDesk nightly 1.2.2 Build Date: 2023-08-01 12:59 has copy / paste working again !!!
Congratulations for your fine work

**Comment by MaDDmin** [comment]
Please, reopen this. 
I'm on v1.2.2 (comp. 2023-08-22 01:58)
Text is copied and pasted ok between machines. Not so files.
Thanks.

**Comment by fufesou** [comment]
@MaDDmin Hi,

Sorry for disturbance, but I haven't seen this issue reported in a long time.

Would you please provide more informations.
Do you use Win -> Win, both v1.2.2 (comp. 2023-08-22 01:58).

Have you checked this option?

![image](https://github.com/rustdesk/rustdesk/assets/13586388/2f40ad32-d5af-4753-a6ee-16c971499a0c)

**Comment by MaDDmin** [comment]
Since I posted this, I've upgraded on both ends to 1.2.3 and still won't work. Right now, remote (acting as server) is Windows 10 and local (acting as client) is GNULinux Mint 21.2 with Cinnamon.
And yes, on both ends the option is enabled on the security menu, although I can't find these in my current version. Maybe it has to do with my local version being the one for GNULinux?

**Comment by MaDDmin** [comment]
Can't confirm that I had that checkbox enabled on 1.2.2. I might go back and try if needed but, where I stand now, it's still not working.

**Comment by MaDDmin** [comment]
Okok... Between Windows 10 machines works perfectly :)

**Comment by Necr0man** [comment]
Hi there! I'm also having issues, but between some versions.

I'm using 1.2.4 nightly on my main PC and copy/paste files won't work when i'm connected to RustDesk 1.2.2, but works if i'm connected to 1.2.1 or 1.2.3 or 1.2.4 nightly.

However copy/paste text works fine!

If i copy text (filename for instance) from 1.2.2 and paste it on my 1.2.4 it works. If i copy file from 1.2.2 and paste it on my 1.2.4 it doesn't work!

Thanks in advance!

**Comment by ajstadlin** [comment]
I am not able top copy / paste plain text between Rustdesk nightly build 1.2.4 running in Debian 12 (Bookworm) KDE Plasma X11 (not Wayland) on Amd64 to Raspberry Pi running Raspbian (Bookworm) X11 (not Wayland) on Arm64.

Both of the above are LAN side (no relay). However, both perform copy paste text via relay with my other Rustdesk remotes.

I have not tried copy / past files.  However, I have that option checked.

I am not sure how to troubleshoot this issue.
