### ISSUE TITLE
Address book lost in nightly build

### ISSUE THREAD

**Issue by dinger1986** [rustdesk/rustdesk#5203]
### Bug Description

with nightly build installed today, the logged in Addressbook with pro shows no peers listed in Addressbook but on 1.2.1 they showed fine, tested on windows and mac

### How to Reproduce

Install nightly build and check out addressbook, all entries will be lost

### Expected Behavior

entries to still be there

### Operating system(s) on local side and remote side

na

### RustDesk Version(s) on local side and remote side

1.2.2 (nightly)

### Screenshots

latest nightly build
![image](https://github.com/rustdesk/rustdesk/assets/7244447/4509321f-3a7d-48f9-985e-55240e1d72d1)

1.2.1
![image](https://github.com/rustdesk/rustdesk/assets/7244447/029ef8e1-3531-4b05-ae4f-d344ba418ee9)

**Comment by rustdesk** [comment]
Close as fix merged, please test
