### ISSUE TITLE
Rustdesk change settings PolicyKit Authentification bypass (Debian 11 KDE )

### ISSUE THREAD

**Issue by xBr0th3rx** [rustdesk/rustdesk#5205]
### Bug Description

When you start Rustdesk and want to change the configuration a popup comes up for authentication. If you simply press cancel you can still edit the configuration.

### How to Reproduce

Debian 11 client with KDE
Install package: rustdesk-1.2.1-x86_64.deb
Start rustdesk
Then open Settings > Network > Unlock network settings
Dialog comes up for authentication
Then press cancel

You can now change the settings without entering a password

### Expected Behavior

When a network setting is changed and an authentication comes, the setting must not be changed until the authentication is successful.

### Operating system(s) on local side and remote side

Debian 11 KDE > Debian 11 KDE

### RustDesk Version(s) on local side and remote side

1.2.1 > 1.2.1

### Screenshots

![rustdesk_1](https://github.com/rustdesk/rustdesk/assets/17457338/0ade79dc-5a06-4f29-ab84-e80b41f4ef4d)
![rustdesk_2](https://github.com/rustdesk/rustdesk/assets/17457338/d3d6ac2e-231a-4969-8598-73ac60ac7ed1)
![rustdesk_3](https://github.com/rustdesk/rustdesk/assets/17457338/e0a804fb-4d72-4bcb-a5d9-7591fb622bf3)
![rustdesk_4](https://github.com/rustdesk/rustdesk/assets/17457338/da7f9a2f-bf0d-40d5-bfa2-e211a1ebdeca)

**Comment by rustdesk** [comment]
Could you show me the result below, please press cancel.

```
pkexec echo 1; echo $?
```

**Comment by rustdesk** [comment]
and how about if click "close" button?

**Comment by xBr0th3rx** [comment]
pkexec echo 1; echo $?
"Error executing command as another user: Not authorized

This incident has been reported.
127"
By Press Cancel

pkexec echo 1; echo $?
"Error executing command as another user: Not authorized

This incident has been reported.
127"
By Press Close Button

**Comment by rustdesk** [comment]
Just put a simple fix https://github.com/rustdesk/rustdesk/commit/ac60ba40a23dd76e9338c4febf5e661bf5bd4936

**Comment by xBr0th3rx** [comment]
> Just put a simple fix [ac60ba4](https://github.com/rustdesk/rustdesk/commit/ac60ba40a23dd76e9338c4febf5e661bf5bd4936)

Thanks that works

**Comment by xBr0th3rx** [comment]
So let me ask you a question.
What is the point of the option "Unlock network settings" if the user can simply edit the RustDesk2.toml with the editor of his choice?

Since the complete folder is writable for the user.
![Rustdesk_entsperren](https://github.com/rustdesk/rustdesk/assets/17457338/49528d32-7bb8-47ac-b3db-885c083d2380)
