### ISSUE TITLE
incorrect behavior after arrow keys pressing in map mode (linux->mac)

### ISSUE THREAD

**Issue by GolemXlV** [rustdesk/rustdesk#5221]
### Bug Description

The map mode is not working after pressing arrow keys.

### How to Reproduce

When pressing arrow key on any text input in map mode, any keys after that recognized with fn button pressed (as example pressing C after that leads to open Control Center, A focus on Dock menu, etc)

### Expected Behavior

Pressing arrow keys on text input shifts cursor in the relevant direction without affecting any futher input

### Operating system(s) on local side and remote side

Linux -> Mac OS Ventura 13.5

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0, 1.2.1 -> 1.2.1

### Screenshots

will be later

**Comment by rustdesk** [comment]
works fine on my connection win11->mac 13.1

**Comment by rustdesk** [comment]
tracked by #4367

**Comment by rustdesk** [comment]
at least you should tell your keyboard layout (language) etc

**Comment by GolemXlV** [comment]
It happens with US qwerty keyboard layout (ISO/NO-ISO) on notebook and external usb keyboard also, didn't test it on others

**Comment by GolemXlV** [comment]
Resolved by removing ~/.config/rustdesk
