### ISSUE TITLE
WOL function not working from UI for direct IP peers

### ISSUE THREAD

**Issue by baldurk** [rustdesk/rustdesk#5224]
### Bug Description

I started using RustDesk recently and since all my computers are on LAN I enabled direct IP connect to start with as that is the workflow I am used to from previous programs.

I wanted to use the WOL function, but when selecting WOL from the context menu on one of my favourited direct IP peers nothing happened, and I saw from Wireshark that no magic packet was being sent.

### How to Reproduce

1. Enable direct IP connect on a LAN machine, and connect to it.
2. Save this connection as a favourite, rename it to a memorable name.
3. Click on the context menu and select 'WOL'.
4. Nothing happens, there is no error but no packet is sent.

### Expected Behavior

I expect the magic WOL packet to be sent.

If I go to the discovered tab and select the corresponding LAN device via id, it works.

### Operating system(s) on local side and remote side

Windows 10 -> Linux

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

Not working WOL from direct IP peer:

![notworking](https://github.com/rustdesk/rustdesk/assets/661798/1b725614-f620-413f-9636-4c696ef5e09e)

Working WOL from discovered peer:

![working](https://github.com/rustdesk/rustdesk/assets/661798/b562c605-5843-44df-ab8a-98dce6a7195a)

### Additional Context

I'm not very familiar with rust but I compiled the project and found the `send_wol` function in `src/lan.rs` and added some log statements to try to investigate. What I found was that the `id` parameter being passed in from elsewhere was a string containing the IP address, in my case `192.168.1.180`, and not the expected id of the peer, e.g. `1234567890`. I hacked the function to check for a match on each peers listed ip addresses from `peer.ip_mac` and I found that the WOL packet was then sent as expected.

I might be looking in the wrong place though for the problem, I'm not sure, but hopefully that is helpful.

**Comment by rustdesk** [comment]
wol should be only appear in discovery.
