### ISSUE TITLE
Remote desktop is offline

### ISSUE THREAD

**Issue by Cris7SA** [rustdesk/rustdesk#5227]
### Bug Description

En estos momentos tenemos dificultades para conectarnos a los diferentes escritorio remotos (clientes), probamos desde la versión mas reciente y las anteriores, no ha sido posible establecer conexión.

Descartamos bloqueos desde nuestro Firewall.

Probamos conectándonos internet desde red móvil y la falla persiste.

### How to Reproduce

Instalar dos software cliente del software y probar conexión remota entre ambos equipos.

### Expected Behavior

Restablezca la conexión entre equipos remotos.

### Operating system(s) on local side and remote side

Windows 10 Pro Versión 22H2

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.2.1

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/141167646/588cbac6-d5e8-4597-862f-2d0db591ee62)
![Rustdesk_connection_error](https://github.com/rustdesk/rustdesk/assets/141167646/e9c7019d-fd30-48e5-91dc-9c7de1b6bcf3)

**Comment by sbrouillettemoss** [comment]
I am having the same issue on Windows 11. Checked the same issues as Cris7SA. Running the current version of RD.

**Comment by kf7mxe** [comment]
I am not able to connect either though I was able to do so last night. I think the default relay server is down because I haven't updated both devices and it was working last night. So I don't know if this is actually a bug but is still an issue.

**Comment by Greytech52** [comment]
I am using my own RustDesk server which works perfectly with 12 remote Windows 10/11 computers using client V1.1.9
If I upgrade any to V1.2.1 and leave the ID Server blank I get Internet connection. As soon as I enter my ID server address I lose internet connection, all other fields are blank. Unable to use 1.2.1 for this reason.

**Comment by dinger1986** [comment]
what is your server running on? have you upgraded your server to the latest version?

**Comment by Greytech52** [comment]
Hi,
Yes, RustDesk server is running the latest version 2023-07-27 on a
Raspberry Pi running docker and Portainer, using the RustDesk docker script
with the only change being my address in hbbs. All required ports are open.
Here is my DNS address extracted from the script:
command: hbbs -r qnkowhawo3rkty3i.myfritz.net:21117
The fault was present on the previous server version before I updated on
the 27 July. Sorry, I don't know how to extract a version number. Client
software 1.1.9 works perfectly but no computer I use will connect using
client 1.2.1 using the same identical settings.
Please advise if you need more information, I am not an expert...

Regards

**Comment by dinger1986** [comment]
so you upgraded the client and server? 

Or the issue is when you upgrade the Server?

Or the issue is when you upgrade the client?

**Comment by Greytech52** [comment]
The issue showed up when I upgraded the client soon after noticing that
1.2.1 had been released. At first I upgraded the clients on half of my
systems and lost connection on them all, I was forced to roll back to the
previous version to restore service and all OK again.

I then upgraded the server software hoping a server update might fix
something - no change.

Tonight I tried 1.2.1 again on one spare windows computer and did the tests
outlined in my posts, still faulty. If I use the IPv4 address I get
connection OK but 1.2.1 will not work using my DNS address.

Cheers

**Comment by dinger1986** [comment]
I have heard the issue with dns before, I am sure thats down to something docker side than rustdesk as rustdesk running directly on a machine would work fine (you could try it directly on your pi)

**Comment by Greytech52** [comment]
Sorry, I am not sure what you mean when you say " rustdesk as rustdesk
running directly on a machine would work fine (you could try it directly on
your pi)".

The Pi is running headless with no GUI so can't run any tests on that as I
don't have any other software on it other than PiHole which is running in
root, not in Docker. Using an IPv4 address in the client works OK so it
looks like a client issue to me, not a server issue. It tells me that the
server is responding and ports are open. You could try for yourself between
two devices using the host address of my server qnkowhawo3rkty3i.myfritz.net
- that will eliminate (or confirm) the server from the equation.
I am using that address for other things, they all work fine on both IPv4
and IPv6.

Cheers
