### ISSUE TITLE
UI: Menu icons hover text inconsistency

### ISSUE THREAD

**Issue by sahilyeole** [rustdesk/rustdesk#5228]
### Bug Description

Not all menu icons show hover text. These icons can be confusing.

### How to Reproduce

Try hovering over all the menu icons

### Expected Behavior

It should show some hover text similar to this:

<img width="333" alt="Screenshot 2023-08-02 at 10 36 12 AM" src="https://github.com/rustdesk/rustdesk/assets/73148455/18348f89-17be-4c73-b9fc-caf7e2e42301">

### Operating system(s) on local side and remote side

Macos

### RustDesk Version(s) on local side and remote side

1.2.2 (nightly)

### Screenshots

<img width="330" alt="Screenshot 2023-08-02 at 10 36 02 AM" src="https://github.com/rustdesk/rustdesk/assets/73148455/5c1847d6-bb6f-4d73-a86b-13d3d882f6ee">

**Comment by sahilyeole** [comment]
Can I work on it @rustdesk ?

**Comment by rustdesk** [comment]
This is open source, nobody can prevent you from working on it.

**Comment by rustdesk** [comment]
We removed some hove text, because it hides 

<img width="475" alt="image" src="https://github.com/rustdesk/rustdesk/assets/71636191/8019f605-6727-4fa7-9528-1b742c5d4379">

**Comment by rustdesk** [comment]
It will be good if you can add all hover text and avoid hiding.

<img width="122" alt="image" src="https://github.com/rustdesk/rustdesk/assets/71636191/00cb0085-dacd-44bf-95b0-32558ba1f9fe">

**Comment by sahilyeole** [comment]
> It will be good if you can add all hover text and avoid hiding.
> 
> <img alt="image" width="122" src="https://user-images.githubusercontent.com/71636191/257713172-00cb0085-dacd-44bf-95b0-32558ba1f9fe.png">

How about displaying hover text above the cursor only for those which would cause hiding?

**Comment by rustdesk** [comment]
yes, you can try.

**Comment by rustdesk** [comment]
Anything about UI you find, please propose, our UI is not good, frankly.

**Comment by sahilyeole** [comment]
> Anything about UI you find, please propose, our UI is not good, frankly.

Ok sure

**Comment by sahilyeole** [comment]
Keeping it above wasn't really an option as it is already on the top of the screen.
So can we do a small delay with property `waitDuration: Duration(milliseconds: 500)` for tooltip?
This will avoid immediate hiding, and I think it even looks better.
![Screen Capture_select-area_20230810112702](https://github.com/rustdesk/rustdesk/assets/73148455/52d84e5c-4fa7-4fe0-a7f9-8b1ebeec179c)

**Comment by rustdesk** [comment]
yes, a standard delay is better

**Comment by rustdesk** [comment]
set it to 1.5s, which is used in macos

**Comment by rustdesk** [comment]
i guess there is a gloabl flutter settings for this, you can check. flutter really does bad on desktop.

**Comment by sahilyeole** [comment]
Sure, I will look into that.
