### ISSUE TITLE
connected from deepin Linux to Windows 10 and there was a flash back

### ISSUE THREAD

**Issue by hlinfocc** [rustdesk/rustdesk#5229]
### Bug Description

I connected from deepin Linux to Windows 10 and there was a flash back (the program immediately exited after connecting)

### How to Reproduce

Run rustdesk-1.2.1-x86_64.AppImage as a regular user on deepin Linux and connect to the rustdesk client on Windows 10

### Expected Behavior

Can connect normally without flashing back

### Operating system(s) on local side and remote side

deepin V20.8 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

![deepinToWindows-logs](https://github.com/rustdesk/rustdesk/assets/30789561/d24b5907-3a03-4f74-ac86-402d9126e967)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by willmcginnis** [comment]
Encountering this also. Happy to test if necessary

**Comment by kenderipa** [comment]
Same problem. Debian (JWM) connecting to an Android device. Other way around works fine.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4844#issuecomment-2294765194

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/5457#issuecomment-2308556053
