### ISSUE TITLE
phytium ft-2000 + YINHE KYLIN Operating System Can be opened but garbled

### ISSUE THREAD

**Issue by yanchenyuvip** [rustdesk/rustdesk#5239]
### Bug Description

The software can be opened but garbled!

### How to Reproduce

The software can be opened but garbled!

### Expected Behavior

The software can be opened but garbled!

### Operating system(s) on local side and remote side

v10

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![微信截图_20230803160649](https://github.com/rustdesk/rustdesk/assets/44298325/a15253db-8ed1-464c-9704-cbeed31bd19e)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
