### ISSUE TITLE
linux-pipewire issue

### ISSUE THREAD

**Issue by hotspringGG** [rustdesk/rustdesk#5245]
### Bug Description

I install Rustdesk by DPKG(I am using Kali linux, a debian-based distro.)
And dpkg shows I missed some libs.
``` rustdesk depends on gstreamer1.0-pipewire; however: Package gstreamer1.0-pipewire is not installed.```
After I run ```sudo apt install -f```to fix the dependencies error, I found that my bluetooth cannot use.
because there has a issue between gstreamer1.0-pipewire and pulseaudio.

### How to Reproduce

install pulseaudio and Rustdesk, you can make a broken bluetooth environment

### Expected Behavior

I just install Rustdesk

### Operating system(s) on local side and remote side

linux and did not use remote desktop

### RustDesk Version(s) on local side and remote side

1.2.1

### Screenshots

Sorry I don't want to break my environment again.

### Additional Context

the pipewire pkg has many issues.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by hotspringGG** [comment]
However, it's a Debian-based systems package issue.
As my test, don't use Pipewire version has no issue like this
since 1.2, the sound system api change to Pipewire, the issue came.
1.1.9 hasn't got this issue.

**Comment by hotspringGG** [comment]
> tracked by #3565

However, it's a Debian-based systems package issue.
As my test, don't use Pipewire version has no issue like this
since 1.2, the sound system api change to Pipewire, the issue came.
1.1.9 hasn't got this issue.
