### ISSUE TITLE
Video encoding downsamples retina resolutions

### ISSUE THREAD

**Issue by DewVinci** [rustdesk/rustdesk#5246]
### Bug Description

When connecting to a macOS device with a retina display, the video encoding uses the non-retina resolution.
When I connect from a Windows system with a high-density display to macOS system with a retina display, I end up getting a very blurry image (scaled down on the server from 2x to 1x and then scaled back up on the client).

### How to Reproduce

Install RustDesk on a macOS laptop with a retina display
Connect from a Windows machine with a 150% scaled display (or higher)
Notice that "Scale Original" results in a tiny display at the non-retina resolution
Notice that "Scale Adaptive" results in a blurry display

Also notice that there is no difference in RustDesk's apparent resolution when switching the macOS device from e.g. "1920x1080" to "1920x1080 low resolution"

### Expected Behavior

At least optionally, the macOS server should be encoding the full resolution display

### Operating system(s) on local side and remote side

Win11 -> macOS

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

<img width="1008" alt="Screenshot 2023-08-03 111354" src="https://github.com/rustdesk/rustdesk/assets/322691/9425f8a0-70d4-46a2-9f41-48d8a5fdda2d">

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/rustdesk) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/rustdesk/rustdesk/issues/5246">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/rustdesk/rustdesk/issues/5246/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/rustdesk/rustdesk/issues/5246/pledge.svg">
</picture>
</a>

**Comment by rustdesk** [comment]
In the plan

**Comment by rustdesk** [comment]
@sahilyeole

**Comment by sahilyeole** [comment]
I noticed something that might be helpful, I don't know.
I have an extension called better display which lets you turn on/off HiDPI(retina). If I turn off HiDPI on my mac while being connected through rustdesk, the stream of my mac on controlling side gets sharper, looks less blurry, but my mac display gets blurry and if I turn it on like normal the stream again gets blurry.

So maybe there's only one output of retina resolution being captured of one display when connected to rustdesk.
I'm not sure though just an observation.

<img width="250" alt="Screenshot 2023-10-11 at 4 37 02 AM" src="https://github.com/rustdesk/rustdesk/assets/73148455/f1eab575-371f-4155-ae42-01bcafc1dd32">

**Comment by kesh-007** [comment]
Hi! Is the issue still open?  I am interested to work on this

**Comment by sahilyeole** [comment]
Yes, it is still open.

**Comment by kesh-007** [comment]
Could you please assign me the task related to the open issues? I'm eager to contribute

**Comment by Foul-Tarnished** [comment]
![image](https://github.com/rustdesk/rustdesk/assets/107711110/159d384c-5e02-42d2-b727-cb820997a50a)
How it looks on my side
1117p on host mac (2234p display)
1080p display on the windows guest

Tried to force AV1, didn't change anything.
Tried to force mac at 2234p, didn't change anything.

**Comment by Foul-Tarnished** [comment]
Does Mac OS even support hardware encoding/decoding of AV1 ?

M3 hw support AV1, but FFMPEG still doesn't (see https://www.mail-archive.com/ffmpeg-trac@avcodec.org/msg65391.html)

**Comment by rustdesk** [comment]
You can pledge behind and help support this effort using Polar.sh


<a href="https://polar.sh/rustdesk/rustdesk/issues/5246">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/rustdesk/rustdesk/issues/5246/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/rustdesk/rustdesk/issues/5246/pledge.svg">
</picture>
</a>

**Comment by sahilyeole** [comment]
To solve this issue we need to multiply the captured display's resolution by 2 if it is a retina display.

Reason: That's the nature of how Retina/HiDPI works on macs. The actual rendered resolution is twice the amount of the selected resolution. While the scaling looks as if it was of the selected resolution. [Source](https://forums.macrumors.com/threads/what-is-hidpi.2032543/)

>  I'm running my 13" at 1440x900, scaled. The display itself is 2560x1600.
This is what happens:
> - the screen is composed (window sizes, positions) as if it was a 1440x900 screen
> - it's a retina screen (HiDPI), so everything is rendered x2, i.e. at 2880x1800
> - the 2880x1800 result is displayed on a 2560x1600 screen

Currently, we are only capturing the selected resolution, not the actual rendered resolution of the retina display (which is 2x). That is why it is blurry.

This is the result with 2x resolution:
![mac_blur](https://github.com/rustdesk/rustdesk/assets/73148455/783cae44-f21b-41ef-a6ee-cce27c886bb6)

Earlier:
![mac_blur_earlier](https://github.com/rustdesk/rustdesk/assets/73148455/440e7762-8898-48be-a6e5-aa7b367f527c)

I hope the difference in images is clear, but in real life the difference is huge and the video is very sharp.

Now, I just need to find a way to identify whether the currently captured display is a retina or not if it is a retina then 2x or else normal.

**Comment by 21pages** [comment]
@DewVinci @kesh-007 @Foul-Tarnished 
Could you try https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.2.4-x86_64-retina.dmg?

**Comment by kajuk** [comment]
It fails with:

dyld[83816]: Library not loaded: @rpath/FlutterMacOS.framework/Versions/A/FlutterMacOS
  Referenced from: <01B2431F-5E37-35CF-AB3B-4D4ECC5926D0> /Applications/RustDesk.app/Contents/MacOS/RustDesk
  Reason: tried: '/usr/lib/swift/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/usr/lib/swift/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/Volumes/RustDesk Installer/RustDesk.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' (code signature in <4C4C4476-5555-3144-A1FB-A50ABB3DEE27> '/Volumes/RustDesk Installer/RustDesk.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Volumes/RustDesk Installer/RustDesk.app/Contents/MacOS/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/Volumes/RustDesk Installer/RustDesk.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' (code signature in <4C4C4476-5555-3144-A1FB-A50ABB3DEE27> '/Volumes/RustDesk Installer/RustDesk.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/usr/lib/swift/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/usr/lib/swift/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/Volumes/RustDesk Installer/RustDesk.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' (code signature in <4C4C4476-5555-3144-A1FB-A50ABB3DEE27> '/Volumes/RustDesk Installer/RustDesk.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Volumes/RustDesk Installer/RustDesk.app/Contents/MacOS/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/Volumes/RustDesk Installer/RustDesk.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' (code signature in <4C4C4476-5555-3144-A1FB-A50ABB3DEE27> '/Volumes/RustDesk Installer/RustDesk.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Library/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/System/Library/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file, not in dyld cache)

**Comment by ofgrenudo** [comment]
I found that turning off HDR in windows settings solved the issue.

**Comment by southerndoc** [comment]
> I found that turning off HDR in windows settings solved the issue.

Where is this option?  I'm experiencing blurriness when connecting from Windows to Mac.  The adaptive display is blurry.  Someone recommended fit local resolution, which I haven't tried yet (my laptop isn't booted up and is at work).
