### ISSUE TITLE
nightly - linux - does not start on startup

### ISSUE THREAD

**Issue by working-name** [rustdesk/rustdesk#5248]
### Bug Description

rustdesk service is running on boot but no connections work, desk appears offline

### How to Reproduce

Install nightly
Restart linux computer
Have no way back in.

### Expected Behavior

Install nightly
Restart linux
Live happily.

### Operating system(s) on local side and remote side

windows 11 > debian 11

### RustDesk Version(s) on local side and remote side

nightly > nightly

### Screenshots

not applicable.

**Comment by rustdesk** [comment]
@sahilyeole your PR is mostly related to this part. Please check.

**Comment by rustdesk** [comment]
@sahilyeole any update?

**Comment by sahilyeole** [comment]
> @sahilyeole any update?

Still working, I believe it's mainly due to user mismatch. I'm trying to figure out a way to fix it. Let's see.

**Comment by sahilyeole** [comment]
I tried a few custom builds, #5212 has indeed solved the `login error: connection refused` problem (as per #5126) which occurred once in a while after restarting and consistently upon logging off, due to user mismatch.

But for some reason(I need to check more why) it is causing --server subprocess to start approx 1 minute after restarting/logging off.

After --server starts, the remote machine is back online.
```bash
ps aux | grep rustdesk
root         535  0.2  0.3 515928 25564 ?        Ssl  22:21   0:00 /usr/bin/rustdesk --service
root        4310  1.8  0.3 1664948 29248 ?       Sl   22:22   0:00 /usr/lib/rustdesk/rustdesk --server
```
Remote: Debian 12 XFCE

**Comment by sahilyeole** [comment]
@working-name If you don't mind, could you please confirm the following behavior on the latest nightly build:
1. Restart linux (remote) machine
2. Try to connect it; should show as offline
3. Wait for approx 1 minute and try again
4. Remote is online; connection successful

**Comment by working-name** [comment]
@sahilyeole 

Installed nightly build, set password, custom relay and such, confirmed I can connect.

Rebooted linux, machine showed offline for about 30 seconds after the login screen was up. Then it was able to connect. It even swapped resolution once I logged on the user, pretty nice.

**Comment by sahilyeole** [comment]
> @sahilyeole
> 
> Installed nightly build, set password, custom relay and such, confirmed I can connect.
> 
> Rebooted linux, machine showed offline for about 30 seconds after the login screen was up. Then it was able to connect. It even swapped resolution once I logged on the user, pretty nice.

That was quick, thank you. I am working on reducing that initial delay.
