### ISSUE TITLE
Keyboard in Android

### ISSUE THREAD

**Issue by it-boerner** [rustdesk/rustdesk#5251]
### Bug Description

With the client version 1.2.1 I was able to access Android tablets and the input on the keyboard was forwarded correctly.

### How to Reproduce

With version 1.2.2, access to Android (version 1.1.10-1) is possible, but typing on the Windows keyboard and scrolling no longer work

### Expected Behavior

When I type on my keyboard, it should be passed to Android. Also, I can no longer scroll with the mouse

### Operating system(s) on local side and remote side

Windows -> Android

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.1.10-1

### Screenshots

.

**Comment by rustdesk** [comment]
How about 1.2.2 -> 1.2.2 android?

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
The keyboard does never work, how can you make it work on 1.2.1 magically?

**Comment by it-boerner** [comment]
> Wie wäre es mit 1.2.2 -> 1.2.2 Android?

Unfortunately I cannot install version 1.2.2 on Android.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367
