### ISSUE TITLE
Keyboard transfer is not exact

### ISSUE THREAD

**Issue by attikov** [rustdesk/rustdesk#5255]
### Bug Description

The host does not know it the pressed key was the left ctrl or the right ctrl, (most likey other keys too) losing functionality in some apps.

### How to Reproduce

.

### Expected Behavior

.

### Operating system(s) on local side and remote side

W10 -> W10

### RustDesk Version(s) on local side and remote side

1.2.0+

### Screenshots

.

### Additional Context

.

**Comment by rustdesk** [comment]
@fufesou

**Comment by dignow** [comment]
@attikov Hi, thanks for your feedback. Did you use "Map mode" or "Translate mode beta"

I've tried Win -> Win. The "Map mode" just send the key code to the remote side. The host knows whether the key is the left ctrl or the right ctrl, and the other keys.

![V3NFRYOAGFNP4NHC6$R5PTA](https://github.com/rustdesk/rustdesk/assets/136106582/7cb42e8e-e910-419a-98e9-6b8463a9be5a)

**Comment by fufesou** [comment]
@attikov  Hi, thanks for your feedback. Did you use "Map mode" or "Translate mode beta"

I've tried Win -> Win. The "Map mode" just send the key code to the remote side. The host knows whether the key is the left ctrl or the right ctrl, and the other keys.

![V3NFRYOAGFNP4NHC6$R5PTA](https://github.com/rustdesk/rustdesk/assets/136106582/7cb42e8e-e910-419a-98e9-6b8463a9be5a)

**Comment by attikov** [comment]
Good question, didn't even know that such thing exists, it was in legacy mode, map mode works like a charm.
I'll try to remember that this setting exist. Is there a documentation on that? What is doing what?

**Comment by fufesou** [comment]
https://github.com/fufesou/rustdesk/wiki/Keyboard-mode----Translate-Mode

![4IQ2JD2X$4(R3$~D0H~T)~P](https://github.com/rustdesk/rustdesk/assets/13586388/90cea93c-07b0-440e-85b1-11cd419ed125)

**Comment by rustdesk** [comment]
No idea why they are still in legacy mode after upgrading to 1.2.

**Comment by mikekgr** [comment]
> No idea why some users are still in legacy mode after upgrading to 1.2. @fufesou have a check.

What I have seen in my upgrade from 1.1.9 to 1.2.2 (in some Windows 10 PCs) is that the default keyboard remaining in legacy mode until I exclusively change it !

**Comment by dignow** [comment]
@mikekgr If you do the following steps, the keyboard mode will be set to the "Legacy mode".
1. Upgrade local version to 1.2.2,while keeps the remote version to 1.1.9.
2. Establish a connection to the remote side.

Then the configuration file will set the keyboard method to the "Legacy mode".

3. After upgrading the remote side to 1.2.2, the keyboard mode is still the "Legacy mode".

The way to deal with the problem is that if the version of the remote side is less than 1.2.0, the do not save the keyboard mode 
 to the configuration file.

But I'm not sure it's worth dealing with this special case.

**Comment by rustdesk** [comment]
> But I'm not sure it's worth dealing with this special case.

No need to spend time on this.

**Comment by rgurfriend** [comment]
pls add separate keyboard in rustdesk for android phone  to android phone remote control  . typing is not good . or tell me a solution for phone to phone typing smoothly

**Comment by miladhatami1393** [comment]
No need

**Comment by fcaronte** [comment]
I have problem to send special key from android app (test with nigthly version to 1.3.9) but won't work, if I connect from kasmvnc and enable the translation beta input will work correctly but can't see how to enable this on the android app. I'm using server from docker and try to update to last release, and can't understand if is possible to use nightly version on server side too
