### ISSUE TITLE
Black or still image after login, no stream connection starting

### ISSUE THREAD

**Issue by rengel8** [rustdesk/rustdesk#5257]
### Bug Description

Being in the same intranet I have hazzlefree access from a Windows 10 notebook to different remote PCs. This also works fine from the internet, but I do have problems with one Windows 10 machine. I tested RustDesk 1.1.9 and 1.2.1 with no actual difference in behaviour. I also can't figure out the difference from that PC to the several others (same software(s) but i7 instead of AMD). 
It is possible to transfer files and this is works also stable, like expected.

Is there a way to get some debugging information as log (without ID's) so that this issue or what is happening/exchanged can be understood better?

### How to Reproduce

Always between these two machines it is constantly not possible, to get a working remote session via internet.

### Expected Behavior

A stable stream connection.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9, 1.2.1 -> 1.2.1

### Screenshots

Most of the time there are two overlaying windows on top of each other but sometimes there is a very short moment, where the screen gets "updated" with another static image.
![00](https://github.com/rustdesk/rustdesk/assets/34138513/8fbc930e-2ceb-4e05-b451-1804308130fa)
![01](https://github.com/rustdesk/rustdesk/assets/34138513/dcbb4497-795b-4398-9df8-5b407598f552)
![02](https://github.com/rustdesk/rustdesk/assets/34138513/5929e4fd-e7b2-4f68-b61d-a305eb7220e9)
![03](https://github.com/rustdesk/rustdesk/assets/34138513/097f1dc8-4427-45aa-8d26-b09c728e101b)

**Comment by rustdesk** [comment]
we do not know your language in pic.

**Comment by rengel8** [comment]
It is German and translates to:
"Connection established. Waiting for the other screen ..."
It also interesting that the OS language is English, but Rustdesk is German, but this isn't important to me.

**Comment by rustdesk** [comment]
Please try out the nightly build, if there is still overlaying window. https://github.com/rustdesk/rustdesk/releases/nightly

**Comment by rengel8** [comment]
I can only test my client and not the host side with the nightly build (So it is 1.2.2 -> 1.2.1). The windows are still overlaying and the message is identical to the above.
![grafik](https://github.com/rustdesk/rustdesk/assets/34138513/3b402c87-33ee-4dc4-ae8b-d788b4ca6702)

.. but after a while it comes to an error message, but before that the distant screen can be moved a few miliiseconds.
 
Connection Error
"bytes remaining on stream"
Try again
![grafik](https://github.com/rustdesk/rustdesk/assets/34138513/ab452e62-0c10-4d04-be83-0c8a76e6bde3)

So it is different, but also similar. I will test that further.
