### ISSUE TITLE
Ask remote user for elevation gives error message on local side

### ISSUE THREAD

**Issue by Benny7587** [rustdesk/rustdesk#5271]
### Bug Description

When asking the remote user for elevation, the local pc showing: "Elevation error - No need to elevate"
The remote user does not see a UAC prompt and the local user does not have elevated rights on the remote pc.

### How to Reproduce

Set up RustDesk connection from local to remote pc via self hosted server.
After an established connection on the local pc click menu "Request elevation" 
In the request elevation modal on the local pc select: Ask the remote user for authentication.
An error popup shows: "Elevation error - No need to elevate"
No UAC prompt on the remote PC

### Expected Behavior

I would expect to see a UAC popup on the remote PC

### Operating system(s) on local side and remote side

W11 -> W11 

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.2

### Screenshots

![elevation error](https://github.com/rustdesk/rustdesk/assets/25138816/c5b2fe2d-aa9a-4384-a685-850f55195809)
![request](https://github.com/rustdesk/rustdesk/assets/25138816/cdde2707-85a8-4a93-8843-399c3fa52eaa)

**Comment by 21pages** [comment]
One possible reason, it has been connected by another user and another user has elevated it, is it?

**Comment by Benny7587** [comment]
It looks very much like a Windows 11 issue. I tested with two W10 pc's and elevation works fine.
W10 -> W11 gives an elvation issue.
W11 -> W10 is okay.

**Comment by rustdesk** [comment]
need to double check code related to elevation 

![image](https://github.com/rustdesk/rustdesk/assets/71636191/8d529806-de24-4677-b0f1-6758ecd807d0)

**Comment by 21pages** [comment]
https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk_test_installed_and_root.exe
Could you run this in a terminal on the host machine which cannot be elevated?

**Comment by Benny7587** [comment]
_> https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk_test_installed_and_root.exe Could you run this in the git bash (I don't know why cmd/powershell print nothing) on the host machine which cannot be elevated? if the result is "is installed:true is root:false", check whether the print "installed exe" exists, if it exists, delete it and retry._

No idea if this was ment for me but via e-mail i got the question to run this exe in a terminal on a machine which could not be elevated. When running this exe in a cmd-window this exe gives no output at all.

**Comment by 21pages** [comment]
Does the host machine display the install button ? 
![1691501189476](https://github.com/rustdesk/rustdesk/assets/14891774/58d86232-2c4c-4568-8535-9c211c1f34f6)

**Comment by Benny7587** [comment]
Output in Bash is:
$ ./rustdesk_test_installed_and_root.exe
installed exe:C:\Program Files\RustDesk\RustDesk.exe
is installed:true, is root:false

**Comment by 21pages** [comment]
> is installed:true
Can you find it in start menu? How did you install/upgrade it, 
> installed exe:C:\Program Files\RustDesk\RustDesk.exe
Can it be uninstalled? if not, delete it manually.

**Comment by Benny7587** [comment]
Very strange. On both W11 PC's when running version 1.2.1, in the lower left corner i see: Your installation is a lower version but RustDesk is not installed on these machines. On both machines i tested with a nightly version 1.2.2 before but did not install this version. That means i cannot uninstall. I deleted the rustdesk dir from appdata/local and roaming so there must be something in the registry from 1.2.2 (????)

**Comment by Benny7587** [comment]
Founfd it!!! In the program files there was an old Rustdesk directory. After deleting the Install prompt shows up in the lower left corner. I will now try to do an elevation from W10 -> W11 with version 1.2.1 on both PC's.

**Comment by 21pages** [comment]
It seems that you installed a version lower than 1.2.1, and it was not unintalled completely.
