### ISSUE TITLE
Keyboard Layout bug with Android App (map/translate support for mobile physical keyboard)

### ISSUE THREAD

**Issue by handmade82** [rustdesk/rustdesk#5279]
### Bug Description

Hi,
when I connect to my linux mint computer via android app, I get into the problem that my german keyboard layout will be translated to an english/us keyboard. My workaround is to use the "nomachine" app which works fine but it would be great if I could switch back to rustdesk again. My Smartphone is an Samsung Galaxy S8+ with Android 9 but I have this bug with other mobiles too. In this case I use samsung dex to work remote with my computer and connect a physical keyboard an mouse with the mobile. But you get the keyboard bug with physical keyboard and screen keyboard.

### How to Reproduce

Use the android app with a mobile that is set to german keyboard and connect remote to a linux or windows machine. Then type in characters like "ü", "ä", "z".

### Expected Behavior

The characters should be correct interpreted.

### Operating system(s) on local side and remote side

android 9 -> linux mint 21.1

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

there is no bug prompt.

**Comment by rustdesk** [comment]
We do not implement intentional keyboard for android physical keyboard yet. @fufesou

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/9717
