### ISSUE TITLE
Failed to connect via relay server

### ISSUE THREAD

**Issue by ddjanic** [rustdesk/rustdesk#5283]
### Bug Description

Good afternoon, at yesterday - stopped connecting to  RustDesk network through some providers.
"Connection ErrorFailed to connect via relay server: Failed to connect to relay server: Please try later"

But if run VPN connect (OpenVPN, Ouline, etc.) and restart the service, it connects OK without problems.

I attached file C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT.log
[RustDesk_rCURRENT.log](https://github.com/rustdesk/rustdesk/files/12282044/RustDesk_rCURRENT.log)

### How to Reproduce

Russia, Rostelecom provider.

### Expected Behavior

Connect to relay.

### Operating system(s) on local side and remote side

Windows 10 x64 for Workstations

### RustDesk Version(s) on local side and remote side

1.2.1

### Screenshots

![2023-08-07_18-29-13](https://github.com/rustdesk/rustdesk/assets/1620653/7162dc70-2737-46c6-a84b-236c4be98035)

**Comment by rustdesk** [comment]
self hosting please

**Comment by rustdesk** [comment]
we have no way to solve your network problem.
