### ISSUE TITLE
Elevation for security settings on RustDesk can be bypassed

### ISSUE THREAD

**Issue by tejasraman** [rustdesk/rustdesk#5284]
### Bug Description

When accessing security settings on RustDesk 1.2.1 on a Linux system (tested using Debian 12 GNOME and Fedora 38 KDE), clicking "cancel" on the policykit dialog allows the user to access security settings for RustDesk. 

This is an extremely serious security problem (as security settings can be changed 

### How to Reproduce

- Install RustDesk
- Click on Settings 
- Open security settings
- Click on "Unlock Security Settings"
- Click "Cancel" on the polkit dialog

### Expected Behavior

RustDesk rejects access to security settings if correct admin password not entered.

### Operating system(s) on local side and remote side

Linux (KDE, GNOME) (remote side N/A)

### RustDesk Version(s) on local side and remote side

1.2.1 (remote side N/A)

### Screenshots

https://github.com/rustdesk/rustdesk/assets/96961804/61716c5c-d3cf-4a6e-816c-6a757407bbb1

**Comment by rustdesk** [comment]
#5255

**Comment by rustdesk** [comment]
#5205
