### ISSUE TITLE
Only IPv4 is being listened to, and the IPv6 port is not being listened to

### ISSUE THREAD

**Issue by a15355447898a** [rustdesk/rustdesk#5294]
### Bug Description

I have enabled IP access and set the port to 21118, but only the IPv4 port is being listened to, while the IPv6 port is not being listened to.

### How to Reproduce

Enabled IP access and set the port

### Expected Behavior

The ipv6 port should also be monitored

### Operating system(s) on local side and remote side

Windows11->nixos

### RustDesk Version(s) on local side and remote side

1.2.1->1.1.9

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/62456287/f27b2846-0d8f-4268-a1a1-0e02374ac648)

**Comment by rustdesk** [comment]
1.1.9 has no ipv6
