### ISSUE TITLE
touch screen no works on client 1.2.1

### ISSUE THREAD

**Issue by kvnxp** [rustdesk/rustdesk#5314]
### Bug Description

windows tablet pc, touch screen no work for move or click  beside of client

### How to Reproduce

-> Connect to remote host
-> Click on something using touch screen or move touch 

### Expected Behavior

Normal mouse interactions. absolute positions with touch

### Operating system(s) on local side and remote side

Windows 11 -> macOs Monterey

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

n/a

### Additional Context

n/a

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by dignow** [comment]
@kvnxp Hi, thanks for your feedback. Touch screen is supported in the latest nightly build. Can you please try https://github.com/rustdesk/rustdesk/releases/tag/nightly?

**Comment by kvnxp** [comment]
thks !! i will try !
