### ISSUE TITLE
Invoke-Ps2Exe input file not found

### ISSUE THREAD

**Issue by mfitrx** [rustdesk/rustdesk#5315]
### Bug Description

When running our custom Windows installation script from our self-hosted server, installation halts and quits due to urlhandler.ps1 not being found.

### How to Reproduce

1. Download the custom installer from self-hosted server.
2. Run PowerShell as Administrator.
3. Navigate to the directory containing the download.
4. Set the PS Execution Policy to being RemoteSigned to the CurrentUser Scope.
5. Run the WindowsAgentAIOInstall.ps1.

### Expected Behavior

I expected to run the installer, have RustDesk install with our self-hosted server information baked in, and automatically open to the main window.

### Operating system(s) on local side and remote side

Windows 10 Pro 22H2 19045.3208 -> Ubuntu Server 20.04

### RustDesk Version(s) on local side and remote side

1.2.1

### Screenshots

![Administrator_ Windows PowerShell 2023-08-09 3_46_23 PM](https://github.com/rustdesk/rustdesk/assets/137228149/8ca04a33-6948-4fd8-9104-6a392a8c03bc)

**Comment by dinger1986** [comment]
This is techaholds script not rustdesk. 

Your script needs updated please check the current one on techahold.
