### ISSUE TITLE
向远程计算机复制文件会卡住

### ISSUE THREAD

**Issue by bgycn** [rustdesk/rustdesk#5327]
### Bug Description

不使用密码，而是在远程计算机上点击“接受”建立的连接，复制复制文件时会卡住，鼠标指针不断转圈圈

### How to Reproduce

不使用密码，而是在远程计算机上点击“接受”建立的连接，在本地计算机复制文件，在远程计算机点击鼠标右键，会导致远程计算机资源管理器卡住，鼠标指针不断转圈圈

### Expected Behavior

不使用密码，而是在远程计算机上点击“接受”建立的连接，应该也可以正常复制

### Operating system(s) on local side and remote side

windows 11 -> windows 10

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

<img width="598" alt="Snipaste_2023-08-10_17-55-46" src="https://github.com/rustdesk/rustdesk/assets/78190214/c8bdd41c-80f6-410e-b1f6-a35cb53286ad">
<img width="607" alt="Snipaste_2023-08-10_17-58-02" src="https://github.com/rustdesk/rustdesk/assets/78190214/6b0b3304-6db0-4f08-961f-245d8d9e3cb5">

**Comment by rustdesk** [comment]
fixed in nightlybuild
