### ISSUE TITLE
Clicking New Connection button resizes Main Window to its previous dimensions

### ISSUE THREAD

**Issue by GSM** [rustdesk/rustdesk#5339]
### Bug Description

When you click the New Connection button in the session's window, the Main Window gets resized if it was previously maximized.
It happens every time in this scenario.

### How to Reproduce

1. Run Rust Desk
2. Maximize the Main Window
3. Open remote session (optionally minimize or close the Main Window)
5. In the session's window click the New Connection button

### Expected Behavior

At most focus should be switched to Main Window or Main Windows restored/displayed without changing its dimensions or state. 

### Operating system(s) on local side and remote side

Windows 10, 11 -> Windows 8, 10, 11

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.2, 1.1.9

### Screenshots

N/A

### Additional Context

The list of reported OSes and Versions might not be exhaustive - I tested this bug on them.

**Comment by rustdesk** [comment]
close as fix merged
