### ISSUE TITLE
TCP Tunneling - it's not possible to add Tunnel (Linux)

### ISSUE THREAD

**Issue by twprh** [rustdesk/rustdesk#5343]
### Bug Description

It is not possible to add new tunnel 
Bug appeard in nightly between version from 04.08.2023 and 10.08.2023

Adding tunnelparameters manually in peer.toml is working 

### How to Reproduce

try adding tcp tunnel

### Expected Behavior

fill out fields and add tunnel like in nightly from 04.08.2023

### Operating system(s) on local side and remote side

Linux  -> Windows

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.2

### Screenshots

![Peek 2023-08-11 02-07](https://github.com/rustdesk/rustdesk/assets/46543715/e8b76dff-0594-41b9-8514-74301e1aea08)
should be:
![Peek 2023-08-11 02-19](https://github.com/rustdesk/rustdesk/assets/46543715/0c9219c8-7677-4046-8067-82f7005fdccb)

**Comment by rustdesk** [comment]
close as fix just merged.
