### ISSUE TITLE
Alt+Tab (switch between windows) doesn't get transmitted to remote session

### ISSUE THREAD

**Issue by GSM** [rustdesk/rustdesk#5357]
### Bug Description

It is not possible to switch between windows using the key combination of Alt+Tab

### How to Reproduce

1. Connect to remote session
2. Have at least 2 windows opened on the remote machine
3. Use Alt+Tab to switch between windows

### Expected Behavior

Windows get switched.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 8, 10, 11

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.1.9, 1.2.2

### Screenshots

N/A

### Additional Context

Individual keystrokes on Alt and Tab get through perfectly. This issue affects the combination of Alt+Tab.
It is possible that other key combos are also affected.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/5255
