### ISSUE TITLE
The session window has a white border when maximized

### ISSUE THREAD

**Issue by GSM** [rustdesk/rustdesk#5358]
### Bug Description

The session window's border doesn't disappear when maximzed.

### How to Reproduce

1. Open remote session
2. Maximize the session's window

### Expected Behavior

A maximized window shouldn't have a border.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 8, 10, 11

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.1.9, 1.2.2

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/12634430/bd7c4e4b-e17d-4ecf-907f-63b1f697d62a)

**Comment by rustdesk** [comment]
on mac, maximum window of chrome has border, full screen has no border.

**Comment by dignow** [comment]
I think it's OK that the window has the border On mac.
But window on Windows should not has the border.

I'll try to fix then.
