### ISSUE TITLE
Resolution 

### ISSUE THREAD

**Issue by roy-lueders** [rustdesk/rustdesk#5361]
### Bug Description

When i Connect from Android to PC the Resolution will be change.

### How to Reproduce

Change in remote PC the Resolution to 1280*720. Close the settings. Exit the remote. Open the remote again the Resolution will be changed to 1024*768.

### Expected Behavior

IT only Happens from Android to Windows 10.

### Operating system(s) on local side and remote side

Android 13 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

![Screenshot_2023-08-12-04-02-17-766_com carriez flutter_hbb](https://github.com/rustdesk/rustdesk/assets/21952094/12bfaf8a-8221-4d0c-bf70-23677edd1f82)
![Screenshot_2023-08-12-03-59-11-647_com carriez flutter_hbb](https://github.com/rustdesk/rustdesk/assets/21952094/cf379e1a-0637-4775-9230-363b74c196c0)

**Comment by rustdesk** [comment]
close as fix merged
