### ISSUE TITLE
windows10 Interface blank

### ISSUE THREAD

**Issue by qingee** [rustdesk/rustdesk#537]
![image](https://user-images.githubusercontent.com/36303077/168580175-c333ea37-4fad-48d4-b298-b4c17b1248a8.png)
windows10 The interface is blank，How to solve it？

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/210
That's why we wanna rewrite UI.

**Comment by qingee** [comment]
When can it be solved？

**Comment by rustdesk** [comment]
rewriting ui is not a short term job

**Comment by grummbeer** [comment]
@qingee have you tried the nightly version https://github.com/rustdesk/rustdesk/releases/tag/nightly

@rustdesk
> rewriting ui is not a short term job

but done :-) thanks.

Do you think this is caused by sciter? then the other "white/blank screen" issues also? for example this #80

**Comment by rustdesk** [comment]
Should be

**Comment by rustdesk** [comment]
agree
