### ISSUE TITLE
Keyboard input not working

### ISSUE THREAD

**Issue by 0verEngineer** [rustdesk/rustdesk#5374]
### Bug Description

I am connected to my Fedora x11 instance from a Fedora KDE Wayland instance, the keyboard input stopped working correctly, stuff like `ctrl+c` is coming through normally, but when i try to write into a text document nothing appears but writing in the Gnome application launcher (the app search thingy) works.

Also it would be good to be able to check the RustDesk version of the remote site in the UI when i am connected...

### How to Reproduce

I don't know

### Expected Behavior

Keyboard input should always work.

### Operating system(s) on local side and remote side

Fedora Linux KDE Wayland -> Fedora Linux Gnome X11

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.1.9

### Screenshots

Please make this field non-required.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/5255
