### ISSUE TITLE
Self built Linux Client does not include Rendezvous Server address

### ISSUE THREAD

**Issue by dwydler** [rustdesk/rustdesk#5375]
### Bug Description

Hello everyone,
i built my own clients, follow the documentation: https://rustdesk.com/docs/en/dev/build/all/. Download the new client from my fork and installed on an Ubuntu Server 22.04.

However, the client includes the values of both Repository secrets. The network settings in the client are empty.
The Windows Client, from the same built action works as expected. So i think it's not an configuration problem on my site.

Regards,
Daniel

### How to Reproduce

1. Create an fork of this repository
2. Create two Repository secrets with the names "RENDEZVOUS_SERVER" and "RS_PUB_KEY" and added each one the values (FQDN, Public key of the rustdesk server)
3. Enable an manual run the workflow "Flutter Nightly Build"
4. Download the built file rustdesk-1.2.2-x86_64.deb
5.  Installed the file with `apt install ./rustdesk-1.2.2-x86_64.deb`

Source: https://rustdesk.com/docs/en/dev/build/all/

### Expected Behavior

The Linux Client use the values of both Repository secrets (see screenshot below).
The Windows Client use the values of both Repository secrets (see screenshot below).

### Operating system(s) on local side and remote side

Ubuntu 22.04

### RustDesk Version(s) on local side and remote side

1.2.2

### Screenshots

Ubuntu 22.04:
![image](https://github.com/rustdesk/rustdesk/assets/3519224/f4c3f0d6-c1d8-483e-9c5e-e2a7a2afc9e1)

Windows 11:
![image](https://github.com/rustdesk/rustdesk/assets/3519224/1fd12afc-1932-485c-bd3f-3d5e65581d1f)

**Comment by rustdesk** [comment]
#763
