### ISSUE TITLE
Virus in version 1.2.1

### ISSUE THREAD

**Issue by JhonAndersonVelasco** [rustdesk/rustdesk#5379]
### Bug Description

360 Total security antivirus detects a virus just downloading file from github

### How to Reproduce

Install 360 Tolal security and download 1.2.1 version

### Expected Behavior

The file must be safe

### Operating system(s) on local side and remote side

Win11

### RustDesk Version(s) on local side and remote side

1.2.1

### Screenshots

![Captura de pantalla (27)](https://github.com/rustdesk/rustdesk/assets/104879206/22fed684-a5f7-40bd-9c91-443b3815af6c)

**Comment by dinger1986** [comment]
False positive, all AVs class remote access tools as grey ware as they can be used for good and bad!
