### ISSUE TITLE
Ubuntu 22.04 using X.Org(X11),screen doesn't display correctly.

### ISSUE THREAD

**Issue by tfkzptzt** [rustdesk/rustdesk#5387]
### Bug Description

我正在用Ubuntu22.04上的rustDesk，因为这个软件提示对Wayland适配不好，我就把Wayland关掉了，想使用X11：
`sudo nano /etc/gdm3/custom.conf`
`WaylandEnable=false`
`sudo systemctl restart gdm3`
结果画面成这样了：
![image](https://github.com/rustdesk/rustdesk/assets/53414921/917c5227-34c6-48a3-b06a-f877e3361696)
请问改如何解决？
还有选择被控制的显示器的设为默认怎么不起作用？

### How to Reproduce

`sudo nano /etc/gdm3/custom.conf`
`WaylandEnable=false`
`sudo systemctl restart gdm3`

### Expected Behavior

我希望能正常显示。
选择被控制的显示器可以记住默认值。

### Operating system(s) on local side and remote side

Windows11 -> Ubuntu 22.04 LTS

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.1

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/53414921/917c5227-34c6-48a3-b06a-f877e3361696)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by rustdesk** [comment]
I guess reboot can help you, maybe.
