### ISSUE TITLE
[BUG] Android TV input not working 

### ISSUE THREAD

**Issue by Dzordzu** [rustdesk/rustdesk#5389]
### Bug Description

No keyboard input / mouse / touchscreen input for android tv. Neither legacy, nor map modes are working. 

### How to Reproduce

1. Use device with android tv (11)
2. Enable mouse input (may require installation of the accessibility permission manager: https://www.reddit.com/r/AndroidTV/comments/pbdgh2/android_accessibility_service/)
3. Try to click anything

### Expected Behavior

Keyboard input and mouse (touch input) works

### Operating system(s) on local side and remote side

Linux -> Android TV 11

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.2

### Screenshots

![rustdesk-android-tv](https://github.com/rustdesk/rustdesk/assets/17514622/c59158fb-62c4-4dd2-a196-7f7b079420c9)

### Additional Context

Used TV: TCL 43P615

Works with Linux -> Android

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893

**Comment by Dzordzu** [comment]
Thanks :)

**Comment by frozen-cdn** [comment]
Exact same issue here on Formuler Z11 lineup of devices, a very popular and well made brand of AndroidTV boxes here.

I can connect to the device and have very very limited functionality for input -- only the little 3 mobile buttons (Back, Home, and ... button) at the top of the screen seem to work.

No keyboard input, and no mouse clicks are doing anything.

I will DONATE to see this resolved, in full.  And can provide open access any time a dev is ready to connect to the device -- it's plugged in and RustDesk is waiting for connections as we speak, so please let me know
