### ISSUE TITLE
Failed to sync adress book to server

### ISSUE THREAD

**Issue by IT-Betreuung** [rustdesk/rustdesk#5399]
### Bug Description

Failed to sync adress book to server: http 400,
FormatExeption: Unexpected character (at character 1)
Failed to parse the request body as JSON: expected value at line 1 columm 1

rustdesk nightly 1.2.2 - Windows and Android
rustdesk-server-pro 1.1.9

There is no error with rustdesk release 1.2.1.

### How to Reproduce

It happens when I want to add a new ID or rename an ID.

### Expected Behavior

0

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.2.2

### Screenshots

![Zwischenablage01](https://github.com/rustdesk/rustdesk/assets/49734977/0f4f283d-3d3b-4a03-9337-0ce8d6d037c7)

**Comment by rustdesk** [comment]
Fixed, will release 1.1.9 Pro soon.

**Comment by rustdesk** [comment]
You can try out https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.1.9 https://github.com/rustdesk/rustdesk/releases/tag/nightly

**Comment by IT-Betreuung** [comment]
Great work!

Thank you,
now it works again!
