### ISSUE TITLE
how to build windows exe?

### ISSUE THREAD

**Issue by vjeson** [rustdesk/rustdesk#54]
I run ,cargo build --release ,and run the grenerated rustdesk.exe ,only get the blank screen with console.
![image](https://user-images.githubusercontent.com/2101082/120662574-d7992b00-c4bb-11eb-98b4-e547a8d689bf.png)

**Comment by rustdesk** [comment]
take care of sciter tis/html/css files

**Comment by rustdesk** [comment]
#33 duplicate

**Comment by july008** [comment]
> I run ,cargo build --release ,and run the grenerated rustdesk.exe ,only get the blank screen with console.
> ![image](https://user-images.githubusercontent.com/2101082/120662574-d7992b00-c4bb-11eb-98b4-e547a8d689bf.png)

copy src\ui\*.* target\release\src\ui\*.*
copy src\ui\*.* target\debug\src\ui\*.*

**Comment by albertoVieiraNeto** [comment]
hi, copied the files and indeed works, but how can i get rid of the console? the ideal would be just the windows to be open.

platform: windows
