### ISSUE TITLE
Some complaints from `systemd` and `namcap`

### ISSUE THREAD

**Issue by sukanka** [rustdesk/rustdesk#540]
**Describe the bug you encountered:**
First, `systemd` complains about the unit service.
```
> systemctl status rustdesk.service
/usr/lib/systemd/system/rustdesk.service:9: PIDFile= references a path below legacy directory /var/run/, updating /var/run/rustdesk.pid → /run/rustdesk.pid; please update the unit file accordingly.
```
This line should be changed
https://github.com/rustdesk/rustdesk/blob/85a2a7cd4452502d16c10edf1ba81573f215ec7c/rustdesk.service#L9
to
```
PIDFile=/run/rustdesk.pid
```

Besides, `namcap` complains about the dependencies (**Only on arch and arch derived distributions**)
Please reconsider the dependencies.
```
rustdesk W: Dependency libxcb included but already satisfied
rustdesk W: Dependency libxfixes included but already satisfied
rustdesk W: Dependency included and not needed ('alsa-lib')
rustdesk W: Dependency included and not needed ('pulseaudio')
rustdesk W: Dependency included and not needed ('ttf-arphic-uming')
rustdesk W: Dependency included and not needed ('python-pip')
rustdesk W: Dependency included and not needed ('curl')
```

BTW, the file `/usr/share/rustdesk/files/pynput_service.py` should be put into `/usr/share/rustdesk/pynput_service.py`,
and `python-pynput` should be added as a dependency, instead of installing it via `sudo pip` in `postinstall`
...

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**
via aur package [rustdesk-bin](https://aur.archlinux.org/packages/rustdesk-bin), but these issues also occur in the officially released package.

---

**RustDesk version and environment**
1.1.9

**Comment by rustdesk** [comment]
Thanks

**Comment by ieugen** [comment]
Also encountered this on Debian:
```
[Vi iun 24 08:03:52 2022] systemd[1]: /etc/systemd/system/rustdesk.service:9: PIDFile= references a path below legacy directory /var/run/, updating /var/run/rustdesk.pid → /run/rustdesk.pid; please update the uni>
[Vi iun 24 08:03:52 2022] systemd[1]
```

**Comment by rustdesk** [comment]
@fufesou take a note

**Comment by fufesou** [comment]
> @fufesou take a note

Ok. I'll change the scripts on the next PR.

**Comment by dolphinoracle** [comment]
the systemd service file should go into /usr/lib/systemd/system.   the location under /etc/systemd prevents systemctl service masks from operating on the rundesk.service file should the user wish to do that.

**Comment by rustdesk** [comment]
@fufesou ensure old one can be removed.
