### ISSUE TITLE
When I connect to a PC and access a virtual machine (VirtualBox) on that PC, the keyboard repeats the letters pressed

### ISSUE THREAD

**Issue by LuisCarbone** [rustdesk/rustdesk#5400]
### Bug Description

That same, when I connect to a PC and access a virtual machine (VirtualBox) of that PC, the keyboard repeats the letters pressed

### How to Reproduce

-

### Expected Behavior

-

### Operating system(s) on local side and remote side

win 10

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

-

**Comment by rustdesk** [comment]
try new version.
