### ISSUE TITLE
ability to switch UI Language in this version

### ISSUE THREAD

**Issue by Dunkelicht** [rustdesk/rustdesk#541]
Many thanks for the project!  and congratulations on shipping server source code!

Please consider to enable UI language via settings, remote user maybe in different region and I need switch language for me and them.

Thank you all! 
 
Stay safe!

**Comment by rustdesk** [comment]
Will be in. the migration. 
https://github.com/rustdesk/rustdesk/discussions/533

**Comment by elki00** [comment]
> Will be in the migration. #533

Ok thank you

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/541

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/c745bf41114b46dd69f3b854a72a6fa262fc3cfd

**Comment by Dunkelicht** [comment]
Please consider do some tiny updates with log enabled, a prestable nightly stable version is advised, this could collect some log for you. We are waiting for a UI changed version for a long time.

Please do consider.

**Comment by grummbeer** [comment]
> Please consider do some tiny updates with log enabled, a prestable nightly stable version is advised, this could collect some log for you.

I am sure they are considering such thinks but just not ready for them yet.

Do you have tried the nightly build? https://github.com/rustdesk/rustdesk/releases/tag/nightly

There is a switch to change the UI language.

![rustdesk-settings-ui-language](https://user-images.githubusercontent.com/67791701/213861232-95e37319-f233-4eca-808b-a966189a1eeb.png)

Ticket can be closed, right?

**Comment by elki00** [comment]
Yeah it can be closed, thank you
