### ISSUE TITLE
Cannot connect to RustDesk Pro server with Sciter

### ISSUE THREAD

**Issue by it-boerner** [rustdesk/rustdesk#5410]
### Bug Description

With the Sciter version (1.2.2) a connection to the RustDeskPro server cannot be established.

I also tested this with the other versions (1.2.1) and it's the same result.

A login to the address book is also not possible.

An excerpt from the log file:

[2023-08-16 09:48:01.124412 +02:00] INFO [src\core_main.rs:158] main start args:[]
[2023-08-16 09:48:01.129368 +02:00] INFO [src\server.rs:409] server not started (will try to start): Das System kann die angegebene Datei nicht finden. (os error 2)
[2023-08-16 09:48:01.137650 +02:00] DEBUG [src\ui.rs:65] Found dll:C:\Users\XXX\AppData\Local\rustdesk\sciter.dll, 
 Ok(())
[2023-08-16 09:48:01.148314 +02:00] INFO [src\ipc.rs:279] Started ipc server at path: \\.\pipe\RustDesk\query
[2023-08-16 09:48:01.155120 +02:00] DEBUG [libs\hbb_common\src\config.rs:434] Configuration path: C:\Users\XXX\AppData\Roaming\RustDesk\config\RustDesk2.toml
[2023-08-16 09:48:01.157321 +02:00] INFO [src\rendezvous_mediator.rs:114] start rendezvous mediator of XXX
[2023-08-16 09:48:01.157524 +02:00] INFO [src\common.rs:560] Testing nat ...
[2023-08-16 09:48:01.160362 +02:00] INFO [src\rendezvous_mediator.rs:519] Direct server listening on: Some(Ok([::]:21118))
[2023-08-16 09:48:01.231731 +02:00] DEBUG [libs\hbb_common\src\config.rs:434] Configuration path: C:\Users\XXX\AppData\Roaming\RustDesk\config\RustDesk_local.toml
[2023-08-16 09:48:01.232598 +02:00] DEBUG [libs\hbb_common\src\config.rs:434] Configuration path: C:\Users\XXX\AppData\Roaming\RustDesk\config\RustDesk.toml
[2023-08-16 09:48:01.238119 +02:00] DEBUG [libs\hbb_common\src\config.rs:434] Configuration path: C:\Users\XXX\AppData\Roaming\RustDesk\config\RustDesk_default.toml
[2023-08-16 09:48:01.321306 +02:00] ERROR [src\common.rs:543] test nat: Failed to connect to XXX:21116
[2023-08-16 09:48:01.321585 +02:00] DEBUG [libs\hbb_common\src\udp.rs:35] Receive buf size of udp 0.0.0.0:0: Ok(65536)
[2023-08-16 09:48:01.677929 +02:00] ERROR [libs\hbb_common\src\platform\windows.rs:71] PdhAddCounterA failed: 0xC0000BB8
[2023-08-16 09:48:02.329523 +02:00] DEBUG [libs\hbb_common\src\config.rs:434] Configuration path: C:\Users\XXX\AppData\Roaming\RustDesk\config\RustDesk_default.toml
[2023-08-16 09:48:04.205762 +02:00] DEBUG [libs\hbb_common\src\udp.rs:35] Receive buf size of udp 0.0.0.0:0: Ok(65536)
[2023-08-16 09:48:19.570322 +02:00] INFO [src\server\input_service.rs:564] fix_key_down_timeout_at_exit

### How to Reproduce

Try connecting with Sciter, it won't work.

Also it doesn't work with my OpenSource server.

### Expected Behavior

.

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.2.2

### Screenshots

![rustdesk_sciter](https://github.com/rustdesk/rustdesk/assets/118393600/f30fc633-6556-4be8-8eff-ffcc633a719a)

**Comment by dinger1986** [comment]
is your server on 1.1.9 @rustdesk ?

**Comment by rustdesk** [comment]
I always use the latest.

**Comment by rustdesk** [comment]
BTW, we won't invest time on improving Sciter version. All dev are on Flutter version.

**Comment by dinger1986** [comment]
> BTW, we won't invest time on improving Sciter version. All dev are on Flutter version.

thats fair enough, we should add that to the docs, Ill add it to my list!

**Comment by it-boerner** [comment]
Ok, then we don't need to deal with the topic any further :)

Focus on the latest version.

I noticed some performance issues with 1.2.2. It is slow acting and the compounds are also slow acting

**Comment by rustdesk** [comment]
> I noticed some performance issues with 1.2.2. It is slow acting and the compounds are also slow acting

Can you give more details?

**Comment by it-boerner** [comment]
When I start the 1.2.2 client, it seemed very slow to open. Then I established a connection and the transmission also seemed very slow.

I cannot define where the problem lies exactly. Is there a setting somewhere that specifies a transfer rate between clients?

**Comment by it-boerner** [comment]
https://github.com/rustdesk/rustdesk/assets/118393600/4afa6e39-d19c-4761-81db-58e57cd5affe

you can see in the video that everything reacts very slowly and sluggishly.

I use the current 1.2.2 (nightly)

**Comment by rustdesk** [comment]
This is wierd. 1.2.1 is smooth on the same machine?

**Comment by it-boerner** [comment]
yes, the other machine runs 1.2.1 as a client and mine runs 1.2.2 (nightly)

**Comment by rustdesk** [comment]
sluggishly on main window?

**Comment by it-boerner** [comment]
no, in the main application everything is smooth and normal. The settings can also be opened normally and quickly

**Comment by it-boerner** [comment]
It's very weird. It doesn't run smoothly on my computer with Windows 11 and 32GB of RAM and Nvidia graphics card

It runs smoothly on a Windows 10, virtual computer with 8 GB of RAM

**Comment by rustdesk** [comment]
can you try out this？ restart the gui after turn it on.

![1692186383544](https://github.com/rustdesk/rustdesk/assets/71636191/643cca7a-dec0-4bc2-a466-9270c034fc6c)

**Comment by rustdesk** [comment]
reboot may also help you.

**Comment by rustdesk** [comment]
I reproduced the issue.

**Comment by it-boerner** [comment]
Perfect, so the problem wasn't mine :)

**Comment by rustdesk** [comment]
It is random, I can not reproduce again, i do not know how I reproduced it. :(

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
@it-boerner 1.2.2 keeps slow on the machine?

**Comment by it-boerner** [comment]
I found that as soon as I install a new version of 1.2.2 and then start the client everything is very slow.

If I close the client completely and restart, then everything works normally.

**Comment by rustdesk** [comment]
The whole OS is slow?

**Comment by it-boerner** [comment]
No, it's just the RustDesk client

**Comment by dignow** [comment]
@it-boerner Hi, can you please try this build? https://github.com/dignow/rustdesk/releases/tag/tmp
I've reverted some changes recently.

**Comment by it-boerner** [comment]
Currently I also have an error with the address book that this error message comes up

![RustDesk_Adressbuch](https://github.com/rustdesk/rustdesk/assets/118393600/f1ae313a-f456-4722-a037-5ea30ec792e7)

**Comment by it-boerner** [comment]
> @it-boernerHallo, kannst du bitte diesen Build ausprobieren? https://github.com/dignow/rustdesk/releases/tag/tmp Ich habe kürzlich einige Änderungen rückgängig gemacht.

@dignow The problem persists.

With this new version, even restarting the entire program does not help. Everything stays slow.

**Comment by it-boerner** [comment]
https://github.com/rustdesk/rustdesk/assets/118393600/540c7073-b6e7-4d57-9c3b-f80ac84ab20b

**Comment by rustdesk** [comment]
1.2.1 is fast now on this machine?

**Comment by rustdesk** [comment]
@it-boerner only the menu is slow? Is it slow when you control the remote machine in the connection widnow?

**Comment by it-boerner** [comment]
@rustdesk Unfortunately I can no longer test 1.2.1 because I can no longer get a network connection to my server. I can only establish a successful connection to my RustDesk server with 1.2.2.

**Comment by it-boerner** [comment]
> @it-boernerNur das Menü ist langsam? Ist es langsam, wenn Sie den Remote-Computer im Verbindungsfenster steuern?

@rustdesk Yes, correct, the connection builds up a bit slowly and the menu is very slow and sluggish

**Comment by dignow** [comment]
@it-boerner It seems that there will be a long pause at the resolutions action, but not others.

**Comment by rustdesk** [comment]
No, All menu items are slow in my test yesterday.

**Comment by it-boerner** [comment]
> @it-boernerEs scheint, dass es bei der Aktion „Auflösungen“ und „Codec“ eine lange Pause geben wird, bei anderen jedoch nicht.

@dignow  But this problem always occurs with the 1.2.2 with all clients. No matter what resolution and the entire menu is very slow and sluggish.

However, if I completely quit RustDesk and restarted, then it was fast.

**Comment by it-boerner** [comment]
> Nein, in meinem Test gestern waren alle Menüpunkte langsam.

This is also the case with the tested version of "dignow"

**Comment by rustdesk** [comment]
Let me build a version for you, it may solve the problem.

**Comment by rustdesk** [comment]
Yes, it looks very wierd.

**Comment by it-boerner** [comment]
> Ja, es sieht sehr seltsam aus. In 1.2.2 ändert sich in diesem Teil nichts im Vergleich zu 1.2.1.

@rustdesk  nevertheless the question remains why the connection with 1.2.1 is no longer possible.

I'm using version 1.1.9 on my RustDeskPro server

could it be because of that?

**Comment by rustdesk** [comment]
The menu sluggish seems related to https://github.com/rustdesk/rustdesk/pull/5334 @sahilyeole  though it looks like rediculous. @fufesou will revert it back and build a version for test.

**Comment by rustdesk** [comment]
> > Ja, es sieht sehr seltsam aus. In 1.2.2 ändert sich in diesem Teil nichts im Vergleich zu 1.2.1.
> 
> @rustdesk nevertheless the question remains why the connection with 1.2.1 is no longer possible.
> 
> I'm using version 1.1.9 on my RustDeskPro server
> 
> could it be because of that?

1.2.2 does fix something related to connection establishment about "waiting for image..". Maybe it is related.

**Comment by dignow** [comment]
@it-boerner  Hi, can you please try this build? To check if the menu still has the issue. Thx

https://github.com/dignow/rustdesk/releases/download/nightly/rustdesk-1.2.2-x86_64.exe

**Comment by it-boerner** [comment]
@rustdesk @dignow 

I completely restarted my computer and the problem is still there. The connection is established very slowly and the menu is very sluggish.

**Comment by dignow** [comment]
@it-boerner Thanks. Can you please set 
```
custom-rendezvous-server = '47.108.130.3:32113'
```
and try Version 1.2.1 or 1.2.0 again?

**Comment by rustdesk** [comment]
> and try Version 1.2.1 or 1.2.0 again?

@it-boerner this is important for us, We have to figure out which version of this problem starts to occur. Please connect to me. 1 004 383 741

**Comment by it-boerner** [comment]
@rustdesk 

I can only connect to you with version 1.2.2 and a password is required

**Comment by rustdesk** [comment]
Thanks for your coorperation. We will build serveral versions between 1.2.1 and 1.2.2 nightly. Hope we can find which version exactly has the problem。

**Comment by dignow** [comment]
@it-boerner Thanks for your help.

There're many build here https://github.com/dignow/rustdesk/releases/tag/tmp .

Can you also help to find out from which version this problem occurs?

**Comment by dignow** [comment]
>  https://github.com/dignow/rustdesk/releases/tag/tmp 

@it-boerner No need to test these builds any more. The reason is found now.

**Comment by it-boerner** [comment]
sorry for the delay but i couldn't test it further as i was away for work.

But I'm glad they were able to find the bug :)

**Comment by rustdesk** [comment]
@it-boerner https://github.com/rustdesk/rustdesk/releases/tag/nightly please try out. works on our side now.

**Comment by it-boerner** [comment]
> @it-boerner https://github.com/rustdesk/rustdesk/releases/tag/nightly please try out. works on our side now.

Now it works perfectly and everything runs smoothly.

But after installing the current version (nightly) I always get this error message from the address book.

![image](https://github.com/rustdesk/rustdesk/assets/118393600/90ca74a6-0482-43a5-ad89-5d2d5284d896)

**Comment by rustdesk** [comment]
Make sure you are running the latest Pro 1.1.9.

**Comment by it-boerner** [comment]
> Make sure you are running the latest Pro 1.1.9.

@rustdesk  I'm using 1.1.9 of the RustDeskPro server

**Comment by rustdesk** [comment]
When did you download and install?

**Comment by it-boerner** [comment]
> When did you download and install?

@rustdesk 

I got an update script from dinger1986

#!/bin/bash

echo -e "Stopping Services"
sudo systemctl stop rustdesk-hbbs.service
sudo systemctl stop rustdesk-hbbr.service
sleep 20
rm -rf /var/lib/rustdesk-server/static

echo -e "Getting Update"

wget https://github.com/rustdesk/rustdesk-server-pro/releases/download/1.1.9/rustdesk-server-linux-amd64.tar.gz
tar -xf rustdesk-server-linux-amd64.tar.gz
mv amd64/static /var/lib/rustdesk-server/
sudo mv amd64/hbbr /usr/bin/
sudo mv amd64/hbbs /usr/bin/
rm -rf amd64/
rm -rf rustdesk-server-linux-amd64.tar.gz

sudo chmod +x /usr/bin/hbbs
sudo chmod +x /usr/bin/hbbr

echo -e "Starting Services"

sudo systemctl start rustdesk-hbbs.service
sudo systemctl start rustdesk-hbbr.service

while ! [[ $CHECK_RUSTDESK_READY ]]; do
  CHECK_RUSTDESK_READY=$(sudo systemctl status rustdesk-hbbr.service | grep "Active: active (running)")
  echo -ne "RustDesk Relay not ready yet...${NC}\n"
  sleep 3
done

echo -e "Updates are complete"

**Comment by rustdesk** [comment]
Anyway, try update again. Old 1.1.9 did have the problem.

**Comment by it-boerner** [comment]
![image](https://github.com/rustdesk/rustdesk/assets/118393600/695df626-23ef-46f7-9d86-0256cee4e740)

but I also always get the error that the RustDesk Relay is not ready

**Comment by rustdesk** [comment]
Ignore this.

**Comment by rustdesk** [comment]
> but I also always get the error that the RustDesk Relay is not ready

@dinger1986

**Comment by dinger1986** [comment]
That’s a loop in the script to check if the service is running before going on to the next part of the script

**Comment by it-boerner** [comment]
Ok, I just did an update and the error in the address book is gone.

Is it intended that the passwords are copied among the clients?

Can the settings be locked by password in the future?

**Comment by rustdesk** [comment]
> Is it intended that the passwords are copied among the clients?
> 
> Can the settings be locked by password in the future?

Not get you, :(

**Comment by it-boerner** [comment]
> Not get you, :(

@rustdesk 

I use the client with the address book on two computers and in the future on my iPhone. Are the passwords also synchronized accordingly?

Can the settings be password protected from the client and not just via the UAC?

**Comment by rustdesk** [comment]
> Can the settings be password protected from the client and not just via the UAC?

I did have this idea, but this is not in our priority.

**Comment by rustdesk** [comment]
password in addressbook are synced.

**Comment by it-boerner** [comment]
> password in addressbook are synced in this version 1.2.2.

@rustdesk 

Perfect.

I noticed the following error.

When I create a tag in the address book and the name has a space, two tags are created

Also, I can select multiple tags, which doesn't make sense or logically

**Comment by rustdesk** [comment]
> When I create a tag in the address book and the name has a space, two tags are created

<img width="260" alt="f08937b65723570f0cb8de34e06a48d" src="https://github.com/rustdesk/rustdesk/assets/71636191/16bbbb7b-401f-4d97-b412-b7e1584e1fbd">

> Also, I can select multiple tags, which doesn't make sense or logically

I will listening to more voices about this.
