### ISSUE TITLE
Android TV crashes after successful connection

### ISSUE THREAD

**Issue by YWAwentm** [rustdesk/rustdesk#5421]
### Bug Description

Android TV crashes after successful connection

### How to Reproduce

Android TV crashes after successful connection

### Expected Behavior

Android TV crashes after successful connection

### Operating system(s) on local side and remote side

Android 11

### RustDesk Version(s) on local side and remote side

1.2.1

### Screenshots

Android TV crashes after successful connection

### Additional Context

Android TV crashes after successful connection

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893
