### ISSUE TITLE
Mouse movement at edge of screen(s) causes rustdesk client to crash

### ISSUE THREAD

**Issue by KosiehBarter** [rustdesk/rustdesk#5429]
#### Simple description
RustDesk binary (rustdesk) crashes when user moves mouse cursor either near edge or crosses edge of screen.

#### Detailed description
  RustDesk binary crashes when user moves or crosses edge of a client's window inside a GNU/Linux-based operating system.
  Windows -> Linux connection is fine and stable.
  I have performed our tests with a friend while testing RustDesk, as he was experiencing crashes.
  My first attempt was to execute the binary directly from CLI, for observation. Logfile is output from my first run.

Basically, client crashes when cursor crosses or bumps into edge of a screen. More details on attached video below, as it is difficult to explain issue by word.

My attempt to run the client with -v (as verbose) mode has no effect on output from CLI.

#### Both installations are done using standard release of *.deb package (apt install ./package.deb).

This issue may extend issue located here: https://github.com/rustdesk/rustdesk/issues/4997

Logs:
Please, see attached logfile.
[rustdesk_error.txt](https://github.com/rustdesk/rustdesk/files/12373985/rustdesk_error.txt)

### How to Reproduce

  - Run rustdesk client from CLI from linux-powered machine
  - connect to either Windows or Linux machine.
  - Move cursor near any edge:
      - top
      - bottom
      - left
      - right

### Expected Behavior

rustdesk binary runs stable on GNU/Linux-based operating system

### Operating system(s) on local side and remote side

Linux -> any

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

[2023-08-18 01-03-42.webm](https://github.com/rustdesk/rustdesk/assets/12064772/259ae829-10e2-485b-b228-12764373cd8b)

This file shows behavior of rustdesk while moving cursor both inside remote physical and local physical edges of screen.

## Environment(s):
  Computer 1:
    - multi-monitor:
      number of displays: 4
    Operating system: Windows 10
    winver: 19045.3324

  Computer 2:
    Virtual or physical: Virtual
    Operating System: Debian 11.3
    XORG: xserver-xorg-core 2:1.20.11-1+deb11u1
    Desktop Environment: LXDE
    Kernel (uname -a): Linux <redacted> 5.10.0-15-amd64 1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux
 
  Computer 3:
    Virtual or physical: Physical - Netbook
    Operating system: Lubuntu 22.04.3 (LTS)
    XORG: xserver-xorg-core 2:21.1.4-2ubuntu1.7~22.04.1
    Desktop Environment: LXDE

  Computer 4:
    Virtual or physical: Physical - Desktop
    number of displays: 3
    Operating system: WIndows 10
    
    
### Notes by friend:
It is very complicated if you have client's screen physical size smaller than the destination one. It crashes every time you move mouse pointer at the edge of a screen.

**Comment by rustdesk** [comment]
Thanks

@fufesou

**Comment by rustdesk** [comment]
close as fix merged
