### ISSUE TITLE
No Audio Transmission on Windows 7 in RustDesk Versions 1.2.0 to 1.2.2

### ISSUE THREAD

**Issue by canyue7897** [rustdesk/rustdesk#5452]
### Bug Description

In RustDesk versions 1.2.0 through 1.2.2, audio transmission is not functional on Windows 7. Despite installing the VCable virtual sound card, which allowed audio transmission in prior versions, the feature does not work in the mentioned versions.

### How to Reproduce

Install RustDesk versions 1.2.0, 1.2.1, or 1.2.2 on a Windows 7 system.
Attempt to initiate an audio transmission session.
Observe that audio is not transmitted, despite the presence of VCable virtual sound card.

### Expected Behavior

①When using RustDesk versions 1.2.0 to 1.2.2 on Windows 7 with the VCable virtual sound card installed, audio transmission should function properly, just as it did in RustDesk version 1.1.9.
②In RustDesk versions 1.2.0 to 1.2.2 on Windows 7, audio transmission should be possible without relying on virtual sound cards. Alternatively, like AnyDesk, the software could include a built-in recording device to capture all sound card audio for transmission.

### Operating system(s) on local side and remote side

Windows 7-> Windows 7

### RustDesk Version(s) on local side and remote side

1.2.0-1.2.2

### Screenshots

No

### Additional Context

In RustDesk version 1.1.9, audio transmission on Windows 7 was functional after installing the VCable virtual sound card. However, starting from version 1.2.0, this feature seems to have broken, rendering audio transmission non-operational. This limitation forces users to revert to version 1.1.9 to maintain audio transmission functionality on Windows 7. Addressing this issue by exploring options such as direct audio transmission or introducing a built-in recording device, similar to AnyDesk, in future versions would be highly appreciated. Thank you for your attention to this matter.

**Comment by rustdesk** [comment]
#763

**Comment by TODO4EVER** [comment]
Hello, do you mind sharing how did you install it in the first place ? I can't install it on windows 7, 1.1.9 juts doesn't do anything when installing, and 1.2.2 results in this error 

https://i.imgur.com/7cAwhw2.png
