### ISSUE TITLE
Crash upon connecting on Debian

### ISSUE THREAD

**Issue by willmcginnis** [rustdesk/rustdesk#5457]
### Bug Description

Using AppImage from the nightly release from 3 days ago
`SHA1(Downloads/rustdesk-1.2.2-x86_64.AppImage)= 5cdb16c4674df5443938c47e87b6d4c8ddc737ee`

I get intermittent crashes on Kubuntu but on Debian in a VMware Fusion VM it crashes right after connecting.

After the crash from attempting to connect, the ID and computer is still successfully saved in the connections list and double clicking attempts the connection again, but then it also crashes

```(rustdesk:1479): GdkPixbuf-CRITICAL **: 20:37:35.776: gdk_pixbuf_copy: assertion                                                                                       'GDK_IS_PIXBUF (pixbuf)' failed                                                                                                                                      

(rustdesk:1479): Gdk-CRITICAL **: 20:37:35.776: gdk_cursor_new_from_pixbuf: asse                                                                                    rtion 'GDK_IS_PIXBUF (pixbuf)' failed                                                                                                                                 
terminate called after throwing an instance of 'std::logic_error'                                                                                                     
  what():  basic_string::_M_construct null not valid                                                                                                                  
Aborted    
```

### How to Reproduce

Using openbox on debian in a vmware fusion VM to a Windows 10 client running the rustdesk nightly. Initial connect putting in an ID and password, then also double clicking on a past connection (if the password was set to be remembered).

### Expected Behavior

Initial connection and double-clicking a past connection shouldn't crash.

### Operating system(s) on local side and remote side

Debian 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.2

### Screenshots

<img width="1052" alt="Screen Shot 2023-08-20 at 8 45 57 PM" src="https://github.com/rustdesk/rustdesk/assets/40506393/1a11cc32-8470-43cf-98e5-4785aff1f0d6">

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/5229

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4844#issuecomment-2294765194

**Comment by jpVm5jYYRE1VIKL** [comment]
Listen You have even gdb dump already. Why just not to fix this stupid error ?

**Comment by jvschiavo** [comment]
> Listen You have even gdb dump already. Why just not to fix this stupid error ?

Is it trivial to do so?
