### ISSUE TITLE
Hosts disappear from address book when including tags they don't belong in

### ISSUE THREAD

**Issue by yaroz** [rustdesk/rustdesk#5467]
### Bug Description

I have added a "Servers" tag to servers, "Workstations" to desktop workstations, "Mobile" to mobile workstations.  If I want to display all workstations, I would normally click on both tags in other apps, like Anydesk.

### How to Reproduce

In the address book, I click on the tag that I know that contain the clients that I want.  If I add in another tag, the list of clients disappears.  Any clients that are tagged with both of the tags still show up.

### Expected Behavior

If I have Client A tagged with #workstations, and Client B tagged with #mobile, I would expect both of them to show up if I have both tags selected.

### Operating system(s) on local side and remote side

Windows 11 -> Ubuntu/docker

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.1.9

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/20463573/a7a3df6d-d643-4d70-b4a2-4c99c7b38a4a)
![image](https://github.com/rustdesk/rustdesk/assets/20463573/2708e1ee-11c4-406f-9eb6-a78fa437d87e)

**Comment by rustdesk** [comment]
close as fix merged
