### ISSUE TITLE
Lowercase and uppercase characters don't work

### ISSUE THREAD

**Issue by heyDaino** [rustdesk/rustdesk#5472]
### Bug Description

Lowercase and uppercase characters don't work

### How to Reproduce

-

### Expected Behavior

Try to use bloc maiusc but nothing, it doesn't work

### Operating system(s) on local side and remote side

Windows 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.2

### Screenshots

-

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/5255
