### ISSUE TITLE
--get-id not working in Version 1.2.2

### ISSUE THREAD

**Issue by k1ee** [rustdesk/rustdesk#5479]
### Bug Description

rustdesk.exe --get-id is not working with Client Versiion 1.2.2

### How to Reproduce

cd C:\Program Files\RustDesk
rustdesk.exe --get-id

### Expected Behavior

Previously the ID were copied to clipboard

### Operating system(s) on local side and remote side

Windows 10/11

### RustDesk Version(s) on local side and remote side

1.2.2

### Screenshots

none

**Comment by rustdesk** [comment]
revert back to old style.

https://github.com/rustdesk/rustdesk/blob/9b542f7653e24745345386d42c42edf00fe18e1e/src/core_main.rs#L270

**Comment by dinger1986** [comment]
`rustdesk.exe --get-id | more` on windows or `rustdesk --get-id` should work on any other platforms
