### ISSUE TITLE
Vertical screen problem

### ISSUE THREAD

**Issue by curisj** [rustdesk/rustdesk#548]
If the remote controlled computer screen is a vertical screen on the hardware (such as a win tablet device), even if the desktop rotates 90 degrees, the picture seen at the control end is still horizontal.

![SharedScreenshot](https://user-images.githubusercontent.com/11458545/168848570-32c568a8-2151-4319-87ba-153fb42830a4.jpg)

**Comment by rustdesk** [comment]
Not same with https://github.com/rustdesk/rustdesk/issues/269?

**Comment by rustdesk** [comment]
He said work the 1.1.9, https://github.com/rustdesk/rustdesk/issues/269#issuecomment-1055142124. Not sure about what difference between your case and his?

**Comment by curisj** [comment]
Problem solved. Works fine with the new 119 version. Thx!

**Comment by curisj** [comment]
> > Problem solved. Works fine with the new 119 version. Thx!
> 
> Wondering if you can give us a Star as support of our project if RustDesk helps you. Thanks!

Ofcouse！
