### ISSUE TITLE
Can't connect to server after upgrading to 1.2.2

### ISSUE THREAD

**Issue by yaroz** [rustdesk/rustdesk#5488]
### Bug Description

We recently purchased the pro package, and upgraded our clients and servers to 1.2.2.  Prior to upgrading, we would connect, then we would have to press the lightning bolt button to get it to bring up the screen, but now we can't even do that.  This seems to only be an issue on one server, a physical Windows Server 2008r2 (which we're in the process of replacing).  It does not affect another Windows Server 2008r2 server that we have, which is a virtual.

### How to Reproduce

Connect to the server, and it sits at the following screen:

![image](https://github.com/rustdesk/rustdesk/assets/20463573/6900291f-ad15-4713-8d29-263823a1fbd0)

### Expected Behavior

Either be able to click on the lightning bolt button to display the screen, or display the screen

### Operating system(s) on local side and remote side

Ubuntu/Windows10/Windows11 -> Windows Server 2008r2

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.2

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/20463573/6900291f-ad15-4713-8d29-263823a1fbd0)

**Comment by rustdesk** [comment]
Please be stick to old version for 2008. We can hardly solve problem for this old version. Very sorry.

**Comment by rustdesk** [comment]
> press the lightning bolt button to get it to bring up the screen

What does this mean?

**Comment by rustdesk** [comment]
How about 1.2.1 -> 1.2.2?

**Comment by rustdesk** [comment]
> I had to do the ctrl-alt-del button (lightning bolt) in the older version. Now, I can't click on that button.
> 
> >

Do you mean you could click on the lightning bolt while there was "waiting for image" dialog in 1.2.1?

**Comment by yaroz** [comment]
in 1.1.9 I could do that.  I skipped right to 1.2.2 from 1.1.9 after we bought the pro server license

**Comment by rustdesk** [comment]
You are genius, how you can find this trick.

**Comment by yaroz** [comment]
> You are genius, how you can find this trick.

My co-worker found it.

**Comment by rustdesk** [comment]
You do not need to try 1.2.1, they have the same behavior for this case. @fufesou will make a change to allow you click on the button while waiting for image. It will be ready tomorrow.

**Comment by rustdesk** [comment]
@yaroz I have a quick fix, https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.3-x86_64.exe. could you try it out by right clicking on the tab as below to send ctl-alt-del?

![image](https://github.com/rustdesk/rustdesk/assets/71636191/6055c6c0-2070-4b87-8438-c285eb2c80e8)

**Comment by rustdesk** [comment]
BTW, this menu has a bug, it disappear after several secons with doing nothing. @fufesou please take care of it.
