### ISSUE TITLE
no sound transmission any more

### ISSUE THREAD

**Issue by 000Chris000** [rustdesk/rustdesk#5492]
### Bug Description

Hello,
after updating to RustDesk 1.2.1 or 1.2.2, I can no longer hear any sound from the remote PC. 
Is there a way to fix the error?

### How to Reproduce

The problem is constant.

### Expected Behavior

a sound transmission from a remote PC.

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.2.1 and 1.2.2

### Screenshots

-

**Comment by heyDaino** [comment]
Same

**Comment by rustdesk** [comment]
#3762

**Comment by rustdesk** [comment]
@21pages

**Comment by 21pages** [comment]
The old version is 1.1.9 or  1.2.0? 
Could you try https://github.com/rustdesk/rustdesk/releases/tag/1.2.0 if the old version is 1.1.9?

**Comment by ChicoSir** [comment]
At present, the Mac is connected to the Mac, and the system 13.6 RustDesk version 1.2.4 has no sound. Even if using Black Hole 2 ch, it is still the same. From win to win, there is normal sound.

**Comment by 21pages** [comment]
mac control win works, win control mac not.
