### ISSUE TITLE
Why does a 1.2.x remote endpoint change its password every time a 1.2.x local user logs off from a session?

### ISSUE THREAD

**Issue by kozman1000** [rustdesk/rustdesk#5497]
### Bug Description

In a 1.1.9 > 1.1.9 scenario, one could could connect, save the password, and subsequently re-connect the saved session at a later time because the endpoints password would stay static (read: not change). In a 1.2.x > 1.2.x scenario, one could connect, save the password, and subsequently re-connect the saved session at a later time but the remote endpoint's password will have changed once the 1.2.x user logs off the endpoint.

### How to Reproduce

Have a scenario where a 1.2.x source machine is connecting to a 1.2.x remote endpoint. The remote endpoint's password will change to something new every time a user logs off.

### Expected Behavior

As was the case with a saved 1.1.9 endpoint / session, the 1.2.x remote endpoint's password should stay static and not change when a user logs off or disconnects.

### Operating system(s) on local side and remote side

Windows 10 x64

### RustDesk Version(s) on local side and remote side

1.2.2 > 1.2.2

### Screenshots

It's easily reproduced and has been present since 1.2.0.

**Comment by 21pages** [comment]
Please set permanent password, one-time password changed each connection is expected.
![1692841941961](https://github.com/rustdesk/rustdesk/assets/14891774/648ff7c8-b8b3-4c5b-bf9b-3e6d4de7b581)
