### ISSUE TITLE
Thank you for contributing such a beautiful software

### ISSUE THREAD

**Issue by zhorsex** [rustdesk/rustdesk#55]
Thank you for contributing such a beautiful software. Can I add a server version that supports raspberry pie? Raspberry pie seems to be more suitable for building low-cost servers.

**Comment by rustdesk** [comment]
But I do not have it

**Comment by lrq3000** [comment]
Since this software is written in Rust and it's running a Debian Linux OS, if you can install Rust then I guess you likely can compile an agent (what you mean by server I guess) and run it with little to no modifications.

**Comment by rustdesk** [comment]
Try out [raspberry-armhf.deb](https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-raspberry-armhf.deb) please.
