### ISSUE TITLE
1.2.2 version of Android controls Android input method too sensitive to use input method （android -> android)

### ISSUE THREAD

**Issue by as886944123** [rustdesk/rustdesk#5515]
### Bug Description

1.2.2 version of Android control. Android input method is too sensitive to remotely control another phone using input method. For example, when inputting the English letter q with input method, it will display 2 qs. It is too sensitive

### How to Reproduce

1.2.2 version of Android control. Android input method is too sensitive to remotely control another phone using input method. For example, when inputting the English letter q with input method, it will display 2 qs. It is too sensitive

### Expected Behavior

1.2.2 version of Android control. Android input method is too sensitive to remotely control another phone using input method. For example, when inputting the English letter q with input method, it will display 2 qs. It is too sensitive

### Operating system(s) on local side and remote side

Android Control Android

### RustDesk Version(s) on local side and remote side

Android Control Android

### Screenshots

![1](https://github.com/rustdesk/rustdesk/assets/58317138/657fba64-6991-4986-aca4-b3158ff872e1)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by as886944123** [comment]
1.2.0 32-bit main control 1.2.2 64 bit normal

**Comment by as886944123** [comment]
1.2.2 64 bit main control 1.2.2 64 bit cannot use input method

**Comment by rustdesk** [comment]
arm32?

**Comment by as886944123** [comment]
1.2.2 64 bit main control 1.2.2 64 bit cannot use input method

1.2.0 32-bit main control 1.2.2 64 bit normal use input method

**Comment by as886944123** [comment]
1.2.2 64 bit main control 1.2.2 64 bit cannot use input method

1.2.0 32-bit main control 1.2.2 64 bit normal use input method


The input method can be used, but it is too sensitive. For example, if there are two qs in the input q

**Comment by as886944123** [comment]
1.2.2 64 bit main control 1.2.2 64 bit cannot use input method

1.2.0 32-bit main control 1.2.2 64 bit normal use input method


The input method can be used, but it is too sensitive. For example, if there are two qs in the input q


Clicking on q will bring up 2
