### ISSUE TITLE
Error starting / install  rustdesk.exe > 1.1.9 if Password set in 1.1.9 contains special characters

### ISSUE THREAD

**Issue by JSoko** [rustdesk/rustdesk#5518]
### Bug Description

Attempting to upgrade from Rustdesk Windows Client 1.1.9 to V1.2.n will fail if the password set in Rustdesk 1.1.9 contains german Umlauts (special characters).

If you change the password in Rustdesk 1.1.9 so it doesn't contain german umlauts, starting Rustdesk.exe V1.2.2 works like expected...

### How to Reproduce

Install Rustdesk Windows 1.1.9
Set an own Password witch contains german Umlauts p.e. äöüß
Start Rustdesk.exe V 1.2.2 or 1.2.1
The window doesn't open

If you try it on cmd you get the following Errormsg:```

thread '<unnamed>' panicked at 'byte index 2 is not a char boundary; it is inside 'ü' (bytes 1..3) of `1ü2345678684E-U3`', libs\hbb_common\src\password_security.rs:108:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected Behavior

It should work or give an Alert, that Passwords mustn't contain special charakters...

### Operating system(s) on local side and remote side

Windows 11 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.1.8

### Screenshots

![grafik](https://github.com/rustdesk/rustdesk/assets/5583290/13fa3cee-5825-42ba-b6b4-74ebc068ccc8)


### Additional Context

_No response_

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
Thanks for reporting this.

**Comment by rustdesk** [comment]
@JSoko can you try out the nightly build (1.2.3)? we put a fix and the build is ready now. https://github.com/rustdesk/rustdesk/releases/nightly

**Comment by rustdesk** [comment]
close since fix merged

**Comment by JSoko** [comment]
> @JSoko can you try out the nightly build (1.2.3)? we put a fix and the build is ready now. https://github.com/rustdesk/rustdesk/releases/nightly

Yes, works like it should. Thank You :-)
