### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by wanghu572** [rustdesk/rustdesk#554]
部分电脑中（不连接互联网的），ID框右上角的菜单点开后，大部分打勾项的“√“会自动消失，点开ID设置的对话框，对话框闪一下会自动消失，其他能弹出的对话框，都会闪一下立马消失

或者不知道有没有和其他软件冲突，目前两台电脑都是这个情况

**Comment by rustdesk** [comment]
We are going to rewrite UI, current UI sdk (Sciter) has big compatiblity issue.
