### ISSUE TITLE
No sound from the controlled end of the mobile phone simulator

### ISSUE THREAD

**Issue by ImmortalD** [rustdesk/rustdesk#5548]
### Bug Description

Install Rustdesk on the mobile emulator, and then connect to the emulator using the phone. Only the screen has no sound, and all permissions have been enabled

![image](https://github.com/rustdesk/rustdesk/assets/29126429/a50d1e92-b0d6-4013-a607-42a973b416e4)

### How to Reproduce

Install Rustdesk on the mobile emulator, and then connect to the emulator using your phone

### Expected Behavior

With screen and sound sharing

### Operating system(s) on local side and remote side

小米9手机 -> mumu模拟器

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.2

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/29126429/f82bb73b-b012-4ff0-a5e8-9d26485d1e7e)

![image](https://github.com/rustdesk/rustdesk/assets/29126429/34f1b514-e810-4ba2-bd8a-8b6816fe202f)

**Comment by rustdesk** [comment]
Sorry, we have no resource to fix this case.

**Comment by rustdesk** [comment]
But we welcome PR.
