### ISSUE TITLE
<CTRL>-<ALT>-<DEL> doesn't work anymore

### ISSUE THREAD

**Issue by kuerbis42** [rustdesk/rustdesk#5549]
### Bug Description

After installation RUSTDEK as client, the functionallity "send <CRTL>-<ALT>-<DEL>" for other software products doesn't work anymore

### How to Reproduce

install RADMIN, connect with RADMIN and use `<CRTL>-<ALT>-<F12> to send  <CRTL>-<ALT>-<DEL>`
Install RUSTDESK, <CRTL>-<ALT>-<F12>  doesn't work anymore, even "mouse-click"-SendKey (similar to RUSTDESK) doesn't work

### Expected Behavior

the `<C>-<A>-<D>`-hook should word for all products which are in need of this

### Operating system(s) on local side and remote side

W10, W11

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

Sorry, I can't send a video and/or screenshot from "keypressing"

### Additional Context

I use RADMIN and RUSTDESK

Normally with RADMIN, you can use `< CTRL > - <ALT> - <F12> to send < CTRL > - <ALT> - <DEL>` to the remote PC.
This works well until installing RUSTDESK.
After that, nor `< CTRL > - <ALT> - < DEL> neither < CTRL > - <ALT> - <F12>` works anymore with RADMIN.
After deinstalling RUSTDESK it doesn't came to work again.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367, but you can ref 

https://github.com/rustdesk/rustdesk/issues/5255
https://github.com/rustdesk/rustdesk/issues/4367

Almost all report about keyboard lately are false report.

**Comment by kuerbis42** [comment]
> Almost all report about keyboard lately are false report.
In this case I've two machines with this issue.
It's reproducible

**Comment by Hoo-Joseph** [comment]
> ### Bug Description
> After installation RUSTDEK as client, the functionallity "send --~" for other software products doesn't work anymore~
> 
> ### How to Reproduce
> install RADMIN, connect with RADMIN and use `<CRTL>-<ALT>-<F12> to send <CRTL>-<ALT>-<DEL>` Install RUSTDESK, -- doesn't work anymore, even "mouse-click"-SendKey (similar to RUSTDESK) doesn't work
> 
> ### Expected Behavior
> the `<C>-<A>-<D>`-hook should word for all products which are in need of this
> 
> ### Operating system(s) on local side and remote side
> W10, W11
> 
> ### RustDesk Version(s) on local side and remote side
> 1.1.9
> 
> ### Screenshots
> Sorry, I can't send a video and/or screenshot from "keypressing"
> 
> ### Additional Context
> I use RADMIN and RUSTDESK
> 
> Normally with RADMIN, you can use `< CTRL > - <ALT> - <F12> to send < CTRL > - <ALT> - <DEL>` to the remote PC. This works well until installing RUSTDESK. After that, nor `< CTRL > - <ALT> - < DEL> neither < CTRL > - <ALT> - <F12>` works anymore with RADMIN. After deinstalling RUSTDESK it doesn't came to work again.

I experienced the same problems after installing the RustDesk Version: 1.2.3-1. Is there any way to solve it?
