### ISSUE TITLE
iOS App doesn’t connect to API server

### ISSUE THREAD

**Issue by Mouxy** [rustdesk/rustdesk#5553]
### Bug Description

The iOS app doesn’t connect to the api server when using https. Used the script to install the pro version that installs Nginx. 

Tried with 21114 and 443 but the error is the same

### How to Reproduce

Fill in the details in the iOS app
Can’t connect
Remove http or https and when I try to login the error “failed to access …” appears 

### Expected Behavior

Being able to login

### Operating system(s) on local side and remote side

iOS

### RustDesk Version(s) on local side and remote side

1.1.10

### Screenshots

![IMG_1810](https://github.com/rustdesk/rustdesk/assets/642149/343b03fc-f51a-4189-bf54-8ad0cf939520)

**Comment by rustdesk** [comment]
https://twitter.com/rustdesk/status/1696828016934965522

**Comment by dinger1986** [comment]
thats correct, docs say needs to be v1.2 or above, new version is being tested

**Comment by rustdesk** [comment]
@dinger1986 please test the https when testflight ready please.
