### ISSUE TITLE
arch中tigervnc+xfce桌面情况下配置depth=16会导致双屏显示错误。

### ISSUE THREAD

**Issue by sunshe35** [rustdesk/rustdesk#5559]
### Bug Description

我使用的是archlinux，内核6.2.16-4-pve(pve下lxc容器)，环境配置是tigervnc+xfce配置，具体配置参考https://wiki.archlinuxcn.org/wiki/TigerVNC
通过tigervnc启动xfce桌面。

正常情况下，rustdesk可以正常运行。

但是我修改了depthc参数，就出现了问题。
```bash
# ~/.vnc/config
session=xfce
geometry=1920x1080
alwaysshared
depth=16
```

他出现了两个图，效果如下（实际上是四个图，上面是两个相同的图，而且颜色有很大的差异）。
![image](https://github.com/rustdesk/rustdesk/assets/16757906/2673e80a-1ac5-40c2-94a8-508c87bb3f8e)

我试了下depth=24参数，发现可以正常显示。

我用depth=16参数在远程vnc的时候不会显示颜色失真，但是rustdesk会出问题，详见上面。
不是depth或depth=24参数在rustdesk显示正常，vnc远程的时候会显示失真（要调整高质量模式可以显示正常）。

### How to Reproduce

参考系统配置。
https://wiki.archlinuxcn.org/wiki/TigerVNC
修改参数如下：

```bash
# ~/.vnc/config
session=xfce
geometry=1920x1080
alwaysshared
depth=16
```

### Expected Behavior

希望修复depth=16这个bug。

### Operating system(s) on local side and remote side

linux：6.2.16-4-pve

### RustDesk Version(s) on local side and remote side

1.2.2->1.2.2

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/16757906/2ce50a71-229b-4c49-9e90-85fb2c6a5798)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
