### ISSUE TITLE
@wwjabc since you have added libvpx/opus ...

### ISSUE THREAD

**Issue by wwjabc** [rustdesk/rustdesk#556]
@wwjabc since you have added libvpx/opus compilation steps, I will remove the baidu download links. and I will also replace ubuntu18.04_rootfs.tar.gz with an official image. Wondering if this link https://github.com/ikwzm/ZynqMP-FPGA-Ubuntu18.04-Ultra96/blob/master/doc/build/ubuntu18.04-rootfs.md is correct?

_Originally posted by @rustdesk in https://github.com/rustdesk/rustdesk/issues/175#issuecomment-1130140801_

This link is not correct, it is running on AARCH64.

**Comment by rustdesk** [comment]
Did you try out docker?

**Comment by wwjabc** [comment]
If I say I'm Linux Xiaobai, do you believe it? 😂 I'm still learning how to use docker. I wanted to try it before, but the foundation was too poor to succeed. I didn't even succeed in building qemu...
In fact, I had been trying to figure out the whole process for almost nine months when I wanted to run RustDesk remotely on my ZYNQ board.
![image](https://user-images.githubusercontent.com/102203060/169193437-f0435d2f-c4ae-4958-982f-54b41d3db09b.png)

**Comment by wwjabc** [comment]
> Did you try out docker?

I'll try.

**Comment by rustdesk** [comment]
> nine months

Respect!!!!!

**Comment by wwjabc** [comment]
> > qemu
> 
> docker is much easier than your current solution. 

The main reason is that you don't have an ARMHF platform. 
I will try to compile with Docker, but it will take time. It could take months...  :)

**Comment by rustdesk** [comment]
> take months

Take easy, :)

**Comment by wwjabc** [comment]
> > take months
> 
> Take easy, :)

In fact, I have an idea. I don't know the feasibility. If you want to run rustdesk on armhf, aarch64 or other embedded systems, the requirements for audio and video are not high, or even only SSH communication is required. However, I'm not good at learning rust. It's too difficult to modify the source code of rustdesk (I tried to modify it, but failed). However, as the "father of rustdesk", it may be relatively easy for you to change, delete unnecessary files and code, and many platforms can be easily compiled and passed.It can be used as a branch of rustdesk.
Of course, this is a bit excessive. I hope you can understand our mood of running rustdesk in embedded system.
事实上，我有一想法不知道可行性怎么样。对于想将rustdesk运行在armhf、aarch64、或者其他嵌入式系统，对音视频的要求并不高，甚至仅仅需要SSH通信即可。奈何我的rust学艺不精，想修改rustdesk源码太难了（我尝试过修改，失败告终）。但是你作为“rustdesk之父”，可能你改起来相对容易，删除不必要的文件和代码，很多平台就很容易编译通过了。可以作为rustdesk的一个分支。
当然，这是有点过分的要求了，希望你能理解我们想在嵌入式系统中跑rustdesk的心情。

**Comment by rustdesk** [comment]
Actually we already have, not maintained for a long time. `cargo run --features cli`, I guess there will compile errors.

**Comment by wwjabc** [comment]
I tried that command, and all dependencies still need to be downloaded and compiled. Some dependencies are not well compiled on some Ubuntu.

**Comment by Heap-Hop** [comment]
@wwjabc Good job!
and a tip,maybe useful for you.
both libvpx and libopus could be installed from apt.(tested on my raspberry pi4 arm32)
`
apt install libvpx-dev libopus-dev
`
you will find them in /usr/lib/arm-linux-gnueabihf.
you can also try to use rust crate 'pkg_config' at 'build.rs'.good luck!

**Comment by wwjabc** [comment]
> @wwjabc Good job! and a tip,maybe useful for you. both libvpx and libopus could be installed from apt.(tested on my raspberry pi4 arm32) `apt install libvpx-dev libopus-dev` you will find them in /usr/lib/arm-linux-gnueabihf. you can also try to use rust crate 'pkg_config' at 'build.rs'.good luck!

I'll try and feed back the results.

**Comment by rustdesk** [comment]
> apt install libvpx-dev libopus-dev

But our build.rs only searches in $VCPKT_ROOT

**Comment by wwjabc** [comment]
> > apt install libvpx-dev libopus-dev
> 
> But our build.rs only searches in $VCPKT_ROOT

Should it be possible to modify the scanning path?

**Comment by rustdesk** [comment]
Have to modify build.rs

**Comment by Heap-Hop** [comment]
> apt install libvpx-dev libopus-dev

I remember that libvpx/libopus can't be built from vcpkg(arm).
Embedded arm is too weak, building them ourselves will waste much time.
So fetching the pre-build bins from offical apt source maybe a better way(just for embedded).

The perfect way is 100% cross-complie, it is also an interesting job.

**Comment by Heap-Hop** [comment]
You can just move the bins from `/usr/lib/arm-linux-gnueabihf` to  $VCPKT_ROOT, `pkg_config` crate is optional.

**Comment by wwjabc** [comment]
It took me more than two hours to complete the compilation, which is equivalent to watching a large film. :)
I tried docker today, but I still didn't succeed! The display cannot be started.

**Comment by rustdesk** [comment]
If you only want tcp tunnelling, there are a lot of choice, e.g. frp.

**Comment by wwjabc** [comment]
> You can just move the bins from `/usr/lib/arm-linux-gnueabihf` to $VCPKT_ROOT, `pkg_config` crate is optional.
I'm going to try that.

**Comment by Heap-Hop** [comment]
> It took me more than two hours to complete the compilation

yes, bad experience......

**Comment by rustdesk** [comment]
> The display cannot be started

Can not run GUI on docker.

**Comment by wwjabc** [comment]
> If you only want tcp tunnelling, there are a lot of choice, e.g. frp.

I think your TCP hole is more reliable. Many tests are perfect and do not consume server traffic.

**Comment by wwjabc** [comment]
> The perfect way is 100% cross-complie, it is also an interesting job.

I've tried cross compiling and failed many times.

**Comment by wwjabc** [comment]
> The perfect way is 100% cross-complie, it is also an interesting job.

In fact, I also want to cross compile on PC or even install virtual machine to compile. Cortex-A9 CPU is really too slow.

**Comment by rustdesk** [comment]
The only good one is building iOS and android on PC.

**Comment by wwjabc** [comment]
> > apt install libvpx-dev libopus-dev
> 
> I remember that libvpx/libopus can't be built from vcpkg(arm). Embedded arm is too weak, building them ourselves will waste much time. So fetching the pre-build bins from offical apt source maybe a better way(just for embedded).
> 
By the way, can I use apt to install libyuv?

**Comment by wwjabc** [comment]
I didn't find a command like apt install libyuv-dev

**Comment by rustdesk** [comment]
> libyuv-dev

https://linux-packages.com/ubuntu-jammy-jellyfish/package/libyuv-dev

**Comment by wwjabc** [comment]
root@pynq:~# apt install libyuv-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libyuv-dev

**Comment by rustdesk** [comment]
Depends on distro version.

**Comment by wwjabc** [comment]
Forget it, I'd better copy the file

**Comment by wwjabc** [comment]
root@pynq:/usr/lib/arm-linux-gnueabihf# ls libvpx*
libvpx.a  libvpx.so  libvpx.so.5  libvpx.so.5.0  libvpx.so.5.0.0
root@pynq:/usr/lib/arm-linux-gnueabihf# ls libopus*
libopus.a  libopus.so  libopus.so.0  libopus.so.0.5.2
root@pynq:/usr/lib/arm-linux-gnueabihf#

These files can be found.

**Comment by Heap-Hop** [comment]
> I didn't find a command like apt install libyuv-dev

I only found this for armhf:
https://mirrors-i.tuna.tsinghua.edu.cn/raspberry-pi-os/raspbian/pool/main/liby/libyuv/

just a mirror, I dont know where is real original.

**Comment by wwjabc** [comment]
/usr/bin/ld: /root/rustdesk/target/release/deps/libmagnum_opus-1adbcc8978ad3a0d.rlib(decode_core.o): relocation R_ARM_THM_MOVW_ABS_NC against `__stack_chk_guard@@GLIBC_2.4' can not be used when making a shared object; recompile with -fPIC
          /usr/bin/ld: /root/rustdesk/target/release/deps/libmagnum_opus-1adbcc8978ad3a0d.rlib(NLSF_encode.o): relocation R_ARM_THM_MOVW_ABS_NC against `__stack_chk_guard@@GLIBC_2.4' can not be used when making a shared object; recompile with -fPIC
          /usr/bin/ld: /root/rustdesk/target/release/deps/libmagnum_opus-1adbcc8978ad3a0d.rlib(NLSF_del_dec_quant.o): relocation R_ARM_THM_MOVW_ABS_NC against `__stack_chk_guard@@GLIBC_2.4' can not be used when making a shared object; recompile with -fPIC
          /root/rustdesk/target/release/deps/libmagnum_opus-1adbcc8978ad3a0d.rlib(celt.o): In function `.LANCHOR0':
          (.rodata+0x24): dangerous relocation: unsupported relocation
          (.rodata+0x28): dangerous relocation: unsupported relocation
          (.rodata+0x2c): dangerous relocation: unsupported relocation
          (.rodata+0x30): dangerous relocation: unsupported relocation
          (.rodata+0x34): dangerous relocation: unsupported relocation
          (.rodata+0x38): dangerous relocation: unsupported relocation
          (.rodata+0x3c): dangerous relocation: unsupported relocation
          (.rodata+0x40): dangerous relocation: unsupported relocation
          /usr/bin/ld: /root/rustdesk/target/release/deps/libmagnum_opus-1adbcc8978ad3a0d.rlib(opus_decoder.o)(.text+0x9a): unresolvable R_ARM_THM_MOVW_ABS_NC relocation against symbol `__stack_chk_guard@@GLIBC_2.4'
          /usr/bin/ld: final link failed: Symbol needs debug section which does not exist
          collect2: error: ld returned 1 exit status
          

error: could not compile `rustdesk` due to previous error
root@pynq:~/rustdesk

Finally failed...

**Comment by wwjabc** [comment]
> Did you try out docker?

I thought about it. I can share my device with you for remote operation. You can realize docker compilation.

**Comment by wwjabc** [comment]
root@pynq:~/ docker info
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
root@pynq:~/ systemctl start docker
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
root@pynq:~/ systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2022-05-22 08:47:36 UTC; 7s ago
     Docs: https://docs.docker.com
  Process: 24690 ExecStart=/usr/bin/dockerd -H unix:// (code=exited, status=1/FAILURE)
 Main PID: 24690 (code=exited, status=1/FAILURE)

May 22 08:47:34 pynq systemd[1]: Failed to start Docker Application Container Engine.
May 22 08:47:36 pynq systemd[1]: docker.service: Service hold-off time over, scheduling restart.
May 22 08:47:36 pynq systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
May 22 08:47:36 pynq systemd[1]: Stopped Docker Application Container Engine.
May 22 08:47:36 pynq systemd[1]: docker.service: Start request repeated too quickly.
May 22 08:47:36 pynq systemd[1]: docker.service: Failed with result 'exit-code'.
May 22 08:47:36 pynq systemd[1]: Failed to start Docker Application Container Engine.
May 22 08:47:39 pynq systemd[1]: docker.service: Start request repeated too quickly.
May 22 08:47:39 pynq systemd[1]: docker.service: Failed with result 'exit-code'.
May 22 08:47:39 pynq systemd[1]: Failed to start Docker Application Container Engine.
root@pynq:~/

'docker 'has been installed, but failed to start.

**Comment by rustdesk** [comment]
Try out [raspberry-armhf.deb](https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-raspberry-armhf.deb) please.

**Comment by piaojin** [comment]
@wwjabc  大佬试过编译iOS端的么？😂
