### ISSUE TITLE
The monitor window appears only for a second and then disappears on RaspberryPi.

### ISSUE THREAD

**Issue by goodluck1982** [rustdesk/rustdesk#5565]
### Bug Description

When I connect to RaspberryPi, the monitor windows like the following appears only for a very short time, abount 1-2 seconds, and then it disappears. And I cannot find it further. Then I cannot know whether a connection is alive. Besides, even if I send a message to RaspberryPi via rustdesk, nothing is received and displayed on RaspberryPi. 
![2023-09-01_01-43](https://github.com/rustdesk/rustdesk/assets/48718961/635b57e6-095a-4241-b6ad-a8f68f3a2e69)

### How to Reproduce

I don't know whether this can be reproduced because I have only one RaspberryPi device. 

### Expected Behavior

I can find the monitor window on RaspberryPi and know that I'm controlled remotely.

### Operating system(s) on local side and remote side

win11 / ubuntu 22.04 -> raspberry pi,    Android -> raspberry pi

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.2,   1.2.2 -> 1.2.2

### Screenshots

![Peek 2023-09-01 01-55](https://github.com/rustdesk/rustdesk/assets/48718961/b5ad9baf-ca59-4394-9b53-c0af32daf2f6)

### Additional Context

rustdesk-1.2.2-aarch64.deb is installed on Raspberry Pi
and the system information is as follows.

$lsb_release -a
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```
$uname -a
```
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

**Comment by rustdesk** [comment]
close as tracked by https://github.com/rustdesk/rustdesk/issues/3565. This can be community driven only, we have no resource to work on PI.
