### ISSUE TITLE
Native window decorations

### ISSUE THREAD

**Issue by tio-trom** [rustdesk/rustdesk#557]
I think would be great if this would allow for window native decorations. In Linux this is important for functionality and design perspective. I am talking about the window that is opened after the connection is made. That does not have it. It uses a Windows-like top bar. Thank you for this software!

**Comment by Arsen6331** [comment]
This would definitely be nice. I'm using a tiling window manager and it's really weird when one of my windows has a title bar.

**Comment by MrKinau** [comment]
I would really appreciate an option to use the native window decorations.

**Comment by cmikovits** [comment]
Hello.

Is this issue "completed" or "wontfix"?

**Comment by ridicolos** [comment]
Would love to see this be implemented for linux!

@cmikovits unfortunately I think that this won't be implemented... as the "wontfix" suggest
