### ISSUE TITLE
Can notes be added to each connected end on the cell phone？

### ISSUE THREAD

**Issue by FMYC2015** [rustdesk/rustdesk#558]
Can notes be added to each connected end on the cell phone?

**Comment by rustdesk** [comment]
@21pages Do not find on mobile.

https://github.com/rustdesk/rustdesk/blob/e80a2d899941a6fd29f32ab7dd539b6d220cf64e/src/ui/header.tis#L213

https://github.com/rustdesk/rustdesk/blob/12f3691645bac1279a9868b7373d9ae31b8b5eab/flutter/lib/desktop/widgets/remote_toolbar.dart#L700

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/blob/a0bca81e050a18e9f48fcbd6f605b00931802585/flutter/lib/common/widgets/toolbar.dart#L113
