### ISSUE TITLE
"Waiting" window appears upon any connection to port 21118 when direct ip is enabled

### ISSUE THREAD

**Issue by GameParrot** [rustdesk/rustdesk#5586]
### Bug Description

When a connection to port 21118 that is not rustdesk occurs the "Waiting" window will show up. This means that port scanning can result in the window showing which can be annoying.

### How to Reproduce

1. Enable direct ip
2. Run `nc 127.0.0.1 21118`

### Expected Behavior

The window should not appear because it isnt rustdesk making the connection

### Operating system(s) on local side and remote side

linux

### RustDesk Version(s) on local side and remote side

1.2.2

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/85067619/0e4f8a29-3b2b-41fa-b916-45f17ed0aee8)

### Additional Context

This also happens when using https://www.yougetsignal.com/tools/open-ports/ on port 21118

**Comment by rustdesk** [comment]
1.2.3 changed the behavior.
