### ISSUE TITLE
Unlock security settings does nothing

### ISSUE THREAD

**Issue by jcelerier** [rustdesk/rustdesk#5588]
### Bug Description

Unlock security settings does nothing and I cannot change security parameters on my local computer.

### How to Reproduce

- I launch rustdesk
- I go on the security tab
- I click on "Unlock security settings"
- Nothing happens and I cannot change said settings

### Expected Behavior

- I launch rustdesk
- I go on the security tab
- I can change the settings

### Operating system(s) on local side and remote side

It's a local issue, no remote is involved. local = Arch Linux 

### RustDesk Version(s) on local side and remote side

1.2.2 Build Date: 2023-08-22 02:11

### Screenshots

https://github.com/rustdesk/rustdesk/assets/2772730/fa297fad-7913-49e4-8014-ba472f0a26cd

### Additional Context

window manager: i3

**Comment by rustdesk** [comment]
duplicate: https://github.com/rustdesk/rustdesk/issues/2756

**Comment by rustdesk** [comment]
Can you run below to show me the output?

```
pkexec  echo 1; echo $?;
```

**Comment by jcelerier** [comment]
```
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/usr/bin/echo 1' as the super user
Authenticating as: jcelerier
Password: 
polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
==== AUTHENTICATION FAILED ====
Error executing command as another user: Not authorized

This incident has been reported.
[1]    366600 exit 127   pkexec echo 1
```

I don't use policykit on my systems, is there a way to disable the check if it is not installed?

**Comment by rustdesk** [comment]
Can not, because this case also return 127. https://github.com/rustdesk/rustdesk/issues/5205#issuecomment-1658059657s

**Comment by rustdesk** [comment]
I got a solution. Could you try this? and tell me output.

```
time pkexec  echo 1; echo $?;
```

**Comment by jcelerier** [comment]
it's stuck on my password prompt (which won't be visible at all if I run the app not from a terminal).
I think you should run 

     pkexec --disable-internal-agent

and skip this check if it returns 

      Error executing command as another user: No authentication agent found.

or even better, use the D-Bus API (https://www.freedesktop.org/software/polkit/docs/latest/eggdbus-interface-org.freedesktop.PolicyKit1.Authority.html)

**Comment by DullUnicorn** [comment]
> I don't use policykit on my systems, is there a way to disable the check if it is not installed?

As a workaround, you can temporarily override the `pkexec` executable, for example, with something like this:
```sh
cd "$(mktemp -dt fake-pkexec.XXXXXXXXXX)"
printf '#!/usr/bin/env sh\nreturn 0' > pkexec
chmod +x pkexec
env PATH="$PWD:$PATH" rustdesk
```
