### ISSUE TITLE
trackpad scrolling is so fast when i'm running rustdesk at Parallels Windows 11 arm on apple silicon

### ISSUE THREAD

**Issue by myshytf** [rustdesk/rustdesk#5590]
### Bug Description

I have been using RustDesk on Windows 11 Arm running on Parallels on an Apple Silicon Mac. I started using it from version 1.1.9, and I find it has several advantages compared to TeamViewer, so I've been using them concurrently. While I've experienced some inconveniences, the biggest issue is that the scrolling speed with the trackpad is too fast. Despite trying various settings, the scrolling speed issue remains unresolved. As a result, I've had to use the method of manually dragging to scroll. Is there a way to resolve this issue?

The resolution of Windows 11 Arm is set to 1800 x 1169. The issue persists even when I changed the connecting side's version to 1.2.3.

ps, i already tried to use scriter version. but still experience not fixed.

### How to Reproduce

scroll when connecting to Windows OS from RustDesk at Macbook's trackpad on Parallels's Windows 11 ARM

### Expected Behavior

optimizing scrolling sensitivity like teamviewer remote desktop.

### Operating system(s) on local side and remote side

Windows 11 Arm -> Windows

### RustDesk Version(s) on local side and remote side

1.1.9->1.2.3

### Screenshots

https://github.com/rustdesk/rustdesk/assets/9619163/a2a220ca-96d0-4a96-8f40-747358497b72

I just want to make sure that scrolling behavior is exactly same when i'm scrolling using rustdesk and teamviewer.

**Comment by rustdesk** [comment]
1.2.3 both please.

**Comment by myshytf** [comment]
> 1.2.3 both please.

i tried 1.2.3 both but still experience same issue.

**Comment by rustdesk** [comment]
How about if not in Parallels?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2655

**Comment by myshytf** [comment]
> #2655



> How about if not in Parallels?

I've encountered issues using RustDesk on Parallels. While scrolling works smoothly on macOS, I experience problems with other functionalities, particularly with Korean typing. I'm seeking solutions to enhance the scrolling experience.

thx!

**Comment by rustdesk** [comment]
Sorry, Fixing for Parallels is the lowest priority for us.

**Comment by rustdesk** [comment]
> I experience problems with other functionalities, particularly with Korean typing

https://github.com/rustdesk/rustdesk/issues/5027

**Comment by myshytf** [comment]
> Sorry, fixing for Parallels is the lowest priority for us.

okay :) no problem. not really matter because of i can use page up and down to scroll so that there is not much incovenience. but i hope someday you can fix the issue!

thx

**Comment by fufesou** [comment]
> I have been using RustDesk on Windows 11 Arm running on Parallels on an Apple Silicon Mac. 

Windows 11 Arm may use the sciter version, which is not fixed. 
Only fluter has handled the tachpad scrolling events correctly for now.

**Comment by rustdesk** [comment]
we do not have windows arm version, neither sciter and flutter.

**Comment by myshytf** [comment]
> > I have been using RustDesk on Windows 11 Arm running on Parallels on an Apple Silicon Mac.
> 
> Windows 11 Arm may use the sciter version, which is not fixed. Only fluter has handled the tachpad scrolling events correctly for now.

do i have to use flutter version for both windows?

**Comment by myshytf** [comment]
> we do not have windows arm version, neither sciter and flutter.

i'm running x86_sciter version on windows arm. there is an emulator that can runs program that built by another architecture.

**Comment by rustdesk** [comment]
use flutter as controlling side is enought. as controlled side, both ok.

**Comment by myshytf** [comment]
tried to use flutter(rustdesk-1.2.3-x86_64.exe) but still have same issue.

https://github.com/rustdesk/rustdesk/assets/9619163/8546ab39-bfe4-4989-abc6-6fb22f00c924

**Comment by rustdesk** [comment]
So this is maybe specific to Parallels
