### ISSUE TITLE
Connection reset by peer - every time I try to enable audio and play it on a Raspberry Pi

### ISSUE THREAD

**Issue by shankargopal** [rustdesk/rustdesk#5592]
### Bug Description

I love Rustdesk! I have just started using it on a Raspberry Pi 4.  

But I have a problem.  There was no audio being sent initially, so I tried changing Rustdesk to monitor the Analog Stereo device instead.  Every time I then tried to play audio in either Chromium or VLC, however, I would get "Connection reset by peer."  Running audio makes it impossible to connect in Rustdesk. Changing to monitoring Digital Stereo makes no difference.  The only way to connect is to either Mute audio on the Pi or not run any audio in Chromium or VLC.  

I am a Rustdesk newbie, so not sure how to diagnose these problems.  The Pi is running Pulseaudio and it makes no difference whether I set the output to Analog (AV jack) or to Digital (HDMI).
  
My client is running Debian Linux with PulseAudio.  This is the output of `uname -a` on my client:

```Linux debian 6.3.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.3.7-1 (2023-06-12) x86_64 GNU/Linux```

This is the output of `uname -a` on my Pi:

```Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux```

The client is running pulseaudio 16.1. The Pi is running pulseaudio 12.2.

### How to Reproduce

1. Install Rustdesk on a Raspberry Pi 4.  
2. Connect to Rustdesk from a Linux client.  This should work.  
3. Try to run a movie in Chromium or a song in VLC. Connection will reset.
4. Try to connect again.  Connection keep resetting or fail to connect as long as that app is open on the remote side. 

### Expected Behavior

Audio to work normally. 

### Operating system(s) on local side and remote side

Debian Linux amd64 -> Raspbian OS (details above)

### RustDesk Version(s) on local side and remote side

1.2.2 --> 1.2.2

### Screenshots

I could not get a screenshot of the "Connection reset by peer" message as it appeared too fast.

**Comment by rustdesk** [comment]
crash there somewhere with audio handling. close as tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by shankargopal** [comment]
Thank you for seeing this so swiftly! should I track the bug in #3565 then?
