### ISSUE TITLE
ipad外接键盘时,出现重复输入的情况

### ISSUE THREAD

**Issue by Solo8World** [rustdesk/rustdesk#5594]
### Bug Description

ipad上打开rustdesk,连接目标机器，通过键盘输入`ls` ，目标机器出现`lsls`。输入回车，目标机器出现两次回车

### How to Reproduce

如上，百分百复现

### Expected Behavior

应正常输入

### Operating system(s) on local side and remote side

ios->linux

### RustDesk Version(s) on local side and remote side

1.1.10->1.2.2

### Screenshots

（待补充）

### Additional Context

上述问题有人已在appStore软件评论区反馈，应该是普遍的问题。
另：ios的应用商店的版本一直没有更新，停留在1.1.10。

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4794

**Comment by rustdesk** [comment]
https://twitter.com/rustdesk/status/1696828016934965522?t=lEWnWfNI9FD-OUc81RCfIA&s=19

**Comment by Solo8World** [comment]
When is it expected to be put on the appStore? Can you give me the test version first? 
My email is ofzhuo@gmail.com ,tanks

**Comment by rustdesk** [comment]
> When is it expected to be put on the appStore? Can you give me the test version first? My email is [ofzhuo@gmail.com](mailto:ofzhuo@gmail.com) ,thanks

added
