### ISSUE TITLE
The current version 1.2.3 has obvious bugs.

### ISSUE THREAD

**Issue by zhangbo8418** [rustdesk/rustdesk#5595]
### Bug Description

See video for details.

### How to Reproduce

See video for details.

### Expected Behavior

See video for details.

### Operating system(s) on local side and remote side

MacOS Ventura1 3.2.1

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

See video for details.

https://github.com/rustdesk/rustdesk/assets/46797568/e98c5e72-eff5-48a2-91ae-bd59d83e6a97

**Comment by rustdesk** [comment]
Thanks

**Comment by dignow** [comment]
@zhangbo8418 Hi, thanks for your feedback.

But I can't get what is wrong here.

<img width="607" alt="1693800189345" src="https://github.com/rustdesk/rustdesk/assets/136106582/e81c346e-51d4-48a4-9b00-d0450efe4bc9">

**Comment by dignow** [comment]
Ok, I get it.

**Comment by zhangbo8418** [comment]
When connecting to Android, this menu will appear for a while and then disappear. After the connection is successful, you need to click the menu switch twice to open it again.

**Comment by rustdesk** [comment]
all fix have been merged, please try out later, nightly build will be ready soon.

**Comment by rustdesk** [comment]
@zhangbo8418 why do you run RustDesk on your TV? I can not understand this use scenario.

**Comment by zhangbo8418** [comment]
> @zhangbo8418 why do you run RustDesk on your TV? I can not understand this use scenario.


The TV box is also Android, it won't shut down.

**Comment by rustdesk** [comment]
Watch TV on your mac?

**Comment by zhangbo8418** [comment]
> > @zhangbo8418 why do you run RustDesk on your TV? I can not understand this use scenario.
> 
> The TV box is also Android, it won't shut down.


In the home scene, I can remotely help parents install the TV box APP, monitor the time children watch TV, etc. . . If it is an enterprise scene, you can remotely control the company's large screen, advertising machine, etc. . .
