### ISSUE TITLE
Can't install printer under mint 21.2 with rustdesk 1.2.2 installed

### ISSUE THREAD

**Issue by baboune56** [rustdesk/rustdesk#5601]
### Bug Description

Hi 
i can't install a printer driver with rustdesk installed on both remote and local machine.
I have to remove rustdesk then install the driver and end reinstall rustdesk.

Got this message error : an error occured while cups operation : "Succes"

When seach for drivers in the base.

### How to Reproduce

install a driver with application printer add a printer in linux mint

### Expected Behavior

Install printer driver through the administration panel of linux mint 21.2

### Operating system(s) on local side and remote side

linux mint 21.2

### RustDesk Version(s) on local side and remote side

1.2.2

### Screenshots

![Capture d’écran du 2023-09-04 18-04-27](https://github.com/rustdesk/rustdesk/assets/128413428/bfe32b8f-0142-431c-9b0b-dacf5ee022fb)

![Capture d’écran du 2023-09-04 18-05-34](https://github.com/rustdesk/rustdesk/assets/128413428/331c1cd6-8063-4af7-9976-09a70790cf9b)

**Comment by rustdesk** [comment]
duplicate https://github.com/rustdesk/rustdesk/issues/3129

**Comment by baboune56** [comment]
Excuse me but real the same.

Not the same version of rustdesk and version of operating system

It was working in linux mint 21.1 and rustdesk 1.2.0

Please consider reopening

Best regards.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3129#issuecomment-1705508856

**Comment by baboune56** [comment]
Sorry and thanks for your patience i haven't see that.

Maybe it will work in another release.

Thanks for your job and developing free softwares

**Comment by rustdesk** [comment]
try out the latest nightly build.
