### ISSUE TITLE
Connected waiting for image on one specific device

### ISSUE THREAD

**Issue by CineArkTP** [rustdesk/rustdesk#5608]
### Bug Description

Using a Macbook Pro 2015 to remote into a Mac Mini. It has worked fine in the past but now I get "Connected waiting for image" and nothing else happens.

### How to Reproduce

Mac mini is in a server rack. Using ID/Relay server, with an ID Server and a key.

### Expected Behavior

Should connect to the Mac mini with no issue

### Operating system(s) on local side and remote side

Mac Os catalina > Mac os Ventura

### RustDesk Version(s) on local side and remote side

1.2.2 > 1.1.9

### Screenshots

<img width="1299" alt="Screenshot 2023-09-05 at 16 05 58" src="https://github.com/rustdesk/rustdesk/assets/144146824/fe7e094b-c71b-4ca0-9640-3b32f8bc2f03">

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/5609

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/5608

**Comment by MoHara23** [comment]
Dear 

I just had same issue on a windows 10 . Trying to connect from a Windows 11 laptop to Windows 10 laptop. After searching for a solution online, nothing found. So I tried to stop and start the Rustdesk service in settings and then it worked. Give it a try.

**Comment by vinloren** [comment]
I came across the same issue today trying to remotely control a Raspberry PI5 from Windows10. Both systems running 1.3.2, if I try  controlling the Windos10 PC from the RaspberryPI5 everything is fine but on Windows the image of the RasPI desktop never comes up as shown in the above picture.

**Comment by 21pages** [comment]
@vinloren Could you try out https://github.com/21pages/rustdesk/releases/download/directx/rustdesk-1.3.5-x86_64.exe on Windows 10 as control side? If waiting for image happens, show the content of  `%appdata%\RustDesk\log\RustDesk_rCurrent.log`, remember to remove lines containing personal informations.

**Comment by vinloren** [comment]
Thanks for your attention, I will check the connection with this downloaded version and let you get the log if the problem shows up. I have to tell you though that the problem is  not there anymore as I replaced Debian 12 with Ubuntu24 in target RaspberryPi5.

**Comment by 21pages** [comment]
Okay, I want to confirm whether it is caused by hardware encoding. Can you control your RaspberryPi5 with H264/H265?

**Comment by vinloren** [comment]
Yes, the GPU hardware encoder in the Raspberry Pi5 has got hardware encoding for H. 264
