### ISSUE TITLE
ios client cannot connect to relay server/ios 客户端无法连接到中继服务器

### ISSUE THREAD

**Issue by dongmuhds** [rustdesk/rustdesk#5613]
### Bug Description

ios client cannot connect to relay server
The ios client has no relay server to fill in the content, only the ID server, connected to the prompt operationnot permitted (os error1)
I can use android, windows, can be linked, is it possible to add the ios version update
ios 客户端无法连接到中继服务器
ios 客户端没有中继服务器填写内容，只有 ID 服务器，连接后提示操作不允许（os error1），我可以使用安卓、windows，都可以链接，是否可以添加 ios 版本更新

### How to Reproduce

下载appstore版本rust，填写id服务器和公钥
输入远程id 连接
Download appstore version rust, fill in the id server and public key input remote id connection

### Expected Behavior

更新ios客户端，并解决该问题

### Operating system(s) on local side and remote side

主要是ios ios -> mac or ios -> android

### RustDesk Version(s) on local side and remote side

本地端ios1.10

### Screenshots

![](https://pic.dongmu001.top/dongmuhds/pic/main/pic/IMG_4544.jpg)
![](https://pic.dongmu001.top/dongmuhds/pic/main/pic/IMG_4545.PNG)

**Comment by rustdesk** [comment]
#763 
https://twitter.com/rustdesk/status/1696828016934965522
