### ISSUE TITLE
Remote Error No Display

### ISSUE THREAD

**Issue by byte-voyager** [rustdesk/rustdesk#5628]
### Bug Description

Debian 12 Xfce 
Rustdesk 1.2.2

It worked fine the other day.

The system desktop will never lock the screen.

Can be connected with other remote tools.

### How to Reproduce

Unable to reproduce

### Expected Behavior

-

### Operating system(s) on local side and remote side

Debian12 xfce

### RustDesk Version(s) on local side and remote side

1.2.2

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/16448666/b2e85bcb-3684-48ae-ae31-258c0ea6c286)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
