### ISSUE TITLE
No output on command line

### ISSUE THREAD

**Issue by matt-theforge** [rustdesk/rustdesk#5629]
### Bug Description

There doesn't seem to be any output from command line invocations of `rustdesk.exe` 1.2.2 on Windows 10:

```pwsh
PS C:\Program Files\RustDesk> .\rustdesk.exe --get-id
PS C:\Program Files\RustDesk> .\rustdesk.exe --password "testpw"
PS C:\Program Files\RustDesk> .\rustdesk.exe --version
PS C:\Program Files\RustDesk>
```

Setting the password this way seems to work, the output just seems to be getting lost somehow.

### How to Reproduce

Invoke `rustdesk.exe` from the command line.

### Expected Behavior

Expected to see output messages in stdout/stderr that are in https://github.com/rustdesk/rustdesk/blob/master/src/core_main.rs

### Operating system(s) on local side and remote side

Windows 10 22H2

### RustDesk Version(s) on local side and remote side

1.2.2

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/97916375/d266e0e7-5941-4fa7-8d27-72f17a3aeea3)

**Comment by rustdesk** [comment]
./rustesk xxx | cat

**Comment by matt-theforge** [comment]
`cat` is an alias for `Get-Content` in powershell, and just results in this output:
```
PS C:\Program Files\RustDesk> .\rustdesk.exe --get-id | cat
←[31;1mGet-Content: ←[31;1mThe input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.←[0m
```

`cat` is not an available command in standard Windows `cmd`, so you just get this:
```
C:\Program Files\RustDesk>rustdesk.exe --get-id | cat
'cat' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by dinger1986** [comment]
It's `| more` or `| out-host`

So `.\rustdesk.exe --password "random password" | out-host` for example
