### ISSUE TITLE
Brief crash of Rustdesk after connection (due to "nomodeset" boot option?)

### ISSUE THREAD

**Issue by aibou-kit** [rustdesk/rustdesk#5661]
### Bug Description

The Rustdesk crashes briefly after the connection.
The app reboots immediately after the crash, but no pop-up with the user's name appears.

### How to Reproduce

Connect to the remote PC which was booted with the "nomodeset" boot option.
(I think the "nomodeset" boot option causes the problem because this problem does not occur when not using "nomodeset")

### Expected Behavior

No crash of the Rustdesk

### Operating system(s) on local side and remote side

MacOS (Ventura) -> Ubuntu 22.04

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.2

### Screenshots

A cropped video of the crash

https://github.com/rustdesk/rustdesk/assets/118586514/9bbb7023-56d7-4b59-9047-4518736565ee

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
