### ISSUE TITLE
Wrong input results from Bluetooth keyboard

### ISSUE THREAD

**Issue by gloomy-lemon-debatable** [rustdesk/rustdesk#5663]
### Bug Description

Sorry for the abstract title. It would be easier to understand if you see an example. Perhaps this bug is related to the fix in issue #907.
This bug causes input failures in rare cases. However, I am affected by this bug rather frequently in my environment, so I would appreciate it if you could make the behavior the same as that of VNC.

### How to Reproduce

Below are results from keyboard test (https://en.key-test.ru/) with input via VNC or via RustDesk:

### Expected Behavior

Input: abc←↑↓→

### Operating system(s) on local side and remote side

Android13 -> Windows11

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.2

### Screenshots

via VNC:
![VNC](https://github.com/rustdesk/rustdesk/assets/91877885/93bc730c-25b1-4bf5-abb8-3c320ee743f1)

via RustDesk:
![RustDesk](https://github.com/rustdesk/rustdesk/assets/91877885/4f99e9a9-59bb-40bf-89e9-27847b544354)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367
