### ISSUE TITLE
wQHD Black Screen vs FullHD screen （netbook）

### ISSUE THREAD

**Issue by KosiehBarter** [rustdesk/rustdesk#5667]
### Bug Description

On behalf of my relative, I want to report bug with the following situation: Friend of mine owns a netbook running Debian or Lubuntu (tested both systems) with the following result:

He receives a black screen while he wants to control a wQHD display (2560x1440) from a netbook. Yet when he switches the wQHD display to a Full-HD resolution (1920x1080), display works normally, as expected.
All is controlled from a Netbook with a native resolution 1024x600

Videos attached below illustrate the difference between what is recorded on client's side (all somehow visible), yet from raw, external cell phone camera view it actually indicates no screen is visible at all.

### How to Reproduce

Netbook with native display of 1024x600:

- Have a netbook with native display of 1024x600, either running Debian or Lubuntu. Friend reports it does not matter, which system he has used.
- Attempt to connect to server: 3x monitors, 2x 1920x1080, 1x 2560x1440, Windows 10
- Note: Issue also occurs on different target setup: 4x monitors, 3x 1920x1080, 1x 2560x1440
- On main, wQHD (2560x1440) monitor, black screen appears instead of desktop

### Expected Behavior

- wQHD monitor (2560x1440) shows correctly desktop and it's contents.

### Operating system(s) on local side and remote side

Linux -> Windows

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3
Build Date: 2023-09-11 00:23 (Nightly)

### Screenshots

[c43271601-20230911235635-vp9_6679iuTI.webm](https://github.com/rustdesk/rustdesk/assets/12064772/c8e3e3c9-421a-4343-b76b-35ba50cd027f)
[VID_20230912_000717.webm](https://github.com/rustdesk/rustdesk/assets/12064772/d580205e-4882-445c-a146-4faf9a7b63f8)

### Additional Context

Also it is good to mention the target destination system is a Windows 10-running computer, having 3 independent displays, 2x Full-HD (1920x1080) and 1x 2560x1440.

I would like to add personal note, from my side:
I also have similar hardware, but given the fact it is a i386-based Intel Atom netbook (specifically Compac Mini 110c), I was not able to compile RustDesk to i386 architecture to help out with testing and to confirm (or even add details) issue from my side.

There was also my attempt to compile RustDesk to be compatible with i386 CPU, I had a missing library (*.so) that was required to compile it.

Therefore I am forced just to pass and translate friend's report from Czech to English.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by rustdesk** [comment]
Please let me know if it does work if you use another machine rather than the netbook.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by lister169126** [comment]
It works from other machine on same linux distro (in VirtualBox). I want to try if it work from netbook with bigger screen.

**Comment by lister169126** [comment]
It looks it definitely issue on my netbook bcs it doesn't work even with fullhd monitor. Maybe drivers on linux? It do a same with anydesk, but teamviewer works.
