### ISSUE TITLE
Can not type colon 

### ISSUE THREAD

**Issue by pcmodula** [rustdesk/rustdesk#567]
**Describe the bug you encountered:**
Unable to type a colon from two identical win10 desktop
...

**What did you expect to happen instead?**
The shift command does not seem to work for the colon
...

**How did you install `RustDesk`?**
Not installed, symply i run a portable version

Rustdesk-1-1-9.exe 64 bit windows portable version
---

I have a problem with ":" SHIFT + "." always shows "." instead of ":", windows italian

Work better from Windows(10) to Linux (Mint debian edition) but fail win2win with same Os, and keyboard layout.
Note if use alt+58 i obtain the semicolon, but it's just an inconvenient way out.

My keyboad scancode using IT437
49 -> onKeyUp nKey: 16 nFlags: -1070989311 (VK_SHIFT)
48 -> onKeyUp SHIFT nKey: 190 nFlags: -1070333951 (VK_OEM_PERIOD)
47 -> onChar SHIFT nKey: 58 CHR: : nFlags: 3407873
46 -> onKeyDown SHIFT nKey: 190 nFlags: 3407873 (VK_OEM_PERIOD)
45 -> onKeyDown SHIFT nKey: 16 nFlags: 2752513 (VK_SHIFT)

June 01, 2022
this problem manifests itself because I have 2 keyboard layouts loaded, of which the Italian in use as a favorite.
From the notebook to the desktop it works, but , I found another problem, the block number of the numeric keypad
is out of sync and does not allow you to execute commands of type ALT+126, also pressing a key on the numeric keypad causes the removal of the block number on the remote PC (windows or linux).
Sometimes it happens that while viewing the remote PC you can not open any program (between 2 Windows PCs on the same lan...) Same behavior with the portable version and the installed version

**Comment by rustdesk** [comment]
Thanks

**Comment by rustdesk** [comment]
The other related issue: https://github.com/rustdesk/rustdesk/issues/406#issuecomment-1132717599

**Comment by asur4s** [comment]
> SHIFT + "." always shows "." instead of ":"

Do you want to say that SHIFT + ";" always shows ";" instead of ":"? 

Other information that can be used to further reproduce(**remote machine and client machine**). For example:
- System Version
- RustDesk Version
- keyboard layout
- Screenshot
![image](https://user-images.githubusercontent.com/99897242/170304567-477e6a54-ac81-4430-82a8-3df8aac7ca97.png)


@pcmodula

**Comment by alexgorbatchev** [comment]
I have the same problem controlling mac from win. I can't type any `Shift+Num` characters, like `*&(` and so on. All other uppercase characters work fine. I have only one language in my systems.

**Comment by rustdesk** [comment]
#1547

**Comment by fufesou** [comment]
@alexgorbatchev Hi, can you please try the nightly build, with "Map mode"?
<img width="235" alt="20230104201351" src="https://user-images.githubusercontent.com/13586388/210715294-bee1c8fc-d584-4931-bf60-2a6771eb3822.png">
