### ISSUE TITLE
Client Keyboard do not work on Ubuntu20.04

### ISSUE THREAD

**Issue by vytasrgl** [rustdesk/rustdesk#5676]
### Bug Description

I failed to make keyboard work on client running Ubuntu 20.04.5 64bit on X11 (with wayland disabled).  I tried on two machines.
I can connect to same hosts from web client and keyboard works fine using web based client on same machines, so issue must be on client side.

Also reverse works fine from Win10 to Ubuntu20.04.

I tried all keyboard modes (map, legacy and translate) with no success.

If i run from teminal, the mouse event produces output however keyboard events seems to be not registered.

### How to Reproduce

Connect to any host from Ubuntu 20.04.5

### Expected Behavior

Keyboard events should work.

### Operating system(s) on local side and remote side

Ubuntu20.04 -> Ubuntu20.04, Win10

### RustDesk Version(s) on local side and remote side

1.2.2 (Also Nightly 1.2.3(sept 13)  build -> 1.2.2

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/6471519/79ff2c58-377a-417c-9e12-8d60f396b82c)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4367#issuecomment-1718750948
