### ISSUE TITLE
Keyboard will not work in client for certain locales on Linux

### ISSUE THREAD

**Issue by vytasrgl** [rustdesk/rustdesk#5688]
### Bug Description

On Ubuntu 20.04 having certain locale will disable keyboard input on client.
On my machine the locale is en_HK.UTF-8 with keyboard layout of US. 

### How to Reproduce

In terminal run:
```bash
export LC_ALL="en_HK.UTF-8"
rustdesk
```
Keyboard input wont work, while with other locales it works fine with some other locales (even if its not US):
```bash
#export LC_ALL="en_US.UTF-8"
export LC_ALL="en_NZ.UTF-8"
rustdesk
```

### Expected Behavior

Keyboard should work regardless of the user localle especially if its valid locale .

### Operating system(s) on local side and remote side

Ubuntu20.04 -> Any

### RustDesk Version(s) on local side and remote side

1.2.2 (Also Nightly 1.2.3(sept 13)  build -> 1.2.2

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/6471519/0123a64c-ddd3-49eb-87a1-6f73f87a3fd6)

### Additional Context

It seem the issue is with underlying rdev library by @fufesou and specifically this line, that will make keyboard object not created by the X11 input functions used there:
https://github.com/fufesou/rdev/blob/master/src/linux/keyboard.rs#L54
```rust
            let string = CString::new("").ok()?;
            libc::setlocale(libc::LC_ALL, string.as_ptr());
```

**Comment by rustdesk** [comment]
@fufesou

**Comment by vytasrgl** [comment]
This would solve my specific issue, and it should not effect any current fuctionality. At very least it should have the ANSI input with unsupported locales.

https://github.com/fufesou/rdev/pull/8

**Comment by rustdesk** [comment]
close as fix merged
