### ISSUE TITLE
Keyboard layout/mapping issues

### ISSUE THREAD

**Issue by dgerzo** [rustdesk/rustdesk#5692]
### Bug Description

Hello,

I am using latest Rustdesk release and I am having issues with keyboard layout/mapping. I have a MacOS client and a Windows10 host. I am using SK-QWERTY layout. The letters on the number-keys match their SK letters, however other keys give me a different letters. The SK keyboard layout on Mac looks like this:
https://cdn.shopify.com/s/files/1/0810/3669/files/slovak-mac-keyboard-layout-keyshorts_1024x1024.png

If I press the ú key, I get f instead over Rustdesk. ä gives me g (just a few examples). Furthermore, I am unable to use ' and shitft-' (for ˇ)... - I get = and % respectively...

Not sure if that makes sense.

Thanks! 

### How to Reproduce

see description

### Expected Behavior

see description

### Operating system(s) on local side and remote side

osx - windows 10

### RustDesk Version(s) on local side and remote side

1.2.2

### Screenshots

I can upload some pics upon request, but I do not consider it neccessary ATM.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/5255

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by dgerzo** [comment]
OK I will try the translation mode, however it appears I will need to update the windows10 host rustdesk as my client on macos currently offers only legacy mode. It seems like it is not possible to update RD remotely or check the installed version (the rustdesk window greys out when I click into it)
