### ISSUE TITLE
The virtualbox virtual machine in the remote windows has an input error.

### ISSUE THREAD

**Issue by kukudemajia** [rustdesk/rustdesk#5701]
### Bug Description

Remote windows input is normal, but the input in virtualbox is abnormal. Sometimes it is impossible to input, and sometimes the last letter is automatically entered repeatedly. Only after switching to windows desktop and switching back to the virtual system can I enter a few letters, and the same problem occurs again.
keyboard input：English(US)

### How to Reproduce

Local windows 11->Remote windows11--Virtualbox--Kali linux 

### Expected Behavior

The last letter is automatically entered repeatedly.

### Operating system(s) on local side and remote side

Windows11 -> Windows11 

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.9

### Screenshots

[kali-linux-2023.3-virtualbox-amd64-screen0.webm](https://github.com/rustdesk/rustdesk/assets/17118600/eedf5c2b-3ee9-4e16-be67-674a3baec254)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4357

**Comment by mishueen** [comment]
is so annoying  .... i have same issue

**Comment by zuernerd** [comment]
Same problem with VMware Workstation 19 Pro and windows guests

**Comment by konosubakonoakua** [comment]
> Same problem with VMware Workstation 19 Pro and windows guestsVMware Workstation 19 Pro 和 Windows 客户机存在同样的问题

do you mean VMware Workstation 17 pro?
