### ISSUE TITLE
Mac keyboard mapping goes crazy, thinks command-control is always pressed.

### ISSUE THREAD

**Issue by jamiegau** [rustdesk/rustdesk#5707]
### Bug Description

I am having problems controlling Mac computers.
The keyboard mapping seems to go crazy and I am not able to use the computer remotely.

For example, in a terminal, hit the "a" key and it jumps to highlight the Finder icon on the dock.
And other randomness.

Disconnecting and reconnecting can fix the issue for a short time.

Another example is hitting the f, which makes the terminal window go full screen,  (command-control-f) equivalent.

Its as if it thinks command-control is still pressed.

I am surprised I have net see a report of this bug already, its a showstopper for rustdesk on MacOS.

This happens with a Mac Or Windows machine controlling a remote Mac.

### How to Reproduce

I have no idea, it appears to be solidly problematic on all machines I updated to 1.2.2. 
I find this issue to be common on machines I try to control
I have noticed this on multiple machines I control/have upgraded.
Using my own relay server.

Was not a problem with the older version I was using everywhere.

### Expected Behavior

Keyboard maps exactly as you expect.

### Operating system(s) on local side and remote side

MacOS 13.5.2 and Windows11 to Mac 13.5.1

### RustDesk Version(s) on local side and remote side

Mac and Windows 1.2.2 to mac 1.2.2

### Screenshots

Screenshot now needed.

**Comment by jamiegau** [comment]
Note, rustdesk on the PC, I can switch to different keyboard modes.
Legacy mode and Translate mode beta, and the problem goes away,
I just noticed this.
There are no options for switching to different modes under rustdesk on a MAC.  So mac to mac, is not workable. (This is a problem for me as I use a Mac laptop, and typically I need to use this from that unit as I am out and about, and need to emergency into a machine.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by ElectroshockGuy** [comment]
I often encounter this issue as well, with uncontrollable input repeatedly pressing the same keyboard key.

**Comment by mrzcpoGit** [comment]
I also encountered this problem. I am using Windows to control a Mac. It seems like the problem is similar to having the fn key on the Mac continuously pressed without releasing it. However, when I changed the keyboard settings to the traditional mode, the problem disappeared. I also tried the Translation mode Beta, but it has another issue where it cannot recognize the command+a shortcut for selecting all. The only solution currently seems to be switching the keyboard settings to the traditional mode.

**Comment by quadbyte** [comment]
I'm also affected by this issue, which makes controlling a Mac an horrible experience.
It seems the faster I type, the faster the issue arise.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/7308

**Comment by rustdesk** [comment]
We put a fix on nightly build today, please test https://github.com/rustdesk/rustdesk/releases/tag/nightly
