### ISSUE TITLE
Input Control always need to restart after stopping service (MIUI 13)

### ISSUE THREAD

**Issue by Smorvel** [rustdesk/rustdesk#571]
When I stop RustDesk service, input control always need to re enable it for some reason. With other programs like this, no such a problem.
![Animation](https://user-images.githubusercontent.com/19754243/169583895-ff74250f-e817-47af-aed4-551382679165.gif)

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by Heap-Hop** [comment]
Yes, this is expected now, not a bug, will be improved later.
