### ISSUE TITLE
The latest RustDesk 1.2.3 version for Mac, when the Mac stops being controlled, the tray will disappear and RustDesk cannot be opened. . .

### ISSUE THREAD

**Issue by zhangbo8418** [rustdesk/rustdesk#5712]
### Bug Description

The latest RustDesk 1.2.3 version for Mac, when the Mac stops being controlled, the tray will disappear and RustDesk cannot be opened. . .

### How to Reproduce

The latest RustDesk 1.2.3 version for Mac, when the Mac stops being controlled, the tray will disappear and RustDesk cannot be opened. . .

### Expected Behavior

The latest RustDesk 1.2.3 version for Mac, when the Mac stops being controlled, the tray will disappear and RustDesk cannot be opened. . .

### Operating system(s) on local side and remote side

Windows 7-> MacOS

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

The latest RustDesk 1.2.3 version for Mac, when the Mac stops being controlled, the tray will disappear and RustDesk cannot be opened. . .

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
close as fix merged
