### ISSUE TITLE
RustDesk 1.2.3 Crash Issue on Android 13

### ISSUE THREAD

**Issue by ANOPREMIUM** [rustdesk/rustdesk#5718]
### Bug Description

RustDesk 1.2.3 Crash Issue on Android 13

Hello RustDesk Team,

I hope this message finds you well. I would like to report a critical issue I'm experiencing with RustDesk version 1.2.3 on Android 13.

Issue Description:
I have been encountering consistent crashes when using RustDesk on my Android device running Android 13. The application crashes abruptly under specific circumstances, and I believe it may be related to the screen resolution of my computer.

Details:

Device Model: SM-N9860
Android Version: Android 13
RustDesk Version: rustdesk-1.2.3-aarch64-signed.apk
Scenario:

My computer setup includes a Samsung Odyssey G9 miniLED monitor with a resolution of 5120 x 1440, although it supports up to 7680 x 2160.
When I connect to my computer at this resolution, RustDesk crashes within a minute of use.
However, when I tested RustDesk on an older computer with a resolution of 1920 x 1080, it remained stable for approximately 15 minutes without any crashes.
Remarkably, RustDesk on my iPhone remains stable even at the 5120 x 1440 resolution, showing that this issue is specific to the Android version of RustDesk.

I have recorded a short video demonstrating the crashes for your reference.
https://www.youtube.com/shorts/RqYR3TChFfA

<img width="556" alt="Snipaste_2023-09-17_11-15-02" src="https://github.com/rustdesk/rustdesk/assets/115340708/b843f100-c25c-443b-ab8c-c846f237bdfa">

<img width="256" alt="Snipaste_2023-09-17_11-16-50" src="https://github.com/rustdesk/rustdesk/assets/115340708/5c221e24-7489-49c7-8fb1-86dba1b81393">
![1693452454615](https://github.com/rustdesk/rustdesk/assets/115340708/1db9b2c7-5067-447f-8108-f67c3cc0cd8e)

I understand that this may be a complex issue, but I wanted to bring it to your attention to help improve the stability of RustDesk on Android 13.

Thank you for your attention to this matter, and please let me know if you need any additional information to investigate this issue further.

Best regards,
[A.NO]

### How to Reproduce

Launch RustDesk.
Select a remote connection.
Enter remote computer details, including IP address and connection password.
Set the remote computer's resolution to 5120 x 1440 (or relevant settings).
Initiate the remote connection.
Observe the application's behavior and record when the issue occurs, along with any relevant error messages.

### Expected Behavior

I expect RustDesk to operate stably on Android 13, regardless of the remote computer's resolution settings. The application should connect smoothly to the remote computer, provide real-time remote desktop control, and should not crash or exit unexpectedly.

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

https://github.com/rustdesk/rustdesk/assets/115340708/8f86ebc1-7be4-4034-b371-79b262b828c4

**Comment by rustdesk** [comment]
close to favor https://github.com/rustdesk/rustdesk/issues/5718
