### ISSUE TITLE
--config and --import-config do not work

### ISSUE THREAD

**Issue by ian-uson** [rustdesk/rustdesk#5740]
### Bug Description

running --config <config_string> and --import-config <config_file> dont seem to actually do the import config
The only way i seem to be able to actually import my config is by going through the ui and using the copy buffer. 

### How to Reproduce

as super user (using su), do `rustdesk --config "0nIiojI5V2aiwiIiojIpBXYiwiIiojI5FGblJnIsIyM24SNx4CO2EjLykTMiojI0N3boJye"`
or `rustdesk --import_config /home/user/Downloads/rustdesk_config` (with the contents being the config string above)

then open rustdesk as user and view the network configuration (it will still be empty)

### Expected Behavior

running the commands should load the configuration the same as using the ui

### Operating system(s) on local side and remote side

Ubuntu -> Debian

### RustDesk Version(s) on local side and remote side

1.2.2->1.2.2

### Screenshots

None

**Comment by ian-uson** [comment]
> #5637

just checked, works when followed by running rustdesk as root, but it still does not work when running rustdesk as user following setting the config as root.

**Comment by dinger1986** [comment]
Restart the service after

**Comment by ian-uson** [comment]
alright. that seems to work. thanks. i wonder why you have to restart the service. since you can run the executable itself without running the service at all (to get to the ui at least)

**Comment by dinger1986** [comment]
The service runs after install, on linux anyway you need to reload it so the settings come through to the users.

I'll get that added to the docs

**Comment by Jirvil** [comment]
I'll add this for reference if someone is studying a similar problem.
After studying the config, it becomes clear how the import works ([here](https://github.com/rustdesk/rustdesk/blob/bdc5cded221af9697eb29aa30babce75e987fcc9/src/core_main.rs#L242)).
In order for the --import-config command to work, it is necessary that:
1. The imported files **are newer** than those that already exist in user directory.
2. There should be **two files** - RustDesk.toml and RustDesk2.toml

For myself, I realized that condition (1) would be difficult to meet, and in my corporate AD environment I simply replace these two files via GPO? without --import-config

**Comment by GunnerCL** [comment]
I have done hundreds of tests of remote installation with Powershell using the WindowsAgentAIOInstall.ps1 installer and the --import-config or --config options do not work, the configurations are simply not applied, in my case I need to apply 

direct-server = 'Y'
verification-method = 'use-permanent-password' 

There should be something simpler or more direct like rustdesk.exe --config "{direct-server = 'Y'}" or something that allows listing or checking the options applied via console/commands

**Comment by pinedriley** [comment]
> I have done hundreds of tests of remote installation with Powershell using the WindowsAgentAIOInstall.ps1 installer and the --import-config or --config options do not work, the configurations are simply not applied, in my case I need to apply
> 
> direct-server = 'Y' verification-method = 'use-permanent-password'
> 
> There should be something simpler or more direct like rustdesk.exe --config "{direct-server = 'Y'}" or something that allows listing or checking the options applied via console/commands

I'm working on a new deployment and running into the same issue with the Powershell deployment.  Even if I open CMD on the machine it was just installed and call ./rustdesk.exe --config and the config string, it wont add it or show up on the server.  

Where/how did you end up adding those options?

**Comment by nosdregamon** [comment]
Having the same problem with version 1.4.0 of the client  and a freshly installed selfhosted server. 

I exported the string  from a client got a String starting with "==Q...". This String I can import into other clients. But I can't use it
in the deployment script, or using --config directly.

**Comment by pinedriley** [comment]
> Having the same problem with version 1.4.0 of the client and a freshly installed selfhosted server.
> 
> I exported the string from a client got a String starting with "==Q...". This String I can import into other clients. But I can't use it in the deployment script, or using --config directly.

So I just tried this, remove the == from the string and it seems to work.  Maybe an oversight somewhere?
Also, I can't get the permanent password to set with the --password option either.

**Comment by josbmw** [comment]
Does still not work. Tried with removing the ==, adding single quotes and double quotes around the config string, but rustdesk.exe just doens't launch.
Tested on Win 11 25H2, directly from the Program Files\RustDesk folder, both with a normal and an administrator command prompt.

Any solution?

**Comment by krblt-onur** [comment]
I’m experiencing the same issue — in an Active Directory environment, the RustDesk config does not apply to standard users.
