### ISSUE TITLE
window with Accept or Disconnect button is mostly off the screen

### ISSUE THREAD

**Issue by ocyzl** [rustdesk/rustdesk#5763]
### Bug Description

I just started using RustDesk yesterday.  The first time I connected to the remote computer, the window position was ok, but the second time, the window was almost entirely off the right side of the screen, and the person at the remote computer could not move it.

Today, I tried again, and the window was again mostly off the screen, but now he could move it, so it's not really a big problem anymore, but I figured I'd let you know anyway.

The window I'm talking about is the one in the first two screenshots [here](https://rustdesk.com/docs/en/client/windows-portable-elevation/).

The remote monitor is 1280 x 1024, if that matters.

How does RustDesk decide where to put this window?  Is there a registry entry or configuration file I could change, to make it appear in the middle of the screen in the future?

### How to Reproduce

I just click Connect on my local computer, and the window appears on the remote computer.

### Expected Behavior

The entire window should be visible.

### Operating system(s) on local side and remote side

Linux (Fedora 38) -> Windows 7

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.2

### Screenshots

Sorry, I don't have a screenshot.

**Comment by rustdesk** [comment]
#763
