### ISSUE TITLE
Using [ALT + TAB] destroys keyboard mapping

### ISSUE THREAD

**Issue by enoch85** [rustdesk/rustdesk#5778]
### Bug Description

Been using Rustdesk for a while (thank you <3) and I've noticed a strange behavior when using alt + tab to switch between my desktop and Rustdesk. It's just like the keyboard mapping is messed up and makes Rustdesk impossible to use. The only way to restore the mapping is to disconnect and reconnect.

I'm on Ubuntu 22.04 desktop (minimal) using the .deb, and the client on the other side is usually Mac or Linux, more less on Windows.

### How to Reproduce

1. Connect to a remote session from Ubuntu 22.04
2. Do alt + tab several times
3. Notice that after X amount of times, the text on the client side is jibberish (%¤#£=)

### Expected Behavior

Keyboard mapping should work no matter if you alt + tab or not.

### Operating system(s) on local side and remote side

Ubuntu 22.04 --> Windows, Mac, Linux

### RustDesk Version(s) on local side and remote side

1.22

### Screenshots

N/A right now

**Comment by enoch85** [comment]
Maybe this fits in here? https://github.com/rustdesk/rustdesk/issues/4367

**Comment by rustdesk** [comment]
yes, tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
@enoch85 Hi, thanks for your feedback.

> Notice that after X amount of times, the text on the client side is jibberish (%¤#£=)

It's not easy to reproduce this issue for me.

Maybe it's related to some other potential flutter bug.

How many times has this problem occurred on your computer? Does it occur easily?

**Comment by enoch85** [comment]
> @enoch85 Hi, thanks for your feedback.
> 
> It's not easy to reproduce this issue for me.
> 
> > Notice that after X amount of times, the text on the client side is jibberish (%¤#£=)
> 
> Maybe it's related to some other potential flutter bug.
> 
> How many times has this problem occurred on your computer? Does it occur easily?

I'm on Wayland, maybe that's the issue?

It occurs exactly 100% of the times if I forget about it (and don't use the mouse to switch between windows instead).

I've been having around 40 sessions so far.

**Comment by enoch85** [comment]
My laptop is a Dell XPS 13, 9310.

**Comment by fufesou** [comment]
Thanks, there's a bug here. I'll fix this issue later.

**Comment by rustdesk** [comment]
Please try out the latest nightly build.

**Comment by enoch85** [comment]
Thanks for a quick fix! 

Will test this on Friday.

**Comment by enoch85** [comment]
Tested now, and it seems to work so far! Thanks!
