### ISSUE TITLE
Small Number Keyboard transmission issue while remote side use VMware Ubuntu.

### ISSUE THREAD

**Issue by lsyanling** [rustdesk/rustdesk#5786]
### Bug Description

I run a VMware Ubuntu 22.04 in remote side, and when I input number by Small Number Keyboard, no characters appear.
In all three modes, the Small Number Keyboard does't work. Besides, in Translate-Mode(beta), the input errors are not only in Small Number Keyboard but all keys in the Keyboard.
However, the behavior is right while I don't input in VMware.

### How to Reproduce

When input number in Small Number Keyboard to VMware Ubuntu, the error output or non-output displays there.

### Expected Behavior

There should be numbers when I press keys in Small Number Keyboard, as the behavior in Teamviewer or Sunlogin.

### Operating system(s) on local side and remote side

Windows 11 -> Windows 11 (VMware Ubuntu 22.04)

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.2

### Screenshots

In 1:1 Mode:
No output with keys in Small Number Keyboard.
![image](https://github.com/rustdesk/rustdesk/assets/65443331/9f74f97f-9e41-4e99-ae54-0b9c33965b35)

In Translate-Mode(beta) with number keys above "QWERT...":
The input is not number but wrong character.
![image](https://github.com/rustdesk/rustdesk/assets/65443331/ddc5865a-0039-4325-b615-71be7a3986f5)

Expected result:
Corrert numbers input.
![image](https://github.com/rustdesk/rustdesk/assets/65443331/08dde3b8-9b4f-4d43-ab7c-287ea4a31583)

### Additional Context

 In Teamviewer or Sunlogin, the input is normal.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4357
