### ISSUE TITLE
Rustdesk cannot capture whole Android 12 tablet screen

### ISSUE THREAD

**Issue by dtantono** [rustdesk/rustdesk#579]
Hi
I use Ubuntu 20.04 and I want to remote control my Samsung Galaxy Tab S7 with Android 12. But, it seems it cannot capture a whole screen. Is it a bug?
![image](https://user-images.githubusercontent.com/29157187/169656649-5b5d9823-e443-4d87-b0cf-8de95b9efd6c.png)

**Comment by Heap-Hop** [comment]
Was the `view style` been set `shrink`?

**Comment by dtantono** [comment]
ok, it works. my question is: this workaround only apply for Android tablet. Is that so?
