### ISSUE TITLE
Chang the name of Windows executable

### ISSUE THREAD

**Issue by JohnCoconut** [rustdesk/rustdesk#580]
The name of Windows executable contains "putes" (reverse of "setup"), which is unfortunately a vulgar term in several languages(French, Austrian etc). See https://en.wiktionary.org/wiki/putes.  

Could it be changed to something else?

I guess the reason for avoiding the filename is due to this, https://stackoverflow.com/questions/11573444/why-is-windows-asking-for-system-administrator-privileges-for-running-executable. One answer provides a solution to use "setup" in the filename. 

Sorry I don't have a widows machine around, so I couldn't test the solution myself.

**Comment by rustdesk** [comment]
Thanks for you reminder. We can not use setup, because WIndows will change the icon. But I will find another word. Maybe setpu etc.

**Comment by youhers** [comment]
You can try my submission on rusdesk.iss

**Comment by youhers** [comment]
https://github.com/rustdesk/rustdesk/pull/583 你可以看看这个

**Comment by SoftwareMagicIT** [comment]
You can use install instead of setup for icon changing issue!
