### ISSUE TITLE
Mac(m2) build target iOS error

### ISSUE THREAD

**Issue by kuke65** [rustdesk/rustdesk#5824]
### Bug Description

(error: linking with `cc` failed: exit status: 1)
  = note: ld: warning: no platform load command found in '/private/var/folders/j2/h2yjx3zs7fvgmkvp4jg1bfj00000gn/T/rustcPriWiy/symbols.o', assuming: iOS
          ld: building for 'iOS', but linking in object file (/Users/zhangshuheng/rustdesk/target/aarch64-apple-ios/release/deps/libscrap-2685ad679e50cc9e.rlib[58](vpx_decoder.c.o)) built for 'macOS'
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

### How to Reproduce

./flutter/ios_arm64.sh

### Expected Behavior

1

### Operating system(s) on local side and remote side

Mac

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

![截屏2023-09-26 19 18 39](https://github.com/rustdesk/rustdesk/assets/73464286/2f12acb4-b0d1-4ac8-a94d-bce3c20b557c)

**Comment by rustdesk** [comment]
#763

**Comment by sahilyeole** [comment]
@kuke65 you can try this:
https://github.com/rustdesk/rustdesk/discussions/5345#discussioncomment-6772568

**Comment by kyrosle** [comment]
> ### Bug Description
> (error: linking with `cc` failed: exit status: 1) = note: ld: warning: no platform load command found in '/private/var/folders/j2/h2yjx3zs7fvgmkvp4jg1bfj00000gn/T/rustcPriWiy/symbols.o', assuming: iOS ld: building for 'iOS', but linking in object file (/Users/zhangshuheng/rustdesk/target/aarch64-apple-ios/release/deps/libscrap-2685ad679e50cc9e.rlib[58](vpx_decoder.c.o)) built for 'macOS' clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> ### How to Reproduce
> ./flutter/ios_arm64.sh
> 
> ### Expected Behavior
> 1
> 
> ### Operating system(s) on local side and remote side
> Mac
> 
> ### RustDesk Version(s) on local side and remote side
> 1.2.3
> 
> ### Screenshots
> ![截屏2023-09-26 19 18 39](https://private-user-images.githubusercontent.com/73464286/270637991-2f12acb4-b0d1-4ac8-a94d-bce3c20b557c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NzE3MDEsIm5iZiI6MTcwMzg3MTQwMSwicGF0aCI6Ii83MzQ2NDI4Ni8yNzA2Mzc5OTEtMmYxMmFjYjQtYjBkMS00YWM4LWE5NGQtYmNlM2MyMGI1NTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDE3MzY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZGVmMDRkYmM2OWQxYjY3MDgwNmY1MzVjMDdiZmEzN2UxMzc5NTEwYzYxMWI2NTk1MmMwMDg2MGRlY2FiZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MvAcywnxL3wKrJ-C1yvGX1_3IQwBMtsjlo3UBaMju00)
> 
> ### Additional Context
> _No response_

hello, do you solve this problem?
