### ISSUE TITLE
windows to remote android,keyboard don’t work 

### ISSUE THREAD

**Issue by wrjcs** [rustdesk/rustdesk#5830]
### Bug Description

Hello 
When will the windows can use the physical keyboard to remote android input?
Thanks

### How to Reproduce

Remote android via windows

### Expected Behavior

The keyboard input of windows can input to android

### Operating system(s) on local side and remote side

Win11->android

### RustDesk Version(s) on local side and remote side

1.2.2->1.2.2

### Screenshots

Can have a photo for this issue

**Comment by rustdesk** [comment]
no duplicate please.
