### ISSUE TITLE
Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed

### ISSUE THREAD

**Issue by simone80an** [rustdesk/rustdesk#5843]
### Bug Description

Application (x86_x64 Debian package) don't load by clicking the application icon and if i run it from terminal displays the error message:

[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(57)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed
Annullato (core dump creato)

Looking on internet seems an [issue](https://github.com/flutter/flutter/issues/85460) related using Nvidia proprietary drivers on Linux.

I also tried run the AppImage version but it's the same.

### How to Reproduce

Run the application on Linux with proprietary Nvidia drivers in use.

### Expected Behavior

Application run and GUI opens.

### Operating system(s) on local side and remote side

Linux Mint 21.2

### RustDesk Version(s) on local side and remote side

1.2.2

### Screenshots

![Selezione_001](https://github.com/rustdesk/rustdesk/assets/28480712/7697b53a-bc88-4f2d-ad95-4871e9a9ad86)

**Comment by 21pages** [comment]
Please run `glxinfo | grep version` and show the output.
Which version is your Mint? https://www.linuxmint.com/download.php

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2543#issuecomment-1352938954

**Comment by rustdesk** [comment]
Since Sciter version works, you can build a Sciter version yourself, PR for this CI is welcome.
