### ISSUE TITLE
Weird bug where I can't simulate control key on windows 10 when connecting from macos

### ISSUE THREAD

**Issue by discoveryX64** [rustdesk/rustdesk#5848]
### Bug Description

When I was remoting to my windows machine one day, I couldn't use the command key how it normally would, and it would act like the windows key. Now it wouldn't let me copy and paste

### How to Reproduce

Use nightly on both clients
Connect to windows from mac
attempt to copy and paste how you normally would and enable the stupid windows clipboard menu

### Expected Behavior

Command on macos would work like control on windows
Control on macos would work like windows key on windows

### Operating system(s) on local side and remote side

macos Ventura -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3 (Both Nightly)

### Screenshots

<img width="642" alt="Screenshot 2023-09-27 at 10 02 39 PM" src="https://github.com/rustdesk/rustdesk/assets/119447512/3a31939d-724d-4fd4-aad2-cea7c03c73ea">

<img width="1440" alt="Screenshot 2023-09-27 at 10 02 15 PM" src="https://github.com/rustdesk/rustdesk/assets/119447512/b9ea3225-8feb-4bae-9bef-1cbb5fabbe80">

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/3121

**Comment by discoveryX64** [comment]
> #3121

My issue is completely different from #3121. Swap key is off, and even with it on beforehand it worked perfectly fine. My issue is that there isn't anyway to press control on the windows side when controlling from a mac. I don't think it has in issue with the swap key function.
