### ISSUE TITLE
A certain action causes the remote desktop window to go blank and cannot be closed.

### ISSUE THREAD

**Issue by YamatoRyou** [rustdesk/rustdesk#5849]
### Bug Description

Result 1:
Located at the control end, this window cannot be moved or closed, the only way is to kill the corresponding process.
![{07BA6D23-030E-D7ED-CA86-4752B99BA3B0}](https://github.com/rustdesk/rustdesk/assets/48104960/d1a8bfc3-b1c0-4cf6-b316-7995ebfbe7af)

Result 2: 
The window can be closed, but the RustDesk main window cannot respond to user operations (moving the mouse on the window can still display the transition animation of the control, and the window can also be moved). The only way is to kill the corresponding process.

Result 3:
The remote window can be closed, and the RustDesk main window can also respond to user operations. However, connecting to the controlled terminal again will pop up a window with a slightly different style, but still cannot be interacted with. The only way is to kill the corresponding process.
![{A924D065-047E-BFDE-0A60-7CBE64A11333}](https://github.com/rustdesk/rustdesk/assets/48104960/f94868ff-0daf-44c3-86ea-00d9731c3c60)

----
**This issue is currently found to only occur in 64-bit Windows version, and does not occur every time.**

### How to Reproduce

0. Ensure that the controlled end is running RustDesk in portable mode (this means that the other end has no services resident in the background);
1. Connect to controlled end's remote desktop;
2. Maximize the remote desktop window and close the other party’s RustDesk in the remote desktop;
3. At this time, you will be prompted "The connection was closed by the other party", and then click "Reconnect" manually "very quickly" (instead of automatically switching to "Reconnect");
4. Click "Cancel".

### Expected Behavior

The remote desktop window is closed, and there are no other strange behaviors affecting user operations.

### Operating system(s) on local side and remote side

x64 Windows 11 -> x86 Windows 8.1

### RustDesk Version(s) on local side and remote side

1.2.3 (x64, Flutter) -> 1.2.3 (x86, Sciter)

### Screenshots

n/a

### Additional Context

n/a

**Comment by rustdesk** [comment]
Confirmed.
