### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by poltpolt** [rustdesk/rustdesk#5852]
### Bug Description

https://github.com/rustdesk/rustdesk/wiki/FAQ#config-client-for-self-hosting

none of the links in the section above exists, error 404

### How to Reproduce

enter https://github.com/rustdesk/rustdesk/wiki/FAQ#config-client-for-self-hosting
click links

### Expected Behavior

links working

### Operating system(s) on local side and remote side

linux

### RustDesk Version(s) on local side and remote side

23.1.4

### Screenshots

no screenshot

**Comment by rustdesk** [comment]
![image](https://github.com/rustdesk/rustdesk/assets/71636191/66b0eaf6-bb7c-4d45-88be-e640fd7f85c5)

**Comment by poltpolt** [comment]
yes the link to https://github.com/rustdesk/rustdesk/wiki/FAQ#config-client-for-self-hosting
works fine,
but the links inside this chapter don't giving 404

I mean those :
https://rustdesk.com/docs/en/self-host/client/
and
https://rustdesk.com/docs/en/self-host/hardcode-settings/

return 
```
404
Sorry, this page does not exist.
Untitled UI logotext
Secure remote desktop access.
```

**Comment by Nerexbcd** [comment]
This is still an Issue, the link for how to hardcode the settings show a `404 Page`.

### The Link: https://rustdesk.com/docs/en/self-host/hardcode-settings/

### What it shows:
<img width="1158" alt="Image" src="https://github.com/user-attachments/assets/9f056cc6-d364-446d-a328-3d49884183e4" />
