### ISSUE TITLE
Pressing the display button shows screen sharing window. It persists as long as the dropdown is visible and goes away once dropdown is hidden.

### ISSUE THREAD

**Issue by kskarthik** [rustdesk/rustdesk#5853]
### Bug Description

Pressing the display button shows screen sharing window. It persists as long as the dropdown is visible and goes away once dropdown is hidden.

### How to Reproduce

Pressing the display button shows screen sharing window. It persists as long as the dropdown is visible and goes away once dropdown is hidden.

### Expected Behavior

it should happen only once 

### Operating system(s) on local side and remote side

Linux

### RustDesk Version(s) on local side and remote side

Windows

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/11899221/f505629d-df8c-483d-9776-fe0382339737)

### Additional Context

Confirmed only happens on Wayland. X11 is fine.

**Comment by rustdesk** [comment]
@sahilyeole

**Comment by sahilyeole** [comment]
Could not reproduce in ubuntu wayland but reproduced in kubuntu wayland (kde) on clicking display icon.

Also reproduced https://github.com/rustdesk/rustdesk/issues/4276 on connecting to kubuntu wayland from mac, prompt occurs every few seconds so it's unusable.

@fufesou can you give any clue on how https://github.com/rustdesk/rustdesk/issues/4276 was solved on ubuntu wayland?

**Comment by fufesou** [comment]
I just comment the two lines https://github.com/rustdesk/rustdesk/blob/40d3085cc2e61fd8ce0b34bc1fd299a31d3c341a/src/server/video_service.rs#L685

https://github.com/rustdesk/rustdesk/issues/4276#issuecomment-1558438376

Maybe you can check where and why `wayland::clear();` and `bail` are called.

**Comment by fufesou** [comment]
But they are not all the same.
This issue says the local side prompt screen sharing window, which should only show on the controlled side.

The prompt window on the local side is confusing and useless.

**Comment by sahilyeole** [comment]
>This issue says the local side prompt screen sharing window, which should only show on the controlled side.

https://github.com/rustdesk/rustdesk/pull/4411 has added a feature for fitting local resolution.
The resolution menu is making a call to get local display resolution details, hence in wayland it's causing the screen share prompt.
https://github.com/rustdesk/rustdesk/blob/40d3085cc2e61fd8ce0b34bc1fd299a31d3c341a/flutter/lib/desktop/widgets/remote_toolbar.dart#L1104-L1106

So, I think fixing #4276 for kde wayland will also fix this issue. Let me know if I'm wrong.
Or else to fix this particular issue I can disable the fitting local resolution feature specific to wayland like it is disabled for ios.

Which approach should I follow?

**Comment by rustdesk** [comment]
> #4411 has added a feature for fitting local resolution.

Good finding.

**Comment by rustdesk** [comment]
> Or else to fix this particular issue I can disable the fitting local resolution feature specific to wayland, like it is disabled for ios.

Let's do this as workaroud, please add a comment in the code change, and ref this issue.

**Comment by rustdesk** [comment]
Or is there any way to get resolution without this popup?

**Comment by fufesou** [comment]
> I think fixing https://github.com/rustdesk/rustdesk/issues/4276 for kde wayland will also fix this issue.

No. https://github.com/rustdesk/rustdesk/issues/4276 is caused by a wrong check on the server side.

I think we can remember current local resolution and do not show the prompt window every time.
Is there any other way to get locla resolution without screen sharing?

**Comment by rustdesk** [comment]
Something like this.

```
  @override
  Widget build(BuildContext context) {
    final Size screenSize = MediaQuery.of(context).size;
    final Size windowSize = window.physicalSize / window.devicePixelRatio;

    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Text('Screen Resolution: ${screenSize.width} x ${screenSize.height}'),
        Text('Window Resolution: ${windowSize.width} x ${windowSize.height}'),
      ],
    );
  }
```

**Comment by sahilyeole** [comment]
>Is there any other way to get local resolution without screen sharing?

We can use `weston-info` / `wayland-info` to get the local display resolution but these tools aren't preinstalled on some.

Or `xrandr` can also be used, I tried to use it but I need to fix this https://github.com/rustdesk/rustdesk/discussions/5403#discussioncomment-7133854 first as `xrandr` and `XFixesGetCursorImage` both depends on xwayland and it seems sometimes xwayland itself is failing on `--server`.

---
>final Size screenSize = MediaQuery.of(context).size;
  final Size windowSize = window.physicalSize / window.devicePixelRatio;
    
I tried this, it is only giving flutter window resolution.
   
<img width="282" alt="Screenshot 2023-10-01 at 12 27 25 AM" src="https://github.com/rustdesk/rustdesk/assets/73148455/d84eb53b-cf7a-4ae7-aa82-998b18810858">

**Comment by rustdesk** [comment]
Please test anydesk/teamviewer, if they can get display resolution without popup.

**Comment by rustdesk** [comment]
> Or `xrandr` can also be used, I tried to use it but I need to fix this [#5403 (reply in thread)](https://github.com/rustdesk/rustdesk/discussions/5403#discussioncomment-7133854) first as `xrandr` and `XFixesGetCursorImage` both depends on xwayland and it seems sometimes xwayland itself is failing on `--server`.

This is not --server, this is GUI, so no issue like $5403

**Comment by fufesou** [comment]
@sahilyeole You can use https://github.com/rustdesk/rustdesk/blob/master/flutter/lib/desktop/pages/desktop_home_page.dart#L564

I've tried on my Ubuntu 22.04 wayland, it works.

**Comment by rustdesk** [comment]
When you do the code change, please apply it only to Wayland.
