### ISSUE TITLE
Unable to access rdp of a windows remote from a Linux machine

### ISSUE THREAD

**Issue by kskarthik** [rustdesk/rustdesk#5854]
### Bug Description

X11 and Wayland both not getting rdp prompt or anything rdp related from a Linux machine

### How to Reproduce

X11 and Wayland both not getting rdp prompt or anything rdp related from a Linux machine

### Expected Behavior

a prompt should appear

### Operating system(s) on local side and remote side

Linux v1.2.3

### RustDesk Version(s) on local side and remote side

Windows v1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/11899221/9a70c0a5-7ea1-46da-84f9-cd4d102e08ec)

### Additional Context

Windows-windows works.

**Comment by macccorehenni** [comment]
I have this issue as well on Ubuntu 22.04 and Google ChromeOS 116.0.5845.210 Crostini.

**Comment by rustdesk** [comment]
this is windows 2 windows only

**Comment by rustdesk** [comment]
@21pages make this windows 2 widnows only, i believe 1.1.9 has this bevavior

**Comment by kskarthik** [comment]
thank you very much!
