### ISSUE TITLE
Install on debian failed

### ISSUE THREAD

**Issue by Thatoo** [rustdesk/rustdesk#586]
**Describe the bug you encountered:**

$ sudo apt install -fy ./rustdesk.deb 
E: Unable to recover http://deb.debian.org/debian/pool/main/p/python-pip/python-pip-whl_20.3.4-4_all.deb 404 Not Found [IP : 2a01:e0c:1:1598::2 80]
E: Could not recover http://deb.debian.org/debian/pool/main/p/python-pip/python3-pip_20.3.4-4_all.deb 404 Not Found [IP: 2a01:e0c:1:1598::2 80]
E: Can't get some archives, maybe you need to run apt-get update or try with --fix-missing?

Indeed, if I go to http://deb.debian.org/debian/pool/main/p/python-pip, I can find
python-pip-whl_20.3.4-4+deb11u1_all.deb
python3-pip_20.3.4-4+deb11u1_all.deb

but no

python-pip-whl_20.3.4-4_all.deb
python3-pip_20.3.4-4_all.deb

**What did you expect to happen instead?**

that installation goes through :-)

**Comment by rustdesk** [comment]
apt-get update？

**Comment by Thatoo** [comment]
Sorry, tried it already, I forgot to mention it.

**Comment by 64kramsystem** [comment]
A few posts on the net mention other two potential solutions: `apt clean` and `apt update --fix-missing`.

**Comment by senntore** [comment]
I'm having same issue, can't install using the deb & there is no other option available for ubuntu or ubuntu based distros(appimage/flatpak)

**Comment by Thatoo** [comment]
appimage is so download, click and play... and universal :heart: 
deb is more ecological and stable (but debian based only) so if it could work, it's already great :-)

**Comment by mbiebl** [comment]
Would it be possible to depend on python3-pynput instead of installing it in postinst via pip(3) for the Debian package?
You could have a `Depends: python3-pynput | python3-pip` and only call pip install in postinst if actually necessary.

**Comment by mbiebl** [comment]
Btw, looking at postinst:
`[ -d /run/systemd/system ]` is the canonical check to see if systemd is the current active init system.
I would also recommend to simply install /usr/share/rustdesk/files/systemd/rustdesk.service as /lib/systemd/system/rustdesk.service and then you just need to enable it.

There is no good reason to manually copy the file from /usr/share/rustdesk/files.

**Comment by ELKTKJ** [comment]
same issue

```shell
(base) user@Ubuntu:~/Downloads$ sudo dpkg -i rustdesk-1.1.9.deb 
(Reading database ... 245934 files and directories currently installed.)
Preparing to unpack rustdesk-1.1.9.deb ...
Failed to stop rustdesk.service: Unit rustdesk.service not loaded.
Unpacking rustdesk (1.1.9) over (1.1.9) ...
dpkg: dependency problems prevent configuration of rustdesk:
 rustdesk depends on libxdo3; however:
  Package libxdo3 is not installed.
 rustdesk depends on python3-pip; however:
  Package python3-pip is not installed.

dpkg: error processing package rustdesk (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Errors were encountered while processing:
 rustdesk
```

`apt clean` and `apt update --fix-missing` seems no works.

**Comment by 64kramsystem** [comment]
> same issue
> 
> ```shell
> (base) user@Ubuntu:~/Downloads$ sudo dpkg -i rustdesk-1.1.9.deb 
> (Reading database ... 245934 files and directories currently installed.)
> Preparing to unpack rustdesk-1.1.9.deb ...
> Failed to stop rustdesk.service: Unit rustdesk.service not loaded.
> Unpacking rustdesk (1.1.9) over (1.1.9) ...
> dpkg: dependency problems prevent configuration of rustdesk:
>  rustdesk depends on libxdo3; however:
>   Package libxdo3 is not installed.
>  rustdesk depends on python3-pip; however:
>   Package python3-pip is not installed.
> 
> dpkg: error processing package rustdesk (--install):
>  dependency problems - leaving unconfigured
> Processing triggers for hicolor-icon-theme (0.17-2) ...
> Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
> Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
> Processing triggers for mime-support (3.64ubuntu1) ...
> Errors were encountered while processing:
>  rustdesk
> ```
> 
> `apt clean` and `apt update --fix-missing` seems no works.

AFAIK `dpkg` doesn't install dependencies. on Ubuntu, you may want to try `gdebi`.

**Comment by rustdesk** [comment]
> install dependencies

sudo apt install -fy ./rustdesk-xx.deb

**Comment by ELKTKJ** [comment]
Retry and it works, thank you.

```
(base) user@Ubuntu:~/Downloads$ sudo apt install -fy ./rustdesk-1.1.9.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'rustdesk' instead of './rustdesk-1.1.9.deb'
rustdesk is already the newest version (1.1.9).
0 upgraded, 0 newly installed, 0 to remove and 90 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up rustdesk (1.1.9) ...
Collecting pynput
  Downloading pynput-1.7.6-py2.py3-none-any.whl (89 kB)
     |████████████████████████████████| 89 kB 72 kB/s 
Collecting python-xlib>=0.17; "linux" in sys_platform
  Downloading python_xlib-0.31-py2.py3-none-any.whl (179 kB)
     |████████████████████████████████| 179 kB 41 kB/s 
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from pynput) (1.14.0)
Collecting evdev>=1.3; "linux" in sys_platform
  Downloading evdev-1.5.0.tar.gz (26 kB)
Building wheels for collected packages: evdev
  Building wheel for evdev (setup.py) ... done
  Created wheel for evdev: filename=evdev-1.5.0-cp38-cp38-linux_x86_64.whl size=99652 sha256=6a72405be3caf6f36690e89ed2e198a5341a42eb9d9e674da2b7d89b37871339
  Stored in directory: /root/.cache/pip/wheels/7f/d9/9f/e55af4e0ac894421abd4e2d86a425d9e7f9ab222761fb98078
Successfully built evdev
Installing collected packages: python-xlib, evdev, pynput
Successfully installed evdev-1.5.0 pynput-1.7.6 python-xlib-0.31
Created symlink /etc/systemd/system/multi-user.target.wants/rustdesk.service → /etc/systemd/system/rustdesk.service.
(base) user@Ubuntu:~/Downloads$ sudo apt install -fy ./rustdesk-1.1.9.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'rustdesk' instead of './rustdesk-1.1.9.deb'
rustdesk is already the newest version (1.1.9).
0 upgraded, 0 newly installed, 0 to remove and 90 not upgraded.
```

**Comment by grummbeer** [comment]
> Retry and it works, thank you.

can be closed.

**Comment by kapitannwel** [comment]
> sudo apt install -fy ./rustdesk-xx.deb

worked on me, thank you very much! =)

**Comment by mgatc** [comment]
This still exists on Ubuntu 24 and the recommended fix doesn't help.

```
$ sudo apt-get install ./rustdesk-1.4.6-x86_64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'rustdesk' instead of './rustdesk-1.4.6-x86_64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 rustdesk : Depends: libxdo3 but it is not installable or
                     libxdo4 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
