### ISSUE TITLE
Elevation and local side remote control, both are lost if the internet briefly disconnects

### ISSUE THREAD

**Issue by sn-o-w** [rustdesk/rustdesk#5864]
### Bug Description

This issue prevents RustDesk from working properly and will make the local side unable to control and click with the mouse and use the keyboard of the remote side.

### How to Reproduce

1. Obviously, you will need two computers to ~~install RustDesk on both~~ install RustDesk on the local side and use the portable version on the remote side.
2. Connect remotely from one computer to the other one.
3. On the local side, request elevation via the top menu (Control Actions -> Request Elevation)
4. On the remote side, grant the elevation normally.
5. On the local side, disconnect your internet for 10-15 seconds, then reconnect it back. You will notice RustDesk will ask you to reconnect, so connect back to the remote side.
6. Notice you won't be able to do anything from the local to the remote side anymore...

### Expected Behavior

Elevation and mouse/keyboard controls should be restored after the local side is connected back to the remote side.
Besides, it would be pretty annoying to grant elevation every time the internet disconnects for a few seconds... 😞

### Operating system(s) on local side and remote side

Windows 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.2

### Additional Context

**_- On the remote side, when the local side connects back, for a few seconds you will see a small panel featuring an "Elevate" button, which means the Elevation was lost._**

**_- On the local side, RustDesk is somehow frozen; you can see the remote screen fine, even if the remote side does actions on the screen, like moving the mouse or anything, but you cannot do anything with your mouse and keyboard from the local side to the remote side. Even if you access the RustDesk's top menu, then Control Actions, you will notice that "Request Elevation" is missing, so the RustDesk on the local side misbelieves elevation is still in effect._**
 
**_- It could be something out of sync if on the local side you cannot Request Elevation anymore, and on the remote side you can press on "Elevate" button._**

**Comment by 21pages** [comment]
> install RustDesk on both

If installed, request elevation menu should not be displayed, elevation is for portable version,  it is displayed on your computer?
![1696034554718](https://github.com/rustdesk/rustdesk/assets/14891774/7bd2c9da-d9cb-4362-a1bf-e09b4327be87)

**Comment by 21pages** [comment]
> Notice you won't be able to do anything from the local to the remote side anymore...

What does this mean? Can't do anything need admin permissions or can't operate the mouse and can't see the screen update ?

**Comment by 21pages** [comment]
Is the remote foreground window elevated window? You can ensure this from the system taskManager

**Comment by 21pages** [comment]
It is possible that the remote computer displays an elevated window, such as a cmd window running in administrator mode. Now we do not prompt for such a window, except taskManager etc.

**Comment by 21pages** [comment]
When you can't click, minisize the current window and open the notepad, will the mouse back to normal?

**Comment by rustdesk** [comment]
> Also, please make it possible for elevation to persist when the local side reconnects. Pretty pleas

fix this, no need waste time to discuss a lot, please get the key point.

**Comment by 21pages** [comment]
Anydesk doesn't persist elevation for reconnect, I'll fix the problem that reqeust elevation menu is gone after reconnect, then user can elevate again.

**Comment by rustdesk** [comment]
feature request please for persistence, but it is not in our high priority.

**Comment by 21pages** [comment]
Please try to request elevation when the mouse doesn't work, if it works, that's the reason, the remote window is a elevated one.

**Comment by 21pages** [comment]
Elevation requires user interaction and it may not be ideal to keep the controlled side elevated for an extended period of time after disconnection. Therefore,  we mark it as feature request.

**Comment by 21pages** [comment]
https://github.com/rustdesk/rustdesk/blob/563cd828adc13cf08e2aa2e7eb9aab375fdb1e89/src/lang/en.rs#L35

Now it is only prompted for windows such as taskManager. It can be prompted whenever a similar situation occurs.
