### ISSUE TITLE
Compiling rustdesk error

### ISSUE THREAD

**Issue by z171262221** [rustdesk/rustdesk#5878]
### Bug Description

PS D:\RustDesk> git clone https://github.com/rustdesk/rustdesk
Cloning into 'rustdesk'...
remote: Enumerating objects: 54168, done.
remote: Counting objects: 100% (12808/12808), done.
remote: Compressing objects: 100% (555/555), done.
remote: Total 54168 (delta 12539), reused 12306 (delta 12253), pack-reused 41360
Receiving objects: 100% (54168/54168), 37.07 MiB | 11.14 MiB/s, done.
Resolving deltas: 100% (40708/40708), done.
PS D:\RustDesk> cd rustdesk
PS D:\RustDesk\rustdesk> cd flutter
PS D:\RustDesk\rustdesk\flutter> flutter pub get
Resolving dependencies... (15.1s)
  animations 2.0.7 (2.0.8 available)
  archive 3.3.6 (3.4.4 available)
  args 2.4.1 (2.4.2 available)
  async 2.10.0 (2.11.0 available)
  auto_size_text_field 2.2.1 (2.2.2 available)
  back_button_interceptor 6.0.2 (7.0.0 available)
  bot_toast 4.0.3 (4.1.3 available)
  build_resolvers 2.2.1 (2.4.1 available)
  build_runner_core 7.2.7 (7.2.11 available)
  built_value 8.4.3 (8.6.3 available)
  cached_network_image 3.2.3 (3.3.0 available)
  cached_network_image_platform_interface 2.0.0 (3.0.0 available)
  cached_network_image_web 1.0.2 (1.1.0 available)
  checked_yaml 2.0.2 (2.0.3 available)
  code_builder 4.4.0 (4.7.0 available)
> collection 1.17.2 (was 1.17.1) (1.18.0 available)
  cross_file 0.3.3+2 (0.3.3+5 available)
  crypto 3.0.2 (3.0.3 available)
  csslib 0.17.2 (1.0.0 available)
  dart_style 2.3.2 (2.3.3 available)
  device_info_plus 4.1.3 (9.0.3 available)
  device_info_plus_linux 3.0.0 (5.0.0 available)
  device_info_plus_macos 3.0.0 (5.0.0 available)
  device_info_plus_platform_interface 3.0.0 (7.0.0 available)
  device_info_plus_web 3.0.0 (5.0.0 available)
  device_info_plus_windows 4.1.0 (6.0.0 available)
  draggable_float_widget 0.0.2 (0.1.0 available)
  dropdown_button2 2.0.0 (2.3.9 available)
  ffi 2.0.1 (2.1.0 available)
  ffigen 7.2.11 (9.0.1 available)
  file 6.1.4 (7.0.0 available)
  file_picker 5.2.5 (5.5.0 available)
  fixnum 1.0.1 (1.1.0 available)
  flutter_cache_manager 3.3.0 (3.3.1 available)
  flutter_keyboard_visibility 5.4.0 (5.4.1 available)
  flutter_lints 2.0.2 (2.0.3 available)
  flutter_plugin_android_lifecycle 2.0.7 (2.0.16 available)
  flutter_rust_bridge 1.75.3 (1.82.1 available)
  flutter_svg 2.0.5 (2.0.7 available)
  freezed 2.4.2 (2.4.3 available)
  get 4.6.5 (4.6.6 available)
  glob 2.1.1 (2.1.2 available)
  graphs 2.2.0 (2.3.1 available)
  html 0.15.1 (0.15.4 available)
  http 0.13.5 (1.1.0 available)
  icons_launcher 2.1.0 (2.1.4 available)
  image 4.0.17 (4.1.3 available)
  image_picker 0.8.6+1 (1.0.4 available)
  image_picker_android 0.8.5+5 (0.8.8+1 available)
  image_picker_for_web 2.1.10 (3.0.1 available)
  image_picker_ios 0.8.6+6 (0.8.8+2 available)
  image_picker_platform_interface 2.6.2 (2.9.1 available)
> intl 0.18.1 (was 0.18.0)
  json_annotation 4.8.0 (4.8.1 available)
  lints 2.0.1 (2.1.1 available)
  logging 1.1.1 (1.2.0 available)
  matcher 0.12.14 (0.12.16 available)
> material_color_utilities 0.5.0 (was 0.2.0) (0.8.0 available)
  meta 1.9.1 (1.10.0 available)
  octo_image 1.0.2 (2.0.0 available)
  package_info_plus 3.1.2 (4.1.0 available)
  path_provider 2.0.12 (2.1.1 available)
  path_provider_android 2.0.22 (2.2.0 available)
  path_provider_foundation 2.1.1 (2.3.1 available)
  path_provider_linux 2.1.7 (2.2.1 available)
  path_provider_platform_interface 2.0.5 (2.1.1 available)
  path_provider_windows 2.1.3 (2.2.1 available)
  percent_indicator 4.2.2 (4.2.3 available)
  petitparser 5.1.0 (6.0.1 available)
  platform 3.1.0 (3.1.2 available)
  plugin_platform_interface 2.1.3 (2.1.6 available)
  pointycastle 3.6.2 (3.7.3 available)
  process 4.2.4 (5.0.0 available)
  pub_semver 2.1.3 (2.1.4 available)
  pubspec_parse 1.2.1 (1.2.3 available)
  puppeteer 2.21.0 (3.4.1 available)
  shelf 1.4.0 (1.4.1 available)
  shelf_static 1.1.1 (1.1.2 available)
  shelf_web_socket 1.0.3 (1.0.4 available)
  source_span 1.9.1 (1.10.0 available)
  sqflite 2.2.4+1 (2.3.0 available)
  sqflite_common 2.4.2+2 (2.5.0 available)
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  synchronized 3.0.1 (3.1.0 available)
  tuple 2.0.1 (2.0.2 available)
  typed_data 1.3.1 (1.3.2 available)
  universal_io 2.0.4 (2.2.2 available)
  url_launcher 6.1.8 (6.1.14 available)
  url_launcher_android 6.0.23 (6.1.0 available)
  url_launcher_ios 6.0.18 (6.1.5 available)
  url_launcher_linux 3.0.2 (3.0.6 available)
  url_launcher_macos 3.0.2 (3.0.7 available)
  url_launcher_platform_interface 2.1.1 (2.1.5 available)
  url_launcher_web 2.0.14 (2.0.20 available)
  url_launcher_windows 3.0.3 (3.0.8 available)
  uuid 3.0.7 (4.1.0 available)
  vector_graphics 1.1.5 (1.1.7 available)
  vector_graphics_codec 1.1.5 (1.1.7 available)
  vector_graphics_compiler 1.1.5 (1.1.7 available)
  video_player 2.7.1 (2.7.2 available)
  video_player_android 2.3.10 (2.4.10 available)
  video_player_avfoundation 2.3.8 (2.5.0 available)
  video_player_web 2.0.13 (2.1.1 available)
  watcher 1.0.2 (1.1.0 available)
+ web 0.1.4-beta (0.2.2-beta available)
  web_socket_channel 2.3.0 (2.4.0 available)
  win32 3.1.3 (5.0.9 available)
  win32_registry 1.0.2 (1.1.2 available)
  xdg_directories 0.2.0+3 (1.0.3 available)
  xml 6.2.2 (6.4.2 available)
  yaml 3.1.1 (3.1.2 available)
  yaml_edit 2.0.3 (2.1.1 available)
Changed 4 dependencies!
PS D:\RustDesk\rustdesk\flutter> cargo install flutter_rust_bridge_codegen --version 1.75.3 --features uuid
     Ignored package `flutter_rust_bridge_codegen v1.75.3` is already installed, use --force to override
PS D:\RustDesk\rustdesk\flutter> ~/.cargo/bin/flutter_rust_bridge_codegen --rust-input ../src/flutter_ffi.rs --dart-output ./lib/generated_bridge.dart --c-output ./macos/Runner/bridge_generated.h
2023/10/02 02:10:59 [WARN] Skipping unresolvable module inline (tried \\?\D:\RustDesk\rustdesk\src\inline.rs, \\?\D:\RustDesk\rustdesk\src\inline\mod.rs, \\?\D:\RustDesk\rustdesk\src\ui\inline.rs, \\?\D:\RustDesk\rustdesk\src\ui\inline\mod.rs, )
2023/10/02 02:10:59 [WARN] Skipping unresolvable module version (tried \\?\D:\RustDesk\rustdesk\src\version.rs, \\?\D:\RustDesk\rustdesk\src\version\mod.rs, \\?\D:\RustDesk\rustdesk\src\lib\version.rs, \\?\D:\RustDesk\rustdesk\src\lib\version\mod.rs, )
2023/10/02 02:10:59 [WARN] Skipping unresolvable module bridge_generated (tried \\?\D:\RustDesk\rustdesk\src\bridge_generated.rs, \\?\D:\RustDesk\rustdesk\src\bridge_generated\mod.rs, \\?\D:\RustDesk\rustdesk\src\lib\bridge_generated.rs, \\?\D:\RustDesk\rustdesk\src\lib\bridge_generated\mod.rs, )
2023/10/02 02:10:59 [INFO] Phase: Validate config(s)
2023/10/02 02:10:59 [INFO] Picked config: Opts { rust_input_path: "D:\\RustDesk\\rustdesk\\flutter\\../src/flutter_ffi.rs", dart_output_path: "D:\\RustDesk\\rustdesk\\flutter\\./lib/generated_bridge.dart", dart_decl_output_path: None, c_output_path: ["D:\\RustDesk\\rustdesk\\flutter\\./macos/Runner/bridge_generated.h"], rust_crate_dir: "D:\\RustDesk\\rustdesk\\flutter\\..", rust_output_path: "D:\\RustDesk\\rustdesk\\flutter\\../src\\bridge_generated.rs", class_name: "Rustdesk", dart_format_line_length: 80, dart_enums_style: false, skip_add_mod_to_lib: false, llvm_path: ["/opt/homebrew/opt/llvm", "/usr/local/opt/llvm", "/usr/lib/llvm-9", "/usr/lib/llvm-10", "/usr/lib/llvm-11", "/usr/lib/llvm-12", "/usr/lib/llvm-13", "/usr/lib/llvm-14", "/usr/lib/", "/usr/lib64/", "C:/Program Files/llvm", "C:/msys64/mingw64"], llvm_compiler_opts: "", manifest_path: "D:\\RustDesk\\rustdesk\\flutter\\..\\Cargo.toml", dart_root: Some("D:\\RustDesk\\rustdesk\\flutter"), build_runner: true, block_index: BlockIndex(0), skip_deps_check: false, wasm_enabled: false, inline_rust: false, bridge_in_method: true, extra_headers: "" }
2023/10/02 02:10:59 [INFO] Phase: Parse source code to AST, then to IR
2023/10/02 02:11:00 [WARN] Skipping unresolvable module inline (tried \\?\D:\RustDesk\rustdesk\src\inline.rs, \\?\D:\RustDesk\rustdesk\src\inline\mod.rs, \\?\D:\RustDesk\rustdesk\src\ui\inline.rs, \\?\D:\RustDesk\rustdesk\src\ui\inline\mod.rs, )
2023/10/02 02:11:00 [WARN] Skipping unresolvable module version (tried \\?\D:\RustDesk\rustdesk\src\version.rs, \\?\D:\RustDesk\rustdesk\src\version\mod.rs, \\?\D:\RustDesk\rustdesk\src\lib\version.rs, \\?\D:\RustDesk\rustdesk\src\lib\version\mod.rs, )
2023/10/02 02:11:00 [WARN] Skipping unresolvable module bridge_generated (tried \\?\D:\RustDesk\rustdesk\src\bridge_generated.rs, \\?\D:\RustDesk\rustdesk\src\bridge_generated\mod.rs, \\?\D:\RustDesk\rustdesk\src\lib\bridge_generated.rs, \\?\D:\RustDesk\rustdesk\src\lib\bridge_generated\mod.rs, )
2023/10/02 02:11:00 [INFO] Phase: Transform IR
2023/10/02 02:11:00 [INFO] Phase: Generate Rust code
2023/10/02 02:11:00 [INFO] Phase: Generate Dart code
Flutter 3.13.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ead455963c (5 days ago) • 2023-09-26 18:28:17 -0700
Engine • revision a794cf2681
Tools • Dart 3.1.3 • DevTools 2.25.0
2023/10/02 02:11:00 [INFO] Phase: Generating Dart bindings for Rust
Deprecated. Use `dart run` instead.
Building package executable...
Built ffigen:ffigen.
Running in Directory: 'D:\RustDesk\rustdesk\flutter'
[SEVERE] : Couldn't find dynamic library in default locations.
[SEVERE] : Please supply one or more path/to/llvm in ffigen's config under the key 'llvm-path'.
[SEVERE] : Couldn't find bin\libclang.dll in specified locations.
2023/10/02 02:11:03 [WARN] command="powershell" "-noprofile" "-command" "& \"flutter\" \"pub\" \"run\" \"ffigen\" \"--config\" \"C:\\\\Users\\\\zhaoyg\\\\AppData\\\\Local\\\\Temp\\\\.tmpX6absn\"" stdout= stderr=
2023/10/02 02:11:03 [ERROR] fatal: ffigen failed:
stderr:
stdout:
PS D:\RustDesk\rustdesk\flutter>

### How to Reproduce

My Flutter version is managed through FVM. Currently, there are three versions on the machine, namely 3.7.12, 3.10.6, and 3.13.6. The global version I exported (FVM global 3.13.6) is 3.13.6, and there are no issues compiling the old version 1.1 in the C++environment. LLVM is 15.02

### Expected Behavior

I compiled and ran the command in D: \RustDesk\rustdesk\run.sh, but the result was an error

### Operating system(s) on local side and remote side

Windows 11 Git Bash

### RustDesk Version(s) on local side and remote side

git clone https://github.com/rustdesk/rustdesk, Latest version obtained locally

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/125204314/fb721380-e998-4b6a-9d85-c56ee57e7eb2)

**Comment by rustdesk** [comment]
#763
