### ISSUE TITLE
Update runtime-version for flatpak

### ISSUE THREAD

**Issue by ximex** [rustdesk/rustdesk#5889]
### Bug Description

i have installed the nightly flatpak image from 2023-10-02 and i got following message on installation and also if i run `flatpak update`:
```
Info: runtime org.freedesktop.Platform branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   com.rustdesk.RustDesk

Info: runtime org.freedesktop.Platform.VAAPI.Intel branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   com.rustdesk.RustDesk

Info: runtime org.freedesktop.Platform.GL.default branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   com.rustdesk.RustDesk
```
the runtime-platform 21.08 is EoL and should be updated

### How to Reproduce

install nightly flatpak image or run `flatpak update`

### Expected Behavior

shouldn't get a warning of a component that is EoL

### Operating system(s) on local side and remote side

Kubuntu 23.04

### RustDesk Version(s) on local side and remote side

1.2.3 from 2023-10-02

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/1078640/49cb6fed-283a-45ec-9c58-95c9b655cd6e)

**Comment by rustdesk** [comment]
@sahilyeole

**Comment by sahilyeole** [comment]
> /attempt #5889

@Vishal-Sikka You can also continue working on this issue since #5918 has not solved it yet.
Also please test your changes first and then create a PR.

**Comment by Emilio1981938** [comment]
Info: runtime org.freedesktop.Platform branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   com.rustdesk.RustDesk

Info: runtime org.freedesktop.Platform.VAAPI.Intel branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   com.rustdesk.RustDesk

Info: runtime org.freedesktop.Platform.GL.default branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   com.rustdesk.RustDesk
reparado marcoherreraoriente@gmail.com
