### ISSUE TITLE
[Feature] Hardware encoding option

### ISSUE THREAD

**Issue by BlueWhale235** [rustdesk/rustdesk#589]
When I used mobile phone to control pc, I discovered that CPU usage was about 10%(i5-10400f).  
**I guest that the video stream is encode by cpu, i'm not surely.**  

I have a video card, I wish the next version has a hardware encoding option.

**Comment by rustdesk** [comment]
Will be in 1.1.10

**Comment by BuleWhale** [comment]
> Will be in 1.1.10

😀👌

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/768

**Comment by bt90** [comment]
Maybe you could use ffmpeg to achieve this on Linux and maybe other platforms:

https://trac.ffmpeg.org/wiki/HWAccelIntro

**Comment by 21pages** [comment]
> Maybe you could use ffmpeg to achieve this on Linux and maybe other platforms:
> 
> https://trac.ffmpeg.org/wiki/HWAccelIntro

Thank you for your advice, it has been implemented on linux and windows platform using ffmpeg, you can try with `cargo run --features hwcodec`, or `./build.py --hwcodec` .

**Comment by bt90** [comment]
Any plans when this will be enabled for stable builds by default?

**Comment by 21pages** [comment]
> Any plans when this will be enabled for stable builds by default?

Probably next version, but need more feedback before that

**Comment by bt90** [comment]
Just a quick thought but prebuilt testing binaries might encourage more users to give it a spin. Pair it with a call to test hw acceleration on a few subreddits like /r/selfhosted or /r/linux and you'll get plenty of feedback.

**Comment by 21pages** [comment]
Thank you, we'll talk about it.

**Comment by rustdesk** [comment]
Wait for a while for Flutter.

**Comment by GuilhermeWerner** [comment]
😁

**Comment by ruchit-bhatt** [comment]
Add feature to set pixel formats for `h264_nvenc` and `hevc_nvenc` 
`YUV 4:2:0`   : This pixel formats is good for low or average quality stream
`YUV 4:4:4`   : This pixel format gives better color quality, which is useful for video editing and color grading artists. 

![pixel format](https://i.ibb.co/sj6HpR5/pixel-format.png)
