### ISSUE TITLE
Unable to connect to Clients without monitor attached

### ISSUE THREAD

**Issue by Midnex** [rustdesk/rustdesk#59]
OS: Linux Mint 20.1 x64
Kernel: 5.4.0-58

Unable to connect to Linux machines with no monitor attached. 
Remote Error:
No Display

**Comment by Midnex** [comment]
What is invalid about it? I am confused, I have tried several machines with no displays connected and get the same error. All running various versions of Linux Mint and Manjaro Linux. I have no tried with Windows.

**Comment by rustdesk** [comment]
Because RustDesk is a screen sharing app.  Without physical or virtual monitor, it has nothing to share.

**Comment by rustdesk** [comment]
I understand your scenario, but in the near future, we can not create virtual display. It is not a simple job.

**Comment by Midnex** [comment]
RustDesk seems to be a remote control app more then a screen sharing. Screen sharing usually lacks controlling. While I understand, other rdp/vnc solutions can already do it. And would love to see it eventually make its way into your app. It is a extremely nice app so far, extremely fast, low memory, and I love it.

**Comment by gongjiaji** [comment]
google remotedesktop could do it, would you please reconsider this scenario as quite a lot of servers are running without a monitor. Thank you.

**Comment by rustdesk** [comment]
> without a monitor

Of course

**Comment by rustdesk** [comment]
> google remotedesktop could do it, would you please reconsider this scenario as quite a lot of servers are running without a monitor. Thank you.

But need more contribution from the community.

**Comment by rustdesk** [comment]
As a temp solution, you can install xrdp on Ubuntu, and rdp to Ubuntu using RustDesk port forwarding.

**Comment by jinjinjijiao** [comment]
![image](https://user-images.githubusercontent.com/46884440/123378830-d4c3be80-d5bf-11eb-97c6-142445cf7ae0.png)
you can solve this problem through this[https://service.oray.com/question/11969.html](url)

**Comment by rustdesk** [comment]
> 远程连接无显示器设备的“deepin系统”主机时出现 No display，连接显示器之后就可以进行连接远程桌面，其他的远程桌面程序在无显示器情况下可以进行远程连接。

**Comment by rustdesk** [comment]
> 有一个软件你必须得知道，就是DisplayAgent  在淘宝上面有卖，这个是虚拟显示器。如果你的rustdesk没有虚拟显示器功能，控制的电脑没有开显示器，就没图像，可能你已经知道。你想想办法。可以找店家交流一下

**Comment by rustdesk** [comment]
> What brought me here?
I have few computers these are remotely located and do not have any monitors attached to them. I create a virtual monitor in them and access them with similar software.  Though these are only 4 computers, but teamviewer sees it as commercial setup and so do other software. So I started to look for something else.  And found this great product. 
I am a programmer and wanted to learn Rust. Well -- so here I am ....

**Comment by starccy** [comment]
This problem also appears on Windows when the screen is locked.

**Comment by rustdesk** [comment]
https://github.com/pavlobu/deskreen/discussions/86

**Comment by fufesou** [comment]
[Xvfb](https://en.wikipedia.iwiki.eu.org/wiki/Xvfb) is a solution. While as methoned in the wiki:
_As of 2016, Xvfb was slated to be replaced by xf86-video-dummy in X.org 7.8._

[Xdummy](https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Xdummy.md) is a supported by default.
You can find the driver file in Ubuntu `/usr/lib/xorg/modules/drivers/` and Centos `/lib64/xorg/modules/drivers/`.

The solutions of [xrdp](https://github.com/neutrinolabs/xrdp) and [xpra](https://github.com/Xpra-org/xpra) are good references.

1. Detect if there is a physical monitor.
2. Provide a login window, input username and password.
3. Start a session and [X Display Manager](https://en.wikipedia.iwiki.eu.org/wiki/X_display_manager). The steps should be the same as [startx](https://linux.die.net/man/1/startx).

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/192#issuecomment-1133901726

**Comment by congzhangzh** [comment]
#634

**Comment by congzhangzh** [comment]
@fufesou @rustdesk please add session management, and not just screen share

**Comment by tcoombs** [comment]
Try using a dummy HDMI connector as this should enable a display that RustDesk can connect too.

**Comment by Luluno01** [comment]
The virtual monitor solution seems to conflict with real monitor - installing a virtual monitor will disable the output to the real monitor (but maybe it is possible to make the real monitor a secondary display?). This will make it harder to rescue your PC when, for example, the network fails, so that you have to connect a real monitor, which won't output anything if you have a virtual monitor installed already. I guess rustdesk will need a [sesman](https://linux.die.net/man/8/sesman) equivalent counterpart?

**Comment by atlex** [comment]
> As a temp solution, you can install xrdp on Linux, and rdp to Linux using RustDesk port forwarding.

Could you please describe it in details?

I have installed the XRDP on my Ubuntu server. It works perfectly.
My next steps?

**Comment by rustdesk** [comment]
For windows,  a virtual display driver is recommended:

https://github.com/rustdesk/rustdesk/issues/418#issuecomment-1233018617

**Comment by Pushkraj19** [comment]
do you know. Anydesk can do it too.

**Comment by tan-wei** [comment]
Seems all the OS (Windows, Linux and MacOS) will not display rightly when the screen is swich off. However, anydesk will not mind this.

So can we wait for the feature in the future? Any plan? Thanks!

**Comment by Jolonte** [comment]
> Try using a dummy HDMI connector as this should enable a display that RustDesk can connect too.

So if I connect an HDMI cable from my machine (Windows 11) to my other computer (Fedora 37 - Gnome, Xorg), would this error be resolved?

**Comment by Jolonte** [comment]
> Wondering if we can borrow something from qemu or virtualbox, they both have virtual display driver. @fufesou

Can you help me pls? If I connect a hdmi cable directly from a computer with windows to a desktop with fedora, this issue will be fixed?

**Comment by rustdesk** [comment]
frankly, do not know

**Comment by Jolonte** [comment]
> frankly, do not know

Alright I'll be testing and share the results here

**Comment by JfiungoM** [comment]
I was with the same problem. I used VGA dummy plug. It works for me.
https://www.geeks3d.com/20091230/vga-hack-how-to-make-a-vga-dummy-plug/

**Comment by nekuneko** [comment]
I'm an headless-linux-workstation xrdp user, so I want to remote control the workstation by VNC/XRDP/AnyDesk/RustDesk/SSH and so many protocols I can in order to keep access to it in case of failure. This my temporal and ugly "hack" for RustDesk server without monitor attached:

1. Connect to the remote machine and login through XRDP (Remmina/Microsoft RDP).
2. Open a terminal and write: `sudo killall rustdesk && rustdesk &`
3. At this point RustDesk has been opened with the xrdp session which previously created a virtual display (I think following `/etc/X11/xrdp/xorg.conf` file).
4. Open RustDesk on your local machine and login with your ID and pre-configurated password.
5. Now you are logged in on the remote machine through RustDesk and no Display connected.
6. Close XRDP session, RustDesk session with the xrdp virtual monitor will keep on.

I already tried the solution of making a custom `/etc/X11/xorg.conf` file but I loosed the HDMI hot-plug with it.
With this "hack" solution HDMI hot-plug is maintained. I will update if I can improve this solution.

I hope RustDesk developers could implement a solution similar to xrdp actually does for creating a virtual environment, I think this feature is crucial to be implemented for headless machines in order to switch from AnyDesk.

**Comment by congzhangzh** [comment]
如果你有intel集显，可以开虚拟显示，而且桌面加速可用。

https://github.com/medlab/daily-scripts-4-us/blob/main/enable_headless_intel_igpu_4_nomachine.sh

**Comment by rustdesk** [comment]
> https://github.com/medlab/daily-scripts-4-us/blob/main/enable_headless_intel_igpu_4_nomachine.sh

Cool

**Comment by madroots** [comment]
Solution for raspberry pi as of September 2023:

edit file /boot/config.txt like this:

Uncomment -> hdmi_force_hotplug=1
Uncomment and change group ->  hdmi_group=2
Uncomment and change mode ->  hdmi_mode=82
Comment -> #dtoverlay=vc4-kms-v3d

save and reboot your pi. Rust desk should connect now. 
Credit goes to @viniwludwig, found this on some youtube video in comments.

**Comment by L1yp** [comment]
> 如果你有intel集显，可以开虚拟显示，而且桌面加速可用。

你好，我的i5 4590电脑遇到了这个问题，请问Intel怎么打开虚拟显示呢，如果实在不行就买个fake HDMI了

**Comment by Kareltje1980** [comment]
> Solution for raspberry pi as of September 2023:
> 
> edit file /boot/config.txt like this:
> 
> Uncomment -> hdmi_force_hotplug=1 Uncomment and change group -> hdmi_group=2 Uncomment and change mode -> hdmi_mode=82 Comment -> #dtoverlay=vc4-kms-v3d
> 
> save and reboot your pi. Rust desk should connect now. Credit goes to @viniwludwig, found this on some youtube video in comments.

For the RPI5 this doesnt work anymore, you need to add ```vc4.force_hotplug=1``` to the end the only one line in  /boot/firmware/cmdline.txt

**Comment by mayemu** [comment]
is there a cleaner more reliable solution besides HDMI dummy plug yet? I really need this functionality for my server. I'll get a dummy plug if I have to but id rather not haha

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/wiki/FAQ#headless-linux-support

**Comment by gregoryPM** [comment]
> vc4.force_hotplug=1

Can confirm this does solve the issue (RPI 5/Ubuntu).

**Comment by rustdesk** [comment]
https://www.reddit.com/r/rustdesk/comments/1fodeku/headless_linux_on_rustdesk_display_and_desktop/

**Comment by jlinkels** [comment]
> edit file /boot/config.txt like this:
> 
> Uncomment -> hdmi_force_hotplug=1 Uncomment and change group -> hdmi_group=2 Uncomment and change mode -> hdmi_mode=82 Comment -> #dtoverlay=vc4-kms-v3d
> 
This works like a charm. However when the Pi runs with this parameters there is a process **mutter**
 which uses 130% on a Pi 4. Which the result that the Pi is getting awfully hot, even with heatsinks.

**Comment by jashanbhullar** [comment]
it works on pi 5 with `video=HDMI-A-1:2048x1440@60D` in file `/boot/firmware/cmdline.txt` 

After connecting it shows a blank screen but it toggle recording, it works 🤷‍♂️

**Comment by Liverpooler10** [comment]
Any idea whether this works on a dell wyse 5070 aswell?

**Comment by coolDad7777** [comment]
> I understand your scenario, but in the near future, we can not create virtual display. It is not a simple job.

What>?
