### ISSUE TITLE
Load librustdesk.so failed on AppImage

### ISSUE THREAD

**Issue by rik1599** [rustdesk/rustdesk#5928]
### Bug Description

I can not open the AppImage version of Rustdesk. If I execute it it returns me that the loading of librustdesk.so is failed.
The app results opened for the OS but the UI is not shown.

### How to Reproduce

Execute the AppImage file from a terminal.

### Expected Behavior

The UI of RustDesk is shown.

### Operating system(s) on local side and remote side

Fedora 38

### RustDesk Version(s) on local side and remote side

1.2.2

### Screenshots

![immagine](https://github.com/rustdesk/rustdesk/assets/31370173/34031d39-cab2-40e7-84e1-22f7564d329f)
![immagine](https://github.com/rustdesk/rustdesk/assets/31370173/c5ddc4af-6db3-435a-b12d-5970d6237dc1)

### Additional Context

The italian parts of the messages says "Unable to open the shared object: file or directory not found"

_No response_

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by rustdesk** [comment]
https://github.com/g-fb/haruna/issues/53
