### ISSUE TITLE
voice and video not synced after a while

### ISSUE THREAD

**Issue by lidawei97688** [rustdesk/rustdesk#593]
After the direct connection, the sound from the controlled computer will gradually lag over time, and it will gradually fail to keep up with the screen. Turn on the mute in the rustdesk menu and wait for the sound to end and then turn off the mute to restore, but it will still be slow as time passes. slow lag

直连连接后，被控电脑传递来的声音会随着时间逐渐滞后，慢慢的跟不上画面，在rustdesk菜单里开启静音等待声音结束再关闭静音会恢复，但随着时间经过还是会慢慢滞后

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/534

**Comment by rustdesk** [comment]
Try out https://github.com/rustdesk/rustdesk/releases/download/tmp/rustdesk-1.1.9-putes.exe please

**Comment by lidawei97688** [comment]
有明显改善，但似乎并未完全解决问题，似乎是窗口尺寸越大，音频延迟增量就越多，而缩小窗口尺寸则会慢慢追回直至同步

**Comment by BenK885** [comment]
> 有明显改善，但似乎并未完全解决问题，似乎是窗口尺寸越大，音频延迟增量就越多，而缩小窗口尺寸则会慢慢追回直至同步
Translated to english:
"Significant improvement, but it doesn't seem to solve the problem completely, it seems that the larger the window size, the more the audio delay increments, and reducing the window size will slowly catch up to sync"

**Comment by rustdesk** [comment]
close to favor https://github.com/rustdesk/rustdesk/issues/534
