### ISSUE TITLE
Working principle

### ISSUE THREAD

**Issue by jinfagang** [rustdesk/rustdesk#594]
How does it work? Any docs? Caused users concerning about the security itself without looking the code. Does it requires a good spec centeric server? what's the minimal requirements of it ?

**Comment by rustdesk** [comment]
https://rustdesk.com/docs/en/

**Comment by rustdesk** [comment]
Doc is still incomplete.

**Comment by zuoxinyu** [comment]
Seems an architecture introduction is needed.

**Comment by rustdesk** [comment]
> architecture introduction

I am really not good at this, everything is in my mind, but I do not know how to draw or write on the paper.

**Comment by asur4s** [comment]
I draw a draft. 

![IMG_7767(20220526-111418)](https://user-images.githubusercontent.com/99897242/170408936-4ac14d79-b8c2-49c7-b912-08e2d8cbfd1a.png)

**Comment by rustdesk** [comment]
> draft

Good job! :)

**Comment by asur4s** [comment]
>  Caused users concerning about the security itself without looking the code.

Security check locally, make sure your password is complex enough.

> what's the minimal requirements of it ?

Depends on video transmission quality. These servers do not need high performance, you only need to consider the bandwidth of the relay server.

**Comment by rustdesk** [comment]
ID / Pasword does not go to server 1.

**Comment by asur4s** [comment]
> ID / Pasword does not go to server 1.

Ok, I fix it soon. The code of server side has a lot of abbr.

**Comment by asur4s** [comment]
I steal it from https://cloud.tencent.com/developer/article/1897847
![image](https://user-images.githubusercontent.com/99897242/170458902-91f0b4c0-dd76-43bb-a7b9-f38ef7f7bb1f.png)

And I draw a simple depoyment diagram to supply some additional information.

![image](https://user-images.githubusercontent.com/99897242/170460431-1fba4f4b-6773-4e7a-94b0-f236233f13f2.png)

**Comment by asur4s** [comment]
> ID / Pasword (encrypted) does not go to server 1

Teah, the password is generated locally, this draft is wrong.

**Comment by rustdesk** [comment]
I will put your diagram into a wiki.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/wiki/How-does-RustDesk-work%3F

**Comment by asur4s** [comment]
> I will put your diagram into a wiki.

I steal the first diagram from https://cloud.tencent.com/developer/article/1897847

**Comment by rustdesk** [comment]
@asur4s The first diagram has a little out of date, B's pk on step 9 is also encrypted in new version.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/blob/master/src/client.rs#L354

**Comment by asur4s** [comment]
Ok, I'll read this part of the code carefully to fix the first diagram.

**Comment by asur4s** [comment]
> Ok, I'll read this part of the code carefully to fix the first diagram.

The time is late. 

I've simplified a lot of information for a better understanding of how rustdesk works, You can also modify it online at this [link](https://www.plantuml.com/plantuml/uml/fLB1RjGm4BtdA-O6bS8An8q3wfOYL4MLLktsniLnfedLP6p6zfRyFHDdDwohZJXmYiP-Vk_DUxdsGN68Gryu-HfjdA80kZT8OGkM6sJuz36xxEhQ7sy-vpUCWmruy_UoA5GCbk9G8nV-nP2WrG0UVqKaZVVelMfnsvkMG8kYe8gMRNJmWAtnqmm02--7hqdyot8BhoPqwMoJWCdQWdfK1mI70ZFqR6S42H6mQRkGnhlR4hPDmsAaXAUdQTnLxtUnxes62iShI32a9hqiCfMZhJCxmkCiUKnQIuh_RNj1d2WlIeh9Ktfx7Y5Oq9O8TLWp8oNuCE7aesHZtvrU64lmasQR3sdBkrkeHt2HT6UeXSxsk5aBO-QT3q19kfkr5aDaoe2NEfeDf9fA6NermYFo0NczcYMdN6C9z5yQQTXLcS1vlj-Nm1Hur97nF3a9wWL7mD-wKzJYs-KNRtiSd6N5u_JFtRo3_Qww0YJDemlOpEdByMEL_KuPnIqcz5HYYm5caerqzmC9MGK4mjVanYd3eAW1Fmu31iCw7MVKMOyULOzlu2Liaq9MQFOgDvI_5biIJVI6sYFFP4XCxsN5BDwKWOXhEmoHZ5Ofr-Lnnhgwm3TBWMqFZGhgKkSLZhLLt9HmRwF7lEorphQnCHQUMGrOmi6S3G9nYM_Q18f2WdTAsh-MCGxz7m00)

![image](https://user-images.githubusercontent.com/99897242/172282341-7ec04806-6c7f-4848-a41f-93937c0c1093.png)

**Comment by rustdesk** [comment]
> understanding

Good Job!

**Comment by asur4s** [comment]
![image](https://user-images.githubusercontent.com/99897242/172283937-0bae0c8c-8bb3-42eb-8376-60f1d29a4671.png)

Is this part correct?

**Comment by rustdesk** [comment]
> correct

Looks ok

**Comment by rustdesk** [comment]
![image](https://user-images.githubusercontent.com/71636191/172284487-7c52cbf0-e2f4-4af5-adb5-4d60870eab1b.png)
Here, you'd better change `remote pk` to  `encrypted remote pk`

**Comment by asur4s** [comment]
Ok

**Comment by WaleedMortaja** [comment]
@rustdesk @asur4s 
If you allow me, I would suggest updating the image in the [wiki](https://github.com/rustdesk/rustdesk/wiki/How-does-RustDesk-work%3F) to the latest image. I would even better suggest removing the wiki, and merging its content to the docs, making the docs the unified central information reference.

For the latest image provided here, I have some questions

1. So, the clients generate public/private key pair independent of the the key of hbbs? May be that phase could be added before the first phase in the diagram?
2. Is the data in the "register" phase encrypted? Maybe using the public key entered in ["ID/Relay Server](https://rustdesk.com/docs/en/self-host/install/#step-3--set-hbbshbbr-address-on-client-side)" config?
3. If one, or both if the clients did not set the hbbs key, why is the connection marked as "not encrypted"? Is not the connection between the client already encrypted using the symmetric key in the last phase?
4. How does a rely server affect the encryption?
5. Can you add a key-map of the abbreviations and ambiguous keys, like ID and UUID. What is the difference? Does Address refer to IP Address?
6. In Steps 11 & 12, How could "Client A" decrypt the data that is encrypted by "B's SK". Is "B's SK" sent in step 10?

One last (Mostly off-topic) question: What does hbbs and hbbr stand for?! I know they are the rendezvous and relay serves, but I can not see how hbbs stands for rendezvous server for example?

Sorry for writing too long and thank you very much for the amazing software!

**Comment by akiross** [comment]
Github supports [mermaidjs](https://mermaid.js.org), so it's possible to draw some simple diagrams using code.

I'm sharing the code of a sequence diagram so you can place that in the wiki or doc and change it with ease.

I'm not sure about how hbbr are used, so I guessed a bit in the last part.

~~~
```mermaid
sequenceDiagram

  participant client A
  participant hbbs
  participant hbbr
  participant client B

  Note over client A, client B: Registration of client A
  
  client A ->> hbbs: 1. Register with hbbs
  hbbs ->> hbbs: 2. Save peer info
  Note right of hbbs: ID, Address, UUID, PK
  hbbs -->> client A: 3. Register response 

  Note over client A, client B: Registration of client B

  client B ->> hbbs: 4. Register with hbbs
  hbbs ->> hbbs: 5. Save peer info
  hbbs -->> client B: 6. Register response

  client B ->> hbbs: 7. Request to establish connection<br/>with RemoteID by punching hole
  hbbs ->> client A: 8. Request remote addr
  client A -->> hbbs: 9. Return remote
  Note left of client A: Remote addr, Relay server addr
  hbbs ->> client B: 10. Return remote info
  Note right of client B: Remote addr, encrypted PK

  Note over client A, client B: Establish a secure connection key exchange

  client A ->> client B: 11. B's TPK encrypted with B's SK
  client B ->> client B: 12. Decrypt B's TPK, generate, new keypair

  client B ->> client A: 13. Sealed symmetric A's TPK
  client A ->> client A: 14. Decrypt, get symmetric TPK/TSK

  Note over client A, client B: Encrypted communication by using symmetric key

  client B ->> hbbr: 15. Control data
  hbbr ->> client A: 15. Control data
  Note left of client A: Keyboard, Mouse
  client A ->> hbbr: 16. Audio frame, video frame, clipboard
  hbbr ->> client B: 16. Audio frame, video frame, clipboard

```
~~~

```mermaid
sequenceDiagram

  participant client A
  participant hbbs
  participant hbbr
  participant client B

  Note over client A, client B: Registration of client A
  
  client A ->> hbbs: 1. Register with hbbs
  hbbs ->> hbbs: 2. Save peer info
  Note right of hbbs: ID, Address, UUID, PK
  hbbs -->> client A: 3. Register response 

  Note over client A, client B: Registration of client B

  client B ->> hbbs: 4. Register with hbbs
  hbbs ->> hbbs: 5. Save peer info
  hbbs -->> client B: 6. Register response

  client B ->> hbbs: 7. Request to establish connection<br/>with RemoteID by punching hole
  hbbs ->> client A: 8. Request remote addr
  client A -->> hbbs: 9. Return remote
  Note left of client A: Remote addr, Relay server addr
  hbbs ->> client B: 10. Return remote info
  Note right of client B: Remote addr, encrypted PK

  Note over client A, client B: Establish a secure connection key exchange

  client A ->> client B: 11. B's TPK encrypted with B's SK
  client B ->> client B: 12. Decrypt B's TPK, generate, new keypair

  client B ->> client A: 13. Sealed symmetric A's TPK
  client A ->> client A: 14. Decrypt, get symmetric TPK/TSK

  Note over client A, client B: Encrypted communication by using symmetric key

  client B ->> hbbr: 15. Control data
  hbbr ->> client A: 15. Control data
  Note left of client A: Keyboard, Mouse
  client A ->> hbbr: 16. Audio frame, video frame, clipboard
  hbbr ->> client B: 16. Audio frame, video frame, clipboard

```

**Comment by softyoda** [comment]
> I steal it from https://cloud.tencent.com/developer/article/1897847 ![image](https://user-images.githubusercontent.com/99897242/170458902-91f0b4c0-dd76-43bb-a7b9-f38ef7f7bb1f.png)
> 
> And I draw a simple depoyment diagram to supply some additional information.

> 
> ![image](https://user-images.githubusercontent.com/99897242/170461347-3c526b1d-ac93-4eb0-a087-d5397803b504.png)




Hi, i'm new and would like to get technical-yet-comprehensible info about RustDesk. I'm using parsec to work remotly (fulltime) and i'd wish to know how your servers works. Is the relay server required? What it is purpose ?

**Comment by nvm-hvktmm** [comment]
hbbs, hbbr meaning?

**Comment by akiross** [comment]
It's in the server doc: https://github.com/rustdesk/rustdesk-server/blob/master/README.md

- hbbs - RustDesk ID/Rendezvous server
- hbbr - RustDesk relay server

**Comment by WaleedMortaja** [comment]
@akiross Their job is in the document. However, It is yet not clear how are their names derived. The question is: What does hbbs/hbbr stand for?

**Comment by nvm-hvktmm** [comment]
hai máy rustdesk kết nối với nhau sử dụng mã hoá gì
nếu sử dụng mã hoá thì nó sinh khoá như thế nào

**Comment by ben221199** [comment]
Still no information about the abbrevation meaning of HBB (as in HBBR and HBBS)?

**Comment by jgstern** [comment]
This is just a guess - I haven't been closely following the above discussion so it should be double-checked?
hbbs: heartbeat and broker server
hbbr: heartbeat and broker relay

**Comment by akiross** [comment]
I'm not sure, but it does make sense and there's an [heartbeat reference in the current docs](https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/ubuntu-server/docker/#4-set-port-forwarding-on-your-routervps):

> 21116 UDP heartbeat/ID server
