### ISSUE TITLE
Error in installing armv7 version on the 3568 industrial Android development board

### ISSUE THREAD

**Issue by lrange2001** [rustdesk/rustdesk#5943]
### Bug Description

adb install /Users/xiaoyu/Desktop/zeekr_new/rustdesk-1.2.2-armv7-signed.apk 
'Performing Streamed Install
adb: failed to install /Users/xiaoyu/Desktop/zeekr_new/rustdesk-1.2.2-armv7-signed.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

### How to Reproduce

adb install /Users/xiaoyu/Desktop/zeekr_new/rustdesk-1.2.2-armv7-signed.apk 
'Performing Streamed Install
adb: failed to install /Users/xiaoyu/Desktop/zeekr_new/rustdesk-1.2.2-armv7-signed.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

### Expected Behavior

adb install /Users/xiaoyu/Desktop/zeekr_new/rustdesk-1.2.2-armv7-signed.apk 
'Performing Streamed Install
adb: failed to install /Users/xiaoyu/Desktop/zeekr_new/rustdesk-1.2.2-armv7-signed.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

### Operating system(s) on local side and remote side

windows11

### RustDesk Version(s) on local side and remote side

1.2.2

### Screenshots

adb install /Users/xiaoyu/Desktop/zeekr_new/rustdesk-1.2.2-armv7-signed.apk 
'Performing Streamed Install
adb: failed to install /Users/xiaoyu/Desktop/zeekr_new/rustdesk-1.2.2-armv7-signed.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893
