### ISSUE TITLE
Rustdesk Mac doesn't work on VM

### ISSUE THREAD

**Issue by Arrmm** [rustdesk/rustdesk#5960]
### Bug Description

For some reason I can't get Rustdesk to run on any Mac VMs that I have running.  I tried Anydesk, TeamViewer all works but not Rustdesk.  The app is running in the background but nothing shows on the display.

### How to Reproduce

Install rustdesk any version from 1.1.9 (1.20, 1.2.1, 1.2.2, even 1.2.3) on a Mac VM and it won't show on display.

### Expected Behavior

Rustdesk should launch inside a Mac VM

### Operating system(s) on local side and remote side

n/a

### RustDesk Version(s) on local side and remote side

n/a

### Screenshots

![2023-10-09_115220](https://github.com/rustdesk/rustdesk/assets/25805638/fb027294-4d42-4d9c-a42a-570a4e916dc3)

**Comment by 21pages** [comment]
https://github.com/flutter/flutter/issues/108304
Please use sciter version.

**Comment by rustdesk** [comment]
duplicate many times
