### ISSUE TITLE
Mobile. Scam message. Action buttons not reachable

### ISSUE THREAD

**Issue by grummbeer** [rustdesk/rustdesk#5963]
### Bug Description

Depending on the screen size, the action buttons are not accessible and make the usage impossible.

### How to Reproduce

Android > Share screen > "enable service"

### Expected Behavior

Buttons are always reachable.

### Operating system(s) on local side and remote side

linux > Android 12

### RustDesk Version(s) on local side and remote side

nightly > nightly mobile

### Screenshots

|en|de|
|--|--|
|![scam-message-en](https://github.com/rustdesk/rustdesk/assets/67791701/40f9f061-db04-4ba2-8b9d-9bd874c72a09)|![scam-message-de](https://github.com/rustdesk/rustdesk/assets/67791701/219eb300-21ce-4b8e-9b3b-3bae7ee01957)|

### Additional Context

Possible solution: The message body could be scrollable.

**Comment by rustdesk** [comment]
@sahilyeole fix it ASAP please.
