### ISSUE TITLE
Only limited resolutions are supported? 

### ISSUE THREAD

**Issue by Creling** [rustdesk/rustdesk#597]
Hello:

I connect from Windows11 with a 1366\*768 resolution to Windows Server 2022, to find that only three resolutions are supported in remote end, which does not include 1366\*786.

![image](https://user-images.githubusercontent.com/43109504/169808454-68bbec76-2626-40d9-b67f-735066dcbb26.png)

Is it possible for me to change the resolution to 1366\*768?

**Comment by rustdesk** [comment]
Not capable yet.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1053

**Comment by rustdesk** [comment]
We are screen capturing, not creating new session as what mstsc does. But in some special case (e.g. no physical display), we can create a virtual display with some resolution, but still impossible as flexible as mstsc. If you insist it, please user our RDP sharing feature https://github.com/rustdesk/rustdesk/issues/914#issuecomment-1173839858.
