### ISSUE TITLE
No binary in x86_64 .deb package release

### ISSUE THREAD

**Issue by narukeh** [rustdesk/rustdesk#5971]
### Bug Description

I thought it was a problem on a ubuntu system of mine. but then i extracted the .deb, and the tar in it, and YES, there is everything except the binary file.

### How to Reproduce

Download https://github.com/rustdesk/rustdesk/releases/download/1.2.3/rustdesk-1.2.3-x86_64.deb , extract/install see if you se anything under /usr/bin

### Expected Behavior

there should be a binary in it

### Operating system(s) on local side and remote side

Linux

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

![pic-selected-231010-1811-53](https://github.com/rustdesk/rustdesk/assets/62762955/befc7dff-83f8-4413-aa3a-3d688d5ca2de)

### Additional Context

the appimages dont work on a default Ubuntu 22.04 installation, therefore i could not deploy the appimage. Rereleasing 1.2.3 would be appreciated.

**Comment by wodin** [comment]
@narukeh they do this:

```console
$ ar p rustdesk-1.2.3-x86_64.deb control.tar.xz | xz -dc | tar xOf - ./postinst | grep ln
		ln -s /usr/lib/rustdesk/rustdesk /usr/bin/rustdesk
```

**Comment by narukeh** [comment]
yeah i get it now, but i dont know why it isnt making the symlink.
tried uninstalling, then installing, but it did not work.
🤷🤷🤷
