### ISSUE TITLE
Connect Headless Linux Client report error: Unsupported display server type "", x11 or wayland expected

### ISSUE THREAD

**Issue by Bao0ne** [rustdesk/rustdesk#5976]
### Bug Description

Unsupported display server type "", x11 or wayland expected

Can connect successfully and run lightdm manually before connecting

my question is how does the headless client automatically create a session like xrdp

### How to Reproduce

running headless client with ubuntu:latest container .

get id and set passowrd by cli

### Expected Behavior

connection succeeded

### Operating system(s) on local side and remote side

osx -> ubuntu

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/37828835/8c0917b0-de11-45c5-a7f9-1cbd28d0ac0d)

### Additional Context

exec headless rustdesk client
```
root@u2-6758bb5fd-966q7:/# loginctl 
No sessions.
root@u2-6758bb5fd-966q7:/# /usr/lib/rustdesk/rustdesk --get-id
198527304
root@u2-6758bb5fd-966q7:/# ps -ef | grep rust
root     1040309  331871  0 Oct10 pts/5    00:05:45 /usr/lib/rustdesk/rustdesk --service
root     1713901 1040309  0 01:08 pts/5    00:00:04 /usr/lib/rustdesk/rustdesk --server
root     1719608 1718860  0 01:18 pts/12   00:00:00 grep --color=auto rust
```

when running lightdm manually
```
root@u2-6758bb5fd-966q7:/# systemctl start lightdm      
root@u2-6758bb5fd-966q7:/# loginctl 
SESSION UID USER    SEAT  TTY
     c8 112 lightdm seat0 

1 sessions listed.
```
Then connection succeeded

**Comment by rustdesk** [comment]
no duplcate please.
