### ISSUE TITLE
mac Connect to mac no sound

### ISSUE THREAD

**Issue by ChicoSir** [rustdesk/rustdesk#5977]
### Bug Description

mac Connect to mac, system 13.6, no sound

Settings inside are turned on audio input devices

I don't know what else to do?

At present, the todesk connection is normal and you can have sound.

### How to Reproduce

NO

### Expected Behavior

If there is a Settings input device in the Settings option, then the playback sound should be heard when connected to the desk

### Operating system(s) on local side and remote side

mac->mac

### RustDesk Version(s) on local side and remote side

1.2.3-1.2.3

### Screenshots

![CleanShot 2023-10-11 at 09 55 33@2x](https://github.com/rustdesk/rustdesk/assets/44128292/622890fd-0e88-42f8-956f-47c6b4d05735)
![CleanShot 2023-10-11 at 09 55 02@2x](https://github.com/rustdesk/rustdesk/assets/44128292/3c13f385-13d6-4377-bd69-7dd250f9083b)

**Comment by rustdesk** [comment]
search duplicate please.
