### ISSUE TITLE
Virtual machine input on the remote computer will be copied infinitely

### ISSUE THREAD

**Issue by CppXL** [rustdesk/rustdesk#5980]
### Bug Description

When I use rustdesk to connect to a remote computer, open the vmware virtual machine on the remote computer and try to log in. After entering a letter in the input box, the letter will be copied infinitely. But this phenomenon will not appear on the remote computer host

### How to Reproduce

Use rustdesk to connect to the remote host, open the VMware virtual machine of the remote host, and try to enter any characters in the virtual machine.

I used a self-built server， rustdesk server ver: 1.1.8

### Expected Behavior

The input is normal and the last entered character will not be copied infinitely.

### Operating system(s) on local side and remote side

windows 10 22h2

### RustDesk Version(s) on local side and remote side

1.2.1 1.2.1

### Screenshots

I entered 1 in the password input box, and then 1 was copied infinitely.

![Snipaste_2023-10-11_15-31-24](https://github.com/rustdesk/rustdesk/assets/36043454/8827bf0e-abea-419d-8326-d295fee27a6b)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4357
