### ISSUE TITLE
RustDesk 1.2.3 window does not show on Ubuntu MATE 22.04 unless I run it with an argument (shown on task bar)

### ISSUE THREAD

**Issue by wodin** [rustdesk/rustdesk#5986]
### Bug Description

I'm doing this on an `Ubuntu MATE 22.04` machine running Xorg.

I had version 1.2.1 installed, but it was crashing when trying to connect to a remote machine. So I downloaded rustdesk-1.2.3-x86_64.deb and installed it.

Now, when I run it, it shows on the task bar, but the window itself does not display. If I hover over it on the task bar, I see the thumbnail of the window correctly. If I click on it, I see the outline of the window minimizing, but do not see the actual contents of the window. Also, while the window is unminimized, it seems to accept mouse input. Or at least, if I click in the area where it would be, the window "behind" the RustDesk window does not respond to the click. So it is as if the RustDesk window is there, but just invisible.

If I run rustdesk from the command line and give it any argument except `--version` (e.g. `-h`, or `--help`, or `-x` or `x`) then the window shows correctly!

After that I downloaded the `AppImage` and it had the same behaviour.

### How to Reproduce

Run `rustdesk` from the command line with no arguments -> invisible window

Run `rustdesk somearg` from the command line -> window shows correctly

### Expected Behavior

When I run RustDesk from the command line with no arguments, or from the Ubuntu MATE menu, I expect the window to be visible.

### Operating system(s) on local side and remote side

Ubuntu MATE 22.04 -> N/A

### RustDesk Version(s) on local side and remote side

1.2.3 -> N/A

### Screenshots

![RustDesk showing thumbnail, but invisible window](https://github.com/rustdesk/rustdesk/assets/4579020/2cf018e0-c14c-4c91-b6eb-c4817138ce6f)

As you can see in the screenshot, the thumbnail shows correctly when hovering over RustDesk on the task bar, but the window is not showing. The window is *not* minimized. It is just invisible. If I click on it in the task bar, I can see the minimize animation. If I click on it again, to unminimize it, it is still invisible.

**Comment by rustdesk** [comment]
How about Flatpak?

**Comment by rustdesk** [comment]
> Run `rustdesk` from the command line with no arguments -> invisible window
> 
> Run `rustdesk somearg` from the command line -> window shows correctly

@fufesou seems some stupid bug related to window hide/show etc

**Comment by wodin** [comment]
> How about Flatpak?

Same behaviour

**Comment by fufesou** [comment]
This is less of an application issue and more of a desktop environment issue. It seems that the window image sometimes doesn't render successfully.

https://github.com/rustdesk/rustdesk/assets/13586388/9bb3dfe7-bc6a-4dab-b268-6448fe7b1519

But the strange thing is that in RustDesk, this problem will only be triggered by opening multiple windows.

RustDesk single window does not have this problem.
I also tried simple example in [rustdesk_desktop_multi_window](https://github.com/rustdesk-org/rustdesk_desktop_multi_window), but couldn't reproduce it.

**Comment by fufesou** [comment]
https://github.com/rustdesk/rustdesk/assets/13586388/2f1ee5b6-13ce-4021-9ba5-b2599d1f6d00

I'm not sure if they're the same issue.

This is a most simple flutter demo. The whole window image is frozen.
The desktop can handle mouse events.

Keeping click fast for a long time may reproduce this issue.

But with multi windows, RustDesk can easily reproduce a frozen window.

**Comment by rustdesk** [comment]
> This is a most simple flutter demo. The whole window image is frozen.

Report to flutter, and ref here.

**Comment by wodin** [comment]
Hi @fufesou thanks for having a look. The behaviour on my machine is different to your video.

I am just running `rustdesk` and the initial window with "Your Desktop" and "Control Remote Desktop" etc. *never* displays for me. Except if I run it with an argument like `rustdesk something`.

I am unable to open more windows when the problem happens, because the initial window is invisible, so I can't click on one of my existing saved connections or something like that.

**Comment by fufesou** [comment]
> I am just running `rustdesk` and the initial window with "Your Desktop" and "Control Remote Desktop" etc. never displays for me.

I cannot reproduce this issue.
But the issues may be the same reason.

> while the window is unminimized, it seems to accept mouse input. Or at least, if I click in the area where it would be, the window "behind" the RustDesk window does not respond to the click. So it is as if the RustDesk window is there, but just invisible.

Can you please try right click on the task bar, then
1. Choose "Move" to see if the window content is frozen. 
2. "Resize" to see if the window comes back?

**Comment by rustdesk** [comment]
> `rustdesk something`.

@fufesou you should test this more times

**Comment by fufesou** [comment]
I've reproduced this issue.

> But the issues may be the same reason.

I'm wrong, they're not the same issue.

I'm trying to find out the reason.

**Comment by OptimusGREEN** [comment]
I can confirm 1.2.3 window doesn't open on macos sonoma on m1 macbook pro either

**Comment by rustdesk** [comment]
Ready in nightly build, https://github.com/rustdesk/rustdesk/releases/tag/nightly

**Comment by Boebbele** [comment]
Dont work with enlightenment 
![2023-12-19-16-00-33-130](https://github.com/rustdesk/rustdesk/assets/77356505/3ed2a0f8-3f1c-43c3-816b-79b158b1fc54)

**Comment by Boebbele** [comment]
Dont work on voidlinux as appimage:

[ingo@voidlinux Downloads]$ ./rustdesk-1.2.4-x86_64.AppImage 
/usr/lib64/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so

(rustdesk:5880): Gdk-CRITICAL **: 16:16:46.826: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-sub-pixel-none.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-yes-antialias.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/48-spacing.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
flutter: launch args: []
flutter: initializing FFI main
flutter: Failed to get documents directory: MissingPlatformDirectoryException(Unable to get application documents directory)
flutter: _appType:main,info1-id:void,info2-name:Void,dir:
flutter: _globalFFI init
flutter: _globalFFI init end
flutter: registerEventHandler native_ui native_ui
flutter: pullAb, force:true, quiet:false

**Comment by Boebbele** [comment]
dont work on voidlinux with flatpak:

[ingo@voidlinux Downloads]$ flatpak run com.rustdesk.RustDesk
sh: Zeile 1: lsmod: Kommando nicht gefunden.

(rustdesk:2): Gdk-CRITICAL **: 16:22:37.073: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
flutter: launch args: []
flutter: initializing FFI main
flutter: _appType:main,info1-id:2be55dc2007cda90aa3bec6a6028dfec,info2-name:Freedesktop SDK,dir:/home/ingo/Dokumente
flutter: _globalFFI init
flutter: _globalFFI init end
flutter: registerEventHandler native_ui native_ui
flutter: pullAb, force:true, quiet:false
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
flutter: pullAb, force:true, quiet:false
flutter: restore lpos: 1366.0/735.0, offset:0.0/0.0
flutter: handled by uni links: false
flutter: [MultiWindowHandler] active window changed: {0}
flutter: Saving frame: null: 1366.0/735.0, offset:0.0/0.0, isMaximized:true, isFullscreen:false

**Comment by rustdesk** [comment]
We still not find the cause, because we can not reproduce it.
Please try out the sciter version, I believe this can work as a workaround. We will continue to dig in.
https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.7-x86_64-sciter.deb
https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.7-x86_64-sciter.flatpak

**Comment by rustdesk** [comment]
Close to favor https://github.com/rustdesk/rustdesk/issues/4844

**Comment by wodin** [comment]
> Close to favor #4844

I am not sure it's the same issue. At least some of the people commenting there seem to be saying that it works when they run it from the command line. In my case it was not working anywhere, except if I specified any argument on the command line.

I will try the sciter version (maybe tomorrow)

**Comment by rustdesk** [comment]
I will also ask them run with an argument.

**Comment by wodin** [comment]
I have done some testing.

The flatpak nightly version (non-sciter) works. The flatpak sciter nightly version also works. Not sure if this is a valid test, though, because it doesn't seem to directly run a "rustdesk" binary.

The .deb nightly sciter version works without an extra command line argument! However, it crashes if I give it one:
```console
$ rustdesk 
INFO:TIS: scaleFactor 1
INFO:TIS: current platform: Linux
INFO:TIS: is_xfce:  false
$ rustdesk test
corrupted size vs. prev_size in fastbins
Aborted (core dumped)
```

The non-sciter .deb nightly version still fails. But this time it still fails if I give it an argument.
*without an argument*
```console
$ rustdesk

** (rustdesk:151938): WARNING **: 15:39:44.587: Failed to start Flutter renderer: Unable to create a GL context

** (rustdesk:151938): WARNING **: 15:40:12.469: Unable to retrieve framework response: No engine to send to
^C
```
*with an argument*
```console
$ rustdesk test

** (rustdesk:151531): WARNING **: 15:39:26.216: Failed to start Flutter renderer: Unable to create a GL context

** (rustdesk:151531): WARNING **: 15:39:29.454: Unable to retrieve framework response: No engine to send to

** (rustdesk:151531): WARNING **: 15:39:31.782: Unable to retrieve framework response: No engine to send to
^C
```

The AppImage nightly version fails in the same way as the .deb

**Comment by rustdesk** [comment]
The flatpak/deb/appimage share the same binary, but Flatpak runs in its virtual env. You can imagine it runs in an Ubuntu.

**Comment by rustdesk** [comment]
> Flutter renderer: Unable to create a GL context

This has told the reason clearly, Frankly we have no ability to fix this, we have to wait for Flutter.

https://github.com/flutter/flutter/issues/106941 though this is arm.

**Comment by wodin** [comment]
I'm not too worried about it, since it's working for me now.
However I don't understand why adding an arbitrary command line argument fixed it (at least for version 1.2.3)

**Comment by 21pages** [comment]
https://github.com/flutter/flutter/issues/76178#issuecomment-1356657603, run `EGL_LOG_LEVEL=debug rustdesk` and paste the log.

**Comment by CuchulainnPrimus** [comment]
For anyone landing here from a search with the same symptom on a **current**
system (taskbar entry present, window never drawn): if you are on Wayland with
an NVIDIA GPU and using the Flathub build, this is most likely a different
cause than the one in this thread.

The Flatpak grants `--socket=x11` but not `--socket=wayland`, so the GTK/Flutter
frontend is forced onto XWayland, where `GtkGLArea` cannot get a GL context on
NVIDIA (<https://gitlab.gnome.org/GNOME/gtk/-/issues/4950>). Flutter never gets
a renderer, so the window is created, mapped and focused but never painted:

```
Gdk-CRITICAL **: gdk_gl_context_make_current: assertion 'GDK_IS_GL_CONTEXT (context)' failed
WARNING **: Failed to initialize GLArea: No available configurations for the given pixel format
```

Workaround:

```sh
flatpak override --user --socket=wayland --env=GDK_BACKEND=wayland com.rustdesk.RustDesk
```

Filed against the Flathub packaging with a suggested manifest change:
flathub/com.rustdesk.RustDesk#36

Note the window may also *report* an off-screen position under XWayland (the
position is scaled 2x, the size is not). That is a red herring — no frame is
ever drawn, so moving it makes no difference.
