### ISSUE TITLE
Do not show right vertical and bottom scroll bar while using fullscreen mode

### ISSUE THREAD

**Issue by jemyzhang** [rustdesk/rustdesk#599]
Linux version under ubuntu 22.04
When entering into fullscreen mode, the scrollbar of rustdesk will overlay the remote UI elements and block the normal actions.

Is there anyway to hide the scrollbar of rustdesk client? Thanks!

**Comment by rustdesk** [comment]
@SoLongAndThanksForAllThePizza we may take this into account in our new design.

**Comment by bigben446** [comment]
the same problem

**Comment by emericv** [comment]
same issue

**Comment by rustdesk** [comment]
can you try out the nightly build? it has mouse follow mode, which does not use scrollbar.

**Comment by emericv** [comment]
> can you try out the nightly build? it has mouse follow mode, which does not use scrollbar.

Thanks for your reply! I will try this asap...

**Comment by emericv** [comment]
> can you try out the nightly build? it has mouse follow mode, which does not use scrollbar.

I have tested just now and I adopt the new UX! Great work!
