### ISSUE TITLE
When the mouse is connected, opening floating keyboard in the Android client causes the pointer to be misplaced.

### ISSUE THREAD

**Issue by Cybercll** [rustdesk/rustdesk#5995]
### Bug Description

When the mouse is connected, opening floating keyboard in the Android client causes the pointer to be misplaced.

RD version: Android RD 1.2.3 Nightly
System version: Android 13 Miui 14.0.12

What have I tried
1. click the down arrow (x)
2. turn off floating keyboard(✓)

### How to Reproduce

How to reproduce bugs
1. connect to remote desktop
2. connect mouse device
3. click keyboard button(I enabled floating keyboard,keyboard sougou input)
4. pointer is misplaced.

### Expected Behavior

When you click the down arrow, the program resumes full-screen mode.

### Operating system(s) on local side and remote side

ANDROID13 to Windows10

### RustDesk Version(s) on local side and remote side

1.2.3nightly to 1.2.3

### Screenshots

phenomenon
![Screenshot_2023-10-12-10-01-10-963_com carriez flutter_hbb](https://github.com/rustdesk/rustdesk/assets/25275727/b64d1d5e-b393-47af-8461-30ff5056ab1b)

**Comment by rustdesk** [comment]
> * click keyboard button(I enabled floating keyboard,keyboard sougou input)

What does this mean? What is flaoting keyboard? no misplace if no floating keyboard?

**Comment by Cybercll** [comment]
> keyboard
my default keyboard have this function(can see in screenshot), maybe RD cannot recognize the keyboard have already closed.
![Screenshot_2023-10-12-11-44-52-297_com carriez flutter_hbb](https://github.com/rustdesk/rustdesk/assets/25275727/e9377afa-7efb-43cf-a583-eeceb20e3c73)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893

**Comment by rustdesk** [comment]
Appoligies, we have no resource to reproduce your issue.

**Comment by Cybercll** [comment]
> > * click keyboard button(I enabled floating keyboard,keyboard sougou input)
> 
> What does this mean? What is flaoting keyboard? no misplace if no floating keyboard?

Additionaly using a mouse to click keyboard button will simultaneously act a click on remote device. This is not what I expected.
