### ISSUE TITLE
Moving cursor will cause clicking

### ISSUE THREAD

**Issue by BeingNoAbility** [rustdesk/rustdesk#6004]
### Bug Description

Moving the cursor will cause clicking

### How to Reproduce

Move the cursor

### Expected Behavior

It shouldn't cause clicking

### Operating system(s) on local side and remote side

Android -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

https://github.com/rustdesk/rustdesk/assets/105844676/bc6647d7-5172-4fc7-8eef-f56663769673

https://github.com/rustdesk/rustdesk/assets/105844676/d5351176-d4c4-429c-8f2e-91a1fb83df0d

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893

**Comment by rustdesk** [comment]
Not all android has this, so you need to tell your android vendor and model.

**Comment by BeingNoAbility** [comment]
Tried on two phones—same problem.
Redmi K50 Pro: Miui 14.0.12
RedMagic 8s Pro: RedMagicOS8.0.19MR3
