### ISSUE TITLE
Null check missing

### ISSUE THREAD

**Issue by kaushal1717** [rustdesk/rustdesk#6017]
### Bug Description

In the given screenshot loadString method we assign String type to key parameter but we are assigning String? as shown. It can cause build errors in the program.

### How to Reproduce

it is shown in the given screenshot

### Expected Behavior

There should be a null check on the pos parameter so we can not get possible build errors.

### Operating system(s) on local side and remote side

MacOS 13.5.2 -> osx

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.1.8

### Screenshots

<img width="1364" alt="Screenshot 2023-10-13 at 11 28 36 AM" src="https://github.com/rustdesk/rustdesk/assets/121810303/3d27e6a4-6f2c-49a5-a530-01beac524ad3">

### Additional Context

Assign this issues to me so I can fix this

**Comment by rustdesk** [comment]
Why can not we see the build error?

**Comment by kaushal1717** [comment]
<img width="1440" alt="Screenshot 2023-10-13 at 12 26 45 PM" src="https://github.com/rustdesk/rustdesk/assets/121810303/20af6ec2-19a9-4ddf-acbd-a1b8c7fd1d25">

**Comment by kaushal1717** [comment]
okay working on it

**Comment by rustdesk** [comment]
My ide does not report error since pos ??= bind.getLocalFlutterOption(k: kWindowPrefix + type.name); making sure it is not null. Changing to pos! will cause error in my ide.
