### ISSUE TITLE
Able to access and execute remote end RustDesk control panel settings through Tab and Enter

### ISSUE THREAD

**Issue by DavidKalashnikov47** [rustdesk/rustdesk#6025]
### Bug Description

The grey-out of the remote end RustDesk control panel can be broken through utilizing Tab, Arrow Keys and Enter.

### How to Reproduce

1. Remote into a remote desktop with one-time-password
2. Click on the RustDesk control window to focus onto it
3. Click the hamburger icon on the right of the title bar
4. Navigate the menu using Tab (tap 4 times to go through the 3 other title bar buttons to reach the main items)
5. Use Arrow Keys and/or Tab to navigate around the menu

### Expected Behavior

So long the client Windows user side is already an admin, you can access to admin-only items, and change the options in the menu using enter
The grey-out for prevent mouse access seems to break when any option involving pop-out window is toggled, however the grey-out would reactivate after the clicking "cancel" button (not tested yet for the close button of the pop-out), otherwise the grey-out would stay disabled.

### Operating system(s) on local side and remote side

Windows 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

https://github.com/rustdesk/rustdesk/assets/24609332/abe06b3a-d681-4f75-b332-018a76f16a34

I would like to apology for the heretic bright theme on the client side since it is in the office and the screen is rather dim.

Also, said attempt also successfully altered the permanent password, that I have to use the altered one for next connection.

**Comment by rustdesk** [comment]
we will remove this greyout soon. there are duplicate discussions and issues about this.
