### ISSUE TITLE
Can't move mouse (UAC?) and can only connect if RustDesk window is open

### ISSUE THREAD

**Issue by Balls0fSteel** [rustdesk/rustdesk#6034]
### Bug Description

**I have four issues but I am not sure if I should open 4 tickets. Don't want to spam the Issue Tracker.**

1) Mouse Movement. 
This looks like an issue with UAC. Every time a window is open with UAC, I can't move the mouse, I can't interact with the windows. The remote user can do what I say, but I can't "affect" the windows.

2) UAC issue:
It's related, or the same as the mouse movement problem. I can't see UAC prompts, I can't answer them, etc. So I can get stuck with RustDesk if anything with UAC comes up.

3) Can't connect unless the window is open.
This is a weird one. On some PCs I installed RustDesk and it's perfection. But on some, I have to open the window from the tray, otherwise I can't connect. My PC will say machine offline, unless the remote user clicks the tray icon. This especially happens on two laptops. One laptop runs Windows 10 LTSC, one runs Windows 10 Pro. They are different laptops, users, everything. Yet the bug is the same.

4) Service is not running. 
This happens on my Windows 11 Pro machine. I installed RustDesk normally. I have UAC on default, never touched anything. Yet, my PC boots and even if my user is auto-login and my whole PC loads, the tray icon is just missing. If I open it, it tells me Service is not running. But Service is set to Auto in Services. ??? Can't really figure this one out.

Some info:
- I don't want to sound like I am running RustDesk on a 1000 PCs. We are talking about 10 computers at best. It's pretty much for my "personal use".
- I consider myself somewhat savvy but I can't really figure out what's causing these issues.
- I run my relay through Docker on my own server and it's set on all these computers.

### How to Reproduce

1)
a) Install Rustdesk on a Windows 10 (maybe 11 too)
b) Connect to it remotely
c) If any application is elevated to admin through, you will not be able to interact with it. Not only that, you can't affect the remote PC anymore if this happens. Like you can't click out of it, click on other things, etc.

2)
a) Install Rustdesk on a Windows 10 (maybe 11 too)
b) Connect to it remotely
c) Have a UAC prompt open like an installation of an application
d) You won't see the prompt

3) 
a) Install RustDesk client
b) Let PC boot
c) RustDesk tray is there
d) But my PC will say it's offline. As soon as I open the app by clicking the tray icon, the machine becomes reachable.

4)
a) Windows 11
b) Install RustDesk
c) Machine will never go online unless you open tray AND click "start service" (service IS enabled and set to auto)

### Expected Behavior

UAC pop-ups should show normally. 

### Operating system(s) on local side and remote side

Windows 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.2

### Screenshots

none

**Comment by rustdesk** [comment]
From your description, I believe your installation is not complete on controlled side, the background services have not been installed successfully, may be prohibited by security software etc.

You can open task manager, go to services tab, check if there is "RustDesk Service" and running.

**Comment by rustdesk** [comment]
Above pic is this machine.

> Can't connect unless the window is open.
This is a weird one. On some PCs I installed RustDesk and it's perfection. But on some, I have to open the window from the tray, otherwise I can't connect. My PC will say machine offline, unless the remote user clicks the tray icon. This especially happens on two laptops. One laptop runs Windows 10 LTSC, one runs Windows 10 Pro. They are different laptops, users, everything. Yet the bug is the same.

**Comment by rustdesk** [comment]
> 3\. This is a weird one. On some PCs I installed RustDesk and it's perfection.

It is not weird, that's windows, nothing is impossible.

**Comment by rustdesk** [comment]
> uber admin rights

What's this?

**Comment by rustdesk** [comment]
We do not request UAC elevation if running as services after installation.

**Comment by rustdesk** [comment]
> Every time I open my PC, I have to open RustDesk and then click start service in there

This is truely wierd. Have you ever disabled service before manually?

**Comment by rustdesk** [comment]
Can you check how many RustDesk processes there in task manager if you do not open any RustDesk window. Normally, there are two processes running as `System` users, one is `rustdesk --service`, the other one is `rustdesk --server`.

**Comment by rustdesk** [comment]
You do not need open new issue, you are encountering the same unknow issue.

**Comment by rustdesk** [comment]
The above issues happend on "UAC" disabled machines?

**Comment by rustdesk** [comment]
Close since no response.
