### ISSUE TITLE
Strange behavior when trying to connect to an existing connection, introduced with version 1.2.4 (Nightly)

### ISSUE THREAD

**Issue by Jemmota** [rustdesk/rustdesk#6049]
### Bug Description

Until version 1.2.3, there was a behavior that I consider normal when trying to open an existing connection: The existing connection window is brought to the foreground. This is the correct behavior, in my opinion. However, as of version 1.2.4 (Nightly) a strange behavior started to occur.  When we trying to open an existing connection a new window opens, however, it doesn't display anything and it is not possible to do anything in this new window (just close it).

### How to Reproduce

Using version 1.2.4, try to open a connection that already exists (see the video).

### Expected Behavior

Using version 1.2.4 (nightly), when we click "connect" in a session that already exists, a new window will be created (or several windows, depending on how many times you try to connect). It is an empty window, and it is not possible to do anything in it. The "normal" behavior (up to version 1.2.3) would be to simply RustDesk detect that the connection is already open and bring the existing connection window to the foreground, without creating a new window (as was the case until version 1.2.3).

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.2.4 (Nightly) 

### Screenshots

https://github.com/rustdesk/rustdesk/assets/129885668/cc382689-a6a6-4e81-a93c-fe336d0a81f0

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
Close as fix merged

**Comment by Jemmota** [comment]
The problem has been resolved. Great job. Thank you.
