### ISSUE TITLE
macos `fn` becomes stuck

### ISSUE THREAD

**Issue by bilogic** [rustdesk/rustdesk#6060]
### Bug Description

When connecting RD1.2.3 from mac to mac, the `fn` key often becomes stuck. If the controller side presses `c`, it becomes `fn + c` on the controlled side, cause the command center to launch.

### How to Reproduce

Unsure exact steps, but both machines were macos

### Expected Behavior

`fn` should not be stuck, pressing `c` should send only `c` to the controlled side.

### Operating system(s) on local side and remote side

osx -> osx

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

don't have

**Comment by bilogic** [comment]
I'm not sure, I was on 1.1.9 connecting to 1.2.3, then I tried 1.2.3 to 1.2.3. I can try 1.1.9 to 1.1.9 tomorrow. First time connecting from mac to mac. Unsure how to reproduce, but the way to fix it was to disconnect and reconnect immediately. We are using VSCode, so pressing a lot of shortcut keys, e.g. cmd, option, shift and control, then suddenly strange things happen:

1. fn + d = dictation
2. fn + f = full screen
3. fn + c = command center
4. fn + h = hide all windows

**Comment by rustdesk** [comment]
have to move to https://github.com/rustdesk/rustdesk/issues/4367 since hard reproduce.

**Comment by rustdesk** [comment]
We put a fix on nightly build today, please test https://github.com/rustdesk/rustdesk/releases/tag/nightly

**Comment by bilogic** [comment]
will test it out thanks
