### ISSUE TITLE
Screen resolution problem. Screen goes black second time connect

### ISSUE THREAD

**Issue by buestad** [rustdesk/rustdesk#6071]
### Bug Description

I have a host running 1920x1080 and a client running 1680x1050. If I log in to the host and change to full screen and change the resolution in the RustDesk top menu to 1680x1050 it works fine the first time connecting. 

The next time I connect the screen is black on the client. I can see the mouse moving on the host and I notice that the resolution on the host has changed, but the resolution on the client RustDesk menu is still 1920x1080. It is also not possible too change the resolution on the RustDesk menu

To fix this I have to uninstall RustDesk on the host and remove all settings in C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk

### How to Reproduce

See desc

### Expected Behavior

See desc

### Operating system(s) on local side and remote side

windows 10 -> windows 10

### RustDesk Version(s) on local side and remote side

1.2.3 and 1.2.4

### Screenshots

First time:
![image](https://github.com/rustdesk/rustdesk/assets/18750265/2c1468db-c42b-4093-a9ed-b5b8973b0e8f)

Second time:
![image](https://github.com/rustdesk/rustdesk/assets/18750265/e05d3f7f-d3f7-4952-8cd0-efeb07293e24)

**Comment by rustdesk** [comment]
@fufesou

**Comment by buestad** [comment]
About the deletion of host data. It might just be that the host gets new ID, and the settings is stored on the client?

**Comment by rustdesk** [comment]
Close as fix merged
