### ISSUE TITLE
Web client "ReferenceError: onGlobalEvent is not defined"

### ISSUE THREAD

**Issue by chunxueer** [rustdesk/rustdesk#608]
Hi ，An error  "ReferenceError: onGlobalEvent is not defined" occurred while I was running "yran dev"，
details are as follows。

Thanks !

![image](https://user-images.githubusercontent.com/13824852/170227849-cdf7e66d-9e70-4ef4-8fa8-f6b7be3e8e17.png)

![image](https://user-images.githubusercontent.com/13824852/170228057-2ed17fe7-7995-4152-a7a7-4d8ed64d64a6.png)

![image](https://user-images.githubusercontent.com/13824852/170228227-e15f3e98-e084-438d-ae40-4514fdfe0c05.png)

**Comment by Heap-Hop** [comment]
run with flutter.
```
cd flutter/web/js
yarn build
flutter run -d chrome
````

**Comment by rustdesk** [comment]
https://rustdesk.com/docs/en/dev/build/web/
