### ISSUE TITLE
Message being typed is cleared when remote message is received

### ISSUE THREAD

**Issue by tytouf** [rustdesk/rustdesk#609]
**Describe the bug you encountered:**

When chatting, I start writing a new message and during the typing a remote message is received and the entry box gets cleared.

**What did you expect to happen instead?**

Do not clear the entry box while I'm typing.

**How did you install `RustDesk`?**

From website Download button.

**RustDesk version and environment**

On Ubuntu, both remote and client version 1.1.9

**Comment by asur4s** [comment]
I have reproduced the bug, let me try. Thanks

**Comment by rustdesk** [comment]
Great

**Comment by asur4s** [comment]
It has been resolved in version 1.20. The version can be obtained by compiling from source.
![bug](https://user-images.githubusercontent.com/99897242/170242812-c2007bc7-3b76-4ab4-8d21-4899df19ecd6.gif)

**Comment by rustdesk** [comment]
@asur4s Good job!

**Comment by rustdesk** [comment]
@asur4s https://github.com/rustdesk/rustdesk/issues/567 and https://github.com/rustdesk/rustdesk/issues/406 are both troublesome international keyboard issues, wondering if you have interests.

**Comment by rustdesk** [comment]
And we also wanna rewrite [pynput](https://github.com/rustdesk/rustdesk/blob/master/pynput_service.py) with Rust, and prepare for wayland support (uinput does support wayland).

**Comment by asur4s** [comment]
Nice, It is not friendly for newbie to solve "good first issue" in the repo. 

e.g. #568 #485

**Comment by asur4s** [comment]
> we also wanna rewrite [pynput](https://github.com/rustdesk/rustdesk/blob/master/pynput_service.py) with Rust

Ok, I will try. You can try to write these plans in [milestone](https://docs.github.com/en/enterprise-cloud@latest/issues/using-labels-and-milestones-to-track-work/about-milestones).

**Comment by rustdesk** [comment]
> milestone

Good suggestion, it is what I wanted to try.

**Comment by tytouf** [comment]
Thanks @asur4s for the prompt reply and fix.

**Comment by glasge** [comment]
The defect is observed again. Windows 11 platform, rustdesc version 1.4.5.
The x86-64 version works correctly in both directions.
The x86-32 version, which is on sciter, works correctly only in one direction. 
When sending from the slave to the master, the unsent message is deleted from the master.
When sending from the master to the slave, everything is fine - the unsent message is not deleted from the slave.

**Comment by rustdesk** [comment]
I do not understand, a video please.

**Comment by glasge** [comment]
The video is the same as in this post:
https://github.com/rustdesk/rustdesk/issues/609#issuecomment-1137075973

I understand that this is the corrected version 1.2.0.
When sending 456 from the left half, 123 is not erased from the right half.
But if you write 456 on the left before sending 123 from the right half, then after sending 123, 456 will be erased.
This is how the x86-32 version on sciter works.
The x86-64 version works correctly in both directions.
I don't know how else to explain it...

**Comment by rustdesk** [comment]
who is slave, who is master? who's unsent message is erased?

**Comment by glasge** [comment]
I probably chose the wrong words..
Would client and host be more correct?
Try to reproduce the situation in the video from #609 (comment).
Write 456 in the left half, and send 123 from the right half.
On the x86-32 version that uses sciter, 456 is deleted after sending and receiving 123.

**Comment by glasge** [comment]
I am using sciter.dll version 4.4.8.23,
but the situation is also reproduced on the rustdesk-1.4.5-x86-sciter.exe build.

**Comment by rustdesk** [comment]
Do you mean you build from our source ,and ask us to fix bug for you?

**Comment by rustdesk** [comment]
> using a custom rustdesc build for the x86-32 architecture.

How do you build it?

**Comment by glasge** [comment]
Something like that...
https://github.com/rustdesk/rustdesk/blob/97de1c0ee6a43907e3477ecc463287785f4462d9/.github/workflows/flutter-build.yml#LL186C16-L186C16

**Comment by rustdesk** [comment]
So please test this https://github.com/rustdesk/rustdesk/tree/sciter-msgbox-unsent-message-erased. It is written by codex. If it does not work, I hope you can fix it with AI.

**Comment by glasge** [comment]
Thanks for the tip! :)
I'll wait for version 1.4.6, maybe it will work...
If not, then of course I'll call on AI for help.

**Comment by rustdesk** [comment]
It won't be in 1.4.6 if you do not test it.

**Comment by glasge** [comment]
> So please test this https://github.com/rustdesk/rustdesk/tree/sciter-msgbox-unsent-message-erased.

This fix helped.
