### ISSUE TITLE
Keys 6 and 7 not working when "Swap control-command key" is enabled

### ISSUE THREAD

**Issue by quadbyte** [rustdesk/rustdesk#6092]
### Bug Description

On a Mac remote with (from Win local), when using "Swap control-command key"  my "6" and "7" keys output a ";"

Also the ";" outputs a "7"

### How to Reproduce

Connect from Win local to Mac Remote and try to type 6 or 7  anywhere in MacOS.

### Expected Behavior

Should be able to type numbers as usual

### Operating system(s) on local side and remote side

Windows 11 -> Mac OS 14

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/2170677/ada968ea-adf5-4ac3-8a10-c8e4a9af21e9)

**Comment by fufesou** [comment]
confirmed

**Comment by rustdesk** [comment]
will reopen if you still has issue without legacy mode.

**Comment by quadbyte** [comment]
Thanks, working fine in Map mode.

**Comment by goofygoofs** [comment]
@rustdesk do you have the map mode functionality on android client? I saw it's available on windows but not android. I've tried the nightly build as well
