### ISSUE TITLE
There was no response when running the self built trustdesk!

### ISSUE THREAD

**Issue by yunfengwangluo** [rustdesk/rustdesk#6100]
### Bug Description

I built Rustdesk on Windows 11 without any response task managers or related processes when running the program "target/release/Rustdesk" There were no error messages either!

### How to Reproduce

The issue with recompilation still persists

### Expected Behavior

Expect the Rustdesk window to appear

### Operating system(s) on local side and remote side

windows 11

### RustDesk Version(s) on local side and remote side

1.73.0

### Screenshots

![{BBC25227-EC21-4552-9BBF-92E1D5A5CFB6}](https://github.com/rustdesk/rustdesk/assets/50440724/686ca1d1-1837-4878-a398-024cdf3e5b3e)

**Comment by rustdesk** [comment]
#763
