### ISSUE TITLE
Unable to connect to Linux system with active Teradici pcoip session - Failed to get capturer display info

### ISSUE THREAD

**Issue by slm-sean** [rustdesk/rustdesk#6121]
### Bug Description

When attempting to establish a remote session using rustdesk to a headless system that is running a teradici pocip session, the rustdesk client returns the following error: Failed to get capturer display info

The output of systemctl status rustdesk contains these messages:
```
Oct 20 15:54:02 ****** sudo[162799]:     root : problem with defaults entries ; TTY=unknown ; PWD=/ ; USER=**** ;
Oct 20 15:54:02 ****** sudo[162799]:     root : TTY=unknown ; PWD=/ ; USER=**** ; ENV=XDG_RUNTIME_DIR=/run/user/1365881150 ; COMMAND=/usr/lib/rustdesk/rustdesk --cm
```

I noticed that the session number of the user logged in with Teradici is :100. Not sure if that contributes to the issue.

Teradici also adds the following configs to X11 to create a dummy monitor.

```
# Override for 'M', 'P', and RTX Series Quadro cards when in pcoip remote mode
Section "Screen"
  Identifier "dummy_screen"
  Device "dummy_videocard"
  Option "UseDisplayDevice" "DFP-0,DFP-2,DFP-4,DFP-6"
  Option "ConnectedMonitor" "DFP-0,DFP-2,DFP-4,DFP-6"
  Option "Monitor-DFP-0" "Monitor0"
  Option "Monitor-DFP-2" "Monitor1"
  Option "Monitor-DFP-4" "Monitor2"
  Option "Monitor-DFP-6" "Monitor3"
  Monitor "Monitor0"
EndSection
```

### How to Reproduce

Try to establish a connection with rustdesk to a workstation running Teradici pcoip

### Expected Behavior

Rustdesk capture the virtual display being used by Teradici.

### Operating system(s) on local side and remote side

Rocky Linux 8

### RustDesk Version(s) on local side and remote side

1.2.4 -> 1.2.4

### Screenshots

<img width="434" alt="image" src="https://github.com/rustdesk/rustdesk/assets/148557968/e4e8cb25-c1cc-4fc0-915a-7182da22b18f">

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
