### ISSUE TITLE
 exec flutter/ndk_arm64.sh:  could not find native static library `aom`

### ISSUE THREAD

**Issue by aswjh** [rustdesk/rustdesk#6129]
### Bug Description

cd rustdesk
rustup target add aarch64-linux-android
cargo install cargo-ndk
VCPKG_ROOT=$HOME/vcpkg ANDROID_NDK_HOME=$HOME/android-ndk-r23c flutter/ndk_arm64.sh

error: could not find native static library `aom`, perhaps an -L flag is missing?

### How to Reproduce

https://rustdesk.com/docs/zh-cn/dev/build/android/

### Expected Behavior

build for android

### Operating system(s) on local side and remote side

debian 12

### RustDesk Version(s) on local side and remote side

git clone https://github.com/rustdesk/rustdesk

### Screenshots

error: could not find native static library `aom`, perhaps an -L flag is missing?

**Comment by rustdesk** [comment]
#763
