### ISSUE TITLE
[BUG] White Client Window (again)

### ISSUE THREAD

**Issue by Eruthon** [rustdesk/rustdesk#6139]
### Bug Description

Since 09/2023 my RustDesk clients 1.22-1.24 on NVidia machines open as white window same as in this problem: https://github.com/rustdesk/rustdesk/issues/418. Most probably NVidia driver issue.

### How to Reproduce

Run RustDesk client with NVidia driver released since 09/2023. (not much to go on on my end)

### Expected Behavior

No white window.

### Operating system(s) on local side and remote side

Windows 11 22H2 -> whatever

### RustDesk Version(s) on local side and remote side

1.22-1.24  -> whatever

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/37985268/48c09d41-5ef3-4047-b7df-28f4cf8a7f2b)

**Comment by Eruthon** [comment]
Also if I start RustDesk from the downloaded .exe, it shows correctly.

**Comment by 21pages** [comment]
What does `downloaded .exe` mean?

**Comment by rustdesk** [comment]
duplicate: https://github.com/rustdesk/rustdesk/issues/5108

**Comment by rustdesk** [comment]
please move discussion to #5108

**Comment by Eruthon** [comment]
Got it working by setting rustdesk.exe to run as admin
