### ISSUE TITLE
Android HMI crashes

### ISSUE THREAD

**Issue by Blueforcer** [rustdesk/rustdesk#6140]
### Bug Description

Ive installed Rustdesk on our Android HMI. It kinda works but it crashes very often when i start to send inputs.
Its a 7" RK3288 device with Android 7.1.2

`delta:1
delta:1
delta:1
delta:0
delta:1
delta:1
delta:1
delta:1
delta:1
delta:1
delta:0
delta:1
end gesture x:672 y:162 time:801
jni::wrapper::java_vm::vm: Attached daemon thread tokio-runtime-worker (ThreadId(13)). 4 threads attached
Error connecting rild-nmea (Connection refused)
art/runtime/indirect_reference_table.cc:132] JNI ERROR (app bug): local reference table overflow (max=512)
art/runtime/indirect_reference_table.cc:132] local reference table dump:
art/runtime/indirect_reference_table.cc:132]   Last 10 entries (of 512):
art/runtime/indirect_reference_table.cc:132]       511: 0x12e707e0 java.lang.String "mouse"
art/runtime/indirect_reference_table.cc:132]       510: 0x12e707c0 java.lang.String "mouse"
art/runtime/indirect_reference_table.cc:132]       509: 0x12e707a0 java.lang.String "mouse"
art/runtime/indirect_reference_table.cc:132]       508: 0x12e70780 java.lang.String "mouse"
art/runtime/indirect_reference_table.cc:132]       507: 0x12e70760 java.lang.String "mouse"
art/runtime/indirect_reference_table.cc:132]       506: 0x12e70740 java.lang.String "mouse"
art/runtime/indirect_reference_table.cc:132]       505: 0x12e70720 java.lang.String "mouse"
art/runtime/indirect_reference_table.cc:132]       504: 0x12e70700 java.lang.String "mouse"
art/runtime/indirect_reference_table.cc:132]       503: 0x12e706e0 java.lang.String "mouse"
art/runtime/indirect_reference_table.cc:132]       502: 0x12e706c0 java.lang.String "mouse"
art/runtime/indirect_reference_table.cc:132]   Summary:
art/runtime/indirect_reference_table.cc:132]       512 of java.lang.String (512 unique instances)
art/runtime/indirect_reference_table.cc:132] 
art/runtime/runtime.cc:422] Runtime aborting...
art/runtime/runtime.cc:422] Aborting thread:
art/runtime/runtime.cc:422] "Thread-7" prio=10 tid=24 Runnable
art/runtime/runtime.cc:422]   | group="" sCount=0 dsCount=0 obj=0x12c4fee0 self=0xa4f59700
art/runtime/runtime.cc:422]   | sysTid=1705 nice=-10 cgrp=default sched=0/0 handle=0x9395a920
art/runtime/runtime.cc:422]   | state=R schedstat=( 1034589051 122627290 1388 ) utm=65 stm=37 core=0 HZ=100
art/runtime/runtime.cc:422]   | stack=0x9375c000-0x9375e000 stackSize=2046KB
art/runtime/runtime.cc:422]   | held mutexes= "abort lock" "mutator lock"(shared held)
art/runtime/runtime.cc:422]   native: #00 pc 003537b1  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+128)
art/runtime/runtime.cc:422]   native: #01 pc 00333c65  /system/lib/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+304)
art/runtime/runtime.cc:422]   native: #02 pc 00326c51  /system/lib/libart.so (_ZNK3art10AbortState10DumpThreadERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEPNS_6ThreadE+24)
art/runtime/runtime.cc:422]   native: #03 pc 00326a9b  /system/lib/libart.so (_ZNK3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+362)
art/runtime/runtime.cc:422]   native: #04 pc 0031d7e1  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+92)
art/runtime/runtime.cc:422]   native: #05 pc 000b5503  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+1134)
art/runtime/runtime.cc:422]   native: #06 pc 001bd92f  /system/lib/libart.so (_ZN3art22IndirectReferenceTable3AddEjPNS_6mirror6ObjectE+194)
art/runtime/runtime.cc:422]   native: #07 pc 002666f3  /system/lib/libart.so (_ZN3art3JNI14GetObjectClassEP7_JNIEnvP8_jobject+426)
art/runtime/runtime.cc:422]   native: #08 pc 00238f0b  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #09 pc 0024555b  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #10 pc 00093c51  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #11 pc 0008bd3f  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #12 pc 0009ed41  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #13 pc 0009f6bb  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #14 pc 000ed159  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #15 pc 00068513  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #16 pc 008cdda9  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #17 pc 008cce21  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #18 pc 008d2261  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #19 pc 008c2349  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #20 pc 008c2e55  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #21 pc 009d7625  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #22 pc 00047323  /system/lib/libc.so (_ZL15__pthread_startPv+22)
art/runtime/runtime.cc:422]   native: #23 pc 00019e5d  /system/lib/libc.so (__start_thread+6)
art/runtime/runtime.cc:422]   (no managed stack frames)
art/runtime/runtime.cc:422] Dumping all threads without appropriate locks held: thread list lock
art/runtime/runtime.cc:422] All threads:
art/runtime/runtime.cc:422] DALVIK THREADS (25):
art/runtime/runtime.cc:422] "Thread-7" prio=10 tid=24 Runnable
art/runtime/runtime.cc:422]   | group="" sCount=0 dsCount=0 obj=0x12c4fee0 self=0xa4f59700
art/runtime/runtime.cc:422]   | sysTid=1705 nice=-10 cgrp=default sched=0/0 handle=0x9395a920
art/runtime/runtime.cc:422]   | state=R schedstat=( 1094463133 127375332 1406 ) utm=68 stm=40 core=0 HZ=100
art/runtime/runtime.cc:422]   | stack=0x9375c000-0x9375e000 stackSize=2046KB
art/runtime/runtime.cc:422]   | held mutexes= "abort lock" "mutator lock"(shared held)
art/runtime/runtime.cc:422]   native: #00 pc 003537b1  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+128)
art/runtime/runtime.cc:422]   native: #01 pc 00333c65  /system/lib/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+304)
art/runtime/runtime.cc:422]   native: #02 pc 00345d6f  /system/lib/libart.so (_ZN3art14DumpCheckpoint3RunEPNS_6ThreadE+622)
art/runtime/runtime.cc:422]   native: #03 pc 0033fcfd  /system/lib/libart.so (_ZN3art10ThreadList13RunCheckpointEPNS_7ClosureE+336)
art/runtime/runtime.cc:422]   native: #04 pc 0033f9f7  /system/lib/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEb+586)
art/runtime/runtime.cc:422]   native: #05 pc 00326aa5  /system/lib/libart.so (_ZNK3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+372)
art/runtime/runtime.cc:422]   native: #06 pc 0031d7e1  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+92)
art/runtime/runtime.cc:422]   native: #07 pc 000b5503  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+1134)
art/runtime/runtime.cc:422]   native: #08 pc 001bd92f  /system/lib/libart.so (_ZN3art22IndirectReferenceTable3AddEjPNS_6mirror6ObjectE+194)
art/runtime/runtime.cc:422]   native: #09 pc 002666f3  /system/lib/libart.so (_ZN3art3JNI14GetObjectClassEP7_JNIEnvP8_jobject+426)
art/runtime/runtime.cc:422]   native: #10 pc 00238f0b  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #11 pc 0024555b  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #12 pc 00093c51  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #13 pc 0008bd3f  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #14 pc 0009ed41  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #15 pc 0009f6bb  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #16 pc 000ed159  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #17 pc 00068513  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #18 pc 008cdda9  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #19 pc 008cce21  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #20 pc 008d2261  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #21 pc 008c2349  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #22 pc 008c2e55  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #23 pc 009d7625  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (???)
art/runtime/runtime.cc:422]   native: #24 pc 00047323  /system/lib/libc.so (_ZL15__pthread_startPv+22)
art/runtime/runtime.cc:422]   native: #25 pc 00019e5d  /system/lib/libc.so (__start_thread+6)
art/runtime/runtime.cc:422]   (no managed stack frames)
art/runtime/runtime.cc:422] 
art/runtime/runtime.cc:422] "main" prio=10 tid=1 Native
art/runtime/runtime.cc:422]   | group="" sCount=1 dsCount=0 obj=0x73f0b000 self=0xb3405400
art/runtime/runtime.cc:422]   | sysTid=1569 nice=0 cgrp=default sched=0/0 handle=0xb61e5534
art/runtime/runtime.cc:422]   | state=S schedstat=( 612105031 112214678 1342 ) utm=46 stm=14 core=2 HZ=100
art/runtime/runtime.cc:422]   | stack=0xbe4e3000-0xbe4e5000 stackSize=8MB
art/runtime/runtime.cc:422]   | held mutexes=
art/runtime/runtime.cc:422]   native: #00 pc 000487a4  /system/lib/libc.so (__epoll_pwait+20)
art/runtime/runtime.cc:422]   native: #01 pc 0001a20d  /system/lib/libc.so (epoll_pwait+60)
art/runtime/runtime.cc:422]   native: #02 pc 0001a23d  /system/lib/libc.so (epoll_wait+12)
art/runtime/runtime.cc:422]   native: #03 pc 00011c83  /system/lib/libutils.so (_ZN7android6Looper9pollInnerEi+118)
art/runtime/runtime.cc:422]   native: #04 pc 00011b7f  /system/lib/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+26)
art/runtime/runtime.cc:422]   native: #05 pc 00093a7d  /system/lib/libandroid_runtime.so (_ZN7android18NativeMessageQueue8pollOnceEP7_JNIEnvP8_jobjecti+22)
art/runtime/runtime.cc:422]   native: #06 pc 0062d825  /system/framework/arm/boot-framework.oat (Java_android_os_MessageQueue_nativePollOnce__JI+96)
art/runtime/runtime.cc:422]   at android.os.MessageQueue.nativePollOnce(Native method)
art/runtime/runtime.cc:422]   at android.os.MessageQueue.next(MessageQueue.java:323)
art/runtime/runtime.cc:422]   at android.os.Looper.loop(Looper.java:136)
art/runtime/runtime.cc:422]   at android.app.ActivityThread.main(ActivityThread.java:6141)
art/runtime/runtime.cc:422]   at java.lang.reflect.Method.invoke!(Native method)
art/runtime/runtime.cc:422]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
art/runtime/runtime.cc:422]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
art/runtime/runtime.cc:422] 
art/runtime/runtime.cc:422] "Jit thread pool worker thread 0" prio=10 tid=2 Native
art/runtime/runtime.cc:422]   | group="" sCount=1 dsCount=0 obj=0x12c4f280 self=0xaa29c000
art/runtime/runtime.cc:422]   | sysTid=1574 nice=9 cgrp=default sched=0/0 handle=0xb2b18920
art/runtime/runtime.cc:422]   | state=S schedstat=( 184500913 80221171 243 ) utm=14 stm=3 core=1 HZ=100
art/runtime/runtime.cc:422]   | stack=0xb2a1a000-0xb2a1c000 stackSize=1022KB
art/runtime/runtime.cc:422]   | held mutexes=
art/runtime/runtime.cc:422]   native: #00 pc 00017418  /system/lib/libc.so (syscall+28)
art/runtime/runtime.cc:422]   native: #01 pc 000b70d9  /system/lib/libart.so (_ZN3art17ConditionVariable16WaitHoldingLocksEPNS_6ThreadE+92)
art/runtime/runtime.cc:422]   native: #02 pc 003472e1  /system/lib/libart.so (_ZN3art10ThreadPool7GetTaskEPNS_6ThreadE+160)
art/runtime/runtime.cc:422]   native: #03 pc 00346b07  /system/lib/libart.so (_ZN3art16ThreadPoolWorker3RunEv+62)
art/runtime/runtime.cc:422]   native: #04 pc 00346627  /system/lib/libart.so (_ZN3art16ThreadPoolWorker8CallbackEPv+78)
art/runtime/runtime.cc:422]   native: #05 pc 00047323  /system/lib/libc.so (_ZL15__pthread_startPv+22)
art/runtime/runtime.cc:422]   native: #06 pc 00019e5d  /system/lib/libc.so (__start_thread+6)
art/runtime/runtime.cc:422]   (no managed stack frames)
art/runtime/runtime.cc:422] 
art/runtime/runtime.cc:422] "Signal Catcher" prio=10 tid=3 WaitingInMainSignalCatcherLoop
art/runtime/runtime.cc:422]   | group="" sCount=1 dsCount=0 obj=0x12c4f310 self=0xb25b0e00
art/runtime/runtime.cc:422]   | sysTid=1575 nice=0 cgrp=default sched=0/0 handle=0xb2a17920
art/runtime/runtime.cc:422]   | state=S schedstat=( 449751 18375 3 ) utm=0 stm=0 core=1 HZ=100
art/runtime/runtime.cc:422]   | stack=0xb291b000-0xb291d000 stackSize=1014KB
art/runtime/runtime.cc:422]   | held mutexes=
art/runtime/runtime.cc:422]   native: #00 pc 00048b10  /system/lib/libc.so (__rt_sigtimedwait+12)
art/runtime/runtime.cc:422]   native: #01 pc 0001e25b  /system/lib/libc.so (sigwait+34)
art/runtime/runtime.cc:422]   native: #02 pc 00329d3f  /system/lib/libart.so (_ZN3art9SignalSet4WaitEv+22)
art/runtime/runtime.cc:422]   native: #03 pc 00329939  /system/lib/libart.so (_ZN3art13SignalCatcher13WaitForSignalEPNS_6ThreadERNS_9SignalSetE+168)
art/runtime/runtime.cc:422]   native: #04 pc 00328659  /system/lib/libart.so (_ZN3art13SignalCatcher3RunEPv+276)
art/runtime/runtime.cc:422]   native: #05 pc 00047323  /system/lib/libc.so (_ZL15__pthread_startPv+22)
art/runtime/runtime.cc:422]   native: #06 pc 00019e5d  /system/lib/libc.so (__start_thread+6)
art/runtime/runtime.cc:422]   (no managed stack frames)`

### How to Reproduce

Start session, and scroll a bit

### Expected Behavior

no crash :)

### Operating system(s) on local side and remote side

Windows 11 -> Android

### RustDesk Version(s) on local side and remote side

1.2.3->1.2.3

### Screenshots

https://github.com/rustdesk/rustdesk/assets/31169771/42cc01f5-b4a5-4d9c-b192-523e1fe42f74

**Comment by rustdesk** [comment]
duplicate: https://github.com/rustdesk/rustdesk/issues/6140

**Comment by Blueforcer** [comment]
@rustdesk 
> duplicate: #4118

Its not really the same i think. My crashes during operation. His after disconnecting.
