### ISSUE TITLE
Accessibility Software breaks privacy

### ISSUE THREAD

**Issue by My1** [rustdesk/rustdesk#6146]
### Bug Description

if Privacy mode is enabled on a machine with assistive software like Windows Narrator or NVDA, it will still talk about what's going on or output it to a braille display.

### How to Reproduce

1) Control Rustdesk on a machine with an assistive software like NVDA or Win Narrator
2) enable privacy mode
3) navigate around

### Expected Behavior

no data being told while privacy mode is active (ideally inform the user about privacy mode and how to kill it)

### Operating system(s) on local side and remote side

Kubuntu 22.04 -> W11

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.3

### Screenshots

not really a way to screenshot that

**Comment by rustdesk** [comment]
Because of current implementation, this is can not be solved. We are writoing new.

**Comment by My1** [comment]
interesting, the screen is successfully blocked tho, so that at least works.
