### ISSUE TITLE
uri and QR codes for quick connect to and also config self-hosted servers?

### ISSUE THREAD

**Issue by wildy** [rustdesk/rustdesk#616]
Hi.

I just had a nice idea for a feature request -- we could implement handling of links with a scheme like such (see below):

  * rustdesk://123456789 -- ordinary connection link, public relay servers.
  * rustdesk://123456789?server=rd.example.org&key=FooBarBaz -- connection through a self-hosted server
  * rustdesk://?server=rd.example.org&key=FooBarBaz -- set self-hosted server parameters

The same thing could be encoded into a QR code which could be read by clients both from screen, camera, or file. I feel like this can be super useful in a lot of scenarios. For example:
  * Set up a client for a custom server quickly: just snap a QR with your smartphone or laptop camera and there you are, custom relay server is set automatically.
  * Help a novice user connect via a custom server without encoding it in client file name -- "Here, click this link, or click that button and let RustDesk grab the code from the screen for you"

Just like Wi-Fi QR codes, but for RustDesk.

Waiting for your comments and suggestions :)

**Comment by rustdesk** [comment]
Thanks, we had such ideas also, but not start this project yet.

**Comment by huddhudd** [comment]
现在还没有实现吗？

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/3076

**Comment by karamba2077** [comment]
Great idea

**Comment by rustdesk** [comment]
# Start connection (mobile / desktop)

`rustdesk://123456789` or `rustdesk://connect/123456789`
`rustdesk://123456789/r`  force relay
`rustdesk://123456789@rd.example.org?key=FooBarBaz`
`rustdesk://123456789/r@rd.example.org?key=FooBarBaz` force relay

# Start file transfer etc
`rustdesk://file-transfer/<ID>@<SERVER>?key=<KEY>&password=<PASSWORD>`
`rustdesk://terminal/<ID>@<SERVER>?key=<KEY>&password=<PASSWORD>`
`rustdesk://view-camera/<ID>@<SERVER>?key=<KEY>&password=<PASSWORD>`
`rustdesk://port-forward/<ID>@<SERVER>?key=<KEY>&password=<PASSWORD>`

# Web
Same uri scheme as desktop, connect like below, any of /#/, /#, #/, # is ok

```
<DOMAIN>/web/#/<ID>
<DOMAIN>/web/#/<ID>@<SERVER>?key=KEY&password=<PASSWORD>
<DOMAIN>/web/#/file-transfer/<ID>@<SERVER>?key=<KEY>&password=<PASSWORD>
```

e.g.
`https:/rustdesk.com/web/#/123456789`

# Android
## start deep link via adb
`adb shell am start -W -a android.intent.action.VIEW -d <URI> <PACKAGE>`
PACKAGE=`com.carriez.flutter_hbb`

## set config and password
config: `rustdesk://config/<config_string>`

You can get config_string from the welcome page of web console, also can be export from `Settings` -> `Network` on RustDesk client.

set permanent password: `rustdesk://password/<password>`

**Comment by GuillaumeHullin** [comment]
@rustdesk it does not seems to work on macOS. Is it a me-problem or something known?

**Comment by aborghesi** [comment]
Hi,

With these commands:

rustdesk://file-transfer/<ID>@<SERVER>?key=<KEY>&password=<PASSWORD>
rustdesk://terminal/<ID>@<SERVER>?key=<KEY>&password=<PASSWORD>
rustdesk://view-camera/<ID>@<SERVER>?key=<KEY>&password=<PASSWORD>
rustdesk://port-forward/<ID>@<SERVER>?key=<KEY>&password=<PASSWORD>

I keep getting "Key mismatch" whether I try the private key or the public key.
Or is it another key?

Also, if I use a command like this in PowerShell

start rustdesk://terminal/my-device@rustdesk.mydomain.com?key=my_key&password=my_password

I get the key mismatch error, but I also get "The term 'password=my_password' is not recognized as a name of a cmdlet, function, script file, or executable program."  Powershell is cutting off the command at the & before password.

Thanks,
