### ISSUE TITLE
(Wayland | Sway | Gentoo) RustDesk constantly asks for monitor to share during connection

### ISSUE THREAD

**Issue by nickc01** [rustdesk/rustdesk#6170]
### Bug Description

When connecting from my Windows 10 Laptop to my Gentoo Computer, Rustdesk will constantly pop-up a menu for selecting which display I want to share. It continues to show this menu until the connection is terminated (video provided below).

### How to Reproduce

1. Startup RustDesk on Windows 10 and on Gentoo Linux.
        - 1.2.4 Nightly (Build Date - 2023-10-24 04:04)  was used on Windows
        - 1.2.4 Commit 2cdfeb8 was used on Gentoo Linux
2. Startup a connection from the Windows 10 Machine to the Gentoo Machine, so the desktop on the Gentoo Machine is viewable on the Windows 10 machine.
3. See the wofi menu for selecting monitors constantly show up during the lifetime of the connection.

### Expected Behavior

The expected behavior is that this menu shouldn't be be popping up constantly when connecting to a machine. It makes it hard to use when I want to connect to my computer from a physically far away location.

### Operating system(s) on local side and remote side

Windows 10 22H2 -> Gentoo Linux

### RustDesk Version(s) on local side and remote side

1.2.4 Nightly (Build Date - 2023-10-24 04:04) -> 1.2.4 Commit 2cdfeb8

### Screenshots

Here is a video of the problem in action:
https://youtu.be/fmA9GeMTjo4?si=IGiJ4687HcY4uXPq

### Additional Context

# Linux System Information
OS: Gentoo 2.14 x86_64
Kernel: 6.1.57-gentoo-dist
WM: Sway (Wayland)
CPU: AMD Ryzen 9 5950X (32) @ 5.08 GHz
GPU: AMD Radeon RX 6750 XT
Pipewire Version: media-video/pipewire-9999 (commit 970a8376)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by rustdesk** [comment]
Please try out latest nigthly build 1.2.5

**Comment by nickc01** [comment]
I just finished updating my entire Gentoo Linux system, and I have tested out the following nightly builds:

-  rustdesk-1.2.6-0-x86_64.pkg.tar.zst 
-  rustdesk-1.2.6-x86_64.AppImage 
- rustdesk-1.2.6-x86_64.flatpak 

I also tested each of these builds under two environments:

- gui-wm/hyprland-0.40.0-r1
- gui-wm/sway-1.9-r1

I wasn't able to get to the point where I could share my screen between my Android phone and my desktop computer. The android app was also on the latest nightly build. Here's the results:

## PKG.TAR.ZST - Hyprland
Upon connecting to the desktop computer, it shows the error: "Login error No such interface "org.freedesktop.portal.RemoteDesktop" on object at path /org/freedesktop/portal/desktop" and immediately disconnects

[TAR_6-22-2024_LOG.txt](https://github.com/user-attachments/files/15937642/TAR_6-22-2024_LOG.txt)

## AppImage - Hyprland
Upon selecting the linux desktop. The linux desktop will open the desktop portal to select a monitor. When I select a monitor, the android phone will then show "Wayland: Please select the screen to be shared(Operate on the peer side)."

After this message, another xdg portal window will show up on the linux desktop, asking to select a monitor again. After selecting it again though, the connection between the phone and computer is disconnected, with the phone showing the popup: "Login error: Failed to create capturer"

[APPIMAGE_6-22-2024_LOG.txt](https://github.com/user-attachments/files/15937784/APPIMAGE_6-22-2024_LOG.txt)


## Flatpak - Hyprland
When I select the computer, it shows for a split second the message: "Wayland: Please select the screen to be shared(Operate on the peer side).", but no xdg portal menu is shown on the desktop side. After a split second, the connection is disconnected, and the following message is shown: "Login error: No such interface "org.freedesktop.portal.RemoteDesktop" on object at path /org/freedesktop/portal/desktop"

[FLATPAK_6-22-2024_LOG.txt](https://github.com/user-attachments/files/15937650/FLATPAK_6-22-2024_LOG.txt)

## PKG.TAR.ZST - Sway
Upon connecting, the android side displays this error: Login error
No such interface "org.freedesktop.portal.RemoteDesktop" on object at path /org/freedesktop/portal/desktop

[SWAY_TAR_6-22-2024_LOG.txt](https://github.com/user-attachments/files/15937790/SWAY_TAR_6-22-2024_LOG.txt)


## AppImage - Sway
When I connect, it prompts me to select a monitor to share, but after selecting, it then disconnects, and shows on the Android Phone : "Login error: Failed to create capturer"

[SWAY_APPIMAGE_6-22-2024_LOG.txt](https://github.com/user-attachments/files/15937810/SWAY_APPIMAGE_6-22-2024_LOG.txt)

## Flatpak - Sway
When I select the computer, the connection is immediately disconnected and the following message is shown: "Login error: No such interface "org.freedesktop.portal.RemoteDesktop" on object at path /org/freedesktop/portal/desktop". No xdg desktop portal popup is ever shown during the process.

[SWAY_FLATPAK_6-22-2024_LOG.txt](https://github.com/user-attachments/files/15937806/SWAY_FLATPAK_6-22-2024_LOG.txt)


Let me know if there's anything I am missing

## Specs
OS: Gentoo 2.15 x86_64
Kernel: 6.6.32-gentoo-dist
CPU: AMD Ryzen 9 5950X (32) @ 5.08 GHz
GPU: AMD Radeon RX 6750 XT
Pipewire Version: media-video/pipewire-1.0.7

**Comment by napaalm** [comment]
I get the message "Login error: No such interface "org.freedesktop.portal.RemoteDesktop" on Arch Linux with sway 1.9, xdg-desktop-portal 1.18.4 and pipewire 1.2.0

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/8935
