### ISSUE TITLE
Hide Connection Manager Window (hide cm) option missing

### ISSUE THREAD

**Issue by Bumanuu** [rustdesk/rustdesk#6175]
### Bug Description

"Hide Connection Manager Window (hide cm)" option has removed because of Kaspersky compliance.
Kaspersky compliance is required on those platforms where Kaspersky is used - MS Windows and for public Rusdesk servers, but not for own/custom rustdesk servers and Linux/Unix platforms.
Please bring this option back for cases when platform is not Windows and/or custom/own Rustdesk-server is configured.

Thanks in advance.

### How to Reproduce

Open Security tab:
there is no option "Hide Connection Manager Window".

### Expected Behavior

Open Security tab:
there is option "Hide Connection Manager Window".

### Operating system(s) on local side and remote side

debian 11 amd64 -> Raspberry Pi OS (debian 11) arm64

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

![изображение](https://github.com/rustdesk/rustdesk/assets/106404525/c31fcbd7-a8d2-421e-912b-ab0fcc94b952)

**Comment by rustdesk** [comment]
search duplicate please

**Comment by rustdesk** [comment]
So another guy will propose another issue, only Windows has security issue, the os does not?
