### ISSUE TITLE
Audio delay

### ISSUE THREAD

**Issue by Zahrun** [rustdesk/rustdesk#6177]
### Bug Description

The sound reaches around 2 or 6 seconds later than the image. It seems these are fixed buffer sizes.
I’m on linux wayland for the host and android for the guest. I’m using direct IP access on a local 5Ghz WiFi which has avg of 80 ms rtt.

### How to Reproduce

Connect through direct IP access on a local network and play a video

### Expected Behavior

I would like to hear less delay in the audio

### Operating system(s) on local side and remote side

Android -> Linux wayland

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

Audio is 2 seconds behind video on android -> linux
https://github.com/rustdesk/rustdesk/assets/10415894/cbd4d317-ca3a-41c7-9eab-e966e391a428

It seems to take around 0.5 sec in the other direction
https://github.com/rustdesk/rustdesk/assets/10415894/86817659-5ae3-4891-8bb1-ddc68b4ca2e4

### Additional Context

Operating System: TUXEDO OS 2
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.11
Kernel Version: 6.2.0-10027-tuxedo (64-bit)
Graphics Platform: Wayland

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by chchia** [comment]
just to addon, same thing happen for Ubuntu 23.10 on LAN. about 3 second behind.

**Comment by chchia** [comment]
Hi in just want to supplement that, in was having audio delay by 2 second issues with my ubuntu. and it turn out the i changed the default pulsewire to pipewire some time ago.

changing back to pulsewire fixed the audio delay issues. this might be a hint.

**Comment by leucome** [comment]
It got the 3 sec delay after updating the computers to Manjaro 24.0. with Plasma 6.  I tried to install pulse audio instead of pipewire then I formatted the PC and installed Manjaro from scratch.  No improvement.  I tried multiple different version of Rustdesk. I also tried to build from source in case. 

I am going to do some more test. But mostly I put a message here to get a notification in case somebody find what is going on.

**Comment by Mortos360** [comment]
I have the same issue running AlmaLinux 9.4
Audio has a delay of 2-3 sec, no matter if I go over the public relay server or direct IP connection in LAN, delay is always the same. I tried the version 1.2.4, 1.2.6 and the current nightly from 23.06.2024. No effect.

**Comment by savineugenioan** [comment]
I have the same issue on EndeavourOS
![image](https://github.com/rustdesk/rustdesk/assets/49971855/a98fd2c5-8807-4d11-8832-cb8379743800)

Audio has a delay of about 3 sec. Public relay server or direct IP connection in LAN.
I tried the version 1.2.6, the current nightly buld 1.2.7.
I also use pipewire.

**Comment by Marty651** [comment]
I have this issue between two Ubuntu 24.10 computers. So I believe the title is misleading as it seems to be a general problem with modern Linux distributions using pipewire. Is there any chance that somebody is working on that?

**Comment by OliverRhyme** [comment]
> I have this issue between two Ubuntu 24.10 computers. So I believe the title is misleading as it seems to be a general problem with modern Linux distributions using pipewire. Is there any chance that somebody is working on that?

Same with my ubuntu 24.04

**Comment by RogerVigo** [comment]
I'm using ubuntu 24.04 as a guest and after changing from pipewire to pulse audio the delay was reduced from 3 seconds to barely nothing.

**Comment by OliverRhyme** [comment]
> I'm using ubuntu 24.04 as a guest and after changing from pipewire to pulse audio the delay was reduced from 3 seconds to barely nothing.

How do you do that?

**Comment by madsmith** [comment]
I was having this issue with RustDesk 1.4.6 and pipewire on Ubuntu 25.10

There's some interplay between Pulse Audio and Pipewire.  Tweaking PULSE_LATENCY_MSEC and PIPEWIRE_LATENCY can fix the problem.  

And...

Apparently the startup config attempts to do this but the environment variables it sets are not passed to the user space rustdesk processes so the fix gets lost.

My fix was to edit env_keep for sudo

```
sudo visudo
```

Add the lines

```
# Environment pass through for rustdesk audio latency
Defaults env_keep += "PULSE_LATENCY_MSEC PIPEWIRE_LATENCY"
```

Then restart the service

```
sudo systemctl daemon-reload
sudo systemctl restart rustdesk.service
```
