### ISSUE TITLE
app can't run correct

### ISSUE THREAD

**Issue by soonsolidchenkan** [rustdesk/rustdesk#6183]
### Bug Description

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'librustdesk.so': dlopen failed: "/data/app/com.carriez.flutter_hbb-n9ojvdlpoBPmFw5ymfQ_Ww==/lib/arm64/librustdesk.so" has unexpected e_machine: 62 (EM_X86_64)

### How to Reproduce

run app

### Expected Behavior

run correct

### Operating system(s) on local side and remote side

windows10

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

![Screenshot_20231026_151617](https://github.com/rustdesk/rustdesk/assets/62323208/4979d1bb-ee32-4f0a-a1dc-0dc807600584)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/5108
