### ISSUE TITLE
Android Screen Record Stops after hours (service killed by system)

### ISSUE THREAD

**Issue by vavolkova** [rustdesk/rustdesk#6192]
Hi guys,

Not sure if that has been discussed before, but I didn't find anything under this topic. I was looking to set unattended access on few Android devices (Android 11). I have set Pro account with Linux server and it all worked properly until I noticed that after 2-3 hours the service stops (Screen Record automatically turns off) and I need to manually turn it on and continue using it.

Is there a solution for that?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/rustdesk) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/rustdesk/rustdesk/issues/6192">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/rustdesk/rustdesk/issues/6192/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/rustdesk/rustdesk/issues/6192/pledge.svg">
</picture>
</a>

**Comment by rustdesk** [comment]
Frankly, we still have no good solution.

**Comment by rustdesk** [comment]
https://support.anydesk.com/knowledge/anydesk-for-android-chromeos

![image](https://github.com/rustdesk/rustdesk/assets/71636191/dd3e4468-1a43-4b69-99c5-84247fe3db09)

**Comment by rustdesk** [comment]
![image](https://github.com/rustdesk/rustdesk/assets/71636191/d5137876-eb94-4ecd-b18f-c317a15dec5e)

**Comment by TheGrave** [comment]
I have the same issue on Xperia 5 and Xperia 1. It's utterly ridiculous - I need to keep TeamViewer Host installed so that I can re-enable the service. This also forces me to have no screen lock on these phones as TeamViewer Host cannot get to an unlock prompt with them.

**Comment by vavolkova** [comment]
Hi @scshiv29-dev ,

I'm not sure how the bounty process works, but is there going to be a solution for this problem anytime soon?

Thanks!

**Comment by scshiv29-dev** [comment]
Hey @vavolkova  the bounty process is designed to give incentives and get open source contributions to the project. The thing is I did the battery optimization setting on my phone and tried 2-3 other phones and rustdesk was working fine . I still think this is an android issue rather than the app code itself, like if the app is stopped from running in the background it will just terminate the session with the server and it would stop.

**Comment by rustdesk** [comment]
@scshiv29-dev Thanks for your effort.

**Comment by rustdesk** [comment]
> ignore list of battery optimization.

I have never seen any app does this. Need a good design for this.

**Comment by scshiv29-dev** [comment]
@rustdesk  for me this is the setting that basically made sure the app was working fine even for long hours but the battery consumption is obviously higher.

![Screenshot_2023-11-23-20-29-25-79_0ba066473b79d6e213a1f6f52505e2ee.jpg](https://github.com/rustdesk/rustdesk/assets/68141773/ce626727-4247-44b0-bf05-79ab4696ddfd)

**Comment by cikeZ00** [comment]
Stock android only has these options. They don't guarantee it won't get killed tho.
![Screenshot_20231123-161239_Settings.png](https://github.com/rustdesk/rustdesk/assets/17727672/19a1c385-c25b-462f-b2ae-28c8ffce3f90)

**Comment by TheGrave** [comment]
> @rustdesk Yea sure, I figured this was getting stopped by the android OS only. It would be better if we also ask users to add the app to ignore list of battery optimization.

This won't be sufficient. I have battery optimization for the app turned off and it still dies. There are vendor-specific battery optimizations (usually called Adaptive Battery or something similar) which surely can contribute to the problem.

**Comment by scshiv29-dev** [comment]
@TheGrave okay , for the devices I tested it did not stopped for me so I thought this was android setting specific.

**Comment by vavolkova** [comment]
Hi everyone,

I just wanted to drop a quick update to let you know that the issue I was facing with Rustdesk has been successfully resolved on my Samsung A10. Big thanks to all of you for the valuable advice and suggestions!

For those who might be experiencing a similar problem, here's what worked for me:

1. Allow Background Activity:
Make sure to allow Rustdesk to run in the background. Sometimes, restrictive background activity settings can interfere with the app's functionality.
2. Remove Rustdesk from Battery Optimization:
Go to your phone's settings and navigate to the list of apps with battery optimization. Remove Rustdesk from this list to ensure it can operate without any restrictions.

By following these steps, I was able to get Rustdesk up and running smoothly on my Samsung A10. I hope this solution proves helpful to others facing the same issue.

Once again, thank you all for your support and suggestions!

**Comment by rustdesk** [comment]
Implement an Android floating window to prevent the system from killing the service, ready in nightly build.
https://x.com/rustdesk/status/1798387103862231205
