### ISSUE TITLE
[FEATURE] - Connect even if device are not on same server

### ISSUE THREAD

**Issue by Apashh** [rustdesk/rustdesk#6198]
Hey,

It will be interesting to connect to a public Rustdesk ID not hosting it on our servers while remaining connected to our hosted server.

Thanks for reply !

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2118

**Comment by rustdesk** [comment]
@sahilyeole Let's support `id@host?key=<value>` in the id input box.

**Comment by rustdesk** [comment]
@sahilyeole Let's support `id@host?key=<value>` in the id input box.

**Comment by rustdesk** [comment]
@sahilyeole add some tooltip there to tell users how to use

**Comment by mycanaletto** [comment]
This is a good idea.

This will enable an isolated customer to install Rustesk without having to be given the key to connect to it the first time.

This raises the problem of the key. If the customer can copy the key, he can use our server for other devices without our knowledge.

We'd need to find a way of making it impossible to copy the key, or of making this possible only if the Rustdesk user is logged in. Otherwise, the key could spread and my server become public...

**Comment by pedjas** [comment]
> We will address this issue in next Pro version.

This explains everything. We were just teased. FInal goal was to make commercial product an sell it to us.

Well, RustDesk is fine product, but while OpenSource. As commercial product it is far behind competition.

**Comment by mycanaletto** [comment]
I bought a license that supports 500 devives. The group is not very small....

Perhaps it should be possible to define several keys and limit them to one group?

**Comment by rustdesk** [comment]
> We'd need to find a way of making it impossible to copy the key, or of making this possible only if the Rustdesk user is logged in. Otherwise, the key could spread and my server become public...

This is pretty a good idea, we will think about this.

**Comment by pdifeo** [comment]
I agree but only if the user can logout and the key  is still configured on
the client.

Il ven 27 ott 2023, 19:33 RustDesk ***@***.***> ha scritto:

**Comment by pdifeo** [comment]
> I agree but only if the user can logout and the key is still configured on the client.

Another solution is protect configuration with an additional passwork, like TeamViewer with "Option Password"

<img width="369" alt="image" src="https://github.com/rustdesk/rustdesk/assets/8618744/60076adb-efc3-47ba-b510-5a145498f5b9">

**Comment by rustdesk** [comment]
![image](https://github.com/rustdesk/rustdesk/assets/71636191/cd5e2959-7481-4309-9f1d-54b3027fab54)

**Comment by bbb5317** [comment]
> ![image](https://private-user-images.githubusercontent.com/71636191/280703242-cd5e2959-7481-4309-9f1d-54b3027fab54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNjUxNjksIm5iZiI6MTcwOTE2NDg2OSwicGF0aCI6Ii83MTYzNjE5MS8yODA3MDMyNDItY2Q1ZTI5NTktNzQ4MS00MzA5LTlmMWQtNTRiMzAyN2ZhYjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDAwMDEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzMjY4ZWU5MWNlNDMzZGVhZjhiMTQ3OTYzNmQ1NzUyNDk2OGU0NTBlMzg5NDIxNGU1MDQ5Y2QzMTdmNzM2ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SbfrHZ72Ufyn6a8hA5MY1tzzVjLAXbWKrvES2bTUGA0)

What version is this on? I tried with my current version but not working.

**Comment by xlionjuan** [comment]
@bbb5317 1.2.4 nightly

**Comment by My1** [comment]
> > We'd need to find a way of making it impossible to copy the key, or of making this possible only if the Rustdesk user is logged in. Otherwise, the key could spread and my server become public...
> 
> This is pretty a good idea, we will think about this. Thanks @mycanaletto

one option especially if you wanna allow supporting strangers could be making it in a way that any outgoing connection doesnt just need the host and the public server key but also a login.

**Comment by SebSeifert** [comment]
Hi, because of the missing online status on remote servers. In https://github.com/rustdesk/rustdesk/issues/10005 it looks to be fixed. Will this be merged in the future? Would be awesome.
