### ISSUE TITLE
Target of URI doesn't exist: '../generated_bridge.dart'

### ISSUE THREAD

**Issue by lieft** [rustdesk/rustdesk#620]
Hello, I'm sorry to bother you.

After importing the fluuter project, I found the file ‘/rustdesk/flutter/lib/models/native_model.dart’. There is 'import '../generated_bridge.dart';'.  But in fact, I found all of them in the GIT project and didn't have this file 'generated_bridge.dart'

**Comment by rustdesk** [comment]
So it is called generated.

**Comment by lieft** [comment]
Well, maybe my generation failed. I'll study it again. Thank you very much
好吧，可能是我生成失败了，我再研究一下，非常感谢

**Comment by mutianhua** [comment]
> So it is called generated.

excuse me, how could I generate this file? Is the command "npm install ts-proto" and "yarn build" in the doc works to generate this file?

**Comment by xiaoqi0117** [comment]
> > 所以它被称为生成。
> 
> 对不起，我怎么能生成这个文件？文档中的命令“npm install ts-proto”和“yarn build”是否可以生成此文件？

请问解决这个问题了吗?

**Comment by xiaoqi0117** [comment]
> 好吧，也许我这一代失败了。我再研究一下。非常感谢 好吧，可能是我失败了，我再研究一下，非常感谢

请问解决这个问题了吗?

**Comment by asur4s** [comment]
Here are my notes, hope it helps you.
```bash
git clone https://github.com/SoLongAndThanksForAllThePizza/flutter_rust_bridge
cargo build --release
sudo cp target/release/flutter_rust_bridge_codegen /usr/local/bin/
# Make sure the installtion was successful
flutter_rust_bridge_codegen

# Fix bug of ffigen: https://github.com/dart-lang/ffigen/issues/257
$ clang -E -x c /dev/null -v # Find the header files of llvm
$ export CPATH="/usr/lib/llvm-10/lib/clang/10.0.0/include"

# Generate flutter code
$ export https_proxy=http://192.168.1.4:7890 http_proxy=http://192.168.1.4:7890 all_proxy=socks5://192.168.1.4:7890
$ cd ~/Documents/rustdesk/flutter && flutter pub get
$ cd ~/Documents/rustdesk && RUST_LOG=debug flutter_rust_bridge_codegen --rust-input src/flutter_ffi.rs --dart-output flutter/lib/generated_bridge.dart --c-output flutter/macos/Runner/bridge_generated.h  --llvm-path /usr/local/share/llvm-home

# Run flutter version
$ cd ~/Documents/rustdesk/flutter && flutter run -d linux
```

**Comment by Love-SunMoon** [comment]
I have the same problem, but don't know where the file was generated?

**Comment by ifoxhz** [comment]
> ```shell
> RUST_LOG=debug flutter_rust_bridge_codegen --rust-input src/flutter_ffi.rs --dart-output flutter/lib/generated_bridge.dart --c-output flutter/macos/Runner/bridge_generated.h  --llvm-path /usr/local/share/llvm-home
> ```

Does it work ?  I have  another issue:
[2022-09-16T08:37:05Z ERROR flutter_rust_bridge_codegen] fatal: unable to parse pubspec.yaml in /home/*/github/rustdesk/flutter

**Comment by yunxingyu** [comment]
may you can  execute sh run.sh

**Comment by doujd** [comment]
Has this problem been solved? I am importing 'lib/generated_bridge.dart' on Mac: No such file or directory

**Comment by doujd** [comment]
> Hello, I'm sorry to bother you.
> 
> After importing the fluuter project, I found the file ‘/rustdesk/flutter/lib/models/native_model.dart’. There is 'import '../generated_bridge.dart';'. But in fact, I found all of them in the GIT project and didn't have this file 'generated_bridge.dart'

Has this problem been solved?

**Comment by ezwardChou** [comment]
> may you can execute sh run.sh

thx, it works for me~

**Comment by pengge924** [comment]
在rustdesk下执行这个命令： RUST_LOG=debug flutter_rust_bridge_codegen --rust-input src/flutter_ffi.rs --dart-output flutter/lib/generated_bridge.dart --c-output flutter/macos/Runner/bridge_generated.h  --llvm-path /usr/local/share/llvm-home   一直卡在这里。没有反应，也不报错  这是什么原因？
