### ISSUE TITLE
Asking to install certificate ("RustDesk Display adapters") on remote machine, after closing connection

### ISSUE THREAD

**Issue by Jemmota** [rustdesk/rustdesk#6204]
### Bug Description

Starting today, in the nightly version I noticed that after accessing the remote machine, when closing the connection, RustDesk started requesting the installation of the certificate on the remote machine. That didn't happen until this morning.

### How to Reproduce

Make a connection and then close it. The message requesting the installation of the certificate ("RustDesk Display adapters") will appear on the remote machine.

### Expected Behavior

A request to install the "RustDesk Display adapters" certificate on the remote machine will appear when closing the connection (on remote machine).

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.2.4 (Nightly) 

### Screenshots

<img width="476" alt="cert" src="https://github.com/rustdesk/rustdesk/assets/129885668/719b8d58-ca1d-4199-b649-3da023ec51db">

**Comment by fufesou** [comment]
Sorry for disturbing

**Comment by rustdesk** [comment]
close as fix merged

**Comment by Jemmota** [comment]
I just tested it. The problem was solved. Thank you very much.
