### ISSUE TITLE
Android crashes

### ISSUE THREAD

**Issue by wirelesshnic** [rustdesk/rustdesk#6216]
### Bug Description

I am on the latest version of andoid on a Pixel 7 pro.  So is the remote connection.

After a short while of screen sharing the app crashes and the service must be restarted in order to restore connectivity.

I also have it set to auto-start with the phone which it does not do and the service frequently crashes.

Second issue, in the previous version I was able to connect and then tap on the screen to wake the device, now it get stuck on "waiting for screen"

### How to Reproduce

Screenshare for a bit and then experience the service crash

### Expected Behavior

No crashes

### Operating system(s) on local side and remote side

Android 14

### RustDesk Version(s) on local side and remote side

1.2.3 to 1.2.3

### Screenshots

None

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3556#issuecomment-1824057453
