### ISSUE TITLE
Client keyboard not working under Crostini Linux on chromeOS

### ISSUE THREAD

**Issue by ajorg** [rustdesk/rustdesk#6220]
### Bug Description

Trying to use a Chromebook as a client, the best options seem to be to use the "Crostini" Linux container. I can connect to a Windows desktop and authenticate. The mouse works too, but the keyboard doesn't work at all.

### How to Reproduce

Use .Appimage, .flatpak, or .deb client on a Debian container on chromeOS to connect to a remote machine.  
Keyboard doesn't work.

### Expected Behavior

Keyboard should work.

### Operating system(s) on local side and remote side

Debian 12 on chromeOS 118 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

Screenshots not relevant.

### Additional Context

I tried from another Windows (10) computer and from another Debian 12 machine (not a chromeOS container) and the keyboard **worked correctly** from both.

I also tried each of the keyboard modes, Legacy, Map, and Translate, none worked.

All tests to the same host, to avoid any confusion there.

I wondered if RustDesk tries to read the keyboard in some kind of raw mode, and because Crostini is a container environment (lxd IIRC) it's not able to get that information. Or it may be a Wayland vs. X11 kind of problem.

I also wondered if this could be the same as #3977 which was marked not reproducible.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
