### ISSUE TITLE
Report Remote offline when close my remote phone 

### ISSUE THREAD

**Issue by qiuruiyu** [rustdesk/rustdesk#6221]
### Bug Description

When I give all permissions, and set my phone (Huawei p30 pro, HarmonyOS 3.0) closed just for a while, I received "Remote Offline", even if that I made RustDesk not to be killed by my phone in the setting.  

### How to Reproduce

- Just closed phone
- Try to connect and got offline

### Expected Behavior

Can connect to my phone even if its screen is closed 

### Operating system(s) on local side and remote side

macos -> android / harmonyOS 

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3 

### Screenshots

<img width="1298" alt="image" src="https://github.com/rustdesk/rustdesk/assets/55018261/d08bac30-9176-4cf3-97c9-dddf1585261e">

**Comment by rustdesk** [comment]
close as many duplicate

**Comment by qiuruiyu** [comment]
您好，感谢您的来信。已确认收到您的邮件，我会尽快处理您的邮件，谢谢。Hello！This is an automatic reply confirming that your email was received. Your email will be handled as soon as possible. Thank you！                                                      仇睿瑜                                              Joseph QIUThis is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by qiuruiyu** [comment]
Hey so could you please offer me a link about the relative issue ? Thanks

**Comment by cxwithyxy** [comment]
我的华为也是这样，目前无解，我判断是息屏一段时间（30分钟）之后，rustdesk也同样挂起了（暂停），但只要唤醒屏幕（不用解锁）就可以连上。临时的一个解决办法：通过macrodroid或者tasker设置定时唤醒屏幕
