### ISSUE TITLE
Change view - small tiles not restored

### ISSUE THREAD

**Issue by deep-soft** [rustdesk/rustdesk#6234]
### Bug Description

The new option to display peers as List is great but after that PR the option to display peers as Small Tiles, even if the option is saved in RustDesk_local.toml file (as value 1), does not work.
For every type selected the option is saved (0 for Big Tiles, 1 for Small Tiles and 2 for List), but on Application start the option 1 (Small Tiles) is restored as 0 (Big Tiles); the other 2 options are restored corectly.

### How to Reproduce

1. Select Small Tiles option in Change View menu on peers list (Recent sessions, Favorites, Discovered)
2. Close main window
3. Restore/launch Application
4. if Small Tiles was selected the Big Tiles is applied

### Expected Behavior

1. Select Small Tiles option in Change View menu on peers list (Recent sessions, Favorites, Discovered)
2. Close main window
3. Restore/launch Application
4. if Small Tiles was selected the Small Tiles need to be applied

### Operating system(s) on local side and remote side

Windows

### RustDesk Version(s) on local side and remote side

1.2.4.

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/10506197/8e96bd32-edb3-4d74-896e-fa01a91d8640)
![image](https://github.com/rustdesk/rustdesk/assets/10506197/d7b5ea87-532e-4cb9-a018-4e1de618f8a1)

### Additional Context

First image - before application restart
Second image - after application restart

**Comment by VaTi1** [comment]
I confirm the same problem on several Windows 10 Home and Pro (22H2) machines with Rustdesk client build: 2023-10-30.

**Comment by rustdesk** [comment]
@sahilyeole

**Comment by sahilyeole** [comment]
@deep-soft @VaTi1 

Thanks for testing. I should have tested better beforehand.
It will be fixed now.
