### ISSUE TITLE
Android build error: com.github.getActivity:XXPermissions:16.2 vanished from jitpack.io

### ISSUE THREAD

**Issue by basilgello** [rustdesk/rustdesk#6254]
I fixed F-Droid release of rustdesk here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13965

but builds fail with the following error:

```
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.getActivity:XXPermissions:16.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/getActivity/XXPermissions/16.2/XXPermissions-16.2.pom
       - https://jcenter.bintray.com/com/github/getActivity/XXPermissions/16.2/XXPermissions-16.2.pom
       - https://jitpack.io/com/github/getActivity/XXPermissions/16.2/XXPermissions-16.2.pom
       - file:/tmp/flutter_tools.BJDUSO/flutter_tool_local_engine_repo.VJXBLQ/com/github/getActivity/XXPermissions/16.2/XXPermissions-16.2.pom
       - https://repo.maven.apache.org/maven2/com/github/getActivity/XXPermissions/16.2/XXPermissions-16.2.pom
     Required by:
         project :app
```

I checked and it really appears that https://jitpack.io/com/github/getActivity/XXPermissions/16.2/XXPermissions-16.2.pom now returns Not found.
Updating the dependency to 18.3 passes all Android manual tests on my side.

**Comment by rustdesk** [comment]
no need to tell us we know, our CI run.

**Comment by basilgello** [comment]
How am I supposed to know what you know if I only checked the master commits and I do not see the bump of that dependency? :)

**Comment by rustdesk** [comment]
Thanks https://github.com/rustdesk/rustdesk/commit/c2287033e36962a02b3e1ea34d11def04a03edc5

**Comment by basilgello** [comment]
Also I tested all 4 android architectures with flutter-rust-bridge version 1.80.1 (you bumped yesterdsy to 1.79). Version 1.81 has undefined `IntoIntoDart<_>` trait and 1.82 gives lots of `annotation required` errors on src/lib_generated.rs. Just in case you did not try building these yet.

**Comment by rustdesk** [comment]
That's why I am stick to 1.79, :(

**Comment by rustdesk** [comment]
Horrible effort needed to upgraded to >=1.80. @fzyzcjy
I gave up.

**Comment by basilgello** [comment]
1.80.1 does work! https://gitlab.com/basilgello/fdroid-main-repo-data/-/commit/11b9fbe2ba0185a2ad778ee949d80ec464d9d194 passed all my tests (android -> android, android -> linux, linyx -> android)

**Comment by rustdesk** [comment]
Thanks, good to know <=1.80.1 works

**Comment by rustdesk** [comment]
bump to 1.80.1, https://github.com/rustdesk/rustdesk/commit/eaa64d7b70a55434f3f6711c63a367a63bb5d5ab

>=1.81 introduces `cargo expand`, this big change give us big trouble. @fzyzcjy can we bypass `expand`?

**Comment by basilgello** [comment]
I forgot to mention: ffigen must stay at 8.0.2 not 9.0.1. 

```
2023/11/01 09:29:42 [INFO] Phase: Transform IR
2023/11/01 09:29:42 [INFO] Phase: Generate Rust code
2023/11/01 09:29:42 [INFO] Phase: Generate Dart code
Flutter 3.13.9 • channel [user-branch] • unknown source
Framework • revision d211f42860 (7 days ago) • 2023-10-25 13:42:25 -0700
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0
2023/11/01 09:29:43 [ERROR] Fatal error encountered. Rerun with RUST_BACKTRACE=1 or RUST_BACKTRACE=full for more details.
Error: External command failure.
Please update version of ffigen in your dev_dependencies. (version >=8.0.0, <9.0.0)

Caused by:
    Please update version of ffigen in your dev_dependencies. (version >=8.0.0, <9.0.0)
==== detail end ====
2023-11-01 09:29:43,233 DEBUG: Error encountered, stopping by user request.
```
