### ISSUE TITLE
keyboard issue and on-screen keyboard issue

### ISSUE THREAD

**Issue by shamirahim111** [rustdesk/rustdesk#6281]
### Bug Description

issue 1. pressing windows key gets triggered on both remote and local side.
issue 2.  pressing win+z or w or any key combination with win key on on-screen keyboard open on remote side does not act normal.
issue 3. win+v hotkey seems to get triggered locally only. does not get transmitted.

i am writing all issues together because they seem to work together.

issue 2 is problematic because if i control onscreen on remote side from there, win+v works properly as it should but if i use rustdesk to do same action, it does not work. it opens start menu and types the key.
It should NOT matter if i am operating on screen keyboard locally or from rustdesk but apparently it does.

tested with both x11 and wayland but recording available of x11 only.

mouse movement in "1 and 2" video  is by operating from rustdesk.
"3 working in x11" shows pressing win+w on local side transmitting sucessfully to wayland
"3 not working in wayland" shows as explained in the name.

### How to Reproduce

try to use shortcuts. they get differently transmitted.

the puzzling this is onscreen keyboard and rustdesk should not affect its usage but it is mimicking the same results as pressing win+key or alt+key or some other combination.

it appears that common shortcuts are working but not many more 

### Expected Behavior

shortcuts should get transmitted as it is.

the windows/meta button has been a problem.

pressing win key opens start menu on both local and remote which is not accurate behaviour

### Operating system(s) on local side and remote side

linux>windows

### RustDesk Version(s) on local side and remote side

1.2.4>1.2.4 nightly latest build 

### Screenshots

https://github.com/rustdesk/rustdesk/assets/149858437/25c3d517-ba75-4d67-8395-dc3efb3e591e

https://github.com/rustdesk/rustdesk/assets/149858437/9e8782e2-bb33-4646-a63f-46c36cb55438

https://github.com/rustdesk/rustdesk/assets/149858437/852a0e1b-2e5d-4244-ad5d-9a2c4c57aa4e

[3 not working on wayland]

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367
