### ISSUE TITLE
Main Window Tabs missing

### ISSUE THREAD

**Issue by kb9gxk** [rustdesk/rustdesk#6298]
### Bug Description

Can't switch between settings and main window.  The tab bar is missing on Windows.

### How to Reproduce

Go to settings

### Expected Behavior

Having a tab bar to switch tabs

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.2.4

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/59369311/5d05e754-abe0-47d9-b167-b041ec4fa680)

**Comment by rustdesk** [comment]
@fufesou same prolem related to flutter 3.13.

**Comment by rustdesk** [comment]
@kb9gxk you see this every time?

**Comment by kb9gxk** [comment]
90% of the time.  It happens at random times when the window is open.  In order to reset it, I have to use task manager to close it.  No issue on remote windows though.

**Comment by fufesou** [comment]
Can you please upload a video to show how it is reproduced? Thx

I can hardly reproduce it.

**Comment by rustdesk** [comment]
0% for me, you got the good luck. :(
