### ISSUE TITLE
When starting RustDesk, no window appears, only an icon on the taskbar.

### ISSUE THREAD

**Issue by ELForcer** [rustdesk/rustdesk#6321]
### Bug Description

When starting RustDesk, no window appears, only an icon on the taskbar.

The command "sudo apt purge rustdesk" did not help.
Deleting the "~/.config/rustdesk" folder did not help.

### How to Reproduce

* Install RustDesk 1.2.3
* Start RustDesk

### Expected Behavior

Main application window.

### Operating system(s) on local side and remote side

Linux Mint 21.2 Cinnamon

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/30798063/e3615bc1-7a18-4c43-8bf2-31e949f15cfe)

### Additional Context

Log when starting rustdesk from the terminal
```
elforcer@elforcerwork ~ $ rustdesk

** (rustdesk:2173126): WARNING **: 14:37:11.959: Failed to start Flutter renderer: Unable to create GL context
```

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/5843#issuecomment-1738344925

**Comment by ELForcer** [comment]
In my case, a regular reboot helped. It turns out there was an automatic update of NVIDIA drivers and it required a PC reboot. After restarting the PC, the application window appeared.
