### ISSUE TITLE
"Flutter Nightly Build" Screen freezes when mouse over Avast or CCleaner icon

### ISSUE THREAD

**Issue by vbUrmel** [rustdesk/rustdesk#6336]
### Bug Description

When I use "Flutter Nightly Build" on a remote system (Windows 10 / 11) and Avast Antivirus and/or CCleaner is installed there, the following error occurs. When I hover the mouse cursor over the Avast icon or CCleaner icon at the bottom right of the taskbar, the screen freezes and no further operation is possible.
This error only occurs with the "Flutter Nightly Build".

### How to Reproduce

Install Avast Antivirus and / or the CCleaner, and use "Flutter Nightly Build" for Windows.

### Expected Behavior

The Screen is not freezing, and i can use Avast and CCleaner over the Remote Connection.

### Operating system(s) on local side and remote side

Windows 10 / 11

### RustDesk Version(s) on local side and remote side

1.2.4-39

### Screenshots

[08-11-2023_12-11-09.pdf](https://github.com/rustdesk/rustdesk/files/13295986/08-11-2023_12-11-09.pdf)
[08-11-2023_12-11-36.pdf](https://github.com/rustdesk/rustdesk/files/13295987/08-11-2023_12-11-36.pdf)

### Additional Context

We use Rustdesk Pro and want to replace TeamViewer. We support around 100 devices via remote maintenance. Of course this doesn't work with this error.

**Comment by basilgello** [comment]
Only over these icons?

**Comment by vbUrmel** [comment]
No, i start firdt time at 14th September with Rustdesk. Since this date i have this issue.

**Comment by fufesou** [comment]
> When I hover the mouse cursor over the Avast icon or CCleaner icon at the bottom right of the taskbar, the screen freezes and no further operation is possible.

The possible cause of this problem is UAC, but you said it only happens in "Nightly Build", which is very strange.

Will the screen be refreshed?

**Comment by vbUrmel** [comment]
> 1.2.3 work?

No, 1.2.3 is not working

**Comment by rustdesk** [comment]
1.2.2 works now?

**Comment by vbUrmel** [comment]
> > When I hover the mouse cursor over the Avast icon or CCleaner icon at the bottom right of the taskbar, the screen freezes and no further operation is possible.
> 
> The possible cause of this problem is UAC, but you said it only happens in "Nightly Build", which is very strange.
> 
> Will the pictures be refreshed?



> 1.2.2 works now?

All versions from 1.2.2 to the current version do not work.

The cause probably lies in Rustdesk.exe. If I just replace the Rustdesk.exe of the "Flutter Nightly Build" with the regular download version, then everything works.

**Comment by rustdesk** [comment]
Windows is a mystery.

**Comment by vbUrmel** [comment]
> Windows is a mystery.

Thats right !!

**Comment by vbUrmel** [comment]
> Windows is a mystery.

Maybe this is still quite helpful. "Flutter Nightly Build" ended with errors from the start. See attached PDF file. However, until now I was of the opinion that this had nothing to do with Windows.

Thank you in advance for everyone involved's efforts.
[09-11-2023_14-08-24.pdf](https://github.com/rustdesk/rustdesk/files/13308456/09-11-2023_14-08-24.pdf)

**Comment by basilgello** [comment]
These errors are CI related, I thought you spotted anything in logs on affected client PC…

**Comment by vbUrmel** [comment]
> These errors are CI related, I thought you spotted anything in logs on affected client PC…

Thanks, but I'll take a closer look at the logs.

**Comment by fufesou** [comment]
> If the mouse is / was over the Avast Icon, then the Screen refreshes after about 10 seconds. If the mouse is / was over the CCleaner Icon, then the Screen don't refresh. The only way to use the screen again is to trigger "CTRL-ALT-DEL" from the menu and then start the task manager. Then simply close the task manager. Now it works until the mouse cursor lands on the “Avast” or “CCleaner” icon again.

@vbUrmel Thanks for your feedback. Can you please

1. Check if mouse events have effects on the controlled side? To make sure if server is working but picture encoding/decoding do not working.
2. Try switch the connection side

I've installed "CCleaner", but cannot reproduce this issue.

**Comment by vbUrmel** [comment]
> Windows is a mystery.

After further testing, the following emerged.
The screen freezes when I hover the mouse cursor over the CCleaner icon or the Avast icon. If I uninstall Avast completely and restart the PC, the PC does not freeze when I hover the mouse over the CCleaner icon. The cause must be a combination of Rustdesk and Avast.

I have not yet encountered such errors with TeamViewer and other VNC tools.

As a reminder: The screen only freezes if the “Flutter Nightly Build” is installed. If I install the version from the normal download, i.e. where I have to enter the server and key manually, everything works perfectly.

Since September 14th, 2023 I have been trying to prepare Rustdesk Pro for professional use. Unfortunately, this still doesn't work properly to this day. Since our subscription with the TV expires on December 1st, 2023, I must have made a decision by then as to which remote software I can work with in the future.

I would like to choose Rustdesk.

Thank you for your effort in advance.

**Comment by rustdesk** [comment]
Since 1.2.3 worked for you, but nightly not. We can build nightly build of different day for you to test and find out the root.

**Comment by wingsman2** [comment]
I am also running into this issue. If I hover my mouse over the avast icon it seems like my remote session is frozen. Mouse inputs are not sent over but I can send ctrl-alt-del to regain control. Interesting enough if I move the mouse off the avast icon on the remote machine the session seems to resume as if nothing has happened. I have not tested any other build. I have just run my own via GitHub Actions. Is there a place for local logs? I tried doing the session recording from both remote device and controlling device but neither are producing recordings.

**Comment by rustdesk** [comment]
> I will note that avast seems to detect the Flutter Nightly Build of mine as a possible generic trojan which might be avast suspending the program from interacting with avast to try and prevent AV bypassing.

Good job.
