### ISSUE TITLE
add session manager to replace x2go and nomachine

### ISSUE THREAD

**Issue by congzhangzh** [rustdesk/rustdesk#634]
Hi Rustdesk,

As title, x2go is very lagging, and nomachine is not free for multisession support。

if rustdesk support special mode to spawn more xephyr as standalone session, it will be very helpful and revolutionary of clouddesktop way of xwindows server.

with session manager that shoud be easy to do something like xrandr.

Tks,
Cong

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
Who are the target users for session manager? I can not understand the scenario.

**Comment by congzhangzh** [comment]
> Who are the target users for session manager? I can not understand the scenario.

A team to access a super computer to develop or do some ui related work。

x2go is very slow, nomachine is very fast but limit one session for free version, btw nomachine is magic fast and powerful!

**Comment by congzhangzh** [comment]
A session manager to start headless x server and gnone like things

**Comment by rustdesk** [comment]
I used nomachine before, not saw magic.

**Comment by congzhangzh** [comment]
> I used nomachine before, not saw magic.

seems your are right, I use rustdesk to connect to rustdesk in nomachine now, it's smooth:)

**Comment by congzhangzh** [comment]
> > Who are the target users for session manager? I can not understand the scenario.
> 
> A team to access a super computer to develop or do some ui related work。
> 
> x2go is very slow, nomachine is very fast but limit one session for free version, btw nomachine is magic fast and powerful!

even x2go very laging, connect rustdesk in x2go very soooth, the only problem is that keyboard input seems be input twice each time when type from rustdesk, can you give a try @rustdesk

BTW, if rustdesk support run different instance for each x2go X session, the problem can be workaround, as connect to 21118+1/2/3/4 for session 1/2/3/4

**Comment by rustdesk** [comment]
Sorry， I have no x2go server env to debug.

**Comment by rustdesk** [comment]
Low priority.

**Comment by congzhangzh** [comment]
Maybe we can split session manager to another  application and make rustdesk focus on remote control? Like add a one 2 one client/server mode with preshare key?

# basic idea, raw server client
server:

``` bash
rustdesk —just-server [xx.xx.xx.xx:]21118 —key-file ~/.rustdesk/prehare-key
```

client:

``` bash
rustdesk —connect-to 21118 —key-file prehare-key-file
```

# with session manager wrapper

``` bash
# client connect to server run desktop & rustdesk in xvfb
ssh xx@xx.xx <<EOF
xvfb :xx&
export DISPLAY=:xx.0
dbus-launch desktop-session-manager &
rustdesk —just-server [xx.xx.xx.xx:]21118 —key-file ~/.rustdesk/prehare-key
#TODO
EOF
# start client rustdesk to connect to it
rustdesk —connect-to 21118 —key-file prehare-key-file
```

**Comment by congzhangzh** [comment]
the mvp can be done in a weekend, and the xvfb part has be tested:) even opengl 4.6 is support in the latest xvfb.

btw, the 100% bitrate is great, even game can be played remotely, and udp maybe improve it to next level?

**Comment by alatteri** [comment]
> I used nomachine before, not saw magic.

Agreed.... NoMachine on macOS is very un-reliable, and on all platforms, the quality is shitty h264 4:2:0 video.

**Comment by chchia** [comment]
i am using both nomachine and rustdesk, nomachine is super fast and superb display quality (much better than rustdesk to be honest) easily close to 60fps, but sometime it get randomly disconnected and need to manual reconnect again.

**Comment by rustdesk** [comment]
Allow us some time to get better.

**Comment by congzhangzh** [comment]
> i am using both nomachine and rustdesk, nomachine is super fast and superb display quality (much better than rustdesk to be honest) easily close to 60fps, but sometime it get randomly disconnected and need to manual reconnect again.

Udp be the key, even when go across trojan:)

**Comment by chchia** [comment]
> Allow us some time to get better.

right, very much appreciate the time and effort you put on this wonderful project.

by the way, do you plan to have nightly build for testing purposes?

**Comment by rustdesk** [comment]
No, we do not update frequently, you see we have very few contributors.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1131

**Comment by congzhangzh** [comment]
this is cool, https://github.com/rustdesk/rustdesk/pull/3902

@fufesou just need multi-session support, is that possible to add some context semantically 

```bash
# the context maybe default/from cmd line/from the environment var
sudo rustdesk  [--session-context [context]] --get-id 
```

**Comment by congzhangzh** [comment]
maybe we can add 3d accelation ?:)

https://github.com/rustdesk/rustdesk/pull/3902/files#diff-26550121d7f5c5179c46ff523f3b81787d25f4ab59724e5a0b1b98572b15c87b
https://www.freedesktop.org/wiki/Software/Glamor/
https://github.com/XQuartz/xorg-server/blob/master/glamor/glamor.c
https://github.com/Xpra-org/xpra/issues/56
https://lists.x.org/archives/xorg-devel/2017-August/054312.html
https://lists.x.org/archives/xorg-devel/2017-August/054310.html

**Comment by congzhangzh** [comment]
https://gitlab.freedesktop.org/xorg/driver/xf86-video-dummy

**Comment by congzhangzh** [comment]
@yuq what's the status about your glamor driver for dummy, can we use or fix it? 


https://lists.x.org/archives/xorg-devel/2017-August/054306.html

**Comment by fufesou** [comment]
@congzhangzh Thanks for searching. Your replies seem helpful.
But we have very few contributors.
We have no plan to update the virtual display under linux in the near future.

**Comment by congzhangzh** [comment]
> @congzhangzh Thanks for searching. Your replies seem helpful. But we have very few contributors. We have no plan to update the virtual display under Linux in the near future.

@fufesou OK,  it's nice to have:)

Tks for your great  work, I think your teams' work will revolutionize on vdi market

**Comment by rustdesk** [comment]
Let's focus on our target.
