### ISSUE TITLE
Can not connect to  server with IPv6.

### ISSUE THREAD

**Issue by goodluck1982** [rustdesk/rustdesk#6344]
### Bug Description

I use the docker `hbbs/hbbr (ver 1.1.8-2)` as my server.  Ports 21116 and 21117 are opened for both IPv4 and IPv6.
On client `(ver 1.2.3)`, if I use the IPv4 address of the server, the service is "Ready".
But if I use the IPv6 address of the server,  the service is "Not Ready"

### How to Reproduce

Use IPv6 address for the ID server.

### Expected Behavior

Work for both IPv4 and IPv6.

### Operating system(s) on local side and remote side

Linux -> Linux

### RustDesk Version(s) on local side and remote side

1.2.3 

### Screenshots

![图片](https://github.com/rustdesk/rustdesk/assets/48718961/43c70649-70db-40f0-b603-c4e8b3640b74)
![图片](https://github.com/rustdesk/rustdesk/assets/48718961/32a62272-ab01-4b25-9e66-dc820af27df3)

![图片](https://github.com/rustdesk/rustdesk/assets/48718961/051dc51d-9fca-4aef-a024-44419ec1eba7)

**Comment by rustdesk** [comment]
#763

**Comment by BenK885** [comment]
Isn't there a way to add a IPv4 / IPv6 toggle in ID/Relay-Server settings? Or change the IPv4 / IPv6 prioritization?
