### ISSUE TITLE
Rustdesk won't connect on KDE6.0

### ISSUE THREAD

**Issue by pnunn** [rustdesk/rustdesk#6348]
### Bug Description

I have installed Rustdesk on KDE Neon Experimental and it refuses to connect.

### How to Reproduce

Install KDE Neon Experimental, install rustdesk latest, run it.

### Expected Behavior

A connection via either remote password, or connecting on accept from the connection popup on the host.

### Operating system(s) on local side and remote side

KDE Neon Experimental

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

N/A

### Additional Context

Log on remote shows

Nov  9 18:52:54 neon-unstable xdg-desktop-portal-kde[15937]: xdp-kde-settings: Namespace  "org.gnome.desktop.a11y.interface"  is not supported
Nov  9 18:52:54 neon-unstable rustdesk[85245]: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
Nov  9 18:52:54 neon-unstable xdg-desktop-portal-kde[15937]: xdp-kde-settings: Namespace  "org.gnome.desktop.interface"  is not supported
Nov  9 18:52:54 neon-unstable rustdesk[85245]: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
Nov  9 18:52:54 neon-unstable rustdesk[85245]: flutter: launch args: [--cm]
Nov  9 18:52:54 neon-unstable rustdesk[85245]: flutter: --cm started
Nov  9 18:52:54 neon-unstable rustdesk[85245]: flutter: initializing FFI cm
Nov  9 18:52:54 neon-unstable rustdesk[85245]: flutter: _appType:cm,info1-id:637161fcde6641d8ba82a7a8b4c69122,info2-name:KDE neon,dir:/home/pnunn
Nov  9 18:52:54 neon-unstable rustdesk[85245]: flutter: _globalFFI init
Nov  9 18:52:54 neon-unstable rustdesk[85245]: flutter: _globalFFI init end
Nov  9 18:52:54 neon-unstable rustdesk[85245]: flutter: registerEventHandler theme theme
Nov  9 18:52:54 neon-unstable rustdesk[85245]: flutter: registerEventHandler language language
Nov  9 18:52:54 neon-unstable rustdesk[85245]: flutter: registerEventHandler native_ui native_ui
Nov  9 18:52:55 neon-unstable rustdesk[85245]: flutter: Bring window 'null' on top
Nov  9 18:53:07 neon-unstable rustdesk[81769]: Authorization required, but no authorization protocol specified
Nov  9 18:53:07 neon-unstable rustdesk[81769]: Authorization required, but no authorization protocol specified
Nov  9 18:53:07 neon-unstable rustdesk[85245]: flutter: Bring window 'null' on top
Nov  9 18:53:07 neon-unstable rustdesk[85245]: flutter: model  closed
Nov  9 18:53:07 neon-unstable rustdesk[85245]: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed
Nov  9 18:53:07 neon-unstable rustdesk[85245]: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed
Nov  9 18:53:07 neon-unstable rustdesk[85245]: gtk_window_get_position: assertion 'GTK_IS_WINDOW (window)' failed
Nov  9 18:53:07 neon-unstable rustdesk[85245]: gtk_window_get_size: assertion 'GTK_IS_WINDOW (window)' failed
Nov  9 18:53:07 neon-unstable rustdesk[85245]: gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed
Nov  9 18:53:07 neon-unstable rustdesk[85245]: gtk_window_move: assertion 'GTK_IS_WINDOW (window)' failed
Nov  9 18:53:07 neon-unstable rustdesk[85245]: gtk_window_resize: assertion 'GTK_IS_WINDOW (window)' failed
Nov  9 18:53:07 neon-unstable rustdesk[81769]: Authorization required, but no authorization protocol specified
Nov  9 18:53:07 neon-unstable rustdesk[81769]: kbd context error
Nov  9 18:53:07 neon-unstable rustdesk[81769]: Authorization required, but no authorization protocol specified
Nov  9 18:53:07 neon-unstable rustdesk[81769]: Error: Can't open display: (null)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by cinit** [comment]
A temporary fix is to run `ln -s /tmp/xauth_* ~/.Xauthority` at X startup, assuming that there is only one /tmp/xauth_* file.

**Comment by maedas** [comment]
Same issue using nixpkgs/rustdesk-flutter 1.3.0 on the following system:

Operating System: NixOS 24.05
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.2
Kernel Version: 6.6.43 (64-bit)
Graphics Platform: Wayland

Posting just to make it known to devs and others. 
Hope this gets resolved fairly soon and thanks for making a good alternative to lesser remote desktop software!
