### ISSUE TITLE
No input on Wayland

### ISSUE THREAD

**Issue by LilToaster69** [rustdesk/rustdesk#6356]
### Bug Description

I can't control another PC with Archlinux and Wayland on KDE.

### How to Reproduce

Open RustDesk on your PC and another PC with wayland you want to connect.
Accept the connection on the PC with wayland and try to move the mouse.

### Expected Behavior

The mouse and keyboard to work.

### Operating system(s) on local side and remote side

Arch Linux (Wayland) -> Arch Linux (Wayland)

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

**Comment by sahilyeole** [comment]
Please ensure if `rustdesk --service` is running as root or not (`ps aux | grep rustdesk`).
If not try `sudo systemctl restart rustdesk`.
