### ISSUE TITLE
Privacy mode / Lock Screen

### ISSUE THREAD

**Issue by blueice777** [rustdesk/rustdesk#636]
Hi, it would be nice if we can get "privacy mode" like enabling user to ask for a password/pin code when RustDesk is started... this is to protect remote desktops where you have saved password...

Thanks

**Comment by fufesou** [comment]
Hi, the "privacy mode" you've mentioned seems like an account management is OS.

**Comment by blueice777** [comment]
Hi, this is not connected with OS. It is like when you use Signal and you can setup Pin Lock for screen. So if anyone unlocks your phone, they can't access to Signal app without PIN/Password. 

Imagine if you control lets say 10 company computers and you save login for each remote machine, if anyone gets the access to RustDesk they can access directly to these computers. But if you "lock" your RustDesk screen no one can access your remote machines list.

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by Heap-Hop** [comment]
Thanks, good advice, we will consider putting it into next version.
Both RustDesk UI and cli mode all need to implement `Pin Lock`.

**Comment by blueice777** [comment]
Thanks, I'm glad you like it. It would be good also to encrypt database and decrypt on PIN unlock. 

Database = List of remote machine ID's

Another question, can we change client name? So when you get connected to hide original username of client.

**Comment by rustdesk** [comment]
> next version
This can not be ensured.

**Comment by blueice777** [comment]
Related to Privacy Mode, also add option to disable any log or trace back to previous sessions if user wants to. Is this possbile?

**Comment by naddel91** [comment]
Is PrivacyMode implemented?

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/636

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/65
