### ISSUE TITLE
Latest nightly broken connection

### ISSUE THREAD

**Issue by TheGrave** [rustdesk/rustdesk#6360]
### Bug Description

I migrated from the 1.2.3 nightly to the 1.2.4 nightly and I can no longer access my Android hosts from Ubuntu (tried Android 11 and 13 - same story). No settings changed, just updated the app on both sides

### How to Reproduce

Install 1.2.4 nighly on a Linux client and and Android one, try connection from the first to the second one.

### Expected Behavior

Connection suffessfull

### Operating system(s) on local side and remote side

Ubuntu 20.04 and Android 11/13

### RustDesk Version(s) on local side and remote side

1.2.4 nightly on both

### Screenshots

https://ibb.co/WpmYmyF

**Comment by basilgello** [comment]
Can you install 1.2.3 on some Android host and try connecting to it with nightly client?

I am testing the opposite scenario (nightly Android -> nightly Debian) and keep getting "Connection reset by peer" every 10-12 seconds. Downgrading host RustDesk to 1.2.3 works fine.

**Comment by sahilyeole** [comment]
It's working for me.
I tested:
Android (1.2.3) -> nightly debian
nightly debian -> Android (1.2.3)
nightly android -> nightly debian
nightly debian -> nightly android

Android 12, nightly build: 10 nov

<img width="300" alt="Screenshot 2023-11-10 at 5 07 09 PM" src="https://github.com/rustdesk/rustdesk/assets/73148455/ea7f6876-ee6f-4484-af04-0577a51e56d4">

![Screenshot from 2023-11-10 17-00-07](https://github.com/rustdesk/rustdesk/assets/73148455/e75747c7-c37f-4f7f-8d7d-a53adc71afe2)

**Comment by basilgello** [comment]
Androids worked for me flawlessly 1st time but 2nd time I got disconnects. I suspect a flaky/overloaded relay server. If connection dices on that server, it becomes choppy.

**Comment by TheGrave** [comment]
Can you point me where I can find the 1.2.3 nightlies? Can't find my way around the github repo.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3556#issuecomment-1804010109

**Comment by 21pages** [comment]
try https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.2.4-aarch64-flexi_logger-0.27.3.apk

**Comment by TheGrave** [comment]
Tested Android 13 nighly to Android 11 nightly - was broken too so I rolled back to 1.2.3. Did you integrate the new patch for using the physical keyboard on the client side to type things on the host side in the stable release already? Seems to me that way at least, nice surprise :)

**Comment by 21pages** [comment]
Did the android client crash?

**Comment by basilgello** [comment]
Not on my side :) By the way, waiting for image occurs for me every first connection with 1.2.4 nightly android -> 1.2.3 debian. Second connection is fine and stablr. How do I turn on extended logging on release builds?

**Comment by 21pages** [comment]
Give app file permissions, log stored in <external storage>/RustDesk/Logs

**Comment by basilgello** [comment]
And on Debian - do I need to install journald into test container or logfile can be specified on command line?

**Comment by 21pages** [comment]
linux log path: https://github.com/rustdesk/rustdesk/blob/58596ad1ab1b96aaaba697a4ef86f9565f8a255d/libs/hbb_common/src/config.rs#L623

**Comment by basilgello** [comment]
By the way, "Waiting for image" can be mitigated by "Force refresh canvas".

**Comment by 21pages** [comment]
When "Waiting for Image" keeps appearing, did you see the remote image already showing?

**Comment by basilgello** [comment]
Nope. You input password and waiting for image pops up but no image is shown until you eother hit Cancel and reconnect or force refresh canvas via menu in android client.

The logs for both issues:

* Waiting for image and reconnect (1.2.4 android client, 1.2.3 debian server):
[rs_waitingforimage_androidclient124.txt](https://github.com/rustdesk/rustdesk/files/13327586/rs_waitingforimage_androidclient124.txt)
[rustdesk_waitingforimage_debianserver123.txt](https://github.com/rustdesk/rustdesk/files/13327588/rustdesk_waitingforimage_debianserver123.txt)

* Disconnects(1.2.4 android client, 1.2.4 debian server):
[rs_disconnects_androidclient124.txt](https://github.com/rustdesk/rustdesk/files/13327589/rs_disconnects_androidclient124.txt)
[rustdesk_disconnects_debianserver124.txt](https://github.com/rustdesk/rustdesk/files/13327590/rustdesk_disconnects_debianserver124.txt)

**Comment by basilgello** [comment]
I have a feeling that disconnects are related to cm fix somehow. If needed, I can share Dockerfile to reproduce the Debian environment.

**Comment by 21pages** [comment]
Much appreciated.

**Comment by basilgello** [comment]
The error in the log points to

```
[2023-11-12 08:34:10.600116 +00:00] ERROR [src/server/connection.rs:1486] ipc to connection manager exit: No valid uid [2023-11-12 08:34:10.600221 +00:00] INFO [src/server/connection.rs:2637] #149 Connection closed: connection manager error: No valid uid
```

and reconnect appears. It is in server side, client shows "Connection reset by peer".

**Comment by 21pages** [comment]
Yes, it's the reason.

**Comment by 21pages** [comment]
After this commit, connection will be disconnected if cm crash.
https://github.com/rustdesk/rustdesk/commit/36b574a5f8dfd69b0d868567c2d4c66176bc039c

**Comment by basilgello** [comment]
The docker / podman set-up: 
[debian-xorg-rustdesk.tar.gz](https://github.com/rustdesk/rustdesk/files/13327703/debian-xorg-rustdesk.tar.gz)

**Comment by basilgello** [comment]
RD runs under root, and XDG_RUNTIME_DIR for root is just /run And running as root is perfectly valid usecase :)

**Comment by basilgello** [comment]
Also, in the same setup file transfer is broken: "No active console user logged" or something like that.
