### ISSUE TITLE
Black screen when WIN7 remote control other PC

### ISSUE THREAD

**Issue by louislau86** [rustdesk/rustdesk#6404]
### Bug Description

In a local area network, when using rustdesk to remotely control a WIN10 computer from a WIN7 computer, the connection can be completed, but the window on the control end displays a black screen status after the connection. Computers are directly connected through a local area network without passing through a transit server.

The attachment is the rustdesk log on Win7, which occurred on November 10th.
[log in win7.zip](https://github.com/rustdesk/rustdesk/files/13343404/log.in.win7.zip)

### How to Reproduce

Using a WIN7 computer with the below OS vesion， remote connect a win10 computer by rustdesk on direct network connection

### Expected Behavior

the rustdesk function normally

### Operating system(s) on local side and remote side

WIN7 -> WIN10

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.2

### Screenshots

![win7 version](https://github.com/rustdesk/rustdesk/assets/28438430/2b9049fe-1db5-47db-b266-aba2e49c29a4)
![black screen capture](https://github.com/rustdesk/rustdesk/assets/28438430/a74aab38-b30c-43dc-8dcd-7ce9d24a6cb1)

**Comment by 21pages** [comment]
Please try latest nighly

**Comment by rustdesk** [comment]
BTW, #763

**Comment by flt6** [comment]
You can try to disable `Use texture rendering` in general option. I solved the same problem by this way.
