### ISSUE TITLE
Mac: keyboard some keys not working

### ISSUE THREAD

**Issue by pete1019** [rustdesk/rustdesk#6412]
### Bug Description

Big Issue:

On Mac to Mac connection: after some minutes some key like "e" or "n" just don't work anymore.
Tried everything.

This happens with 1.2.3 or the latest 1.2.4 nightly.

Is this a known bug? Why does this happen?

Thanks a lot.

### How to Reproduce

after some minutes

### Expected Behavior

all keys working

### Operating system(s) on local side and remote side

OSX

### RustDesk Version(s) on local side and remote side

1.2.3 or 1.2.4 nightly

### Screenshots

No screenshot possible to explain.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367
