### ISSUE TITLE
Waiting for screen transmission！

### ISSUE THREAD

**Issue by UNIONDONG** [rustdesk/rustdesk#6419]
### Bug Description

connect success ， Waiting for screen transmission 

![image](https://github.com/rustdesk/rustdesk/assets/35584433/db212d3a-f7ca-4df2-8a28-15d52d9715fd)

### How to Reproduce

enter password and connect success 

### Expected Behavior

can be use

### Operating system(s) on local side and remote side

windows11

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/35584433/07fb7196-ce1e-4ad3-94bd-d3cdcd787116)

**Comment by pdifeo** [comment]
Same problem only on a single site for the moment

The remote client is connected and in Ready state
![1](https://github.com/rustdesk/rustdesk/assets/8618744/d8899e95-631a-4f91-87f1-69e7d612c613)

the local client is always connecting 

https://github.com/rustdesk/rustdesk/assets/8618744/3319dc59-7c7d-4ddd-b952-d9a2c4aa5468

**Comment by pdifeo** [comment]
The last time I was able to connect was version 1.2.1

**Comment by pdifeo** [comment]
This is what is present into log of hbbr for this connection 

 [src/relay_server.rs:456] New relay request 14644c4c-1316-4663-bd4e-3bdb7cf1e0ce from [::ffff:xx.x30.1xx.2xx]:30919
 [src/relay_server.rs:452] Relay of [::ffff:xx.x30.1xx.2xx]:32253 closed

Normally there are 

[src/relay_server.rs:456] New relay request 909c09b0-d8fd-4b8d-a18f-be68f37cd0d2 from 
[src/relay_server.rs:440] Relayrequest 909c09b0-d8fd-4b8d-a18f-be68f37cd0d2 from [::ff
[src/relay_server.rs:446] Both are raw

both client are configured to use the same relay server. Connecting with ip address, instead, is working.

**Comment by 21pages** [comment]
@pdifeo  Is the key of the controlled side correct?

**Comment by rustdesk** [comment]
@fufesou please diagnose this with @pdifeo

**Comment by fufesou** [comment]
@pdifeo Hi, thanks for your feedback. 

> [src/relay_server.rs:456] New relay request 14644c4c-1316-4663-bd4e-3bdb7cf1e0ce from [::ffff:xx.x30.1xx.2xx]:30919
[src/relay_server.rs:452] Relay of [::ffff:xx.x30.1xx.2xx]:32253 closed

Is the log here complete? 

Can you please show the build date in the settings page?

![image](https://github.com/rustdesk/rustdesk/assets/13586388/a9a24fa5-7f73-4659-b036-b310dd1fd849)


Do you always get the "deadline" error?

**Comment by pdifeo** [comment]
The log is not complete and I cannot post here for security. The version is, as told, 1.2.3

Yes, aleays get "deadline". In the past (1.2.1 client and 1.1.9 server, i have license), after a couple of attempts it was possible to connect

![image](https://github.com/rustdesk/rustdesk/assets/8618744/eb66480b-fd43-4c68-add4-7204be30324e)

**Comment by fufesou** [comment]
@pdifeo Hi, do you use self-host server or the public server? It's a little hard for me to reproduce your issue.

**Comment by fufesou** [comment]
@UNIONDONG Hi, I've sent you an email.

If you do not receive the email, you can send an email to [me](shuanglongchen@yeah.net).

I cannot reproduce your issue. Can I connect your PC to see what's wrong.

**Comment by pdifeo** [comment]
> > Yes, aleays get "deadline". In the past (1.2.1 client and 1.1.9 server, i have license), after a couple of attempts it was possible to connect
> 
> This is another problem， please do not mix with "waiting for image" issue.

Of course. I replied to question.

> @pdifeo Hi, do you use self-host server or the public server? It's a little hard for me to reproduce your issue.

As told, I have licensed server. How else could I have sent you the logs?

**Comment by rustdesk** [comment]
@21pages follow up @pdifeo 's deadline issue, please do it in another thread.

**Comment by UNIONDONG** [comment]
> @UNIONDONG Hi, I've sent you an email.
> 
> If you do not receive the email, you can send an email to [me](shuanglongchen@yeah.net).
> 
> I cannot reproduce your issue. Can I connect your PC to see what's wrong.

I get it and I have connect you by wechat, thank you

**Comment by UNIONDONG** [comment]
thank @fufesou  help . Today when I go home then it is ok . 

I don't know what happend.......

**Comment by rustdesk** [comment]
@fufesou dig it out if there is some clue
