### ISSUE TITLE
VMWare app doesn't render well. it's almost unvisible 

### ISSUE THREAD

**Issue by VojkoCendak** [rustdesk/rustdesk#6431]
### Bug Description

Hi, (VMWARE 15.5.7, guest Windows 10 pro latest)

when we installed version 1.2.4, the main form doesn't render well at all.
Fonts are kind of very blurred. If I switch off 3D accelerate graphics it works.

### How to Reproduce

just install and run.

### Expected Behavior

well visible form with controls, ...

### Operating system(s) on local side and remote side

Windows 10 pro latest

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/7000744/747acdc2-9299-41bd-a8aa-379cbd222c76)

**Comment by rustdesk** [comment]
flutter related.
