### ISSUE TITLE
Waiting for display on Linux Arch (but transfer & chat work)

### ISSUE THREAD

**Issue by ngharris** [rustdesk/rustdesk#6456]
### Bug Description

-This occurs from Linux-to-Linux and from Windows-to-Linux.
-rustdesk-nightly 1.24 (on both ends). We have also downgraded to rustdesk 1.20 (same issue)
-The display connects successfully but an image is not shown. However, the chat and transfer work without fail.
-This occurs using all default settings of rustdesk.
-This also occurs using the IP address of the target Linux system.

This is the readout:
(see screenshot)

### How to Reproduce

Install rustdesk on Arch (fully updated, KDE or XFCE desktop, SDDM manager)
Start rustdesk using either sudo systemctl or manually as a user
Connect to Linux Desktop  from either another Linux or Windows11 box.

Incidentally, Display remote computers onto the Linux computer works fine.
Tried removing the fire wall- no difference

### Expected Behavior

Expect the display to show.

### Operating system(s) on local side and remote side

Linux-->Linux or Windows

### RustDesk Version(s) on local side and remote side

1.24

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/101953721/98a5512f-adcc-456c-81b9-cf98ad624293)

### Additional Context

[rustdesk_rCURRENT.log](https://github.com/rustdesk/rustdesk/files/13397738/rustdesk_rCURRENT.log)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by rustdesk** [comment]
@sahilyeole let's have quick fix for ssdm

**Comment by sahilyeole** [comment]
sddm + xfce on arch (endeavour os, updated), nightly rustdesk is working without any issue for me.


https://github.com/rustdesk/rustdesk/assets/73148455/be7aefa1-f6e0-42df-8590-089deb7a490e

**Comment by ngharris** [comment]
Update: (Success) The failure to show image on the client is reliably fixed by setting the display codec on the client to H265 or H264 (from the default setting Auto). (rustdesk nightly v1.2.4 on both ends).

**Comment by rustdesk** [comment]
vp8/9 does not work?

**Comment by rustdesk** [comment]
Please try out the new nightly build, we have a fix for software codecs.
