### ISSUE TITLE
keyboard does not work right in x2go session

### ISSUE THREAD

**Issue by congzhangzh** [rustdesk/rustdesk#646]
**Describe the bug you encountered:**

if I type anything wit will happan twice, for both alphabet and control key like up/down/left/right

**What did you expect to happen instead?**

one for each type

**How did you install `RustDesk`?**

deb Package

---

**RustDesk version and environment**

the latest version of rustdesk, and the latest stable debian which x2goserver, but I think this problem should happen on ubuntu too

**more info to reproduce**

1. I run connect to x2goserver
2. run rustdesk
3. connect to it by ip direct 
4. works magic but keyboard will be twice for each type

**Comment by rustdesk** [comment]
Sorry， I have no x2go server env to debug. Low Priority.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/634
