### ISSUE TITLE
RustDeskIdd: Failed InstallUpdate in privacy mode 2

### ISSUE THREAD

**Issue by Creling** [rustdesk/rustdesk#6472]
### Bug Description

![image](https://github.com/rustdesk/rustdesk/assets/43109504/dd358de5-1893-4a2b-9c54-8e203410b6d5)

local device: windows11 + Rustdesk v1.2.4 2023-11-18 00:22
remote device: windows11 + Rustdesk v1.2.4 2023-11-18 00:22

### How to Reproduce

Just connect to the remote device and enable privacy mode 2

### Expected Behavior

N/A

### Operating system(s) on local side and remote side

Window 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

Rustdesk v1.2.4 2023-11-18 00:22 -> Rustdesk v1.2.4 2023-11-18 00:22

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/43109504/dd358de5-1893-4a2b-9c54-8e203410b6d5)

**Comment by Creling** [comment]
Update: For anyone meet this issue like me, you should enable the "Install the Cert" when installing the Rustdesk.

**Comment by fufesou** [comment]
@Creling Hi, do you solve this issue by installing the cert?

<img width="941" alt="1700451833968" src="https://github.com/rustdesk/rustdesk/assets/13586388/efb5e083-0424-4005-a652-d6de3083969d">

**Comment by Creling** [comment]
> @Creling Hi, do you solve this issue by installing the cert?
> 
> <img alt="1700451833968" width="941" src="https://user-images.githubusercontent.com/13586388/284123958-efb5e083-0424-4005-a652-d6de3083969d.png">

yep, I have resolved it by installing the cert.

**Comment by fufesou** [comment]
> Update: For anyone meet this issue like me, you should enable the "Install the Cert" when installing the Rustdesk.

I'll do it.
