### ISSUE TITLE
fail to start rustdesk in Ubuntu 20.04.6 LTS

### ISSUE THREAD

**Issue by erictamhk** [rustdesk/rustdesk#6477]
### Bug Description

cannot open the rustdesk in Ubuntu 20.04.6 LTS
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
rustdesk: ../../src/xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)

### How to Reproduce

just install it in the Ubuntu 20.04.6 LTS
and try to start it

### Expected Behavior

open the rustdesk

### Operating system(s) on local side and remote side

Ubuntu 20.04.6 LTS

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/36356044/2858d4d8-2d95-4c52-b288-953dceae93b7)

**Comment by rustdesk** [comment]
@sahilyeole please follow up

**Comment by rustdesk** [comment]
@erictamhk could you run from source?

**Comment by erictamhk** [comment]
> @erictamhk could you run from source?

don't know how to do, sorry

**Comment by erictamhk** [comment]
after uninstall it and install it multiple times, it works

**Comment by rustdesk** [comment]
> after uninstall it and install it multiple times, it works

Bad news, this makes debugging harder.

**Comment by sahilyeole** [comment]
I could not reproduce but it seems like an issue with libx11/distro.
https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/170
https://github.com/godotengine/godot/issues/69352#issuecomment-1749767338
https://github.com/godotengine/godot/issues/75308#issuecomment-1751010890

@erictamhk what version of libx11 are you using?
Please try updating to the latest version of libx11, if it still does not work try downgrading libx11 to 1.8.4
