### ISSUE TITLE
Enable remote configuration modification bypass

### ISSUE THREAD

**Issue by emielmaters** [rustdesk/rustdesk#6484]
### Bug Description

When hovering over the settingspanel in the remote desktop, it is not clickable.
However, using the tab-, arrows and enter button, you can manage to check the 'Enable remote configuration modification' checkbox. After that you get full control to the settings.

### How to Reproduce

1. connect to remote client
2. use tab key to highlight the settingstab
3. while in the settings view, use arrows and enter button to select the option 'Enable remote configuration modification'

### Expected Behavior

Expected behavior is not to be able to use keyboard to navigate around and bypass the 'Enable remote configuration modification' setting.

### Operating system(s) on local side and remote side

Windows 11 --> Windows Server 2022

### RustDesk Version(s) on local side and remote side

1.2.3 --> 1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/37311615/026409a5-689c-4e02-9c51-84e9fcf1d98e)
![image](https://github.com/rustdesk/rustdesk/assets/37311615/9a173fec-3daf-4d60-a70e-249ecb408d3c)

**Comment by rustdesk** [comment]
duplicate: https://github.com/rustdesk/rustdesk/issues/2680
