### ISSUE TITLE
Can't change OS password

### ISSUE THREAD

**Issue by kingprapop** [rustdesk/rustdesk#6495]
### Screenshots
![image](https://github.com/rustdesk/rustdesk/assets/67626409/ceda1613-6aa7-4fe0-bcd6-248ecb73b104)
when i want to change OS Password (IOS 1.2.2), click pencil icon (next OS Password). it paste last password ,not edit
I test on PC (1.2.3) ,it normal to change with same process

### How to Reproduce

everytime in IOS (1.2.2)

### Expected Behavior

I think buttom area of Icon edit was behide OS Password buttom.

### Operating system(s) on local side and remote side

IOS->win10

### RustDesk Version(s) on local side and remote side

1.2.2->1.2.3

**Comment by rustdesk** [comment]
It is working on 1.2.4, for iOS 1.2.4, you have to wait.

**Comment by rustdesk** [comment]
@21pages fix it

**Comment by rustdesk** [comment]
close since fix merged

**Comment by kingprapop** [comment]
Thank you , For every quick fix.
