### ISSUE TITLE
iD does not exist

### ISSUE THREAD

**Issue by jotenakis2** [rustdesk/rustdesk#6499]
### Bug Description

I am using rustdesk since one month it is working well.
I have tried to install hbbs and hbbr for self hosting, on the same machine I want to take control of.

### How to Reproduce

with hbbr and hbbs -r localhost running, and configuring the client with LAN IP adress of the self hosted serer (plus pub Key), I cannot connect. 

### Expected Behavior

Error message is : ID does not exist.
Status bar is indicating : READY in green.

### Operating system(s) on local side and remote side

MACOS -> ARCH LINUX

### RustDesk Version(s) on local side and remote side

1.1.8 -> 1.1.8

### Screenshots

<img width="364" alt="Capture d’écran 2023-11-22 à 11 31 35" src="https://github.com/rustdesk/rustdesk/assets/111786784/eec7af6d-d512-4df4-8dbb-118ec99275b0">

**Comment by rustdesk** [comment]
#763
