### ISSUE TITLE
Privacy Mode (Blacken the screen)

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#65]
Need your help, I have no idea how to implement it yet.

**Comment by geshii** [comment]
You mean, clicking on a button to hide the screen ? But still keep the audio?

**Comment by rustdesk** [comment]
> You mean, clicking on a button to hide the screen ? But still keep the audio?
> Sorry for bumping by the way

Blacken the physical screen, but remote display still works

**Comment by rustdesk** [comment]
> > You mean, clicking on a button to hide the screen ? But still keep the audio?
> > Sorry for bumping by the way
> 
> Blacken the physical screen, but remote display still works

Need to write display card driver.

**Comment by rustdesk** [comment]
https://www.wowza.com/community/t/blocking-screen-capture/38423/5    

> Actually blocking screen captures probably requires hooking into the video drivers to detect if anything else hooks into the video drivers.

**Comment by geshii** [comment]
> 
> 
> > > You mean, clicking on a button to hide the screen ? But still keep the audio?
> > > Sorry for bumping by the way
> > 
> > 
> > Blacken the physical screen, but remote display still works
> 
> Need to write display card driver.

Oh I see ! But how will you re-enable it after ? If you want to enable it from the physical pc ? A keybind ?

**Comment by geshii** [comment]
https://en.wikipedia.org/wiki/Hardware_overlay
Something like this ?

**Comment by rustdesk** [comment]
> https://en.wikipedia.org/wiki/Hardware_overlay
> Something like this ?

Maybe, I am not sure if "hardware overlay window" affects remote display

**Comment by rustdesk** [comment]
> re-enable

After connection closed

**Comment by geshii** [comment]
> After connection closed

Ok

> Maybe, I am not sure if "hardware overlay window" affects remote display
I will try to learn more info about this ASAP

**Comment by rustdesk** [comment]
@geshii Thanks

**Comment by atomsos** [comment]
Software 向日葵(https://sunlogin.oray.com/download/) and teamviewer has the function. It seems involving a driver hacking.

e.g. 
![](https://pic2.zhimg.com/80/v2-bd0711fd67d0a9f9b5d0a7222b2ea1e9_720w.jpg)

![](https://pic3.zhimg.com/80/v2-9e93c9d17e8628af2033670856b2bb96_720w.jpg)

**Comment by rustdesk** [comment]
> Software 向日葵(https://sunlogin.oray.com/download/) and teamviewer has the function. It seems involving a driver hacking.
> 

any idea how to hack?

**Comment by rustdesk** [comment]
toDesk: https://docs.todesk.com/zh-CN/privacyscreen

**Comment by Veiintc** [comment]
> toDesk: https://docs.todesk.com/zh-CN/privacyscreen

it seems  use "Magnification.dll"(MagSetWindowFilterList) to Windows 8.1 or later

**Comment by rustdesk** [comment]
> MagSetWindowFilterList

@fufesou

**Comment by fufesou** [comment]
> > toDesk: https://docs.todesk.com/zh-CN/privacyscreen
> 
> it seems use "Magnification.dll"(MagSetWindowFilterList) to Windows 8 or later

Thank you. I'll learn that function.

**Comment by zhangxaochen** [comment]
is there a 'Privacy Mode' button when using the PC(win11) client? I'm using the latest version v1.1.9, but I dont find a button/option to toggle on this...
![image](https://user-images.githubusercontent.com/3416677/200150310-f64fdcef-95c7-4d69-99d2-94f6a60e4433.png)

**Comment by rustdesk** [comment]
try out nightly build (Windows) on both side for privacy mode.

**Comment by Tchiimy** [comment]
> try out nightly build (Windows) on both side for privacy mode.

Hello, 

I'm a new user and I wanted to try the privacy mode so I installed the nightly build (windows) on both computers. But I don't see where can I can enable this option ? Is it actually available ?

**Comment by fufesou** [comment]
@Tchiimy 
![20221220231844](https://user-images.githubusercontent.com/13586388/208701520-fc3caee2-6de8-44c4-abbf-f10f5f4180b8.png)

**Comment by Tchiimy** [comment]
> @Tchiimy ![20221220231844](https://user-images.githubusercontent.com/13586388/208701520-fc3caee2-6de8-44c4-abbf-f10f5f4180b8.png)

Hmmm it seems that I don't have this option available (tested with 2 nighly version of rustdesk in 2 windows 10 computers, a dell and a asus). 

What version do you use ? Did you installed some drivers on your computer ?

**Comment by fufesou** [comment]
@Tchiimy I've tested Win11, the provacy mode is supported.

Privacy mode need [`Magnification`](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/magapi/entry-magapi-sdk) support. Maybe you have multiple screens. Or Magnification is not supported on you system (x86?). BTW, Magnification's api may be removed in the future. We'll consider another privacy mode implemetation.
https://github.com/rustdesk/rustdesk/blob/7f006102b5a018575cc3fc1a9c0e458dbb8a8993/src/server/connection.rs#L768
https://github.com/rustdesk/rustdesk/blob/7f006102b5a018575cc3fc1a9c0e458dbb8a8993/src/server/video_service.rs#L76
https://github.com/rustdesk/rustdesk/blob/7f006102b5a018575cc3fc1a9c0e458dbb8a8993/libs/scrap/src/dxgi/mag.rs#L271
https://github.com/rustdesk/rustdesk/blob/7f006102b5a018575cc3fc1a9c0e458dbb8a8993/libs/scrap/src/dxgi/mag.rs#L130

**Comment by Tchiimy** [comment]
> @Tchiimy I've tested Win11, the provacy mode is supported.

I don't know if it's linked but activating the license of W11 seems to have resolved the problem thanks !

**Comment by Zhang-0952** [comment]
所有终端都有这个隐私屏选项么？
Do all terminals have this privacy screen option?

**Comment by fufesou** [comment]
> Do all terminals have this privacy screen option?

@Zhang-0952  The remote side should be at lease Win10.

**Comment by sabxp** [comment]
> Some point about this for android (borrowed from srccpy, not sure if depends on adb) #3815

It's not depending on adb, it's java code from API setDisplayPowerMode():

`
import android.os.Build;
import java.lang.reflect.Method;
import java.lang.reflect.InvocationTargetException;
public class DisplayToggle {

    private static final Class<?> CLASS;
	static {
        	try {
            		CLASS = Class.forName("android.view.SurfaceControl");
		} catch (ClassNotFoundException e) {
        	throw new AssertionError(e);
     	 }
    }

    public static void main(String... args) throws Exception {
	System.out.print("Display mode: "+args[0]);
	Method method = CLASS.getMethod("setDisplayPowerMode", IBinder.class, int.class);
	try {
            method.invoke(null, getBuiltInDisplay(),Integer.parseInt(args[0]));
        } catch (InvocationTargetException | IllegalAccessException e) {
	    e.printStackTrace();
        }
    }

    private static Method getGetBuiltInDisplayMethod() throws NoSuchMethodException {
       Method getBuiltInDisplayMethod;
            // the method signature has changed in Android Q
            // <https://github.com/Genymobile/scrcpy/issues/586>
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
                getBuiltInDisplayMethod = CLASS.getMethod("getBuiltInDisplay", int.class);
            } else {
                getBuiltInDisplayMethod = CLASS.getMethod("getInternalDisplayToken");
            }
        return getBuiltInDisplayMethod;
    }

    public static IBinder getBuiltInDisplay() {
        try {
            Method method = getGetBuiltInDisplayMethod();
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
                // call getBuiltInDisplay(0)
                return (IBinder) method.invoke(null, 0);
            }
            // call getInternalDisplayToken()
            return (IBinder) method.invoke(null);
           } catch (InvocationTargetException | IllegalAccessException | NoSuchMethodException e) {
            e.printStackTrace();
            return null;
        }
    }
}
`

**Comment by Karbust** [comment]
Privacy Mode is not working when connecting from Windows 11 to Windows 10 when using the portable executable.

I haven't tested with the full installation as I don't have admin permissions.

Do I need to make any changes on the remote computer (Windows 10)?

**Comment by fufesou** [comment]
> Do I need to make any changes on the remote computer (Windows 10)?

No. It's where we don't do well enough.

**Comment by fufesou** [comment]
> from iPhone it works, that I already tried

Do you mean the Privacy mode works on iPhone -> Windows portable?
I'm confused. But it should not work before PR 4473.

**Comment by Karbust** [comment]
> > from iPhone it works, that I already tried
> 
> Do you mean the Privacy mode works on iPhone -> Windows portable? I'm confused. But it should not work before PR 4473.

On both the host and the client I'm running the nightly version: [rustdesk-1.2.0-x86_64.exe](https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64.exe)
https://github.com/rustdesk/rustdesk/releases/tag/nightly

The iPhone worked without any issues on the desktop running the nightly version.

Running the same version on the host and client computers, the client is running in Portable, the host is installed.

![image](https://github.com/rustdesk/rustdesk/assets/20361229/0d735869-44b5-4c14-92e2-05b55fdddcee)

**Comment by fufesou** [comment]
It is the controlled side that causes the failing.

The installed version has this file, while the portable version does not have this file.

![image](https://github.com/rustdesk/rustdesk/assets/13586388/7c91a97c-3325-4e43-9840-8b0538726791)

**Comment by Karbust** [comment]
> It is the controlled side that causes the failing.
> 
> The installed version has this file, while the portable version does not have this file.
> 
> ![image](https://user-images.githubusercontent.com/13586388/240633471-7c91a97c-3325-4e43-9840-8b0538726791.png)

But the Privacy Mode is working on Nightly, and I'm connecting to the host using the Portable. (both computers using Nightly, host is using the installed version).

Not entirely sure what your changes on #4473 are for, I don't know Rust, but so far it's working.

**Comment by cxtem** [comment]
do you have any solution that leaves the android screen black in privacy mode, do I need my clients android to dim while I do support ??

**Comment by cxtem** [comment]
tell me whatsapp +551195928027

**Comment by hooligans44** [comment]
> You mean, clicking on a button to hide the screen ? But still keep the audio? Sorry for bumping by the way

Its called curtain mode.

**Comment by bartquant** [comment]
@hooligans44 can you explain more? I have enabled privacy mode on the android and macos application but it keeps the screen on.

**Comment by chan-yuu** [comment]
> [@hooligans44](https://github.com/hooligans44) can you explain more? I have enabled privacy mode on the android and macos application but it keeps the screen on.你能详细解释一下吗？我已经在安卓和 macOS 应用上启用了隐私模式，但屏幕仍然亮着。

Linux too.

**Comment by lucaskent651-ai** [comment]
Can you explain a bit more?
I’ve enabled privacy mode on Android, macOS, and Linux, but the screen
still stays on. Am I missing something?
