### ISSUE TITLE
Windows 打开Rustdesk 无法接入网络

### ISSUE THREAD

**Issue by badboycxcc** [rustdesk/rustdesk#6509]
### Bug Description

一直提示未连接，请检查网络连接，但是电脑有网

### How to Reproduce

打开就是这样

### Expected Behavior

希望可以正常使用

### Operating system(s) on local side and remote side

Windows11

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

无

**Comment by rustdesk** [comment]
self-host please
