### ISSUE TITLE
Build failed arm64

### ISSUE THREAD

**Issue by kunduzb17** [rustdesk/rustdesk#651]
Describe the bug you encountered:

I am trying to build rustdesk but i am getting this error every time. I searched similar issues but their solutions didn't help. I would be really happy if you could help me to resolve this issue.

Compiling zstd v0.9.2+zstd.1.5.1 Compiling magnum-opus v0.4.0 (https://github.com/open-trade/magnum-opus#3c3d0b86) Compiling scrap v0.5.0 (/Users/kunduzb17/vcpkg/rustdesk/libs/scrap) error: failed to run custom build command for magnum-opus v0.4.0 ([https://github.com/open-trade/magnum-opus#3c3d0b86)`](https://github.com/open-trade/magnum-opus#3c3d0b86)%60)

Caused by:
process didn't exit successfully: /Users/kunduzb17/vcpkg/rustdesk/target/debug/build/magnum-opus-1c57be6f6a18c8fd/build-script-build (exit status: 101)
--- stdout
cargo:info=x64-osx
cargo:rustc-link-lib=static=opus
cargo:rustc-link-search=/Users/kunduzb17/vcpkg/installed/x64-osx/lib
cargo:include=/Users/kunduzb17/vcpkg/installed/x64-osx/include
rerun-if-changed=/Users/kunduzb17/.cargo/git/checkouts/magnum-opus-7580b098b18e2bc5/3c3d0b8/opus_ffi.h
rerun-if-changed=/Users/kunduzb17/vcpkg/installed/x64-osx/include

--- stderr
/Users/kunduzb17/.cargo/git/checkouts/magnum-opus-7580b098b18e2bc5/3c3d0b8/opus_ffi.h:1:10: fatal error: 'opus/opus_multistream.h' file not found
/Users/kunduzb17/.cargo/git/checkouts/magnum-opus-7580b098b18e2bc5/3c3d0b8/opus_ffi.h:1:10: fatal error: 'opus/opus_multistream.h' file not found, err: true
thread 'main' panicked at 'called Result::unwrap() on an Err value: ()', /Users/kunduzb17/.cargo/git/checkouts/magnum-opus-7580b098b18e2bc5/3c3d0b8/build.rs:66:18
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed`

What did you expect to happen instead?

I expected successful build

How did you install RustDesk?

I used exactly like this: https://rustdesk.com/docs/en/dev/build/osx/

RustDesk version and environment

macOS Monterey 12.4 arm64
cargo 1.61.0 (a028ae42f 2022-04-29)
rustup 1.24.3 (ce5817a94 2021-05-31)
rustc 1.61.0 (fe5b13d68 2022-05-18)

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/165

**Comment by harryhuang2015** [comment]
Platform: MacOS M1
Check  dir
cargo:rustc-link-search=/Users/kunduzb17/vcpkg/installed/x64-osx/lib
cargo:include=/Users/kunduzb17/vcpkg/installed/x64-osx/include

/Users/kunduzb17/vcpkg/installed/x64-osx  does not exist
you can find /Users/kunduzb17/vcpkg/installed/arm64-osx

I create a link dir
cd /Users/kunduzb17/vcpkg/installed/
ln -s x64-osx arm64-osx

run again:
cargo run

Success

**Comment by mahdiba97** [comment]
The error message indicates that the build process is unable to find the 'opus/opus_multistream.h' file. This file is part of the Opus library, which is a dependency for the magnum-opus crate you're trying to build.
Here are a few steps you can take to resolve this issue:
Check if the Opus library is installed: The Opus library needs to be installed on your system. You can usually do this through your system's package manager. For example, on Ubuntu, you would use the command sudo apt-get install libopus-dev.
