### ISSUE TITLE
Key Mismatch 

### ISSUE THREAD

**Issue by skadefro** [rustdesk/rustdesk#6522]
### Bug Description

All clients ( windows 10, linux ( nixos ), macos and ios ( 17.1.1 ) is reporting Key Mismatch.
No id/relay server defined

### How to Reproduce

Try and connect from any client to any other client

### Expected Behavior

Connection work and not getting "Key Mismatch" error 

### Operating system(s) on local side and remote side

any -> any

### RustDesk Version(s) on local side and remote side

ios 1.2.2 / linux 1.1.9 / windows 1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/4155937/15a664c2-c6d5-4d78-b820-b365593b0449)

**Comment by alfred-liu96** [comment]
same here

**Comment by rustdesk** [comment]
Upgrading server, will be ready soon.

**Comment by gigidarc** [comment]
Buonasera, sto avendo lo stesso problema, anche con l'applicazione da telefono iphone.

**Comment by skadefro** [comment]
No need to keep issue open, if its not a bug, but just a server upgrade.

**Comment by zx013** [comment]
I find two id_ed25519.pub. One is /root/id_ed25519.pub, another is /opt/rustdesk/id_ed25519.pub. Then I use /opt/rustdesk/id_ed25519.pub, the key error disappear.
