### ISSUE TITLE
Manjaro - Mouse randomly doesn't

### ISSUE THREAD

**Issue by fauconjona** [rustdesk/rustdesk#6538]
### Bug Description

Sometimes, when I come back to RustDesk, the mouse doesn't click where I want it to, such as on a window in the background or not at the correct position. I have to reconnect to make it work.

### How to Reproduce

I don't know exactly, it's when I come back on RustDesk, it happens after 10 minutes and sometimes after 30 secondes.

### Expected Behavior

Trigger the click where I clicked

### Operating system(s) on local side and remote side

Manjaro -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.4 -> 1.2.4

### Screenshots

I don't think screenshot is necessary

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by rustdesk** [comment]
please tell more about the Manjora, it is very necessary, just like this https://github.com/rustdesk/rustdesk/issues/6505#issuecomment-1824855705

**Comment by fauconjona** [comment]
It's a Manjaro KDE plasma on Kernel Linux6.1.62-1

**Comment by polyzium** [comment]
Kernel doesn't play a role here, it is definitely Plasma X11. Plasma Wayland doesn't have such issues to my knowledge
