### ISSUE TITLE
Mac to Windows file transfer is failing

### ISSUE THREAD

**Issue by carlca** [rustdesk/rustdesk#6539]
### Bug Description

I'm trying to transfer a file. It's 4.7MB in size and is a Java .JAR but with a .bwextension. It's a file that acts as a Java extension to the Music DAW Bitwig. I've made sure that Bitwig is not running on either machine.
The file in question is attached (I had to zip it in order to attach it)...
[midimix.zip](https://github.com/rustdesk/rustdesk/files/13479553/midimix.zip)

### How to Reproduce

Simply attempt to transfer the file.

### Expected Behavior

I expected the transfer to occur with no error indicated.

### Operating system(s) on local side and remote side

macOS 13.6 -> Win 10 Pro

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

![SCR-20231128-jhvk](https://github.com/rustdesk/rustdesk/assets/260612/1011a903-4bef-4af0-92dd-51c9387c314a)

**Comment by carlca** [comment]
I've just tried it with a PDF and it still says Error, although the error message changes to Finished after a couple of seconds. However, the file is nowhere to be found on the destination machine.

![SCR-20231128-kebd](https://github.com/rustdesk/rustdesk/assets/260612/14a0bc30-3a6e-4d12-a241-7ac93a1a57fd)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/6534

**Comment by carlca** [comment]
I did miss something! The actual destination folder, not the identically named folder, did have restricted permissions. I added myself with `Full Access` and it all works perfectly now. Thanks for your help with this 🙏🏽
