### ISSUE TITLE
It cannot work properly in Redroid and touch will fail

### ISSUE THREAD

**Issue by qq859952722** [rustdesk/rustdesk#6546]
### Bug Description

11-28 13:58:05.956   503   503 I KeyButtonView: Back button event: ACTION_UP
11-28 13:58:05.957   278   302 D AutofillManagerService: onBackKeyPressed()
11-28 13:58:06.058   114   921 D hwcomposer: VSYNC event status:0
11-28 13:58:08.116   114   921 D hwcomposer: VSYNC event status:1
11-28 13:58:08.219 24377 24661 D input service: delta:82
11-28 13:58:08.291   114   921 D hwcomposer: VSYNC event status:0
11-28 13:58:08.824 24377 24661 D input service: end gesture x:350 y:1086 time:611
11-28 13:58:08.826 24377 24661 E input service: endGesture error:java.lang.IllegalStateException: touchscreen supported device must report faketouch.
11-28 13:58:08.989 24377 24661 D input service: delta:84
11-28 13:58:09.159 24377 24661 D input service: end gesture x:376 y:1012 time:170
11-28 13:58:09.161 24377 24661 E input service: endGesture error:java.lang.IllegalStateException: touchscreen supported device must report faketouch.
11-28 13:58:10.096 24377 24661 D input service: delta:128
11-28 13:58:10.096 24377 24661 D input service: end gesture x:330 y:1266 time:1
11-28 13:58:10.097 24377 24661 E input service: endGesture error:java.lang.IllegalStateException: touchscreen supported device must report faketouch.
11-28 13:58:11.375 24377 24664 D input service: end gesture x:508 y:362 time:263
11-28 13:58:11.378 24377 24664 E input service: endGesture error:java.lang.IllegalStateException: touchscreen supported device must report faketouch.
11-28 13:58:12.495 24377 24664 D input service: end gesture x:378 y:772 time:537
11-28 13:58:12.497 24377 24664 E input service: endGesture error:java.lang.IllegalStateException: touchscreen supported device must report faketouch.
11-28 13:58:12.831 24377 24661 D input service: delta:122
11-28 13:58:13.409 24377 24661 D input service: end gesture x:482 y:520 time:580
11-28 13:58:13.412 24377 24661 E input service: endGesture error:java.lang.IllegalStateException: touchscreen supported device must report faketouch.
11-28 13:58:13.895 24377 24661 D input service: end gesture x:400 y:690 time:82
11-28 13:58:13.897 24377 24661 E input service: endGesture error:java.lang.IllegalStateException: touchscreen supported device must report faketouch.
11-28 13:58:14.199 24377 24664 D input service: end gesture x:382 y:704 time:4
11-28 13:58:14.201 24377 24664 E input service: endGesture error:java.lang.IllegalStateException: touchscreen supported device must report faketouch.
11-28 13:58:14.298 24377 24664 D input service: end gesture x:382 y:704 time:94
11-28 13:58:14.300 24377 24664 E input service: endGesture error:java.lang.IllegalStateException: touchscreen supported device must report faketouch.
11-28 13:58:14.568 24377 24661 D input service: end gesture x:366 y:770 time:5
11-28 13:58:14.569 24377 24661 E input service: endGesture error:java.lang.IllegalStateException: touchscreen supported device must report faketouch.
11-28 13:58:14.583 24377 24661 D input service: end gesture x:366 y:770 time:11
11-28 13:58:14.585 24377 24661 E input service: endGesture error:java.lang.IllegalStateException: touchscreen supported device must report faketouch.

### How to Reproduce

I test it  in android11 and Android13，it do not work all.

### Expected Behavior

hope it can be touch.

### Operating system(s) on local side and remote side

android > android

### RustDesk Version(s) on local side and remote side

1.2.3 > 1.2.3

### Screenshots

![{0BAB98AC-391E-4b8c-A173-0C75FFA8E9F0}](https://github.com/rustdesk/rustdesk/assets/20221585/0b365674-da80-4203-90b1-d342b5250f08)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893

**Comment by qq859952722** [comment]
ok，thks
