### ISSUE TITLE
error: failed to run custom build command for `scrap v0.5.0

### ISSUE THREAD

**Issue by HaleTom** [rustdesk/rustdesk#658]
**Describe the bug you encountered:**

Can't build due to scrap custom build command issue

**What did you expect to happen instead?**

Build succeeds

**Other info**

I'm running on Manjaro Linux.  I expect that Arch users and all Arch derivatives will have the same issue.

I raised the issue upstream, but perhaps it's more appropriate to raise it here?  Please close if not!

https://github.com/quadrupleslap/scrap/issues/43

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/19

**Comment by mway-pappenberger** [comment]
https://github.com/rustdesk/rustdesk/issues/19#issuecomment-1181553611

**Comment by QYH2MMT4EVER** [comment]
> **Describe the bug you encountered:**
> 
> Can't build due to scrap custom build command issue
> 
> **What did you expect to happen instead?**
> 
> Build succeeds
> 
> **Other info**
> 
> I'm running on Manjaro Linux. I expect that Arch users and all Arch derivatives will have the same issue.
> 
> I raised the issue upstream, but perhaps it's more appropriate to raise it here? Please close if not!
> 
> [quadrupleslap/scrap#43](https://github.com/quadrupleslap/scrap/issues/43)

hello bro! Have you fix up this problem? i am stuck in this problem for days ......could you plz give me a hand?
thx!
