### ISSUE TITLE
Re-generate the password after each connection

### ISSUE THREAD

**Issue by iosifnicolae2** [rustdesk/rustdesk#659]
In order to strengthen the security of RustDesk it would be awesome by default to re-generate the password after each connection.

Thank you!

**Comment by rustdesk** [comment]
> Hi, I think that Anydesk store his password remotely on their server so it's more secure because it's stored in a central place where users have no direct access. Don't you think it's a good solution?

**Comment by rustdesk** [comment]
> Is there a way to move/encrypt the TOML files with the ID and pass inside? I dont want users to be able to poke about in those files should they be so inclined. To be able to lock changing the password in the GUI would be nice also.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/1036
