### ISSUE TITLE
Alternative layout issues

### ISSUE THREAD

**Issue by qweered** [rustdesk/rustdesk#6596]
### Bug Description

I have https://github.com/Apsu/Canary installed on both sides using release build on Hyprland and latest windows 11. It worked flawlessly on some monthly old build for client, and now it is broken. Changing layout on remote side between canary and us do nothing, it still thinks I type in us

### How to Reproduce

Install layouts on both sides

### Expected Behavior

To work properly

### Operating system(s) on local side and remote side

Hyprland -> Windows 11

### RustDesk Version(s) on local side and remote side

latest commit -> 1.2.3

### Screenshots

No

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367
