### ISSUE TITLE
URL handler

### ISSUE THREAD

**Issue by bdrayersyno** [rustdesk/rustdesk#660]
Hi,

In Windows there is a way to add URL handlers to allow opening an other program using an URL (mailto:\<email\> or anydesk:\<id\>).

I have managed to do it for rustdesk (until it's integrated with it) but needed to create a small independant URL handler to do that.

The registry keys necessary for this are : 

<pre><code>
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\RustDesk]
@="URL:RustDesk Protocol"
"URL Protocol"=""

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\RustDesk\DefaultIcon]
@="RustDesk.exe,0"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\RustDesk\shell]

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\RustDesk\shell\open]

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\RustDesk\shell\open\command]
@="\"C:\\Program Files\\RustDesk\\urlhandler.exe\" \"%1\""
</code></pre>

The small URL handler in powershell is

<pre><code>
$url_handler = $args[0
$rustdesk_id = $url_handler -creplace '(?s)^.*\:',''
Start-Process -NoNewWindow -FilePath "${Env:ProgramFiles}\RustDesk\rustdesk.exe" -ArgumentList "--connect $rustdesk_id"
</code></pre>

I then convert the Powershell script to an exe file using ps2exe and put it on the same directory as rustdesk.exe

<pre><code>
Install-Module ps2exe
Invoke-ps2exe .\urlhandler.ps1 .\urlhandler.exe
</code></pre>

When all this is done you can finally connect to a machine using the URL rustdesk:\<id\> on a browser.

Would be great to have an intergrated URL handler into rustdesk.exe that convert the information received from the browser (rustdesk:\<id\>) to just the \<id\> (perhaps using a different command that connect (but that would do the same at the end) like -urlhandler %1 (which is rustdesk:\<id\>)

**Comment by dinger1986** [comment]
I have added this to a windows install script I have written https://github.com/dinger1986/rustdeskinstall/blob/main/WindowsAgentAIOInstall.ps1

**Comment by rustdesk** [comment]
> script

Thanks

**Comment by rustdesk** [comment]
added in master
