### ISSUE TITLE
Does not display file transfer history on remote computer

### ISSUE THREAD

**Issue by pzokid2** [rustdesk/rustdesk#6618]
### Bug Description

Local computer: Win 10 Pro 1909 64 bit.
Remote computer: Win 10 Pro 1909 64 bit.
rustdesk-1.2.3-x86-sciter.exe download from github.
The file transfer history window on the remote computer doesn't show anything every time I send and receive files.

### How to Reproduce

Use rustdesk 32 bit (no installation) to remote into a computer on the LAN with Direct IP, then use the file transfer feature.

### Expected Behavior

File transfer history is clearly displayed on the remote machine (like rustdesk 64 bit).

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

rustdesk-1.2.3-x86-sciter

### Screenshots

![RUSTDESK_LOCAL](https://github.com/rustdesk/rustdesk/assets/64058177/98aa3e3d-52e1-412b-9579-3b286f4f80dd)
![RUSTDESK_REMOTE](https://github.com/rustdesk/rustdesk/assets/64058177/64fc47e7-5ca8-44d2-ada7-3935bf6ba1dc)

**Comment by rustdesk** [comment]
Sorry, we won't maintain 32 sciter version actively.

**Comment by pzokid2** [comment]
That's sad, but thank you for your answer
