### ISSUE TITLE
connection does not establish when logged in addressbook

### ISSUE THREAD

**Issue by akarl10** [rustdesk/rustdesk#6621]
### Bug Description

when logged in with an addressbook account, connecting to any id does not work anymore most of the time

### How to Reproduce

connect to id without being logged in -> immediate connect
log into addressbook -> spinning, timeout

only forcing relay connection "fixes" it, but very large delay when connecting.

### Expected Behavior

no different behavior (I don't see a way how it should affect in the source)

### Operating system(s) on local side and remote side

windows or linux

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

.

### Additional Context

wireshark shows that a relay connection is established but immediatly closed if logged into addressbook

also it seems to ignore nat_type since it tries to do tcp hole punching on a asymmetric nat that it will not do when not logged in.
Looking at the code I don't see any place where nat_type is treated different when logged in or not..

**Comment by rustdesk** [comment]
#763
