### ISSUE TITLE
Side Mouse Buttons Not Working in Jetbrains IDEs

### ISSUE THREAD

**Issue by SimonBorg1012** [rustdesk/rustdesk#6644]
### Bug Description

Basically back/foward mouse side buttons don't work when you're inside a jetbrains IDE.(Though it does sometimes work for a few minutes, but eventually stops working).

If connect to a host and open a browser and start going to a few links and then press the back/forward mouse buttons, it works as it's suppose to where the browser goes to the previous/next url. But for jetbrains IDEs like Rider, Goland etc. 

Again might work sometimes and then stops working after a few seconds/minutes.

### How to Reproduce

Connect to a host > Open project in Rider > open a file > open a different File > Open a 3rd file > Press Back Side Mouse Button - **you should now be on the 2nd file** > press forward button  - **should now be in 3rd file.**

But instead you're stuck in the 3rd file most likely. Again this sometimes works, but stops working at some point.

### Expected Behavior

Connect to a host > Open project in Rider > open a file > open a different File > Open a 3rd file > Press Back Side Mouse Button > you should now be on the 2nd file > press forward button > should now be in 3rd file.

### Operating system(s) on local side and remote side

local 11 , remote 10

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

If needed I will add a recording, but it will be tricky to also record the mouse at the same time and sync the videos afterwards.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by Sciroccogti** [comment]
Is this implemented?

**Comment by AtomicStryker** [comment]
No, the problem is still present. You can use X-Mouse button control to mitigate: I made rules for the Rustdesk application to swap mousewheel-tilt-right and mousewheel-tilt-left (because Rustdesk inverts them). I also rebound mouse4 to trigger keyboard F10 instead, and configured F10 to be "back" in the remote Intellij. Sadly this means back wont work as expected in browsers and explorer, but its the smaller annoyance to me.

**Comment by adrianstas** [comment]
Just try to assign shortcuts in Settings -> Keymap

For Back it looks like:
<img width="364" alt="image" src="https://github.com/user-attachments/assets/1fe7dd1e-48a4-4978-901f-ca9e5967c282">

**Comment by PhilBarila** [comment]
When the problem manifests, Button 4 and 5 are not recognized in the "mouse shortcut" dialog.
