### ISSUE TITLE
The relay server can be used, but it shows as not ready

### ISSUE THREAD

**Issue by pumpkin-nbc** [rustdesk/rustdesk#6649]
### Bug Description

The relay server can be used, but it shows as not ready
I deployed using a domain name and Docker
My internal network connection Docker is displaying normally, while my external network connection is displaying abnormally

### How to Reproduce

Deploy using domain name and Docker

### Expected Behavior

The correct deployment environment

### Operating system(s) on local side and remote side

win11

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/58675642/e6b47eea-9603-4316-94c5-f7f47678a9ec)

**Comment by rustdesk** [comment]
#763
