### ISSUE TITLE
Hostname issues on RustDesk Android App

### ISSUE THREAD

**Issue by phoenixwarrior95** [rustdesk/rustdesk#665]
I have a Galaxy S22 Ultra running Android 12 and I am using AT&T as my cell phone provider.

Relay Server and ID server have been successfully setup on my Windows PC and Ive tested it with successful results (with an IP address format of 1.2.3.4). My public IP (lets call this 1.2.3.4) works for both WiFi and 4G/5G and WIFI connections, even with VPN on WiFI and VPN on 4G/5G. Now, once I use my hostname (lets call this blablah.com) that has the public IP of 1.2.3.4, thats where I run into problems.

On 4G/5G, I get an error of "Address Family Not Supported by protocol (os error 97). On WiFi (using blahblah.com), it connects. Even on 4G/5G connected to my home VPN via wireguard, blahblah.com makes a successful connection. 

Edit: In this screenshot, I also added the port 21116 at the end of blahblah.com and set the Direct Connection option to port 21116. I tried doing it without it too. I even tried hbbs.blahblah.com and hbbs.blablah.com:21116 and nothing works.
![Screenshot_20220528-125914](https://user-images.githubusercontent.com/43919854/171094027-2349257a-aedb-434c-81c2-1051a587a8ca.jpg)
![image0](https://user-images.githubusercontent.com/43919854/171094030-7d4607c9-a3b0-416f-bb51-4ba2d5f6b44d.jpg)

**Comment by rustdesk** [comment]
Thanks

**Comment by srbPierre** [comment]
Same problem in 4G/5G here in France.
Below IP configuration of my Android Samrtphone (but same error under iPhone)

![Screenshot_2022-06-08-10-47-28](https://user-images.githubusercontent.com/107108065/172576948-b3665063-4806-4d48-be09-91233459a230.png)
![Screenshot_2022-06-08-10-48-37](https://user-images.githubusercontent.com/107108065/172577016-f4747417-373b-4021-b4a4-85d087a129e4.png)

**Comment by Choukajohn** [comment]
Same problem for me on Android 12 Pixel 6 with 4G.
Works well connected to the wifi network.
The problem may be with the IPV6 address, it's the difference between the 4G connection and my home network.

**Comment by rustdesk** [comment]
> IPV6 address

Thanks

**Comment by rustdesk** [comment]
[app-release.zip](https://github.com/rustdesk/rustdesk/files/8885842/app-release.zip)
@srbPierre @phoenixwarrior95 could you please try out this?

**Comment by Choukajohn** [comment]
> [app-release.zip](https://github.com/rustdesk/rustdesk/files/8885842/app-release.zip)
> @srbPierre @phoenixwarrior95 could you please try out this?

New error for me with this release.
![Screenshot_20220612-153724.png](https://user-images.githubusercontent.com/12159975/173235962-a92b06f0-cfda-4166-bdc8-e80a1c48b2e3.png)

**Comment by rustdesk** [comment]
It means we can not resolve a valid ip v4 address from you domain name.

> error

**Comment by Choukajohn** [comment]
I don't use any domain, I'm using the rustdesk default server.
I got these errors when I try to connect with my 4g/5g connection with my Android phone (my device has an IPv6 internet address).
When I'm connected to my home network (IPv4 address) I have no issue.

**Comment by rustdesk** [comment]
> rustdesk default server

Thanks, then I have no clue again, :(

**Comment by rustdesk** [comment]
could you set custom id server address to google.com, then let me know what errors you will  see.

**Comment by Choukajohn** [comment]
> could you please set custom id server address to google.com? then let me know what errors you will  see.

There is no error with the id server set to google.com.

Maybe another clue : if I'm connected (with 4g/5g) to a VPN which has an IPv4 address over internet, it works.

**Comment by phoenixwarrior95** [comment]
So here is a huge update. After testing it, it actually works, but with a confusion.

So this is how my RustDesk Server looks like on my computer. The ID and Relay Server's ip addresses are set to local. All of my ports are open on my windows firewall and router. canyouseeme shows that they are open. The logic of this is that when you enter in your local IP address on the ID and Server (since the rustdesk client is on the SAME local machine as the server, it makes sense for me to set blahblah.com or my WAN IP from my Android phone and connect via 5G for it to work.
**
![image](https://user-images.githubusercontent.com/43919854/173239284-5faebfc8-6751-4b34-8c2e-36d8141399f2.png)
**

So as I configure my phone with the ID and relay of blahblah.com pointing to my server PC, it refuses to connect (infinitely connects and hangs). In the screenshot above, the client is set to a local IP and it should technically work. Once I set my client PC to blahblah.com and have my phone on my 5G connection to blahblah.com, it connects, which is fine, but it also should work if the client is on the same machine pointing to the server's IP. Ive tried 0.0.0.0, 127.0.0.01, and 192.168.68.79. Can there be a fix for this?

**Comment by rustdesk** [comment]
> confusion

https://github.com/rustdesk/rustdesk-server/issues/24#issuecomment-1135350475

**Comment by rustdesk** [comment]
asking in stackoverflow: https://stackoverflow.com/questions/72593907/failed-to-resolve-hostname-to-ipv4-address-with-rust-on-4g-5g

**Comment by Choukajohn** [comment]
> asking in stackoverflow: https://stackoverflow.com/questions/72593907/failed-to-resolve-hostname-to-ipv4-address-with-rust-on-4g-5g

I just tried with the DNS of my internet provider and it works, it seems to be an issue with Android private DNS option (I use cloudflare to avoid censorship).

**Comment by srbPierre** [comment]
Hi,

The release work fine on my Android in  4G/5G

Thank’s very mutch !

[TERRIER Pierre]
Découvrez le site Internet du SRB ici !<http://www.s-rb.fr/>
Vous y trouverez par exemple les numéros d’astreinte et les informations pratiques.


De : RustDesk ***@***.***>
Envoyé : dimanche 12 juin 2022 14:49
À : rustdesk/rustdesk ***@***.***>
Cc : Pierre Terrier ***@***.***>; Mention ***@***.***>
Objet : Re: [rustdesk/rustdesk] Hostname issues on RustDesk Android App (Issue #665)


app-release.zip<https://github.com/rustdesk/rustdesk/files/8885842/app-release.zip>
@srbPierre<https://github.com/srbPierre> @phoenixwarrior95<https://github.com/phoenixwarrior95> could you please try out this?

**Comment by isrbaral** [comment]
Just to clarify what is the solution here? I'm having what I think is the the same issue, on iOS trying to connect to a windows machine, the windows PC is with an ISP that has **_no_** IPv6 at all, my LTE/5G service is with T-mobile which I believe uses IPv6 by default and tunnels to IPv4.

**Comment by rustdesk** [comment]
Try out our nightly build please.

**Comment by sumanmandal1992** [comment]
Thanks, The nighty build works perfectly, and thanks for such a great application. I am using it over a year.
