### ISSUE TITLE
can not copy screenshot or picture between the local and  remote

### ISSUE THREAD

**Issue by xyfZzz** [rustdesk/rustdesk#6651]
### Bug Description

can not copy screenshot or picture between the local and  remote

### How to Reproduce

can not copy screenshot or picture between the local and  remote

### Expected Behavior

copy screenshot or picture between the local and  remote

### Operating system(s) on local side and remote side

Windows 10 -> Ubuntu 20.04

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

.

### Additional Context

version of rustdesk-server is 1.1.9

**Comment by rustdesk** [comment]
duplicate
