### ISSUE TITLE
Target of URI doesn't exist: 'package:flutter_hbb/generated_bridge.dart'

### ISSUE THREAD

**Issue by zhangping1109** [rustdesk/rustdesk#6663]
### Bug Description

flutter run.sh  file execution failed

### How to Reproduce

flutter> ~/.cargo/bin/flutter_rust_bridge_codegen --rust-input ../src/flutter_ffi.rs --dart-output 
./lib/generated_bridge.dart --c-output ./macos/Runner/bridge_generated.h
2023/12/12 16:19:33 [INFO] Running cargo expand in 'E:/rustapp/rustdesk/flutter/..'
2023/12/12 16:21:19 [WARN] command="cargo" "expand" "--theme=none" "--ugly" stdout= stderr=   Compiling scrap v0.5.0 (E:\rustapp\rustdesk\libs\scrap)
error: failed to run custom build command for `scrap v0.5.0 (E:\rustapp\rustdesk\libs\scrap)`
Caused by:
  process didn't exit successfully: `E:\rustapp\rustdesk\target\debug\build\scrap-3bbaaba4ac059a1a\build-script-build` (exit code: 101)

[ERROR] panicked at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\flutter_rust_bridge_codegen-1.82.4\src\commands.rs:316:17:
cargo expand returned empty output

### Expected Behavior

Missing file, unable to compile

### Operating system(s) on local side and remote side

windows 10

### RustDesk Version(s) on local side and remote side

master

### Screenshots

<img width="638" alt="1702370036417" src="https://github.com/rustdesk/rustdesk/assets/66348293/6a98d230-9652-4d7e-afe4-74c22677dd48">

**Comment by rustdesk** [comment]
#763
