### ISSUE TITLE
RustDesk breaks kiosk mode on Raspberry OS

### ISSUE THREAD

**Issue by ben221199** [rustdesk/rustdesk#6666]
### Bug Description

When enabling the RustDesk service on the Raspberry OS, when Chromium is autostarted in kiosk mode, the RustDesk service will do something that causes Chromium to leave kiosk mode after ~30 seconds. The used window system is Wayland.

### How to Reproduce

1. Install the Raspberry OS on a Raspberry and set all things up.

2. Setup kiosk mode:
```desktop
# Content of /etc/xdg/autostart/kiosk.desktop
[Desktop Entry]
Exec=sh /opt/kiosk.sh
Type=Application
```

```sh
# Content of /opt/kiosk.sh
chromium-browser --kiosk --start-maximized "https://rustdesk.com"
```

3. Install RustDesk.

I get RustDesk working on Raspberry OS with the following commands:

```sh
sudo su
dpkg -i <deb-file>
apt update
apt upgrade
apt --fix-broken install
reboot
```

### Expected Behavior

After step 1 and 2, kiosk mode works. After step 3, it RustDesk is installed and will cause Chromium to leave kiosk mode after ~30 seconds. The expected behavior is that Chromium doesn't leave kiosk mode.

### Operating system(s) on local side and remote side

Windows 11 -> Raspberry OS

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

This will appear after ~30 seconds:
![image](https://github.com/rustdesk/rustdesk/assets/12856904/f9b2e541-57a3-466f-bbcd-0b24b7062fdc)

### Additional Context

The service logs:
```log
Dec 12 13:19:56 raspberrypi systemd[1]: Started rustdesk.service - RustDesk.
Dec 12 13:19:57 raspberrypi rustdesk[1102]: Error: Can't open display: (null)
Dec 12 13:19:58 raspberrypi sudo[1248]:     root : PWD=/ ; USER=someraspberryuser ; ENV=XDG_RUNTIME_DIR=/run/user/1000 ; COMMAND=/usr/lib/rustdesk/rustdesk --server
Dec 12 13:19:58 raspberrypi sudo[1248]: pam_unix(sudo:session): session opened for user someraspberryuser(uid=1000) by (uid=0)
Dec 12 13:19:58 raspberrypi rustdesk[1249]: Error: Can't open display: (null)
```

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
