### ISSUE TITLE
Clipboard not working with longer text (VM)

### ISSUE THREAD

**Issue by fmigneault** [rustdesk/rustdesk#6674]
### Bug Description

Copying a value longer than `1234567890123456789` from the local instance and trying to paste it on the remotely connected VM side does not paste the updated content (either nothing pasted, or the previous copy of shorter text is pasted). Doing the inverse operation (copy on remote, paste locally) does not work regardless of content length.

It seems the clipboard fails to store the text for transfer.

### How to Reproduce

Copy `1234567890123456789` from local and paste on remote anywhere. This should work.
Copy `1234567890123456789xxx` from local and paste on remote. Does not work or pastes the previous `1234567890123456789`.

### Expected Behavior

Copied text should be pasted regardless of length (or at least up to a reasonably large size) to allow transfer file configs and such.

### Operating system(s) on local side and remote side

Windows 11 local, Ubuntu 22.04.6 LTS remote

### RustDesk Version(s) on local side and remote side

nightly "1.2.4" on 2023-12-13

### Screenshots

see "how to reproduce"

**Comment by sahilyeole** [comment]
Hello, Thanks for reporting but I could not reproduce it on:
mac -> ubuntu wayland & x11
windows -> mac
[I ran out of space for VMs so currently can't test windows -> ubuntu but if it's needed I can free up space soon 😅]

- Here's mac -> ubuntu wayland; recently introduced clipboard feature:
#6586

https://github.com/rustdesk/rustdesk/assets/73148455/d02519db-5608-4012-b5e0-2e158ff5e042

**Comment by fmigneault** [comment]
Hi @sahilyeole 
Thanks for looking into this.

It seems the result is very inconsistent.
I made a video to demonstrate various combinations of right-click copy/paste vs CTRL-C/CTRL-V and to/from local/remote.
I recorded the audio so we can hear when I do the CTRL instead of right-click. 
Sometimes something is pasted, but it seems to be an older clipboard text in some cases.

https://github.com/rustdesk/rustdesk/assets/19194484/ee1423da-0ba6-476f-bed4-3bfce352202a

**Comment by rustdesk** [comment]
expected

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4357

**Comment by rustdesk** [comment]
@fmigneault please confirm if it is Wayland on remote side.

**Comment by fmigneault** [comment]
@rustdesk 
Wayland is disabled. Using X11 only.
