### ISSUE TITLE
Snap-Window doesn't work on right side

### ISSUE THREAD

**Issue by albotroz** [rustdesk/rustdesk#6678]
### Bug Description

I recently updated from 1.1.9 to the new Rustdesk version 1.2.3 and noticed that the snap-function of windows on the right side no longer works. However, it works on the left side. 

### How to Reproduce

Try to snap with mouse a window on right and left side. Of left side it works and snap.

### Expected Behavior

Should snap to the right side as it used to do on the left side.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

![snap](https://github.com/rustdesk/rustdesk/assets/67508404/0687a271-2c40-4182-9a68-23a094e5eefe)

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
close as fix merged.

**Comment by rustdesk** [comment]
@albotroz please try out tomorrow's nightly build.
