### ISSUE TITLE
Abnormal display when the remote PC has no monitor turned on

### ISSUE THREAD

**Issue by cubicYYY** [rustdesk/rustdesk#6682]
### Bug Description

If there's no working monitors for the remote, some strange behaviors/glitches occured in rendering some windows.  
The behavior: https://github.com/rustdesk/rustdesk/discussions/6551
(Yes, the same, but find the most related reason and it is now reproducible)

### How to Reproduce

+ Turn off all the connected monitors, but keep the HDMI/DP cable connected (or just close the laptop to disable the screen)
+ Remote control it 

### Expected Behavior

Display normally, like where a monitor connected & turned-on

### Operating system(s) on local side and remote side

Windows 11 23H2 (both)

### RustDesk Version(s) on local side and remote side

1.2.3->1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/93425234/fb62dd9e-65b0-4436-b19d-4c4c8419bb01)

### Additional Context

Laptop: ASUS Redolbook14 with AMD CPU, integrated GPU Vega7, Windows11 23H2
Desktop: ASUS Motherboard + AMD 5800X + NVIDIA RTX 3080, Windows11 23H2

**Comment by yangluoning** [comment]
![image](https://github.com/rustdesk/rustdesk/assets/7410894/22a37055-3bec-4928-99b5-0f5b82f4a5d1)
有同样的问题，无显示器白屏，望解决

**Comment by wbright** [comment]
+1  same issue

**Comment by wbright** [comment]
update: 
 when i  plugin a mouse to my remote host，it works  well  in most scenarios @cubicYYY

**Comment by bigretromike** [comment]
This issue is common for vnc and sometimes other remote access software. The hardware workaround is to use dumb monitor plugs you can buy - fake monitor plug, that will add fake monitor via hdmi/display port plug. In past I wasn't able to overcome thing becuase its windows and gpu related issue - some gpus wont even post pc on restart/power on if you dont have monitor turn on. But I would gladly see this resolved here.

**Comment by wbright** [comment]
> This issue is common for vnc and sometimes other remote access software. The hardware workaround is to use dumb monitor plugs you can buy - fake monitor plug, that will add fake monitor via hdmi/display port plug. In past I wasn't able to overcome thing becuase its windows and gpu related issue - some gpus wont even post pc on restart/power on if you dont have monitor turn on. But I would gladly see this resolved here.

it works after installing a virtual monitor driver

**Comment by bigretromike** [comment]
> > This issue is common for vnc and sometimes other remote access software. The hardware workaround is to use dumb monitor plugs you can buy - fake monitor plug, that will add fake monitor via hdmi/display port plug. In past I wasn't able to overcome thing becuase its windows and gpu related issue - some gpus wont even post pc on restart/power on if you dont have monitor turn on. But I would gladly see this resolved here.
> 
> it works after installing a virtual monitor driver

Could you provide name or link for that driver?

**Comment by cubicYYY** [comment]
> > This issue is common for vnc and sometimes other remote access software. The hardware workaround is to use dumb monitor plugs you can buy - fake monitor plug, that will add fake monitor via hdmi/display port plug. In past I wasn't able to overcome thing becuase its windows and gpu related issue - some gpus wont even post pc on restart/power on if you dont have monitor turn on. But I would gladly see this resolved here.
> 
> it works after installing a virtual monitor driver

I would like to ask which virtual driver you installed

**Comment by T3kla** [comment]
> > This issue is common for vnc and sometimes other remote access software. The hardware workaround is to use dumb monitor plugs you can buy - fake monitor plug, that will add fake monitor via hdmi/display port plug. In past I wasn't able to overcome thing becuase its windows and gpu related issue - some gpus wont even post pc on restart/power on if you dont have monitor turn on. But I would gladly see this resolved here.
> 
> it works after installing a virtual monitor driver

Please provide the name of said driver, I have tried many and none work.

**Comment by bigretromike** [comment]
@wbright  could you share driver name with us ?

**Comment by wbright** [comment]
RustDeskIddDriver_x64
@bigretromike @T3kla @cubicYYY

**Comment by T3kla** [comment]
I have been using [these](https://github.com/itsmikethetech/Virtual-Display-Driver/releases), which [this video](https://www.youtube.com/watch?v=byfBWDnToYk) explains how to use.

**Comment by rustdesk** [comment]
close this since we have virtual display support now in 1.2.4.

https://twitter.com/rustdesk/status/1781263566504653052?t=bnpFjiNHcvgxAvzKTkuciw&s=19

**Comment by KaMyKaSii** [comment]
> close this since we have virtual display support now in 1.2.4.
> 
> https://twitter.com/rustdesk/status/1781263566504653052?t=bnpFjiNHcvgxAvzKTkuciw&s=19

Just for Windows? I have the same problem controlling a Linux Mint machine, the image freezes if there is no monitor connected to the remote computer

**Comment by Gryzore** [comment]
I have maybe a useful hint to this problem. I also had the problem accessing an Kubuntu Linux system (22.04 and 24.04) while my monitor was powered off. Today I have discovered that using an HDMI  (instead of a DisplayPort) cable solved my problem. HDMI seems to passthrough somehow the physical connection between the monitor and the computer system whilst DisplayPort does not.

**Comment by themightyoarfish** [comment]
Sad that this does not work on linux. No workaround other than to plug something into the computer?

**Comment by bigretromike** [comment]
@themightyoarfish did you try adding virtual monitor on linux example: https://www.reddit.com/r/Immersed/comments/1bjqqbb/how_can_i_add_another_screen_im_currently_working/ ?

**Comment by rvsh2** [comment]
Check this:
https://github.com/rvsh2/rustdesk-no-monitor-fix
