### ISSUE TITLE
Order of monitors in toolbar is totally wrong

### ISSUE THREAD

**Issue by rxsto** [rustdesk/rustdesk#6683]
### Bug Description

When connecting to a multi-monitor setup the buttons for switching to different monitors are not in the correct order. I was unable to find out by what they are exactly ordered, but they're definitely not ordered by the configured display settings.

### How to Reproduce

Connect to a multi-monitor setup and identify the monitors by switching between them using the monitor buttons.

### Expected Behavior

The monitors should be ordered by left to right (or top-left to bottom-right, depending on the setup). This should potentially be configurable.

### Operating system(s) on local side and remote side

MacOS 14.2 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

<img width="603" alt="actual" src="https://github.com/rustdesk/rustdesk/assets/30745852/c2dfcf6e-84ab-47bf-ad64-4fc7f8cb38e2">
This is how the monitors are mapped.

How they should actually be mapped:
1 -> the vertical one at the left
2 -> the horizontal one in the center
3 -> the horizontal one at the right

### Additional Context

This complication could additionally be simplified by streaming a low-res preview of each of those monitors.

**Comment by fragtion** [comment]
Why was this closed & marked invalid?

**Comment by rxsto** [comment]
That's actually a great question. My bug report seems pretty reasonable, since there's no way of knowing which monitor would be which when knowing the external setup, which ends up being super confusing. If there's some clever reason for this situation, then I'd love to hear an explanation, so I can figure out how to properly use it. But when there's a sort of expectation that the first monitor in the list would be the one on the left, then this behavior makes working on remote setups quite a bit more confusing.
