### ISSUE TITLE
docker flutter_web_desk v1.0.0  cannot be used

### ISSUE THREAD

**Issue by xuewenhub** [rustdesk/rustdesk#6684]
### Bug Description

Deploy the dockerhub image to the personal server, use the Chrome browser (version: 120.0.6099.109) to open http://publicIp:5000/#/, and there will be a blue circle on the page. Using F12, the console prompts: index.js:1 WebSocket connection to 'ws://rs-us.rustdesk.com:21118/' failed:

### How to Reproduce

docker pull keyurbhole/flutter_web_desk
docker run -p 5000:5000 keyurbhole/flutter_web_desk

### Expected Behavior

Can be used normally

### Operating system(s) on local side and remote side

macm2  -> centos8

### RustDesk Version(s) on local side and remote side

 docker flutter_web_desk v1.0.0->1.18

### Screenshots

no

### Additional Context

no

**Comment by rustdesk** [comment]
#763
