### ISSUE TITLE
individual windows swithching bug

### ISSUE THREAD

**Issue by k-k-s-s** [rustdesk/rustdesk#6686]
### Bug Description

In dual-screen mode, when switching between two screens, the mouse will click randomly on the other screen.

### How to Reproduce

Open different software on different screens, one of which can preferably be a browser that scrolls web pages, or other software

### Expected Behavior

When switching between screens by clicking, the mouse on the other screen will click or scroll randomly

It's not completely random, it's concentrated in the red area in the picture below
![image](https://github.com/rustdesk/rustdesk/assets/7893382/907d1128-c0a9-45d6-b3f0-e60f339559c7)

### Operating system(s) on local side and remote side

osx ---> windows 10

### RustDesk Version(s) on local side and remote side

1.24--->1.24

### Screenshots

https://github.com/rustdesk/rustdesk/assets/7893382/6cf7ba1a-0507-40c4-86b6-6c27fd6c63ef

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
close as fix merged, please try out tommorrow's nightly build.
