### ISSUE TITLE
Debian12 Unable to remotely by default X11

### ISSUE THREAD

**Issue by gonboy** [rustdesk/rustdesk#6687]
### Bug Description

set `WaylandEnable=false`, it can remote. but rdp couldn't connect.
if not set `#WaylandEnable=false`, rdp connect ok. but remote is failed.

```bash
# 修改(change)
$sudo vim /etc/gdm3/daemon.conf

WaylandEnable=false
# 重启服务(reset server)
$sudo systemctl restart gdm.service
$sudo systemctl restart rustdesk.service
```

### How to Reproduce

None

### Expected Behavior

None

### Operating system(s) on local side and remote side

debian12

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

无

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3565
