### ISSUE TITLE
The tray icon repeatedly appeared.

### ISSUE THREAD

**Issue by YamatoRyou** [rustdesk/rustdesk#6692]
### Bug Description

As a controlled side, every time the remote desktop connection is accepted, a pallet will add a new icon. Even if the connection is over, the tray icon will not disappear.

### How to Reproduce

1. Install RustDesk to the system;
2. Start the service so that RustDesk is resident in the system;
3. The control end and the controlled terminal must be connected to the self -hosted server;
4. Connect to the remote desktop on the controlled end, and then end the connection (the control terminal can be another computer or mobile phone, the controlled terminal must be Windows);
5. Repeat steps 4 several times.

### Expected Behavior

Regardless of whether the controlled system exists or not `RustDesk.exe --tray`, the number of tray icons should always be controlled by users.

### Operating system(s) on local side and remote side

Any -> Windows

### RustDesk Version(s) on local side and remote side

1.2.3 (Any) -> 1.2.3 (x64 Windows, Flutter)

### Screenshots

![{BB702385-1E89-51D1-FBED-73BF6F17A946}](https://github.com/rustdesk/rustdesk/assets/48104960/8c7734f4-536a-473d-abb7-33411ef105bd)

**Comment by 21pages** [comment]
There is a problem with checking running status of tray on your computer. Please install https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.2.4-x86_64-repeated-tray.exe and follow the reproduce steps, and then delete the self-host ip information in `C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT.log` and upload it.

**Comment by YamatoRyou** [comment]
> There is a problem with checking running status of tray on your computer. Please install https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.2.4-x86_64-repeated-tray.exe and follow your reproduce steps, and then delete the self-host ip information in `C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT.log` and upload it.

[{FA1DFCFB-D9A2-49BB-E3E5-9BB5625BA1AC}.zip](https://github.com/rustdesk/rustdesk/files/13694625/FA1DFCFB-D9A2-49BB-E3E5-9BB5625BA1AC.zip)
**Unzip password: `{EED5C9A6-D42A-F5DD-3C06-68B468B212EA}`**

**I may have found the reason: I used an NTFS symlink when installing (the installation directory was actually in `D:\Program Files`, but the symlink made it to `C:\Program Files`). This was done to ease the include Third-party software including RustDesk occupies the system partition.**

**Comment by rustdesk** [comment]
Sorry, your case is too specific, we have no plan it for now, except we are receiving more cases in the future, we will keep watch

**Comment by Endracion** [comment]
Just want to say, I'm getting this too, but I have a subst created drive that's a folder on another drive - is that what's causing this? Because of the install location?

**Comment by YamatoRyou** [comment]
> Sorry, your case is too specific, we have no plan to fix it (no beautiful solution yet) with the risk to raise more bug for the time being, except we are receiving more cases in the future, we will keep watch

I want to update the latest situation.
After updating to 1.4.0 (x64 Windows), this problem has become worse. Without changing the above installation method, now every time the main window is opened, there will be an additional tray icon (and the corresponding process of the icon).

![Image](https://github.com/user-attachments/assets/572c0d12-b916-4d31-8eae-b00a65430e6c)
![Image](https://github.com/user-attachments/assets/325b33cb-fcc8-42fa-99b3-77d7147e7a1f)
