### ISSUE TITLE
rustdesk unsupported display server type wayland，x11 is expected

### ISSUE THREAD

**Issue by willzhang** [rustdesk/rustdesk#670]
**Describe the bug you encountered:**
windows 10 connect ubuntu 22.04 desktop  with error, what i should do for ubuntu to use x11?

![](https://user-images.githubusercontent.com/24804667/121676948-d71a1900-cae7-11eb-9db0-532f81c1df4c.png)
...

**What did you expect to happen instead?**
connect success
...

**How did you install `RustDesk`?**

dep for ubuntu
---

**RustDesk version and environment**
1.1.9

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/220

**Comment by congzhangzh** [comment]
BTW, the x session detected depends on login ctrl which does not always work like run in the docker container!

works:
```bash
 Xvfb  :7&
 export DISPLAY=:7
 dbus-launch gnome-session&
 rustdesk Unsupported 
```

failed if run in docker and say the same error, that X server unsupported

**Comment by congzhangzh** [comment]
loginctl depend on init=0 process?

**Comment by rustdesk** [comment]
Better solution is welcome.

**Comment by rustdesk** [comment]
> loginctl depend on init=0 process?

I do not know either.

**Comment by frank-dspeed** [comment]
On Ubuntu and that works also for all other snapd enabled distros i have something that we can experiment with i guess it will work and i guess i will do a writeup about that as i plan to depend on that code base

## How without the why 
you need to do ```apt-get install xwayland``` if your on a current ubuntu release if your on a older xwayland gets shipped with x11 

## The Why
https://wayland.freedesktop.org/docs/html/ch05.html

**Comment by SVG62** [comment]
I’m not going to reinstall the system for the sake of rustdesk, it’s easier to stop using rastdesk and stay on guacamole

**Comment by dolphinoracle** [comment]
it would be nice for the x11 detection to not require systemd.   we can help with a sysVinit script, but just having the init script doesn't allow the detection to work properly.

**Comment by frank-dspeed** [comment]
i guess we should implement a command line switch anyway to connect rustdesk to diffrent x11 and mir sockets then we could better integrate that and also offer remote virtual desktops with it.


I for my Self at present trying the idea of so called confined desktops that means we run 1 main MirServer that holds all connected displays then we create new so called frames sub sockets that attach partial to the existing displays this way i can expose sockets for a part of the display or a single window.

This all is part of ChromiumOS we are sitting on the same problem that our remote desktop stack needs to be able to connect to diffrent sockets we solved that via command line switches. We got a own Window System that has adapters to x11 and Mir

**Comment by rustdesk** [comment]
> implement a command line switch

Good

**Comment by ceewanna** [comment]
I happened to make stupid changes to X11 conf.d and reboot. Somehow the pc can reboot (I know because it's still sending files out as expected) but I can't access via rustdesk and get the same screen. The pc is on a remote location. I wonder if there is anyway to access via rustdesk into terminal screen instead of X11. Or there is any other things I should do.

**Comment by ristein** [comment]
I'm trying to connect to Ubuntu 22 (RustDesk 1.1.9) from Android (Rustdesk 1.1.9 or 1.1.10-1 from F-Droid).
It says: "Login Error, Unsupportedt displa server type wayland, x11 expected"
xwayland already installed on ubuntu.
What can I do?

**Comment by Shadowphoenix** [comment]
> I'm trying to connect to Ubuntu 22 (RustDesk 1.1.9) from Android (Rustdesk 1.1.9 or 1.1.10-1 from F-Droid). It says: "Login Error, Unsupportedt displa server type wayland, x11 expected" xwayland already installed on ubuntu. What can I do?

Similar Issue on Arch - i am currently trying out Wayland to see if i can squeeze out a bit more performance from my machine

Turns out after logging into Wayland from SDDM gives me this error if i then connect from another machine, 
If i launch into an X11-Session and try to remote into it, it works fine...
its kind of inconvenient because it is essentially locking out all Distros that embrace Wayland over X11, which more and more of them will do over time. This needs a fix of some sort - either that or make it "just" a warning that clarifies wayland is unsupported so its my problem if it works or not.

**Comment by frank-dspeed** [comment]
@draftman9 heheheh the x11 implementation xwayland does not expose the wayland desktops via x11 it is doing something total diffrent it allows you to create additional wayland desktops that are x11 driven!!

So you can not expose wayland via x11 but you can run x11 on wayland so to use x11 with rustdesk you need to run something that you want to remote controll in the same xwayland session 

wayland unlike x11 is able to run nested and isolated that the reason why it exists its not a flat structure it is a tree :)

**Comment by kalkanijayesh** [comment]
1 Login to Ubuntu via SSH or open terminal/console
2 Edit the /etc/gdm3/custom.conf file
`sudo nano /etc/gdm3/custom.conf`
Find and uncomment the 
`#WaylandEnable=false by removing “#” in the front`

Ctrl + X, Y, Enter key to Save and Exit

3 Restart gdm3

sudo service gdm3 restart

**The above steps are working fine for me in Ubuntu 22.04.**

**Comment by Chief36** [comment]
I use a systemd-free OS and I'm unable to use my desktop from another device  because loginctl does not work in systemd-free OS. An alternate detection method that is init agnostic could make things better. I'm using MX Linux 21 (Based on Debian 11 Bullseye) with SysV init.

**Comment by sheerun** [comment]
Honestly rustdeck is the only software I care about to support wayland in order to switch to it :) I hope it will work out of the box one day on major distributions like Ubuntu and Fedora

**Comment by rustdesk** [comment]
Try out nightly build please, Wayland support already added.

**Comment by Eliances** [comment]
> 1 Login to Ubuntu via SSH or open terminal/console 2 Edit the /etc/gdm3/custom.conf file `sudo nano /etc/gdm3/custom.conf` Find and uncomment the `#WaylandEnable=false by removing “#” in the front`
> 
> Ctrl + X, Y, Enter key to Save and Exit
> 
> 3 Restart gdm3
> 
> sudo service gdm3 restart
> 
> **The above steps are working fine for me in Ubuntu 22.04.**

Worked totally fine with these instructions, thankss a lot

**Comment by macccorehenni** [comment]
> > 1 Login to Ubuntu via SSH or open terminal/console 2 Edit the /etc/gdm3/custom.conf file `sudo nano /etc/gdm3/custom.conf` Find and uncomment the `#WaylandEnable=false by removing “#” in the front`
> 
> > 
> 
> > Ctrl + X, Y, Enter key to Save and Exit
> 
> > 
> 
> > 3 Restart gdm3
> 
> > 
> 
> > sudo service gdm3 restart
> 
> > 
> 
> > **The above steps are working fine for me in Ubuntu 22.04.**
> 
> 
> 
> Worked totally fine with these instructions, thankss a lot

I want to point out that on my copy of Debian, this file was daemon.conf.

**Comment by Frank1016** [comment]
> 1 Login to Ubuntu via SSH or open terminal/console 2 Edit the /etc/gdm3/custom.conf file `sudo nano /etc/gdm3/custom.conf` Find and uncomment the `#WaylandEnable=false by removing “#” in the front`
> 
> Ctrl + X, Y, Enter key to Save and Exit
> 
> 3 Restart gdm3
> 
> sudo service gdm3 restart
> 
> **The above steps are working fine for me in Ubuntu 22.04.**

I'm on Linux Lite 6.6 in Virtual Machine Manager on Synology NAS, after installing gdm3 and change setting like this, the system won't even start, so now I have to re-install Linux.

**Comment by SKJoy** [comment]
> 1 Login to Ubuntu via SSH or open terminal/console 2 Edit the /etc/gdm3/custom.conf file `sudo nano /etc/gdm3/custom.conf` Find and uncomment the `#WaylandEnable=false by removing “#” in the front`
> 
> Ctrl + X, Y, Enter key to Save and Exit
> 
> 3 Restart gdm3
> 
> sudo service gdm3 restart
> 
> **The above steps are working fine for me in Ubuntu 22.04.**

Did not work for me :( Using `Linux Ubuntu Rolling` with `GNome` inside `Docker` container.

**Comment by macccorehenni** [comment]
Does this have to do with a XWayland bug?

Cameron Reape

**Comment by SKJoy** [comment]
> Does this have to do with a XWayland bug? Cameron Reape
> […](#)
> On Apr 8, 2024 at 17:42 -0700, Broken Arrow ***@***.***>, wrote: > 1 Login to Ubuntu via SSH or open terminal/console 2 Edit the /etc/gdm3/custom.conf file sudo nano /etc/gdm3/custom.conf Find and uncomment the #WaylandEnable=false by removing “#” in the front > Ctrl + X, Y, Enter key to Save and Exit > 3 Restart gdm3 > sudo service gdm3 restart > The above steps are working fine for me in Ubuntu 22.04. Did not work for me :( Using Linux Ubuntu Rolling with GNome inside Docker container. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

I actually uncommented that line... still not working :(

```
[daemon]
# Uncomment the line below to force the login screen to use Xorg
WaylandEnable=false
```

**Comment by emoxam** [comment]
Got ubuntu 23.10
1. did
nano /etc/gdm/custom.conf
uncomment #WaylandEnable=false
got error no display
2. did like here https://github.com/rustdesk/rustdesk/discussions/1615#discussioncomment-5355588 - installed xserver-xorg-video-dummy and created /usr/share/X11/xorg.conf.d/xorg.conf 
3. got error "Unsupported display server type "", x11 or wayland expected"
what to try ? Night build ?
