### ISSUE TITLE
Unable to control laptop if lid is closed

### ISSUE THREAD

**Issue by Nitrowolf** [rustdesk/rustdesk#6703]
### Bug Description

Rustdesk works fine if the lid on the laptop is open.  If the lid is closed, I can connect but unable to interact with the laptop until the lid is open.

Version 1.2.3 Build 2023-10-13 10:57

Machine is Samsung Galaxy Book3 360 with Intel Xe graphics.  No dual GPU setup

### How to Reproduce

Install Rustdesk on laptop.  

Connect to laptop with lid closed, or close lid while in an active session.

Unable to interact with display.  Open lid, and everything you've tried to do pops up instantly as display updates.

### Expected Behavior

Close lid, continue to interact with laptop properly.

### Operating system(s) on local side and remote side

Windows 11 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

Nothing to screenshot, since you can't interact with the environment.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4296
