### ISSUE TITLE
 Problems that occur during compilation

### ISSUE THREAD

**Issue by 287809671** [rustdesk/rustdesk#6704]
### Bug Description

![微信图片_20231218142257](https://github.com/rustdesk/rustdesk/assets/53225361/e6b8bb8c-ac12-4d3f-abb1-97e0ab415a70)

Problems that occur during compilation
https://github.com/rustdesk/rustdesk

### How to Reproduce

Problems that occur during compilation

### Expected Behavior

Problems that occur during compilation

### Operating system(s) on local side and remote side

windows 10

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

Problems that occur during compilation

### Additional Context

Problems that occur during compilation

**Comment by rustdesk** [comment]
#763
