### ISSUE TITLE
privacy mode with multiple monitors

### ISSUE THREAD

**Issue by Double-Click-ERP** [rustdesk/rustdesk#6707]
### Bug Description

When connecting to a computer with multiple monitors and activate privacy mode
i only can use first monitor , and only the first monitor is showing privacy screen

### How to Reproduce

1. connect to pc with multiple monitors (Extend)
2. activate privacy mode

### Expected Behavior

privacy screen will show on both monitors , and i can use both monitors 

### Operating system(s) on local side and remote side

Windows 10 > Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3 > 1.2.3

### Screenshots

![18-12-2023 11-45-40 AM](https://github.com/rustdesk/rustdesk/assets/121224467/f00901cc-a58d-40b6-9824-cee373591fe7)

![18-12-2023 12-33-03 PM](https://github.com/rustdesk/rustdesk/assets/121224467/6ce4e2a5-23e6-4fe8-91ee-1334a3afb9cc)

**Comment by rustdesk** [comment]
Current solution supports one monitor only.
