### ISSUE TITLE
The conversation recording function has disappeared, and the automatic recording of visiting conversations is invalid

### ISSUE THREAD

**Issue by 0xtlu** [rustdesk/rustdesk#6715]
### Bug Description

The conversation recording function has disappeared, and the automatic recording of visiting conversations is invalid
In my testing, I found that when running the Rustdesk client (1.2.3) in Windows 10, the control side cannot see the function item for session recording; At the same time, even if automatic recording of visiting sessions is enabled in the controlled end, video files cannot be generated, and even the default path cannot generate a directory. I don't understand the reason, I even changed the system running the server to Centos 7.9 and Windows 10, using the server version. 1.1.8 (Linux) and 1.1.9 ()

### How to Reproduce

The conversation recording function has disappeared, and the automatic recording of visiting conversations is invalid
In my testing, I found that when running the Rustdesk client (1.2.3) in Windows 10, the control side cannot see the function item for session recording; At the same time, even if automatic recording of visiting sessions is enabled in the controlled end, video files cannot be generated, and even the default path cannot generate a directory. I don't understand the reason, I even changed the system running the server to Centos 7.9 and Windows 10, using the server version. 1.1.8 (Linux) and 1.1.9 ()

### Expected Behavior

The conversation recording function has disappeared, and the automatic recording of visiting conversations is invalid
In my testing, I found that when running the Rustdesk client (1.2.3) in Windows 10, the control side cannot see the function item for session recording; At the same time, even if automatic recording of visiting sessions is enabled in the controlled end, video files cannot be generated, and even the default path cannot generate a directory. I don't understand the reason, I even changed the system running the server to Centos 7.9 and Windows 10, using the server version. 1.1.8 (Linux) and 1.1.9 ()

### Operating system(s) on local side and remote side

Windows 10 ->Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

<img width="853" alt="tumei_2023-12-19_16-22-49" src="https://github.com/rustdesk/rustdesk/assets/79645308/b13ccef7-649a-49be-a4cc-e1292ee7f194">
<img width="661" alt="tumei_2023-12-19_16-23-23" src="https://github.com/rustdesk/rustdesk/assets/79645308/da95d71c-bece-48d2-9047-674d262008ed">
<img width="670" alt="tumei_2023-12-19_16-23-31" src="https://github.com/rustdesk/rustdesk/assets/79645308/5778c5bc-c11f-4411-b5d0-eb7409714742">
<img width="762" alt="tumei_2023-12-19_16-23-53" src="https://github.com/rustdesk/rustdesk/assets/79645308/aaf523c8-d5b1-4b97-98d7-65d030cec81e">
<img width="619" alt="tumei_2023-12-19_16-33-01" src="https://github.com/rustdesk/rustdesk/assets/79645308/a0325510-d7dd-4d8a-8371-7d986111c95c">
<img width="797" alt="tumei_2023-12-19_16-23-15" src="https://github.com/rustdesk/rustdesk/assets/79645308/92ecbfd8-1515-4403-824a-32f2ee07d46e">

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/6587
