### ISSUE TITLE
Incredible slow when privacy mode is activated. 

### ISSUE THREAD

**Issue by josedellabosca** [rustdesk/rustdesk#6718]
### Bug Description

When privacy mode is activated FPS is literally 0 to 1fps.
Screen selector disappear.

in no privacy mode it works perfect.

### How to Reproduce

Install rustdesk, lan connect by ip, select privacy mode.

### Expected Behavior

To work the same way as privacy mode is not selected. and have screen selector enable.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

![rustdesk](https://github.com/rustdesk/rustdesk/assets/30614010/f81504a2-5a2e-485b-ae9e-2d2eeb123d62)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/3255
