### ISSUE TITLE
No Mouse Pointer when no physical mouse detected

### ISSUE THREAD

**Issue by phoenixwarrior95** [rustdesk/rustdesk#672]
Im running RustDesk on my Galaxy S22 Ultra (Android).

My remote computer doesnt have a mouse physically connected, so there is no mouse cursor unless I connect one to PC. While using the RuskDesk on my phone to control my remote PC with no physical mouse attached and with Mouse mode function, there is no cursor visible but I can still move around and click on things and even hold and roght click. Even enabling "Show Remote cursor" doesnt work.

Suggestions: Just like VNC, it has a dot as a cursor (within the app and not remote cursor). I believe you should add that to the android app to have a cursor automatically regardless if a physical mouse is or isnt detected.

![Screenshot_20220531-171045](https://user-images.githubusercontent.com/43919854/171287039-1fc6968f-2b1f-41ba-9a81-c3e19226eb61.jpg)
![Screenshot_20220531-171100](https://user-images.githubusercontent.com/43919854/171287041-25889b78-4a3c-4041-8361-e31a7c14be4a.jpg)

**Comment by rustdesk** [comment]
Thanks

**Comment by madkoding** [comment]
when you don't have a mouse connected and can't see mouse remotely, you could install a custom mouse driver to avoid that problem

This [Wacom driver](https://support.lenovo.com/us/en/downloads/ds004071) solve that

**Comment by phoenixwarrior95** [comment]
Thank you, Madkoding.

I do have another question. I made a Github request for the 5G hostname
issue. Not sure if that can be fixed. Its a major issue with connecting to
rustdesk via my hostname.

**Comment by shayaknyc** [comment]
Found this entry while searching for this problem. I'm still experiencing an issue where there's no cursor on the client window when there's no physical mouse installed. This is not an issue on windows clients, but on Android, there's no visual indicator of where the mouse is, unless there's some kind of "mouse over" effect on the connected machine's UI. Checked #2100 but didn't really understand the solution....?

**Comment by arnowelzel** [comment]
The linked issue [#112377](https://github.com/rustdesk/rustdesk/issues/12377) was closed as a duplicate to this. But my problem is not that there is no cursor but the cursor is the wrong one as soon as you do something which changes to cursor shape as the old shape is not restored then.

I would prefer having no cursor in this case, since having a little position indicator only - which happens in Android as well - is still better then have the wrong cursor shape depending on what you do (which also happens in Android).

**Comment by arnowelzel** [comment]
> Found this entry while searching for this problem. I'm still experiencing an issue where there's no cursor on the client window when there's no physical mouse installed. This is not an issue on windows clients, but on Android, there's no visual indicator of where the mouse is, unless there's some kind of "mouse over" effect on the connected machine's UI. Checked [#2100](https://github.com/rustdesk/rustdesk/pull/2100) but didn't really understand the solution....?

Maybe this was changed since you wrote that comment - but I have visual indicator in Android when there is no mouse pointer. My problem is, that this indicator changes to a double arrow mouse pointer when you resize windows and that shape then stays at is it is even when the UI action is done.
