### ISSUE TITLE
Manjaro KDE RustDesk UI too small on HD display 2880x1800

### ISSUE THREAD

**Issue by codeliger** [rustdesk/rustdesk#6722]
### Bug Description

My app UI is too small on Manjaro Linux running KDE.
I already am scaling the entire desktop up, and if I do it anymore the taskbar and other apps become too large.

### How to Reproduce

`yay -S rustdesk-bin`
> open rustdesk

### Expected Behavior

UI is normal size like other apps: 

OBS is the correct size:

![image](https://github.com/rustdesk/rustdesk/assets/9361348/422f3661-1455-492b-a2b4-6609fe371c4e)

### Operating system(s) on local side and remote side

Manjaro Linux Kernel 6.6.7-4 kded5 5.112.0

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/9361348/3205a924-0511-46c9-8a6c-5cefe1851d81)

![image](https://github.com/rustdesk/rustdesk/assets/9361348/9074a747-e38f-4a6d-999e-6ccb48521963)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by sang-shelton** [comment]
Same issue here

![Screenshot_20241006_031446](https://github.com/user-attachments/assets/873d1840-e8fb-420b-8870-88aa257aa23a)

![Screenshot_20241006_031623](https://github.com/user-attachments/assets/72083fe8-dfdb-4666-b73b-6a977cc67b0b)

![Screenshot_20241006_031851](https://github.com/user-attachments/assets/ae0e17f6-6f64-4419-ac3b-4deebffa3f2c)
