### ISSUE TITLE
Rustdesk lose focus after left-click or grabing any title windows bar in xfce

### ISSUE THREAD

**Issue by didli** [rustdesk/rustdesk#6724]
### Bug Description

After a left click on any windows title bar in the distant session, rustdesk lose focus : I can still move the cursor but I can't select, (left/right) click or grab anything. A "refresh" does nothing. On the controlled machine, the local cursor is in ALT mode (the cursor is locked on the window as if I was continuously pressing ALT to move it around). I will only retrieve the focus if I release the ALT mode locally on the physical machine. 

### How to Reproduce

- any left click on any xfce title bar window (right click works)

### Expected Behavior

- I should be able to click on the title window bar, with a long press to grab it and move it around 

### Operating system(s) on local side and remote side

Local : RDP session on a rocky linux LXC container / Distant : physical server with Fedora 38 xfce

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

unapplicable

### Additional Context

I believe the way I'm using rustdesk is a bit specific, which could make it quite hard to debug something like this :
I run a xrdp session to connect to an LXC container running latest Rocky Linux. From there I run rustdesk to reach a physical machine with Fedora 38 xfce.  It's not that important ~~since I can still right click to move windows around~~ * but I thought I should notify this issue for this particular use case.
* : I though I could move windows around from the right click menu but that was wrong : as soon as I need to "grab" a window, rustdesk lose focus.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
