### ISSUE TITLE
Mouse/Keyboard input not working on windows

### ISSUE THREAD

**Issue by MlHsieh** [rustdesk/rustdesk#6726]
### Bug Description

The remote side does not respond to mouse or keyboard input at all. File transfer works normally.
The remote side is win 10, and local side is win 11. The permission for mouse and keyboard input is ON for both remote and local sides.   
I tried on two remote computers (both win 10) and both encountered the same issue. If I switch the local side to android, the above issue disappeared.

### How to Reproduce

1. Install rustdesk 1.2.3 on the remote computer (Win 10).
2. Install rustdesk 1.2.3 on the local computer (Win 11).
3. Connect the remote computer.

### Expected Behavior

Control the remote computer normally.

### Operating system(s) on local side and remote side

Windows 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

I noticed some options are greyed out, and I don't have "sending Ctrl + Alt + Delete" options as well.
![image](https://github.com/rustdesk/rustdesk/assets/61381271/d03201ff-d06c-4d92-9da1-662f1fc11c50)
![image](https://github.com/rustdesk/rustdesk/assets/61381271/4bb67940-e497-4eff-875f-6090d19c0dce)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by rustdesk** [comment]
You turned on view mode.
