### ISSUE TITLE
Allow Renaming/Editing options for Android and Desktop App

### ISSUE THREAD

**Issue by phoenixwarrior95** [rustdesk/rustdesk#673]
I would like to be able to edit/rename my computer to whatever I desire, like editing out the Alias (Name of the user), the ID, the password and an option to remember the password and save it for quicker access for the Android app. It lacks all those features that the desktop app mostly has.

 As for the desktop app, Renaming is possible, but no editing ID/password, just unremember password (which is a good feature to have)

![Screenshot_20220531-172847](https://user-images.githubusercontent.com/43919854/171287729-e851fb2c-e4b8-4f9c-bfed-bf9effec03e2.jpg)
![20220531_173342](https://user-images.githubusercontent.com/43919854/171288727-6bdd501d-2846-45a7-9db8-70bb01d79ab9.jpg)

**Comment by rustdesk** [comment]
Thanks

**Comment by zoomx** [comment]
Any news about renaming in Android app?

**Comment by rustdesk** [comment]
in nightly build.
