### ISSUE TITLE
Voice call unable to connect. Click to accept, no response

### ISSUE THREAD

**Issue by 287809671** [rustdesk/rustdesk#6730]
### Bug Description

Voice call unable to connect. Click to accept, no response
![微信图片_20231221173529](https://github.com/rustdesk/rustdesk/assets/53225361/e4d1825c-8281-40bc-958c-c1b7ad3fce14)

### How to Reproduce

Voice call unable to connect. Click to accept, no response

### Expected Behavior

Voice call unable to connect. Click to accept, no response

### Operating system(s) on local side and remote side

windows 10

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

Voice call unable to connect. Click to accept, no response

### Additional Context

Voice call unable to connect. Click to accept, no response

**Comment by rustdesk** [comment]
@21pages

**Comment by 287809671** [comment]
Someone can help answer the code？

**Comment by 21pages** [comment]
1.2.3 works on my pc, let me find the possbile reason.

https://github.com/rustdesk/rustdesk/assets/14891774/6a0f04eb-a901-4e4b-8492-559d532d1558

**Comment by 287809671** [comment]
windows 10 This problem has occurred.

**Comment by 287809671** [comment]
During remote control, clicking to agree to a call is not allowed and must be done by a computer. This is the original issue.
