### ISSUE TITLE
RustDeskServer.Setup.exe isn't signed

### ISSUE THREAD

**Issue by tomaszs** [rustdesk/rustdesk#6734]
### Bug Description

The file included in https://github.com/rustdesk/rustdesk-server/releases/tag/1.1.9 for Windows in the ZIP file isn't signed, and it doesn't have publisher specifically. It means that Windows 11 shows two safety warnings that it may not be safe to run it.

![image](https://github.com/rustdesk/rustdesk/assets/834977/51e3df71-723e-4afa-9dc3-d81f6f0ce1fd)

### How to Reproduce

1. Download 1.1.9 Windows ZIP file
2. Try to run the Setup file

### Expected Behavior

Setup file is signed and has a publisher. No warning appears

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/834977/695d494e-75fe-4361-90c5-7de973c5087f)

**Comment by tomaszs** [comment]
I see you've closed my previous report about the poor installation experience (https://github.com/rustdesk/rustdesk/issues/6734).  I wanted to add you could add information to the instructions so that people won't quit when seeing security issues. I'm not happy with how you handle it

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/6467
