### ISSUE TITLE
Controls don't move with handle

### ISSUE THREAD

**Issue by fragtion** [rustdesk/rustdesk#6735]
### Bug Description

When moving the handle for the controls (using the 3x3 grey dots), only the lower portion of the controls dock/overlay moves away. The main control buttons remain centered.

Not sure if this is supposed to be intended behavior, but I've always found it a bit strange and annoying. It helps that the lower part can be moved around (and can be used to hide the top part) - but I think it would be more convenient (and less confusion) to simply be able to move the whole overlay as a single unit so the whole thing can be moved out of the way rather than minimized and moved separately which needs more clicks/steps.

### How to Reproduce

Drag the controls widget left or right. The upper section (buttons and controls) remain in place while the lower portion of the widget moves freely as expected.

### Expected Behavior

Both sections of the controls widget should shift together. The lower portion and upper portion should be locked together as if they were a single object?

### Operating system(s) on local side and remote side

All platforms

### RustDesk Version(s) on local side and remote side

1.2.4 nightly

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/2876889/82f78a3c-89a2-4ffe-bb1a-cff88e224fc7)

### Additional Context

I consider this more of a bug than a feature request, and hence the issue rather than a discussion suggestion.

**Comment by rustdesk** [comment]
Expected.

**Comment by rustdesk** [comment]
Lock the conversation because I know your meaning and we know what we are doing. Don't need endless invalid discussions.
