### ISSUE TITLE
Mouse-Icons not correct on Windows Server 2022

### ISSUE THREAD

**Issue by jogybaer0815** [rustdesk/rustdesk#6738]
### Bug Description

Mouse icons are not implemented correctly when remotely controlling a Windows server (2022 in my case).
When the session starts, a blue ball appears as a mouse pointer. An arrow only appears again when you move a window.
No dynamic adjustment, e.g. when changing the size of a window or text cursor. The last mouse icon remains static until the next adjustment.
Best regards

### How to Reproduce

Start the session with Windows Server 2022, regardless of whether it is from a Mac or Windows system

### Expected Behavior

Dynamic adjustment of the mouse icon depending on the editing step: move the window, change the size, mark text, etc. and return to the arrow when hovering over the desktop.

### Operating system(s) on local side and remote side

Windows 10, 11, MacOS Big Sur -> Windows Server 2022

### RustDesk Version(s) on local side and remote side

1.0 - 1.2.1

### Screenshots

![1_After-Start](https://github.com/rustdesk/rustdesk/assets/61113650/44f6a2f8-5ec8-4165-8f85-20ab388daf15)
![2_WindowResize](https://github.com/rustdesk/rustdesk/assets/61113650/b5158057-44a7-468c-9ada-0f59c38629ee)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367
