### ISSUE TITLE
Flashing occurs when the controlled end is Linux

### ISSUE THREAD

**Issue by bouyeijiang** [rustdesk/rustdesk#6743]
### Bug Description

The controlled end screen flashing

### How to Reproduce

Build your own server and the controlled end is Linux mint

### Expected Behavior

screen flashing

### Operating system(s) on local side and remote side

linux mint 20

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

...

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by ELForcer** [comment]
I think this is the same tearing problem when working with X.ORG on NVDIA video card, mentioned in these problems:
https://github.com/rustdesk/rustdesk/issues/6772 and https://github.com/rustdesk/rustdesk/issues/6857

This is not a RustDesk problem.
This is a tearing problem on Linux.
The reasons for tearing are usually the shortcomings of the X.org graphics server (there is no tearing on Wayland), the use of Nvidia graphics cards (I heard that there is no tearing on AMD) and bugs on the part of the developers of the desktop environments.
To solve the problem on NVIDIA, you need to turn off the Allow Flipping option. However, you will then have tearing in video games, when watching videos. Choose what is more important to you. No tearing or no artifacts when recording the screen / working in RustDesk

More details on how to do this are written here: https://github.com/rustdesk/rustdesk/issues/6772#issuecomment-2308207027

**Comment by bouyeijiang** [comment]
谢谢您的来信！我会及时查阅的

**Comment by bouyeijiang** [comment]
There is no such problem in other similar products, such as Anydesk, Todesk, Teamview, etc.
