### ISSUE TITLE
[Android] Scam warning doesn't appear if "start service" gets automatically enabled when toggling one of the share/capture toggles, most notably "screen capture"

### ISSUE THREAD

**Issue by NintendoManiac64** [rustdesk/rustdesk#6747]
### Bug Description

Simply put, the scam warning does not appear if the "start service" gets automatically enabled when toggling one of the share/capture toggles, most notably "screen capture"

### How to Reproduce

In the Android app, while "start service" is *not* enabled, enable "screen capture".

### Expected Behavior

The scam warning should appear when "start service" get automatically enabled when you toggle one of the various share/capture toggles, most notably "screen capture"

### Operating system(s) on local side

Android

### RustDesk Version(s) on local side

1.2.3

**Comment by sahilyeole** [comment]
Thanks for reporting. I'm on it.
