### ISSUE TITLE
Missing hevc and h264 encoders

### ISSUE THREAD

**Issue by Ilya87** [rustdesk/rustdesk#6751]
### Bug Description

In codec selection section I recently could't find hevc and h264 encoder.
Remote pc has 4070, my local AMD 5800H (integrated graphics)

5800H:
`[2023-12-25T16:44:50Z INFO  available] encoder count:2
"h264_amf"
"hevc_amf"
[2023-12-25T16:44:50Z INFO  available] decoders count:6
"h264" AV_HWDEVICE_TYPE_NONE
"hevc" AV_HWDEVICE_TYPE_NONE
"h264" AV_HWDEVICE_TYPE_DXVA2
"hevc" AV_HWDEVICE_TYPE_DXVA2
"hevc" AV_HWDEVICE_TYPE_D3D11VA
"h264" AV_HWDEVICE_TYPE_D3D11VA`

4070:
`[2023-12-25T20:04:38Z INFO  available] encoder count:2
"hevc_nvenc"
"h264_nvenc"
[2023-12-25T20:04:40Z INFO  available] decoders count:10
"h264" AV_HWDEVICE_TYPE_NONE
"hevc" AV_HWDEVICE_TYPE_NONE
"h264" AV_HWDEVICE_TYPE_CUDA
"hevc" AV_HWDEVICE_TYPE_CUDA
"h264" AV_HWDEVICE_TYPE_D3D11VA
"hevc" AV_HWDEVICE_TYPE_D3D11VA
"hevc" AV_HWDEVICE_TYPE_DXVA2
"h264" AV_HWDEVICE_TYPE_DXVA2
"h264_qsv" AV_HWDEVICE_TYPE_NONE
"hevc_qsv" AV_HWDEVICE_TYPE_NONE`

![Снимок экрана 2023-12-25 231444](https://github.com/rustdesk/rustdesk/assets/1446573/875804fb-bd9d-4699-b759-4405d6ffdc02)

### How to Reproduce

Connect from laptop to PC.

### Expected Behavior

HEVC and H264 codecs must be available

### Operating system(s) on local side and remote side

Windows 11 both sides

### RustDesk Version(s) on local side and remote side

1.2.3 both sides

### Screenshots

![Снимок экрана 2023-12-25 231444](https://github.com/rustdesk/rustdesk/assets/1446573/b38b1708-deed-4db9-8159-0efe83e5a1cb)

**Comment by 21pages** [comment]
1. Is  hardware codec option enabled on both side?
![rustdesk_UrXzbvDUUN](https://github.com/rustdesk/rustdesk/assets/14891774/e6eed0c1-4182-4b6e-8edb-6b4aa1506910)

2. This may occur when the app is just launched because the detection of hardware encoding and decoding availability has not been completed. Is this the connection made immediately after opening the app?

**Comment by Ilya87** [comment]
After remote PC reboot and installation of nightly version, the issue was fixed
