### ISSUE TITLE
Empty window on Mac when trying to build RustDesk.

### ISSUE THREAD

**Issue by jgcoelhof** [rustdesk/rustdesk#6754]
### Bug Description

Hello, good morning!

I am trying to build RustDesk on macOS, but I am facing issues...

When I run `cargo run`, I receive the following log:

[2023-12-26T14:43:37Z INFO  librustdesk::core_main] main start args:[]
WARNING:DOM: failed to load "/Users/iosi/Documents/rustdesk/vcpkg/src/ui/index.html" file, error=2
[sciter] warning! null element for HANDLE_BEHAVIOR_EVENT:DOCUMENT_CLOSE_REQUEST
[sciter] warning! null element for HANDLE_BEHAVIOR_EVENT:DOCUMENT_CLOSE_REQUEST

It opens RustDesk with an empty window, and it's not possible to use the application. It works fine on Linux.

### How to Reproduce

Run the standard RustDesk build for Mac, just change the git clone repository to the repository of my project.

cd
git clone https://github.com/microsoft/vcpkg
cd vcpkg
git checkout 2023.04.15
./bootstrap-vcpkg.sh
brew install nasm yasm
./vcpkg install libvpx libyuv opus aom
git clone https://github.com/ViniciusAndradex/rustdesk
cd rustdesk
export VCPKG_ROOT=$HOME/vcpkg
wget https://github.com/c-smile/sciter-sdk/raw/master/bin.osx/libsciter.dylib
cargo run

### Expected Behavior

Open RustDesk normally.

### Operating system(s) on local side and remote side

macOS

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

https://cdn.discordapp.com/attachments/804630702657110018/1189221608708132944/Captura_de_Tela_2023-12-26_as_11.png?ex=659d5fee&is=658aeaee&hm=2794924c5d398f30a01f5afd46bba35ba8c1960b4b47d7363b9170bd3e1a2b83&

<img width="1680" alt="Captura de Tela 2023-12-26 às 11 55 56" src="https://github.com/rustdesk/rustdesk/assets/95655454/5db40445-0379-4272-be0e-5cfd45972298">

**Comment by rustdesk** [comment]
#763
