### ISSUE TITLE
Issues when running the AppImage with AppImaged

### ISSUE THREAD

**Issue by RandallFlagg** [rustdesk/rustdesk#6759]
### Bug Description

When running the rust appimage using [AppImaged](https://github.com/probonopd/go-appimage/blob/master/src/appimaged/README.md) there are several errors reported(e.g. short name) and the icon isn't showing up.
Please fix the AppImage package to work with the AppImaged app.

### How to Reproduce

1. Run the appimage of rust with AppImaged (I used the Linux 64bit version).

### Expected Behavior

To work properly

### Operating system(s) on local side and remote side

Linux

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/434681/2cc9a703-f20b-461e-be1d-5946aa6fef2e)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
