### ISSUE TITLE
Unable to Run Project

### ISSUE THREAD

**Issue by astikbiswas304** [rustdesk/rustdesk#6767]
### Bug Description

showing Error (Xcode): 'bridge_generated.h' file not found while running this project.
Flutter Version: 3.16.5
Xcode Version: 15.1
Android SDK version 33.0.2
Android Studio (version 2022.3)

### How to Reproduce

Followed this process for ios
https://rustdesk.com/docs/nl/dev/build/ios/

### Expected Behavior

expected to run Rustdesk project on ios and android devices

### Operating system(s) on local side and remote side

Mac Os 14.2.1 

### RustDesk Version(s) on local side and remote side

1.2.4

### Screenshots

<img width="1388" alt="Screenshot 2023-12-29 at 4 08 15 PM" src="https://github.com/rustdesk/rustdesk/assets/42149347/5157ee3a-9dca-48bb-9190-aebb367d83f1">

**Comment by rustdesk** [comment]
#763
