### ISSUE TITLE
Android build issue when run ndk_arm64.sh 

### ISSUE THREAD

**Issue by souravkgp** [rustdesk/rustdesk#6768]
### Bug Description

error: could not find native static library `aom`, perhaps an -L flag is missing?

warning: `scrap` (lib) generated 1 warning
error: could not compile `scrap` (lib) due to previous error; 1 warning emitted

### How to Reproduce

I have follow the simply step of android build documentation
https://rustdesk.com/docs/en/dev/build/android/
When I have run ndk_arm64.sh then got this type of issue

### Expected Behavior

I have follow the simply step of android build documentation
https://rustdesk.com/docs/en/dev/build/android/
When I have run ndk_arm64.sh then got this type of issue

### Operating system(s) on local side and remote side

Linux mint 21.1

### RustDesk Version(s) on local side and remote side

1.82.6

### Screenshots

![Screenshot from 2023-12-29 17-22-53](https://github.com/rustdesk/rustdesk/assets/155157516/df5621b4-d8e0-492b-9824-c4bbddce5e52)

**Comment by rustdesk** [comment]
#763
