### ISSUE TITLE
Flickering On Linux Mint

### ISSUE THREAD

**Issue by BrendanKapp** [rustdesk/rustdesk#6772]
### Bug Description

Flickering occurs on the upper portion of the window when using RustDesk.

### How to Reproduce

- Run RustDesk to connect to a Linux Mint 21 Cinnamon machine.
- Wait for flicker to occur (moving mouse / window navigation increases this).

### Expected Behavior

No flickering on the window.

### Operating system(s) on local side and remote side

Linux Mint 21 w/ Cinnamon -> Linux Mint 21 w/ Cinnamon 

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.1.9

### Screenshots

[c391142046_20231229141637_VP9.webm](https://github.com/rustdesk/rustdesk/assets/43078099/fb93ff11-0b61-46a0-b9f0-48fc5e9664be)

### Additional Context

Public server and self-hosted server both produce the issue.

The window beneath the open window flickers through, in the video this is the desktop and its wallpaper.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by ELForcer** [comment]
This is not a RustDesk problem.
This is a tearing problem on Linux.
The reasons for tearing are usually the shortcomings of the X.org graphics server (there is no tearing on Wayland), the use of Nvidia graphics cards (I heard that there is no tearing on AMD) and bugs on the part of the developers of the desktop environments.
To solve the problem on NVIDIA, you need to turn off the Allow Flipping option. However, you will then have tearing in video games, when watching videos. Choose what is more important to you. No tearing or no artifacts when recording the screen / working in RustDesk

**Comment by vaab** [comment]
I confirm @ELForcer description and workaround. Many Thanks.
Server is on on ubuntu 22.04, using X and NVidia, and has the issue described. 

Let me breakdown further the fix mentioned by @ELForcer:

1. run `nvidia-settings`
2. in `nvidia-settings window`, select the `X Screen 0 / OpenGL Settings` menu item in the left part
3. un-tick `Allow Flipping` option in the right pane.
4. click the `Quit` Button on the bottom right,
5. confirm Quitting in the dialog box.

It should not flick anymore.
