### ISSUE TITLE
Blurry image MacOS Ventura 13.6.2 M2

### ISSUE THREAD

**Issue by kinhsman** [rustdesk/rustdesk#6773]
### Bug Description

The image is blurry, using self-hosted server

### How to Reproduce

connect to a Mac running MacOS Ventura 13.6.2 M2

### Expected Behavior

Image is not blurry

### Operating system(s) on local side and remote side

Windows/Ubuntu/iOS -> MacOS

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

![IMG_0122](https://github.com/rustdesk/rustdesk/assets/145226962/92ff8225-2199-4abc-95b3-0cdb95ee93b1)
![image](https://github.com/rustdesk/rustdesk/assets/145226962/1e8da815-5032-4ea8-a7c1-4f6c313e073c)
![image](https://github.com/rustdesk/rustdesk/assets/145226962/422a738a-f127-498f-8e09-5a65311f03b6)

**Comment by 21pages** [comment]
What about 1312x848 or VP9?

**Comment by sahilyeole** [comment]
Possibly related to https://github.com/rustdesk/rustdesk/issues/5246
