### ISSUE TITLE
es_ES keyboard mapping shows as en_US from Windows10 to Fedora38 i3WM (Stable+Nightly)

### ISSUE THREAD

**Issue by almAngel** [rustdesk/rustdesk#6774]
### Bug Description

Currently tested in 1.2.4 Nightly, but also tested in 1.2.3 Stable release. While typing in my Windows 10 spanish keyboard (has no numpad), it translates into english keyboard in my i3wm Fedora 38 linux (has numpad). Both are physical spanish keyboards.

### How to Reproduce

Connect from Windows 10 to Fedora 38 i3wm using either RustDesk 1.2.4 Nightly or RustDesk 1.2.3

### Expected Behavior

Keyboard mapping is not correct even trying other keyboard modes..

### Operating system(s) on local side and remote side

Windows 10 -> Fedora 38 i3WM

### RustDesk Version(s) on local side and remote side

1.2.4

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/22323419/38c02cb6-5cbd-48ee-8360-a0ad466d054f)
![image](https://github.com/rustdesk/rustdesk/assets/22323419/94509e16-f8e2-402c-a61b-6aad8d38b5ce)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
