### ISSUE TITLE
Application run  in iOS But Blank Screen

### ISSUE THREAD

**Issue by astikbiswas304** [rustdesk/rustdesk#6776]
### Bug Description

<img width="1344" alt="Screenshot 2024-01-01 at 1 41 14 PM" src="https://github.com/rustdesk/rustdesk/assets/42149347/66ddb17d-a1e8-4af5-85f6-374ee3d07e9d">

### How to Reproduce

When running on an ios device but the screen comes with white with errors

### Expected Behavior

Comes with proper UI

### Operating system(s) on local side and remote side

Mac Os 14.2.1 

### RustDesk Version(s) on local side and remote side

1.2.4

### Screenshots

<img width="1344" alt="Screenshot 2024-01-01 at 1 41 14 PM" src="https://github.com/rustdesk/rustdesk/assets/42149347/93936201-a773-442d-9638-0c9c16d467a3">

**Comment by rustdesk** [comment]
#763
