### ISSUE TITLE
When using in a dual-screen environment on Windows 7, the second screen will freeze.

### ISSUE THREAD

**Issue by Lao5-0ss** [rustdesk/rustdesk#6779]
### Bug Description

If you install the RustDesk nightly build version in Windows 7, there will be no response to any content on the second screen during remote connection.

### How to Reproduce

On a Windows 7 host and a remote client, install the latest version of the nightly build. After remotely connecting to the host and selecting to display the main and secondary screens simultaneously, there is no visible response to any operations on the secondary screen. However, if you connect to the host using AnyDesk or other remote software to observe the secondary screen, you will see that remote operations performed through RustDesk are being executed, but the display is not transmitted to the remote host. At this point, clicking on the refresh button in RustDesk will reveal the latest content on the screen. However, the screen will freeze again after a few seconds.

### Expected Behavior

If the host of RustDesk is Windows 10, everything is normal. The multi-screen functionality in Windows 7 is inconsistent with Windows 10.

### Operating system(s) on local side and remote side

osx->windows7

### RustDesk Version(s) on local side and remote side

1.2.4->1.2.4

### Screenshots

<img width="361" alt="截屏2024-01-02 下午3 54 08" src="https://github.com/rustdesk/rustdesk/assets/62927491/e20bf104-793b-4d1f-b7cf-a1fd9ab395a9">
<img width="361" alt="截屏2024-01-02 下午3 54 08" src="https://github.com/rustdesk/rustdesk/assets/62927491/8c0ec229-1a03-404b-a3a9-2cffab2f1dec">

**Comment by rustdesk** [comment]
#763
