### ISSUE TITLE
Scrap Error

### ISSUE THREAD

**Issue by astikbiswas304** [rustdesk/rustdesk#6780]
### Bug Description

error: failed to run custom build command for scrap v0.5.0 (/Users/astikbiswas/Documents/Projects/rustdesk/libs/scrap)       any solution for this? 

### How to Reproduce

while cargo build

### Expected Behavior

cargo run successfully 

### Operating system(s) on local side and remote side

Mac Os 14.2.1 

### RustDesk Version(s) on local side and remote side

1.2.4

### Screenshots

<img width="1342" alt="Screenshot 2024-01-02 at 4 08 03 PM" src="https://github.com/rustdesk/rustdesk/assets/42149347/d3008e21-a611-41e2-9379-63153fc787c3">

**Comment by rustdesk** [comment]
#763
