### ISSUE TITLE
Characters sent via Linux compose key are not processed

### ISSUE THREAD

**Issue by 64kramsystem** [rustdesk/rustdesk#6784]
### Bug Description

Characters sent via Linux compose key are not processed.

When trying to compose one, I hear the error bell, and the character is not composed/sent on the remote side.

This is independent of the keyboard mode (I've tried both map and translate).

### How to Reproduce

Assuming that:

- both client and remote side are Linux
- the compose key is Caps lock
- trying to compose `ä`

The steps are (on a connected):

1. tap `Caps lock`
1. tap `a`
1. the compose sequence is initiated (an underscore cursor will display)
1. tap `"`
1. the error bell will ring (probably this is on the client side), and the compose sequence is cancelled

### Expected Behavior

On point (5), the character `ä` should be sent.

### Operating system(s) on local side and remote side

Ubuntu -> Ubuntu

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

(none)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367
