### ISSUE TITLE
generated_bridge

### ISSUE THREAD

**Issue by IOCloudFly** [rustdesk/rustdesk#6785]
### Bug Description

![a85f87a14e4f1936c872570a61eb30f](https://github.com/rustdesk/rustdesk/assets/45480314/732091b5-3da5-4ef1-97f8-88cc702b9e95)

### How to Reproduce

import 'package:flutter_hbb/generated_bridge.dart';
no this generated_bridge

### Expected Behavior

1

### Operating system(s) on local side and remote side

Android 

### RustDesk Version(s) on local side and remote side

Flutter 3.16.5 • channel stable

### Screenshots

1

### Additional Context

1

**Comment by rustdesk** [comment]
#763
