### ISSUE TITLE
Bad network condition on client side cause multi-typing 

### ISSUE THREAD

**Issue by ddddavid-he** [rustdesk/rustdesk#6793]
### Bug Description

When connecting to remote computer in unstable network connections, rustdesk will perform multiple strikes on a single keystroke during typing. (as shown in the screenshot below)

![Screenshot_20240104_130702](https://github.com/rustdesk/rustdesk/assets/58453183/a625345c-5e24-4b91-b8ac-cd687e06c9cd)

### How to Reproduce

type some word in unstable network connections

### Expected Behavior

Type <ANYTHING> in client, do the same in remote.

### Operating system(s) on local side and remote side

Windows 11 -> Debian 12 (KDE Plasma 5)

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.4

### Screenshots

![Screenshot_20240104_130702](https://github.com/rustdesk/rustdesk/assets/58453183/c6fa025d-2e1d-4701-a436-b384837c29cb)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by rustdesk** [comment]
@fufesou to solve this, we need simulate linux long-press like Windows, I remember Windows long press generate multiple key down (Please confirm windows and osx).

**Comment by fufesou** [comment]
@ddddavid-he 

I can't understand how this issue arises. Did you long press the key? Or you just type "p" one time(down and up)?

If you type one time, the sender will only send the key event once, and the receiver will only process one key event.

**Comment by fufesou** [comment]
> Windows generates multiple down events for long press

Yes, it generates multiple down events.

**Comment by ddddavid-he** [comment]
To be more detailed, I only type "p" once and then the screen freezed for a while, after that a series of "p"s appears. The same thing happens to any key including Backspace, which is quite dangerous for coding or typing work.

**Comment by PiratesIRC** [comment]
I have the same issue, but it only happens when I am typing into VMs on the computer that I am remoted into. The computer I am logging in with and logging in to are connected via ethernet and the rust server is self-hosted on the same computer that is hosting the VMs. This started when I upgraded to the latest version of the rust client.

**Comment by harshRn** [comment]
Hi @rustdesk 
Seeing that this is not taken up by anyone, could I take a crack at it ? not sure, how involved the changes would be, but I would be glad to be of some help.
Thanks!

**Comment by rustdesk** [comment]
@harshRn of course.

**Comment by rustdesk** [comment]
> When we type passwords, some characters are often entered twice or even more often.


> Local OS: Windows 10 Pro 22H2
> Remote OS: Debian 12

**Comment by rustdesk** [comment]
The fix has been merged, please try out the latest nigthly build.
