### ISSUE TITLE
macOS Mojave, black screen at login

### ISSUE THREAD

**Issue by kyokus** [rustdesk/rustdesk#6794]
### Bug Description

When you log out of a user's session to log in with another user, the screen goes black. One character: indicates connected, waiting for image.

### How to Reproduce

When you log out of a user's session to log in with another user, the screen goes black. One character: indicates connected, waiting for image.

### Expected Behavior
to be able to switch between users without problems

### Operating system(s) on local side and remote side

Windows 11 > macOS Mojave

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

not

**Comment by rustdesk** [comment]
Very sorry, Mojave is too old for us for bug fix. If you have this problem on new osx, please let us know.

**Comment by kyokus** [comment]
I apologize, it is monterey the operating system.
