### ISSUE TITLE
error: linking with cc failed: exit status: 1

### ISSUE THREAD

**Issue by BiswajitRedoQ** [rustdesk/rustdesk#6804]
### Bug Description

I am trying to run for iOS Simulator, but I am getting the following error.

**error: linking with cc failed: exit status: 1**

Please help me for resolve this issue.
My system details,
<img width="279" alt="Screenshot 2024-01-05 at 1 22 30 PM" src="https://github.com/rustdesk/rustdesk/assets/154425598/8f2dfa94-8edc-4d44-a8c3-1c77e25c05ad">

### How to Reproduce

I have followed step which you are define in following url.
[https://rustdesk.com/docs/nl/dev/build/ios/](url)
When I want to run **VCPKG_ROOT=$HOME/vcpkg ./flutter/ios_x64.sh** this command, I am facing this error.

### Expected Behavior

This should run without any error.

### Operating system(s) on local side and remote side

macOS: 13.6.1 

### RustDesk Version(s) on local side and remote side

1.2.4

### Screenshots

<img width="1046" alt="Screenshot 2024-01-05 at 1 41 02 PM" src="https://github.com/rustdesk/rustdesk/assets/154425598/13eeddd0-c13a-4ea8-9d25-c9bedf43d3ff">

**Comment by rustdesk** [comment]
#763
