### ISSUE TITLE
Screen blur phenomenon when controlling Android phone

### ISSUE THREAD

**Issue by wsnfly** [rustdesk/rustdesk#6809]
### Bug Description

When controlling an Android phone, incorrectly reading the phone's horizontal or vertical screen status will cause screen distortion.  The error can be reproduced.  When this error occurs, you need to manually switch the screen direction of the controlled terminal, and let the console read it once again to display it normally.  However, the screen orientation cannot be effectively controlled during the screen blur period, so it is difficult to resolve the error without touching the controlled phone.
![Screenshot_20240105_170448_com carriez flutter_hbb](https://github.com/rustdesk/rustdesk/assets/22979107/75a48c10-58b8-40c4-a09c-7e2039a68245)

### How to Reproduce

被控端必须为安卓手机。使用软件强制切换成横屏模式，此时连接被控端，然后关闭连接。然后被控端强制退出到主界面。再次连接安卓手机。此时有概率花屏。

### Expected Behavior

希望在控制时可以准确读取被控端的屏幕方向

### Operating system(s) on local side and remote side

当远程端为安卓系统时

### RustDesk Version(s) on local side and remote side

1.2.1-1.2.3

### Screenshots

此时我的远程端手机为竖屏模式，但本地端错误的认为远程手机为横屏模式

https://github.com/rustdesk/rustdesk/assets/22979107/2235efc6-d506-4e08-a8cd-509da99797d1

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893

**Comment by wsnfly** [comment]
https://github.com/rustdesk/rustdesk/assets/22979107/79f2f268-27bf-4b94-9ba0-a62d6a1d5647
