### ISSUE TITLE
android scam warn dialog layout 

### ISSUE THREAD

**Issue by yangjuncode** [rustdesk/rustdesk#6812]
### Bug Description

屏幕共享后弹出的警告很难点击同意按钮

### How to Reproduce

 点击屏幕录制开关，弹出的警告框，同意按钮位置异常，无法点击

### Expected Behavior

界面按钮位置正常好点击

### Operating system(s) on local side and remote side

android 10.0

### RustDesk Version(s) on local side and remote side

1.2.4 nightly 2024-01-06

### Screenshots

![Screenshot_20240106-120426](https://github.com/rustdesk/rustdesk/assets/47293522/b40bb634-fe73-4b3c-8ca1-14484ad26494)

### Additional Context

估计跟我手机用的是  三星 android oneui 中的简易模式和界面字体加大了有关系，不过应该加个滚动条的

**Comment by rustdesk** [comment]
@sahilyeole
