### ISSUE TITLE
Key Mismatch

### ISSUE THREAD

**Issue by SimplyAnotherAnon** [rustdesk/rustdesk#6815]
### Bug Description

"Key Mismatch" error thrown by client when trying to connect to another system

### How to Reproduce

Type in ID, connect, get "key mismatch"

### Expected Behavior

should just connect as normal

### Operating system(s) on local side and remote side

windows 11 - > windows 10

### RustDesk Version(s) on local side and remote side

1.2.3 - > 1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/115472706/cab8a19d-d6d6-44f5-ae8f-d9298d29dd4c)

**Comment by rustdesk** [comment]
Upgrading server.
