### ISSUE TITLE
flatpak: Unsupported Display server, X11 or Wayland expected

### ISSUE THREAD

**Issue by wenerme** [rustdesk/rustdesk#6834]
### Bug Description

Unsupported Display server, X11 or Wayland expected

start by flatpak

- AlpineLinux
- xface
- x11

### How to Reproduce

after setup xface

```bash
flatpak install --user ./Downloads/rustdesk-1.2.3-x86_64.flatpak
```

then start

### Expected Behavior

works

### Operating system(s) on local side and remote side

osx

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/1777211/c27eaadf-fb37-4577-9f4e-60fac4f49b2b)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3565

**Comment by rustdesk** [comment]
anyway, try out nightly build please.

**Comment by wenerme** [comment]
@rustdesk tried nightly, same issues.

**Comment by rustdesk** [comment]
We have no resource to support every distro, this issue has to be left for enthusiast to solve.

**Comment by BienGudBoy** [comment]
@rustdesk @wenerme This bug is fixed in latest nightly, however I can't connect with this error: Connection refused

**Comment by rustdesk** [comment]
I can reproduce this on Fedora 44 with nightly flatpak, both wayland and x11. @fufesou please follow this up.

**Comment by rustdesk** [comment]
> I can reproduce this on Fedora 44 with nightly flatpak (on arm64, no SELinux), both wayland and x11. @fufesou please follow this up.

The latest nightly fixed my problem.

**Comment by BienGudBoy** [comment]
> > I can reproduce this on Fedora 44 with nightly flatpak (on arm64, no SELinux), both wayland and x11. @fufesou please follow this up.
> 
> The latest nightly fixed my problem.

@rustdesk It didn't fix the issue on Wayland unfortunately, on my side.

**Comment by CaptainFlint** [comment]
Just FYI, in case anybody finds this issue by searching. I also had this problem with rustdesk-1.2.3-2 on AlpineLinux (X11, Xfce, rustdesk installed from flatpak). I found the culprit: rustdesk is using `loginctl` to determine the session type, but it's not installed in Alpine by default. After installing elogind and rebooting, the display server type detection started working fine.
