### ISSUE TITLE
Elevated as Administrator is unusable

### ISSUE THREAD

**Issue by JulianAtkins** [rustdesk/rustdesk#6838]
### Bug Description

I connect to a remote Windows 10 system from another Windows 10 system.

When I open a cmd.exe or other application "as administrator" then the screen becomes frozen and I can't click anywhere (or type for that matter), the focus remains on the opened window, but I am unable to do anything.

The remote Windows 10 machine is running under VirtualBox, maybe that plays a role? I am not sure.

### How to Reproduce

- connect to remote system
- open cmd.exe as administrator
- verify that nothing on the screen is clickable, everything appears frozen

### Expected Behavior

I expected administrator windows/apps to work fine remotely.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

![screenshot](https://github.com/rustdesk/rustdesk/assets/156084296/a56ba5ed-7fdd-4ebb-8363-86293110903f)

**Comment by rustdesk** [comment]
Search "UAC" issues in this repo please.
