### ISSUE TITLE
blurry text when connect with web client using canvaskit 

### ISSUE THREAD

**Issue by liyimeng** [rustdesk/rustdesk#6851]
### Bug Description

blurry text when connect with web client using canvaskit. If rendering with html5, it looks ok, but too slow.

### How to Reproduce

connect to a rustdesk using web-client

### Expected Behavior

clear text

### Operating system(s) on local side and remote side

web --> windows/linux

### RustDesk Version(s) on local side and remote side

1.2.3 --> 1.2.3

### Screenshots

![Uploading Screenshot 2024-01-11 at 18.05.52.png…]()

**Comment by rustdesk** [comment]
Web client is meta, not maintained yet.
