### ISSUE TITLE
Privacy mode turns the remote screen black on Win 11

### ISSUE THREAD

**Issue by cyber-sec0** [rustdesk/rustdesk#6852]
### Bug Description

Privacy mode turns the remote screen black on Win 11

### How to Reproduce

Connect from a W10 to a W11 pc, and then enable privacy mode

### Expected Behavior

I should be able to see the screen using rustdesk

### Operating system(s) on local side and remote side

Windows 10 -> Windows 11

### RustDesk Version(s) on local side and remote side

W10 -> W11

### Screenshots

I can't see the W11 screen, it's all black.

**Comment by rustdesk** [comment]
Please try out nightly build on both side. There are two mode of privacy mode in nightly build, please try out both. Let us know there are still problem, also please screenshots please. We will reopen the issue if you confirm the two modes in nightly build
