### ISSUE TITLE
Occasional artifacts on screen

### ISSUE THREAD

**Issue by kibernaut** [rustdesk/rustdesk#6857]
### Bug Description

When connected to a desktop running Linux Mint, the screen flashes pixels like this. The "client" part is on Windows 10. Recorded a brief video for a sample.

### How to Reproduce

Connect to Linux Mint through the Windows 10 client.

### Expected Behavior

It worked fine on version 1.1.9.

### Operating system(s) on local side and remote side

Windows 10 -> Linux Mint 21

### RustDesk Version(s) on local side and remote side

1.2.3 - 1.2.3

### Screenshots

![2024-01-12 14_41_13-](https://github.com/rustdesk/rustdesk/assets/6024807/8fbb8209-fe23-4d00-af50-dd57d239b34b)

**Comment by kibernaut** [comment]
https://github.com/rustdesk/rustdesk/assets/6024807/da39a447-6c94-4da2-839e-cd48bad7ae9a

**Comment by kibernaut** [comment]
https://github.com/rustdesk/rustdesk/assets/6024807/7794b23d-ab72-401c-9a6a-0337f9cc321b

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by savineugenioan** [comment]
I have the same problem on 6.8.0-35-generic kernel...... But if I use codec H265 it is somehow a little better

**Comment by ELForcer** [comment]
This is not a RustDesk problem.
This is a tearing problem on Linux.
The reasons for tearing are usually the shortcomings of the X.org graphics server (there is no tearing on Wayland), the use of Nvidia graphics cards (I heard that there is no tearing on AMD) and bugs on the part of the developers of the desktop environments.
To solve the problem on NVIDIA, you need to turn off the Allow Flipping option. However, you will then have tearing in video games, when watching videos. Choose what is more important to you. No tearing or no artifacts when recording the screen / working in RustDesk

**Comment by zihaooo** [comment]
> To solve the problem on NVIDIA, you need to turn off the Allow Flipping option.

To the people who try to find this option, it is in the `nvidia-settings` -> X Screen 0 -> OpenGL Settings -> Allow Flipping
