### ISSUE TITLE
RustDesk 1.1.9 After installation, it is very slow

### ISSUE THREAD

**Issue by chmis8000** [rustdesk/rustdesk#689]
**Describe the bug you encountered:**

1.1.9 My own server, the remote desktop is very fast when it is not installed. After installation, it is very slow. For example, when you click the icon on the desktop, there is a delay of about 2-3 seconds.

**How did you install `RustDesk`?**

1.1.9 x64, 1.1.9 x86 on windows 2008 r2 x64

**Comment by rustdesk** [comment]
Mysterious

**Comment by congzhangzh** [comment]
When I increase bit rates, the keyboard response slow, will this give more insight?

**Comment by locklack** [comment]
I have same issue (windows 2019)
