### ISSUE TITLE
The problem of the Android mobile terminal

### ISSUE THREAD

**Issue by eramicro** [rustdesk/rustdesk#6899]
### Bug Description

The self-built service of ID, the dynamic public network IP used by the ID server network. When the IP is automatically replaced, the remote mobile Android terminal (frequently turned on) shows that it cannot be connected. Only restart the mobile service, I look forward to solving this problem in the new version, thank you.

### How to Reproduce

The self-built service of ID, the dynamic public network IP used by the ID server network. When the IP is automatically replaced, the remote mobile Android terminal (frequently turned on) shows that it cannot be connected.

### Expected Behavior

Hope to add a automatic detection function.

### Operating system(s) on local side and remote side

Android -> Android

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

Sorry forgot to forget the screenshot.

**Comment by rustdesk** [comment]
#763
