### ISSUE TITLE
whiteboard when close the laptop

### ISSUE THREAD

**Issue by ugenehan** [rustdesk/rustdesk#6900]
### Bug Description

If close the laptop, a whiteboard will appear while remote. And when remote, if I open a window and then open other windows, there will be no response. In fact, this window has already been opened. I need to disconnect the remote and reconnect,and the window opened for the second time will be displayed.

### How to Reproduce

1.close laptop
2. Connect to laptop remotely
3. open rustdesk,it is whiteboard
4. open chrome
5. open one folder,or click start menu and then open setting
6. 

### Expected Behavior

work ok.

### Operating system(s) on local side and remote side

Windows11 

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/9714462/f55bea41-60db-453c-9f35-ddb2d16d4426)

**Comment by rustdesk** [comment]
close to favor, https://github.com/rustdesk/rustdesk/issues/4296
