### ISSUE TITLE
Remote Linux local macOS non 0 DISPLAY Arrow keys strange behavior

### ISSUE THREAD

**Issue by zhshch2002** [rustdesk/rustdesk#6901]
### Bug Description

I'm using Manjaro as remote, macOS 14.2.1 (23C71) local. An X server running on DISPLAY 16 launched KDE's desktop environment and RustDesk.

After testing, the arrow keys are mapped to strange keys.

Up -> PtrSc
Left -> Alt
Down -> Meta
Right Normal

Normal when using DISPALY 0.

All legacy, map, translate mode has same problem.

On top of that, it seems that the macOS Nightly build is experiencing problems.

### How to Reproduce

as mentioned above

### Expected Behavior

Correct arrow key response

### Operating system(s) on local side and remote side

macOS to Linux

### RustDesk Version(s) on local side and remote side

1.2.2 to 1.2.4 nightly has tested

### Screenshots

-

**Comment by imcsq** [comment]
I'm using ubuntu+gnome as remote, encountering the same problem (Up -> PtrSc; Left -> Alt; Right & Down: unknown yet).

**Comment by imcsq** [comment]
hi @zhshch2002 , have you fixed the issue :)

**Comment by turekv** [comment]
Same problem also here:
* Local machine: Devuan x64 (KDE) or Windows 11 x64
* Remote machine: Devuan x64 (KDE)
* In the case of Devuan local & remote, both PCs even use the identical physical keyboard (make & model).

I also noticed that the numpad keys respond in a strange way (e.g., / is mapped to Insert).

Changing the keyboard mode from Map to Translate or Legacy makes no difference. Switching to "Input source 2" (only Map mode is available here) does not solve the problem either.
