### ISSUE TITLE
Filetransfer not available if remote system got a custom shell instead of standard explorer.exe

### ISSUE THREAD

**Issue by bykidi** [rustdesk/rustdesk#6912]
### Bug Description

Issue name^.
Tested on Windows 11 (master) machine (PC that is connecting to another machine) and Windows 7 (slave) machine (which we connect to).

### How to Reproduce

On the machine with Windows 7 (not tested on any other OS type) if we activate advanced shell settings and change our desired shell to something else (windows will not boot explorer.exe upon startup) - when we connect to it there will be no disks or folders and filetransfer from or to that machine is not available.

### Expected Behavior

Filetransfer should work no matter what shell is executed upon startup.

### Operating system(s) on local side and remote side

Windows 11 x64, No matter actually

### RustDesk Version(s) on local side and remote side

1.2.3 (2023-10-13 10:57) > 1.2.3 (2023-10-13 10:57)

### Screenshots

![изображение](https://github.com/rustdesk/rustdesk/assets/1337953/2a58bcc7-5712-4c3e-bc47-e4a1fac6069e)

### Additional Context

If we manually start an explorer.exe and then reconnect with rustdesk then filetranfer will be available again

**Comment by rustdesk** [comment]
#763
