### ISSUE TITLE
Xorg warping mouse into window doesn't capture keyboard

### ISSUE THREAD

**Issue by norpie** [rustdesk/rustdesk#6916]
### Bug Description

When using a window manager (dwm in my case) to move your mouse to the rustdesk window, the window doesn't take keyboard input until you mouse out of the window and back in.

### How to Reproduce

1. Have rustdesk open next to other window.
2. Use keyboard shortcut to warp mouse to rustdesk.
3. Observe keyboard input not working.
4. Mouse out and back in the window manually.
5. Keyboard input now works.

### Expected Behavior

1. Have rustdesk open next to other window.
2. Use keyboard shortcut to warp mouse to rustdesk.
3. Keyboard input works.

### Operating system(s) on local side and remote side

ArchLinux (Xorg) -> any

### RustDesk Version(s) on local side and remote side

1.2.3 -> any

### Screenshots

https://github.com/rustdesk/rustdesk/assets/46564751/dbb67ffb-1b7b-4982-bbca-6a1f5c7b1b1d

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
