### ISSUE TITLE
[AppImage] Rustdesk opens but doesn't show any windows

### ISSUE THREAD

**Issue by Heus-Sueh** [rustdesk/rustdesk#6917]
### Bug Description

![image](https://github.com/rustdesk/rustdesk/assets/98482469/a5b3a32f-ea2d-4c74-84c5-42260262226f)

```
❯ ./rustdesk-1.2.3-x86_64.AppImage 
load librustdesk.so failed

(rustdesk:32416): Gtk-WARNING **: 11:04:41.349: Theme parsing error: gtk.css:519:34: 'font-feature-settings' is not a valid property name

(rustdesk:32416): Gtk-WARNING **: 11:04:41.352: Theme parsing error: gtk.css:1233:81: 'font-feature-settings' is not a valid property name

(rustdesk:32416): Gtk-WARNING **: 11:04:41.353: Theme parsing error: gtk.css:1419:91: 'font-feature-settings' is not a valid property name

(rustdesk:32416): Gtk-WARNING **: 11:04:41.359: Theme parsing error: gtk.css:3216:109: 'font-feature-settings' is not a valid property name

(rustdesk:32416): Gtk-WARNING **: 11:04:41.359: Theme parsing error: gtk.css:3218:62: 'font-feature-settings' is not a valid property name

(rustdesk:32416): Gtk-WARNING **: 11:04:41.359: Theme parsing error: gtk.css:3282:65: 'font-feature-settings' is not a valid property name

(rustdesk:32416): Gtk-WARNING **: 11:04:41.359: Theme parsing error: gtk.css:3349:77: 'font-feature-settings' is not a valid property name
Gtk-Message: 11:04:41.389: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:04:41.390: Failed to load module "canberra-gtk-module"
flutter: launch args: []
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'librustdesk.so': libnsl.so.1: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
#2      PlatformFFI.init (package:flutter_hbb/models/native_model.dart:112)
#3      initEnv (package:flutter_hbb/main.dart:107)
#4      runMainApp (package:flutter_hbb/main.dart:120)
#5      main (package:flutter_hbb/main.dart:101)
<asynchronous suspension>


** (rustdesk:32416): WARNING **: 11:05:07.033: atk-bridge: get_device_events_reply: unknown signature

```

### How to Reproduce

maybe try running rustdesk [AppImage] on Fedora Silverblue

### Expected Behavior

show something

### Operating system(s) on local side and remote side

Fedora Silverblue

### RustDesk Version(s) on local side and remote side

Fedora Silverblue

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/98482469/b72720c6-f18f-4000-94bb-e389aff6c788)

### Additional Context

# System Details Report

## Report details
- **Date generated:**                              2024-01-18 11:09:21

## Hardware Information:
- **Hardware Model:**                              Gigabyte Technology Co., Ltd. Z370M AORUS Gaming
- **Memory:**                                      16.0 GiB
- **Processor:**                                   Intel® Core™ i7-8700K × 12
- **Graphics:**                                    NVIDIA GeForce GTX 1060 6GB
- **Disk Capacity:**                               1.2 TB

## Software Information:
- **Firmware Version:**                            F14
- **OS Name:**                                     Fedora Linux 39.20240116.0 (Silverblue)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.3
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.6.9-200.fc39.x86_64

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1691
