### ISSUE TITLE
Problem with Shift + "."

### ISSUE THREAD

**Issue by giuliovale** [rustdesk/rustdesk#692]
The problem with shift + "." it is still present in the new build as well

https://github.com/rustdesk/rustdesk/blob/2724bd40000f81b5e316ea867fee66bf9761abc0/libs/enigo/src/win/win_impl.rs#L378

**Comment by rustdesk** [comment]
It worked on my keyboard though.

**Comment by giuliovale** [comment]
Thanks for reply .
I make test on diffent machine (windows 10/ windows 11) and there is the same problem

**Comment by giuliovale** [comment]
> It worked on my US keyboard with Italian language though. We only have US keyboard, no way to test on different language keyboards yet.

Isn't it possible to have a debug version or a boot option that scans the keyboard and saves the codes? In this way we could contribute.

**Comment by rustdesk** [comment]
Could you build and run from source code and figure out why https://github.com/rustdesk/rustdesk/blob/2724bd40000f81b5e316ea867fee66bf9761abc0/libs/enigo/src/win/win_impl.rs#L378 failed, or figure out a new way?

**Comment by giuliovale** [comment]
> Could you build and run from source code and figure out why
> 
> https://github.com/rustdesk/rustdesk/blob/2724bd40000f81b5e316ea867fee66bf9761abc0/libs/enigo/src/win/win_impl.rs#L378
> 
> failed, or figure out a new way?

Compile is not so simple for me
What you think if we use something like https://www.nirsoft.net/utils/keyboard_state_view.html ?

**Comment by rustdesk** [comment]
@giuliovale 
Could you please checkout rustdesk source code, and run below with git bash.

```
cd rustdesk/libs/enigo
cargo run --example key
```

https://github.com/rustdesk/rustdesk/blob/b526bf4a67f7e05b2d3f739864ecc31cabc18a85/libs/enigo/examples/key.rs#L9

This is easy to compile and debug for you.

**Comment by giuliovale** [comment]
Ok after compile if I run key.exe the output is .

**Comment by rustdesk** [comment]
@giuliovale could you git pull and run again?

**Comment by giuliovale** [comment]
> @giuliovale could you git pull and run again?

Yeah now I think is ok I see :_

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/tag/1.1.9 updated
