### ISSUE TITLE
OS password trims white space and saves it incorrectly

### ISSUE THREAD

**Issue by nickdickinson** [rustdesk/rustdesk#6920]
### Bug Description

On Version 1.2.3 if one has a space at either the beginning or the end of the password, RustDesk trims the input. This makes the password fail.

### How to Reproduce

1. Input an OS password with a space at beginning or end of the password.
2. Edit the password and make it visible and the space is missing.
3. Try to insert the password and it will fail because the space is missing.

### Expected Behavior

The expected behaviour would be to accept the password as-is without any trimming.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

First adding spaces
![Screenshot 2024-01-19 12 10 13](https://github.com/rustdesk/rustdesk/assets/1900032/efbc3548-b124-48a3-a3af-8b5dabe28ead)

Then editing the OS password and no spaces anymore
![Screenshot 2024-01-19 12 10 28](https://github.com/rustdesk/rustdesk/assets/1900032/e28ec180-9753-4b62-afef-3dabd66c80ba)

This can also be tested with an OS and user set to have a space at start or end of the user password and then it will not work when inserting. Somewhere trimming is applied

**Comment by rustdesk** [comment]
Sorry, we wont fix this.

**Comment by nickdickinson** [comment]
Where can we have a discussion about this? @rustdesk
I think that perhaps some people will copy paste once from a word document and then need a trim but anyone with a password manager should not have this issue. I think that if there is pasting involved, then perhaps trimming could be done on pasting rather than on save.
