### ISSUE TITLE
Ubuntu 20.04.3 LTS RK3566 libGL error: failed to create dri screen rockchip GL proc resolver's glGetString(GL_VERSION) failed

### ISSUE THREAD

**Issue by bi7jta** [rustdesk/rustdesk#6936]
### Bug Description

rustdesk 
libGL error: failed to create dri screen
libGL error: failed to load driver: rockchip                                                                  
libGL error: failed to create dri screen                                                                      
libGL error: failed to load driver: rockchip                                                                  
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(57)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed                                                                             
Aborted            

run:
LIBGL_ALWAYS_SOFTWARE=1 rustdesk

Not work.

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

### How to Reproduce

Desktop,  run application.

### Expected Behavior

Normal open the app

### Operating system(s) on local side and remote side

Ubuntu 20.04.3 LTS  RK3566 ARM64bit

### RustDesk Version(s) on local side and remote side

rustdesk-1.2.3-aarch64.deb

### Screenshots

![RK3566](https://github.com/rustdesk/rustdesk/assets/22002824/ac58d203-bdd0-4399-81c5-562dc01a726e)

### Additional Context

ido@ido:~$ rustdesk 
libGL error: failed to create dri screen
libGL error: failed to load driver: rockchip                                                                  
libGL error: failed to create dri screen                                                                      
libGL error: failed to load driver: rockchip                                                                  
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(57)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed                                                                             
Aborted                                                                                                       
ido@ido:~$ rustdesk                                                                                           
libGL error: failed to create dri screen                                                                      
libGL error: failed to load driver: rockchip                                                                  
libGL error: failed to create dri screen                                                                      
libGL error: failed to load driver: rockchip                                                                  
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(57)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed                                                                             
Aborted                                                                                                       
ido@ido:~$ glxinfo | grep version                                                                             
libGL error: failed to create dri screen                                                                      
libGL error: failed to load driver: rockchip                                                                  
libGL error: failed to create dri screen                                                                      
libGL error: failed to load driver: rockchip                                                                  
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.5
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL core profile version string: 4.5 (Core Profile) Mesa 21.0.3
OpenGL core profile shading language version string: 4.50
OpenGL version string: 3.1 Mesa 21.0.3
OpenGL shading language version string: 1.40
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
    GL_EXT_shader_implicit_conversions, GL_EXT_shader_integer_mix, 
ido@ido:~$ LIBGL_ALWAYS_SOFTWARE=1 rustdesk                                                                   
libGL error: failed to create dri screen                                                                      
libGL error: failed to load driver: rockchip                                                                  
libGL error: failed to create dri screen                                                                      
libGL error: failed to load driver: rockchip                                                                  
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(57)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed
Aborted
ido@ido:~$ LIBGL_ALWAYS_SOFTWARE=1 rustdesk
libGL error: failed to create dri screen
libGL error: failed to load driver: rockchip
libGL error: failed to create dri screen
libGL error: failed to load driver: rockchip
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(57)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed
Aborted
ido@ido:~$

**Comment by rustdesk** [comment]
Please search libGL in this repo, you will find a lot of duplicates.

**Comment by bi7jta** [comment]
> Please search libGL in this repo, you will find a lot of duplicates.

glxinfo | grep "OpenGL"
libGL error: failed to create dri screen
libGL error: failed to load driver: rockchip
libGL error: failed to create dri screen
libGL error: failed to load driver: rockchip
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 12.0.0, 128 bits)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 21.0.3
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.1 Mesa 21.0.3
OpenGL shading language version string: 1.40
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions

**Comment by pourfard** [comment]
I had the same problem with my orangepi. I tried lot's of ways and even compiled the rustdesk source. Finally rustdesk runs but shows a white empty screen and I think all of the problems is flutter. So I decided to run some commands.

you can get rustdesk id with `sudo rustdesk --get-id` and change the password with `sudo rustdesk --password YOUR_PASSWORD` and if you want to set ID/Relay server to your own server just change `/root/.config/rustdesk/RustDesk2.toml` and restart the service.

**Comment by Octolus** [comment]
@bi7jta Hi, did you find a solution for this? I have same issue on RK3588 Debian 11.

**Comment by czboosj** [comment]
同样的问题, 无法解决

**Comment by jhoughjr** [comment]
I'm just trying to build a svelte kit app on the opi. zero reason for libel to be involved with a client build I'd think.

**Comment by leorio23** [comment]
I had same problem, but using:
LIBGL_ALWAYS_INDIRECT=1 rustdesk

Worked on my RK3588, debian image from OrangePi site.
Orange Pi 1.2.2 Jammy with Linux 6.1.99-rockchip-rk3588

**Comment by YasinFu** [comment]
> I had the same problem with my orangepi. I tried lots of ways and even compiled the rustdesk source. Finally rustdesk runs but shows a white empty screen and I think all of the problems is flutter. So I decided to run some commands.
> 
> you can get rustdesk id with `sudo rustdesk --get-id` and change the password with `sudo rustdesk --password YOUR_PASSWORD` and if you want to set ID/Relay server to your own server just change `/root/.config/rustdesk/RustDesk2.toml` and restart the service.

This method is useful, but how to set the transferable file? Currently, the directory cannot be read when transferring files.
