### ISSUE TITLE
ERROR librustdesk::ui_interface] ipc connection closed: reset by the peer

### ISSUE THREAD

**Issue by KhieuDuong** [rustdesk/rustdesk#6947]
### Bug Description

I built an exe file using the command 'python3 build.py --flutter,' then installed the newly built file on my computer. However, when connecting to this computer from another computer, I encountered the following error:
 ERROR librustdesk::ui_interface] ipc connection closed: reset by the peer
[2024-01-22T05:48:56Z INFO  librustdesk::ui_cm_interface] cm ipc connection closed: reset by the peer
error: process didn't exit successfully: `target\debug\rustdesk.exe` (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)

### How to Reproduce

![Screenshot 2024-01-22 145811](https://github.com/rustdesk/rustdesk/assets/66666649/b766b089-b4d9-498e-8a08-a775bdf9914c)

### Expected Behavior

![Screenshot 2024-01-22 145811](https://github.com/rustdesk/rustdesk/assets/66666649/a76043f4-46d9-4132-865b-718e85386f05)

### Operating system(s) on local side and remote side

Window 10 and window 11

### RustDesk Version(s) on local side and remote side

1.2.14

### Screenshots

![Screenshot 2024-01-22 145811](https://github.com/rustdesk/rustdesk/assets/66666649/85f92ed3-c740-49db-8fa3-314c798c593c)

**Comment by rustdesk** [comment]
#763

**Comment by elseif** [comment]
libs\scrap\src\common\codec.rs
Encoder::update

**Comment by rustdesk** [comment]
@elseif AV1 causes this?

**Comment by 21pages** [comment]
@elseif Please try https://github.com/21pages/test/releases/download/test/benchmark.exe to see if AV1 is ok
