### ISSUE TITLE
Color rendering mismatch on all odd vertical pixel count-sized resolutions

### ISSUE THREAD

**Issue by skull-squadron** [rustdesk/rustdesk#6964]
### Bug Description

Every vertical resolution with an odd number of pixels (default for half resolution on 16" MBP m1) renders color-containing image data offset up.

Grayscale items will be in their original position relative to the framebuffer, however color-containing regions appear offset.

### Remote
1. Set mac built-in display to resolution 1728x1117
2. Start background service
### Local
3. Connect to remote from a Windows client

### Expected Behavior

Colors rendered on the remote display should line up similarly to even vertical pixel-sized displays.

### Operating system(s) on local side and remote side

Windows 11 22H2 -> macOS Sonoma 14.2.1

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

![Screenshot 2024-01-23 010524](https://github.com/rustdesk/rustdesk/assets/224304/42dcef9a-24fc-449e-9bce-59cd34d57cdb)
![Screenshot 2024-01-23 010235](https://github.com/rustdesk/rustdesk/assets/224304/418bd49b-80b7-46ba-9a15-552de9a9a268)
![Screenshot 2024-01-23 010302](https://github.com/rustdesk/rustdesk/assets/224304/1a65bf18-b1aa-4acf-b79d-a206434554d4)
![Screenshot 2024-01-23 010320](https://github.com/rustdesk/rustdesk/assets/224304/4747784d-de1e-4750-8d70-afc4713c78c3)
![Screenshot 2024-01-23 010342](https://github.com/rustdesk/rustdesk/assets/224304/47d975a5-05ce-4ff2-bdd0-6d382236cb81)
![Screenshot 2024-01-23 010400](https://github.com/rustdesk/rustdesk/assets/224304/d7d9024e-7158-4f47-a32d-0071314515d0)
![Screenshot 2024-01-23 010420](https://github.com/rustdesk/rustdesk/assets/224304/e2011119-3f3c-41d4-aba9-344f906ab31a)
![Screenshot 2024-01-23 010433](https://github.com/rustdesk/rustdesk/assets/224304/77dd8f57-c0d1-49be-b265-8ac50943993c)
![Screenshot 2024-01-23 010453](https://github.com/rustdesk/rustdesk/assets/224304/19bca0fb-0be7-4bd1-84b4-cb334b29117b)
![Screenshot 2024-01-23 010509](https://github.com/rustdesk/rustdesk/assets/224304/a91f05ce-d4ff-4e50-a123-bf610f0f6613)

### Additional Context

- Local display: 5120x1440 (SDR) external secondary, 2560x1440 (HDR-capable) primary (disabled)
- Hardware codec: Enabled \*
- ID server: LAN-local Docker container
- Relay server: LAN-local Docker container
- API server: (blank)
- Key: (blank)
- Encryption: disabled (Running locally only)
- Direct IP: enabled
- Scale: Scale adaptive \*
- Image quality: Good image quality \*
- Codec: Auto # 

\* No impact with any other setting
\# AV1 displayed in screenshots. VP8 produces a similar but different corruption. VP9 corruption same as VP8.

**Comment by rustdesk** [comment]
close to favor https://github.com/rustdesk/rustdesk/issues/6518

**Comment by rustdesk** [comment]
@21pages I thought same to #6518, but not, please check

**Comment by rustdesk** [comment]
Sorry, this is related to https://github.com/rustdesk/rustdesk/issues/5246
