### ISSUE TITLE
Cannot install rustdesk client 1.2.3 on windows 11

### ISSUE THREAD

**Issue by stormextra** [rustdesk/rustdesk#6974]
### Bug Description

running the exe doesn't open any dialog window. uac is disabled. also trying to install it via powershell script. writing request stream goes through, then installing service shows, and it gets stuck there. i am on windows 11 21h2. it works on another windows machine which is w11 23h2, but also doesn't work on another running w11 23h2. windows 10 devices work fine on all of them i have tested.
the nightly build works fine on all machines.

### How to Reproduce

try to install the rustdesk client 1.2.3 on a windows 11 device

### Expected Behavior

rustdesk client would install on my machine

### Operating system(s) on local side and remote side

windows 11

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

i can provide any screenshots needed.

**Comment by rustdesk** [comment]
Then, use nightly build please.

**Comment by stormextra** [comment]
Ok understandable. I'm trying to mass deploy to 450+ devices so need to use the script, I tried to adjust the script to use the nightly build but couldn't get it working. Do you have an example of this?

**Comment by happyme531** [comment]
> Thanks for your report. Use nightly build please. We won't go back to fix 1.2.3

Current Nightly build does not work either on my Windows 23H2 22635.3139

**Comment by happyme531** [comment]
> > Thanks for your report. Use nightly build please. We won't go back to fix 1.2.3
> 
> Current Nightly build does not work either on my Windows 23H2 22635.3139

Rebooted my computer, issue solved
