### ISSUE TITLE
Rustdesk infinite "connecting" on LAN

### ISSUE THREAD

**Issue by KianBrose** [rustdesk/rustdesk#6981]
### Bug Description

I have two computers on the same local area network. One of them is the server that I want to remotely control, it is located on 192.168.1.79.

After setting up the client as seen below, it says "Ready" implying that it is able to connect:
<img width="343" alt="image" src="https://github.com/rustdesk/rustdesk/assets/62078964/be623d86-b0c4-4c9a-9560-b33a1e783495">
<img width="609" alt="image" src="https://github.com/rustdesk/rustdesk/assets/62078964/f0eb8066-749a-4285-a820-a899f70ff762">

However, when actually trying to connect, it says "connecting" infinitely, and eventually timeout:
<img width="1176" alt="image" src="https://github.com/rustdesk/rustdesk/assets/62078964/b7908a96-448c-4325-afc9-2bf443ff8c47">

I tried this on both the latest version of rustdesk AND nightly, I attempted to look at other open github issues and no solution worked whatsoever.

The /var/log/rustdesk `.error` files were empty.

The firewall is active and set up as such:
![image](https://github.com/rustdesk/rustdesk/assets/62078964/2311430f-138f-45dd-847d-148bd032239c)

Systemctl indicated everything is running fine:
![image](https://github.com/rustdesk/rustdesk/assets/62078964/25e0a227-8d89-4443-9c97-f1f432dc9e23)

Rustdesk doctor shows that everything is OK except the API which to my understanding isn't necessary and can be ignored.
![image](https://github.com/rustdesk/rustdesk/assets/62078964/645810b2-c24b-4bb2-8481-5c4ee906203f)

What's causing the infinite connecting & eventual timeout?

### How to Reproduce

Perform default installation and attempt to connect in LAN on both LTS and nightly.

### Expected Behavior

It should be able to connect

**Comment by rustdesk** [comment]
#763
