### ISSUE TITLE
SmartPhone - direct connection vi IP

### ISSUE THREAD

**Issue by weekendkoder** [rustdesk/rustdesk#699]
I like the RustDesk version on my Android Smartphone a lot ! It works fine. What i would like to see is a **direct IP connection** to my phone inside my home wireless lan system. This Feature would be great. I hope something like this is possible to realize. Thanks.

**Comment by rustdesk** [comment]
@fufesou

**Comment by weekendkoder** [comment]
Okay. Even its low ... luckily its on a priority list 👍

**Comment by rustdesk** [comment]
merged
