### ISSUE TITLE
My mouse cannot be controlled, accessible mode has been turned on

### ISSUE THREAD

**Issue by lrange2001** [rustdesk/rustdesk#6990]
### Bug Description

Android Industrial Development Edition 3566, 3568;

My mouse cannot be controlled, accessible mode has been turned on

### How to Reproduce

Android Industrial Development Edition 3566, 3568;

My mouse cannot be controlled, accessible mode has been turned on

### Expected Behavior

Android Industrial Development Edition 3566, 3568;

My mouse cannot be controlled, accessible mode has been turned on

### Operating system(s) on local side and remote side

Android11

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

Android Industrial Development Edition 3566, 3568;

My mouse cannot be controlled, accessible mode has been turned on

**Comment by rustdesk** [comment]
nightly build please
