### ISSUE TITLE
Scam warning buttons out of screen on android

### ISSUE THREAD

**Issue by shanks3042** [rustdesk/rustdesk#6993]
### Bug Description

The buttons of the scam warning are not on the screen and i can't click it. Thus I can't start rustdesk on my phone.

### How to Reproduce

Click "start service" button on a phone with screen <= 5" (I'm using [Xperia XA1](https://www.gsmarena.com/sony_xperia_xa1-8596.php))

### Expected Behavior

Buttons should be on the screen and clickable.

### Operating system(s) on local side and remote side

Local: Android, remote not possible.

### RustDesk Version(s) on local side and remote side

1.2.3-2

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/50264155/64316588-7788-4cc9-842b-a3dd9e88e8b5)

### Additional Context

The buttons are barely visible but if I click them (the left button) the service is not started and I get this warning again the next time I click "Start Service".

**Comment by rustdesk** [comment]
fixed in nightly build already.
