### ISSUE TITLE
[Feature Request] Is it possible to add support for ARMv7 processors for Android version? (安卓版能否增加对 ARMv7 处理器的支持？)

### ISSUE THREAD

**Issue by ynyyn** [rustdesk/rustdesk#7]
I failed to install RustDesk for Android on an old device. After some research I found that RustDesk‘s native-code is `arm64-v8a` but my old device is with an ARMv7 processor. 
我无法在一台旧设备上安装 RustDesk 安卓版。经过调查发现 RustDesk 的 native-code 编译为 arm64-v8a，而那台旧设备的处理器为 ARMv7 处理器。

```powershell
PS > aapt.exe dump badging rustdesk-1.1.1.apk
...
native-code: 'arm64-v8a'
```

Could you consider adding support for ARMv7?
请问能否考虑增加对 ARMv7 的支持？

**Comment by open-trade** [comment]
还在用ARMv7的机器不多吧

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/611
