### ISSUE TITLE
Add way to remotely enter admin password

### ISSUE THREAD

**Issue by marekjedrzejewski** [rustdesk/rustdesk#70]
When rustdesk is ran as standard user in Windows, when UAC prompt shows up, on the connecting side screen just freezes, and I don't see option to provide password without entering it on the other side. Would be very nice to have this option :)

**Comment by rustdesk** [comment]
Sorry, not understand

**Comment by rustdesk** [comment]
Ok, I got it. But I have no idea how to implement it yet for now. You'd better install it and let it run as service.

**Comment by marekjedrzejewski** [comment]
AnyDesk has option to provide credentials to run its client with. I did some googling and looks like [CreateProcessWithLogonW](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createprocesswithlogonw) might be the function that it's using under the hood.

**Comment by rustdesk** [comment]
Thanks, i will check

**Comment by rustdesk** [comment]
> 企业windows用户都是user，DC管理下的用户运行rustdesk，远程进去后，rustdesk不能升级windows 特权，不会弹出windows管理员的验证窗口，我想问ruskdesk有没有解决这个问题进度。

**Comment by schleyk** [comment]
> In teamviewer when asked for id and password you can insert windows credential instead. those credential are passed from the client to the remote machine server that once receive them restart itself with those credential.

![image](https://user-images.githubusercontent.com/17356113/176906417-b79e1a7a-0f8d-46a4-bcbc-c5353d80910f.png)

**Comment by lasselin** [comment]
Hi,
Same issue here. It makes it useless when the remote user is not admin.
So it would be a nice feature for Rustdesk.
Thanks in advance.
Best regards,

**Comment by bilogic** [comment]
I recall Teamviewer portable being able to control admin apps without asking for UAC, did I remember correctly? 
I meant to ask: how did they do it?

**Comment by kintaro1981** [comment]
They are doing it in the way @schleyk said.

From the client you can choose to authenticate with the "generic" password generated from the server or with "windows authentication" in this way who give support insert local admin credential and click on log on. After this teamviewer server restart it self and launching it self  with the credential provided from the client (like a runas), at this point the client once connected to the server can see and interact with UAC.

**Comment by bilogic** [comment]
Actually I just tested again, TeamviewerQS did request for UAC, that is probably why they are able to control all windows.
Perhaps RustDesk can do the same.

**Comment by kintaro1981** [comment]
@bilogic TeamviewerQS ask yes/no when it restart it self after the client send the administrative credentials by TV authentication (see @schleyk message here: https://github.com/rustdesk/rustdesk/issues/70#issuecomment-1172364732).

If you launch it from a limited user it don't request for UAC and in this case if you connect to it with "standard tv authentication" (id and tv password) you can't interact with UAC.

**Comment by PacGyver** [comment]
Supremo and PC Visit are able to pass the UAC while launched as standard User. PC Visit is even more advanced, as it is able to ask the remote User for credentials. Dont know how it is actually working, but I think:
"someone" entering administrative credentials
These are used to spawn a New process
UAC getting up for the remote User, but He doesnt have to input anything, just yes/no Dialog.
The New process is elevated.
Dont know if it is able to restart the rustdesk Session directly or of it is  Necessary to create a Service first.

**Comment by mnaiman** [comment]
Hi @rustdesk - this is really great software and I agree that ability to control UAC is important. Even for portable version (only reason why Im using TeamViewer now :/).

If I start portable version using this command 
`PsExec64.exe -sid RustDesk.exe`
Im able to control UAC with portable version.
PsExec is Microsoft tool to run process as SYSTEM.
So clearly it doesn't need to service be installed (portable version).

What's need to be implemented 
1. manifest to need to be run as elevated https://learn.microsoft.com/en-us/cpp/security/how-user-account-control-uac-affects-your-application?view=msvc-170
2. only elevated process (as admin will be able to ask for SYSTEM rights) - standard user process will not be able
3. in code impersonate to SYSTEM account when there is active connection for example using this sequence of API calls https://github.com/tobiohlala/ImpersonateSystem/blob/master/ImpersonateSystem.psm1

**Comment by rustdesk** [comment]
@21pages is working on this

**Comment by rustdesk** [comment]
> AnyDesk has option to provide credentials to run its client with. I did some googling and looks like [CreateProcessWithLogonW](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createprocesswithlogonw) might be the function that it's using under the hood.

It is useless, even we call it, there is still a UAC window poped out though no need to input account/password, but still need to wait for clicking from host user.

**Comment by PacGyver** [comment]
> > AnyDesk has option to provide credentials to run its client with. I did some googling and looks like [CreateProcessWithLogonW](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createprocesswithlogonw) might be the function that it's using under the hood.
> 
> It is useless, even we call it, there is still a UAC window poped out though no need to input account/password, but still need to wait for clicking from host user.

Commercial ones are acting the same and i think this is one Part of handling the UAC properly. For on demand Support this is no problem.

**Comment by rustdesk** [comment]
Close this because we can support remotely input user/password, but UAC windows is still popped out, it does not help much.

**Comment by rustdesk** [comment]
try out tomorrow's nightly build please, though still require host user input user/password

**Comment by rustdesk** [comment]
in the future we can also provide a version like TeamviewerQS  which always require uac when you open it.

**Comment by rustdesk** [comment]
> in the future we can also provide a version like TeamviewerQS which always require uac when you open it.

@21pages add it into nightly ci please

**Comment by neogalaxy88** [comment]
> in the future we can also provide a version like TeamviewerQS which always require uac when you open it.

for me the best way is like Anydesk: when necessary the operator requests administrative privileges with the possibility of entering  by the user or by operator

**Comment by kintaro1981** [comment]
It is going to be good enough. Usually you are in contact with the remote user (text or voice). The solution is to ask to click on “yes”.

**Comment by schleyk** [comment]
With TeamViewer / AnyDesk, the user also receives a UAC message which the person in front of the screen must confirm with "Yes" and TeamViewer / AnyDesk starts as admin.

Afterwards, it is possible to run applications as administrator and enter the password via remote control.

**Comment by rustdesk** [comment]
So, this issue is for the case the host is not the administrator, but the remote user is the administrator?

**Comment by kintaro1981** [comment]
The host doesn’t know the local administrator password (and doesn’t have to know it). The remote user knows host’s local credentials  password.

**Comment by rustdesk** [comment]
Idea here
> pop up something like this
> 
> ![57f8c14946ce5b3313f82d06cf3795d](https://user-images.githubusercontent.com/71636191/202371151-2456ae5f-57fb-4559-bd7a-8d09acc636ea.png)
> 
> account/password is sent to host and invoke [CreateProcessWithLogonW](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createprocesswithlogonw) to run portable service and elevate to wait for host user click yes (UAC) only.

**Comment by kintaro1981** [comment]
Exactly the remote user once connected or before sending rustdesk password send windows username and password (usually admin credentials of the host) and the remote host rustdesk restart it self with those credentials (if valid). At that point UAC is going to ask "yes or no" to the host. This is the best can be archived without installing rustdesk, and is how are working anydesk/teamviewer.

I can't remember is anydesk/teamviewer maintain those admin credential in cache during the session so the host can be remotely restarted and the remote user can re-connect without host's user interaction after the reboot.

**Comment by rakleed** [comment]
@rustdesk a few ideas on how to improve the UX of this feature:
1. Request elevation can be done at any time while I am connected to the host. (TeamViewer only allows me to do this when connected, which is very inconvenient.)
2. If a UAC window appears on the host, then RustDesk should detect this and offer a window requesting for elevation. (This is how AnyDesk can do it.)
3. If I want to transmit the administrator username and password, then I can choose from a list of predefined names. (I can do this in [Zoho Assist](https://help.zoho.com/portal/en/kb/assist/user-guide/troubleshooting/articles/troubleshooting-run-as-service#:~:text=How%20does%20the%20elevation%20process%20work%3F), and it's handy since I can't get the computer name/domain and username wrong.)
4. When transmitting the username and password, if I entered the password incorrectly, then display a hint next to the password or popup, but then allow me to immediately re-enter the password. (AnyDesk closes the request elevation window, and every time I fail to enter a password, I have to re-do the request elevation, which is inconvenient.)

It would be great if you could implement these improvements in the future.

**Comment by rustdesk** [comment]
> 3\. If I want to transmit the administrator username and password, then I can choose from a list of predefined names. (I can do this in [Zoho Assist](https://help.zoho.com/portal/en/kb/assist/user-guide/troubleshooting/articles/troubleshooting-run-as-service#:~:text=How%20does%20the%20elevation%20process%20work%3F), and it's handy since I can't get the computer

where are they prededined? some picture please. @rakleed

**Comment by qaqz111** [comment]
When the nightly1.2 starts as admin on remote host, the client still can not click UAC window remotely, while Teamviewer/AnyDesk/ToDesk can.

So can the operation of clicking elevate on host be skipped while rustdesk started as admin on host like the others do?

**Comment by rakleed** [comment]
> > 3. If I want to transmit the administrator username and password, then I can choose from a list of predefined names. (I can do this in [Zoho Assist](https://help.zoho.com/portal/en/kb/assist/user-guide/troubleshooting/articles/troubleshooting-run-as-service#:~:text=How%20does%20the%20elevation%20process%20work%3F), and it's handy since I can't get the computer
> 
> where are they prededined? some picture please. @rakleed

@rustdesk [here](https://help.zoho.com/portal/en/kb/assist/user-guide/general/articles/run-as-service#Local__Domain_Admin_User_Authentication) the first screenshot is from Windows 7, and the second screenshot is from Windows 10 and newer. It is important that this window is called on the host, and not through the interface on the remote computer, so I do not know if it can be done at all in your case.

I don't know Terminal Session is the same (what [@WhiteAls](https://github.com/rustdesk/rustdesk/issues/70#issuecomment-1384174445) wrote about), but I would like to see a similar interface in RustDesk.

**Comment by qaqz111** [comment]
> > When the nightly1.2 starts as admin on remote host, the client still can not click UAC window remotely, while Teamviewer/AnyDesk/ToDesk can.
> 
> Make sense, @21pages

It's great to see this has been implemented, thanks for your work!

**Comment by Dittos-Glove** [comment]
> > > When the nightly1.2 starts as admin on remote host, the client still can not click UAC window remotely, while Teamviewer/AnyDesk/ToDesk can.
> > 
> > 
> > Make sense, @21pages
> 
> It's great to see this has been implemented, thanks for your work!

I'm probably doing something wrong. But whatever was implemented doesn't seem to be working for me. I still am unable to see the popup when I remote into a users computer.

**Comment by TGeRi** [comment]
Any update on this? A Rustdesk-client-side button "request UAC" would be nice. One time the user would have to click YES on the UAC window on the host machine and after that we could click with elevated privilages? Now for example if I want to uninstall an app from appwiz remotely I have to ask te user to click through all buttons as I cannot click with Rustdesk. :(

**Comment by technomancer-101** [comment]
@rustdesk was this feature removed due to the antivirus issues?
I understand that the client cannot interact with the UAC prompt directly, but from my understanding, @21pages made it so the portable client would send a prompt for escalation. That doesn't seem to be happening from what I've tested so far.

**Comment by 21pages** [comment]
not removed.
> That doesn't seem to be happening from what I've tested so far.

Not seen this or not seen rustdesk elevation prompt in the controlled side?
![1686267466552](https://github.com/rustdesk/rustdesk/assets/14891774/4da1b4db-f3d1-475f-a0a3-16c4c78af693)

**Comment by technomancer-101** [comment]
> Not seen this or not seen rustdesk elevation prompt in the controlled side?

Not seeing either. When I click on something that needs admin rights, UAC pops up on the host end asking for credentials (which the host doesn't have) and the remote side freezes until the UAC prompt is closed again. Is there a setting or a specific build I need to be running?

**Comment by 21pages** [comment]
> > Not seen this or not seen rustdesk elevation prompt in the controlled side?
> 
> Not seeing either. When I click on something that needs admin rights, UAC pops up on the host end asking for credentials (which the host doesn't have) and the remote side freezes until the UAC prompt is closed again. Is there a setting or a specific build I need to be running?
> 

no specific settings, what about using request elevation in the remote action menu ?

**Comment by technomancer-101** [comment]
Sorry, apparently I need more coffee. Was still running 1.19 on my test computer...
Installed 1.20 and all is good now. Thanks for the help

**Comment by cody151** [comment]
I'm on 1.2.1 and UAC is completely broken. RustDesk can't handle it and just freezes?? Any ideas how to fix this?? I have set to full permissions and full access in settings and yet still it crashes when a UAC prompt appears.

**Comment by cody151** [comment]
Completely unusable at the moment??? How do I fix this? UAC request keeps crashing the desktop app!!

**Comment by cody151** [comment]
> > no specific settings, what about using request elevation in the remote action menu ?
> 
> 
> 
> Sorry, apparently I need more coffee. Was still running 1.19 on my test computer...
> 
> Installed 1.20 and all is good now. Thanks for the help

How did u prevent the desktop app from crashing when there is UAC elevation??

**Comment by 21pages** [comment]
server side crashed? Here is something you can help:
1. show the recent log file in `%appdata%/RustDesk/log/` 
2. show its content of today's log file in `%appdata%/RustDesk/log/portable-service` if it exists.
3. upload the dmp files in `%localappdata%\CrashDumps` if it exists.
