### ISSUE TITLE
devcontanier init debian apt update connection error

### ISSUE THREAD

**Issue by Kambaa** [rustdesk/rustdesk#7002]
### Bug Description

When i tried to initialize the project via dev containers, there was a problem about not connecting to debian servers

`E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

There's no problem if you have previously do this(because of caching), but i think there's some rate-limiting involved when running apt update. Could you please check and edit so that update checks are done with apt-get? (changing this made this error go away for me)

### How to Reproduce

Try to initialize devcontainer(without caching of course)

### Expected Behavior

devcontainer link on the main github page should work every time you click it, i think first time is more important for setting up.

### Operating system(s) on local side and remote side

Win 10 > Win 10

### RustDesk Version(s) on local side and remote side

latest

### Screenshots

![resim](https://github.com/rustdesk/rustdesk/assets/5601326/d75c28f4-89df-4dbc-a6d5-9d0a156dec7d)

**Comment by rustdesk** [comment]
#764
