### ISSUE TITLE
Save Direct Connections

### ISSUE THREAD

**Issue by bebeidon** [rustdesk/rustdesk#701]
When I use the direct IP connection, the connection will not be saved afterwards in "last connections". Only when I connect via ID it will show it there.

...

Is this the expected behaviour or is there another way of saving the direct connections? And are direct connections always unencrypted?

...

I installed the latest release 1.1.19 with the installer on Win11 machines.

---

**Comment by rustdesk** [comment]
@Kingtous take care of this in Flutter migrating project.

**Comment by grummbeer** [comment]
solved. can be closed

@bebeidon try the nightly version https://github.com/rustdesk/rustdesk/releases/tag/nightly
![rustdesk-ip-connect-recent-sessions](https://user-images.githubusercontent.com/67791701/214425343-a6bb0e47-3e7f-49ad-998c-1119d299a34d.png)
