### ISSUE TITLE
Major rustdesk public network outage

### ISSUE THREAD

**Issue by jamiegau** [rustdesk/rustdesk#7023]
### Bug Description

I have been unable to connect to the majority of my sites for the last 3-4 days.
occasionally, if I hit reconnect many times it will work, but on some sites, I have tried for 5-10 min and will not connect.

This morning, as I try to connect every morning, to see if the situation has improved, I am  getting a new error
```
Connection error
Failed to connect to rs-ny.rustdesk.com:21116: Please try later
```
Can we please get an update on what's happening and a timeframe for rectification?  Otherwise, I will have to abandon rustdesk for an alternative.  I don't want to have to do that.

### How to Reproduce

Attempt to connect to any computer.

### Expected Behavior

It works as expected.

### Operating system(s) on local side and remote side

windows 11/MacOX -> W-server2022, W10

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

none needed

### Additional Context

I am looking to utilise my own server to get around this for now, but this breaks an essential requirement in that I use this to allow external agents to get in for support issues when required.  Having them have to setup the network server and relay agent hosts in the software to connect to different sites is not workable.

**Comment by DavidMR91** [comment]
Same here
