### ISSUE TITLE
Rustdesk 1.2.3 Delayed Input After Installing System Service

### ISSUE THREAD

**Issue by whiskeytangofoxy** [rustdesk/rustdesk#7024]
### Bug Description

After installing Rustdesk as a system service on v1.2.3 on Mac (via rustdesk-1.2.3-aarch64.dmg), I am experiencing severe input delay that sometimes results in incorrect inputs and unexpected behavior.

### How to Reproduce

1. Remove Rustdesk application and service
2. Download rustdesk-1.2.3-aarch64.dmg
3. Drag Rustdesk to Application folder
4. Run Rustdesk
5. Enable service (but do not install)
6. No input delay; runs great
7. Now install system service and restart Rustdesk
8. Massive input delay (from Win11 connected host to the Mac guest) and unexpected input behavior (e.g., sometimes alt or command keys are input in combination with keys pressed, even though said keys are not being pressed on host)

### Expected Behavior

There should not be an increase in input delay after install the Rustdesk system service.

### Operating system(s) on local side and remote side

Windows 11 -> MacOS 14.2.1

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

No applicable screenshots.

### Additional Context

Self-hosted (never had an issue until installing system service). Note that the stream itself is not delayed (4-12ms range), just inputs via keyboard.

**Comment by adamency** [comment]
When did this issue occur exactly ? Are you everything is set up correctly for self-hosting ? Cause Rustdesk is currently being DDOS-ed #7027 and maybe this is the cause of your delay, if somewhere in your setup something is trying to connect to their servers.

**Comment by mimkisa** [comment]
please someone share with me his server id, relay server API server key

**Comment by rustdesk** [comment]
Possibly related to https://github.com/rustdesk/rustdesk/pull/7319. Could you try out the nightly build?

**Comment by rustdesk** [comment]
close since no response

**Comment by fufesou** [comment]
@DragunityMAX Thanks for your feedback.

I tried 1.3.1 and the latest nightly build on the controlled side, but could not reproduce this issue.

Could you please give more details and test

1. Which versions did you use on both sides?

2. Give a screenshot of the keyboard settings.

<img width="300" alt="a" src="https://github.com/user-attachments/assets/215c8c4b-53d9-4a78-8faf-ffb9cabd2533" >

3. What app did you use to test the input?

4. Is there a special keystroke that triggers this issue? Or is it just random?
 
5. Test the "Legacy mode" and "Map mode", to check if both modes has this issue?
