### ISSUE TITLE
PSA - RUSTDESK IS DOWN: DDOS on Rustdesk Public Servers => Non-Selfhosted Rustdesk does NOT work currently

### ISSUE THREAD

**Issue by adamency** [rustdesk/rustdesk#7027]
# Rustdesk have [reported being DDOS-ed](https://twitter.com/rustdesk/status/1752733206174945687) at the moment on their public servers and the entire service seems to be down.

### More Information

Here are where discussions are taking place:

[Tweet reporting the DDOS](https://twitter.com/rustdesk/status/1752733206174945687) (posted 31/01/2024 16:38:00 UTC i.e 7h ago now)
[Current Discussion](https://github.com/rustdesk/rustdesk/discussions/7008)

[Old Discussion but people still commenting now](https://github.com/rustdesk/rustdesk/discussions/5538)

### Solutions

The only solution currently reliable is to self-host your own Rustdesk server.

---
&nbsp;

PS: PLEASE DO NOT CREATE MORE ISSUES ON THIS TOPIC

**Comment by Bibek9111** [comment]
Has this been fixed yet?

**Comment by Mingggzzzx** [comment]
Still down as of post.

**Comment by gmhall506** [comment]
Can anyone comment about why this would affect a self-hosted server?

**Comment by BentHaase** [comment]
> Can anyone comment about why this would affect a self-hosted server?

Would not affect your server if all your clients are properly configured.

**Comment by cyber-sec0** [comment]
Waiting...

**Comment by adamency** [comment]
@cyber-sec0 and others passing by

## please do not comment if you have no information to provide

These comments serves nothing except even more cluttering information.

**Comment by MichaelUray** [comment]
Since it is not an issue with the server software itself, such an issue should actually get reported there:
https://github.com/rustdesk/uptime/issues

**Comment by engerex** [comment]
The shuttle was in "ready" status several times during the day. But this only lasted a few seconds.

**Comment by engerex** [comment]
"Ready"

**Comment by adamency** [comment]
@MichaelUray Maybe, but it is obvious that far more people go check here, and that almost no one would see the information if it only was there. I wasn't even aware of such repository. So I'd say it is better to leave this issue here.

I also believe another github repository for dealing with uptime of an already existing repository isn't a good solution and that it only exists because github doesn't provide a way to indicate uptime of service (because a git repository isn't meant to represent a service originally). Some information about the downtime should be visible here IMO.

**Comment by KoalaBear84** [comment]
I didn't knew about it earlier, it was created two months ago.

I'll defend the splitting in another repository. You don't want uptime information in your code repository as its only clutter and not code. It will get in the way of everything, when making code branches, you will always get conflict or have to update code every time.

**Comment by adamency** [comment]
@KoalaBear84 No you don't understand. Tracking files in a repository for reporting uptime is not the way at all. We simply should be able as the maintainer of a repository to display real-time information about the service on the github page of our repo. Just like the description of the repo, **which is not code in the repo**. That's the way to go.

**Comment by cosminmocan** [comment]
How can we help?

**Comment by polygonnedpotato** [comment]
is there a way i can just connect directly via ip?
