### ISSUE TITLE
Upgrade flutter to v3.16

### ISSUE THREAD

**Issue by ZorinFoss** [rustdesk/rustdesk#7034]
### Bug Description

Hi,

Please upgrade flutter to v3.16.x

This version has a significant graphics features specially on linux. (The app start much faster now)

### How to Reproduce

- Install `RustDesk` on `ArchLinux`.
- Open the app.
- App take some time before launch.

### Expected Behavior

- App launcher start faster. 

### Operating system(s) on local side and remote side

ArchLinux

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

[test.md](https://github.com/rustdesk/rustdesk/files/14135238/test.md)

**Comment by rustdesk** [comment]
Thanks, we have the plan.
