### ISSUE TITLE
Rustdesk not working when connected screen is turned off

### ISSUE THREAD

**Issue by hatl** [rustdesk/rustdesk#7037]
### Bug Description

When connecting to a Linux PC with which has a monitor attached that's powered-off, I get: "Remote Error" "No Display"

### How to Reproduce

Start rustdesk.
Remove power cable from monitor.
Try to connect --> error

### Expected Behavior

Connection is working

### Operating system(s) on local side and remote side

Ubuntu 23.10 -> Ubuntu 23.10

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

Error message:
![image](https://github.com/rustdesk/rustdesk/assets/70505/13f5ecb2-9d2a-410a-8f84-792fcbe55ca6)

Working connection via x11vnc:
![image](https://github.com/rustdesk/rustdesk/assets/70505/e0358eb8-a249-4713-ba40-44454a97ce62)

### Additional Context

The corresponding X11 screen exists and should be used by rustdesk.

xrandr output:

```
Screen 0: minimum 8 x 8, current 3840 x 2160, maximum 32767 x 32767
DVI-D-0 disconnected (normal left inverted right x axis y axis)
HDMI-0 disconnected primary (normal left inverted right x axis y axis)
DP-0 disconnected (normal left inverted right x axis y axis)
```

---

The same use case works, when using x11vnc - while using the existing screen `:0` (see screenshot)
You can even see that rustdesk is running when connecting via vnc

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4296

**Comment by rustdesk** [comment]
This is not vnc

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/7032

**Comment by hatl** [comment]
I did some analysis:
seems like the screen should be part of the iterator: https://github.com/rustdesk/rustdesk/blob/c97cc15c0eaeffe98958cc405fb7020af674785d/libs/scrap/src/x11/iter.rs#L20

I've created a minimum example to show that the screen is actually available:

```C
#include <stdio.h>
#include <stdlib.h>
#include <xcb/xcb.h>

int main(void) {
    /* Establish a connection to the X server */
    xcb_connection_t *connection = xcb_connect(NULL, NULL);
    if (xcb_connection_has_error(connection)) {
        fprintf(stderr, "Error: Cannot open display\n");
        exit(1);
    }

    /* Retrieve the setup data */
    const xcb_setup_t *setup = xcb_get_setup(connection);
    if (!setup) {
        fprintf(stderr, "Error: Cannot retrieve setup information\n");
        xcb_disconnect(connection);
        exit(1);
    }

    /* Use xcb_setup_roots_iterator to iterate through screens */
    xcb_screen_iterator_t iter = xcb_setup_roots_iterator(setup);
    int screen_num = 0;

    for (; iter.rem; xcb_screen_next(&iter), screen_num++) {
        xcb_screen_t *screen = iter.data;
        printf("Screen %d: %dx%d\n", screen_num, screen->width_in_pixels, screen->height_in_pixels);
    }

    /* Clean up and close the connection */
    xcb_disconnect(connection);
    return 0;
}
```

compile using:
```bash
gcc -o list_screens list_screens.c $(pkg-config --cflags --libs xcb)```
```

this prints:
`Screen 0: 3840x2160`

---

Maybe the issue is somewhere here?
https://github.com/rustdesk/rustdesk/blob/c97cc15c0eaeffe98958cc405fb7020af674785d/libs/scrap/src/common/x11.rs#L89-L93

**Comment by aki42** [comment]
Thanks a lot for your bug report - otherwise I never would have thought that the (sort of) solution to this problem really can be to turn on the monitor of the machine I want to control remotely. Of course this is no real solution because that monitor now consumes power without any use than to avoid the "Remote Error"/"No Display" errors. But the connection works at least. Really astonishing this bug got closed though you even provided demo code and a hint regarding where the code looking for displays might fail. :shrug:

**Comment by hatl** [comment]
I was also quite surprised.
I still think this should be easily fixable (without turning the monitor on).

**Comment by cubicYYY** [comment]
#6682

**Comment by petesimon** [comment]
is this actually solved or not?

**Comment by hatl** [comment]
just tested using Rustdesk 1.4.1 - still not working

**Comment by bludash** [comment]
Still not working.

**Comment by rvsh2** [comment]
Check this:
https://github.com/rvsh2/rustdesk-no-monitor-fix
