### ISSUE TITLE
Single click on local side becomes double click on remote side when using an iphone to control an android phone.

### ISSUE THREAD

**Issue by YangDongwen** [rustdesk/rustdesk#7046]
### Bug Description

When using iphone to control an  android phone, single click in local becomes double click in remote. For example, when I tried to type a "hello", I got a "hheellloo" in android. 

### How to Reproduce

Using an iphone to control an android phone.

### Expected Behavior

A single click in iphone produce a single click in android rather than a double click.

### Operating system(s) on local side and remote side

IOS 16.6.1 -> android 9

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.3-2

### Screenshots

![微信图片_20240203153014](https://github.com/rustdesk/rustdesk/assets/37059002/df356bee-fba9-4cc6-bf93-a65bad0426ad)

**Comment by rustdesk** [comment]
fixed in nightly build.
