### ISSUE TITLE
Missing libraries in doc.rustdesk.com (Ubuntu 18) build

### ISSUE THREAD

**Issue by PJaros** [rustdesk/rustdesk#7058]
### Bug Description

The installation for the required libraries for Ubuntu on https://github.com/rustdesk/doc.rustdesk.com/blob/master/content/dev/build/linux/_index.en.md are different from the one on https://github.com/rustdesk/rustdesk says.

Mainly the libraries:
 - libgstreamer1.0-dev
 - libgstreamer-plugins-base1.0-dev

are missing.

The doc.rustdesk says (space added and backslash marks removed trying to make it easier to compare) :
```bash
sudo apt install -y     g++ gcc git curl wget nasm yasm libgtk-3-dev clang libxcb-randr0-dev libxdo-dev libxfixes-dev libxcb-shape0-dev libxcb-xfixes0-dev libasound2-dev libpulse-dev cmake
```
Readme.md on main github rustdesk repo says:
```bash
sudo apt install -y zip g++ gcc git curl wget nasm yasm libgtk-3-dev clang libxcb-randr0-dev libxdo-dev libxfixes-dev libxcb-shape0-dev libxcb-xfixes0-dev libasound2-dev libpulse-dev cmake make libclang-dev ninja-build libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
```

### How to Reproduce

Compiling without the two libraries fails `libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev` fails. Which was also reported in issue https://github.com/rustdesk/rustdesk/issues/2881

### Expected Behavior

The build instructions should be up to date with the latest changes on the main repository.

### Operating system(s) on local side and remote side

Compiling on Ubuntu 18(.04)

### RustDesk Version(s) on local side and remote side

Tested with 1.2.3 and nightly-2024-02-05

### Screenshots

Irrelevant

**Comment by rustdesk** [comment]
#763

**Comment by PJaros** [comment]
I **did** follow the tutorial https://rustdesk.com/docs/en/dev/build/linux/ to the letter. It is not up to date.

The two libraries:
 - libgstreamer1.0-dev
 - libgstreamer-plugins-base1.0-dev

are missing in the documentation.

Is there a documentation on how to change the documentation myself? Do I need to fork the repository and change every language version myself?
