### ISSUE TITLE
Connecting from Ubuntu 18(.04) with nightly compile (2024-02-05) to Windows 10 1.2.3 doesn't send keyboard press

### ISSUE THREAD

**Issue by PJaros** [rustdesk/rustdesk#7059]
### Bug Description

Using the Ubuntu 18(.04) with nightly compile (2024-02-05) connects to the a Windows 10 machine running with RustDesk 1.2.3 but won't transmit keypresses

### How to Reproduce

Compile RustDesk nightly for Ubuntu 18(.04) and install RustDesk 1.2.3 on a Windows 10 Machine. Run RustDesk on both sides and connect from Ubuntu to the Windows 10 machine. Everything will work but the keypresses.

### Expected Behavior

The keypresses should be transmitted. Everything works as soon as RustDesk 1.2.3 is compiled on the Ubuntu side.

### Operating system(s) on local side and remote side

Local: Ubuntu 18(.04), Remote: Windows 10

### RustDesk Version(s) on local side and remote side

Local: Nightly-2024-02-05, Remote: 1.2.3

### Screenshots

Irrelevant

**Comment by rustdesk** [comment]
tracekd by https://github.com/rustdesk/rustdesk/issues/3565
