### ISSUE TITLE
Autotype / virtual keypress not working

### ISSUE THREAD

**Issue by ramon-kramer-flashtec** [rustdesk/rustdesk#7079]
### Bug Description

When using typing functions like Auto-type in KeePass or AutoKey, the virtual keypresses are not working. I tried KeePass XC (Linux & Windows) and also Autokey on Linux with every keyboard mode of RustDesk and both directions.

### How to Reproduce

Install KeePass, create a Password and use Autotyping Feature into the RustDesk Window.

### Expected Behavior

RustDesk should accept the virtual keypresses.

### Operating system(s) on local side and remote side

Ubuntu 22.04 ,18.04 > Windows 10, 11, Server 2019 / Windows 10, 11 > Windows 10, 11, Server 2019

### RustDesk Version(s) on local side and remote side

1.2.3 > 1.2.3

### Screenshots

[windows-11-pro-screen0.webm](https://github.com/rustdesk/rustdesk/assets/45063643/c7b44c13-1059-4d17-a864-285f790d25df)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by TheRealHoobi** [comment]
I've tested all keyboard settings using KeePass2, KeePassXC and [ClickPaste](https://github.com/Collective-Software/ClickPaste).

- Global Hotkeys works only using keyboard settings > input source 2. 
- KeePass2 native autotype feature not working. With [Advanced AutoType](https://github.com/rookiestyle/advancedautotype)  plugin and keyboard set to input source 2, autotype works.
- KeePassXC native autotype kinda-work in input source 2 mode. It's not typing username and password, but uses TAB key.
- ClickPaste works almost everytime with point&click (exception was MapMode & Forms.SendKeys).
