### ISSUE TITLE
Android 14 (xiaomi hyperOS)

### ISSUE THREAD

**Issue by davoodice** [rustdesk/rustdesk#7081]
### Bug Description

connection from Windows to an Android device for the first time is OK, but Windows is stuck on the "waiting for image "message for the second time. 
on my old phone samsung A20 it works perfectly.
![Screenshot 2024-02-07 193532](https://github.com/rustdesk/rustdesk/assets/68325902/4859f3fb-35fd-4834-85e3-482ef6b98fae)

### How to Reproduce

simply disconnect after first connecting and reconnect from windows.

### Expected Behavior

I expected to connect without any issues, 

### Operating system(s) on local side and remote side

win 11 > android 14 hyperOS Xiaomi

### RustDesk Version(s) on local side and remote side

1.2.3 > 1.2.3

### Screenshots

![Screenshot 2024-02-07 193532](https://github.com/rustdesk/rustdesk/assets/68325902/6c8def1d-077d-4018-ad1c-c386124cd5af)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893

**Comment by muba00** [comment]
FYI, This issue still exist
