### ISSUE TITLE
MacOS and Microsoft app language is wrong

### ISSUE THREAD

**Issue by elki00** [rustdesk/rustdesk#709]
**Describe the bug you encountered:**

Hello. Whether I install the app on MaOS or Windows it comes out in german only (that's where I am located)> Any possibility to change it in the configuration file? The app settings seem to have no options to switch to another language. Thx

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/541

**Comment by rustdesk** [comment]
As a workaround on Windows, you can modify `%APPDATA%\RustDesk\config\RustDesk_local.toml`,  add `lang="en"`  under [options].

On Mac, it locates under `$HOME/Library/Preferences/com.carriez.rustdesk/`

**Comment by mikkolukas** [comment]
> > recent-sessions-style = 'list'
> > lang = `en'
> 
> Thank you. I did it but nothing changed. still german. Do I have to replace some language file first?

You need to edit the file while the app is closed.

Also, it should be `lang = 'en'`, not lang = `en'

**Comment by grummbeer** [comment]
can be closed? also #541
