### ISSUE TITLE
Cannot install on a 64-bit Window 8 computer.

### ISSUE THREAD

**Issue by OuttaBody** [rustdesk/rustdesk#7090]
### Bug Description

I’m having a problem with installing rustdesk-1.2.3-x86_64 on a 64-bit Window 8 computer. 

On the installation screen, I put a check mark on all of the options below and click on “Accept and install” to continue with installation, but after a few seconds, the installation screen disappears without any confirmation that the installation was complete. And nothing gets copied into the installation path, I guess, because the installation is prematurely terminated for some reason.

✓ Create start menu shortcuts
✓ Create desktop icon
✓ Install RustDesk certificate

I thought it could be the antivirus program that may interfere with the installation. I temporarily turned off the antivirus, but it didn’t help. Any help and advice are greatly appreciated to install rustdesk-1.2.3-x86_64 in this 64-bit Windows 8 computer.

Thanks!

### How to Reproduce

You can reproduce the same problem by installing rustdesk-1.2.3-x86_64 in a 64-bit Windows 8 computer.

### Expected Behavior

After a few seconds, the installation screen disappears without any confirmation that the installation was complete. And nothing gets copied into the installation path.

### Operating system(s) on local side and remote side

Windows 8 64-bit

### RustDesk Version(s) on local side and remote side

rustdesk-1.2.3-x86_64

### Screenshots

N/A

**Comment by rustdesk** [comment]
#763
