### ISSUE TITLE
Remotly changing settings with disabled "Enable remote configuration modification"

### ISSUE THREAD

**Issue by XLC0** [rustdesk/rustdesk#7092]
### Bug Description

If "Enable remote configuration modification" is disabled your window gets grayed out while hovering with the mouse over it.
But youre able to use the tabulator remotly to modify settings. Thinking not realy a security issue, but should be fixed if possible.

### How to Reproduce

Remotly using tabulator in the open Rustdek main window.

### Expected Behavior

Tabulator should not usable within the open Rustdesk main window.

### Operating system(s) on local side and remote side

Win11->Linux

### RustDesk Version(s) on local side and remote side

1.2.3->1.2.3

### Screenshots

![grafik](https://github.com/rustdesk/rustdesk/assets/150535661/d32e1053-4bd5-4cb3-a3cf-7059bcba2870)

**Comment by tomasz1986** [comment]
I would add that you can actually use the mouse too if you move it over the window and click very quickly before it becomes greyed out.

**Comment by rustdesk** [comment]
a lot of duplicate about this.
