### ISSUE TITLE
OS password not always being filled in

### ISSUE THREAD

**Issue by marcatmadu** [rustdesk/rustdesk#7105]
### Bug Description

I noticed that when I make a connection to my Win 11 Pro computer (version 23H2) , which is running but locked, the login screen asking for the pssword is always being activated/shown, but in about 50% of the case the OS password that I filled in in rustdesk, is being filled in, resulting in seeing my desktop but in another 50% of the cases, the password field stays empty, waiting for the password. I really see no logic in when it works and when it doesn't works.

### How to Reproduce

make a connection to a Win11 Pro computer that is locked

### Expected Behavior

unlocked desktop computer

### Operating system(s) on local side and remote side

Win 11 Pro 22H2 --> Win 11 Pro 23H2 

### RustDesk Version(s) on local side and remote side

1.2.4 nightly both computers

### Screenshots

![2024-02-12 00_00_26-BOSKORLAPW022 - Remote Desktop - RustDesk](https://github.com/rustdesk/rustdesk/assets/137408223/688fa4c9-8db4-4e2a-9c3d-469fcc19db9b)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/918#:~:text=native%20os%20password%20auto%20input%20(e.g.%20windows%20credential%20provider%2C%20did%20this%20before)%2C%20currently%20we%20send%20key%20events%20to%20remote%20side.
