### ISSUE TITLE
unable to control my linux wayland machine from a windows machine

### ISSUE THREAD

**Issue by back-lacking** [rustdesk/rustdesk#7107]
### Bug Description

what the tin says
when i connect to my linux machine from my windows machine, i am unable to control my linux desktop. on the linux side, i have given the windows machine permission to use mouse and keyboard. when i try to go control from windows machine, nothing happens, no keyboard shortcuts go through, typing in any letters into my terminal doesnt work, clicking on any open windows doesnt work. 
Also tried installing from chocolatey (1.2.2 installer) and scoop (1.2.3 portable)
Windows client info
- Win10 22H2, Build 19045.3930
- Rustdesk 1.2.3, installer, installed using winget
Linux client info
- Fedora 38
- Gnome 44.8, Wayland
- Rustdesk 1.2.3 (RPM package from github releases)

### How to Reproduce

1. install up rustdesk on linux and windows clients
2. connect to linux (with wayland) from windows client
3. on linux machine, accept connection, and tick on "allow keyboard and mouse"
4. try to do things to linux machine from windows machine 

### Expected Behavior

be able to use my keyboard input on linux machine from windows machine. 

### Operating system(s) on local side and remote side

Windows 10 -> Fedora 38

### RustDesk Version(s) on local side and remote side

1.2.3 (from winget) -> 1.2.3 (RPM package)

### Screenshots

https://github.com/rustdesk/rustdesk/assets/86173810/5a538d58-55bd-4e37-bc08-833287e5367a

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by back-lacking** [comment]
> Try out nightly build, and make sure selinux is set correctly.
> 
> https://github.com/rustdesk/rustdesk/releases/tag/nightly https://rustdesk.com/docs/en/client/linux/selinux/

so, first on 1.2.3, i did the selinux guide on the docs. 
im now swapped over to the nightly build, just went to the nightly build section in releases, grabbed the rpm, and then installed it. 
the issue is still persistent. 
![image](https://github.com/rustdesk/rustdesk/assets/86173810/e1acd315-addb-42b5-b634-398e5a62049d)
this is the rust desk im currently using, do i need to go reapply the rule since i installed the se linux rules and then installed a new version of rustdesk?

**Comment by rustdesk** [comment]
No idea, our fedora 38 works well.

**Comment by back-lacking** [comment]
> No idea, our fedora 38 works well.
> 
> Could you try `setenforce 0` temporarily? If `setenforce 0` works, it will say we miss some rules in https://rustdesk.com/docs/en/client/linux/selinux/

shouldve added at the beginning of my issue, i was following the "[create a type rustdesk_t](https://rustdesk.com/docs/en/client/linux/selinux/#create-a-type-rustdesk_t)" instructions. i enabled the rules following the "[enable directly](https://rustdesk.com/docs/en/client/linux/selinux/#enable-directly)"
where do i run `setenforce 0`? is it a command i directly run from the terminal, or is it something i add onto the end of one of the rustdesk rule files (and then from there i recompile and reapply using the "enable directly" instructions)

**Comment by rustdesk** [comment]
https://www.man7.org/linux/man-pages/man8/setenforce.8.html

**Comment by back-lacking** [comment]
> https://www.man7.org/linux/man-pages/man8/setenforce.8.html

so... i think i have introduced an unforeseen variable into this. 
i very likely while testing earlier, the view mode under the keyboard icon was ticked on and i forgot to disable it, which seemed to block all keybaord input. im not sure exactly when i enabled it. 
![image](https://github.com/rustdesk/rustdesk/assets/86173810/c72cf38c-326f-405a-831b-f44a55fa7c39)
now its on map mode, keyboard and mouse input from windows machine now work
before i discovered this, i tried running `setenforce 0`, which didnt seem to work, as keyboard and mouse input (from windows machine) didnt work. i made the above realization, ticked off view mode and enabled map mode, and now it works.
