### ISSUE TITLE
[ rdp like] please add file copy & paste function support like rdp

### ISSUE THREAD

**Issue by congzhangzh** [rustdesk/rustdesk#712]
As title, this will be killer feature:)

**Comment by rustdesk** [comment]
already there，but for windows only, it is not enabled by default,
https://github.com/rustdesk/rustdesk/blob/master/src/ui/header.tis#L163

**Comment by rustdesk** [comment]
@fufesou need to change title here, `copy & paste file`

**Comment by fufesou** [comment]
> &

Ok.  BTW, dragging files is a similar implementation on Windows. Dragging files can be done after UI is refactored.

**Comment by rustdesk** [comment]
> Dragging

Ok

**Comment by congzhangzh** [comment]
cool:)
