### ISSUE TITLE
Replacement for dead link "https://rustdesk.com/blog/id-relay-set/"

### ISSUE THREAD

**Issue by grummbeer** [rustdesk/rustdesk#7126]
### Bug Description

The link for "Ready, For faster connection, please set up your own server" => "https://rustdesk.com/blog/id-relay-set/" is dead.

Is there an replacement? is it "https://rustdesk.com/docs/en/client/#configuring-rustdesk"?

### How to Reproduce

The link leads to the page https://rustdesk.com/pricing.html

### Expected Behavior

The link should lead to a corresponding destination.

### Operating system(s) on local side and remote side

all

### RustDesk Version(s) on local side and remote side

all

### Screenshots

not needed

**Comment by rustdesk** [comment]
I prefer pricing.html page. :(

**Comment by grummbeer** [comment]
:-) right

**Comment by grummbeer** [comment]
wait, should the link then not be directy "https://rustdesk.com/pricing.html"?

**Comment by rustdesk** [comment]
Yes, can change to pricing.thml in new code.

**Comment by grummbeer** [comment]
> new code.

bigger rewrite? Not replace in the current code?

**Comment by grummbeer** [comment]
just as a note / to collect


https://rustdesk.com/docs/en/manual/linux/#x11-required > https://rustdesk.com/docs/en/client/linux/#x11-required


https://rustdesk.com/docs/en/manual/linux/#login-screen >
https://rustdesk.com/docs/en/client/linux/#login-screen

**Comment by rustdesk** [comment]
I will add to nginx confi

**Comment by rustdesk** [comment]
Thanks, I also fix in code, https://github.com/rustdesk/rustdesk/commit/236687ae53eba002767af559217de5fc53364a94

Now, both old link and new link work.

**Comment by grummbeer** [comment]
I found the links because i fiddle around on the home page (due the "UX/UI" discussion), but your "new code" let me think you already have a rewrite in work. If so, i stop.

the most important thing is in fact the missing clear link to the settings. So it could placed to the left:
![home-links-2](https://github.com/rustdesk/rustdesk/assets/67791701/feaf87e7-6d2e-4821-b8db-c0b219e10297)

The message from left moved to bottom and remove this pinkish/redish background. The own implementation of this message could replaced with a SnackBar (https://api.flutter.dev/flutter/material/SnackBar-class.html) but not sure at the moment.

![message](https://github.com/rustdesk/rustdesk/assets/67791701/07efea09-ada0-45dc-8d8f-a3e56412f91b)

A further step could be removing the "tabs" in main window. If there is no good idea what placing in the title bar, then the tabs for just home and settings makes no sense (for me). could look this:


![settings-new-2](https://github.com/rustdesk/rustdesk/assets/67791701/99c3c463-fed0-456b-9510-04294c030ff1)

What do you think?

**Comment by rustdesk** [comment]
Looks strange to me.

**Comment by grummbeer** [comment]
> Looks strange to me. 

The three column layout for settings?

**Comment by rustdesk** [comment]
All

**Comment by grummbeer** [comment]
yeah

**Comment by grummbeer** [comment]
Wait … my intention is not to make the most beautiful interface, but to make the settings more accessible. A button/link labeled with "Settings" leaves no doubt that clicking on it will take you to the settings. The "three-dot" menu next to "ID" or the "hamburger" at the top right are not clear enough, that my motivation.

**Comment by rustdesk** [comment]
But you did so many things in above 3 pictures.

**Comment by rustdesk** [comment]
I still think you should have a poll about the "three-dot" menu if you think it is not obvious. I believe most of guys can find the settings because there is no guys asking me where is the settings.

**Comment by rustdesk** [comment]
No, you did not bother me. I also thought "three-dot" is not obvious enough when I designed it, but I could not find a better way to make it obivous and also beautiful.  Putting a "gear" icon there seems not look good.

**Comment by rustdesk** [comment]
I am considering to have new design since I am working on SaaS. In the new release, it will look like this, or put somewhere else.

![image](https://github.com/rustdesk/rustdesk/assets/71636191/c78f6ecf-eccb-43ed-abf5-3ebaecdc8f5d)

**Comment by grummbeer** [comment]
> I also thought "three-dot" is not obvious enough when I designed it, but I could not find a better way to make it obivous and also beautiful.

You did nothing wrong, and I understand how this view is growed.

The three-dot is context-dependent. Next to the "ID", it should open a menu corresponding to the "ID" or a deep link to the "Change ID" section in the settings. A "gear" would not be proper at this position, but proper next to a labeled link/button "settings" (to general settings page).

> Login

Yes, thats the well know position of User/Account/Login (with "user" icon, not "gear") action, including the avatar and name after you logged in. 

Let me think, i want not repeat my fails from past (babble a lot, doing less, fail on time and skills)

**Comment by rustdesk** [comment]
I have considered these, I may use in the future as we have more functionalities.

**Comment by grummbeer** [comment]
OK, thanks.

**Comment by grummbeer** [comment]
> UX/UI discussion

very very nice ideas, and indeed this kind of power tool to handle dozens of devices could be a major issue to sell more subscriptions to exactly these power users, because they earn with it. 
 
I'm just a hobby user for personal use, I don't make any money from it and I could care totally less about this project. But I care because I love it, even if I'm a noob, whether it's in flutter or rust. It's a shame that so few developers contribute to it … Developers where are you?

**Comment by rustdesk** [comment]
You are my hero. :)
