### ISSUE TITLE
Massive SELinux errors on Fedora-39

### ISSUE THREAD

**Issue by tuxmaster5000** [rustdesk/rustdesk#7164]
### Bug Description

After installing it the the system will show one SELinux error after the next. :(

### How to Reproduce

Simple only install it.

### Expected Behavior

Working app without massive SELinux alert messages.

### Operating system(s) on local side and remote side

Fedora-39

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

No

### Additional Context

SELinux alert log:
cat /var/log/audit/audit.log|grep rust > /tmp/alert.txt
[alert.txt](https://github.com/rustdesk/rustdesk/files/14319503/alert.txt)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4267
