### ISSUE TITLE
Single click leads to Double click on Touch mode

### ISSUE THREAD

**Issue by wopeizl** [rustdesk/rustdesk#7171]
### Bug Description

Env: 
Controller: ios  16.1 with rustdesk 1.2.3
Host: Macos catalina 10.15.7 with rustdesk 1.2.3
relay server: linux with rustdesk-server 1.1.9 and key enabled

bug:
On touch mode, the single click will trigger a double click, however on mouse mode it's ok

### How to Reproduce

Log on server via controller, on touch mode, the single click doesn't behave normal, it is double click. However on mouse mode it's ok.

### Expected Behavior

touch mode behave normal

### Operating system(s) on local side and remote side

ios 16.1 -> macos 10.15.7

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

xx

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by rustdesk** [comment]
unreproducable in master branch.

**Comment by wopeizl** [comment]
Very likely due to the IOS controller, since use Android controller instead then everything works perfect.

**Comment by sczhengyabin** [comment]
Same issue here 

Env:
Controller: ios 17.3.1 with rustdesk 1.2.2
Host: Android 1.2.3
relay server: linux with rustdesk-server 1.1.9 and key enabled

**Comment by CrazyBunQnQ** [comment]
Same issue here

Env:
Controller: iPhone 13 pro ios 15~17.5.1 with rustdesk 1.2.2
Host: Android 1.2.3
relay server: docker image rustdesk/rustdesk-server:latest-arm64v8(c841df87f2d7) and key enabled
