### ISSUE TITLE
Remote connection to ubuntu22.04 screen display abnormality 

### ISSUE THREAD

**Issue by xldistance** [rustdesk/rustdesk#7172]
### Bug Description

I have a normal screen display on Ubuntu 18.04 and an abnormal display on Ubuntu 22.04.

### How to Reproduce

Connecting remotely from windows to Ubuntu 22.04 on top of it keeps giving me this problem

### Expected Behavior

Normally only one screen should be displayed, and it is displayed normally

### Operating system(s) on local side and remote side

windows11 -> ubuntu22.04

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

![QQ截图20240218191127](https://github.com/rustdesk/rustdesk/assets/29418474/ba8ee349-4273-4f29-8287-f33f17311780)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by rustdesk** [comment]
This should be fixed in https://github.com/rustdesk/rustdesk/pull/6487, please try out the nightly build, https://github.com/rustdesk/rustdesk/releases/tag/nightly
