### ISSUE TITLE
Previously working connection now results in a black screen

### ISSUE THREAD

**Issue by GeorgeCiesinski** [rustdesk/rustdesk#7176]
### Bug Description

I have two machines that are connected on the same private network (One over wifi, one wired). Both machines are using Win 11 and are on the latest updates. 

In the past, i could easily connect to the host machine and everything seemed to work perfectly, however now I am finding that the image portion of the connection is just a black screen. When I move my mouse around the black screen, the cursor seems to change as if going over interactive elements on the screen. When observed on the host machine, the mouse is in fact moving. As far as I can tell, only the image is not working.  

### How to Reproduce

I am not sure how to reproduce this because it occurred when I updated Rustdesk to latest version on host and client machine. As far as I can tell, this behavior started after I updated. 

### Expected Behavior

The image from the host machine should be visible as it was in the past. 

### Operating system(s) on local side and remote side

Win 11 -> Win 11

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/7014211/93951533-7858-4fee-a306-e4ee378a915e)

### Additional Context

1) I checked my windows firewall settings and they seem to be unchanged, and still allowing all of the Rustdesk components. 
2) The Host machine has not had any new software such as antivirus/firewall software installed. It mostly just sits there and serves media over my host network.
3) My macbook running Rustdesk 1.2.2 is able to connect to the host machine without any issues as far as I can tell. 
4) I looked through the closed issues, but the only other black screen issues I found were from many years ago and didn't seem to have solutions to this issue.

**Comment by rustdesk** [comment]
can you try out https://github.com/rustdesk/rustdesk/releases/tag/nightly

**Comment by Bell-see** [comment]
> can you try out https://github.com/rustdesk/rustdesk/releases/tag/nightly?

我遇到了同样的问题，在看到这个issues后，尝试了这个版本，发现问题解决了。谢谢。
不知道提问者的问题解决了没😂

**Comment by Bell-see** [comment]
> can you try out https://github.com/rustdesk/rustdesk/releases/tag/nightly?

1.2.3-1 版本确实有BUG！大佬赶快去修BUG啦~

**Comment by cloudmaker97** [comment]
Had the same issue, i tried to install to the latest version without success, but the https://github.com/rustdesk/rustdesk/releases/tag/nightly build resolved the issue. Thanks for this great support!
