### ISSUE TITLE
Keyboard Input not transferred from Windows 11 to Windows 10

### ISSUE THREAD

**Issue by kristian** [rustdesk/rustdesk#7180]
### Bug Description

I compiled the latest RustDesk client from source (master branch) and used it to connect from a Windows 11 to a Windows 10 machine. I can use mouse input, however keyboard input is not being transferred to the client. Do you have any idea what could be the issue? With an older version of RustDesk I had compiled from source a couple of month ago, everything worked perfectly fine.

### How to Reproduce

Unknown yet

### Expected Behavior

Keyboard input works and is transferred to remote

### Operating system(s) on local side and remote side

Windows 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.4 -> 1.2.4

### Screenshots

No screenshots of no input ;)

**Comment by rustdesk** [comment]
#763

**Comment by 1loong** [comment]
I also encountered this problem, have you solved it?

**Comment by kristian** [comment]
> I also encountered this problem, have you solved it?

Unfortunately not 👎  seems there will be no support for self-built clients if something doesn‘t work…
