### ISSUE TITLE
RustDesk iOS - It’s too slow and prone to error to use the target android soft keyboard on the screen

### ISSUE THREAD

**Issue by plia7** [rustdesk/rustdesk#7185]
### Bug Description

I tried to use the remote soft keyboard of Android, but It's too slow and prone to errors to try to type on the target Android soft keyboard that’s on the target screen rather than sending the keystrokes from the client connecting iOS side native soft keyboard.

Other remote desktop apps including TeamViewer allow this without any problem. Here is an example for another remote desktop app that gives you the option to either use the target android soft keyboard on screen or the source ios soft keyboard:

https://imgur.com/a/m5OirEK

I believe that’s how it should be in RustDesk too. The way it is right now basically makes the keyboard input very difficult and extremely unreliable especially if facing with a less stable connection.

### How to Reproduce

When I connect to an Android target using RustDesk iOS app, the keyboard icon appears to be missing from the menu. It does show if I connect to a windows based target.

### Expected Behavior

Keyboard icon is showing/Native iOS soft keyboard should be allowed to be used just like other remote desktop apps

### Operating system(s) on local side and remote side

iOS, Android

### RustDesk Version(s) on local side and remote side

iOS app version 1.2.2

### Screenshots

No keyboard icon when connecting to mobile device:

![BBB25C38-A029-46B8-8A08-1ED789A1D4C0](https://github.com/rustdesk/rustdesk/assets/134864072/680cd046-0165-40a3-b475-340072fade9b)

For reference, here is the keyboard icon I’m talking about that shows if I connect to a Windows based target:

![6809AB38-0297-459A-8D4E-55F45DFC1A22](https://github.com/rustdesk/rustdesk/assets/134864072/230b557f-7037-4e0d-912d-6c640551f0aa)

Other remote desktop apps including TeamViewer allow this without any problem. Here is an example for another remote desktop app that gives you the option to either use the target android soft keyboard on screen or the source ios soft keyboard:

https://imgur.com/a/m5OirEK

### Additional Context

It's too slow and prone to errors to try to type on the target Android keyboard that’s on the screen rather than sending the keystrokes from the client connecting iOS side native keyboard. Other remote desktop apps such as TeamViewer allow this without any problem.

**Comment by rustdesk** [comment]
I will block you if you continue to create duplicate

**Comment by plia7** [comment]
> You will be blocked if you continue to create duplicate

What do you keep closing my issue then? This is a valid problem.
