### ISSUE TITLE
when the android screen is off , the remote connection cannot be established

### ISSUE THREAD

**Issue by zzqCh** [rustdesk/rustdesk#7203]
### Bug Description

when the android screen is off , remote connection cannot be established，but when you turn on the screen , remote connection can be established

当被控手机处于黑屏状态时，无法建立连接，但是当被控手机屏幕亮起来后（人工解锁），那么就可以建立连接

### How to Reproduce

1. turn on the screen , remote connection can be established
2. turn off the screen and after 10 minutes , remote connection can't be established
3. turn on the screen again, now the remote connection can be established

### Expected Behavior

when the android screen is off , remote connection can  be established

### Operating system(s) on local side and remote side

android miui13.0.10（android12）--->androind emui 10.0.0 （android 10）

### RustDesk Version(s) on local side and remote side

1.2.3-->1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/10181098/ec256734-78df-4438-a44d-e077281a6abc)

**Comment by rustdesk** [comment]
A lot of duplicate related to this.

**Comment by zzqCh** [comment]
> A lot of duplicate related to this.

can you give me some issue id?
