### ISSUE TITLE
Mac OS shortcut key problem

### ISSUE THREAD

**Issue by barisyild** [rustdesk/rustdesk#7221]
### Bug Description

After using RustDesk for a while, all the buttons start working like hotkeys and even if I disconnect and reopen the connection, the problem is not solved.

for example Q key opens notes application

### How to Reproduce

Connect to a Mac using the RustDesk app from a Windows machine for a while.

### Expected Behavior

The keyboard must not run a shortcut key.

### Operating system(s) on local side and remote side

Windows 11 -> OS X 14.3.1

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

Nothing

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by Qingnan7780** [comment]
I also have the same problem, which arises in the 1:1 mode. If traditional input methods are used, they will fail
