### ISSUE TITLE
Rustdesk 32Bit Version (rustdesk-1.2.3-x86-sciter.exe) Whitelist does not work correctly

### ISSUE THREAD

**Issue by wkoetz** [rustdesk/rustdesk#7222]
### Bug Description

I want to put 172.21.95.0/24 on the whitelist. Does not work and shows an error. The normal x64 Windows Version whitelist works as expected.

### How to Reproduce

Try to put 172.21.95.0/24 on the whitelist. Does not work and shows an error.

### Expected Behavior

Should work as 192.168.0.1/24

### Operating system(s) on local side and remote side

Windows 10 32 Bit

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

not necessary

**Comment by rustdesk** [comment]
32bit/64bit share the same code, except UI, no way not work.

**Comment by wkoetz** [comment]
Yes, problem solved. I had two IP ranges on the whitelist, separated with new line. This does not work in the 32Bit version. When I have only one range or separate it with a "," or ";" it works.

**Comment by wkoetz** [comment]
Problem solved
