### ISSUE TITLE
Sign rustdesk files failing in Windows x86_64

### ISSUE THREAD

**Issue by chris-notley** [rustdesk/rustdesk#7224]
### Bug Description

We have previously been able to sign the Windows installer with our code signing certificate.  Following the response from @deep-soft in issue #6549 it started working again now.

The Windows x86_64 job is now failing with the following error

```
Error: Action failed with error: Error: ENOENT: no such file or directory, scandir 'D:\a\rustdesk\rustdesk\flutter\build\windows\runner\Release'
```
(attaching an image in screenshot section too)

We can see the certificate imports successfully, but it can't find the files to sign by the looks of it.

In terms of modification, we have removed some self-signed jobs from the build file and made the changes identified in #6549.

### How to Reproduce

Run the nightly build with a code signing certificate and the following secrets defined:

```
WINDOWS_PFX_BASE64
PASSWORD
SHA1_THUMPRINT
```

### Expected Behavior

Signing to complete successfully.

### Operating system(s) on local side and remote side

Windows 11 -> CI

### RustDesk Version(s) on local side and remote side

Nightly as of 20240221

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/55881642/15c88610-d78a-4b64-bf9c-865a5efa1ab0)

**Comment by rustdesk** [comment]
#763

**Comment by deep-soft** [comment]
> The Windows x86_64 job is now failing with the following error
> ```
> Error: Action failed with error: Error: ENOENT: no such file or directory, scandir 'D:\a\rustdesk\rustdesk\flutter\build\windows\runner\Release'
> ```

use:
folder: ```./flutter/build/windows/x64/runner/Release/```

from this PR:
https://github.com/rustdesk/rustdesk/pull/7209
  or this commit:
https://github.com/rustdesk/rustdesk/commit/7b317619acdf26853e05c5e398f5bdc19fee776c

**Comment by chris-notley** [comment]
Thanks @deep-soft!
