### ISSUE TITLE
iOs keyboard and mac connexion

### ISSUE THREAD

**Issue by Hydro8** [rustdesk/rustdesk#7245]
### Bug Description

Hi
I want to use ios app with my mac but I have a problem with my ios french keyboard.

Letters are ok but signs and numbers are not the same between my ios french keyboard and my mac input. I don't know how to write number for example.

Do you know where the problem come from ?

Thanks

### How to Reproduce

Connect rustdesk iphone to a mac computer with french keyboard on both side.

### Expected Behavior

When typing on my ios keyboard, to have the same characters on my mac.
It works ok when I'm connecting my iphone to a windows computer.

### Operating system(s) on local side and remote side

iphone -> mac sonoma

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.4

### Screenshots

My keyboard looks like this on my iphone : 

![IMG_1584](https://github.com/rustdesk/rustdesk/assets/5537697/81fb7ab9-252d-4f14-8c96-85eea97d708d)

That's one is ok.

![IMG_1585](https://github.com/rustdesk/rustdesk/assets/5537697/0841e5b2-0ac3-4e86-b61d-ae7423b95eec)

When I use this one, here the result : 

`&é"'(§è!çà)=:;()€&@« :,?!’`

Some signs are ok but some not and I can't write numbers.

![IMG_1586](https://github.com/rustdesk/rustdesk/assets/5537697/644a86fa-40a3-407a-9114-db5f5c26925c)

When I use this one, here the result : 

`^${}#%^*+-_`<>$£¥•:,?!’`

For this one too some signs are ok but some not.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367
