### ISSUE TITLE
Scan out Trojans

### ISSUE THREAD

**Issue by hanxiang-li** [rustdesk/rustdesk#7250]
### Bug Description

name：Win64/HackTool.RustDesk.HgEATTwA
page：C:\Users\q1211\Downloads\rustdesk-1.2.3-1-x86_64.exe

### How to Reproduce

Download link: https://github.com/rustdesk/rustdesk/releases/download/1.2.3-1/rustdesk-1.2.3-1-x86_64.exe
Scan Trojans in 360 Security Center

### Expected Behavior

Trojan horse prompts should not appear

### Operating system(s) on local side and remote side

Windows11

### RustDesk Version(s) on local side and remote side

1.2.3-1

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/45918130/d41d7afa-2fef-47ab-bf74-3d7d72af4cdc)
![image](https://github.com/rustdesk/rustdesk/assets/45918130/5dd86444-d900-485f-8dc4-abf7f104d406)

**Comment by rustdesk** [comment]
I guess you know 360.
