### ISSUE TITLE
Still NO crtl+alt+del send button!

### ISSUE THREAD

**Issue by agithubber2** [rustdesk/rustdesk#7254]
### Bug Description

The server I'm truing to connect to has an ealier rustdesk version 1.1.9. I have NO idea , I've tried all buttons in my rustdesk version 1.2.3-1 to send  crtl+alt+del  to login to the server!!
Why on earth is there NO  crtl+alt+del  specific button in your app?!?? Thank you

### How to Reproduce

Try to connect to server having 1.1.9 version

### Expected Behavior

Specific button to send crtl+alt+del  to remote server

### Operating system(s) on local side and remote side

windows 11 -> windows server 2019

### RustDesk Version(s) on local side and remote side

1.2.3-1 --> 1.1.9

### Screenshots

![Clipboard01](https://github.com/rustdesk/rustdesk/assets/65526781/555f9061-bb02-4893-9162-ba360f3b1a3c)

**Comment by rustdesk** [comment]
It is determined by remote side, not by local side, please install 1.2.3-1 on remote side.

**Comment by agithubber2** [comment]
> It is determined by remote side, not by local side, please install 1.2.3-1 on remote side.

Sorry, you're wrong: if I connect using 1.1.9 I CAN connect. Good programming practice is to provide backword compatibily , at least in basic functions. But if you don't like to fix the issue , well, I'll have to stay on 1.1.9 on both sides. Thank you
