### ISSUE TITLE
Failed to run custom build on Debian for magnum-opus v0.4.0 and scrapv0.5.0

### ISSUE THREAD

**Issue by Warkann2** [rustdesk/rustdesk#727]
![Capture](https://user-images.githubusercontent.com/99244680/172403210-1423eb45-6a0e-4c67-9be3-dc605459fdbf.PNG)

I'm trying to build rustDesk with Cargo run but I get these 2 errors. However, I do have the VCPGK_ROOT environment variable. If anyone has the solution. I'm on Debian 10

Thanks for your help everyone

**Comment by rustdesk** [comment]
No build issue any more.

**Comment by Warkann2** [comment]
What no issue ?, i don't think i unterstand...
