### ISSUE TITLE
Android client to Windows host: Can't change OS password

### ISSUE THREAD

**Issue by yambadr** [rustdesk/rustdesk#7273]
### Bug Description

I changed my Windows login password. When I try try to change OS password on the Android client with the edit button, it pastes the saved old password instead of prompting me to change it.

### How to Reproduce

Tap the edit icon next to OS password. Reproducible every time.

### Expected Behavior

Rustdesk should prompt me to change the password.

### Operating system(s) on local side and remote side

Android 13 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

![Screenshot_20240227-144438_RustDesk](https://github.com/rustdesk/rustdesk/assets/161468399/fc50005b-1f90-46b0-995b-375443706614)
![Screenshot_20240227-145414_RustDesk](https://github.com/rustdesk/rustdesk/assets/161468399/0f809e90-3f48-4be2-8865-6a52ebc80bbc)

**Comment by rustdesk** [comment]
I can not reproduce with nightly build.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/6495

**Comment by yambadr** [comment]
I'm on the latest stable version 1.2.3-1

**Comment by yambadr** [comment]
I can confirm that it's fixed in the nightly 1.2.4. However, it's reproducible in 1.2.3-1
