### ISSUE TITLE
Login error: The name is not activatable

### ISSUE THREAD

**Issue by 0xEED131C78F2C6052** [rustdesk/rustdesk#7280]
### Bug Description

IDK why. What can I do for addition?

### How to Reproduce

Standard steps (have another remote sides but on Windows) for connection.
OS: ArchLinux, Wyland, Sway.
The package: from [AUR](https://aur.archlinux.org/packages/rustdesk-bin).

### Expected Behavior

Possibility of remote control.

### Operating system(s) on local side and remote side

Windows 11 Pro -> ArchLinux

### RustDesk Version(s) on local side and remote side

1.2.3-1 -> 1.2.3-3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/146383984/868b3c15-e5e3-489f-8622-f6fe90809a69)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by lessu** [comment]
Archlinux + Hyprland.
After install `xdg-desktop-portal-hyprland`, this error disappeared ( other error comes up in my case though)

I think you should install xdg-desktop-portal-xxx according to your DE differently

**Comment by fuad-daoud** [comment]
> Archlinux + Hyprland. After install `xdg-desktop-portal-hyprland`, this error disappeared ( other error comes up in my case though)
> 
> I think you should install xdg-desktop-portal-xxx according to your DE differently

Archlinux + Sway 

Installing `xdg-desktop-portal-wlr` and it works perfectly. 

@lessu thanks man
