### ISSUE TITLE
Bizarre brightness issue when connecting to remote

### ISSUE THREAD

**Issue by pedrob37** [rustdesk/rustdesk#7289]
### Bug Description

I've been using Rustdesk for a few days to connect to my Ubuntu machine from my Windows laptop. This morning, however, when I connected, my shared screen looked bizarre, bright in the middle with tapering off brightness towards the edges. It's still usable, but it is extremely jarring. Could this be some weird feature I haven't realised is on?

### How to Reproduce

It just happened when I connected for the first time in the day.

### Expected Behavior

I would expect the screen to appear normal, with homogenous brightness throughout.

### Operating system(s) on local side and remote side

Windows 10 -> Ubuntu 18.04

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/33317198/656444d8-24bd-436c-9708-d4f22e6f0b17)

**Comment by FabFav** [comment]
Same problem connecting from linux to windows 11 machine...
