### ISSUE TITLE
ios crash (iPhoneXSMax, 16.6)

### ISSUE THREAD

**Issue by L1yp** [rustdesk/rustdesk#7291]
### Bug Description

IOS控制端闪退

### How to Reproduce

iPhoneXSMax 256G，系统版本：16.6

### Expected Behavior

正常使用

### Operating system(s) on local side and remote side

被控端windows11

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.3-1

### Screenshots

NO

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893

**Comment by L1yp** [comment]
版本降级到1.2.2即可稳定使用
