### ISSUE TITLE
Changing the application name generates an error during the build process. (Trying to troubleshoot a problem with Kaspersky AV)

### ISSUE THREAD

**Issue by Jemmota** [rustdesk/rustdesk#7292]
### Bug Description

Some time ago it was possible to change the name of the RustDesk application's executable to whatever name we wanted, according to this tutorial https://github.com/CW3MH6/rustdesk-customization... The name "RustDesk" in the executable never bothered me. However, I have been experiencing some issues with Kaspersky Antivirus on my clients. I wanted to do an experiment, renaming the application name (including the rustdesk.exe executable) to see if this eliminates the AV problem. However, when I do the procedures to change the name of the executable, it generates an error during the build process. I would like to know if it is still possible to change the name of the application and what is the correct procedure?

### How to Reproduce

Change the application name from RustDesk to any other desired name, as per the instructions in the document https://github.com/CW3MH6/rustdesk-customization

### Expected Behavior

The build process stops due to error below:
```
warning: function `start_query_session_count` is never used
   --> src\tray.rs:172:10
    |
172 | async fn start_query_session_count(sender: std::sync::mpsc::Sender<Data>) {
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^

warning: `ipmrmt` (lib) generated 9 warnings (run `cargo fix --lib -p ipmrmt` to apply 2 suggestions)
    Finished release [optimized] target(s) in 3m 59s

lib/models/platform_model.dart(7,1): error G5FE39F1E: Type 'RustdeskImpl' not found. [C:\SIS\Lib\GitHub\rustdesk-bld\flutter\build\windows\x64\flutter\flutter_assemble.vcxproj]
lib/models/native_model.dart(35,8): error G5FE39F1E: Type 'RustdeskImpl' not found. [C:\SIS\Lib\GitHub\rustdesk-bld\flutter\build\windows\x64\flutter\flutter_assemble.vcxproj]
lib/models/native_model.dart(44,3): error G5FE39F1E: Type 'RustdeskImpl' not found. [C:\SIS\Lib\GitHub\rustdesk-bld\flutter\build\windows\x64\flutter\flutter_assemble.vcxproj] ...
```

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.2.4 (Nightly) 

### Screenshots

<img width="867" alt="build_error" src="https://github.com/rustdesk/rustdesk/assets/129885668/1b9325ce-d1ec-4233-8e39-72ac4535b57b">

### Additional Context

.

**Comment by rustdesk** [comment]
#763
