### ISSUE TITLE
Flutter build error: The getter 'TextScaler' isn't defined

### ISSUE THREAD

**Issue by nicolas-ecarnot-sitpi** [rustdesk/rustdesk#7293]
### Bug Description

Flutter : Building Linux appimage/FlatPak/ubuntu 18.04 packages are failing with the error : 

ERROR: lib/main.dart:430:37: Error: The getter 'TextScaler' isn't defined for the class '_AppState'.
in run-flutter-nightly-build / build-rustdesk x86_64-unknown-linux-gnu (ubuntu-18.04) []

### How to Reproduce

Fork the project, use Github to run Actions / jobs / run workflow / choose a nightly build.
Every build-rust-libs sub tasks are green / running OK, but every Linux related sub task is failing.

### Expected Behavior

Every assets are built.

### Operating system(s) on local side and remote side

github actions

### RustDesk Version(s) on local side and remote side

latest (source code daily updated)

### Screenshots

![2024-02-29_17-04](https://github.com/rustdesk/rustdesk/assets/152623478/0c17c464-ec48-4e96-a6a1-56d1de621e4e)

**Comment by rustdesk** [comment]
#763
