### ISSUE TITLE
Issue with multiple screen display

### ISSUE THREAD

**Issue by strive1216** [rustdesk/rustdesk#7295]
### Bug Description

Today's nightly version, when remotely accessing Windows 10 from Debian, does not support dual screen dual windows support. What happened?

### How to Reproduce

The remote end has a single screen, while the local end has dual screens. Virtual multi-screen display is not possible

### Expected Behavior

Can display remote desktop on both screens locally.

### Operating system(s) on local side and remote side

debian->windwos

### RustDesk Version(s) on local side and remote side

1.2.4->1.2.4

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/22957560/1b72f6c5-ffb5-4f7a-9187-e4d689727fd3)
![image](https://github.com/rustdesk/rustdesk/assets/22957560/e10fe1eb-aaf1-4363-9dcb-724876732b1a)

**Comment by rustdesk** [comment]
This is not RDP, we do not create virtual display for you.
