### ISSUE TITLE
Got error undefined symbol: new_uint_8_list_0 

### ISSUE THREAD

**Issue by souravkgp** [rustdesk/rustdesk#7296]
### Bug Description

initialize failed: Invalid argument(s): Failed to lookup symbol 'new_uint_8_list_0': undefined symbol: new_uint_8_list_0

### How to Reproduce

When I install the build and run the android app 
got this error when build successfully done and android app has been run
BUT whole app screen has been white.

### Expected Behavior

run app successfully with proper .screen interaction

### Operating system(s) on local side and remote side

Ubuntu 20.04

### RustDesk Version(s) on local side and remote side

1.2.4

### Screenshots

![Screenshot from 2024-03-01 15-45-14](https://github.com/rustdesk/rustdesk/assets/155157516/4f6ef4b8-b416-423d-a125-8456c4e3e4d9)

**Comment by rustdesk** [comment]
#763
