### ISSUE TITLE
Self-hosted server resets the connection immediately on each attempt

### ISSUE THREAD

**Issue by adamryczkowski** [rustdesk/rustdesk#7298]
### Bug Description

I am able to connect between two computers that share the local LAN, but for the normal internet connections I've got cryptic error "Connection Error Reset by the peer". 

When I inspect the standard output/error of the  `hbbs` and `hbbr`, I see no trace of attempted connections.
I suspect that there are is some problem with the opened ports. 

Or maybe there is some form of connection to either `hbbs` or `hbbr`, but it is deemed "too insignificant" for output. Is there any way to increase the verbosity level of messages produced by the `hbbr` and `hbbs`? 

Is there a way to test the `hbbr` separately from `hbbs`? What is the `hbbr` needed for, anyway? Is there any use case, where I would want it to be run on a separate machine? Afaik, it seems to be used only by the paid version of the program.

### How to Reproduce

On headless Ubuntu 22.04 I've created an LXD container with Ubuntu 22.04, I've installed there these two packages to have private Rustdesk server instance:

`rustdesk-server-hbbr_1.1.10-3_amd64.deb`
`rustdesk-server-hbbs_1.1.10-3_amd64.deb`

I've made sure the relevant services are up and running. In particular, the programs are run with the following command line arguments:
```
hbbs -r 139.162.226.242 -k _
hbbr -k _
```

There is a valid `id_ed25519.pub` in the working directory of both programs. 

I've also made sure the following ports are forwarded to host:
```
tcp:21115
tcp:21116
tcp:21117
tcp:21118
tcp:21119
udp:21116
```

In the client's settings, I filled in the server's IP for the "ID server" and "Relay server" fields, as well as the Key.

### Expected Behavior

Client connected to another's client remote desktop.

### Operating system(s) on local side and remote side

Ubuntu 22.04

### RustDesk Version(s) on local side and remote side

1.2.3->1.2.3-2

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/4469707/6d9aa1bc-6eac-49dc-b4dc-41bef4a2a159)

**Comment by rustdesk** [comment]
#763
