### ISSUE TITLE
Unsupported display server type,x11 expected

### ISSUE THREAD

**Issue by ac5tin** [rustdesk/rustdesk#73]
i tried to connect to an ubuntu server (20.04) with xfce installed. Im connecting from Manjaro i3wm and the error popup message is: Unsupported display server type, x11 expected
![2021-06-11-190441_500x174_scrot](https://user-images.githubusercontent.com/24804667/121676948-d71a1900-cae7-11eb-9db0-532f81c1df4c.png)

**Comment by rustdesk** [comment]
Wayland not support yet.

**Comment by ac5tin** [comment]
but i am using x11 

![2021-06-11-190907_276x191_scrot](https://user-images.githubusercontent.com/24804667/121677450-73442000-cae8-11eb-8713-7f8b33c138ef.png)

**Comment by rustdesk** [comment]
Could you show me output of `loginctl'  and `loginctl  show-session  -p Type <session_number>`?

**Comment by rustdesk** [comment]
Can not find seat0

**Comment by rustdesk** [comment]
Can you show me your /root/.local/share/logs/RustDesk/service/rustdesk_rCURRENT.log?

**Comment by ac5tin** [comment]
![2021-06-11-193254_764x122_scrot](https://user-images.githubusercontent.com/24804667/121680141-c5d30b80-caeb-11eb-99ba-f134677cde10.png)

**Comment by rustdesk** [comment]
`loginctl show-session -p State <session_number>` please

**Comment by ac5tin** [comment]
![2021-06-11-194017_407x388_scrot](https://user-images.githubusercontent.com/24804667/121681062-e64f9580-caec-11eb-9b9c-c1663b0d1d02.png)

**Comment by rustdesk** [comment]
Ok, I will give you a workaround soon.

**Comment by rustdesk** [comment]
try out this new build https://github.com/rustdesk/rustdesk/releases/download/tmp/rustdesk-1.1.6.deb

**Comment by ac5tin** [comment]
> try out this new build https://github.com/rustdesk/rustdesk/releases/download/tmp/rustdesk-1.1.6.deb

 yup this works now, thx

**Comment by hboetes** [comment]
I'm getting exactly the same problem with i3wm on debian-11.6

```
h.boetes@habocp1 ~ % loginctl                        
SESSION  UID USER     SEAT  TTY
     20 1102 h.boetes seat0 
      3 1102 h.boetes       pts/0

2 sessions listed.
h.boetes@habocp1 ~ % loginctl show-session -p Type 20
Type=x11
h.boetes@habocp1 ~ % loginctl show-session -p Type 3 
Type=tty
```

**Comment by dapize** [comment]
I'm getting the same error in Linux Mint 21.1
