### ISSUE TITLE
Windows White Screen in the latest rustdesk-1.2.3-1-x86_64.exe (Flutter). 

### ISSUE THREAD

**Issue by therong537** [rustdesk/rustdesk#7304]
### Bug Description

The latest release [rustdesk-1.2.3-1-x86_64.exe] shows up as a white screen on Windows. Previous issues suggest that this issue can be fixed once the Flutter UI migration kicks in.

### How to Reproduce

Not sure, seems like a common issue in Flutter App. Maybe there is some dependences need to be installed? 

### Expected Behavior

White screen.

### Operating system(s) on local side and remote side

Windows 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3-1 -> 1.2.3-1

### Screenshots

![rustdesk white screen](https://github.com/rustdesk/rustdesk/assets/17779501/b7036fa6-dda6-437c-b4f6-55ef22a68d66)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/5108#issuecomment-1837335668
