### ISSUE TITLE
Privacy mode bug on 3 screens

### ISSUE THREAD

**Issue by Vasilis553** [rustdesk/rustdesk#7306]
### Bug Description

Hello, I have 3 monitor pc and I realized that privacy mode toggles only on monitor number 1 the second or third monitor remains visible to host screen and on rustdesk you can't control the other tree monitors when the number one is in privacy mode

### How to Reproduce

No

### Expected Behavior

No

### Operating system(s) on local side and remote side

Windows 10-11

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

. 

### Additional Context

.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/6707
