### ISSUE TITLE
Keyboard usage bug

### ISSUE THREAD

**Issue by Qingnan7780** [rustdesk/rustdesk#7308]
### Bug Description

1. Traditional mode MAC input method often fails
2.1:1 transmission mode often triggers MAC shortcut keys without reason
3. Change Mac replication to ctrl+c, but when Windows is remote, the replication is still command+c
The above are all bugs caused by Windows 10 remote Mac

### How to Reproduce

This problem can be directly reproduced

### Expected Behavior

Win10 has significant remote MAC issues

### Operating system(s) on local side and remote side

Windows 10 -> Macos

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

![未命名](https://github.com/rustdesk/rustdesk/assets/63048659/461ea220-73e8-430b-bf4a-6876ecdb031b)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by rustdesk** [comment]
Could you try out our nightly build on both side? https://github.com/rustdesk/rustdesk/releases/tag/nightly

**Comment by rustdesk** [comment]
@fufesou follow it up after @Qingnan7780 tested nightly.

**Comment by rustdesk** [comment]
We put a fix on nightly build today, please test https://github.com/rustdesk/rustdesk/releases/tag/nightly

**Comment by Qingnan7780** [comment]
> We put a fix on nightly build today, please test https://github.com/rustdesk/rustdesk/releases/tag/nightly

I have test，At present, the shortcut key issue has been resolved, but there is still one issue. The copy shortcut key set by my Mac is ctrl+c, but I still need to use command+c on my Windows end

**Comment by fufesou** [comment]
Have you checked on this option?

<img width="215" alt="1709875972157" src="https://github.com/rustdesk/rustdesk/assets/13586388/1d6dba45-1321-455a-bc82-71c526a90759">

**Comment by Qingnan7780** [comment]
> > We put a fix on nightly build today, please test https://github.com/rustdesk/rustdesk/releases/tag/nightly
> 
> I have test，At present, the shortcut key issue has been resolved, but there is still one issue. The copy shortcut key set by my Mac is ctrl+c, but I still need to use command+c on my Windows end

Heads up! The last email your site attempted to send was unsuccessful.

Email Source: WP核心
Mailer: Google / Gmail
You must provide at least one recipient email address.
For more details please try running an Email Test or reading the latest [error event](https://www.vwodis.com/wp-admin/admin.php?page=wp-mail-smtp-tools&tab=debug-events).

**Comment by Qingnan7780** [comment]
> Have you checked on this option?
> 
> <img alt="1709875972157" width="215" src="https://private-user-images.githubusercontent.com/13586388/311126760-1d6dba45-1321-455a-bc82-71c526a90759.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4Nzc2MzksIm5iZiI6MTcwOTg3NzMzOSwicGF0aCI6Ii8xMzU4NjM4OC8zMTExMjY3NjAtMWQ2ZGJhNDUtMTMyMS00NTVhLWJjODItNzFjNTI2YTkwNzU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA1NTUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZWZmYzg4MzkzYjNhZjRmNzZhMmUwNzM5MWExYjhhYmQxMzA4YmNlNDA2NGZiZjgyNTkxM2QwMzQ1YzNlYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wi0sJg3qpG_j_sKPCmX88gUfDTG35KFC04vl11t6pqs">

thanks

**Comment by Qingnan7780** [comment]
> Have you checked on this option?
> 
> <img alt="1709875972157" width="215" src="https://private-user-images.githubusercontent.com/13586388/311126760-1d6dba45-1321-455a-bc82-71c526a90759.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4Nzc2MzksIm5iZiI6MTcwOTg3NzMzOSwicGF0aCI6Ii8xMzU4NjM4OC8zMTExMjY3NjAtMWQ2ZGJhNDUtMTMyMS00NTVhLWJjODItNzFjNTI2YTkwNzU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA1NTUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZWZmYzg4MzkzYjNhZjRmNzZhMmUwNzM5MWExYjhhYmQxMzA4YmNlNDA2NGZiZjgyNTkxM2QwMzQ1YzNlYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wi0sJg3qpG_j_sKPCmX88gUfDTG35KFC04vl11t6pqs">

What is the difference between traditional mode and 1:1 mode?

**Comment by fufesou** [comment]
> What is the difference between traditional mode and 1:1 mode?

The traditional and translate mode send letters to the remote side.
1:1 simulate keystrokes.

> There is a delay in the command button now

Is only "Command" affected?

The latest build should not affect "Command" key.

Can you please try "Command" directly on the remote side?

**Comment by rustdesk** [comment]
I do not see delay issue.

**Comment by Qingnan7780** [comment]
> I tested two cases,

Windows ->MAC
1. Traditional mode: When I use command+c, it works normally
2.1:1 Mode: When I use command+c, there is command delay or even no work
So I'm not sure about the difference between traditional mode and 1:1 mode

**Comment by fufesou** [comment]
@Qingnan7780  Thanks for your detailed feedback.

But I cannot reproduce the two issues.

I've tested both the installed version and the non-install version.

> 2. 1:1 Mode: When I use command+c, there is command delay or even no work
So I'm not sure about the difference between traditional mode and 1:1 mode

I've printed the simulating keycode of "Command + c" for the traditional mode and the 1:1 mode.
They are simulating the same keycodes, "55 + 8" .

And there's no delay for me.

**Comment by Qingnan7780** [comment]
> I've printed the simulating keycode of "Command + c" for the traditional mode and the 1:1 mode. They are simulating the same keycodes, "55 + 8" .
> 
> And there's no delay for me.

The problem I am currently facing is
1. In traditional mode, pressing keys 6 and 7 will automatically close Rustdesk or characters will appear;
2. 1:1 CTL delay in mode
I have crashed, Rustdesk is currently the smoothest remote software I have.

**Comment by Qingnan7780** [comment]
> I do not see `delay`, just tested.
> 
> I tested two cases,
> 
> 1. Windows in RDP on Mac -> Mac
> 2. Windows -> MAC
> 
> Though `command` does not work in case 1 (but in swap mode, both command and ctl works, interesting, I think this case is too special), but does work in case 2.

1. 1: 1 mode, do not enable swapping Ctrl and Command, copy and paste will not be delayed
2. Traditional mode cannot be used, keys generate shortcut keys

**Comment by Qingnan7780** [comment]
> 感谢您的详细反馈。
> 
> 但我不能重现这两个问题。
> 
> 我在两边都使用最新版本。我已经在远程端测试了已安装版本和非安装版本。
> 
> > 2. 1：1 模式：当我使用 command+c 时，有命令延迟甚至没有工作 所以我不确定传统模式和 1：1 模式的区别
> 
> 我已经打印了传统模式和 1：1 模式的“Command + c”模拟键代码。他们正在模拟相同的键码，“55 + 8”。
> 
> 对我来说没有延迟。

HI，how can i connect you?i need you help me

**Comment by fufesou** [comment]
@Qingnan7780 Hi, this is my email `c2h1YW5nbG9uZ2NoZW5AeWVhaC5lbnQ=` (in base64)
