### ISSUE TITLE
RustDesk iOS - Black screen when first connecting to android

### ISSUE THREAD

**Issue by plia7** [rustdesk/rustdesk#7311]
### Bug Description

When I connect to an Android target using RustDesk iOS app, a black screen shows.

### How to Reproduce

Connect to the target, you first see a black screen.
Tap one time on the black screen and then the phone screen will show.

### Expected Behavior

Being able to see the phone screen when connecting without the need to tap one time on the black screen to see the phone screen.

### Operating system(s) on local side and remote side

iOS 14 -> Android 11

### RustDesk Version(s) on local side and remote side

1.1.10 -> 1.1.10-1

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/134864072/b72d3bf9-b0d3-4e99-b56e-3c8635b6f799)

### Additional Context

Same issue if I connect from RustDesk 1.2.2:

![image](https://github.com/rustdesk/rustdesk/assets/134864072/6acefb06-9c76-4c4b-b1b0-a3d665756dfb)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893
