### ISSUE TITLE
can't build nightly with selfhosted rendezvous_server

### ISSUE THREAD

**Issue by Raxiel1987** [rustdesk/rustdesk#7318]
### Bug Description

i'm building a selfhosted version of rustdesk but i can't get it to work with rendevouz server
i configured the repo with the instruction, i added the:

Click “New repository secret”, for the name put RENDEZVOUS_SERVER, for the secret put your servers name/ip address.

Click “New repository secret”, for the name put RS_PUB_KEY, for the secret put your servers public key.

another problem too, i can't create the macos arm versione

### How to Reproduce

clone the repo

### Expected Behavior

with the istruction i should connect to my hosted server, but not happens

### Operating system(s) on local side and remote side

linux

### RustDesk Version(s) on local side and remote side

1.2.4 nightly

### Screenshots

![Schermata del 2024-03-04 23-11-22](https://github.com/rustdesk/rustdesk/assets/98883346/4d6a7d6d-f5c0-4851-bd39-9be480bb15d7)

in this screenshot it tell me that for a better performance i should add a personal server

**Comment by rustdesk** [comment]
#763
