### ISSUE TITLE
"deadline has elapsed". Can't connect to remote server

### ISSUE THREAD

**Issue by giou** [rustdesk/rustdesk#732]
**Describe the bug you encountered:**

It does not connect to RustDesk instances that are on different network

**How did you install `RustDesk`?**

Github release **1.1.9**. Tested multiple computers, Windows and Linux. The PC's I want to connect to are all Windows machines.

**log/connect**
```
[2022-06-08 14:12:55.164546 +02:00] INFO [src\common.rs:69] clipboard update found on client
[2022-06-08 14:12:55.164875 +02:00] INFO [src\client.rs:146] rendezvous server:server.com:21116
[2022-06-08 14:12:55.255551 +02:00] INFO [src\client.rs:160] #1 punch attempt with local-ip:65097, id: 48xxxxx
[2022-06-08 14:12:57.148292 +02:00] INFO [src\client.rs:201] Hole Punched 48xxxxx = ip:55411
[2022-06-08 14:12:57.148329 +02:00] INFO [src\client.rs:232] 1892 ms used to punch hole, relay_server: server.com, nat_type: ASYMMETRIC
[2022-06-08 14:12:57.148464 +02:00] INFO [src\client.rs:307] peer address: ip:55411, timeout: 18000
[2022-06-08 14:12:58.175640 +02:00] INFO [src\client.rs:341] 1.0271696s used to establish connection
[2022-06-08 14:13:16.221571 +02:00] INFO [src\client.rs:1181] Video decoder loop exits
[2022-06-08 14:13:16.221571 +02:00] INFO [src\client.rs:1200] Audio decoder loop exits
[2022-06-08 14:13:16.539706 +02:00] DEBUG [src\ui\remote.rs:1477] Exit clipboard service of client
```

I've tried with the default relay public servers and also with the selfhost server, same results. Only working for computers in the same network.

I've tried adding an allow rule in windows advanced firewall.

While connecting if flashes an error for about 0.5s that says: "deadline has elapsed".

![deadline](https://user-images.githubusercontent.com/5844127/172649804-99ddc1c3-187a-465d-9f78-373e09963f4d.png)

**Comment by rustdesk** [comment]
honestly, i have no clue for now.

**Comment by rustdesk** [comment]
> End user here with seeing similar issue.

I have no clue either before I can reproduce the problem.

**Comment by acseven** [comment]
One additional information: this is apparently an issue with the Windows client. I've successfully connected to a linux box on. a different network using a Mac.

**Comment by GivenChaos** [comment]
I had the same issue after a couple days of use with no issues, but what fixed it for me was a simple Uninstall and Reinstall. I'm also running Windows 10.

**Comment by skrzacikus** [comment]
I had the same issue on Windows 11. I uninstalled client, then installed again and everything works fine.

**Comment by skrzacikus** [comment]
> Reinstalled as well but no go.
Reinstalling without uninstalling first, doesn't help.
I had to uninstall rustdesk and install it again to make it work again.

**Comment by acseven** [comment]
I've deployed the server again, uninstalled rustdesk and issue remains unfortunately. Using the Web functionality is also unavailable. Tryning to be clearer:
- Network 1
 - Hosts server
 - Hosts offending Windows client, same LAN
- Network 2
 - Some Windows/Linux servers and Windows machines, all work fine in the LAN, all reach the server on Network 1
 - Can't reach Hosts on Network 1

Issue persists even with OpenVPN connection between networks.

**Comment by haranobuhardo** [comment]
Just tried RustDesk today and encountered the same issue between three computer (all using free online server; 2xWin10 & 1xWin11). But when I tried to connect all from RustDesk on Android (and vice versa), it worked like a charm. Looks like there's an issue on Windows OS
![Screenshot (2)](https://user-images.githubusercontent.com/38966576/181504425-fde68cf5-498f-4d63-9cbc-b7b2684a400a.png)

![Screenshot (1)](https://user-images.githubusercontent.com/38966576/181504406-2de3f74e-3254-4eae-afca-1b7d8a6135b0.png)

**Comment by rustdesk** [comment]
Interesting

**Comment by cozdil** [comment]
I am experiencing same issue with two computers. One is Windows 7 and another is Windows 10.

If I try to reach any of these computers from Windows client, keep getting "deadline has elapsed" message with 

[2022-08-09 21:53:55.693582 +03:00] INFO [src\client.rs:341] 26.0081ms used to establish connection
[2022-08-09 21:54:13.740507 +03:00] INFO [src\client.rs:1200] Audio decoder loop exits
[2022-08-09 21:54:13.740507 +03:00] INFO [src\client.rs:1181] Video decoder loop exits

logs, but I can successfully connect either of these machines from web client (web.rustdesk.com).

If there is any way I can help please let me know.

**Comment by rustdesk** [comment]
> web

@21pages similar to 10054 problem

**Comment by 21pages** [comment]
> I am experiencing same issue with two computers. One is Windows 7 and another is Windows 10.
> 
> If I try to reach any of these computers from Windows client, keep getting "deadline has elapsed" message with
> 
> [2022-08-09 21:53:55.693582 +03:00] INFO [src\client.rs:341] 26.0081ms used to establish connection [2022-08-09 21:54:13.740507 +03:00] INFO [src\client.rs:1200] Audio decoder loop exits [2022-08-09 21:54:13.740507 +03:00] INFO [src\client.rs:1181] Video decoder loop exits
> 
> logs, but I can successfully connect either of these machines from web client (web.rustdesk.com).
> 
> If there is any way I can help please let me know.

We need to connect to your computer, password is not needed.

**Comment by cozdil** [comment]
> > I am experiencing same issue with two computers. One is Windows 7 and another is Windows 10.
> > If I try to reach any of these computers from Windows client, keep getting "deadline has elapsed" message with
> > [2022-08-09 21:53:55.693582 +03:00] INFO [src\client.rs:341] 26.0081ms used to establish connection [2022-08-09 21:54:13.740507 +03:00] INFO [src\client.rs:1200] Audio decoder loop exits [2022-08-09 21:54:13.740507 +03:00] INFO [src\client.rs:1181] Video decoder loop exits
> > logs, but I can successfully connect either of these machines from web client (web.rustdesk.com).
> > If there is any way I can help please let me know.
> 
> Can I connect to your computer for diagnose? password is not needed, just check the connection initialization process.

Sure, it's running our selfhosted server but i can share needed info with you, could you share an email address with me?

**Comment by 21pages** [comment]
> > > I am experiencing same issue with two computers. One is Windows 7 and another is Windows 10.
> > > If I try to reach any of these computers from Windows client, keep getting "deadline has elapsed" message with
> > > [2022-08-09 21:53:55.693582 +03:00] INFO [src\client.rs:341] 26.0081ms used to establish connection [2022-08-09 21:54:13.740507 +03:00] INFO [src\client.rs:1200] Audio decoder loop exits [2022-08-09 21:54:13.740507 +03:00] INFO [src\client.rs:1181] Video decoder loop exits
> > > logs, but I can successfully connect either of these machines from web client (web.rustdesk.com).
> > > If there is any way I can help please let me know.
> > 
> > 
> > Can I connect to your computer for diagnose? password is not needed, just check the connection initialization process.
> 
> Sure, it's running our selfhosted server but i can share needed info with you, could you share an email address with me?

My email is pages21@163.com

**Comment by cozdil** [comment]
> > > > I am experiencing same issue with two computers. One is Windows 7 and another is Windows 10.
> > > > If I try to reach any of these computers from Windows client, keep getting "deadline has elapsed" message with
> > > > [2022-08-09 21:53:55.693582 +03:00] INFO [src\client.rs:341] 26.0081ms used to establish connection [2022-08-09 21:54:13.740507 +03:00] INFO [src\client.rs:1200] Audio decoder loop exits [2022-08-09 21:54:13.740507 +03:00] INFO [src\client.rs:1181] Video decoder loop exits
> > > > logs, but I can successfully connect either of these machines from web client (web.rustdesk.com).
> > > > If there is any way I can help please let me know.
> > > 
> > > 
> > > Can I connect to your computer for diagnose? password is not needed, just check the connection initialization process.
> > 
> > 
> > Sure, it's running our selfhosted server but i can share needed info with you, could you share an email address with me?
> 
> My email is [pages21@163.com](mailto:pages21@163.com) . Your help will be important to us.

Sent connection info to your mail address.

**Comment by barajasfernando** [comment]
Hi!  Newbie to Rustdesk.  I'm having the same problems connecting 2 computers using Windows 10.  When I try to connect to the remote computer from Rustdesk WEB, it works perfectly, but when I try to connect from my windows computer, I get the mentioned error (deadline has elapsed).  

Where can I check the logs?  What can I try to fix it?  I'll try to reinstall.

**Comment by jwood1980** [comment]
I am having the same issue, I have tried everything that I can think of... The only way I can get this to work is by keeping the ID/Relay server field blank. Whenever I enter the IP or hostname for my server, it will display the error "Deadline has elapsed", but the status is saying it is ready and is green and the notification "for faster connection please set up your own server" disappears. So from first appearance, it looks like the initial connection is working. However, it refuses to connect.

My setup:
I am running an Ubuntu server VM within VMware Workstation, running on Windows 11. I have RustDesk installed on the host, another computer at my workplace and my Android handset. All of which refuse to connect when I enter the correct IP/hostname in the ID/Relay field, however all three machines will work together, if the field is empty.

So the issue clearly has something to do with my self host setup. I have checked the docker-compose.yml and the address/port in there is correct. I have tried this with the local IP and the No-IP hostname I have set up, as my external IP changes. So in theory, it should be working. As mentioned, I get the green ready indication at the bottom of the RustDesk GUI and indicates that it is ready to connect.

I have tried turning off the UFW firewall, turning it on, turning off Windows Firewall and on, adding rules etc. Nothing helps here.
I have also checked the VM settings and the network is set to bridged and has it's own IP address. I have forwarded the ports in my home router and these appear correct too.

I am at a complete loss as to why this isn't working. This is part of a test at home as my team are planning to use this, in place of Teamviewer, so it would be great if I could get this working.

Does anyone here have any insight?

Thank you in advance.

**Comment by rustdesk** [comment]
> insight

Go to discord please, there may be some one can help you.

**Comment by daykx** [comment]
Had a struggle too, with self host and clients in same LAN - there is some confusion with LAN and WAN addresses.
First, "failed to connect via relay server", after changing server IP to domain name it "failed to connect via rendezvous server", eventually problem solved after setting NAT Loopback (or Hairpin) rules in my router.

**Comment by rustdesk** [comment]
> Had a struggle too, with self host and clients in same LAN - there is some confusion with LAN and WAN addresses. First, "failed to connect via relay server", after changing server IP to domain name it "failed to connect via rendezvous server" when connecting to LAN clients, or "deadline has elapsed" when connecting from LAN clients. Eventually problem solved after setting NAT Loopback (aka Hairpin) rules in LAN router!

good try

**Comment by severach** [comment]
Didn't work for me either. LAN to same LAN connections worked most of the time but Internet connections rarely connected. Got rendezvous, offline, and deadline errors. All working and fast when I finally got my own server running over gig fiber.

The recent Anydesk [debacle](https://old.reddit.com/r/AnyDesk/comments/yp61q0/just_switch_to_rustdesk/) has RustDesk servers overloaded. Run your own server or don't bother. The current instructions are too sparse for all but the Internet mavens to get working. Own server will get easier when more people get it working and write better guides.

**Comment by acseven** [comment]
The issue occurs with self hosted servers.

**Comment by giou** [comment]
> The issue occurs with self hosted servers.

Like I said in the post, at least in 1.1.9. The issue occurs also in public servers.

**Comment by rustdesk** [comment]
From discord:
> Setup a NAT rule in your firewall that allows your internal clients to “speak directly” to your external IP address. Assuming you haven’t done this already as this was my hold up. 
> 
> The following article should help if you’re behind a Cisco firewall. (Note; the instructions are essentially the same for FMC and FTD)
> 
> https://integratingit.wordpress.com/2021/07/11/ftd-nat-reflection/

**Comment by Aerasyn** [comment]
I get the deadline has elapsed message on one out of 6 computers while self hosting. It doesnt happen on that connection if its inside the LAN but when I attempt the same connection ouitside the LAN it doesn't connect and gives that message.

**Comment by severach** [comment]
After adding more peers and more testing I ended up with a few pairs on different LAN that wouldn't connect. Error is "deadline has elapsed." Seems to be routers specific as all pairs behind the same two LAN cannot connect yet I have other pairs on one same and one different LAN that do connect. No home peer connects to any peer at office 2. Any home peer connects to every peer at office 1 and 3. Office 2 connects to office 1 but not office 3 or home. Office 1 hosts the server and connects to all. Office 3 connects to office 1 or home but not office 2.

Home: Cable Fortigate 60D
Office 1: Fiber Fortigate 60E Static IP hbbr hbbs server 1.1.6 host not on default ports
Office 2: Cable Fortigate 60E
Office 3: Cable Technicolor DPC3941

Upgrading both peers to 1.2.0 nightly fixed the problem, or at least fixed the problem enough that they can connect. On first connect I get error "Connection reset by peer (os error 104)". Something is written to the Linux saved session `~/.config/rustdesk/peers/*.toml` to prevent this error and speed up future connects.

Own server or public server made no difference. Windows 1.1.9 or Linux 1.1.9 have the same connection problem. Moving own server to subnet not accessible by office 1 peers made no difference.

May be related to #1597

**Comment by rustdesk** [comment]
Can you try out nightly build? There is a fix, though not good enough, not sure if it works in your scenario.

**Comment by kevinlau2015** [comment]
很抱歉这里用中文，英文能看不会写。

我也出现了这个问题，尝试了以下情况，看是否有有用的信息。
1.[A地点]始终无法连接到[B地点]的电脑，提示deadline has elapsed（控制端 win10，被控端win7 win2012）。
   [A地点]测试了两台电脑，[B地点]也测试了两台电脑。
2.尝试了将服务器配置为自建云服务器、[A地点]所在网络内的服务器、rustdesk公共服务器都是一样的结果。
3.尝试了1.1.9版本和1.2.0每日构建版本，也一样。

4.尝试了[C地点]的电脑连接[B地点]的电脑，连接成功，连接方式为[加密中转]

另：[A地点]的电脑一直以来连接其他地方的电脑都是没问题。

日志截图
![Snipaste_2022-11-25_16-29-10](https://user-images.githubusercontent.com/13088124/203940352-5dce0fb3-4e02-4cdc-924a-52dc2a88766d.png)

报错截图
![image](https://user-images.githubusercontent.com/13088124/203934923-397ced22-3252-4fa8-a8e7-7cc83fd652d1.png)

**Comment by FatTiger500kg** [comment]
> 很抱歉这里用中文，英文能看不会写。
> 
> 我也出现了这个问题，尝试了以下情况，看是否有有用的信息。 1.[A地点]始终无法连接到[B地点]的电脑，提示deadline has elapsed（控制端 win10，被控端win7 win2012）。 [A地点]测试了两台电脑，[B地点]也测试了两台电脑。 2.尝试了将服务器配置为自建云服务器、[A地点]所在网络内的服务器、rustdesk公共服务器都是一样的结果。 3.尝试了1.1.9版本和1.2.0每日构建版本，也一样。
> 
> 4.尝试了[C地点]的电脑连接[B地点]的电脑，连接成功，连接方式为[加密中转]
> 
> 另：[A地点]的电脑一直以来连接其他地方的电脑都是没问题。
> 
> 日志截图 ![Snipaste_2022-11-25_16-29-10](https://user-images.githubusercontent.com/13088124/203940352-5dce0fb3-4e02-4cdc-924a-52dc2a88766d.png)
> 
> 报错截图 ![image](https://user-images.githubusercontent.com/13088124/203934923-397ced22-3252-4fa8-a8e7-7cc83fd652d1.png)
> 
> **2022年11月27日** 使用了1.2.0每日构建版本，在[最近访问过]对应的菜单中选中“强制走中继连接”，能够连接，而且连接很快。 ![image](https://user-images.githubusercontent.com/13088124/204123582-2cd7fe12-54d9-4d17-b49b-be7af0e4bcc2.png)
> 
> 但是问题是如果没有连接成功过的电脑是无法出现在[最近访问过]的。 我是在AppData\Roaming\RustDesk\config\peers下复制了其他电脑的文件，然后后将文件名改为[deadline has elapsed]电脑的Id，然后在[最近访问过]就能有了

Solved the problem in the same way. It looks like it is caused by the client not being able to automatically link through the transit tunnel.

**Comment by nonickz88** [comment]
Hi,

I have the same issue here (self hosted server), multiple sites connected with VPN...SITE A to Site B we got the deadline has elapsed error... Tested on multiple PCs in SiteA without success
But if we disable windows firewall on SITE A PCs we can connect to remote client on SITE B.
tested with version 1.1.9
on Wireshark tests we've noticed that for some reason after TCP Handshake the rst packet is dropped for some reason I think it could be related to a diferent sequence number or something... 
if we upgrade to version 1.2.0 it connects very fast and works fine

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1597#issuecomment-1432517984

**Comment by LeonCame** [comment]
Settings that work with opnsense:
- in the “ports forward” rules: select “NAT reflection” = enable
- in "Firewall" - "Settings" - "Advanced": check "Automatic outbound NAT for Reflection"
- in the network settings of the Rustdesk client (which is on the same LAN as the Rustdesk Server): put IP:port as if it were an external client. (And not the internal IP of the LAN).

**Comment by shuxin8795** [comment]
自建服务器也出现了同样的问题，“截止日期已过”。

**Comment by VitaliyAT** [comment]
What ports should be forwarded for normal work? And why it work on Common Servers but not work if it local (under NAT). ANd in local net where this server placed - it work OK, but outside of NAT it's not... but it see units. Problem just when I try connect to outside.

**Comment by mv-si** [comment]
This is still an issue for us, please re-open. 
On some distant sites it works fine, and others we have to wait atleast one minute of retrying before connection can be made.

**Comment by mclovin-2k** [comment]
To me, this issue can be resolved by downgrading hbbr to 1.1.9 (hbbs can be new).
With current newest version(1.11.1-1) of hbbr, "deadline has elapsed" always happened.

**Comment by FleshCannon** [comment]
Same issues here on 1.4.0 clients of both windows and android system.
Only it's working for computers in the local network.

**Comment by FleshCannon** [comment]
> Same issues here on 1.4.0 clients of both windows and android system. Only it's working for computers in the local network.

After I filled the key on the controlled computer the problem resolved.

**Comment by NSGrid** [comment]
> > Same issues here on 1.4.0 clients of both windows and android system. Only it's working for computers in the local network.
> 
> After I filled the key on the controlled computer the problem resolved.

I noticed that this setting depends on the "encryption only" variable. If you set it to "YES," it requires entering the encryption key not only on the host computer (device), but also on the managed computer (device).

**Comment by nightrider77** [comment]
Having the same error. Seems isn't a reliable solution to use.
Reboot didn't help.

**Comment by alpsware** [comment]
> Having the same error. Seems isn't a reliable solution to use. Reboot didn't help.

We also had the same issue for clients above version 1.4.0, in our case it had something to do with the private key in use. So we deleted both id_ed25519 and id_ed25519.pub files and restarted services, which created new keys then. This keys need to be added to the clients of course, but then it worked again.

**Comment by MarcosOtilio** [comment]
Estou com o mesmo problema, já até reinicializei e instalei do zero o RustDesk e o erro permanece.
Sistema Operacional: Windows 10 / 11
Versão do RustDesk Testada: 1.3.8 / 1.4.6

**Comment by aurorapar** [comment]
Currently having the same issue after setting up using the Techahold install script. Linux relay and signal server setup, linux client trying to access.

**Comment by marko-clg** [comment]
It is happening to me randomly with 20+ widnows clients, but not always. Eg I would have 3 clients next to each other on same LAN switch and I can connect to 1 of them and not other two. Sometimes connects between 1 and 5 attempts, sometimes not even after 30 attempts. What I've tested so far is if I add server api key on client configuration the connection is much more stable. I may be wrong here but worth trying. 

It does not matter much if it's newer or older version, I did not find it more or less table with any between 1.1.9 to 1.4.x.

**Comment by hamselvdk** [comment]
<img width="572" height="329" alt="Image" src="https://github.com/user-attachments/assets/27a3d641-eeba-475e-b9bf-e3a5cfdca25e" />

The Linux client in this setup can connect through the local rustdesk server to the internet connected rustdesk instance - but the local windows client cannot. it shows this error:

<img width="524" height="193" alt="Image" src="https://github.com/user-attachments/assets/8a916e8b-d2bf-4fee-9aa9-b0313986277d" />

so I have the same issue with windows as others mention - am I missing something?
