### ISSUE TITLE
Cannot remote into Neon after Plasma 6 upgrade (x11) or wayland. Connection refused. v1.2.3 both ends

### ISSUE THREAD

**Issue by dasruralgeek** [rustdesk/rustdesk#7324]
### Bug Description

Cannot remote into Neon after Plasma 6 upgrade (x11) or Wayland. Connection refused. v1.2.3 both ends

### How to Reproduce

Reproduced on 2 different Plasma 6 upgrades.
Have tested using both permanent and One-time password in a side by side test.
inbound to plasma 6 DE refuses the connection.
Remote out to Mint or Mate desktop works as expected.

### Expected Behavior

Expect inbound connection to work on plasma 6 DE as it did in 5.27

### Operating system(s) on local side and remote side

KDE neon plasma 6

### RustDesk Version(s) on local side and remote side

1.2.3 > 1.2.3

### Screenshots

![Connection refused Plasma 6 DE](https://github.com/rustdesk/rustdesk/assets/39967526/222b7679-8ee0-45e5-b431-50024e6f9b8a)
![remote to plasma 6 DE](https://github.com/rustdesk/rustdesk/assets/39967526/16f6b2a5-ad30-4094-b1d0-9aac9ab5ccd1)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by mac-linux-free** [comment]
Same to me Plasma6 on Archlinux. Also Nightly 1.2.4 does not work.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/5095#discussioncomment-8757160
