### ISSUE TITLE
Connection Reset by Peer; Host with more than one X Screen

### ISSUE THREAD

**Issue by FeintDoxx** [rustdesk/rustdesk#7325]
### Bug Description

When attempting to connect to a rust desk host that is configured to use 2 xscreens, upon connection on the client end the message is:

`Connection Reset by Peer` after being prompted for the password and entering it correctly.

If I set my xscreen back to only 1 screen with both displays on the screen the connection is completed and I can remote in without an issue & can swap between screens.

### How to Reproduce

"Xorg conf:

`#https://wiki.archlinux.org/title/clipboard nvidia-settings: X configuration file generated by nvidia-settings
# nvidia-settings:  version 550.54.14

# nvidia-xconfig: X configuration file generated by nvidia-xconfig
# nvidia-xconfig:  version 545.29.06

Section "ServerLayout"

# Removed Option "Xinerama" "0"
    Identifier     "Layout0"
    Screen      0  "Screen0" 0 0
    Screen      1  "Screen1" 1920 0
    InputDevice    "Keyboard0" "CoreKeyboard"
    InputDevice    "Mouse0" "CorePointer"
    Option         "Xinerama" "1"
EndSection

Section "Files"
EndSection

Section "InputDevice"

    # generated from default
    Identifier     "Mouse0"
    Driver         "mouse"
    Option         "Protocol" "auto"
    Option         "Device" "/dev/psaux"
    Option         "Emulate3Buttons" "no"
    Option         "ZAxisMapping" "4 5"
EndSection

Section "InputDevice"

    # generated from default
    Identifier     "Keyboard0"
    Driver         "kbd"
EndSection

Section "Monitor"
    Identifier     "Monitor0"
    VendorName     "Unknown"
    ModelName      "Microstep MSI MAG273R"
    HorizSync       162.0 - 162.0
    VertRefresh     48.0 - 144.0
    Option         "DPMS"
EndSection

Section "Monitor"
    Identifier     "Monitor1"
    VendorName     "Unknown"
    ModelName      "LG Electronics LG ULTRAFINE"
    HorizSync       30.0 - 135.0
    VertRefresh     40.0 - 60.0
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "NVIDIA GeForce RTX 3080"
    BusID          "PCI:45:0:0"
    Screen          0
EndSection

Section "Device"
    Identifier     "Device1"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "NVIDIA GeForce RTX 3080"
    BusID          "PCI:45:0:0"
    Screen          1
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option         "Stereo" "0"
    Option         "nvidiaXineramaInfoOrder" "DFP-5"
    Option         "metamodes" "DP-4: 1920x1080_144 +0+0"
    Option         "SLI" "Off"
    Option         "MultiGPU" "Off"
    Option         "BaseMosaic" "off"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection

Section "Screen"
    Identifier     "Screen1"
    Device         "Device1"
    Monitor        "Monitor1"
    DefaultDepth    24
    Option         "Stereo" "0"
    Option         "nvidiaXineramaInfoOrder" "DFP-3"
    Option         "metamodes" "DP-2: 3840x2160_60 +0+0 {AllowGSYNC=Off}"
    Option         "SLI" "Off"
    Option         "MultiGPU" "Off"
    Option         "BaseMosaic" "off"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection
`
"

### Expected Behavior

Connection to the host with xscreen 0 being primary display being shown.

### Operating system(s) on local side and remote side

Windows 10 > Arch Linux

### RustDesk Version(s) on local side and remote side

1.2.2 > 1.2.3

### Screenshots

`Feb 26 08:03:49 ArchLee systemd[1]: Started RustDesk.
Feb 26 08:35:13 ArchLee sudo[39420]:     root : PWD=/ ; USER=feintdoxx ; ENV=XDG_RUNTIME_DIR=/run/user/1000 ; COMMAND=/usr/lib/rustdesk/rustdesk --cm
Feb 26 08:35:13 ArchLee sudo[39420]: pam_unix(sudo:session): session opened for user feintdoxx(uid=1000) by (uid=0)
Feb 26 08:35:14 ArchLee rustdesk[39422]: flutter: launch args: [--cm]
Feb 26 08:35:14 ArchLee rustdesk[39422]: flutter: --cm started
Feb 26 08:35:14 ArchLee rustdesk[39422]: flutter: initializing FFI cm
Feb 26 08:35:14 ArchLee rustdesk[39422]: flutter: _appType:cm,info1-id:2ed436a13f684bb7aed9bced8b8f2a94,info2-name:Arch Linux,dir:/home/feintdoxx/Documents
Feb 26 08:35:14 ArchLee rustdesk[39422]: flutter: _globalFFI init
Feb 26 08:35:14 ArchLee rustdesk[39422]: flutter: _globalFFI init end
Feb 26 08:35:14 ArchLee rustdesk[39422]: flutter: registerEventHandler theme theme
Feb 26 08:35:14 ArchLee rustdesk[39422]: flutter: registerEventHandler language language
Feb 26 08:35:14 ArchLee rustdesk[39422]: flutter: registerEventHandler native_ui native_ui
Feb 26 08:35:15 ArchLee rustdesk[39422]: flutter: Bring window 'null' on top
Feb 26 08:35:15 ArchLee rustdesk[39422]: flutter: Bring window 'null' on top
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: Bring window 'null' on top
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: Null check operator used on a null value
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #0      RenderBox.size (package:flutter/src/rendering/box.dart:1988)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #1      RenderClipOval._defaultClip (package:flutter/src/rendering/proxy_box.dart:1715)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #2      _SemanticsGeometry._computeValues (package:flutter/src/rendering/object.dart:4925)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #3      new _SemanticsGeometry (package:flutter/src/rendering/object.dart:4876)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #4      _SwitchableSemanticsFragment._computeSemanticsGeometry (package:flutter/src/rendering/object.dart:4810)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #5      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4720)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4771)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #7      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4771)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #8      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4706)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #9      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4706)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #10     _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4706)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #11     _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4706)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #12     _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4771)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #13     _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4474)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #14     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:3442)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #15     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1268)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #16     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #17     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:905)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #18     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #19     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #20     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #21     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #22     _invoke (dart:ui/hooks.dart:142)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #23     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: #24     _drawFrame (dart:ui/hooks.dart:112)
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
Feb 26 08:37:05 ArchLee rustdesk[39422]: flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
Feb 26 08:37:10 ArchLee rustdesk[39422]: flutter: Bring window 'null' on top
Feb 26 08:37:10 ArchLee rustdesk[39422]: flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
Feb 26 08:37:11 ArchLee rustdesk[39422]: flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
Feb 26 08:37:36 ArchLee rustdesk[39422]: flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
Feb 26 08:37:38 ArchLee rustdesk[39422]: flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
Feb 26 08:37:41 ArchLee rustdesk[39422]: flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
Feb 26 08:37:50 ArchLee rustdesk[39422]: flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
Feb 26 08:40:49 ArchLee rustdesk[39422]: flutter: Bring window 'null' on top
Feb 26 08:57:17 ArchLee rustdesk[39422]: flutter: Bring window 'null' on top
Feb 26 09:50:35 ArchLee rustdesk[39422]: flutter: Bring window 'null' on top
Feb 26 09:50:36 ArchLee rustdesk[39422]: flutter: Bring window 'null' on top
Feb 26 09:51:58 ArchLee rustdesk[39422]: flutter: model  closed
Feb 26 09:51:58 ArchLee rustdesk[39422]: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed
Feb 26 09:51:58 ArchLee rustdesk[39422]: gtk_window_get_position: assertion 'GTK_IS_WINDOW (window)' failed
Feb 26 09:51:58 ArchLee rustdesk[39422]: gtk_window_get_size: assertion 'GTK_IS_WINDOW (window)' failed
Feb 26 09:51:58 ArchLee rustdesk[39422]: gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed
Feb 26 09:51:58 ArchLee rustdesk[39422]: gtk_window_move: assertion 'GTK_IS_WINDOW (window)' failed
Feb 26 09:51:58 ArchLee rustdesk[39422]: gtk_window_resize: assertion 'GTK_IS_WINDOW (window)' failed
Feb 26 09:51:58 ArchLee sudo[39420]: pam_unix(sudo:session): session closed for user feintdoxx`

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
