### ISSUE TITLE
Kaspersky antivirus detects as #not-a-virus:HEUR:RemoteAdmin.Win64.RustDesk.gen

### ISSUE THREAD

**Issue by Skinoku** [rustdesk/rustdesk#7334]
### Bug Description

When a computer tries to download or run the executable, the operation is blocked by Kaspersky antivirus detecting the software as #not-a-virus:HEUR:RemoteAdmin.Win64.RustDesk.gen.

### How to Reproduce

Try to download or execute the application on a Windows computer running Kaspersky security suites.

### Expected Behavior

Proper compatibility with the security suite.

### Operating system(s) on local side and remote side

Windows

### RustDesk Version(s) on local side and remote side

1.2.3-1

### Screenshots

Not applicable.

**Comment by rustdesk** [comment]
close since many duplicate
