### ISSUE TITLE
the scroll wheel fails

### ISSUE THREAD

**Issue by Userlgz** [rustdesk/rustdesk#7336]
### Bug Description

When using a mouse for Android(huawei pad) remote control of Windows 10, the scroll wheel fails

### How to Reproduce

use mouse in android

### Expected Behavior

I want to use keyboard and mouse to control compute in HUAWEI

### Operating system(s) on local side and remote side

android -> windows10

### RustDesk Version(s) on local side and remote side

1.2.3->1.2.3

### Screenshots

None

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893
ref: https://github.com/rustdesk/rustdesk/pull/1623
