### ISSUE TITLE
Enabled encryption with -K flag and have been using keys from .pub file but have had issues accessing devices over the internet. Devices on the same lan works fine over the encrypted connection but when tried to access devices over the internet. It is stuck at Connected, waiting for image attached is the screenshot.

### ISSUE THREAD

**Issue by mvyas80** [rustdesk/rustdesk#7337]
### Bug Description

Enabled encryption with -K flag and have been using keys from .pub file but have had issues accessing devices over the internet. Devices on the same lan works fine over the encrypted connection but when tried to access devices over the internet with encryption. It is stuck at Connected, waiting for image attached is the screenshot.
I have been using the key in hbbr .pub file and have made sure hbbr and hbbs both volumes have same .pub file.
Over LAN it works perfect with with encryption but over the internet it is just stuck.
server is on a ubuntu 22.04 and the client machines over the internet are windows 10 and 11 respectively.
Happening with devices over the internet.
Any help would be appreciated.

### How to Reproduce

Attached are the docker-compose-yaml file and the error.

### Expected Behavior

It should work over the internet with encryption as that would be more safe.

### Operating system(s) on local side and remote side

Windows 11 and windows 10

### RustDesk Version(s) on local side and remote side

1.2.3-1 and also on nightly version 1.2.4

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/133155749/e3079245-eb89-43fa-9ad0-8de36d56541d)
![Dc](https://github.com/rustdesk/rustdesk/assets/133155749/492ab047-9b2b-4739-81ba-9721aaa81ba1)

**Comment by rustdesk** [comment]
#763
