### ISSUE TITLE
Ctrl key does not work intermittently on Windows 11 

### ISSUE THREAD

**Issue by TuranTimur** [rustdesk/rustdesk#7351]
### Bug Description

Keyboard ctrl key does not work out of box

Keyboard mode = all (legacy, map) 

### How to Reproduce

1) run Mobaxterm  SSH terminal client  software on windows 11 ( https://mobaxterm.mobatek.net/download.html )
2) open SSH session using Mobaxterm, and join ssh connection. 
3) run Ctrl + C on ssh terminal, and find that it does not work 

workaround: on Mobaxterm, open another terminal tap, then suddenly ctrl key works 

### Expected Behavior

Ctrl + C on ssh terminal should work without any workaround 

### Operating system(s) on local side and remote side

Arch linux Gnome desktop -> windows 11 (actually windows server 2025)

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3-1-x86_64  

### Screenshots

[https://youtu.be/h8J8MmbhDas](https://youtu.be/h8J8MmbhDas)

### Additional Context

Hi. I know this is strange, but I've tested many times and I confirm that it is really happening.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367
