### ISSUE TITLE
After clicking "enable service" Rustdesk refuses to operate

### ISSUE THREAD

**Issue by biggestsonicfan** [rustdesk/rustdesk#7355]
### Bug Description

I was connected to a remote system and decided to "enable service" while connected. Rustdesk then force-minimized and began an infinite loop where every second my cursor would show "busy". Attempting to restore Rustdesk from the tray resulted in the application minimizing again. I uninstalled Rustdesk, however running the executable from releases results in Rustdesk force closing,I can not reinstall.

### How to Reproduce

(Assumed)

- Install Rustdesk from the 1.2.3-1 release on a Windows 10 system, but do not enable the service.
- Connect to a remote computer.
- Click the "Enable service" hyperlink at the bottom of the application while connected.
- - I did notice that on the remote computer it suggested to set up my own server instead of the "Enable service" option

### Expected Behavior

Rustdesk should close, install the service, then allow Rustdesk to be launched again.

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3-1 -> 1.2.3-1

### Screenshots

As I can no longer get Rustdesk running on my host, I am only including a relevant entry I am finding using ProcMon

![Screenshot 2024-03-10 150800](https://github.com/rustdesk/rustdesk/assets/9744201/f784144b-eb2c-4b97-8bb8-1867dd26b8d0)

### Additional Context

There doesn't appear to be a Rustdesk service running or any config files Rustdesk is reading to inform itself to force close.

**Comment by biggestsonicfan** [comment]
After a reboot, I was able to replicate the issue while recording.

https://github.com/rustdesk/rustdesk/assets/9744201/7d3fff9e-5947-4a6c-adf7-a41d6a099e26

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/7342

**Comment by biggestsonicfan** [comment]
How was this unreproducible? I managed to reproduce it, which is how I got footage of it.

**Comment by biggestsonicfan** [comment]
Running a fresh install using [Windows 10 Media creator](https://www.microsoft.com/en-us/software-download/windows10) to create an ISO and installing in [VirtualBox 7.0](https://www.virtualbox.org/wiki/Downloads) I was able to reproduce the issue 100%. Please remove the "unreproducible" label.


https://github.com/rustdesk/rustdesk/assets/9744201/ba7dd133-71b2-4006-8dc0-59e19d71ffb1

**Comment by devdevfork** [comment]
This bug is indeed weird and happened to me sometimes, the solution would be if that happens terminate the rustdesk service via task manager, and re-launch rustdesk.

**Comment by biggestsonicfan** [comment]
> This bug is indeed weird and happened to me sometimes, the solution would be if that happens terminate the rustdesk service via task manager, and re-launch rustdesk.

Or maybe not have an option available during a remote session that will cripple remotedesk. It can be prompted when there is no remote session.

**Comment by biggestsonicfan** [comment]
You gonna remove the `unreproducible` tag yet or what? It is 100% reproducible even on a fresh environment.

**Comment by biggestsonicfan** [comment]
Revisiting this issue as requested per https://github.com/rustdesk/rustdesk/issues/7342#issuecomment-2189226151

1. A clean, baseline environment was created using the [Windows 10 Media Creation Tool](https://www.microsoft.com/en-us/software-download/windows10) once again. An ISO was made.
2. My [VirtualBox](https://www.virtualbox.org/wiki/VirtualBox) was updated to 7.0.20.
3. Windows 10 was installed in a virtual machine in offline mode, then updates were installed. Edge has not been launched for the first time yet.
4. The baseline environment was cloned to become a second environment in which the two virtual environments will be connected to eachother.
5. Rustdesk 1.3.0 was installed on both virtual machines, and attempting to reproduce the issue failed.
6. Rustdesk 1.3.0 was installed on the host computer to connect to a remote virtual machine also failed to reproduce the issue.
7. Rustdesk 1.3.0 was uninstalled from the host computer and Rustdesk 1.2.3-1 was reinstalled. It was then connected to the previously used remote physical machine in https://github.com/rustdesk/rustdesk/issues/7355#issuecomment-1987430919 and the issue was successfully reproduced.
8. Rustdesk 1.2.3-1 was uninstalled to reinstall Rustdesk 1.3.0, however Rustdesk 1.3.0 now refuses to launch, seemingly the carry-over bug from 1.2.3-1 that crippled Rustdesk 1.2.3-1 from being used further, which is why I filed this issue.
9. After rebooting and launching Rustdesk 1.3.0, Rustdesk reports "Your installation is lower version" (questionable grammar)
10. After confirming Rustdesk 1.2.3-1 was indeed uninstalled, I proceeded with the "Click to upgrade" button.
11. Interestingly, upon launching the installed Rustdesk 1.3.0, I see "Service is not running", where it always was after installing 1.3.0 previously.
12. Clicking "Start service" did not cripple the software in an infinite softlock.

I'd say the bug is resolved, except the developers refused to acknowledge the bug existed in the first place. It would have been nice for them to test the bug by reproducing the steps _exactly as written_ but their apparent refusal to do so has left me wondering for months if it would ever get fixed, only for it to magically disappear upstream somewhere either in their code or some cargo dependency. Who knows, maybe it was magic, but I will not be using Rustdesk going forward because of this inability to adequately acknowledge bugs and simply sweep issues into a condensed "tracked" list. Which wasn't seemingly tracked at all. I created a discussion about why Rustdesk does not simply disable issues on github and create seperate issue tracking site, but the discussion was seemingly nuked without being informed why.

If the developers refuse to acknowledge their bugs, blanket sweep their bugs into a "tracker" to keep the issue count lower than it really is, and can't elaborate on where a bug was fixed upstream in their own code or in a dependency, I can not trust the software they produce. That, in my humble opinion, is more dangerous and reckless than a software developed in a memory-unsafe language.

**Comment by qu4542** [comment]
my sister is blind and she cant click the stgart service button.
please make this barrier free
