### ISSUE TITLE
Invalid/misspelled Relay Server Key causes silent pairing failures

### ISSUE THREAD

**Issue by botekp** [rustdesk/rustdesk#7358]
### Bug Description

Experienced behaviour (current version of Rustdesk) :
1) Rustdesk self hosted relay on WAN; client and server on the same LAN
2) Invalid/misspelled Relay Server Key string is typed into the client Rustdesk GUI
3) "Always connect via relay" is checked on the client
4) User Connect session gets stuck on dialog "Connecting" and eventually gives up. User is not notified that used Relay Server Key is invalid. HBBR relay service logs "new relay request ..." but never pairs and never logs error message notifying about invalid Relay Server Key used by the user

Expected behaviour:
1) User gets notified immediately that his Connect session failed due to invalid Relay Server Key. Would it also be possible to fix up clipboard text pasting into Android servers, because typing those long server keys will always cause misspellings and it currently just silently fails when pairing at relay.
2) HBBR service logs error message notifying about invalid Relay Server key

* I think the key to fixing this problem is in relay_server.rs at line 419:
     if !key.is_empty() && rf.licence_key != key {
                    return;
                }

* It just needs to get a bit more verbose so user/admin knows what's going on

* This bug is easily mistaken for NAT hairpinning problem people have been battling with as per https://github.com/rustdesk/rustdesk/wiki/FAQ#deploy-rustdesk-server-in-intranet . But really this is a separate problem that only has similar symptoms.

Thanks for fixing it! P.

### How to Reproduce

as above

### Expected Behavior

as above

### Operating system(s) on local side and remote side

n/a

### RustDesk Version(s) on local side and remote side

current

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/4343002/b1c2e586-90dc-492f-8f83-0f24f3805893)

**Comment by rustdesk** [comment]
#763

**Comment by botekp** [comment]
Are you sure this is not a problem with this software?
