### ISSUE TITLE
Failed to run build.py

### ISSUE THREAD

**Issue by jgcoelhof** [rustdesk/rustdesk#7360]
### Bug Description

I cloned the repository and when trying to build with the build.py script I receive the following errors:

First compilation: 

Finished release [optimized] target(s) in 3m 22s
    Bundling rustdesk_1.2.4_amd64.deb
    Finished 1 bundle at:
        /home/joao/Documentos/dev/rustdesknemeu/rustdesk/target/release/bundle/deb/rustdesk_1.2.4_amd64.deb
cp: unable to get status of 'DEBIAN/*': No such file or directory
cp: unable to get status of 'pam.d/rustdesk.debian': No such file or directory
cp: unable to get status of 'libsciter-gtk.so': No such file or directory
Error occurred when executing: cp libsciter-gtk.so tmpdeb/usr/lib/rustdesk/. Exiting.

After I compile the first time, it creates the tmpdeb folder and the rustdesk.deb file (installs but doesn't work).

Second compilation: 

Finished release [optimized] target(s) in 2m 51s
    Bundling rustdesk_1.2.4_amd64.deb
    Finished 1 bundle at:
        /home/joao/Documentos/dev/rustdesknemeu/rustdesk/target/release/bundle/deb/rustdesk_1.2.4_amd64.deb
dpkg-deb (subprocess): unexpected pre-existing tmpdeb/DEBIAN pathname: File exists
dpkg-deb: error: tar subprocess returned exit status 2 error
Error occurred when executing: dpkg-deb -R rustdesk.deb tmpdeb. Exiting.

### How to Reproduce

Clone rustdesk client, install VCPKG then run build.py

### Expected Behavior

Achieve efficient application build

### Operating system(s) on local side and remote side

Ubuntu 22.04.2 LTS

### RustDesk Version(s) on local side and remote side

1.2.4

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/95655454/89c72057-8b5f-40f1-8ba3-98d984625c28)
![image](https://github.com/rustdesk/rustdesk/assets/95655454/b657a9ac-8d8d-4c8a-b200-f888a9b894c3)

**Comment by rustdesk** [comment]
#763
