### ISSUE TITLE
Keyboard input fails (rustdesk 1.2.3+)

### ISSUE THREAD

**Issue by Dzordzu** [rustdesk/rustdesk#7362]
### Bug Description

Using any rustdesk above 1.2.2 ends up with malfunctioning remote keyboard input control. None of the available input modes allows user to pass the input to the target. Input from the older client versions (ex. 1.2.2, android version) works. 

Issue appears to be system independent - I've noticed [some discussions](https://github.com/rustdesk/rustdesk/discussions/7305) pointing the similar issue with Windows. 

### How to Reproduce

Use any client 1.2.3+. No keyboard input is sent to the server. With client 1.2.2 everything works as expected. 

(Almost) all the binaries are self built. Building 1.2.2 required cargo update, `tray-icon` dependency replacement with the one from tauri and some minor code tweaks. 

### Expected Behavior

The keyboard input is properly passed to the client window, and properly sent to the server

### Operating system(s) on local side and remote side

Linux (gentoo, openrc, kernel 6.6.13) -> Linux (gentoo, openrc, kernel 6.7.7)

### RustDesk Version(s) on local side and remote side

1.2.3+ -> 1.2.2+

## Working 1.2.2 client
![2024-03-12 01-32-27](https://github.com/rustdesk/rustdesk/assets/17514622/4acc8596-cd18-4d1d-9a2d-36d70630e020)

## Problematic 1.2.3+ client
![2024-03-12 01-39-27](https://github.com/rustdesk/rustdesk/assets/17514622/36773964-2efa-43ea-b0a8-4f4a7c08f85f)
 

### Additional Context

I've tested it on a several machines. Clients were linux/android based. Servers were linux based. I suppose I've used all the possible permutations. 

Used machines:
Gentoo Linux (kern. 6.7.7, openrc) 
Gentoo Linux (kern 6.6.13, openrc)
Archilnux (kern 6.X, systemd)
Android

**Comment by rustdesk** [comment]
#763

**Comment by Dzordzu** [comment]
@rustdesk It's not about a build!

**Comment by rustdesk** [comment]
Please report again, if there is problem with our nightly build (run on both sides), https://github.com/rustdesk/rustdesk/releases/tag/nightly, and try out different keyboard mapping mode, https://github.com/rustdesk/rustdesk/issues/

**Comment by Dzordzu** [comment]
> Please report again, if there is problem with our nightly build 

It's not only on nightly, but also on released 1.2.3 version

> and try out different keyboard mapping mode

The mapping mode didn't work at all for me. For neither of the tested versions

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by rustdesk** [comment]
BTW, please do not report your build's problem here.
