### ISSUE TITLE
The "deadline has elapsed" error occurs for the connection after KEY is forcibly specified.

### ISSUE THREAD

**Issue by shuxin8795** [rustdesk/rustdesk#7363]
### Bug Description

connection error, ["deadline has elapsed"]. There is always a connection in progress, triggering ["deadline has elapsed"] every 15 seconds or so (triggering 0.5 seconds)

### How to Reproduce

I'm new here and my English isn't very good. I can only describe my deployment process completely

Server system：CentOS7.6-Docker24
Approach:：Docker deployment
Reproduce the process：
1、docker installation
curl -fsSL https://get.docker.com | bash -s docker --mirror Aliyun
yum install docker-compose-plugin
 systemctl start docker
 systemctl enable docker
2、Create configuration file
mkdir -p /root/rustdesk
touch /root/rustdesk/docker-compose.yml（Add the official configuration here）
3、Execute the download image and start docker container
cd /root/rustdesk
docker compose up -d
4, test whether the normal connection: the connection is normal.
5、Configuration file hbbs and hbbr add -k _ parameter behind
6, reload the container:
cd /root/rustdesk/
docker compose pull
docker compose up -d
7、View the public key
8,、Execute reboot
9、test whether the normal connection: connection error, ["deadline has elapsed"]. There is always a connection in progress, triggering ["deadline has elapsed"] every 15 seconds or so (triggering 0.5 seconds)

### Expected Behavior

连接正常

### Operating system(s) on local side and remote side

CentOS7.6-Docker24

### RustDesk Version(s) on local side and remote side

1.1.10-3

### Screenshots

![c74f28b255ec4606a3d8c12682af675d](https://github.com/rustdesk/rustdesk/assets/65381978/0950fbdc-5d00-475f-86a6-8fa62e34c3da)

**Comment by rustdesk** [comment]
#763
