### ISSUE TITLE
MacOS Black screen after opening the application

### ISSUE THREAD

**Issue by RosiersRobin** [rustdesk/rustdesk#7369]
### Bug Description

After installing rustdesk (usining brew or the .dmg) I can start the application, but then it's just a black window.

### How to Reproduce

Install rustdesk via brew (brew install --cask rustdesk) or by downloading the release from github and start the application.

### Expected Behavior

I epect the application to run

### Operating system(s) on local side and remote side

osx -> android

### RustDesk Version(s) on local side and remote side

1.2.3-1 -> 1.2.3-1

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/5263188/d0a86241-62d1-4ebb-a8b2-dbbeffe5b6b2)

### Additional Context

Is there something I need to enable? I'm running an Macbook pro M3 (14.3.1 (23D60)

**Comment by rustdesk** [comment]
Try out the nightly build please, https://github.com/rustdesk/rustdesk/releases/tag/nightly

**Comment by RosiersRobin** [comment]
That one worked! 👌 

I do however have issues with an older android version that it doesn't want to install...
