### ISSUE TITLE
Licensing error on free version.

### ISSUE THREAD

**Issue by aaronouthier** [rustdesk/rustdesk#7371]
### Bug Description

I have setup my own server on Linux Docker (Ubuntu 2.04). When I try to connect to another machine (both connected to the same Relay server, with the correct key), I am told that the connection is not allowed, due to an invalid or expired license.

I have never had or used a license. This is my first time using this product, aside from a few test runs with the public server.

### How to Reproduce

Installed app on both PCs. Installed hbbr and hbbs docker components, and 'upped' with docker-compose up -d .
Attempted to connect to a friend's pc to help them with an issue.

### Expected Behavior

To be able to connect to emote machine with out issues...

### Operating system(s) on local side and remote side

Window 10 22H2 to Windows 10 22H2

### RustDesk Version(s) on local side and remote side

1.2.3-1 on both ends.

### Screenshots

![Capture](https://github.com/rustdesk/rustdesk/assets/10721430/22ab4528-6b7b-428b-8f49-bd3b1c619718)

### Additional Context

Experienced linux and docker user.

**Comment by rustdesk** [comment]
#763
