### ISSUE TITLE
[Android TV] Cannot control the app using TV remote

### ISSUE THREAD

**Issue by TtuxX** [rustdesk/rustdesk#7372]
### Bug Description

Hi there (and I've checked but all my apologies in advance if this is a duplicate),

I'm using a Nvidia Shield and would be happy to be able to navigate/use the app with the Shield TV remote stick.

I use the Rustdesk Android TV to cast my computer screen to my TV, and I would love to initiate connection from Rustdesk Android TV app to my computer using the TV remote only.
It is however not possible and I have to use workarounds (Nvidia Shield TV android mouse app) to navigate through the Rustdesk Android TV app.

Could you please help me for this ? 

### How to Reproduce

Try to use the Rustdesk android app using the TV stick (remote) and realise it is not possible and it does not work as intended.

### Expected Behavior

Be able to select any item on the screen (not possible) and to click on any of them (click does not work as OK button does nothing in the Rustdesk app).

### Operating system(s) on local side and remote side

Nvidia Shield Androit TV v9.1.1 (Android 11) -> Ubuntu Mate 23.04

### RustDesk Version(s) on local side and remote side

1.2.4 -> 1.2.4

### Screenshots

Nothing too specific visually

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893
