### ISSUE TITLE
cannot build nightly windows builds

### ISSUE THREAD

**Issue by devdevfork** [rustdesk/rustdesk#7377]
### Bug Description

requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /tasks/sign (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002069A22D548>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Error: Process completed with exit code 1.

### How to Reproduce

try to build nightly build

### Expected Behavior

should be building fine.

### Operating system(s) on local side and remote side

git

### RustDesk Version(s) on local side and remote side

any

### Screenshots

will post if needed

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/a314f59db9e50f1c77723d92dc9f6713246392d5

**Comment by devdevfork** [comment]
thanks
