### ISSUE TITLE
android's keyboard not showing but still clickable 

### ISSUE THREAD

**Issue by lovitus** [rustdesk/rustdesk#7379]
### Bug Description

- unable to type anything on android device , 
- screen keyboard not showing , 
- if click the screen could type some words
 

### How to Reproduce

- use pc to control an android device , give all permission 
- click input box (no keyboard pop up ,  and no type if you press key on PC side ) 
- click the android's screen where the keyboard should appear ( there is no onscreen keyboard but you could type something)

### Expected Behavior

- shows keyboard normally 
- type on PC side could send the key event to Android side 

### Operating system(s) on local side and remote side

Win10 --> android 13

### RustDesk Version(s) on local side and remote side

1.2.3 for both (latest)

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/14361541/5a02d5c7-b4a6-412f-b2bf-751520809735)

### Additional Context

have tried other IMEs , same problem .

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893

**Comment by rustdesk** [comment]
https://twitter.com/rustdesk/status/1721795544689922168

**Comment by wutongskype** [comment]
I also had the same problem. The Android phone as the controlled end could not display the on-screen keyboard and could not input Chinese.

Mobile phone: Redmi note12 turbo
OS: China licensed version > MIUI 14.0.23 (TMRCNXM)
rustdesk ver : 1.30
