### ISSUE TITLE
Webconsole - minimum characters for LDAP users

### ISSUE THREAD

**Issue by CyrosX** [rustdesk/rustdesk#7401]
### Bug Description

It is not possible to login with LDAP accounts consisting of less than four characters.
An error message appears:
"The name is too short, at least 4 characters"

### How to Reproduce

Login with LDAP credentials

### Expected Behavior

Being able to login

### Operating system(s) on local side and remote side

Linux - Docker

### RustDesk Version(s) on local side and remote side

RustDesk Server Pro 1.1.14-7

### Screenshots

<img width="419" alt="webconsole" src="https://github.com/rustdesk/rustdesk/assets/15161462/febe7bc2-39fe-43fa-9e2c-6945854b0e6a">

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.2.0
