### ISSUE TITLE
Remote user can access and change settings of rustdesk by using tab/arrows/space keys to navigate thru all menus

### ISSUE THREAD

**Issue by nerozero** [rustdesk/rustdesk#7402]
### Bug Description

Remote guest can can access almost all settings of the host machine's rustdesk

### How to Reproduce

From remote machine: 

- Make rustdesk host window active ( by clicking at the window title )
- use tab/arrows  keys to navigate thru entire menus, including settings ( difficult to guess the current location but possible).

sometimes during tab keys content of the rustdesk window slides to the left or right.

Once input control is selected, remove guest can change values. Including unlocking security settings.

Tested on Linux->Windows7 in virtualbox, but i'm sure this can be possible on any machine regardless OS.

### Expected Behavior

Remote guest should not have any access to change host machine settings

### Operating system(s) on local side and remote side

linux mint -> windows7 (in virtualbox vm)

### RustDesk Version(s) on local side and remote side

1.2.3-1

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/18283531/e12bc5ea-b564-4c2e-936d-3496afebb4f8)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2680
