### ISSUE TITLE
No program is associated to execute this action while installing (windows 7)

### ISSUE THREAD

**Issue by wadih** [rustdesk/rustdesk#7409]
### Bug Description

Running rustdesk works when double clicking.

Then I click on Install, and click "Accept and Install", and that's when the error appears and install is aborted: 

![Screenshot from 2024-03-16 10-09-20](https://github.com/rustdesk/rustdesk/assets/1222066/9a72f76e-515c-4e5f-9f61-1b7f0ed7ea6f)

I tried unchecking the options of "Create start menu shortcut" and "Create desktop icon", but the error still appears.

I set the executable's Compatibility mode = Windows 7 , but still getting this error .

The message is in french, and translated in english means: 

```
ruskdesk://
No program is associated to execute the required action. Install a program, or 
if it's already the case, create an association in the Control Panel in Default 
Programs.
```

### How to Reproduce

Double click on rustdesk-1.2.3-1-x86_64.exe
Click on "Install"
Click on "Accept and Install"

### Expected Behavior

Program would get installed

### Operating system(s) on local side and remote side

Windows 7 SP1

### RustDesk Version(s) on local side and remote side

1.2.3-1

### Screenshots

![Screenshot from 2024-03-16 10-09-20](https://github.com/rustdesk/rustdesk/assets/1222066/5ba62a79-556d-4ee9-9b78-abcd7562cce7)

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
use the sciter 32 versino please.

**Comment by wadih** [comment]
I am willing to find a solution, I think everything is almost perfectly working, but the installation does a single step which seems isn't working on that machine. 

It seems the installer is trying to create a rustdesk:// schema and that step doesn't work, and the installation stops there. 

I could try to create the schema manually in regedit .

Edit: Ok trying the sciter 32 version now

**Comment by wadih** [comment]
sciter32 version has the same issue with that "rustdesk://" schema step. 

It seems the failure happens at Windows level so no additional details on what exactly fails. 

Perhaps I can start the installer with logging on and look at the final step before failure?

**Comment by rustdesk** [comment]
no log

**Comment by wadih** [comment]
Ok. I will try to think about it, and check the source code.

I tried other previous versions, I think one of them worked when I uncheck the "add shortcuts" options, but it was an older version.

**Comment by rustdesk** [comment]
Thanks

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/blob/6cbbb6498fbab1b75b70fa6b5bd5512231eeaea5/src/platform/windows.rs#L1091

**Comment by rustdesk** [comment]
You can try `rustdesk.exe --silent-install 1` in command line. You will see where it stops.

**Comment by wadih** [comment]
I found a solution. 

When right-clicking on the sciter .exe and choosing "Resolve compatibility issues", windows recommends setting Windows XP SP2 compatibility. 

Then I do this, and installation succeeds! 

It only works on sciter .exe version, the other version doesn't have Windows XP SP2 availability in compatibility mode, only Windows Vista, but it doesn't work.

**Comment by rustdesk** [comment]
@21pages follow it up later, including 1.2.4 sciter does not work because of bcryptprimitives.dll missed, check which crate introduce this.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/7503
