### ISSUE TITLE
Unknown error when logging in using self host server

### ISSUE THREAD

**Issue by herunyu** [rustdesk/rustdesk#7410]
### Bug Description

When try to log in, it shows an unknown error.

### How to Reproduce

1. Use self host server
2. try to log in and pop up the error

### Expected Behavior

Should be able to log in

### Operating system(s) on local side and remote side

Windows 11, Mac OS 14

### RustDesk Version(s) on local side and remote side

1.2.3-1

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/5023850/0ada725c-1fd5-4260-843c-54b7b16faaef)

**Comment by rustdesk** [comment]
#763
