### ISSUE TITLE
Custom Client Default Settings Not Working

### ISSUE THREAD

**Issue by devNull2and1** [rustdesk/rustdesk#7417]
### Bug Description

If i set default settings for custom client build, they are not set under `%AppData%\Roaming\%CustomClientAppName\*.toml`
Here my default settings:

```
show_monitors_toolbar=Y
show_remote_cursor=Y
zoom-cursor=Y
enable_file_transfer=Y
view_style=adaptive
collapse_toolbar=Y
enable-check-update=N
temporary-password-length=10
direct-server=Y
allow-remote-config-modification=Y
enable-audio=N
enable-open-new-connections-in-tabs=N
theme=dark
```

### How to Reproduce

build custom client, start it, watch romaing folder for settings to take place

### Expected Behavior

default settings should be loaded.

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

Newest

### Screenshots

not needed

**Comment by rustdesk** [comment]
wait for our doc please

**Comment by devNull2and1** [comment]
@rustdesk where can i find the documentation? upgraded to latest version, settings default/overwrite still not possible.

**Comment by rustdesk** [comment]
We will update here, https://github.com/rustdesk/rustdesk-server-pro/discussions/212, please subscribe.
Apologize, no update yet since still on dev, the doc has to be delayed.
