### ISSUE TITLE
Mouse Wheel Scroll "Up" Not Working

### ISSUE THREAD

**Issue by vical22** [rustdesk/rustdesk#7419]
### Bug Description

I am currently using the latest 1.2.4 Nightly build.

When I scroll "down" a page, it works fine, but the scroll "up" is not working.

The same behaviour for folders, webpages, word, etc.

### How to Reproduce

Scroll down works perfectly.

Scroll "up" is not working.

### Expected Behavior

When scrolling up the mouse wheel, pages scroll up.

### Operating system(s) on local side and remote side

Win 11 -> MacOS Sonoma

### RustDesk Version(s) on local side and remote side

1.2.4 -> 1.2.4

### Screenshots

https://youtube.com/shorts/tbSZp90rg6A

**Comment by 21pages** [comment]
Can't reproduce, both side latest version.
[c508521610_20240318193652096_av1.webm](https://github.com/rustdesk/rustdesk/assets/14891774/f2342342-a549-4c07-851e-3f650d778ec8)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by stealthlab85** [comment]
Same problem here. Seems to be a problem with screen resolution, if I change screen resolution from rustdesk the scroll up seem to be working, but visual is not very good, i think is related to retina scaling or something similar.

**Comment by clspeter** [comment]
Same problem here. If enable HiDPI, Scrolling up will stop working
[Disable HiDPI](https://github.com/rustdesk/rustdesk/assets/16301430/187abb79-9823-4a4a-8342-f5efa23c6bf6)
[Enable HiDPI](https://github.com/rustdesk/rustdesk/assets/16301430/f6eaffed-21af-48e2-902e-711635152929)

**Comment by 21pages** [comment]
@clspeter Thans for your feedback, it can be reproduced with HiDPI

**Comment by rustdesk** [comment]
The fix is merged, please test if the new nightly build is ready.

**Comment by clspeter** [comment]
@21pages Thanks for quick fix!
