### ISSUE TITLE
Mouse clicks accidently once you touch the screen

### ISSUE THREAD

**Issue by hexman1999** [rustdesk/rustdesk#7421]
### Bug Description

Controling from android makes accedental clicks upon moving the cursor in mouse mode

### How to Reproduce

Make click on tap only

### Expected Behavior

Move without click

### Operating system(s) on local side and remote side

Android -> windows 

### RustDesk Version(s) on local side and remote side

1.2.3-1-> 1.2.3-1

### Screenshots

As described but I may upload later

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367
