### ISSUE TITLE
Bug: Can not click Allow button on v1.2.3-1 or early version

### ISSUE THREAD

**Issue by davidngrc** [rustdesk/rustdesk#7425]
### Bug Description

A phone client connected to a ubuntu host,
the 2nd device, in my case pubic windows pc, make a new connection to the same ubuntu host.
on the phone client, try to click "Allow" to allowing the public windows pc to connect to ubuntu host.
the "Allow" button is not clickable in the phone client.

### How to Reproduce

1. version installed
PC1, Ubuntu 22.04, installed v1.2.3-1
PC2, windows 11 Pro, installed v1.2.3-1
Phone, Samsung Android 12, installed v1.2.3-1

2. PC1 Ubuntu is the PC we want to control.
    it set up like allow saved password or one time password to login.

3. PC 2 is a windows PC in a public place.
    I don't want to input my ubuntu remote PC1 password into this public PC

4. in my android phone, I saved the PC1 ubuntu password
    so I auto login to PC1 ubuntu without any password in my android phone.

5. I click the connect button in the PC2 public window PC.
    now on my android phone, seeing in this app, I can see in PC1 ubuntu, a windows popup, saying someone is try to login, two options, "Allow" or "Cancel".
     I try to move my mouse to click "Allow", the mouse curse changed, but I can't click it, no matter how hard I try.

### Expected Behavior

however, I can click the "Allow" button in AnyDesk, same phone, same ubuntu.

### Operating system(s) on local side and remote side

Samsung Android 12 -> Ubuntu 22.04

### RustDesk Version(s) on local side and remote side

1.2.3-1

### Screenshots

![Untitled](https://github.com/rustdesk/rustdesk/assets/33573086/6f71fc49-61c3-40cf-aa3a-78997c0ea80c)

**Comment by davidngrc** [comment]
I dont get it, AnyDesk can connect in this way.
why RustDesk dont?

**Comment by davidngrc** [comment]
@rustdesk I just upgrade client and server to v1.2.6, this issue still exists.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/8660 This option is for custom client of Pro only.
