### ISSUE TITLE
ARMv7 Build for Android

### ISSUE THREAD

**Issue by ata-star** [rustdesk/rustdesk#743]
There are still alot of armv7 droids out there, please add at least an option to build that.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/611

**Comment by rustdesk** [comment]
It seems I underestimated the market ratio of arm32.

**Comment by rustdesk** [comment]
Some 64bit arm still uses ARMv7a abi, e.g. samsung a11

**Comment by rustdesk** [comment]
@ata-star

**Comment by rustdesk** [comment]
@ata-star https://github.com/rustdesk/rustdesk/files/8885404/rustdesk-armeabi-v7a-release.zip

**Comment by areful** [comment]
The armeabi-v7a apk works well on Android 7.0 emulator, but cannot work on Android 6.0.

part of error log:
... dlopen failed: cannot locate symbol "getifaddrs" referenced by "/data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so"
 ...

apk from here:
[rustdesk-1.2.0-armv7-linux-androideabi-release-signed.apk](https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-armv7-linux-androideabi-release-signed.apk)

**Comment by rustdesk** [comment]
> getifaddrs

https://github.com/rustdesk/rustdesk/blob/632f9e264c23468b2d38a5c440bd20207be61773/Cargo.toml#L60

used by lan.rs

Sadly, no plan to fix this for android 6.

**Comment by areful** [comment]
> > getifaddrs
> 
> https://github.com/rustdesk/rustdesk/blob/632f9e264c23468b2d38a5c440bd20207be61773/Cargo.toml#L60
> 
> used by `lan.rs`
> 
> Sadly, no plan to fix this for android 6.

Thanks for your reply.

**Comment by areful** [comment]
> default-net

I changed the library 'default-net' version to 0.14.1, and then the app can run on Android 6.0 mobile. 

But remote controller can only display the mobile's screen, cannot control the mobile. 
Any idea?

**Comment by areful** [comment]
> > default-net
> 
> I changed the library 'default-net' version to 0.14.1, and then the app can run on Android 6.0 mobile.
> 
> But remote controller can only display the mobile's screen, cannot control the mobile. Any idea?

Now I found the problem is caused by code in InputService.kt. It uses android.accessibilityservice.GestureDescription that is supported in Anddroid API 24 (Android 7.0).

Maybe it could work on Android 6.0 if I modify the function 'onMouseInput()'.

**Comment by rustdesk** [comment]
Go ahead.

**Comment by jmbajo** [comment]
> > > default-net
> > 
> > 
> > I changed the library 'default-net' version to 0.14.1, and then the app can run on Android 6.0 mobile.
> > But remote controller can only display the mobile's screen, cannot control the mobile. Any idea?
> 
> Now I found the problem is caused by code in InputService.kt. It uses android.accessibilityservice.GestureDescription that is supported in Anddroid API 24 (Android 7.0).
> 
> Maybe it could work on Android 6.0 if I modify the function `onMouseInput()`

Hi, Did you continue working on that? I could help in that case. I need to make RustDesk compatible with Android 6.0

**Comment by areful** [comment]
> > > > default-net
> > > 
> > > 
> > > I changed the library 'default-net' version to 0.14.1, and then the app can run on Android 6.0 mobile.
> > > But remote controller can only display the mobile's screen, cannot control the mobile. Any idea?
> > 
> > 
> > Now I found the problem is caused by code in InputService.kt. It uses android.accessibilityservice.GestureDescription that is supported in Anddroid API 24 (Android 7.0).
> > Maybe it could work on Android 6.0 if I modify the function `onMouseInput()`
> 
> Hi, Did you continue working on that? I could help in that case. I need to make RustDesk compatible with Android 6.0

It seems could only control the app itself, below Android 7. Maybe we can dispatch the event using remote service, seemed worth a try.

If your phone's ABI is arm64-v8a, then just dispatch the events to your app's top activity.

If the ABI is armeabi-v7a, you should also compile the .so for the special ABI. 
It takes us a lot of time. The offcial code of libvpx cannot works on armeabi-v7a, so we compile it manually, uses this: https://github.com/cmeng-git/vpx-android.
