### ISSUE TITLE
Instantly reconnecting with every single key press

### ISSUE THREAD

**Issue by awad0** [rustdesk/rustdesk#7430]
### Bug Description

Self hosted (Version 1.2.3-1). Client on a remote Catalina Mac, static password, Rustdesk service installed. Local client on Sonoma Mac. 

### How to Reproduce

I can connect with no issues and the connection is stable. Until a key gets pressed. Then the connection is instantly interrupted and the dialog for reconnection appears. Sometimes a restart fixes that. macOS on-screen keyboard still works. 

### Expected Behavior

Pressing any key without connection interruption.

### Operating system(s) on local side and remote side

macOS <-> macOS

### RustDesk Version(s) on local side and remote side

1.2.3-1 <-> 1.2.3-1

### Screenshots

<img width="1431" alt="Bildschirmfoto 2024-03-19 um 18 12 03" src="https://github.com/rustdesk/rustdesk/assets/117205836/aa1da959-086b-46d4-bba2-cd78f4e0ba95">

### Additional Context

RustDesk Dock icon bounces every few seconds on the remote machine.

**Comment by rustdesk** [comment]
We do not dev against Catalina any more, please report if you have this issue on controlled Sonoma.
