### ISSUE TITLE
Auto Screen-switch / Mouse follow

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#7439]
### Discussed in https://github.com/rustdesk/rustdesk/discussions/7437

<div type='discussions-op-text'>

<sup>Originally posted by **Benno1308** March 20, 2024</sup>
### Short Summary
I would like to request a feature that allows the client to automatically follow the remote mouse cursor.

### Scenario
1. I'm connected to someone via RustDesk
2. The remote side has multiple monitors connected
3. The remote side is actively using his mouse across all monitors

### Expected Behaviour
Whenever the remote side moves the mouse cursor to a new monitor, 
I expect my RustDesk client to automatically follow the cursor to that monitor.

This can also be extended to be based on which window is currently focused, 
allowing to follow the remote work based on either where the mouse is, or which window is currently active.

### Bounty
I am willing to add a bounty of 750 USD via [polar.sh](https://polar.sh/rustdesk/rustdesk), or a similar service, if there is be a reasonable timeline to add this feature

### Reference
#2059 (Creating a seperate feature request as this one adds the request for follow window focus)

https://support.anydesk.com/knowledge/display
```
If the remote device has multiple monitors, enabling "Follow remote cursor" automatically switches the AnyDesk view to the correct monitor if the remote user moves the cursor to a different monitor.
If the remote device has multiple monitors, enabling "Follow remote window focus" automatically switches the AnyDesk view to the display where the foreground window is located.
```

</div>

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/rustdesk) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/rustdesk/rustdesk/issues/7439">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/rustdesk/rustdesk/issues/7439/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/rustdesk/rustdesk/issues/7439/pledge.svg">
</picture>
</a>

**Comment by Benno1308** [comment]
![grafik](https://github.com/rustdesk/rustdesk/assets/954915/68e8d29a-b4ca-41ac-a1ba-a59c81ed9e69)

Issue has been funded

**Comment by emilwidlund** [comment]
I'm topping up another $150 on behalf of @polarsource :)

**Comment by sahilyeole** [comment]
I'm on it! :)

**Comment by rustdesk** [comment]
@sahilyeole you'd better run AnyDesk first before writing code. Be considerate and pay attention to details.

- [ ] How about if mutiple connections?
- [ ] Should we switch on local side or remote side, which side is easier and less code?

**Comment by rustdesk** [comment]
@emilwidlund I chose wrong country while setup. Now I can not continue.

![image](https://github.com/rustdesk/rustdesk/assets/71636191/da38f254-173b-4540-8452-9a86a059e6a9)

**Comment by emilwidlund** [comment]
> @emilwidlund I chose wrong country while setup. Now I can not continue (always show your debit card comes from Singapore, not US).
> 
> BTW, I already have an stripe accout with [info@rustdesk.com](mailto:info@rustdesk.com), why do I need to create another one with the same email?
> 
> ![image](https://private-user-images.githubusercontent.com/71636191/314912715-da38f254-173b-4540-8452-9a86a059e6a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDk1NTUsIm5iZiI6MTcxMTAwOTI1NSwicGF0aCI6Ii83MTYzNjE5MS8zMTQ5MTI3MTUtZGEzOGYyNTQtMTczYi00NTQwLTg0NTItOWE4NmEwNTllNmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA4MjA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZWE2YjkwNWQ3ZjdmZWNlNTkwMTY5M2UzYWM0ZDM1ODVhYmE2MGFiYjhiNzg1MTQ2ZGYxZmJhY2EzZDI0MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hIQUV1p_h6XkP--eHY_o__wJyREGBOHvF2_h7K3g6I0)

We’ve now deleted your wrong account - you should be able to create a new one for Singapore now. 

The reason you need a new one is that these are Stripe Express accounts - connected to the Polar platform. That’s a little bit different than the normal Stripe accounts.

**Comment by rustdesk** [comment]
Thanks

**Comment by squarer3** [comment]
I'm also interested in doing this project.

**Comment by sahilyeole** [comment]
Just an update: I have done the implementation for `Follow remote cursor`.
- It works only if both `Show remote cursor` and `Follow remote cursor` are enabled, similar to AnyDesk.
- Multiple connections are also working. If the above options are enabled on all clients, the display will be switched for all the clients. If it's only enabled on one, the display will switch only for that client, and others are unaffected.

I will check more if I can improve it.

https://github.com/rustdesk/rustdesk/assets/73148455/2f28589b-395c-4118-b82b-87edcc17a170

For `Follow remote window focus` I might need to use platform-specific APIs to get the display index of the currently focused window. I'm looking into that.

I will update this message as I progress.

**Comment by Benno1308** [comment]
Very nice, thanks for the status update and the work you are putting in.

Can't wait for this feature to be on the release channel soon :)

**Comment by rustdesk** [comment]
@sahilyeole Thanks forr you update. Please take care of below.

- [ ] How about if both "follow mouse" and "Follow remote window focus" turned on, if there is conflict, how to handle?
- [ ] How about multiple display for Mac with retina?

**Comment by Benno1308** [comment]
> * How about if both "follow mouse" and "Follow remote window focus" turned on, if there is conflict, how to handle?

Maybe instead of making both an option insert it in the menu as a sub menu (like the image quality selection)

Menu:
Auto Follow

Sub Menu:
[ ] Disabled
[ ] Follow Mouse
[ ] Follow Focus

**Comment by sahilyeole** [comment]
I made some improvements from the above suggestions.

>  How about if both follow the mouse and Follow remote window focus turned on, if there is conflict, how to handle? How does anydesk do this?

In anydesk, If both options are enabled both the features work.
Ex: If my mouse is on display 1 and I focus a window on display 2 using keyboard (cmd+tab) then the display switches to display 2 but as soon as I move the mouse on display 1 the display switches back to display 1.
I am following the same.

> Maybe instead of making both an option insert it in the menu as a sub menu

This sounds good but for now, I've kept it as menu options only similar to anydesk. If @rustdesk would like it to be a sub-menu I will change it to that.

> Follow remote cursor implies Show remote cursor. So when the Follow remote cursor is turned on, Show remote cursor option should be grayed and marked as selected.

Yes, on anydesk I had to manually enable `Show remote cursor` after `Follow remote cursor` or else it didn't work. This will be a good improvement for us to automatically enable `Show remote cursor` and gray it out.

> How about multiple display for Mac with retina?

It is working. I considered the scale of the display while calculating the display index of the current cursor position.

> How about the mutiple windows for multiple displays case (and show all displays on one window)?

It conflicts with them and makes a display switch, so I have disabled this feature for those scenarios.

**Comment by rustdesk** [comment]
Good job.

> This sounds good but for now, I've kept it as menu options only similar to anydesk. If @rustdesk would like it to be a sub-menu I will change it to that.

Please give me a snapshot about this first.

**Comment by sahilyeole** [comment]
Anydesk
on mac:
<img width="298" alt="Screenshot 2024-03-27 at 12 24 53 PM" src="https://github.com/rustdesk/rustdesk/assets/73148455/5995d2fe-a0f3-4fb6-a5f0-707ed6494d48">

on linux:
![anydesk_linux](https://github.com/rustdesk/rustdesk/assets/73148455/ed987edd-0e07-424d-b37c-2876ec44f05e)

Rustdesk:
<img width="462" alt="Screenshot 2024-03-27 at 1 21 36 PM" src="https://github.com/rustdesk/rustdesk/assets/73148455/12aa7390-9fcb-41a8-894e-7582c222e1f6">

**Comment by rustdesk** [comment]
Add a seperator below Follow remote window focus. And how about mobile?

**Comment by sahilyeole** [comment]
Desktop:

<img width="388" alt="Screenshot 2024-03-27 at 3 33 08 PM" src="https://github.com/rustdesk/rustdesk/assets/73148455/db6d514a-f4ff-43d8-8bd6-a2bb879f9d8a">
<img width="539" alt="Screenshot 2024-03-27 at 3 33 28 PM" src="https://github.com/rustdesk/rustdesk/assets/73148455/131bbbba-bd0b-492f-8942-d9a9080aa950">

Mobile:

<img width="347" alt="Screenshot 2024-03-27 at 3 49 05 PM" src="https://github.com/rustdesk/rustdesk/assets/73148455/cdd51a79-1259-4976-9bd9-67b8b579fbf5">
<img width="356" alt="Screenshot 2024-03-27 at 3 49 20 PM" src="https://github.com/rustdesk/rustdesk/assets/73148455/6645259d-5caf-4b21-a275-b255c0c4f94e">

**Comment by rustdesk** [comment]
It is scrollable on mobile?

**Comment by sahilyeole** [comment]
Yes, scrollable.

https://github.com/rustdesk/rustdesk/assets/73148455/26b1eeb8-b28a-4120-bc58-0287554e8eef

**Comment by sahilyeole** [comment]
Update:
I have done the implementation of `follow current window` on all 3 platforms (mac, linux, windows)

**Comment by sahilyeole** [comment]
Update:
I have done the implementation of `Follow remote window focus` on all 3 platforms (mac, linux, windows).
Here I am switching windows using cmd+tab:

https://github.com/rustdesk/rustdesk/assets/73148455/a5c0d7b1-49db-41f4-856f-5ea731d1430e

Some more work to be done:
- [ ] Fix the display position on the client window after switching (as it can be seen in the video).
- [ ] Handle conflict of both the features. (By making the display switch only when the window focused is changed).
- [ ] Disable these 2 features when show all displays or show displays in separate windows is enabled.
- [ ] Gray out `show remote cursor` option when `Follow remote cursor` is enabled

**Comment by rustdesk** [comment]
Good job.
