### ISSUE TITLE
Appimage and Deb builds don't contain RENDEZVOUS_SERVER and RS_PUB_KEY 

### ISSUE THREAD

**Issue by cfrepak** [rustdesk/rustdesk#7445]
### Bug Description

I just compiled the client with Github Actions and it seems that the builds of Appimage and Debs do not pick up the defined variables RENDEZVOUS_SERVER and RS_PUB_KEY. The Windows version works fine, but I don't see the settings in the network settings.

### How to Reproduce

Follow this instructions and try the compiled Appimage and Deb with your self hosted Server. You won't be able to see or connect to your clients from the self hosted Server. https://rustdesk.com/docs/en/dev/build/all/

### Expected Behavior

RENDEZVOUS_SERVER and RS_PUB_KEY should be compiled into every build and should be visible in "Settings > Network"

### Operating system(s) on local side and remote side

debian 12 -> debian 12; debian 12 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.4 -> 1.2.4

### Screenshots

Linux Appimage Version:
![linux_start](https://github.com/rustdesk/rustdesk/assets/110811649/02cf3289-482e-4abd-a9c9-6a32a22ae78b)
![linux_settings](https://github.com/rustdesk/rustdesk/assets/110811649/6093a306-8fca-4d73-a2d4-3406632d9aee)

Windows Version:
![win11_start](https://github.com/rustdesk/rustdesk/assets/110811649/7513b348-7950-4287-be0b-8d1e3fec3b07)
![win_settings](https://github.com/rustdesk/rustdesk/assets/110811649/4d85db97-500f-47b7-9d68-14cb5920ec3e)

**Comment by rustdesk** [comment]
#763

**Comment by cfrepak** [comment]
Please reopen, since this is clearly a bug. Or at least comment why this is not working. I set the variables in GitHub Actions and even replaced the public key and server adress in the 'libs/hbb_common/src/config.rs' and recompiled. still the linux versions are using the rustdesk public server.

other mentions of this issue:
https://github.com/rustdesk/rustdesk/discussions/7108

this old thread had the same issue. apperently it was fixed for windows, which i can confirm. linux versions are still not working:
https://github.com/rustdesk/rustdesk/issues/3126
