### ISSUE TITLE
Multi-monitor mouse dragging

### ISSUE THREAD

**Issue by coelho** [rustdesk/rustdesk#7453]
### Bug Description

When utilizing Multi-monitor in Nightly, you cannot mouse drag across screens. 

### How to Reproduce

1. Try to drag any window from Screen 1 to Screen 2. 
2. As soon as your mouse goes from Screen 1 to Screen 2, the drag will stop.

### Expected Behavior

You should be able to drag across multiple screens.

### Operating system(s) on local side and remote side

Windows 11 -> Windows 11

### RustDesk Version(s) on local side and remote side

Nightly -> Nightly

### Screenshots

n/a

### Additional Context

- I'm guessing this issue is due to RustDesk is creating 2 windows for multi-monitor (1 for each screen?) which would cut off the input
- Possibly it would be less bug-prone to create 1 window that spans both screens?

**Comment by rustdesk** [comment]
duplicate: https://github.com/rustdesk/rustdesk/discussions/7427

**Comment by coelho** [comment]
@rustdesk Submitted to convert that discussion to an issue for proper issue tracking ^
Please re-open if valid.

**Comment by Poojary-K** [comment]
The mentioned duplicate is not a bug.
Please read description carefully.
The multi monitor switcher is not showing up in toolbar.
I have mention the cause as well.
