### ISSUE TITLE
Moving windows from one screen to another (Multi-monitor mouse dragging)

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#7454]
### Discussed in https://github.com/rustdesk/rustdesk/discussions/7427

<div type='discussions-op-text'>

<sup>Originally posted by **Winours** March 19, 2024</sup>
Hello everybody,
Rust desk is a really cool project. The only thing I can see to make it perfect would be the multi monitor windows management. I compare with teamviewer which is the only alternative to have the right behavior in this case.

Host has 3 screens (but it is the same with two screens)
Client has 3 screens.

I open the 3 screens of the host on client side and dispatch them on the 3 screens I have locally.
When I try to move a window to another screen, it does not work. Rust desk thinks I want to go to the edge of the screen and host is providing me with windows management as if I had only one screen...
I would be so great to obtain the same behavior as `teamviewer` : you have ponctually acces to windows management, but very quicly it understand you are on another screen and allow you to move a window from one screen to another.

Hope this is clear as english is not my native language.

Best regards</div>

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/rustdesk) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/rustdesk/rustdesk/issues/7454">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/rustdesk/rustdesk/issues/7454/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/rustdesk/rustdesk/issues/7454/pledge.svg">
</picture>
</a>

**Comment by Winours** [comment]
On my version (nightly) I cannot see any difference. Is it normal ?

**Comment by rustdesk** [comment]
https://twitter.com/rustdesk/status/1784102193760801170
