### ISSUE TITLE
Muliple Sceens and privacy mode

### ISSUE THREAD

**Issue by Dolphin1220** [rustdesk/rustdesk#7455]
### Bug Description

I use a multi-screen setup (on both sides) when I activate the private mode, the icon where you can switch the monitors disappears.

### How to Reproduce

it's easy, just activate the private mode and the icon disappears.

### Expected Behavior

The option to use two screens should also be possible in private mode.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3-1 -> 1.2.3-1

### Screenshots

![2024-03-21 09_13_41-Window](https://github.com/rustdesk/rustdesk/assets/123817278/e7d362ef-a04b-4018-8b9c-da90283af213)
![2024-03-21 09_12_44-Window](https://github.com/rustdesk/rustdesk/assets/123817278/1ee9d83a-a230-4062-b9ee-3086b5c88460)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/6707#issuecomment-1860073303
