### ISSUE TITLE
Connect to client without running shell [Windows]

### ISSUE THREAD

**Issue by JannNEC** [rustdesk/rustdesk#7478]
### Bug Description

No window on the remote side to accept the connection 

### How to Reproduce

stop the shell on the remote site and try to conncet to it 

### Expected Behavior

a small window on which you can allow the connection

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.4 -> 1.2.4

### Screenshots

![TMP](https://github.com/rustdesk/rustdesk/assets/164491974/70a1867c-7386-4edc-9022-baa280d7e989)

**Comment by JannNEC** [comment]
#7476

**Comment by rustdesk** [comment]
We do not support this, also no plan yet.
