### ISSUE TITLE
Rustdesk not honoring specified relay port

### ISSUE THREAD

**Issue by Karbust** [rustdesk/rustdesk#7479]
### Bug Description

The port specified on the relay server's url is not being honored for connections when connecting always through relay.

### How to Reproduce

Use a different port on the relay server's address.

### Expected Behavior

Use the specified port to connect through the relay server.

### Operating system(s) on local side and remote side

Windows 10/11 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3-1

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/20361229/3ee7e75d-3b04-494f-b87b-3910845bdb02)

### Additional Context

hbbs is using the `-r` option with the same address and port specified on the client.

**Comment by rustdesk** [comment]
#763
