### ISSUE TITLE
Connection error notice blocks tab switching until its dismissed

### ISSUE THREAD

**Issue by Benno1308** [rustdesk/rustdesk#7481]
### Bug Description

While connected to two sessions in the same window, if one session fails (because of network problems, remote side crashing etc) the "Connection error"-info prevents switching tabs to the other session, until said error notice is dismissed.

### How to Reproduce

1. Open up two connections (Making sure they are in the same window)
2. Somehow kill one of the sessions to force the "Connection error" pop-up
3. Observe that its no longer possible to switch the tab to the other (working) session

### Expected Behavior

I expect that even if one session is broken/had connection problems,
I'm still able to switch the to the working one, and switch back later to the other (broken) session to press "reconnect" at a later point in time

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

Connection broken, and tab-bar is grayed out until error is dismissed
![grafik](https://github.com/rustdesk/rustdesk/assets/954915/e4d3f5c0-a34b-448e-a3e5-9fe8a14886bb)

### Bounty
Willing to add a 50 USD bounty if this is a bug and gets fixed, 
or if its expected behaviour and will get reworked to allow tab-switching

**Comment by fufesou** [comment]
@Benno1308 Thanks for you feedback and 

I can reproduce this issue with 1.2.3.

But the nightly build has fixed it.   https://github.com/rustdesk/rustdesk/releases/tag/nightly


https://github.com/rustdesk/rustdesk/assets/13586388/129d2703-1e37-407d-931e-bcdb1215b37b
