### ISSUE TITLE
Windows 7 Connection Problem 

### ISSUE THREAD

**Issue by Vasilis553** [rustdesk/rustdesk#7483]
### Bug Description

Hello i have an older laptop running windows 7 64bit professional and i downloaded both 1.2.3 or 1.2.3sciter but i cant establish connections both for win7laptop==>main win11 error message "failed connect via relay to rs servers" or from main win11 ==> win7laptop error type "conecting and then error box"  service says "ready"

### How to Reproduce

-

### Expected Behavior

-

### Operating system(s) on local side and remote side

win11 and win7

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

-

### Additional Context

-

**Comment by rustdesk** [comment]
#763
