### ISSUE TITLE
HTTP proxy

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#7487]
### Discussed in https://github.com/rustdesk/rustdesk/discussions/5687

<div type='discussions-op-text'>

<sup>Originally posted by **RafaelLinux** August 31, 2022</sup>
In my intranet, we require to use an http(s) proxy. RustDesk nowadays only works with socks proxy, so it shows "Connecting to the RustDesk network" forever and I don't get an ID.

Please, could you add the HTTP(S) proxy feature?

Thank you</div>

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/rustdesk) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/rustdesk/rustdesk/issues/7487">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/rustdesk/rustdesk/issues/7487/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/rustdesk/rustdesk/issues/7487/pledge.svg">
</picture>
</a>

**Comment by rustdesk** [comment]
This will work on public server and self-host `Pro`, since currently OSS self-host requires UDP.

**Comment by yuluo-zy** [comment]
Thanks, I will start this work

**Comment by yuluo-zy** [comment]
@rustdesk Hi, I have completed the core content of http proxy forwarding. Now I have a problem with the UI of the software.
![image](https://github.com/rustdesk/rustdesk/assets/33770335/7cde6f38-2c58-404d-a251-4a68b23d4e8d)
or
![image](https://github.com/rustdesk/rustdesk/assets/33770335/59e34332-f3d3-403d-a437-404334692b20)
，Which method should I take to complete the configuration of the http proxy?
Also, whether OSS self-hosting will change the protocol information in the future?

**Comment by rustdesk** [comment]
Please do on Flutter version, not the old Sciter version.

**Comment by yuluo-zy** [comment]
Got it， thx！

**Comment by rustdesk** [comment]
Thank you @yuluo-zy for contributing to close this issue! ⭐

The rewards from this issue, totalling $450, has been shared with you.

**What now?**

1. Create a [Polar](https://polar.sh) account
2. See incoming rewards & setup Stripe to receive them
3. Get payouts as backers finalize their payments

_If you already have a Polar account setup, you don't need to do anything._
