### ISSUE TITLE
The 1.1.9 not work after router restarts (ip changed, DDNS) for self-hosting.

### ISSUE THREAD

**Issue by zhangbo8418** [rustdesk/rustdesk#751]
**Describe the bug you encountered:**

The 1.1.9 client is not easy to use. My home is DDNS and the 1.1.5 server is installed on Synology. When my router restarts, the 1.1.9 client shows that the remote computer is offline, and 1.1.8 No problem.
Server v1.1.5
<img width="1439" alt="服务端" src="https://user-images.githubusercontent.com/46797568/173263939-26a4bb2e-a635-4f77-878e-07c88241c38a.png">

Remote 1.1.9 client.But IP direct access can be connected.
<img width="1438" alt="1 1 9客户端" src="https://user-images.githubusercontent.com/46797568/173264017-d80316a0-3b0f-47d4-8376-ff5804fa975d.png">

Remote 1.1.8 client.
<img width="1439" alt="1 1 8客户端" src="https://user-images.githubusercontent.com/46797568/173264144-d7782492-4258-489a-8979-52f47f17242a.png">

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

**Comment by youhers** [comment]
This must be done on purpose by the author I also found this problem. Once the DDNS is changed, all clients will not be able to connect to the cloud server. There is no such problem.

**Comment by youhers** [comment]
I also found this problem. Once the DDNS is changed, all clients will not be able to connect           to the cloud server. There is no such problem.

**Comment by youhers** [comment]
I also found this problem. Once the DDNS is changed, all clients will not be able to connect to the

**Comment by youhers** [comment]
I also found this problem. Once the DDNS is changed, all clients will not be able to connect to the server. If the cloud server is not this problem

**Comment by youhers** [comment]
Hope the author can fix this

**Comment by zhangbo8418** [comment]
> 我也发现了这个问题。更改 DDNS 后，所有客户端将无法连接到服务器。如果云服务器不是这个问题



> I also found this problem. Once the DDNS is changed, all clients will not be able to connect to the server. If the cloud server is not this problem

You can change the client to 1.1.8, but 1.1.8 will show unencrypted connections.

**Comment by youhers** [comment]
I know but 1.1.8 can't copy paste

**Comment by youhers** [comment]
1.1.9 4月份的版本也没有这个问题的 我测试过

**Comment by rustdesk** [comment]
It is not on purpose. I even do not know what is ddns.

**Comment by youhers** [comment]
DDNS 就是动态域名解析公网IP  真实的公网IP 每天让它变换一下 域名指向的IP地址也会变换来绑定rustdesk服务器 目前的版本 只要域名指向的ip变了以后 所有客户端都会连接不上 不会像1.1.8一样 自动连接新的服务器 我测试过 手动重启rustdesk服务也可生效 但是 无人值守的服务器 就不好处理了 基本处于失联状态

**Comment by youhers** [comment]
编译起来打包 我还是没搞懂。。 目前没有折腾了

**Comment by youhers** [comment]
目前买了云服务器  就不会有这个问题  但是 哎。。云服务器带宽实在是太低了中继传文件太慢   打洞直连成功率也实在太低了

**Comment by rustdesk** [comment]
Then you reminds me, we do have some code refactory about dns check in https://github.com/rustdesk/rustdesk/blob/master/src/rendezvous_mediator.rs#L243
You can roll back to find the problem. And you do not need to package, `cargo run` is enough for you test.

**Comment by rustdesk** [comment]
> 成功率也实在太低

It is not low out of China.

**Comment by youhers** [comment]
我不是用于测试环境的  如果不能打包  没有办法安装系统服务  我想测试都没法弄  哎。。 希望后期能解决这个问题把  幸苦你了 如果我搞懂了如何打包成一个exe  我会自行测试 并告诉你我测试的结果

**Comment by rustdesk** [comment]
System service is not required, `carg run` will start a service thread (if system service not started) to listen for connection request.

**Comment by youhers** [comment]
> > 我也发现了这个问题。更改 DDNS 后，所有客户端将无法连接到服务器。如果云服务器不是这个问题
> 
> > 我也发现了这个问题。更改 DDNS 后，所有客户端将无法连接到服务器。如果云服务器不是这个问题
> 
> 您可以将客户端更改为 1.1.8，但 1.1.8 将显示未加密的连接。

裙下孤魂大神 把你的套件能不能分享给作者  让更多的人可以用上

**Comment by youhers** [comment]
> 系统服务不是必需的，将启动一个服务线程（如果系统服务未启动）来监听连接请求。`cargo run`

好  我用空再测试一下吧

**Comment by rustdesk** [comment]
> 我用空再测试一下吧

That's the meaning and spritit of open source.

**Comment by zhangbo8418** [comment]
> It is not on purpose. I even do not know what is ddns. You overestimated the author's capabliltiy. haha. Since it is open source, and I see you can modify our code, hope you can find the problem.

DDNS is dynamic domain name resolution. Generally, the public network IP of home broadband is dynamic, that is, if the IP is re-dialed, it will be changed, so DDNS needs to be used. When the IP changes, DDNS will re-point the domain name to the new IP.

**Comment by rustdesk** [comment]
@zhangbo8418 I have a new idea about ddns, we can provide a simple ddns service, e.g. `@<yourname>.rustdesk`. The self-hosting user can use `@<yourname>.rustdesk` as its server address in RustDesk client.

**Comment by youhers** [comment]
这个可以 免得终端用户再继续买域名  最好是收费提供 提供快速的DDNS动态解析 
这样更加稳定 昨天的版本修复了那个bug么

**Comment by youhers** [comment]
这是一条生财之道

**Comment by rustdesk** [comment]
> that bug

no, waiting for contributors.

**Comment by rustdesk** [comment]
and won't by us.

**Comment by rustdesk** [comment]
Try out this one https://github.com/rustdesk/rustdesk/releases/download/tmp/rustdesk-1.1.9-windows_x64.zip.

**Comment by zhangbo8418** [comment]
> 试试这个https://github.com/rustdesk/rustdesk/releases/download/tmp/rustdesk-1.1.9-windows_x64.zip。


Thank you big guy, there is no problem with the test, but there is another suggestion, you can add a search box to the file transfer interface, or you can transfer files directly through the pasteboard, it's perfect!

**Comment by zhangbo8418** [comment]
> @zhangbo8418更新了 rustdesk 服务器，https://github.com/rustdesk/rustdesk-server/releases/tag/1.1.6，也许你可以升级 Synogy 包。

Very good, the LAN connection takes less than 1 second, and the public network connection takes less than 3 seconds.

**Comment by rustdesk** [comment]
> pasteboard

https://github.com/rustdesk/rustdesk/issues/712#issuecomment-1146939652

**Comment by youhers** [comment]
> [试试这个 https://github.com/rustdesk/rustdesk/releases/download/tmp/rustdesk-1.1.9-windows_x64.zip](https://github.com/rustdesk/rustdesk/releases/download/tmp/rustdesk-1.1.9-windows_x64.zip)。

Can you provide the X32 version?

**Comment by youhers** [comment]
thanks for the fix

**Comment by rustdesk** [comment]
> X32

https://github.com/rustdesk/rustdesk/releases/download/tmp/rustdesk-1.1.9-windows_x32.zip

**Comment by mikekgr** [comment]
The last upgrade to the server makes the connections very fast!!! Congratulations to the developers of this marvelous piece of software!

**Comment by bigretromike** [comment]
@rustdesk You fixed the issue, and ddns is dynamic dns (domain name system), its when you are using 3rd party or selfhosted system that will update your IP that is binded with your dynamic domain name, so even when you IP changes (after router restart) yours dynamic domain name still point to your machine (even with new ip address). Very popular solution some time ago was no-ip.org also Active Directory Domain Controler (Miscrosoft AD/DC aka Windows Domain) use same mechanism for machines that joins domain, so even when using DHCP setup computer can be access by thier name (not netbios) aka FQDN.

**Comment by DaleyKD** [comment]
@bigretromike : I use No-IP. Is there a "newer" way of doing it? I don't want to show my age by staying stuck on older ways. 😄

**Comment by bigretromike** [comment]
> @bigretromike : I use No-IP. Is there a "newer" way of doing it? I don't want to show my age by staying stuck on older ways. 😄

Probably not, I migrated from No-IP when they switched many-many years ago from free to freemium plan, and I switched to selfhosted solution which is fine for what I needed.
`If it's not broke, don't fix it `

**Comment by open-trade** [comment]
![e9a35ee77c6046ef6ab2a648b5afa79](https://user-images.githubusercontent.com/42061627/206685943-d124fae6-23f9-4e0f-9267-5ffca25f47f2.png)

**Comment by zhangbo8418** [comment]
@rustdesk 
The old problem has reappeared in the latest version 1.2.4.

**Comment by bigretromike** [comment]
if server is behind ddns (aka dynamic IP), each time you turn router off you can get different IP. You/Client need to update DNS before its able to connect to server. Most dns servers and even OS are caching dns query also it depend from you ddns client configuraiton - if its time base (15minut delays), event based (eth down/up) or other. Your ddns provider need to update his DNS, then that information need to get to You or your clients. 

If you have issue with connecting to server with client can you ping (resolve) ddns name and see if its pointing to your new IP ? 
The only issue I could potentialy see here is that rustdesk cache dns - but its easy to check (ping ddns after change), if your OS see your new IP address under your ddns name, and rust cant connect then its rust issue. if your os dont resolve it correctly then its infrastructure issue and not a rust bug.
