### ISSUE TITLE
Cann't switch monitors from Win11 connect to Ubuntu22.04

### ISSUE THREAD

**Issue by sailangyf** [rustdesk/rustdesk#7519]
### Bug Description

Hello,
Now I am using RustDesk 1.2.3. When I make a remote connection from win11 to Ubuntu22.04, I can't find the button to switch monitors. (because my Ubuntu has 2 monitors)

### How to Reproduce

Always

### Expected Behavior

There is a button for me to switch monitors.

### Operating system(s) on local side and remote side

Windows11 -> Ubuntu22.04

### RustDesk Version(s) on local side and remote side

1.2.3-1 -> 1.2.3

### Screenshots

![Screenshot 2024-03-26 090056](https://github.com/rustdesk/rustdesk/assets/67216677/47619211-e7fe-4887-a782-92291cb45f64)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
