### ISSUE TITLE
rustdesk-1.2.4-x86_64.deb

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#7521]
### Discussed in https://github.com/rustdesk/rustdesk/discussions/7520

<div type='discussions-op-text'>

<sup>Originally posted by **IT-Betreuung** March 26, 2024</sup>
The „rustdesk-1.2.4-x86_64.deb“
generates continuasly new IDs
(since when I don´t know).

I have noticed it on Debian Bookworm  6.1.0-18-amd64 - Debian 6.1.76-1
and Ubuntu Server 22.04.4 LTS - Linux 5.15.0-101-generic x86_64.

When I downgrade to „rustdesk-1.2.3-x86_64.deb“,
everything is O.K..</div>

**Comment by rustdesk** [comment]
@IT-Betreuung what does `generates continuasly new IDs` mean? generate ID everytime run it? or the first time run it from 1.2.3?

**Comment by IT-Betreuung** [comment]
I updated 3 Client- PCs to „rustdesk-1.2.4-x86_64.deb“,
then the IDs were changed without connecting,
repeated several times a day,
what I observed on my RustDesk Server Pro 1.2.0 device- list.

I deinstalled RustDesk
(sudo apt-get --purge autoremove rustdesk –yes
sudo rm -rf ~/.config/rustdesk
sudo rm -rf /root/.config/rustdesk)
and reinstall it,
but no changes in the behavior.

Downgrade to rustdesk-1.2.3-x86_64,
everything is fine.


Client- PCs:
version: 1.2.3; cpu: Intel(R) Pentium(R) CPU N3540 @ 2.16GHz, 2.54GHz, 4/4 cores; mem: 7.64GB
with  Ubuntu Server 22.04.4 LTS - Linux 5.15.0-101-generic x86_64

version: 1.2.3; cpu: Intel(R) Celeron(R) J4025 CPU @ 2.00GHz, 1.95GHz, 2/2 cores; mem: 2.9GB
version: 1.2.3; cpu: AMD Ryzen Embedded R1600, 2.54GHz, 4/4 cores; mem: 7.75GB (VM on Synology DiskStation)
both with Debian Bookworm 6.1.0-18-amd64 - Debian 6.1.76-1

**Comment by rustdesk** [comment]
@IT-Betreuung Could you run the AppImage/ Flatpak of 1.2.4 version? wanna confirm if they generate new id.

**Comment by IT-Betreuung** [comment]
New ID of the same device.

I´ll test it on one of my test- PCs
the 3 PCs are from customers.

**Comment by rustdesk** [comment]
The id you mean is this column? If so, this is super wierd, because this id can not be changed automatically if the user does not change it from the client manually.

![image](https://github.com/rustdesk/rustdesk/assets/71636191/330f2959-9ba8-4d6b-97ee-ca3e1c3604a6)

**Comment by IT-Betreuung** [comment]
Yes, it's super weird,
because all 3 devices run headless
and as far as I know
nobody else has access.

**Comment by IT-Betreuung** [comment]
I „upgraded“ my Test- PC
and the ID was changed „over night“.

Then I deinstalled RustDesk,
but with flatpak I can´t start RustDesk:

Codec (null) not found
avcodec_open2: Operation not permitted
Codec (null) not found
avcodec_open2: Unknown error occurred
avcodec_open2: Unknown error occurred
avcodec_open2: Operation not permitted
Failed to create specified HW device:Operation not permitted
reset failed
Failed to create specified HW device:Operation not permitted
reset failed
hw_frames_ctx is NULL
sh: Zeile 1: lsmod: Kommando nicht gefunden.

**Comment by rustdesk** [comment]
> and the ID was changed „over night“.

Maybe we can get some clue from `/root/.local/share/logs/RustDesk/server/`

**Comment by rustdesk** [comment]
> Codec (null) not found
> avcodec_open2: Operation not permitted
> Codec (null) not found
> avcodec_open2: Unknown error occurred
> avcodec_open2: Unknown error occurred
> avcodec_open2: Operation not permitted
> Failed to create specified HW device:Operation not permitted
> reset failed
> Failed to create specified HW device:Operation not permitted
> reset failed
> hw_frames_ctx is NULL
> sh: Zeile 1: lsmod: Kommando nicht gefunden.
Is this all messages? Thoese seems not the root cause of Flatpak failure. All are related to ffmpeg (hardware codec check). @21pages

**Comment by 21pages** [comment]
Let me test flatpak

**Comment by 21pages** [comment]
I can start rustdesk flatpak on my ubuntu 22.04. The beginning of the log is also these, followed by the flutter log.

**Comment by IT-Betreuung** [comment]
@21pages 
RustDesk is running now with flatpak

@rustdesk
`/.local/share/logs/RustDesk/service/rustdesk_r2024-03-26_11-23-11.log
[2024-03-26 11:23:11.821750 +01:00] INFO [src/core_main.rs:164] main start args:["--service"]
[2024-03-26 11:23:11.822102 +01:00] INFO [src/core_main.rs:272] start --service
[2024-03-26 11:23:11.859135 +01:00] INFO [src/server/uinput.rs:750] start uinput control service
[2024-03-26 11:23:11.859129 +01:00] INFO [src/server/uinput.rs:736] start uinput keyboard service
[2024-03-26 11:23:11.859620 +01:00] INFO [src/server/uinput.rs:743] start uinput mouse service
[2024-03-26 11:23:12.129393 +01:00] INFO [src/ipc.rs:280] Started ipc_service server at path: /tmp/RustDesk/ipc_service
[2024-03-26 11:23:12.129986 +01:00] INFO [src/ipc.rs:280] Started ipc_uinput_control server at path: /tmp/RustDesk/ipc_uinput_control
[2024-03-26 11:23:12.130123 +01:00] INFO [src/ipc.rs:280] Started ipc_uinput_mouse server at path: /tmp/RustDesk/ipc_uinput_mouse
[2024-03-26 11:23:12.131363 +01:00] INFO [src/ipc.rs:280] Started ipc_uinput_keyboard server at path: /tmp/RustDesk/ipc_uinput_keyboard
[2024-03-26 11:23:18.967144 +01:00] INFO [src/platform/linux.rs:258] DISPLAY: :0
[2024-03-26 11:23:18.967171 +01:00] INFO [src/platform/linux.rs:259] XAUTHORITY: /home/it-service/.Xauthority
[2024-03-26 11:26:12.817504 +01:00] INFO [src/platform/linux.rs:321] restart server



/.local/share/logs/RustDesk/service/rustdesk_r2024-03-26_11-30-43.log
[2024-03-26 11:30:43.577945 +01:00] INFO [src/core_main.rs:164] main start args:["--service"]
[2024-03-26 11:30:43.580381 +01:00] INFO [src/core_main.rs:272] start --service
[2024-03-26 11:30:43.630117 +01:00] INFO [src/ipc.rs:280] Started ipc_service server at path: /tmp/RustDesk/ipc_service
[2024-03-26 11:30:43.631048 +01:00] INFO [src/server/uinput.rs:743] start uinput mouse service
[2024-03-26 11:30:43.631044 +01:00] INFO [src/server/uinput.rs:750] start uinput control service
[2024-03-26 11:30:43.631093 +01:00] INFO [src/server/uinput.rs:736] start uinput keyboard service
[2024-03-26 11:30:43.631183 +01:00] INFO [src/ipc.rs:280] Started ipc_uinput_mouse server at path: /tmp/RustDesk/ipc_uinput_mouse
[2024-03-26 11:30:43.631196 +01:00] INFO [src/ipc.rs:280] Started ipc_uinput_control server at path: /tmp/RustDesk/ipc_uinput_control
[2024-03-26 11:30:43.631212 +01:00] INFO [src/ipc.rs:280] Started ipc_uinput_keyboard server at path: /tmp/RustDesk/ipc_uinput_keyboard
[2024-03-26 11:30:57.653651 +01:00] INFO [src/platform/linux.rs:258] DISPLAY: :0
[2024-03-26 11:30:57.653698 +01:00] INFO [src/platform/linux.rs:259] XAUTHORITY: /home/it-service/.Xauthority
17 x
[2024-03-26 11:31:45.684178 +01:00] INFO [src/platform/linux.rs:321] restart server
Until 23:14:59.936017 +01:00


/.local/share/logs/RustDesk/service/rustdesk_rCURRENT.log
8 x
[2024-03-27 00:15:01.416103 +01:00] INFO [src/platform/linux.rs:321] restart server
Until 07:15:10.962428 +01:00
`

**Comment by rustdesk** [comment]
Need logs in server rather than service.

**Comment by IT-Betreuung** [comment]
The server is running on Debian Bookworm.

Which logs do you need
/var/log/rustdesk-server?

**Comment by rustdesk** [comment]
I meant ` /root/.local/share/logs/RustDesk/server/` on your controlled machine.

**Comment by IT-Betreuung** [comment]
6 log- files with the same content from 05:06:32.885210 +01:00 to this:
root@test:~/.local/share/logs/RustDesk/server# /root/.local/share/logs/RustDesk/server/rustdesk_r2024-03-26_10-06-39.log
/root/.local/share/logs/RustDesk/server/rustdesk_r2024-03-26_10-06-39.log: line 1: [2024-03-26: command not found
/root/.local/share/logs/RustDesk/server/rustdesk_r2024-03-26_10-06-39.log: line 2: [2024-03-26: command not found
/root/.local/share/logs/RustDesk/server/rustdesk_r2024-03-26_10-06-39.log: line 3: syntax error near unexpected token `('
/root/.local/share/logs/RustDesk/server/rustdesk_r2024-03-26_10-06-39.log: line 3: `[2024-03-26 10:06:39.542703 +01:00] INFO [src/server.rs:422] DISPLAY=Ok(":0")'

root@test:~/.local/share/logs/RustDesk/server# /root/.local/share/logs/RustDesk/server/rustdesk_rCURRENT.log
/root/.local/share/logs/RustDesk/server/rustdesk_rCURRENT.log: line 1: [2024-03-26: command not found
/root/.local/share/logs/RustDesk/server/rustdesk_rCURRENT.log: line 2: [2024-03-26: command not found
/root/.local/share/logs/RustDesk/server/rustdesk_rCURRENT.log: line 3: syntax error near unexpected token `('
/root/.local/share/logs/RustDesk/server/rustdesk_rCURRENT.log: line 3: `[2024-03-26 11:06:40.969359 +01:00] INFO [src/server.rs:422] DISPLAY=Ok(":0")'

**Comment by rustdesk** [comment]
No useful info

**Comment by IT-Betreuung** [comment]
I'm sorry about that,
I'll do my best. ;-)

I´m able to start flatpak- RustDesk
via Remote- Desktop
but not via the ssh console.

no-hwcodec.flatpak "says":
(rustdesk:2): Gtk-WARNING **: 13:06:41.258: cannot open display:

What else can I do,
to steal your time?

**Comment by rustdesk** [comment]
It can not start from ssh, it required display.

**Comment by IT-Betreuung** [comment]
That was a misconception,
I thought,
that I had to start RustDesk via the console,
to transfer the logs.

Then I'll wait,
if the ID changes.

Many thanks for your efforts!

**Comment by mikekgr** [comment]
Dear Sirs,
I also faced a random self rustdesk id changes in my Debian 11 desktop. The problem started after updating the rustdesk deb package from 17/03/2024 nightly release to 30/03/2024 nughtly release.
What to suggest? Maybe to go to stable release 1.2.3.1 ?

**Comment by IT-Betreuung** [comment]
Yes,
a downgrade worked for me.

**Comment by mikekgr** [comment]
> Yes, a downgrade worked for me.

Thanks for the reply. I already have 1.2.3-1 installed. Let's see, so far it's ok

**Comment by mikekgr** [comment]
Also I realize that in both versions (1.2.4 nightly, 1.2.3-1) rustdesk aplication doesn't keep/save the user resizing of its window.

**Comment by rustdesk** [comment]
> 17/03/2024 nightly release to 30/03/2024

@21pages check this please. So this happens between 17/03 -> 25/03.

**Comment by rustdesk** [comment]
@mikekgr we can build any day's build for your testing.

**Comment by mikekgr** [comment]
> @mikekgr we can build any day's build for your testing. @IT-Betreuung also for you.

Now I am watching my 17/03 installation. Although I am sure that it is changed once the ID now, several minutes it is keeping the latest one even after a reboot. Give me sometine to get an idea and I will report back here. 
The fact is in both of my systems that is running Debian 11 and XFCE 4.18.1 the "OLD" ID changed to a new one by itself...

**Comment by mikekgr** [comment]
To test both of my Debian 11 installations that express the mentioned problem I upgraded RustDesk as following:

1) mx-mikek  RustDesk 1.2.3 2023-10-13 11:30  ==>  RustDesk 1.2.4 2024-03-31 00:25

2) mx RustDesk 1.2.4 2024-03-17  ==>  RustDesk 1.2.4 2024-03-31 00:25

I am watching both installations, till now no ID changed (except the old reported).
I will report back after some hours ...

**Comment by rustdesk** [comment]
Thanks so much

**Comment by 21pages** [comment]
@mikekgr @IT-Betreuung You can test with any of these programs, https://github.com/21pages/rustdesk/releases/tag/new_id,  there will be logs like below when id changes.

```
[2024-03-31 15:02:23.404096 +08:00] INFO [src/ipc.rs:422] ================ ipc server set id
[2024-03-31 15:02:23.404178 +08:00] INFO [src/ipc.rs:423] ================== update_id stack start ===================
[2024-03-31 15:02:23.477693 +08:00] INFO [src/ipc.rs:427] "start_thread"
[2024-03-31 15:02:23.477744 +08:00] INFO [src/ipc.rs:427] "__GI___clone3"
[2024-03-31 15:02:23.477755 +08:00] INFO [src/ipc.rs:432] ================== update_id stack end ===================
[2024-03-31 15:02:23.477972 +08:00] INFO [libs/hbb_common/src/config.rs:781] ================set id: 1789173836 => pc12345
[2024-03-31 15:02:23.477981 +08:00] INFO [libs/hbb_common/src/config.rs:782] ================== set id stack start ===================
[2024-03-31 15:02:23.478010 +08:00] INFO [libs/hbb_common/src/config.rs:786] "start_thread"
[2024-03-31 15:02:23.478016 +08:00] INFO [libs/hbb_common/src/config.rs:786] "__GI___clone3"
[2024-03-31 15:02:23.478020 +08:00] INFO [libs/hbb_common/src/config.rs:791] ================== set id stack end ===================

```

**Comment by IT-Betreuung** [comment]
Do I still have anything to do with the flatpak installation?

So far the ID has not changed.

**Comment by rustdesk** [comment]
Thanks @IT-Betreuung, no need to test Flatpak any more.

**Comment by mikekgr** [comment]
it happens again in a time span of 7 hours at my mx-mikek Debian 11 pc running the today nightly build.
I don't know what is triggering this ID changings...
The other one, mx Debian 11 pc, practically same OS running same rustdesk didn't change ID yes. I just restarted to push it but it is started with the latest ID I keep it in running.

Just to mention that I have my own rustdesk server (hbbr & hbbs) running at my Ubuntu 22.04 server, this server is not new I running it as RustDesk  server for ages ...

**Comment by rustdesk** [comment]
You ID change is the same as @IT-Betreuung , ID changed here rather thean adding new device with new id?

![image](https://github.com/rustdesk/rustdesk/assets/71636191/18a4cbb4-2077-4997-81c2-e7e3c7049953)

**Comment by rustdesk** [comment]
And can you run https://github.com/21pages/rustdesk/releases/tag/new_id? We can see more log with these build.

**Comment by 21pages** [comment]
Please try https://github.com/21pages/rustdesk/releases/download/new_id/rustdesk-1.2.4-x86_64-20240325_d36e33a.deb first, It's not striped

**Comment by mikekgr** [comment]
> Is you ID change the same as @IT-Betreuung , ID changed here rather than new device added in the web console?
> 
> ![image](https://private-user-images.githubusercontent.com/71636191/318274158-18a4cbb4-2077-4997-81c2-e7e3c7049953.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4OTM2OTcsIm5iZiI6MTcxMTg5MzM5NywicGF0aCI6Ii83MTYzNjE5MS8zMTgyNzQxNTgtMThhNGNiYjQtMjA3Ny00OTk3LTgxYzItZTdlM2M3MDQ5OTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDEzNTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZmIyYmVhNGE3NzhlOWMwZTUyNjkwNTJmNWZlN2U5ZDczYmMwNDZiMmUxMWM5YjRkMDQyNDJmNzIzODdlNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QvixvKSi5UEG43fN6UeJqPL1WNe_0mJSX2QLakTfxCM)

Sorry I don't understand what is it? I am running the free version of RustDesk.

**Comment by mikekgr** [comment]
> Please try https://github.com/21pages/rustdesk/releases/download/new_id/rustdesk-1.2.4-x86_64-20240325_d36e33a.deb first, It's not striped

OK so you suggesting me to install this? 
I will do, tell me where can see then the log(s) ?

**Comment by 21pages** [comment]
~/.local/share/logs/RustDesk/server/rustdesk_rCURRENT.log
~/.local/share/logs/RustDesk/rustdesk_rCURRENT.log

**Comment by mikekgr** [comment]
> ~/.local/share/logs/RustDesk/server/rustdesk_rCURRENT.log ~/.local/share/logs/RustDesk/rustdesk_rCURRENT.log

OK I installed and I swa this logs. What next?

**Comment by 21pages** [comment]
When you find ID changes agian, run `grep "stack"  ~/.local/share/logs/RustDesk/ -rn`, it's may in the history log.

**Comment by mikekgr** [comment]
> When you find ID changes again, run `grep "stack" ~/.local/share/logs/RustDesk/ -rn`, it may in the history log. Don’t have to always keep an eye on it.

As all we know, I faced Murphy's law... meaning that till now no ID changed !
I will keep you informed.

**Comment by rustdesk** [comment]
`/root/.local/....`

**Comment by IT-Betreuung** [comment]
I installed "rustdesk-1.2.4-x86_64-20240325_d36e33a.deb" on
Debian Bookworm
and
Ubuntu Server 22.04.4 LTS

This ist the output from Ubuntu:

grep "stack" ~/.local/share/logs/RustDesk/ -rn
/home/xxxx/.local/share/logs/RustDesk/rustdesk_rCURRENT.log:5:[2024-03-31 13:30:13.257616 +02:00] INFO [libs/hbb_common/src/config.rs:544] ================== load config generate new id stack start ===================
/home/xxxx/.local/share/logs/RustDesk/rustdesk_rCURRENT.log:8:[2024-03-31 13:30:13.342847 +02:00] INFO [libs/hbb_common/src/config.rs:553] ================== load config generate new id stack end ===================

But the error occured this "morning"
(2024-04-01 ??????????),
Debian also changed the ID,
but no output.

All other logs are older.

I have a hunch,
because it mostly happens at night
and my Internet connection changes IP address at around 03:00 to 04:00 o´clock,
that there might be a connection.

**Comment by rustdesk** [comment]
Please do not install or uninstall new version, let's keep watch, if the id still change today.

**Comment by 21pages** [comment]
Could you paste the all related log between "stack start " and "stack end" in rustdesk_rCURRENT.log?

**Comment by IT-Betreuung** [comment]
07:11 (MESZ)
I restarted my router,
got a new IP
and also a new RustDesk- ID,
but no new logs.

Perhaps something about connect to devices on the other self-host or public server?

**Comment by rustdesk** [comment]
@IT-Betreuung can you restart router again to check if ID change?

**Comment by rustdesk** [comment]
The ip change causing ID change should happen once after reinstalling rustdesk.

**Comment by rustdesk** [comment]
Please do not od this when your reinstall RustDesk.

```
sudo rm -rf ~/.config/rustdesk
sudo rm -rf /root/.config/rustdesk
```

Below will cause id change once your ip change, but it will cause only once.

**Comment by IT-Betreuung** [comment]
I restarted my router again,
got a new IP
and also a new RustDesk- ID.

I have a customer PC and my "Service- Laptop"
(both Windows 10)
that also changed their ID´s,
but it is some weeks ago.

**Comment by rustdesk** [comment]
It connecs to your Pro self-host?

**Comment by rustdesk** [comment]
Thanks, I reproduced the id change, but only change once, later no matter how I change ip, the id does not change.

**Comment by IT-Betreuung** [comment]
Pro- self- host 1.2.0

**Comment by IT-Betreuung** [comment]
That would be my logic of the problem:

My RustDesk Server Pro 1.2.0 is "connected to the Internet" via a Telekom Regio- connection (Germany). "connected to the Internet".

The IP address is "changed" every 24 hours for Telekom's Regio- connections,
so that the forced disconnection by the provider does not happen during the day,
I have set in my FRITZ!Box 7590,
that a new IP is obtained between 03:00 and 04:00 (CET).

I have this setting for all my customers,
who are connected to a "similar connection",
set up in exactly the same way.

The domain (the ID-, Connection- & API- server)
"runs" via a STRATO DynDNS,
which is set up directly on the FRITZ! Box.

Once the new IP address has been obtained,
it takes up to 10 minutes for the DynDNS to point to the new IP address.

I therefore assume,
that the RustDesk clients "notice",
that the IP of their connection has changed,
try to "communicate" this to the server,
but cannot reach it
and "try their luck" with another server,
which gives them a new ID.

**Comment by rustdesk** [comment]
Thanks @IT-Betreuung , I can now constantly reproduce ip change -> id change on our side. This is not expected. It is a bug indeed. We will try to fix this.

**Comment by mikekgr** [comment]
> Thanks @IT-Betreuung , I can now constantly reproduce ip change -> id change on our side with the nightly build, and we also see logs not generated. This is not expected. It is a bug indeed. We will try to fix this.

I saw that you track the problem but let me add: I faced the same problem and looking at the logs (both for user and root) nothing found, I mean grep "stack" ...      returns nothing.

**Comment by rustdesk** [comment]
Yes, I saw this log bug.

**Comment by rustdesk** [comment]
Fixed in nightly build, work well per my test.

**Comment by mikekgr** [comment]
> Fixed in nightly build #7579, work well in my test.

Thanks a lot. I will test it in a moment. Meanwhile help me if it is possible, is there any easy way to change the current ID with an "OLD" id? If yes, show me how.
Thanks !

**Comment by rustdesk** [comment]
Apologize there is no easy way to change to "OLD" id.

**Comment by mikekgr** [comment]
> Apologize there is no easy way to change to "OLD" id for the time being. Here is a proposal of changing id from web console, we are still considering. [rustdesk/rustdesk-server-pro#225](https://github.com/rustdesk/rustdesk-server-pro/discussions/225)

Thanks for your reply. Sorry to hear that. Further more I use the free version so the pro things aren't for me. Please consider an easy utility to perform this id changing.

Best Regards,
Mike Kranidis
