### ISSUE TITLE
Compile 32-bit software, running normally, forced to shut down when remotely controlling other hosts

### ISSUE THREAD

**Issue by chenjin1993** [rustdesk/rustdesk#7529]
### Bug Description

The compiled 32-bit program, after successfully verifying the connection IP and password, forcibly closes the window while waiting for the remote desktop image to be established
![2024-03-26_174629](https://github.com/rustdesk/rustdesk/assets/26199193/97da368c-31b7-46f6-9b33-9370b7e91192)
![2024-03-26_174720](https://github.com/rustdesk/rustdesk/assets/26199193/561807d9-d838-4c17-9b1b-f4e48e3d3100)
![2024-03-26_174743](https://github.com/rustdesk/rustdesk/assets/26199193/59f665e8-1fd9-4bad-82bc-283ae9d6f076)

**Operation video recording：**
https://github.com/rustdesk/rustdesk/assets/26199193/5d1c35ad-6445-406c-832b-e3c52469301b

### How to Reproduce

Step 1: Compile the 32-bit program;
Step 2: Enter the connection IP and password;
Step 3: After successful verification, the remote window is forced to close while waiting for the remote desktop image to be created;

### Expected Behavior

Step 1: Compile the 32-bit program;
Step 2: Enter the connection IP and password;
Step 3: After successful verification, the remote window is forced to close while waiting for the remote desktop image to be created;

### Operating system(s) on local side and remote side

windows10 64bit

### RustDesk Version(s) on local side and remote side

1.2.4

### Screenshots

https://github.com/rustdesk/rustdesk/assets/26199193/fe3728f9-99f0-446c-ba04-b26b6a82c44c

**Comment by rustdesk** [comment]
#763

**Comment by chenjin1993** [comment]
> #763

You don't need to close it directly for me. I am building a 32-bit program in the Windows 10 environment, and your official guidance document does not explain it; And I have successfully compiled it, but when connecting remotely, the window may close. I hope you can help answer this question, thank you!
