### ISSUE TITLE
Unsupported display server tty, x11 expected

### ISSUE THREAD

**Issue by kars0n777** [rustdesk/rustdesk#7531]
### Bug Description

I can't run remote into my machine as it says "Unsupported display server tty, x11 expected"

### How to Reproduce

I installed `rustdesk-bin` from the AUR and `rustdesk-openrc` since I'm on Artix Linux. I run `dwm` using `startx` to start my Xorg session.

### Expected Behavior

To be able to remote into my machine and latop (both have the same artix/dwm setup and both get the error

### Operating system(s) on local side and remote side

Artix Linux

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

![2024-03-26-17-19-54-07-00](https://github.com/rustdesk/rustdesk/assets/79391709/ec2b7ef4-f295-4c44-b31e-08796a6a83c2)

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/5195

**Comment by rustdesk** [comment]
Please try out nightly build? https://github.com/rustdesk/rustdesk/releases/tag/nightly. Not sure if fix this, but we did have a lot of change about this.

**Comment by kars0n777** [comment]
I just tried the nightly build from [the aur](https://aur.archlinux.org/packages/rustdesk-nightly) and still same error.

**Comment by rustdesk** [comment]
Then have to say sorry, we have no plan to dev on no-display-manager scenario for the time being.

**Comment by ascendforever** [comment]
Same issue here, except the connection is from Qubes to Arch. I'm using rustdesk 1.3.0 on both.

**Comment by FraYoshi** [comment]
Same issue with the appimage on Arch. Unsupported dispay server tty, x11 expected. But running xfce4 (xfwm4, x11)

**Comment by DrewRidley** [comment]
Try setting,

```
XDG_SESSION_TYPE=wayland
```
when running rustdesk. It should solve this problem.

**Comment by FraYoshi** [comment]
It indeed did the trick, warning gone! 🥳

**Comment by artkpv** [comment]
This is interesting app. Thanks to the contributors. It does not work for me. I share my PC (ArchLinux) screen at my Android device (e-book). When I try to connect at the Android device to the rustdesk at my PC the error pops up at the Android device: "Login error", "Unsupported display server type "tty", x11 or wayland expected". No error at the rustdesk at the PC: it shows the confirmation dialog to accept an incomming connection and when I confirm it the error pops up at the Android device. I tried running rustdesk at the Archlinux with `XDG_SESSION_TYPE=x11 rustdesk` , the same error.

@DrewRidley @rustdesk
