### ISSUE TITLE
Non-latin characters become tofu

### ISSUE THREAD

**Issue by ckykenken** [rustdesk/rustdesk#7535]
### Bug Description

I need to use Chinese UI and it shows tofu

### How to Reproduce

Just run the program

### Expected Behavior

The UI should look like this as if on Windows

### Operating system(s) on local side and remote side

Manjaro ARM -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.[3,4] -> 1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/26035978/fcb903f4-dbd7-43f3-8d10-12fdb2e93191)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
