### ISSUE TITLE
The discovery of a completely unknown device

### ISSUE THREAD

**Issue by dixtdf** [rustdesk/rustdesk#7550]
### Bug Description

I'm using rustdesk-server to build my own nbbs and nbbr, and I found an unknown mac device inside the discovery tab.

### How to Reproduce

always

### Expected Behavior

It shouldn't be here. I don't recognize it.

### Operating system(s) on local side and remote side

Window10

### RustDesk Version(s) on local side and remote side

releases: 1.2.3-1 Build Date: 2024-02-19 17:25

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/106577535/4daf6fbf-8f73-4ee4-b422-11fc3aaf3781)

**Comment by rustdesk** [comment]
#763
