### ISSUE TITLE
Rustdesk display wrong orientation and scale when connecting to RK3588 kiosk board with screen rotation

### ISSUE THREAD

**Issue by goodwill** [rustdesk/rustdesk#7553]
### Bug Description

When I installed RustDesk on a RK3588 based kiosk mainboard + Android 12, the screen orientation of the remote connection is wrong - basically it display as landscape like, with the screen mostly cutoff and touch location completely off.

### How to Reproduce

Just direct install and connect Rustdesk

### Expected Behavior

Screen should properly show as portrait and with proper touch points.

### Operating system(s) on local side and remote side

Mac / iPhone -> Android 12

### RustDesk Version(s) on local side and remote side

1.2.3 (39) -> 1.2.3-2 (via F-Droid)

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/18467/9c8d83a1-099e-4436-8ee0-b8722dd819cf)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893
