### ISSUE TITLE
ID/Relay server popup closes immediately

### ISSUE THREAD

**Issue by lucas-dehandschutter** [rustdesk/rustdesk#756]
**Describe the bug you encountered:**
Once installed on Ubuntu 22.04, after the wayland deactivation procedure and a reboot, I tried to add my own relay server by selecting the id/relay server in the menu. Then a popup open but once I click/type anything, the popup closes immediately.
...

**What did you expect to happen instead?**
I expect to be able to define my own relay server using the menu.
...

**How did you install `RustDesk`?**

Downloaded the 1.1.9.deb file frome the website and installed it with:

`sudo dpkg -i rustdesk-1.1.9.deb`
---

**RustDesk version and environment**

OS: Ubuntu 22.04 LTS Desktop (also occur on Ubuntu 20.04 LTS Desktop)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/726

**Comment by rustdesk** [comment]
deb updated https://github.com/rustdesk/rustdesk/releases/tag/1.1.9
