### ISSUE TITLE
Rotated Display Issue on Raspberry Pi v4

### ISSUE THREAD

**Issue by alptugan** [rustdesk/rustdesk#7564]
### Bug Description

I am using RPi 4 display in portrait mode. It is rotated via desktop gui.

### How to Reproduce

- RPI 4, debian OS with desktop 
- Download and install [rustdesk-1.2.3-1-aarch64.deb](https://github.com/rustdesk/rustdesk/releases/download/1.2.3-1/rustdesk-1.2.3-1-aarch64.deb)
- Rotate the screen using "Screen Layout Editor" on RPI 4
- Download and install RustDesk on M2 Macbook Pro
- Open the app and connect to RPi from Mac 

### Expected Behavior

The screen of RPi is shown as expected. But the mouse position is not rotated on RustDesk client. E.g: 
Normally, if the screen is not rotated on RPi desktop, the start menu button on taskbar is located on the top-left corner. When the screen is rotated, it is seen as expected on the RustDesk client, but the the position of the GUI elements behave as if the screen was not rotated. When I click on the top-left clock, the start menu opens.

### Operating system(s) on local side and remote side

Mac OS - aarch64 -> RPI 4 Debian - aarch64 

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

![318210192-72c0a556-ad2f-43e5-97d2-99a8a51aaa16](https://github.com/rustdesk/rustdesk/assets/315287/41b54461-ff2d-4aef-b6c9-0ad7c5937167)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
