### ISSUE TITLE
Release unzipped Windows execuatables for Winget

### ISSUE THREAD

**Issue by sitiom** [rustdesk/rustdesk#758]
Winget doesn't support zipped files yet (https://github.com/microsoft/winget-cli/issues/140), so it would be great to release https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-windows_x64.zip and https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-windows_x32.zip unzipped (i.e., the `.exe` file itself) for now.

**Comment by rustdesk** [comment]
I do not wanna support x32 in Winget.

**Comment by sitiom** [comment]
Why? It's available, so why not just add it?

**Comment by rustdesk** [comment]
I do not wanna spend extra time on it.

**Comment by sitiom** [comment]
It would be added regardless, if you don't want to support 32-bit just stop releasing them altogether.

**Comment by rustdesk** [comment]
Let me investigate on Winget first before investing time on it.

**Comment by rustdesk** [comment]
Thank you very much.

**Comment by rustdesk** [comment]
Winget only works on Win10, do we really have 32-bit Win10 machines?

**Comment by rustdesk** [comment]
I am afraid of wrong installation causes us trouble, because they will ask issues on our GitHub.

**Comment by sitiom** [comment]
> Winget only works on Win10

Windows 10 and 11*

>  do we really have 32-bit Win10 machines?

Yes, but Windows 11 does not have 32-bit. if you didn't want to support 32-bit in the first place, why release one? If you stop releasing 32-bit if you don't want to support it.

> Where will be RustDesk installed with Winget?

Same as with `rustdesk-1.1.9-putes.exe --silent-install`. Winget doesn't do anything else than call the installer of the program

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9.exe

building 32 ...

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-x32.exe
https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-x64.exe

**Comment by rustdesk** [comment]
Please let me know when Winget is ready.

**Comment by sitiom** [comment]
Thanks, just a little nitpick: `x86` is the proper name of the 32-bit architecture, not `x32`.

**Comment by rustdesk** [comment]
86 > 64, haha.

**Comment by sitiom** [comment]
@rustdesk You can watch the ongoing Winget PR here: https://github.com/microsoft/winget-pkgs/pull/63466

**Comment by rustdesk** [comment]
Got it
