### ISSUE TITLE
"ID does not exist" when self-hosting in version 1.2.3 and connecting with client 1.2.3-1

### ISSUE THREAD

**Issue by esberngeilini** [rustdesk/rustdesk#7583]
### Bug Description

My self-host server and environment has run without issues for version 1.2.3, but the latest users that have tried to connect usingversion 1.2.3-1 ran into "ID does not exist" issues when trying to connect, even though the ID existed and users who previously had connected were still able to connect.
The issue was only for new users.

The issue is for Windows 64-bit. Works fine for Android version.

### How to Reproduce

Set up a self-host, and prepare two clients on different devices. One with version 1.2.3 (Windows 64-bit) and one with version 1.2.3-1 (Windows 64-bit)
Setup both clients to use the self-host server, and try to connect client with version 1.2.3-1 to client with version 1.2.3
A "ID does not exist" appears.

To fix the issue, I had to remove RustDesk from the AppData/Roaming folder and restart the device on the device that had version 1.2.3-1. Then I had to user the lower version (1.2.3) to connect.

Afterwards, I could connect using 1.2.3-1 version without issue.

### Expected Behavior

Should connect without issue

### Operating system(s) on local side and remote side

Windows 10 -> Windows 7

### RustDesk Version(s) on local side and remote side

1.2.3-1 -> 1.2.3

### Screenshots

![429928526_677974091052664_5728270511951185620_n](https://github.com/rustdesk/rustdesk/assets/76955143/ae1f5fd0-9ac9-4e85-967f-827b19d48e80)

**Comment by rustdesk** [comment]
#763
