### ISSUE TITLE
The compiled 32-bit program cannot be remotely accessed by others, it can only be remotely accessed by others

### ISSUE THREAD

**Issue by chenjin1993** [rustdesk/rustdesk#7596]
### Bug Description

The compiled 32-bit program cannot be remotely accessed by others, it can only be remotely accessed by others

### How to Reproduce

Step 1: Compile the 32-bit program;
Step 2: Enter the connection IP and password;
Step 3: After successful verification, the remote window is forced to close while waiting for the remote desktop image to be created;

### Expected Behavior

15/10000
实时翻译
15/10000实时翻译划译编译后的32位程序可以由其他人远程访问

划译
The compiled 32-bit program can be remotely accessed by others

### Operating system(s) on local side and remote side

windows10 64bit -> windows10 64bit

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

https://github.com/rustdesk/rustdesk/assets/26199193/47399623-7625-43ea-bfb8-43d5f5b2fd7c

**Comment by rustdesk** [comment]
#763
