### ISSUE TITLE
Can not remote control mobile？QtScrcpy is slow to control mobile

### ISSUE THREAD

**Issue by zhangbo8418** [rustdesk/rustdesk#76]
I use QtScpy to remote control mobile phone, the LAN is pretty good, but it is stuck when I use 5G,  as below.

我用QtScrcpy远程手机，局域网蛮流畅的，但是我用5G就好卡，就像下面那样，卡死了。。。
https://user-images.githubusercontent.com/46797568/122165636-0f847300-ceab-11eb-81df-4dfa3be8df7a.mp4

**Comment by rustdesk** [comment]
Relay server is in  Seoul.

**Comment by rustdesk** [comment]
Controlling mobile is in the plan, but not with highest priority.

**Comment by rustdesk** [comment]
We need to finish Wayland, iOS support first.

**Comment by rustdesk** [comment]
https://github.com/Genymobile/scrcpy

**Comment by rustdesk** [comment]
Google play version can, but still not stable.
