### ISSUE TITLE
The screen live menu does not get updated for nightly after 01/04/2024

### ISSUE THREAD

**Issue by mikekgr** [rustdesk/rustdesk#7602]
### Bug Description

The drop down screen menu does not visually show users selection. The function activated or deactivated but it does not update the menu appearance 

### How to Reproduce

Just run e.g. the today nightly build in Windows 10 or 11 and select from live screen menu the "Show quality monitor". The functionality will be there but the menu shows inactivated the "Show quality monitor" but it is !

### Expected Behavior

to follow user selection

### Operating system(s) on local side and remote side

Windows 10 / 11 to Windows 10 / 11

### RustDesk Version(s) on local side and remote side

1.2.4 Today Nightly

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/15084551/a67e5e15-fe4e-454b-afd7-38e27cfa034e)

**Comment by fufesou** [comment]
Thanks for your feedback.

This bug is introduced by upgrading flutter to 3.19.5.

I'll try fix it.

**Comment by rustdesk** [comment]
close as fix merged
