### ISSUE TITLE
Android kiosk in portrait mode results half screen display

### ISSUE THREAD

**Issue by goodwill** [rustdesk/rustdesk#7615]
### Bug Description

From original post #7553 , we now change the native display orientation of the device to portrait, while now the touch works (I tried to click the bottom middle will successfully trigger home even the display is black), the screen output ends at around a square - I believe around 1080p. 

### How to Reproduce

Use a kiosk mainboard with native portrait 1920x1080 display

### Expected Behavior

Full screen should be displayed

### Operating system(s) on local side and remote side

MacOS -> Android

### RustDesk Version(s) on local side and remote side

1.2.3 (39) -> 1.2.3-2 (via F-Droid)

### Screenshots

![rustdesk-half-screen](https://github.com/rustdesk/rustdesk/assets/18467/4b549d11-07a4-4478-b157-54f44920a36b)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893
