### ISSUE TITLE
crash update 1.2.3 to 1.2.3-1

### ISSUE THREAD

**Issue by hueldoeu** [rustdesk/rustdesk#7617]
### Bug Description

somehow rustdusk crashes when updating from 1.2.3 to 1.2.3-1 on windows server 2012 but deinstalling and then reinstalling solved it.

### How to Reproduce

open rustdesk.exe v1.2.3-1 and click on upgrade. crash. rustdesk also won't get updated.

### Expected Behavior

upgrade successful

### Operating system(s) on local side and remote side

windows server 2012

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

no

**Comment by rustdesk** [comment]
#763

**Comment by hueldoeu** [comment]
a reminder to myself, if the .msi wants to deinstall, it looks like this
![image](https://github.com/rustdesk/rustdesk/assets/11273667/96a1a351-3809-4983-9efa-484936522e5b)
and this if the .exe had been installed
![image](https://github.com/rustdesk/rustdesk/assets/11273667/dbf89165-cef1-44b5-bea8-6f7b4136fd04)
