### ISSUE TITLE
Unable to click on Oculus Quest 3

### ISSUE THREAD

**Issue by Limdel** [rustdesk/rustdesk#7621]
### Bug Description

I'm using android client on Oculus Quest 3 to connect to Arch Linux desktop. I'm able to connect, type on my keyboard, move mouse cursor, but the only thing that doesn't work is clicking.

### How to Reproduce

1) Install apk on Meta Quest 3
2) Connect to Linux Desktop
3) Try to click on something

### Expected Behavior

Nice working clicking

### Operating system(s) on local side and remote side

Meta Quest 3 Android firmware v64 -> Arch Linux

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

The only successful click was made from laptop keyboard, not remote one.
https://youtu.be/EGlhm27aP6A

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893
