### ISSUE TITLE
RustDesk flatpak 'copy / paste' not working

### ISSUE THREAD

**Issue by BentHaase** [rustdesk/rustdesk#7638]
### Bug Description

When connected to a host (e.g. Windows) copy and paste from the client (Linux system) does not work even though clipboard is **not** disabled.

### How to Reproduce

1. Use recent Linux System with Wayland (e.g. Fedora 39)
2. Download latest flatpak `curl -O https://github.com/rustdesk/rustdesk/releases/download/1.2.3-1/rustdesk-1.2.3-1-x86_64.flatpak`
3. Install flatpak `sudo flatpak install rustdesk-1.2.3-1-x86_64.flatpak`
4. Launch RustDesk and connect to host
5. Copy something on client
6. Paste on host

### Expected Behavior

The copied text from the client (aka. connecting system) appears upon pasting on the host system.

### Operating system(s) on local side and remote side

Fedora 39 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3-1

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/5788982/7ec86a1b-7295-466b-8df7-f3cd8f89f027)

(the text explains the issue already)

### Additional Context

Maybe relevant information: https://wayland.app/protocols/wlr-data-control-unstable-v1

Potential fix (?): https://github.com/solopasha/bitwarden_flatpak/blob/build-from-source/wayland-clipboard.patch

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/5900
