### ISSUE TITLE
RHEL 8.6 Bad Display Exception

### ISSUE THREAD

**Issue by longmoon77** [rustdesk/rustdesk#764]
**Describe the bug you encountered:**

![U2YS2}YP(~E2N5FK2Z 6T1P](https://user-images.githubusercontent.com/62339707/173477623-4c7bda53-ff7c-4941-b819-42197fc72ef1.png)

**What did you expect to happen instead?**

![_GABS9ZACNJ}MX2(BMI90}I.png](https://user-images.githubusercontent.com/62339707/173475957-146263dc-1571-4390-8a6f-a491c8461928.png)

**How did you install `RustDesk`?**

Github Release
rustdesk-1.1.9-fedora28-centos8.rpm
with dependency _cjkuni-uming-fonts_ (from _Raven_ repository) installed

**RustDesk version and environment**

RustDesk version: ![N2VBW7R1MP_60Q1C420M$KR.png](https://user-images.githubusercontent.com/62339707/173476684-2467a981-1784-4c49-964e-a33306db95a5.png)

Linux Distribution: AlmaLinux 8.6 Sky Tiger (fork of Red Hat Enterprise Linux 8.6)

Display server: X11

![QFC$)BMRSLRDO5Q{485Z_{W(1).png](https://user-images.githubusercontent.com/62339707/173477155-e009b010-8289-4924-8012-320268a904e4.png)

![3J~PH%D2Q0G~IYM8~S9RV(C.png](https://user-images.githubusercontent.com/62339707/173477173-39f41f7e-4964-455c-b9ff-9f0c7cc0b1dc.png)

**Comment by rustdesk** [comment]
Thanks

**Comment by grummbeer** [comment]
realated to #1073

@longmoon77 can you try the nightly build? https://github.com/rustdesk/rustdesk/releases/tag/nightly
