### ISSUE TITLE
android deep link failed

### ISSUE THREAD

**Issue by JerryMoon** [rustdesk/rustdesk#7647]
### Bug Description

In version 1.3.2-2, there is an intent-filter for the deep link in the [manifest](https://github.com/rustdesk/rustdesk/blob/1.2.3-2/flutter/android/app/src/main/AndroidManifest.xml) file, but my test couldn't find the dp activity. Has the PR that supports deep links been merged in version 1.3.2-2, or is there a problem with my operation?

adb shell am start -W -a android.intent.action.VIEW -d rustdesk://1234567890 com.carriez.flutter_hbb
Starting: Intent { act=android.intent.action.VIEW dat=rustdesk://1234567890/... pkg=com.carriez.flutter_hbb }
Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=rustdesk://1234567890/... flg=0x10000000 pkg=com.carriez.flutter_hbb }

adb shell am start -a android.intent.action.VIEW -c android.intent.category.BROWSABLE -c android.intent.category.DEFAULT -d rustdesk://1234567890
Starting: Intent { act=android.intent.action.VIEW cat=[android.intent.category.DEFAULT,android.intent.category.BROWSABLE] dat=rustdesk://1234567890/... }
Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW cat=[android.intent.category.DEFAULT,android.intent.category.BROWSABLE] dat=rustdesk://1234567890/... flg=0x10000000 }

### How to Reproduce

use adb command or mobile browser <a href="rustdesk://xxxx">

### Expected Behavior

open rustdesk app and connect

### Operating system(s) on local side and remote side

android

### RustDesk Version(s) on local side and remote side

1.2.3-1  1.2.3-2

### Screenshots

/

**Comment by rustdesk** [comment]
In nightly only.
