### ISSUE TITLE
MacOS keep service running after close main window

### ISSUE THREAD

**Issue by xiaozhuai** [rustdesk/rustdesk#77]
Cannot connect to MacOS after close main window

1. Add a tray icon and keep service running
2. Add service auto start (but do not open main window)
3. Add an option for hiding from dock

**Comment by rustdesk** [comment]
Yes, background service is not implemented yet for MacOS, it is also in my todo list.

**Comment by xiaozhuai** [comment]
Any progress?

**Comment by rustdesk** [comment]
Sorry, but still in pending to-do list

**Comment by xiaozhuai** [comment]
@rustdesk : ) Thanks! Waiting for good news.

**Comment by rustdesk** [comment]
Applogize, lately I spend most of time on building team and thinking about the future of the product, few time on dev. Once everything is settled down, the progress will be fast.

**Comment by rustdesk** [comment]
“ Sharpening your axe will not delay your job of chopping wood.” ：）

**Comment by rustdesk** [comment]
https://github.com/stweil/OSXvnc/issues/1#issuecomment-270301314
