### ISSUE TITLE
Fix buttons of crtl,alt,etc for physical keyboard.

### ISSUE THREAD

**Issue by smarttommyau** [rustdesk/rustdesk#772]
This does not appear when phsical keyboard is being used

**Comment by rustdesk** [comment]
You physical keyboard does not have thoese?

**Comment by smarttommyau** [comment]
the input sometimes cant capture them because of some weird input and my physical keyboard doesnt have esc.

**Comment by rustdesk** [comment]
Give me a picture of your keyboard please.

**Comment by smarttommyau** [comment]
![IMG_20220614_190424_edit_488455260948903](https://user-images.githubusercontent.com/75346987/173563205-e17f0e83-0f63-4626-9b72-50eea27a371e.jpg)

**Comment by smarttommyau** [comment]
And also simpily adding a button to toogle the menu should not affect the user experience and can fix input problems

**Comment by smarttommyau** [comment]
i think some of the button on the physical keyboard is being catch by the system for example alt-tab, so maybe those buttons are catch by the system cause it works weirdly.
