### ISSUE TITLE
When using the Delete key to delete an ID, the application closes

### ISSUE THREAD

**Issue by luapfr** [rustdesk/rustdesk#7731]
### Bug Description

When using the Delete key to delete an ID, the application closes

See the attached video.

Windows 11

### How to Reproduce

When using the Delete key to delete an ID, the application closes

See the attached video.

Windows 11

### Expected Behavior

When using the Delete key to delete an ID, the application closes

See the attached video.

Windows 11

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

All

### Screenshots

[Delete RustError.webm](https://github.com/rustdesk/rustdesk/assets/50739062/1c007f00-3c84-4f4d-b94a-a5dcc270d4e6)

**Comment by rustdesk** [comment]
please confirm if https://github.com/rustdesk/rustdesk/releases/tag/nightly has the same issue

**Comment by rustdesk** [comment]
Will reopen if confirmed nightly build.
