### ISSUE TITLE
Privacy Mode Failed on Windows 11 Device

### ISSUE THREAD

**Issue by i7phillip** [rustdesk/rustdesk#7735]
### Bug Description

When connected to a Windows 11 device, when I click on "Privacy Mode" I get an error "Privacy mode failed".

![image](https://github.com/rustdesk/rustdesk/assets/100315674/7468306e-d7c0-4930-83e4-f8242c196ce9)

### How to Reproduce

Connect to pc, check the box next to Privacy Mode in the menu

### Expected Behavior

Blank end user screen

### Operating system(s) on local side and remote side

Windows 11 (both)

### RustDesk Version(s) on local side and remote side

1.2.2

### Screenshots

https://github.com/rustdesk/rustdesk/assets/100315674/3192cbf8-f638-4389-be9b-dc122e5a47ce

### Additional Context

OSS Self-hosted server, installed using latest build and instructions.

**Comment by fufesou** [comment]
Hi, can you please try the latest nightly build on both sides?
The error message is not good with 1.2.2.

**Comment by rustdesk** [comment]
Will reopen if confirmed nightly build.

**Comment by i7phillip** [comment]
Updated both sides to 1.2.3-2. Getting the following error:

![image](https://github.com/rustdesk/rustdesk/assets/100315674/489abe4d-7ae4-4fb9-804c-e712c1ea6d3f)

**Comment by fufesou** [comment]
I cannot finger out the reason of the error.
It just says the privacy window cannot be found after starting the target process.

Please do the following steps to get more clues:
1. Open the command line. Run `tasklist | findstr RuntimeBroker`, to see if there're processed named `RuntimeBroker_rustdesk.exe`
2. Open Windows Event Viewer, and see if there are any errors when switching privacy mode. 
    a. Press "Win"
    b. Input "Event Viewer"
    c. "Event Viewer(Local)" --> "Windows Logs" --> "Application"
3. What error do you get when you try toggle privacy mode the next time?

**Comment by i7phillip** [comment]
I appreciate the help. I’ll give it a try tomorrow 

Thank you,

Phillip Davis
i7MEDIA, LLC | www.i7media.com
Phone: 816-479-0233 Direct: 816-479-0232

Need hosting, web design or development? Check us out!

On Apr 16, 2024, at 22:27, fufesou ***@***.***> wrote:

﻿

I cannot finger out the reason of the error.
It just says the privacy window cannot be found after starting the target process.
Please do the following steps to get more clues:

- Open the command line. Run tasklist | findstr RuntimeBroker, to see if there're processed named RuntimeBroker_rustdesk.exe
- Open Windows Event Viewer, and see if there are any errors when switching privacy mode.
a. Press "Win"
b. Input "Event Viewer"
c. "Event Viewer(Local)" --> "Windows Logs" --> "Application"
- What error do you get when you try toggle privacy mode the next time?
