### ISSUE TITLE
Using windows to control Android (moto), typing on PC cannot input any letters to Android

### ISSUE THREAD

**Issue by zclikezc** [rustdesk/rustdesk#7737]
### Bug Description

Using windows to control Android (moto), typing on PC cannot input any letters to Android

### How to Reproduce

Using windows to control Android (moto), typing on PC cannot input any letters to Android

### Expected Behavior

Using windows to control Android (moto), typing on PC cannot input any letters to Android

### Operating system(s) on local side and remote side

Windows 11 -> Android

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.3

### Screenshots

Using windows to control Android (moto), typing on PC cannot input any letters to Android

**Comment by rustdesk** [comment]
dupliate

**Comment by rustdesk** [comment]
https://twitter.com/rustdesk/status/1721795544689922168
