### ISSUE TITLE
Extend search field | username, hostname

### ISSUE THREAD

**Issue by Vogelbusch** [rustdesk/rustdesk#774]
Is it possible to extend the function of the search field to find username and hostname?
![grafik](https://user-images.githubusercontent.com/107399413/173579312-89a628ac-1c1f-4885-82f0-3a7a58cd5601.png)

**Comment by rustdesk** [comment]
@asur4s

**Comment by rustdesk** [comment]
@Kingtous +https://github.com/rustdesk/rustdesk/issues/774

**Comment by Kingtous** [comment]
ok，got it.

**Comment by grummbeer** [comment]
working. this can be closed.
