### ISSUE TITLE
Password keeps changing by itself.

### ISSUE THREAD

**Issue by luapfr** [rustdesk/rustdesk#7741]
### Bug Description

Why does the password keep changing?

I don't want to put a unique password, but I think the password could only change if I close and open RustDesk again, but it keeps changing from time to time, there seems to be a timer that it will change, why is that?

is configured to accept password in both modes.

### How to Reproduce

....

### Expected Behavior

...

### Operating system(s) on local side and remote side

Windows 7, 10, 11 etc...

### RustDesk Version(s) on local side and remote side

All

### Screenshots

....

**Comment by rustdesk** [comment]
https://www.reddit.com/r/rustdesk/comments/1c2pmi9/password_resets_often/
