### ISSUE TITLE
Memory leaking  MAC OS 13

### ISSUE THREAD

**Issue by lovitus** [rustdesk/rustdesk#7747]
### Bug Description

reaching more than 2G memory usage after few days  (only standby , no remote control connected before )

### How to Reproduce

open Rustdesk, keep it in background running .

### Expected Behavior

drain reasonable memory usage 

### Operating system(s) on local side and remote side

Macos 13

### RustDesk Version(s) on local side and remote side

1.2.3(39)

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/14361541/d44350b7-68c6-4d94-90da-d44a047d6a2d)

**Comment by rustdesk** [comment]
try out https://github.com/rustdesk/rustdesk/releases/nightly please

**Comment by lovitus** [comment]
> try out https://github.com/rustdesk/rustdesk/releases/nightly please

problem solved in nightly version .
