### ISSUE TITLE
RustDesk iOS -> Android - No audio in Chrome browser app

### ISSUE THREAD

**Issue by plia7** [rustdesk/rustdesk#7749]
### Bug Description

When I connect to an Android target using RustDesk iOS app, go to Chrome browser, open a website with some audio playback and click play - I can't hear the audio.
### 

### How to Reproduce

1. Connect to an Android target using RustDesk iOS app. 

2. Open Chrome browser app (version Chrome 94.0.4606.85) and open a website with audio playback such as:
https://www2.iis.fraunhofer.de/AAC/multichannel.html

3. Click play.

### Expected Behavior

Audio should be heard just like audio is heard in other audio based apps such as Youtube app, games apps, etc.

### Operating system(s) on local side and remote side

iOS 14.4.1 -> Android 11; moto g pure Build/RRHS31.Q3-46-123-5-4

### RustDesk Version(s) on local side and remote side

1.1.10 -> 1.1.10-1

### Screenshots

Website with audio playback example:

https://www2.iis.fraunhofer.de/AAC/multichannel.html

### Additional Context

Other audio based apps such as Youtube and games apps audio is heard through RustDesk iOS so it's only an issue with Chrome browser app.

**Comment by rustdesk** [comment]
tracked by  https://github.com/rustdesk/rustdesk/issues/3893
