### ISSUE TITLE
voice call no sound

### ISSUE THREAD

**Issue by changsheng123456789** [rustdesk/rustdesk#7754]
### Bug Description

connect to a windows 10 and win7 pc,voice call connected,but no sound

### How to Reproduce

Try to connect using windows10 to windows 10

### Expected Behavior

Person automatically can hear my voice and I can hear him

### Operating system(s) on local side and remote side

windows10->windows10； windows7->windows10

### RustDesk Version(s) on local side and remote side

1.2.3-2>1.2.3.-2

### Screenshots

![1](https://github.com/rustdesk/rustdesk/assets/167416248/33838cd4-1282-4c90-aeb1-31d56d6108b0)
![2](https://github.com/rustdesk/rustdesk/assets/167416248/ca4a3a95-d12e-40ed-ba26-c84740c8c60e)

**Comment by rustdesk** [comment]
Using ASIO like this https://github.com/rustdesk/rustdesk/issues/3762#issuecomment-1868437852?

**Comment by changsheng123456789** [comment]
I have self-built a Windows version RustDesk server. When testing voice calls using several Windows PCs, we are unable to hear each other's voices on all tested computers.

**Comment by rustdesk** [comment]
Please test https://github.com/rustdesk/rustdesk/pull/7922

**Comment by rustdesk** [comment]
close as fix merged
