### ISSUE TITLE
Build flutter on window10

### ISSUE THREAD

**Issue by xubingyan** [rustdesk/rustdesk#7755]
### Bug Description

E:\workspace\code\rustdesk>flutter_rust_bridge_codegen --llvm-path D:\\Program Files\\LLVM --rust-input ./src/flutter_ffi.rs --dart-output ./flutter/lib/generated_bridge.dart
2024/04/18 17:36:02 [WARN] Skipping unresolvable module inline (tried \\?\E:\workspace\code\rustdesk\src\inline.rs, \\?\E:\workspace\code\rustdesk\src\inline\mod.rs, \\?\E:\workspace\code\rustdesk\src\ui\inline.rs, \\?\E:\workspace\code\rustdesk\src\ui\inline\mod.rs, )
2024/04/18 17:36:02 [WARN] Skipping unresolvable module version (tried \\?\E:\workspace\code\rustdesk\src\version.rs, \\?\E:\workspace\code\rustdesk\src\version\mod.rs, \\?\E:\workspace\code\rustdesk\src\lib\version.rs, \\?\E:\workspace\code\rustdesk\src\lib\version\mod.rs, )
2024/04/18 17:36:02 [WARN] Skipping unresolvable module io (tried \\?\E:\workspace\code\rustdesk\src\io.rs, \\?\E:\workspace\code\rustdesk\src\io\mod.rs, \\?\E:\workspace\code\rustdesk\src\bridge_generated\io.rs, \\?\E:\workspace\code\rustdesk\src\bridge_generated\io\mod.rs, )
2024/04/18 17:36:02 [INFO] Phase: Validate config(s)
2024/04/18 17:36:02 [INFO] Picked config: Opts { rust_input_path: "E:\\workspace\\code\\rustdesk\\./src/flutter_ffi.rs", dart_output_path: "E:\\workspace\\code\\rustdesk\\./flutter/lib/generated_bridge.dart", dart_decl_output_path: None, c_output_path: ["C:\\Users\\35328\\AppData\\Local\\Temp\\.tmpem7YVD.h"], rust_crate_dir: "E:\\workspace\\code\\rustdesk", rust_output_path: "E:\\workspace\\code\\rustdesk\\./src\\bridge_generated.rs", class_name: "Rustdesk", dart_format_line_length: 80, dart_enums_style: false, skip_add_mod_to_lib: false, llvm_path: ["D:\\\\Program", "Files\\\\LLVM"], llvm_compiler_opts: "", manifest_path: "E:\\workspace\\code\\rustdesk\\Cargo.toml", dart_root: Some("E:\\workspace\\code\\rustdesk\\./flutter"), build_runner: true, block_index: BlockIndex(0), skip_deps_check: false, wasm_enabled: false, inline_rust: false, bridge_in_method: true, extra_headers: "", dart3: true, keep_going: false }
2024/04/18 17:36:02 [INFO] Phase: Parse source code to AST, then to IR
2024/04/18 17:36:04 [WARN] Skipping unresolvable module inline (tried \\?\E:\workspace\code\rustdesk\src\inline.rs, \\?\E:\workspace\code\rustdesk\src\inline\mod.rs, \\?\E:\workspace\code\rustdesk\src\ui\inline.rs, \\?\E:\workspace\code\rustdesk\src\ui\inline\mod.rs, )
2024/04/18 17:36:04 [WARN] Skipping unresolvable module version (tried \\?\E:\workspace\code\rustdesk\src\version.rs, \\?\E:\workspace\code\rustdesk\src\version\mod.rs, \\?\E:\workspace\code\rustdesk\src\lib\version.rs, \\?\E:\workspace\code\rustdesk\src\lib\version\mod.rs, )
2024/04/18 17:36:04 [WARN] Skipping unresolvable module io (tried \\?\E:\workspace\code\rustdesk\src\io.rs, \\?\E:\workspace\code\rustdesk\src\io\mod.rs, \\?\E:\workspace\code\rustdesk\src\bridge_generated\io.rs, \\?\E:\workspace\code\rustdesk\src\bridge_generated\io\mod.rs, )
2024/04/18 17:36:04 [INFO] Phase: Transform IR
2024/04/18 17:36:04 [INFO] Phase: Generate Rust code
2024/04/18 17:36:04 [INFO] Phase: Generate Dart code
Flutter 3.22.0-12.0.pre.30 • channel master • https://github.com/flutter/flutter.git
Framework • revision 34bc632493 (34 hours ago) • 2024-04-16 18:55:59 -0500
Engine • revision 4d69c0c954
Tools • Dart 3.5.0 (build 3.5.0-66.0.dev) • DevTools 2.35.0-dev.8
2024/04/18 17:36:07 [INFO] Phase: Generating Dart bindings for Rust
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Deprecated. Use `dart run` instead.
Resolving dependencies...
Downloading packages...
Got dependencies.
Resolving dependencies...
Downloading packages...
Got dependencies.
Running in Directory: 'E:\workspace\code\rustdesk\flutter'
[SEVERE] : Couldn't find dynamic library in default locations.
[SEVERE] : Please supply one or more path/to/llvm in ffigen's config under the key 'llvm-path'.
[SEVERE] : Couldn't find bin\libclang.dll in specified locations.
2024/04/18 17:36:13 [WARN] command="powershell" "-noprofile" "-command" "& \"flutter\" \"pub\" \"run\" \"ffigen\" \"--config\" \"C:\\\\Users\\\\35328\\\\AppData\\\\Local\\\\Temp\\\\.tmpwwtdxi\"" stdout= stderr=
2024/04/18 17:36:13 [ERROR] Fatal error encountered. Rerun with RUST_BACKTRACE=1 or RUST_BACKTRACE=full for more details.

### How to Reproduce

Run the command ,flutter_rust_bridge_codegen --llvm-path D:\\Program Files\\LLVM --rust-input ./src/flutter_ffi.rs --dart-output ./flutter/lib/generated_bridge.dart

### Expected Behavior

I need the generated dart file name "generated_bridge.dart" in the flutter project

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

rustc 1.77.2 (25ef9e3d8 2024-04-09)

### Screenshots

E:\workspace\code\rustdesk>flutter_rust_bridge_codegen --llvm-path D:\\Program Files\\LLVM --rust-input ./src/flutter_ffi.rs --dart-output ./flutter/lib/generated_bridge.dart
2024/04/18 17:36:02 [WARN] Skipping unresolvable module inline (tried \\?\E:\workspace\code\rustdesk\src\inline.rs, \\?\E:\workspace\code\rustdesk\src\inline\mod.rs, \\?\E:\workspace\code\rustdesk\src\ui\inline.rs, \\?\E:\workspace\code\rustdesk\src\ui\inline\mod.rs, )
2024/04/18 17:36:02 [WARN] Skipping unresolvable module version (tried \\?\E:\workspace\code\rustdesk\src\version.rs, \\?\E:\workspace\code\rustdesk\src\version\mod.rs, \\?\E:\workspace\code\rustdesk\src\lib\version.rs, \\?\E:\workspace\code\rustdesk\src\lib\version\mod.rs, )
2024/04/18 17:36:02 [WARN] Skipping unresolvable module io (tried \\?\E:\workspace\code\rustdesk\src\io.rs, \\?\E:\workspace\code\rustdesk\src\io\mod.rs, \\?\E:\workspace\code\rustdesk\src\bridge_generated\io.rs, \\?\E:\workspace\code\rustdesk\src\bridge_generated\io\mod.rs, )
2024/04/18 17:36:02 [INFO] Phase: Validate config(s)
2024/04/18 17:36:02 [INFO] Picked config: Opts { rust_input_path: "E:\\workspace\\code\\rustdesk\\./src/flutter_ffi.rs", dart_output_path: "E:\\workspace\\code\\rustdesk\\./flutter/lib/generated_bridge.dart", dart_decl_output_path: None, c_output_path: ["C:\\Users\\35328\\AppData\\Local\\Temp\\.tmpem7YVD.h"], rust_crate_dir: "E:\\workspace\\code\\rustdesk", rust_output_path: "E:\\workspace\\code\\rustdesk\\./src\\bridge_generated.rs", class_name: "Rustdesk", dart_format_line_length: 80, dart_enums_style: false, skip_add_mod_to_lib: false, llvm_path: ["D:\\\\Program", "Files\\\\LLVM"], llvm_compiler_opts: "", manifest_path: "E:\\workspace\\code\\rustdesk\\Cargo.toml", dart_root: Some("E:\\workspace\\code\\rustdesk\\./flutter"), build_runner: true, block_index: BlockIndex(0), skip_deps_check: false, wasm_enabled: false, inline_rust: false, bridge_in_method: true, extra_headers: "", dart3: true, keep_going: false }
2024/04/18 17:36:02 [INFO] Phase: Parse source code to AST, then to IR
2024/04/18 17:36:04 [WARN] Skipping unresolvable module inline (tried \\?\E:\workspace\code\rustdesk\src\inline.rs, \\?\E:\workspace\code\rustdesk\src\inline\mod.rs, \\?\E:\workspace\code\rustdesk\src\ui\inline.rs, \\?\E:\workspace\code\rustdesk\src\ui\inline\mod.rs, )
2024/04/18 17:36:04 [WARN] Skipping unresolvable module version (tried \\?\E:\workspace\code\rustdesk\src\version.rs, \\?\E:\workspace\code\rustdesk\src\version\mod.rs, \\?\E:\workspace\code\rustdesk\src\lib\version.rs, \\?\E:\workspace\code\rustdesk\src\lib\version\mod.rs, )
2024/04/18 17:36:04 [WARN] Skipping unresolvable module io (tried \\?\E:\workspace\code\rustdesk\src\io.rs, \\?\E:\workspace\code\rustdesk\src\io\mod.rs, \\?\E:\workspace\code\rustdesk\src\bridge_generated\io.rs, \\?\E:\workspace\code\rustdesk\src\bridge_generated\io\mod.rs, )
2024/04/18 17:36:04 [INFO] Phase: Transform IR
2024/04/18 17:36:04 [INFO] Phase: Generate Rust code
2024/04/18 17:36:04 [INFO] Phase: Generate Dart code
Flutter 3.22.0-12.0.pre.30 • channel master • https://github.com/flutter/flutter.git
Framework • revision 34bc632493 (34 hours ago) • 2024-04-16 18:55:59 -0500
Engine • revision 4d69c0c954
Tools • Dart 3.5.0 (build 3.5.0-66.0.dev) • DevTools 2.35.0-dev.8
2024/04/18 17:36:07 [INFO] Phase: Generating Dart bindings for Rust
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Deprecated. Use `dart run` instead.
Resolving dependencies...
Downloading packages...
Got dependencies.
Resolving dependencies...
Downloading packages...
Got dependencies.
Running in Directory: 'E:\workspace\code\rustdesk\flutter'
[SEVERE] : Couldn't find dynamic library in default locations.
[SEVERE] : Please supply one or more path/to/llvm in ffigen's config under the key 'llvm-path'.
[SEVERE] : Couldn't find bin\libclang.dll in specified locations.
2024/04/18 17:36:13 [WARN] command="powershell" "-noprofile" "-command" "& \"flutter\" \"pub\" \"run\" \"ffigen\" \"--config\" \"C:\\\\Users\\\\35328\\\\AppData\\\\Local\\\\Temp\\\\.tmpwwtdxi\"" stdout= stderr=
2024/04/18 17:36:13 [ERROR] Fatal error encountered. Rerun with RUST_BACKTRACE=1 or RUST_BACKTRACE=full for more details.

### Additional Context

I need the generated dart file name "generated_bridge.dart" in the flutter project

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
We do not teach.
