### ISSUE TITLE
Missing Lib in the AppImage

### ISSUE THREAD

**Issue by Tanerx** [rustdesk/rustdesk#7756]
### Bug Description

I'm using X not wayland and this lib is missing in the AppImage.

```
./rustdesk-1.2.3-2-x86_64.AppImage 
/tmp/.mount_rustdeMgEhZi/usr/lib/rustdesk/rustdesk: error while loading shared libraries: libwayland-client.so.0: cannot open shared object file: No such file or directory
```

### How to Reproduce

Just run it in non-wayland system

### Expected Behavior

Lib should be included to AppImage or new AppImage for non-wayland systems

### Operating system(s) on local side and remote side

gentoo latest

### RustDesk Version(s) on local side and remote side

rustdesk-1.2.3-2-x86_64.AppImage

### Screenshots

No SS is need for this.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/115fb05c859c8b172a42acac7ab43d214426459a
