### ISSUE TITLE
On click will input two same characters when using ipad app control win10

### ISSUE THREAD

**Issue by ynnie** [rustdesk/rustdesk#776]
**Describe the bug you encountered:**
Using iPad app connect to a win10 desktop. The connection can be established and the desktop showed normally. But the keyboard was not work normally, click one key will input two sam characters.

**What did you expect to happen instead?**
Click one key will only input one character.
---

**How did you install `RustDesk`?**

Win10: installer from the official website
Ipad: from app store

---

**RustDesk version and environment**
1.1.9

**Comment by rustdesk** [comment]
Physical keyboard？

**Comment by ynnie** [comment]
> 

yes
