### ISSUE TITLE
Can't connedt via X11 - KDE Neon fresh install (KDE 6)

### ISSUE THREAD

**Issue by gusarg81** [rustdesk/rustdesk#7760]
### Bug Description

When setting X11 on KDE Neon, I can't connect (it does only allow me to connect on SDDM screen, but when desktops gets loaded, I loose connection.

This was working before, I don´t know if somethings has changed in KDE Neon (new installations, old installations works OK).

Logs:

> Apr 18 09:06:11 minipc-feria rustdesk[11594]: Authorization required, but no authorization protocol specified
> Apr 18 09:06:11 minipc-feria rustdesk[11594]: Authorization required, but no authorization protocol specified
> Apr 18 09:06:11 minipc-feria xdg-desktop-portal-kde[9391]: xdp-kde-settings: Namespace  "org.gnome.desktop.interface"  is not supported
> Apr 18 09:06:11 minipc-feria xdg-desktop-portal-kde[9391]: message repeated 2 times: [ xdp-kde-settings: Namespace  "org.gnome.desktop.interface"  is not supported]
> Apr 18 09:06:11 minipc-feria xdg-desktop-portal-kde[9391]: xdp-kde-settings: Namespace  "org.gnome.desktop.a11y.interface"  is not supported
> Apr 18 09:06:11 minipc-feria xdg-desktop-portal-kde[9391]: xdp-kde-settings: Namespace  "org.gnome.desktop.interface"  is not supported
> Apr 18 09:06:11 minipc-feria baloo_file_extractor[20417]: kf.idletime: Could not find any system poller plugin
> Apr 18 09:06:11 minipc-feria baloo_file_extractor[20417]: qt.core.qobject.connect: QObject::connect(KAbstractIdleTimePoller, KIdleTime): invalid nullptr parameter
> Apr 18 09:06:11 minipc-feria baloo_file_extractor[20417]: qt.core.qobject.connect: QObject::connect(KAbstractIdleTimePoller, KIdleTime): invalid nullptr parameter
> Apr 18 09:06:12 minipc-feria rustdesk[20373]: flutter: launch args: [--cm]
> Apr 18 09:06:12 minipc-feria rustdesk[20373]: flutter: --cm started
> Apr 18 09:06:12 minipc-feria rustdesk[20373]: flutter: initializing FFI cm
> Apr 18 09:06:12 minipc-feria rustdesk[20373]: flutter: _appType:cm,info1-id:d61d7791c6cc4fac875cc3288f387b32,info2-name:KDE neon,dir:/home/feria/Documentos
> Apr 18 09:06:12 minipc-feria rustdesk[20373]: flutter: _globalFFI init
> Apr 18 09:06:12 minipc-feria rustdesk[20373]: flutter: _globalFFI init end
> Apr 18 09:06:12 minipc-feria rustdesk[20373]: flutter: registerEventHandler theme theme
> Apr 18 09:06:12 minipc-feria rustdesk[20373]: flutter: registerEventHandler language language
> Apr 18 09:06:12 minipc-feria rustdesk[20373]: flutter: registerEventHandler native_ui native_ui
> Apr 18 09:06:12 minipc-feria rustdesk[20373]: flutter: Bring window 'null' on top
> Apr 18 09:06:12 minipc-feria rustdesk[20373]: flutter: model  closed
> Apr 18 09:06:12 minipc-feria rustdesk[20373]: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed
> Apr 18 09:06:12 minipc-feria rustdesk[20373]: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

### How to Reproduce

Change to X11 and once Desktop gets loaded, you will be disconnected (on a new KDE neon fresh install).

### Expected Behavior

Should allow me to connect to the desktop.

### Operating system(s) on local side and remote side

KDE Neon (KDE 6.x, which is based on Ubuntu 22.04)

### RustDesk Version(s) on local side and remote side

Both latest: 1.2.3-2

### Screenshots

![Captura de pantalla_20240418_091159](https://github.com/rustdesk/rustdesk/assets/6312430/c5750b7a-446e-4713-95ac-f804b1c88494)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/5095#discussioncomment-8812999
