### ISSUE TITLE
ID server does not reconnect automatically

### ISSUE THREAD

**Issue by MemeCats** [rustdesk/rustdesk#7781]
### Bug Description

The IP used by my ID server changes automatically every once in a while, I use DDNS service to change the domain resolution IP automatically, but rustdesk on the machine that needs to be controlled won't reacquire the domain IP, resulting in no connectivity

### How to Reproduce

Changing the IP of the ID server

### Expected Behavior

After the domain name modifies the IP record, the controlled side should get the latest IP automatically

### Operating system(s) on local side and remote side

Windows10  -> Windows10

### RustDesk Version(s) on local side and remote side

1.2.4  -> 1.2.4

### Screenshots

![Uploading Snipaste_2024-04-20_05-26-57.png…]()

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/7045#discussioncomment-8627590
