### ISSUE TITLE
Rustdesk install in Android 10  doesn't support audio capture.

### ISSUE THREAD

**Issue by ZGLinus** [rustdesk/rustdesk#7790]
### Bug Description

I install Rustdesk in MIUI v12 based on Android 10 (SDK 29). In "Share screen" tab, Rustdesk tell me to upgrade to Android 10 or higher because it tell me that the android version does not support audio capture. My phone is already in Android 10, but i do not want to upgrade to a11 because of the limited access of Android/data.

### How to Reproduce

1. Install Rustdesk in MIUI v12 based on Android 10
2. open "Share screen" tab

### Expected Behavior

It will allow Rustdesk to capture the audio

### Operating system(s) on local side and remote side

Android -> Android

### RustDesk Version(s) on local side and remote side

1.2.3 (build data: 2023-10-13 10:53) -> 1.2.4 (build date: 2024-4-21 07:08)

### Screenshots

Rustdesk screenshot
![Screenshot_2024-04-22-04-10-16-991_com carriez flutter_hbb](https://github.com/rustdesk/rustdesk/assets/69845097/1661c529-a842-4073-9453-11081a150b73)
System info
![Screenshot_2024-04-22-04-08-59-750_com finalwire aida64](https://github.com/rustdesk/rustdesk/assets/69845097/80777417-ebab-4f25-88d7-c25677e4193e)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893
