### ISSUE TITLE
Bug Report - Taskbar Icon Causes Multiple Window Instances

### ISSUE THREAD

**Issue by GxCoderZ** [rustdesk/rustdesk#7798]
### Bug Description

Dear RustDesk Team,

I hope this message finds you well. I am writing to report a recurring issue I've encountered with the RustDesk application. When clicking the taskbar icon, the application repeatedly opens multiple instances of the main window instead of bringing the already open window to the foreground.

### How to Reproduce

Bug Description:

Severity: Medium
Frequency: Always
Steps to Reproduce:
Open RustDesk.
Minimize the RustDesk window to the taskbar.
Click on the RustDesk icon in the taskbar.
Observe that a new window opens each time the icon is clicked instead of just one window.

Actual Behavior:
Each click on the taskbar icon results in a new RustDesk window, leading to multiple instances.

### Expected Behavior

Clicking the taskbar icon should bring the already opened RustDesk window to the foreground, not open new instances.

### Operating system(s) on local side and remote side

windows11

### RustDesk Version(s) on local side and remote side

1.2.3-2

### Screenshots

![Snipaste_2024-04-22_23-13-24](https://github.com/rustdesk/rustdesk/assets/112332259/48b84419-ea62-46f5-afec-d9d575666f29)

**Comment by rustdesk** [comment]
fixed in master
