### ISSUE TITLE
android rustdesk client Unable to wake the screen.

### ISSUE THREAD

**Issue by Andieqqq** [rustdesk/rustdesk#7816]
### Bug Description

The operating system is MIUI 12+,I confirm that the permission to open the screen is turned on.

### How to Reproduce

Use any Android phone to connect the client that can't wake up the screen to reproduce.

### Expected Behavior

Found connected, waiting for the transmission of the picture.

### Operating system(s) on local side and remote side

Android 11 ->&&MIUI12 ->

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

![Screenshot_2024-04-24-15-07-48-140_com android settings](https://github.com/rustdesk/rustdesk/assets/60780557/b9999d26-9126-4887-b2c1-76b0cc123043)

### Additional Context

I'm not sure if there are any other interference factors. My equipment has Red k30     k40    note  11 pro

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/6515 in night build, https://github.com/rustdesk/rustdesk/releases/tag/nightly

**Comment by liuzhenggang** [comment]
I encountered the same problem

**Comment by zacharee** [comment]
This doesn't seem to be fixed. Using the latest nightly, when I try to connect to an Android device with the screen of, I still get stuck at "Connected, waiting for image...". I have to physically turn on the screen for RustDesk to work.
