### ISSUE TITLE
Rockchip-rk3588 ubuntu jammy crush on first connection as server

### ISSUE THREAD

**Issue by yixinin** [rustdesk/rustdesk#7819]
### Bug Description

OS Info: Linux orangepi5plus 6.1.43-rockchip-rk3588 #1.0.8 SMP Sat Feb  3 00:04:38 CST 2024 aarch64 aarch64 aarch64 GNU/Linux
RustDesk Version: 1.2.3

Error:
<img width="1860" alt="Screenshot 2024-04-25 at 09 36 33" src="https://github.com/rustdesk/rustdesk/assets/17738162/5628bff1-4368-4404-ab3d-98ba585120c4">

Reconnect will be successfully.

### How to Reproduce

every connection

### Expected Behavior

connect and no crush

### Operating system(s) on local side and remote side

windows10 -> ubuntu22.04

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

<img width="1860" alt="Screenshot 2024-04-25 at 09 36 33" src="https://github.com/rustdesk/rustdesk/assets/17738162/5628bff1-4368-4404-ab3d-98ba585120c4">

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
