### ISSUE TITLE
Linux: Systray flickers while sharing screen

### ISSUE THREAD

**Issue by J4nsen** [rustdesk/rustdesk#7829]
### Bug Description

Hi, when i share my screen my systray bar starts to flicker. A icon seems to appear and immediately disappear again. I've attached a video of the bug. 

```
Operating System: Arch Linux 
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
Qt Version: 6.7.0
Kernel Version: 6.8.7-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 PRO 5850U with Radeon Graphics
Memory: 27,2 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: LENOVO
Product Name: 21A0000DGE
System Version: ThinkPad P14s Gen 2a
```

### How to Reproduce

Just start a screenshare with KDE Plasma on Linux with Wayland

### Expected Behavior

No systray flicker when sharing my screen

### Operating system(s) on local side and remote side

Arch Linux -> Mac/Linux

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

https://github.com/rustdesk/rustdesk/assets/3029093/c6ba9c54-1894-4b49-9e56-46db954a2fa0

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
