### ISSUE TITLE
The ViewStyle option "view_style = 'shrink'" is not taken into account in the RustDesk2.toml file

### ISSUE THREAD

**Issue by Vogelbusch** [rustdesk/rustdesk#783]
The ViewStyle option "view_style = 'shrink'" is not taken into account in the RustDesk2.toml file.
![grafik](https://user-images.githubusercontent.com/107399413/173820114-7d8efb5b-33db-45a6-9079-705503100f4e.png)

Our goal is to enable the ViewStyle option to all our clients as a default view style

**Comment by rustdesk** [comment]
I understand your intention. But for now, it is a peer option, there is no such global default option.

**Comment by rustdesk** [comment]
default options added
