### ISSUE TITLE
if service runnung, then RustDesk client drop each time I run it, end_if

### ISSUE THREAD

**Issue by VitaliyAT** [rustdesk/rustdesk#7835]
### Bug Description

If service is not running - I can run program and all is OK...
But it write me in bottom that service is not running... so, I run it, imidiate main window (and process in running process) closed. When I try run it again - it run but I just see how main window opend and closed immediately. Can't change any settings. My last changes in settings was change Net settings to my self-hosting server "DNS name" that placed under NAT and revers proxy in my net. I have static IP and idea was up RD server on Synology and open it trhoough reverser-proxy to outside. In local it worked OK - no luck was with outside points (clients). When it was just IP - it didn't drop. When I change it to DNS name - as I said higher.

### How to Reproduce

Don't really know. In my situation I just run it and getting bug.

### Expected Behavior

I expect that it run stable as minimum.

### Operating system(s) on local side and remote side

Win10 19044.4291

### RustDesk Version(s) on local side and remote side

1.2.3-2

### Screenshots

Can't or it will be my clear desctop.

**Comment by rustdesk** [comment]
#763
