### ISSUE TITLE
File transfer screen tweaks - favourite/memory + overwrite dialog

### ISSUE THREAD

**Issue by trentnetau** [rustdesk/rustdesk#784]
It would be most wonderful if the file transfer was to allow for memory of the last accessed folder or even storage of commonly accessed folders as favourites on local/remote computer in the transfer window so you can bring them back up.

I use the remote access utilities (like RustDesk - currently testing and loving thus far) to complete audio transfers to manage a remote audio playout system and I commonly access a folder every night to move files across and currently need to find the folder which is on a secondary drive.

Additionally I have noted that it doesn't warn me about overwriting files on the remote computer like other applications.

**Comment by Kingtous** [comment]
We have implemented `overwrite dialog` in our new version `1.1.10` and will release it soon. Now we'll take a look into this `favourite` screen tweaks.
