### ISSUE TITLE
Excessive kworker processes that bog down system (Debian on Raspberry Pi, all OS versions)

### ISSUE THREAD

**Issue by MStylesMS** [rustdesk/rustdesk#7842]
### Bug Description

After installing RustDesk there appear to be a few hundred kworker processes created per minute, which eventually leads to signifigant performance issues.  After an hour or more, the machine may become sluggish and remain that way until rebooted, when it starts again.

### How to Reproduce

Installing the following libraries works fine, and appears to be required for RustDesk to run:

`sudo apt-get install libgtk-3-0 libwebkit2gtk-4.0-37 libavahi-compat-libdnssd-dev libxdo3 gstreamer1.0-pipewire` 

Checking the processes things are still fine.  Then install either the aarch64 or arm7-sciter DEB versions (depending upon 64 or 32 bit OS), which required forcing the installation of dependencies:

`sudo dpkg -i rustdesk_[version].deb`
`sudo apt-get install -f`

At that point you can launch RustDesk and it appears to work fine.  However, if you use `ps -aux | grep ps`, wait 10 seconds, then do `ps` again the PID is likely around a hundred higher.  Before this it was only 2 higher.   A closer look showing the kworker processes can be seen by using the following command twice, about ten seconds apart:

`ps -eo pid,stime,cmd --sort=start_time | tail -n 10`

Which should show the PID numbers increasing at a fast rate.  Next, remove RustDesk with:

`sudo apt-get remove rustdesk` 

Check the processes with `ps` again about 10 seconds apart and it should revert to the PID only being 2 higher.  

### Expected Behavior

Excessive kworker processes should not be generated.  

### Operating system(s) on local side and remote side

Raspberry Pi OS, Bookworm, Bullseye, and Buster

### RustDesk Version(s) on local side and remote side

1.2.3-2

### Screenshots

<img width="591" alt="RustDesk-kworker" src="https://github.com/rustdesk/rustdesk/assets/20646124/5b0506a5-e150-4e97-8448-2b36dad0c1dd">

### Additional Context

Currently unsure if this applies to other Debian installations or not.

**Comment by MStylesMS** [comment]
This is also happening on a Mint Linux installation on an x86 computer.  So it appears more widespread that just Raspberry Pi's.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by rustdesk** [comment]
Apologize, we do not have PI, can help you.

**Comment by rustdesk** [comment]
Hopefully some contributors using PI can figure it out.
