### ISSUE TITLE
The latest x86_64 MacOS version is no longer available. . .

### ISSUE THREAD

**Issue by zhangbo8418** [rustdesk/rustdesk#7854]
### Bug Description

The latest x86_64 MacOS version is no longer available. . .

### How to Reproduce

The latest x86_64 MacOS version is no longer available. . .

### Expected Behavior

Support MacOS x86_64

### Operating system(s) on local side and remote side

MacOS

### RustDesk Version(s) on local side and remote side

1.2.4

### Screenshots

<img width="1201" alt="QQ20240428-111814@2x" src="https://github.com/rustdesk/rustdesk/assets/46797568/d9af745e-e317-4c93-abed-74f41fd6cd5f">

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/e084ff4f7b4ecd350584b360c2f64940885fd0f1
