### ISSUE TITLE
macos build android fail

### ISSUE THREAD

**Issue by tanzhh-bingosoft** [rustdesk/rustdesk#7859]
### Bug Description

error: failed to run custom build command for `scrap v0.5.0 (/Users/tanzhihui/rustdesk/libs/scrap)`

Caused by:
  process didn't exit successfully: `/Users/tanzhihui/rustdesk/target/release/build/scrap-20fb58f4526295ef/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=NO_PKG_CONFIG_libyuv
  cargo:info=arm64-android
  cargo:rustc-link-lib=static=yuv
  cargo:rustc-link-search=/Users/tanzhihui/Develop/vcpkg/installed/arm64-android/lib
  cargo:include=/Users/tanzhihui/Develop/vcpkg/installed/arm64-android/include
  cargo:rerun-if-env-changed=NO_PKG_CONFIG_libvpx
  cargo:info=arm64-android
  cargo:rustc-link-lib=static=vpx
  cargo:rustc-link-search=/Users/tanzhihui/Develop/vcpkg/installed/arm64-android/lib
  cargo:include=/Users/tanzhihui/Develop/vcpkg/installed/arm64-android/include
  rerun-if-changed=/Users/tanzhihui/rustdesk/libs/scrap/src/bindings/vpx_ffi.h
  rerun-if-changed=/Users/tanzhihui/Develop/vcpkg/installed/arm64-android/include

  --- stderr
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include/inttypes.h:21:15: fatal error: 'inttypes.h' file not found
  thread 'main' panicked at libs/scrap/build.rs:169:18:
  called `Result::unwrap()` on an `Err` value: ClangDiagnostic("/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include/inttypes.h:21:15: fatal error: 'inttypes.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
note: If the build failed due to a missing target, you can run this command:
note: 
note:     rustup target install aarch64-linux-android

### How to Reproduce

The preceding error is reported when the./flutter/ndk_arm64.sh command is executed

### Expected Behavior

Build success.

### Operating system(s) on local side and remote side

macos

### RustDesk Version(s) on local side and remote side

1.2.3-2

### Screenshots

none

**Comment by rustdesk** [comment]
#763
