### ISSUE TITLE
Default server configuration does not work in ubuntu

### ISSUE THREAD

**Issue by sanmigit** [rustdesk/rustdesk#7865]
### Bug Description

Hello, I have a problem with rustdesk when compiling the application, I followed the instructions in this link https://rustdesk.com/docs/en/dev/build/all/  to put the changes in the application itself with the variables RENDEZVOUS_SERVER and RS_PUB_KEY, both windows and android has not given me any problem, but for linux does not set my default server and uses the generic, anyone has any idea what may be the problem?

As you can see in the screenshots below, in windows the configuration does accept it although it does not appear in the configuration options.

### How to Reproduce

The only thing i have done is to follow the steps in this link: https://rustdesk.com/docs/en/dev/build/all/

### Expected Behavior

The workflows should work and not give problems, but when viewing the changes in linux they have not been produced.

### Operating system(s) on local side and remote side

linux - windows 10

### RustDesk Version(s) on local side and remote side

1.2.4

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/36620837/156eb643-d694-40e8-824c-b806663361ce)
![image](https://github.com/rustdesk/rustdesk/assets/36620837/673daa65-48b8-408a-a318-b7cf51062765)
![image](https://github.com/rustdesk/rustdesk/assets/36620837/72c97b34-2f16-434f-af96-73f496b3fa1f)

**Comment by rustdesk** [comment]
#763
