### ISSUE TITLE
Middle mouse button release bug

### ISSUE THREAD

**Issue by liventsev96** [rustdesk/rustdesk#787]
**Describe the bug you encountered:**

Hello! When I move in the program window by pressing the middle mouse button (Archicad or 3dMax), after releasing the button, it still remains pressed.

**What did you expect to happen instead?**

The middle button must be released together on the remote machine.

**How did you install `RustDesk`?**

MacOS (Client) Installed
Windows (Remote client) - fully installed

---

**RustDesk version and environment**

MacOS - 1.1.9
Windows - 1.1.9

**Comment by rustdesk** [comment]
@asur4s

**Comment by rustdesk** [comment]
@fufesou https://github.com/rustdesk/rustdesk/issues/1547

**Comment by rustdesk** [comment]
try out nightly build please.

**Comment by fufesou** [comment]
I've tested with autodesk web viewer.
1.1.9 can reproduce this issue.
The nightly build is fine.
