### ISSUE TITLE
Can't access menu for items in address book in "List" mode

### ISSUE THREAD

**Issue by yaroz** [rustdesk/rustdesk#7874]
### Bug Description

When viewing items in a list view in the address book, there is no way to access the menu, to add tags/rename the item.

### How to Reproduce

While in an address book, switch to List view

### Expected Behavior

There should be the three dots to access the menu for each item

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.2.4

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/20463573/8e234682-5eba-4541-97a1-f3fba232e045)

**Comment by rustdesk** [comment]
the fix has been merged
