### ISSUE TITLE
 i cannot access other drives than c on the computer. 

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#788]
from reddit

> I have noticed a couple of peculiar issues when testing Rustdesk.
> 
> Transferring files. i cannot access other drives than c on the computer. It is Windows 7, and maybe it is a peculiarity with this version of Windows.
> 
> Anyone else notice this.

**Comment by rustdesk** [comment]
There is a workaround, you can input '/' as below.

![image](https://user-images.githubusercontent.com/71636191/174005492-bd41ad8c-9801-4148-bca4-b9348efe86cd.png)

**Comment by rustdesk** [comment]
We may add this to `favorite` in the future release. https://github.com/rustdesk/rustdesk/issues/784#issuecomment-1157176043 @Kingtous

**Comment by liumingju** [comment]
Android端应用也有同样的问题，无法访问C：\以外的驱动器
---------------------------------------------------------
Android applications also have the same issue， unable to access drives other than c:\


![微信图片编辑_20220708213046](https://user-images.githubusercontent.com/10863399/178002166-b94d2143-a646-4bca-b141-967c7e945535.jpg)
。

**Comment by psketi** [comment]
Bump, this issue still exists. Huge problem on mobile since there is no workaround.
Perhaps set `/` as default?

**Comment by rustdesk** [comment]
fixed in master

**Comment by ProxyPlayerHD** [comment]
How is this fixed? The android app still can't access other drives. (From Playstore, v1.1.10-1)

**Comment by dinger1986** [comment]
Use the apk from GitHub

**Comment by ProxyPlayerHD** [comment]
ok that works. thanks!

though it's weird that the playstore version is so outdated then
