### ISSUE TITLE
rustdesk do not start on linuxmint mate x64

### ISSUE THREAD

**Issue by twprh** [rustdesk/rustdesk#7881]
### Bug Description

load librustdesk.so failed
/usr/lib/rustdesk/lib/librustdesk.so: undefined symbol: MFXVideoCORE_GetHandleflutter: launch args: []
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'librustdesk.so': /usr/lib/rustdesk/lib/librustdesk.so: undefined symbol: MFXVideoCORE_GetHandle
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
#2      PlatformFFI.init (package:flutter_hbb/models/native_model.dart:117)
#3      initEnv (package:flutter_hbb/main.dart:104)
#4      runMainApp (package:flutter_hbb/main.dart:117)
#5      main (package:flutter_hbb/main.dart:98)
<asynchronous suspension>

### How to Reproduce

start rustdesk (on linuxmint mate)

### Expected Behavior

start like nightly-version 3 days ago (20240428)

rustdesk
Cannot load libcuda.so.1
Cannot load libcuda.so.1
flutter: launch args: []
flutter: initializing FFI main
flutter: _appType:main,info1-id:1a2f143a26374a19bf06824f4eea0221,info2-name:Linux Mint,dir:/home/user/Dokumente
flutter: _globalFFI init
flutter: _globalFFI init end
flutter: registerEventHandler native_ui native_ui
flutter: pullAb, force: ForcePullAb.listAndCurrent, quiet: false
flutter: registerEventHandler callback_query_onlines favorite peer
flutter: registerEventHandler load_fav_peers favorite peer
flutter: restore lpos: 1254.0/784.0, offset:191.0/42.0
flutter: handled by uni links: false
flutter: [MultiWindowHandler] active window changed: {0}

### Operating system(s) on local side and remote side

Linux  -> Windows

### RustDesk Version(s) on local side and remote side

nightly

### Screenshots

not working:
![grafik](https://github.com/rustdesk/rustdesk/assets/46543715/19107312-cd6c-4a3c-817e-0e99d5cd6f2d)

working:
![grafik](https://github.com/rustdesk/rustdesk/assets/46543715/970ebf13-c6d6-432e-88e2-7cfb8dc8bfc0)

### Additional Context

hopefully it is only a smal bug ;)

**Comment by 21pages** [comment]
Thanks for your feedback, it can be reproduced.

**Comment by SpuDytsk** [comment]
same on Fedora 40

**Comment by twprh** [comment]
thanks for fast fix
