### ISSUE TITLE
Side mouse buttons not being detected

### ISSUE THREAD

**Issue by cpc2** [rustdesk/rustdesk#7889]
### Bug Description

Using the mouse Logitech G603 the mouse side buttons aren't being detected, while in other remote desktop programs like Parsec or Anydesk they are. I tried all three different input methods that Rustdesk offers but the same happened in all of them.

### How to Reproduce

Connect to a remote machine and attempt to use any of the side buttons of a mouse (Logitech G603 but probably happens with other mice).

### Expected Behavior

When pressing the side buttons, the input should be detected. 

### Operating system(s) on local side and remote side

Windows 10 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.3-2 -> 1.2.3-2

### Screenshots

While pressing button 4 (one of the side buttons) if detected it should light up on X-mouse button control.
Rustdesk:
![image](https://github.com/rustdesk/rustdesk/assets/48025245/aa3d648e-879d-4acb-8186-4e5c7e135ed4)
Parsec:
![image](https://github.com/rustdesk/rustdesk/assets/48025245/bf8aadfb-425a-4144-8269-4272a4fe2684)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by fbd-ss** [comment]
Using linux -> linux it does not work on 1.4.6 either.  Logitech M720 if that helps, not sure why it would.
