### ISSUE TITLE
cannot run in my win7

### ISSUE THREAD

**Issue by txunda** [rustdesk/rustdesk#789]
![image](https://user-images.githubusercontent.com/76721805/174013874-2ff62c6b-d32d-489b-ada9-294505a8361c.png)
cannot run in win7，win10 is ok

**Comment by rustdesk** [comment]
It is ok on most of win7. To make it work on all win7, need more help from contributors.

**Comment by grummbeer** [comment]
related to #2833

**Comment by rustdesk** [comment]
wont fix win 7 anymore
