### ISSUE TITLE
caps lock key cannot be enabled

### ISSUE THREAD

**Issue by cctv130** [rustdesk/rustdesk#7904]
### Bug Description

It doesn't matter how you switch the case

### How to Reproduce

It doesn't matter how you switch the case

### Expected Behavior

enabled capslock

### Operating system(s) on local side and remote side

android -> windows 11

### RustDesk Version(s) on local side and remote side

1.2.3 ->1.2.3-2

### Screenshots

aaaaaaaaaaaa

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367
