### ISSUE TITLE
Cannot connect to any remote PC's

### ISSUE THREAD

**Issue by Davidi74** [rustdesk/rustdesk#7935]
### Bug Description

Getting the error: The connection is not allowed. To further prevent scamming, we only allow connections between users in the same city.

### How to Reproduce

Connect to ANY remote desktop, Even ones in "the same city"

### Expected Behavior

Should be able to connect

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3-2

### Screenshots

![Screenshot 2024-05-07 135611](https://github.com/rustdesk/rustdesk/assets/64612639/a0769e4e-c4ae-4bc1-afb0-3f1106717e9e)

### Additional Context

I hope this can be fixed. A great app that I use almost every day is now useless if this isn't a bug.

**Comment by rustdesk** [comment]
https://twitter.com/rustdesk/status/1787689958276472982
https://github.com/rustdesk/rustdesk/discussions/7934
