### ISSUE TITLE
Automatic recording is not effective.

### ISSUE THREAD

**Issue by AemonCao** [rustdesk/rustdesk#7948]
### Bug Description

After enabling automatically record incoming sessions, it didn't take effect.

Neither controlling other devices nor being controlled allows video recording.

The target folder set does not contain any video files, either during control or after control ends.

### How to Reproduce

After making the following settings and being accessed by other devices, there was no effect.

![image](https://github.com/rustdesk/rustdesk/assets/19542659/3c1063af-0041-4549-a6fc-71f78fc25380)

### Expected Behavior

It is possible to generate recordings while being controlled or controlling other devices.

### Operating system(s) on local side and remote side

windows 11 -> windows 10

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/19542659/a8fab1ea-9bf8-4861-9435-d4a20ac72f3c)

![image](https://github.com/rustdesk/rustdesk/assets/19542659/3c1063af-0041-4549-a6fc-71f78fc25380)

### Additional Context

A self-hosted ID server has been set up, and the RustDesk client is installed using Scoop.

**Comment by rustdesk** [comment]
nightly build please on both sides

**Comment by 21pages** [comment]
Thanks, It can reproduced after installation.

**Comment by almedina-tech** [comment]
will you please elaborate what Nightly build meanns?

**Comment by AemonCao** [comment]
> will you please elaborate what Nightly build meanns?

https://github.com/rustdesk/rustdesk/releases/tag/nightly
