### ISSUE TITLE
如何让远程控制时，远端黑屏，或者注销模式？最好可以断开链接，远端自动锁定？

### ISSUE THREAD

**Issue by heshen** [rustdesk/rustdesk#797]
如何让远程控制时，远端黑屏，或者注销模式？最好可以断开链接，远端自动锁定？
How to keep the remote end of the mac on a black screen when remotely controlled, or logout mode, so as to ensure the privacy and security of the user? Is it better to break the link and lock the remote end automatically?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/65

**Comment by rustdesk** [comment]
Please turn on "lock after session close" from the menu of connection window.
