### ISSUE TITLE
Rust Desk APPCRASH

### ISSUE THREAD

**Issue by aphonsoeliasf** [rustdesk/rustdesk#7998]
### Bug Description

When i start my system, the above error application message is showed
![RustDesk error msg](https://github.com/rustdesk/rustdesk/assets/29491462/ee2540e3-0ada-4fb3-b0bf-e89c4312626c)

### How to Reproduce

The error message appears when i boot the system, when i open the software and when i go to shutdown/reboot the system. When i checked the error message in windows, i get the above message.
![RustDesk Error](https://github.com/rustdesk/rustdesk/assets/29491462/9a335a5d-38b8-4d46-9242-1d3065b37d18)

### Expected Behavior

The software to work without that message, in previous version i don't have that problem.

### Operating system(s) on local side and remote side

Windows 10 Pro 22H2

### RustDesk Version(s) on local side and remote side

1.2.3.2

**Comment by rustdesk** [comment]
tracked with https://github.com/rustdesk/rustdesk/issues/7412
