### ISSUE TITLE
Error occurred during installation on ubuntu system

### ISSUE THREAD

**Issue by Ekko-G0d** [rustdesk/rustdesk#7999]
### Bug Description

error: failed to run custom build command for `pam-sys v1.0.0-alpha4`

Caused by:
  process didn't exit successfully: `/home/ekko/myappdata/rustdesk/rustdesk/rustdesk/target/debug/build/pam-sys-8f2e6b1acacb4aab/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=pam
  cargo:rustc-link-lib=pam_misc
  cargo:rerun-if-changed=wrapper.h

  --- stderr
  wrapper.h:1:10: fatal error: 'security/pam_appl.h' file not found
  wrapper.h:1:10: fatal error: 'security/pam_appl.h' file not found, err: true
  thread 'main' panicked at /home/ekko/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pam-sys-1.0.0-alpha4/build.rs:69:10:
  Unable to generate bindings: ()
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

### How to Reproduce

When executing the build command：
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source $HOME/.cargo/env
git clone https://github.com/rustdesk/rustdesk
cd rustdesk
mkdir -p target/debug
wget https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin.lnx/x64/libsciter-gtk.so
mv libsciter-gtk.so target/debug
VCPKG_ROOT=$HOME/vcpkg cargo run

### Expected Behavior

successfully installed rustdesk

### Operating system(s) on local side and remote side

ubuntu

### RustDesk Version(s) on local side and remote side

1.2.3-2

### Screenshots

![微信截图_20240510014743](https://github.com/rustdesk/rustdesk/assets/84793241/38f60ee0-615e-4a97-9175-22db6f45945a)

**Comment by rustdesk** [comment]
#763

**Comment by luxingshun** [comment]
I meet the same issue on rustdesk version 1.3.5,
issue:
error: failed to run custom build command for `pam-sys v1.0.0-alpha4 (https://github.com/rustdesk-org/pam-sys?branch=fix%2Fv1.0.0-alpha4_gnuc_va_list#3337c9bb)`

os:
ubuntu18.04 

how fixed this issue???

**Comment by apzc2529** [comment]
Fix it by install libpam0g-dev package:
sudo apt install libpam0g-dev
