### ISSUE TITLE
不停弹黑框是啥问题？

### ISSUE THREAD

**Issue by zhangbo8418** [rustdesk/rustdesk#8]
更新到最新版后就不停弹黑框，关掉RustDesk的服务就好了。。。
![Screenshot_20201226_223051_juejin android todesk](https://user-images.githubusercontent.com/46797568/103153269-07961280-4755-11eb-98ab-7f428e7895ed.jpg)
![QQ截图20201227121532](https://user-images.githubusercontent.com/46797568/103163793-b3b32880-483d-11eb-8b5b-145d1e609426.png)

**Comment by open-trade** [comment]
win7?

**Comment by open-trade** [comment]
win7和win10上目前都还没有重现这个问题

**Comment by open-trade** [comment]
也许是装了某某杀毒软件，产生冲突了吧

**Comment by zhangbo8418** [comment]
> 也许是装了某某杀毒软件，产生冲突了吧

Win7是装的卡巴斯基，Win2019啥也没装，系统自带。。。我家里没有Win10的设备，没法测试，Win10上的情况。。。

**Comment by open-trade** [comment]
反复弹窗的是2019?我测试win7没问题。新版本就是加了系统托盘，这个系统托盘会在系统登录过程中反复尝试几次，因为只有在系统完全登陆后运行托盘才会成功，也许是这个导致了黒窗2020年12月27日 17:34，裙下孤魂 <notifications@github.com>写道：



也许是装了某某杀毒软件，产生冲突了吧



Win7是装的卡巴斯基，Win2019啥也没装，系统自带。。。我家里没有Win10的设备，没法测试，Win10上的情况。。。

**Comment by zhangbo8418** [comment]
> 反复弹窗的是2019?我测试win7没问题。新版本就是加了系统托盘，这个系统托盘会在系统登录过程中反复尝试几次，因为只有在系统完全登陆后运行托盘才会成功，也许是这个导致了黒窗2020年12月27日 17:34，裙下孤魂 <notifications@github.com>写道： 也许是装了某某杀毒软件，产生冲突了吧 Win7是装的卡巴斯基，Win2019啥也没装，系统自带。。。我家里没有Win10的设备，没法测试，Win10上的情况。。。 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

都一样。。。

**Comment by mingpcer** [comment]
一样的情况，RustDesk V1.1.1，Win10 2004版，没装杀软，系统自带安全中心。

**Comment by rustdesk** [comment]
好的 我更新win10看看2021年2月21日 14:06，mingpcer <notifications@github.com>写道：

一样的情况，RustDesk V1.1.1，Win10 2004版，没装杀软，系统自带安全中心。

**Comment by rustdesk** [comment]
不好意思 找不到就win10测试2021年2月22日 15:22，RustDesk Help <info@rustdesk.com>写道：好的 我更新win10看看2021年2月21日 14:06，mingpcer <notifications@github.com>写道：

一样的情况，RustDesk V1.1.1，Win10 2004版，没装杀软，系统自带安全中心。

**Comment by DyingLight12** [comment]
一样  我又换回1.1.0

**Comment by qiershow2** [comment]
我也有這個問題，也是更新了Windows10 20H3質量更新才出現的，之前正常，用的版本是1.1.1，不停彈出黑框一閃一閃，只能在任務管理器結束rustdesk的自動啟動服務才消失黑框，但遠程不能連結，試過兼容模式和管理員模式都無法避開這個問題

**Comment by rustdesk** [comment]
> 我也有這個問題，也是更新了Windows10 20H3質量更新才出現的，之前正常，用的版本是1.1.1，不停彈出黑框一閃一閃，只能在任務管理器結束rustdesk的自動啟動服務才消失黑框，但遠程不能連結，試過兼容模式和管理員模式都無法避開這個問題

能否录个小视频或者gif给我看看，我怎么也复现不了问题，很想把这个问题解决掉。发到我的邮箱info@rustdesk.com

**Comment by rustdesk** [comment]
> > 我也有這個問題，也是更新了Windows10 20H3質量更新才出現的，之前正常，用的版本是1.1.1，不停彈出黑框一閃一閃，只能在任務管理器結束rustdesk的自動啟動服務才消失黑框，但遠程不能連結，試過兼容模式和管理員模式都無法避開這個問題
> 
> 能否录个小视频或者gif给我看看，我怎么也复现不了问题，很想把这个问题解决掉。发到我的邮箱[info@rustdesk.com](mailto:info@rustdesk.com)

算了，不用了

**Comment by rustdesk** [comment]
劳烦试一下 https://github.com/rustdesk/rustdesk/releases/download/1.1.2/rustdesk-1.1.2.exe

**Comment by qiershow2** [comment]
😉還是失敗了，安裝模式無法使用，即使是請求了管理員權限的cmd批處理，能創建桌面圖標但安裝程序沒到安裝文件夾。

**Comment by qiershow2** [comment]
> 😉還是失敗了，安裝模式無法使用，即使是請求了管理員權限的cmd批處理，能創建桌面圖標但安裝程序沒到安裝文件夾。

手動創建文件夾餅複製exe去rustdesk文件夾重啟後不彈cmd了

**Comment by rustdesk** [comment]
辛苦了2021年3月18日 08:26，qiershow2 ***@***.***>写道：



😉還是失敗了，安裝模式無法使用，即使是請求了管理員權限的cmd批處理，能創建桌面圖標但安裝程序沒到安裝文件夾。



手動創建文件夾餅複製exe去rustdesk文件夾重啟後不彈cmd了

**Comment by rustdesk** [comment]
请问cmd里echo %ProgramFiles%出什么结果？

> > 😉還是失敗了，安裝模式無法使用，即使是請求了管理員權限的cmd批處理，能創建桌面圖標但安裝程序沒到安裝文件夾。
> 
> 手動創建文件夾餅複製exe去rustdesk文件夾重啟後不彈cmd了

**Comment by qiershow2** [comment]
沒有打印出結果，也沒用cmd介面，產生了一個找不到原文件的快捷方式。

**Comment by rustdesk** [comment]
> 沒有打印出結果，也沒用cmd介面，產生了一個找不到原文件的快捷方式。

能否打开cmd， 然后输入echo %ProgramFiles% ？我想看看输出什么结果

**Comment by qiershow2** [comment]
C:\Program Files

**Comment by zhangbo8418** [comment]
> > 沒有打印出結果，也沒用cmd介面，產生了一個找不到原文件的快捷方式。
> 
> 能否打开cmd， 然后输入echo %ProgramFiles% ？我想看看输出什么结果

搞个QQ群或者电报群呗？

**Comment by qiershow2** [comment]
結案：在我這裡這個問題產生於windows10的自帶安全軟件中的「受控制文件夾」安全功能被打開所導致，添加rustdesk到信任程序中，問題不再浮現

**Comment by qiershow2** [comment]
找到了閃cmd窗口原因，和Windows10自帶安全軟件中的「受保護文件夾」功能相關，需要手動添加rustdesk.exe到允許列表中便可正常使用

**Comment by rustdesk** [comment]
谢谢2021年3月20日 13:45，qiershow2 ***@***.***>写道：

結案：在我這裡這個問題產生於windows10的自帶安全軟件中的「受控制文件夾」安全功能被打開所導致，添加rustdesk到信任程序中，問題不再浮現

**Comment by Refactoring** [comment]
```
RustDesk版本：1.1.2

OS:  Windows Server 2016 Standard   
版本：10.0.14393
 
杀毒软件老版Windows Defender：
反恶意软件客户端版本: 4.18.2102.4
引擎版本: 1.1.18000.5
防病毒定义: 1.335.74.0
反间谍软件定义: 1.335.74.0
网络检查系统引擎版本: 1.1.18000.5
网络检查系统定义版本: 1.335.74.0
```

我这也出现这种情况， 系统自带的老版Windows Defender，不是Win10中的安全软件，没有受控制文件夾功能。
安装完成后，不会弹命令行窗口。 但只要用RustDesk连接过去后，就会不停弹窗，长时间Connection连接，断开，重连后，不能进行任何操作。
断开后，用其他远程工具连接，一直在弹窗。

**Comment by open-trade** [comment]
> ```
> RustDesk版本：1.1.2
> 
> OS:  Windows Server 2016 Standard   
> 版本：10.0.14393
>  
> 杀毒软件老版Windows Defender：
> 反恶意软件客户端版本: 4.18.2102.4
> 引擎版本: 1.1.18000.5
> 防病毒定义: 1.335.74.0
> 反间谍软件定义: 1.335.74.0
> 网络检查系统引擎版本: 1.1.18000.5
> 网络检查系统定义版本: 1.335.74.0
> ```
> 
> 我这也出现这种情况， 系统自带的老版Windows Defender，不是Win10中的安全软件，没有受控制文件夾功能。
> 安装完成后，不会弹命令行窗口。 但只要用RustDesk连接过去后，就会不停弹窗，长时间Connection连接，断开，重连后，不能进行任何操作。
> 断开后，用其他远程工具连接，一直在弹窗。

用其他远程工具连接，也一直弹窗? RustDesk没有能力影响好其他工具。

**Comment by Refactoring** [comment]
我描述的不太合适-_-!!   就是上面其他人说的这种命令行窗口，一闪而过，但是不停的出现。 

不影响其他工具。 是在A电脑上安装RustDesk后，没有上述问题。 完后在B电脑上用RustDesk远程连接过去，就会出现命令行窗口不停闪现的问题。 在RustDesk远程界面上能看到，此时远程窗口做不了任何操作。

关闭B电脑的RustDesk连接。 用其他远程工具远程过去，命令行窗口还是一直闪现。

**Comment by open-trade** [comment]
> 我描述的不太合适-_-!! 就是上面其他人说的这种命令行窗口，一闪而过，但是不停的出现。
> 
> 不影响其他工具。 是在A电脑上安装RustDesk后，没有上述问题。 完后在B电脑上用RustDesk远程连接过去，就会出现命令行窗口不停闪现的问题。 在RustDesk远程界面上能看到，此时远程窗口做不了任何操作。
> 
> 关闭B电脑的RustDesk连接。 用其他远程工具远程过去，命令行窗口还是一直闪现。

谢谢，描述的很清楚。

**Comment by rustdesk** [comment]
> > 我描述的不太合适-_-!! 就是上面其他人说的这种命令行窗口，一闪而过，但是不停的出现。
> > 不影响其他工具。 是在A电脑上安装RustDesk后，没有上述问题。 完后在B电脑上用RustDesk远程连接过去，就会出现命令行窗口不停闪现的问题。 在RustDesk远程界面上能看到，此时远程窗口做不了任何操作。
> > 关闭B电脑的RustDesk连接。 用其他远程工具远程过去，命令行窗口还是一直闪现。
> 
> 谢谢，描述的很清楚。
很尴尬，我在同样的2016 10.0.14393版本上没能发现问题。
![image](https://user-images.githubusercontent.com/71636191/113558678-ad013200-9632-11eb-8ba8-a1020989463e.png)

**Comment by Refactoring** [comment]
这..., 看来软件没问题，跟我的环境有关系了。

能提示下，哪些功能逻辑会执行命令行窗口吗？ 我找找我这里的原因。

**Comment by rustdesk** [comment]
> 这..., 看来软件没问题，跟我的环境有关系了。
> 
> 能提示下，哪些功能逻辑会执行命令行窗口吗？ 我找找我这里的原因。

连接建立后，没有执行命令行窗口的操作，只是在建立连接之前认证登录的时候可能会有一个，https://github.com/rustdesk/rustdesk/blob/master/src/server/connection.rs#L384。以前那个反复弹出窗口，是因为RustDesk的bug导致RustDesk服务进程反复重启所致。我的程序里偷懒调用std::process::Command::new运行cmd窗口获取一些系统信息，比如当前系统的活跃用户名，都在 https://github.com/rustdesk/rustdesk/blob/master/src/platform/windows.rs 里面。

**Comment by Refactoring** [comment]
终于看清跳出命令行窗口的标题了，是执行`query`命令查询当前活动用户名。
我用其他远程工具，远程的服务器上，在命令行窗口执行`query user`,可以获取到信息。
```
Microsoft Windows [版本 10.0.14393]
(c) 2016 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>query user
 用户名                会话名             ID  状态    空闲时间   登录时间
>administrator         console             2  运行中    4+04:11  2021-03-23 16:37

C:\Users\Administrator>
```

还有个提示，我点击`Transfer File`准备进行传入文件，提示`No active console user logged on, please connect and logon first.`。

看情况应该是无法获取到当前登录用户名，引起的问题。

**Comment by rustdesk** [comment]
> 终于看清跳出命令行窗口的标题了，是执行`query`命令查询当前活动用户名。
> 我用其他远程工具，远程的服务器上，在命令行窗口执行`query user`,可以获取到信息。
> 
> ```
> Microsoft Windows [版本 10.0.14393]
> (c) 2016 Microsoft Corporation。保留所有权利。
> 
> C:\Users\Administrator>query user
>  用户名                会话名             ID  状态    空闲时间   登录时间
> >administrator         console             2  运行中    4+04:11  2021-03-23 16:37
> 
> C:\Users\Administrator>
> ```
> 
> 还有个提示，我点击`Transfer File`准备进行传入文件，提示`No active console user logged on, please connect and logon first.`。
> 
> 看情况应该是无法获取到当前登录用户名，引起的问题。

明白了，中文的问题没找到，我查的是Active关键字，你这里是运行中，我会在下个版本修复。

**Comment by rustdesk** [comment]
> 终于看清跳出命令行窗口的标题了，是执行`query`命令查询当前活动用户名。
> 我用其他远程工具，远程的服务器上，在命令行窗口执行`query user`,可以获取到信息。
> 
> ```
> Microsoft Windows [版本 10.0.14393]
> (c) 2016 Microsoft Corporation。保留所有权利。
> 
> C:\Users\Administrator>query user
>  用户名                会话名             ID  状态    空闲时间   登录时间
> >administrator         console             2  运行中    4+04:11  2021-03-23 16:37
> 
> C:\Users\Administrator>
> ```
> 
> 还有个提示，我点击`Transfer File`准备进行传入文件，提示`No active console user logged on, please connect and logon first.`。
> 
> 看情况应该是无法获取到当前登录用户名，引起的问题。

我还是该用API吧，不偷懒了，弹出窗口的确挺丑的。

**Comment by rustdesk** [comment]
> 终于看清跳出命令行窗口的标题了，是执行`query`命令查询当前活动用户名。
> 我用其他远程工具，远程的服务器上，在命令行窗口执行`query user`,可以获取到信息。
> 
> ```
> Microsoft Windows [版本 10.0.14393]
> (c) 2016 Microsoft Corporation。保留所有权利。
> 
> C:\Users\Administrator>query user
>  用户名                会话名             ID  状态    空闲时间   登录时间
> >administrator         console             2  运行中    4+04:11  2021-03-23 16:37
> 
> C:\Users\Administrator>
> ```
> 
> 还有个提示，我点击`Transfer File`准备进行传入文件，提示`No active console user logged on, please connect and logon first.`。
> 
> 看情况应该是无法获取到当前登录用户名，引起的问题。

请试一下 https://gitee.com/rustdesk/rustdesk/attach_files/647756/download/rustdesk-1.1.2.exe

**Comment by Refactoring** [comment]
`https://gitee.com/rustdesk/rustdesk/attach_files/647756/download/rustdesk-1.1.2.exe` 文件不存在..  删掉了？

**Comment by rustdesk** [comment]
> https://gitee.com/rustdesk/rustdesk/attach_files/647756/download/rustdesk-1.1.2.exe

https://gitee.com/rustdesk/rustdesk/attach_files/663680/download/rustdesk-1.1.2.exe

**Comment by Refactoring** [comment]
没有命令行窗口不停弹出的问题了。 

不过又出现个无法连接的问题。 提示`Remote desktop is offline`。
成功连接过一次，后面就一直连接不上。 Rustdesk服务重启了，本地这边也安装了上面发的这个版本，都不行。
是我这边远程服务器的网络问题？

**Comment by rustdesk** [comment]
> 没有命令行窗口不停弹出的问题了。
> 
> 不过又出现个无法连接的问题。 提示`Remote desktop is offline`。
> 成功连接过一次，后面就一直连接不上。 Rustdesk服务重启了，本地这边也安装了上面发的这个版本，都不行。
> 是我这边远程服务器的网络问题？

从报错看，是

**Comment by Refactoring** [comment]
哎呀，那就无解了。我这服务器地区特殊些。

**Comment by rustdesk** [comment]
> 哎呀，那就无解了。我这服务器地区特殊些。

Remote desktop is offline 表示受控端没有连接到中心服务器。可以贴出log看看，C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT

**Comment by zhangbo8418** [comment]
> > 哎呀，那就无解了。我这服务器地区特殊些。
> 
> Remote desktop is offline 表示受控端没有连接到中心服务器。可以贴出log看看，C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT

感谢大佬，那个啥的弹黑窗木有了，中文用户名变乱码了，能不能搞个群啊？QQ群？电报群？

**Comment by open-trade** [comment]
> > > 哎呀，那就无解了。我这服务器地区特殊些。
> > 
> > 
> > Remote desktop is offline 表示受控端没有连接到中心服务器。可以贴出log看看，C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT
> 
> 感谢大佬，那个啥的弹黑窗木有了，中文用户名变乱码了，能不能搞个群啊？QQ群？电报群？

不喜欢群，不好追踪问题。能把乱码截图给我看看吗？

**Comment by zhangbo8418** [comment]
> > > > 哎呀，那就无解了。我这服务器地区特殊些。
> > > 
> > > 
> > > Remote desktop is offline 表示受控端没有连接到中心服务器。可以贴出log看看，C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT
> > 
> > 感谢大佬，那个啥的弹黑窗木有了，中文用户名变乱码了，能不能搞个群啊？QQ群？电报群？
> 
> 不喜欢群，不好追踪问题。能把乱码截图给我看看吗？

![乱码(1).png](https://user-images.githubusercontent.com/46797568/113976006-ecb65c80-9872-11eb-9f4c-2ce409943327.png)

**Comment by rustdesk** [comment]
> > > > > 哎呀，那就无解了。我这服务器地区特殊些。
> > > > 
> > > > 
> > > > Remote desktop is offline 表示受控端没有连接到中心服务器。可以贴出log看看，C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT
> > > 
> > > 
> > > 感谢大佬，那个啥的弹黑窗木有了，中文用户名变乱码了，能不能搞个群啊？QQ群？电报群？
> > 
> > 
> > 不喜欢群，不好追踪问题。能把乱码截图给我看看吗？
> 
> ![乱码(1).png](https://user-images.githubusercontent.com/46797568/113976006-ecb65c80-9872-11eb-9f4c-2ce409943327.png)

好的，我在下一版本解决，这俩天就会发出了。

**Comment by rustdesk** [comment]
> > > > > > 哎呀，那就无解了。我这服务器地区特殊些。
> > > > > 
> > > > > 
> > > > > Remote desktop is offline 表示受控端没有连接到中心服务器。可以贴出log看看，C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT
> > > > 
> > > > 
> > > > 感谢大佬，那个啥的弹黑窗木有了，中文用户名变乱码了，能不能搞个群啊？QQ群？电报群？
> > > 
> > > 
> > > 不喜欢群，不好追踪问题。能把乱码截图给我看看吗？
> > 
> > 
> > ![乱码(1).png](https://user-images.githubusercontent.com/46797568/113976006-ecb65c80-9872-11eb-9f4c-2ce409943327.png)
> 
> 好的，我在下一版本解决，这俩天就会发出了。

很尴尬，我的中文名字可以显示出来。回家我再用mac试试，不过用中文做用户名也有点让我始料未及。
![image](https://user-images.githubusercontent.com/71636191/113986300-b206f100-987f-11eb-8d76-7d29f69afed2.png)

**Comment by rustdesk** [comment]
> > > > > 哎呀，那就无解了。我这服务器地区特殊些。
> > > > 
> > > > 
> > > > Remote desktop is offline 表示受控端没有连接到中心服务器。可以贴出log看看，C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT
> > > 
> > > 
> > > 感谢大佬，那个啥的弹黑窗木有了，中文用户名变乱码了，能不能搞个群啊？QQ群？电报群？
> > 
> > 
> > 不喜欢群，不好追踪问题。能把乱码截图给我看看吗？
> 
> ![乱码(1).png](https://user-images.githubusercontent.com/46797568/113976006-ecb65c80-9872-11eb-9f4c-2ce409943327.png)

修复了 https://gitee.com/rustdesk/rustdesk-server/attach_files/665611/download/rustdesk-1.1.3.exe

**Comment by Refactoring** [comment]
> > 哎呀，那就无解了。我这服务器地区特殊些。
> 
> Remote desktop is offline 表示受控端没有连接到中心服务器。可以贴出log看看，
第一个是昨天的，第二个是今天的。
[RustDesk_r2021-04-08_12-09-58.restart-0000.log](https://github.com/rustdesk/rustdesk/files/6283942/RustDesk_r2021-04-08_12-09-58.restart-0000.log)
[RustDesk_rCURRENT.log](https://github.com/rustdesk/rustdesk/files/6283941/RustDesk_rCURRENT.log)

**Comment by rustdesk** [comment]
> > > 哎呀，那就无解了。我这服务器地区特殊些。
> > 
> > 
> > Remote desktop is offline 表示受控端没有连接到中心服务器。可以贴出log看看，
> > 第一个是昨天的，第二个是今天的。
> > [RustDesk_r2021-04-08_12-09-58.restart-0000.log](https://github.com/rustdesk/rustdesk/files/6283942/RustDesk_r2021-04-08_12-09-58.restart-0000.log)
> > [RustDesk_rCURRENT.log](https://github.com/rustdesk/rustdesk/files/6283941/RustDesk_rCURRENT.log)

昨天网络有问题。
`不知道这样的主机。 (os error 11001) `
代表网络问题
