### ISSUE TITLE
White screen window on win10 (gpu acceleration acquired by flutter)

### ISSUE THREAD

**Issue by MaxSecurity** [rustdesk/rustdesk#80]
不知道什么情况
![image](https://user-images.githubusercontent.com/16812469/122397658-c1a36400-cfab-11eb-85b7-f6dff32395f3.png)

**Comment by rustdesk** [comment]
Thanks, there is also somebody seeing this on some Ubuntu. Interesting, it is random. I will give you a version, please try later.

**Comment by MaxSecurity** [comment]
> 谢谢，也有人在某些 Ubuntu 上看到了这个。有趣的是，它是随机的。我给你一个版本，请稍后再试。

好的请给我下载链接

**Comment by rustdesk** [comment]
Give me 1 hour, I need change the way to inline html/js into exe.

**Comment by MaxSecurity** [comment]
> 给我 1 小时，我需要改变将 html/js 内联到 exe 的方式。

老哥你是国人还是usa？

**Comment by rustdesk** [comment]
You guess

**Comment by MaxSecurity** [comment]
> 你猜

肯定是国人 看你那么熟练的看懂中文

**Comment by rustdesk** [comment]
> 链接

https://github.com/rustdesk/rustdesk/releases/download/1.1.6/rustdesk-1.1.6.zip

**Comment by MaxSecurity** [comment]
安装新版本 程序还是白屏  
![image](https://user-images.githubusercontent.com/16812469/122416696-87da5980-cfbb-11eb-8083-bb1df34d8916.png)


> > 链接
> 
> https://github.com/rustdesk/rustdesk/releases/download/1.1.6/rustdesk-1.1.6.zip

**Comment by rustdesk** [comment]
不知道您能不能用开源版本自己编译调试一下？

**Comment by rustdesk** [comment]
我这没发复现也是头疼

**Comment by MaxSecurity** [comment]
> 我这没发复现也是头疼

我这台电脑是老家的没有环境 很尴尬。。。。

**Comment by rustdesk** [comment]
你的windows update版本是啥？

**Comment by rustdesk** [comment]
要不更新一下系统试试

**Comment by MaxSecurity** [comment]
> 要不更新一下系统试试

ok我尝试一下

**Comment by rustdesk** [comment]
> > 要不更新一下系统试试
> 
> ok我尝试一下

OK?

**Comment by MaxSecurity** [comment]
> > > 要不更新一下系统试试
> > 
> > 
> > ok我尝试一下
> 
> OK?
不行还是白屏 不知道啥情况等假期 看看啥情况

**Comment by rustdesk** [comment]
> 还是白屏

看来是那里与我的GUI SDK冲突了，选了个小众的SDK库，的确自己找虐。

**Comment by MaxSecurity** [comment]
> > 还是白屏
> 
> 看来是我的GUI SDK 冲突了，选了个小众的SDK 库，确实自己找虐。

要改GUI SDK???

**Comment by rustdesk** [comment]
未来我会统一成flutter，移动桌面全统一，暂时不会18.06.2021, 14:37, "Doctor_Who丶Max" ***@***.***>:


还是白屏

看来是我的GUI SDK 冲突了，选了个小众的SDK 库，确实自己找虐。

要改GUI SDK???

**Comment by MaxSecurity** [comment]
> 未来我会统一成flutter，移动桌面全统一，暂时不会18.06.2021, 14:37, "Doctor_Who丶Max" ***@***.***>: 还是白屏 看来是我的GUI SDK 冲突了，选了个小众的SDK 库，确实自己找虐。 要改GUI SDK??? —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

👌

**Comment by rustdesk** [comment]
@MaxSecurity 有兴趣可以参与，加速统一步伐。

**Comment by MaxSecurity** [comment]
> @MaxSecurity 有兴趣可以参与，加速统一步伐。

没问题 有什么联系的方式没比如微信群什么的

**Comment by rustdesk** [comment]
> 微信

Email me your wx, info@rustdesk.com

**Comment by MaxSecurity** [comment]
> [info@rustdesk.com](mailto:info@rustdesk.com)

ok

**Comment by MaxSecurity** [comment]
> > 微信
> 
> Email me your wx, [info@rustdesk.com](mailto:info@rustdesk.com)

已发送。

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/93

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/d89d5ef825b1faa0ece05dcca7c1d949036ebea8

**Comment by rustdesk** [comment]
@MaxSecurity could you help me try out 
https://github.com/rustdesk/rustdesk/releases/download/1.1.8/rustdesk-1.1.8-windows_x64.zip

and

https://github.com/rustdesk/rustdesk/releases/download/1.1.8/rustdesk-1.1.8-skia.zip

Hope one can solve the problem.

**Comment by Zejia** [comment]
windows 10 安装了1.1.9有同样的问题。  mac 没有这个问题。
![WechatIMG517](https://user-images.githubusercontent.com/9083195/171315922-d5353507-06e2-4ed3-b61b-262887c44dad.jpeg)

**Comment by rustdesk** [comment]
We are rewriting our UI with Flutter, which will fix this issue.

**Comment by ql2005** [comment]
一样的问题....mac版没问题, 家里的win10白屏, 1.18, 1.19都是~

**Comment by rustdesk** [comment]
try out our nightly build please

**Comment by ql2005** [comment]
> try out our nightly build please

Still a white screen, but a little bit different
![1666961047374](https://user-images.githubusercontent.com/1982911/198590110-e85111c3-6f25-4499-8c3b-79efc8ef905c.jpg)

**Comment by ql2005** [comment]
When I reopen it, it becomes a pure white screen again, but the close button in the upper right corner is interactive, it seems that there is only a problem with the UI display?

**Comment by rustdesk** [comment]
@Kingtous

**Comment by ql2005** [comment]
So amazing!!! When I installed rustdesk on my home computer with a remote tool (todesk & sunlogin) in the company, it was a white screen. When I got home and turned on the monitor, I found that the UI was displayed normally!!
Looking at the screenshot of @MaxSecurity , it seems that he is also using remote tools....

**Comment by rustdesk** [comment]
interesting

**Comment by ql2005** [comment]
Today I connected to my home computer with Rustdesk at my company, and as expected, it was also a white screen

^_^
![1667188546833](https://user-images.githubusercontent.com/1982911/198928314-062ba0bb-ba17-4907-96ae-35108a995e4c.jpg)

**Comment by rustdesk** [comment]
> white

Interesting, honestly, I do no clue either.

**Comment by ql2005** [comment]
inexplicable bug
can interact, just can't see
remote only~

**Comment by grummbeer** [comment]
@ql2005 @MaxSecurity please try with the nighlty version https://github.com/rustdesk/rustdesk/releases/tag/nightly

Still any problems?

**Comment by SwenVogel** [comment]
Hi guys. I have the same problem. I tried the following versions:

- rustdesk-1.2.0-x86-pc-windows-msvc-exe
- rustdesk-1.1.9-windows_x32
- rustdesk-1.1.9-windows_x64-portable
- rustdesk-1.1.9-windows_x64

I have a Windows 10 x64 operating system. I've noticed that in version x there are also no buttons in the title bar. Like "Minimize", "Maximize" or "Close". In every other version the buttons were visible.

**Comment by rustdesk** [comment]
https://github.com/flutter/flutter/issues/74507

**Comment by rustdesk** [comment]
@Kingtous One reason of migrating to flutter is to solve this white screen issue, so embarrassing. Can you follow up to find some workaround?

**Comment by Kingtous** [comment]
> white screen issue, so embarrassing. Can you follow up to find some workaround?

Yes. Seems like a graphic driver issue.

**Comment by Kingtous** [comment]
> 

Could you please provide the detail of your graphic card, and check if your graphic driver is the latest one?  

It seems like the graphic engine of `flutter` has not started successfully.

**Comment by rustdesk** [comment]
does not flutter have fallback solution with degraded performance if there is graphic card issue?

**Comment by Kingtous** [comment]
> does not flutter have fallback solution with degraded performance if there is graphic card issue?


https://github.com/flutter/flutter/issues/75878

Seems that flutter has been working on disabling gpu acceleration in command line.

**Comment by rustdesk** [comment]
@SwenVogel still blank? the latest nightly build.

**Comment by HerrTete** [comment]
I figured out, that the white screen problem is solved by copying the src/ui folder side by side.

**Comment by HerrTete** [comment]
This fixed it for me completly!

https://github.com/sotechdev/rustdesk-customization#embedding-ui--enable-inline-builds

**Comment by rustdesk** [comment]
Close to favor https://github.com/rustdesk/rustdesk/issues/3900

**Comment by CaiMiao** [comment]
用向日葵链接的远端机器，用最新的nightly版本依然显示全白，是不是向日葵用的显示驱动有问题（或者做手脚）？
他们家的win菜单好像显示也不正常，但是shift+win+s截屏后，win菜单显示会正常，但是rustdesk依然全白。
我倾向于是做了手脚。

![图片](https://github.com/rustdesk/rustdesk/assets/4640483/81da82cd-ee95-4bcb-9f13-c7e89b16e0bc)

![图片](https://github.com/rustdesk/rustdesk/assets/4640483/8c55b261-730a-4f21-9977-4b560383aeb7)

**Comment by Alan-HuangKP** [comment]
Hi, I was able to reproduce the bug when opening with Sunlogin, but not when operating via Microsoft Remote Desktop and Direct. The Rustdesk version is 1.2.1.

**Comment by yangjieshao** [comment]
还是白屏
rustdesk-1.4.1-x86_64
第一台
win10 22H2
E5-2676 v3
GTX 1060

第二台
win10 22H2
i7-8700K
RTX 2070

**Comment by yangjieshao** [comment]
接了个物理的显示器后 显示了
所以要接个显卡欺骗器？
