### ISSUE TITLE
Keyboard not work on my MacBook Pro

### ISSUE THREAD

**Issue by JarnTang** [rustdesk/rustdesk#800]
两台MacBook Pro电脑，连接远程电脑后，使用外接键盘没法输入，使用MacBook Pro自带键盘可以正常输入（键盘没有坏）

**Comment by rustdesk** [comment]
https://rustdesk.com/docs/en/manual/mac/#enable-permissions

**Comment by trentnetau** [comment]
Other apps that I have used push a dialog on first run which reminds people and can push to change the settings before the app can be used.

I can't quite remember whether something like this came up on my first run of the app on my MBA M1 when I first launched it, but if it's not already in place....could it be an idea to consider?

**Comment by lucky-wh** [comment]
My situation is using my Mac to control the win computer, and the built-in keyboard cannot be used

**Comment by rysyd** [comment]
> 

Same problem, have you solved it yet?
