### ISSUE TITLE
Moving Tab to Another Window Results in Black Screen

### ISSUE THREAD

**Issue by isential-gmbh** [rustdesk/rustdesk#8008]
### Bug Description

When I have multiple remote sessions in one window and want to detach one of them by clicking on the tab and selecting 'Move Tab to Another Window,' the window detaches but remains black.

Is this a known issue, and is there a solution available?

Thanks a lot!

René

### How to Reproduce

Right-click on the tab and select 'Move to Another Window.'

### Expected Behavior

The remote session should continue in the new detached window.

### Operating system(s) on local side and remote side

Windows 11 Prof. 23H2

### RustDesk Version(s) on local side and remote side

1.2.4 from 2024-04-07 06:4 -> (How to determine the version of RustDesk Server?)

### Screenshots

![1](https://github.com/rustdesk/rustdesk/assets/68383884/62c555b9-cb6c-4f51-85ac-e404a442a4a6)

![2](https://github.com/rustdesk/rustdesk/assets/68383884/0729a1ce-2cb4-4292-a306-f4dca60bdeca)

![3](https://github.com/rustdesk/rustdesk/assets/68383884/0e1b4a23-d0a1-4742-9d81-baa680233159)

**Comment by rustdesk** [comment]
Please test latest nightly

**Comment by rustdesk** [comment]
close as fix merged

**Comment by isential-gmbh** [comment]
Thank you for the quick and uncomplicated response.
