### ISSUE TITLE
Linux,Nightly: can't resize window

### ISSUE THREAD

**Issue by twprh** [rustdesk/rustdesk#8014]
### Bug Description

OS: Linuxmint
no way to resize window

### How to Reproduce

see video

### Expected Behavior

possibility to resize window

### Operating system(s) on local side and remote side

Linux Mint   -> Windows

### RustDesk Version(s) on local side and remote side

nightly: Erstelldatum: 2024-05-10 08:57

### Screenshots

not ok: (nightly release 2024-05-10 08:57)
![rd-nok](https://github.com/rustdesk/rustdesk/assets/46543715/07ebb822-8840-4570-8df3-80ab1e025106)

ok: (nightly release: 2024-05-08 14:25)
![rd-ok](https://github.com/rustdesk/rustdesk/assets/46543715/5f98a849-933b-4aa3-a8d6-2420115b7866)

**Comment by rustdesk** [comment]
close as fix merged
