### ISSUE TITLE
How to protect the privacy of the responsible so that the hosted screen is not displayed

### ISSUE THREAD

**Issue by heshen** [rustdesk/rustdesk#802]
如何保证被控端屏幕不被查看，远程连接后远程的屏幕不显示数据，或者是屏幕保护。
How to protect the privacy of the responsible so that the hosted screen is not displayed

**Comment by heshen** [comment]
on macOs catalina

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/65
