### ISSUE TITLE
Wrong color space after apply icc profile (Plasma 6 wayland)

### ISSUE THREAD

**Issue by st0nie** [rustdesk/rustdesk#8023]
### Bug Description

Display become white after applying icc profile under plasma 6 wayland

### How to Reproduce

Apply icc profile in the display setting
![image](https://github.com/rustdesk/rustdesk/assets/42872734/52515e5a-029c-4d48-ba9a-f37ec3d0035c)

### Expected Behavior

The display is normal and not gone white

### Operating system(s) on local side and remote side

Linux

### RustDesk Version(s) on local side and remote side

1.2.4-nightly

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/42872734/7ce1f08e-eebc-4a41-86cd-2116ba1e4b87)

### Additional Context

Without icc profile, everything behaves normally

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
