### ISSUE TITLE
I compiled Rustdesk myself and ran it with an error message

### ISSUE THREAD

**Issue by mingpuwu** [rustdesk/rustdesk#8024]
### Bug Description

error message :
Finished `dev` profile [unoptimized + debuginfo] target(s) in 3.48s
     Running `target\debug\rustdesk.exe`
[2024-05-12T05:00:00Z INFO  librustdesk::core_main] main start args:[]
thread 'main' panicked at library\core\src\panicking.rs:156:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
error: process didn't exit successfully: `target\debug\rustdesk.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)

### How to Reproduce

I don't know if you've ever encountered such a situation before

### Expected Behavior

Can be compiled and used normally

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.2.4

### Screenshots

![20240512130905](https://github.com/rustdesk/rustdesk/assets/40490370/e838cebf-3e99-41a3-818a-fcf4dfe51111)

**Comment by rustdesk** [comment]
#763
