### ISSUE TITLE
Feature Request - DNS Service Record Lookup

### ISSUE THREAD

**Issue by nhalstead** [rustdesk/rustdesk#803]
Allow the relay server input box to use the [DNS Service record](https://en.wikipedia.org/wiki/SRV_record) for a host and port to connect to.

This would allow a "zero-touch" config feel for configuring the client and enable the clients to know what host and port to use to connect. Basically doing the same thing as Minecraft, Kerberos, SIP, and LDAP all support the use of service records via DNS.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/514#issuecomment-1126679055

dup
