### ISSUE TITLE
Multimonitor: Window Positioning Issues

### ISSUE THREAD

**Issue by isential-gmbh** [rustdesk/rustdesk#8038]
### Bug Description

My Setup:

Dell XPS Notebook i9
Notebook Display: Primary Display, 3840x2400 pixels, Scaling 175%, HDR on, located on the right
Second Display: Secondary Display, LG, 3840x2160 pixels, Scaling 100%, HDR on, located on the left

Move program window to the secondary display and then close it. Upon reopening, the program window is positioned at a different location on the secondary display; often partially or completely outside the visible area.

The incorrect window position is always to the left of the secondary display.

After startup, I need to press Alt+Spacebar to display the context menu (it always appears on the left edge of the primary display). Then, I select 'Restore', and with the right arrow key, I bring the window back into the visible area.

When I close the program on the primary display, the window size and position are correctly restored upon restart.

### How to Reproduce

Move program window to the secondary display and then close it. Upon reopening, the program window is positioned at a different location on the secondary display; often partially or completely outside the visible area."

### Expected Behavior

The position and size of the program window should be restored correctly upon program startup.

### Operating system(s) on local side and remote side

Windows 11 Prof. 23H2

### RustDesk Version(s) on local side and remote side

1.2.4 from 2024-04-07 06:4 -> ???

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/68383884/c9acca60-ac64-475a-bed9-3a719660726f)

**Comment by rustdesk** [comment]
@fufesou follow up

**Comment by fufesou** [comment]
Sorry, I haven't found a fix yet. This issue may take some time to fix.

**Comment by rustdesk** [comment]
Please test the nightly build.

**Comment by rustdesk** [comment]
close as fix merged
