### ISSUE TITLE
Windows 10/11 Pro Silent Install Parameter Issue

### ISSUE THREAD

**Issue by darkofficial** [rustdesk/rustdesk#8046]
### Bug Description

I tried to install via a script from the developer's website https://rustdesk.com/docs/en/self-host/client-deployment/ with Windows batch/cmd, adding after --silent-install the parameter -installdir. Also Trying -l, -d, -path and nothing work - RustDesk still placed in Program Files. 
Also trying the same via winget with the same configs (-l, -d, -path) and trying --override with /D= and INSTALLDIR= - still doesn't work.
How to change directory?

### How to Reproduce

Using the script or winget

### Expected Behavior

Change the destination folder to something else, for example D:\Multimedia\RustDesk

### Operating system(s) on local side and remote side

Windows 10/11

### RustDesk Version(s) on local side and remote side

1.2.3-x86_64

### Screenshots

Nothing to show

**Comment by rustdesk** [comment]
#763
