### ISSUE TITLE
Starting service result in program looping.

### ISSUE THREAD

**Issue by nate235** [rustdesk/rustdesk#8059]
### Bug Description

Selecting "start service" frequently hangs/loops the program

### How to Reproduce

As above, the program runs without the service starting for whatever reason. Selecting start service then cause the program to close and reopen multiple times, frequently looping. Resulting in have to kill the process in task manager.

### Expected Behavior

Not have to start a service, within the program I've opened. Not having the program crash or get stuck when selecting this option.

### Operating system(s) on local side and remote side

Windows 11 -> win 10

### RustDesk Version(s) on local side and remote side

1.2.3-2 -> 1.2.3-2 (happened previous version)

### Screenshots

Unless a vid is required a screenshot won't help.

### Additional Context

Happened last version as well.

**Comment by rustdesk** [comment]
duplicate: https://github.com/rustdesk/rustdesk/discussions/6640#discussioncomment-9430285
