### ISSUE TITLE
FTR on a NanoPC-T6

### ISSUE THREAD

**Issue by JiffB** [rustdesk/rustdesk#8062]
### Bug Description

Fail to run on a FriendlyElec NanoPC-T6 computer (aarch64 - CPU RK3588) using their Debian bullseye OS image.

### How to Reproduce

```
~$ rustdesk
libGL error: failed to create dri screen
libGL error: failed to load driver: rockchip
libGL error: failed to create dri screen
libGL error: failed to load driver: rockchip
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(57)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed
Aborted
```

### Expected Behavior

rustdesk to run correctly on this machine.

### Operating system(s) on local side and remote side

debian bullseye aarch64

### RustDesk Version(s) on local side and remote side

1.48.0-dfsg1-2

### Screenshots

irrelevant

### Additional Context

This looks like the same as the NVidia driver problem issue open bug - I hope there's a cure for this one.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
