### ISSUE TITLE
web client doesn`t work on debian

### ISSUE THREAD

**Issue by svcgv** [rustdesk/rustdesk#8064]
### Bug Description

I clonened code and build web client. It could work on win11 and Ubuntu,but not work on debian chrome.deb.I can show mouse and use keyboard, the screen is alwayse black whatever I use any codec.
![微信截图_20240515171629](https://github.com/rustdesk/rustdesk/assets/25626424/7d26929e-bc54-4221-b71f-e56cb5b944c3)

### How to Reproduce

1.install a new debian system
2.install chrome
3.view web client page&connect

### Expected Behavior

show real screen

### Operating system(s) on local side and remote side

debian-12.5.0-amd64-netinst -> any

### RustDesk Version(s) on local side and remote side

1.2.3|1.2.4 -> 1.2.3

### Screenshots

![微信截图_20240515172409](https://github.com/rustdesk/rustdesk/assets/25626424/32cba812-87ad-4a6f-a604-b112646e5a4d)
![微信截图_20240515171629](https://github.com/rustdesk/rustdesk/assets/25626424/ad2518c0-51c0-490a-b365-94ee943f7b1a)

**Comment by rustdesk** [comment]
Under dev, no issue accepted.
