### ISSUE TITLE
Mouse scrollwheel horizontal direction is in reverse

### ISSUE THREAD

**Issue by AtmanActive** [rustdesk/rustdesk#8081]
### Bug Description

This is on the latest windows server version and the latest windows client version.

When using a modern mouse that has scrollwheel tilt left and tilt right capabilities, the reaction on the RustDesk server is reversed. When I tilt my scrollwheel left, RustDesk scrolls right, and when I tilt my scrollwheel right, RustDesk scrolls left.
This is incorrect.
The direction should be reversed.

### How to Reproduce

Open this URL in your browser, both on your local machine and on the remote desktop machine.

https://codepen.io/jaemskyle/pen/XWJvRL

Now use your mouse scrollwheel tilt to scroll left/right.
On your local desktop, scroll direction is correct, on the remote desktop, it is reversed.

[](https://codepen.io/jaemskyle/pen/XWJvRL)

### Expected Behavior

When I tilt my scrollwheel left, RustDesk should scroll left, and when I tilt my scrollwheel right, RustDesk should scroll to the right.

### Operating system(s) on local side and remote side

Windows 10 Pro x64 -> Windows 10 Pro x64

### RustDesk Version(s) on local side and remote side

1.2.3-2 -> 1.2.3-2

### Screenshots

It is about the movement, no screenshots can show this bug.

**Comment by AtmanActive** [comment]
Yes, there is a "Reverse mouse wheel" drop down option but that one reverses both the wheel and the tilt.
So, when I enable that one I get tilt working correctly but now the scroll wheel is in reverse (scrolling up when I'm pulling the wheel down and vice versa).

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367
