### ISSUE TITLE
Keys F13-F24 are not going through

### ISSUE THREAD

**Issue by AtmanActive** [rustdesk/rustdesk#8082]
### Bug Description

Keys F13-F24 are not going through.

### How to Reproduce

Get a keyboard app that can transmit keys F13-F24 (StreamDeck, SayoDevice...).
Open the following URL both on your local machine and on the remote machine.

https://onlinekeyboardtester.com/

Keep pressing any of the keys from F13 to F24.
Your local browser shows these key presses, the remote machine does not.

### Expected Behavior

Keys F13-F24 are registered on the remote machine.

### Operating system(s) on local side and remote side

Windows 10 Pro x64 -> Windows 10 Pro x64

### RustDesk Version(s) on local side and remote side

1.2.3-2 -> 1.2.3-2

### Screenshots

N/A

**Comment by AtmanActive** [comment]
```
That's in "Legacy mode":  F13-F24 are not going through, NumPadLeft and NumPadRight are going through.
In "Map Mode":            F13-F24 are going through, NumPadLeft and NumPadRight are not going through.
In "Translate Mode Beta": F13-F24 are going through, NumPadLeft and NumPadRight are not going through.
```

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367
