### ISSUE TITLE
--config Invalid 

### ISSUE THREAD

**Issue by jackadam1981** [rustdesk/rustdesk#8088]
### Bug Description

I am trying to deploy Rustdesk within the AD domain and will use the config command to configure the server and key.

I have exported the configuration information from the network configuration and attempted to import it, and it is working properly.
9JSPjtCnChWQxkHb182MTJ0UvF2cQhDWlBXcqNlT0pGUQNXNBRlaOlVY1hFU4IiOikXZrJCLiIiikGchJCLiIiOikXYsVmciwiIyIjLy4CO2EjLykTMiojI0N3boJye

Following https://rustdesk.com/docs/en/self-host/client-deployment/
Rustdesk.exe -- silent install
CD "C: \ Program Files \ RustDesk \"
Rustdesk.exe -- install service

however
Rustdesk.exe -- config "9JSPjtCNChWQxkHb182MTJ0UvF2cQhDWlBXcqNlT0pGUQNXNBRlaOlVY1hFU4IiOikXZrJCLiIiOikGchJCIiOikXYsVmciwiIyIjLy4CO2EjLykTMiojI0N3boJye"
Not effective.

### How to Reproduce

rustdesk-1.2.3-2-x86_64.exe -- silent install
CD "C: \ Program Files \ RustDesk \"
Rustdesk.exe -- install service

### Expected Behavior

Set server address and key through command line

### Operating system(s) on local side and remote side

Windows11 -> 

### RustDesk Version(s) on local side and remote side

1.2.3-2

### Screenshots

no need 

### Additional Context

C:\Users\jacka\AppData\Roaming\RustDesk\log\config\rustdesk_r2024-05-18_21-34-15.log

[2024-05-18 21:32:46.306650 +08:00] INFO [src\core_main.rs:162] main start args:["--config", "9JSPjtCNChWQxkHb182MTJ0UvF2cQhDWlBXcqNlT0pGUQNXNBRlaOlVY1hFU4IiOikXZrJCLiIiOikGchJCLiIiOikXYsVmciwiIyIjLy4CO2EjLykTMiojI0N3boJye"]

C:\Users\jacka\AppData\Roaming\RustDesk\log\config\rustdesk_rCURRENT.log

[2024-05-18 21:35:30.231379 +08:00] INFO [src\core_main.rs:162] main start args:["--config", "9JSPjtCNChWQxkHb182MTJ0UvF2cQhDWlBXcqNlT0pGUQNXNBRlaOlVY1hFU4IiOikXZrJCLiIiOikGchJCLiIiOikXYsVmciwiIyIjLy4CO2EjLykTMiojI0N3boJye"]

C:\Users\jacka\AppData\Roaming\RustDesk\config\RustDesk2.toml

rendezvous_server = 'rs-ny.rustdesk.com:21116'
nat_type = 1
serial = 0

[options]
local-ip-addr = '172.16.0.2'

**Comment by rustdesk** [comment]
#763
