### ISSUE TITLE
Add tray and background service on Linux

### ISSUE THREAD

**Issue by mingti** [rustdesk/rustdesk#809]
on manjaro linux , Clicking the close button will exit the program, I want to minimize to tray and keeping in background

**Comment by rustdesk** [comment]
There is already background service once you install, but we do have no tray yet.

**Comment by weirdal3333** [comment]
Bumping this, having a minimize to tray feature is very important to a lot of people! The background service seems to be broken, because when I close the rustdesk window it kills all connections and I can't reconnect

**Comment by rustdesk** [comment]
tracked by #389

**Comment by rustdesk** [comment]
close as fix merged. for systemd only.

**Comment by whamadmin** [comment]
### Add background service for Flatpak

Every time I close the Flatpak, the background service ends, not allowing me to remote into the machine.
Is there a command to keep the background service running?

**Comment by rpgdev** [comment]
> There is already background service once you install, but we do have no tray yet.

Is that so? If I close the app on Fedora Linux after some time I can't start a session. I installed and restarted my computer and this is still the case. Am I doing something wrong @rustdesk ? If so what can i review to make sure the service isn't killed?

**Comment by Mr-MooMoo** [comment]
Same here (opensuse TW, rustdesk 1.2.6)

**Comment by drwpls** [comment]
> > There is already background service once you install, but we do have no tray yet.
> 
> Is that so? If I close the app on Fedora Linux after some time I can't start a session. I installed and restarted my computer and this is still the case. Am I doing something wrong @rustdesk ? If so what can i review to make sure the service isn't killed?

Same issue, may be SELinux prevents this?

**Comment by giswqs** [comment]
I just ran into the same issue. Clicking the close button on Manjaro will end the program, and I can't connect to Rustdesk any more.

**Comment by rpgdev** [comment]
I do not have issues with the 1.3.7 RPM after upgrading to Fedora 40 so the issue isn't relevant to me anymore. Tray icon shows up if the service is enabled and I can connect to my session.

**Comment by francwalter** [comment]
I had the same problem on Ubuntu 24.04 with the missing background service.
I had installed RustDesk with the Software App (showing "Flathub" and "FLATPAK" under the Install Button). 
When I exited RustDesk the background service was not running, no connection possible. No icon in the NotificationBar neither.
I solved that issue with clean (complete) uninstalling from Software and reinstalling the deb file from the Downloads on Github with:

`sudo apt install rustdesk-1.3.8-x86_64.deb`

The ID was then the same but I had to do all settings (e.g. the permanent password).
But now the Icon is present and the service is running 😄 
I guess I have to do updates manually now.
Thank you for this great opensource software, it was time to say goodbye to those "free" Nagscreen-apps like TeamViewer and AnyDesk 😏

**Comment by Techttv** [comment]
I managed to make it tray even if I installed it with yay. 
```
mkdir -p ~/.config/systemd/user
nano ~/.config/systemd/user/rustdesk.service
```
```

[Unit]
Description=RustDesk Remote Desktop
After=graphical-session.target

[Service]
Type=simple
ExecStart=/usr/bin/rustdesk --service
Restart=always
Environment=DISPLAY=:0
Environment=WAYLAND_DISPLAY=wayland-0

[Install]
WantedBy=default.target
```

```
systemctl --user enable rustdesk.service
systemctl --user start rustdesk.service
systemctl --user status rustdesk.service
```


But after the first connection when I had to select the screen to use I can't connect anymore and it loops and fail everytime.
