### ISSUE TITLE
connection speed slow

### ISSUE THREAD

**Issue by yunxilyf** [rustdesk/rustdesk#8104]
### Bug Description

If the client uses the server's key, the connection speed will become very slow. Currently, it can only connect without using the key.

### How to Reproduce

If the client uses the server's key, the connection speed will become very slow. Currently, it can only connect without using the key.

### Expected Behavior

If the client uses the server's key, the connection speed will become very slow. Currently, it can only connect without using the key.

### Operating system(s) on local side and remote side

win11

### RustDesk Version(s) on local side and remote side

1.2.3-2

### Screenshots

no

**Comment by rustdesk** [comment]
#763
