### ISSUE TITLE
HTTP proxy not working (username insertion disabled)

### ISSUE THREAD

**Issue by maicardi** [rustdesk/rustdesk#8105]
### Bug Description

To me HTTP proxy does not work, as the username field in the "Proxy Socks5/Http(s)" is disabled and can't be filled.

RustDesk v1.2.4 (2024-05-21 00:27) on Ubuntu 22.04.4 LTS

### How to Reproduce

Open program settings, click on "Network", choose "Proxy Socks5/Http(s)" and try to enter the username.

### Expected Behavior

Username should be editable

### Operating system(s) on local side and remote side

Ubuntu 22.04.4 LTS

### RustDesk Version(s) on local side and remote side

1.2.4

### Screenshots

(useless)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by rustdesk** [comment]
Apologize, I can reproduce. @fufesou

**Comment by rustdesk** [comment]
close as fix merged in #8109
