### ISSUE TITLE
Rustdesk service not starting on gnome shell login screen

### ISSUE THREAD

**Issue by NicKoehler** [rustdesk/rustdesk#8106]
### Bug Description

The service is not starting properly on boot using this specs:

Distro: Arch Linux
Kernel: Linux 6.9.1-arch1-1
DE: Gnome 46

this is what `systemctl status rustdesk` shows

```bash
● rustdesk.service - RustDesk
     Loaded: loaded (/etc/systemd/system/rustdesk.service; enabled; preset: disabled)
     Active: active (running) since Tue 2024-05-21 13:02:13 CEST; 23s ago
   Main PID: 675 (rustdesk)
      Tasks: 19 (limit: 38275)
     Memory: 43.0M (peak: 44.4M)
        CPU: 5.573s
     CGroup: /system.slice/rustdesk.service
             └─675 /usr/bin/rustdesk --service

mag 21 13:02:30 arch rustdesk[5031]: sudo: errore nell'inizializzare il plugin di audit sudoers_audit
mag 21 13:02:32 arch sudo[5882]:     root : unknown user listed. ; PWD=/ ; USER=listed. ;
```

It seems like the error comes from rustdesk parsing an user named "listed." instead of the actual username (maybe root?).

### How to Reproduce

1. install rustdesk
2. enable rustdesk service
3. reboot and don't login
4. try to connect from another client

### Expected Behavior

I should be able to connect

### Operating system(s) on local side and remote side

All -> Linux

### RustDesk Version(s) on local side and remote side

nightly -> nightly

**Comment by fufesou** [comment]
Thanks for your feedback.

Can you please run `longinctl` and paste the output here?
Please hide private info.

**Comment by NicKoehler** [comment]
From what I can tell seems like the error is from this function:

https://github.com/rustdesk/rustdesk/blob/676ee997091f091f68fbaa20de4ee7c376b210be/libs/hbb_common/src/platform/linux.rs#L145



> Thanks for your feedback.
> 
> Can you please run `longinctl` on the server side and paste the output here? Please hide private info.

```bash
SESSION  UID USER SEAT  TTY   STATE  IDLE SINCE    
      2  120 gdm  seat0 tty1  active yes  13min ago
      4 1000 nic  -     pts/0 active no   -        
      5 1000 nic  -     pts/1 active no   -       
```

**Comment by rustdesk** [comment]
Is it currently wayland or x11?

**Comment by NicKoehler** [comment]
Same issue with both, the server doesn't show up as online too.

**Comment by rustdesk** [comment]
Both for x11 and wayland?

**Comment by NicKoehler** [comment]
Yes, both X11 and Wayland

**Comment by rustdesk** [comment]
Could confirm with below command?

`show-session -p Type <session-id>`

**Comment by NicKoehler** [comment]
I have

```bash
loginctl show-session -p Type 2
Type=wayland
```

But my `/etc/gdm/custom.conf` is like this:
```
t# GDM configuration storage

[daemon]
# Uncomment the line below to force the login screen to use Xorg
WaylandEnable=false

[security]

[xdmcp]

[chooser]

[debug]
# Uncomment the line below to turn on debugging
#Enable=true
```

**Comment by rustdesk** [comment]
So it is still Wayland.

**Comment by NicKoehler** [comment]
I see, but previously the server would still appear online, and if I tried to connect, it would say that Wayland is not supported. Now it just appears completely off.

**Comment by rustdesk** [comment]
Is this important for you? both not usable.

**Comment by NicKoehler** [comment]
No, I just reported it because I was using X11 all the time and suddenly it stopped working. Now I see that the problem is my session still being Wayland and ignoring my custom.conf.

**Comment by rustdesk** [comment]
Nervertheless, you are right, it should show "Login screen using Wayland is not supported".
@fufesou follow it up.

**Comment by NicKoehler** [comment]
> Is this important for you? both not usable. And previously is it gnome 46?

No after I updated my nighly after a long time of no updates.

**Comment by rustdesk** [comment]
Nevertheless, you are right, it should show Login screen using Wayland is not supported.
@fufesou follow it up.

**Comment by NicKoehler** [comment]
I wouldn't have opened this issue if I had seen the Wayland message. I would have fixed my session, sorry for the misunderstanding.

**Comment by rustdesk** [comment]
This is a good report. Thanks.

**Comment by NicKoehler** [comment]
My custom.conf was not working, for some reason. I fixed it by changing my `/usr/share/gdm/gdm.schemas`:

```
 <schema>
      <key>daemon/WaylandEnable</key>
      <signature>b</signature>
      <default>false</default>  # <- changed this to from true to false and restarted my gdm session.
    </schema>
```

Probably not a proper fix, but it worked.

**Comment by rustdesk** [comment]
Thanks

**Comment by rustdesk** [comment]
@NicKoehler please help test the latest nightly

**Comment by NicKoehler** [comment]
Tried both wayland and x with the expected results. Wayland not working but showing a message, x working fine.
