### ISSUE TITLE
win10 remote macos Keyboard mapping error

### ISSUE THREAD

**Issue by Qingnan7780** [rustdesk/rustdesk#8112]
### Bug Description

version 1.2.4
legacy mode
1. windows input  numbers 6 and 7， macos becomes a symbol;
2. Windows input symbol 7 , macos changes to number 7
3. Windows input symbol  "  , macos becomes symbol 「」

map mode
After exchanging CTRL and Command, there is a delay in the CTRL key

### How to Reproduce

Any Windows remote Mac will do this

### Expected Behavior

correct this error

### Operating system(s) on local side and remote side

windows10 remote macos

### RustDesk Version(s) on local side and remote side

1.24 remote 1.24

### Screenshots

test please

**Comment by Qingnan7780** [comment]
The above error will only occur when opening the swap control command key

**Comment by Qingnan7780** [comment]
> c2h1YW5nbG9uZ2NoZW5AeWVhaC5lbnQ=

yeah.net?i think wrong?cannot send email

**Comment by rustdesk** [comment]
yes, a typo there, please send mail to fufesou, and allow him remote your mac if possible so that he can reproduce the issue and diagnose

**Comment by Qingnan7780** [comment]
> yes, a typo there, please send mail to fufesou, and allow him remote your mac if possible so that he can reproduce the issue and diagnose

email wrong，i cannot send email

**Comment by fufesou** [comment]
my email `shuanglongchen@yeah.net`

**Comment by rustdesk** [comment]
shuanglongchen@yeah.net

**Comment by Qingnan7780** [comment]
https://github.com/rustdesk/rustdesk/assets/63048659/8969a010-29d6-4f0f-a8d4-bec3731f7c9b

**Comment by Dylandoesprogramming** [comment]
I can confirm this same bug, going from windows 11 to macOS Sonoma 14.2.1, main difference was it swapped my 7 and ; characters. Disabling ctrl command swap fixes the issue.

Can't use map or translate mode as they both fail to copy and paste or redo/undo (basically any keyboard shortcuts) consistently, legacy doesnt have that issue.

**Comment by fufesou** [comment]
@Dylandoesprogramming Hi, could you please give a screenshot of the keyboard settings?

![image](https://github.com/user-attachments/assets/f4431ea2-31d2-4a31-8177-66975a784ea8)

Windows -> MacOS, "Map mode", No "Swap control-command key", `CMD`+`C` , `CMD`+`Z`, `CMD` + `Shift` + `Z` work fine for me.

**Comment by Dylandoesprogramming** [comment]
@fufesou 
Here you go, in map mode the `CMD` + `C` and other cmd keyboard shortcuts will only work if pressed at exactly the same time, if you press it with a slight delay between `CMD` and `C` or press the command twice without letting off `CMD` and repressing it, it will again just write the character `C`.

Funny enough the symbol swapping issue seems to have disappeared at least for myself, 7 and ; are no longer swapped.

![image](https://github.com/user-attachments/assets/b27bdaac-6093-472c-95f3-e9b4a48f79b4)

@sakisdog I think you might be right, I can't do and `CMD` commands (or control commands if swapped) while mouse is moving, but that appears to be a separate issue from my above described one, as I wasn't moving my mouse during those tests.

**Comment by fufesou** [comment]
>  if you press it with a slight delay between `CMD` and `C` or press the command twice without letting off `CMD` and repressing it, it will again just write the character `C`

Thanks. I can't reproduce this though, I'll run some more tests.

**Comment by rustdesk** [comment]
Please test the nightly build, update on controlled side.

**Comment by joshvermast** [comment]
FYI this is still happening for me with "Swap control-command key" enabled on 1.4.1 @rustdesk 

<img width="235" height="257" alt="Image" src="https://github.com/user-attachments/assets/c7a6624d-3e35-4099-972f-34326aba4156" />
