### ISSUE TITLE
RustDeskIddDriver Device Not Installing - No Monitor plugged in

### ISSUE THREAD

**Issue by tcherry7** [rustdesk/rustdesk#8113]
### Bug Description

The RustDeskIDD Driver Device isn't listed in Device Manager so when I use Rustdesk to connect to the workstation it shows "Successful Connected, waiting for image..." 

If I plug a monitor in while that message is showing Rustdesk will connect. 

### How to Reproduce

Attempt to connect to headless workstation.

### Expected Behavior

Connection to workstation opens and I'm able to control the workstation. 

### Operating system(s) on local side and remote side

Windows11 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.3->1.2.4

### Screenshots

![Rustdesk error](https://github.com/rustdesk/rustdesk/assets/62858974/fc9c57cc-5635-4bd8-aaf9-dce597d9e0b8)

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
@tcherry7 please test 1.2.4 to 1.2.4 first, also please test add virtual display from the menu of remote window.

**Comment by tcherry7** [comment]
> @tcherry7 please test 1.2.4 to 1.2.4 first, also please test add virtual display manually from the menu of remote window. If possible, could you also test how anydesk or teamviewer work in your case?

I thought I had tried that earlier but apparently I didn't. That fixed my issue. Thank you!

**Comment by fufesou** [comment]
@tcherry7 Do you use the build here? https://github.com/rustdesk/rustdesk/releases/tag/1.2.4 

We do not include `RustDeskIddDriver` any more.

Please check if you have this device installed?

![image](https://github.com/rustdesk/rustdesk/assets/13586388/36262dd6-88c2-425e-8885-6542d1e92002)
