### ISSUE TITLE
Android app crash Version 1.2.3

### ISSUE THREAD

**Issue by elicec** [rustdesk/rustdesk#8124]
### Bug Description

When the computer client attempts to control an Android device, and while sliding through an interface containing a list on the computer side, the app on the Android end crashes.

### How to Reproduce

When the computer client attempts to control an Android device, and while sliding through an interface containing a list on the computer side, the app on the Android end crashes.

### Expected Behavior

normal slid

### Operating system(s) on local side and remote side

window 10 - > android 7

### RustDesk Version(s) on local side and remote side

1.2.3-2 -> 1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/9591680/11004177-eb77-4571-8f03-cd11aebb84a7)

### Additional Context

05-23 04:34:47.225  7400  7400 F DEBUG   : Revision: '0'
05-23 04:34:47.225  7400  7400 F DEBUG   : ABI: 'arm'
05-23 04:34:47.226  7400  7400 F DEBUG   : pid: 6979, tid: 7117, name: Thread-8  >>> com.carriez.flutter_hbb <<<
05-23 04:34:47.226  7400  7400 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
05-23 04:34:47.235  7400  7400 F DEBUG   : Abort message: 'art/runtime/indirect_reference_table.cc:132] JNI ERROR (app bug): local reference table overflow (max=512)'
05-23 04:34:47.235  7400  7400 F DEBUG   :     r0 00000000  r1 00001bcd  r2 00000006  r3 00000008
05-23 04:34:47.235  7400  7400 F DEBUG   :     r4 86a77978  r5 00000006  r6 86a77920  r7 0000010c
05-23 04:34:47.235  7400  7400 F DEBUG   :     r8 00000000  r9 0000000a  sl 0000028c  fp 89363300
05-23 04:34:47.235  7400  7400 F DEBUG   :     ip 0000000b  sp 86a72910  lr aa8a35a7  pc aa8a5e28  cpsr 200d0010
05-23 04:34:47.257  7400  7400 F DEBUG   : 
05-23 04:34:47.257  7400  7400 F DEBUG   : backtrace:
05-23 04:34:47.258  7400  7400 F DEBUG   :     #00 pc 00049e28  /system/lib/libc.so (tgkill+12)
05-23 04:34:47.258  7400  7400 F DEBUG   :     #01 pc 000475a3  /system/lib/libc.so (pthread_kill+34)
05-23 04:34:47.258  7400  7400 F DEBUG   :     #02 pc 0001d7f5  /system/lib/libc.so (raise+10)
05-23 04:34:47.258  7400  7400 F DEBUG   :     #03 pc 00019331  /system/lib/libc.so (__libc_android_abort+34)
05-23 04:34:47.258  7400  7400 F DEBUG   :     #04 pc 000172e8  /system/lib/libc.so (abort+4)
05-23 04:34:47.258  7400  7400 F DEBUG   :     #05 pc 0031af89  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+328)
05-23 04:34:47.259  7400  7400 F DEBUG   :     #06 pc 000b5285  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+1132)
05-23 04:34:47.259  7400  7400 F DEBUG   :     #07 pc 001bc4bb  /system/lib/libart.so (_ZN3art22IndirectReferenceTable3AddEjPNS_6mirror6ObjectE+194)
05-23 04:34:47.259  7400  7400 F DEBUG   :     #08 pc 00264993  /system/lib/libart.so (_ZN3art3JNI14GetObjectClassEP7_JNIEnvP8_jobject+426)
05-23 04:34:47.259  7400  7400 F DEBUG   :     #09 pc 00238f0b  /data/app/com.carriez.flutter_hbb-1/lib/arm/librustdesk.so (offset 0x2fe000)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4118
