### ISSUE TITLE
black screen on one particular Windows 10 PC

### ISSUE THREAD

**Issue by mac1-131** [rustdesk/rustdesk#8142]
### Bug Description

when I make a connection from this one particular PC, the screen is always black. The mouse moves at the other end, but all I see is a black screen

inbound connections to this PC are fine

recording a video, if I use AV1 codec I can only play the video in Firefox (other media players show errors) but if I use AV9 codec, I can play the video in media players, but black screen on rustdesk

### How to Reproduce

make an outbound connection

### Expected Behavior

see the other device's dcreen

### Operating system(s) on local side and remote side

Windows 10 x64 build 19045

### RustDesk Version(s) on local side and remote side

1.2.3-2 and 1.2.4

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/57259400/754e3852-aa25-4a3a-a377-c5eed2a68c0b)

### Additional Context

using my own rustdesk server, which seems to work fine on all other devices, Windows 10, Windows 11, headless raspberry pi, Android, IOS

**Comment by 21pages** [comment]
Can't reproduce with 1.2.3-2 -> 1.2.4/nightly using vp9/av1.

> if I use AV1 codec I can only play the video in Firefox

Maybe your media player lack of av1 decoding ability, try vlc/potplayer

Could you send `%appdata%/Rustdesk/log/rustdesk_rCURRENT.log` to my email after the black screen connection? My email is `c3VuYm9lYXN5QGdtYWlsLmNvbQo=` (base64).

After that, please try nightly as the control side.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/8107
