### ISSUE TITLE
Wayland/Sway clipboard does not work

### ISSUE THREAD

**Issue by jtagcat** [rustdesk/rustdesk#8144]
### Bug Description

Related #3455

### How to Reproduce

Guest: Windows 11
Viewer: Sway, Arch Linux

Clipboard from-to the guest does not wrk at all. Running from CLI gives no logs about clipboard, or errors. Using `QT_QPA_PLATFORM=xcb` doesn't help. Using https://github.com/Linus789/wl-clip-persist or https://github.com/chmouel/clipman does not help.

### Expected Behavior

Clipboard works :sparkles: 

### Operating system(s) on local side and remote side

Arch Linux -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

not applicable

**Comment by jtagcat** [comment]
Ah, I missed the boat when skimming over the issue multiple times. `GDK_BACKEND=x11` does work. Keeping open, as it appears that clipboard should work running natively as well.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/6586 1.2.4
