### ISSUE TITLE
Mouse icon display error

### ISSUE THREAD

**Issue by saobilin** [rustdesk/rustdesk#8147]
### Bug Description

<img width="232" alt="rustmo" src="https://github.com/rustdesk/rustdesk/assets/50769148/d1348d5b-5ebb-4a7d-aa25-8efb85234d73">
When i install the system to win11,icon turned like this.And there is always only one type of icon, without any changes to other icons.In android app also the same.And his actual click point is slightly lower than a normal mouse

### How to Reproduce

i dont know how to reproduce it.i try to reboot my pc,it still like this.

### Expected Behavior

Change back to a normal mouse icon

### Operating system(s) on local side and remote side

Windows 11 > Windows 11

### RustDesk Version(s) on local side and remote side

1.2.3-1 > 1.2.3-1

### Screenshots

<img width="232" alt="rustmo" src="https://github.com/rustdesk/rustdesk/assets/50769148/b475c7ea-a9eb-4349-98e8-8e43f94f68c4">

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367
