### ISSUE TITLE
Xiaomi Pad 5 Pro, Bluetooth keyboard input invalid.

### ISSUE THREAD

**Issue by mp075496706** [rustdesk/rustdesk#8151]
### Bug Description

Android：xiaomi pad 5 pro
Rustdesk：1.2.3

PC：win10
Rustdek：1.2.3

Xiaomi Pad 5 Pro, Bluetooth keyboard input invalid.
My Xiaomi Pad 5 Pro is connected to the mouse and keyboard via Bluetooth. All mouse operations are normal without any problems.
However, there are some issues with the Bluetooth keyboard, such as typing, but the keys cannot be recognized.
I have also tried other remote software, such as Sunflower Remote Connection, and my Bluetooth mouse and keyboard are working properly without any issues with invalid buttons.

### How to Reproduce

None

### Expected Behavior

None

### Operating system(s) on local side and remote side

Android Pad -> Win10

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

None

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893

**Comment by mp075496706** [comment]
The latest discovery is that when I first connect to the computer using Xiaomi Pad 5 Pro, the keyboard input is invalid. No matter how hard I press the keys, the remotely controlled computer cannot type words.
Then, for testing purposes, I tried all the keys on the keyboard and found that when I pressed the Tab key, The element in the Rustdesk taskbar of Xiaomi Pad5 Pro has been selected, and pressing the Enter key will trigger a click event in the title bar like a mouse click operation. Then I created a new txt text file on my computer and tried to input some text. Surprisingly, the buttons worked!
So I tested it several times, from initially connecting to the keyboard and typing was invalid, to pressing Tab, then Enter, and then entering text in the txt file, and the keyboard was working!

I hope the above feedback can help you locate the problem!

**Comment by wingsolakiri** [comment]
I think this is same issue, so i written in here.
I have iPad Pro 11 inch (gen3), and tried with bluetooth keyboard and Magic Keyboard.
Both mouse is work, but with no luck, I don't have any key/button work on my Pad. (even try @mp075496706 method)
