### ISSUE TITLE
Erratic mouse scroll wheel behaviour in RustDesk GUI

### ISSUE THREAD

**Issue by xbyte99** [rustdesk/rustdesk#8152]
### Bug Description

The mouse wheel scrolling in the RustDesk main window has some pretty annoying behaviour for all list contents, like all Home tabs (recent, favorites etc) and Settings screen. The smaller the RustDesk window dimensions the worse the impact, because you have more contents which must be displayed as lists and lists becoming longer.

This bug has been with RustDesk pretty much from the beginning on.

Summary: Mouse scrolling directions get mixed up and content is skipped because a single scroll step jumps more than one page of content.

### How to Reproduce

When doing only mouse wheel downs until the end of a list:
- first mouse scroll down: 2 entries/lines down
- second mouse scroll down: 1+ entire page down (some missing content in between pages)
- consecutive mouse scroll down: 1+ entire page down (some missing content in between pages)
Depending on the length of the list it seems more content is skipped/missed. The longer the list, the more content is missed.

When changing direction in between it gets even worse and more confusing:
- first mouse scroll down: 2 entries/lines
- consecutive mouse scroll down: see above
- **mouse scroll up: depending on length of list between a few lines up to a page _down(!)_**
- consecutive mouse scroll up: 1+ entire page up (some missing content in between pages)

The same behaviour just in reverse order shows when starting with mouse wheel up (when at the end of a list)

### Expected Behavior

- adhere to Windows system settings (default 3 lines per scroll)
- do not jump too far so content is missed
- when changing directions, go in the desired direction

### Operating system(s) on local side and remote side

Windows 11 -> remote side irrelevant

### RustDesk Version(s) on local side and remote side

1.2.4 nightly 2024-05-26  -> remote side irrelevant

### Screenshots

Screenshot/video not suitable to demonstrate the erratic behaviour. The reproduction steps should be sufficient

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by KevinL2015** [comment]
If the remote device is vertical screen and the local device is horizontal screen, the same problem occurs in "scale original" mode

**Comment by xbyte99** [comment]
This but actually seems resolved and the collector #4367 can be updated
