### ISSUE TITLE
RustDesk can't control mouse cursor remotely using Flatpak

### ISSUE THREAD

**Issue by jose-rafael** [rustdesk/rustdesk#8154]
### Bug Description

I have 2 Linux Systems Fedora Kinoite 40 and Arch Linux with KDE Plasma 6, and both the mouse cursor doesn't control the guest's curotor, it's a blue dot, and it doesn't control anything, I only have the option to see what the guest can do!

### How to Reproduce

Use RustDeck in Flatpak on both host and guest system

### Expected Behavior

the Mouse cursor was supposed to work being able to control the remote PC

### Operating system(s) on local side and remote side

Arch Linux Plasma -> Fedora Kinoite 40; Fedora kinoite 40 -> Arch Linux KDE Plasma

### RustDesk Version(s) on local side and remote side

1.2.3  -> 1.2.3

### Screenshots

https://github.com/rustdesk/rustdesk/assets/36747560/db7f39b5-c365-47e8-a1ec-114ba253dc0a

**Comment by rustdesk** [comment]
fixed in nightly build
