### ISSUE TITLE
Pattern screen black on Android from PC

### ISSUE THREAD

**Issue by JaMoLpE88** [rustdesk/rustdesk#816]
Phone: Xiaomi MI 11T

Android:Miui 13.0.5

Lock: Pattern and Fingerprint

Share Screen Service: Enabled

Permissions: All open

Mobile Version: 1.1.10-1
PC Version: 1.1.9

Bug: When the phone is locked, if I enter remotely with the password, the phone wakes up perfectly, but when the unlock screen is displayed on the phone, only the black screen is seen on the remote terminal, while on the terminal the unlock screen is displayed with the pattern dots.
As soon as you enter the pattern or fingerprint on the phone, remotely it can be seen and controlled perfectly, but it is not possible to enter the pattern because the screen comes out black, so there is no way to be able to carry out an unattended session remotely.

Images:
1 - Screen locked when entering the phone while it is idle.
2 - Pattern unlock screen. On the phone it comes out to enter the pattern but on remote it comes out black.
3 - Unlocked screen and perfect and normal use.

![1 - locked](https://user-images.githubusercontent.com/47107967/174472238-4491f8cb-a74b-45fc-a6f5-92363d359d5d.jpg)
![2 - pattern screen](https://user-images.githubusercontent.com/47107967/174472239-5b87ce63-2e47-4830-9955-fd4ef9d64ce9.jpg)
![3 - unlocked](https://user-images.githubusercontent.com/47107967/174472242-a921ae58-c729-4ab6-b8e0-ac5acd8c4509.jpg)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/619

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/550

**Comment by JaMoLpE88** [comment]
> 

I don't see what is the relationship between that question and this issue.

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by xtyuns** [comment]
Here is a temporary solution for the root user
[Xposed-Disable-FLAG_SECURE](https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE#usage)

![Snipaste_2022-08-20_20-10-20](https://user-images.githubusercontent.com/41326335/185745770-ffd28536-02c9-42aa-85b3-3079f25b7abb.png)

**Comment by rustdesk** [comment]
> solution
Thanks

**Comment by rustdesk** [comment]
https://www.reddit.com/r/rustdesk/comments/10d3ym4/remote_desktop_is_offline_for_my_7_android/

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3893
