### ISSUE TITLE
Connection error - Key mismatch

### ISSUE THREAD

**Issue by anatom74** [rustdesk/rustdesk#8174]
### Bug Description

Yesterday it worked ok, but today I got a message:  "Connection error - Key mismatch".
I'm hosting own server on Synology NAS (docker)

### How to Reproduce

-

### Expected Behavior

Should establish connection

### Operating system(s) on local side and remote side

Windows -> windows

### RustDesk Version(s) on local side and remote side

1.2.3-1 ->  !.2.3-1

### Screenshots

no screenshot

**Comment by rustdesk** [comment]
#763
