### ISSUE TITLE
macOS Monterey - Screensharing is not working on virtualized machine (VM)

### ISSUE THREAD

**Issue by maveice** [rustdesk/rustdesk#819]
Scenario:
**Machine 1** (RustDesk session to be initiated from here): MacStudio with macOS Monterey installed and from which a new RustDesk session is initiated 
**Machine 2** (RustDesk) shall be monitored by Machine 1: VM with macOS Monterey installed on a VMware 7.03u environment 

While the session initiation process seems to work normally on Machine 2 the screen on Machine 1just says "Connected, waiting for screen ..." - after clicking "OK" the screen on Machine 1 closes and nothing happens. 

...

**What did you expect to happen instead?**

Session should be established as it also does with other VMs that are being hosted on same VM-environment (like Ubuntu with RustDesk installed). In this case everything is working just fine. 
...

**How did you install `RustDesk`?**

Rustdesk was installed form today's downloaded DMG-File for Mac ("rustdesk-1.1.9.dmg").

---

**RustDesk version and environment**

pls. see above

**Comment by itsharis** [comment]
I ran into this issue as well. Not sure why but i assume this happens because the virtual GPU does not support metal.

Passing in a GPU solves the issue for me. 

However it does send double key inputs which i will probably a different issue i will open later.

**Comment by rustdesk** [comment]
Have to say, we have no solution to fix this issue till now.

**Comment by rustdesk** [comment]
close to favor #1821
