### ISSUE TITLE
Wayland Display Authorization 

### ISSUE THREAD

**Issue by nmcbride** [rustdesk/rustdesk#8190]
### Bug Description

I connected to my machine from my android phone the  first time. Allowed the connection.

Phone said "Please select the screen to be shared."
I picked my horizontal one. I also have a smaller vertical one.

I was able to connect but the mouse wasn't aligned with the one on my phone and I could not see the remote mouse. So I really wasn't able to use it. Similar to this old one: https://github.com/rustdesk/rustdesk/issues/4288. I did notice that the mouse, even though on android showed moving across the whole screen, was only registering movement on part of the screen similar to the vertical resolution of my other monitor.

I disconnected to try again. Allowed the connection.

Phone said "Please select the screen to be shared."
This time however there is no popup on the remote to pick the display again.

Eventually the phone times out and raises a connection error. This seems to be similar to this one: https://github.com/rustdesk/rustdesk/issues/8164 that was closed 6 days ago tagged as "invalid". However, it seems to be similar, albeit different, ultimately coming down to wayland display authorization issues. For him, not being able to add a second display as he can't get the display authorization to show again and for me, not being able to connect a second time as the phone is waiting on the wayland display authorization which never happens on connections 2+.

### How to Reproduce

Go through the connection process twice to a modern wayland distro like Fedora. The first one works but the second (at least on the phone) will not work and wait forever for a display authorization dialog that never happens.

### Expected Behavior

I'd most likely expect a popup each time a connection is made to authorize a display or when a display is changed to one that hasn't been authorized for the current session. It'd also be nice if there was a way to set a default for unattended access when no one is on the remote.

### Operating system(s) on local side and remote side

android -> fedora

### RustDesk Version(s) on local side and remote side

1.2.3-2 -> 1.2.4

### Screenshots

Cannot get a screenshot that is applicable as display authorization window doesn't appear anymore on connection.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
