### ISSUE TITLE
Connection resets continually in version 1.2.4 with a custom client

### ISSUE THREAD

**Issue by NickCQMSRazer** [rustdesk/rustdesk#8193]
### Bug Description

When connected to the desktop using version 1.2.4, the client resets some TCP connection regularly, however if we replace the client that we are connecting to with version 1.2.3-2 the connections work fine (still using the same versions on the server and on the system we are connecting from).

### How to Reproduce

1. Install RustDesk Server Pro 1.3.5.

2. Set a default strategy with:

- Custom permissions, everything enabled **except** configuration modification
- Approve mode via password only
- Use a permanent password
- Hide connection management window
- Deny LAN discovery

3. Create a custom Windows client with:
- an msi installer 
- incoming connections, 
- disable settings, disable TCP listen port, disable user account
- enable a preset password

5. Create a custom Windows client with:
- outgoing connections
- disable address book, disable user account

6. Install the msi on computer A.
7. Run the other client on computer B.
8. Connect from computer B to computer A.
9. Connection resets every 10 seconds or so, when this happens one of the rustdesk processes on computer A seems to restart (memory drops and climbs again, but PID is the same)
10. Uninstall the client on computer A and replace it with a client from version 1.2.3-2 that has an appropriate string in the file name to ensure connection to the same server
11. Problem is gone

### Expected Behavior

A stable connection without connection resets is able to be achieved with an msi installer running using version 1.2.4

### Operating system(s) on local side and remote side

Windows 11 -> Windows 10 IoT

### RustDesk Version(s) on local side and remote side

1.2.4 -> 1.2.4

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/43527200/fb155d65-7f35-42f1-ba9e-f16ba5dac34e)
![image](https://github.com/rustdesk/rustdesk/assets/43527200/965f0198-b7d5-4549-9c4e-5f82c44ca82e)

**Comment by rustdesk** [comment]
This crashes because we have turned on hardware codecs in the custom client, it is still software codecs with 1.2.3. Could you try out build a new msi and run on A (controlled device)? I just upgraded custom client from 1.2.4 to 1.2.5 and fix some hardware codec problem.

**Comment by rustdesk** [comment]
Windows 10 IoT? How much ram on this machine? Could you show us what codec (you can display quality monitor and see it) used when crash?

![image](https://github.com/rustdesk/rustdesk/assets/71636191/a0e80fc8-68ac-4263-96f6-5298377ea0e1)

**Comment by samkingstoncr** [comment]
Thanks, will try the newer client today. Is there a way to pin or specify the version the custom client creates or will it pick whatever is the latest?

The machine we're connecting to has 4GB RAM and using VP9 codec. Works fine with no performance issues in the software renderer.

**Comment by NickCQMSRazer** [comment]
I can confirm that this appears to be fixed with the newer client.

**Comment by NickCQMSRazer** [comment]
It seems I was mistaken - sorry. After a bit of use today with 1.2.5 on the remote side the issue has reappeared with the exact same symptoms. I've tried changing between the codecs, reinstalling, rebooting, and restarting the service without any change to the behaviour. 

I'm not sure why it worked ok for a little while but appears to be broken again now.

**Comment by rustdesk** [comment]
How about vp8?

**Comment by NickCQMSRazer** [comment]
To clarify, @samkingstoncr is a colleague - we are working on this together.

* The remote is Windows 10 IoT Professional LTSC, much more fully featured than the standard Windows 10 IoT version.
* Our test system has 8GB RAM, but some of the intended remotes only have 4GB.

There appear to be two RustDesk processes running (renamed for internal use), one of them is consuming a very large amount of RAM. On every connection reset event, the RAM usage drops a bit and then increases to more than before, similarly it seems to be creating many more threads.

![image](https://github.com/rustdesk/rustdesk/assets/43527200/c78b3200-6859-40c3-b6fb-2ee638ea335f)

**Comment by rustdesk** [comment]
Will the Iot system kill the process if it comsumes memory too much?
Could you compare the memory usage of 1.2.5 and 1.2.3-2?

**Comment by NickCQMSRazer** [comment]
> Will the Iot system kill the process if it comsumes memory too much? Could you compare the memory usage of 1.2.5 and 1.2.3-2?

It runs like normal windows - no unexpected process management. I'll collect the logs and run up both tomorrow to help diagnose.

**Comment by NickCQMSRazer** [comment]
This issue seeems to be quite intermittent now and I'm having trouble reliably reproducing.

I have done a preliminary review of the log files and correlated the connection resets to the following lines in `C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\<RustDesk>\log\server\<RustDesk>_rCURRENT.log`

```[2024-05-30 23:38:07.465440 +00:00] DEBUG [src\server\connection.rs:3260] Start cm
[2024-05-30 23:38:07.472210 +00:00] ERROR [src\server\connection.rs:3275] Failed to run cm: Err(Failed to launch ["--cm"] with session id 1: The parameter is incorrect. (os error 87))
[2024-05-30 23:38:08.474168 +00:00] DEBUG [src\server\connection.rs:3260] Start cm
[2024-05-30 23:38:08.481333 +00:00] ERROR [src\server\connection.rs:3275] Failed to run cm: Err(Failed to launch ["--cm"] with session id 1: The parameter is incorrect. (os error 87))
[2024-05-30 23:38:09.481979 +00:00] DEBUG [src\server\connection.rs:3260] Start cm
[2024-05-30 23:38:09.488658 +00:00] ERROR [src\server\connection.rs:3275] Failed to run cm: Err(Failed to launch ["--cm"] with session id 1: The parameter is incorrect. (os error 87))
[2024-05-30 23:38:10.489756 +00:00] DEBUG [src\server\connection.rs:3260] Start cm```

I am will anonymise and post full logs when I get a chance.

**Comment by NickCQMSRazer** [comment]
BUMP - see logs on prior post.

**Comment by rustdesk** [comment]
@21pages follow up

**Comment by 21pages** [comment]
@NickCQMSRazer Could you install the following program at the controlled side? When the reset happens, there will be more logs in the same log file.
https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.2.6-x86_64-log-run-as-user.exe
BTW, 
* how many accounts are there on that computer? Do the accounts have administrator rights?
* Is there this log `No image, fall back to gdi` when connecting normally?

**Comment by NickCQMSRazer** [comment]
Thanks @21pages . 

1. There is only a single user account.
2. When the connection is working normally, the logs don't have much in them. When the issue is happening (most of the time) there is always the `No image, fall back to gdi` message shortly before all the `Failed to run cm:...` messages.  Below I have posted the tail of the current log which was showing the symptoms when I connected for a few minutes, but has been fine for almost 10 minutes now.
```
[2024-06-04 10:41:40.213240 +00:00] DEBUG [src\server\connection.rs:3260] Start cm
[2024-06-04 10:41:40.219590 +00:00] ERROR [src\server\connection.rs:3275] Failed to run cm: Err(Failed to launch ["--cm"] with session id 1: The parameter is incorrect. (os error 87))
[2024-06-04 10:41:41.220888 +00:00] DEBUG [src\server\connection.rs:3260] Start cm
[2024-06-04 10:41:41.227506 +00:00] ERROR [src\server\connection.rs:3275] Failed to run cm: Err(Failed to launch ["--cm"] with session id 1: The parameter is incorrect. (os error 87))
[2024-06-04 10:41:41.240401 +00:00] DEBUG [src\server\audio_service.rs:377] Audio Zero Gate Attack
[2024-06-04 10:41:42.228689 +00:00] DEBUG [src\server\connection.rs:3260] Start cm
[2024-06-04 10:44:36.215913 +00:00] INFO [src\server\video_service.rs:628] dxgi error, fall back to gdi: Kind(ConnectionReset)
[2024-06-04 10:47:01.767871 +00:00] DEBUG [src\common.rs:379] clipboard updated on host
[2024-06-04 10:48:01.693985 +00:00] DEBUG [src\rendezvous_mediator.rs:194] Latency of remote.****.com:21116: 62.494ms
[2024-06-04 10:50:24.619863 +00:00] INFO [src\common.rs:303] clipboard update found on host
```


I'll install the linked program on the controlled side and get back to you with the extra logs.



I'll

**Comment by 21pages** [comment]
Could you send me a log file which contains multiple normal connections to my email, `c3VuYm9lYXN5QGdtYWlsLmNvbQo=` (base64), don't forget to remove sever information like before.

**Comment by NickCQMSRazer** [comment]
> @NickCQMSRazer Could you install the following program at the controlled side? When the reset happens, there will be more logs in the same log file. https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.2.6-x86_64-log-run-as-user.exe 
> 

That executable worked fine and did not show any problems. See log below.
[rustdesk_rCURRENT_RunAsUser.log](https://github.com/user-attachments/files/15571173/rustdesk_rCURRENT_RunAsUser.log)

> Could you check whether every connection will fallback to gdi, dxgi is actually unavailable ?

I'm not sure how to check, I've provided the DirectX diagnostics tool output (dxdiag.exe) in the hope that this helps. If this isn't helpful, please provide further instructions.
[DxDiag.txt](https://github.com/user-attachments/files/15571257/DxDiag.txt)

**Comment by 21pages** [comment]
@NickCQMSRazer  Thanks for your feedback, according to the logs, `rustdesk-1.2.6-x86-64-log-run-as-user.exe` is not installed, it was installed in the previous log. Could you install it?

**Comment by NickCQMSRazer** [comment]
> @NickCQMSRazer Thanks for your feedback, according to the logs, `rustdesk-1.2.6-x86-64-log-run-as-user.exe` is not installed, it was installed in the previous log. Could you install it?

Sorry, here is a new log.

[RustDesk_rCURRENT_RunAsService.log](https://github.com/user-attachments/files/15571663/RustDesk_rCURRENT_RunAsService.log)

Some more information in case it helps: I've noticed that when I start explorer.exe the problem goes away (e.g. open a command prompt and type `start .`). This isn't a usable work-around for us, but maybe that extra information helps?

**Comment by 21pages** [comment]
Yes, probably you find the reason, `explorer.exe` is used for start cm when installed. If you reboot your system, there is not `explorer.exe` process int the task mananger?

**Comment by NickCQMSRazer** [comment]
> @NickCQMSRazer Yes, probably you have found the reason, explorer.exe is used to start cm when installed. If you reboot your system, there is no explorer.exe process in the task mananger?
@21pages we purposely do not start explorer.exe as we run our own in-house user interface. There is no explorer.exe process in task manager unless we explicitly start it.

https://learn.microsoft.com/en-us/windows/iot/iot-enterprise/customize/shell-launcher

This was not a problem with 1.2.3-2 - that version works fine.

I can run with the h264/h265 codecs, but the disconnects still happen.

**Comment by 21pages** [comment]
> I can run with the h264/h265 codecs, but the disconnects still happen.

If you start explorer.exe manually, will the disconnects happen?

**Comment by NickCQMSRazer** [comment]
> If you start explorer.exe manually, will the disconnects happen?

The disconnects stop once explorer.exe has been started manually.

**Comment by rustdesk** [comment]
> explorer.ex

@NickCQMSRazer could you confirm if there is `taskhost.exe` process your task manager?

**Comment by NickCQMSRazer** [comment]
>@NickCQMSRazer could you confirm if there is taskhost.exe, svchost.exe processes in your task manager?

Attached is the output from running `tasklist.exe`. Note that cmd.exe is only running so that I could run tasklist.exe.
[processes.txt](https://github.com/user-attachments/files/15754430/processes.txt)

**Comment by rustdesk** [comment]
Please try out the new client build, we had a fix for this, but file transfer may not work.

**Comment by NickCQMSRazer** [comment]
> Please try out the new client build, we had a fix for this, but file transfer window may not work in your case for the time being.

This seems to work much better now. We have observed the following:
* No more constant disconnections!
* When the client connection is established, our custom UI is automatically minimised. This is annoying, but ok. IT did not happen previously.
* File transfer works ok
* We sometimes get corrupted http responses when using the port forwarding feature. We will investigate further in case that is something specific to the devices we use on the network.
