### ISSUE TITLE
Rustdesk RPM package install 1.2.3 instead of 1.2.3-2

### ISSUE THREAD

**Issue by AlexisPPLIN** [rustdesk/rustdesk#8200]
### Bug Description

Hi,

I'm trying to install the latest version of RustDesk (1.2.3-2) on my Fedora machine and the RPM seems to install version `1.2.3` instead of `1.2.3-2`.

### How to Reproduce

1. Download latest RPM available : https://github.com/rustdesk/rustdesk/releases/download/1.2.3-2/rustdesk-1.2.3-2.x86_64.rpm

2. Check the `.rpm` hash and RPM info :

```shell
$ sha256sum rustdesk-1.2.3-2.x86_64.rpm 
bfd289fd6c29b4929e5fd89c65a35adf2eb7d0215c8f7d7295e88a53ff3fed4c  rustdesk-1.2.3-2.x86_64.rpm
$ rpm -qip rustdesk-1.2.3-2.x86_64.rpm 
Name        : rustdesk
Version     : 1.2.3
Release     : 0
Architecture: x86_64
Install Date: (not installed)
Group       : Unspecified
Size        : 64764286
License     : GPL-3.0
Signature   : (none)
Source RPM  : rustdesk-1.2.3-0.src.rpm
Build Date  : ven. 13 oct. 2023 13:46:08
Build Host  : 6815d1d13ee4
Summary     : RPM package
Description :
The best open-source remote desktop client software, written in Rust.
```

We see `Version     : 1.2.3`

3. Then we install the rpm using `dnf install rustdesk-1.2.3-2.x86_64.rpm`.
4. After opening RustDesk, in `Settings > About`, we see `Version : 1.2.3` :

![image](https://github.com/rustdesk/rustdesk/assets/82219937/890daf5d-d709-49a0-b929-49993d2ac989)

### Expected Behavior

The `1.2.3-2` RPM should install `1.2.3-2` version.

### Operating system(s) on local side and remote side

Fedora Linux 39 -> x

### RustDesk Version(s) on local side and remote side

1.2.3 -> x

### Screenshots

Already uploaded in "How to reproduce"

**Comment by rustdesk** [comment]
1.2.3-2 has only fix to windows, no for linux.
