### ISSUE TITLE
android 9 paste

### ISSUE THREAD

**Issue by alen978** [rustdesk/rustdesk#8203]
### Bug Description

android 9 to control other android 9

as u see, copy the text , then try to paste it to the controlled android 9, but failed. even if long press in the controlled android 9, failed.

### How to Reproduce

android 9 to control other android 9

### Expected Behavior

the text can be copied and pasted to the controlled android 9

### Operating system(s) on local side and remote side

android 9 to control other android 9

### RustDesk Version(s) on local side and remote side

1.2.3-2  

### Screenshots

![a1](https://github.com/rustdesk/rustdesk/assets/92972585/a6f8ba4e-5f93-4af3-ba9d-69a5659ade3d)
![a2](https://github.com/rustdesk/rustdesk/assets/92972585/75ecd7ce-e62a-40e9-aef1-4bff37bb21a2)
![a3](https://github.com/rustdesk/rustdesk/assets/92972585/c56988cd-28ab-4642-bbfa-3fa03f4f9bc3)

**Comment by rustdesk** [comment]
not  support yet, @21pages remove this.paste menu item

**Comment by alen978** [comment]
> not support yet, @21pages remove this paste menu item for controlling android

is there the plan to support it? if yes, when?
