### ISSUE TITLE
When I use 2 keys, it automatically disconnects

### ISSUE THREAD

**Issue by ljh740** [rustdesk/rustdesk#8209]
### Bug Description

eg: cmd+c cmd+v

### How to Reproduce

There is no path, and once you encounter it, you can only restart it.

### Expected Behavior

fix it

### Operating system(s) on local side and remote side

m1 mac -> intel mac

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/9330229/650d2cd3-bc66-4a3f-8da7-301a9d5880f3)
when i press cmd + any

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/tag/nightly
