### ISSUE TITLE
Keyboard not typing on remote machine

### ISSUE THREAD

**Issue by artyck** [rustdesk/rustdesk#8222]
### Bug Description

I just built the latest version available (release target), builds and runs. Only problem is typing not being reproduced on the remote machine.
Connection is established, the mouse works, seemingly everything is fine, except typing does not work (working on an up to date private server).
The old build (built on the same machine) i have from version 1.2 still works fine.
Any ideas on what i might be doing wrong?

### How to Reproduce

Build from git source latest version on windows 11.
Connect to another client typing does not work.

### Expected Behavior

Typing on the connecting side should reproduce on the receiving side.

### Operating system(s) on local side and remote side

Windows 10, 11 -> Windows 10, 11

### RustDesk Version(s) on local side and remote side

1.2.3-2 -> 1.2.3-2, 1.2

### Screenshots

Not applicable.

**Comment by rustdesk** [comment]
#763
