### ISSUE TITLE
Modify screen resolution issue

### ISSUE THREAD

**Issue by tzengshinfu** [rustdesk/rustdesk#8233]
### Bug Description

After changing the screen resolution,
the small screen overlaps with the large screen,
preventing full-screen display.
Additionally, when operating on the large screen,
the small screen will also show the corresponding actions.

### How to Reproduce

1. Connect to remote host.
2. Select "Display settings">"Resolution">"Fit local resolution" on the top menu.
3. Display anomaly.

### Expected Behavior

Normal display and operation.

### Operating system(s) on local side and remote side

Windows 10 19045.4291 -> Windows 10 22H2 19045.3031

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

![2024-06-01 12 25 47](https://github.com/rustdesk/rustdesk/assets/2170033/e69e920f-c3d4-48da-aaf0-a1fea1107895)
![a](https://github.com/rustdesk/rustdesk/assets/2170033/5ca6a70d-bc44-45b1-8907-0fec1af75a0d)

Display settings
![image_20240601_123739](https://github.com/rustdesk/rustdesk/assets/2170033/65af9a31-a6ca-4b9b-a70d-6a8d2d287f1b)
![image_20240601_123746](https://github.com/rustdesk/rustdesk/assets/2170033/0bfbc888-289a-42bc-b23e-34086bb37fac)
![image_20240601_123802](https://github.com/rustdesk/rustdesk/assets/2170033/0c75cac0-49f9-4de5-88f8-4eb51b781553)
![image_20240601_123809](https://github.com/rustdesk/rustdesk/assets/2170033/b7d86fd0-eb2f-4b92-a7c5-07dfe1eddb3f)

### Additional Context

local resolution: 1366 x 768
remote resolution: 1920 x 1080

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/tag/nightly please
