### ISSUE TITLE
mouse bug on windows after locking screen

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#824]
Google translation: After locking the screen and then entering the desktop, you will encounter clicking the left button of the mouse, and the start menu will pop up once, but the mouse is not on the start button, you need to press the left button and drag it around for a few times to return to normal~~
> 最近才开始用这个，体验感比 RDP 差了点，但整体还是不错的，很满意，有个小 Bug 在这里说下：锁屏之后再进入桌面，会遇到点一下鼠标左键，就弹一次开始菜单，而鼠标是不在开始键上的，需要按着左键到处拖几下才会恢复正常~~

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/tag/nightly try it out on both sides

**Comment by zuiyu1998** [comment]
i find that the bug  cannot be found in the latest version but the bug is esay found in the old version。 The possible reasons are that the old version will send CursorPosion on Connecting and alse send CursorPosion after locking screen.
we need check that the bug is existed on the latest version？

**Comment by TheBongStack** [comment]
I am new to open source contribution and just learned rust. Can i get assigned to solving this issue?

**Comment by zuiyu1998** [comment]
The bug is not find in the version.
