### ISSUE TITLE
Pop OS 22.04

### ISSUE THREAD

**Issue by eiol** [rustdesk/rustdesk#825]
**Describe the bug you encountered:**
Unable to install RustDesk in POPOS

`Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'rustdesk' instead of './rustdesk-1.1.9.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
rustdesk : Depends: pulseaudio
E: Unable to correct problems, you have held broken packages.`

cannot install pulseaudio on Pop
Any alternative for installation?
...

**What did you expect to happen instead?**
Not install
...

**How did you install `RustDesk`?**

http://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9.deb
---

**RustDesk version and environment**

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/559

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3203
