### ISSUE TITLE
Key mismatch on self built server

### ISSUE THREAD

**Issue by homuraLan** [rustdesk/rustdesk#8255]
### Bug Description

When I applied an empty key on a Windows 11 client, even if I later changed the correct key or deleted and reconfigured all the Windows 11 Rustdesk client files, there was still a key mismatch error，But another Windows 11 client can control it

### How to Reproduce

As above

### Expected Behavior

normal

### Operating system(s) on local side and remote side

Windows 11 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.5

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/96775034/0d0f28a3-c740-4eec-83ce-4c6000204ee9)

**Comment by rustdesk** [comment]
#763
