### ISSUE TITLE
After a fresh start, only a wallpaper is shown and nothing else.

### ISSUE THREAD

**Issue by hypgfrch** [rustdesk/rustdesk#8256]
### Bug Description

After a fresh start, only a wallpaper is shown and nothing else.

### How to Reproduce

(no information)

### Expected Behavior

The standard Rustdesk windows

### Operating system(s) on local side and remote side

Windows 8

### RustDesk Version(s) on local side and remote side

1.2.3.2

### Screenshots

---

### Additional Context

---

**Comment by rustdesk** [comment]
#763
