### ISSUE TITLE
Corruption on Wayland on Fedora 40 KDE Spin

### ISSUE THREAD

**Issue by Wave6677** [rustdesk/rustdesk#8260]
### Bug Description

When using RustDesk (as a streaming client) on Fedora 40 KDE Spin, the video is completely corrupted when connecting to it from a receiving client (Android rust desk, or remoting in from the same machine for example). The issue is fixed when using X11. The issue is apparent on both .rpm and flatpak. I could not get the app image to open correctly.

### How to Reproduce

Download Rustdesk on Fedora 40 KDE using Wayland
Launch the app, and connect using the ID provided by the app from another device

### Expected Behavior

A non corrupted video

### Operating system(s) on local side and remote side

Android -> Fedora 40 KDE Wayland or Fedora 40 KDE -> Fedora 40 KDE

### RustDesk Version(s) on local side and remote side

1.2.3-2 -> 1.2.3-0

### Screenshots

![Screenshot_20240604_113256](https://github.com/rustdesk/rustdesk/assets/86343914/10685c5d-6398-4826-9b47-0721abf9fd38)

### Additional Context

I am realizing I did not test using the default server as I am self hosting. I will try the default shortly and will update this if there is a difference. I will remove this message if it doesn't make a difference

**Comment by rustdesk** [comment]
fixed in nightly build
