### ISSUE TITLE
overflow when run cargo

### ISSUE THREAD

**Issue by am1752** [rustdesk/rustdesk#8263]
### Bug Description

[2024-06-05T08:05:51Z INFO  librustdesk::core_main] main start args:[]
thread 'main' panicked at library\core\src\panicking.rs:156:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:645
   1: core::panicking::panic_nounwind_fmt::runtime
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:110
   2: core::panicking::panic_nounwind_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:123
   3: core::panicking::panic_nounwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:156
   4: core::slice::raw::from_raw_parts::precondition_check
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\intrinsics.rs:2799
   5: core::slice::raw::from_raw_parts<sciter::capi::scvalue::VALUE>
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\slice\raw.rs:98
   6: sciter::value::Value::unpack_from
             at C:\Users\CORE\.cargo\git\checkouts\rust-sciter-06aa50f9c0fcf3d6\fab913b\src\value.rs:563
   7: sciter::eventhandler::process_events
             at C:\Users\CORE\.cargo\git\checkouts\rust-sciter-06aa50f9c0fcf3d6\fab913b\src\eventhandler.rs:208
   8: sciter::eventhandler::_event_handler_window_proc<librustdesk::ui::UI>
             at C:\Users\CORE\.cargo\git\checkouts\rust-sciter-06aa50f9c0fcf3d6\fab913b\src\eventhandler.rs:54
   9: <unknown>
  10: SciterAPI
  11: SciterAPI
  12: SciterAPI
  13: SciterAPI
  14: SciterAPI
  15: SciterAPI
  16: SciterAPI
  17: SciterAPI
  18: SciterAPI
  19: SciterAPI
  20: SciterAPI
  21: SciterAPI
  22: SciterAPI
  23: SciterAPI
  24: SciterAPI
  25: SciterAPI
  26: SciterAPI
  27: SciterAPI
  28: SciterAPI
  29: SciterAPI
  30: SciterAPI
  31: <unknown>
  32: sciter::host::Host::load_file
             at C:\Users\CORE\.cargo\git\checkouts\rust-sciter-06aa50f9c0fcf3d6\fab913b\src\host.rs:275
  33: sciter::window::Window::load_file
             at C:\Users\CORE\.cargo\git\checkouts\rust-sciter-06aa50f9c0fcf3d6\fab913b\src\window.rs:281
  34: librustdesk::ui::start
             at .\src\ui.rs:172
  35: rustdesk::main
             at .\src\main.rs:35
  36: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\ops\function.rs:250
  37: core::hint::black_box
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\hint.rs:337
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread caused non-unwinding panic. aborting.
error: process didn't exit successfully: `target\debug\rustdesk.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)

### How to Reproduce

cargo run

### Expected Behavior

when i command "cargo run"

i receive message "overflow"

how can i fix it?

i run on windows 10

### Operating system(s) on local side and remote side

win10

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![1](https://github.com/rustdesk/rustdesk/assets/60413231/76a97b3c-ff00-40f7-91f5-ac636c3cd48f)

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
use rustc <= 1.77, 1.78 introduce an ABI change, https://blog.rust-lang.org/2024/03/30/i128-layout-update.html

Or you can help me modify https://github.com/open-trade/rust-sciter
