### ISSUE TITLE
Typing input issues, win11->mac by IP. Long press key 10 seconds, remote outputs 10 seconds. like delay or key cache issue

### ISSUE THREAD

**Issue by terrybao** [rustdesk/rustdesk#8269]
### Bug Description

Typing input issues, from win11 to mac by IP, try long press any key 10 seconds in win11, and then you will see the remote outputs 10 seconds.  it's very bad input for editing text in remote pc.  

### How to Reproduce

restdesk version 1.2.6,
Directly connect to mac x86 ventura from windows 11 by IP 
Try long press and key 10 seconds (or much more seconds) in win11
And then you see this issue, the vscode in my Mac will continue to input characters for 10 seconds, which is a delay, more like caching (key buffer?). This problem directly leads to me frequently making input errors.

### Expected Behavior

The normal situation should be: after continuously holding down any button for 10 or 100 seconds, when the key is up, the input should immediately stop.
Whether it is a regular key or other functional keys such as ctrl/alt/option

### Operating system(s) on local side and remote side

Windows11 -> osx x86 ventura

### RustDesk Version(s) on local side and remote side

1.2.6 -> 1.2.6

### Screenshots

![rustdesk_keyboard](https://github.com/rustdesk/rustdesk/assets/17898957/32053273-ffee-4103-accd-4fc1f135c860)

### Additional Context

This is probably a keyboard input cache issue, which has a significant impact on the function keys. Sometimes, there may be an unexpected shortcut operation, which is likely due to pressing ctrl/alt/option for too long, causing the wrong operation to be triggered.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367
