### ISSUE TITLE
Android Rename Option has gone...

### ISSUE THREAD

**Issue by blasiusx** [rustdesk/rustdesk#8274]
### Bug Description

Devices with Android 10-14: Since Rustdesk 1.2.5 (also in the nightlys, and also 1.2.6) it is no longer possible to rename the individual connections to the other clients. The "Rename" option simply no longer exists.
In Windows all is okay. 

### How to Reproduce

You have to tap the three dots on the right of a recent connection and a submenu will appear. The "Rename" option is missing here.

### Expected Behavior

I except, if i press and hold the Connection, i could see the "rename" Button. 

### Operating system(s) on local side and remote side

Android 10-13

### RustDesk Version(s) on local side and remote side

1.2.5<>1.2.5 or 1.2.5<>1.2.6

### Screenshots

![Screenshot_20240606-143245](https://github.com/rustdesk/rustdesk/assets/114309961/4d925b5d-8f32-412b-a53b-5cf386d97720)

**Comment by rustdesk** [comment]
Thanks

**Comment by rustdesk** [comment]
Close as fix merged

**Comment by blasiusx** [comment]
Thank you!!
