### ISSUE TITLE
Restart remote PC 

### ISSUE THREAD

**Issue by matth94** [rustdesk/rustdesk#828]
Hello, 
Can we have the possibility to restart a remote PC and resume control automatically after restarting it?
Thanks

**Comment by rustdesk** [comment]
?

**Comment by Steath** [comment]
You can already do that, at least it worked on a Win10 Remote Client (installed, not portable)  when just restarting via windows.

**Comment by 21pages** [comment]
You can use system reboot on windows and linux. Restart as follows:
1. install rustdesk service
2. make the network connect automatically
3. system reboot
4. reconnect with permanent password (You can choose to remember password when connecting before)
5. you can see the lock screen

Teamviewer has a restart buttton. When the controlled end is online, it will prompt you to reconnect without entering a password. Not having to remember the password is the only saving step.

**Comment by rustdesk** [comment]
I guess "Restart remote PC" should be mainly for some case controlled side can not be remoted with screen capturing. screen capturing requires too much resources, the controlled  side has no resources when it is too busy or having some unknown problems.

**Comment by 21pages** [comment]
|                                   | teamviewer                               | anydesk                                  | todesk                                   |
| --------------------------------- | ---------------------------------------- | ---------------------------------------- | ---------------------------------------- |
| Option reboot in safe mode        | Y                                        | Y                                        | N                                        |
| Option log out                    | Y                                        | N                                        | Y                                        |
| reboot permission                 | confirmation dialog                      | Permission button                        | N                                        |
| After click reboot button         | 1. Pop up a confirmation dialog on the controlled end <br/>2. If yes, pop up a confirmation dialog on the control side on whether want to automatically reconnect<br/> | Pop up a waiting dialog with a cancel button | pop up a confirmation dialog which shows that the connection was interrupted unexpectedly, reconnecting.... like a network interrupt |
| When the controlled end is online | If choose yes in the previous step, pop up a confirmation dialog on whether to reconnect | If the cancel button is not clicked,  it will reconnect automatically | reconnect automatically if  If the message dialog is not closed |


I think the anydesk's method is the best, it's procedure is more simple than teamviewer and is more explicit than todesk

**Comment by rustdesk** [comment]
> anydesk's

Agree
