### ISSUE TITLE
CustomClient OverwriteSettings

### ISSUE THREAD

**Issue by devNull2and1** [rustdesk/rustdesk#8299]
### Bug Description

Installed newest Docker for Console and Relay.
Installed newest Client Custom Build.
Settings configured from https://rustdesk.com/docs/en/self-host/client-configuration/advanced-settings/
```
access-mode=custom
enable-keyboard=Y
enable-clipboard=Y
enable-file-transfer=Y
enable-audio=N
enable-tunnel=Y
enable-remote-restart=Y
enable-record-session=Y
enable-block-input=Y
allow-remote-config-modification=Y
enable-lan-discovery=Y
direct-server=Y
direct-access-port=21118
approve-mode=password-click
theme=dark
lang=default
allow-remove-wallpaper=y
enable-open-new-connections-in-tabs=Y
show-monitors-toolbar=Y
collapse-toolbar=Y
show-remote-cursor=Y
follow-remote-cursor=Y
disable-audio=Y
enable-file-copy-paste=Y
disable-clipboard=N
view-style=adaptive
view-only=N
```

When i connect to a client, the client must allow everything. but overwrite settings should already allow everything!?
Nothing is allowed!

### How to Reproduce

Installe newest Docker for Console and Relay.
Installe newest Client Custom Build.
Take this settings for overwrite.
```
access-mode=custom
enable-keyboard=Y
enable-clipboard=Y
enable-file-transfer=Y
enable-audio=N
enable-tunnel=Y
enable-remote-restart=Y
enable-record-session=Y
enable-block-input=Y
allow-remote-config-modification=Y
enable-lan-discovery=Y
direct-server=Y
direct-access-port=21118
approve-mode=password-click
theme=dark
lang=default
allow-remove-wallpaper=y
enable-open-new-connections-in-tabs=Y
show-monitors-toolbar=Y
collapse-toolbar=Y
show-remote-cursor=Y
follow-remote-cursor=Y
disable-audio=Y
enable-file-copy-paste=Y
disable-clipboard=N
view-style=adaptive
view-only=N
```

### Expected Behavior

Permissions should be allowed with overwrite settings!!!!!!!!!

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.2.5->1.2.5

### Screenshots

wrong as it is:
![image](https://github.com/rustdesk/rustdesk/assets/144108510/24a5651f-abbe-4689-a409-ad9b84e49e5b)

correct as it should be:
![image](https://github.com/rustdesk/rustdesk/assets/144108510/9fa7e353-d5ba-4cdf-889b-55aabd881a6b)

**Comment by devNull2and1** [comment]
The advanced settings documentation does not clearly state how this is regulated. In the settings it says everywhere, after the first connection. Maybe you think that should or has to be like that for security reasons.

Put yourself in the following situation: you have the worst possible user on the other end who is not able to set the permissions in the window because he is simply too stupid to understand what the symbols mean.

For this to happen, it should, can and must be possible to overwrite the settings.

**Comment by rustdesk** [comment]
Thank you, please try out new custom client, we had a fix for this.
