### ISSUE TITLE
win10->win7，keyboard works, but mouse not

### ISSUE THREAD

**Issue by Joe192168** [rustdesk/rustdesk#83]
both side：rustdesk-1.1.6.exe

**Comment by rustdesk** [comment]
If you run controlled side without installation, please install it.

**Comment by rustdesk** [comment]
What's your win7 update version?

**Comment by Joe192168** [comment]
> What's your win7 update version?

win7的版本：
![image](https://user-images.githubusercontent.com/13096678/122540491-46998680-d05b-11eb-9c3b-f41c6232a6eb.png)

**Comment by Joe192168** [comment]
> If you run controlled side without installation, please install it.

肯定是安装了，才远程访问的啊

**Comment by rustdesk** [comment]
Win10 -> Win7
![image](https://user-images.githubusercontent.com/71636191/124698333-3cacca00-df1b-11eb-8596-64393fbd4dc4.png)

**Comment by rustdesk** [comment]
Compatibility issue on some Win7

**Comment by rustdesk** [comment]
Try out latest version please.
