### ISSUE TITLE
Keypair mismatch

### ISSUE THREAD

**Issue by IndiGP** [rustdesk/rustdesk#8306]
### Bug Description

Hello,
we are trying to connect to rustdesk server in docker container with latest tag. Always if we try to connect, we will get reset with error "keypair mismatch". If I use older version tag 1.1.10-3 its working fine.

Config (running - "latest" tag not working):
version: '3'

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:1.1.10-3
    command: hbbs -r **DOMAIN**:21117
    environment:
      - "ALWAYS_USE_RELAY=N"
      - "RELAY=**DOMAIN**:21117"
      - "ENCRYPTED_ONLY=1"
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: always

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:1.1.10-3
    command: hbbr
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    restart: always

### How to Reproduce

Retry to connect with container via latest tag.

### Expected Behavior

Connect as usual to remote desktop.

### Operating system(s) on local side and remote side

Windows 10 <- Linux Docker Container -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3-2

### Screenshots

-

**Comment by rustdesk** [comment]
#763
