### ISSUE TITLE
remote.css

### ISSUE THREAD

**Issue by am1752** [rustdesk/rustdesk#8310]
### Bug Description

table#remote-folder-view {
    context-menu: selector(menu#remote-folder-view);
}

table#local-folder-view {
    context-menu: selector(menu#local-folder-view);
}

where local-folder-view?

### How to Reproduce

css error

### Expected Behavior

design is not working properly

### Operating system(s) on local side and remote side

win10

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

local-folder-view

**Comment by rustdesk** [comment]
we favor flutter now
