### ISSUE TITLE
Software update routine does not detect new version

### ISSUE THREAD

**Issue by aeltorio** [rustdesk/rustdesk#8314]
### Bug Description

Software update does not detect new version

### How to Reproduce

When a new version is available at https://github.com/rustdesk/rustdesk/releases/latest, GitHub redirects to https://github.com/rustdesk/rustdesk/releases/tag/1.2.3-2.  
The function common::check_software_update_() (located in src/common.rs) parses the redirected URL to extract the version number 1.2.3-2.

Here’s the relevant Rust code:

```rust
pub fn check_software_update() {
    std::thread::spawn(move || allow_err!(check_software_update_()));
}

#[tokio::main(flavor = "current_thread")]
async fn check_software_update_() -> hbb_common::ResultType<()> {
    let url = "https://github.com/rustdesk/rustdesk/releases/latest";
    let latest_release_response = create_http_client_async().get(url).send().await?;
    let latest_release_version = latest_release_response
        .url()
        .path()
        .rsplit('/')
        .next()
        .unwrap_or_default();

    let response_url = latest_release_response.url().to_string();

    if get_version_number(&latest_release_version) > get_version_number(crate::VERSION) {
        *SOFTWARE_UPDATE_URL.lock().unwrap() = response_url;
    }
    Ok(())
}
```

The issue arises because this function is called via `InitState()` in *flutter/lib/desktop/pages/desktop_home_page.dart* and `main_get_software_update_url()` in *src/flutter_ffi.rs*. The function `crate::common::check_software_update()` returns before the version is read because `check_software_update_()` is spawned.

Here’s the relevant Rust code:

```rust
pub fn main_get_software_update_url() -> String {
    if get_local_option("enable-check-update".to_string()) != "N" {
        crate::common::check_software_update();
    }
    crate::common::SOFTWARE_UPDATE_URL.lock().unwrap().clone()
}
```

### Expected Behavior

wait for thread `check_software_update_()` to end

### Operating system(s) on local side and remote side

OSX -> Linux amd64

### RustDesk Version(s) on local side and remote side

1.2.6 -> 1.3

### Screenshots

n/a

**Comment by rustdesk** [comment]
1.2.6 is pre-release.
