### ISSUE TITLE
About: Allow IP Direct Access

### ISSUE THREAD

**Issue by CoireLen** [rustdesk/rustdesk#832]
I turned on Allow IP Direct Access from the menu on the main window.
So as long as port 21118 is mapped to the public network, I can access it through the public network ip?
Or can I connect peer-to-peer without going through the server to achieve a better link effect?

我开启了允许IP直接访问这个功能。
所以只要将端口21118映射到公网，我就可以通过公网ip来进行访问？
还是说我可以点对点不通过服务器进行连接以达到更好的链接效果？

**Comment by cloudetel** [comment]
You can enter static ip in place of id and then connect you will get the direct ip access
