### ISSUE TITLE
Auto recording to MP4 when connecting

### ISSUE THREAD

**Issue by bilogic** [rustdesk/rustdesk#833]
Possible to perform auto recording of the session to MP4 or something?

Ideally on the server, otherwise on the client that is controlling the remote desktop.

Thank you.

**Comment by 21pages** [comment]
File: Teamviewer and Anydesk both use unique formats, '.tvs' or '.anydesk', and they are stored at the control end.
Permission: Teamviewer via confirm messagebox, anydesk via permission button
Direction: Teamviewer can only record outgoing sessions after session start, Anydesk can choose to record incoming/outgoing sessions at the session start automatically.

**Comment by rustdesk** [comment]
We follow AnyDesk

**Comment by 21pages** [comment]
Save encoded video frames and audio frames to file? Each frame contains its own size, format and duration information.

**Comment by bilogic** [comment]
I know it's easy to describe, but much harder to code, however:

In my experience, modern remote desktops use video/audio streaming, so this feature is about further piping the streams to an encoder and having it persist to a file. By reusing code from open standards, MKV/MP4 etc, it should make this feature easier to implement.

**Comment by 21pages** [comment]
If using standard format,  I don't konw how to implement these things:
1. Muxing 264 files to mp4 files can be done, but I don't know how to mux 264 frames to mp4 files in real time.
2. RustDesk supports switching video formats in real time, I don't know whether it is possible to mux different video formats into the same mp4 file
If using custom format, we can decode different video frames with different decoders.
Audio and video synchronization will not be easy in these two ways.

**Comment by rustdesk** [comment]
standard format for sure.

**Comment by 21pages** [comment]
> standard format for sure.
ok

**Comment by rustdesk** [comment]
reuse the capture, no need to reuse the encoder, because recording must be high image quality.

**Comment by 21pages** [comment]
Yes, it will be easier

**Comment by rustdesk** [comment]
Check AnyDesk first. To verify it is different encoder, you can set low quality, and see if the recorded file also low quality.

**Comment by rustdesk** [comment]
Recording should be in different thread without affecting live streaming, performance is important. But I do not know if the CPU + GPU can afford two encoder.

**Comment by bilogic** [comment]
Teamviewer seems to do it this way:

1. Record the video/audio stream as-is first into `.tvs` first
2. Allow user to perform 2nd step to convert `.tvs` into `.avi`, but this part is very buggy, some encoders work, some don't and only `.avi` is reliable, MP4 and others are not.

**Comment by rustdesk** [comment]
For vpx, we can use webm format.

**Comment by rustdesk** [comment]
webm is popular enough.

**Comment by 21pages** [comment]
> Check AnyDesk first. To verify it is different encoder, you can set low quality, and see if the recorded file also low quality.

The file sizes on both sides are basically the same, possibly the same encoder

**Comment by rustdesk** [comment]
Can verify with cpu/gpu usage also.

**Comment by 21pages** [comment]
Cannot draw a definite conclusion

**Comment by rustdesk** [comment]
#1577
