### ISSUE TITLE
Using mobile actions makes rustdesk crash

### ISSUE THREAD

**Issue by jmpangilinan** [rustdesk/rustdesk#8336]
### Bug Description

Sometimes, when I remote my android device and use mobile actions (the three dots), and when it does not response to the click of the button, rustdesk crashes, using nightly build 1.2.6, tested Android 12 and 13

### How to Reproduce

Use mobile actions (three dots)

### Expected Behavior

Should show opened apps

### Operating system(s) on local side and remote side

Windows 10 -> Android 12 and 13

### RustDesk Version(s) on local side and remote side

1.2.6 -> 1.2.6

### Screenshots

Will upload later

### Additional Context

None

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
close since no  sceernshot
