### ISSUE TITLE
sciter  在  load_file 的时候报错  

### ISSUE THREAD

**Issue by anan1213095357** [rustdesk/rustdesk#8337]
### Bug Description

 println!(
        "file://{}/src/ui/{}",
        std::env::current_dir()
            .map(|c| c.display().to_string())
            .unwrap_or_else(|_| "".to_string()),
        page
    );

    frame.load_file(&format!(
        "file://{}/src/ui/{}",
        std::env::current_dir()
            .map(|c| c.display().to_string())
            .unwrap_or("".to_owned()),
        page
    ));

我这里打印的结果是 file://E:\rustdesk/src/ui/index.html  这个路径是存在的  我如果把  file://  中的  // 去掉 file:E:\rustdesk/src/ui/index.html   这样虽然可以用  但是 common.tis   和 common.css 都无法加载

### How to Reproduce

null

### Expected Behavior

这个虽然是个小问题，但是对与不会 的人来说根本 没办法解决。  我在  Discord  提问根本得不到回复 ，现在只能来这里提问了。

### Operating system(s) on local side and remote side

win11

### RustDesk Version(s) on local side and remote side

最新的

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/43770875/6953f024-5bd4-46d1-b0c7-878fcbff26c1)

**Comment by rustdesk** [comment]
#763
