### ISSUE TITLE
    frame.load_file(&format!(         "file://{}/src/ui/{}",         std::env::current_dir()             .map(|c| c.display().to_string())             .unwrap_or("".to_owned()),         page     ));

### ISSUE THREAD

**Issue by anan1213095357** [rustdesk/rustdesk#8339]
### Bug Description

    frame.load_file(&format!(
        "file://{}/src/ui/{}",
        std::env::current_dir()
            .map(|c| c.display().to_string())
            .unwrap_or("".to_owned()),
        page
    ));

### How to Reproduce

    frame.load_file(&format!(
        "file://{}/src/ui/{}",
        std::env::current_dir()
            .map(|c| c.display().to_string())
            .unwrap_or("".to_owned()),
        page
    ));

### Expected Behavior

    frame.load_file(&format!(
        "file://{}/src/ui/{}",
        std::env::current_dir()
            .map(|c| c.display().to_string())
            .unwrap_or("".to_owned()),
        page
    ));

### Operating system(s) on local side and remote side

win11

### RustDesk Version(s) on local side and remote side

最新的

### Screenshots

    frame.load_file(&format!(
        "file://{}/src/ui/{}",
        std::env::current_dir()
            .map(|c| c.display().to_string())
            .unwrap_or("".to_owned()),
        page
    ));

**Comment by rustdesk** [comment]
#763
