### ISSUE TITLE
Build Failed 

### ISSUE THREAD

**Issue by ITSOFTNEPAL** [rustdesk/rustdesk#8360]
### Bug Description

error: failed to run custom build command for `pam-sys v1.0.0-alpha4`

Caused by:
  process didn't exit successfully: `/home/omar/Documents/rustdesk-master/target/debug/build/pam-sys-2ef6c09477dfda74/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=pam
  cargo:rustc-link-lib=pam_misc
  cargo:rerun-if-changed=wrapper.h

  --- stderr
  wrapper.h:1:10: fatal error: 'security/pam_appl.h' file not found
  wrapper.h:1:10: fatal error: 'security/pam_appl.h' file not found, err: true
  thread 'main' panicked at /home/omar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pam-sys-1.0.0-alpha4/build.rs:69:10:
  Unable to generate bindings: ()
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

### How to Reproduce

 VCPKG_ROOT=$HOME/vcpkg cargo run

### Expected Behavior

Build of rustdesk

### Operating system(s) on local side and remote side

Zorin OS

### RustDesk Version(s) on local side and remote side

latest

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/170808392/58cca4e8-4120-4544-9425-1952ecaa427c)

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
https://discord.com/invite/nDceKgxnkV build channel
