### ISSUE TITLE
German Keymap / QWERTZ Layout is not working 

### ISSUE THREAD

**Issue by geraldurbas** [rustdesk/rustdesk#8361]
### Bug Description

German Keyboard is not working as expected

### How to Reproduce

Install Lubuntu 22.04.2 (ex. in a virtual proxmox environment)
Via VNC German key are working correct,
but in Rustdesk not.

Additonal info:
Lubuntu 20.04 works as expected.

### Expected Behavior

Working Germans special chars (like öäü)

### Operating system(s) on local side and remote side

Windows 10 w. Rustdesk 1.1.9 > Linux Lubuntu w. Rustdesk 1.2.3

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/121263/85a0dda4-3b40-426c-a903-9fb55c56ff5c)

### Additional Context

Try a nightly / unstable and report

**Comment by geraldurbas** [comment]
Tried some combinations.
It may be a problem with Ubuntu (Lubuntu Flavor) 22.04.4 LTS (Jammy Jellyfish)

**Comment by rustdesk** [comment]
nightly！

**Comment by 21pages** [comment]
Can you please confirm whether it is related to the hardware codec option again?

When the keyboard of the controlled side is not German, `üöä` is shown as `';[`

![8cbf46a20753395ade7878c00038b38](https://github.com/rustdesk/rustdesk/assets/14891774/dd88d1b6-e323-4ba1-8475-482196731b9f)
