### ISSUE TITLE
No Cursors in VirtualBox

### ISSUE THREAD

**Issue by VitaliyAT** [rustdesk/rustdesk#8369]
### Bug Description

1st PC (operator here) connected to 2nd PC (to whom connection was made). 2nd PC run in VirtualBox (can't check it somewhere else, possible that on analogs of VB too) Tested on both Win10 PC's - possible that it's independent problem from OS.
After few seconds of operator doing something all mouse coursosrs gone and stay not visible. So 2nd PC don't see what 1st PC doing on it, where is operatior's mouse is.

### How to Reproduce

Just up this connection as said higher.

### Expected Behavior

2nd PC should see what 1st PC do and see mouse cursor.

### Operating system(s) on local side and remote side

Win10 -> Win10 in VB

### RustDesk Version(s) on local side and remote side

1.2.3-2

**Comment by rustdesk** [comment]
traced by https://github.com/rustdesk/rustdesk/issues/4356
