### ISSUE TITLE
Rustdesk Running crash in macos

### ISSUE THREAD

**Issue by remloyal** [rustdesk/rustdesk#8379]
### Bug Description

After installing Rustdesk on Macos, remote connections can be used normally without the need for a self built server. However, when I try to use a self built server and enter the ID server, the application crashes,

![image](https://github.com/rustdesk/rustdesk/assets/93071492/2720a62d-945e-4adc-8b41-6405576d2549)

### How to Reproduce

Chip: AMD 4800H
Version: MacOS 14.2.1
Architecture: x86_64

After installing Rustdesk, when entering the ID server, the application will crash

### Expected Behavior

Self built service information should be able to be input normally

### Operating system(s) on local side and remote side

macos 14.2.1

### RustDesk Version(s) on local side and remote side

1.2.5

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/93071492/4437efc9-44f9-406a-9960-4d4c92a9464a)

**Comment by remloyal** [comment]
[logo.txt](https://github.com/user-attachments/files/15861313/logo.txt)
This is my application crash log

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/discussions/7766
