### ISSUE TITLE
How to forcefully change RustDesk client ID

### ISSUE THREAD

**Issue by givbra** [rustdesk/rustdesk#838]
Hi, RustDesk Team!

Take for example we have a situation of 20 exactly the same personal computers in a work/school room. We install OS Windows 10, drivers, programs, full install of RustDesk 1.1.9, make lots of changes and configurations and then apply the same image to the rest of the PCs (to save time and resources) ... How exactly to change the ID of every of the cloned PCs (before or after that), because after imaging every one of them is having the same ID and pass ... In Teamviewer after cloning one PC to another it somehow finds out the hardware have changed (even a little bit - new CPU, SSD, Mainboard serial numbers) and therefore changes ID automatically, too ... In Anydesk if you delete C:\programdata\Anydesk folder before cloning and then after applying the image to the rest of the PCs and when starting each one we have different IDs, if you don't delete C:\programdata\Anydesk - ID is the same to all of the PCs ... I have experimented to delete C:\Users\User\AppData\Roaming\RustDesk folder before or after cloning (stopping RustDesk service first) with no success - always the same ID and pass ...

What to do in these cases?!

**Comment by rustdesk** [comment]
Please group your feature requests to one please.

**Comment by rustdesk** [comment]
``

**Comment by givbra** [comment]
Please, any idea or instructions how to do it now, with the latest version of 1.1.9 for Windows, because I need to know how to change ID soon ...

**Comment by K2M74** [comment]
%AppData%\RustDesk\config\RustDesk.toml
Manually change the first line

**Comment by imtrobin** [comment]
I have the same issue, I open the RustDesk.toml, it doesn't have a id parameter.

**Comment by severach** [comment]
For Linux this file is `/root/.config/rustdesk/RustDesk.toml`. You may also need to delete `/etc/machine-id` and reboot to generate another one.

**Comment by Arrmm** [comment]
> For Linux this file is `/root/.config/rustdesk/RustDesk.toml`. You may also need to delete `/etc/machine-id` and reboot to generate another one.

Does anyone know the directory for Android?  I thought it is \sdcard\Android\data\com.carriez.flutter_hbb but the folder is empty

**Comment by bilogic** [comment]
There should be some kind of auto deconflict, especially if we are dealing with cloned VMs have rustdesk preinstalled

**Comment by jfoust2** [comment]
I recently cloned a Windows 10 PC, p2p.  No sysprep, so two systems with the same SID.  Both RustDesk 1.1.19 x64. 

I wanted to reset the Rustdesk ID on both systems.  I tried uninstalling and reinstalling and rebooting, deleted C:\Users\Xxxx\AppData\Roaming\RustDesk and C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk, tried the "id = '0' / password = '' / salt = '' reset method suggested here, but it would generate the same RustDesk ID for both systems every time.  

Without diving into the source code, it's clearly just using the Windows SID. Is there a way around this?

**Comment by Arrmm** [comment]
> I recently cloned a Windows 10 PC, p2p. No sysprep, so two systems with the same SID. Both RustDesk 1.1.19 x64.
> 
> I wanted to reset the Rustdesk ID on both systems. I tried uninstalling and reinstalling and rebooting, deleted C:\Users\Xxxx\AppData\Roaming\RustDesk and C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk, tried the "id = '0' / password = '' / salt = '' reset method suggested here, but it would generate the same RustDesk ID for both systems every time.
> 
> Without diving into the source code, it's clearly just using the Windows SID. Is there a way around this?

Did you try my steps to set up a different ID?  It should be able to solve your problem.

https://github.com/rustdesk/rustdesk-server/issues/22#issuecomment-1383266373

**Comment by Arrmm** [comment]
> > Did you try my steps to set up a different ID? It should be able to solve your problem.
> 
> There's the "Change ID" function in the dot-dot-dot menu. If my old ID was 12345678, I tried changing to A12345678 and the error was "Not yet supported by the server." This error happened whether or not the service was stopped.
> 
> Manually changing the ID in the ServiceProfile seems to work, thank you!

Yes, for whatever reason they stop supported the change ID feature since server 1.1.6.  I was in the same boat as you and luckily found the other thread and so I decided to write a mini guide to help my fellow Rustdesk supporters on how to manually change the ID.  It is not the most effective way but at least there is a workaround.

**Comment by ksingh7** [comment]
After reading this issue and collaborating all responses here is a slightly improved  command sequence to change ID and Password

```
net stop RustDesk
taskkill /im RustDesk /f

$id = Get-Content C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml | Select -Index 0
$password = Get-Content C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml | Select -Index 1

$id
$password

$newId = "id = '000001'"
$newPassword = "password = '111'"

$newId
$newPassword

$filecontent = Get-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml -Raw
$filecontent

$filecontent.Replace("$id","$newId") | Set-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml 
$filecontent.Replace("$password","$newPassword") | Set-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml

## Its a hack, ID gets overridden, hence need to it again , let me know if anyone else have a better solution

$filecontent.Replace("$id","$newId") | Set-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml                  

$filecontent = Get-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml -Raw
$filecontent


net start RustDesk
```

**Comment by ksingh7** [comment]
I am still wondering if anyone has figured out a neat way to get or set ID / Password to Rustdesk via CLI  , CLI argument is what we need , desperately need. 

Anyone ?

**Comment by sikandarsir98** [comment]
I have just created a batch file for myselft. I am not a professional. I am using batch file to execute the powershell command which I have Rustdesk Community and modified it as needed: 

Batch File:
--------------------------------------------------------------------------------------------------------------------------------------------
:start
set /P choice="Choose Option 1 for stop service and close program, 2 for run powershell command, 3 for start the service and program: "
if '%choice%'=='1' goto 1
if '%choice%'=='2' goto 2
if '%choice%'=='3' goto 3

:1
net stop RustDesk
taskkill /im rustdesk.exe /f
goto start
:2
powershell -ExecutionPolicy Bypass -File "%~dp0RustDesk.ps1"
goto start
:3
net start RustDesk
goto start


PS1 File:
--------------------------------------------------------------------------------------------------------------------------------------------
$Name = Read-Host -Prompt "Enter Name of ID: "
$id = Get-Content C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml | Select -First 1
$newId = "id = '$Name'"
$filecontent = Get-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml -Raw
$filecontent.Replace("$id","$newId") | Set-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml
$Pass = Get-Content C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml | Select -First 2 | Select -Skip 1
$newPass = "password = 'Password@123'"
$filecontent = Get-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml -Raw
$filecontent.Replace("$Pass","$newPass") | Set-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml
$filecontent

**Comment by sesu-tech** [comment]
@sikandarsir98

Don't forget to restart the RustDesk service after your PS1 script here, add the following line at the end:
`Restart-Service -Name "RustDesk"`

**Comment by sikandarsir98** [comment]
> @sikandarsir98
> 
> Don't forget to restart the RustDesk service after your PS1 script here, add the following line at the end: `Restart-Service -Name "RustDesk"`

I am initiating/restarting the RustDesk service from my batch file. 

Thank you for the thumbs-up!

**Comment by sesu-tech** [comment]
@sikandarsir98 

Ohhh, my bad, I wasn't using the batch and just incorporated that specific part into my PS1 script that's deploying RustDesk. :P

**Comment by vegardgithub** [comment]
Try deleting C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml before cloning computers. When RustDesk starts up the first time it creates a new RustDesk.toml with unique ID. Works for my W10 image with rustdesk version 1-2-3-1 :)

**Comment by DanielPiperno** [comment]
I did it in a simple way:
1. I turned off the Rustdesk service
2. I deleted the ID from the Rustdesk.toml file.
3. I activated a VPN to get a new IP.
4. I turned on the Rustdesk service again and it assigned me a new ID
Ready!

**Comment by Sven1403** [comment]
Got a Problem with the ID Changing: https://github.com/rustdesk/rustdesk-server/issues/22#issuecomment-2097803108

Maybe someone here can help? :)

**Comment by jericholab** [comment]
> I did it in a simple way:
> 
>     1. I turned off the Rustdesk service
> 
>     2. I deleted the ID from the Rustdesk.toml file.
> 
>     3. I activated a VPN to get a new IP.
> 
>     4. I turned on the Rustdesk service again and it assigned me a new ID
>        Ready!

Your idea worked for me on Raspberry Pi OS. Thank you! After trying every other suggestions (e.g. id= '0'..... etc). I just connected to hotspot instead of VPN and that forced a new ID.

**Comment by jericholab** [comment]
Although yesterday's solution worked initially, it reverted back to the original ID when I reverted back to the original WiFi. So I found a more permanent solution. It turns out that RustDesk tries to keep the same ID to a computer "forever". When the config file is lost, and the software tries to determine on which computer it is running, it seems to look at various things, such as IP address and Machine ID. I don't know if you are familiar with Machine ID, but most Operating Systems give a unique ID to a computer. This number is used by different processes and software to recognize unique computers. When we create an OS image, this number is copied. Therefore, it will actually be useful to prevent other problems to give a unique machine ID to each clone.

So here is an updated procedure:

    Delete the folder $HOME/.config/RustDesk folder (if you don't see the hidden folders in your file explorer, press "CTRL + H")
    $ sudo systemctl stop rustdesk.service   (Remember that default username is Pi and default password is 'raspberry').
    $ sudo kill rustdesk
    $ sudo rm /etc/machine-id
    $ sudo sudo systemd-machine-id-setup
    Launch RustDesk app again via the menu (Start/Internet/RustDesk).
    You should now see a new ID on the left (9 or 10 digits).
    The permanent password will have been reinitialized. You must go into Menu/Security and Unlock security settings". The default password is 'raspberry'. Then you will be able to 'Set permanent password'. Please enter the usual password ("marmeladeXmas1").

**Comment by 21509lele** [comment]
If modifying the 'RustDesk.toml' file in the system does not generate a new ID, try clearing the ID in the 'RustDesk.toml' file located in the AppData folder of the corresponding user.

**Comment by ssrgmbh** [comment]
I created a interactive Powershell Script to deal with this issue on Windows Computers. 
https://github.com/ssrgmbh/change-rustdesk-id

Features:
- Changes the ID to either Hostname, random 9-digit-number or a custom value
- Offers the option to save the password to your bitwarden server

**Comment by lukaspavelka** [comment]
> Changing manually the ID with a new (another) one in C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml does the job, but you have to be sure first it is not already used by someone else and this is almost impossible to find (making a test connection to the ID (in question) to check whether it used is not enough, the remote machine could be offline at that moment) ...
> 
> I have found another smarter, easier and safer way - forcing the app to change the ID automatically by changing the following in C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml for the installed version:
> 
> id = '0' password = '' salt = ''
> 
> You do not need to stop the app at all. After making changes to this file only restart the computer and the work is done ...
> 
> id = '0' - is unacceptable value for the app and it takes immediately the actions to search for a new free ID and change the one before ... password = '' - changes automatically the password, too ... Don't touch, if you want to preserve the password ... salt = '' - for just in case ....

It works for me, gr8, thx

**Comment by aileenfun** [comment]
does anyone knows how to chang id on Mac?

**Comment by VitaliyAT** [comment]
It would be better if creators add button "Change ID" in GUI

**Comment by C-Duv** [comment]
I don't see the `--set-id` option mentioned.

It does work fine.

Note: it does not allow any values as the `id` key in `RustDesk.toml`.

**Comment by Kerrnel** [comment]
On 1.35, Mac/Linux/Windows tested - changing enc_id = 'xyz' to id = 'pdq' in BOTH RustDesk.toml files (user, system) - and restarting the service - DOES set the id and update the file to enc_id with the new encrypted version of it.

**Comment by bigretromike** [comment]
stop service (from GUI)
Delete: C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\
Delete: C:\users\<USER>\AppData\Roaming\RustDesk\config\
start service (from GUI)
reconfigure RD

**Comment by ThomasWaldmann** [comment]
I wrote a script, see there: https://github.com/rustdesk/rustdesk-server/issues/22#issuecomment-3139768174
