### ISSUE TITLE
Key mismatch

### ISSUE THREAD

**Issue by shaojun** [rustdesk/rustdesk#8381]
### Bug Description

I'm running the **single** instance of open source rustdesk server via the official `compose.yml`, and i believe everything is there:
```
root@ubuntu-s-1vcpu-1gb-sgp1-01:~# docker ps
CONTAINER ID   IMAGE                             COMMAND   CREATED             STATUS         PORTS     NAMES
9b48bbfe5401   rustdesk/rustdesk-server:latest   "hbbs"    About an hour ago   Up 6 minutes             hbbs
fdef1b6c9e66   rustdesk/rustdesk-server:latest   "hbbr"    About an hour ago   Up 6 minutes             hbbr

```
and:
```
root@ubuntu-s-1vcpu-1gb-sgp1-01:~/rustdesk# ls
compose.yml  data
root@ubuntu-s-1vcpu-1gb-sgp1-01:~/rustdesk# ls data/
db_v2.sqlite3  db_v2.sqlite3-shm  db_v2.sqlite3-wal  id_ed25519  id_ed25519.pub
```
and I set my server's public domain name into rustdesk client(`Version: 1.2.3-2`):
![image](https://github.com/rustdesk/rustdesk/assets/3241829/18b2d47e-6f54-49a7-ac45-e079d8cfefc2)

then, no matter if the target client exists or not, once i click connect, the `Key mismatch` poped up:
![image](https://github.com/rustdesk/rustdesk/assets/3241829/f31fae56-c192-400e-95d9-be0d486ed304)

### How to Reproduce

described above.

### Expected Behavior

the client should connect to remote peers.

### Operating system(s) on local side and remote side

Windows 11 -> Ubuntu 24.04 LTS

### RustDesk Version(s) on local side and remote side

1.2.3-2 -> latest

### Screenshots

attached.

**Comment by shaojun** [comment]
> You are missing the `Key` here:
> 
> ![](https://private-user-images.githubusercontent.com/3241829/340203977-18b2d47e-6f54-49a7-ac45-e079d8cfefc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDkzNDYsIm5iZiI6MTcxODYwOTA0NiwicGF0aCI6Ii8zMjQxODI5LzM0MDIwMzk3Ny0xOGIyZDQ3ZS02ZjU0LTQ5YTctYWM0NS1lMDc5ZDhjZmVmYzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTdUMDcyNDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODM1NGFkZTU1NjNlYWZiMDkyNGFjMzllZjkwZGU0Mjg3MzBiOGEwOTY2MmJjYTRhZTNlODY1MzdlZGJjMDUyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5V50QbprK1zy84JDdR_gpIwdN_tqfpIp1r9GnGjLGVI)
> 
> You need to put the content of `id_ed25519.pub`.

yes, it takes an hour for me to point it out, looks like the document didn't covered this parameter which is necessary for client?

**Comment by NicKoehler** [comment]
@shaojun You can read it [here](https://rustdesk.com/docs/en/self-host/client-configuration/#set-key)

**Comment by shaojun** [comment]
@NicKoehler thanks.   
I was told (I didn't to prove it) the key string in client side is not a mandatory, so is this a new requirement or I was wrong.

**Comment by NicKoehler** [comment]
Is not mandatory for public servers afaik

**Comment by shaojun** [comment]
> Is not mandatory for public servers afaik

so looks like the default behavior changed.

**Comment by william20210206** [comment]
Useful,RustDesk ofccial document did't metioned that When the new version released

**Comment by niky45** [comment]
I came here with the same error. 
client/server config documentation NEEDS to be improved. namely, **this needs to be explained.** 
I thought the key was like, for pro only. i.e. license key.

**Comment by william20210206** [comment]
> You are missing the `Key` here:
> 
> ![](https://private-user-images.githubusercontent.com/3241829/340203977-18b2d47e-6f54-49a7-ac45-e079d8cfefc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDkzNDYsIm5iZiI6MTcxODYwOTA0NiwicGF0aCI6Ii8zMjQxODI5LzM0MDIwMzk3Ny0xOGIyZDQ3ZS02ZjU0LTQ5YTctYWM0NS1lMDc5ZDhjZmVmYzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTdUMDcyNDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODM1NGFkZTU1NjNlYWZiMDkyNGFjMzllZjkwZGU0Mjg3MzBiOGEwOTY2MmJjYTRhZTNlODY1MzdlZGJjMDUyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5V50QbprK1zy84JDdR_gpIwdN_tqfpIp1r9GnGjLGVI)
> 
> You need to put the content of `id_ed25519.pub`.

this is the solution

**Comment by damies13** [comment]
I also found this issue explained details that were missing/unclear from the documentation. The client UI also does not make it clear where the key comes from, so I also thought the key was only for the pro version.
I guess this issue is now part of the "official" documentation and FAQ?
