### ISSUE TITLE
iPad -> Manjaro KDE 6 Wayland really bumpy, only parts of screen available

### ISSUE THREAD

**Issue by 8192K** [rustdesk/rustdesk#8386]
### Bug Description

I am using the iPad app to connect to Manjaro Stable KDE 6 on Wayland. On this platform I am using Rustdesk on nightly (1.2.6-0). Connecting works fine (I (still) have to select the screen to share in Wayland first) but it is really hard to do anything on the shared screen on the iPad. On the iPad I am using a connected bluetooth mouse and keyboard. I am showing the remove cursor.
The remote cursor only moves in a very bumpy fashion, jumping from place to place. I can drag windows around, but this, as a consequence, is also very bumpy. Furthermore, I can't use the somewhat upper half or 40% of the screen. The mouse just doesn't go there. The screen is set to a global scale of 165% in KDE. That could be a correlation there.

I know that Wayland support is only experimental, but I thought I'd share the experience for you to improve things. Hoping for great Wayland support soon!

### How to Reproduce

See above

### Expected Behavior

See above

### Operating system(s) on local side and remote side

ipadOS 17.5.1 -> Manjaro Stable with KDE Plasma 6.0.5 Wayland (Kernel 6.9.3.3, KDE 6.2.0)

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.6-0 nightly

### Screenshots

Can add a video later if necessary

### Additional Context

Pretty sure this is a Wayland issue, not an iPad one.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by 8192K** [comment]
I need to be more precise:
- Moving the mouse and moving windows around is smooth, but only after a reconnect

- using the remote mouse:
The remote mouse can move on the entire remote screen, but it is not visible on the local iPad screen. The local arrow cursor is stuck in the lower half (+/-) of the ipad. It moves correctly to left and right but only proportionally up and down. This happens with any global scale set to > 100%.
When using a global scale of 100%, the local cursor and the remote mouse match positions - but then the local cursor doesn't go into a small top and a small bottom section of the screen while the remote mouse can go everywhere, still.

- using the local mouse (connected by bluetooth to the ipad):
The cursor can now be moved everywhere, but the mentioned proportional mismatch still happens in case of global scale > 100%.
