### ISSUE TITLE
Remote low resolution Android tablet display is too small

### ISSUE THREAD

**Issue by haisong66** [rustdesk/rustdesk#8396]
### Bug Description

Remote low resolution Android tablet display is too small

### How to Reproduce

Can it be adjusted to >1920 or 1600 to reduce the display size by half? Otherwise the 1366 tablet display is too small.

### Expected Behavior

I hope the remote 1366 size device will display larger

### Operating system(s) on local side and remote side

Windows10->1.2.6

### RustDesk Version(s) on local side and remote side

1.2.6->1.2.6

### Screenshots

![1718689333786](https://github.com/rustdesk/rustdesk/assets/168391999/f215a50b-de21-461d-82fb-89858127febd)

https://github.com/rustdesk/rustdesk/assets/168391999/0ba6d190-b325-499b-b419-8a7465a2d371

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/8167#issuecomment-2174835593
