### ISSUE TITLE
Mac用IP连接win显示 No Display

### ISSUE THREAD

**Issue by aloasut** [rustdesk/rustdesk#84]
最新版1.1.6
1.同一个局域网，用IP内网连接，已经允许并设置了密码，用管理员运行。
2.mac连接win，如果同时打开微软远程桌面，rustdesk可以连接
3.关闭远程桌面连接，则rustdesk freeze；
4.单独用rustdesk连接显示 No Display，与此同时，点击传输文件可以显示win里面的文件。就是无法连接显示。

**Comment by aloasut** [comment]
补充，等待10分钟后单独用rustdesk就可以连接了。
在远端看B站视频音质很差，有回音。
暂时无法取代微软远程桌面。

**Comment by rustdesk** [comment]
Thanks

**Comment by rustdesk** [comment]
My audio codec uses a simple linear sampling. We will improve it in the future. Yes RDP is better.
