### ISSUE TITLE
Windows to MacOs - keyboard issue

### ISSUE THREAD

**Issue by bferrie93** [rustdesk/rustdesk#8402]
### Bug Description

I use windows 11 to MacOs Catalina. French keyboard on both. Map keyboard. Same problem with 2 different windows. I only have one iMac.
I regularly have keyboard transcription problems, which occur at random. I restart the session, everything works again, until the problem returns after a while.
When the problem manifests itself, certain keys are no longer recognized or call up unsolicited shortcuts: the windows key to make the command key on mac no longer works, the E key calls up shortcuts, the D key too, for example, without pressing any other key.

Also, keyboard retranscription is rather slow.

### How to Reproduce

After a while.
I couldn't find anything to force the problem.

### Expected Behavior

A correct keyboard transcription ans faster.

### Operating system(s) on local side and remote side

windows 11 to MacOs Catalina

### RustDesk Version(s) on local side and remote side

1.2.3 on both

### Screenshots

I would try

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by rustdesk** [comment]
try out nighty build first please.

**Comment by bferrie93** [comment]
Since your reply, I've tried nigthly and it seems to work better, fewer bugs that force you to restart.
Only the ^ key for accents sometimes doesn't work anymore.
And some badly transmitted keys: for example, the - ont the 6 key becomes §.

Thanks

**Comment by rustdesk** [comment]
> the - ont the 6 key becomes §.

?

**Comment by bferrie93** [comment]
When i press - Key (on the 6 Key) on my windows keyboard, it writes § on the MacOs client.

**Comment by rustdesk** [comment]
What is "on the 6 Key"?

**Comment by bferrie93** [comment]
![Screenshot_20240628-125406](https://github.com/rustdesk/rustdesk/assets/148718802/410c3bfe-0df4-44bf-8d7e-321d3db74358)

This Key, sorry.

**Comment by rustdesk** [comment]
@fufesou follow it up

**Comment by fufesou** [comment]
@bferrie93 Hi, do you want to input "-" instead of "§"? Maybe you need to choose another input method.

https://github.com/rustdesk/rustdesk/assets/13586388/8396a705-3394-4ce8-bcf5-0c67d5c00d98

https://github.com/rustdesk/rustdesk/wiki/FAQ#keyboard-translation-modes

Or you can use the "Translate mode".

![image](https://github.com/rustdesk/rustdesk/assets/13586388/7a428fe0-72eb-405e-8b33-d24b11db249e)

**Comment by bferrie93** [comment]
Thanks for your reply.
In fact, changing the Mac keyboard to French pc is better.
Just the accent ^which still doesn't work sometimes.

Thanks for your great software and your help

**Comment by fufesou** [comment]
> Just the accent ^which still doesn't work sometimes.

Yes, there may be some issues with the accent  ^.

Can you please give some examples, thanks.

**Comment by bferrie93** [comment]
Sorry I can't, it happens randomly. The ^ accent works fine at first, and then sometimes it starts not working. If I restart the session, it works again. I wonder if this is a keyboard "refresh" problem.
But the problem seems to be quite rare now. If I can figure out what's triggering the problem I'll come back.
