### ISSUE TITLE
Automatic Winget submission is broken

### ISSUE THREAD

**Issue by Danik1601** [rustdesk/rustdesk#8403]
### Bug Description

Action "[Publish to Winget](https://github.com/rustdesk/rustdesk/actions/workflows/winget.yml)" seems broken since at least 1.2.4.
Winget is the preferred method of installation because it easily works easily with mass-deployment and does not ask about installing certificate (or any other parameter) by default.

### How to Reproduce

Look at the [workflow](https://github.com/rustdesk/rustdesk/actions/workflows/winget.yml), visit [winget-pkgs](https://github.com/microsoft/winget-pkgs) and look at [these pull requests](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+RustDesk.RustDesk+version).

### Expected Behavior

New RustDesk versions should be automatically submitted to Winget

### Operating system(s) on local side and remote side

Windows 10, Windows 11

### RustDesk Version(s) on local side and remote side

1.2.4 and later versions

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/17238959/f88df76c-0f8e-4aab-892c-13805728936b)

**Comment by rustdesk** [comment]
We know, you do not need to mention us. We have our plan.
