### ISSUE TITLE
Pressing the physical middle mouse button on the touchpad does not work

### ISSUE THREAD

**Issue by hz61p1** [rustdesk/rustdesk#8405]
### Bug Description

I have a Thinkpad T480 with a Suse TW system, with all the latest updates, with KDE 6 and Wayland desktop and Rustedsk 1.2.6 installed as flatpak. It doesn't really matter which version of Rustdesk and which way the installation was done, I've tried different options and versions. When I connect to a remote computer and invoke the click of the physical middle mouse button the touchpad is not transmitted to the remote computer, but if a mouse is connected to the laptop the click works through the physical mouse.

### How to Reproduce

I don't know other than using the same hardware or similar with having a physical middle button on the touchpad

### Expected Behavior

Transmitting a click to a remote computer

### Operating system(s) on local side and remote side

Suse TW -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.6 -> 1.2.6

### Screenshots

I assume a textual description is sufficient

### Additional Context
I'm using Fusion 360 on a remote computer, and the shift+middle_button combination doesn't work to rotate the camera, but as mentioned if you use a physical mouse it works

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367
