### ISSUE TITLE
when connect to android7.1 the home button is huge then android12

### ISSUE THREAD

**Issue by blankhang** [rustdesk/rustdesk#8411]
### Bug Description

when connect to android7.1 the home button is huge then android12

### How to Reproduce

mac 1.2.6 connect to android 7.1.2 1.2.6

### Expected Behavior

home botton size is normal

### Operating system(s) on local side and remote side

mac -> android

### RustDesk Version(s) on local side and remote side

1.2.6 -> 1.26

### Screenshots

android 7.1.2
<img width="1300" alt="image" src="https://github.com/rustdesk/rustdesk/assets/3981276/72c238e6-b003-47c4-8b13-ebfe6328ca2b">
android 12
<img width="1300" alt="image" src="https://github.com/rustdesk/rustdesk/assets/3981276/1997558a-dfbf-476a-932c-9d5a71bf1b36">

### Additional Context

Thanks very much for making 1.2.6 working on android 7.1.2 again

**Comment by rustdesk** [comment]
Close as wontfix
