### ISSUE TITLE
When using /r to force relay connection file transfer ingore this setting

### ISSUE THREAD

**Issue by bigretromike** [rustdesk/rustdesk#8415]
### Bug Description

When forced connection to using relay by inputing /r into ID textbox when I want to transfer files, the file transfer connection ignores `/r` and try to connect directly which fails. 

### How to Reproduce

While having one computer in network that is unable to get direct connection, input his ID into ID box with `/r` and connect, then try to transfer files.

### Expected Behavior

if `/r` is used it should be used for all connection from that session with that ID.

### Operating system(s) on local side and remote side

Windows 11 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.3-2

### Screenshots

none

**Comment by 21pages** [comment]
try 1.2.6, https://github.com/rustdesk/rustdesk/releases/tag/1.2.6

**Comment by rustdesk** [comment]
I tried nightly, it uses relay
