### ISSUE TITLE
Add an option in the main GUI window to search for name, not only for ID ...

### ISSUE THREAD

**Issue by givbra** [rustdesk/rustdesk#842]
Add an option in the main GUI window in Recent Sessions, Favorites, Address Book to search for name, not only for ID - useful when we rename some client ID machines to be easier for us to find when making lots ot connections over time and it gets crowded ...

**Comment by rustdesk** [comment]
Please group your feature requests to one please.

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/774
