### ISSUE TITLE
Incorrect Cursor Without Physical Mouse

### ISSUE THREAD

**Issue by khat17** [rustdesk/rustdesk#8424]
### Bug Description

Physical mouse present - cursor renders properly. 

Physical mouse not present - cursor renders as a blue dot or gets stuck at the last render.

### How to Reproduce

Connect to a client with no physical mouse present. Doesn't matter if mouse is unplugged before/after full system startup.

### Expected Behavior

Cursor will render initially as a blue dot. Depending on actions, cursor may render as pointer, resize pointer or text pointer but may not revert to regular pointer.

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.2.4

### Screenshots

https://github.com/rustdesk/rustdesk/assets/26496753/a76f2b9d-e700-49a0-8f29-03f7815b98c0

### Additional Context

Noticed on remote server - reproduced locally. Will can be reproduced if mouse is plugged in/out.

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/672
