### ISSUE TITLE
Black screen with remote pc's laptop lid open, image only shows when closing lid

### ISSUE THREAD

**Issue by LunaFennec** [rustdesk/rustdesk#8430]
### Bug Description

I have a laptop running a radio server, normally with the screen open as an added bonus of being able to use the front facing camera as a crude "security camera" when i'm not at home.
Connection worked fine before, but after switching to Tiny10 on the remote device(hp laptop) using latest Rustdesk 1.2.6 nightly after roughly 10 connections it suddenly happened. absolutely no setting will change this behavior, only closing the lid will make it show an image but then most of windows fails to render properly as when you close the lid and turn off sleep with closed lid windows stops rendering stuff on screen.

### How to Reproduce

Only happens with this specific laptop. 
Install Tiny10 iso, connect a few times before getting black screen, then change "choose what happens when you close the lid" to do nothing, then close lid, reconnect. 

### Expected Behavior

A connection with an image. This did not happen with the lid open.

### Operating system(s) on local side and remote side

Tiny10 23H2 (custom windows 10 iso based on win10 home 23H2) remote side, Windows 10 Pro 22H2 local side

### RustDesk Version(s) on local side and remote side

1.2.6 Nightly remote side, Rustdesk 1.2.2 Local side

### Screenshots

Lid closed!
![ss2](https://github.com/rustdesk/rustdesk/assets/163932228/1fcdc858-eaba-4b34-833d-bd1abca1b4bc)
Lid open!
![ss](https://github.com/rustdesk/rustdesk/assets/163932228/54bb641e-6bb1-4392-b746-8c2e747ec3cd)

**Comment by rustdesk** [comment]
close to favor https://github.com/rustdesk/rustdesk/issues/4296, similar issue
