### ISSUE TITLE
x11 forwarding could not authenticate the unlock setting

### ISSUE THREAD

**Issue by MaxKingPor** [rustdesk/rustdesk#8433]
### Bug Description

The x11 forwarding could not authenticate the unlock settings, and it was also very stuck

### How to Reproduce

Xmanager 7 x11 forwards the rustdesk ui for Ubuntu 24.04 LTS

### Expected Behavior

The endpoint or UI under X11 forwarding completes the authentication to optimize the forwarding lag problem

### Operating system(s) on local side and remote side

win11 -> Ubuntu 24.04 LTS

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/43533178/a53fbdce-ca8a-4521-8788-ee9b777a03a0)

### Additional Context

`polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie`

**Comment by rustdesk** [comment]
no plan to fix such case
