### ISSUE TITLE
Connected, waiting for image （-> Xperia)

### ISSUE THREAD

**Issue by TheGrave** [rustdesk/rustdesk#8448]
### Bug Description

Ever since I started using RustDesk (both stable and nightly versions on both client and server side) about 18-24 months agon50% of my connections end up with the "Connected, waiting for image screen". Only restarting the service on the server side helps which forces me to have TeamViewer Host installed alongside. Servers are all Sony Xperia - I, I 3, and V. OS on them - Android 11 and 13. I doubt this issue is hardware or OS-specific or that it's the first time it is reported.

### How to Reproduce

Connect from an Android, Ubuntu or Windows client to an Android server

### Expected Behavior

Successful connection

### Operating system(s) on local side and remote side

Android, Ubuntu, Windows - Android 11/13

### RustDesk Version(s) on local side and remote side

1.x.x - > 1.x.x

### Screenshots

![Screenshot_20240623-101111](https://github.com/rustdesk/rustdesk/assets/105408446/6e3284f5-3b45-42ba-a419-9f6ca1255262)

**Comment by rustdesk** [comment]
@21pages

**Comment by 21pages** [comment]
@TheGrave  Could you try this program https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.2.6-aarch64-log-waiting-for-image.apk and send me the log? It's compiled with https://github.com/21pages/rustdesk/actions/runs/9632248752. 

Install this program on the andriod controlled side and connect to it, after waiting for image appears, get the log, https://github.com/rustdesk/rustdesk/wiki/FAQ#access-logs,  remove your server informations in the log, and send it to my email, `c3VuYm9lYXN5QGdtYWlsLmNvbQo=` (base64).

**Comment by TheGrave** [comment]
I planted the bomb but now the connection drops 1s after connecting and the client (1.2.6 stable) cannot re-connect. Gotta close the app and connect again.

**Comment by 21pages** [comment]
>  the connection drops 1s

Could you send me the log of the controlled side?

**Comment by TheGrave** [comment]
Mail sent Pass is: "rustdesk"

**Comment by 21pages** [comment]
In the log, the mediacodec encoder creation fails and falls back directly to vp9, then the connection lasts for about 15 seconds and everything looks fine. 

> I planted the bomb but now the connection drops 1s after connecting with "Connection reset by peer" and the client (1.2.6 stable) cannot re-connect. Gotta close the app to connect again. Tried the client on different ISPs too.

Did you see the image? `Gotta close the app to connect again` is close the controlled side or the control side? 

> Connected, waiting for image

What's the controlled android rustdesk version when this happens?

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893
