### ISSUE TITLE
The Discovery does not work well

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#845]
### Discussed in https://github.com/rustdesk/rustdesk/discussions/844

<div type='discussions-op-text'>

<sup>Originally posted by **mikekgr** June 22, 2022</sup>
Dear Sirs,
first of all congratulation for this project. Is VERY good
I am using Self-Host server (Ubuntu 20.04.4), running both hbbr & hbbs and all seems fine using Windows clients to get connected together, but the Discovery doesn't work or I have misunderstood the functionality of this function. I am expecting inside the "Discovery" window to have the registered clients to the server correct?  What to check?

Thanks and Best Regards,
Mike Kranidis</div>

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/261

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/129

**Comment by bigretromike** [comment]
@rustdesk this was resolved in #261, this issue can be close.
