### ISSUE TITLE
Failed cargo vendor

### ISSUE THREAD

**Issue by U2FsdGVkX1** [rustdesk/rustdesk#8454]
### Bug Description

Running cargo vendor will fail because there are two duplicate core-foundation package

### How to Reproduce

```
git clone https://github.com/rustdesk/rustdesk
cd rustdesk
cargo vendor
```

### Expected Behavior

Cache rustdesk dependencies for use on CI or build servers

### Operating system(s) on local side and remote side

Linux

### RustDesk Version(s) on local side and remote side

1.2.6

### Screenshots

```
error: failed to sync

Caused by:
  found duplicate version of package `core-foundation v0.9.3` vendored from two sources:

        source 1: registry `crates-io`
        source 2: https://github.com/madsmtm/core-foundation-rs.git?rev=7d593d016175755e492a92ef89edca68ac3bd5cd#7d593d01
```

**Comment by rustdesk** [comment]
#763
