### ISSUE TITLE
make this app availble in flathub

### ISSUE THREAD

**Issue by userforsource** [rustdesk/rustdesk#8456]
### Bug Description

not available in flathub but it have flatpak support

### How to Reproduce

search rustdesk in flathub

### Expected Behavior

i should find the app

### Operating system(s) on local side and remote side

rhel 9

### RustDesk Version(s) on local side and remote side

2.0

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/162728301/9b93fe50-871c-45df-a682-0ed4ebef7d96)

**Comment by rustdesk** [comment]
no duplidate.
