### ISSUE TITLE
Window corners graphic / transparency glitch

### ISSUE THREAD

**Issue by C-O-D** [rustdesk/rustdesk#8458]
### Bug Description

There's something wrong with the window corners on Linux, no matter what installation or theme I use. Square background is always visible in the corners. 

### How to Reproduce

Start RustDesk and have a look at the window corners

### Expected Behavior

When the corners are supposed to be round then there should be no background visible behind

### Operating system(s) on local side and remote side

Manjaro Linux / Cinnamon -> remote irrelevant

### RustDesk Version(s) on local side and remote side

1.2.6 -> remote irrelevant

### Screenshots

https://github.com/rustdesk/rustdesk/assets/45463988/874ae811-cb78-4560-85a8-5963625178ee

### Additional Context

Can the corner radius be made optional since some themes have square corners and therefore round corners don't fit very well?

I have the problem also mentioned [here](https://github.com/rustdesk/rustdesk/pull/7946)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
