### ISSUE TITLE
The reverse behavior of the "enable remote configuration modification" option in version 1.2.6-x86

### ISSUE THREAD

**Issue by jurykor** [rustdesk/rustdesk#8479]
### Bug Description

The reverse behavior of the "enable remote configuration modification" option in version 1.2.6-x86.
When the option is enabled, remote modification is prohibited. When disabled, it is allowed.

### How to Reproduce

Enable/disable the option

### Expected Behavior

When the option is disabled, remote modification is prohibited. When enabled, it is allowed.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3-2, 1.2.6 -> 1.2.6-x86

### Screenshots

outgoing_342776115_20240626110435070_vp9.webm

[outgoing_342776115_20240626110435070_vp9.webm](https://github.com/rustdesk/rustdesk/assets/159616976/a615149a-2779-46e6-be31-98489a291e4b)

**Comment by rustdesk** [comment]
Thanks and fix merged
