### ISSUE TITLE
Change ID, but the server does not support it

### ISSUE THREAD

**Issue by remloyal** [rustdesk/rustdesk#8499]
### Bug Description

Unable to change device ID

### How to Reproduce

Settings => Security => Change ID

### Expected Behavior

support

### Operating system(s) on local side and remote side

WIN or Mac

### RustDesk Version(s) on local side and remote side

WIN or Mac

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/93071492/489d5a3e-4ef5-44ed-8898-85f989187867)

**Comment by rustdesk** [comment]
The message has told you all.
