### ISSUE TITLE
Flickers child screen when resizing window

### ISSUE THREAD

**Issue by letrungdo** [rustdesk/rustdesk#8505]
### Bug Description

Thank you for the great application of the development team.

When open the child screen, I resize the screen and it flashes black like the screenshot video

### How to Reproduce

Resize child screen.

### Expected Behavior

No flashing black

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.2.6

### Screenshots

[screen-capture.webm](https://github.com/rustdesk/rustdesk/assets/16357748/0607a10a-53c3-4dc3-af6a-2a20577d08ed)

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
It seems related to the hardware?

I've tried two machines with win11 and one machine with win10.
I cannot reproduces this issue.


https://github.com/rustdesk/rustdesk/assets/13586388/84444311-e828-41fa-802e-9791918141cd

**Comment by rustdesk** [comment]
Could you try out newest nightly build? maybe https://github.com/rustdesk/rustdesk/pull/8738 fix it.

**Comment by letrungdo** [comment]
I think it is related to this bug: https://github.com/rustdesk-org/rustdesk_desktop_multi_window/pull/11, before fixing it, the background was white so it would be easier to see, then the black background was similar to the dark theme so it will be hard to see.

**Comment by rustdesk** [comment]
How about the flickering?

**Comment by rustdesk** [comment]
@letrungdo You can revert back https://github.com/rustdesk-org/rustdesk_desktop_multi_window/pull/11, and try.

**Comment by letrungdo** [comment]
@rustdesk  I know it's not related to rustdesk-org/rustdesk_desktop_multi_window#11
This bug was previously present in the original library https://github.com/MixinNetwork/flutter-plugins/tree/main/packages/desktop_multi_window

**Comment by rustdesk** [comment]
Do you have more clue?

**Comment by letrungdo** [comment]
@rustdesk @fufesou We are also actively looking for the cause. You can run debug to clearly see the flickering when resizing the window.

**Comment by letrungdo** [comment]
Because it has been fixed in the above PR, I will close this issue. Thanks team for the support!
