### ISSUE TITLE
Arrows to move cursor writes a number when multiple times is pressed

### ISSUE THREAD

**Issue by LBoullosa** [rustdesk/rustdesk#851]
**Describe the bug you encountered:**
When pressing the arrows to move the cursor, sometimes works, but if it is pressed to quickly then the movement is replaced with the value of the number from the keypad.

**What did you expect to happen instead?**

Cursor moves to the right, left, up or down (depending on the arrow pressed)

**How did you install `RustDesk`?**

Portable version

**RustDesk version and environment**

1.1.9 on Windows 10 with relay and server running.
1.1.9 on Windows 10 for client using the server/relay on local network.

**Comment by grummbeer** [comment]
Saw this at some point in the past, but not anymore.

@LBoullosa please try out the nightly build https://github.com/rustdesk/rustdesk/releases/tag/nightly
A lot of keyboard issues are fixed #1547
