### ISSUE TITLE
Rustdesk Main Window Randomly turns blank on Ubuntu 22.04

### ISSUE THREAD

**Issue by XuShenLZ** [rustdesk/rustdesk#8516]
### Bug Description

Most of the time, I can use Rustdesk to connect to/from other machine just fine. But sometimes, the main Rustdesk window becomes blank and I cannot use it at all. The tray icon is still there, but when I click on "open", the main window is still blank. 

I tried to quit the tray icon, restart the `rustdesk.service`, and re-launch the application. Nothing is fixed. Also, I cannot connect from another machine anymore. It would just tell me "remote desktop is offline".

The only effective way to fix this is to reboot my system. 

This happened for all versions like 1.2.0, 1.2.3, and 1.2.6. I would be grateful if someone can tell me how to fix this (properly restart all rustdesk stuff without rebooting the system, since I have some code running so I cannot shut down my pc)

### How to Reproduce

It was hard to tell what triggers this bug. It would just happen randomly for no reason.

### Expected Behavior

The main application window should be opened normally, and we should be able to connect from another machine.

### Operating system(s) on local side and remote side

Ubuntu 22.04 -> Any

### RustDesk Version(s) on local side and remote side

1.2.6 -> Any

### Screenshots

Please see this screencast for detail:

[Screencast from 06-27-2024 04:24:30 PM.webm](https://github.com/rustdesk/rustdesk/assets/31999415/2ad3b46f-b80f-4c65-b271-548cc5c20025)

**Comment by rustdesk** [comment]
close to favor https://github.com/rustdesk/rustdesk/issues/5986

**Comment by rustdesk** [comment]
Can you run from command? We want to see if there something in the output.

**Comment by XuShenLZ** [comment]
Thanks for responding quickly! I killed my own code and had a system reboot.. I will ping you next time when this happens and attach screenshots

**Comment by rustdesk** [comment]
We still not find the cause, because we can not reproduce it.
Please try out the sciter version, I believe this can work as a workaround. We will continue to dig in.
https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.7-x86_64-sciter.deb
https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.7-x86_64-sciter.flatpak

**Comment by XuShenLZ** [comment]
Thanks a lot! I will follow up when it happens again and collect more information for you

**Comment by rustdesk** [comment]
could you help run with an argument from command line? https://github.com/rustdesk/rustdesk/issues/5986#issuecomment-2203775637

**Comment by rustdesk** [comment]
Could try out export LIBGL_ALWAYS_SOFTWARE=1

or run
LIBGL_ALWAYS_SOFTWARE=1 rustdesk
