### ISSUE TITLE
1.2.6 Sever lag compared to old versions

### ISSUE THREAD

**Issue by imtrobin** [rustdesk/rustdesk#8518]
### Bug Description

With 1.2.6, the screen is showing delay up to 30 seconds. It did not happen with 1.24 or nighty. It is not the network problem as I use a screen share using meet.jit.si and it is 0.5 delay in screen change.

I reported this with 1.2.5 but it got moved to discussions
https://github.com/rustdesk/rustdesk/discussions/8372

### How to Reproduce

1. Connect rustdesk. It can lag up to 30 sec with frequent disconnects.
2. At same time, open a room in meet.jit.si (e.g https://meet.jit.si/testruskdeskroom).  Sign in and share screen.  Lag is under 1 sec.

### Expected Behavior

Rustdesk lag should be same as meet.jit.si

### Operating system(s) on local side and remote side

Both Windows 10

### RustDesk Version(s) on local side and remote side

1.2.6

### Screenshots

None

**Comment by rustdesk** [comment]
no duplicate
