### ISSUE TITLE
Rustdesk-x86-Sciter 1.2.4 or later, the keyboard cannot be entered

### ISSUE THREAD

**Issue by lpy5511241** [rustdesk/rustdesk#8519]
### Bug Description

Rustdesk-x86-Sciter 1.2.4 or later, the keyboard cannot be entered

### How to Reproduce

Use x86-Scitter version 1.24 or later

### Expected Behavior

Using x86-Scitter 1.24 or later versions of rustdesk, when controlling the opponent's computer, the keyboard does not work properly, all the keys are invalid, and the mouse controls are normal,and reusing version 1.23 is normal

### Operating system(s) on local side and remote side

win7 -> win11  win7 -> win10  win10 -> win7

### RustDesk Version(s) on local side and remote side

1.2.4/1.2.5/1.2.6-x86-Sciter ->1.2.3/1.2.6-x86-64

### Screenshots

![8EA0033E-F9BE-4514-9B05-E862AA07D033](https://github.com/rustdesk/rustdesk/assets/51349704/2c6100b2-4ad3-4f15-8fa9-2a1430e95aa7)

**Comment by rustdesk** [comment]
#763 sorry, we will continue to dev on win7. use 1.2.3. please for win7 case.

**Comment by sinyb** [comment]
The same thing happens on 32bit Windows 10. Last working version is 1.2.3-2.
So it is not "Win 7" but "Win 32 bit".
