### ISSUE TITLE
Mouse Cursor Mismtach on scaled Wayland Screen

### ISSUE THREAD

**Issue by ergouser** [rustdesk/rustdesk#8524]
### Bug Description

Remote system is wayland with screen scaled to 150%.  Cursors are correct in the top left of the screen but diverge as the cursor moves towards the bottom right (remote cursor moves more towards the bottom right)

### How to Reproduce

Remote is a Manjaro system NVIDIA/Wayland (updated today, clean system, RustDesk just installed).
If the scaling is set to 100% the cursors track correctly.
I've tested from two local systems, the remove behaves the same with both, but both (all the systems involved) are Manjaro.

### Expected Behavior

Cursors should always align.

### Operating system(s) on local side and remote side

Manjaro->Manjaro

### RustDesk Version(s) on local side and remote side

1.2.4->1.2.6

### Screenshots

Please let me know if these would help, but they'd just show cursors in two spots.

**Comment by rustdesk** [comment]
known: https://github.com/rustdesk/rustdesk/pull/6502#issue-2007175125

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by Shylock-Hg** [comment]
@ergouser Hello, do you use `multiple monitors` with `GNOME`?

**Comment by rustdesk** [comment]
Default Manjaro is KDE.

**Comment by Shylock-Hg** [comment]
> Default Manjaro is KDE.

As I know, manjaro officially supports both `KDE` and `GNOME`.

**Comment by ergouser** [comment]
System is KDE/Plasma on a single monitor.

**Comment by Shylock-Hg** [comment]
> System is KDE/Plasma on a single monitor.

Yes, I have reproduced it.

**Comment by Shylock-Hg** [comment]
@rust
I found the problem, it's caused by rdp input mouse don't support scale. When I set the scale manually it works. So, I think we could add scale support for mouse by `x = x / scale` for rdp input mouse.
WDYT?

**Comment by Shylock-Hg** [comment]
The rdp input is enabled here. https://github.com/rustdesk/rustdesk/pull/6675/files#diff-d0a786df47f37a36992cdf8bc3a5f81b7d8b051fd9883a05083eba65bdfdaab4

**Comment by rustdesk** [comment]
@fufesou please answer @Shylock-Hg

**Comment by rustdesk** [comment]
> @rustdesk I found the problem, it's caused by rdp input mouse don't support scale. When I set the scale manually it works. So, I think we could add scale support by `x = x / scale, y = y / scale` for rdp input mouse. WDYT?

@beelchester do you have any input about this?

**Comment by beelchester** [comment]
https://github.com/rustdesk/rustdesk/pull/6758
RDP was later disabled for normal wayland packages, it was only made to be used for flatpak packages. I'm not sure if there are any recent changes in this.

**Comment by Shylock-Hg** [comment]
> > @rustdesk I found the problem, it's caused by rdp input mouse don't support scale. When I set the scale manually it works. So, I think we could add scale support by `x = x / scale, y = y / scale` for rdp input mouse. WDYT?
> 
> Sounds correct.
> 
> But I'm a little confused, all mouse movements are handled the same, why there is no problem with Windows or other system coordinates.
> 
> I haven't tested, I'll test later.

I'm not sure about this. But when I check the source, multiple implementations of mouse controller are implemented, there are three way (uinput, rdp, xdo) just in Linux.

**Comment by fufesou** [comment]
> But I'm a little confused, all mouse movements are handled the same, why there is no problem with Windows or other system coordinates?

Sorry, maybe this is normal. It's related to the special input method.

**Comment by fufesou** [comment]
> I'm not sure about this. But when I check the source, multiple implementations of mouse controller are implemented, there are three way (uinput, rdp, xdo) just in Linux.

Yes. We need to make sure what input method or methods needs to be scaled.

`xdo`  -> X11
`rdp` -> Wayland (flatpak, AppImage)
`uinput` -> Wayland (installed versiosn)

**Comment by Shylock-Hg** [comment]
> > I'm not sure about this. But when I check the source, multiple implementations of mouse controller are implemented, there are three way (uinput, rdp, xdo) just in Linux.
> 
> Yes. We need to find out what input method or methods needs to be scaled.
> 
> `xdo` -> X11 `rdp` -> Wayland (flatpak, AppImage) `uinput` -> Wayland (installed versiosn)

Ok, there is maybe a mistake. I build a binary in manjaro, but rdp input is enabled.

**Comment by fufesou** [comment]
> Ok, there is maybe a mistake. I build a binary in manjaro, but rdp input is enabled.

No, it's normal.

`rdp` is enabled when running without `--server` running.

**Comment by Shylock-Hg** [comment]
> Maybe you can try
> 
> https://github.com/google/flutter-desktop-embedding/blob/eb3964990cf19629c89ff8cb4a37640c7b3d5601/plugins/window_size/linux/window_size_plugin.cc#L104
> 
> It's what we're using here
> 
> https://github.com/rustdesk/rustdesk/blob/5e7d4fd2d62fb5fb45b18453f2c195a1316a2213/flutter/lib/common.dart#L2938

I tried it, but it's an integer not fractional scale. e.g. It's 2 when scale is set to 150%, in this way, the mouse cursor will become inaccurate.

**Comment by rustdesk** [comment]
That's the issue we have.

**Comment by Shylock-Hg** [comment]
> That's the issue we have.

Ok, I found gdk4 provide a method to get fractional scale of monitor, https://gtk-rs.org/gtk4-rs/stable/latest/docs/gdk4/struct.Monitor.html#method.scale. But this crate can't get current Dispaly, I will track it.

**Comment by Shylock-Hg** [comment]
```
(rustdesk:74263): GLib-GObject-CRITICAL **: 15:32:30.309: cannot register existing type 'GdkDisplay'
```
This gdk4 will conflict with `gtk3` already used in this project. To update it will be a big break change. I think maybe we should suspend this issue. How do you think about it? @rustdesk

**Comment by rustdesk** [comment]
Is it possible that we call gdk4 with dynamic loading?

**Comment by Shylock-Hg** [comment]
> Is it possible that we call gdk4 with dynamic loading, e.g. `dlopen`? Here is a good example, [tauri-apps/libappindicator-rs#32](https://github.com/tauri-apps/libappindicator-rs/pull/32).

Not work.
```
(process:124189): Gtk-ERROR **: 16:44:55.395: GTK 2/3 symbols detected. Using GTK 2/3 and GTK 4 in the same process is not supported
```
I have loaded the sharded library in local mode.

**Comment by Shylock-Hg** [comment]
Another ugly way is to build a binary to get this scale and spawn it when we need this.

**Comment by rustdesk** [comment]
> Another ugly way is to build a binary to get this scale and spawn it when we need this.

You can do this, it is not ugly.

**Comment by rustdesk** [comment]
> #6758 RDP was later disabled for normal wayland packages, it was only made to be used for flatpak packages. I'm not sure if there are any recent changes in this.

Do you know the disadvantage / limit of RDP? why not we also use it in normal wayland packages?

**Comment by beelchester** [comment]
It can be used for normal wayland packages also https://github.com/rustdesk/rustdesk/pull/6675#issuecomment-1854967344.
But we found that compatibility with old versions like Ubuntu 20.04 is not good https://github.com/rustdesk/rustdesk/pull/6675#issuecomment-1855099442.
Also, might need improvements in utilizing persist_mode I'm not sure https://github.com/rustdesk/rustdesk/pull/6742#issuecomment-1868927546.
I think on cargo/flutter run it still uses RDP for input on wayland... you can check RDP's capability there. If implemented, it should work the same on installed packages.

**Comment by rustdesk** [comment]
Thanks @beelchester

**Comment by rustdesk** [comment]
@ergouser are you using flatpak or appimage with this issue?
