### ISSUE TITLE
100% CPU core usage when "Disable clipboard" is checked in display settings

### ISSUE THREAD

**Issue by yakumi9x** [rustdesk/rustdesk#8542]
### Bug Description

When using the "Disable clipboard" option in display settings, one CPU core (thread) will be stuck at 100%.

### How to Reproduce

1. Connect to a remote machine.
2. Under "Display settings", enable (check) "Disable clipboard".
3. Observe the local client's CPU usage using htop or similar; one core (thread) is pegged at 100%.
4. Under "Display settings", disable (uncheck) "Disable clipboard".
5. Observe the local client's CPU usage using htop or similar; the CPU usage drops to normal levels again.

### Expected Behavior

The CPU usage should remain at normal levels at all times.

### Operating system(s) on local side and remote side

Kubuntu 22.04 -> Kubuntu 22.04

### RustDesk Version(s) on local side and remote side

1.2.6 -> 1.2.6

### Screenshots

![Screenshot](https://github.com/rustdesk/rustdesk/assets/75916193/a2036f30-fd9d-4064-b390-c3c248ca232f)

### Additional Context

Through testing, I have determined that this bug first appeared in version 1.2.4, and is still present in the latest release 1.2.6.
Version 1.2.3-2 is not affected.

Please fix this bug & push out a new release ASAP, as this bug makes RustDesk practically unusable for me & my environment.

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
close as fix merged https://github.com/rustdesk/rustdesk/commit/1252f45506257e5a4a3819be61473e705bc3b20b
It is ready in https://github.com/rustdesk/rustdesk/releases/tag/nightly
