### ISSUE TITLE
MacOS client session freezes when leaving RustDesk window

### ISSUE THREAD

**Issue by B4DschK4Pp** [rustdesk/rustdesk#8548]
### Bug Description

I just installed the RustDesk 1.2.6 client on MacOS Ventura and connected to a Windows PC running RustDesk 1.2.6 as well.
The initial connection is fine but when I switch to another window locally (or even just click on the local osx desktop with my mouse) and return to the RustDesk session window afterwards, the session seems to be frozen. But actually I can see on the remote side that input is still being forwarded (mouse and keyboard). The session window on the host side (osx) does not update accordingly.
This state remains until I restart the RustDesk client on MacOS and initiate a new connection.

### How to Reproduce

- Start RustDesk on osx and start a remote session to another client.
- Leave the session window/switch to another window on your MacOS client.
- Set focus on the active RustDesk session window again.
==> Video of the session is frozen.

### Expected Behavior

Reenter the session window and continue remote session with video working.

### Operating system(s) on local side and remote side

osx -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.6 -> 1.2.6

### Screenshots

https://github.com/rustdesk/rustdesk/assets/26527958/2884ea35-642d-4215-b8b1-8b5aa557252b

Left side: RustDesk on MacOS Ventura as the local side. 
Right side: remote VM being controlled.

### Additional Context

RustDesk 1.2.6 running on MacOS Ventura 13.6.7 on Intel Mac Book Pro 2020

**Comment by fufesou** [comment]
@B4DschK4Pp Hi, thanks for your feedback.
Can you please also give a screenshot of the RustDesk build date on macOS side.

![image](https://github.com/rustdesk/rustdesk/assets/13586388/2d3cbb78-aa88-495c-8122-318c78972668)

**Comment by gbyers** [comment]
Having the exact same issue 2020 Intel Mac Pro.

**Comment by xavetar** [comment]
The last successful build version is 1.2.3-2. Subsequent versions freeze after exiting the window.

**Comment by Tackyou** [comment]
I have the same issue, thought it's random. Good that @B4DschK4Pp found out it's caused by leaving the window. That should make it a little easier to debug. Have to stay on 1.2.3-2. for now. Hope this gets fixed.

**Comment by gcharita** [comment]
It appears that this issue is not happening when the app is in Full Screen mode. Also, entering and then exiting Full Screen mode seams to also temporary fix the session freeze issue.

**Comment by rustdesk** [comment]
> That should make it a little easier to debug

we can not reproduce it.

**Comment by rustdesk** [comment]
@xavetar @Tackyou @gcharita let's report your mac os version, and intel or arm.

**Comment by rustdesk** [comment]
Do you anyone can run with `flutter run`?

**Comment by rustdesk** [comment]
Please try out turn on below `use texture rendering` option.

![image](https://github.com/rustdesk/rustdesk/assets/71636191/0c2ec3bc-43c7-493a-9a2f-2d8e888cff06)

**Comment by gcharita** [comment]
> @xavetar @Tackyou @gcharita please report your mac os version, and intel or arm.

macOS v14.5 Intel

**Comment by gcharita** [comment]
> Please try out turning on below `use texture rendering` option.
> 
> ![image](https://private-user-images.githubusercontent.com/71636191/347394941-0c2ec3bc-43c7-493a-9a2f-2d8e888cff06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NDc0ODQsIm5iZiI6MTcyMDY0NzE4NCwicGF0aCI6Ii83MTYzNjE5MS8zNDczOTQ5NDEtMGMyZWMzYmMtNDNjNy00OTNhLTlhMmYtMmQ4ZTg4OGNmZjA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDIxMzMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNGU5NDA0NzU5Njc0NjQ2MWQyMWFlNTlmYWY0ZmY2NzBkYzk1NGM0Nzk5Yjg4NzdlYjAyMjNmMGMxMzg0ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fjbQMPYwHBLC46tmx_AcvRUfbHLrOPJ8JhSEBzEU0Wo)

I can confirm. This seems to resolve the issue in my case.

**Comment by Tackyou** [comment]
> > Please try out turning on below `use texture rendering` option.
> 
> I can confirm. This seems to resolve the issue in my case. Thank you!

Unfortunately this doesn't fully solve the issue.

The freeze bug still happens, but interaction with the remote session keeps working in texture rendering mode.
The rest of the window though, does not react to any interaction anymore.

Like the controls on top are not clickable anymore. The session also doesn't disconnect when the window is closed, as it would usually do. Reconnecting to the same remote just reopens the bugged out session window.

I'm on MacOS 15 Beta 3 / Intel btw. A friend of mine is on 14.5 and has the exact same issues with Rustdesk 1.2.6.

1.2.3. keeps working fine so something must have changed within the Rustdesk Client.
It seems like MacOS is putting the window in "standby" when it loses focus, but doesn't properly wake it up again when the window is focused again...

Could it be an issue with flutter? 

I tested 1.2.5 and 1.2.4 they also have the bug.
1.2.3-2 is the latest one that doesn't have the issue.

**Comment by rustdesk** [comment]
it is definitely related to flutter, actually 1.2.3-2 uses 1.2.3 code base, so it is last october.

**Comment by rustdesk** [comment]
> A friend of mine is on 14.5

Intel?

**Comment by rustdesk** [comment]
Please help try out 
https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.7-x86_64-flutter3.16.9.dmg
and
https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.7-x86_64-flutter3.22.2.dmg

**Comment by B4DschK4Pp** [comment]
> Please try out turning on below use texture rendering option.

This doesn't fix it for me.

> Please help try out
> https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.7-x86_64-flutter3.16.9.dmg
> and
> https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.7-x86_64-flutter3.22.2.dmg

I cannot make out any difference in the way they behave. Still the same issue with session freezing.

**Comment by rustdesk** [comment]
Coud you please try out https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.7-x86_64-flutter3.13.9.dmg? this version use the same flutter as 1.2.3.

**Comment by rustdesk** [comment]
So it is not related to flutter, I will compile on different dates.

**Comment by rustdesk** [comment]
Could you try out below ones? 
https://github.com/rustdesk/rustdesk/releases/download/nightly

![image](https://github.com/user-attachments/assets/50e9a07e-5d65-44d1-8d71-a313db8ae6a0)

**Comment by Tackyou** [comment]
rustdesk-1.2.7-x86_64-flutter3.**16**.9-flutter20240419.dmg - some kind of "assistant" build that can only receive connections, same with rustdesk-1.2.7-x86_64-flutter3.**19**.6-flutter20240419.dmg

rustdesk-1.2.7-x86_64-flutter3.16.9-flutter20240319.dmg  - texture rendering on by default? remote session interaction keeps working, rest of the window freezes

rustdesk-1.2.7-x86_64-flutter3.16.9-flutter20240219.dmg - same as 20240319

rustdesk-1.2.7-x86_64-flutter3.16.9-flutter20240119.dmg - this one has some additional white lines in the gui, otherwise behaves the same as 20240319

rustdesk-1.2.7-x86_64-flutter3.16.9-flutter20231219.dmg - also white border lines in gui, behaves the same as 20240319

**Comment by rustdesk** [comment]
Thanks a lot. We are very close to 1.2.3.

**Comment by rustdesk** [comment]
Could you try out below builds?

https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.7-x86_64-flutter3.10.6-flutter20231010.dmg
https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.7-x86_64-flutter3.10.6-flutter20231019.dmg
https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.7-x86_64-flutter3.10.6-flutter20231030.dmg
https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.7-x86_64-flutter3.16.9-flutter20231119.dmg

**Comment by Tackyou** [comment]
rustdesk-1.2.7-x86_64-flutter3.10.6-flutter20231010.dmg - no issue

rustdesk-1.2.7-x86_64-flutter3.10.6-flutter20231019.dmg - no issue

rustdesk-1.2.7-x86_64-flutter3.10.6-flutter20231030.dmg - no issue

rustdesk-1.2.7-x86_64-flutter3.16.9-flutter20231119.dmg - white border lines in gui and also has the freeze bug

**Comment by rustdesk** [comment]
I can basically cofirm flutter 3.10.6 works.

**Comment by xavetar** [comment]
> @xavetar @Tackyou @gcharita please report your mac os version, and intel or arm.

[aarch64] macOS Sonoma 14.6 (Beta 3)

**Comment by rustdesk** [comment]
Could you try out the latest nightly build, https://github.com/rustdesk/rustdesk/releases/download/nightly?

We added a workaround, not sure if it works.

**Comment by Tackyou** [comment]
> Could you try out the latest nightly build, https://github.com/rustdesk/rustdesk/releases/download/nightly?
> 
> We added a workaround, not sure if it works.

Tried the nightly, still has the bug. Is it not reproducible in a MacOS VM?

**Comment by rustdesk** [comment]
we failed to install osx on vm, though we could install old osx on vm.

**Comment by Tackyou** [comment]
You need the original MacOS .app installer converted into a dmg or iso.
I converted it a few days ago for installing in VMware. 
Let me share it with you: http://hosting205231.a2e76.netcup.net/macOS_1450_installer.iso

VMware Workstation Pro
Windows: https://softwareupdate.vmware.com/cds/vmw-desktop/ws/17.5.2/23775571/windows/core/VMware-workstation-17.5.2-23775571.exe.tar
Linux: https://softwareupdate.vmware.com/cds/vmw-desktop/ws/17.5.2/23775571/linux/core/VMware-Workstation-17.5.2-23775571.x86_64.bundle.tar

**Comment by rustdesk** [comment]
Please test the newest nightly build. we put a new workaround, it seems ok per one user's feedback.

**Comment by fufesou** [comment]
> You need the original MacOS .app installer converted into a dmg or iso.

@Tackyou Hi, I'm stuck at this step. It seems the iso file is broken. But I've downloaded it twice, both have thie error.

![image](https://github.com/user-attachments/assets/3bf65809-f174-4c21-82c7-07d174898bdd)


https://github.com/user-attachments/assets/e0bae597-e0a7-47af-85ce-6c11b0b7ff16


https://github.com/user-attachments/assets/cce708cb-4de0-42be-8ffb-1ded9e6325ff

**Comment by Tackyou** [comment]
Hey,

sorry for the confusion apparently VMware Workstation does not support MacOS. I was using VMware Fusion.

But there seems to be an unlocker that enables MacOS support on VMware Workstation: https://github.com/paolo-projects/auto-unlocker

Here's a guide that has all the details: https://www.tweaking4all.com/forum/macos-x-software/vmware-on-windows-how-to-create-a-macos-virtual-machine-on-vmware-workstation-player-17/

**Comment by Tackyou** [comment]
> Please test the newest nightly build. we put a new workaround, it seems ok per one user's feedback.

The newest nightly seems to fix the bug. I was not able to reproduce the freeze bug anymore.
Both the remote session and the user interface stay responsive.

**Comment by rustdesk** [comment]
close since the workaround works.
