### ISSUE TITLE
Non English (Czech) characters are not working on iPadOS keyboard

### ISSUE THREAD

**Issue by bambita** [rustdesk/rustdesk#8549]
### Bug Description

When connected from iPad (using HW keyboard) to Windows 10 the Czech keyboard cannot be used. It always write English characters although both source and destination system are set to use Czech keyboard.

### How to Reproduce

Latest RustDesk on source iPadOS and destination Windows 10. Have a Czech keyboard on iPad with HW keyboard. Connect via RustDesk and type Czech characters. It will not work.

### Expected Behavior

Czech characters to work as in all other system and apps.

### Operating system(s) on local side and remote side

iPadOS -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.3-2

### Screenshots

![771479B7-5F1C-42C3-94B7-568D08AAC979](https://github.com/rustdesk/rustdesk/assets/16983664/428231e4-a544-4ceb-b12b-3f16c354d9fa)
![524663C8-7C48-4BB4-99B0-1783316B1B76](https://github.com/rustdesk/rustdesk/assets/16983664/2cc2d117-3d15-4100-9ce1-f8e55cb48922)

**Comment by rustdesk** [comment]
duplicate: https://github.com/rustdesk/rustdesk/issues/8390

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/9717
