### ISSUE TITLE
Login error/ connection not allowed; Ubuntu client on Pi4 (64 bit OS)

### ISSUE THREAD

**Issue by nerlins** [rustdesk/rustdesk#8552]
### Bug Description

It constantly says this. Windows clients work fine. I tried the current .deb file and the nightly. Both give the same error. I am using the ARM64 version. About to try the 32 bit version.

### How to Reproduce

Uhh..install either ARM64 .deb file...

### Expected Behavior

For it to work.

### Operating system(s) on local side and remote side

Windows local -> Ubuntu remote

### RustDesk Version(s) on local side and remote side

Current. Just set it all up today...

### Screenshots

No thanks

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by nerlins** [comment]
Why is this completed already? Tracked as in there is a temporary fix, or what?
