### ISSUE TITLE
In the virtual machine system in the remote computer, letters are input infinitely

### ISSUE THREAD

**Issue by Wizzercn** [rustdesk/rustdesk#8554]
### Bug Description

Mac remote Windows 11 system, open the vmare virtual machine win7 or win11 system in Windows 11, and it will appear that you enter a letter in vmare, and then you will keep entering the same letter, infinite input...

mac电脑远程windows11（或其他win系统），在windows11里打开vmare虚拟机win7或win11系统，会出现在vmare里输入一个字母的，后续会一直输入相同字母，无限输入……

### How to Reproduce

Two computers: PC and Macbook
PC: Install Windows system, install vmare inside, install Windows virtual machine in vmare (win7/win10 is OK)
Macbook: Remote to PC
Reproduction: In the Windows virtual machine in vmare, open any input box, such as the browser address box, although you enter a letter

两台电脑：PC和Macbook
PC：安装windows系统，里面安装vmare，vmare安装Windows虚拟机（win7/win10都行）
Macbook：远程到PC
复现：在vmare里的Windows虚拟机中，随便打开一个可输入框，如浏览器地址框，虽然输入一个字母

### Expected Behavior

The content should be entered normally in the virtual machine system

在虚拟机的系统里应该正常输入内容

### Operating system(s) on local side and remote side

MacOS 14.5 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.1.9 -> 1.2.0

### Screenshots

![1719805377558](https://github.com/rustdesk/rustdesk/assets/2408114/5c37f73d-7927-4059-b3e5-0f0edbaad933)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4357
