### ISSUE TITLE
Key mismatch even with public server

### ISSUE THREAD

**Issue by styris-ame** [rustdesk/rustdesk#8564]
### Bug Description

After updating both my Rustdesk clients and server, it seems I must provide a Key even though this was not necessary before.

Note that I am using a public domain:
![Screenshot 2024-07-01 194915](https://github.com/rustdesk/rustdesk/assets/123859041/72007333-39af-4aa4-9fa4-aaa43795bea4)

### Expected Behavior

No key should be required.

### Operating system(s) on local side and remote side

Windows 11 -> Android

### RustDesk Version(s) on local side and remote side

1.2.6 -> 1.2.6

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
Please go to discord, we do not answer your usage things.
