### ISSUE TITLE
should only exist in one control window at the same time

### ISSUE THREAD

**Issue by cweijan** [rustdesk/rustdesk#858]
每当我从托盘双击按钮后, 会不断的创建新的窗口实例, 应该只保留一个才对, 版本1.1.9.
![image](https://user-images.githubusercontent.com/27798227/175474626-095e0582-899b-4426-b93f-235116fb0e19.png)

**Comment by rustdesk** [comment]
similar: https://github.com/rustdesk/rustdesk/issues/293

**Comment by rustdesk** [comment]
https://github.com/users/rustdesk/projects/6/views/1

**Comment by rustdesk** [comment]
fixed in nightly.

**Comment by lrvprestes** [comment]
Hello, I want to know if there is a way to make a personalized version and receive updates
