### ISSUE TITLE
MacOS texture rendering red flickers

### ISSUE THREAD

**Issue by alexandru-bagu** [rustdesk/rustdesk#8581]
### Bug Description

Every once in a while there are random red flickers when using texture rendering. The red flicker cover the entire window for a frame.
I am using H264 though.

### How to Reproduce

Unfortunately it's random. I don't know how to trigger it.

### Expected Behavior

No red frame flickers would be great.

### Operating system(s) on local side and remote side

macOS -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.6 -> 1.2.6

### Screenshots

Trying to get a video might be annoying because it doesn't always happen.

**Comment by rustdesk** [comment]
This is know, that's why we add this option to turn it off.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/6296
