### ISSUE TITLE
Another Unsupported display server tty, x11 expected 

### ISSUE THREAD

**Issue by costel78** [rustdesk/rustdesk#8588]
### Bug Description

Unsupported display server tty, x11 expected
Using Gentoo Linux with Xfce DE. Patch proposed.

### How to Reproduce

Start X server via console (startx) using bash_profile and .xinitrc
.bash_profile
`...
if [[ ! ${DISPLAY} && ${XDG_VTNR} == 1 && $(tty) == /dev/tty1 ]]; then
  export GTK_THEME=Adwaita:dark
  exec startx &>/dev/null
fi
`
.xinitrc
`exec startxfce4`

`costel@gentoo ~ $ ps -e | grep tty
   2270 tty1     00:00:00 login
   2501 tty1     00:00:00 startx
   2526 tty1     00:00:00 xinit
   2527 tty1     00:00:03 X
   2563 tty1     00:00:00 xfce4-session
   2608 tty1     00:00:00 xfwm4
   2627 tty1     00:00:00 xfsettingsd
   2643 tty1     00:00:00 xfce4-panel
   2648 tty1     00:00:00 Thunar
   2654 tty1     00:00:00 xfdesktop
   2660 tty1     00:00:00 xfce4-power-man
   2662 tty1     00:00:00 polkit-gnome-au
   2666 tty1     00:00:00 nm-applet
....`

In rustdesk connection window I got "Unsupported display server tty, x11 expected"

### Expected Behavior

With this patch, issue is gone - alsa searching for startx:
`--- a/libs/hbb_common/src/platform/linux.rs.orig	2024-06-23 06:39:44.000000000 +0300
+++ b/libs/hbb_common/src/platform/linux.rs	2024-07-02 21:15:35.047501684 +0300
@@ -98,7 +98,7 @@
                     .replace("TTY=", "")
                     .trim_end()
                     .into();
-                if let Ok(xorg_results) = run_cmds(&format!("ps -e | grep \"{tty}.\\\\+Xorg\""))
+                if let Ok(xorg_results) = run_cmds(&format!("ps -e | grep -e \"{tty}.\\\\+startx\\|{tty}.\\\\+Xorg\""))
                 // And check if Xorg is running on that tty
                 {
                     if xorg_results.trim_end() != "" {
`

### Operating system(s) on local side and remote side

Gentoo Linux

### RustDesk Version(s) on local side and remote side

1.2.6

### Screenshots

No screenshot

**Comment by costel78** [comment]
[misc2.patch.txt](https://github.com/user-attachments/files/16082457/misc2.patch.txt)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/92f570831d2ae7a772fa7dde0e764cf562416c68 
I think no need to do such check, return x11 for all tty.
