### ISSUE TITLE
Version 1.2.6 cannot connect to the Windows 7 operating system

### ISSUE THREAD

**Issue by 755713372** [rustdesk/rustdesk#8590]
### Bug Description

Unable to connect to a Windows 7 computer, and when connecting to a Windows 7 computer, a black screen appears. The Windows 10 operating system experiences slow connection speeds or even fails to connect to remote computers.

### How to Reproduce

Installing software in Windows 7 system, unable to connect to this computer through other computers

### Expected Behavior

-

### Operating system(s) on local side and remote side

windows10->windows7

### RustDesk Version(s) on local side and remote side

1.2.6

### Screenshots

![微信截图_20240703201036](https://github.com/rustdesk/rustdesk/assets/32669654/2074bce7-68db-4a9e-a1f9-c83926ce2985)

**Comment by rustdesk** [comment]
#763
