### ISSUE TITLE
The start menu content of Win11 cannot be displayed remotely

### ISSUE THREAD

**Issue by Fcscanf** [rustdesk/rustdesk#8592]
### Bug Description

When clicking on the start menu on a remote Win11 device, the control party cannot see the start menu screen, but the status of the menu can be seen as active
![GIF 2024-7-3-星期三 20-59-03](https://github.com/rustdesk/rustdesk/assets/27654200/c2424d8d-a792-4dfd-bca6-56e7fa427994)
And when clicking on Win11 settings, ghosting appears on the screen, the previous menu screen is still there, the left menu bar has scrolled, but the content seen by the control party has not been updated, Like this:
![image](https://github.com/rustdesk/rustdesk/assets/27654200/b706d2b3-cec3-4901-9d87-39a9bd32b373)
The remote management interface of Rustdesk cannot see the screen content on the control end
![image](https://github.com/rustdesk/rustdesk/assets/27654200/b643c352-0c30-49ba-9ae4-8937681be622)
The main interface of RustDesk is also white and invisible
![image](https://github.com/rustdesk/rustdesk/assets/27654200/1210b28b-22f3-4de1-9f40-69f817bee5bc)

### How to Reproduce

Remote Win11 device click on start menu and system settings application

### Expected Behavior

The start menu function is displayed normally, and the settings interface is loaded normally

### Operating system(s) on local side and remote side

win11 -> win11

### RustDesk Version(s) on local side and remote side

1.2.4->1.2.4

### Screenshots

see Bug Description

**Comment by 21pages** [comment]
https://github.com/rustdesk/rustdesk/pull/8191 try 1.2.6

**Comment by Fcscanf** [comment]
Version 1.2.6 is also not shown
![image](https://github.com/rustdesk/rustdesk/assets/27654200/a83a5c5c-e5a5-4a1c-95be-518fd7595a30)

**Comment by Nollasko** [comment]
#4296

**Comment by Fcscanf** [comment]
@Nollasko I have disabled the Capture screen using DirectX option and resolved the issue. Thank you
