### ISSUE TITLE
Failed to obtain screen capture in Plasma 6 with Wayland session (KDE Neon)

### ISSUE THREAD

**Issue by linlinxza** [rustdesk/rustdesk#8600]
### Bug Description

Does not work with Plasma 6 with Wayland session - Use KDE Neon. Just says "Failed to obtain screen capture."

### How to Reproduce

Install Rustdesk. Run as usual on a distro with Plasma 6. Then try to connect to that system. Use KDE Neon as the distro (but I'm sure any distro with Plasma 6 running a Wayland session should suffice).

### Expected Behavior

Should just work. Screen Cast works with other applications like OBS on my system. But with Rustdesk (with uses Screen Cast), it doesn't work.

### Operating system(s) on local side and remote side

KDE Neon (both local and remote)

### RustDesk Version(s) on local side and remote side

1.2.3 > 1.2.6

### Screenshots

![Screenshot_20240703_170736](https://github.com/rustdesk/rustdesk/assets/11242593/ad2c7b30-6a84-4dd8-ade9-5021f5785520)

### Additional Context

So, this is apparently just an issue with Plasma 6 on a Wayland session.

**Comment by rustdesk** [comment]
@21pages

**Comment by 21pages** [comment]
Could you try switch to x11 from wayland?

**Comment by 21pages** [comment]
Could you try this program to see if it can take screenshots successfully?https://github.com/21pages/rustdesk/releases/download/tmp/xcap, it's compiled from https://github.com/nashaofu/xcap

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by rustdesk** [comment]
Close as trace by #3565

**Comment by miaomiao1992** [comment]
https://github.com/rustdesk/rustdesk/blob/1.2.7/libs/scrap/src/wayland/pipewire.rs#L584

it seems like streams_res is empty.

**Comment by fufesou** [comment]
Maybe it's a bug of kde neon.
Upgrading pipewire works for me. `neon-user-20240725-0828.iso`

https://mastodon.social/@talesofaprinny/112684096504021198

https://obsproject.com/forum/threads/pipewire-error-after-update-kde-neon.176872/post-652321

https://pipewire-debian.github.io/pipewire-debian/

**Comment by fufesou** [comment]
"Open" action in the tray menu (`xdg-open rustdesk://`) will report "Could not read file rustdesk://."

After upgrading `pipewire` above and reinstall RustDesk, it is also fixed.

**Comment by linlinxza** [comment]
> Maybe it's a bug of kde neon. Upgrading `pipewire` works for me. `neon-user-20240725-0828.iso`
> 
> https://mastodon.social/@talesofaprinny/112684096504021198
> 
> https://obsproject.com/forum/threads/pipewire-error-after-update-kde-neon.176872/post-652321
> 
> https://pipewire-debian.github.io/pipewire-debian/
> 
> ```
> sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream
> sudo add-apt-repository ppa:pipewire-debian/wireplumber-upstream
> sudo apt-get update
> 
> sudo apt install gstreamer1.0-pipewire libpipewire-0.3-{0,dev,modules} libspa-0.2-{bluetooth,dev,jack,modules} pipewire{,-{audio-client-libraries,pulse,bin,jack,alsa,v4l2,libcamera,locales,tests}}
> 
> sudo apt-get install wireplumber{,-doc} gir1.2-wp-0.4 libwireplumber-0.4-{0,dev}
> ```

I prefer to avoid adding extra PPAs that don't come with the base distro.

**Comment by linlinxza** [comment]
> Maybe it's a bug of kde neon. Upgrading `pipewire` works for me. `neon-user-20240725-0828.iso`
> 
> https://mastodon.social/@talesofaprinny/112684096504021198
> 
> https://obsproject.com/forum/threads/pipewire-error-after-update-kde-neon.176872/post-652321
> 
> https://pipewire-debian.github.io/pipewire-debian/
> 
> ```
> sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream
> sudo add-apt-repository ppa:pipewire-debian/wireplumber-upstream
> sudo apt-get update
> 
> sudo apt install gstreamer1.0-pipewire libpipewire-0.3-{0,dev,modules} libspa-0.2-{bluetooth,dev,jack,modules} pipewire{,-{audio-client-libraries,pulse,bin,jack,alsa,v4l2,libcamera,locales,tests}}
> 
> sudo apt-get install wireplumber{,-doc} gir1.2-wp-0.4 libwireplumber-0.4-{0,dev}
> ```

So, how do you purge the PPA?

Because when I need to upgrade, I need to remove this PPA. I tried using `sudo ppa-purge ppa:pipewire-debian/pipewire-upstream` 

After, it leaves with broken packages. Saying: `libpipewire-0.3-0 : Depends: libspa-0.2-modules (= 1.0.7-3~ubuntu22.04) but 0.3.48-1ubuntu1 is installed` when I try to run `sudo apt --fix-broken install`

**Comment by rustdesk** [comment]
OBS fails with pipewire either, xcap works, but it uses a slow screenshot api.

<img width="525" alt="image" src="https://github.com/user-attachments/assets/d69242e5-1e04-46b9-a591-9377f19d0cd4">

<img width="305" alt="image" src="https://github.com/user-attachments/assets/f5b331d3-c72b-4287-8673-abdce2b70e05">

**Comment by fufesou** [comment]
> So, how do you purge the PPA?

> Because when I need to upgrade, I need to remove this PPA. I tried using `sudo ppa-purge ppa:pipewire-debian/pipewire-upstream`

> After, it leaves with broken packages. Saying: `libpipewire-0.3-0 : Depends: libspa-0.2-modules (= 1.0.7-3~ubuntu22.04) but 0.3.48-1ubuntu1` is installed when I try to run `sudo apt --fix-broken install`

Sorry, I didn't think of your scenario.
I just tried your commands and got the same error. I haven't found how to purge the PPA correctly yet.

https://pipewire-debian.github.io/pipewire-debian/#:~:text=ignore%20this)%20(Optional)-,Uninstalling,-If%20PipeWire%20was

It seems we need to downgrade the packages firstly, then purge the PPA.

I've added the PPA back. But it's a little hard to find how to downgrade all the packages.

**Comment by linlinxza** [comment]
> It seems we need to downgrade the packages firstly, then purge the PPA.

And how do we do that?

**Comment by fufesou** [comment]
Sorry, I still can't find the right way after some attempts.

I've tried manually run ` sudo apt install pipewire-pulse=0.3.48-1ubuntu3 pipewire=0.3.48-1ubuntu3 libpipewire-0.3-modules=0.3.48-1ubuntu3 pipewire-bin=0.3.48-1ubuntu3 libpipewire-0.3-0=0.3.48-1ubuntu3 libpipewire-0.3-0=0.3.48-1ubuntu3 libspa-0.2-modules=0.3.48-1ubuntu3` after adding the ppa `sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream && sudo apt update` back.

```
dpkg: warning: downgrading pipewire-pulse from 1.0.7-3~ubuntu22.04 to 0.3.48-1ubuntu3
(Reading database ... 238186 files and directories currently installed.)
Preparing to unpack .../pipewire-pulse_0.3.48-1ubuntu3_amd64.deb ...
Unpacking pipewire-pulse (0.3.48-1ubuntu3) over (1.0.7-3~ubuntu22.04) ...
dpkg: error processing archive /var/cache/apt/archives/pipewire-pulse_0.3.48-1ubuntu3_amd64.deb (--unpack):
 trying to overwrite '/usr/share/man/man1/pipewire-pulse.1.gz', which is also in package pipewire-bin 1.0.7-3~ubuntu22.04
dpkg: warning: downgrading libspa-0.2-modules:amd64 from 1.0.7-3~ubuntu22.04 to 0.3.48-1ubuntu3
Preparing to unpack .../libspa-0.2-modules_0.3.48-1ubuntu3_amd64.deb ...
Unpacking libspa-0.2-modules:amd64 (0.3.48-1ubuntu3) over (1.0.7-3~ubuntu22.04) ...
Errors were encountered while processing:
 /var/cache/apt/archives/pipewire-pulse_0.3.48-1ubuntu3_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

No idea why it cannot be added back. There seems to be a problem with nested references.

```
$ sudo dpkg -i /var/cache/apt/archives/pipewire-pulse_0.3.48-1ubuntu3_amd64.deb
dpkg: warning: downgrading pipewire-pulse from 1.0.7-3~ubuntu22.04 to 0.3.48-1ubuntu3
(Reading database ... 238182 files and directories currently installed.)
Preparing to unpack .../pipewire-pulse_0.3.48-1ubuntu3_amd64.deb ...
Unpacking pipewire-pulse (0.3.48-1ubuntu3) over (1.0.7-3~ubuntu22.04) ...
dpkg: error processing archive /var/cache/apt/archives/pipewire-pulse_0.3.48-1ubuntu3_amd64.deb (--install):
 trying to overwrite '/usr/share/man/man1/pipewire-pulse.1.gz', which is also in package pipewire-bin 1.0.7-3~ubuntu22.04
Processing triggers for man-db (2.10.2-1) ...
Not building database; man-db/auto-update is not 'true'.
Errors were encountered while processing:
 /var/cache/apt/archives/pipewire-pulse_0.3.48-1ubuntu3_amd64.deb
```

**Comment by linlinxza** [comment]
Yeah. I came to something like that too with pipewire-pulse. So, really, all I have is a headache now. I am glad I just installed this on one system. But now I am trying to figure out how to downgrade fully in a virtual machine.

**Comment by linlinxza** [comment]
Anyway, I figured it out. You can use Synaptic Package Manager to force the version of libpipewire-0.3-0. By selecting the 0.3.48-1ubuntu3 version, I was able to purge the PPA without breaking packages.

However, I don't know the command line equivalent to achieve this.

**Comment by rustdesk** [comment]
Even though, https://github.com/rustdesk/rustdesk/issues/9026#issuecomment-2282791931

**Comment by martin-braun** [comment]
@rustdesk why can't this dependency be part of Flatpak. I thought that's the point of Flatpak, to contain all its dependencies.

I'm on Debian, I want a rock solid OS that doesn't break. Please don't force me to sacrifice my stability in order to use your Flatpak. 

Do I really have to run RustDesk in `distrobox`, I've no idea if this will even enable unattended mode to me, but it's painful to deal with.

**Comment by raizer88** [comment]
@rustdesk just as FYI, I used rustdesk no problem on my Raspberry Pi 400 until today that I sudo upgraded, and I got the error:

"Failed to obtain screen capture. You may need to upgrade the PipeWire library for better compatibility. Please check https://github.com/rustdesk/rustdesk/issues/8600#issuecomment-2254720954 for more details."

So either @rustdesk you fix the problem, or you are not compatible anymore with any Raspberry Pi.

**Comment by linlinxza** [comment]
> @rustdesk just as FYI, I used rustdesk no problem on my Raspberry Pi 400 until today that I sudo upgraded, and I got the error:
> 
> "Failed to obtain screen capture. You may need to upgrade the PipeWire library for better compatibility. Please check [#8600 (comment)](https://github.com/rustdesk/rustdesk/issues/8600#issuecomment-2254720954) for more details."
> 
> So either @rustdesk you fix the problem, or you are not compatible anymore with any Raspberry Pi.

That's what I said to them; to make Wayland their utmost priority. And when I made the same issue with a newer version, one dev told me they would ban me.

PS: I read that Raspberry PI OS has gone Wayland by default. Now that 1.3.2 is out, hopefully it will work for me too.

**Comment by AlexandreBonneau** [comment]
For info, 1.3.2 does not fix the problem on Debian trixie, which runs Wayland.

**Comment by voidxela** [comment]
I just ran into this issue on the latest KDE Neon, resolved easily with the upstream PPAs. Agreed that this should be bundled in somehow but I don't mind much, as long as it works. I was confused at first because the error message linked specifically to this comment: https://github.com/rustdesk/rustdesk/issues/8600#issuecomment-2254720954

That's for _reverting_ the change, not applying it. This did the trick for me:
```
sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream
sudo add-apt-repository ppa:pipewire-debian/wireplumber-upstream
sudo pkcon update
```

If you're not on Neon you'll want `apt update` instead of `pkcon`.

**Comment by sadhin555** [comment]
⚠️ Failed to obtain screen capture. You may need to upgrade the PipeWire library for better compatibility. 

Please check↩️ https://github.com/rustdesk/rustdesk/issues/8600#issuecomment-2254720954 

✅ For more details.

**Comment by officialh1** [comment]
> Anyway, I figured it out. You can use Synaptic Package Manager to force the version of libpipewire-0.3-0. By selecting the 0.3.48-1ubuntu3 version, I was able to purge the PPA without breaking packages.
> 
> However, I don't know the command line equivalent to achieve this.
> 
> EDIT:
> 
> The command, after much trial and error in the VM to completely downgrade is this: `sudo apt install libpipewire-0.3-{0,modules}=0.3.48-1ubuntu3 libspa-0.2-modules=0.3.48-1ubuntu3 pipewire{,-bin}=0.3.48-1ubuntu3`
> 
> Then the Pipewire PPA can be successfully purged.

I am lost a bit, so many threads here about Raspberry Pi then Neon, PopOS, COSMIC....

I have a brand-new Pi 5, latest updates, started failing because of missing components (I suspected since running rustdesk --service produced those errors) although I was able to connect get one screen and then it would freeze. I added them and now I get a URL pointing here as a message and I am not sure there is a resolution to my problem.

File transfer and TCP tunneling work fine and stable.

**Comment by officialh1** [comment]
> > Anyway, I figured it out. You can use Synaptic Package Manager to force the version of libpipewire-0.3-0. By selecting the 0.3.48-1ubuntu3 version, I was able to purge the PPA without breaking packages.
> > However, I don't know the command line equivalent to achieve this.
> > EDIT:
> > The command, after much trial and error in the VM to completely downgrade is this: `sudo apt install libpipewire-0.3-{0,modules}=0.3.48-1ubuntu3 libspa-0.2-modules=0.3.48-1ubuntu3 pipewire{,-bin}=0.3.48-1ubuntu3`
> > Then the Pipewire PPA can be successfully purged.
> 
> I am lost a bit, so many threads here about Raspberry Pi then Neon, PopOS, COSMIC....
> 
> I have a brand-new Pi 5, latest updates, started failing because of missing components (I suspected since running rustdesk --service produced those errors) although I was able to connect get one screen and then it would freeze. I added them and now I get a URL pointing here as a message and I am not sure there is a resolution to my problem.
> 
> File transfer and TCP tunneling work fine and stable.

Okay I am running dark mode and there was other text other than this link and was difficult to see at on a surface laptop studio 2 but noticed it when I moved to monitor 2. You need that text to be white when dark mode is on, please :)

I have updated everything, and I see the versions are certainly updated. I am still getting the same message. With the wild path of AI I was able to, at one point, start receiving a un/pw request, which was different but fails to show an image still. There are a ton of logs to review, and this takes some time to troubleshoot, I think I am going to just use VNC (it had stability issues too but the updates to review, et al fixed it) but use RustDesk to run the tunnel for now until this is fixed. I guess I will check back in 6 months or so...

**Comment by tojestzart** [comment]
Debian 12 not working EOT

**Comment by rmdes** [comment]
it used to work perfectly for me with Fedora 42 ,Gnome Wayland and then I upgraded to Fedora 43.. and had this odd idea to give a try to Plasma 6... and I landed from rustdeck in this GitHub thread. seems a lost battle by the looks of it?

**Comment by h879628981-pixel** [comment]
升到最新版rustdesk能否解决？

**Comment by sunshine971115** [comment]
Failed to obtain screen capture. You may need to upgrade the PipeWire library for better compatibility. Please check https://github.com/rustdesk/rustdesk/issues/8600#issuecomment-2254720954 for more details.

This error occurs when connecting to a remote computer.
