### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by matthiasg** [rustdesk/rustdesk#8606]
### Bug Description

I see that https://github.com/rustdesk/rustdesk/issues/8486 was closed referring to piping the output

Apart from not working for eg. **"--connect"** it is also quite unintuitive and not a workaround even available in some environments. In my case I would like to configure starting rustdesk to connect to another machine, but the main program does not support piped calls, just direct exe calls. 

Has anyone investigated why it even happens ? It seems not to be an issue with normal rust programs using clap as I never had any issues like this with it.

### How to Reproduce

call `rustdesk --version`

### Expected Behavior

Output of version

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.2.6

### Screenshots

No required

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/wiki/FAQ#command-line-output-on-windows

**Comment by rustdesk** [comment]
There is reason, but I have no interest to explain, we are not here to teach.
