### ISSUE TITLE
I found that the remote connection speed on the web side is much faster than the client side speed

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#861]
### Discussed in https://github.com/rustdesk/rustdesk/discussions/815

<div type='discussions-op-text'>

<sup>Originally posted by **youhers** June 19, 2022</sup>
The client always needs to go around in circles for a long time to connect to the controlled end, but the web page does not. It can be connected with one click. What is the situation?</div>

**Comment by rustdesk** [comment]
Wondering if some one can propose a better solution to reduce the attempt time.

**Comment by rustdesk** [comment]
Seems most slowness reported, host hbbr/hbbs in intranet or via Synogy with some type of router.

https://github.com/rustdesk/rustdesk-server/issues/24

**Comment by LJH1024** [comment]
你好，网页测试版怎么使用，我一直很困惑
