### ISSUE TITLE
自建服务器的一些问题

### ISSUE THREAD

**Issue by Green1ee** [rustdesk/rustdesk#862]
1.重为使用过rustdesk的电脑，通过文件名（rustdesk-host=10.xx.xx.xx,key=9Ovw9VxxMWv01iMRDQ=.exe）的方式设置了host和key，直接连接会提示无法连接到中继服务器，需要手工去添加中继服务器地址
2.hbbs和hbbr以及控制端和被控端都设置了key，但是连接成功后还是显示非加密中继器连接
3.通过RDP连接成功后显示为黑屏，无法操作
4.本地通过windows自带远程工具mstsc连接秒通，说明网络本身是非常快的，但通过rustdesk连接响应要等约1分多钟(有时10来秒)

客户端、服务端版本均为1.1.9

![image](https://user-images.githubusercontent.com/9738666/175510825-754add7b-857e-4707-8702-00387d23b5ef.png)
![image](https://user-images.githubusercontent.com/9738666/175511071-13eeab4a-3260-4bba-86b5-d823d970b487.png)
![image](https://user-images.githubusercontent.com/9738666/175511446-3e0f0e31-5c9c-4d01-9a9e-eef07cec8ce3.png)
![image](https://user-images.githubusercontent.com/9738666/175511822-9236a97c-3603-44ec-9174-9568380160f3.png)

**Comment by rustdesk** [comment]
for 4）please check： https://github.com/rustdesk/rustdesk/issues/861

For the others,  https://github.com/rustdesk/rustdesk/discussions/763

Again: English pelease.
