### ISSUE TITLE
I have to set the relay server address in the network settings can only client 2 for client 1 to connect properly

### ISSUE THREAD

**Issue by Fansirsqi** [rustdesk/rustdesk#8621]
### Bug Description

In client 2, I modified rustdesk.exe according to the official documentation to rustdesk-host=,key=.exe. When I try to connect to client 2 from client 1, I get the message “Unable to connect to the relay server: Please try again later.” I have to set the relay server address in the network settings can only client 2 for client 1 to connect properly.

### client 1 net config

![image](https://github.com/rustdesk/rustdesk/assets/38542005/da2f5ad1-c3e4-4295-931e-017006396a6b)

### client 2 about and net config

![image](https://github.com/rustdesk/rustdesk/assets/38542005/29704dc9-4489-4943-ba92-a4308e17ead4)

![image](https://github.com/rustdesk/rustdesk/assets/38542005/e8349179-0690-416d-ad05-55076412ffc8)

### client 1 to client 2 connection results

![image](https://github.com/rustdesk/rustdesk/assets/38542005/cdd6854a-8a68-4df6-9705-7aba454ae3bb)

## Passed Case

set the relay server address in the network settings in client 2 and applyed it

### client 2 net config

![image](https://github.com/rustdesk/rustdesk/assets/38542005/febfbdf6-7ed4-4ef3-a61c-2540c45dd053)

### client 1 to client 2 connection results

![image](https://github.com/rustdesk/rustdesk/assets/38542005/e13c74dd-3230-4b56-a7be-488e6beaf398)

### Expected Behavior

all in issues Reproduce

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.2.6

### Screenshots

all in Reproduce

### Additional Context

all in Reproduce

**Comment by rustdesk** [comment]
#763
