### ISSUE TITLE
German Keyboard Mapping problem with Version 1.2.6

### ISSUE THREAD

**Issue by geraldurbas** [rustdesk/rustdesk#8626]
### Bug Description

Keyboard mapping is much better in these latest version.
But the @ and \ key with ALT GT are not working.

What is a surprise because € ² ³ and other ALT Gr Keys work 

### How to Reproduce

Install Version 1.2.6 on both sides

### Expected Behavior

Working @ and \

### Operating system(s) on local side and remote side

windows 10 > ubuntu

### RustDesk Version(s) on local side and remote side

1.2.6 > 1.2.6

### Screenshots

hard...

**Comment by rustdesk** [comment]
Could you please confirm same to this https://github.com/rustdesk/rustdesk/issues/8599#issuecomment-2209274270?

**Comment by geraldurbas** [comment]
> Could you please confirm if this is same to [#8599 (comment)](https://github.com/rustdesk/rustdesk/issues/8599#issuecomment-2208933888)?

not exactly... i use an german/austrian keyboard layout.

But found following: Its the Keyboard Compatibility Mode, that causes the problem!
![image](https://github.com/rustdesk/rustdesk/assets/121263/cafb0dc1-975b-4948-a6bf-635dd5304f88)

the 2 other options transmit my @ and \ keys correct.

**Comment by rustdesk** [comment]
That's why it is called legacy mode.
