### ISSUE TITLE
After the private mode is enabled, the right-clicks not working

### ISSUE THREAD

**Issue by telppa** [rustdesk/rustdesk#8627]
### Bug Description

After the private mode is enabled, the right-clicks not working

### How to Reproduce

1. enabled private mode
2. right click

### Expected Behavior

Generate a right-click

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.2.6

### Screenshots

no screenshot

### Additional Context

Tested with a laptop

_No response_

**Comment by rustdesk** [comment]
Use mode 2 please.

**Comment by telppa** [comment]
> Use mode 2 please.
> 
> There is no way to fix since out of our control.

Have tried mode 2 and it still doesn't work

**Comment by telppa** [comment]
> Use mode 2 please.
> 
> There is no way to fix since out of our control.

Have tried mode 2 and it still doesn't work

**Comment by fufesou** [comment]
@telppa Hi, I've tested these two modes. I can right click through RustDesk.

RustDesk will block the others' input including physical keyboard and mouse events in privacy mode.

There's no special logic for right clicks.
Only right clicks not working? Are the keys input ok?

**Comment by telppa** [comment]
> @telppa Hi, I've tested these two modes. I can right click through RustDesk.
> 
> RustDesk will block the others' input including physical keyboard and mouse events in privacy mode.
> 
> There's no special logic for right clicks. Only right clicks not working? Are the keys input ok?

Sorry, my physical display is missing and I can't test again.

**Comment by fufesou** [comment]
> RustDesk will block the others' input including physical keyboard and mouse events in privacy mode.

No need to test, just illustrate here.

> There's no special logic for right clicks. Only right clicks not working? Are the keys input ok?

How about this?

**Comment by telppa** [comment]
> > RustDesk will block the others' input including physical keyboard and mouse events in privacy mode.
> 
> No need to test, just illustrate here.
> 
> > There's no special logic for right clicks. Only right clicks not working? Are the keys input ok?
> 
> How about this?

@fufesou Since I lost my physical monitor, I can't enable privacy mode right now, so I can't answer this question.

**Comment by telppa** [comment]
I tested it again, and the reason the right-click for mode1 & mode2 doesn't work is a conflict with the software `MouseGestureL`.
