### ISSUE TITLE
Settings > Security > Enable Remote Configuration Modification 

### ISSUE THREAD

**Issue by DCVolo** [rustdesk/rustdesk#8633]
### Bug Description

Settings > Security > Enable Remote Configuration Modification, default state is disabled.

But it can be modified remotely.

Litteraly my first 15s of use.

### How to Reproduce

Select any other window
ALT-TAB back to RustDeskp
Navigate through the menu using TAB and arrows
press enter to apply changes

### Expected Behavior

Window should be unresponsive from any type of input

### Operating system(s) on local side and remote side

Windows 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.6

### Screenshots

[Screen Recording 2024-07-07 184923.zip](https://github.com/user-attachments/files/16120070/Screen.Recording.2024-07-07.184923.zip)

### Additional Context

file is MKV x265

First thing happening is me showing that having the option pre-selected i can enable/disable the option at will.
Then it describes the steps i provided.

**Comment by rustdesk** [comment]
duplicate https://github.com/rustdesk/rustdesk/issues/2680#issuecomment-1975002181

**Comment by rustdesk** [comment]
close since fix merged
