### ISSUE TITLE
After turning on privacy mode, right-clicking the mouse has no effect

### ISSUE THREAD

**Issue by lxlalalala** [rustdesk/rustdesk#8639]
### Bug Description

After turning on privacy mode, right-clicking the mouse has no effect, including the mouse gesture function. Only double-clicking the right button will work.

### How to Reproduce

Turn on privacy mode, either 1 or 2，than right click anywhere，it won't work。

### Expected Behavior

I hope that after turning on privacy mode, right-click and mouse gestures can also work normally, just like when not turning on privacy mode.

### Operating system(s) on local side and remote side

windows 10 -> windows 11

### RustDesk Version(s) on local side and remote side

1.2.6 -> 1.2.6

### Screenshots

no picture

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/8627#issuecomment-2213091514
