### ISSUE TITLE
IPad IOS 17.5.1 no Adressbook by Login

### ISSUE THREAD

**Issue by Thiwico** [rustdesk/rustdesk#8646]
### Bug Description

Hello,

We use Rustdesk Pro and have the problem on the iPad that when you log in, the shared address book is not visible.

An error message appears with Ivalid tokens.

Manually connecting to the server works without problems.

That would mean that the ID/relay server settings are OK.

These problems do not exist on the Windows client.

### How to Reproduce

1. Delete the APP
2. Reinstall the APP
3. ID/server settings
4. Login

### Expected Behavior

Viewing the Shared Address Book

### Operating system(s) on local side and remote side

IOS 15.7.1

### RustDesk Version(s) on local side and remote side

RustDesk Server Pro 1.3.10 > Rustdesk ios 1.2.2

### Screenshots

![20240708_122839000_iOS](https://github.com/rustdesk/rustdesk/assets/82508582/19009436-0468-4a29-869a-3dc6bdd5b3be)

**Comment by rustdesk** [comment]
https://x.com/rustdesk/status/1804531445576220990
