### ISSUE TITLE
warning of virus "a.gray.RacketeerlM.b" by my Samsung phone

### ISSUE THREAD

**Issue by chiwhalee** [rustdesk/rustdesk#8657]
### Bug Description

see the picture

### How to Reproduce

no

### Expected Behavior

no

### Operating system(s) on local side and remote side

Android 14

### RustDesk Version(s) on local side and remote side

1.2.3 
The apk was downloaded from your github page

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/2557151/97e0b9ea-ba78-4de7-86a4-db36268e648b)
![image](https://github.com/rustdesk/rustdesk/assets/2557151/7d358c59-3668-439a-ba98-b794700e8ae7)

**Comment by rustdesk** [comment]
I like this warning.
