### ISSUE TITLE
Not working at all on Plasma 6 Wayland (Failed to obtain screen capture)

### ISSUE THREAD

**Issue by linlinxza** [rustdesk/rustdesk#8667]
### Bug Description

Failed to obtain screen capture.

### How to Reproduce

Install a distro that has Plasma 6 and use Wayland as the session.

### Expected Behavior

Should just work.

### Operating system(s) on local side and remote side

KDE Neon

### RustDesk Version(s) on local side and remote side

1.2.6

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/11242593/66dc3fe3-f608-4c99-988b-a6355a5d716c)

**Comment by rustdesk** [comment]
close to favor https://github.com/rustdesk/rustdesk/issues/8600

**Comment by rustdesk** [comment]
Please help test https://github.com/rustdesk/rustdesk/issues/8600#issuecomment-2207953508

**Comment by linlinxza** [comment]
> Please help test [#8600 (comment)](https://github.com/rustdesk/rustdesk/issues/8600#issuecomment-2207953508)

I made that issue originally. But now I discovered that this isn't an AMD graphics issue. Rustdesk is failing to capture the screen even on a fresh install with the latest version of Plasma 6.
