### ISSUE TITLE
iPad Pro iPadOS 17.5.1 - Rustdesk 1.2.6 (45) via TestFlight (1.2.2 same behavior) - cannot do any action on the screen

### ISSUE THREAD

**Issue by EmmanuelJacobs** [rustdesk/rustdesk#8670]
### Bug Description

cannot do any action on the screen
after getting rid of app from "memory" a kind of "crash report" message appear.

I can assist test things, install other testflight betas, live troubelshoot, ...

### How to Reproduce

Clear out any other app "in memory", reboot iPadOS, type in pin code, start RustDesk.

### Expected Behavior

we can interact with RustDesk on the touch screen

### Operating system(s) on local side and remote side

iPadOS 17.5.1 > n/a

### RustDesk Version(s) on local side and remote side

1.2.6 (45) via TestFlight (1.2.2 same behavior) > n/a

### Screenshots

<img width="674" alt="iPadOS version" src="https://github.com/rustdesk/rustdesk/assets/14026455/21a97b2d-694c-491d-bdd3-e4110aee1457">
<img width="430" alt="RustDesk iPadOS version" src="https://github.com/rustdesk/rustdesk/assets/14026455/70e07092-28fc-4438-b66e-ced42ad05d61">

https://github.com/rustdesk/rustdesk/assets/14026455/0666dc6f-ef51-4bca-af39-1f61986be5f2

**Comment by EmmanuelJacobs** [comment]
Oh and btw, I reported the crash once using anotehr email than the one used for login in GitHub.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893

**Comment by rustdesk** [comment]
This ipados 17.5.2 https://github.com/rustdesk/rustdesk/issues/8390 works well though having physical keyboard issue

**Comment by EmmanuelJacobs** [comment]
I de-installed and re-installed TestFlight 1.2.6 (45) and it indeed work again.

**Comment by EmmanuelJacobs** [comment]
When going from main 1.2.2 from Apple Store to 1.2.6 (45) I thought it was like first version de-installed, second installed but not it seems. Thank-you very much !

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/9717
