### ISSUE TITLE
Windows 11 controls Android 13 phone, keyboard pops up when inputting content but no screen is displayed

### ISSUE THREAD

**Issue by 1459586433** [rustdesk/rustdesk#8671]
### Bug Description

Windows 11 controls Android 13 phones. When inputting content, the keyboard pops up but the screen is not displayed. The same problem occurs when using the phone to control the Android phone

### How to Reproduce

Windows 11 controls Android 13 phones. When inputting content, the keyboard pops up but the screen is not displayed. The same problem occurs when using the phone to control the Android phone

### Expected Behavior

Windows 11 controls Android 13 phones. When inputting content, the keyboard pops up but the screen is not displayed. The same problem occurs when using the phone to control the Android phone

### Operating system(s) on local side and remote side

windows11

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.6

### Screenshots

![(E$WB1_J%90SSC3)G3Q$YPR](https://github.com/rustdesk/rustdesk/assets/131569031/71fc593e-4093-4026-9fde-ae9e3767a198)
![bd30f8ef30bed40135f5243dcfc0261](https://github.com/rustdesk/rustdesk/assets/131569031/222b3557-0402-4c7b-9284-ca14d1101375)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893
