### ISSUE TITLE
Windows 7 cannot close home page

### ISSUE THREAD

**Issue by zhangbo8418** [rustdesk/rustdesk#8676]
### Bug Description

Windows 7 cannot close home page

### How to Reproduce

Watch the video below

### Expected Behavior

Can be closed normally

### Operating system(s) on local side and remote side

Windows7

### RustDesk Version(s) on local side and remote side

1.2.7

### Screenshots

https://github.com/rustdesk/rustdesk/assets/46797568/75636fde-c69f-4e62-a264-a4b62f8ddb2e

**Comment by 21pages** [comment]
What version is your win7?

**Comment by rustdesk** [comment]
We won't spend time on Win7, use sciter version please.
