### ISSUE TITLE
Wake up after sleep can't connect

### ISSUE THREAD

**Issue by K2M74** [rustdesk/rustdesk#868]
**Describe the bug you encountered:**

When you wake up after sleeping, there is a certain chance that you will not be able to connect, indicating that the ID is not online. After comparison:
There will be two UDP connections when online normally (because I installed the server on the router).
![2022-06-26_13-07-20](https://user-images.githubusercontent.com/50667472/175800269-72af63b1-070a-4e84-85b3-ecab8bfebccc.png)

The UDP connection sent by the router is missing when the problem occurs.
![2022-06-26_12-37-23](https://user-images.githubusercontent.com/50667472/175800230-bdb16d6e-06a9-4dd6-a17a-cf4c36c8d32f.png)

当睡眠后唤醒，有一定几率会连接不上，提示ID不在线，经过对比：
正常在线时会有两条UDP连接（因为我把服务器安装在路由器上）。
出现问题时缺少路由器发送过来的UDP连接。

**What did you expect to happen instead?**

Maybe add a check to make sure all connections are available.
My current approach is to schedule the task, restart the service and tray when a wake is detected.

也许可以增加一个检测功能确保所有连接可用。
我目前的方法是计划任务，检测到唤醒时重启服务和托盘。

**How did you install `RustDesk`?**

GitHub release

**RustDesk version and environment**
v1.1.9 Windows10 Enterprise Edition 20H2 19042.868.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/649ff52970c7a077cfe9a0aa404dca4e3d22534a

**Comment by K2M74** [comment]
我好像明白了，这是DDNS引起的问题，只是它在半夜重拨，难怪感觉挺随机的。
