### ISSUE TITLE
wrong fullscreen behavior

### ISSUE THREAD

**Issue by twprh** [rustdesk/rustdesk#8688]
### Bug Description

if remote is fullscreen and stopping remote session - screen left blank

see video

### How to Reproduce

sett remote session to fullscreen and close session.

### Expected Behavior

no blank window in front

### Operating system(s) on local side and remote side

Windows -> Windows

### RustDesk Version(s) on local side and remote side

nightly: 2024-07.11

### Screenshots

[Video.webm](https://github.com/user-attachments/assets/8653fbca-60e0-4307-a4ee-a39b5df14cc8)

### Additional Context

if remote client is offline -> blank screen and only way out is to kill rustdesk

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
1.2.6 ok?

**Comment by twprh** [comment]
yes 
nightly:1.2.6 2024-06-27 is ok

**Comment by rustdesk** [comment]
Thanks for your report

**Comment by rustdesk** [comment]
Close as fix merged, please try out tomorrow's nightly build.
