### ISSUE TITLE
Keyboard inputs are not passed from Linux client to host

### ISSUE THREAD

**Issue by monosoul** [rustdesk/rustdesk#869]
**Describe the bug you encountered:**
When I'm connecting from my Linux laptop to any other host (tried Windows, Android), keyboard inputs from the client are not passed to the host for some reason.

To make sure it's not a host issue, I tried connecting from my my Android phone to the Windows host, keyboard inputs were working just fine.

The OS I'm using is Fedora 36 with Wayland. Just in case I tried loading X11 session, the keyboard inputs didn't work there as well.

**What did you expect to happen instead?**
Keyboard inputs are passed to the remote host.

**How did you install `RustDesk`?**

- On the Linux client RustDesk is installed from this pkg: https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-fedora28-centos8.rpm
- On the Windows host RustDesk in installed from this pkg: https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-windows_x64.zip

**RustDesk version and environment**

Both the client and the hosts are running RustDesk `1.1.9`. I'm using a self-hosted server running in a container on a raspberry pi 4.

**Comment by monosoul** [comment]
As a workaround I used on-screen keyboard on the Windows host, but I'd like to help you troubleshoot and fix the issue :slightly_smiling_face:

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/406

**Comment by rustdesk** [comment]
Please make sure both sides with the same keyboard layout.

**Comment by monosoul** [comment]
Yep, both sides have the same layout, that was the first thing I checked

**Comment by rustdesk** [comment]
Wayland may be the problem, Our keyboard capture works on X11 only, wayland support is under dev. @fufesou

**Comment by monosoul** [comment]
Yeah, I know it's not supposed to work under Wayland, that's why I loaded X11 session, but had the same issue there

**Comment by rustdesk** [comment]
@fufesou  we need add wayland support in to https://github.com/open-trade/rdev for wayland.

**Comment by rustdesk** [comment]
> X11

Strange, we have no such problem.

![image](https://user-images.githubusercontent.com/71636191/175818338-b8042a4a-f039-4973-bbb5-6b8ace57fdc8.png)

**Comment by rustdesk** [comment]
Though I have never tested Fedora 36

**Comment by monosoul** [comment]
Wait, my bad. When I loaded to X11, I actually tried connecting to an Android host and keyboard inputs didn't work there. But now I have tried connecting to a Windows host and it worked. So yeah, I guess X11 session on client end works with Windows host. And I guess it's impossible to send keyboard inputs to an Android host?

**Comment by rustdesk** [comment]
> impossible

Yes

**Comment by monosoul** [comment]
Thanks for the prompt reply, I'll close the issue. Would be nice to get Wayland support at least for the client :heart:

**Comment by Hubro** [comment]
Why close the issue? Shouldn't it remain open until keyboard input on Wayland works? :slightly_smiling_face:

**Comment by monosoul** [comment]
The issue I had wasn't related to Wayland
