### ISSUE TITLE
Strategy change via command line isn't applied

### ISSUE THREAD

**Issue by MeneerikNL** [rustdesk/rustdesk#8691]
### Bug Description

When I change the strategy of a client via commandline, the new strategy isn't applied on the client. When I change the strategy via the webconsole the changes are applied within the 30 seconds.

### How to Reproduce

on the client run:
customclient.exe --assign --token {TOKEN} --strategy_name {NEWSTRATEGYNAME}

Login to the webconsole and the device is added to the new strategy, but the settings are not applied.

Move the client to a different strategy via the webconsole and the settings are applied.

### Expected Behavior

When I change the strategy via the command line  you want the strategy settings to be applied.

### Operating system(s) on local side and remote side

Windows 10 , Windows 11

### RustDesk Version(s) on local side and remote side

1.2.6.44 -> 1.3.11

**Comment by rustdesk** [comment]
https://rustdesk.com/docs/en/self-host/rustdesk-server-pro/console/#:~:text=To%20get%20output%2C%20please%20run%20like%20this

**Comment by MeneerikNL** [comment]
Output is: 
Done!

and yes in the webconsole , the devices is changed to the new strategy, but the settings of this strategy will not be applied on the client

**Comment by rustdesk** [comment]
@21pages follow it up.

**Comment by rustdesk** [comment]
Thanks for your report, the fix has been published, https://github.com/rustdesk/rustdesk-server-pro/releases/tag/1.3.12
