### ISSUE TITLE
Copying text from PyCharm results in HTML output

### ISSUE THREAD

**Issue by stdedos** [rustdesk/rustdesk#8694]
### Bug Description

Copying text from PyCharm results in pasting HTML output, instead of text

### How to Reproduce

* Open PyCharm
* Have some source code file open (e.g. Python)
* Copy some colorful part of it (e.g. `ssignattr(self, node: AssignAttr):`)
* Paste (either locally, or remote)

### Expected Behavior

* `ssignattr(self, node: AssignAttr):` text is pasted
* **Actual**: `<html><head><meta http-equiv="content-type" content="text/html; charset=UTF-8"></head><body><div style="background-color:#ffffff;color:#080808"><pre style="font-family:'Droid Sans Mono',monospace;font-size:9.0pt;"><span style="color:#00627a;">ssignattr</span>(<span style="color:#94558d;">self</span>,&#32;<span style="color:#000000;">node</span>:&#32;<span style="color:#000000;">AssignAttr</span>):</pre></div></body></html>` text appears

### Operating system(s) on local side and remote side

10.0.18363.836 -> Ubuntu 20.04.6

### RustDesk Version(s) on local side and remote side

1.2.6

### Screenshots

_It is well-explained textually_

**Comment by rustdesk** [comment]
no support html yet.

**Comment by stdedos** [comment]
There is no HTML involved AFAIK.
It's just plaintext, and that's what I'd like in my clipboard.

Please consider reopening

**Comment by fufesou** [comment]
Hi, I think it's more lated to your PyCharm settings.

> Paste (either locally, or remote)

Because it's HTML output even you paste locally. And RustDesk 1.2.6 just read the text clipboard, no HTML values.

**Comment by stdedos** [comment]
I guess you mean that?

![image](https://github.com/user-attachments/assets/dba20fe7-f6d8-4acb-87e2-04138f1c6440)

Somehow the OS knows when to paste plaintext, but RustDesk cannot tell the difference?

Because if I paste first e.g. to Sublime, and then copy from Sublime, I can paste on my computer just fine.
Directly though, it is pasting an html string, with no possibility to receive only plaintext (something like Ctrl+Shift+C does on some applications).

(It seems that also e.g. webp image copy is not working, in addition to one of [png|jpg])

**Comment by fufesou** [comment]
> Somehow the OS knows when to paste plaintext, but RustDesk cannot tell the difference?

It may be a bug on your OS. I've tried on Windows and MacOS, it works fine.

RustDesk 1.2.6 only read the plain text. No idea why it read the html content as plain text.

> 10.0.18363.836 -> Ubuntu 20.04.6

What is this OS ? 


> (It seems that also e.g. webp image copy is not working, in addition to one of [png|jpg])

Yes, 1.2.6 only support plain text.

**Comment by stdedos** [comment]
Windows 10.0.18363.836 -> Ubuntu 20.04.6

> Yes, 1.2.6 only support plain text.

Ah - I saw https://github.com/rustdesk/rustdesk/issues/683 and thought it was fixed already

> Can you please upload a video?

As soon as I toggled that setting, it doesn't work anymore 😕 

I will upload the video next time it happens
