### ISSUE TITLE
1.1.9 for Fedora rpm does not create /u/s/applications/rustdesk.desktop anymore

### ISSUE THREAD

**Issue by Cyborgscode** [rustdesk/rustdesk#871]
Rustdesk does not show up in desktop app list anymore, because the /usr/share/applications/rustdesk.desktop file is not created.

As soon as the old desktopfile is recreated i.e. manually, it reappears in the list.

...

**How did you install `RustDesk`?**

dnf update https://github.com/<path-to-newest-release.rpm>

from 1.1.8 to 1.1.9

---

FEDORA 35 Rustdesk 1.1.9 with Cinnamon

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
Thanks for report.
#911

**Comment by itamarjp** [comment]
how about packaging rust desk for fedora centos and others ?

**Comment by fufesou** [comment]
> how about packaging rust desk for fedora centos and others ?

I've read and tested the scripts.
They all seems good on upgrading.

## rpm
[`rpm.spec`](https://github.com/rustdesk/rustdesk/blob/master/rpm.spec) and [`rpm-suse.spec`](https://github.com/rustdesk/rustdesk/blob/master/rpm-suse.spec) #911 

## debian
[`DEBIAN`](https://github.com/rustdesk/rustdesk/tree/master/DEBIAN) works good.

`man dpkg`
> 
> -i, --install package-file...
>            Install the package. If --recursive or -R option is specified, package-file must refer to a directory instead.
> 
>            Installation consists of the following steps:
> 
>            1. Extract the control files of the new package.
> 
>            2. If another version of the same package was installed before the new installation, execute prerm script of the old package.
> 
>            3. Run preinst script, if provided by the package.
> 
>            4. Unpack the new files, and at the same time back up the old files, so that if something goes wrong, they can be restored.
> 
>            5. If another version of the same package was installed before the new installation, execute the postrm script of the old package. Note that this script is executed after the preinst
>            script of the new package, because new files are written at the same time old files are removed.
> 
>            6. Configure the package. See --configure for detailed information about how this is done.
> 

The scritps order of upgrading package is:
1. old prerm
2. new preinst
3. old postrm
4. new postinst

## pacman

[`pacman_install`](https://github.com/rustdesk/rustdesk/blob/master/pacman_install)

`install`, `upgrade`, `remove` are completely implemented by 6 functions. The functions are independent to each other.
