### ISSUE TITLE
Debian Unable to unlock settings (debian, xfce)

### ISSUE THREAD

**Issue by leapleekl** [rustdesk/rustdesk#8719]
### Bug Description

When I enter the password and the password is correct, the settings cannot be unlocked

### How to Reproduce

1.open settings 
2.click “security“ -> ”unlook security settings“ -> type passwd

### Expected Behavior

please fix it ，Some people say it can be modified through appimage, but I didn't succeed.

### Operating system(s) on local side and remote side

Debian sid xfce4（kernel6.9）

### RustDesk Version(s) on local side and remote side

1.2.3-->1.2.6

### Screenshots

![rustd](https://github.com/user-attachments/assets/fcb0b19b-773e-4e3c-9915-e3b5eb63ba60)

**Comment by rustdesk** [comment]
close as tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by rustdesk** [comment]
Can you run below to show me the output?

Two cases
- click on cancel
- input correct password, then ok

```
pkexec  echo 1; echo $?;
```

**Comment by leapleekl** [comment]
![cancel_ok](https://github.com/user-attachments/assets/ac0ff499-2ed2-4158-bd66-58469162b9ba)

**Comment by rustdesk** [comment]
How about this?

```
pkexec /usr/share/rustdesk/files/polkit; echo $?;
```

**Comment by leapleekl** [comment]
![ulo](https://github.com/user-attachments/assets/87ac2934-641a-44a7-9830-6ce95d72434e)

**Comment by rustdesk** [comment]
It seems normal. did you run on Debian sid xfce4?

**Comment by leapleekl** [comment]
yes, 
![sid](https://github.com/user-attachments/assets/c57a0955-6fc2-4b74-a083-b841eb5f8193)

**Comment by rustdesk** [comment]
Thanks

**Comment by leapleekl** [comment]
Currently I can only modify the locking settings through the `.Appimage` file.

**Comment by rustdesk** [comment]
We will install a debian xfce4 to fix this.

**Comment by leapleekl** [comment]
thanks！！！

**Comment by 21pages** [comment]
https://www.debian.org/releases/trixie/release-notes/issues.en.html#changes-to-polkit-configuration

**Comment by leapleekl** [comment]
Ok, thank you for your reply. 
At present, I can temporarily solve it with `.Appimage` , but it is troublesome

**Comment by HiFiPhile** [comment]
I've tried 1.3.0 on Debian 12 X11, Archlinux X11 and Archlinux wayland, on all these platforms clicking unlock settings button does nothing.

If I run the test the dialog is correctly showed:
```
![image](https://github.com/user-attachments/assets/7f8ea722-6711-483e-8c22-6dc2da3af065)
```

**Comment by rustdesk** [comment]
use this workaround https://github.com/rustdesk/rustdesk/wiki/FAQ#unlock-security-settings-not-work-on-some-linux
