### ISSUE TITLE
iPad App has a big mouse pointer

### ISSUE THREAD

**Issue by HappyZHero** [rustdesk/rustdesk#8727]
### Bug Description

iPad app has a big mouse pointer

### How to Reproduce

iPad  TestFlight newest app

### Expected Behavior

Pls correct this bug

### Operating system(s) on local side and remote side

iOS -> windows 11

### RustDesk Version(s) on local side and remote side

1.2.6 -> 1.2.6

### Screenshots

![IMG_0012](https://github.com/user-attachments/assets/844ef6ce-6974-45ec-8dd5-7dd89b68546a)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/8478
