### ISSUE TITLE
blue screen crash

### ISSUE THREAD

**Issue by julienallexandre** [rustdesk/rustdesk#8743]
### Bug Description

when I open Windows Sanbox and download rustdesk, the moment I click on the executable to install it, my pc turns blue. 

### How to Reproduce

Open Windows Sandbox
Download RustDesk
Run the executable for installation

### Expected Behavior

I'd like to be able to install rustdesk in windonws sandbox without crashing.

### Operating system(s) on local side and remote side

Local : Windows 11 Professionnel 23H2 / Sandbox : Windows 11 Enterprise 22H2

### RustDesk Version(s) on local side and remote side

1.2.6

### Screenshots

I can't screen the blue screen

**Comment by rustdesk** [comment]
No plan to fix sandbox.
