### ISSUE TITLE
Keyboard Issues in both directions on RaspberryPi Raspian 11 32bit

### ISSUE THREAD

**Issue by 0nelight** [rustdesk/rustdesk#8755]
### Bug Description

When using a Windows 10 Machine to access a RaspberryPi the Keyboard-Layout doesn't get converted properly.
I ensured they have the same setting for language and keyboard layout. F.e. when pressing "," on Windows, I get "/" on RaspiOs (Debian).

When using the RaspberryPi to access the Windows 10 Machine, Mouse input works, but Keyboard doesn't work at all.

### How to Reproduce

See Bug describtion.

### Expected Behavior

Keyboard should work.

### Operating system(s) on local side and remote side

Windows 10 -> Raspian 11 32bit / Raspbian 11 32bit -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.6 -> 1.2.6

### Screenshots

-

### Additional Context

Running X11 with LXDE on Raspberry.
Host: Raspberry Pi 4 Model B Rev 1.2 
Kernel: 6.1.21-v8+ 

**The Keyboard is functioning flawlessly with the Version before Flutter introduction -> [1.1.9](https://github.com/rustdesk/rustdesk/releases/tag/1.1.9).**
Tried also nightly-build on Raspberry. Issue seems to be the Raspbery-Side because both Issues don't exist with [1.1.9](https://github.com/rustdesk/rustdesk/releases/tag/1.1.9).

**Comment by rustdesk** [comment]
We wont fix PI 32 bit.

**Comment by 0nelight** [comment]
Running this on RaspberryPi now and it works GREAT as a Client :sunglasses: :heart_eyes: (Not tested as Host)

    Raspberry Pi OS with desktop
    Release date: July 4th 2024
    System: 64-bit
    Kernel version: 6.6
    Debian version: 12 (bookworm)
    Wayland
    rustdesk-1.2.6-aarch64.deb
