### ISSUE TITLE
CapsLock fail (11 -> Ubuntu 22, lang?)

### ISSUE THREAD

**Issue by alanmcanonical** [rustdesk/rustdesk#8760]
### Bug Description

Client side:
OS: Windows 10 x64
version: rustdesk-1.2.6-x86_64.exe
Server side:
OS: Ubuntu 22.04
version: 1.2.6 (apt install)

The CapsLocks works fine outside the control window but only outputs lower case char inside the control window

### How to Reproduce

Use the portable rustdesk on Windows 11 x64 and use apt to install rustdesk on Ubuntu. The Ubuntu serves as server side.
Turn on the CapsLock and type whatever character inside the **Firefox/librewolf** of remote side (which I think could be the root cause)

### Expected Behavior

Type in uppercase char

### Operating system(s) on local side and remote side

Windows 11 -> Ubuntu 22.04 amd64 

### RustDesk Version(s) on local side and remote side

1.2.6 -> 1.2.6

### Screenshots

N/A

**Comment by fufesou** [comment]
Hi, thanks for your feedback.

Do you use the "Legacy mode"? Please use the "Map mode" or "Translate mode".    https://github.com/rustdesk/rustdesk/wiki/FAQ#keyboard-translation-modes

![image](https://github.com/user-attachments/assets/a708a3e4-355c-49c1-9275-aa24c24552c8)

**Comment by rustdesk** [comment]
similar, https://github.com/rustdesk/rustdesk/issues/8599, just as a ref

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/9060#discussioncomment-10910327
