### ISSUE TITLE
Still not working on KDE Neon with Wayland session at all

### ISSUE THREAD

**Issue by linlinxza** [rustdesk/rustdesk#8790]
### Bug Description

Should just work on Wayland. Only works on X11 (and no, I am not going back to X11). But I did try it on X11 and it works that way. 

### How to Reproduce

Install KDE Neon and use the Wayland session. Try connecting to the system using KDE Neon.

### Expected Behavior

Should just work on Wayland. X11 is basically dead. It's time to make Wayland the top priority now.

### Operating system(s) on local side and remote side

KDE Neon (both local and remote)

### RustDesk Version(s) on local side and remote side

1.2.7 (both local and remote)

### Screenshots

![image](https://github.com/user-attachments/assets/d0539677-0d04-4db0-9ce2-44a869174e1f)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/8600

**Comment by rustdesk** [comment]
You will be blocked if you continue to create duplicate
