### ISSUE TITLE
there is only a white board when starting rustdesk.exe in win 10 x86_64

### ISSUE THREAD

**Issue by miaomiao1992** [rustdesk/rustdesk#8797]
### Bug Description

there is only a white board when starting rustdesk.exe in win 10 x86_64

### How to Reproduce

after installing all dependencies, then cargo run --release

(cargo check is ok.)

### Expected Behavior

we can see something

### Operating system(s) on local side and remote side

win10

### RustDesk Version(s) on local side and remote side

1.2.7 -> 1.2.7

### Screenshots

![1](https://github.com/user-attachments/assets/bea49b88-3af8-490a-8211-5e9b58d423a5)

![2](https://github.com/user-attachments/assets/56dcea13-f0a8-4dca-9f57-4e2c583e3c0d)

**Comment by rustdesk** [comment]
#763
