### ISSUE TITLE
rustdesk-1.1.9-raspberry-armhf.deb  doesn't work on my Raspberry pi 4  8Gb

### ISSUE THREAD

**Issue by srbPierre** [rustdesk/rustdesk#881]
Hi,

no problem on install process, but the GUI will not appear

**RustDesk version and environment**
rustdesk-1.1.9-raspberry-armhf.deb  
Raspberry Pi 4  8 Gb ram

**Comment by Heap-Hop** [comment]
> *A known issue is that the UI cannot be translated, so it only works well in English.

![2022-06-28-165743_1920x1080_scrot](https://user-images.githubusercontent.com/62206297/176138943-8eb2981d-0be1-4c3b-b02b-b9594114bec7.png)

**Comment by srbPierre** [comment]
My Raspberry is in French ;-)
and under Raspbian 10 not 11...

![raspberry](https://user-images.githubusercontent.com/107108065/176140277-8e0466cd-f28a-4418-a94f-7b5f8062434f.JPG)

If is only a translate problem I can try to do the translation if you want?

**Comment by Heap-Hop** [comment]
>but the GUI will not appear

Nothing happend after run RustDesk on your Pi?

**Comment by srbPierre** [comment]
No.
the cursor rotates and disappears...

**Comment by srbPierre** [comment]
Library missing !
how to install ?

![Capture2](https://user-images.githubusercontent.com/107108065/176175249-958dbc0f-0570-4a32-8346-31d966934e33.JPG)

**Comment by Heap-Hop** [comment]
> under Raspbian 10 not 11...

Thx! Looks like doesn't support version 10.

I haven't tested on 10. Could you please build for yourself, and share your result? Thx!

https://github.com/rustdesk/rustdesk/discussions/697#discussioncomment-2879261

**Comment by srbPierre** [comment]
GLIBC 2.29 not available on Buster...

https://raspberrypi.stackexchange.com/questions/108314/libc-2-29-on-buster

**Comment by srbPierre** [comment]
ok thanks...
you can close these issue
