### ISSUE TITLE
Keyboard doesn't work in 32-bit Sciter version

### ISSUE THREAD

**Issue by MrStranger812** [rustdesk/rustdesk#8811]
### Bug Description

When connecting from one 32-bit Sciter version of RustDesk to another 32-bit Sciter version of RustfDesk, the keyboard input does not function. This issue prevents typing in applications such as Notepad, browsers, and others.

### How to Reproduce

1) Install the 32-bit Sciter version of RustDesk on both systems.
2) Connect from one 32-bit Sciter version of RustDesk to another.
3) Attempt to type in applications like Notepad or a browser on the remote system.
4) Observe that keyboard input does not work.

### Expected Behavior

When connecting to another 32-bit Sciter version of RustDesk, keyboard input should function correctly, allowing users to type in applications such as Notepad, browsers, and other text input fields without issues.

### Operating system(s) on local side and remote side

win11(64bit) -> win7(32-bit)

### RustDesk Version(s) on local side and remote side

1.2.7 -> 1.2.7

### Screenshots

![Screenshot 7_24_2024 1_10_52 PM](https://github.com/user-attachments/assets/71fd922f-ed3e-4a8e-9590-1b82719f07ee)

**Comment by rustdesk** [comment]
#763

**Comment by serg499** [comment]
Same bug when connecting from Windows 7 (sciter) to Winodws 10 PC. Both use v.1.2.7.
It's a seriuos bug, making RustDesk on Windows 7 almost useless.
