### ISSUE TITLE
Black screen, don't touch, don't see menu bar when remotely controlling android UI 6 (Samsung Table)

### ISSUE THREAD

**Issue by sparkid** [rustdesk/rustdesk#8818]
### Bug Description

Remote Samsung Table UI 6 no turn on screen, don't allow remote control, don't work  app before update one UI 5.1 to One UI 6.

### How to Reproduce

All time 

### Expected Behavior

Retake control remote from tablet

### Operating system(s) on local side and remote side

All - > android

### RustDesk Version(s) on local side and remote side

1.2.x - 1.2.7

### Screenshots

Don't have 

### Additional Context

With previous 1.2.6 power screen but don't have input control

**Comment by sparkid** [comment]
All previous version full work until update one ui

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893
