### ISSUE TITLE
3D / CAD Program viewports unusable

### ISSUE THREAD

**Issue by indexofrefraction** [rustdesk/rustdesk#8821]
### Bug Description

As with other RD clients i tried, working in Cinema 4D is impossible.
As soon as you try to rotate or scale objects in one of the 3D viewports, 
the program reacts over-sensitive and proper work with the app is impossible.
TeamViewer is the only app i know so fare where this does not happen.

### How to Reproduce

Open C4D, add an object and start rotating the 3D viewport

### Expected Behavior

smooth viewport movements as when working directly on the machine

### Operating system(s) on local side and remote side

macos -> Win10

### RustDesk Version(s) on local side and remote side

1.2.7 -> 1.2.7

### Screenshots

makes no sense

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367
