### ISSUE TITLE
Remote performance degrades over time

### ISSUE THREAD

**Issue by AtomicStryker** [rustdesk/rustdesk#8831]
### Bug Description

I use a locally hosted (on my PC) Rustdesk for controlling a laptop, basically remote into the laptop from my main PC with its better screen and keyboard. When doing this for >6 hours at a time, the clientside becomes more and more sluggish as if the network connection was terrible. The picture and inputs may lag for several seconds. The delay is constant, not coming and going. Restarting the connection or the client does not help.

Restarting the remote service helps. The response is snappy again. There is some kind of leak or queue ballooning.

### How to Reproduce

Connect. Have the connection running (and use it) for several hours. Note a severe slowdown to be point of unusability.

### Expected Behavior

It should not matter how long a connection has been active.

### Operating system(s) on local side and remote side

Windows 11 -> Windows 11 both up to date

### RustDesk Version(s) on local side and remote side

1.2.7 nightly 2024-07-01 00:33 -> 1.2.7 nightly 2024-07-01 00:33

### Screenshots

n/a

**Comment by AtomicStryker** [comment]
Updated to current nightly. Noted i still had a slowdown after the restart ... checked network which seemed slow. Perhaps its an issue with network after all. Will investigate and reproduce more first.

**Comment by 21pages** [comment]
What's the codec and gpu on the controlled side? When this happens, please check the gpu, cpu, and memory usage.
