### ISSUE TITLE
error link on win7  

### ISSUE THREAD

**Issue by ianfor** [rustdesk/rustdesk#885]
LINK : fatal error LNK1181: cannot open input file 'OneCoreUAP.lib'

环境: vs2015 update 3, clang 8.1, rustc 1.61, rustdesk版本当前的master版本
其他步骤都正常通过了，最后link的时候没有找到该lib，
查了下msdn，这个lib是在win10之后的sdk才有的，但是win10编译出来的程序win7不能跑#789，
想问下是不是rustdesk编译vs版本必须要vs2017以上么？

**Comment by rustdesk** [comment]
#763
