### ISSUE TITLE
Can't run MacOS app when using private build with custom Github actions

### ISSUE THREAD

**Issue by tschettervictor** [rustdesk/rustdesk#8858]
### Bug Description

When I download the 1.2.7 version of rustdesk from the official GitHub page, it works fine. But when I fork the repo and run the nightly flutter build, I cannot get the app to work on MacOS. I have tried all versions from 1.2.2 - 1.2.7 and none of them work.

This only happens when using my custom build using the actions menu in GitHub. The official dmg works fine.

### How to Reproduce

Follow the rustdesk instructions to fork and create custom nightly releases with your own custom relay server and key built in. Then download the appropriate dmg file for MacOS and try to run it.

### Expected Behavior

I expect  the app to run, just like the official version from the rustdesk GitHub page, but instead I get a warning saying to get the software updated. See screenshot below.

### Operating system(s) on local side and remote side

MacOS 14.5 Sonoma

### RustDesk Version(s) on local side and remote side

1.2.7

### Screenshot

<img width="328" alt="Screenshot 2024-07-27 at 11 36 50 AM" src="https://github.com/user-attachments/assets/cf2d3052-2736-45ed-a78c-0e7a8867cae2">

**Comment by rustdesk** [comment]
#763
