### ISSUE TITLE
Android5.1 is not supported for remote control

### ISSUE THREAD

**Issue by johnny-lv** [rustdesk/rustdesk#887]
As titled, I can connect to android5.1(version of rustdesk on android=1.1.10) with rustdesk(1.1.9) on win11, rustdesk input is set to ON, but still cannot control android5.1. Expecting it working for Android5.1. Thanks!

**Comment by KreativeKrise** [comment]
I have the same problem on an old Moto G3 with Android 6.0.1.

**Comment by Heap-Hop** [comment]
Sorry guys, RustDesk apk requires Android 7 at least. We use many api above Android 7.
