### ISSUE TITLE
Rustdesk with Cocolatey installation

### ISSUE THREAD

**Issue by michaelortnersanube** [rustdesk/rustdesk#888]
RustDesk with Chocolatey not working

...

In the windows searching box there should be to find rustdesk.

...

**How did you install `RustDesk`?**

Over Chocolatey

---

**RustDesk version and environment**

1.1.19

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/100#issuecomment-1011954938

we support winget, No plan to support it at least for now.
