### ISSUE TITLE
Huge memory usage on Mac

### ISSUE THREAD

**Issue by Seraphli** [rustdesk/rustdesk#8883]
### Bug Description

I just connected to my remote manjaro. The first seconds are fine. Then the connection became laggy. When I check the memory usage, RustDesk used up all the memory and continue to grow. I have to force quit the app in order to make it stop.

### How to Reproduce

I just connect to a 4K remote host. I remember when I haven't upgrade to 1.2.7, I didn't come across this issue.

### Expected Behavior

constant memory usage

### Operating system(s) on local side and remote side

Mac -> Manjaro

### RustDesk Version(s) on local side and remote side

1.2.7 -> 1.2.6

### Screenshots

<img width="268" alt="image" src="https://github.com/user-attachments/assets/a3d90c74-d820-42d3-8725-7c41e2e9d933">

**Comment by Seraphli** [comment]
I just install back 1.2.7, using the dmg file I downloaded last time. The issue disappeared. I didn't change any setting. I don't know why.

**Comment by rustdesk** [comment]
Let's know if it can constanly reproduce.

**Comment by Seraphli** [comment]
I find out how to reproduce this issue. Run a game on the remote host and 1.2.7 client will have this issue. Turn on texture rendering solves this issue.

**Comment by rustdesk** [comment]
How about playing a video?

**Comment by Seraphli** [comment]
Confirmed. Playing a video without turning on texture rendering also cause this issue.

**Comment by rustdesk** [comment]
Coud you try out the nightly, https://github.com/rustdesk/rustdesk/releases/tag/nightly? I just put a fix.

**Comment by Seraphli** [comment]
I tried the nightly and this issue is fixed.

**Comment by rustdesk** [comment]
Thanks a lot, could you confirm the texture rendering was turned off?

**Comment by Seraphli** [comment]
Yes, the texture rendering was turned off.
