### ISSUE TITLE
Android -> PC Landscape Mode

### ISSUE THREAD

**Issue by mickhaorex** [rustdesk/rustdesk#889]
When controlling a PC from an Android phone, is it possible to forcibly switch the Android screen in your program to landscape (horizontal) mode. Because it is inconvenient to operate when the phone is in an upright position, since the entire computer screen is not visible.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/880

**Comment by rustdesk** [comment]
But I like portrait.

**Comment by Heap-Hop** [comment]
#576

**Comment by mickhaorex** [comment]
So many answers in a short period of time.
I am glad that the support service is following issues. Only I didn't understand anything, is it possible to switch the program to landscape mode without touching the basic android settings?

**Comment by rustdesk** [comment]
close to favor #889
