### ISSUE TITLE
RDP credentials saved in cleartext

### ISSUE THREAD

**Issue by JouBr0** [rustdesk/rustdesk#891]
**Describe the bug you encountered:**
When using the functionality to save RDP-Credentials (using the little pen) they are saved in cleatext within the directory C:\Users\<User>\AppData\Roaming\Rustdesk\config\peers\<id.toml>.

![2022-06-29_16-45-51](https://user-images.githubusercontent.com/78957542/176466514-0f3dcc65-ebb5-4a76-a371-cb459ac50c04.png)

I suppose this isnt intended. Maybe you are able to fix it. :)

**RustDesk version and environment**
Tested with Rustdesk Version 1.1.9 on Windows.

Besides this I really like your product and am interested to see where it goes!

**Comment by simeononsecurity** [comment]
Yeah this is a fault and definitely needs to be fixed. No keys or passwords should ever be stored in clear text ever. 
Please fix @rustdesk

**Comment by rustdesk** [comment]
![image](https://user-images.githubusercontent.com/71636191/218622898-3a0cf3b7-d370-4f49-8326-f26b3a491bbd.png)

**Comment by rustdesk** [comment]
In nightly build.
