### ISSUE TITLE
Rustdesk doesn't pick Ukrainian translation by default (when OS language matches)

### ISSUE THREAD

**Issue by xalt7x** [rustdesk/rustdesk#8923]
### Bug Description

I've noticed that on both desktop and Android, Rustdesk is displayed in English by default if OS language is set to Ukrainian.
I believe it should select existing Ukrainian translation instead.

I've also tried setting other languages in Android (e.g., Italian) and after the app restart, Rustdesk automatically selected relevant translation.

### How to Reproduce

On Android:
1. Make sure that Rustdesk app language is set to "Default"
2. "Force stop" Rustdesk app
3. In Settings set Android interface language to Ukrainian (it can be called "Українська (Україна)")
4. Open Rustdesk app

### Expected Behavior

Interface language should switch to Ukrainian to match user-selected Android language

### Operating system(s) on local side and remote side

Android 13

### RustDesk Version(s) on local side and remote side

1.2.6-0.1

### Screenshots

On screenshots at the top you can see Android System Settings, and at the bottom - floating Rustdesk window. 

Here's the correct Rustdesk language selection when Android language is set to Italian:

![Selected_Italian](https://github.com/user-attachments/assets/d429a51d-7ff8-4ef2-8c19-6f4a55d46aca)

And here's Rustdesk displays in English when Android language is set to Ukrainian:

![Not_Selected_Ukrainian](https://github.com/user-attachments/assets/dd578b12-7dc9-42b4-9ebb-02f7bfbd5c82)

### Additional Context

Not sure what is the exact reason for this, but I have a few guesses:
1. For commit [e733666](https://github.com/rustdesk/rustdesk/commit/e733666f55e6b5e0814d4a89f41fd6b6017d6b0e), the initial translator provided slightly incorrect language code name ("ua"). According to [Flutter documentation](https://api.flutter.dev/flutter/flutter_localizations/kMaterialSupportedLanguages.html) and other sources, locale code for Ukrainian should be "uk"
2. I'm not sure about this one but [flutter/lib/common.dart](https://github.com/rustdesk/rustdesk/blob/cba8aaa4108f7826810b07a43163c41bd3743b5a/flutter/lib/common.dart#L612) doesn't have "uk" in the list of supported locales (which was updated several times)

**Comment by 21pages** [comment]
try https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.3.0-aarch64-ua-uk.apk

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/2333ee2c07c6a67ed6c58ccfbc50a3bee203f90d

**Comment by xalt7x** [comment]
> try https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.3.0-aarch64-ua-uk.apk
> 
> [21pages@44009cc](https://github.com/21pages/rustdesk/commit/44009ccefcff807cd82f61a16e79c3a7bdac22e0)

Thanks for the quick response.   

Unfortunately app installed from that apk crashes on start. And that may affect many users as my current OS language is English.    
If rename is the way to fix this, than I believe that translation file `src/lang/ua.rs` should be renamed to `src/lang/uk.rs` as well.

P.S. As for the `List<Locale> supportedLocales = const ` in the `flutter/lib/common.dart` I see that except "uk", it doesn't have many other lang codes from the filenames of the `src/lang` directory ( ar, be, bg, ca, el, et, eu, fa, he, hr, lt, lv, nb, nl, ro, sl, sq, sr, sv, th, vn).
