### ISSUE TITLE
CTRL shortcuts won't work (debian QWERTZ -> Windows AZERTY)

### ISSUE THREAD

**Issue by GeekCornerGH** [rustdesk/rustdesk#8936]
### Bug Description

I'm using Rustdesk from Linux, and my friend from Windows. When I try to run "CTRL+C" or "CTRL+A" for example, it won't work.
I'm using a QWERTZ keyboard layout, and he's using an AZERTY layout.

### How to Reproduce

1. Connect to a PC
2. Try to use keyboard translation
3. Try to run a ctrl shortcut
4. It won't work

### Expected Behavior

I wanted the shortcut to get through the remote session

### Operating system(s) on local side and remote side

Debian 12 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.7

### Screenshots

N/A

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/8920

**Comment by rustdesk** [comment]
translation mode?
