### ISSUE TITLE
glitched image

### ISSUE THREAD

**Issue by konosubakonoakua** [rustdesk/rustdesk#8945]
### Bug Description

After I boot up my linuxmint 22, I try to connect rustdesk server running on mint from win11 pc.
It keeps reconnecting, after some tries, it quit.
I use ssh to connect to mint, then I disable rustdesk.service then restart it.
It connected, but flicking at first frames then the whole desktop become glitched like this:
![PixPin_2024-08-03_23-28-06](https://github.com/user-attachments/assets/937c40f2-6e6a-4525-940e-682b6222cf6f)

### How to Reproduce

maybe disable then restart, IDK

### Expected Behavior

do not become glitched

### Operating system(s) on local side and remote side

win11 -> linux mint22

### RustDesk Version(s) on local side and remote side

1.2.6 -> 1.2.6

### Screenshots

![PixPin_2024-08-03_23-28-06](https://github.com/user-attachments/assets/937c40f2-6e6a-4525-940e-682b6222cf6f)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
