### ISSUE TITLE
This issue can be replicated when computers are on the same local area network but using different routers.

### ISSUE THREAD

**Issue by 755713372** [rustdesk/rustdesk#8948]
### Bug Description

When using this software, I encountered a problem: two computers within the same local area network cannot connect to each other remotely. The server providing the service is in the cloud. Remote access works for computers that are not on the same local area network, but the connection speed is very slow and takes about 30 seconds to establish. I am a user in China, and I am not sure if this issue is related to our network conditions. When computers are on the same local area network but on different routers, they might fail to connect and time out. Could someone experienced help me resolve this frustrating issue?
![微信截图_20240804155321](https://github.com/user-attachments/assets/623f66be-ec57-4909-9e3b-063f49a10aec)

### How to Reproduce

This issue can be replicated when computers are on the same local area network but using different routers.

### Expected Behavior

-

### Operating system(s) on local side and remote side

windows

### RustDesk Version(s) on local side and remote side

1.2.7

### Screenshots

![微信截图_20240804155321](https://github.com/user-attachments/assets/26671597-27ac-46a4-8c51-e2943b67d63a)

**Comment by rustdesk** [comment]
#763
