### ISSUE TITLE
RustDesk do not install on windows 7

### ISSUE THREAD

**Issue by Infra034** [rustdesk/rustdesk#895]
Hello, When I try to install RustDesk on windows 7 (x86, I did not test on x64) nothing happens and if I create a folder on program files and start the installing it just delete the folder.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/759753c000775ba7a3c7b4af8e6ab17c1388ac56

**Comment by rustdesk** [comment]
[rustdesk-1.1.9-putes.zip](https://github.com/rustdesk/rustdesk/files/9030401/rustdesk-1.1.9-putes.zip)
Please run above in cmd window `/rustdesk-1.1.9-putes.exe --silent-install 1` and paste the output of the cmd window here.

**Comment by Infra034** [comment]
https://prnt.sc/u8g1NE6wJQ6y

**Comment by rustdesk** [comment]
> https://prnt.sc/u8g1NE6wJQ6y

it tell nothing, could you scroll down, and show all, you can copy the text and paste here.

**Comment by Coethium** [comment]
Hi, same problem here (Win7 x86).
I tried the installer you gave here :

> [rustdesk-1.1.9-putes.zip](https://github.com/rustdesk/rustdesk/files/9030401/rustdesk-1.1.9-putes.zip) Please run `rustdesk-1.1.9-putes.exe --silent-install 1` in cmd window, and then paste the output of the cmd window here.

As with the installer given on Releases page, the .BAT exit before the end, and the cmd window is killed. So it never reaches the timeout 300. I ran it with a redirection : `rustdesk-1.1.9-putes.exe --silent-install 1 > log.txt` ; here is the content :

> 
> C:\Users\Michael\AppData\Local\Temp>chcp 65001 
> Page de codes activeÿ: 65001
> 
> C:\Users\Michael\AppData\Local\Temp>sc stop RustDesk 
> [SC] OpenService ‚chec(s) 1060 :
> 
> Le service sp‚cifi‚ n'existe pas en tant que service install‚.
> 
> 
> C:\Users\Michael\AppData\Local\Temp>sc delete RustDesk 
> [SC] OpenService ‚chec(s) 1060 :
> 
> Le service sp‚cifi‚ n'existe pas en tant que service install‚.
> 
> 
> C:\Users\Michael\AppData\Local\Temp>taskkill /F /IM RustDesk.exe 
> 
> C:\Users\Michael\AppData\Local\Temp>reg delete HKEY_CLASSES_ROOT\.rustdesk /f 
> 
> C:\Users\Michael\AppData\Local\Temp>netsh advfirewall firewall delete rule name="RustDesk Service" 
> 
> Aucune rÃ¨gle ne correspond aux critÃ¨res spÃ©cifiÃ©s.
> 
> 
> C:\Users\Michael\AppData\Local\Temp>reg delete HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk /f 
> 
> C:\Users\Michael\AppData\Local\Temp>rd /s /q "C:\Program Files (x86)\RustDesk

"

**Comment by rustdesk** [comment]
> rustdesk_install.bat

Could you run this in cmd? then we can get all information. Your redirection tells nothing.

**Comment by Coethium** [comment]
I redirected the content, because when i just type `rustdesk_install.bat` in cmd ; the script begins, show a few lines ; then the cmd window exits. So the last line you see in the log (rd /s/q ...) is the last thing done before the termination of the window (I guess that's important : the cmd window is killed).

**Comment by rustdesk** [comment]
Wierd, could you remove line by line in the rustdesk_install.bat to find out which line causes the exit?

**Comment by rustdesk** [comment]
> rd

Could you show me the two rd lines? very strange, only exit on some Windows.

**Comment by Coethium** [comment]
After some tests, `rd` lines kill the script (and the parent window) if the directory does'nt exist. As you said : that's weird...
When the directory exists, it works.

Here a simple hack :

>     if exist "C:\Program Files (x86)\RustDesk" rd /s /q "C:\Program Files (x86)\RustDesk"
>     if exist "%ProgramData%\Microsoft\Windows\Start Menu\Programs\RustDesk" rd /s /q "%ProgramData%\Microsoft\Windows\Start Menu\Programs\RustDesk"

**Comment by rustdesk** [comment]
could you please try to remove /r or /q to see if exit?

**Comment by Coethium** [comment]
--> All test done in the batch file

I guess you mean `/s`, not `/r`.

Without `/s`, it exits the batch file (and kill the cmd window) in two cases :
- if the directory exists and has content
- if the directory does'nt exist

Without `/q`, the rd process "pauses" without message, but i guess it asks the "are you sure ?" question, because if i answer "y" ("o" in french for me) it continues (= del the directory tree if it exists, or exits and kill the cmd window if the directory does'nt exist)

It really seems the rd command is buggy on W7.

Here the doc :
> C:\Windows\system32>rd /?
> Supprime un répertoire.
> 
> RMDIR [/S] [/Q] [lecteur:]chemin
> RD [/S] [/Q] [lecteur:]chemin
> 
>     /S      Supprime tous les répertoires et les fichiers dans le
>             répertoire spécifié en plus du répertoire lui-même.
>             Utilisé pour supprimer une arborescence.
> 
>     /Q      Mode silencieux, ne demande pas de confirmation pour supprimer
>             une arborescence de répertoires avec /S.

And a quick translation (cause i'm using the french version):
> C:\Windows\system32>rd /?
> Delete a directory.
> 
> RMDIR [/S] [/Q] [drive:]path
> RD [/S] [/Q] [drive:]path
> 
>     /S      Delete all the directories and the files in the given directory, and the directory itself.
>             Used to delete a directory tree.
> 
>     /Q      Silent mode, do not ask a confirmation to delete a directory tree with /S.

**Comment by rustdesk** [comment]
> buggy on W7

Agree, Thanks

**Comment by Infra034** [comment]
can be fixed this issue?

**Comment by rustdesk** [comment]
@Coethium could you please try out this one? Make sure old one is uninstalled.
[x86.zip](https://github.com/rustdesk/rustdesk/files/9041174/x86.zip)

**Comment by Coethium** [comment]
It works (W7/x86) !

I don't know if you use the hack on every version of the Windows installer (7/8/10/11) ? But a few hours ago, I tested the installation on W8/64 and the same problem occurs. I can guess the hack resolve this now (but i'm sorry, it will be impossible for me to make new tests on W8/64)

**Comment by Coethium** [comment]
> For me not work yet. =/

Did you try with the installer given here : https://github.com/rustdesk/rustdesk/issues/895#issuecomment-1174008661 ?

> @Coethium could you please try out this one? Make sure the old one is uninstalled. [x86.zip](https://github.com/rustdesk/rustdesk/files/9041174/x86.zip)

**Comment by Infra034** [comment]
> > For me not work yet. =/
> 
> Did you try with the installer given here : [#895 (comment)](https://github.com/rustdesk/rustdesk/issues/895#issuecomment-1174008661) ?
> 
> > @Coethium could you please try out this one? Make sure the old one is uninstalled. [x86.zip](https://github.com/rustdesk/rustdesk/files/9041174/x86.zip)

I tried that one, but still nothing.. I found the rustdesk_install.bat as he/she said but I don't understand what changes I need to make for this batch file works.

**Comment by Coethium** [comment]
With the zip given, no need to modifiy rustdesk_install.bat.
Could you try this :
- launch again the installer (to be sure the TEMP path is populated by install files)
- execute `cmd` as **administrator** 
- type `%TEMP%\rustdesk_install.bat > log.txt`
- give us here the content of `%TEMP%\log.txt`

**Comment by rustdesk** [comment]
Looks like exit at `del /f /q`

**Comment by rustdesk** [comment]
Could you remove all `del /f /q` line in the bat file, then run again?

**Comment by Infra034** [comment]
> Could you remove all `del /f /q` lines in the bat file, then run again?


C:\Windows\system32>chcp 65001 
P gina de c¢digo ativa: 65001

C:\Windows\system32>sc stop RustDesk 
[SC] OpenService FALHA 1060:

O servi‡o especificado nÆo existe como servi‡o instalado.


C:\Windows\system32>sc delete RustDesk 
[SC] OpenService FALHA 1060:

O servi‡o especificado nÆo existe como servi‡o instalado.


C:\Windows\system32>taskkill /F /IM RustDesk.exe 

C:\Windows\system32>reg delete HKEY_CLASSES_ROOT\.rustdesk /f 

C:\Windows\system32>netsh advfirewall firewall delete rule name="RustDesk Service" 

Nenhuma regra correspondente aos critÃ©rios especificados.


C:\Windows\system32>reg delete HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk /f 

C:\Windows\system32>if exist "C:\Program Files\RustDesk" rd /s /q "C:\Program Files\RustDesk" 

C:\Windows\system32>if exist "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\RustDesk" rd /s /q "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\RustDesk" 

C:\Windows\system32>del /f /q "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\RustDesk Tray.lnk"

**Comment by Coethium** [comment]
Tested here : if a directory to be deleted doesn't exist, `del` also kills the batch... That's soo unbelievable !?!

**Comment by rustdesk** [comment]
[x86-v2.zip](https://github.com/rustdesk/rustdesk/files/9048263/x86-v2.zip)

@Infra034 try out this one please.

**Comment by rustdesk** [comment]
> unbelievable

believable for Windows.

**Comment by Coethium** [comment]
Soo after many tests, it seems the problem occurs when a subprocess wants to write into stderr (and when a folder doesn't exists the rd/del command print a message into stderr). But don't ask me why stderr isn't always redirected on the terminal...

A simple workaround is to launch the batch file with a redirection of the stderr to null :

`%TEMP%\rustdesk_install.bat 2>nul` (only one L in MS OSes)

No more need of the repetitive IF in the batch, just add `2>nul` at the end of the call of the script.

**Comment by Infra034** [comment]
Thank you guys both solutions works for me (x86 v2 and command line by Coethium).

**Comment by rustdesk** [comment]
> 2>nul

interesting
