### ISSUE TITLE
BSOD when connecting to Physical Windows Host with an NVIDIA GPU

### ISSUE THREAD

**Issue by NightHammer1000** [rustdesk/rustdesk#8954]
### Bug Description

I sometimes have BSODs when connecting to a WIndows Rustdesk Host.
It started with 1.2.6 and downgrading to 1.2.5 actually gets rid of the Issue.

Stop Code is 0x116: VIDEO_TDR_FAILURE
So the GPU Driver fails to recover from a Crash.

GPU is an  RTX 4080.

![image](https://github.com/user-attachments/assets/5cdeb3ed-4ba7-43bf-9e8b-3734a916b1b9)

It also sometimes happens when I switch from a Multi Display (3 Display) configuration to a Single Display Setup while the connection is active.

GPU is fine. Tested with older 3080 which displayed the same Issue. 

The issue does not happen when I use a AMD GPU. So its possible related to the NVIDIA Driver.

Using different Codecs does not help the situation. 

### How to Reproduce

Just connect to the 1.2.6 or 1.2.7 Host. In 6 out of 10 attempts the screen in Rustdesk stays blank for a bit, then the Host gets an BSOD and reboots.

or

Switch from a 3 Screen Setup over to only one Display (In my Case a HDMI Dummy Plug)
BSOD in this Case will happen 8 out of 10 times.

### Expected Behavior

Rustdesk should connect without hard crashing the Host

### Operating system(s) on local side and remote side

Windows 11 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.7 -> 1.2.7 and 1.2.7 -> 1.2.6

### Screenshots

![image](https://github.com/user-attachments/assets/5cdeb3ed-4ba7-43bf-9e8b-3734a916b1b9)

**Comment by 21pages** [comment]
> Using different Codecs does not help the situation.

Will this happen on vp9?

**Comment by NightHammer1000** [comment]
Yes. Also happens with VP9 and on Nightly as well. Just tested.

**Comment by 21pages** [comment]
1. First, please disable the hwcodec option on both sides and then reinstall the app and test again. This will help to rule out the possibility of a hardware codec issue.
2. If the problem still persists, could you please try running the program within the commit range between June 23, 2023 and June 30, 2023? We need your help to narrow down the source of the problem.

Here are the program history, you need not to try every one.
https://github.com/21pages/rustdesk/releases/tag/history

**Comment by NightHammer1000** [comment]
I now disabled "Capture Display with DirectX" and it appears that the Issue is gone. I will keep an eye on it.

**Comment by rustdesk** [comment]
could you try out 1.2.6 files in https://github.com/21pages/rustdesk/releases/tag/history？please enable directx. without directx will slow down your machine a lot.

**Comment by NightHammer1000** [comment]
Yeah. I know. I just have a busy week. Wont get to it until the weekend. But I will check.

**Comment by rustdesk** [comment]
Thanks

**Comment by rustdesk** [comment]
CLose since no response.
