### ISSUE TITLE
When controlling a Windows computer through an Android phone, you cannot control the up, down, left, and right directions

### ISSUE THREAD

**Issue by hudingwen** [rustdesk/rustdesk#8959]
### Bug Description

The up, down, left, and right keys cannot function properly.

### How to Reproduce

When I open the keyboard on my Android phone and click the left and right keys or long press the left and right keys, I cannot control the Windows computer normally

### Expected Behavior

For example, I clicked the left button on the phone, but the game character in the software could not follow the normal keyboard keys, but the normal behavior should be that the game character moved a little bit to the left.

### Operating system(s) on local side and remote side

Android -> Windows

### RustDesk Version(s) on local side and remote side

1.2.7 - > 1.2.6

### Screenshots

none.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by rustdesk** [comment]
Does android have up, down, left, and right keys?

**Comment by rustdesk** [comment]
up, down, left, and right keys work fine on edit box, it is just not compatible with your game.

**Comment by aiyundiy** [comment]
However, there is no problem with the keyboard functions of controlling up, down, left, and right from Windows 10 to Windows 10.
