### ISSUE TITLE
Installer - "Loading..." not translated

### ISSUE THREAD

**Issue by bovirus** [rustdesk/rustdesk#8966]
### Bug Description

@rustdesk 

At installer start show "Loading..." (not translated).

Could be possible to localize it?

Thanks.

### How to Reproduce

Start the installer

### Expected Behavior

Localize the strings

### Operating system(s) on local side and remote side

Windos 10 22 H2 64bit Italian

### RustDesk Version(s) on local side and remote side

1.3.0

### Screenshots

No screenshot

**Comment by rustdesk** [comment]
Noted

**Comment by bovirus** [comment]
@rustdesk 

It's first strings that you see and it's in English.
I believe that could be add to translation queu.
