### ISSUE TITLE
error: unable to find library -lndk_compat

### ISSUE THREAD

**Issue by huaxiaos** [rustdesk/rustdesk#8971]
### Bug Description

I compiled librustdesk.so through ./flutter/ndk_arm64.sh. When I executed the last step, the error described in the title appeared. How can I solve it?

  = note: ld: error: unable to find library -lndk_compat
          clang-12: error: linker command failed with exit code 1 (use -v to see invocation)

### How to Reproduce

./flutter/ndk_arm64.sh

### Expected Behavior

./flutter/ndk_arm64.sh

### Operating system(s) on local side and remote side

macos

### RustDesk Version(s) on local side and remote side

latest

### Screenshots

./flutter/ndk_arm64.sh

### Additional Context

![WX20240806-234509@2x](https://github.com/user-attachments/assets/5b2c1dd8-916b-4356-bffd-f6f7fa74a577)

**Comment by rustdesk** [comment]
#763
