### ISSUE TITLE
After maximizing the control window, the active bar of the Windows taskbar icon cannot be seen

### ISSUE THREAD

**Issue by BlackdBlook** [rustdesk/rustdesk#8979]
### Bug Description

When the control window is maximized, the taskbar on the controlled side shows a strip indicator at the bottom of the icons for already opened but minimized windows, but it is not visible as shown in the images:
·· This is the control window in windowed mode:
![This is the windowed appearance of the control end](https://github.com/user-attachments/assets/f5cbf598-4fe6-4ac7-84d4-7864a3cdd783)
·· This is the control window maximized, the indicator strip is blocked: 
![This is the appearance after maximizing the control end, with the identification bar blocked](https://github.com/user-attachments/assets/7dce1394-2b14-483d-8efd-256d2ac0eac3)

### How to Reproduce

Connect normally and maximize the control window.

### Expected Behavior

The activity indicator strip should be displayed correctly.

### Operating system(s) on local side and remote side

Windows10->Windows10

### RustDesk Version(s) on local side and remote side

1.2.7->1.2.7

### Screenshots

![This is the windowed appearance of the control end](https://github.com/user-attachments/assets/f5cbf598-4fe6-4ac7-84d4-7864a3cdd783)
![This is the appearance after maximizing the control end, with the identification bar blocked](https://github.com/user-attachments/assets/7dce1394-2b14-483d-8efd-256d2ac0eac3)

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
https://github.com/leanflutter/window_manager/pull/477
