### ISSUE TITLE
Rustdesk constantly maxes out one thread

### ISSUE THREAD

**Issue by paperbenni** [rustdesk/rustdesk#90]
Whenever the rustdesk systemd service is running one CPU thread is constantly at 100%. This happens regardless of whether the device is connecting to anyone, anyone is connected to the device or even if the GUI is open or not. Stopping the systemd service immediately makes the cpu return to normal

I tested this on two machines, both are running Arch and a ryzen cpu. One has vega inbuilt graphics, one a gtx 1060

**Comment by rustdesk** [comment]
Yes, we noticed this bug, please uploaded new build, please use the new build.

**Comment by paperbenni** [comment]
where did you upload the build? The bug occurs with the newest github release (1.1.6)

**Comment by rustdesk** [comment]
We did you download it?

**Comment by rustdesk** [comment]
I did not create new release, just uploaded and overwrote.

**Comment by paperbenni** [comment]
The fix works :)

**Comment by paperbenni** [comment]
@rustdesk By the way I know it doesn't look pretty to create a new release with nothing in it but replacing releases causes lots of problems. For instance I think you just broke the AUR package for rustdesk. It doesn't check the validity test because it downloads from the github release URL but then checks for the old hash.

**Comment by rustdesk** [comment]
> broke

Then how can I help you?
