### ISSUE TITLE
Possible violation of the GPL license

### ISSUE THREAD

**Issue by artenax** [rustdesk/rustdesk#900]
Your source code contains blobs - libsciter-gtk.so. sciter-sdk provides the binary, but the source code only [for payment](https://sciter.com/prices/), which violates the GPL (as far as I understand). Accordingly, sciter is not opensource, but blobs. You are using proprietary components.

**Comment by kim-sondrup** [comment]
It seems safe to say that the plan is to discard Sciter based on info in [README.md](https://github.com/rustdesk/rustdesk/commit/21ad4cb8d8804862d903a90f2aa3a3ddbf85001b#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R39) and comments written in other issues https://github.com/rustdesk/rustdesk/issues/442#issuecomment-1091028955

**Comment by davidak** [comment]
Here are related resources on the topic:

- https://www.gnu.org/licenses/gpl-faq.html#FSWithNFLibs
- https://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs

>If you [write free software that uses nonfree libraries], your program won't be fully usable in a free environment.

That's exactly the issue i ran into:

```
[davidak@gaming:~]$ nix run nixpkgs#rustdesk
error: Package ‘libsciter-4.4.8.23-bis’ in /nix/store/ivb0wajfz0fil96cx2qy0hyk46lwh7v9-source/pkgs/development/libraries/libsciter/default.nix:40 has an unfree license (‘unfree’), refusing to evaluate.

       a) To temporarily allow unfree packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNFREE=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnfree = true; }
       in configuration.nix to override this.

       Alternatively you can configure a predicate to allow specific packages:
         { nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
             "libsciter"
           ];
         }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnfree = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```

On my NixOS system, unfree software is not allowed by default. I have to allow each package specifically. I rarely make a compromise, like with Steam.

So i see forward to a replacement of Sciter (https://github.com/rustdesk/rustdesk/issues/103).

**Comment by mon-jai** [comment]
If I recalled it right, the limitation only applies to licensee, but not the owner of the project.

**Comment by Aarstad** [comment]
Such a shame there's really not a contender for sciter. Taurus is not using a custom renderer so you'll have inconsistencies with what the user has installed on their system. 

Flutter you're basically turning the whole app into a massive electron bloated mess. Well okay it's like electron diet but still a huge binary for what you get. In that regard I'd even wager the amount of things you get in electron for just a little more binary size make more sense than what you get with flutter, except ofc the whole cross device unified experience. 

Wpf locks you into the Ms ecosystem, gtk and others just don't offer the technical fidelity. 

Strange, but this sciter really is a niche product that has no other contender out there, shame it isn't open source.
