### ISSUE TITLE
redmi phone can't open the RustDesk permission

### ISSUE THREAD

**Issue by gif-gif** [rustdesk/rustdesk#9030]
### Bug Description

I want to open the permission for control input , click the redmi permission menu

### How to Reproduce

- install to the redmi phone 
- click open the control input 
- click the redmi permission menu

### Expected Behavior

open control input for remote control

### Operating system(s) on local side and remote side

 Android 13 -> osx

### RustDesk Version(s) on local side and remote side

1.2.7

### Screenshots

<img width="370" alt="image" src="https://github.com/user-attachments/assets/7330e6b2-e8fd-4ff1-b2db-29a1b20e40f3">

<img width="420" alt="image" src="https://github.com/user-attachments/assets/6fcf5e07-3343-4c3d-a985-1f8cfa65a108">

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/6241
