### ISSUE TITLE
Cannot maximize rustdesk-window on local side

### ISSUE THREAD

**Issue by Lolen10** [rustdesk/rustdesk#9033]
### Bug Description

If I try to maximize the rustdesk-window the window doesn't really adjust and it becomes uncontrollable. Then I can't make any inputs anymore. If I make the window smaller again it works fine.

### How to Reproduce

1. Enter a rustdesk session
2. maximize the window

The window doesn't adjust it's size and I can't control the rustdesk session anymore. The buttons on the top are not clickable either.

### Expected Behavior

Maximize the window correctly 

### Operating system(s) on local side and remote side

Windows 11 -> Any operating system

### RustDesk Version(s) on local side and remote side

1.3.0 (nightly 2024-08-12) -> any version

### Screenshots

![Screenshot 2024-08-12 121726](https://github.com/user-attachments/assets/c9d87fa3-04d8-4e87-941a-f1c4f2d3e89b)
Normal state (not maximized)

![Screenshot 2024-08-12 122200](https://github.com/user-attachments/assets/7bd38de5-009c-4c1c-9a84-bf62b3c12dc2)
Maximized state

![Screenshot 2024-08-12 123013](https://github.com/user-attachments/assets/ce39d6ec-c6f1-4567-a1f7-c9ae9bb800e6)
Problem also present when still connecting

I think the standard windows titlebar as seen in both maximized screenshots shouldn't appear at all

### Additional Context

Problem isn't present in release version 1.2.7

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
@Lolen10 Hi, thanks for your feedback.

But I cannot reproduce this issue. The video shows what I did.

https://github.com/user-attachments/assets/3667103a-993d-4c28-b282-8ae28681242d

Is there any additional operation to reproduce?

Can you please also check the log `C:\Users\hoosm\AppData\Roaming\RustDesk\log\rustdesk_rCURRENT.log` to see if there're some errors?

> I think the standard windows titlebar as seen in both maximized screenshots shouldn't appear at all

I can't understand clearly. 

Windows explorer also show the tabbar.

![image](https://github.com/user-attachments/assets/0fc56062-4c02-4505-a1c8-f7a0205de918)

**Comment by fufesou** [comment]
Hi, Do you have a physical display on that machine? Can you find any monitors in device manager?

![image](https://github.com/user-attachments/assets/4c4667cb-fe15-4b8b-be8e-6d7cd409044f)

I find Win11 will try create a dummy virtual display if there's no monitor.
It will has the same name and properties of the the last plugged display.

The the window rendering is not normal.

**Comment by Lolen10** [comment]
> Is there any additional operation to reproduce?

No. It happens every time I try to maximize the window.

> Can you please also check the log 

I didn't notice anything out of the ordanary. [RustDesk_rCURRENT.log](https://drive.proton.me/urls/TH2964W2X8#5jNWU8bdsGqi)

> I can't understand clearly.

I meant the white windows titlebar on the top of the 2 maximized screenshots as normally rustdesk uses it's own (grey) titlebar

>  do you have a physical display on that machine?

yes I have.
![grafik](https://github.com/user-attachments/assets/e37ac0b7-ec1f-4135-84ac-8eb7a34419a8)

> If I plug out the display, then connect

Yes, after plugging out both displays It seems to work.

**Comment by Lolen10** [comment]
For context, my screens are setup like this
![grafik](https://github.com/user-attachments/assets/567a8f23-dc6f-4ca3-b142-294dce5cdd33)
The internal display is screen 1

I noticed something else:
When I plugged out the external monitors it worked as my notebook screen was the primary display.

Now after plugging it back in again it doesn't work anymore on my notebook-screen and it doesn't work on screen 2 but I noticed that it works on screen 3. In my configuration screen 3 is set as the primary display. So it might have to do with that.

Now I tried changing the primary display. I set screen 2 as primary display and as soon as I did that it worked there and screen 3 had some problems now with rustdesk.

So it might have to do with the primary screen configuration?

**Comment by Lolen10** [comment]
> It's strange, can you please double confirm?

I now downgraded to 1.2.7 (release) (i didn't delete Appdata\Rustdesk or anything, I just uninstalled and reinstalled the old version) and in this version everything works flawless on all 3 screens. So yes. The problem isn't present in 1.2.7

**Comment by rustdesk** [comment]
> I meant the white windows titlebar on the top of the 2 maximized screenshots as normally rustdesk uses it's own (grey) titlebar

You'd better mark on the screenshot. I do not understand you either.

**Comment by rustdesk** [comment]
Please try out this new build https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.3.0-x86_64.exe

**Comment by Lolen10** [comment]
> Please try out this new build https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.3.0-x86_64.exe

Problem seems to be gone in the new build.
