### ISSUE TITLE
Mouse pointer is a blue circle

### ISSUE THREAD

**Issue by qq1907** [rustdesk/rustdesk#9048]
### Bug Description

When using the PC version and Android version to connect to the remote end, the mouse pointer turns into a blue circle

### How to Reproduce

The remote end is Windows 10 Enterprise Edition LTSC and no keyboard and mouse are installed

### Expected Behavior

The mouse pointer was displayed normally before, but after I changed the CPU of the host, the pointer turned into a blue circle

### Operating system(s) on local side and remote side

windows 10 -> windows10

### RustDesk Version(s) on local side and remote side

1.3.0 -> 1.3.0

### Screenshots

![IMG_20240813_074429](https://github.com/user-attachments/assets/f0d72cb1-83e7-4dce-9983-a5f994f09b6a)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/4945
