### ISSUE TITLE
failed to run custom build command for `scrap v0.5.0 (/root/ruskdesk/rustdesk/libs/scrap)`

### ISSUE THREAD

**Issue by toohandsome** [rustdesk/rustdesk#905]
ubuntu 20.4
latest version code

run
```VCPKG_ROOT=/root/ruskdesk/vcpkg/installed/ ANDROID_NDK_HOME=/root/ruskdesk/android-ndk-r22b /root/ruskdesk/rustdesk/flutter/ndk_arm64.sh```
failed

![image](https://user-images.githubusercontent.com/46422252/177019554-f392ca4f-42b3-41f4-a950-99c76ce2da50.png)
```
   Compiling reqwest v0.11.11
error: failed to run custom build command for `scrap v0.5.0 (/root/ruskdesk/rustdesk/libs/scrap)`

Caused by:
  process didn't exit successfully: `/root/ruskdesk/rustdesk/target/release/build/scrap-4881eeebd6e1e2b7/build-script-build` (exit status: 101)
  --- stdout
  cargo:info=arm64-android
  cargo:rustc-link-lib=static=yuv
  cargo:rustc-link-search=/root/ruskdesk/vcpkg/installed/installed/arm64-android/lib
  cargo:include=/root/ruskdesk/vcpkg/installed/installed/arm64-android/include
  cargo:info=arm64-android
  cargo:rustc-link-lib=static=vpx
  cargo:rustc-link-search=/root/ruskdesk/vcpkg/installed/installed/arm64-android/lib
  cargo:include=/root/ruskdesk/vcpkg/installed/installed/arm64-android/include
  rerun-if-changed=/root/ruskdesk/rustdesk/libs/scrap/vpx_ffi.h
  rerun-if-changed=/root/ruskdesk/vcpkg/installed/installed/arm64-android/include

  --- stderr
  /root/ruskdesk/rustdesk/libs/scrap/vpx_ffi.h:1:10: fatal error: 'vpx/vp8.h' file not found
  /root/ruskdesk/rustdesk/libs/scrap/vpx_ffi.h:1:10: fatal error: 'vpx/vp8.h' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', libs/scrap/build.rs:63:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
[2022-07-02T23:55:24Z INFO  cargo_ndk::cli] If the build failed due to a missing target, you can run this command:
[2022-07-02T23:55:24Z INFO  cargo_ndk::cli] 
[2022-07-02T23:55:24Z INFO  cargo_ndk::cli]     rustup target install aarch64-linux-android

```

**Comment by rustdesk** [comment]
#763

**Comment by hlwhl** [comment]
Have u solved the issue? I encountered the error as well.

**Comment by onrdmr** [comment]
i think this error is about `vcpkg install libvpx:x64-windows` installation. I got same error and this libvpx package installation stuck on -- Generating makefile
-- Generating MSBuild projects
and nothing happens but its dependencies are installed correctly. 

- vcpkg install vcpkg-msbuild                  in pwsh at 21:02:07
Computing installation plan...
The following packages are already installed:
    vcpkg-msbuild:x64-windows@2023-08-08
vcpkg-msbuild:x64-windows is already installed
Total install time: 1.37 ms
- vcpkg install vcpkg-cmake-get-vars           in pwsh at 21:10:25
Computing installation plan...
The following packages are already installed:
    vcpkg-cmake-get-vars:x64-windows@2024-09-22
vcpkg-cmake-get-vars:x64-windows is already installed

i don't want to compile own. https://github.com/microsoft/vcpkg/issues/45588 i open this issue to them.
