### ISSUE TITLE
 android app restart id server config was losed 

### ISSUE THREAD

**Issue by toohandsome** [rustdesk/rustdesk#906]
android app restart " id server config" was losed 
when i start service , it will losed,
when i not start service and restat app , config will retain.
![Screenshot_2022-07-03-10-27-58-497_com carriez flutter_hbb](https://user-images.githubusercontent.com/46422252/177022115-dacf9110-64d4-451d-9cf6-523073dddbab.jpg)

...

**What did you expect to happen instead?**

 config be saved.

**How did you install `RustDesk`?**

android app 1.1.10-1
xiaomi 9 se
 

another question is: 

 why everytime start service, app will generate a new id ?
![IMG_20220703_103003](https://user-images.githubusercontent.com/46422252/177022159-5c8413ff-182b-4d7b-8d01-2637e937e74e.jpg)

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by rustdesk** [comment]
I can not reproduce.

**Comment by toohandsome** [comment]
> I can not reproduce.

Is there any relevant log I can provide to you

**Comment by rustdesk** [comment]
@toohandsome Thank you very much, we will build a debug version for you to see what problem. Allow a little time.

**Comment by toohandsome** [comment]
this is default id server
![image](https://user-images.githubusercontent.com/46422252/178148993-7820472e-432b-4fc4-8e29-309feba3fbc8.png)

**Comment by toohandsome** [comment]
it's weird,this debug version can't reproduce ,but it has another problem
when i stop server , the "input control" will be off .
like this :
![image](https://user-images.githubusercontent.com/46422252/178149901-cef0a7ac-75a3-4f89-b692-dc87ac2c0a9f.png)
last version it will stay on status.

and when i open option "rustdesk input Shortcuts",
like this:

![image](https://user-images.githubusercontent.com/46422252/178150039-fc47dafc-6b19-4380-b9e3-0781a7630fac.png)

the "input control" will  lose efficacy

![image](https://user-images.githubusercontent.com/46422252/178150067-6a59a397-96ed-4ad3-bb5b-e5c1a1f1b880.png)

**Comment by toohandsome** [comment]
btw, is there any way to configure  the length of the generated ID

**Comment by Heap-Hop** [comment]
>restart app when the service is running (stop service is normal), the "input control" will be off . (must restart android ).

Thx, but I can't reproduce too, :(
Does it only happen in this Debug apk?

Could you please check these two problems on Fdroid version again?
- server ID losed
- input control off when restart app

**Comment by toohandsome** [comment]
> * server ID losed

i can't reproduce also


> * input control off when restart app

i use redmi k50 , also can reproduce （not debug version）
like this:

https://user-images.githubusercontent.com/46422252/178172221-cbd92906-9f4e-4021-8108-635de1a8d730.mp4

**Comment by Heap-Hop** [comment]
@toohandsome Nice video, thanks a lot!

**Comment by toohandsome** [comment]
> @toohandsome
> 
> > input control off when restart app
> 
> I tested `RustDesk` and `droidVNC-NG` with redmi k50 in https://testit.miui.com/. Both apps run background Accessibility Services failed. Seems like MiUi OS limits the background service. https://www.zhihu.com/question/413200649 . Different Android Rom have different power strategies. I haven't found a solution for MiUi yet :( .

thanks . it's not a big deal。

The following information is for your reference
1.power strategies is unlimited
2.background is locked
3.when input control is opend , reboot android, input control is on status

![fe06e26edf1e759eb26ae0c8c3c69f5](https://user-images.githubusercontent.com/46422252/178390654-489e78d5-fca8-46e3-8d65-7f81f307d52b.jpg)
