### ISSUE TITLE
On Android app, characters typed with Bluetooth keyboard are double-typed

### ISSUE THREAD

**Issue by gloomy-lemon-debatable** [rustdesk/rustdesk#907]
**Describe the bug you encountered:**
On Android app, characters typed with Bluetooth keyboard are double-typed
...

**What did you expect to happen instead?**
(e.g.)Input:abc Output:aabbcc
...

**How did you install `RustDesk`?**
from F-droid

---

**RustDesk version and environment**
RustDesk v1.1.10-1 (Android11)

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/777

**Comment by gaetanolip** [comment]
same problem for me , android app, italian keyboard

**Comment by krisek** [comment]
Happens on my Chromebook controlling a Windows desktop (installed version 1.1.10-1 from the Play Store)

**Comment by yousefamar** [comment]
Same for Android app through Samsung DeX, with a generic bluetooth keyboard unfortunately. Crawling back to VNC I go :(

**Comment by rustdesk** [comment]
try out our niglhtly build

**Comment by gloomy-lemon-debatable** [comment]
It's now completely fixed. Thank you for your resolving.

**Comment by YiHui-Liu** [comment]
* Huawei MatePad 10.8 (Harmony OS 3.0) with RustDesk Version 1.1.10-1
* Window10 (22H2, 19045.2728) with RustDesk Version 1.1.9 (Installed)
I meet the same problem:

https://user-images.githubusercontent.com/30190271/227712554-a591602e-24b7-4450-9398-c2358e2b57d0.mp4

**Comment by YiHui-Liu** [comment]
similar issues:
* [Support and optimize for bluetooth Mouse and Keyboard native operations](https://github.com/rustdesk/rustdesk/issues/1739)
* [Bluetooth keyboard and Bluetooth mouse are experiencing problems in use (Android -> Windows 10)](https://github.com/rustdesk/rustdesk/issues/3576)

**Comment by rustdesk** [comment]
#1547
