### ISSUE TITLE
Will the NAT type cause the inability to connect to the self-built server?

### ISSUE THREAD

**Issue by sunlewuyou** [rustdesk/rustdesk#9071]
### Bug Description

**Please tell me: Will the NAT type cause the inability to connect to the self-built server? Please answer "yes" or "no". If the answer is "no", I guess: it is most likely caused by the hardware firewall of the host manufacturer, thank you!**

### How to Reproduce

Please do not close this issue. Please answer yes or no before closing it. Thank you!

### Expected Behavior

Please do not close this issue. Please answer yes or no before closing it. Thank you!

### Operating system(s) on local side and remote side

Windows 11 > debian 11

### RustDesk Version(s) on local side and remote side

1.3.0 -> 1.1.11-1

### Screenshots

Please do not close this issue. Please answer yes or no before closing it. Thank you!

### Additional Context

Please do not close this issue. Please answer yes or no before closing it. Thank you!

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
You will be blocked if you continue.
