### ISSUE TITLE
2FA prompt keep popping upon using port tunneling

### ISSUE THREAD

**Issue by Sirachosur** [rustdesk/rustdesk#9080]
### Bug Description

I'm using ComfyUI remotely.  Using RustDesk to tunnel 8188/tcp makes the rustdesk client prompt for 2FA constantly.

### How to Reproduce

Build a comfyui environment and start it with the --listen directive (make sure firewalld or similar firewall is off
Install Rustdesk with 2FA enabled on a computer on the same subnet as the comfyui instance
Connect to the rustdesk computer, tunnel port 8188 and connect using a browser using http://localhost:8188.

Enjoy.

### Expected Behavior

Ask 2FA upon initial connection and not every time a tcp SYN packet is sent.

### Operating system(s) on local side and remote side

MacOS (the latest one) <- Windows 11

### RustDesk Version(s) on local side and remote side

1.2.7 -> 1.2.7

### Screenshots

![image](https://github.com/user-attachments/assets/feadb735-143f-4d29-98a6-18ac0780e7bc)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/487
