### ISSUE TITLE
Same ID in cloned computer

### ISSUE THREAD

**Issue by Fish-Samasat** [rustdesk/rustdesk#9082]
### Bug Description

I have installed Rustdesk on one computer, then cloned the hard disk and restored this image on other computers and the ID is repeated on all cloned computers.

### How to Reproduce

Install Rustdesk 
Clone Hard Disk 
Restore to another computer 
Open Rustdesk

### Expected Behavior

Se espera que sea un ID diferente, o tener la posibildiad de generar un nuevo ID. 

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.2.3-2

### Screenshots

![image](https://github.com/user-attachments/assets/b23369d1-cb5d-42ac-9477-e490f5f115bf)
![image](https://github.com/user-attachments/assets/dc8bf47c-822b-4789-8d9e-b985a4e30324)

**Comment by rustdesk** [comment]
Duplicate
