### ISSUE TITLE
Dock icon frequently bouncing on macOS

### ISSUE THREAD

**Issue by GabrielGonGod** [rustdesk/rustdesk#9088]
### Bug Description

On macOS (Sonoma 14.6.1), RustDesk frequently bounces and flashes in the dock for no apparent reason. Exiting RustDesk or removing the icon from the dock doesn’t resolve the issue.

### How to Reproduce

After installation, the issue occurs.

### Expected Behavior

After installation, the issue occurs. I would prefer if the icon stays quietly in the background without this random bouncing, as it’s quite distracting.

### Operating system(s) on local side and remote side

macOS (Sonoma 14.6.1)

### RustDesk Version(s) on local side and remote side

1.2.7

### Screenshots

https://github.com/user-attachments/assets/4d3edbac-9fb6-45ee-a878-03f212cf0eb5

**Comment by rustdesk** [comment]
Try out https://github.com/rustdesk/rustdesk/releases/tag/nightly
