### ISSUE TITLE
Can I run this on VPS?

### ISSUE THREAD

**Issue by quetzalsly** [rustdesk/rustdesk#91]
If I have a ubuntu VPS, is it possible to have this software running 24/7 allowing someone to access remotely from anywhere?
If so then how does the security aspect work?
For example username + password, someone can try brute force it? is it possible to have something like: if more than 3 tries are wrong then ip is banned?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/blob/master/src/server/connection.rs#L593

**Comment by rustdesk** [comment]
> a ubuntu VPS

Never tested.

**Comment by rustdesk** [comment]
I guess you will get "No display" or some other error, because there is no active X session.

**Comment by rustdesk** [comment]
> the security aspect
https://github.com/rustdesk/rustdesk/blob/master/src/server/connection.rs#L593

**Comment by quetzalsly** [comment]
What if I install ubuntu or ubuntu with desktop environment? can you please tell me if sessions expire or I can just leave the software to run on boot? it would be a great solution if it just works with no interaction forever.

**Comment by rustdesk** [comment]
> What if I install Lubuntu or Ubuntu with desktop environment? can you please tell me if sessions expire or I can just leave the software to run on boot? it would be a great solution if it just works with no interaction forever.

Yes. a system service will be created, and run on boot.

**Comment by quetzalsly** [comment]
Great I will try it thanks!
