### ISSUE TITLE
The client cannot resolve IPv6

### ISSUE THREAD

**Issue by picpo** [rustdesk/rustdesk#9101]
### Bug Description

I am a self-hosting user, and my domain name resolves to both IPv4 and IPv6 addresses. I have set up RustDesk services on my home network. However, I discovered that while my macOS, iOS, and Android devices can connect to the RustDesk network via the domain name using the same 2.1.7 software version, Windows devices cannot. This puzzles me. I first ruled out the NAT loopback issue, as other devices and services automatically switch to the IPv6 route when encountering NAT loopback problems, but RustDesk seems to fail in this regard. The final solution was to use netsh interface to prioritize IPv6. I hope the RustDesk developers will pay attention to this issue. Other services can switch to IPv6 when IPv4 cannot be connected, but this software only displays "Not Ready. Please check your connection."

### How to Reproduce

Set up RustDesk services on the internal network, use a domain name for both A and AAAA records, and then connect to this domain using the client.

### Expected Behavior

Not ready. Please check connection

### Operating system(s) on local side and remote side

Windows11

### RustDesk Version(s) on local side and remote side

1.2.7

### Screenshots

Nothing to preview

**Comment by rustdesk** [comment]
#763
