### ISSUE TITLE
x86_64 AppImage crashed on Rocky Linux 8

### ISSUE THREAD

**Issue by ckywong** [rustdesk/rustdesk#9103]
### Bug Description

When running x86_64 AppImage on Rocky Linux 8, it crashed and show error message:
`/tmp/.mount_rustdeXX3U2f/usr/lib/rustdesk/rustdesk: symbol lookup error: /lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE`

### How to Reproduce

Run x86_64 AppImage on Rocky Linx 8, e.g.,
`./rustdesk-1.2.4-x86_64.AppImage`

### Expected Behavior

Rustdesk starts and shows its main window

### Operating system(s) on local side and remote side

Local side: Rocky Linux 8.10

### RustDesk Version(s) on local side and remote side

Local side:  >= 1.2.4

### Screenshots

![image](https://github.com/user-attachments/assets/f083894a-da3a-40be-b23e-1253eba8d057)

**Comment by rustdesk** [comment]
No way to ensure it can run every Linux.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/d1fe61767076cdf3b044c2dd87351da211bf6742

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/4e084c5ee0318c4ea24aa97d44d324a3480c981c
If anyone have time to test, please try it out
