### ISSUE TITLE
rustdesk 1.2.7 can't display correctly on arch / manjaro with scale > 100%

### ISSUE THREAD

**Issue by Shylock-Hg** [rustdesk/rustdesk#9106]
### Bug Description

Start failed.

### How to Reproduce
1. set scale to 150%
2. install and start https://github.com/rustdesk/rustdesk/releases/download/1.2.7/rustdesk-1.2.7-0-x86_64.pkg.tar.zst

os: manjaro-kde

### Expected Behavior

Start well.

### Operating system(s) on local side and remote side

any->manjaro

### RustDesk Version(s) on local side and remote side

any->1.2.7

### Screenshots

![Screenshot_20240818_182542](https://github.com/user-attachments/assets/6f92dd65-8411-43cb-9a14-043fc481ead9)

**Comment by fufesou** [comment]
I've tried three OSs.

| OS  | DESKTOP  | RESULT  |
| :--: | :---: | :--- | 
| Manjaro-kde-24.0.5 | KDE |   :x: | 
| KUbuntu-24.04 | KDE |   :white_check_mark: |
| Ubuntu 24.04 | Gnome |   :white_check_mark: |

**Comment by rustdesk** [comment]
Normal scale is ok?

**Comment by rustdesk** [comment]
What about a simple flutter demo?

**Comment by Shylock-Hg** [comment]
> non-fractional scale is ok?

100% is ok.

**Comment by rustdesk** [comment]
200%

**Comment by Shylock-Hg** [comment]
> 200% ?

I tried 125%, it reproduced too.

**Comment by rustdesk** [comment]
200% ?

**Comment by Shylock-Hg** [comment]
> 200% ?

Reproduced.

**Comment by fufesou** [comment]
> What about a simple flutter demo?

https://github.com/user-attachments/assets/3e5050ae-3bde-477f-8def-09572fe5c9ed


1. UI is not display correctly.
2. The cursor also has some bug.

**Comment by rustdesk** [comment]
@fufesou report this to Flutter.

**Comment by Shylock-Hg** [comment]
Also reproduced in `archlinux-kde`

**Comment by rustdesk** [comment]
> flutter 3.16.9,

Try out latest Flutter.

**Comment by fufesou** [comment]
Flutter 3.24.0, same issue.

**Comment by rustdesk** [comment]
Report to flutter.

**Comment by rustdesk** [comment]
Before Flutter fix this, use our Sciter version please.

**Comment by fufesou** [comment]
@Shylock-Hg Please confirm https://github.com/flutter/flutter/issues/153656#issuecomment-2297940096

**Comment by rustdesk** [comment]
Close this since there is nothing we can do.
