### ISSUE TITLE
Privacy Mode 2 doesn't work on latest nightly

### ISSUE THREAD

**Issue by mikemykhaylov** [rustdesk/rustdesk#9110]
### Bug Description

When connecting from a Mac to a Windows PC (in a VM for simplicity), Privacy Mode 2 fails to enable. Privacy Mode 1 works

### How to Reproduce

Try to enable Privacy Mode 2 when connected to the VM. Observe the following error:
```
Failed ChangeDisplaySettingsEx, ret: -1
```

### Expected Behavior

Privacy Mode 2 works

### Operating system(s) on local side and remote side

macOS 13.6.9 (22G830) -> Windows 11

### RustDesk Version(s) on local side and remote side

1.30.0 -> 1.30.0 (build dates 2024-08-19 00:24)

### Screenshots

https://github.com/user-attachments/assets/83874e10-2d3a-45b6-beae-d4aa1bf924d8

Password obviously changed

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/8994

**Comment by rustdesk** [comment]
1.2.7 works?

**Comment by mikemykhaylov** [comment]
Tested both client and server sjde, also doesn't with the same error

**Comment by rustdesk** [comment]
How about not in VM?

**Comment by mikemykhaylov** [comment]
Can't test Mac to Windows 11, but I can roll boot camp on Mac and do Android to Windows 10, don't have any other device handy. Gimme like an hour

**Comment by rustdesk** [comment]
Coud you try out this virtual display if it works on your VM? we use the same tech.

https://github.com/nomi-san/parsec-vdd

**Comment by mikemykhaylov** [comment]
Sure, what should I be looking for? Whether I can create the virtual display or not?

**Comment by rustdesk** [comment]
> Whether I can create the virtual display or not?

Yes.

**Comment by MatthK** [comment]
I have a similar problem. Installed a self-hosted Version 1.3.3 (client). Both the local and remote PC have Windows 10 installed.
Local PC with one monitor, the remote has 3 monitors.
Privacy Mode 1 works, however when turned on, it is not possible to switch to another monitor anymore, as the monitor icon vanishes
Privacy Mode 2 does not engage, or if, then it disengages immediately.

Are there some log files that I could check?

**Comment by fufesou** [comment]
@MatthK Thanks for the feedback.

You can check the log `C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT.log` on the controlled side.

There may be some logs that contains `EnumDisplaySettingsW` or `ChangeDisplaySettingsEx`.

Please paste them here. Or you can attach the log file here after removing some privacy infos.

**Comment by MatthK** [comment]
That was a quick response.

On the remote side I found these two lines at the bottom.

```
[2024-11-19 15:26:52.936875 +08:00] ERROR [src\privacy_mode\win_virtual_display.rs:244] Failed ChangeDisplaySettingsEx, device name: Ok("\\\\.\\DISPLAY1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"), flags: 268435457, ret: -2
[2024-11-19 15:26:54.729161 +08:00] ERROR [src\server\connection.rs:3038] Failed to turn on privacy mode. Failed ChangeDisplaySettingsEx, ret: -2
[2024-11-19 15:26:54.758675 +08:00] INFO [src\server\video_service.rs:654] dxgi error, fall back to gdi: Kind(InvalidData)
[2024-11-19 15:26:54.777952 +08:00] INFO [src\server\video_service.rs:520] switch to refresh
[2024-11-19 15:26:54.956981 +08:00] INFO [libs\scrap\src\common\vram.rs:316] set display#1 not use vram encode to false
[2024-11-19 15:26:54.957024 +08:00] INFO [libs\scrap\src\common\codec.rs:167] update:Check
[2024-11-19 15:26:54.957055 +08:00] INFO [libs\scrap\src\common\codec.rs:309] usable: vp8=true, av1=true, h264=true, h265=true
[2024-11-19 15:26:54.957064 +08:00] INFO [libs\scrap\src\common\codec.rs:312] connection count: 1, used preference: Auto, encoder: H265
[2024-11-19 15:26:54.957074 +08:00] ERROR [src\server\service.rs:308] Error of video1 service: SWITCH
[2024-11-19 15:26:54.985172 +08:00] INFO [src\server\display_service.rs:242] Displays changed
[2024-11-19 15:26:55.075774 +08:00] DEBUG [src\server\service.rs:305] Enter video1 service inner loop
```

And on the local side I could record an error message popping up for a split-second that said pretty much the same thing.
```
Privacy Mode
Failed ChangeDisplaySettingsEx, ret: -2
```

**Comment by fufesou** [comment]
Thanks a lot.
I'll put a possible fix later.

**Comment by rustdesk** [comment]
Could you the nightly (controlled side)?  https://github.com/rustdesk/rustdesk/releases/nightly
We have put a fix.

**Comment by MatthK** [comment]
Wow, that was a quick fix. Long message short: It works now.

In a bit more details. Privacy Mode 2 now works on a Windows 10 PC with multiple monitors. However, different to what I expected, on the local side the desktop gets reduced to a single window/monitor, so that "messes" up the window placements etc. But I guess that's how it's supposed to be. The remote PC turns black on all three monitors, which is as expected.
When I go out of Privacy Mode 2, the remote PC's Desktop settings also initially were messed up, with the taskbar being on the wrong monitor and open windows kinda disappeared. On the local PC, I only saw two monitors, and I guess one was the virtual one.
After disconnecting from the remote PC, the desktop settings recovered though and the taskbar was back to the correct monitor. 

I'm very much impressed by the speed of the solution made available. Much appreciated.

**Comment by fufesou** [comment]
> When I go out of Privacy Mode 2, the remote PC's Desktop settings also initially were messed up, with the taskbar being on the wrong monitor and open windows kinda disappeared. On the local PC, I only saw two monitors, and I guess one was the virtual one.

This behavior is not expected. I'll check what's going wrong.

There should be 3 physical monitors after exiting Privacy Mode 2.

**Comment by MatthK** [comment]
I tried once more and it seems now it is working better. 
Previously I added a virtual display, and it seems that somehow stayed there. I went back to normal mode with Privacy turned off. Then removed the virtual display and turned Privacay Mode 2 again. After that, it did restore the three monitors back to how they should be.
