### ISSUE TITLE
'Enable remote configuration modification' toggled off can be bypassed easily

### ISSUE THREAD

**Issue by nevaran** [rustdesk/rustdesk#9130]
### Bug Description

Since the window is locked after a few frames the mouse goes over the RD window, it is possible to use the screen's touchscreen to traverse the GUI and toggle the remote configuration option.
This is testesd and works when both endpoints arent installed, and one endpoint has the service started for connection. Connection lacency is from 5 to 20ms between two differnt sites within the same town

### How to Reproduce

Any way that has instant mouse position and click (like touchscreen). It is possible that latency also plays a role in this.

### Expected Behavior

Prevent changes or interaction with the GUI

### Operating system(s) on local side and remote side

Windows 11 - > Windows 10, 11

### RustDesk Version(s) on local side and remote side

1.3.0

### Screenshots

https://imgur.com/a/erALKmg

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2680#issuecomment-1975002181
