### ISSUE TITLE
Windows 7 Pro, Successful, Connected, waiting for image won't allow control. Logs in fine, but can't close dialog, only option is to "Cancel"

### ISSUE THREAD

**Issue by scrabjon** [rustdesk/rustdesk#9131]
### Bug Description

From Windows 7 Pro PC. This dialog box precludes any control except through the RustDesk control panel menu. It essentially blocks keyboard and mouse. Only option is to "Cancel" and close the connection. Tried changing all sorts of options to get it to work. Randomly, the dialog went away (timed out??) but I still could not control it with keyboard and mouse.

### How to Reproduce

From Windows 7 Pro, use latest 1.30 connecting to 1.27. Not unique to a computer, tried multiple PCs. Remote computers w10, w11, all with 1.27 remotely. Only the controlling PC had 1.30 and now not control is possible.

### Expected Behavior

Like 1.27, connect as usual with "waiting for image" to disappear after the remote screen comes up and allow keyboard and mouse control.

### Operating system(s) on local side and remote side

Windows 7 -> Windows 10,11

### RustDesk Version(s) on local side and remote side

1.30 -> 1.27

### Screenshots

![image](https://github.com/user-attachments/assets/757da8e0-6480-4ed3-ad42-4e4f3359e7cc)

### Additional Context

Sad to see Windows 7 is broken finally :(

**Comment by 21pages** [comment]
https://github.com/rustdesk/rustdesk/discussions/9124#discussioncomment-10391439

**Comment by scrabjon** [comment]
In my case it seems to be Windows 7 control side that doesn't work. In attempts to get a workaround, I broke Atera after adding a virtual display then removing it. I had to add it back to get control again.

**Comment by 21pages** [comment]
Could you show the log printed by that commit?

**Comment by rustdesk** [comment]
#763

**Comment by 21pages** [comment]
Could you try differernt versions as control side?

**Comment by 21pages** [comment]
https://github.com/21pages/rustdesk/releases/tag/history

Could you find the first program between 240724 and 20240815 that has this problem?

**Comment by rustdesk** [comment]
@scrabjon could you help test above?

**Comment by rustdesk** [comment]
Close since inactivitity.
