### ISSUE TITLE
--get-id not working

### ISSUE THREAD

**Issue by chileocat** [rustdesk/rustdesk#9136]
### Bug Description

Argument --get-id is not working, output is blank

### How to Reproduce

Running as administrator:
```
cd "c:\Program Files\RustDesk"
rustdesk.exe --get-id
```

### Expected Behavior

Should print my RustDesk ID, which I can see in the client (31 08x xxx).

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.3.0

### Screenshots

![grafik](https://github.com/user-attachments/assets/fa4ff1de-10b2-4b7c-bb12-d61e4c78cdcc)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/wiki/
