### ISSUE TITLE
No accept/decline window after windows client installation  (rdp session sharing)

### ISSUE THREAD

**Issue by KreativeKrise** [rustdesk/rustdesk#914]
**Describe the bug you encountered:**

If the Windows client was installed, the user gets no window to accept/decline the remote connection. If the portable version is used, it works fine.

**What did you expect to happen instead?**

If someone tries to connect remotely, the user should get a window to accept/decline the connection.

**How did you install `RustDesk`?**

- Downloaded rustdesk-1.1.9-x64.exe from GitHub release page
- Started rustdesk-1.1.9-x64.exe as user without admin permissions
- Pressed "Install" button
- On UAC entered the data of a user with admin permissions
- restarted the system

---

**RustDesk version and environment**

RustDesk 1.1.9 x64 Windows
Windows 10 21H2

**Comment by rustdesk** [comment]
There should be a window popped out after installation, it is wierd you can not see.

**Comment by rustdesk** [comment]
> That's what I expected. How can I debug this to get more useful information to find the problem?

I do not have clue or where to get useful info either.

**Comment by rustdesk** [comment]
You are the first one reporting this issue. Embarassing.

**Comment by rustdesk** [comment]
Both installation and portable version try to pop out window here.

https://github.com/rustdesk/rustdesk/blob/master/src/server/connection.rs#L1280

**Comment by KreativeKrise** [comment]
Could it be a problem that I'm connected via RDP to my testing machines? I installed the client on 2 laptops where I have physical access, 1 workstation with RDP access and 1 virtual machine with RDP access. On the 2 laptops everything works fine, on the RDP sessions it does not.

I had a similar problem with a deployment toolkit, which did not redirect the interactive elements to the correct user session.

**Comment by rustdesk** [comment]
Maybe, i have no the other execuse, :).

**Comment by KreativeKrise** [comment]
Session ID physical access: 1
Session ID RDP access: 2+

So a fix would probably be interesting for users who use a terminal server.

Unfortunately, I am not a software developer to help you to fix the issue. With PowerShell/Batch I would to a `query session`, grep the row with current logged in username and get the session ID. Then somehow the interactive elements must be redirected to that session.
