### ISSUE TITLE
Hbbs problem with windows server

### ISSUE THREAD

**Issue by Hydro8** [rustdesk/rustdesk#9142]
### Bug Description

Hi

I try to run my own server on a windows server 2016 but I have a problem with hbbs (hbbr works well). 

### How to Reproduce

I followed your tutorial, download NSSM and your window package. 

But when I try to launch hbbs with cmd, it say that system cannot execute the program. 

I tried to disable window defender and add the folder in path but it don’t work. 

### Expected Behavior

What is weird is that I install the server with the GUI version and it work ! I can even launch hbbs with cmd without any problem. 

Why the old version of hbbs work but not the new one ?

### Operating system(s) on local side and remote side

Windows server 2016

### RustDesk Version(s) on local side and remote side

Latest rustdesk server

### Screenshots

[
![IMG_2373](https://github.com/user-attachments/assets/33368e9a-4942-4da1-9f16-11162dbb839d)
](url)

### Additional Context

Any help to launch Hbbs on windows server 2016 ?
I tried on a classic windows 11 and it works well. 

Thanks !

**Comment by rustdesk** [comment]
#763
