### ISSUE TITLE
Privacy mode cannot display user control pop-ups properly

### ISSUE THREAD

**Issue by yanxin152133** [rustdesk/rustdesk#9146]
### Bug Description

Privacy mode cannot display user control pop-ups properly
![image](https://github.com/user-attachments/assets/ba9cc2e0-76b8-4297-b3df-267e788c2b56)

### How to Reproduce

Turn on privacy mode 1
Click on the software installation package that requires user control pop-up window for authorization

### Expected Behavior

Turn on privacy mode to display desktop content normally

### Operating system(s) on local side and remote side

win10 ltsc 1809

### RustDesk Version(s) on local side and remote side

1.2.7->1.2.7

### Screenshots

![image](https://github.com/user-attachments/assets/ba9cc2e0-76b8-4297-b3df-267e788c2b56)

**Comment by rustdesk** [comment]
This is not what we can control
