### ISSUE TITLE
A fault eaten my resources

### ISSUE THREAD

**Issue by py-lwb** [rustdesk/rustdesk#9147]
### Bug Description

i do not know where to check logs.
today i remove kde for xfce,it ancidently remove rustdesk,then i reinstall it.And found that (image)
![image](https://github.com/user-attachments/assets/e56e1cab-0e96-4523-8eb6-e702827056a1)

### How to Reproduce

I do not know

### Expected Behavior

High resource waste.

### Operating system(s) on local side and remote side

ubuntu-22.04

### RustDesk Version(s) on local side and remote side

1.1.9

### Screenshots

![image](https://github.com/user-attachments/assets/613bd2b0-3a82-453b-a06f-f62c5e5eb9a1)

### Additional Context

Tell me where can i found the log,i will public it to you

**Comment by rustdesk** [comment]
1.1.9 too old
