### ISSUE TITLE
When controlling Windows from Android, the top status bar of Android will not be hidden when using the hover keyboard and cannot be closed using RustDesk's keyboard button.

### ISSUE THREAD

**Issue by qixing-jk** [rustdesk/rustdesk#9148]
### Bug Description

After using RustDesk's keyboard button to call out the latest version of Gboard's hover keyboard, the Android top status bar cannot be hidden and cannot be closed using RustDesk's keyboard button.

Even after closing it with the keyboard's own close function, the problem is still not solved.

### How to Reproduce

1. Connect to Remote Desktop 
2. Click on the keyboard button (Enable Floating Keyboard, Gboard Keyboard) 
3. The top top status bar can no longer be hidden

### Expected Behavior

1. connect to the remote desktop
2. click on the keyboard button (enable floating keyboard, Gboard keyboard)
3. the top top status bar stays hidden
4. be able to close it again via RustDesk's keyboard button (this is the best case scenario)

### Operating system(s) on local side and remote side

Android14 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.7 -> 1.3.0

### Screenshots

![Clip_20240822_221100](https://github.com/user-attachments/assets/1d733ebb-c00d-4d74-9495-5b6d8f31cb80)
![Clip_20240822_221146](https://github.com/user-attachments/assets/21dd0eb4-5452-4871-affe-40a06b9dc8ee)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893
