### ISSUE TITLE
Invalid format displayed when changing ID

### ISSUE THREAD

**Issue by kidzgy** [rustdesk/rustdesk#9149]
### Bug Description

The ID I changed meets the requirements and no matter what I enter it shows an invalid format.
![20240822220650](https://github.com/user-attachments/assets/13071e64-b0d0-4bd7-b330-0392df956be8)

### How to Reproduce

My system is Windows 11 23H2 and I use my own ID server .
After installing the program, the ID will be randomly generated, at this time, I entered my ID server address and KEY in the network, and after connecting successfully, I started to modify my ID name, and found that, no matter how I entered the name, it prompted an invalid format.

### Expected Behavior

I hope the name change works.

### Operating system(s) on local side and remote side

Win 11,ver 10.0.22631.3880

### RustDesk Version(s) on local side and remote side

1.3.0

### Screenshots

Picture above

**Comment by rustdesk** [comment]
#763
