### ISSUE TITLE
Remote ID input will cause crashes on iOS 

### ISSUE THREAD

**Issue by zrll12** [rustdesk/rustdesk#9152]
### Bug Description

Editing the remote id input on the main page will make the app stop responding 

### How to Reproduce

Install v1.2.7 of the app

### Expected Behavior

Edit the id

### Operating system(s) on local side and remote side

iOS 17.1

### RustDesk Version(s) on local side and remote side

1.2.7

### Screenshots

![IMG_6931](https://github.com/user-attachments/assets/7cf7c782-fb61-40c3-82bc-d9637e647ded)

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893
