### ISSUE TITLE
privacy mode1 ，no pop Window

### ISSUE THREAD

**Issue by tqangxl** [rustdesk/rustdesk#9154]
### Bug Description

隐私模式1下，不弹出窗口

### How to Reproduce

privacy mode1 ，pop Window UAC Window 
os：win 2019 std

### Expected Behavior

no pop Window UAC Window 

### Operating system(s) on local side and remote side

win 11 --> remote side win 2019 std

### RustDesk Version(s) on local side and remote side

v1.3->v1.3

### Screenshots

![image](https://github.com/user-attachments/assets/090beda6-8620-4b71-b2e5-df652c4ea1b8)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/9146#issuecomment-2304144292
