### ISSUE TITLE
Dragging the remote desktop window displays abnormally under certain conditions.

### ISSUE THREAD

**Issue by YamatoRyou** [rustdesk/rustdesk#9159]
### Bug Description

Execute to step 3, the content on the window title bar disappears, as shown in the figure:
![{B15D6559-C847-58A6-AA84-34968C0675C5}](https://github.com/user-attachments/assets/f1a60004-c7ec-4bea-92eb-c0d4a09fac7a)

Execute to step 4, the window title bar becomes the Windows standard appearance, and the window client area is black, as shown in the figure:
![{B1C88D92-361E-1B72-3587-EF0A700DFA59}](https://github.com/user-attachments/assets/8e15f550-6bcd-45dd-a7f6-4e1f3cc33048)

Restore the window of the above appearance to the initial size and it will return to normal. If you repeat steps 3~4, the problem will reappear.

### How to Reproduce

0. Ensure the following prerequisites:  
    - Disable "Show window contents while dragging";
    - Have 2 monitors, and each monitor has its own desktop.
1. Connect to any remote desktop and make the remote desktop window appear;
2. Maximize the window (in my case, the window is maximized on the primary monitor);
3. Drag the window to another monitor and maximize it;
4. Drag it to the primary monitor.

**Moving and maximizing operations need to be completed before releasing the left mouse button.**

### Expected Behavior

n/a

### Operating system(s) on local side and remote side

x64 Windows 11 -> x64 Windows 7

### RustDesk Version(s) on local side and remote side

1.3.0 (x64) -> 1.3.0 (x64)

### Screenshots

n/a

### Additional Context

n/a

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/7342
