### ISSUE TITLE
Random repeated keystrokes seeeeeeeeeeeeent to the server

### ISSUE THREAD

**Issue by vaab** [rustdesk/rustdesk#9162]
### Bug Description

This makesss   the usage of rustdesk very cumbersommmme... in everyday usageeeeeeee...... Iss      that ennnnough as aaaaa description ooof            thhhe iiiiiissue ?
 

### How to Reproduce

It seems to be correlated with bad network network conditions (high jitter and low unstable upload).
Client is under windows, version 1.2.6

### Expected Behavior

Keys should not be repeated even under bad network conditions.

### Operating system(s) on local side and remote side

Windows 10 -> Ubuntu Linux 22.04

### RustDesk Version(s) on local side and remote side

1.2.6 -> 1.2.6

### Screenshots

Recording a video as I type                             to show the issuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuue.

### Additional Context

I'm aware of #189 but obviously it doesn't solve my problem but seems to be similar isssssssssssssssssssssssssue.

**Comment by fufesou** [comment]
https://github.com/rustdesk/rustdesk/pull/8757

Please try `1.3.0` on both sides.

**Comment by vaab** [comment]
With `1.3.0`, the remote host is limited to the dynamic of the windows client keyboard, which is not expected neither. I set my `xkbd rate 190 50` on the linux server side and was pleased to see that it was working correctly before. `1.3.0` is breaking that expectation, I'm returning to 1.2.6 on the client side for the moment as my network conditions improved enough to be usable.
