### ISSUE TITLE
AppImage crashed GDK_IS_PIXBUF (pixbuf)' failed void linux

### ISSUE THREAD

**Issue by Baturax** [rustdesk/rustdesk#9164]
### Bug Description

1.3.0 version crashed
`flutter: Register custom cursor with key _-1_320000000_320000000 (16.0,16.0)

(rustdesk:25188): GdkPixbuf-CRITICAL **: 21:54:11.201: gdk_pixbuf_copy: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(rustdesk:25188): Gdk-CRITICAL **: 21:54:11.201: gdk_cursor_new_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted
`

### How to Reproduce

tried to connect phone 

### Expected Behavior

    No crash
    working

### Operating system(s) on local side and remote side

void linux -> android 14arm64

### RustDesk Version(s) on local side and remote side

1.3.0 -> 1.3.0

### Screenshots

![image](https://github.com/user-attachments/assets/011f1532-4cfd-47f4-9724-55cc25e43f21)
![image](https://github.com/user-attachments/assets/88814c97-2b3a-4dc5-816c-2537d7766861)
![image](https://github.com/user-attachments/assets/c705c571-4dcc-4bf8-b5ff-cd7d41f5ede3)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/7013
