### ISSUE TITLE
Wrong key from ipad to mac

### ISSUE THREAD

**Issue by EmranMR** [rustdesk/rustdesk#9173]
### Bug Description

Hi,
Thank you all for such superb app, there is only one tiny problem that I have, I am not sure if it is a bug.
I am on latest versions of ipad and macos. I am connecting to the macos from my ipad. 
Unfortunately when i press the key for `6` the `;` is sent, and whew `;` is located `7`, also`7` sends `;` as well.

not sure what is causing this. I tried with and without ipad keyboard both do the same

### How to Reproduce

pressing ; should send ;
same with 6 and 7

### Expected Behavior

pressing ;  sends 7
`6` the `;`
`7` sends `;`

### Operating system(s) on local side and remote side

latest macos sonoma and ipadOS

### RustDesk Version(s) on local side and remote side

1.3.0 on mac, 1.2.7 on ipados which is latest

### Screenshots

I am not sure how can this issue be recorded.

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/8390

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/9717
