### ISSUE TITLE
Rustdesk --no-tray not work

### ISSUE THREAD

**Issue by xBr0th3rx** [rustdesk/rustdesk#9177]
### Bug Description

If I start rustdesk under Debian 11 with "rustdesk --no-tray" then a system tray is still displayed.

### How to Reproduce

Debain 11 KDE
Rustdesk Version: 1.3

Start rustdesk with "--no-tray" and close the window and the Icons shows in the system tray.

### Expected Behavior

Tray icon is not displayed.

### Operating system(s) on local side and remote side

Debian 11 > KDE

### RustDesk Version(s) on local side and remote side

1.3

### Screenshots

![Screenshot_20240826_112706](https://github.com/user-attachments/assets/6c46ef5f-d813-4aad-866d-1d3e258b954b)

**Comment by rustdesk** [comment]
https://rustdesk.com/docs/en/self-host/client-configuration/advanced-settings/#hide-tray
