### ISSUE TITLE
Multiple monitor feature is not working (Read the issue description)

### ISSUE THREAD

**Issue by Poojary-K** [rustdesk/rustdesk#9199]
### Bug Description

Recently installed rustdesk in ubuntu 22 , tried to access device which has multiple monitors but the computer A which is trying to remote access computer B (multi monitor system) .. not able to see multi monitor switcher in toolbar.
Turn out after 2 days of reading threads , surfiing internet...
This is causing only if ur accessing system which has wayland... for X11 works fine.

### How to Reproduce

Try on wayland system type 

### Expected Behavior

No multi monitor swicther in toolbar

### Operating system(s) on local side and remote side

Ubuntu 22

### RustDesk Version(s) on local side and remote side

1.3.1

### Screenshots

![Screenshot from 2024-08-28 18-38-25](https://github.com/user-attachments/assets/a5ccd77a-c924-42aa-9f8a-6cdcbc97cd2c)

### Additional Context

Works in X11 , but no in wayland

**Comment by rustdesk** [comment]
It is expected.
