### ISSUE TITLE
No desktop connection when using a relay server and connecting to an android device (1.3.0 only, waiting for image)

### ISSUE THREAD

**Issue by GoodSoulGermany** [rustdesk/rustdesk#9201]
### Bug Description

I was using up 1.2.7 before and everything was working fine. After a reboot, the services came online and I was able to connect. 

I was happy when 1.3.0 was announced and (stupidly) upgraded all my android devices to 1.3.0. That was a huge mistake. Since then I am unable to connect to any of these devices after a reboot anymore. Rustdesk stuck at "waiting for remote display" (sorry, german here, do not know what the english term is).

I was able to solve this by downgrading to 1.2.7 and everything is working fine again.

As a hint: I am using an own docker-image with my own hbbr/hbbs. Docker images are latest.

### How to Reproduce

Install 1.3.0 on PC and Android, try to connect to Android using a relay server. Both PC and Android need to be on totally different systems (via inet) and relay server itself should not be used.

### Expected Behavior

Connection should be possible as in 1.2.7.

### Operating system(s) on local side and remote side

Windows 10 (19045.4529) and Android 14

### RustDesk Version(s) on local side and remote side

1.3.0

### Screenshots

![2024-08-28 16_28_36-🕸️ POCO F5 Pro@POCO-23013PC75G - Remote Desktop - RustDesk](https://github.com/user-attachments/assets/74eeda49-ba92-43aa-8ffd-af10ded231aa)

**Comment by rustdesk** [comment]
How about 1.2.7 (pc) -> 1.3.0 (android)?

**Comment by 21pages** [comment]
We want to get the log of both side? Could you try https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.3.0-x86_64-waiting-for-image.exe and https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.3.0-aarch64-waiting-for-image.apk and send the logs to my email? `c3VuYm9lYXN5QGdtYWlsLmNvbQo=` base64.

**Comment by rustdesk** [comment]
Might be related https://github.com/rustdesk/rustdesk/pull/8985

**Comment by 21pages** [comment]
This program may fix your issue if caused by #8985.
https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.3.1-aarch64-use-ndk.apk

**Comment by rustdesk** [comment]
Please try this first

> How about 1.2.7 (pc) -> 1.3.0 (android)?

Then try this.

> This program may fix your issue if caused by https://github.com/rustdesk/rustdesk/pull/8985.
https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.3.1-aarch64-use-ndk.apk

**Comment by GoodSoulGermany** [comment]
- Using PC 1.2.7 connecting Android 1.3.0 works (can see image).
- Autostart of screencast does not work needed to put "appops set com.carriez.flutter_hbb PROJECT_MEDIA allow" to make it work as well as settings put secure enabled_accessibility_services com.carriez.flutter_hbb/.InputService. Don't know which of these two cmds did the job, but now its autostarting after a reboot.

**Comment by 21pages** [comment]
> Using PC 1.2.7 connecting Android 1.3.0 works (can see image).

So it's not the problem of android,  try out this https://github.com/rustdesk/rustdesk/discussions/9124#discussioncomment-10391439 to replace the windows program and paste the related log in the log commit, this can help us address the problem.

**Comment by rustdesk** [comment]
Also could you try below files under https://github.com/21pages/rustdesk/releases/tag/history

![image](https://github.com/user-attachments/assets/4c040939-298f-40a7-9913-cf9a54959730)

**Comment by wxdjf0212** [comment]
usage version 1.2.3-2 is ok，he connection speed is very fast，but above this  version connection speed is too bad

**Comment by rustdesk** [comment]
Close since no response.
