### ISSUE TITLE
make it available in flathub

### ISSUE THREAD

**Issue by olumolu** [rustdesk/rustdesk#9202]
### Bug Description

This is not available in flathub anydesk is already available in flathub

### How to Reproduce

Open flathub and search for rustdesk

### Expected Behavior

Rustdesk should be available in flathub

### Operating system(s) on local side and remote side

linux

### RustDesk Version(s) on local side and remote side

p

### Screenshots

None

**Comment by rustdesk** [comment]
Stop create duplicate
