### ISSUE TITLE
Password not shown on change init seetings when services is enabled.

### ISSUE THREAD

**Issue by Juniorsnet** [rustdesk/rustdesk#9203]
### Bug Description

When start rustdesk vía rustdesk.service can't change rustdesk settings in gui, password prompt not shown.

If I stop rustdesk.service and start rustdesk vía start menu everything works OK I can config rustdesk, setting password etc.

The password configured in rust desk vía start menu not work when start rustdesk vía rustdesk.service

### How to Reproduce

Clean install on Manjaro Linux with XFCE

### Expected Behavior

Change settings in service mode.

### Operating system(s) on local side and remote side

Manjaro Linux

### RustDesk Version(s) on local side and remote side

1.3.0

### Screenshots

![image](https://github.com/user-attachments/assets/8afd4f0c-2681-46ba-8057-47ab4f658496)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/wiki/FAQ#unlock-security-settings-not-work-on-some-linux
