### ISSUE TITLE
Remote cursor showing blue circle

### ISSUE THREAD

**Issue by nishantgupta01** [rustdesk/rustdesk#9214]
### Bug Description

Trying to remote connect from Windows 11 Pro 64-bit -> Windows 10 Pro 32-bit machine. the remote cursor shows as not arrow but a blue circle

There's another machine i am connecting (Windows 11 Pro 64-bit -> Windows 10 Pro 64-bit ). that machine shows remote cursor as arrow (no issues)

### How to Reproduce

U can reconnect to the machine and it will show the blue circle again

### Expected Behavior

Remote cursor should show arrow, unless u change the mouse settings

### Operating system(s) on local side and remote side

Windows 11 Pro 64-bit -> Windows 10 Pro 32-bit

### RustDesk Version(s) on local side and remote side

1.2.7 - > 1.3.0

### Screenshots

No need for screenshot. the remote cursor is a blue circle

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/4945
