### ISSUE TITLE
Rustdesk deletes autostart file after closing the incoming connection

### ISSUE THREAD

**Issue by Mohammad699** [rustdesk/rustdesk#9246]
### Bug Description

I couldn't find an option in the app to autostart it on linux so I created a file manually in ./config/autostart but after I connect to the computer from my Android phone and close the connection the file gets deleted.
Why this is happening and how to prevent it?

### How to Reproduce

Install the app on Ubuntu via .deb file 
goto ./config/autostart
create a file and name it `rustdesk.desktop`
open the file and put this in it :
```
 [Desktop Entry] 
 Type=Application 
 Exec=rustdesk --tray 
 NoDisplay=false 
```
Now connect to your computer from your phone and close the connection
Check the file you'll not find it.

### Expected Behavior

The file should remain there.

### Operating system(s) on local side and remote side

Tuxedo OS based on Ubuntu

### RustDesk Version(s) on local side and remote side

1.3.0

### Screenshots

![image](https://github.com/user-attachments/assets/0537b79e-e72c-4911-88d6-7adaef763154)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4863#issuecomment-2270345388

**Comment by rustdesk** [comment]
we will remove this "remove autostart file" in next version.
