### ISSUE TITLE
Config in Filename - not working

### ISSUE THREAD

**Issue by plittlefield** [rustdesk/rustdesk#925]
In the official documention, it mentions a trick to put the config details in the filename on a Windows computer.

https://rustdesk.com/docs/en/self-host/install/#put-config-in-rustdeskexe-file-name-windows-only

However, I have tried to do this on several different Windows computers and I cannot get it to autofill the ID/Relay Server + Key.

If I copy and paste them in manually, then it works ofcourse and saves the settings on a reboot.

Thanks.

**Comment by rustdesk** [comment]
#763
