### ISSUE TITLE
Application RustDesk is not open anymore error while rustdesk runs in the background on maOS Sequoia

### ISSUE THREAD

**Issue by rafajrichard** [rustdesk/rustdesk#9260]
### Bug Description

While RustDesk is running as a service it is unable to be opened via Spotlight, Finder etc. on macOS. Only option working is opening it from the menu bar item.

### How to Reproduce

Install RustDesk as a service on macOS.
Close all windows of RustDesk.
Try to open RustDesk from Spotlight.

### Expected Behavior

RustDesk opens normally.

### Operating system(s) on local side and remote side

macOS Sequoia

### RustDesk Version(s) on local side and remote side

1.3.0

### Screenshots

![CleanShot 2024-09-04 at 20 58 19](https://github.com/user-attachments/assets/48bdd032-0108-4482-a7c5-67fe4a6f6e9f)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/5631#discussioncomment-6943538

**Comment by rafajrichard** [comment]
Does not fix the issue permanently. The issue just came back.

**Comment by matthiasg** [comment]
I have the same issue since today. process running. Menu bar exists. Cannot open any window
