### ISSUE TITLE
Untranslated string (os error)

### ISSUE THREAD

**Issue by bovirus** [rustdesk/rustdesk#9261]
### Bug Description

Please check screenshot

### How to Reproduce

Disconnect device

### Expected Behavior

Translated string (errore s.o.)

### Operating system(s) on local side and remote side

Windows 10 22 H2 64bit

### RustDesk Version(s) on local side and remote side

1.3.0

### Screenshots

![image](https://github.com/user-attachments/assets/2dad87bc-9561-479d-92e4-9fade2bbade1)

### Additional Context

No additional context

**Comment by rustdesk** [comment]
This is from system, not from us.
