### ISSUE TITLE
probably memory leak

### ISSUE THREAD

**Issue by AddisZone** [rustdesk/rustdesk#9262]
### Bug Description

I used the task manager with "memory usage - decending" to see how much memory the main browser meanwhile is using. I expected it - as usuallly the case - as number one. But it was rustdesk with a usage of about 6GB! It can be seen in attached screenshot. In the first part of the diagram there are two open connections with a total of three transferred screens. The large drop in memory usage at ~6pm (18:00) is caused by a restart of rustdesk. Since then no connections. 

(Beside this rustdesk in general needs much memory resources 'just' for transferring data.)

### How to Reproduce

Start that powershell script for some hours
 
$processName = "RustDesk"
$logFile = "memory_usage_log.csv"
$interval = 10  # seconds

"Timestamp,WorkingSet(MB),PrivateMemory(MB)" | Out-File $logFile

while ($true) {
    $process = Get-Process -Name $processName -ErrorAction SilentlyContinue
    if ($process) {
        $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        $workingSet = $process.WorkingSet64 / 1MB
        $privateMemory = $process.PrivateMemorySize64 / 1MB
        "$timestamp,$workingSet,$privateMemory" | Out-File $logFile -Append
    } else {
        "Process not found: $processName"
    }
    Start-Sleep -Seconds $interval
}

### Expected Behavior

No raising memory usage.

### Operating system(s) on local side and remote side

Windows10-64 1809 LTSC

### RustDesk Version(s) on local side and remote side

both 1.2.7

### Screenshots

![rustdesk-1 2 7_memory-usage](https://github.com/user-attachments/assets/1c17ed94-1583-44b1-9921-ddb4b84338cb)

**Comment by AddisZone** [comment]
Sorry that I haven't found that before sending report.

**Comment by rustdesk** [comment]
Try out please, we fixed the leak, https://github.com/rustdesk/rustdesk/releases/nightly

**Comment by AddisZone** [comment]
Updated on both machines to 1.3.1. The problem seems to persist.
![rustdesk-1 3 1-mem-usage](https://github.com/user-attachments/assets/63a2499f-c673-439f-91cb-afd4947bd34b)

**Comment by 21pages** [comment]
>  The problem seems to persist (also without connection and regardless of controlled or controlling side).

If there is no connection, the memory leak may occur due to frequent rebuilds of the online state. We have implemented some optimizations, https://github.com/rustdesk/rustdesk/pull/9331,. Please try the latest nightly build.
