### ISSUE TITLE
Remote Mouse pointer bug

### ISSUE THREAD

**Issue by AriaRobav** [rustdesk/rustdesk#9274]
### Bug Description

I connect to various PCs remotely. In some cases, without a clear reason, the remote mouse pointer is not displayed (even though the corresponding option is selected), but instead, a blue circle with a dot in the center appears.  
If a function that involves changing the shape of the mouse is selected (for example, the window resizing function), the mouse takes that shape and does not change it until a function that modifies the pointer is used.

### How to Reproduce

I don't know

### Expected Behavior

If the Show Remote Mouse Pointer option is enabled, show the remote mouse pointer 

### Operating system(s) on local side and remote side

Windows 10/Windows 11

### RustDesk Version(s) on local side and remote side

1.2.3 and newer

### Screenshots

I'cant take a screenshot becouse of the mouse pointer in RusteDesk is displayed only when RustDesk remote windows has focus.
If I try to take a snapshot, it losses the focus and mouse pointer isn't shown

**Comment by nishantgupta01** [comment]
i had the same issue. i opened a bug request # 9214 but somebody telling me that this issue is fixed by following the steps in ticket https://github.com/rustdesk/rustdesk/discussions/4945 but this issue doesnt go away. Even if i follow the steps in 4945 ticket, this issue comes back.

**Comment by AriaRobav** [comment]
For me the steps in ticket https://github.com/rustdesk/rustdesk/discussions/4945 fixed the issue.
The reason of the issue was the lack of a physical mouss connected to the remore PC.
Thank you.

**Comment by hansolocambo** [comment]
> reason of the issue was the lack of a physical mouss connected to the remore PC. Thank you.

I use the remote computer only... remotely. Having to buy a mouse just to be able to see it on screen doesn't sound like a great option :/
Would be nice to just see the cursor. Why remove it in the first place O.o

So yeah I confirm. No mouse on remote computer = blue dot on main computer instead of cursor + no cursor on remote computer :/

Not the end of the world, but it's really not convenient to click precisely...
