### ISSUE TITLE
Unable to stop RustDesk service ("Exit" on tray menu)

### ISSUE THREAD

**Issue by Sunil178** [rustdesk/rustdesk#9286]
### Bug Description

Once the RustDesk is opened, unable to stop or close it.
There must be an option to enable / disable the startup application.
It starts at boot and don't close when clicked "Exit" button from the notification indicator.

What I understand is, whenever I exit the application even killing it from System Monitor, it restarts the application by default. Whenever clicked the "Exit" button, it restarts the application.

### How to Reproduce

Open the RustDesk, try to quit the application, it won't.

### Expected Behavior

It must close the RustDesk when clicked "Exit" button from the notification indicator.

### Operating system(s) on local side and remote side

Pop!_OS 22.04 LTS

### RustDesk Version(s) on local side and remote side

1.3.0

### Screenshots

Please find below the screen recordings where I tried by clicking "Exit" button and killing from system monitor application.

https://github.com/user-attachments/assets/b71fa614-745d-4247-a20a-ca1bf28d5646

https://github.com/user-attachments/assets/2ee66db2-2063-4113-9290-ff9e15d74096

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/9284

**Comment by rustdesk** [comment]
"Exit" button does have issue, introduced in 1.3.0. @21pages is following up.

**Comment by rustdesk** [comment]
`pkexec` causes us trouble endlessly, we have to find an alternative.

**Comment by mischa-robots** [comment]
I can confirm the behavior.

Version: rustdesk-1.3.0-x86_64.deb
on System: Ubuntu 23 and Ubuntu 24

I guess sending a SIGTERM is not enough?
I had to use `sudo kill -9 <pid>` to stop the main process.

**Comment by mrslowfloww** [comment]
I can confirm this happens on Kubuntu 24 too. Really annoying.

**Comment by rustdesk** [comment]
Please use the nightly build, https://github.com/rustdesk/rustdesk/releases/tag/nightly

**Comment by xlionjuan** [comment]
wow....it means we will lose fingerprint or security key authentication
