### ISSUE TITLE
Remote Cursor does not change

### ISSUE THREAD

**Issue by wwdto** [rustdesk/rustdesk#9294]
### Bug Description

Cursor does not change. The remote  hourglass-cursor does not change back to arrow-pointer, mouseover on window-border does not change to  double-arrows for scaling etc.

### How to Reproduce

Changed between different application-windows,  here: FileMaker Pro and Chrome

### Expected behaviour

mouse-pointer should be refreshed when situation changes

### Operating system(s) on local side and remote side

local: OSX 14.6  remote: Windows 11 Home

### RustDesk Version(s) on local side and remote side

MAC, 1.30 -> WIN 1.30

### Screenshots

https://github.com/user-attachments/assets/86a967b3-80ba-4a4d-85f2-ac5bd5ece1fd

[see screen-movie](https://nextcloud.dto-server.de/index.php/s/WPjxN2WrqoW8xai)

### Additional Context

when anydesk is simultaneos active, cursor behavior - also on RustDesk - works  as expected

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/9274

**Comment by rustdesk** [comment]
> when anydesk is simultaneos active, cursor behavior - also on RustDesk - works as expected

It seems anydesk does something like https://github.com/rustdesk/rustdesk/issues/9274#issuecomment-2334374678

**Comment by rustdesk** [comment]
Close since no repsonse.
