### ISSUE TITLE
Self built server cannot call self built server address

### ISSUE THREAD

**Issue by kaixlong** [rustdesk/rustdesk#9296]
### Bug Description

Building a self built server, whether changing the name or pulling cloud compilation from GitHub, cannot call the address of the self built server

Modify config. rs,
pub const RENDEZVOUS_SERVERS: &[&str] = &["xxx.com"];
pub const PUBLIC_RS_PUB_KEY: &str = "bddddddddddddddddddddddLPwOg=";

It's not possible either

Only by filling in the self built server data in the settings and network can it be linked

### How to Reproduce

After fixing the bug, change the name or pull GitHub to modify CONFIG RS file, enabling direct access to self built server data. thank you

### Expected Behavior

host=xx.com Can call self built servers

### Operating system(s) on local side and remote side

win7 win10 Android

### RustDesk Version(s) on local side and remote side

1.3.0

### Screenshots

![dddddd](https://github.com/user-attachments/assets/ea27cb7e-dc35-4b9b-af81-b02c0d6afd4a)

**Comment by rustdesk** [comment]
#763
