### ISSUE TITLE
Empty White Screen On Startup

### ISSUE THREAD

**Issue by nxiss7** [rustdesk/rustdesk#93]
Hi
I tried using the program on KDE Neon but it just shows a blank, white screen. 
It complains about wrong DOM model etc. in the console output.

System Details:
Kernel: 5.11.15-051115-generic x86_64
Desktop: KDE Plasma 5.22.1 
Distro: KDE Neon 20.04 5.22 (Based on Ubuntu 20.04)
GPU: AMD Radeon RX Vega 7
OpenGL: AMD RENOIR (DRM 3.40.0 5.11.15-051115-generic LLVM 11.0.0) v4.6 Mesa 20.2.6 

Console Output:
ERROR:TIS: Error: bad syntax : Expecting a primary expression
ERROR:TIS: line:var svg_checkmark = ;
ERROR:TIS: here:____________________^
ERROR:TIS: file:(index.html(125))
WARNING:CSS: unrecognized property name syntax at (index.html(1))
ERROR:DOM: Creation of behavior edit was rejected by <input> element. Wrong DOM model.
ERROR:DOM: Creation of behavior edit was rejected by <input> element. Wrong DOM model.
ERROR:DOM: Creation of behavior edit was rejected by <input> element. Wrong DOM model.
ERROR:DOM: Creation of behavior edit was rejected by <input> element. Wrong DOM model.
ERROR:DOM: Creation of behavior edit was rejected by <input> element. Wrong DOM model.
ERROR:DOM: Creation of behavior edit was rejected by <input> element. Wrong DOM model.
ERROR:DOM: Creation of behavior edit was rejected by <input> element. Wrong DOM model.
ERROR:DOM: Creation of behavior edit was rejected by <input.input}> element. Wrong DOM model.
ERROR:DOM: Creation of behavior password was rejected by <input> element. Wrong DOM model.
ERROR:DOM: Creation of behavior password was rejected by <input> element. Wrong DOM model.
ERROR:DOM: Creation of behavior edit was rejected by <input#remote_id.outline-focus> element. Wrong DOM model.
WARNING:CSS: unrecognized property name syntax at (index.html(1))
WARNING:CSS: unrecognized property name syntax at (index.html(1))
WARNING:CSS: unrecognized property name syntax at (index.html(1))

White screen:
![Screenshot_20210620_171123](https://user-images.githubusercontent.com/32893517/122677352-ac684880-d1ea-11eb-82cb-ae94cde68501.png)

**Comment by rustdesk** [comment]
Noted with thanks
