### ISSUE TITLE
 Incorrect Image Orientation when Remoting into Microsoft Surface or Windows Tablet

### ISSUE THREAD

**Issue by deadboy18** [rustdesk/rustdesk#9301]
### Bug Description

When using RustDesk version 1.3.0 on Windows 10 to connect to a Microsoft Surface Pro 4 or other Windows tablets with gyroscopic capabilities, the image orientation on the local side adapts to the tablet's orientation rather than maintaining a consistent orientation relative to the remote desktop view.

### How to Reproduce

Start RustDesk version 1.3.0 on Windows 10.
Connect to a Microsoft Surface Pro 4 or any Windows tablet with gyro.
Observe the image orientation on the local screen.
Rotate the tablet and notice how the image orientation on the local screen changes accordingly.

### Expected Behavior

The image orientation on the local screen should remain consistent regardless of the tablet's orientation. Similar behavior to AnyDesk where the image auto-rotates to match the correct orientation for the local viewer.

### Operating system(s) on local side and remote side

Windows 10 22H2 on both end local and remote side

### RustDesk Version(s) on local side and remote side

1.3.0 on both side 

### Screenshots

![image](https://github.com/user-attachments/assets/4248d6f5-1c03-412c-aa30-3ea16135de89)
![image](https://github.com/user-attachments/assets/f357ab51-0425-45c4-9931-ee04af5406f7)
Below is Anydesk
![image](https://github.com/user-attachments/assets/e6a79ae5-2c3b-43e6-a214-d9aaeb3b3c60)

### Additional Context

 This issue has been tested and observed consistently on Microsoft Surface Pro 4 devices. The issue impacts user experience when remote desktop orientation does not match local expectations, unlike behavior observed with other remote desktop solutions such as AnyDesk.
 
 Discord Message Link: https://discord.com/channels/804630702657110016/804630702657110018/1281075454777753664

**Comment by fufesou** [comment]
@deadboy18 Hi, thanks for your feedback.

Only this orientation has this issue?

<img width="162" alt="d73d03f6eb86e20cefb18f9cc2a07b5" src="https://github.com/user-attachments/assets/a48890f0-cd2b-4c2e-855b-a3a7cdaf2b51">

How about the other two "Portait" orientation?

**Comment by fufesou** [comment]
Could you also test if this build works fine?
