### ISSUE TITLE
use wechat screenshot,crash.

### ISSUE THREAD

**Issue by shizenghua** [rustdesk/rustdesk#9302]
### Bug Description

use wechat screenshot,crash.
if i restart,always crash.
if i copy a text,restart again,it's normal.

### How to Reproduce

use wechat screenshot,crash.

### Expected Behavior

use wechat screenshot,crash.

### Operating system(s) on local side and remote side

windows 11

### RustDesk Version(s) on local side and remote side

1.3.0

### Screenshots

use wechat screenshot,crash.

**Comment by martint028** [comment]
I also encountered the same problem

**Comment by fufesou** [comment]
@shizenghua @martint028 Thanks for your feedback.

It seems the app crashes when "copy&paste" the image data.

But I've tried both `1.3.0` -> `1.3.0` and `1.3.1` -> `1.3.1`, both Windows. It does not crash.

Could you please:
1. Try `1.3.1` -> `1.3.1`
2. Connect, then use "PrtScr" to "copy&paste" screenshot

![image](https://github.com/user-attachments/assets/d27b2db2-3ce2-47b0-bb60-338cc02d8ffe)

**Comment by martint028** [comment]
Is it because of using the clipboard synchronization feature of the WeType input method in WeChat that all my Windows 11 computers experience the same crash? Even after upgrading to version 1.3.1, the issue remains the same.

**Comment by fufesou** [comment]
> Is it because of using the clipboard synchronization feature of the WeType input method in WeChat

Maybe

@martint028 I've tried 1.3.1 -> 1.3.1 again. But failed to reproduce this issue. Could you please give a short video, thanks?

**Comment by rustdesk** [comment]
Close since no response and we can not reproduce.

**Comment by fufesou** [comment]
@shizenghua @martint028 could u please test this build on both sides? https://github.com/fufesou/rustdesk/releases/tag/test-clipboard-win-crash
