### ISSUE TITLE
Mouse cursor disappears when using web client to connect with Android device

### ISSUE THREAD

**Issue by ouyangyi1998** [rustdesk/rustdesk#9303]
### Bug Description

I cannot find mouse cursor when connecting with Android device using web client.
*The Rustdesk Input has been installed on Android device.
Thanks in Advanced！

### How to Reproduce

1: Use the web client.
2: Connect with Android device.

### Expected Behavior

1: Use mouse to control Android device via web client

### Operating system(s) on local side and remote side

Chrome > Android 10

### RustDesk Version(s) on local side and remote side

webclient-> Rustdesk(1.3)

### Screenshots

*

**Comment by rustdesk** [comment]
web client is being rewritten.
