### ISSUE TITLE
Win 7 -> Android mouse wheel does nothing

### ISSUE THREAD

**Issue by tigros** [rustdesk/rustdesk#9321]
### Bug Description

Hi,
Thanks so much for this program! Coming from windows teamviewer -> LG G7 phone to new Pixel 8 phone. Teamviewer doesn't remote control this phone :(
Everything is fine except the mouse wheel does nothing, looked around to fix but futile.
Not sure if it's Windows 7 problem? Guess i could try Win 10 partition but Win 7 is main OS.

### How to Reproduce

scroll the wheel

### Expected Behavior

should scroll w/e i'm looking at.

### Operating system(s) on local side and remote side

Win 7 ultimate -> Pixel 8 android 14

### RustDesk Version(s) on local side and remote side

1.3.0.46 -> 1.3.0

### Screenshots

![image](https://github.com/user-attachments/assets/7b33e686-54cf-4785-9e9a-343ab0396a07)

**Comment by rustdesk** [comment]
Physical keyboard and mouse not fully support yet.

**Comment by TtuxX** [comment]
Hi all! All my apologies for pinging this issue but I also encounter it.
Do you know if such support will one day be possible ? 
Many thanks in advance !
