### ISSUE TITLE
In ubuntu20.04.5, certain conditions caused the ubuntu system Settings to crash

### ISSUE THREAD

**Issue by Carl-haijiao** [rustdesk/rustdesk#9323]
### Bug Description

The Settings screen of the ubuntu system crashes

### How to Reproduce

Run the sudo apt install -fy /rustdesk-1.3.0-x86_64.deb command on ubuntu20.04.5. Go to the ubuntu Settings screen and click the Users option. The ubuntu Settings will crash and you will no longer be able to access the Settings screen

### Expected Behavior

System functions are not affected

### Operating system(s) on local side and remote side

local side ：Ubuntu 20.04.5 LTS (GNU/Linux 5.15.0-46-generic x86_64)。remote side：Ubuntu 20.04.2 LTS

### RustDesk Version(s) on local side and remote side

1.3.0 

### Screenshots

The Settings return to normal after using apt install pipewire

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
