### ISSUE TITLE
Not all mouse buttons are trigger

### ISSUE THREAD

**Issue by ikfir** [rustdesk/rustdesk#9337]
### Bug Description

As the title said
Not all mouse button are being send to the endpoint
If I want to browse the web and go back I can't press the `BACK` button on the mouse same apply for `FORWARD`
![image](https://github.com/user-attachments/assets/311ba474-6347-421b-aaea-ae696b462c10)

### How to Reproduce

Try to use web browser and going back using `BACK` button on phsyical mouse

### Expected Behavior

Being able to press on `BACK` & `FORWARD` buttons

### Operating system(s) on local side and remote side

Arch -> Arch

### RustDesk Version(s) on local side and remote side

1.3.0-4 -> 1.2.7-1

### Screenshots

![image](https://github.com/user-attachments/assets/311ba474-6347-421b-aaea-ae696b462c10)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/9185
