### ISSUE TITLE
Invalid 32bit application after first run - there is no installation in first execution

### ISSUE THREAD

**Issue by aquananu** [rustdesk/rustdesk#9338]
### Bug Description

when trying to run the 32 bit on win xp sp3, the application runs for once and then there is no action in the foreground.

then if we try to run it again, then it says invalid 32bit application  

### How to Reproduce

download 32bit and run

### Expected Behavior

no action on first run

second run file is corrupted

### Operating system(s) on local side and remote side

windows xp sp3

### RustDesk Version(s) on local side and remote side

1.3.0

### Screenshots

none

**Comment by rustdesk** [comment]
not support xp.
