### ISSUE TITLE
Keyboard not working on RHEL 8.6

### ISSUE THREAD

**Issue by reiserfn** [rustdesk/rustdesk#934]
**Describe the bug you encountered:**
Keyboard input is not working when i connect to Windows VM from my Rhel 8.6 machine. 
...

**What did you expect to happen instead?**
Keyboard to work, mouse is working fine.
...

**How did you install `RustDesk`?**
I am using rustdesk-1.1.9-windows_x64-portable.zip with RustDesk-1.1.10-x86_64_1804.AppImage

---

**RustDesk version and environment**

RHEL 8.6, 4.18.0-372.9.1.el8.x86_64
Windows 10 Pro Version 21H2 (Build 19044.1806)

**Comment by rustdesk** [comment]
How about if install?

**Comment by reiserfn** [comment]
Keyboard is also not working with install.

**Comment by reiserfn** [comment]
I don't see any error message. Only a warning that a wayland session is not supported but i assume that is only relevant if try to connect to the wayland session as the remote client?

**Comment by rustdesk** [comment]
> the remote client

No, both side has the same problem. Please wait a moment for our wayland support.

**Comment by Extarys** [comment]
FWIW Fedora 36 KDE/Wayland here with RustDesk native 1.1.9, I can control a remote Windows 10 machine with mouse, but I cannot send keyboard inputs. Client on Windows is natively installed too.

I installed hbbs/hbbr yesterday and never played with RustDesk before but it's safe to say it must be a Wayland issue :man_shrugging: 

Nonetheless I'm very impressed with RustDesk <3 Gonna follow the wayland support issue.

**Comment by rustdesk** [comment]
Wayland support is under dev
