### ISSUE TITLE
Mouse klick + letter not working on AArch64 (ARM64)

### ISSUE THREAD

**Issue by EgertKanep** [rustdesk/rustdesk#9345]
### Bug Description

After connecting from client to host, I try to utilize a shortcut for a program which requires a left klick and letter "t" combination, but it does not work. I have tested with x86 rustfdesk client ant it works there. Other buttons like shift and ctrl seem to be working.

### How to Reproduce

Install rusdesk AArch64 (ARM64) version. Connect to host computer and try to use letter + mouse klick combination to control program.

### Expected Behavior

To be able to use letter + klick combination to control program. 

### Operating system(s) on local side and remote side

Armbian 24.8.1 -> Rocky Linux 9

### RustDesk Version(s) on local side and remote side

1.30 -> 1.30

### Screenshots

none

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565
