### ISSUE TITLE
Virus Detected by Chrome 

### ISSUE THREAD

**Issue by zarion99** [rustdesk/rustdesk#938]
RustDesk-Master triggers a virus warning. 
**Describe the bug you encountered:**

...

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/855

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/144
