### ISSUE TITLE
keyboard not working from win10 x32 to win10 x64

### ISSUE THREAD

**Issue by div4r4k** [rustdesk/rustdesk#9390]
### Bug Description

Hello, I can connect my win10 x32 machine to control my x64 win10 machine, mouse works, but keyboard don't. Using latest version.
If I use my phone to control my x64 machine there is no issues.
Please help.

### How to Reproduce

just connect 

### Expected Behavior

when I type on my local keyboard, the remote screen responds

### Operating system(s) on local side and remote side

win10 x32 -> win10 x64

### RustDesk Version(s) on local side and remote side

1.3 both sides

### Screenshots

no screenchots

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/9143
