### ISSUE TITLE
Privacy mode 2 will not automatically match the resolution of the local screen

### ISSUE THREAD

**Issue by ZhaoZelin2000** [rustdesk/rustdesk#9396]
### Bug Description

Privacy mode 2 will not automatically match the resolution of the local screen

### How to Reproduce

When I activate privacy mode 2

### Expected Behavior

Privacy mode 2 automatically matches the resolution of my local computer

### Operating system(s) on local side and remote side

OS 名称:          Microsoft Windows 11 专业版 OS 版本:          10.0.22631 暂缺 Build 22631

### RustDesk Version(s) on local side and remote side

1.3.0->1.3.0

### Screenshots

![image](https://github.com/user-attachments/assets/31a4a238-75fb-4e6c-81d1-933711684820)

**Comment by fufesou** [comment]
Yes, it would be better if privacy mode screen matches local.
But both scale and resolution must be set. No suitable API was found for setting scale.
