### ISSUE TITLE
Crash After Unlock Network Settings

### ISSUE THREAD

**Issue by JimmyLX** [rustdesk/rustdesk#9408]
### Bug Description

100% Crash After clicking "Unlock Network Settings" on Macbook Pro 2017 macOS 13.7 (22H123)
All the permissions are granted, apple's crash log attached

Spec:
2.9 GHz 4 Intel Core i7 
Radeon Pro 560 4 GB
Intel HD Graphics 630 1536 MB 
16 GB 2133 MHz LPDDR3

### How to Reproduce

100% Crash After clicking "Unlock Network Settings"

### Expected Behavior

Unlock the network setting

### Operating system(s) on local side and remote side

macOS 13.7 (22H123)

### RustDesk Version(s) on local side and remote side

1.3.0

### Screenshots

https://github.com/user-attachments/assets/5a3bce5a-5c84-4e40-8164-46e7a0084fea

### Additional Context

apple's crash log attached
[RustDeskCrashLog.txt](https://github.com/user-attachments/files/17069282/RustDeskCrashLog.txt)

**Comment by rustdesk** [comment]
Sorry, we won't maintain old mac.

**Comment by xlionjuan** [comment]
Try clear all data/config.

1. Close & Stop RustDesk 
2. Goto Library (資源庫)-> Application Support, find RustDesk folder, delete it (let me know if I'm remember wrong.)
3. Try if it still crashes

**Comment by JimmyLX** [comment]
After uninstalling & cleaning all the files related to RustDesk, reinstall and crash issue remains.
After exiting all other softwares(VPN related, like Clash, Surge 5), it kinda works now. I am aassuming it's port conflict?

Thanks for the reply and your time!
