### ISSUE TITLE
"Check for software update on startup" not working?

### ISSUE THREAD

**Issue by ozgurkazancci** [rustdesk/rustdesk#9453]
### Bug Description

"Check for software update on startup" not working. Tested on: 1.3.0 on Windows 10 - 64 bit.

### How to Reproduce

"Check for software update on startup" not working. Tested on: 1.3.0 on Windows 10 - 64 bit.

### Expected Behavior

Ask each time/install whenever there is a new update.

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.3.0

### Screenshots

No screenshot.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/9444

**Comment by carloscampano** [comment]
Can you add the option for auto-update? And is it possible not to elevate the UAC with cmd when it is installed?
