### ISSUE TITLE
IOS 1.3.1

### ISSUE THREAD

**Issue by Nawaki89** [rustdesk/rustdesk#9455]
### Bug Description

If you have shared address book open and swap to another one the UI is not displaying the new groups units.  Still shows the first group you have open. 

Close the app and reopen and it will select the most recent group you tried to view and display the correct units. 

### How to Reproduce

Open a shared address book and try another one.

### Expected Behavior

To display the correct units in that shared address book.

### Operating system(s) on local side and remote side

IOS

### RustDesk Version(s) on local side and remote side

1.3.1

### Screenshots

![IMG_9689](https://github.com/user-attachments/assets/a2b99699-37ca-4f68-b7fe-4676c9f72c10)
![IMG_9688](https://github.com/user-attachments/assets/bdfcdb44-27e6-43bd-891e-c7fc9530b331)

**Comment by rustdesk** [comment]
@21pages
