### ISSUE TITLE
Nightly Build not adding repository secrets to Packages

### ISSUE THREAD

**Issue by NoirPi** [rustdesk/rustdesk#9460]
### Bug Description

I reproduced every step from this How-To and all builds ran through.
But after downloading the builded packages there are no RENDEZVOUS_SERVER and RS_PUB_KEY are set.

https://rustdesk.com/docs/de/dev/build/all/

### How to Reproduce

Just follow the instructions under:
https://rustdesk.com/docs/de/dev/build/all/

### Expected Behavior

RS_PUB_KEY and RENDEZVOUS_SERVER should be baked in the finished builds

### Operating system(s) on local side and remote side

Windows 10 - Docker Container on a Debian Bookworm Host

### RustDesk Version(s) on local side and remote side

1.3.1 - latest Docker image

### Screenshots

# Here the set Action secrets
![image](https://github.com/user-attachments/assets/070e2e8a-fadb-4f40-a561-8e384443811c)
# Here the load image 
![image](https://github.com/user-attachments/assets/60fd943f-aa60-412f-a730-873c2743e36a)

**Comment by rustdesk** [comment]
#763
