### ISSUE TITLE
Windows->Mac, can't do anything when Mac shows screen saver or black

### ISSUE THREAD

**Issue by veigarwang** [rustdesk/rustdesk#947]
**Describe the bug you encountered:**
![image](https://user-images.githubusercontent.com/75204277/177916982-e634600a-33e8-4513-9bda-dadc85d8aa4e.png)
I can't do anything when Mac shows screen saver or black.
System: Win10, MacOS Catalina 10.15.7
...

**What did you expect to happen instead?**
Mac can be controlled even if it shows screen saver or black(sleep mode?).
...

**How did you install `RustDesk`?**
Win: rustdesk-1.1.9-windows_x64.zip
Mac: rustdesk-1.1.9.dmg

---

**RustDesk version and environment**
1.1.9

**Comment by rustdesk** [comment]
Sorry,  technically "it shows screen saver or black" can not done. Our implementation is recording console session, rather than creating new session like RDP, VNC.
