### ISSUE TITLE
Maximize Window Bug

### ISSUE THREAD

**Issue by Aerasyn** [rustdesk/rustdesk#9479]
### Bug Description

When remoting into a 1080 laptop from a 4K desktop pc (not sure if resolution difference is important) I will minimize a window to look at another and then when I maximize the rustdesk session window the display will be shrunken way small and have a strange graphical line horizontally though the screen above the shrunken image of the remote display. Going fullscreen and then unfullscreening fixes it. This is happening in current 1.3.1 version and was present in 1.3 version as well. It is not a 100% consistent error either. Sometimes it won't do make the error

### How to Reproduce

Minimizing remote display window and then maximizing it. Possible 4K to 1080 resolution issue

### Expected Behavior

Minimizing and maximizing the window resulting in the same display size after maximizing

### Operating system(s) on local side and remote side

Local Windows 11

### RustDesk Version(s) on local side and remote side

1.3.1 both sides

### Screenshots

![image](https://github.com/user-attachments/assets/5576ad0a-88f5-496d-9782-e8812e97df00)
This is after maximizing the window

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
Could you also try out 1.2.7 / 12.6 / 1.2.3? only on controlling side, no need to install.

**Comment by Aerasyn** [comment]
Can't seem to reproduce the error on either of those versions. Just 1.3+ so far.

**Comment by rustdesk** [comment]
Please test https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.3.2-x86_64.exe

**Comment by Aerasyn** [comment]
Tried my hardest to get it to bug again. This version didn't let it happen. Looks good.
