### ISSUE TITLE
[Windows OS] Window size exceeds screen limit when restore from minimize

### ISSUE THREAD

**Issue by letrungdo** [rustdesk/rustdesk#9481]
### Bug Description

When restoring window from minimize, window overflows beyond monitor size

### How to Reproduce

1. Connect laptop to external monitor
2. Open app and press Connect to open child Window
3. If the child window is opened on the external monitor, drag it to the laptop screen.
4. Press the maximize button in the child window then minimize this window
5. Restore window from taskbar

### Expected Behavior

When restoring from minimize, the window displays full screen, not overflowing.

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.3.1

### Screenshots

[screen-capture.webm](https://github.com/user-attachments/assets/c1c414ab-f84e-4383-8b9d-2057a95c5432)

### Additional Context
I think it might come from fixing this bug:
https://github.com/leanflutter/window_manager/issues/483#issuecomment-2375724990

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
Could you also try out 1.3.0 / 1.2.7 / 12.6 / 1.2.3? only on controlling side, no need to install.

**Comment by fufesou** [comment]
No need to try.
I've reproduced this issue. I'll fix it.

**Comment by letrungdo** [comment]
@fufesou @rustdesk Thank you! version 1.2.7 is OK

**Comment by letrungdo** [comment]
@fufesou @rustdesk Thanks for your quick support!
Besides, I saw this bug, I think it's related so I want to ask you to help fix it.
Version 1.2.7 OK
Version 1.3.1 NG
### How to Reproduce
Toggle maximize child window, then go to settings and adjust the Display scale to 150%, then adjust the scale to 100%
=> scale 100% it scales larger than 150% => NG
[screen-capture.webm](https://github.com/user-attachments/assets/dc9894e4-5b08-4a87-bfe9-0fec02751424)

**Comment by rustdesk** [comment]
Please test https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.3.2-x86_64.exe

**Comment by fufesou** [comment]
> => scale 100% it scales larger than 150% => NG

Reproduced, I'll fix it.

**Comment by fufesou** [comment]
> => scale 100% it scales larger than 150% => NG

It seems this line can affect the scale factor of the window.

https://github.com/rustdesk-org/rustdesk_desktop_multi_window/blob/af2e9a51f18effd9796bebb2fa75e0b7ef079613/windows/flutter_window.h#L109

The scale factor is connrect if
1. Commnet out this line
2. `sz->rgrc[0].bottom += 8` or someother consts number.
3. Change to   (Resolution `1920x1080`, switching between `100` and `150`)

```C
if (t == -8) {
     // The same value to  `sz->rgrc[0].bottom += t;`
    sz->rgrc[0].bottom = 1032;
} else {
     // The same value to  `sz->rgrc[0].bottom += t;`
    sz->rgrc[0].bottom = 1008;
}
```

I don't know why this line affects. Maybe the logic is not good elsewhere.

Or there are some problems with Windows here.

Sorry I cann't find a way to solve it right now.
I can only note this issue and keep an eye out for possible causes. Maybe I will find a solution someday.

**Comment by rustdesk** [comment]
Stop spending time on the corner case, we have long todo.

**Comment by letrungdo** [comment]
@fufesou Thanks! Based on your suggestion, I fixed it in this commit
https://github.com/rustdesk-org/rustdesk_desktop_multi_window/commit/b715c9859636da4a7fa1b1807156a94ae6a49fdb
