### ISSUE TITLE
Rustdesk 1.3.1 Android Failed to receive public key

### ISSUE THREAD

**Issue by ChayneC** [rustdesk/rustdesk#9492]
### Bug Description

I upgraded my self host rustdesk setup.
New AWS instance Debian 12 -  Docker installed version 1.3.1

> /opt/rustdesk$ sudo docker ps
CONTAINER ID   IMAGE                             COMMAND                  CREATED      STATUS      PORTS                                                                                                                                                                 NAMES
1fb4b39f8acf   rustdesk/rustdesk-server:latest   "hbbs -r 127.0.0.1:2…"   2 days ago   Up 2 days   0.0.0.0:21115-21116->21115-21116/tcp, :::21115-21116->21115-21116/tcp, 0.0.0.0:21118->21118/tcp, :::21118->21118/tcp, 0.0.0.0:21116->21116/udp, :::21116->21116/udp   hbbs
fff97f89f2b0   rustdesk/rustdesk-server:latest   "hbbr -k _"              2 days ago   Up 2 days   0.0.0.0:21117->21117/tcp, :::21117->21117/tcp, 0.0.0.0:21119->21119/tcp, :::21119->21119/tcp                                                                          hbbr

all endpoints are running V1.3.1 client
Windows to Windows connects without issue
Android to windows I get connection reset by peer

I have not seen any mention of this issue throughout all of my investigations,
If i could fix myself i would, But i find no record of this issue wlsewhere

[2024-09-27 16:24:51.676339 +01:00] ERROR [src\server.rs:231] Failed to create relay connection for x.x.x.x:12998 with uuid c59a6a9f-2dc3-4686-977d-xxxxxxxxxxx: Failed to receive public key

### How to Reproduce

This happens each time i try connect via android to any of my PC devices

### Expected Behavior

To connect and allow remote control.
This worked on my previous old version setup

### Operating system(s) on local side and remote side

android 14 - windows 11

### RustDesk Version(s) on local side and remote side

1.3.1

### Screenshots

![Untitled](https://github.com/user-attachments/assets/c0eb985b-6131-4b5e-a964-74baf745bdf2)

### Additional Context

If you need anymore logs or anything i can test to overcome this issue please let me know.

**Comment by rustdesk** [comment]
#763
