### ISSUE TITLE
 white screen

### ISSUE THREAD

**Issue by cc1021743436** [rustdesk/rustdesk#9497]
### Bug Description

On Windows 11 23H2/22631.4169, the software opens white screen and is not responding

### How to Reproduce

open the sofrware

### Expected Behavior

fix the bug

### Operating system(s) on local side and remote side

Windows 11 23H2

### RustDesk Version(s) on local side and remote side

1,3.1

### Screenshots

![problem](https://github.com/user-attachments/assets/0a05945c-8d77-4cae-914a-54adfcc9924b)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/6756
