### ISSUE TITLE
ID/Relay server dialog

### ISSUE THREAD

**Issue by JReally** [rustdesk/rustdesk#953]
May I suggest that on the initial run of RustDesk, a dialog appears to allow the specification of the host.

"default" would be the default setting but it would allow the specification of a different address for self-hosted installations.

This would simplify the startup situation for users.  Currently I have to tell them to click the 3 dots etc etc to install the address to the self-hosted server.

JR

**Comment by rustdesk** [comment]
Sorry, can not, because most of users are not using self-hosting.
