### ISSUE TITLE
App image not opening on fedora workstation after install or run once 

### ISSUE THREAD

**Issue by UnixPhonez** [rustdesk/rustdesk#954]
**Describe the bug you encountered:**

app doesn't run after install nor open

**What did you expect to happen instead?**

for the app to open 

**How did you install `RustDesk`?**

[RustDesk-1.1.10-x86_64_1804.AppImage](https://github.com/rustdesk/rustdesk/releases/download/1.1.9/RustDesk-1.1.10-x86_64_1804.AppImage)

**RustDesk version and environment**
1.1.9
fedora workstation install on thinkpad t14s amd model

**Comment by rustdesk** [comment]
We are going to remove AppImage in the next version for various reasons. Sorry we can not support it.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/577
