### ISSUE TITLE
Crashes after trying to modify the ID/Realy server

### ISSUE THREAD

**Issue by ke1ewang** [rustdesk/rustdesk#9548]
### Bug Description

Rustdesk crashes when I type any characters in ID server or Relay server or API server

### How to Reproduce

Settings -> Network -> Unlock network settings -> Enter any character

https://github.com/user-attachments/assets/2fb02cc0-61a2-4e5c-8329-1d71a2675803

### Expected Behavior

Normal work

### Operating system(s) on local side and remote side

macOS Sequola 15.0

### RustDesk Version(s) on local side and remote side

1.3.1

### Screenshots

<img width="1112" alt="Screenshot 2024-10-03 at 11 02 08" src="https://github.com/user-attachments/assets/b90ac383-d824-446a-89f8-d6ef69ab628c">

**Comment by ke1ewang** [comment]
#9408 
#7765

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/7766
