### ISSUE TITLE
Weird requests to an uknown relay server undocumented in network requirements - "Failed to connect to relay server"

### ISSUE THREAD

**Issue by xes** [rustdesk/rustdesk#9553]
### Bug Description

Sometimes, latest release 1.3.1 (from github release page) tries to connect to an unknown relay server:  116.203.239.11 on port 21117
During the same session, dns queries are searching for "rs-ny.rustdesk.com" that is resolved as 209.250.254.15

If that ip 116.203.239.11 is blocked, it is impossible to obtain a connection.

### How to Reproduce

Pretty hard, it happens random, it does not depends on network, device or OS. 
So far i cannot find a pattern for this.

### Expected Behavior

It should connect respecting Rustdesk network requirements explained in documentation

### Operating system(s) on local side and remote side

Win 10 / Win 11 / Linux

### RustDesk Version(s) on local side and remote side

1.3.1

### Screenshots

On the screen you will obtain an error: "Failed to connect to relay server"

**Comment by rustdesk** [comment]
116.203.239.11 is one of the relay servers, it is too crowded, set up your own server please.
