### ISSUE TITLE
Installation from source failed on i686 32bit Debian 12 

### ISSUE THREAD

**Issue by vinloren** [rustdesk/rustdesk#9574]
### Bug Description

After succesfully installed vcdpkg
git clone https://github.com/microsoft/vcpkg
cd vcpkg
git checkout 2023.04.15
cd ..
vcpkg/bootstrap-vcpkg.sh
export VCPKG_ROOT=$HOME/vcpkg
vcpkg/vcpkg install libvpx libyuv opus aom

At the end of
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source $HOME/.cargo/env
git clone https://github.com/rustdesk/rustdesk
cd rustdesk
mkdir -p target/debug
wget https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin.lnx/x64/libsciter-gtk.so
mv libsciter-gtk.so target/debug
VCPKG_ROOT=$HOME/vcpkg cargo run

I got:
 Compiling hyper-rustls v0.24.2
error: failed to run custom build command for `scrap v0.5.0 (/home/enzo/Scaricati/rustdesk/libs/scrap)`
 Compiling hyper-rustls v0.24.2
error: failed to run custom build command for `scrap v0.5.0 (/home/enzo/Scaricati/rustdesk/libs/scrap)`

Caused by:
  process didn't exit successfully: `/home/enzo/Scaricati/rustdesk/target/debug/build/scrap-fcdf363d169e3c08/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=NO_PKG_CONFIG_libyuv
  cargo:info=x86-linux
  cargo:rustc-link-lib=static=yuv
  cargo:rustc-link-search=/home/enzo/vcpkg/installed/x86-linux/lib
  cargo:include=/home/enzo/vcpkg/installed/x86-linux/include
  cargo:rerun-if-env-changed=NO_PKG_CONFIG_libvpx
  cargo:info=x86-linux
  cargo:rustc-link-lib=static=vpx
  cargo:rustc-link-search=/home/enzo/vcpkg/installed/x86-linux/lib
  cargo:include=/home/enzo/vcpkg/installed/x86-linux/include
  rerun-if-changed=/home/enzo/Scaricati/rustdesk/libs/scrap/src/bindings/vpx_ffi.h
  rerun-if-changed=/home/enzo/vcpkg/installed/x86-linux/include
  cargo:rerun-if-env-changed=NO_PKG_CONFIG_aom
  cargo:info=x86-linux
  cargo:rustc-link-lib=static=aom
  cargo:rustc-link-search=/home/enzo/vcpkg/installed/x86-linux/lib
  cargo:include=/home/enzo/vcpkg/installed/x86-linux/include
  rerun-if-changed=/home/enzo/Scaricati/rustdesk/libs/scrap/src/bindings/aom_ffi.h
  rerun-if-changed=/home/enzo/vcpkg/installed/x86-linux/include
  cargo:rerun-if-env-changed=NO_PKG_CONFIG_libyuv
  cargo:info=x86-linux
  cargo:rustc-link-lib=static=yuv
  cargo:rustc-link-search=/home/enzo/vcpkg/installed/x86-linux/lib
  cargo:include=/home/enzo/vcpkg/installed/x86-linux/include
  rerun-if-changed=/home/enzo/Scaricati/rustdesk/libs/scrap/src/bindings/yuv_ffi.h
  rerun-if-changed=/home/enzo/vcpkg/installed/x86-linux/include

### How to Reproduce

Running the scipts above on a i686 Linux machine running Debian 12

### Expected Behavior

The expected behaviour is a clean installetion of rustdesk at the end of the procedure

### Operating system(s) on local side and remote side

Windows 10 / Debian 12 Linux

### RustDesk Version(s) on local side and remote side

none yet

### Screenshots

not applicable

**Comment by rustdesk** [comment]
#763
