### ISSUE TITLE
Mac Proxy Issues

### ISSUE THREAD

**Issue by Anber55** [rustdesk/rustdesk#9593]
### Bug Description

RustDesk is really a great product and I use it a lot, but recently I found a problem, my Mac is able to use RustDesk normally without using a proxy, but once I start using a proxy, the interface shown below is displayed in the Network Activity of the Proxy software, which results in the iPhone connecting to Mac failing all the time and prompting the following Message:

Connection error, unable to establish connection through registration server: please try again later

I hope to receive your reply as soon as possible to tell me how to solve the problem, thanks a lot!

### How to Reproduce

Connecting to Mac with iPhone when Mac has proxy turned on

### Expected Behavior

Connection error, unable to establish connection through registration server: please try again later

### Operating system(s) on local side and remote side

iOS→macOS

### RustDesk Version(s) on local side and remote side

1.3.2

### Screenshots

<img width="444" alt="截屏2024-10-08 18 19 48" src="https://github.com/user-attachments/assets/64043f30-5b0c-415e-a478-8fb972d7a6cf">

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/9592
