### ISSUE TITLE
Mac-> win10, mouse/keyboard not work

### ISSUE THREAD

**Issue by immustard** [rustdesk/rustdesk#96]
mac：11.4
app：1.1.6

**Comment by rustdesk** [comment]
install please

**Comment by immustard** [comment]
install what?

**Comment by rustdesk** [comment]
You run RustDesk on windows 10 after installation or not?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/83

**Comment by immustard** [comment]
how can i use it without installation ???

**Comment by rustdesk** [comment]
there is UAC control on Windows. So when you open some system dialog or program, the keyboard and mouse will not work if you do not install RustDesk.

**Comment by immustard** [comment]
you mean i can use RustDesk on Mac to connect Win with UAC?

**Comment by rustdesk** [comment]
> you mean i can use RustDesk on Mac to connect Win with UAC?

I mean UAC cause keyboard/mouse not working on windows10

**Comment by immustard** [comment]
i get it. but i have installed.

**Comment by immustard** [comment]
for example, the icon becomes highlighted when mouse hover it, but it happens nothing when i click it

**Comment by rustdesk** [comment]
It is bug then, what's you Mac version and Window 10 update version?

**Comment by rustdesk** [comment]
Or can you try if reboot and upgrade your window10 can work

**Comment by tinyhare** [comment]
> install please

I installed it on the remote Win10, the problem has been solved, thank you.

**Comment by EmPablo** [comment]
Tested with Mac-> win10 with the following versions:
 MacOS: 11.4  RustDesk: 1.1.6
Status: Working good
The reason caused the issues is that most users do not install the App on Windows instead of open RustDesk App directly after download. That's why!
 If it still happen, Any screenshots? or pls close the issue after it works.

> for example, the icon becomes highlighted when mouse hover it, but it happens nothing when i click it

**Comment by caoyiwen** [comment]
win-> win, also

**Comment by vinz243** [comment]
Hello I'm unable to type my password on the W10 login screen (mac -> windows too). I have it installed on windows. I even tried to give the .exe admin rights.

**Comment by rustdesk** [comment]
> Hello I'm unable to type my password on the W10 login screen (mac -> windows too). I have it installed on windows. I even tried to give the .exe admin rights.

Are you sure RustDesk service is running on W10 side? Can you also try connect to W10 without Mac?

**Comment by rustdesk** [comment]
> I meant that I can see the screen, the login prompt is visible, but when I type nothing happens.

Understood you.

**Comment by vinz243** [comment]
Okay, my bad, I can't actually type at all whether or not I'm logged in with RustDesk

**Comment by rustdesk** [comment]
The same keyboard layout, the same language?

**Comment by vinz243** [comment]
I can't say whether they are exactly the same but both are azerty. Windows is in French, mac in English tho

**Comment by rustdesk** [comment]
Can you try switch to the same language?

**Comment by vinz243** [comment]
I tried, it's not working :/

**Comment by flattery103** [comment]
I am having the same issue connecting my Mac to Linux (Fedora 36 with X11)

**Comment by immustard** [comment]
您好，您的邮件已经收到。

**Comment by GhostDogAlpha** [comment]
I was having this same issue connecting from Mac (MacOS 12.5) to either a Windows or Linux box. I was able to fix it, though, by providing Input Monitoring permissions to the RustDesk client. (Settings -> Security & Privacy -> Input Monitoring)

**Comment by immustard** [comment]
您好，您的邮件已经收到。

**Comment by rustdesk** [comment]
> Settings

Yes，this is the workaround, though not elegant, https://github.com/rustdesk/rustdesk/issues/974#issuecomment-1186577391.  No quick fix can be found yet, but this issue will vanish in our new Flutter UI version, which will be our next release.

**Comment by rustdesk** [comment]
possible dup: #974

**Comment by GhostDogAlpha** [comment]
When I was done with the RustDesk and closing everything out, I found the window that told me that RustDesk needed the input monitoring permissions hidden behind all of the other windows, which was odd because most of the time those sorts of windows are brought immediately to the front. Not sure if there is a way to force that window to the front, but if so, I think that solves about 90% of the problem. Anyway, thank you guys for this and all the work you've put into it. I was very impressed with it, and its something that was desperately needed.

**Comment by immustard** [comment]
您好，您的邮件已经收到。

**Comment by zeroalphagit** [comment]
> I was having this same issue connecting from Mac (MacOS 12.5) to either a Windows or Linux box. I was able to fix it, though, by providing Input Monitoring permissions to the RustDesk client. (Settings -> Security & Privacy -> Input Monitoring)

This solved it for me

**Comment by immustard** [comment]
您好，您的邮件已经收到。
