### ISSUE TITLE
Windowing issues on windows 

### ISSUE THREAD

**Issue by UnixPhonez** [rustdesk/rustdesk#960]
**Describe the bug you encountered:**

the windowing is messed up and cuts out bottom toolbar plus more on windows 10 connections 

**What did you expect to happen instead?**

for the windowing to be correctly implemented

**How did you install `RustDesk`?**

windows was .exe from website

**RustDesk version and environment**

the computer controlling the windows 10 computer was fedora linux 

** Screenshot of issue**

https://ibb.co/jTTJwPZ

**Comment by rustdesk** [comment]
what is messed up?

**Comment by UnixPhonez** [comment]
It’s zoomed in and not full screen

**Comment by rustdesk** [comment]
There are scrollbars, and there are view mode you can choose in the menu.

**Comment by UnixPhonez** [comment]
> There are scrollbars, and there are view mode you can choose in the menu.

Ahh I will look but was confused at first I’ll keep you updated

**Comment by rustdesk** [comment]
Only few guys get confused.

**Comment by UnixPhonez** [comment]
yea the scroll isn't displayed which confuses people, is there any way to zoom out ?
