### ISSUE TITLE
DPI problems when running x64 RustDesk on Windows 7

### ISSUE THREAD

**Issue by jernejs** [rustdesk/rustdesk#9605]
### Bug Description

When running x64 version of RustDesk on Windows 7, it seems to not run in high-DPI-compatible mode, which results in only part of the screen being visible when the controlled computer is using anything other than 100% DPI. Mouse pointer is also offset on the actual computer compared to what RustDesk is showing.

x86 version of RustDesk doesn't have this problem.

### How to Reproduce

Set Windows 7 computer to 150% DPI, run RustDesk, take control from remote computer

### Expected Behavior

Whole screen visible

### Operating system(s) on local side and remote side

Windows 11 → Windows 7

### RustDesk Version(s) on local side and remote side

1.3.2 → 1.3.2

### Screenshots

![{C4F9AA3B-198C-41CB-8EDF-E079832DF556}](https://github.com/user-attachments/assets/7994a9e3-9ced-4089-8d9a-53d43f4963a6)
![image](https://github.com/user-attachments/assets/f5dd594e-9784-4064-abfe-6f18c7c9649a)

**Comment by rustdesk** [comment]
#763
