### ISSUE TITLE
Privacy mode on two screens

### ISSUE THREAD

**Issue by mick1357** [rustdesk/rustdesk#9613]
### Bug Description

I'm using two screens - a laptop (Display 1) plus an auxiliary monitor (Display 2) connected by VGA. 'Extend these displays' is set in Windows and Display 2 is my main display. When I access my laptop remotely, both displays appear in the RustDesk toolbar and I can switch between them or view them both at once. When I select Privacy Mode 1, only Display 2 is blanked and Display 1 remains unblanked. However, Display 1 disappears from the toolbar, which now does not show multiple displays, and therefore it cannot be accessed. Privacy Mode 2 does not blank either display.

### How to Reproduce

Similar hardware configuration.

### Expected Behavior

Privacy Mode blanks both displays but they remain accessible via the toolbar.

### Operating system(s) on local side and remote side

Windows 10 Pro -> Windows 10 Pro

### RustDesk Version(s) on local side and remote side

1.3.1 -> 1.3.1

### Screenshots

N/A

**Comment by rustdesk** [comment]
do not create duplciate thigns please.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/9110
