### ISSUE TITLE
key: CAPS  LOCK takes no effect (Linux mint -> macOS)

### ISSUE THREAD

**Issue by Leo-Lionni** [rustdesk/rustdesk#9617]
### Bug Description

- environments
  # remote 
  ```bash
  rustdesk --version  
  1.3.1

   chy@MacBook-Pro.local
                   ,xNMM.          ---------------------
                 .OMMMMo           OS: macOS Catalina 10.15.7 19H2 x86_64
                 OMMM0,            Host: MacBookPro15,4
       .;loddo:' loolloddol;.      Kernel: 19.6.0
     cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 32 days, 2 hours, 41 mins
   .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 293 (brew)
   XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.7.1
  ;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1440x900@2x
  :MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
  .MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
   kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark)
   .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: iTerm2
    .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: RobotoMonoForPowerline-Bold 12
      kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Intel i5-8257U (8) @ 1.40GHz
       ;KMMMMMMMWXXWMMMMMMMk.      GPU: Intel Iris Plus Graphics 645
         .cooc,.    .,coo:.        Memory: 5727MiB / 8192MiB
  
  ```
  # mylocal
  ```bash
  rustdesk --version  
  1.3.1

  leo@lionniCHY:~$ uname -a
  Linux lionniCHY 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
  leo@lionniCHY:~$ lsb_release -a
  No LSB modules are available.
  Distributor ID:	Linuxmint
  Description:	Linux Mint 21.1 and derived from  Ubuntu 22.04
  Release:	21.1
  Codename:	vera
  ```
#  Conclusion
when connecting  with rustdesk from local(linux mint) to remote(mac) ,  i wanna to input any Uppercase alphabet.i do  press CAPS LOCK once (make sure the Caps Lock light is on ), and then press `a`, the result should be  `A` , but `a`. The other alphabet are same too.

## consequence
the result of press `a` 
|    name / result| Keep pressing , light on |   press  and then release immediately , light on |
|  ----  | ----  |----  |
|CAPS LOCK|A|a|
|L-Shift|A|/|
|R-Shift|A|/|

### How to Reproduce

such described as Bug above and input any alphabet compared with CAPS LOCK enabled or  disabled.

### Expected Behavior

when CAPS LOCK is enabled and  light on , input `a` should be `A`.

### Operating system(s) on local side and remote side

linux mint 21.1 -> macos 10.15

### RustDesk Version(s) on local side and remote side

1.3.1 -> 1.3.1

### Screenshots

sorry , there would be  easily  obvious, thus i forget to take a screenshot.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/8760

**Comment by fufesou** [comment]
@Leo-Lionni Hi, which input did you use?

https://github.com/rustdesk/rustdesk/wiki/FAQ#keyboard-translation-modes

![image](https://github.com/user-attachments/assets/19626ba8-f42d-491f-95de-a3fa40861102)

"Legacy mode" did has this issue.

**Comment by Leo-Lionni** [comment]
> @Leo-Lionni Hi, which input did you use?
> 
> https://github.com/rustdesk/rustdesk/wiki/FAQ#keyboard-translation-modes
> 
> ![image](https://private-user-images.githubusercontent.com/13586388/376429362-19626ba8-f42d-491f-95de-a3fa40861102.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NjQ1MDUsIm5iZiI6MTcyODk2NDIwNSwicGF0aCI6Ii8xMzU4NjM4OC8zNzY0MjkzNjItMTk2MjZiYTgtZjQyZC00OTFmLTk1ZGUtYTNmYTQwODYxMTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDAzNTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZmU4ZjE2MjdhN2YxOTQ3YjY4MDNlYzhmMWI2MDgxMGE1YzE2MmE1NDkwZjEwMTNlMWYxOGZjMGZhOTdlOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ccsgOgmOaxMZABLLQ-6iUMZnwfeEmQdz_w1JLlPKlkA)
> 
> "Legacy mode" did has this issue.

Yeah,  i'm in legacy mode by default. Sorry, i have no enough experience  leading to not switch to `map mode`.
