### ISSUE TITLE
I Can't connetct to a remote id other server

### ISSUE THREAD

**Issue by mikekgr** [rustdesk/rustdesk#9623]
### Bug Description

Using the latest stable version 1.3.1 running at Windows 10 (tested also with Windows 11), I can't connect to a remote pc (Running 1.3.1 Windows 10) that is in different server than mine (both are running the open-source version of private server 1.1.11-1). I have tried the below scheme :
remote_id@ipaddress:port?key=this_is_the_remote_server_key
I have tried all ports that I have thing of: 21115, 21116, 21117, 21118, 21119
always unsuccessfully.
Am I doing something wrong? Please help me.

Thanks 

### How to Reproduce

See the description

### Expected Behavior

To be able to connect from one network (server) to an remote id that is belong to another private server

### Operating system(s) on local side and remote side

Windows 10 / 11 to Windows 10 / 11

### RustDesk Version(s) on local side and remote side

1.3.1 -> 1.3.1

### Screenshots

NP

**Comment by rustdesk** [comment]
#763
