### ISSUE TITLE
See https://github.com/rustdesk/rustdesk/issues/9623 it is not custom build

### ISSUE THREAD

**Issue by mikekgr** [rustdesk/rustdesk#9624]
### Bug Description

Please re read the https://github.com/rustdesk/rustdesk/issues/9623 error it is not my build, I am using official releases

### How to Reproduce

NP

### Expected Behavior

See above

### Operating system(s) on local side and remote side

https://github.com/rustdesk/rustdesk/issues/9623

### RustDesk Version(s) on local side and remote side

https://github.com/rustdesk/rustdesk/issues/9623

### Screenshots

NP

**Comment by rustdesk** [comment]
we do not help on connection problem.

**Comment by rustdesk** [comment]
Go to discord, https://discord.com/invite/nDceKgxnkV
