### ISSUE TITLE
std::logic_error in appimage debian 12 KDE

### ISSUE THREAD

**Issue by CharaVerKys** [rustdesk/rustdesk#9633]
### Bug Description

Unhandled exception when connecting with default settings

### How to Reproduce

linux debian 12 kde 5.103.0 waylandx
kernel 6.1.0-25-amd64 (64-bit)
(almost clear system)

1. download latest available rustdesk version  appimage 
2. start rustdesk
3. connect via id and password
4. visible screen for 100-200 ms 
5. crash

### Expected Behavior

stable work of application.

### Operating system(s) on local side and remote side

linux debian -> windows 10 and linux ubuntu 22.04

### RustDesk Version(s) on local side and remote side

1.3.1 -> 1.3.1

### Screenshots

![Screenshot_20241012_171217](https://github.com/user-attachments/assets/daf9543e-7271-472c-8769-8440293cc5b2)
![Screenshot_20241012_171301](https://github.com/user-attachments/assets/c728f2f1-525f-49b3-8c2b-d67498a6c265)
![Screenshot_20241012_171307](https://github.com/user-attachments/assets/0c5550b9-bd00-447e-a5df-2e61d11b32b7)
![Screenshot_20241012_171343](https://github.com/user-attachments/assets/5c4d7536-4e89-474a-a453-5e97fc70dc57)
![Screenshot_20241012_171350](https://github.com/user-attachments/assets/d5eec30b-aac7-47d3-9f6b-1673a85d5b28)
![Screenshot_20241012_171445](https://github.com/user-attachments/assets/fb503677-e7a9-4821-aab9-eac59543a89c)

### Additional Context

[win.log](https://github.com/user-attachments/files/17350356/win.log)
[ubuntu.log](https://github.com/user-attachments/files/17350358/ubuntu.log)

**Comment by CharaVerKys** [comment]
same result with pre-release version

no issue with 1.3.1 deb packet BUT IT require dependencies 

dpkg: dependency problems prevent configuration of rustdesk:
 rustdesk depends on libxdo3; however:
  Package libxdo3 is not installed.
 rustdesk depends on curl; however:
  Package curl is not installed. 
 rustdesk depends on gstreamer1.0-pipewire; however:
  Package gstreamer1.0-pipewire is not installed.

but i wanna install appimage and not care about any dependency

even if dependency installed i encounter std::terminate call

**Comment by rustdesk** [comment]
Please use Flatpak instead. AppImage is not good choice.
