### ISSUE TITLE
RustDesk audio delay 100 times more than Google Meet, it is 2500 ms

### ISSUE THREAD

**Issue by iexcept** [rustdesk/rustdesk#9654]
### Bug Description

Environment: 
1. Local ethernet with 1 Gbps LAN switch
2. RustDesk server 
3. 2 PCs with RustDesk clients (Windows 10 and Ubuntu 22)

I manually measured the delay, and it is about **2500 ms** in LAN (which is about 100 times more than e.g. Google Meet conference over the internet with other cities, not LAN).

### How to Reproduce

1. Setup your own RustDesk server
2. Setup the first client-1 PC with the latest Windows 10 x64.
3. Set up a second client-2 PC with Ubuntu 22.04
4. Connect everything with LAN (turn off WiFis to minimize delays)
5. Open RustDesk on the client-1 and connect to the client-2
6. Open some audio output app on the client-2 (Ubuntu 22)
7. Run the stopwatch and, right at the same time play some song on the client-2. Press stop on the stopwatch when you start to hear the sound locally.
8. Observe the delay from 2300 to 2800 ms.

### Expected Behavior

The audio delay is < 30 ms

### Operating system(s) on local side and remote side

Windows 10 -> Ubuntu 22.04

### RustDesk Version(s) on local side and remote side

1.2.3-2 -> 1.2.3

### Screenshots

I don't know how to create a screenshot for this bug. Please give me a hint...

**Comment by rustdesk** [comment]
latest build please
