### ISSUE TITLE
Snap Layouts (Windows 11) not works in rustdesk

### ISSUE THREAD

**Issue by augustresende** [rustdesk/rustdesk#9656]
### Bug Description

When i hover the maximize button it says "Maximize"
![image](https://github.com/user-attachments/assets/007a03a3-2b71-4e8e-8e92-1cdc33c14272)

But instead in Windows 11 should appear snap layouts

![image](https://github.com/user-attachments/assets/277e5a04-7c7f-4cc7-a996-e4475ffef564)

Microsoft official fix: https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/ui/apply-snap-layout-menu

### How to Reproduce

Open the app

Hover the maximize button

See

### Expected Behavior

Should appear Windows 11 snap layouts

### Operating system(s) on local side and remote side

Windows 11 -> Windows 11

### RustDesk Version(s) on local side and remote side

latest

### Screenshots

![image](https://github.com/user-attachments/assets/007a03a3-2b71-4e8e-8e92-1cdc33c14272)

### Additional Context

Related: https://github.com/flutter/flutter/issues/156791

Probably needs native code.

**Comment by rustdesk** [comment]
This is beyond what we can do, we can wait for flutter only.

**Comment by augustresende** [comment]
@rustdesk https://github.com/PleaseDont/snap_layouts
