### ISSUE TITLE
Remote Linux, the keyboard direction keys are not sensitive, the up key will trigger a screenshot, other unknown

### ISSUE THREAD

**Issue by xw-l** [rustdesk/rustdesk#9659]
### Bug Description

client ubuntu24.04,other client ubuntu22.04

### How to Reproduce

just test keyboard arrow keys

### Expected Behavior

Keyboard arrow keys not working

### Operating system(s) on local side and remote side

ubuntu24.04-->ubuntu22.04

### RustDesk Version(s) on local side and remote side

1.3.2

### Screenshots

![image](https://github.com/user-attachments/assets/5980a605-e32d-408e-8bf6-6a5f2eef8063)

**Comment by rustdesk** [comment]
Could you help test 1.3.1 and 1.3.0?

**Comment by xw-l** [comment]
sure,tomorrow,by the way,ubuntu24.04=physical machine,ubuntu22.04=virtual machine(ARM)

**Comment by xw-l** [comment]
It seems to be working normally now. After removing the WaylandEnable=false comment, everything is normal now.
