### ISSUE TITLE
Bug Report: Scroll Wheel in host list scrolls wrong direction (once)

### ISSUE THREAD

**Issue by ChroMagnus** [rustdesk/rustdesk#9664]
### Bug Description

When viewing a host list that requires scrolling, when you scroll a few clicks with the mouse wheel then change directions, the first scroll click in the opposite direction continues scrolling the original direction.

### How to Reproduce

Steps to Reproduce:

1. In the address book or host list, using the mouse scroll wheel (slowly enough to watch the scroll bar, fast enough that the scroll bar does not hide)
2. Scroll multiple individual scroll wheel 'clicks' in the same direction
3. Scroll a single scroll wheel 'click' in the opposite direction

Exhibited Behavior:

- First scroll 'click' in the opposite direction maintains the direction of previous 'click's (scrolling down, first scroll up moves the user down the list, subsequent scroll up moves the user up the list)

### Expected Behavior

Expected Behavior:

- First scroll 'click' in the opposite direction reverses the direction (scrolling down, first scroll up moves the user up in the list)

### Operating system(s) on local side and remote side

Windows 11 (no remote, local issue)

### RustDesk Version(s) on local side and remote side

1.3.0 (no remote, local issue)

### Screenshots

https://github.com/user-attachments/assets/f3a9287e-196f-4b5d-918f-d4bb3399b6a2

The last scroll 'click' in the attached video was intended to go back up the list but continues down the list

**Comment by rustdesk** [comment]
No duplicate please

**Comment by ChroMagnus** [comment]
Sorry, I closed the discussion after I realized I should have filed as an issue

**Comment by rustdesk** [comment]
If possible, please check if a flutter demo can reproduce this.

**Comment by rustdesk** [comment]
https://github.com/flutter/flutter/issues/72213
