### ISSUE TITLE
LinuxMint  couldn't work with my self-host  server

### ISSUE THREAD

**Issue by Leo-Lionni** [rustdesk/rustdesk#9669]
### Bug Description

My usage situation is  below.

i built my own rustdesk-server using AliYun at china. Then, it's useful for Windows11 and Android, exception with   Linux mint 21.1 .

All my rustdesk version are 1.3.1 and downloaded from github.com.I was convinced that `the same ip:port and key were used on different platform clients

- Windows 11  

![image-20241016105045516](https://img2023.cnblogs.com/blog/1897795/202410/1897795-20241016111904651-37348759.png)

- Linux mint21.1

  - situation1, AppImage

    ```bash
    linux mint 21.1 vera  
    Linux  5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
    rustdesk 1.3.1  # AppImage
    
    ```

    rustdesk was stuck at `正在接入RustDesk网络`, but my custtom server had been added in the network of client options.

![image-20241016104747638](https://img2023.cnblogs.com/blog/1897795/202410/1897795-20241016111904137-950420936.png)

![image-20241016105116275](https://img2023.cnblogs.com/blog/1897795/202410/1897795-20241016111903569-1817564585.png)

- situation1, AppImage

​	when i've finished  the installation of  rustdesk-deb file,  it's **disable** for me to input the `ip:port` and  `key` of  ID/RELAY server. please  see the video that had been uploaded from github issue. 

video:
https://github.com/user-attachments/assets/9466488d-9f17-45ee-8311-3e8311bd36e5

```bash
leo@lionniCHY:~/soft$ which rustdesk
/usr/bin/rustdesk # deb 
```

- Android 12   (MIUI 13 )

  i'm in china. the  delay of my custom server  is pretty lower than the official rustdesk server. so Android enjoys convenience.

![image-20241016104942824](https://img2023.cnblogs.com/blog/1897795/202410/1897795-20241016111903183-1938483797.png)

![image-20241016104959895](https://img2023.cnblogs.com/blog/1897795/202410/1897795-20241016111902648-1281748169.png)

### How to Reproduce

platform:  Linux Mint 21.1
- rustdesk.AppImage 
- apt install  -f ./rustdes.1.3.1.deb

### Expected Behavior

may be that rustdesk works well at linuxmint 21.1

### Operating system(s) on local side and remote side

Windows11->Linux Mint21.1 or MIUI13 -> LinuxMint 21.1

### RustDesk Version(s) on local side and remote side

1.3.1 both 

### Screenshots

https://github.com/user-attachments/assets/9466488d-9f17-45ee-8311-3e8311bd36e5  same as the above.

**Comment by rustdesk** [comment]
#763
