### ISSUE TITLE
Keepass auto-type not transferring input immediately causing partial auto-type failure

### ISSUE THREAD

**Issue by alexander-krug** [rustdesk/rustdesk#9682]
### Bug Description

#7079 was marked as closed and added to the issue #4367. But autotype is still not working fully. I know the following will sound like an Auto-Type misconfig, making it a user-error, but it is reproducable and only happens with RustDesk not TeamViewer. 

When using autotype's default "auto-type sequence" _{USERNAME}{TAB}{PASSWORD}{ENTER}_ it only inputs the password and presses enter.
When modified by adding a TAB in the beginning, it works as expected, inputting username and password and hitting enter at the end: 
_**{TAB}**{USERNAME}{TAB}{PASSWORD}{ENTER}_

(The initial TAB from the workaround I described is not visible input in RustDesk (tested with an empty wordpad file on the remote side into which auto-type types into))

### How to Reproduce

on the local side: Install KeePass 2.55, create a username and password and use Autotyping Feature with the default setting {USERNAME}{TAB}{PASSWORD}{ENTER} into the RustDesk Window.

on the remote side: open Wordpad so you can see text being input by auto-type

### Expected Behavior

Username and password should be passed to RustDesk, without needing to add a tab in the beginning.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.3.1 -> 1.3.1 

### Screenshots

![image](https://github.com/user-attachments/assets/96e88158-e9ad-448f-9cad-39aecec95aa8)

**Comment by alexander-krug** [comment]
@rustdesk can you explain which this is a duplicate of and link to where this is being worked on?

**Comment by rustdesk** [comment]
> #7079 was marked as closed and added to the issue #4367.

It is marked `unresoved` in #4367
