### ISSUE TITLE
[Bug/Linux/KDE] No longer able to quit Rustdesk via tray with fingerprint

### ISSUE THREAD

**Issue by helpimnotdrowning** [rustdesk/rustdesk#9705]
### Bug Description

Before, in Rustdesk ~1.2.x, when I clicked the "Exit" button in the Rustdesk tray icon's right-click menu, it would bring up a graphical sudo authentication prompt, like this:
![image](https://github.com/user-attachments/assets/eee0e442-b95a-439a-a811-8914f30bc02a)

I upgraded to the latest version a week or two ago. When I tried to exit Rustdesk earlier, it instead showed a different prompt:
![image](https://github.com/user-attachments/assets/87df6c83-cbb5-4b79-a731-9780a9e6a58e)

Notably, this prompt does not let me authenticate with my fingerprint, and instead requires my password. Having to type my password is far less convenient for me (both on me needing to type the password, and me hardly knowing my password since I can always use my fingerprint) than just touching my fp sensor. 

### How to Reproduce

1. Setup fingerprint unlock (via PAM, I think) on KDE
2. With the way I have configured it, using `sudo` in a terminal should first ask for fingerprint authentication, before falling back to password auth
- `/etc/pam.d/common-auth`
```
auth    [success=2 default=ignore]  pam_fprintd.so max-tries=1 timeout=10 # debug
auth    [success=1 default=ignore]  pam_unix.so nullok try_first_pass
auth    requisite           pam_deny.so
auth    required            pam_permit.so
```
- `/etc/pam.d/sddm`
```
auth    [success=1 new_authtok_reqd=1 default=ignore]   pam_unix.so try_first_pass likeauth nullok
# auth    sufficient  pam_unix.so try_first_pass likeauth nullok
auth    sufficient  pam_fprintd.so

# < rest of file ... >
```
- `/etc/pam.d/kde`
```
auth 			sufficient  	pam_unix.so try_first_pass likeauth nullok
auth 			sufficient  	pam_fprintd.so
```

3. Run Rustdesk in a KDE (5, probably also 6) environment
4. Right-click the tray icon, then click "Exit"
5. Observe the new authentication prompt, which does not offer fp auth

### Expected Behavior

Rustdesk should accept fingerprint auth to exit, like before.

### Operating system(s) on local side and remote side

Linux -> *

### RustDesk Version(s) on local side and remote side

1.3.1 -> *

### Screenshots

Original prompt:
![image](https://github.com/user-attachments/assets/6720beca-e227-4dbd-bde0-7a8d266a1cc2)

New prompt: 
![image](https://github.com/user-attachments/assets/804e226a-c62d-447a-b5b8-8e880ef77ac1)

### Additional Context

using:
- Debian 12.7
- KDE Plasma 5.27.5-2
- Rustdesk 1.2.7, 1.3.1

**Comment by 21pages** [comment]
Could you try the latest https://github.com/rustdesk/rustdesk/releases/tag/nightly? We put a fix if your  environment is not English.

**Comment by helpimnotdrowning** [comment]
Addendum: the new prompt actually *does* accept fingerprint authentication, **but** it's very wonky. When the prompt comes up, I leave the password box empty, then press "Authenticate". When the prompt disappears, I assume it also passes through the same PAM auth chain that the old prompt did (just invisibly, with no indication of it asking).  Here, I can quickly tap my finger on my sensor, and it will authenticate.

The issue now, I guess, is that the new prompt shows no indication of waiting for my fingerprint like the old one did. It invisibly waits in the background, with no window.

**Comment by 21pages** [comment]
Pkexec does not work on some devices, https://github.com/rustdesk/rustdesk/issues/9286, so we replace it, https://github.com/rustdesk/rustdesk/pull/9383, and current implement doens't support fingerprint.

**Comment by rustdesk** [comment]
Looks like we need to restore pkexec as an option. Also use pin instead if pin is enabled.
