### ISSUE TITLE
Better build instructions?

### ISSUE THREAD

**Issue by agoodfellow123** [rustdesk/rustdesk#971]
Hello there, I have an fedora virtual machine that I need to install Rustdesk. I did everything that was told on the build list. In the end the program worked after compilation, however the program neither shows up in the terminal nor gui programs list, so simply put the build list does build the program but not install it, thus for running the program I need to compile it again each time.

As a solution I tried to use the appimage version but that gave a gcc related error (its on my virtual machine so I can't really show it).

I'm completely fine compiling the program myself but can the build instructions be expanded to include installation too?

**Comment by rustdesk** [comment]
#763
