### ISSUE TITLE
Transfer Files asking for Password which is already saved

### ISSUE THREAD

**Issue by TOMIPortugal** [rustdesk/rustdesk#9723]
### Bug Description

When using the Address Book with Passwords pre-filled, if we connect to a Device and then use the **Transfer files** option within the **Control actions** menu, it unexpectedly asks for a Password.

If we instead click the **Transfer file** option from the 3-dots menu directly in the Address Book, it does not ask for a password, as expected.

### How to Reproduce

1. Add a device to an address book and set its password through the Web Dashboard;
2. Through the client, connect to the Device via the Address Book;
3. Via the `Control actions` menu, click `Transfer files`
4. See that it asks for a Password

### Expected Behavior

When clicking `Transfer files` via the `Control actions` while connected to a Device, it should not ask for a Password if we connected via the Address Book which already has the device password saved.

### Operating system(s) on local side and remote side

Windows 11 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.3.1 -> 1.3.1

### Screenshots

![rustdesk_TxQrcG9zcP](https://github.com/user-attachments/assets/548e7a83-0874-4ead-bf40-ab024f2ba365)

**Comment by rustdesk** [comment]
@21pages

**Comment by rustdesk** [comment]
Close as fix merged
