### ISSUE TITLE
My public IP is blocked by you and I can't access Rustdesk

### ISSUE THREAD

**Issue by Timsamex** [rustdesk/rustdesk#9724]
### Bug Description

For a few days now I have not been able to provide support to my users through the Rustdesk application.

When I am on my internal office network, the application tells me that the connection to the Rustdesk network is in progress and after a few seconds it gives the error It is not ready, check your connection.

Tests have already been carried out via my mobile connection and it automatically connects to the Rustdesk service.

Tests have also been carried out with our internet provider, with another IP address and the connection is made immediately. It was checked that the TCP ports 21114-21119 UDP 21116 were not blocked.

My public IP is the following 177.244.41.105, could you help me check if it is blacklisted?

### How to Reproduce

The error is generated when opening the application

### Expected Behavior

That can connect to the Rustdesk service

### Operating system(s) on local side and remote side

Windows 10 and 11

### RustDesk Version(s) on local side and remote side

1.3.1

### Screenshots

![Captura de pantalla 2024-10-22 132726](https://github.com/user-attachments/assets/80aed4c9-8984-4eae-9405-f760d2c69145)
![Captura de pantalla 2024-10-22 132800](https://github.com/user-attachments/assets/8834af20-6931-41fe-a82b-6fc43b825f6f)

**Comment by rustdesk** [comment]
https://www.reddit.com/r/rustdesk/comments/1cr8kfv/should_you_selfhost_a_rustdesk_server/
