### ISSUE TITLE
Building a Mac client with GitHub Actions doesn't work

### ISSUE THREAD

**Issue by Smianao** [rustdesk/rustdesk#9725]
### Bug Description

As per the question, ran the mac side of the build with no response

### How to Reproduce

As per the question, ran the mac side of the build with no response

### Expected Behavior

As per the question, ran the mac side of the build with no response

### Operating system(s) on local side and remote side

Macos

### RustDesk Version(s) on local side and remote side

1.3.2

### Screenshots

As per the question, ran the mac side of the build with no response

**Comment by rustdesk** [comment]
#763
