### ISSUE TITLE
ios client force relay server

### ISSUE THREAD

**Issue by 315923876** [rustdesk/rustdesk#9727]
### Bug Description

cannot connect id server when relay server is empty. in rustdesk desktop, i only need to enter my self-host id server adress, but ios client said failed to connect to relay server when i do same thing. i tried to use "localhost" and the address of id server to relay server, but it still shows that cannot connect relay server. by the way, the hbbr and hbbs all started and port 21117 is reachable. so i only can connect my computer directly using ip.
![image](https://github.com/user-attachments/assets/1892fc44-2f8d-4ab7-ba02-efe973834fd6)
![image](https://github.com/user-attachments/assets/da2fb09f-fe4b-45c5-a9a1-afc5551cdbc3)
![image](https://github.com/user-attachments/assets/a99e8715-a389-4857-848e-dcf0a7d4afeb)

### How to Reproduce

connect id server when relay server is empty

### Expected Behavior

can connect id server with empty relay server

### Operating system(s) on local side and remote side

ipados17.6.1

### RustDesk Version(s) on local side and remote side

rustdesk1.3.1,rustdesk-server 1.1.12

### Screenshots

above

**Comment by rustdesk** [comment]
#763
