### ISSUE TITLE
CMD+C , CMD+Z, CMD + Shift + Z and more keyboard shortcuts print letters instead of performing the assigned actions 

### ISSUE THREAD

**Issue by sakisdog** [rustdesk/rustdesk#9729]
### Bug Description

Every now and then when i try to copy, paste, find or something else via a keyboard shortcut it prints the letters i press instead of doing the action assigned to shortcut. 
For example: if i copy using CMD+C it prints "c" on the screen instead of copying.
This happens only **from Windows machines** **to Mac OS machines** using **Translate** or **Map mode**.
This does not happen with Legacy mode. 
Tried many different versions of Rustdesk without a success.

### How to Reproduce

Try to copy or paste multiple times with different timing during the key press combination.

### Expected Behavior

Do the assigned shortcut action

### Operating system(s) on local side and remote side

Windows 10 or 11 -> Mac OS

### RustDesk Version(s) on local side and remote side

1.3.1 -> 1.31

### Screenshots

No screenshots

**Comment by fufesou** [comment]
@sakisdog Hi, could you please give a screenshot of the keyboard settings?

![image](https://github.com/user-attachments/assets/f4431ea2-31d2-4a31-8177-66975a784ea8)

Windows -> MacOS, "Map mode", No "Swap control-command key", `CMD`+`C` , `CMD`+`Z`, `CMD` + `Shift` + `Z` work fine for me.

**Comment by sakisdog** [comment]
I think i found the bug! Try to move your mouse while pasting.

**Comment by fufesou** [comment]
https://github.com/user-attachments/assets/4955ecf7-63e7-47c6-bfc8-ba1ab5bc3955

**Comment by sakisdog** [comment]
@fufesou That's right! You reproduced the problem i guess

**Comment by rustdesk** [comment]
Please test the nightly build, update on controlled side.

**Comment by sakisdog** [comment]
I can confirm that using the new nightly build the issue is gone. It now works even on Translate and Map mode.
Thank you for the fix.
