### ISSUE TITLE
IOS Canvas Bug

### ISSUE THREAD

**Issue by i1Fury** [rustdesk/rustdesk#9732]
### Bug Description

When in keyboard mode and zoomed in on ios, the canvas does not follow the cursor up/down, making it impossible to see the screen effectively and perform many tasks.

### How to Reproduce

1. Connect to a remote host using the ios app.
2. Use mouse mode.
3. Enter keyboard mode.
4. Zoom in and move the mouse to the top of the screen then the bottom.

### Expected Behavior

Canvas follows mouse

### Operating system(s) on local side and remote side

ios -> Windows 10

### RustDesk Version(s) on local side and remote side

1.3.1 -> 1.3.1

### Screenshots

https://github.com/user-attachments/assets/e92b4c51-dd8c-4261-a568-26c340bc9622

**Comment by rustdesk** [comment]
Sorry, this is internatonal design, there will be more problem if allowing moving.

**Comment by i1Fury** [comment]
Why would you just close an issue without discussion? Chrome Remote Desktop
has it working completely fine with allowing moving. It is significantly
more difficult to operate this way, and when implemented properly will not
create more problems.

**Comment by i1Fury** [comment]
Here’s how it irrefutably should operate.
https://github.com/user-attachments/assets/f02d6382-9f14-443a-95e0-42546dda621d
