### ISSUE TITLE
View is reset when bringing up the keyboard on my Galaxy Fold when unfolded

### ISSUE THREAD

**Issue by azsde** [rustdesk/rustdesk#9748]
### Bug Description

Hi everyone,

In the current version of the Android App, bringing up the keyboard while unfolded cause the view to be reset.

This issue only happens when device is unfolded.

### How to Reproduce

- connect to a remote machine while device is unfolded
- zoom in or change the view of the screen
- being up the keyboard

### Expected Behavior

The view should remain where it was set before bringing up the keyboard

### Operating system(s) on local side and remote side

Android -> Windows 11

### RustDesk Version(s) on local side and remote side

1.3.1 -> 1.2.2

### Screenshots

https://github.com/user-attachments/assets/e2a917b8-8e37-4cd0-a1ea-eb943cdbdbfb

**Comment by rustdesk** [comment]
We have no unfold phone to test it, tracked by https://github.com/rustdesk/rustdesk/issues/3893
