### ISSUE TITLE
WINDOWS COPY BUG

### ISSUE THREAD

**Issue by llfj** [rustdesk/rustdesk#9754]
### Bug Description

When I use the rustdesk remote desktop of a WINDOWS system to connect to the rustdesk of another WINDOWS system, if I copy a relatively large file of about 10 MB on either end, the software will crash and I will not be able to connect normally afterwards until I clear the clipboard.

### How to Reproduce

-

### Expected Behavior

-

### Operating system(s) on local side and remote side

WINDOWS10

### RustDesk Version(s) on local side and remote side

1.3.1

### Screenshots

-

### Additional Context

-

**Comment by rustdesk** [comment]
> I copy a relatively large file of about 10 MB on either end

Copy the file or copy the content of the file?

**Comment by rustdesk** [comment]
> I clear the clipboard.

How do you clear?

**Comment by rustdesk** [comment]
> the software will crash

Which side crashed?

**Comment by fufesou** [comment]
@llfj Hi, thanks for your feedback.

I've tried `1.3.1`(Win11) -> `1.3.1`(Win11), both installed and non-installed version. Coping from local to the remote and from the remote to local. All work fine.

Please also provide a screenshot of the delay. Maybe there is an underlying bug.

![image](https://github.com/user-attachments/assets/9da7eb9a-ea9f-45aa-bdbf-b5fa5632a49e)

**Comment by rustdesk** [comment]
Close since no response.

**Comment by lkyu-ly** [comment]
same problem, i use screenshot tool to copy part of screen to clipboard, it may crash after i use ctrl v to paste what just be copied

**Comment by lkyu-ly** [comment]
ver 1.3.1

**Comment by lkyu-ly** [comment]
> Could you please give more details, thanks

sure. 

1. remote machine to be controlled is using 1.3.1, and the controller side uses 1.3.8
2. just copy the screen from controlled side and immediately paste it to a doc file on controlled side
3. of course

**Comment by fufesou** [comment]
> just copy the screen from controlled side and immediately paste it to a doc file on controlled side

Both Copy&Paste are executed on the controlled side?

RustDesk will not affect the clipboard on the side which is operated by the user.

But if there's another app that will read/write the clipboard. It will be different.
Do you have another remote app or another clipboard app?

**Comment by fufesou** [comment]
BTW, is it possible to upgrade the controlled side to `1.3.8`?

**Comment by lkyu-ly** [comment]
sure. i'll test all mentioned above.
I would reply then.



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 10, 2025 12:26 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [rustdesk/rustdesk] WINDOWS COPY BUG (Issue #9754)


   
BTW, is it possible to upgrade the controlled side to 1.3.8?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
  fufesou left a comment (rustdesk/rustdesk#9754)
 
BTW, is it possible to upgrade the controlled side to 1.3.8?

**Comment by lkyu-ly** [comment]
> BTW, is it possible to upgrade the controlled side to `1.3.8`?另外，是否可以将受控端升级到 `1.3.8` ？

Glad that after upgrading, it seems to run normally till now.

If the situation changes, I will update this information further.

Many thanks.

**Comment by lkyu-ly** [comment]
> But if there's another app that will read/write the clipboard. It will be different. Do you have another remote app or another clipboard app?

Well, this happens again.

I have ditto on both two sides which provides primary clipboard recording. However closing it on both side never help to reduce the crash.

The crash never happens after copying of pure text context but usually immediately after copying other types —— excel cells, images …… I even have no chance to paste it.

When error occurs, it always perform as:

1. A pop-up window is shown noticing that the connection is interrupted, as my connection is stable, it immediately reconnects.
2. I have configured RustDesk to lock the remote screen during disconnection and unlock it upon reconnection. However, the disconnection fails to lock the screen, and after reconnecting, the password is inadvertently entered into any available input field on the remote screen.
3. After reconnecting, the controlling side usually crash suddenly after about 1 minute. No other signals can been observed. 

Seems that this could be a new issue on the latest ver, I will open a new issue for this.
