### ISSUE TITLE
Windows compilation fails to open normally

### ISSUE THREAD

**Issue by BiFangKNT** [rustdesk/rustdesk#9758]
### Bug Description

![image](https://github.com/user-attachments/assets/f8ae1836-1dc2-4968-b9b6-ecc5a9781f12)
As shown in the figure. The compiled executable file opens to a blank screen when double-clicked; only the program started with `cargo run` can be used normally. It seems there is an issue with the working directory.

### How to Reproduce

Follow the tutorial in the [official documentation](https://rustdesk.com/docs/en/dev/build/windows/) to compile, and double-click the executable file to open.

### Expected Behavior

Double-click the executable file to use it normally, just like starting with `cargo run`.

### Operating system(s) on local side and remote side

windows10 -> windows10

### RustDesk Version(s) on local side and remote side

1.3.1 -> 1.3.1

### Screenshots

![image](https://github.com/user-attachments/assets/f8ae1836-1dc2-4968-b9b6-ecc5a9781f12)

**Comment by rustdesk** [comment]
#763
