### ISSUE TITLE
Keyboard mapping mismatch with connection from iPad Keyboard to Debian Wayland

### ISSUE THREAD

**Issue by Schattenruf** [rustdesk/rustdesk#9765]
### Bug Description

There is a keyboard mapping mismatch bug with rustdesk 1.3.1 when connect from iPad with an external Keyboard to Debian Wayland.
This issue does not affect Android or iPad built in keyboard.

Examples:

With a German keyboard y and z are swapped.
A language swap does not help here sadly.

### How to Reproduce

Running rustdesk service on Debian and running rustdesk client on iPad with an external keyboard (for me it was a logitech one that uses the smart connector and not bluetooth with a QWERTZ Layout).

### Expected Behavior

iPad attached Keyboard  is translated in the correct way. 

### Operating system(s) on local side and remote side

iPadOS 18-> Debian Wayland

### RustDesk Version(s) on local side and remote side

1.3.1 -> 1.3.1

### Screenshots

if needed I will try to upload a short video

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/9717
