### ISSUE TITLE
Keyboard not working properly on the latest update

### ISSUE THREAD

**Issue by DarkLordGMS** [rustdesk/rustdesk#9789]
### Bug Description

The keyboard doesn't work properly when connecting from Android. I have tested with different keyboards. I have also tested connecting to Windows and Debian. Same result. Also it looks like when you connect, there's a bunch of 1's on the keyboard. See the videos for details. 

### How to Reproduce

1. Connect from Android using the latest version
2. Try to type anything 

### Expected Behavior

Keyboard should work properly like in v1.3.1

### Operating system(s) on local side and remote side

Android -> Windows/Debian

### RustDesk Version(s) on local side and remote side

1.3.2 -> 1.3.2/1.3.1

### Screenshots

https://github.com/user-attachments/assets/eef0297a-b317-48a5-819b-30ce723b8d85

https://github.com/user-attachments/assets/f4a34f33-c723-4bb9-8880-cf5c134d8172

https://github.com/user-attachments/assets/7872175a-5963-417a-bc3f-f2eca5af2d66

**Comment by ThomasCr** [comment]
I also have problems with keyboard input from Android Version 1.3.2 to Windows. I cant enter something on the Login Screen from Windows. On beginning some letters was typed, than it stopped working.

**Comment by fufesou** [comment]
@DarkLordGMS @ThomasCr Please try the latest nightly build. We've put a fix.

https://github.com/rustdesk/rustdesk/releases/tag/nightly

> there's a bunch of 1's on the keyboard

These 1's are used to assist input.
It seems that your input method can see these values, but some input methods cannot.
Does this have any impact on your use?

**Comment by DarkLordGMS** [comment]
> Please try the latest nightly build. We've put a fix.

By nightly so you mean this one?
https://github.com/rustdesk/rustdesk/releases/tag/nightly

I installed it and I still can see the 1's in SwiftKey and Samsung Keyboard
Most of the time I can't see what I'm typing 
Thankfully I can tap use Enter now

> We will only send the words after composing now. 

Oh that's... different. Any reason for the change? 
Would it be possible to have a toggle added in the settings to be able to enable or disable that? 

> But the input method seems not to give the candidate prompt when the word is composing. Is it normal? This seems to cause input blindness. 

No. The 1's were not visible before.

**Comment by fufesou** [comment]
> Would it be possible to have a toggle added in the settings to be able to enable or disable that?

Sorry, no. I'll put a fix today.

**Comment by rustdesk** [comment]
Please test the new nightly.

**Comment by DarkLordGMS** [comment]
The 1's are still visible when I open the keyboard
Sometimes some keystrokes don't register

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
@DarkLordGMS Thanks for your test and feedback.

> The 1's are still visible when I open the keyboard

I can reproduce it with SwiftKey, both `1.3.1` and the latest nightly build.

> Sometimes some keystrokes don't register

Could you please give more details, thanks.

Only input `space` then `.` not work for me, SwiftKey.

<img width="200" alt="a" src="https://github.com/user-attachments/assets/f803e464-cd1c-400b-a3e4-cf3b7f6efef9">

I'll fix them.

**Comment by DarkLordGMS** [comment]
Here's another video that might be useful

https://github.com/user-attachments/assets/d2a3c1e9-52ce-4df6-810f-b9459e23a321

Is it possible to revert to v1.3.1 without losing my saved connections on Android?

**Comment by fufesou** [comment]
Thanks! 

Is 1.3.1 work fine for you? Did you use the Sumsung input method in your video? 


> Is it possible to revert to v1.3.1 without losing my saved connections on Android?

Yes.

**Comment by DarkLordGMS** [comment]
> Is 1.3.1 work fine for you? 

Yes. 

> Did you use the Sumsung input method in your video?

Yes. I tested SwiftKey and it's a little better. At first the 1's show up but then they dissappear but after I start typing the words sometimes start getting mashed up together and then the corrections don't work. Check this video. 

[Screen_Recording_20241107_030534.zip](https://github.com/user-attachments/files/17658138/Screen_Recording_20241107_030534.zip)

**Comment by fufesou** [comment]
> > Is 1.3.1 work fine for you?
> 
> Yes.
> 

But on Android input there is no difference in the code implementation.

Could you please also test this build https://github.com/fufesou/rustdesk/releases/tag/tset-android-input-field

and upload the record videos?

There're no changs but shows the hidden input text field.

It may help up improve the Android input.

I cannot test  the Sumsung input method for now.

**Comment by veilside03** [comment]
I can confirm the same problem on iOS 18. A lot of 1's using the default keyboard, so my Debian PC doesn't accept my password from my phone.

Furthermore when I enter special hungarian characters (é, á, ű, ó, etc.) I always get the US equivalent, however all my devices are set to hungarian. How can I avoid this? Thank you!

**Comment by DarkLordGMS** [comment]
Sorry for the delay. Here are the videos you requested @fufesou


[video 1.zip](https://github.com/user-attachments/files/17713325/video.1.zip)
[video 2.zip](https://github.com/user-attachments/files/17713327/video.2.zip)

**Comment by fufesou** [comment]
> Here are the videos you requested

Thanks a lot. I can see what has happened clearly.

But I think `1.3.1` should have the same issue. Could you please double confirm, thanks!

**Comment by veilside03** [comment]
Please, fix this issue ASAP! Login is impossible with the current version from iOS device to any devices!

**Comment by DarkLordGMS** [comment]
Sorry for the delay. @fufesou 
Yes, I tested 1.3.1 and the keyboard is doing the same thing.
