### ISSUE TITLE
MacOS <-> Windows10: Keystrokes in client when RestDesk window out of focus

### ISSUE THREAD

**Issue by de-cp** [rustdesk/rustdesk#980]
**Describe the bug you encountered:**
Situation 1:
I am accessing a Windows 10 client (desktop app) (WC1) from a MacOS machine (desktop app) (MC2). 
When I tab out of an active RustDesk window to let's say Firefox on MC2 (CMD+Tab) two unintended things happen:
1. In the remote session on WC1 'CMD+Tab' triggers 'WIN+Tab': This results in opening the 'Task View' [0] which is weird but not tragic.
2. When the remote user in front of WC1 clicks on one of the tasks from the 'Task View' or in other words focuses on one window on WC1 (i.e. Notepad), all keystrokes of MC2 get transfered to WC1. Which could be catastrophic and result in data loss. Ways to stop this are either to disconnect RustDesk or refocus to RustDesk on MC2 and use the Mac Taskbar to switch to another app.

To reproduce it is not enough to CMD+Tab to RustDesk and away. You have to be active in the RustDesk window. 

Situation 2:
Testing the other way around (WC1 is accessing MC2) we have a different outcome:
Focused on the RustDesk window on WC1 the keyboard shortcut WIN+TAB does not open any app switcher on both systems. It does however switch between the last two active windows on MC2. WIN+ALT does nothing. 
...

**What did you expect to happen instead?**
Situation 1:
For 1.: I would expect that either CMD+Tab changes focus on MC2 and nothing happens on WC1 OR CMD+Tab opens the 'Task View' on WC1 and focus does not change on MC2.

For 2: As soon as there is no focus on the RustDesk app, no keystrokes or mouse movements or anything should get mirrored to the remote session. 

Situation 2:
I would expect that either WIN+Tab opens the 'Task View' on WC1 and nothing happens on MC2 OR WIN+Tab opens the 'App Switcher' on MC2 and nothing happens on WC1. Same for ALT+TAB.
...

**How did you install `RustDesk`?**

On MC2: brew install rustdesk
On WC1: choco install rustdesk

---

**RustDesk version and environment**
MC2: RustDesk v1.1.9
WC1: RustDesk v1.1.9

MC2: MacOS 10.15.7
WC1: Win10 21H2

**Comment by rustdesk** [comment]
Please confirm the behavior on TeamViewer, if some one wanna help.

**Comment by de-cp** [comment]
> Please confirm the behavior on TeamViewer first, if some one wanna help.

do you mean if teamviewer has the same problem, or someone watches over my shoulder on teamviewer? 

I just checked a connection with Teamviewer  MC2 -> WC1. CMD+Tab=no 'Task View' or window changes on WC1 and on MC2 the app switcher opens. pressing only CMD opens the start menu on WC1. No keystrokes or keypresses get mirrored to WC1.

I can show you on TeamViewer if it helps. (Have "licensing problem" right now, but for a quick presentation it would probably work.)

**Comment by rustdesk** [comment]
Ignore my reply, I talked to potential contributor.

**Comment by de-cp** [comment]
> Ignore my reply, I talked to potential contributor.

Thanks for your quick response. I'd love to contribute, but not a coder unfortunately. :/ Thanks for the great product and your work by the way.

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/1178

**Comment by kirides** [comment]
#1342 is supposed to be a duplicate of this.

But this issue is closed and doesn't look like it's an active" **must** be fixed" type of issue.

sadly i can not use this software for the purpose of remote access to a workstation because it leads to my local machine not producing the correct input in a local editor of choice. No matter if the remote window is visible or not, or minimized.

I'd imagine that a rather simple "OnWindowActivated/OnLostFocus" could be enough to stop processing _all_ keystroke manipulations.

Using the clipboard (atleast on windows) can be accomplished with putting items in it and consuming them appropriately.
In case of a remote connection, we can use deferred rendering or `IStream` to put things in there and consume them.
