### ISSUE TITLE
Cannot wake up Mac Mini from sleep?

### ISSUE THREAD

**Issue by leonguyen52** [rustdesk/rustdesk#981]
Hi, I'm using RustDesk on Android/iPhone app and tried to wake up my Mac Mini M1 which is running RustDesk for Mac v1.1.9 but I cannot wake it up to control from sleeping. I can use chrome remote desktop to wake it normally. Any suggestion?

**Comment by drkvogel** [comment]
Same here with MacBook Pro 2018 host MacOS 10.14.6 and Linux Ubuntu client

**Comment by tamiaO** [comment]
我使用 macBookPro 连接到 mac mini 时也存在此 bug，只要是 mac 睡眠或是锁定屏幕了，就无法成功连接到远程电脑。具体表现为（客户端提示）连接成功，等待画面传输，此时，用其它任何客户端都是连不上远程的

**Comment by Seriels** [comment]
![EV1X42~%C}2DZL9981KNG(7](https://user-images.githubusercontent.com/33693501/187673838-57a83ac2-aefa-4c3e-be33-d7ef723019d8.png)


咋看日志。。。

**Comment by Seriels** [comment]
>  
mac 是 kvm  安装的 系统    manjaro  是宿主机器
mac 连接 manjaro  是没有问题的   但是 连回到 mac 就 一直卡在 已连接 等待画面传输

**Comment by mihauOne87** [comment]
Same here, Black Screen when connected to Sleeped iMac.

**Comment by mihauOne87** [comment]
RustDesk is useless on MacBook After sleep Mode. TeamView working without Problems. Is the Team Plan some fixes for this Problem?

**Comment by neteric** [comment]
Same issue, Black Screen when connected to Sleeped iMac.

**Comment by neteric** [comment]
Same issue, can't wake up black screen when connected to sleeped macos.

**Comment by ondohotola** [comment]
Same/Similar issue, I expect the login window (due to inactivity) but can ‘t get that.
On Windows it works very well, and when logged into the Mac it does as well.

Latest versions on all devices.

**Comment by fisherwei** [comment]
我尝试了一下先用macos自带的vnc端口连接上，晃动一下鼠标点亮显示器，然后rustdesk就可以正常工作了。

能否考虑先简单的解决一下：服务端收到链接请求之后，让鼠标晃动1px，点亮睡眠的显示器？

**Comment by rustdesk** [comment]
> vnc

@asur4s good clue，we can check out osxvnc.

**Comment by KarryZhou** [comment]
> 我使用 macBookPro 连接到 mac mini 时也存在此 bug，只要是 mac 睡眠或是锁定屏幕了，就无法成功连接到远程电脑。具体表现为（客户端提示）连接成功，等待画面传输，此时，用其它任何客户端都是连不上远程的

相同的情况，虽然我是mac air和mac pro

**Comment by bellwether-softworks** [comment]
For people experiencing this problem, if you have SSH access to the mac in question, the `caffeinate` command can be used to wake the machine and allow RustDesk connectivity; e.g. `caffeinate -u -t 2`.

**Comment by ondohotola** [comment]
what does this mean, like, in English?

el

—
Gesendet von meinem iPad

**Comment by ondohotola** [comment]
Very cool!

Now if one could make RustDesk issue this on a password less ssh command, that would be really sexy.

el

el

—
Gesendet von meinem iPad

**Comment by ondohotola** [comment]
I am doing this from iTerm on the Mac, and have created Profiles (which
one can tie to a keyboard if one wants) and that works fine.

el

On 12/11/2022 18:44, Dr Eberhard W Lisse wrote:
> Very cool!
> 
> Now if one could make RustDesk issue this on a password less ssh
> command, that would be really sexy.
> 
> el
[...]

> On 12. Nov 2022 at 14:01 +0100, Justin Bell ***@***.***>,
> wrote:
>>
>> For people experiencing this problem, if you have SSH access to the
>> mac in question, the |caffeinate| command can be used to wake the
>> machine and allow RustDesk connectivity; e.g. |caffeinate -u -t 2|.
[...]


-- 
Dr. Eberhard W. Lisse   \         /       Obstetrician & Gynaecologist
***@***.***             / *      |  Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht  \      /  If this email is signed with GPG/PGP
10007, Namibia           ;____/ Sect 20 of Act No. 4 of 2019 may apply

**Comment by gateslu** [comment]
> For people experiencing this problem, if you have SSH access to the mac in question, the `caffeinate` command can be used to wake the machine and allow RustDesk connectivity; e.g. `caffeinate -u -t 2`.

it works for me👍👍👍

**Comment by rustdesk** [comment]
We will work on this once we have time.

**Comment by fazakis** [comment]
Hi I intorduced a small hack to overcome this problem by integrating caffeinate in the source, in
case somebody wants to use it: https://github.com/rustdesk/rustdesk/compare/master...fazakis:rustdesk:mac_hack

**Comment by weifpeng** [comment]
> ![EV1X42~%C}2DZL9981KNG(7](https://user-images.githubusercontent.com/33693501/187673838-57a83ac2-aefa-4c3e-be33-d7ef723019d8.png)
> 
> 咋看日志。。。

same problem，pve install mac ，windows rustdesk client connect
![image](https://user-images.githubusercontent.com/14124283/219396490-0d1e7dbf-cbc9-4004-8ba6-483d599cb3d5.png)

**Comment by liaojianqiang** [comment]
> caffeinate

碰到同样的问题，用这个办法解决了。非常感谢。

**Comment by liaojianqiang** [comment]
> For people experiencing this problem, if you have SSH access to the mac in question, the `caffeinate` command can be used to wake the machine and allow RustDesk connectivity; e.g. `caffeinate -u -t 2`.


caffeinate

用这个办法解决了。thank you !

**Comment by zhaixuepan** [comment]
同样的问题，用其他远程软件没问题

**Comment by 350050183** [comment]
这是超大的bug，竟然这么久也没有解决？mac mini m2电脑我全部设置了不要睡眠，竟然仍是连不上

**Comment by doudoupower** [comment]
windows连接windows服务端也是同样的问题，“已连接，等待画面传输...”， 用mstsc连一下就显示内容了

**Comment by ondohotola** [comment]
While it would be helpful to post in English, Deepl has helped :-)-O

The current versions for both iPad/iPhone and MacOS (Homebrew) wake the remote Mac up quite nicely, thank you very much indeed.

**Comment by asmoker** [comment]
ref https://github.com/asmoker/mac-wake-display

**Comment by ondohotola** [comment]
Aha,

what are you trying to say here? The current version works very well

**Comment by nxneo** [comment]
用官方的版本就好了
