### ISSUE TITLE
Rust Desk not connecting

### ISSUE THREAD

**Issue by pkrumins** [rustdesk/rustdesk#9813]
### Bug Description

no connection

![image](https://github.com/user-attachments/assets/68a10f98-6eb9-4d64-8175-383738d4b43b)

### How to Reproduce

run

### Expected Behavior

connected and working

### Operating system(s) on local side and remote side

macos 15

### RustDesk Version(s) on local side and remote side

1.3.1 loacl

### Screenshots

![image](https://github.com/user-attachments/assets/940fb469-3a17-49d1-b6e9-ad7995f50bdd)

### Additional Context

help

**Comment by pkrumins** [comment]
bonus $100 for fix

**Comment by pkrumins** [comment]
still not work, fast fix pleas

**Comment by fufesou** [comment]
Did you please self-hosted server? Please ensure 

1. `hbbs` is running on your server.
2. The IP and port are accessible.

![image](https://github.com/user-attachments/assets/0b891023-ca73-402b-a6e1-ce4b6727d46c)

**Comment by pkrumins** [comment]
thanks you!

it looks like `hbbs` is not running. i will try re-install.

it worked goods but stops workings after i disable "remote sharing" in macos settings (accidental)

![image](https://github.com/user-attachments/assets/e749f5fd-89b2-47a7-ab1c-2f267319dcee)

i re-enable via `sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -restart -agent -privs -all -allowAccessFor -allUsers`

**Comment by rustdesk** [comment]
#763
