### ISSUE TITLE
No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop

### ISSUE THREAD

**Issue by Alpharedstoneking** [rustdesk/rustdesk#9864]
### Bug Description

The Rust desk is not able to connect to my raspberry pi and just gives this erro

### How to Reproduce

Install Rust desk on a raspberry pi and on a windows pc the try to connect

### Expected Behavior

I expect to connect with all permissions enable to my raspberry pi

### Operating system(s) on local side and remote side

Connecting side Windoes 10 Remote side Raspberry pi os

### RustDesk Version(s) on local side and remote side

1.3.2

### Screenshots

![SharedScreenshot](https://github.com/user-attachments/assets/242fb949-2b7b-4a85-a2d7-6b99af0dd568)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4276#issuecomment-1537105758
