### ISSUE TITLE
Remote window goes into Fullscreen mode

### ISSUE THREAD

**Issue by char990** [rustdesk/rustdesk#9873]
### Bug Description

Rustdesk Version: 1.3.1 on both host and remote.
Host system is Win10 Pro 22H2, Remote system is Win10 2016 LTSB.

Maximised Remote window goes to fullscreen when selected from taskbar

### How to Reproduce

On Host, connect to Remote in "Scale adaptive" mode. The Remote window is maximised, NOT fullscreen.
If I minimise the Remote window or use "show desktop" button at end of the  taskbar, and do some other work, then select Remote from taskbar. The Remote window goes into fullscreen mode. The taskbar on Remote is covered by Host taskbar.

If the Remote window is NOT in maximise mode, it restores from taskbar correctly.

### Expected Behavior

Minimised the Remote window from a maximised mode. When select it from taskbar/restore it, the Remote window should be return to maximise mode, NOT fullscreen.

### Operating system(s) on local side and remote side

win10 ->win10

### RustDesk Version(s) on local side and remote side

1.3.1->1.3.1

### Screenshots

Remote is connected and window is maximised:
![1](https://github.com/user-attachments/assets/fc051828-b41e-4ba1-9d15-aeae8e721018)

Minimise and restore it. The window goes into fullscreen
![2](https://github.com/user-attachments/assets/e96e22ab-a88a-4a44-baeb-c8357a3066a2)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/9479
