### ISSUE TITLE
RustDesk >= 1.2.4 AppImage + Gentoo Linux: undefined symbol: drmCloseBufferHandle

### ISSUE THREAD

**Issue by aruslantsev** [rustdesk/rustdesk#9876]
### Bug Description

I use AppImage version of RustDesk client.
At start RustDesk client writes to the terminal:
```
MESA-LOADER: failed to open iris: /usr/lib64/libdrm_intel.so.1: undefined symbol: drmCloseBufferHandle (search paths /usr/lib64/dri, suffix _dri)
failed to load driver: iris
MESA-LOADER: failed to open zink: /usr/lib64/dri/zink_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri, suffix _dri)
MESA-LOADER: failed to open iris: /usr/lib64/libdrm_intel.so.1: undefined symbol: drmCloseBufferHandle (search paths /usr/lib64/dri, suffix _dri)
failed to load driver: iris
MESA-LOADER: failed to open swrast: /usr/lib64/libdrm_intel.so.1: undefined symbol: drmCloseBufferHandle (search paths /usr/lib64/dri, suffix _dri)

** (rustdesk:18709): WARNING **: 08:08:54.372: Failed to start Flutter renderer: Unable to create a GL context

** (rustdesk:18709): WARNING **: 08:08:58.234: Unable to retrieve framework response: No engine to send to
```
Window does not appear. 
All versions after 1.2.3-2 have his problem. 1.2.3-2 is the latest working version.

I have x11-libs/libdrm-2.4.123-r1. And symbol drmCloseBufferHandle is really undefined in `libdrm_intel.so.1`, but it is defined in `libdrm.so.2`. Both of this files are located in `/usr/lib64/`.

```
$ readelf -Ws /usr/lib64/libdrm_intel.so.1.123.0 | grep drmCloseBufferHandle
    34: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND drmCloseBufferHandle
```
```
$ readelf -Ws /usr/lib64/libdrm.so.2.123.0 | grep drmCloseBufferHandle
   102: 000000000000b910    74 FUNC    GLOBAL DEFAULT   13 drmCloseBufferHandle
```

### How to Reproduce

- Open terminal.
- Execute ./rustdesk-1.3.2-x86_64.AppImage (I tried all versions after 1.2.3-2, result is the same)
- Read the error in the terminal

### Expected Behavior

RustDesk client starts

### Operating system(s) on local side and remote side

Gentoo Linux

### RustDesk Version(s) on local side and remote side

1.3.2, 1.3.1, 1.3.0, 1.2.7, 1.2.6, 1.2.5, 1.2.4

### Screenshots

![image](https://github.com/user-attachments/assets/16b2bf81-a032-4664-9c23-42fa54b9619b)

**Comment by rustdesk** [comment]
Use Flatpak instead. We wont recommend AppImage for its bad compatibility.
