### ISSUE TITLE
Not compatible with Huawei Tablet's mouse wheel operation

### ISSUE THREAD

**Issue by li2282231** [rustdesk/rustdesk#9892]
### Bug Description

When I use Huawei tablet to control a computer remotely, the keyboard control is normal, but the mouse control is not normal. For example, if the mouse wheel scrolls down to browse a web page, the page of the computer on the controlled end will not scroll down.

### How to Reproduce

Use Huawei tablet to install rustdesk apk, then remote control the computer, use Huawei mouse to connect to the tablet, then the mouse wheel to control the page scrolling, you will find the page is not controlled by the mouse wheel.

### Expected Behavior

I would like to be able to control computer page scrolling with the mouse wheel.

### Operating system(s) on local side and remote side

harmony 4.2.0->Windows 11

### RustDesk Version(s) on local side and remote side

1.3.2->1.3.2

### Screenshots

https://github.com/user-attachments/assets/560208d2-bac7-4b65-aa59-4df6467cf104

### Additional Context

The console uses a Huawei tablet, the console mouse is a Huawei Bluetooth mouse,Huawei tablet is installed with android AArch64 (ARM64) version of the program, the version number is 1.3.2.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3893

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
Do you have this huawei tablet only? How about the other android devices?

**Comment by li2282231** [comment]
> Do you have this huawei tablet only? How about the other android devices?

Yes, I only have a Huawei tablet and a Huawei mouse, no other Android tablets.

**Comment by fufesou** [comment]
Android -> Windows, 1.3.2->1.3.2, wheel click and scrolling works for me.

**Comment by rustdesk** [comment]
Close as tracked by https://github.com/rustdesk/rustdesk/issues/3893

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/7336
