### ISSUE TITLE
http to https upgrade not present

### ISSUE THREAD

**Issue by FireMasterK** [rustdesk/rustdesk#99]
This is on the website - http://rustdesk.com/
I can see that HSTS is present, but the request is never upgraded to https. The site could also be preloaded to Firefox and Chromium via https://hstspreload.org/?domain=rustdesk.com if possible.

I also noticed that http2 wasn't enabled, maybe that could be enabled for better performance

**Comment by rustdesk** [comment]
Noted with Thanks
