### ISSUE TITLE
no connection over wan or vpn (lan only)

### ISSUE THREAD

**Issue by rowie** [rustdesk/rustdesk#991]
Hi,

my server is running on a netcup root server with ubuntu 22.04LTS. rustdesk is running i a docker container. All ports are reachable from the internet and the clients coult connect to the rustdesk server.
my clients (windows10 and pop!os) could connect to eath other in the lan but not to clients othside the lan via wan or vpn. 
I can see the tcp high ports connection on the firewall but nothing happend on the client.
Let me know if you nedd mor e date!

br,
rowie

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server/issues/24

**Comment by rowie** [comment]
There is only one hostname as i descripted and the rustdesk server is not running in my LAN!
