### ISSUE TITLE
Cannot connect to some clients

### ISSUE THREAD

**Issue by paulsommer** [rustdesk/rustdesk#9910]
### Bug Description

Rustdesk cannot connect to some (two) of my many Windows-clients

### How to Reproduce

Connect to a client.
Rustdesk says: "Connection is being established" (Verbindung wird hergestellt)
Client doesn't see the dialog to accept the connection.

### Expected Behavior

Client should see the dialog to accept the connection.

### Operating system(s) on local side and remote side

Kubuntu Linux -> Windows 11

### RustDesk Version(s) on local side and remote side

1.3.1 -> 1.3.2 (and older)

### Screenshots

No Screenshot

### Additional Context

Rustdesk works with many Linux, Apple, Windows10 and 11 clients. But not with two Windows systems.
I am using a selfhosted connection server.
I have no idea how to investigate on that phenomenon.

**Comment by rustdesk** [comment]
#763
