### ISSUE TITLE
Problem with sound interruption

### ISSUE THREAD

**Issue by POLFODEX** [rustdesk/rustdesk#9916]
### Bug Description

All versions after 1.2.7 have an issue with sound interruptions. If any version of RustDesk is installed on the remote side, and version 1.3.0 or higher is installed on the connecting computer, the sound cuts off every half second. However, if version 1.2.7 is installed, the microphone audio is transmitted correctly and without delays.

### How to Reproduce

1. On the remote side, you can use any version of RustDesk.
2. On the remote side, select the audio source as the microphone (in my case, I'm using the microphone built into the Logitech C270 webcam).
3. On the computer from which the connection will be made, you need to install version 1.3.0 or higher (I tested it on macOS 15.0, Windows 10, and 11) — this issue occurs on all of them.
4. If the sound keeps cutting off, revert to version 1.2.7. After that, the sound will work as expected.

### Expected Behavior

Most likely, versions above 1.2.7 use a different audio transmission algorithm, which is why interruptions occur. It is necessary to analyze which method was used in version 1.2.7 and in all subsequent versions.

### Operating system(s) on local side and remote side

MacOS Sequoia 15.0 -> Linux Debian 12

### RustDesk Version(s) on local side and remote side

1.3.2 -> 1.3.2

### Screenshots

![rustmacos](https://github.com/user-attachments/assets/56c4d78b-7f8e-47d7-97f6-76d8876460ae)
![rustdebian](https://github.com/user-attachments/assets/78dc4240-69ae-4d5f-b160-cc3aea444130)

**Comment by rustdesk** [comment]
162.55.219.27

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/9770
