### ISSUE TITLE
Crash while doing unrelated stuff 

### ISSUE THREAD

**Issue by xvolks** [rustdesk/rustdesk#995]
**Describe the bug you encountered:**

Rustdesk crashed while I was browsing with Safari.

**What did you expect to happen instead?**

No crash

**How did you install `RustDesk`?**

Github release

**RustDesk version and environment**

Rustdesk 1.1.9, macOS 12.4; macbook pro 2012 with Dortania's OpenCore Legacy patcher.
 
[rd_crash.log](https://github.com/rustdesk/rustdesk/files/9134232/rd_crash.log)

**Comment by rustdesk** [comment]
Sciter crash. We are replacing Sciter. https://github.com/rustdesk/rustdesk/issues/103
