### ISSUE TITLE
Desktop is visible on both clients but no keyboard/mouse/touch input

### ISSUE THREAD

**Issue by elki00** [rustdesk/rustdesk#996]
**Describe the bug you encountered:**

From whatever client device (iOS>macOS, macOS>macOS) I access to any other, desktops are shown but there's no way of interacting with it. Checked firewall rules on devices and router but nothing is filtering, added RUSTDESK to security&privacy on Mac OS (also input monitoring) but It just won't work, it's a static image of the desktop. File transfer and chat both working, switch to second monitor too

**What did you expect to happen instead?**

keyboard and mouse (touch in iOS) input 

**How did you install `RustDesk`?**

From RUSTDESK website .dmg installer

**RustDesk version and environment**

V 1.1.9 on both Macs, V 1.1.10 iOS
Mac1 Monterey 12.2.1
Mac2 Mojave 14.6
iOS 15.1

**Comment by rustdesk** [comment]
https://rustdesk.com/docs/en/manual/mac/#enable-permissions

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/974

**Comment by elki00** [comment]
thank you. the permissions are all already set on both Macs. I removed app and agents and reinstalled everything, granted permissions again, it worked once from Mojave Mac > Monterey Mac and then now the display is totally black when connecting in both directions. Tried with killing the running agent and reopening Rustdesk to no avail. Same applies from ios to both macs: display is black. Few things to notice: **1.** the daemon icon on the app bar is not there when reopening rustdesk, but rustdesk launchd process is running on root and user level. **2.** The display is black even if devices are properly connected, I can see the invisible mouse arrow hovering over the mac screen, but still no input. **3.** Mojave's _Security&Privacy_ settings only has the _Accessibility_ tab for permission, no _Input devices_, nor _Screen Recording_

**Comment by DennisdeWitNL** [comment]
I face the same problem. I have no black screen though. I just only can use the flag key to have the start menu popping up. Typing isn't working. Too bad, I liked RustDesk. Now it is yet another useless tool. 👎

**Comment by rustdesk** [comment]
Try out this workaround please, https://github.com/rustdesk/rustdesk/issues/974#issuecomment-1185644923

**Comment by gifnotgif** [comment]
For what it's worth, I'm no longer having this problem since upgrading to Ventura 13.3 (and now 13.3.1)
