### ISSUE TITLE
Crash on macOS when try to input Relay server config

### ISSUE THREAD

**Issue by vstar37** [rustdesk/rustdesk#9980]
### Bug Description

When I try to enter the network settings in the GUI a crash occurs

### How to Reproduce

settings -> Network -> Unlock network settings -> then input to the ID/Relay sever box.

### Expected Behavior

not crash

### Operating system(s) on local (controlling) side and remote (controlled) side

macOS 15.1

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

 1.3.2

### Screenshots

just crash

### Additional Context

crash log: [https://pastebin.com/raw/S5iUbmLA](https://pastebin.com/raw/S5iUbmLA)

**Comment by rustdesk** [comment]
there are duplicates
