### ISSUE TITLE
Self-built server, Android phone cannot be controlled

### ISSUE THREAD

**Issue by ligbyte** [rustdesk/rustdesk#9994]
### Bug Description

![54e5faf940f32071762c2f8783f883e](https://github.com/user-attachments/assets/fbc83474-f06a-4d88-bdb9-c209fe7345c3)

![d3d42962e0934be388829ef920fe1d2](https://github.com/user-attachments/assets/2052aa6b-af88-40d2-b19b-074a19505f4f)

### How to Reproduce

![54e5faf940f32071762c2f8783f883e](https://github.com/user-attachments/assets/b58c6f0d-cab1-4ec1-bc20-36b54de2c7f9)

![d3d42962e0934be388829ef920fe1d2](https://github.com/user-attachments/assets/f9bfc2d9-1d67-471e-8c4e-54b58f1d02b2)

### Expected Behavior

![54e5faf940f32071762c2f8783f883e](https://github.com/user-attachments/assets/8e451867-6e2c-43cb-ba94-b57de104ae78)
![d3d42962e0934be388829ef920fe1d2](https://github.com/user-attachments/assets/19848d97-ebbf-4bd7-a391-f7423aceb284)

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows 11

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.3

### Screenshots

![d3d42962e0934be388829ef920fe1d2](https://github.com/user-attachments/assets/05144a5b-ccf3-4e32-abbf-8d7573d13d95)

**Comment by rustdesk** [comment]
#763
