### ISSUE TITLE
Use native window decorations and tray icons

### ISSUE THREAD

**Issue by witt-bit** [rustdesk/rustdesk#9995]
### Bug Description

I am a manjaro user. I abandoned the ToDesk program and switched to rustDesk. I have two problems with it.

1. It does not use native window decorations

2. There is no tray icon in the taskbar

### How to Reproduce

1.I am used to placing window buttons on the left side of the window, but since rustDesk does not use native window decorations, the window buttons are on the right side, which makes it inconvenient for me to use.

2.After closing the rustDesk main window, there is no tray icon. I don't know whether it is currently exited or continues to run in the background.

### Expected Behavior

1.Provide support for native window decorations. If you are worried about layout issues, you can add a toggle option. This is common practice.

2.Create a tray icon for rustDesk to display when running in the background

### Operating system(s) on local (controlling) side and remote (controlled) side

Linux Manjaro 24.1.2 Xahea

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.2

### Screenshots

![image](https://github.com/user-attachments/assets/560708ee-49e7-47f1-9d1a-997f27f62cfc)

![image](https://github.com/user-attachments/assets/83e56420-d14c-47d9-ad4c-d51b00e72cec)

**Comment by witt-bit** [comment]
I understand there is an ISSUE #557 but I haven't seen any progress and it has been closed.

**Comment by rustdesk** [comment]
I will block you if you continue to create duplicate issue.
