### ISSUE TITLE
Official RustDesk-Network unreachable after too many connection requests

### ISSUE THREAD

**Issue by Crazore** [rustdesk/rustdesk#9996]
### Bug Description

Unable to connect to the RustDesk network via my whole testing Network (every machine), while working if I connect same machines to another network.
It formerly worked as it should.

### How to Reproduce

I guess (I don't want to misuse another network for that) if you excessively try to connect to an existing but currently not reachable connection by repeatedly clicking the reconnect button it should be reproducible.

### Expected Behavior

Connection via this network to the RustDesk network should be possible.

### Operating system(s) on local (controlling) side and remote (controlled) side

Main Windows 11 (additional tested on Win 10 / Ubuntu / Win Server 2016)

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.2 previous and testwise currently the nightly build 1.3.3

### Screenshots

![Screenshot 2024-11-21 084307](https://github.com/user-attachments/assets/46e52b04-a867-4cae-a08f-ba72ee52cc7e)

![RustDesk_rCURRENT_1](https://github.com/user-attachments/assets/9a3be8e4-38b6-4800-a9dc-28b4ba5cf674)

### Additional Context

I am currently evaluating RustDesk as a potential replacement for our existing remote support system. While everything has been functioning smoothly overall, I encountered an issue after the last test session. During this session, I made an unusually high number of connection requests to a specific device. Subsequently, it appears that RustDesk is blocking the entire internal network. Interestingly, when I connect the same computer to a different network, it works flawlessly again. However, all devices on the affected network remain blocked.

**Comment by Crazore** [comment]
Please excuse me in advance if I made any mistakes while submitting this issue. This is my very first request on GitHub.

**Comment by rustdesk** [comment]
https://www.reddit.com/r/rustdesk/comments/1cr8kfv/should_you_selfhost_a_rustdesk_server/
